### ISSUE TITLE
low version of NPM & Nodejs

### ISSUE THREAD

**Issue by zysoo** [LaraDock/laradock#100]
In workspace, the version of npm is 1.3.10 and nodejs is 0.10.25
As the latest nodejs is 6.*, is it possible to upgrade them in Dockerfile?  At least in my project, i have to upgrade to install Jeffery's laravel-elixir-vueify package.

**Comment by appleboy** [comment]
@zysoo see the https://github.com/LaraDock/laradock/pull/111 PR

**Comment by appleboy** [comment]
@Mahmoudz close this issue? `v2.4.3` support new node and npm version.
