### ISSUE TITLE
Mysql container fails on start

### ISSUE THREAD

**Issue by invasioncredible** [laradock/laradock#1009]
Latest docker - latest laradock (master)

If i do `docker-compose up -d nginx php-fpm mysql phpyadmin `
nginx - almost default config
php - 7.0
Mysql - simple configuration
Phpmyadmin - no custom config

it starts, and then the mysql container falls, and i have to do
`docker-compose up -d mysql `
and only then it properly runs. 
I didn't have this problem with the previos versions of laradock. 

Not a fatal bug, but i would be happy if you fix this)

**Comment by dtkoval** [comment]
Just try to use [docker-machine-nfs](https://github.com/adlogix/docker-machine-nfs) if you use mac

**Comment by Mahmoudz** [comment]
@invasioncredible sometimes it does that in the first attempt! try `docker-compose down` then run your containers again. And let us know if it works.

**Comment by nguyencongkrb** [comment]
I have fixed it. Disable AIO

https://stackoverflow.com/questions/48239668/fails-to-initialize-mysql-database-on-windows-10
