### ISSUE TITLE
php-fpm  laravel.pool.conf  is not works

### ISSUE THREAD

**Issue by djjandyhl** [laradock/laradock#1011]
modify the values in  laravel.pool.conf file,
for example  :
pm.max_children = 200
pm.start_servers = 20
pm.min_spare_servers = 10

it would be not works, because there is a config file (/usr/local/etc/php-fpm.d/www.conf) in the php-fpm container will overwrite the values.

**Comment by aconital** [comment]
Any update on this issue?

**Comment by aconital** [comment]
For anyone looking at this issue later, it seems this has been resolved by adding a `x` in laravel.pool.conf so it alphabetically comes after www.conf so it can overwrite it.

**Comment by bestlong** [comment]
@aconital 
https://github.com/laradock/laradock/commit/5c5f94600a4430f5932703a74bcca5a922fd0b81
