### ISSUE TITLE
Unknown database, mysql database and user does not exist...?

### ISSUE THREAD

**Issue by blomdahldaniel** [laradock/laradock#1017]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): ab464d93d3bfe0808257dbece36c18e3474d761f
- System info (Mac, PC, Linux): Mac
- System info disto/version: macOS Sierra

##### What seems to be going wrong?
It seems like there is no database nor user created for the mysql server.
The server is up and running but there are no database called "homestead" or what ever i add in my .env
_____

##### What should be happening instead?
A database and a user should be created
_____

##### How might we be able to reproduce the error?
I follow basic getting started instrucitons, add laradock as an git submodule.
I run: `docker-compose up -d nginx mysql`

_____

#### Laravel .env (changed `DB_HOST` to `mysql`
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```
#### Laradock .env (default)
```
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
```

**Comment by ItaloBC** [comment]
Can you post your [Docker logs](https://docs.docker.com/engine/reference/commandline/logs/#parent-command) from the MySQL container?

**Comment by iredmedia** [comment]
I'm noticing that i can change this ONLY on the first run. Subsequent builds/runs fail to update with these new values, and retain the first run (regardless of removing volumes, containers, images).

**Comment by sakanaproductions** [comment]
@ItaloBC @iredmedia I am having the same problem, it seems that one of the commits removed all the ENV commands from the mysql Dockerfile:

[8820501644bdfd7b763ce135b6381590cc7ea212](https://github.com/laradock/laradock/commit/8820501644bdfd7b763ce135b6381590cc7ea212)

**Comment by iredmedia** [comment]
The issue in my case is that CHANGING after FIRST run, the DB still exists on the host OS and isn't modified as per #1028. Need to manually change info, or delete ~/.laradock/data/[mysql/postgres] etc.

in the .env file

```
### Data Path:
# For all storage systems.
DATA_SAVE_PATH=~/.laradock/data
```
