### ISSUE TITLE
how to use mssql and how to login mssql from command line

### ISSUE THREAD

**Issue by gr-jialeiwang** [laradock/laradock#1021]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

- Laradock commit (`$ git rev-parse HEAD`): c35445b066245f9b300016042dca4df3f2c314ae
- System info (Mac, PC, Linux): Mac
- System info disto/version: OS X EI Capitan Version 10.11.6

##### What seems to be going wrong?
i edited my laradock .env to make my project can connect to sql server.
its work fine when i connect to remote server such like 192.168.11.11
but i cant connect to my localhost sql server i did
  docker-compose up -d nginx adminer mssql
and docker ps is

```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
55406b546bdc        laradock_adminer     "docker-php-entryp..."   7 seconds ago       Up 6 seconds        0.0.0.0:8080->8080/tcp                     laradock_adminer_1
466fdf1d0bc6        laradock_mssql       "/bin/sh -c '/bin/..."   11 seconds ago      Up 9 seconds        0.0.0.0:1433->1433/tcp                     laradock_mssql_1
c2a9a42adf63        laradock_nginx       "nginx"                  7 days ago          Up 7 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   laradock_nginx_1
db39867fd2c2        laradock_php-fpm     "docker-php-entryp..."   7 days ago          Up 8 seconds        9000/tcp                                   laradock_php-fpm_1
4c20c1582b05        laradock_workspace   "/sbin/my_init"          7 days ago          Up 9 seconds        0.0.0.0:2222->22/tcp                       laradock_workspace_1
```

how can i login my local sql server like mysql?
i know how to login to mysql 
docker-compose exec mysql bash
mysql -u root -p

but its not work to mssql.
anyone help?

_____

##### What should be happening instead?

i want to login from command line to my local sql server
_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
// place code here
```
my .env 
...
WORKSPACE_INSTALL_MSSQL=true
...
PHP_FPM_INSTALL_MSSQL=true
...
MSSQL_DATABASE=homestead
MSSQL_PASSWORD=root
MSSQL_PORT=1433
...
ADM_INSTALL_MSSQL=true
...

**Comment by ItaloBC** [comment]
Did you read the [official documentation from Microsoft](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-connect-and-query-sqlcmd)?

You should be able to use this:

`sqlcmd -S <servername> -U <username> -P <YourPassword>`

This issue seems related to Microsoft SQL Server and not Laradock. Please refrain from posting issues not related to Laradock.

**Comment by gr-jialeiwang** [comment]
thank you. 
finally i found the reason. 
```
docker-compose up -d mssql
docker logs mssql
```
and 
```
sqlservr: This program requires a machine with at least 3250 megabytes of memory.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```
it seems memory is not enough so please tell me 
where is the mssql's memory setting? i want to set it to 4GB
anyone help?

**Comment by ItaloBC** [comment]
> `sqlservr: This program requires a machine with at least 3250 megabytes of memory.`

Basically, your VM (or your system, if you are under Linux) should have more than 4GB available, [as the Microsoft SQL Server Docker Image says](https://hub.docker.com/r/microsoft/mssql-server-linux/).

AFAIK `docker-compose.yml` can [reserve and limit a designated memory pool](https://docs.docker.com/compose/compose-file/#resources) but only on version 3 of the file.

**Comment by gr-jialeiwang** [comment]
@ItaloBC  thank you

**Comment by ItaloBC** [comment]
Personally I would recommend MySQL or MariaDB, they don't require 4GB to start, unless your project demands such RDBMS.
