### ISSUE TITLE
The pgadmin can not boot!

### ISSUE THREAD

**Issue by zuohuadong** [laradock/laradock#1024]
### Info:
- Docker version (`$ docker --version`): 17.05
- Laradock commit (`$ git rev-parse HEAD`): now
- System info (Mac, PC, Linux): Linux
- System info disto/version: elementaryOS 0.4.1

##### What seems to be going wrong?
![Markdown](http://i1.buimg.com/1949/901659cb376a8640.png)
_____

##### What should be happening instead?

_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
// place code here
```

**Comment by winfried-van-loon** [comment]
There's a hint there:
> Is another postmaster already running

Perhaps another is already running - Could that be the explanation for postgres not working?
