### ISSUE TITLE
How to upgrade pgadmin 1.1 to 1.5 ?

### ISSUE THREAD

**Issue by kamrava** [laradock/laradock#1025]
How can I upgrade pgadmin 1.1 to 1.5 in laradock?

**Comment by winfried-van-loon** [comment]
Currently, Laradock uses [fenglc/pgadmin4](https://hub.docker.com/r/fenglc/pgadmin4/), which you [may edit in this file](https://github.com/laradock/laradock/blob/master/pgadmin/Dockerfile#L1). After giving it a quick look, it seems that repo does not have the 1.5 pgadmin yet. There are alternatives available, such as [chorss/docker-pgadmin4](https://hub.docker.com/r/chorss/docker-pgadmin4/) which do contain that version.

**Comment by winfried-van-loon** [comment]
1.5 is now available in [fenglc/pgadmin4](https://hub.docker.com/r/fenglc/pgadmin4/) which will now be the default when building. That should solve the issue!
