### ISSUE TITLE
 Xdebug on Workspace Container

### ISSUE THREAD

**Issue by Euthimios** [laradock/laradock#1027]
### Info:
- Docker version  (`$ docker --version`):  Docker version 1.12.6
- Laradock commit (`$ git rev-parse HEAD`): c35445b066245f9b300016042dca4df3f2c314ae
- System info (Mac, PC, Linux): Linux
- System info disto/version: UBUNTU 16.10

##### What seems to be going wrong?
I can't install xdebugger on workspace container . i am following the instructions and i set the 

WORKSPACE_INSTALL_XDEBUG=true

but when i execute the command : docker-compose build workspace php-fpm
the workspace container throw the bellow :

**After this operation, 3,720 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php-xdebug amd64 2.5.1-1+deb.sury.org~xenial+1
  404  Not Found
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php-xdebug_2.5.1-1+deb.sury.org~xenial+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y --force-yes php-xdebug &&     sed -i 's/^;//g' /etc/php/7.1/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi' returned a non-zero code: 100**

_____

##### What should be happening instead?
to install xdebug to workspace container
_____

##### How might we be able to reproduce the error?
set WORKSPACE_INSTALL_XDEBUG=true
at the .env environment file 
_____

### Relevant Code:

After this operation, 3,720 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php-xdebug amd64 2.5.1-1+deb.sury.org~xenial+1
  404  Not Found
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php-xdebug_2.5.1-1+deb.sury.org~xenial+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y --force-yes php-xdebug &&     sed -i 's/^;//g' /etc/php/7.1/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi' returned a non-zero code: 100

**Comment by NewbMiao** [comment]
modify like this: `apt-get -y update && apt-get install -y --force-yes php7.1-xdebug `
install php-xdebug after update , it's ok for me.

**Comment by benkelukas** [comment]
Hi,
@NewbMiao Could You please elaborate on this? I'm having same problem.
@Euthimios Did You manage to solve this? Seems we are not the only one affected #996

**Comment by fireproofsocks** [comment]
**+1 on more clarification on this in the docs.**  If I edit the `.env`, rebuild via `docker-compose down` and `docker-compose up -d`, then hit my website in a browser, I can see xdebug in the `phpinfo()` output, but the xdebug module isn't loaded in the cli (`php -m` doesn't show xdebug).

The docs do not show any info on where to set the typical URL triggers for xdebug... so I would recommend that the docs include the bit about which container to log into and where to edit the options, e.g. 

```
docker-compose exec php-fpm bash
vi /usr/local/etc/php/conf.d/xdebug.ini
# restart nginx / php-fpm
```
but, of course, I can't find an editor installed on that container (not vim, emacs, pico, nano, etc).  So it's a long and windy homework assignment to figure out how this was intended to be used when an extra sentence or two could have saved many of us hours of time.

Furthermore...

I don't see any `.php-fpm` folder, so the entire section on http://laradock.io/guides/#enablePhpXdebug seems completely irrelevant.  I've used xdebug for years and never gotten it to work with PHPStorm, _even when working with folks from IDEA_, so I'm amazed that section even exists in the docs for Laradock, let alone that it appears to describe a feature that actually works for someone (!!!).

**Comment by brunen9** [comment]
@fireproofsocks , but why did you try to edit xdebug.ini **IN** container when docs clearly says 

> 2 - Open laradock/workspace/xdebug.ini and laradock/php-fpm/xdebug.ini and enable at least the following configurations: 
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_connect_back=1

And about `.php-fpm` mention in docs - it is indeed mistake. There must be `./php-fpm` folder which is `laradock/php-fpm`.

**Comment by fireproofsocks** [comment]
What docs are you reading @brunen9 ? The only xdebug info I've found http://laradock.io/guides/#enable-xdebug-on-php-fpm -- besides the error you confirmed, it says this:

> If you have enabled xdebug=true in docker-compose.yml/php-fpm, xdebug will already be running when php-fpm is started and listening for debug info on port 9000.

which I don't think specifies anything about which host or folder where edits should be made... the only bit about the xdebug.ini seems to be in the wrong section (down by the firewall settings?).  Regardless, I don't think the proper place to enable xdebug is in any docker-compose.yml file, is it?  It looks like it's meant to be edited in the .env, no?  But then what steps are required to recompile the containers with that extension enabled?  Those are really the most important bits of information about using xdebug and they do not appear to be in the docs.  What am I missing?

**Comment by brunen9** [comment]
@fireproofsocks , try this link: http://laradock.io/documentation/#install-xdebug

**Comment by fireproofsocks** [comment]
@brunen9 thanks!  That would be a useful page to link to from the other section.  

It seems that the `laradock/php-fpm/xdebug` has errors:
```
./xdebug start
./xdebug: line 100: syntax error: unexpected end of file
```

**Comment by brunen9** [comment]
@fireproofsocks , in my case this file is fine and works, and line 100 is just empty line: https://github.com/laradock/laradock/blob/c2c30bfd0f278f6978a48dc62cf3ee063c9f3efa/php-fpm/xdebug#L100
