### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by iredmedia** [laradock/laradock#1028]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 21f0a1034364a9224025604a6b2daab3fcf066df
- System info (Mac, PC, Linux): Linux
- System info disto/version: El Capitan 10.11.6 (15G31)

##### What seems to be going wrong?
I'm unable to change passwords for prod-ready dbs. I've changed the .env and checked ```docker-compose config``` to validate.

I've removed all containers, volumes, images, to my knowledge ```docker stop $(docker ps -qa)``` ```docker rm $(docker ps -qa)``` ```docker volume rm $(docker volume ls -q)```

```docker-compose up -d postgres``` doesn't change anything for me, I'm not sure where it's finding the old values, but for some reason they still work. 
_____

##### What should be happening instead?
The test should be succeeding like it does when I use the old information. I am using the correct db, I'm running it on DigitalOcean. 

being able to attempt to login directly might be helpful but i get the "root" disallowed error.
_____

##### How might we be able to reproduce the error?
Fails on second load only!

1. cp env-example .env
1. (IMPORTANT) docker-compose up -d postgres
1. docker stop $(docker ps -qa) && docker rm $(docker ps -qa) && docker volume rm $(docker volume ls -q)
1. Change password/username/dbname in .env for postgres
1. docker-compose up -d postgres
_____

**Comment by iredmedia** [comment]
It works perfectly when doing this with mysql

**Comment by iredmedia** [comment]
I updated my post, it fails on second-load so I must be missing something.

**Comment by bestlong** [comment]
Hi @iredmedia by default,  database container will storage to host os by .env config:

```
# .env file
DATA_SAVE_PATH=~/.laradock/data
```

so, you need delete ~/.laradock/data/postgres folder. **but this action will lost all data**.

**Comment by iredmedia** [comment]
Okay, that makes a lot of sense. So the best way to change these values would be to execute commands to pgsql like normal?

**Comment by bestlong** [comment]
@iredmedia Yes, use pgsql or pgadmin do password change without delete all database.
