### ISSUE TITLE
PHP-worker and Setup for Multiple Projects

### ISSUE THREAD

**Issue by nguyenhaiphan** [laradock/laradock#1030]
##### The php-worker is not working for the case "Setup for Multiple Projects"

_____

##### The current php-worker is not support the command line for the case "Setup for Multiple Projects", the command at line 5 (https://github.com/laradock/laradock/blob/master/php-worker/supervisord.conf) should have some fallback under that case.

_____

##### Do the step follow Setup for Multiple Projects guide, then run below to found out that artisan is not found at /var/www (which currrently is under any shared-childred laravel project)
```
docker-compose up php-worker
```
_____

### Relevant Code:

```
command=php /var/www/artisan queue:work --sleep=3 --tries=3 --daemon #<-- trouble here
```

**Comment by ariefitriadin** [comment]
also maybe better  the configuration file ( e.g supervisord.conf) that reside in  /conf.d folder should linked from volume folder just like nginx site configuration.
so we can create multiple configuration file for supervisor based on project

**Comment by evantolorio** [comment]
I tried changing line 5 to something like this:

`command=php /var/www/<app_name>/artisan queue:work --sleep=3 --tries=3 --daemon`

and it runs. However, it enters into fatal state after many spawn retries

**Comment by pnghai** [comment]
https://stackoverflow.com/questions/28994647/supervisor-how-to-run-multiple-commands

Yo, finally I have found a way to run as many tasks for each project as the system allow 🗡
