### ISSUE TITLE
ERROR: Cannot start service workspace

### ISSUE THREAD

**Issue by sakanaproductions** [laradock/laradock#1037]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 7c9f9c1ecd2aac099da00267303d984db3b0fdc3
- System info (Mac, PC, Linux): Mac
- System info disto/version: OSX Sierra

##### What seems to be going wrong?

docker-compose up -d nginx mysql
Recreating laradock_mysql_1
Starting laradock_applications_1
Recreating laradock_workspace_1

ERROR: for workspace  Cannot start service workspace: oci runtime error: container_linux.go:247: starting container process caused "chdir
to cwd (\"/var/www/laravel\") set in config.json failed: no such file or directory"
ERROR: Encountered errors while bringing up the project.
_____

##### What should be happening instead?

All containers should bootup on fresh install
_____

##### How might we be able to reproduce the error?

install laradock on existing project, follow default steps
_____

**Comment by amadeann** [comment]
What is your directory structure? Do you have a project directory with 2 subdirectories for laradock and your laravel app? 

What Application Path did you specify in the .env file?

**Comment by sakanaproductions** [comment]
@amadeann typical setup for laravel project with laradock within the project per quick start guide

APPLICATION=../
