### ISSUE TITLE
Add Prestissimo composer plugin in workspace image

### ISSUE THREAD

**Issue by luciano-jr** [LaraDock/laradock#104]
This plugin (https://github.com/hirak/prestissimo) help us with composer to have a parallel install approach.

It's very useful, the results makes really difference in the workflow.

**Comment by Mahmoudz** [comment]
@luciano-jr Yes I'm familiar with it. Do you think we should have it by default installed on the Workspace container!! or let interested developers installed it on their own images whenever needed!

**Comment by luciano-jr** [comment]
@Mahmoudz I don't think we will have problem to add by default in the container. The key here is that most developers don't know about Prestissimo, maybe we could just recommend in the documentation or something like this.
