### ISSUE TITLE
Installing wordpress with laradock 

### ISSUE THREAD

**Issue by govnah** [laradock/laradock#1045]
### Info:
- Docker version (`17.06.0-ce, build 02c1d87`): 
- Laradock commit (`bf60f7520b9f437c54f8e00f349dfaaffce37361`): 
- System info (Mac): 
- System info macOS Sierra/10.12.5: 

##### What seems to be going wrong?
When trying to set up wordpress, i get HTTP ERROR 500 on step 2.
I have searched for errors in the logs, but nothing. I have read about on setting CODEIGNITER=true but that variable is not in the .env file.

_____

##### What should be happening instead?
i expected wordpress to be able to connect to the database with the same credentials i connect to sequel pro with. 
_____

##### How might we be able to reproduce the error?
Follow the installation guide on laradock.io create a multi project environment. Download wordpress, set nginx custom domain and allow that in hosts file, run wordpress setup.
_____

### Relevant Code:

```
// place code here
```

**Comment by govnah** [comment]
Got it working by setting `ARG INSTALL_MYSQLI=true ` in Dockerfile-71 found in php-fpm.

**Comment by stoneshower** [comment]
It's not working on my side.

**Comment by stoneshower** [comment]
In my case, I needed to login as root.

Used below for login to phpmyadmin
server: mysql
user: root
pass: root

The default credential is in .env
```
MYSQL_VERSION=latest
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root

```
