### ISSUE TITLE
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on  and ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1 

### ISSUE THREAD

**Issue by sagarjethi** [laradock/laradock#1046]
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 
(70abb55c6fea0fad18be272bec05c124f70585a5d5da79d781e1608c5d847b0e): Bind for 0.0.0.0:443 failed: port is already allocated  ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1 (7223c8ffa61a6f82de0f37f9e9ac5d8bfd7087626426c5eda3ff7e4d1efba1e0): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use

**Comment by Mahmoudz** [comment]
@sagarjethi apparently your ports (443 and 3306) are already in use, either change them in the .env file or see where those ports are used in your machine and turn them off.
