### ISSUE TITLE
ERROR 1146 (42S02): Table 'information_schema.SCHEMATA' doesn't exist

### ISSUE THREAD

**Issue by francisco-ltech** [laradock/laradock#1047]
### Info:
- Docker version (`$ docker --version`): Docker version 17.06.0-ce, build 02c1d87
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): PC
- System info disto/version: windows 10

##### What seems to be going wrong?
docker exec -it <mysql> bash
mysql -u root -p
show databases;
_____

##### What should be happening instead?
see available databases or none? isn't the container supposed to create it by default?
_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
// place code here
```

**Comment by francisco-ltech** [comment]
I resolved this error by running:
`mysql_upgrade -u root -p --force`

However, the next error whilst try to migrate the schema versions of Laravel is:
`SQLSTATE[HY000] [2054] Server sent charset unknown to the client. default character set utf8mb4 collate utf8mb4_unicode_ci.`

It seems the problem has to do with a bug in the driver in the version of PHP that comes with laradock?
https://bugs.php.net/bug.php?id=74461

This bug seems to be resolved in PHP1.7.5.

**Comment by govnah** [comment]
Hi, was having the same issue, i run the mysql_upgrade you posted and now i'm able to see databases. But i still have an issue of connecting to the database via sequel pro, using credentials i changed in .env

Are you facing same issue and have you been able to solve it? 

thank you

**Comment by francisco-ltech** [comment]
Have you tried to using host=mysql?

If you are using the laradock repo you can spin up phpmyadmin: 
docker-compose up -d nginx mysql phpmyadmin
then you can browse phpmyadmin at: http://localhost:8080

**Comment by govnah** [comment]
I have added 127.0.0.1 mysql in my hosts file, base on some post i read. 
i just used phpmyadmin wth the following credentials and it worked:
`username: laradock`
`password: secret`
`database: zoo` (Collation: utf8mb4_0900_ai_ci)

Then i have a php file which i have this code in it.
`$con = mysqli_connect("127.0.0.1","laradock","secret","zoo");
var_dump($con);`

this is the result i get:
`Warning: mysqli_connect(): (HY000/2002): Connection refused in....`

When i use "mysql" instead of "127.0.0.1", i get:
`Warning: mysqli_connect(): Server sent charset (255) unknown to the client. `

**Comment by Mahmoudz** [comment]
Try downgrading the MySQL version from 8.0 to 5.7 https://github.com/laradock/laradock/commit/50834268a76afb0b4685345b03943b2cd80ac6ea then rebuild the container.

**Comment by pablorsk** [comment]
I try downgrading MySQL to 5.7, but when up docker-machine I receive this:
```
laradock_mysql_1 exited with code 1
```

**Comment by govnah** [comment]
I did the following to get mine working:

1. Removed image `$ docker rmi laradock_mysql`
2. Remove container `$ docker rm laradock_mysql`
3. Located `DATA_SAVE_PATH=~/.laradock/data` in .env file
4. Deleted **mysql** folder
5. Modified **laradock/mysql/Dockerfile** 
```
FROM mysql:5.7
MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
RUN chown -R mysql:root /var/lib/mysql/
ADD my.cnf /etc/mysql/conf.d/my.cnf
CMD ["mysqld"]
EXPOSE 3306
```
6. Buil `docker-compeer up -d mysql nginx`


I hope I didn't miss anything in the steps.

**Comment by roballport** [comment]
Changing the mysql container version to 5.7 from 8.0 didn't fix this for me. 

After lots of faffing I decided to start from scratch. Before building the containers for the first time ensure you have set the mysql version at ```laradock/mysql/Dockerfile``` to 5.7 as described at https://github.com/laradock/laradock/issues/1047#issuecomment-314942343. 

Setting the version from mysql 8.0 to 5.7 caused lots of issues. At the moment it's quicker to set the version before starting the build process.

**Comment by springjk** [comment]
**solution**:

1. `rm -rf ~/.laradock/data/mysql` **warning**: it will delete your mysql exist data
2. `docker-compose up --build mysql`

**question**:

for this issue, i do `docker-compose down -v`, but the error still exist, i realize the mysql container not use docker volume system , so i checked `docker-compose.yml`,In there, i found a question:

for laradock old version, mysql use docker volume save data, example:
```
    mysql:
        ……
        volumes:
            - mysql:/var/lib/mysql
``` 
now:
```
    mysql:
        ……
        volumes:
            - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
   volumes:
      mysql:
        driver: "local"

   DATA_SAVE_PATH=~/.laradock/data
``` 

so, who is using the volume `mysql`? I hope I didn't miss anything for this config. is that a bug? @Mahmoudz

**Comment by NdsmallsYT** [comment]
I'm trying to do an assignment for school through this platform with mySQL and I keep getting this error: 

Status: FAILED!
Check: 1
Test: Query the start date for each driver
Reason: The following error is preventing tests from completing: 1146 (42S02): Table 'InstantRide.DRIVERS' doesn't exist
Error : ProgrammingError - 1146 (42S02): Table 'InstantRide.DRIVERS' doesn't exist
Timestamp: 2025-03-23 20:42:54.844827

Any idea on how to fix this?
