### ISSUE TITLE
Split `docker-compose.yml` and `env-example` into smaller files

### ISSUE THREAD

**Issue by vwchu** [laradock/laradock#1053]
Currently, the `docker-compose.yml` is one large file for all the containers defined and the `env-example` is one large file that contains all the environment variables. As the number of images and containers continues to increase this becomes more and more difficult manage, maintain and extend easily.

Originally, I tried to reorder the sections in the `env-example` based on the ordering in the `docker-compose.yml`, but I thought they still will be two very large files. So, why not split the `docker-compose.yml` into smaller files, one for each image, and split the `env-example` similarly, one for each `docker-compose.yml`, approximately.

The `docker-compose.yml` files can be composed together using the `-f` option in the `docker-compose` command and the `env-example` files can concatenated together via a shell script or the [laradock/cli](https://github.com/laradock/cli).

This way it is more modular and we can add new images by adding a `docker-compose.yml` and `.env.example` and registering the module in the shell script.

```bash
scripts/laradock.sh environvars:template --output .env
docker-compose $(scripts/laradock.sh dockercompose:args) up
```

**Other benefits:**

I can choose which modules to include when generating my `.env` and composing my `docker-compose.yml`, keeping my `.env` relatively small with only the modules I need. For instance:

```bash
MODULES=workspace nginx php-fpm mysql
scripts/laradock.sh environvars:template --output .env ${MODULES}
docker-compose $(scripts/laradock.sh dockercompose:args ${MODULES}) up ${MODULES}
```

I can write an `.env.example` with only the variables that I want to modify and override the default
variables in the modules that I chose to include. For example:

`../.env.example`:
```
APPLICATION=../../
DATA_SAVE_PATH=../.data
```
```bash
MODULES=workspace nginx php-fpm mysql
TEMPLATE=$(scripts/laradock.sh environvars:template ${MODULES})
echo "$TEMPLATE" | scripts/laradock.sh environvars:evaluate --output ../.env --template /dev/stdin ../.env.example
docker-compose $(scripts/laradock.sh dockercompose:args ${MODULES}) up ${MODULES}
```

Currently, it is a work in progress, here: https://github.com/vwchu/laradock/tree/feat-split-configs

Any thoughts?

**Comment by vwchu** [comment]
I have an extension that adds the ability to do variable substitution in the `.env.example` files. https://github.com/vwchu/laradock/tree/feat-variable-subs 

For example:

**`./.env.example`**:
```
BUILD_ROOT=.
APPLICATION=../
DATA_SAVE_PATH=~/.laradock/data
LOG_PATH=${BUILD_ROOT}/logs
DEFAULT_IMAGE_TAG=default
PHP_VERSION=71
PHP_INTERPRETER=php-fpm
PHP_SOCKET_PORT=9000
```

**`./apache2/.env.example`**:
```
### Apache Server Container

APACHE_IMAGE_TAG=${DEFAULT_IMAGE_TAG}
APACHE_HOST_HTTP_PORT=80
APACHE_HOST_HTTPS_PORT=443
APACHE_PHP_INTERPRETER=${PHP_INTERPRETER}
APACHE_PHP_SOCKET_PORT=${PHP_SOCKET_PORT}
APACHE_HOST_LOG_PATH=${LOG_PATH}/apache2
APACHE_SITES_PATH=${BUILD_ROOT}/apache2/sites
```

**Comment by vwchu** [comment]
See: https://github.com/laradock/laradock/tree/laradock-next

**Comment by a-h-abid** [comment]
While I'm on board with splitting up docker-compose file, I'm not OK with env file being separated. It may become big, I don't want to go around all folder and update env file. It will become frustrating when setting up on a server environment. Also I think any new developer or beginner coming to laradock will see this as a hassle.

**Comment by vwchu** [comment]
@a-h-abid I currently merge the env files into a single file before executing the docker-compose using the `environvars:template` command in the script.

Also, the `environvars:evaluate` command allows you to create a file with all the relevant variables that you changed or are applicable to your project. Then, when you want to run docker-compose, you build the `.env` file with the `environvars:evaluate` command, that substitutes your specified values into the output. That way you only need to change that file with your project-specific variables.

**Comment by vwchu** [comment]
@a-h-abid Thanks for the feedback. I think splitting up the docker-compose file and the env file will actually make the project much more maintainable and scalable. It will make it possible to plugin new images with no changing to the docker-compose and env file that affects other images.

In terms of user experience, it should be all that different from it is now. With the additional of a CLI, editing project specific environment variables shouldn't be different from editing the env file currently. But we get benefits such as only including containers, images and variables that we need for our specific projects, automatic dependency management for which docker-compose and env files to be included, etc.

Unfortunately, my implementation of the CLI is kind of clumsy and not very elegant or easy to use. And I intend to fix that. Again thanks for your feedback.
