### ISSUE TITLE
Scripts and styles files do not update properly on change...

### ISSUE THREAD

**Issue by sushantDev** [laradock/laradock#1054]
### Info:
- Docker version (`Docker version 17.05.0-ce, build 89658be`): 
- Laradock commit (`7c9f9c1ecd2aac099da00267303d984db3b0fdc3`): 
- System info (PC): 
- System info Windows 10 Home Edition: 

### Issue:
It is working perfectly but the problem is any changes done to styles and scripts are not being reflected in browser. I am using laravel mix watch to compile my resources. Whenever i try to recompile my resources, the file changes but, the browser opens a different version of file with unknown characters like: ������������������� at the end.

##### What seems to be going wrong?
I think it's the problem related to cache.

I already tried:
1. clearing cache in nginx.
2. clear all artisan cache too.
3. kept send file : off in nginx.conf file.
4. rechecked my file paths.
_____

### Expected behavior:
Should have changed resources to the browser according to my changes in my editor.

**Comment by ShresthaSrawan** [comment]
I also encountered the same issue... In my case I changed my css but it wont change in the browser. I could not find any viable solution but to use [Laravel mix](https://laravel.com/docs/5.4/mix#versioning-and-cache-busting) to generate different version of the same file in each compilation.

**Comment by famelis** [comment]
The problem, IMHO, is with the browser. It is using the cache for css and js.
If you are in development environment you can use google chrome and open the programmer's tools (Ctrl+Shift+I)
Then in the Network tab the "Disable cache" must be checked, and this solves the problem.
In production you need to have different paths/names for the files, possibly with version number, for the browser to re-read the files and not use the cache.

**Comment by mro1127** [comment]
nginx/nginx.conf
`  sendfile off;
  tcp_nopush off;
  tcp_nodelay off;
`
and then:

 `
docker-compose build nginx
docker-compose restart nginx
`
