### ISSUE TITLE
pgAdmin 4 - login page

### ISSUE THREAD

**Issue by jvzanatta** [laradock/laradock#1060]
### Issue:

Sorry if it's just me not being able to use the tool properly, but I searched a lot and did not found any answers.

After `docker-compose up` I go to localhost:5050 and the login page of pgadmin4 is displayed. I don't know how to access the databases without this login (e-mail), nor have any ideia of which login is the screen talking about... How to proceed? Thanks in advance!

_____

### Expected behavior:

I expected to see the pgdmin4 interface

_____

### Reproduce:

Clone the project then start the postgres and pgadmin containers, then access 0.0.0.0:5050 or localhost:5050

**Comment by jvzanatta** [comment]
My bad, did not see the official container page with default login/password.

**Comment by inthedeepend** [comment]
For future reference 

Username : pgadmin4@pgadmin.org
Password : admin

Let's get this into the docs!
