### ISSUE TITLE
Proposed major revisions to Laradock

### ISSUE THREAD

**Issue by vwchu** [laradock/laradock#1065]
Hi everyone,

Currently, Laradock has one very large `docker-compose.yml` file and one large `env-example` file.
With the demand of more containers and features from users, maintaining, extending and simply using these files will become increasingly difficult. (https://github.com/laradock/laradock/issues/1053) So, I did a major reworking of Laradock by splitting the `docker-compose.yml` and `env-example` into smaller files, one of each for each Docker image. Then, I wrote a Bash script to manage these `docker-compose.yml` and `env` example files and provide a number of handy commands for using Laradock and docker-compose. 

### Goals of this revision:

* Improve modularity and extensibility of the system
* Improve user experience for power users and novice alike with a CLI tool.

### Commands:

- `laradock build` -- Generate the `.env` file and run docker-compose build.
- `laradock dockercompose` -- Execute `docker-compose` with the given arguments
- `laradock down` -- Stop and remove containers and networks, optionally volumes and images as well.
- `laradock help` -- Shows help for the CLI.
- `laradock init` -- Initializes Laradock into existing projects.
- `laradock install` -- Install local copy of specific modules into your project.
- `laradock linkcli` -- Creates a link to this CLI.
- `laradock logs` -- View output from containers.
- `laradock tty` -- Execute `docker-compose exec -it <container> bash`.
- `laradock up` -- Create and start containers.

### Features

- Generates two files `.laradock.example` and `.laradock.env`.
   - `.laradock.example` is for project specific customizations
   - `.laradock.env` is for sensitive information, such as usernames, passwords, keys, etc.
- Only include Docker containers and variables that are needed for your project.
- Automatically, dependency inclusion for `docker-compose.yml`'s and `.env`'s.
- At build time, using `.laradock.example` and `.laradock.env`, `.env` is generated automatically.
- **Variable substitution within the `.env` files similarly to within the `docker-compose.yml` files, including default values.**
- **Just-in-time creation of the `.env` for all `laradock (up|down|tty|logs|dockercompose)` commands if `.env` output is detected as changed.**
- **Install local copy of modules into your projects, enable customization of site configs, dockerfiles, etc without editing the originals.**
- **Generate single `docker-compose.yml` output for systems that can't run laradock or projects that don't want to depend on laradock in production.**
- **Add `Node` image and container.**

### Changes

- **`docker-compose.yml` versions upgraded to 2.2, adds support for default value for variables.**
- **All images will be named `laradock/<image>:local.<tag>`**
- **Image build paths specified in `.env` file.**
- **All modules, grouped into `modules` directory.**
- **Missing variables, for hardcoded ports and values in `docker-compose.yml`'s, added to `.env`'s.**
- **Add common, `LOG_PATH` and `USERCONFIG_PATH` variables.**

### Remaining Tasks

- Add commands and facilities to register and unregister commands and modules "plugins".
- Add update and versioning commands.
- Performance improvements, and fix bugs. Reduce startup times.
- Update documentations

### Additional commands and debugging:

- See `ENABLE_PRIVATE_VARIABLES=true laradock help`
- `VERBOSE` (between 0 "silent" and 7 "verbose")

Still a work in progress.
But you can check it out here, at https://github.com/vwchu/laradock.
Could use any feedback or contributions.

**Updated:** 2017.07.25 (**NEW** in bold).

**Comment by Mahmoudz** [comment]
@laradock/admins Hello guys, hope you all doing well. 

Please check [this](https://github.com/vwchu/laradock) interesting feature whenever you have some free time. Would love to get your opinions and feedbacks.

**Comment by kirtangajjar** [comment]
@vwchu @Mahmoudz Not related to this, but while we're at it, can we update certbot to use `certbot` and not `letsencrypt`? 

Also, it would be great if we could - 
1. Somehow copy paste the certs to right place(probably to a `.ssh` folder in application).
2. Add some default configuration for ssl in apache/nginx containers so that ssl could work out of box.

**Comment by appleboy** [comment]
We can also discuss here https://github.com/laradock/cli/issues/1 maybe I can write CLI tool using Golang which supports Windows, Linux and MacOS.

**Comment by Mahmoudz** [comment]
@vwchu Hello, will this [tool](https://github.com/gulien/orbit) be helpful for your implementation of the CLI?

Orbit is made by @gulien maybe he can share with us an intro about it here.

**Comment by gulien** [comment]
Hi @vwchu!

Looks like you did some nice works here 😃 

[Orbit](https://github.com/gulien/orbit) might indeed helps you a lot in your job!

Its first functionality is its ability to generate files from templates using values provided by one or more YAML files and one or more `.env` files. In your project, you rely a lot on `.env` files to setup your `docker-compose.yml` files.  Orbit might handle for you the generation of those `.env` files using valus provided by a `.env` file and a `laradock.yml` file. The first would contain sensible data (secrets for example) and environments related data. The last would contain cross-environments data (users of modules, ports and so on). 

Also, an interesting functionality of Orbit is to let you define commands in a YAML file. 
From the documentation:

---
```yaml
commands:
  - use: "my_first_command"
    run:
      - command [args]
      - command [args]
      - ...
  - use: "my_second_command"
    run:
      - command [args]
      - command [args]
      - ...
```

* the `use` attribute is the name of your Orbit command.
* the `run` attribute is the stack of external commands to run.
* an external command is a binary which is available in your `$PATH`.

Once you've created your `orbit.yml` file, you're able
to run your Orbit commands with:

```
orbit run my_first_command
orbit run my_second_command
orbit run my_first_command my_second_command
```

Notice that you may run nested Orbit commands :metal:!

---

We could imagine the following:

*Project structure*
```
.
├── config
     └── orbit # folder which contains sub Orbit configuration files
├── modules
     └── a_module
          └── .env.blueprint # a .env template
├── orbit.yml # the main Orbit configuration file
├── .env # the main .env file
└── laradock.yml # the cross-environments data
```

*modules/a_module/.env.blueprint*

```
A_USER={{ Values.Laradock.a_module.a_user }}
A_SECRET={{ .EnvFiles.Laradock.A_SECRET }}
A_PORT={{ Values.Laradock.a_module.a_port }}
```

*.env*

```
A_SECRET=my_awesome_secret
```

*laradock.yml*

```yaml
a_module:
    a_user: my_awesome_user
    a_port: my_awesome_port
```

*config/orbit/orbit-generate.yml*

```yaml
commands:
  - use: "generate-a-module"
    run:
      - orbit generate -t=modules/a_module/.env.blueprint -o=modules/a_module/.env -v=Laradock,laradock.yml -e=Laradock,.env
```

*orbit.yml*

```yaml
commands:
  - use: "generate"
    run:
      - orbit run generate-a-module -c=config/orbit/orbit-generate.yml
      - ...
```

So, when running `orbit run generate` at the root of the project, Orbit will generate the `.env` file of  `a_module` 👍 ! Of course, this is a basic example. As Orbit uses the Go package `text/template`under the hood as a template engine, you have at your disposal a interesting amount of logic for your templates.

Also, you wrote a lot of nice scripts, which are unfortunately not cross-platform. We could imagine having a "Laradock image" which contains those scripts. See [here](https://github.com/thecodingmachine/kickoff-docker-php/blob/master/.docker/.orbit/orbit-docker-commands.yml#L34) how I handled calling scripts from a container with Orbit.

Last but not least, you should take a look at the [kickoff-docker-php](https://github.com/thecodingmachine/kickoff-docker-php) to have a real example on how I used Orbit to run my stack.

If you need help, let me know 😄 ! I'll be glad to help!

**Comment by vwchu** [comment]
Hi @Mahmoudz @gulien, I'll definitely have a look at Orbit. Looks promising for a rewrite into Go. Something that I have been considering, but I just have been too busy lately and am not too familiar with Go.

**Comment by gulien** [comment]
@vwchu Your project structure inspired me for the first v2.0.0 stable release of my project! 😄
You have now a complete example at your disposal. 😉

**Comment by jeff-h** [comment]
I am very interested in discussion around a restructure of Laradock.

Using it in dev, the changes I have had to make to laradock's various configs are numerous and hard to find. The only way I can really know what I've changed is manual file diffs and git history. I'm just talking simple things like php memory allocation, installing libssh2, adding a shared volume or three etc

I'm also working toward using laradock in production, so the configuration management becomes even more difficult; most prod config need to inherit from dev, but some things need to extend it, some things need to be removed.

I am hoping there might be a better way! @vwchu do you think your changes would help resolve the above concerns?

As a docker newb Laradock currently feels simple and easy to understand — really just a bunch of fine-tuned standard docker configs — so I'm nervous about introducing "proprietary" stuff to it. I'm probably asking for the impossible — powerful but simple to understand :)

**Comment by vwchu** [comment]
Hi @jeff-h, sorry for the delay response. Haven't been able to devote much time to this project lately.

My original proposal was to restructure the project was rooted the following concerns and goals:
- I only want the modules that I use
- Similarly, I only want to deal with the configuration for the modules use
- Modules should be independent from each other and dependencies between them should be explicit and versioned. 
- Module implementation should be libraries (immutable / blank box to users) 
- Configurations are separate from implementations and centralized. Managed by the users with a generated scaffolding provided. 

Originally, I used a shell script to prototype this, but it was too slow. Thinking currently about a solution using a mix between Docker hub, a package manager, Docker in Docker, and maybe multi stage Docker builds. 

Another effort has been to make a Go-based CLI laradock/cli but not sure about its progress and status. 

Unfortunately I don't have the time currently to experiment. Maybe in the holiday or new year. But it would be probably be from scratch with modules ported over eventually if it works. 

-- VC

**Comment by jasperf** [comment]
Interesting development. Was looking into easier ways to setup Laradock for development as well as production. Tips on what do do and not do for production specifically. I would prefer to work with one `docker-compose.yml` file and have it all work on development and production using a secure enough setup and a different SSL Certificate for both local and productions setups. Then I bumped into this thread. I agree it would be easier to have a modular approach so you do not have to wade through a large .env and `docker-compose.yml` file. Would also be awesome to be able to grab modules using a command like tool. Perhaps a bit like Laravel and its packages. But I see this setup is tough and might not come to fruition any time soon. Will keep track of this thread while I keep on learning to tweak my  Laradock setup with `Nginx, MariaDB, Redis, PHP FPM, Horizon`.
