### ISSUE TITLE
Get rid of the multiple docker files for the php-fpm & workspace containers

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#1067]
Currently we have multiple `dockerfiles` for the `php-fpm` and `workspace` containers. 
Both images have `dockerfile-56`, `dockerfile-70` and `dockerfile-71`, we can get rid of them now after the new docker ability to define variable in the image tag.

As an example see the [Mysql docker file](https://github.com/laradock/laradock/blob/master/mysql/Dockerfile).

```dockerfile
ARG MYSQL_VERSION=8.0
FROM mysql:${MYSQL_VERSION}
```

The `MYSQL_VERSION` can be defined in the `.env` file.

For the difference between the different versions setup, we can use some `if-else` statements within the single file.

**Comment by vwchu** [comment]
I'll start making these changes to my branch.
I have added a Node image, that could make use of it.
Should we upgrade the docker-compose format to the latest version "3.3" as well?
I have already upgrade mine to 2.2, adding support for default values in the docker-compose.yml, so we omit variables in the env files. The problem with upgrading to 3.3 is some containers use `volumes-from` which was removed.

**Comment by vwchu** [comment]
Perhaps: add tags on Docker Hub for laradock/workspace:1.8-71 to laradock/workspace:1.8-7.1, etc.

**Comment by Mahmoudz** [comment]
@vwchu yeah it works I've tested it today.

Would be awesome if we upgrade docker compose to `3.*` but as you mentioned the problem with removing `volumes_from` is forcing us to change the way the `application` container maps the code with the other containers. I haven't played with this, if you have some time to experiment it would be great.

**Comment by vwchu** [comment]
Sounds good. If you have a chance, PR me with the changes to workspace, php-fpm and maybe mysql.
Or should I finally create a branch here on this project. It is nearly final for me, with just some small loose ends.

Also, going to be super busy going forward unfortunately, so less commits from me for this project.
