### ISSUE TITLE
MySQL 8 ut8mb4 error

### ISSUE THREAD

**Issue by samijnih** [laradock/laradock#1071]
### Info:
- Docker version (`$ docker --version`): Docker version 17.06.0-ce, build 02c1d87
- Laradock commit (`$ git rev-parse HEAD`): from master for mysql/php-fpm/redis/workspace/nginx
- System info (Mac, PC, Linux): MAC
- System info disto/version: 

### Issue:

I'm currently using PDO through Doctrine with Silex.

When connecting to the database, it says:
```
[Doctrine\DBAL\Exception\DriverException]
  An exception occurred in driver: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers
```

That's a PHP problem due to its version (7.1.4 from the latest of laradock). It should have been solved with the release of 7.1.5 but 7.1.4 seems to be the "latest" php version installed through laradock.

These lines don't work after stopping/building/running mysql:

> mysql/my.cnf

```
[mysqld]
character-set-server=utf8
```
_____

### Expected behavior:
Idk
_____

### Reproduce:
`.env` with `PHP_VERSION=71` and `MYSQL_VERSION=8.0`

`docker-compose build`
`docker-compose up -d mysql`

```
<?php
    $mysqli = new mysqli($aConnection['host'], $aConnection['user'], $aConnection['password'], null, $aConnection['port'], null);
    if ( $mysqli->connect_error ) {
        echo $mysqli->connect_error . ' (' . $mysqli->connect_errno . ')';
    }
?>
```

More details available there [https://bugs.php.net/bug.php?id=74461](https://bugs.php.net/bug.php?id=74461)

**Comment by Mahmoudz** [comment]
@samijnih try deleting this folder `.laradock/data/mysql` then rebuilding the MySQL container. 

Note you will lose your current data. So consider exporting your data first if needed. 

Also if your previous data was created with MySQL 5.7 and trying to import it to MySQL 8.0 you might face troubles. So pick the right version for you and rebuild but always delete that folder when doing so.

**Comment by samijnih** [comment]
I already did it but it doesn't solve the problem :/

**Comment by samijnih** [comment]
On the Ubuntu repo, it seems to be PHP 7.1.7. 

Maybe you could fetch this last version according to the current Ubuntu architecture?

https://ibb.co/dGS3n5

**Comment by Mahmoudz** [comment]
Maybe this helps #955 !

**Comment by hominglee** [comment]
@samijnih 
I have the same problem and solve it :)
1. Our php version(workspace) should be 7.1.9 or higher.
2. Use `docker-compose build` or `docker build` instead of `docker-compose up`.
Because `docker-compose up` won't rebuild the image, that make our php version too old to use laradock, if we have laradock in our computer yet.

**Comment by samijnih** [comment]
@hominglee thanks, but I switched on postgresql haha
