### ISSUE TITLE
Unable to connect to mysql

### ISSUE THREAD

**Issue by Narahari-Sundaragopalan** [laradock/laradock#1073]
I am using Laradock on Mac OS with a laravel project. 

### Issue:
I used laradock containers mysql and nginx. I am able to get the application running on my localhost. But I am unable to connect to mysql container from my host machine (MAC OS).

My docker-compose.yml contains all the configuration for MySQL as shown below: 
mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE:homestead
        - MYSQL_USER:homestead
        - MYSQL_PASSWORD:secret
        - MYSQL_ROOT_PASSWORD:secret
        - TZ:${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      networks:
        - backend
Then I did docker-compose up -d mysql nginx 
This created the containers and bought them up and running. 
Next I changed the .env file accordingly for DB connection. 
APP_DEBUG=true
APP_ENV=local
APP_EXECUTION_TIME_LIMIT=300
APP_KEY=fshhVdCCne5dJTznON0W988vFnDTiDlm
BUGSNAG_API_KEY=
CACHE_DRIVER=file
DB_DATABASE=homestead
DB_HOST=127.0.0.1
DB_PASSWORD=secret
DB_USERNAME=homestead
DB_PORT=3306
SESSION_DRIVER=file
QUEUE_DRIVER=database

After that I did php artisan:migrate. --> This caused the tables to be created and I also seeded them succesfully from the command line. 
But when I open my app on localhost, and try to login, I get connection refused for mysql container.
I also tried to change the IP from localhost to the IP of the mysql docker container (172.23.0.2) or something, but then the request times out. And I am unable to ping the machine from my terminal.
The ports are also exposed in laradock.

I am new to laradock and not aware if I am missing something basic to be done here or doing it the wrong way. 

I want my application to connect to the database. Can someone please help asap ?

**Comment by weweliang** [comment]
`DB_HOST=mysql`

and add

`127.0.0.1 mysql`

in your Mac /etc/hosts

**Comment by Narahari-Sundaragopalan** [comment]
Thanks, I had already done that. I figured out the issue was that, I had to set the port number in the my.cnf file of mysql. Then i was able to connect to MySQL from host machine.

**Comment by exfriend** [comment]
Just for future: had the same issue but no luck with any solution. Turned out I had wrong permissions on my.cnf

**Comment by xushaobo** [comment]
try the command:
chown -R mysql:mysql /var/run/mysqld
