### ISSUE TITLE
Port 80: Connection refused

### ISSUE THREAD

**Issue by rkmaier** [laradock/laradock#1078]
### Info:
- Docker version (`$ docker --version`):  Docker version 17.06.0-ce, build 02c1d87
- Laradock commit (`$ git rev-parse HEAD`): d2920abcd9ff0629f078f8c99592bdeaec77b3fe
- System info: PC
- System info disto/version: 

### Issue:
I run mutliple sites inside an apache2 container using vhosts, and I added my hosts as extra_host in the  docker-compose file. My problem is i cant  make post/get request using curl from inside the container to my own vhosts domains, i get a Connection refused error message.

**Comment by Snaver** [comment]
https://github.com/laradock/laradock/issues/435#issuecomment-315064141
