### ISSUE TITLE
PUID .env option should effect more then just workspace

### ISSUE THREAD

**Issue by Shadow2004** [laradock/laradock#1083]
### Info:
- Docker version 17.06.0-ce, build 02c1d87
- Laradock commit d32cfb31b16b419cebfc5f86fa584caf1e4d2efa
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:
When docker is run as a user who is not the first added user on the system e.g first user has PID of 1000 but second user has PID of 1001. Then the nginx, php-fpm and maybe other instances don't run correctly as their file permissions don't line up correctly.

For the workspace container this can be changed by the PUID option in the .env file but this does not then transfer over to the other containers and you need to then change this manually in the docker files.
_____

### Expected behaviour:
An overall PUID option in the .env file that setups up the PID for all containers correctly. This would then mean that file permissions are assigned correctly in each container to the user running the docker instances.
_____

### Reproduce:
Start laradock instances with a user who is not the first user on the system, then connect into the workspace, nginx or php-fpm container. Once connected check the files for any loaded applications in the www folder and you will see them owned by a number say 1002 rather then the laradock user.
_____

### Relevant Code:

php-fpm container - Dockerfile-71

```bash
RUN usermod -u 1000 www-data
```

Nginx container - Dockerfile

```bash
RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && adduser -D -H -u 1000 -s /bin/bash www-data \
    && rm /etc/nginx/conf.d/default.conf \
    && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf
```

**Comment by 0reo** [comment]
I seem to have just run into this issue

**Comment by jasperf** [comment]
I am running into this issue as well it seems. It is causing Image Intervention issues I believe and I have been writing about this at https://github.com/laradock/laradock/issues/1969 . I am also looking for a solution so I do not get directories generated as root and images that can be manipulated by the PHP-FPM user as well as Nginx.
