### ISSUE TITLE
How to add SSL to NGINX in laradock.

### ISSUE THREAD

**Issue by tariqbilal** [laradock/laradock#1084]
I have used caddy but a client wants me to use the SSL he provided me. So i am stuck, can anyone tell me how to add ssl in nginx.

**Comment by Shadow2004** [comment]
Within your site config file you will want something similar to the below

```bash
server {
    listen 80;
    listen 443 ssl;
    listen [::]:80;
    server_name {SITE_NAME};
    root /var/www/{DOCUMENT_ROOT}/public;
    index index.php index.html index.htm;

    ssl_certificate     {CERTIFICATE_LOCATION};
    ssl_certificate_key {KEY_LOCATION};

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
````

You will then want to add the below code to your nginx Dockerfile to install openssl and create the key files for you

```bash
# install openssl
RUN apk add --no-cache openssl

# create a folder for the keys
RUN mkdir /etc/nginx/ssl 2> /dev/null

# generate the keys for your local domain
RUN openssl genrsa -out "/etc/nginx/ssl/{SITE_NAME}.key" 2048 \
    && openssl req -new -key "/etc/nginx/ssl/{SITE_NAME}.key" -out "/etc/nginx/ssl/{SITE_NAME}.csr" -subj "/CN={SITE_NAME}/O={SITE_NAME}/C=UK" \
    && openssl x509 -req -days 365 -in "/etc/nginx/ssl/{SITE_NAME}.csr" -signkey "/etc/nginx/ssl/{SITE_NAME}.key" -out "/etc/nginx/ssl/{SITE_NAME}.crt"
```
This is for a development setup with self signed certificated, if you wanted to use this for a production server you would need to remove the lines that generate the keys.

**Comment by a-h-abid** [comment]
I also have similar issue. Would you advice keeping the production SSL certificates and keys in the built image? If not, how would we add the SSL certs/keys in automate manner?

**Comment by Shadow2004** [comment]
Yes for production I keep the certs within the repo but I am using a private repo so they are secure.

If you have a non private repo I would leave a hole for them then place them in the right place when you install the application on live.

**Comment by Shadow2004** [comment]
I just re-read that and realised you have put in an automated manner.

That question I am not sure I can answer at this time as I haven't automated the installation of certs on live but you could have some sort of secure file storage for them then change the nginx Dockerfile to pull from that location at build time.

**Comment by elliotleelewis** [comment]
@Shadow2004 So I followed your steps, and when I launch nginx I get the following error:

```
[emerg] 1#1: PEM_read_bio_X509_AUX("/etc/nginx/ssl/Site.csr") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
```

Any ideas?

**Comment by swim89** [comment]
After I modified my Dockerfile and mysite.conf file, I ran:

`docker-compose build --force-rm --no-cache nginx`

And I have this error:

> BIO_new_file("/etc/nginx/ssl/mysite.local.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/mysite.local.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

Could you please help me?

**Comment by bgultekin** [comment]
I think @Shadow2004 's answers should be added to documentation. 

Because we use laradock for local development generally with local, not-real domain names. That's why using caddy with let's encrypt (requires domain validation) as written in documentation is overkill feature in order to access your local development over https. Using self-signed certificates are fine for these circumstances.

**Comment by Shadow2004** [comment]
@swim89 It looks like nginx cant find the vert docs that you generated, so make sure the nginx config is looking in the correct place. Other then that please post your nginx config and nginx DockerFile so i can have a look.

**Comment by neorganic** [comment]
@Shadow2004 can you confirm this is still working? I am getting -  NET::ERR_CERT_AUTHORITY_INVALID from Chrome - I can still go trough via clicking Advanced etc., but Chrome is always reminding that connection is not secure

**Comment by dave-colenso** [comment]
@neorganic that's expected behaviour when using a self-signed certificate. [this](https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate) stackoverflow link explains how to get chrome to trust a self-signed certificate and give you the green padlock

**Comment by Hironate** [comment]
Try installing letsencrypt certificate in nginx or docker container. it works for me. Enter into server cli with - `docker-compose exec apache2 bash` and install the way you do in ubuntu.

**Comment by Myusuf060696** [comment]
i try @Shadow2004 way

and then have this 
```
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/test.mywebsite.co.id.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/test.mywebsite.co.id.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by dm17** [comment]
> i try @Shadow2004 way
> 
> and then have this
> 
> ```
> nginx: [emerg] cannot load certificate "/etc/nginx/ssl/test.mywebsite.co.id.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/test.mywebsite.co.id.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> ```

Same.
