### ISSUE TITLE
Changes in laradock require Docker >= 17.0.5

### ISSUE THREAD

**Issue by benkelukas** [laradock/laradock#1087]
### Info:
- Docker version (`$ docker --version`): Docker version 17.06.0-ce, build 02c1d87 
- Laradock commit (`$ git rev-parse HEAD`): git rev-parse HEAD
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.04

### Issue:
With older versions of Docker (<=17.0.5) we cannot build images because dockerfiles are using ARG before FROM, maybe update documentation to reflect this?

Build fails with error: 
`Step 1/3 : ARG foo
Please provide a source image with `from` prior to commit`

relevat docker issue: https://github.com/moby/moby/issues/32457
pull: https://github.com/moby/moby/pull/31352
_____

### Expected behavior:
_____

### Reproduce:
Try to do `docker-compose up -d nginx mysql` with docker version older than 17.0.5
_____

### Relevant Code:

**Comment by bestlong** [comment]
v7.11.0 https://laradock.io/getting-started/
```
Requirements
* Git
* Docker >= 17.12
```
