### ISSUE TITLE
Caddy fails with subdomain?

### ISSUE THREAD

**Issue by tariqbilal** [laradock/laradock#1088]
How can I set up caddy with subdmain?

gives me this error on set up

failed to get certificate: acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://xyz.abc.com/.well-known/acme-challenge/U--U2WN-VKqudDGm_DQdeNxzCCEGXwKkLAacaW1d86o: "

using a random domain name but this error occurs on my server with real parameters.

**Comment by zuohuadong** [comment]
Make sure the domain name resolves normally.
