### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dupengshenyang** [laradock/laradock#1090]
![image](https://user-images.githubusercontent.com/8084847/29238115-3534cfc6-7f60-11e7-9a20-e90361336e2f.png)
docker-compose up redis nginx mysql
First installation error

**Comment by zuohuadong** [comment]
Internet problem
You can use  shadowsock  or vpn

**Comment by exfriend** [comment]
If you're working on multiple projects, you probably noticed that building workspace in general taske a while. So I decided to build my own base image off of workspace/Dockerfile like this:
https://github.com/exbox/workspace

And then simply 

```
FROM exbox/workspace:1
MAINTAINER exfriend <i@zlad.tk>

```
I suggest you to consider doing something like this, build it once on a good internet connection and then let docker do the rest.
