### ISSUE TITLE
Service 'mysql' failed to build on fresh install

### ISSUE THREAD

**Issue by suncoastkid** [laradock/laradock#1091]
### Info:
Docker version 1.12.6, build 78d1802
- Laradock commit: 586a225c117aa449a9840332f1979b6ccdfba2da
- System info: Linux
- System info disto/version: Ubuntu 16.04

### Issue:
Building mysql
Step 1 : ARG MYSQL_VERSION=8.0
ERROR: Service 'mysql' failed to build: Please provide a source image with `from` prior to commit

### Reproduce:
docker-compose up -d nginx mysql

**Comment by manjurulcis** [comment]
I am also facing the same issue while yesterday it was working too.
<img width="287" alt="image" src="https://user-images.githubusercontent.com/4739315/29244693-3b38baa6-7fc7-11e7-9d26-fc00d12fd4f0.png">

**Comment by manjurulcis** [comment]
Just I get it working by upgrading the docker version.

**Comment by suncoastkid** [comment]
Yep, needed to update docker and now it works:
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

**Comment by atefBB** [comment]
@shukebeta Should I use Docker CE?
