### ISSUE TITLE
Postgresql error-  could not connect to server: Connection refused

### ISSUE THREAD

**Issue by sanketraut** [laradock/laradock#1092]
### Info:
- Docker version (`$ docker --version`):  1.12.5
- Laradock commit (`$ git rev-parse HEAD`): 245ddf3441dd1b05b5a6081b9c6244aa368220a9
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

### Issue:
Whenever I run `php artisan migrate`  inside my workspace, I get an error `Could not connect to server`. The detailed error is as follows:
 [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
  could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
_____

### Expected behavior:
The database connection should be establised and the tables should get created. The success message should be displayed as `Migrations ran successfully`
_____

### Reproduce:
- Install laradock on Windows 10 using virtualbox
- Create a shared folder on vbox and mount it to the docker machine from the terminal
  - sudo mkdir mountedfolder
  - sudo mount -t vboxsf sharedfolder /mountedfolder
- Then run `docker-compose up -d nginx postgres`
- Login to the workspace `docker-compose exec workspace`
- Run `php artisan migrate`

_____

### Relevant Code:
Config sample code is as follows:
```
DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
```

**Comment by manjurulcis** [comment]
from your sample config code, DB_HOST=pgsql or 127.0.0.1

**Comment by zuohuadong** [comment]
DB_HOST=postgres 
Suggested use docker 17.3 or new

**Comment by YehuditCharaz** [comment]
hsdgfghjhkl;jhkgjfhdftyguhij;hlgkcfjgxhdfghujklkbhjvhchxgfchvjbknmlnjkhjgchfgxgfvnbhjnkljhkgjvhcf
