### ISSUE TITLE
Service 'mysql' failed to build: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by hanachan1026** [laradock/laradock#1098]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 38fb49bccc5124dfa26b92b809ea6efbd6307eba
- System info (Mac, PC, Linux): macOS Sierra 10.12.4

### Issue:

I think I followed the instruction correctly. But I get
*Service 'mysql' failed to build: Please provide a source image with `from` prior to commit*
_____

### Expected behavior:

Php-fpm, nginx, mysql and laradock-workspace should work and i see Laravel main view on ```myapp.dev:8888``` in my browser
_____

### Reproduce:

```git clone https://github.com/Laradock/laradock.git```
```cd laradock```
```docker-compose up -d workspace```
```docker exec -it laradock_workspace_1 /bin/bash```
```composer create-project laravel/laravel myapp```
```exit```
```docker-compose stop```
...changing ```docker-compose.yml``` and nginx configuration files but no touching mysql settings
```docker-compose up -d nginx mysql phpmyadmin```
_____

**Comment by springjk** [comment]
Update your docker version to 17.06-ce.

**Comment by hominglee** [comment]
springjs is right.
The Document of How to Install Docker CE:
https://fabianlee.org/2017/03/07/docker-installing-docker-ce-on-ubuntu-14-04-and-16-04/

**Comment by psgganesh** [comment]
Sometimes, networking is the root cause, two things

> 1. Allow docker to be able to make requests to hub.docker or other repo - from the front-end - generally shows up during installation
> 2. Create a valid login on hub.docker and enter the same on CLI by using 
```
docker login
```

Adding to it, if you are still finding issues on mysql 8.0, please consider using the stable build mysql 5.7 by changing the values in below files 

```
..../laradock/mysql/Dockerfile
.../laradock/env-example
```
Actually if all works, please consider to close this issue.

**Comment by atefBB** [comment]
@psgganesh 
I change MySQL version to 5.7 but the issue still occurs!
Any ideas?

**Comment by thiagorb** [comment]
Had this issue on Docker version `17.12.0-ce, build c97c6d6`, running on macOS. Solved by setting the version manually to 5.7 on `mysql/Dockerfile` *and* removing the line `ARG MYSQL_VERSION=latest`.

**Comment by mhightower** [comment]
Had this issue just come up. This Dockerfile was working and build images images a few days ago not sure what changed. I have:

     ARG TIMEZONE=America/Chicago
     ARG APACHE_DOCUMENT_ROOT=/usr/local/apache2/htdocs
     FROM composer:1.5.1 AS composer
     ...

**Comment by lhq0826** [comment]
@thiagorb 
```container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
Service 'mysql' failed to build: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"```
win 10

**Comment by bestlong** [comment]
sometime, is networking problem.

try run `docker pull mysql:latest` or `docker pull mysql:5.7` to direct download image

**Comment by xulei131401** [comment]
Service 'mysql' failed to build: Please provide a source image with `from` prior to commit

**Comment by lhq0826** [comment]
After the docker I upgrade to the latest version `18.03.0-ce` , solved the problem
