### ISSUE TITLE
mcrypt error

### ISSUE THREAD

**Issue by simongas** [LaraDock/laradock#110]
Hi hope you can help me, im using ubuntu 16.04 and im trying to run a laravel 4.2 project that I had I used git submodule add in the directory, and could get the containers working but I get the mcrypt error when I go to 127.0.0.1
Im using php7.0

**Comment by Kauhat** [comment]
Hi @simongas 

Can you double check your docker IP address using the following command, as it may be something other than `127.0.0.1`.

`ifconfig docker0 | grep 'inet' | cut -d: -f2 | awk '{ print $1}' | head -n1`

**Comment by simongas** [comment]
Thanks for answering, I will check as soon as I can. =)

**Comment by simongas** [comment]
I did it and the ip is 172.17.0.1 but the same error appears 
Mcrypt PHP extension required. 
anyone had the same issue?

**Comment by zhikiri** [comment]
Yes, mcrypt is missing.
But it's really easy to add it. You need just modify the `php-fpm/Dockerfile-XX` with mcrypt information.
You need to install the: `libmcrypt-dev` and add `RUN docker-php-ext-install mcrypt` after.

**Comment by simongas** [comment]
Thanks zhikiri, Im really new to docker, just trying it on my spare time which is very limited =/

**Comment by zhikiri** [comment]
No problem, @simongas I'm not really familiar with docker too :) 
About this issue, you can check my PR find solution there

**Comment by Mahmoudz** [comment]
#116
