### ISSUE TITLE
Step 2/10 : FROM mysql:${MYSQL_VERSION}

### ISSUE THREAD

**Issue by uniraymond** [laradock/laradock#1102]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (PC): 
- System info disto/version: 

### Issue:

ERROR: Service 'mysql' failed to build: Get https://registry-1.docker.io/v2/library/mysql/manifests/8.0: unauthorized: incorrect username or password

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by mikeerickson** [comment]
This ticket needs more information so that we can proceed with offer assistance.  If you can supply the necessary details as outlined in the issue request, we can address it easier 

In addition, if you could please supply your version of .env and docker-compose.yml that would be helpful
