### ISSUE TITLE
Service 'workspace' failed to build: One or more build-args [INSTALL V8JS]

### ISSUE THREAD

**Issue by ScottSpittle** [laradock/laradock#1103]
**###** Info:
- Docker version (`$ docker --version`): Docker version 1.12.6, build 78d1802
- Laradock commit (`$ git rev-parse HEAD`): 86a1e117f7ac1817349aa75bdbc44b1e68f62c60 
- System info (Mac, PC, Linux): Ubuntu 17.04
- System info disto/version: 

### Issue:

sudo docker-compose up -d nginx with php_version 56 give the following error:

Service 'workspace' failed to build: One or more build-args [INSTALL V8JS]

### Expected behavior:

_____
### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by mikeerickson** [comment]
Can you please upgrade your version of docker and try again

**Comment by ScottSpittle** [comment]
I'll give that a try, I ran apt-get update and apt-get install and assumed it got the latest. I'll get back to you in a bit. Thanks.

**Comment by ScottSpittle** [comment]
Great thanks! All good after updating docker.
