### ISSUE TITLE
docker-compose up -d nginx mysql and then got error message 

### ISSUE THREAD

**Issue by uniraymond** [laradock/laradock#1104]
### Info:
- Docker version (`$ docker --version`): 17.06.0-ce
- Laradock commit (`$ git rev-parse HEAD`): 38fb49bccc5124dfa26b92b809ea6efbd6307eba
- System info (Mac, PC, Linux): Windows10
- System info disto/version: 

### Issue:

docker-compose up -d nginx mysql and then got error message 
ERROR: Service 'mysql' failed to build: Get https://registry-1.docker.io/v2/library/mysql/manifests/8.0: unauthorized: incorrect username or password

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by mikeerickson** [comment]
@uniraymond Can you please provide steps necessary to reproduce.  All works on my end with a new pull, etc.

**Comment by uniraymond** [comment]
Solved, and just found have to login on the command line as well by using 'docker login'

**Comment by Khaleel** [comment]
Thanks so much @uniraymond needed this!
