### ISSUE TITLE
Mysql database is not recreated with --build --force-recreate

### ISSUE THREAD

**Issue by gustavovendramini** [laradock/laradock#1105]
### Info:
- Docker version (`$ docker --version`): Docker version 17.05.0-ce, build 89658be
- Laradock commit (`$ git rev-parse HEAD`): 38fb49bccc5124dfa26b92b809ea6efbd6307eba
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04

### Issue:

Database is not recreated with the command:
```
docker-compose up --build --force-recreate mysql
```
In my .env file:
```
MYSQL_VERSION=5.6
MYSQL_DATABASE=mydb
MYSQL_USER=myuser
MYSQL_PASSWORD=myuser123
MYSQL_PORT=3310
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```
_____

### Expected behavior:

The container recreated from scratch and database recreated
_____

### Reproduce:

Start Laradock, rename the database (MYSQL_DATABASE), and recreate the mysql container.
_____

**Comment by alchimik** [comment]
How to `docker-compose up --force-recreate` without reusing previous volumes -
 https://github.com/docker/compose/issues/2127

**Comment by onema** [comment]
I think there is an issue with any of the `5.x` versions. I consistently get the following when using any version other than 8.0:
```
> docker-compose up -d mysql

...

> docker-compose ps
      Name                   Command             State    Ports
---------------------------------------------------------------
laradock_mysql_1   docker-entrypoint.sh mysqld   Exit 1
```

**Comment by Umkus** [comment]
Might this be your case: https://github.com/docker/compose/issues/4273#issuecomment-324054392?

**Comment by mauricios** [comment]
I'm using `Docker version 18.06.1-ce, build e68fc7a` and I can use the following command to recreate anonymous volumes:

```bash
docker-compose up -d --build --force-recreate --renew-anon-volumes db
```

It seems the flag `--renew-anon-volumes` was recently added

**Comment by votanlean** [comment]
> I'm using `Docker version 18.06.1-ce, build e68fc7a` and I can use the following command to recreate anonymous volumes:
> 
> ```shell
> docker-compose up -d --build --force-recreate --renew-anon-volumes db
> ```
> 
> It seems the flag `--renew-anon-volumes` was recently added and it works to recreate volumes created in the Dockerfile of the image.

--renew-anon-volumes works like charm.
As far as I know, db service will run the .sql file in the docker-entrypoint-initdb.d folder for the first time we "docker-compose up" because the volume is not existed. From the second time, we need to use the option --renew-anon-volumes to force db service to re-run the files in docker-entrypoint-initdb.d folder
