### ISSUE TITLE
Add support for old ext-mongo.so on php 5.6

### ISSUE THREAD

**Issue by taichunmin** [laradock/laradock#1112]
### Issue:
There are two mongo module in php 5.6. 
<https://docs.mongodb.com/ecosystem/drivers/php/#language-compatibility>

My old project still use the old ext-mongo module instead of newer ext-mongodb module.
May I create a PR add support ext-mongo only for php 5.6?
I already create a commit in my fork.
<https://github.com/taichunmin/laradock/commit/a02733f4132a30f2f6037b471a5e3982add89cf8>

I found some similar issue: #254

**Comment by jourdon** [comment]
Has the problem been fixed？

**Comment by bestlong** [comment]
now php5.6 install both

https://github.com/laradock/laradock/blob/8f6923531fa39fc2c76fc187fd3273ddd3527984/php-fpm/Dockerfile#L221-L235
