### ISSUE TITLE
Elasticsearch container crashes after start 

### ISSUE THREAD

**Issue by symbios-zi** [laradock/laradock#1114]
### Info:
- Docker version (`$ docker --version`):  17.06.1-ce-mac24 (18950)
- Laradock commit (`$ git rev-parse HEAD`): c35445b066245f9b300016042dca4df3f2c314ae
- System info (Mac, PC, Linux): MacOS 
- System info disto/version: Siera 10.12.6 (16G29)
- Using d4m-nfs
### Issue:

When I try to start elasticsearch using 
`docker-compose up -d elasticsearch`
it starts and stop a few seconds later. It worked at previous version of laradock

docker logs docker logs laradock_elasticsearch_1 gives me this
https://paste.laravel.io/99a8e1bd-913f-45b2-9d65-5a39f9971c19#3

Seems like I should give permissions, but I do not know which folder?

**Comment by progsmile** [comment]
I'm having the same issue

**Comment by symbios-zi** [comment]
@progsmile I had removed all the images and volumes, updated laradock to latest version and setup it anew.

**Comment by progsmile** [comment]
@symbios-zi may be you know: Can I set less than 1gb for elasticsearch 5.* ?

**Comment by acmitch** [comment]
It is running out of memory.

```
sudo sysctl -w vm.max_map_count=262144
vim docker-compose.yml
```

Change `mem_limit` from 512m to 1g
```
mem_limit: 1g
```
Start back up. Good Luck!
```
docker-compose up -d --build elasticsearch
```

**Comment by symbios-zi** [comment]
@acmitch yeah, that's right. I have up memory like you. Sorry, for a long answer

**Comment by BalaWxd** [comment]
I am using docker for windows and entered a problem like this one: https://github.com/pires/kubernetes-elasticsearch-cluster/issues/145, after restarting the containers.

mem_limit already 1024m.

With recreated the images, the issue still exists... until I changed the named volume from elasticsearch-data to some other name, as described here: https://discuss.elastic.co/t/elastic-elasticsearch-docker-not-assigning-permissions-to-data-directory-on-run/65812/2.

Anyone knows why?? 

This don't seem to be a problem in laradock, but someone else finds this issue can also try this workaround...

**Comment by bestlong** [comment]
new version 6.6.0
```
~/Sites/laradock (master *)$ docker-compose build elasticsearch
Building elasticsearch
Step 1/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.0
6.6.0: Pulling from elasticsearch/elasticsearch
a02a4930cb5d: Pull complete
7decffa70b3b: Pull complete
498315b62345: Pull complete
c84790c95eb9: Pull complete
6a3b0a2308b2: Pull complete
33b21a7b5e00: Pull complete
f620bc30e187: Pull complete
Digest: sha256:e9cba8dec2df88a1af911787f05cf5200a5d9d64e4517f64deb8bafc6e96176f
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:6.6.0
 ---> 13aa43015aa1
Step 2/2 : EXPOSE 9200 9300
 ---> Running in d1eb9f7d0fd0
Removing intermediate container d1eb9f7d0fd0
 ---> f6d0cab8d52b
Successfully built f6d0cab8d52b
Successfully tagged laradock_elasticsearch:latest
~/Sites/laradock (master *)$ docker-compose up -d elasticsearch
Creating network "laradock_frontend" with driver "bridge"
Creating network "laradock_backend" with driver "bridge"
Creating network "laradock_default" with the default driver
Creating laradock_docker-in-docker_1 ... done
Creating laradock_workspace_1        ... done
Creating laradock_php-fpm_1          ... done
Creating laradock_elasticsearch_1    ... done
~/Sites/laradock (master *)$ docker-compose ps
           Name                          Command               State                       Ports
---------------------------------------------------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh            Up      2375/tcp
laradock_elasticsearch_1      /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
laradock_php-fpm_1            docker-php-entrypoint php-fpm    Up      9000/tcp
laradock_workspace_1          /sbin/my_init                    Up      0.0.0.0:2222->22/tcp
~/Sites/laradock (master *)$
```
