### ISSUE TITLE
docker-compose exec mysql bash  error

### ISSUE THREAD

**Issue by ljlx1120** [laradock/laradock#1118]
### Info:
- Docker version (`$ docker --version`): Docker version 17.06.1-ce, build 874a737
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  Linux
- System info disto/version: ubuntu 16.04

### Issue:

Frist I did ..docker-compose up mysql. It will show Creating laradock_mysql_1 ... done
but when I do docker-compose exec mysql bash will show
ERROR: No container found for mysql_1
then I checked docker ps, mysql is not there.
_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by exfriend** [comment]
What's the output of `docker-compose ps`?

**Comment by a-h-abid** [comment]
Also please post the logs from `docker-compose logs mysql`.
