### ISSUE TITLE
Caddy Multisite setup not working workdir in dockerfile

### ISSUE THREAD

**Issue by nguyenhaiphan** [laradock/laradock#1123]
### Info:
- Docker version (`$ docker --version`): 17.05.0-ce, build 89658be
- Laradock commit (`$ git rev-parse HEAD`): 801ccd47d22999d087896045cdfd1d7316212174
- System info (Mac, PC, Linux): Linux
- System info disto/version: Linux version 4.4.0-87-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017

### Issue:
ERROR: for caddy  Cannot start service caddy: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/var/www/public\") set in config.json failed: no such file or directory"
_____

### Expected behavior:
The caddy\Dockerfile is properly config for support multisite mode
_____

### Reproduce:
Setup project with multisite mode (APPLICATION =../, Caddyfile with config ```root /var/www/<project_folder>/public```)
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by codeitlikemiley** [comment]
bump i also facing this issue anyone have fixed or have idea how to fix this?

**Comment by nguyenhaiphan** [comment]
Check the caddy\Caddyfile, there are 2 block {}, just comment out every block that you don't need them, such as
```
# laradock.demo {
#     root /var/www/public
# }
```
and your should change the WORKDIR config in the caddy\Dockerfile like below
```
WORKDIR /var/www/<your project folder name>/public
```

Hope you can solve your problem.

**Comment by codeitlikemiley** [comment]
i had done that already, but its not workable for multisite , or separate laravel folder installed apps...
as you can see WORKDIR is only for one folder....
If i did what you said here only one site has SSL , the other one wont even load at all
i think this should be change to adopt for multisite...

**Comment by nguyenhaiphan** [comment]
The separate apps can signed many times via the caddy\Caddyfile. 

From Docker file, you can think about WORKDIR just like a CD command from shell.
```Dockerfile
WORKDIR /var/www/mailautoreply-ai-basic/public

#Almost forgot, it seems that I've changed the cmd like below
CMD ["/usr/bin/caddy", "-conf", "/etc/Caddyfile"] #<-- this one always call from root hierachy, not caring anything about workdir.
```
