### ISSUE TITLE
can't login to phpmyadmin and mysql

### ISSUE THREAD

**Issue by rachidsghir** [laradock/laradock#1127]
### Info:
- Docker version (`$ docker --version`): 17.06.2-ce, build cec0b72
- Laradock commit (`$ git rev-parse HEAD`): a1d3eeb 
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04 LTS

### Issue:
When I try login to phpmyadmin  I'v got this error : 

    2005 - Unknown MySQL server host 'mysql' (-2).

and when running `docker-compose exec mysql bash` I've got this error:

    No container found for mysql_1

_____

### Expected behavior:
- login to phpmyadmin
- loading of mysql container

**Comment by exfriend** [comment]
execute `docker-compose logs mysql` and look for [ERROR]
