### ISSUE TITLE
Laradock routing to 127.0.0.1 instead of custom domain.

### ISSUE THREAD

**Issue by de6eling** [laradock/laradock#1129]
### Info:
- Docker version  17.06.2-ce, build cec0b72
- Laradock commit: 38fb49bccc5124dfa26b92b809ea6efbd6307eba 
- System info: Linux
- System info disto/version: Ubuntu 16.04.3 LTS

### Issue:

Laravel internal routing is directing the application to local host instead of the given domain.  For example login form route ```action="{{ url('/login') }}"``` resolves to ```action="http://127.0.0.1:8889/login"``` 

Even when I don't use the ```{{ url('/login') }}``` function and instead just use ```/login``` it still routes back to ```127.0.0.1```.  Something inside of the way Laradock is configured is routing it to localhost for some reason.  

I have changed the APP_URL in the .env file.  I have changed and rebuild multiple different Apache2 and Nginx configurations to no avail.  

_____

### Expected behavior:

The route should resolve to ```action="http://MYDOMAIN.com/login"``` or simply ```action="/login"```
_____

### Reproduce:

I used the exact same laravel application without Laradock on an Apache2 server and everything routed perfectly fine.  Only when I have used Laradock has this been a problem.
_____

### Relevant Code:

Current default.apache.conf:
```
<VirtualHost *:80>
  ServerName MYDOMAIN.com
  ServerAlias www.MYDOMAIN.com
  DocumentRoot /var/www/public
  Options Indexes FollowSymLinks

  <Directory "/var/www/public">
    AllowOverride All
    <IfVersion < 2.4>
      Allow from all
    </IfVersion>
    <IfVersion >= 2.4>
      Require all granted
    </IfVersion>
  </Directory>

</VirtualHost>
```

Current nginx default.conf
```
server {

    listen 80;
    listen [::]:80 ipv6only=on;

    server_name MYDOMAIN.com;
    root /var/www/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
```

Current Laradock .env
```
### NGINX ##############################################################################################################

NGINX_HOST_HTTP_PORT=8889
NGINX_HOST_HTTPS_PORT=4443
NGINX_HOST_LOG_PATH=./logs/nginx/
NGINX_SITES_PATH=./nginx/sites/
NGINX_PHP_UPSTREAM_CONTAINER=php-fpm
NGINX_PHP_UPSTREAM_PORT=9000

### APACHE #############################################################################################################

APACHE_HOST_HTTP_PORT=80
APACHE_HOST_HTTPS_PORT=443
APACHE_HOST_LOG_PATH=./logs/apache2
APACHE_SITES_PATH=./apache2/sites
APACHE_PHP_UPSTREAM_CONTAINER=php-fpm
APACHE_PHP_UPSTREAM_PORT=9000
```

Current application .env
```
APP_ENV=local
APP_KEY=****************************************
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://MYDOMAIN.com
```

**Comment by Yangwendaxia** [comment]
You should set 
```
protected $proxies= '*';
```
in TrustProxies.php.
