### ISSUE TITLE
temp file created index.php___jb_old___

### ISSUE THREAD

**Issue by LarryEitel** [LaraDock/laradock#113]
Seems to be a recent 'issue' for me. I edit `public/index.php` with Sublime and refresh repeating twice, and then the file in workspace is truncated and no longer showing edits.

I then open the same file from PHPStorm and `public/index.php___jb_old___` is created.

What's going on?

This is a fresh laradock sitting in a php app.

**Comment by LarryEitel** [comment]
What I have tried:

1. Searched docker forum
2. Deleted and rebuilt all containers
3. Moved host source files into Users tree
4. Stopped/Restarted Docker

Behavior:

Edit `public/index.php` and add `print gethostname();`. I see this added.
If I make one more change and save, the change is not made.
I bash into `workspace` and cat the file. Only the first file edit was persisted.

THEN I open `public/index.php` in PHPStorm. I see the update that was made by Sublime. I make an edit and save and notice that `public/index.php___jb_old___` has been created.

If possible interest:
```
root@b691ae3b2b32:/var/www/laravel/public# ll
...
-rwxr-xr-x 1 root root  252 Jun 22 18:35 index.php*
-rwxr-xr-x 1 root root  231 Jun 22 18:32 index.php___jb_old___*
...
```
```
root@b691ae3b2b32:/var/www/laravel/public# cat index.php___jb_old___
cat: index.php___jb_old___: No such file or directory
```

**Comment by LarryEitel** [comment]
Update...

Fresh composer install of Laravel. Dropped Laradock in and fired it up.

Same behavior with `public/index.php`.

HOWEVER!!!!
I CAN edit/save `welcome.blade.php` multiple times with SUCCESS.

I CAN edit/save `bootstrap/app.php` multiple time with success as well.

So why am I not able to edit `public/index.php` multiple times. Actually, I have to restart containers to edit that file again.

**Comment by LarryEitel** [comment]
I discovered that I have the same problem with any .php file in `publiic/`. I added a `public/info.php` and after second edit, changes were no longer persisted to container.

Can someone please confirm whether anyone else is experiencing the same behavior?

Open `public/index.php`.
Add a print statement like `print 'hello';`, save and refresh site. See `hello`. Great.
Add another one just like it, save and refresh. See two `hello`'s? NO!!!!!!

Same thing happens when I added `info.php`.

Do you see a similar behavior?

**Comment by LarryEitel** [comment]
So in order for me to see multiple edits to a file in `public/`, I have to restart `nginx` using: `docker-compose restart nginx`.

In the interests of tracking this issue down, I also tried without success a suggestion elsewhere related to changing in `nginx/nginx.conf` from `sendfile    on;` to `sendfile    off;`.

**Comment by AminMkh** [comment]
so the issue is you are unable to edit certain files? could you post your development environment, are you using docker native on linux or toolbox, or the beta docker native for windows/mac

**Comment by LarryEitel** [comment]
Running Windows native Beta. 

I open laravel/public/index.php.
Add `print 'hello 1';`
Save.

Refresh page and see `hello 1`.
Edit same file and change to `hello 2'`
Save.

Refresh page and still see `hello 1`.

I stop/start docker-compose.
Refresh page and now see `hello 1`.

BTW, I am running a scaled down version of this repo using a repo I created: [phpdock](https://github.com/LarryEitel/phpdock) to better document a `Laradock` inspired php dev stack with PHPStorm debug configured. But I experienced the same behavior in `Laradock`.

I also just confirmed that it appears to only be files in `/public` DIR. I can repeatedly edit for example, `app/bootstrap/app.php` with no prob.

**Comment by Mahmoudz** [comment]
I'll close this old issue now, if the error still exist we'll open it back.

**Comment by LarryEitel** [comment]
I found the solution!! :)

http://stackoverflow.com/a/27449850/913295

**Comment by lechengyu** [comment]
@LarryEitel the solution works!  Thanks!
