### ISSUE TITLE
laradoc_mysql container fails to start: '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)

### ISSUE THREAD

**Issue by daniel359davidson** [laradock/laradock#1134]
### Info:
- Docker version (`$ docker --version`): 17.06.2-ce, build cec0b72
- Laradock commit (`$ git rev-parse HEAD`): 655b9a152660e5fe3148ade51f7a289fd390da94
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.04

### Issue:
laradoc_mysql fails to start:

docker log:
Initializing database
mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
2017-09-13T12:16:45.775330Z 0 [Note] Basedir set to /usr/
2017-09-13T12:16:45.775811Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
2017-09-13T12:16:45.775864Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
2017-09-13T12:16:45.777329Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
2017-09-13T12:16:45.777348Z 0 [ERROR] Aborting

chmod 777 doesn't help
_____

### Expected behavior:
Container up and running
_____

### Reproduce:
On fresh install:

docker-compose up -d mysql
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by nikolasok** [comment]
same problem..

**Comment by nikolasok** [comment]
- Docker version ($ docker --version): 17.05.0-ce, build 89658be
- Laradock commit ($ git rev-parse HEAD): 655b9a152660e5fe3148ade51f7a289fd390da94
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04.3 x64

> docker-compose up -d mysql

Then

> docker ps
```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                        NAMES


There is nothing
```

Then

> docker ps -a

```
91e7bd3e2d3f        laradock_mysql       "docker-entrypoint..."   6 minutes ago       Exited (1) 6 minutes ago                                                laradock_mysql_1

```

Then

> docker-compose logs

```
> mysql_1                | Initializing database
> mysql_1                | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
> mysql_1                | 2017-09-13T19:33:19.914251Z 0 [Note] Basedir set to /usr/
> mysql_1                | 2017-09-13T19:33:19.914501Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
> mysql_1                | 2017-09-13T19:33:19.914566Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
> mysql_1                | 2017-09-13T19:33:19.920252Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
> mysql_1                | 2017-09-13T19:33:19.920298Z 0 [ERROR] Aborting
> 
```

**Comment by daniel359davidson** [comment]
@nikolasok i found solution to this problem.

First run of the laradock creates a .laradock directory in the current user home directory, but the **directory is owned by root**, so running docker under the current user will fail.

Simply just chown .laradock directory to current user:
`sudo chown -R $USER ~/.laradock`

**Comment by henriale** [comment]
@daniel359davidson I did exactly as you but I'm still getting the same error. :(
do you have any clue of what it might be? have you run any other command than this?

**Comment by henriale** [comment]
Just found that this issue was solved [here](https://github.com/docker-library/mysql/issues/219) by @yosifkit.

You just have to add `user: "1000:50"` into `mysql` in `docker-compose.yml`.

**Comment by zetas** [comment]
This is very bizzarre, im dealing with this with one of my devs on a project. We're both running the same laradock setup (cloned from the same forked repo) and yet he is having issues getting the percona container to start, getting this error, and i am not. We both have the exact same .env file, neither of us has an existing mysql user in /etc/passwd on our macs and yet mine starts and his doesn't. 

By default it creates the data directory in the users home dir ~/.laradock so what @daniel359davidson suggested doesn't seem to be an actual fix. Unless you ran the docker-compose as a root or something (why would you) the .laradock folder would already be owned by the user, and indeed it is on both our systems. It's marked as user:staff on every folder on both systems. 

I'm trying to find the actual problem here as I need to have a reliable laradock setup for all my developers. I can't start baking in work-arounds for peoples environments. I want to find the root cause and fix it.

**Comment by spzorn123** [comment]
> Just found that this issue was solved [here](https://github.com/docker-library/mysql/issues/219) by @yosifkit.
> 
> You just have to add `user: "1000:50"` into `mysql` in `docker-compose.yml`.

Can you show me where you added this in the file?
thank you
