### ISSUE TITLE
 mkdir /tmp/pty117853616: permission denied

### ISSUE THREAD

**Issue by shupan** [laradock/laradock#1135]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  MAC
- System info disto/version: 

### Issue:

_____
 docker-compose exec mysql bash

### Expected behavior:

_____
Not error info

### Reproduce:

_____
docker-compose exec mysql bash
rpc error: code = 2 desc = shim error: mkdir /tmp/pty117853616: permission denied

 ll /tmp
lrwxr-xr-x@ 1 root  wheel    11B Feb 18  2017 /tmp -> private/tmp

### Relevant Code:

```
// place a code sample here
```

**Comment by migueloop** [comment]
Same problem here on OSX

**Comment by migueloop** [comment]
I fixed the problem on OSX by going to preferences and removing /tmp file in File Sharing tab

![image](https://user-images.githubusercontent.com/409981/31931076-47d93c7c-b8a2-11e7-8f41-b7e3fa1c2fe8.png)

**Comment by sachinruk** [comment]
In the newer UI it looks like this: 
![image](https://user-images.githubusercontent.com/1410927/135398235-1f2b9655-696e-4b37-88b8-c6094e04b6d0.png)
