### ISSUE TITLE
laradock_mysql_1 exited with code 1

### ISSUE THREAD

**Issue by medz** [laradock/laradock#1138]
### Info:
- Docker version (`$ docker --version`): 17.06.2-ce
- Laradock commit (`$ git rev-parse HEAD`): 655b9a152660e5fe3148ade51f7a289fd390da94
- System info (Mac, PC, Linux): Linux
- System info disto/version: ContOS 7

### Issue:

_____
Such as title
### Expected behavior:

_____

### Reproduce:

_____
I don't know.
### Relevant Code:

```
[root@izwz9ae97zwl4jkhado19vz laradock]# docker-compose up mysql
Recreating laradock_mysql_1 ...
Recreating laradock_mysql_1 ... done
Attaching to laradock_mysql_1
mysql_1                | 2017-09-15T07:57:38.879109Z 0 [Note] Basedir set to /usr/
mysql_1                | 2017-09-15T07:57:38.879314Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
mysql_1                | 2017-09-15T07:57:38.879352Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql_1                | 2017-09-15T07:57:38.879381Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
mysql_1                | 2017-09-15T07:57:38.879414Z 0 [Note] /usr/sbin/mysqld (mysqld 8.0.2-dmr) starting as process 1 ...
mysql_1                | 2017-09-15T07:57:38.881850Z 0 [Warning] Can't create test file /var/lib/mysql/281ff12c207c.lower-test
mysql_1                | 2017-09-15T07:57:38.881862Z 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mysql_1                | 2017-09-15T07:57:38.905820Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1                | 2017-09-15T07:57:38.905985Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1                | 2017-09-15T07:57:38.928540Z 1 [ERROR] Failed to find valid data directory.
mysql_1                | 2017-09-15T07:57:38.928696Z 0 [ERROR] Data Dictionary initialization failed.
mysql_1                | 2017-09-15T07:57:38.928712Z 0 [ERROR] Aborting
mysql_1                | 2017-09-15T07:57:38.928856Z 0 [Note] Binlog end
mysql_1                | 2017-09-15T07:57:38.929055Z 0 [Note] Shutting down plugin 'InnoDB'
mysql_1                | 2017-09-15T07:57:38.929154Z 0 [Note] Shutting down plugin 'MyISAM'
mysql_1                | 2017-09-15T07:57:38.929162Z 0 [Note] Shutting down plugin 'CSV'
mysql_1                | 2017-09-15T07:57:38.929619Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
mysql_1                |
laradock_mysql_1 exited with code 1
```

**Comment by luciano-jr** [comment]
What you have in your DATA_SAVE_PATH variable in .env file?

**Comment by medz** [comment]
@luciano-jr `DATA_SAVE_PATH=~/.laradock/data`

I do not think there is a problem with this configuration before I upgraded Laravel
  MySQL is 5.7 version, but after upgrading to 655b9a152660e5fe3148ade51f7a289fd390da94 after the MySQL version has become the 8 version, and in the `.env` file to modify the version configuration is invalid, I think it is willing to cause MySQL can not do.

**Comment by medz** [comment]
My upgrade reference: http: //laradock.io/documentation/#upgradinging-laradock

**Comment by sasokovacic** [comment]
same problem here. If I install latest laradock and leave everything default it runs but it does not create any database...
Here is the output

> Starting laradock_mysql_1
Attaching to laradock_mysql_1
mysql_1                | 2017-09-29T18:47:00.385928Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1                | 2017-09-29T18:47:00.385974Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql_1                | 2017-09-29T18:47:00.385996Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
mysql_1                | 2017-09-29T18:47:00.386023Z 0 [Note] mysqld (mysqld 8.0.1-dmr) starting as process 1 ...
mysql_1                | 2017-09-29T18:47:00.390780Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1                | 2017-09-29T18:47:00.390860Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1                | 2017-09-29T18:47:00.391552Z 1 [Note] InnoDB: PUNCH HOLE support available
mysql_1                | 2017-09-29T18:47:00.391575Z 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1                | 2017-09-29T18:47:00.391580Z 1 [Note] InnoDB: Uses event mutexes
mysql_1                | 2017-09-29T18:47:00.391584Z 1 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1                | 2017-09-29T18:47:00.391588Z 1 [Note] InnoDB: Compressed tables use zlib 1.2.3
mysql_1                | 2017-09-29T18:47:00.391839Z 1 [Note] InnoDB: Number of pools: 1
mysql_1                | 2017-09-29T18:47:00.391930Z 1 [Note] InnoDB: Using CPU crc32 instructions
mysql_1                | 2017-09-29T18:47:00.393402Z 1 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1                | mbind: Operation not permitted
mysql_1                | mbind: Operation not permitted
mysql_1                | mbind: Operation not permitted
mysql_1                | mbind: Operation not permitted
mysql_1                | 2017-09-29T18:47:00.399654Z 1 [Note] InnoDB: Completed initialization of buffer pool
mysql_1                | 2017-09-29T18:47:00.401053Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1                | 2017-09-29T18:47:00.431780Z 1 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1                | 2017-09-29T18:47:00.431868Z 1 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1                | 2017-09-29T18:47:00.482526Z 1 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1                | 2017-09-29T18:47:00.483284Z 1 [Note] InnoDB: 32 rollback segment(s) are active in the temporary tablespace.
mysql_1                | 2017-09-29T18:47:00.483598Z 1 [Note] InnoDB: 8.0.1 started; log sequence number 67976367
mysql_1                | 2017-09-29T18:47:00.485106Z 1 [Note] InnoDB: Waiting for purge to start
mysql_1                | 2017-09-29T18:47:00.535442Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1                | 2017-09-29T18:47:00.536326Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170929 18:47:00
mysql_1                | 2017-09-29T18:47:00.582710Z 1 [Note] Found data dictionary with version 1
mysql_1                | 2017-09-29T18:47:00.584940Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1                | 2017-09-29T18:47:00.585133Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1                | 2017-09-29T18:47:00.586555Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1                | 2017-09-29T18:47:00.586580Z 0 [Note] IPv6 is available.
mysql_1                | 2017-09-29T18:47:00.586587Z 0 [Note]   - '::' resolves to '::';
mysql_1                | 2017-09-29T18:47:00.586613Z 0 [Note] Server socket created on IP: '::'.
mysql_1                | 2017-09-29T18:47:00.593951Z 0 [ERROR] Table 'mysql.component' doesn't exist
mysql_1                | 2017-09-29T18:47:00.593994Z 0 [ERROR] The mysql.component table is missing or has an incorrect definition.
mysql_1                | 2017-09-29T18:47:00.597193Z 0 [Warning] ACL table mysql.'user' must use supported storage engine
mysql_1                | 2017-09-29T18:47:00.597206Z 0 [Warning] ACL table mysql.'db' must use supported storage engine
mysql_1                | 2017-09-29T18:47:00.597220Z 0 [Warning] ACL table mysql.'proxies_priv' must use supported storage engine
mysql_1                | 2017-09-29T18:47:00.597221Z 0 [Warning] ACL table mysql.'tables_priv' must use supported storage engine
mysql_1                | 2017-09-29T18:47:00.597223Z 0 [Warning] ACL table mysql.'columns_priv' must use supported storage engine
mysql_1                | 2017-09-29T18:47:00.597224Z 0 [Warning] ACL table mysql.'procs_priv' must use supported storage engine
mysql_1                | 2017-09-29T18:47:00.597252Z 0 [ERROR] mysqld: Column count of mysql.user is wrong. Expected 47, found 45. The table is probably corrupted
mysql_1                | 2017-09-29T18:47:00.597494Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_1                | 2017-09-29T18:47:00.597513Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1                | 2017-09-29T18:47:00.597544Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1                | 2017-09-29T18:47:00.597559Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1                | 2017-09-29T18:47:00.597565Z 0 [ERROR] Missing system table mysql.global_grants; please run mysql_upgrade to create it
mysql_1                | 2017-09-29T18:47:00.597700Z 0 [Warning] Could not load mysql.role_edges and mysql.default_roles tables. ACL DDLs will not work unless mysql_upgrade is executed.
mysql_1                | 2017-09-29T18:47:00.602202Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1                | 2017-09-29T18:47:00.603138Z 0 [Warning] System table 'func' is expected to be transactional.
mysql_1                | 2017-09-29T18:47:00.609780Z 0 [ERROR] Incorrect definition of table performance_schema.setup_actors: expected column 'ROLE' at position 2 to have type char(32), found type char(16).
mysql_1                | 2017-09-29T18:47:00.618478Z 0 [ERROR] Column count of performance_schema.events_statements_summary_by_digest is wrong. Expected 32, found 29. The table is probably corrupted
mysql_1                | 2017-09-29T18:47:00.619384Z 0 [ERROR] Native table 'performance_schema'.'events_statements_histogram_global' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.619601Z 0 [ERROR] Native table 'performance_schema'.'events_statements_histogram_by_digest' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.624034Z 0 [ERROR] Native table 'performance_schema'.'events_errors_summary_by_user_by_error' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.624160Z 0 [ERROR] Native table 'performance_schema'.'events_errors_summary_by_host_by_error' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.624298Z 0 [ERROR] Native table 'performance_schema'.'events_errors_summary_by_account_by_error' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.624396Z 0 [ERROR] Native table 'performance_schema'.'events_errors_summary_by_thread_by_error' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.624515Z 0 [ERROR] Native table 'performance_schema'.'events_errors_summary_global_by_error' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.628294Z 0 [ERROR] Native table 'performance_schema'.'data_locks' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.628500Z 0 [ERROR] Native table 'performance_schema'.'data_lock_waits' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.629624Z 0 [ERROR] Column count of performance_schema.replication_connection_status is wrong. Expected 20, found 11. The table is probably corrupted
mysql_1                | 2017-09-29T18:47:00.630471Z 0 [ERROR] Column count of performance_schema.replication_applier_status_by_coordinator is wrong. Expected 15, found 6. The table is probably corrupted
mysql_1                | 2017-09-29T18:47:00.630858Z 0 [ERROR] Column count of performance_schema.replication_applier_status_by_worker is wrong. Expected 16, found 8. The table is probably corrupted
mysql_1                | 2017-09-29T18:47:00.631243Z 0 [ERROR] Native table 'performance_schema'.'replication_applier_filters' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.631372Z 0 [ERROR] Native table 'performance_schema'.'replication_applier_global_filters' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.634042Z 0 [ERROR] Native table 'performance_schema'.'variables_info' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.634174Z 0 [ERROR] Native table 'performance_schema'.'persisted_variables' has the wrong structure
mysql_1                | 2017-09-29T18:47:00.635408Z 0 [Note] mysqld: ready for connections.
mysql_1                | Version: '8.0.1-dmr'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping laradock_mysql_1 ... done

if I change anything in the .env file (e.g. version from 8.0 to 5.7) and rebuild I get the same as @medz

**Comment by medz** [comment]
I think, should give a 5.7 change mysql to 8.0 after a remedy.

**Comment by b1nj** [comment]
I have the same problem with a fresh laradock version when i switch mysql to 5.7.

**Comment by sasokovacic** [comment]
ok for me the problem was old databases from existing projects... I changed DATA_SAVE_PATH in the .env file from 

> DATA_SAVE_PATH=~/.laradock/data

to 

> DATA_SAVE_PATH=~/.laradock/finance/data

for this specific project and now everything works... It seems like when you "up" mysql container it loads all the databases from all the projects and if you have some mysql 5.6 databases it fails because of breaking changes in mysql 5.7 (more strict rules...)

**Comment by b1nj** [comment]
thank sasokovacic. I delete .laradock/data and now it's ok.

**Comment by eleftrik** [comment]
I had the same problem. Same fix as @sasokovacic suggested, but the key in .env file now is _DATA_PATH_HOST_

**Comment by godbout** [comment]
Confirming here. Same issue. I run different projects with their own laradock. The laradock folder name for each project is different and the COMPOSE_PROJECT_NAME variable too, but still it fails if some projects use mysql 5.5 and others 5.7.

**Comment by huypx-nfq** [comment]
In my case, i crash to mariadb data in `~/.laradock/data/mariadb` so solution is remove or rename data folder and restart laradock

Ref: https://devhoi.com/threads/laradock-on-mac-error-unknown-unsupported-storage-engine-innodb.28/
