### ISSUE TITLE
nginx aliyun.com repositories hang during build

### ISSUE THREAD

**Issue by kevindessely** [laradock/laradock#1139]
https://github.com/laradock/laradock/blob/ae048e6c661035ff0066e00b64a2cdc689eb3432/nginx/Dockerfile#L11

Hang forever during build on DigitalOcean servers, after commenting out this line work flawlessly. Can someone confirm this too for `mirrors.aliyun.com` ?

**Comment by danielkullik** [comment]
Same here. Running `docker-compose up -d nginx mysql' results in an endless download of `http://mirrors.aliyun.com/alpine/v3.5/main/x86_64/APKINDEX.tar.gz'. Running on a bare-metal Debian 9.1 server.

**Comment by alenn-m** [comment]
Same here

**Comment by rssawhney** [comment]
same here, but works after commenting line

**Comment by neliseev** [comment]
Same here, works on local MBP, but on CI agent stuck...I think issue in memory limits, agent have only 4gb RAM and APK using memory based installation (directly to ram), so maybe this issue?

**Comment by vjekoslav** [comment]
Same here. It seems that [mirrors.aliyun.com](http://mirrors.aliyun.com) does not respond. It seems to work with original repos, so commenting that line out fixes it, so probably mirrors fix is no longer needed. 

I guess that it works some people due to docker layer caching. 

Here is my [PR](https://github.com/laradock/laradock/pull/1145) for it.

**Comment by cheelahim** [comment]
#749

**Comment by mouyong** [comment]
抱歉，可能给你们带来了一些麻烦，我并不知道在 中国以外的服务器对 阿里 mirrors 能否进行响应，但是，我认为，这个应该交友使用者在 .env 文件中进行配置。当他在中国的范围内，应该使用 sed 进行换源，如果非中国范围（例如在非中国服务器上），就跳过使用 sed 命令。这样才应该是更好的选择。我朋友和我说他使用最新版的 laradock build nginx 出现 apk add --no-cache bash 报错。后来切换到旧版的 laradock 后，build nginx 成功工作了。所以我认为应该这样处理。

**Comment by mouyong** [comment]
还有个问题是，某些版本之下的 alpine 中，某个 tar.xz 归档文件将会无法下载，所以。更换 alpine 的 源 也许是个比较好的选择，在中国内，可以更换为 阿里 的 ，在非中国地区，如果官方源无法下载，大家有比较好的源，也可以提供出来，告知其他使用者。

**Comment by nilsenj** [comment]
the new fix doesn't work for me in Ukraine!
just hang on 
Building nginx
Step 1/10 : FROM nginx:alpine
 ---> 21a2450d623e
Step 2/10 : MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
 ---> Using cache
 ---> 43397aea6468
Step 3/10 : ADD nginx.conf /etc/nginx/
 ---> Using cache
 ---> c807c78322ea
Step 4/10 : ARG PHP_UPSTREAM_CONTAINER=php-fpm
 ---> Using cache
 ---> 650ade4a8aa9
Step 5/10 : ARG PHP_UPSTREAM_PORT=9000
 ---> Using cache
 ---> cb9c4733fd42
Step 6/10 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories
 ---> Using cache
 ---> 24ba8436497a
Step 7/10 : RUN apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data
 ---> Running in 06749a342b52
fetch http://mirrors.aliyun.com/alpine/v3.5/main/x86_64/APKINDEX.tar.gz


and hangs forever(

**Comment by vjekoslav** [comment]
> Step 6/10 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories

If you had correct version you would not have this step. You didn't pull or something else is wrong. Try cloning a new repo from beginning.

**Comment by mouyong** [comment]
@vjekoslav 我不是特别同意你的观点。也许你我的环境不同。你不知道我们不进行换源处理需要多么的耗时。https://laravel-china.org/articles/6731/laradock-nginx-uses-domestic-sources#reply1 ，并且，这一步是对某些环境下才需要的。

**Comment by mouyong** [comment]
@vjekoslav  
This is issue in the past:
 https://github.com/laradock/laradock/issues/397

In version 3.4 of apline, there is a file that cannot be downloaded from the default source, but this file is an index file and is indispensable. Index file is

Http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz

Now maybe this problem has been repaired. But the developers in china. It takes a long time to build the environment.
