### ISSUE TITLE
Imagick script not even loading on WAMP

### ISSUE THREAD

**Issue by tharindulucky** [laradock/laradock#1143]
I successfully installed Imagick on WAMP and everything looks fine. However when I run this PHP Imagick script, nothing happens but this default error page comes up.

```
try
{
    $image = 'image.jpg';

    $im = new Imagick($image);

    echo 'Imagick';
}
catch(Exception $e)
{
    echo $e->getMessage();
}
```
![capture](https://user-images.githubusercontent.com/15250118/30627003-45b5f27c-9deb-11e7-9ffb-91a792b8967f.PNG)

However, I realized that this error only happens when I pass the argument when creating the Imagick object.

If I create Imagick object without the arguments, it works fine.

`$im = new Imagick();`
So, that's the problem. I can't find any errors since this doesn't give any error message.

This is my phpinfo() page and see how imagick configuration

![capture2](https://user-images.githubusercontent.com/15250118/30627023-58ff432e-9deb-11e7-893c-fd82a917b56e.PNG)

Any help would be much appreciated.

**Comment by samthomson** [comment]
Why did you install it on wamp, aren't you running your project in docker?
