### ISSUE TITLE
Call to undefined function geoip_country_code_by_name() 

### ISSUE THREAD

**Issue by itelmenko** [laradock/laradock#1144]
### Info:
- Docker version (`$ docker --version`): 17.06.1-ce, build 874a737
- Laradock commit (`$ git rev-parse HEAD`): 8485add87a42120e6d53b5053efa4489593fe166
- System info (Mac, PC, Linux): Linux
- System info disto/version: Linux Mint 18.2 Sonya 

### Issue:
In my application I use function geoip_country_code_by_name()
But I have error:
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\Http\Controllers\geoip_country_code_by_name() 

Look like php-geoip module was not installed in image.
_____

### Expected behavior:
geoip_country_code_by_name() must be work
_____

### Reproduce:
Just call geoip_country_code_by_name() in any controller
_____

### Relevant Code:

```
$ip = $request->ip(); // For example, '5.44.32.1'
$isoCode = geoip_country_code_by_name($ip);
```

**Comment by shov** [comment]
Have got same problem

**Comment by elgrim312** [comment]
I've got same problem

**Comment by itelmenko** [comment]
I have fixed it

In `~/projects/laradock/php-fpm/Dockerfile` we need add

```
RUN apt-get install -y geoip-database libgeoip-dev && \
	  pecl install geoip-beta && \
	  docker-php-ext-enable geoip
```

Then rebuild php-fpm container
```
docker-compose build php-fpm 
```

Now you can run docker-compose... and then try
```
docker-compose exec php-fpm bash -c 'php -m | grep geo'
```
You will see `geoip` string.

If you need it also in workspace container you need add it to this container also.

I can do pull request for this feature with variables like `INSTALL_GEOIP` for `.env`.
But I am not sure that this is popular case to use geoip in laradock.
May be we need just do something like this
```php
if(function_exists('geoip_country_code_by_name')) {
// use it
} else {
// use a default value
}
```

What do you think about it?
