### ISSUE TITLE
How To Issue Certificate With Certbot Together with NGINX

### ISSUE THREAD

**Issue by codeitlikemiley** [laradock/laradock#1146]
Has Anybody had a Successful Usage of Certbot and Nginx for Multiple SSL Sites?
Right Now there are so many new Containers and Sadly its not Documented How to Use it...
OR Any Use Cases Specially for Production Deployment .

**Comment by JIFT** [comment]
The same please!

**Comment by abstractk** [comment]
+1

**Comment by ronydebnath** [comment]
+1

**Comment by mattogodoy** [comment]
+1

**Comment by carlosqueiroz** [comment]
+1

**Comment by HamzaDevz** [comment]
+1

**Comment by arcarruda** [comment]
Follow the sequence:

1 - Edit the laradock/nginx/sites/default.conf 
a - root /var/www/public; to root /var/www;

2 - Edit the laradock/docker-compose.yml
a - Add nginx volumes:
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt

2 - docker-compose up -d nginx

3 - docker-compose up -d certbot
***** Important: run certbot after nginx

4 - docker-compose logs certbot
- Congratulations!

**Comment by burakc** [comment]
> Follow the sequence:
> 
> 1 - Edit the laradock/nginx/sites/default.conf
> a - root /var/www/public; to root /var/www;
> 
> 2 - Edit the laradock/docker-compose.yml
> a - Add nginx volumes:
> - ./data/certbot/certs/:/var/certs
> - ./certbot/letsencrypt/:/var/www/letsencrypt
> 
> 2 - docker-compose up -d nginx
> 
> 3 - docker-compose up -d certbot
> ***** Important: run certbot after nginx
> 
> 4 - docker-compose logs certbot
> 
> * Congratulations!

ttaching to laradock_certbot_1
certbot_1              | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1              | Plugins selected: Authenticator webroot, Installer None
certbot_1              | Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
certbot_1              | Obtaining a new certificate
certbot_1              | Performing the following challenges:
certbot_1              | http-01 challenge for docker.domain.com
certbot_1              | Using the webroot path /var/www/letsencrypt for all unmatched domains.
certbot_1              | Waiting for verification...
certbot_1              | Cleaning up challenges
certbot_1              | IMPORTANT NOTES:
certbot_1              |  - Congratulations! Your certificate and chain have been saved at:
certbot_1              |    /etc/letsencrypt/live/docker.yourdomain.com/fullchain.pem
certbot_1              |    Your key file has been saved at:
certbot_1              |    /etc/letsencrypt/live/docker.yourdomain.com/privkey.pem
certbot_1              |    Your cert will expire on 2020-04-25. To obtain a new or tweaked
certbot_1              |    version of this certificate in the future, simply run certbot
certbot_1              |    again. To non-interactively renew *all* of your certificates, run
certbot_1              |    "certbot renew"
certbot_1              |  - Your account credentials have been saved in your Certbot
certbot_1              |    configuration directory at /etc/letsencrypt. You should make a
certbot_1              |    secure backup of this folder now. This configuration directory will
certbot_1              |    also contain certificates and private keys obtained by Certbot so
certbot_1              |    making regular backups of this folder is ideal.
certbot_1              |  - If you like Certbot, please consider supporting our work by:
certbot_1              | 
certbot_1              |    Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
certbot_1              |    Donating to EFF:                    https://eff.org/donate-le
certbot_1              | 

Check the log then:
correct this file with:

nano laradock/nginx/sites/default.conf

    listen 80;
    listen [::]:80;
    # For https
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    ssl_certificate /var/certs/cert1.pem;
    ssl_certificate_key /var/certs/privkey1.pem;
    server_name docker.yourdomain.com;
    root /var/www;
    index index.php index.html index.htm;
    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }
    location /pma {
        try_files $uri $uri/ /pma/index.php?$args;
    }
    location /project1 {
        try_files $uri $uri/ /project1/index.php?$args;
    }
    location /project2 {
        try_files $uri $uri/ /project2/index.php?$args;
    }

**Comment by Whosc** [comment]
> Follow the sequence:
> 
> 1 - Edit the laradock/nginx/sites/default.conf
> a - root /var/www/public; to root /var/www;
> 
> 2 - Edit the laradock/docker-compose.yml
> a - Add nginx volumes:
> - ./data/certbot/certs/:/var/certs
> - ./certbot/letsencrypt/:/var/www/letsencrypt
> 
> 2 - docker-compose up -d nginx
> 
> 3 - docker-compose up -d certbot
> ***** Important: run certbot after nginx
> 
> 4 - docker-compose logs certbot
> 
> * Congratulations!

Hi,it still not work for me ,please help me out ,thx !

![image](https://user-images.githubusercontent.com/16221204/79840852-16b80a00-83e9-11ea-8199-3e66b3dfafa2.png)

![image](https://user-images.githubusercontent.com/16221204/79840888-22a3cc00-83e9-11ea-8aa8-2e14637361b5.png)


![image](https://user-images.githubusercontent.com/16221204/79840951-3cddaa00-83e9-11ea-8c4c-ae34a54fc422.png)

**Comment by vjdavid** [comment]
@Whosc looks like your file have commented the lines of the SSL configuration and port 443, that lines should be without the `#`
