### ISSUE TITLE
dinghy use thd port 443 and 80, so nginx service will not start 

### ISSUE THREAD

**Issue by gfd6th** [laradock/laradock#1149]
### Info:
- Docker version (`$ docker --version`): Docker version 17.06.0-ce, build 02c1d87
- Laradock commit (`$ git rev-parse HEAD`): 53b7f75
- System info (Mac, PC, Linux): Mac
- System info disto/version: 12.12.6

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by NickToony** [comment]
Specific error message:

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (f52fbd0008270eabb0b6375119264fcc19d8dce0bc5a6aa93433ada054aaae5c): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

**Comment by NickToony** [comment]
As a workaround:

1. Shut down dinghy if it's running (`dinghy halt`)
2. Edit the dinghy config, ~/.dinghy/preferences.yml, and change proxy_disable to true
3. Save and boot dinghy back up (`dinghy up`)
4. Boot up laradock the normal way

Your laradock app will be available at http://web.myapp.docker/.

This is a good enough solution for me currently, though maybe someone can figure out a proper fix.

**Comment by idflood** [comment]
I confirm this is still an issue, also visible when using apache2 instead of nginx. I didn't find a solution yet and I am also wondering how to connect from host to mysql for instance. With sequel pro I can connect to `127.0.0.1:3306` when not using dinghy, but with it it doesn't work with the same host/port.

**Comment by idflood** [comment]
So I've finally been playing with docker native NFS support on osx following this guide https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc . And I have to say that I've seen a massive performance boost and this new method is "easier" to setup. 

I think that the documentation could be updated to at least mention this possibility and provide instructions about how to setup this. I will try to fork the laradock repository to have a diff of the changes made to the .env (local) and docker-compose file.

**Comment by idflood** [comment]
So here is the fork with the changes required on homestead to use NFS volume: https://github.com/idflood/laradock/commit/cad44b583d89360b4c73156f5647e3aa4da2726e

Note that you also need to run the script from https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc to setup nfs file sharing correctly.
