### ISSUE TITLE
install new relic

### ISSUE THREAD

**Issue by od3n** [laradock/laradock#1155]
anyone install newrelic on your server? how do you do it?

**Comment by khromov** [comment]
Also wondering...

**Comment by Shadow2004** [comment]
Yes I have and I will explain in my next post as it will take me a little bit to write it :-)

**Comment by Shadow2004** [comment]
Ok so to start the system monitoring tool needs to be installed on your base machine as this will monitor the docker instances as well so go ahead and follow the new relic docs for that one. Small note the new relic server monitoring tool is being removed soon so if you have a paid account go ahead an install the infrastructure stuff instead.

For APM you will want to first edit you php-fpm Dockerfile-{VERSION} file and insert the below code in just above the final touch section.

```bash
# install newrelic apm agent
ENV NEWRELIC_FILENAME=newrelic-php5-7.4.0.198-linux-musl.tar.gz
ENV ENVIRONMENT {APP NAME GOES HERE}
ENV NR_INSTALL_SILENT true
ENV NR_INSTALL_KEY {LICENCE KEY GOES HERE}

RUN cd /opt \
    && apt-get install -y wget --no-install-recommends \
	&& wget -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - \
	&& sh -c 'echo "deb http://apt.newrelic.com/debian/ newrelic non-free" > /etc/apt/sources.list.d/newrelic.list' \
	&& apt-get update \
	&& apt-get install -y newrelic-php5 --no-install-recommends \
	&& newrelic-install install
```
Then rebuild you nginx container and new relic should be installed and monitoring. 

If you have multiple site running then you will want to edit you nginx site config and add the code below into each of the location ~ \.php$ sections for each site
```bash
fastcgi_param PHP_VALUE "newrelic.appname={SITE NAME}";
```

**Comment by aconital** [comment]
@Shadow2004 when I run your script in my php-fpm dockerfile I get this error:
`Cannot write to '-' (Broken pipe).` . Any Idea why?

**Comment by shapito27** [comment]
> @Shadow2004 when I run your script in my php-fpm dockerfile I get this error:
> `Cannot write to '-' (Broken pipe).` . Any Idea why?

I've faced with same problem. Fixed by adding:
`apt-get install -y apt-transport-https gnupg`


 ```
   apt-get install -y wget --no-install-recommends \
    && apt-get install -y apt-transport-https gnupg \
	&& sh -c 'echo "deb http://apt.newrelic.com/debian/ newrelic non-free" > /etc/apt/sources.list.d/newrelic.list' \
	&& wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add - \
	&& apt-get update \
	&& apt-get install -y newrelic-php5 --no-install-recommends \
	&& newrelic-install install \
```
