### ISSUE TITLE
Service 'aws' failed to build

### ISSUE THREAD

**Issue by mruzekw** [laradock/laradock#1156]
### Info:
- Docker version (`$ docker --version`): 17.06.2-ce, build cec0b72
- Laradock commit (`$ git rev-parse HEAD`): c0e823b8d254b9b94b73120e64e9533af49d8cff
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.12.6 (16G29)

### Issue:

Build fails.
_____

### Expected behavior:

A running install.
_____

### Reproduce:

`docker-compose build --no-cache`
_____

### Relevant Code:

```
Step 6/8 : COPY /ssh_keys/. /root/.ssh/
ERROR: Service 'aws' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder601749834/ssh_keys: no such file or directory
```

**Comment by marabesi** [comment]
Same here, is there a way to disable AWS?

**Comment by marabesi** [comment]
As a temporary solution I commented out the failing lines:

Original file:
```
FROM python:slim

MAINTAINER melchabcede@gmail.com

RUN pip install --upgrade --no-cache-dir awsebcli
RUN apt-get -yqq update && apt-get -yqq install git-all

#NOTE: make sure ssh keys are added to ssh_keys folder

RUN mkdir root/tmp_ssh
COPY /ssh_keys/. /root/.ssh/
RUN cd /root/.ssh && chmod 600 * && chmod 644 *.pub

# Set default work directory
WORKDIR /var/www
```

Commented file:

```
As a temporary solution I commented out the failing lines:

```
FROM python:slim

MAINTAINER melchabcede@gmail.com

RUN pip install --upgrade --no-cache-dir awsebcli
RUN apt-get -yqq update && apt-get -yqq install git-all

#NOTE: make sure ssh keys are added to ssh_keys folder

RUN mkdir root/tmp_ssh
# COPY /ssh_keys/. /root/.ssh/
# RUN cd /root/.ssh && chmod 600 * && chmod 644 *.pub

# Set default work directory
WORKDIR /var/www

```
```

**Comment by acmitch** [comment]
Tmp fix:

```
mkdir aws/ssh_keys/
touch aws/ssh_keys/id_rsa.pub
docker-compose build --no-cache
```

**Comment by rickkuilman** [comment]
Thanks for the fix! It is still an issue though (Ubuntu 17.10)

**Comment by LarsZondag** [comment]
Has there been an update yet? I'm running into the same problem.

**Comment by mruzekw** [comment]
@LarsZondag I moved on to [Vessel](https://vessel.shippingdocker.com/). It has what I need and it's easier to modify for my needs.

**Comment by cannect** [comment]
Stumbled upon the same error today. I now just run `docker-compose up -d nginx mysql` to not to load everything.

**Comment by whoisryosuke** [comment]
Docker version: 18.03.0-ce-mac59 (23608)
Laradock commit: 164069c2562bc67945b70f88ee1502b820c8698d
MacOS 10.13.4

Had this issue today. Project was working great for months, then I added Laradock to another project, came back to this one, and started getting this error.

Tried rebuilding, rebuilding with `--no-cache`, only calling specific services (`nginx mysql`), etc -- nothing worked. Rebuilding every time would result in the error about AWS:

```
ERROR: Service 'aws' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder463720578/ssh_keys: no such file ordirectory
```

Trying to run the server results in an error about the application failing (mysql runs, nginx fails):
```
Cannot start service applications: b'network 6b6e69c472bf1091a3809680f3c954ed5639851fe9b0eb0e6862df54ebae4cbb not found'
```

I tried commenting out the code as @marabesi suggested, as well as creating the directory as @acmitch suggested. Ran the rebuild. Still getting errors.

```
Ryos-iMac:laradock ryo$ docker-compose up -d nginx mysql redis elasticsearch
Recreating laradock_mysql_1 ...
Recreating laradock_redis_1 ...
Starting laradock_applications_1 ... error
Recreating laradock_mysql_1      ... done
Recreating laradock_redis_1      ... doneb0e6862df54ebae4cbb not found'

ERROR: for applications  Cannot start service applications: b'network 6b6e69c472bf1091a3809680f3c954ed5639851fe9b0eb0e6862df54ebae4cbb not found'
ERROR: Encountered errors while bringing up the project.
```

Not sure what I can do beyond deleting the entire Laradock folder and trying from scratch. The errors are pretty cryptic.

**Comment by whoisryosuke** [comment]
Just wanted to update this by adding that I was able to resolve the issue by updating my project to the latest version of Laradock, and specifying different local folders for storage (that /~User/laradock/.data/ folder) in the ENV. I was a whole version behind, before those ENV configs existed.

**Comment by denissceluiko** [comment]
If relevant to anyone ending up here who is just rebuildind their Laradock without an explicit need for AWS.
Just run: `docker compose build nginx mysql workspace` if you need more services just add them as additional arguments.

Instead of using `docker compose build` without specifying services. That will attemt to build everything, including AWS.
