### ISSUE TITLE
dinghy could not start redis service

### ISSUE THREAD

**Issue by gfd6th** [laradock/laradock#1159]
docker-compose logs redis
```
redis_1                | chown: changing ownership of './dump.rdb': Operation not permitted
redis_1                | chown: changing ownership of '.': Operation not permitted

```

**Comment by erikstorli** [comment]
Did the same as here: https://github.com/laradock/laradock/issues/1007#issuecomment-310883173

Setting `user: redis` under the redis-container in docker-compose.yml worked.

**Comment by hoavoq** [comment]
> Did the same as here: [#1007 (comment)](https://github.com/laradock/laradock/issues/1007#issuecomment-310883173)
> 
> Setting `user: redis` under the redis-container in docker-compose.yml worked.

This comment was written 5 years ago but is still very useful today. Thank you very much
