### ISSUE TITLE
Add pgsql support for php-fpm

### ISSUE THREAD

**Issue by geraintdong** [laradock/laradock#1161]
### Info:
- Docker version (`$ docker --version`): 17.06.2-ce
- Laradock commit (`$ git rev-parse HEAD`): please these commits in my forked repo 
https://github.com/geraintdong/my-custom-laradock/commit/3cc917c9de7dd7735e86025a5b731f4331f42da7 
https://github.com/geraintdong/my-custom-laradock/commit/8f7b1b7e9feb79408d9d1d706c56aaf3cba435d8 
https://github.com/geraintdong/my-custom-laradock/commit/ca9c07eb7697419e558bc61e6d40f365ad564321
- System info (Mac, PC, Linux): Mac

### Issue:
PostgreSQL is not currently supported in php-fpm
_____

### Expected behavior:
PostgreSQL should be supported in php-fpm when needed
_____

### Reproduce:
Download [phppgadmin](http://phppgadmin.sourceforge.net/) to www directory & run on browser
_____

**Comment by zuohuadong** [comment]
you can use `pdo_postgresql`

**Comment by geraintdong** [comment]
@zuohuadong that would not be a good solution for legacy apps

**Comment by zuohuadong** [comment]
https://github.com/laradock/laradock/pull/1199

I  will  add it~
