### ISSUE TITLE
Empty continuation line found

### ISSUE THREAD

**Issue by hackel** [laradock/laradock#1164]
### Info:
- Docker version: 17.07.0-ce, build 8784753
- Laradock version: 5.6.0 (d340b6e) 
- System info: Linux
- System info disto/version: Ubuntu 16.10

### Issue:
Rebuilding the php-fpm image, I got a bunch of "Empty continuation line found" warnings:
```
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_SOAP} = true ]; then     apt-get update -yqq &&     apt-get -y install libxml2-dev php-soap &&     docker-php-ext-install soap ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_XDEBUG} = true ]; then     pecl install xdebug &&     docker-php-ext-enable xdebug ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl install -o -f redis     &&  rm -rf /tmp/pear     &&  docker-php-ext-enable redis ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_SWOOLE} = true ]; then     pecl install swoole     &&  docker-php-ext-enable swoole ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_MONGO} = true ]; then     pecl install mongodb &&     docker-php-ext-enable mongodb ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_ZIP_ARCHIVE} = true ]; then     docker-php-ext-install zip ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_BCMATH} = true ]; then     docker-php-ext-install bcmath ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_MEMCACHED} = true ]; then     curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz"     && mkdir -p memcached     && tar -C memcached -zxvf /tmp/memcached.tar.gz --strip 1     && (         cd memcached         && phpize         && ./configure         && make -j$(nproc)         && make install     )     && rm -r memcached     && rm /tmp/memcached.tar.gz     && docker-php-ext-enable memcached ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_EXIF} = true ]; then     docker-php-ext-install exif ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_AEROSPIKE} = true ]; then     apt-get update -yqq &&     apt-get -y install sudo wget &&     curl -L -o /tmp/aerospike-client-php.tar.gz "https://github.com/aerospike/aerospike-client-php/archive/3.4.14.tar.gz"     && mkdir -p aerospike-client-php     && tar -C aerospike-client-php -zxvf /tmp/aerospike-client-php.tar.gz --strip 1     && (         cd aerospike-client-php/src/aerospike         && phpize         && ./build.sh         && make install     )     && rm /tmp/aerospike-client-php.tar.gz ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_INTL} = true ]; then     apt-get update -yqq &&     apt-get install -y zlib1g-dev libicu-dev g++ &&     docker-php-ext-configure intl &&     docker-php-ext-install intl ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_GHOSTSCRIPT} = true ]; then     apt-get update -yqq     && apt-get install -y     poppler-utils     ghostscript ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_MSSQL} = true ]; then     apt-get update -yqq && apt-get install -y apt-transport-https         && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -         && curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list         && apt-get update -yqq         && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev libgss3 odbcinst msodbcsql locales         && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen         && pecl install pdo_sqlsrv-4.1.8preview sqlsrv-4.1.8preview         && docker-php-ext-enable pdo_sqlsrv sqlsrv ;fi
[WARNING]: Empty continuation lines will become errors in a future release.
```
I am guessing this is related to the comments inside of the shell commands in the Dockerfile.  e.g.
```sh
RUN if [ ${INSTALL_SOAP} = true ]; then \
    # Install the soap extension
    apt-get update -yqq && \
    apt-get -y install libxml2-dev php-soap && \
    docker-php-ext-install soap \
;fi
```
They probably just need to be moved outside of the if statement, since I assume adding a backslash to the end of a commented line won't work.

**Comment by wormhoudt** [comment]
Comments != empty lines. Don't count them as such.

... Is this the part where I bow?

**Comment by brunen9** [comment]
> Comments != empty lines. Don't count them as such.

But the parser in docker "thinks" that they are. If you move comments outside of RUN statement the parser will not throw those errors. 

And please pay attention to last warning in building log:
> [WARNING]: Empty continuation lines will become errors in a future release.

In future those comments would become a problem.

P.S. I found the issue related to this topic, there is a lot of talking in it: https://github.com/moby/moby/issues/29005

**Comment by a-bashtannik** [comment]
Confirm this annoying issue and the reason. Need to move the comments outside RUN section.

**Comment by a-bashtannik** [comment]
Hey, it's so easy to fix this bug, I can do it if somebody will merge my PR in the nearest feature... @Mahmoudz ?

`[WARNING]: Empty continuation lines will become errors in a future release.`

**Comment by brunen9** [comment]
@a-bashtannik , look at [this issue](https://github.com/nginxinc/docker-nginx/issues/203)

**Comment by a-bashtannik** [comment]
Oh, I see. Your comment should be here, thx.

**Comment by centigrade-thomas-becker** [comment]
In my docker file I use a lot of comments in combination with the line continuation character. Example:

```
# declare ports for services
EXPOSE \
    # service foo
    2005 \
    # service bar
    2010 \
    # service baz
    3000
[...]
```

I get an error that the lines with comments are invalid. Do I need to remove these comments for upcoming releases, or will the behaviour of the parser modified to tolerate these comment lines?

**Comment by mahnunchik** [comment]
Any news?

**Comment by wormhoudt** [comment]
Comment lines shouldn't count. Simple as. Anything short of that is either laziness or technical masturbation. Fix the parser to function appropriately rather than excoriating users for using comments in a way that is commensurate with typical usage. The whole point of comments is to be able to add them where the make sense contextually.

**Comment by lemats** [comment]
Should be fixed through [Moby #35004](https://github.com/moby/moby/pull/35004) (Docker 17.10 and up).

**Comment by yanhongwang** [comment]
Hi, but that still unfortunately happen in **docker 17.12.0-ce** ...

I use **Linux Mint 18**.
I follow installation by
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

**Comment by alexpnet89** [comment]
Hello, i'm having the same problem too in version 17.12.0-ce.
There is an alternative to this problem?

**Comment by terreb** [comment]
Same here, 17.12.0-ce-mac49 (21995)

**Comment by sinden** [comment]
Same here, 17.12.0-ce, windows 10.

**Comment by timerlau** [comment]
Same here, 17.12.0-ce, Ubuntu 16.04.3 LTS

**Comment by centigrade-thomas-becker** [comment]
These latest "me too" posts are not particularly helpful. Please use the +1 buttons on an existing post for that.

**Comment by naretini** [comment]
Just cloned laradock and 
$docker-compose up --build nginx
I got a series of errors like:

> [WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_AEROSPIKE} = true ]; then     apt-get update -yqq &&     apt-get -y install sudo wget &&     curl -L -o /tmp/aerospike-client-php.tar.gz "https://github.com/aerospike/aerospike-client-php/archive/master.tar.gz"     && mkdir -p aerospike-client-php     && tar -C aerospike-client-php -zxvf /tmp/aerospike-client-php.tar.gz --strip 1     && (         cd aerospike-client-php/src         && phpize         && ./build.sh         && make install     )     && rm /tmp/aerospike-client-php.tar.gz ;fi

.env id s set up to use PHP_VERSION=71


So looking in Dockerfile-71 for php-fpm and workspace I see there are inline comments.
I guess the error is related to them

> RUN if [ ${INSTALL_AEROSPIKE} = true ]; then \
    # Fix dependencies for PHPUnit within aerospike extension
    apt-get update -yqq && \
    apt-get -y install sudo wget && \

    # Install the php aerospike extension
    curl -L -o /tmp/aerospike-client-php.tar.gz "https://github.com/aerospike/aerospike-client-php/archive/master.tar.gz" \
    && mkdir -p aerospike-client-php \
    && tar -C aerospike-client-php -zxvf /tmp/aerospike-client-php.tar.gz --strip 1 \
    && ( \
        cd aerospike-client-php/src \
        && phpize \
        && ./build.sh \
        && make install \
    ) \
    && rm /tmp/aerospike-client-php.tar.gz \
;fi

Removing the comments doesn't solve the warning.... what am I supposed to do?

**Comment by kcz-code** [comment]
remove the last continuation character:

&& rm /tmp/aerospike-client-php.tar.gz \
  should be:
&& rm /tmp/aerospike-client-php.tar.gz

**Comment by zjien** [comment]
and same here, Version 17.12.0-ce-mac55 (23011)

**Comment by Boycce** [comment]
Why prevent the use of blank lines anyway?

e.g
```
RUN rm -rf /home/app && \
ln -sf /vagrant/ /home/app && \
ln -s /home/app /home/app2 && \

# Setup folders and files
rm -f /etc/service/sshd /&& \
rm -f /etc/service/rsyslog/ && \
...
```

**Comment by t3chn0m4g3** [comment]
Same here, Ubuntu 18.04, Docker version 17.12.1-ce, build 7390fc6

**Comment by indywidualny** [comment]
Any progress? Comments should be allowed. It will become a real issue in the future.

**Comment by Karunamon** [comment]
Still exists 18.06.1-ce, build e68fc7a on MacOS. I really, *really* hope this gets fixed before Dockerfiles start breaking.

**Comment by AaronLiuIsCool** [comment]
Any progress in 2019?

**Comment by nickwongdev** [comment]
I just converted my comments into echo statements and called it a day.
```
RUN echo "############ Doing a thing! ##################" && \
    things be doin && \
    echo "############ Doing another thing! ##################" && \
    more things to do
```

This way they also show up in things like Jenkins builds and stuff.

**Comment by almothafar** [comment]
@nickwongdev 

I did the same and that solved the issue, something like:

```docker
RUN \
  echo "create user with appropriate rights, groups and permissions" && \
  useradd --user-group --create-home --shell /bin/false ${USER} && \
  echo "${USER}:${USER}" | chpasswd && \
  adduser ${USER} sudo && \
  adduser ${USER} root && \
  chown ${USER}:${USER} / && \
  usermod -a -G root ${USER} && \
  \
  echo "create the file and set permissions now with root user" && \
  mkdir /app && chown ${USER}:${USER} /app && chmod 777 /app && \
  mkdir /build && chown ${USER}:${USER} /build && chmod 777 /build && \
  \
  echo "create the file and set permissions now with root user" && \
  touch /image.config && chown ${USER}:${USER} /image.config && chmod 777 /image.config
```

**Comment by dkarapanos** [comment]
Error response from daemon: Dockerfile parse error line 13: unknown instruction: &&


> remove the last continuation character:
> 
> && rm /tmp/aerospike-client-php.tar.gz \
> should be:
> && rm /tmp/aerospike-client-php.tar.gz

**Comment by wdy331644741** [comment]
same here :
```
[WARNING]: Empty continuation line found in:
    RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >/etc/apt/sources.list && echo "deb http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list && echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >>/etc/apt/sources.list && echo "deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list && apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev git zip unzip && docker-php-ext-install -j$(nproc) mcrypt pdo_mysql && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && docker-php-ext-install -j$(nproc) gd && pecl install redis && pecl install xdebug && pecl install swoole && docker-php-ext-enable redis swoole xdebug RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
[WARNING]: Empty continuation lines will become errors in a future release.
```

**Comment by tahiryasin** [comment]
The last line should not have a forward slash `\' at the end
