### ISSUE TITLE
npm install failing at acorn@5.1.2

### ISSUE THREAD

**Issue by dnguneratne** [laradock/laradock#1165]
### Info:
- Docker version (`$ docker --version`): 17.06.0-ce, build 02c1d87
- Laradock commit (`$ git rev-parse HEAD`): 8989c73711a145c19265f279e6e2f8da295358fb
- System info (Mac, PC, Linux):  PC
- System info disto/version: Windows 8.1

### Issue:
`npm install` hangs at `build: verb linkMans acorn@5.1.2` and exists with,
`npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/var/www/node_modules/.bin/acorn'`
_____

### Expected behavior:
`npm install` completes successfully. 
_____

### Reproduce:
1. Edit `myProject\laradock\.env`. Change `WORKSPACE_INSTALL_NODE=false` to `WORKSPACE_INSTALL_NODE=true`.
2. `docker-compose up -d workspace nginx mysql`.
3. `docker-compose exec workspace bash`.
4. `composer install`.
5. `php artisan key:generate`.
6. `exit`.
7. `docker exec -it laradock_workspace_1 bash`.
8. `npm install`.
_____

### Relevant Code:
The following is the last few lines of the npm log.
```
1318 info lifecycle minimatch@3.0.4~preinstall: minimatch@3.0.4
1319 silly preinstall form-data@2.1.4
1320 info lifecycle form-data@2.1.4~preinstall: form-data@2.1.4
1321 silly doSerial build 710
1322 silly build acorn@5.1.2
1323 info linkStuff acorn@5.1.2
1324 silly linkStuff acorn@5.1.2 has /var/www/node_modules as its parent node_modules
1325 verbose linkBins acorn@5.1.2
1326 verbose linkBins [ { acorn: './bin/acorn' }, '/var/www/node_modules/.bin', false ]
1327 verbose linkMans acorn@5.1.2
1328 verbose unlock done using /home/laradock/.npm/_locks/staging-14d94e7bc34cac4a.lock for /var/www/node_modules/.staging
1329 warn ETXTBSY: text file is busy, rmdir '/var/www/node_modules/fsevents/build/Release/.deps/Users/eshanker/Code/fsevents/lib/binding/Release'
1330 verbose stack Error: EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/var/www/node_modules/.bin/acorn'
1331 verbose cwd /var/www
1332 verbose Linux 4.4.74-boot2docker
1333 verbose argv "/home/laradock/.nvm/versions/node/v8.6.0/bin/node" "/home/laradock/.nvm/versions/node/v8.6.0/bin/npm" "install"
1334 verbose node v8.6.0
1335 verbose npm  v5.3.0
1336 error path ../acorn/bin/acorn
1337 error code EPROTO
1338 error errno -71
1339 error syscall symlink
1340 error EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/var/www/node_modules/.bin/acorn'
1341 verbose exit [ -71, true ]
```
### Other:
- After, `7. docker exec -it laradock_workspace_1 bash`  I tried `su laradock` and `npm install`. npm failed with the same results.  
- If I `cd` into `myProject` and run `npm install` `acorn@5.1.2` gets installed properly. It appears that this is the only package that is not getting installed via the docker container.

**Comment by ArtisanTinkerer** [comment]
Did you resolve this? I am getting a similar problem.
