### ISSUE TITLE
Point a domain name to nodejs api

### ISSUE THREAD

**Issue by gazatem** [laradock/laradock#1169]
I've developed a nodejs api server using restify. However not able to point domain to this nodejs. 

I'm getting 504 Gateway Error

My Nginx conf is here:

```
server {

    listen 80;
    listen [::]:80;

    server_name api.domain.app;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
 
Need some advice

**Comment by samthomson** [comment]
Could you expand on your project structure and what you're trying to achieve. That would make it easier to help :)
You have made a project and want it to be accessible on your computer? That project currently runs in a docker container and you can reach it at `http://127.0.0.1:3000`?
