### ISSUE TITLE
apache2 fails to start

### ISSUE THREAD

**Issue by jelovac** [laradock/laradock#1174]
### Info:
- Docker version:  17.07.0-ce, build 8784753
- Laradock commit: a2edf57e3b328ee636a0b0721764a4fe460a7a33
- System info (Mac, PC, Linux): Windows 10
- Additional info: Docker toolbox for Windows using Virtualbox as docker provider

### Issue:
Apache virtual host .conf files are not copied to workspace container and because of that the apache2 service fails.

````
2017-10-05 16:36:22,836 INFO spawned: 'apached' with pid 1319
-> Executing /opt/docker/bin/service.d/httpd.d//10-init.sh
2017-10-05 16:36:22,881 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
apache2: Syntax error on line 219 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/sites-enabled/vhost.conf: No matches for the wildcard '*.conf' in '/etc/apache2/sites-available', failing (use IncludeOptional if required)
2017-10-05 16:36:22,977 INFO exited: apached (exit status 1; not expected)
2017-10-05 16:36:23,988 INFO spawned: 'apached' with pid 1324
-> Executing /opt/docker/bin/service.d/httpd.d//10-init.sh
2017-10-05 16:36:24,029 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
apache2: Syntax error on line 219 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/sites-enabled/vhost.conf: No matches for the wildcard '*.conf' in '/etc/apache2/sites-available', failing (use IncludeOptional if required)
2017-10-05 16:36:24,128 INFO exited: apached (exit status 1; not expected)
````
_____

### Expected behavior:
The .conf files should have been copied to the apache2 sites-available directory.
_____

### Reproduce:
- $ mkdir laradock-test && cd laradock-test
- $ git clone https://github.com/laravel/laravel.git .
- $ git submodule add https://github.com/Laradock/laradock.git
- $ cd laradock && cp env-example .env
- $ nano .env # Enable xdebug on the Workspace image and save
- $ docker-compose up -d apache2 mariadb
- add laradock.dev to hosts and try to access it
_____

### Relevant Information:

The reason why it fails is because default.apache.conf has not been copied, I also tried to create additional *.conf files in the laradock/apache2/sites directory but for some reason they are not copied when I rebuild the containers.

**Comment by ChrGriffin** [comment]
Windows 7, Docker 17.07.0-ce. Encountering this same issue.

**Comment by devployment** [comment]
Just in case. If you changed your Windows password recently, make sure that the drives you need are shared in the Docker settings again. It just happened to me that these shares were lost. Probably as I had to change my password recently.

So I created a new `DockerUser` and gave it the needed (admin) rights. By this it should not happen anymore if the company policy forces me to change my password. Or just use your Windows user and make sure everything is shared as needed.
