### ISSUE TITLE
Fail to execute "php artisan storage:link" in workspace container via windows container

### ISSUE THREAD

**Issue by Ansonhkg** [laradock/laradock#1177]
### Info:
- Docker version 17.07.0-ce, build 8784753
- a2edf57e3b328ee636a0b0721764a4fe460a7a33
- PC (Windows Container via Docker Quickstart Terminal, not using Hyper V)

### Issue:
I'm trying to run `php artisan storage:link` inside the workspace container, however, it throws error exception as following:
```
 [ErrorException]
 symlink(): Protocol error
```
It works fine with Hyper-V and Linux container. However, I'm also using Android emulator which could not be run on Hyper-V that's why I'm using Windows container. 
_____

### Expected behavior:
It should create a symbolic link from **/public/storage** to **/storage/app/public**
_____

### Reproduce:
- Use Windows Container
- docker-compose exec workspace bash
- php artisan storage:link
_____

**Comment by megaxlr** [comment]
Can confirm for a Ubuntu host. 
Running `storage:link` on the host machine does make the symbolic link, however this points to the path as seen from the host machine. The path may or may not be the same in the container.
