### ISSUE TITLE
Ability to speficy Postgres version

### ISSUE THREAD

**Issue by szyzak** [laradock/laradock#1178]
### Info:
- Docker version (`$ docker --version`): Docker version 1.12.6, build 78d1802
- Laradock commit (`$ git rev-parse HEAD`): 01c358b6bc76333f4960a7da582d3bdbc33b9155
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.04

### Issue:
Docker installs latest Postgres version
_____

### Expected behavior:
Beeing able to speficy Postgres version  in .env file
_____

### Reproduce:
```
docker-compose up -d postgres
```
_____

### Relevant Code:

```
FROM postgres:latest

```

**Comment by zuohuadong** [comment]
`docker tag postgres:10 postgres`

**Comment by allaniftrue** [comment]
How do I downgrade the version? I tried `docker tag postgres:9.6 postgres` but it didn't recognise the tag

**Comment by allaniftrue** [comment]
Inside `postgres/Dockerfile` change 

`FROM postgres:alpine`

to

`FROM postgres:<version>`  e.g.  `FROM postgres:9.6`
