### ISSUE TITLE
how to update lib-gd

### ISSUE THREAD

**Issue by samthomson** [laradock/laradock#1179]
There is a bug in lib-gd which has just been fixed in the latest version: https://github.com/libgd/libgd/issues/338

How can I use this later version of the GD in my laradock project?
The bundled version is 2.1.0 but the latest is 2.2.5
![image](https://user-images.githubusercontent.com/6588340/31406206-6f4f5bb0-adf8-11e7-8752-d0253364afbe.png)

**Comment by scaule** [comment]
Hi,

In Docker to upgrade libgd you have two choices :

-> ( Bad and not persistant if you drop your container ) connect you in your PHP container and update it like on a real server ( apt-get install php-gd for exemple on debian)

-> (Good) update the Dockerfile of php-fpm and re-build it 

Personnally i use the first one to test and when it's good i write on Dockerfile.

**Comment by samthomson** [comment]
Thanks @scaule I ended up doing just that :)
