### ISSUE TITLE
Laradock MYSQL container is getting wipped out

### ISSUE THREAD

**Issue by tariqbilal** [laradock/laradock#1185]
### Info:
- Docker version (`$ docker --version`): 
Docker version 17.05.0-ce, build 89658be
- Laradock commit (`$ git rev-parse HEAD`): 
01c358b6bc76333f4960a7da582d3bdbc33b9155
- System info (Mac, PC, Linux): 
Linux
- System info disto/version: 
Ubuntu Xenial
### Issue:

The MySQL containers is getting hacked, all my database data is lost so I have to back it up.

Another Table is created containing messages to ask for BTC.

how can I secure my laradock containers?

**Comment by mclxly** [comment]
Me too.

How do you fix the problem?
