### ISSUE TITLE
short_open_tag = Off in CLI even when set to On in .ini

### ISSUE THREAD

**Issue by szyzak** [laradock/laradock#1186]
### Info:
- Docker version (`$ docker --version`): Docker version 1.12.6, build 78d1802
- Laradock commit (`$ git rev-parse HEAD`): 903c77421c8433619a7d6cf79cec68e24ac99266
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.04

### Issue:
php CLI short_open_tag is set to Off
_____

### Expected behavior:
php CLI short_open tag should be set to On if in php.ini file it was On

However nginx short_open_tag is On
_____

### Reproduce:
.env
PHP_VERSION=71

php71.ini
short_open_tag = On
_____

### Relevant Code:

```bash
docker-compose up -d nginx
docker-compose exec workspace bash
php -ini | grep short_open_tag
```

in app code

```php
<?php
echo phpinfo();
die;
```

**Comment by StanislavDremin** [comment]
I created file ./ php-fpm/cgi.ini in which specified short_open_tag = on and in docker-compose.yml pointed to 
workspace:
    volumes:
       -./ php-fpm/cli.ini:/etc/php/${PHP_VERSION}/cli / conf.d / 30-cli.ini
