### ISSUE TITLE
Postgres won't run

### ISSUE THREAD

**Issue by zolotov88** [laradock/laradock#1188]
### Info:
- Docker version (`$ docker --version`):  Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): 903c77421c8433619a7d6cf79cec68e24ac99266
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

### Issue:
Postgres won't run
_____

### Expected behavior:
Postgres should run
_____

### Reproduce:
```
$ docker-compose up -d nginx postgres
$ Starting laradock_postgres_1 ...
$ Starting laradock_postgres_1
```
Without "done"

```
$ docker-compose ps
         Name                        Command              State                     Ports
-----------------------------------------------------------------------------------------------------------
laradock_postgres_1       docker-entrypoint.sh postgres   Exit 1

$ docker-compose logs
postgres_1             | 2017-10-13 13:31:26.125 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
postgres_1             | 2017-10-13 13:31:26.125 UTC [1] HINT:  The server must be started by the user that owns the data directory.
```

**Comment by Zolotov88** [comment]
Can work if change ```- ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data``` to ``` - /var/lib/postgresql/data``` in ```docker-compose.yml```

**Comment by demesiooliveira** [comment]
The problem is in updating the postgres image, which when you change it changes the permissions of the data folder. To solve it simply change `- ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data` to `- ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql` without the 'data'

**Comment by rwoody** [comment]
Removing `data` worked to solve this for me (and similarly for Redis - I had to change `/data` to `/redis` for the volume). I'm using Dinghy on OSX if that makes a difference.

**Comment by vutrungduc7593** [comment]
I'm using Windows 10 OS.
I solved it by changing DATA_PATH_HOST=~/.laradock/data to DATA_PATH_HOST=D:\laradock-data-host in laradock/.env file

**Comment by atthakorn** [comment]
> The problem is in updating the postgres image, which when you change it changes the permissions of the data folder. To solve it simply change `- ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data` to `- ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql` without the 'data'

This works for me too!  thanks @demesiooliveira
