### ISSUE TITLE
MySQL container connection refused

### ISSUE THREAD

**Issue by ipansensoy** [laradock/laradock#1190]
Can't connect to my mysql container using this config is there anything wrong with the actual laradock?
MYSQL_VERSION=8.0
MYSQL_DATABASE=laravel-app
MYSQL_USER=root
MYSQL_PASSWORD=secret
MYSQL_PORT=3308
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

**Comment by ganjarsetia** [comment]
have you try `docker ps -a` ? does the mysql is run or exited?
