### ISSUE TITLE
xdebug config error on mac high sierra phpstorm

### ISSUE THREAD

**Issue by busyfree** [laradock/laradock#1191]
### Info:
- Docker version (`$ docker --version`): 
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64
Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

- Laradock commit (`$ git rev-parse HEAD`): 
a5c505bf28232ab703758fe7a0e2a597264cc3db
- System info (Mac, PC, Linux): 
macOS high sierra
- System info disto/version: 
10.13
### Issue:

phpstorm version is 2017.2.4
ssh ppk file format error
host is 127.0.0.1 laravel

![image](https://user-images.githubusercontent.com/504251/31593315-8c857512-b1f3-11e7-944d-7ee3c1718fd6.png)

**Comment by vudev** [comment]
renew ssh key file

https://support.rackspace.com/how-to/connecting-to-a-server-using-ssh-on-linux-or-mac-os/
