### ISSUE TITLE
request for contributor

### ISSUE THREAD

**Issue by zuohuadong** [laradock/laradock#1195]
May you add me as a contributor to this project? I would like to do some job to let laradock has a better support for postgres and caddy.

Here are 12 PR I have made for laradock

add postgres for php-fpm 
#1199 opened 6 minutes ago by zuohuadong  
alpine be quckly 
#1184 by zuohuadong was merged 2 days ago  
update jenkins version 
#1183 by zuohuadong was merged 2 days ago  
use caddy in Apache-2.0 
#1181 by zuohuadong was merged 2 days ago  
add pgadmin backup volumes 
#1094 by zuohuadong was merged on 15 Aug  
fix to backup and fix max client 
#1093 by zuohuadong was merged on 24 Aug  
use openssh-client not openssh* 
#1080 by zuohuadong was merged on 8 Aug  
add demo and use caddy example for laravel 
#1079 by zuohuadong was merged on 8 Aug  
Fix pgadmin can't boot 
#1000 by zuohuadong was merged on 4 Jul  
git key to pull code 
#992 by zuohuadong was merged on 7 Jun  
Fix git's BUG & add plugin 
#844 by zuohuadong was merged on 22 Apr  
update cadddy version to 0.10.0 

Thank you.

**Comment by rodion-arr** [comment]
Don't you already specified as contributor automatically?
[Laradock contributors](https://github.com/laradock/laradock/graphs/contributors)

**Comment by zuohuadong** [comment]
yes, thanks~

**Comment by zuohuadong** [comment]
ERROR: Permission to laradock/laradock.git denied to zuohuadong.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rodion-arr** [comment]
Don't understand why you need direct access to repo :)

**Comment by zuohuadong** [comment]
I hope to maintain pgadmin  : Cross-version backup .

postgres: Cross-version upgrade.

caddy: Like caddyserver.com as simple to install, and can be used commercially.
