### ISSUE TITLE
command not found: docker-compose

### ISSUE THREAD

**Issue by wedojava** [LaraDock/laradock#12]
The step:9 - Finally run the containers. Make sure you are in the docker folder before running this command.

When I run the command blow,there is a error :`command not found: docker-compose`

    docker-compose up -d

And if I run `docker -v`,reponse blow:

    Docker version 1.10.1, build 9e83765

Could there is anyone do me a favor?

**Comment by Mahmoudz** [comment]
@wedojava `docker-compose` is a different software than `docker` you should be running `docker-compose -v` to see if you have it installed. Most probably you have not yet installed it. If you install the **Docker Toolbox** you should get it. Check out this link https://docs.docker.com/compose/install/

**Comment by wedojava** [comment]
Thank you.I got it!
I'm a newer in docker and English.These is not a good issue.
I'd better to read document more carefully yet.
Have a good one.
