### ISSUE TITLE
mix.browserSync(); doesn't work

### ISSUE THREAD

**Issue by delmicio** [laradock/laradock#1205]
### Info:
- Docker version:  17.09.0-ce-win33 (13620)
- System info (Mac, PC, Linux): PC Win 10

### Issue:

`mix.browserSync();` doesn't work and there is no instructions on how to use.
_____

### Expected behavior:

Adding `mix.browserSync();` should work on localhost:3000
_____

### Reproduce:

add `mix.browserSync();` to you webpack.mix.js
run `npm run watch` inside workspace container
```
[Browsersync] Proxying: http://app.dev
[Browsersync] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://172.19.0.2:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://172.19.0.2:3001
 -----------------------------------
[Browsersync] Watching files...
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```
goto `http://localhost:3000` and nothing

**Comment by Harti** [comment]
_Someone_ already found a solution in #640, but never posted the exact steps to reproduce it.
