### ISSUE TITLE
PHP extensions (V8Js) don't work

### ISSUE THREAD

**Issue by Zolotov88** [laradock/laradock#1207]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): 05879bdda24080f5eed8e1ff4dc864bcf0034414
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 LTSB

### Issue:
When I use 
```
$ docker-compose exec workspace bash
$ php -m
``` 
And I see 56 PHP modules. 
But when I use ```get_loaded_extensions();``` in my php file with nginx only 36 modules are working there.
How can I use v8js for examle im my php files?

**Comment by smoleniuch** [comment]
I have the same issue, the extension is not installed at all.

**Comment by Rishats** [comment]
Extension _is not installed at all_ +++
