### ISSUE TITLE
WARNING: The PHP_FPM_PG_CLIENT variable is not set. Defaulting to a blank string

### ISSUE THREAD

**Issue by nellonican** [laradock/laradock#1208]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): c05c6754080f490ae3e70df9e463888807ed0f3b
- System info (Mac, PC, Linux): Linux
- System info disto/version: Debian 9

### Issue:
When starting the php-fpm container the following warning shows:
`WARNING: The PHP_FPM_PG_CLIENT variable is not set. Defaulting to a blank string`
_____

### Expected behavior:
No warning when starting the `php-fpm` container
_____

### Reproduce:
Copy `env-example` to `.env` and start a `php-fpm` container
_____

### Fix:
Add a `PHP_FPM_PG_CLIENT` variable to `env-example`.

**Comment by hetsch** [comment]
Same here with more undefined variables:

```
WARNING: The PHP_FPM_INSTALL_PGSQL variable is not set. Defaulting to a blank string.
WARNING: The PHP_FPM_PG_CLIENT variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_PORT variable is not set. Defaulting to a blank string.
WARNING: The MAILDEV_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MAILDEV_SMTP_PORT variable is not set. Defaulting to a blank string.
```

Throws error:

```
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.maildev.ports is invalid: Port ranges don't match in length
services.grafana.ports is invalid: Port ranges don't match in length
services.maildev.ports is invalid: Port ranges don't match in length
```
