### ISSUE TITLE
Fix: Missing PGSQL drivers on PHP-Workers

### ISSUE THREAD

**Issue by NickToony** [laradock/laradock#1217]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): 152c896515ecd9c47a77a881dbc99763ec8799dc
- System info (Mac, PC, Linux): Mac
- System info disto/version:  OSX 10.12

### Issue:
When using PostreSQL (and in my case, PostGIS), Laravel works completely fine, but php-workers will fail. They will throw the following exception:

```
Next Doctrine\DBAL\Driver\PDOException: could not find driver in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47
```

I can confirm the supervisor container is running, and the jobs are running with the correct .env (the values appear in the stack trace). This seems to be an issue of php-worker not having the pgsql drivers.
_____

### Fix:

I edited the dockerfile-71 for php-worker, and added the code below:

```
# Install PGSQL drivers
RUN set -ex \
  && apk --no-cache add \
    postgresql-dev

RUN docker-php-ext-install pdo pdo_pgsql
```

Then I rebuilt the container, and my php-workers began working. I'm unsure if this is the correct approach, so making an issue rather than pull request.

### Ref:
I grabbed the pgsql install code from:
https://github.com/docker-library/php/issues/221

**Comment by brunen9** [comment]
@NickToony , I added variable `PHP_WORKER_INSTALL_PGSQL` and such code:
```
#####################################
# PostgreSQL:
#####################################
ARG INSTALL_PGSQL=false
ENV INSTALL_PGSQL ${INSTALL_PGSQL}
RUN if [ ${INSTALL_PGSQL} = true ]; then \
    apk --update add postgresql-dev \
    && docker-php-ext-install pdo_pgsql \
    && rm /var/cache/apk/* \
    && mkdir -p /var/www \
;fi
```
