### ISSUE TITLE
All in one container !

### ISSUE THREAD

**Issue by mojtabye** [laradock/laradock#1221]
is there any way to build an all in one container ( LEMP Container + project for example ) using laradock? 

the issue is about using laradock single project mode with minimum containers count.

**Comment by JeroenVanOort** [comment]
As far as I know, using a single container is not possible.

Why would you like to do this? Running multiple containers has many advantages.

**Comment by Mahmoudz** [comment]
@mojtabye there are other projects with that kind of approach. Which is not recommended. The more separated containers the better for everything.
