### ISSUE TITLE
docker-compose up nginx Permission Error

### ISSUE THREAD

**Issue by antagus1953** [laradock/laradock#1222]
Hi.

Can you help me with these error?. When I  try to do docker-compose up nginx it fails with this error:

Step 28/149 : COPY ./aliases.sh /home/laradock/aliases.sh
 ---> Using cache
 ---> 1cf3d5e352fd
Step 29/149 : RUN echo "" >> ~/.bashrc &&     echo "# Load Custom Aliases" >> ~/.bashrc &&     echo "source /home/laradock/aliases.sh" >> ~/.bashrc &&  echo "" >> ~/.bashrc &&         sed -i 's/\r//' /home/laradock/aliases.sh &&         sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
 ---> Running in a46324b143a9
sed: can't read /home/laradock/aliases.sh: Permission denied
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c echo "" >> ~/.bashrc &&     echo "# Load Custom Aliases" >> ~/.bashrc &&     echo "source /home/laradock/aliases.sh" >> ~/.bashrc &&     echo "" >> ~/.bashrc &&         sed -i 's/\r//' /home/laradock/aliases.sh &&    sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh' returned a non-zero code: 2

I'm using Photon OS with    docker version 17.06.0-ce and docker-compose version 1.17.0-rc1

**Comment by NakanishiTetsuhiro** [comment]
I'm having the same problem...

**Comment by NakanishiTetsuhiro** [comment]
It solved it!
I was trying to use Laradock on Ubuntu on VirtualBox.
When I run Laradock on the shared folder with the host OS, laradock not working.
After moving laradock dir to Desktop and runnning it works

**Comment by jmkylvy** [comment]
try to shutdown SELinux if your system have. hopes this can help.
