### ISSUE TITLE
ict

### ISSUE THREAD

**Issue by lambrojos** [laradock/laradock#1223]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by Mahmoudz** [comment]
@lambrojos can you give us more details?

**Comment by lambrojos** [comment]
sorry I must have opened this issue by mistake, somehow
