### ISSUE TITLE
add php sockets support

### ISSUE THREAD

**Issue by terryzwt** [laradock/laradock#1235]
### Info:
- Docker version (Docker version 17.09.0-ce, build afdb6d4`): 
- Laradock commit (7138d7a13c797339f1c3c5930d9cc6a2d9505d9c): 
- System info (Mac): 
- System info disto/version: 

### Issue:

no php ext : socket support.

### Expected behavior:

php sockets extension should be a config.

ref link:
https://github.com/docker-library/php/issues/253

**Comment by robbygallo** [comment]
Please add this code to your _php-fpm/Dockerfile_, then run _docker-compose build php-fpm_

> ###########################################################################
> # sockets:
> ###########################################################################
> 
> ARG INSTALL_SOCKET=true
> 
> RUN if [ ${INSTALL_SOCKET} = true ]; then \
>     # Install the sockets extension
>     docker-php-ext-install sockets \
> ;fi

**Comment by robbygallo** [comment]
I have found a solution:
Add to your _php-fpm/Dockerfile_

> ###########################################################################
> # sockets:
> ###########################################################################
> 
> ARG INSTALL_SOCKET=true
> 
> RUN if [ ${INSTALL_SOCKET} = true ]; then \
>     # Install the sockets extension
>     docker-php-ext-install sockets \
> ;fi

- stop your laradock
- then remove your php-fpm  and rebuild it
- restart your laradock

that's all

**Comment by robbygallo** [comment]
u have to add it after for eg soap

**Comment by terryzwt** [comment]
the problem is that, I think laradock should support it. you should not touch any code to support this feature.

**Comment by FoxxMD** [comment]
@robbygallo solution is not working for me. The dockerfile seems to run correctly but I still get errors IE `Call to undefined function socket_create()`

When I check `/usr/local/etc/php/conf.d` there is no sockets ini specifying `sockets.so`

**Comment by vlauciani** [comment]
I've the same error: `Call to undefined function socket_create()`

Did you find a solution?

**Comment by FoxxMD** [comment]
No i did not find a solution, unfortunately.

**Comment by adesr** [comment]
sorry for my poor english

to anyone who get this problem, you can implement @robbygallo solution.
and add those snippet to _**php-worker/Dockerfile**_.
stop _**laradock**_, rebuild **_php-worker_** and restart **_laradock_**

hope this helps anyone
