### ISSUE TITLE
sockets support

### ISSUE THREAD

**Issue by terryzwt** [laradock/laradock#1236]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by jeff-h** [comment]
What socket server are you thinking?

**Comment by terryzwt** [comment]
just support socket function in php.

like socket_create etc.

**Comment by jeff-h** [comment]
Ah, sorry. I misunderstood.
