### ISSUE TITLE
Can't install  Node  & npm

### ISSUE THREAD

**Issue by ilyatab** [laradock/laradock#1238]
### Info:
- Docker version (` 17.09.0-ce-mac35 (19611)`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac): 
- System info disto/version: 

### Issue:
Can't install node, because not installed npm...
_____

### Expected behavior:
npm install  - successfully completed!
_____

### Reproduce:
1. I create dir test1.loc -
2. Edit myProject\laradock\.env. 
3. Change WORKSPACE_INSTALL_NODE=false to WORKSPACE_INSTALL_NODE=true.
4. docker-compose up -d workspace nginx mysql. 
was OK
5. docker-compose exec workspace bash.
6. composer install.
7. php artisan key:generate.
8. After I went to browser - all ok!
9. Go to dir in my project ( cd test1.loc)
10 .npm install.

....error...
_____

### Relevant Code:

```

gyp verb `which` failed   stack: 'Error: not found: /path/to/executable/python2.7\n    at getNotFoundError (/var/www/test1.loc/node_modules/which/which.js:13:12)\n    at F (/var/www/test1.loc/node_modules/which/which.js:68:19)\n    at E (/var/www/test1.loc/node_modules/which/which.js:80:29)\n    at /var/www/test1.loc/node_modules/which/which.js:89:16\n    at /var/www/test1.loc/node_modules/isexe/index.js:42:5\n    at /var/www/test1.loc/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/var/www/test1.loc/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/test1.loc/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/var/www/test1.loc/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/var/www/test1.loc/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/test1.loc/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/test1.loc/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/test1.loc/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/home/laradock/.nvm/versions/node/v9.1.0/bin/node" "/var/www/test1.loc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/test1.loc/node_modules/node-sass
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN EINVAL: invalid argument, scandir '/var/www/test1.loc/node_modules/fsevents/node_modules/dashdash/node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-09T17_26_45_943Z-debug.log
```

**Comment by JeromeDesseaux** [comment]
Same error here. I upvote.

**Comment by JeromeDesseaux** [comment]
I managed to fix it adding two lines to workspace/Dockerfile-71
Line 56 : 
` apt-get install -y python2.7`

And at the end, once NPM is installed : 
`npm config set python /usr/bin/python2.7`


Hope it could be useful. I guess it should be added to the official Dockerfile.

**Comment by nellonican** [comment]
The `.env` file also has a `WORKSPACE_INSTALL_PYTHON` which is set to `false` by default. If you set it to `true`, python will be installed in the workspace image.

**Comment by mitjarobic** [comment]
@nellonican i have installed it via WORKSPACE_INSTALL_PYTHON=true on the latest laradock but i get the same error. I am using linux.

**Comment by sumihiro** [comment]
I have same problem.
I changed WORKSPACE_INSTALL_PYTHON =false to WORKSPACE_INSTALL_PYTHON =true.
However, it seems that Python is not installed correctly on the system.

```
root@8ab127771d5f:/var/www# which python
root@8ab127771d5f:/var/www# ls -la /usr/bin/python*
lrwxrwxrwx 1 root root       9 Dec 10  2015 /usr/bin/python -> python2.7
lrwxrwxrwx 1 root root       9 Dec 10  2015 /usr/bin/python2 -> python2.7
lrwxrwxrwx 1 root root      33 Nov 19  2016 /usr/bin/python2.7-config -> x86_64-linux-gnu-python2.7-config
lrwxrwxrwx 1 root root      16 Dec 10  2015 /usr/bin/python2-config -> python2.7-config
lrwxrwxrwx 1 root root       9 Mar 23  2016 /usr/bin/python3 -> python3.5
-rwxr-xr-x 2 root root 4456240 Sep 18 15:59 /usr/bin/python3.5
-rwxr-xr-x 2 root root 4456240 Sep 18 15:59 /usr/bin/python3.5m
lrwxrwxrwx 1 root root      10 Mar 23  2016 /usr/bin/python3m -> python3.5m
lrwxrwxrwx 1 root root      16 Dec 10  2015 /usr/bin/python-config -> python2.7-config
```

"python 2.7" does not exist.
Instead, python3 is installed.

I think that the location where python is installed in the workspace/Dockerfile-71 file is corrupt.

```
#####################################
# PYTHON:
#####################################

ARG INSTALL_PYTHON=false
ENV INSTALL_PYTHON ${INSTALL_PYTHON}
RUN if [ ${INSTALL_PYTHON} = true ]; then \
  apt-get update \
  && apt-get -y install python python-pip python-dev build-essential  \
  && pip install --upgrade pip  \
  && pip install --upgrade virtualenv \
;fi
```

This code seems to install python3 instead of python 2.7.

**Comment by nellonican** [comment]
This is because of 2 old commits creating a conflict with the `WORKSPACE_INSTALL_PYTHON` variable.

See:
https://github.com/laradock/laradock/pull/1240

If you remove the changes the following 2 commits make, it should work. Can you test it?

Commit https://github.com/laradock/laradock/commit/c5ccc2f4ff26adce44ce98373b951ff14eae3f8a
Commit https://github.com/laradock/laradock/commit/b47963c80d88ff393ce25b0df1c9c8986dcdfdae

**Comment by ModernArtisan** [comment]
The same issue repeats with `WORKSPACE_INSTALL_PYTHON=ture` and `WORKSPACE_INSTALL_PYTHON=false`. In bin path only `python3` exists. How it's happend if I have set `WORKSPACE_INSTALL_PYTHON=false` ? And with
```bash
RUN groupadd -g ${PGID} laradock && \
    useradd -u ${PUID} -g laradock -m laradock && \
    apt-get update -yqq && \
    apt-get install -y python2.7
```

**Comment by nellonican** [comment]
@ModernArtisan Using python3 instead of python2 should be no problem.

But you need to *undo* the changes that were made in commit https://github.com/laradock/laradock/commit/c5ccc2f4ff26adce44ce98373b951ff14eae3f8a 
and set `WORKSPACE_INSTALL_PYTHON` to `true` in `.env`

`workspace/Dockerfile-71` has the following on `line 690`:
```
    npm config set python /usr/bin/python2.7
```

That is why `npm install` is looking for python2.

**Comment by ModernArtisan** [comment]
@nellonican Nope, we need exactly python2.7! Because:
```bash
gyp ERR! stack Error: Python executable "/usr/bin/python3" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```
During installation npm dependencies

**Comment by nellonican** [comment]
@ModernArtisan 
Can you try to build the workspace image with the following version of workspace/Dockerfile-71 ? 

https://github.com/nellonican/laradock/blob/nellonican/workspace/Dockerfile-71

And set ` WORKSPACE_INSTALL_PYTHON` to `true` in `.env`

By using that, I am able to create the `workspace` docker image.

**Comment by ModernArtisan** [comment]
@nellonican Yep, it works fine now! I think it should be a pull request :)
So, why these lines was added before?
```
apt-get update -yqq && \
apt-get install -y python2.7
```
```
npm config set python /usr/bin/python2.7
```

**Comment by nellonican** [comment]
They were added by @JeromeDesseaux . He didn't see the `WORKSPACE_INSTALL_PYTHON` variable in `.env` and added the python install to Dockerfile-71 .

**Comment by patrickcarlohickman** [comment]
The other problem is that the line `npm config set python /usr/bin/python2.7` is not doing what is intended. The previous `rm -rf` statement is not terminated, so this addition is actually attempting to delete the files `npm`, `config`, `set`, `python`, and `/usr/bin/python2.7`. In this case, the python2.7 exectuable does actually get deleted.

@nellonican's PR #1257 will fix the issue, though.

**Comment by jeperello** [comment]
Using version 8.12.0 of nvm we solve this problem:
- nvm install 8.12.0
- nvm use 8.12.0
Remove installed packages:
- rm -Rf node_modules/
- rm -f package-lock.json
Finally, run install again:
- npm install
Good luck!

**Comment by fonger900** [comment]
Thanks a lot!

**Comment by Sogl** [comment]
I still have this problem on latest laradock: `failed Error: not found: python2`
I created a new issue for this: https://github.com/laradock/laradock/issues/2175

**Comment by yorulmazsinan** [comment]
> Using version 8.12.0 of nvm we solve this problem:
> 
> * nvm install 8.12.0
> * nvm use 8.12.0
>   Remove installed packages:
> * rm -Rf node_modules/
> * rm -f package-lock.json
>   Finally, run install again:
> * npm install
>   Good luck!

Thanks bro.
