### ISSUE TITLE
Ecs Task Definition example for laradoc

### ISSUE THREAD

**Issue by aniamin** [LaraDock/laradock#124]
I want to run my container using AMZON ECS. It would be really great If you can help me providing a sample task_definition file.

I am using the workspace,nginx, php-fpm container for my app

**Comment by Mahmoudz** [comment]
@aniamin I was working on that to include it as part of LaraDock but didn't finished it. Would be awesome if someone can contribute with that.

**Comment by aniamin** [comment]
I was asking for some help as I am getting it little bit difficult to
manage multiple containers through ECS

**Comment by Mahmoudz** [comment]
Let's continue this conversation on this Issue #244

**Comment by canfone** [comment]
@aniamin 
Any updates about you trying to deploy to ECS? I am currently working on deploying laradock containers to AWS elastic beanstalk but I don't know where or what to start. That would be great if you can share some knowledge. 

Thanks!

**Comment by warrence** [comment]
I also would like to know how to deploy Laradock to ECS, any updates?
