### ISSUE TITLE
docker-compose up -d nginx mysql fails at step 7/152

### ISSUE THREAD

**Issue by f0nZ** [laradock/laradock#1242]
### Info:
- Docker version Version 17.09.0-ce-win33 (13620) Channel: stable 8c56a3b
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  PC
- System info disto/version:  Windows 10

### Issue:

Step 7/152 when doing "docker-compose up -d nginx mysql"
_____

### Expected behavior:

Should work I guess
_____

### Reproduce:

"docker-compose up -d nginx mysql" while using git bash (https://git-scm.com/downloads)

### Relevant Code:
![screenshot_1](https://user-images.githubusercontent.com/7041307/32702731-076e3b9c-c7e3-11e7-913a-e98fc44f602f.jpg)

**Comment by nellonican** [comment]
I had the same error. This should be fixed by https://github.com/laradock/laradock/pull/1241
