### ISSUE TITLE
laravel-echo-server npm install fails to fetch package, build fails due to missing python

### ISSUE THREAD

**Issue by axit-joost** [laradock/laradock#1245]
### Info:
- Docker version: Docker version 17.10.0-ce, build f4ffd25
- Laradock commit: f7ac8cf8621f071ad3888d55b6ab94dbe85324cf
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.10

### Issue:
When spinning up a laravel-echo-server, the step to run `npm install` fails. The cause of this is due to npm being unable to fetch a required dependency as a prebuilt binary (HTTP 403 Access Denied) and consequently tries to build the missing package, which fails due to the fact that python is missing from the environment.

Package that 403's:
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-linux-x64.tar.gz 

Deps missing in Container:
- python

Workaround:
Add the following line before the `RUN npm install` line:
```
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base
```
_____

### Expected behavior:
The prebuilt package should be available, but if it is not, it should have the necessary dependencies to be able to build the deps.
_____

### Reproduce:
1. Install a Ubuntu 17.10 environment
2. Install docker-ce
3. Clone laradock
4. `mv env-example .env`
5. `docker-compose up -d nginx mysql phpmyadmin redis laravel-echo-server beanstalkd beanstalkd-console`
6. Observe the failure in the stdout.

_____

### Relevant Code:

https://github.com/laradock/laradock/blob/f7ac8cf8621f071ad3888d55b6ab94dbe85324cf/laravel-echo-server/Dockerfile#L9
```
RUN npm install
```
We should change this to:
```
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base

RUN npm install
```

**Comment by vipinkundal** [comment]
I changed it to
`RUN apk add --update --no-cache curl py-pip`
and it worked

**Comment by Geovanek** [comment]
I have the same problem now.

I solved change de code
``RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base``

To
``RUN apk add --update \
    python3 \
    python3-dev \
    py-pip3 \
    build-base``
