### ISSUE TITLE
docker-compose build workspace

### ISSUE THREAD

**Issue by liezu** [laradock/laradock#1249]
➜  laradock git:(master) ✗ docker-compose build workspace
Building workspace
Step 1/152 : FROM laradock/workspace:1.9-71
 ---> 343e50be369a
Step 2/152 : MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
 ---> Using cache
 ---> ded8cb4d2d78
Step 3/152 : ARG PUID=1000
 ---> Using cache
 ---> f2badffea79b
Step 4/152 : ARG PGID=1000
 ---> Using cache
 ---> f6dddf1ec125
Step 5/152 : ENV PUID ${PUID}
 ---> Using cache
 ---> a029ce282a51
Step 6/152 : ENV PGID ${PGID}
 ---> Using cache
 ---> 9edc24d1b3cf
Step 7/152 : RUN groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock &&     apt-get update -yqq
 ---> Using cache
 ---> bffff7e459c8
Step 8/152 : USER root
 ---> Using cache
 ---> a0339584ef8e
Step 9/152 : ARG INSTALL_SOAP=false
 ---> Using cache
 ---> 73b61ab6c3f1
Step 10/152 : ENV INSTALL_SOAP ${INSTALL_SOAP}
 ---> Using cache
 ---> 4ac8ec53df64
Step 11/152 : RUN if [ ${INSTALL_SOAP} = true ]; then   add-apt-repository -y ppa:ondrej/php &&   apt-get update -yqq &&   apt-get -y install libxml2-dev php7.1-soap ;fi
 ---> Using cache
 ---> d1456b02b9e5
Step 12/152 : ARG INSTALL_LDAP=false
 ---> Using cache
 ---> 2463aff9ae96
Step 13/152 : ENV INSTALL_LDAP ${INSTALL_LDAP}
 ---> Using cache
 ---> 9ac498b0bd57
Step 14/152 : RUN if [ ${INSTALL_LDAP} = true ]; then     apt-get update -yqq &&     apt-get install -y libldap2-dev &&     apt-get install -y php7.1-ldap ;fi
 ---> Using cache
 ---> e80aa7aa0578
Step 15/152 : ARG INSTALL_IMAP=false
 ---> Using cache
 ---> 57d4c8b38104
Step 16/152 : ENV INSTALL_IMAP ${INSTALL_IMAP}
 ---> Using cache
 ---> 1e6db1513001
Step 17/152 : RUN if [ ${INSTALL_IMAP} = true ]; then     apt-get update -yqq &&     apt-get install -y php7.1-imap ;fi
 ---> Using cache
 ---> 69bed5eb94d0
Step 18/152 : ARG TZ=UTC
 ---> Using cache
 ---> bc7b81c9ab3b
Step 19/152 : ENV TZ ${TZ}
 ---> Using cache
 ---> 1959a5791e8d
Step 20/152 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> 22257b5eea8f
Step 21/152 : COPY ./composer.json /home/laradock/.composer/composer.json
 ---> Using cache
 ---> 98ee6ea8d4c1
Step 22/152 : RUN chown -R laradock:laradock /home/laradock/.composer
 ---> Using cache
 ---> 00e05b6ae287
Step 23/152 : USER laradock
 ---> Using cache
 ---> 0e19ab00b487
Step 24/152 : ARG COMPOSER_GLOBAL_INSTALL=false
 ---> Using cache
 ---> 2dbd19a54475
Step 25/152 : ENV COMPOSER_GLOBAL_INSTALL ${COMPOSER_GLOBAL_INSTALL}
 ---> Using cache
 ---> 51fb62cd30f7
Step 26/152 : RUN if [ ${COMPOSER_GLOBAL_INSTALL} = true ]; then     composer global install ;fi
 ---> Using cache
 ---> 44a73fac438f
Step 27/152 : USER root
 ---> Using cache
 ---> 81c65806ecce
Step 28/152 : COPY ./crontab /etc/cron.d
 ---> Using cache
 ---> 3547ff5d55ee
Step 29/152 : RUN chmod -R 644 /etc/cron.d
 ---> Using cache
 ---> b8f297ecd2ab
Step 30/152 : USER laradock
 ---> Using cache
 ---> 350f361dc114
Step 31/152 : COPY ./aliases.sh /home/laradock/aliases.sh
 ---> Using cache
 ---> 902cb5773745
Step 32/152 : RUN echo "" >> ~/.bashrc &&     echo "# Load Custom Aliases" >> ~/.bashrc &&     echo "source /home/laradock/aliases.sh" >> ~/.bashrc && 	echo "" >> ~/.bashrc && 	sed -i 's/\r//' /home/laradock/aliases.sh && 	sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
 ---> Using cache
 ---> c67d28f7789e
Step 33/152 : USER root
 ---> Using cache
 ---> fb0836165356
Step 34/152 : RUN echo "" >> ~/.bashrc &&     echo "# Load Custom Aliases" >> ~/.bashrc &&     echo "source /home/laradock/aliases.sh" >> ~/.bashrc && 	echo "" >> ~/.bashrc && 	sed -i 's/\r//' /home/laradock/aliases.sh && 	sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
 ---> Using cache
 ---> 3339c0ca4fed
Step 35/152 : ARG INSTALL_XDEBUG=false
 ---> Using cache
 ---> 24abd8d6285a
Step 36/152 : RUN if [ ${INSTALL_XDEBUG} = true ]; then     apt-get update &&     apt-get install -y --force-yes php7.1-xdebug &&     sed -i 's/^;//g' /etc/php/7.1/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi
 ---> Using cache
 ---> fe6d11baec82
Step 37/152 : COPY ./xdebug.ini /etc/php/7.1/cli/conf.d/xdebug.ini
 ---> Using cache
 ---> 66b6b22f8a83
Step 38/152 : ARG INSTALL_BLACKFIRE=false
 ---> Using cache
 ---> 80ecaa66cea7
Step 39/152 : ARG BLACKFIRE_CLIENT_ID
 ---> Using cache
 ---> 5a8dab644b64
Step 40/152 : ARG BLACKFIRE_CLIENT_TOKEN
 ---> Using cache
 ---> 318197f1dcdc
Step 41/152 : ENV BLACKFIRE_CLIENT_ID ${BLACKFIRE_CLIENT_ID}
 ---> Using cache
 ---> 965f21f5c7ed
Step 42/152 : ENV BLACKFIRE_CLIENT_TOKEN ${BLACKFIRE_CLIENT_TOKEN}
 ---> Using cache
 ---> 9ae8de6ce08b
Step 43/152 : RUN if [ ${INSTALL_XDEBUG} = false -a ${INSTALL_BLACKFIRE} = true ]; then     curl -L https://packagecloud.io/gpg.key | apt-key add - &&     echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list &&     apt-get update -yqq &&     apt-get install blackfire-agent ;fi
 ---> Using cache
 ---> 4cb0a59ccc6a
Step 44/152 : ARG INSTALL_WORKSPACE_SSH=false
 ---> Using cache
 ---> 19a32d0afb78
Step 45/152 : ENV INSTALL_WORKSPACE_SSH ${INSTALL_WORKSPACE_SSH}
 ---> Using cache
 ---> 535cc61969a4
Step 46/152 : ADD insecure_id_rsa /tmp/id_rsa
 ---> Using cache
 ---> ffd07a9dc13d
Step 47/152 : ADD insecure_id_rsa.pub /tmp/id_rsa.pub
 ---> Using cache
 ---> 08f67e7b9d8c
Step 48/152 : RUN if [ ${INSTALL_WORKSPACE_SSH} = true ]; then     rm -f /etc/service/sshd/down &&     cat /tmp/id_rsa.pub >> /root/.ssh/authorized_keys         && cat /tmp/id_rsa.pub >> /root/.ssh/id_rsa.pub         && cat /tmp/id_rsa >> /root/.ssh/id_rsa         && rm -f /tmp/id_rsa*         && chmod 644 /root/.ssh/authorized_keys /root/.ssh/id_rsa.pub     && chmod 400 /root/.ssh/id_rsa ;fi
 ---> Using cache
 ---> f76e4b873dda
Step 49/152 : ARG INSTALL_MONGO=false
 ---> Using cache
 ---> 869103f63812
Step 50/152 : ENV INSTALL_MONGO ${INSTALL_MONGO}
 ---> Using cache
 ---> e1184401fc4a
Step 51/152 : RUN if [ ${INSTALL_MONGO} = true ]; then     pecl -q install mongodb &&     echo "extension=mongodb.so" >> /etc/php/7.1/mods-available/mongodb.ini &&     ln -s /etc/php/7.1/mods-available/mongodb.ini /etc/php/7.1/cli/conf.d/30-mongodb.ini ;fi
 ---> Using cache
 ---> 220c428198ca
Step 52/152 : ARG INSTALL_PHPREDIS=false
 ---> Using cache
 ---> d6383b3d4942
Step 53/152 : ENV INSTALL_PHPREDIS ${INSTALL_PHPREDIS}
 ---> Using cache
 ---> 016ea225721d
Step 54/152 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl -q install -o -f redis &&     echo "extension=redis.so" >> /etc/php/7.1/mods-available/redis.ini &&     phpenmod redis ;fi
 ---> Using cache
 ---> 491db133d09b
Step 55/152 : USER root
 ---> Using cache
 ---> b13fd2c14146
Step 56/152 : ENV DRUSH_VERSION 8.1.2
 ---> Using cache
 ---> 8b9120b443ca
Step 57/152 : ARG INSTALL_DRUSH=false
 ---> Using cache
 ---> 6be9cf131703
Step 58/152 : ENV INSTALL_DRUSH ${INSTALL_DRUSH}
 ---> Using cache
 ---> a7793ec4e934
Step 59/152 : RUN if [ ${INSTALL_DRUSH} = true ]; then     apt-get update -yqq &&     apt-get -y install mysql-client &&     curl -fsSL -o /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/$DRUSH_VERSION/drush.phar | bash &&     chmod +x /usr/local/bin/drush &&     drush core-status ;fi
 ---> Using cache
 ---> f1e54da8321b
Step 60/152 : USER root
 ---> Using cache
 ---> c8b7626f49ac
Step 61/152 : ARG INSTALL_DRUPAL_CONSOLE=false
 ---> Using cache
 ---> 1bfdaabaf6c7
Step 62/152 : ENV INSTALL_DRUPAL_CONSOLE ${INSTALL_DRUPAL_CONSOLE}
 ---> Using cache
 ---> 93e3a9215c0c
Step 63/152 : RUN if [ ${INSTALL_DRUPAL_CONSOLE} = true ]; then     apt-get update -yqq &&     apt-get -y install mysql-client &&     curl https://drupalconsole.com/installer -L -o drupal.phar &&     mv drupal.phar /usr/local/bin/drupal &&     chmod +x /usr/local/bin/drupal ;fi
 ---> Using cache
 ---> 7e35cdd6b0f1
Step 64/152 : USER laradock
 ---> Using cache
 ---> df72f780084e
Step 65/152 : ARG NODE_VERSION=stable
 ---> Using cache
 ---> eb79c4f46ac5
Step 66/152 : ENV NODE_VERSION ${NODE_VERSION}
 ---> Using cache
 ---> c0fca191eccd
Step 67/152 : ARG INSTALL_NODE=false
 ---> Using cache
 ---> e4be3ea99fdf
Step 68/152 : ENV INSTALL_NODE ${INSTALL_NODE}
 ---> Using cache
 ---> fd29113a6837
Step 69/152 : ENV NVM_DIR /home/laradock/.nvm
 ---> Using cache
 ---> 7808cfbc50ee
Step 70/152 : RUN if [ ${INSTALL_NODE} = true ]; then     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash &&         . $NVM_DIR/nvm.sh &&         nvm install ${NODE_VERSION} &&         nvm use ${NODE_VERSION} &&         nvm alias ${NODE_VERSION} &&         npm install -g gulp bower vue-cli ;fi
 ---> Running in 3ce2be20709b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11388  100 11388    0     0    960      0  0:00:11  0:00:11 --:--:--  2424
=> Downloading nvm from git to '/home/laradock/.nvm'
=> Cloning into '/home/laradock/.nvm'...
* (HEAD detached at v0.33.1)
  master
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/laradock/.profile
=> bash_completion source string already in /home/laradock/.profile
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
Downloading and installing node v9.1.0...
Downloading https://nodejs.org/dist/v9.1.0/node-v9.1.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v9.1.0 (npm v5.5.1)
Creating default alias: default -> stable (-> v9.1.0)
Now using node v9.1.0 (npm v5.5.1)
stable -> 9.1 (-> v9.1.0) (default)
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code EINTEGRITY
npm ERR! sha1-RBT/dKUIecII7l/cgm4ywwNUnto= integrity checksum failed when using sha1: wanted sha1-RBT/dKUIecII7l/cgm4ywwNUnto= but got sha1-9g8q43PWhnQCUvA3IGisi7sN3iI=. (155482 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/laradock/.npm/_logs/2017-11-14T10_26_10_756Z-debug.log
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash &&         . $NVM_DIR/nvm.sh &&         nvm install ${NODE_VERSION} &&         nvm use ${NODE_VERSION} &&         nvm alias ${NODE_VERSION} &&         npm install -g gulp bower vue-cli ;fi' returned a non-zero code: 1

**Comment by for0231** [comment]
**When I add drush and drupalconsole to build, it reports below:**


doe:laradock doe$ docker-compose build workspace
Building workspace
Step 1/158 : ARG PHP_VERSION=${PHP_VERSION}
Step 2/158 : FROM laradock/workspace:2.2-${PHP_VERSION}
 ---> 95b8f4b0dbc9
Step 3/158 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Using cache
 ---> 5a4c150921b4
Step 4/158 : USER root
 ---> Using cache
 ---> d91fb7947bdd
Step 5/158 : ARG PUID=1000
 ---> Using cache
 ---> 0bcca2f1c018
Step 6/158 : ENV PUID ${PUID}
 ---> Using cache
 ---> 5c31cbf4cf7c
Step 7/158 : ARG PGID=1000
 ---> Using cache
 ---> 1534198a9997
Step 8/158 : ENV PGID ${PGID}
 ---> Using cache
 ---> 484e399d28dd
Step 9/158 : RUN groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock
 ---> Using cache
 ---> 2bdda045c4c2
Step 10/158 : ARG TZ=UTC
 ---> Using cache
 ---> 8b5ff4e2672b
Step 11/158 : ENV TZ ${TZ}
 ---> Using cache
 ---> d7a1a5b5ccb3
Step 12/158 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> 1396ecc8d6b0
Step 13/158 : USER root
 ---> Using cache
 ---> 4f610e5e7ccf
Step 14/158 : COPY ./aliases.sh /root/aliases.sh
 ---> Using cache
 ---> a409d07f3eb9
Step 15/158 : COPY ./aliases.sh /home/laradock/aliases.sh
 ---> Using cache
 ---> 67e55d39c0b7
Step 16/158 : RUN sed -i 's/\r//' /root/aliases.sh &&     sed -i 's/\r//' /home/laradock/aliases.sh &&     chown laradock:laradock /home/laradock/aliases.sh &&     echo "" >> ~/.bashrc &&     echo "# Load Custom Aliases" >> ~/.bashrc &&     echo "source ~/aliases.sh" >> ~/.bashrc && 	echo "" >> ~/.bashrc
 ---> Using cache
 ---> 4088a2aed690
Step 17/158 : USER laradock
 ---> Using cache
 ---> b423a1af8d25
Step 18/158 : RUN echo "" >> ~/.bashrc &&     echo "# Load Custom Aliases" >> ~/.bashrc &&     echo "source ~/aliases.sh" >> ~/.bashrc && 	echo "" >> ~/.bashrc
 ---> Using cache
 ---> 49b20b6362bd
Step 19/158 : USER root
 ---> Using cache
 ---> a5d0997b0e7e
Step 20/158 : COPY ./composer.json /home/laradock/.composer/composer.json
 ---> Using cache
 ---> 351271f54377
Step 21/158 : RUN chown -R laradock:laradock /home/laradock/.composer
 ---> Using cache
 ---> 12a1643d2d3e
Step 22/158 : USER laradock
 ---> Using cache
 ---> 32dd97d6f1eb
Step 23/158 : ARG COMPOSER_GLOBAL_INSTALL=false
 ---> Using cache
 ---> cd0636b1b7e5
Step 24/158 : ENV COMPOSER_GLOBAL_INSTALL ${COMPOSER_GLOBAL_INSTALL}
 ---> Using cache
 ---> e624aa3d7167
Step 25/158 : RUN if [ ${COMPOSER_GLOBAL_INSTALL} = true ]; then     composer global install ;fi
 ---> Using cache
 ---> ac314b6015d9
Step 26/158 : ARG COMPOSER_REPO_PACKAGIST
 ---> Using cache
 ---> 48259687f34b
Step 27/158 : ENV COMPOSER_REPO_PACKAGIST ${COMPOSER_REPO_PACKAGIST}
 ---> Using cache
 ---> 54de0bba275d
Step 28/158 : RUN if [ ${COMPOSER_REPO_PACKAGIST} ]; then     composer config -g repo.packagist composer ${COMPOSER_REPO_PACKAGIST} ;fi
 ---> Using cache
 ---> b01e1d4b4e3f
Step 29/158 : RUN echo "" >> ~/.bashrc &&     echo 'export PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc
 ---> Using cache
 ---> 04b97b595ec7
Step 30/158 : USER laradock
 ---> Using cache
 ---> f5f43021814d
Step 31/158 : RUN echo "" >> ~/.bashrc &&     echo 'export PATH="/var/www/vendor/bin:$PATH"' >> ~/.bashrc
 ---> Using cache
 ---> 6fcb0627e2e0
Step 32/158 : USER root
 ---> Using cache
 ---> f76979f23719
Step 33/158 : COPY ./crontab /etc/cron.d
 ---> Using cache
 ---> dcc09f2fd9f3
Step 34/158 : RUN chmod -R 644 /etc/cron.d
 ---> Using cache
 ---> ced7dc3dcbc1
Step 35/158 : USER root
 ---> Using cache
 ---> 71fe5b256288
Step 36/158 : ARG INSTALL_SOAP=false
 ---> Using cache
 ---> 37d83f56dc0a
Step 37/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 6134f5bb1dc4
Step 38/158 : RUN if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${PHP_VERSION}-soap ;fi
 ---> Using cache
 ---> 101f08e113ee
Step 39/158 : ARG INSTALL_LDAP=false
 ---> Using cache
 ---> a716e7c6fa2b
Step 40/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 172ea54df7b8
Step 41/158 : RUN if [ ${INSTALL_LDAP} = true ]; then     apt-get install -y libldap2-dev &&     apt-get install -y php${PHP_VERSION}-ldap ;fi
 ---> Using cache
 ---> b096315df9ef
Step 42/158 : ARG INSTALL_IMAP=false
 ---> Using cache
 ---> 50dff4ff5774
Step 43/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> b08d4d27da8a
Step 44/158 : RUN if [ ${INSTALL_IMAP} = true ]; then     apt-get install -y php${PHP_VERSION}-imap ;fi
 ---> Using cache
 ---> 38a37a7bf19d
Step 45/158 : USER root
 ---> Using cache
 ---> 46fd2615af4d
Step 46/158 : ARG INSTALL_XDEBUG=false
 ---> Using cache
 ---> cdf07c358cca
Step 47/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 7138ccdf7a4b
Step 48/158 : RUN if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y --force-yes php${PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi
 ---> Using cache
 ---> 1095b94f87d1
Step 49/158 : COPY ./xdebug.ini /etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini
 ---> Using cache
 ---> 780cf0643d7d
Step 50/158 : ARG INSTALL_BLACKFIRE=false
 ---> Using cache
 ---> 0dd0fcfeff6c
Step 51/158 : ARG BLACKFIRE_CLIENT_ID
 ---> Using cache
 ---> 7442a6eb006d
Step 52/158 : ENV BLACKFIRE_CLIENT_ID ${BLACKFIRE_CLIENT_ID}
 ---> Using cache
 ---> 4579228f59b6
Step 53/158 : ARG BLACKFIRE_CLIENT_TOKEN
 ---> Using cache
 ---> ffcf50ae647e
Step 54/158 : ENV BLACKFIRE_CLIENT_TOKEN ${BLACKFIRE_CLIENT_TOKEN}
 ---> Using cache
 ---> ef42e11255c9
Step 55/158 : RUN if [ ${INSTALL_XDEBUG} = false -a ${INSTALL_BLACKFIRE} = true ]; then     curl -L https://packagecloud.io/gpg.key | apt-key add - &&     echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list &&     apt-get update -yqq &&     apt-get install blackfire-agent ;fi
 ---> Using cache
 ---> deee3819ee1f
Step 56/158 : ARG INSTALL_WORKSPACE_SSH=false
 ---> Using cache
 ---> bfcdf8a70b2c
Step 57/158 : COPY insecure_id_rsa /tmp/id_rsa
 ---> Using cache
 ---> 41e1341d7a4b
Step 58/158 : COPY insecure_id_rsa.pub /tmp/id_rsa.pub
 ---> Using cache
 ---> c29d5e6280e1
Step 59/158 : RUN if [ ${INSTALL_WORKSPACE_SSH} = true ]; then     rm -f /etc/service/sshd/down &&     cat /tmp/id_rsa.pub >> /root/.ssh/authorized_keys         && cat /tmp/id_rsa.pub >> /root/.ssh/id_rsa.pub         && cat /tmp/id_rsa >> /root/.ssh/id_rsa         && rm -f /tmp/id_rsa*         && chmod 644 /root/.ssh/authorized_keys /root/.ssh/id_rsa.pub     && chmod 400 /root/.ssh/id_rsa     && cp -rf /root/.ssh /home/laradock     && chown -R laradock:laradock /home/laradock/.ssh ;fi
 ---> Using cache
 ---> 9b0da886f6b5
Step 60/158 : ARG INSTALL_MONGO=false
 ---> Using cache
 ---> 0140ea2cbcc8
Step 61/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 04779eb325c6
Step 62/158 : RUN if [ ${INSTALL_MONGO} = true ]; then     pecl -q install mongodb &&     echo "extension=mongodb.so" >> /etc/php/${PHP_VERSION}/mods-available/mongodb.ini &&     ln -s /etc/php/${PHP_VERSION}/mods-available/mongodb.ini /etc/php/${PHP_VERSION}/cli/conf.d/30-mongodb.ini ;fi
 ---> Using cache
 ---> 66084f92b7ee
Step 63/158 : ARG INSTALL_AMQP=false
 ---> Using cache
 ---> e049fa692fe0
Step 64/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 53c24f29c818
Step 65/158 : RUN if [ ${INSTALL_AMQP} = true ]; then     apt-get install librabbitmq-dev -y &&     pecl -q install amqp &&     echo "extension=amqp.so" >> /etc/php/${PHP_VERSION}/mods-available/amqp.ini &&     ln -s /etc/php/${PHP_VERSION}/mods-available/amqp.ini /etc/php/${PHP_VERSION}/cli/conf.d/30-amqp.ini ;fi
 ---> Using cache
 ---> 32282f605228
Step 66/158 : ARG INSTALL_PHPREDIS=false
 ---> Using cache
 ---> d39879b31ec0
Step 67/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 3ae7cbf8a89c
Step 68/158 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl -q install -o -f redis &&     echo "extension=redis.so" >> /etc/php/${PHP_VERSION}/mods-available/redis.ini &&     phpenmod redis ;fi
 ---> Using cache
 ---> 6ff820bb03ed
Step 69/158 : ARG INSTALL_SWOOLE=false
 ---> Using cache
 ---> 25b3b5cdde48
Step 70/158 : ARG PHP_VERSION=${PHP_VERSION}
 ---> Using cache
 ---> 5aeb1e33c08a
Step 71/158 : RUN if [ ${INSTALL_SWOOLE} = true ]; then     pecl -q install swoole &&     echo "extension=swoole.so" >> /etc/php/${PHP_VERSION}/mods-available/swoole.ini &&     ln -s /etc/php/${PHP_VERSION}/mods-available/swoole.ini /etc/php/${PHP_VERSION}/cli/conf.d/20-swoole.ini ;fi
 ---> Using cache
 ---> c3a016edbce4
Step 72/158 : USER root
 ---> Using cache
 ---> e6907008602f
Step 73/158 : ARG INSTALL_DRUSH=false
 ---> Using cache
 ---> 6e8f38609676
Step 74/158 : RUN if [ ${INSTALL_DRUSH} = true ]; then     apt-get -y install mariadb-client &&     curl -fsSL -o /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar | bash &&     chmod +x /usr/local/bin/drush &&     drush core-status ;fi
 ---> Running in ff3e169a6ef1
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libaio1 libdbd-mysql-perl libdbi-perl libmysqlclient20 libreadline5
  libterm-readkey-perl mariadb-client-10.0 mariadb-client-core-10.0
  mariadb-common mysql-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl
The following NEW packages will be installed:
  libaio1 libdbd-mysql-perl libdbi-perl libmysqlclient20 libreadline5
  libterm-readkey-perl mariadb-client mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mysql-common
0 upgraded, 11 newly installed, 0 to remove and 28 not upgraded.
Need to get 7,277 kB of archives.
After this operation, 52.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libaio1 amd64 0.3.110-2 [6,356 B]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libdbi-perl amd64 1.634-1build1 [743 kB]
Err:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-common all 5.7.21-0ubuntu0.16.04.1
  404  Not Found [IP: 91.189.88.152 80]
Ign:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libmysqlclient20 amd64 5.7.21-0ubuntu0.16.04.1
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 libdbd-mysql-perl amd64 4.033-1ubuntu0.1 [84.3 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/main amd64 libreadline5 amd64 5.2+dfsg-3build1 [99.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libterm-readkey-perl amd64 2.33-1build1 [27.2 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 mariadb-common all 10.0.34-0ubuntu0.16.04.1 [16.0 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 mariadb-client-core-10.0 amd64 10.0.34-0ubuntu0.16.04.1 [4,289 kB]
Err:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 mysql-common all 5.7.21-0ubuntu0.16.04.1
  404  Not Found [IP: 91.189.88.152 80]
Err:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libmysqlclient20 amd64 5.7.21-0ubuntu0.16.04.1
  404  Not Found [IP: 91.189.88.152 80]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 mariadb-client-10.0 amd64 10.0.34-0ubuntu0.16.04.1 [1,173 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 mariadb-client all 10.0.34-0ubuntu0.16.04.1 [13.0 kB]
Fetched 6,452 kB in 9s (686 kB/s)
**E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-common_5.7.21-0ubuntu0.16.04.1_all.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient20_5.7.21-0ubuntu0.16.04.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_DRUSH} = true ]; then     apt-get -y install mariadb-client &&     curl -fsSL -o /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar | bash &&     chmod +x /usr/local/bin/drush &&     drush core-status ;fi' returned a non-zero code: 100**

**Comment by michaelwzk** [comment]
I have a same problem?  How can i do it


=> Appending nvm source string to /home/laradock/.bashrc
=> Appending bash_completion source string to /home/laradock/.bashrc
=> Installing Node.js version node
Downloading and installing node v11.13.0...
Downloading https://nodejs.org/dist/v11.13.0/node-v11.13.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v11.13.0 (npm v6.7.0)
Creating default alias: default -> node (-> v11.13.0)
=> Node.js version node has been successfully installed
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
v11.13.0 is already installed.
Now using node v11.13.0 (npm v6.7.0)
Now using node v11.13.0 (npm v6.7.0)
node -> stable (-> v11.13.0) (default)
npm ERR! Unexpected end of JSON input while parsing near '...8c866","tarball":"htt'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/laradock/.npm/_logs/2019-04-04T14_06_58_480Z-debug.log
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi' returned a non-zero code: 1

**Comment by jasperf** [comment]
Did you try `docker-compose build --no-cache workspace` yet?
