### ISSUE TITLE
Send Email on production via mail or sendmail

### ISSUE THREAD

**Issue by samarhaider** [laradock/laradock#1250]
What configuration need to be set in .env file for sending mail on production.
When I set below, its working perfectly
```
MAIL_DRIVER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
```
So, What configuration needed for production

**Comment by rick20** [comment]
have you solve this issue?

**Comment by neomobil** [comment]
If you use an smtp server than take the host and the from that. 📫 Otherwise you can use mail too.
