### ISSUE TITLE
Horizontal scale PHP-FPM/Nginx

### ISSUE THREAD

**Issue by fosron** [laradock/laradock#1258]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): 48a0c4b878b9085140849c93776a20905ff00188
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.13.1 (17B48)

### Issue:

Is there a way to properly use `scale` option of docker-compose on laradock? I'm doing some CPU-Intensive tasks and i think scaling at-least PHP-FPM would help with that. The question is how to do that properly with laradock?

**Comment by CeddyG** [comment]
Hi,

`sudo docker-compose up --scale php-fpm=3 -d nginx`

Does it work ?

**Comment by fosron** [comment]
It just adds the instances, but nginx config will still not point to them?

**Comment by CeddyG** [comment]
You can use gethostname() somewhere in your code to check.

In a view : 

`{{ gethostname() }}`

You can see different values when you refresh your page and see the Container ID.

**Comment by fosron** [comment]
Is it going to point to different nginx instances, even if there's no config for that?

**Comment by CeddyG** [comment]
Yes, you can see it by using gethostname().

**Comment by andersonpem** [comment]
I had quite some time searching why this behavior works out of the box.
When you scale a named service, Docker does a "Round-robin DNS A Record" in the pool of available containers for that specific service. It chooses one of the available containers and serve its IP when you call the service by its name.
More info about that in the "Discovering containers on the same service or stack" part of the service discovery documentation of Docker:
https://docs.docker.com/docker-cloud/apps/service-links/#discovering-containers-on-the-same-service-or-stack
