### ISSUE TITLE
npm run watch not rebuild after file change

### ISSUE THREAD

**Issue by superbull** [laradock/laradock#1259]
### Info:
- Docker version (`$ docker --version`): 17.09.0
- Laradock commit (`$ git rev-parse HEAD`): 9877f0453ef5d1c8f556403804f8f21df2618de6
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.13.1

### Issue:
I am running a laravel project, after execute `npm run watch`, the frontend build successfully, but after file changes it is not rebuild.
_____

### Reproduce:
1. docker-compose up -d nginx postgres adminer
2. docker-compose exec --user=laradock workspace bash
3. npm run watch

**Comment by lbavendanos** [comment]
test running `npm run watch-poll`

**Comment by superbull** [comment]
@lbavendanos Thanks, this works for me.

Some more information about this:
https://laravel.com/docs/5.4/mix#running-mix
https://webpack.js.org/configuration/watch/#watchoptions-poll

**Comment by superbull** [comment]
But when I using polling the fan of my MAC becomes very noisy. Below is the screen shot of my activity monitor:
<img width="446" alt="screen shot 2017-11-19 at 4 24 49 pm" src="https://user-images.githubusercontent.com/455630/32992071-98e69f66-cd46-11e7-9ab5-ae241e04ca2b.png">
The energy impact of docker jump from **4** to more than **400*.

I decide to run `npm run watch` locally in my MAC.

**Comment by lbavendanos** [comment]
@superbull The same thing also happens to me.

Observing the webpack configuration, it gives us the option to exclude a large folder as `node_modules` with the option` watchOptions.ignored`.
https://webpack.js.org/configuration/watch/#watchoptions-ignored

Therefore, it should be added in `webpack.mix.js` file:
```
mix.webpackConfig({
    watchOptions: {
        ignored: /node_modules/
    }
});
```
this would reduce the excess CPU and memory usage by using the commands `npm run watch` and `npm run watch-poll` in docker.

**Comment by superbull** [comment]
Yes, that's significantly reduced the CPU usage. Thanks.

I thought ignore `node_modules` should be configured in Laravel by default.

**Comment by lcdss** [comment]
I have a similar problem: I access the workspace and run `yarn run dev` which runs at localhost:3000, but I'm unable to access it from the host machine or others containers, even after I have exposed the port 3000 and opened the port 3000 in the docker-compose.yml file.
@superbull How are you accessing it from the host OS?

**Comment by superbull** [comment]
@lcdss Sorry, I cannot answer your question. Because I just run `npm run watch` to **build** the assets, not **serve** them.

**Comment by lcdss** [comment]
@superbull No problem. I already solve my problem changing the listening address to 0.0.0.0 instead of localhost or 127.0.0.1.

**Comment by luongs3** [comment]
@lcdss could you tell me more detail, what do you mean when say " changing the listening address to 0.0.0.0 instead of localhost or 127.0.0.1"

**Comment by eblanshey** [comment]
Ignoring the node_modules directory does not lower my CPU usage unfortunately. Docker uses 50% CPU and fans run on max. Has anyone else been able to find a solution on Docker for Mac and running watch or watch-poll successfully?

**Comment by connor11528** [comment]
I am getting a different error when trying to have webpack watch my Vue files:

```
$ docker-compose exec workspace bash
/var/www# npm run watch
bash: npm: command not found
```
Is there some config I need to set up for the laradock environment?

**Comment by meckyblaze** [comment]
> test running `npm run watch-poll`

This worked for me

**Comment by henryonsoftware** [comment]
I wonder why `npm run watch` doesn't work but `npm run watch-poll` does

**Comment by academicbridge-apps** [comment]
@henryonsoftware check this answer on stackoverflow [Difference between npm run watch and npm run watch-poll](https://stackoverflow.com/a/44127901/13490128)

**Comment by amav96** [comment]
i cant make work npm run watch-poll
mi docker-compose-yml

`version: "3.7"
services:
    nginx_smart:
        image: nginx:stable-alpine
        container_name: nginx_smart
        ports:
            - "8000:80"
            # puerto-local:puerto-container
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app_smart
            - mysql
        networks:
            - larvel-network

    app_smart:
        build:
            args:
                user: laraveluser
                uid: 1000
            context: .
            dockerfile: ./Dockerfile
        container_name: app_smart
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - larvel-network
#  Redis Server
    redis:
        image: redis:alpine
        container_name: redis_smart
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
        networks:
            - larvel-network
# MySql server
    mysql:
        image: mysql:8.0
        container_name: mysql_smart
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - larvel-network`

nginx config

`server {
  listen 80;
  index index.php index.html;
  server_name localhost;
  error_log /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
  root /var/www/html/public;


  location ~ \.php$ {
    try_files $uri = 404;
    fastcgi_split_path_info ^(.+\.php)(/.+$);
    fastcgi_pass app_smart:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
  }
} 
`

webpack.mix.js

`mix.webpackConfig({
    devServer: {
        host: '0.0.0.0',
        port: 8000,
        static: false,
    },
});`

can some see any errors?

docker +  laravel and vue + redis + mysql

only work when i make f5 to reload page, but not work hot reload
