### ISSUE TITLE
Sequel Pro stops working after running Laravel Migration successfully

### ISSUE THREAD

**Issue by huuvan20** [laradock/laradock#1261]
### Info:
- Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): f7ac8cf8621f071ad3888d55b6ab94dbe85324cf
- System info (Mac, PC, Linux): Mac
- System info disto/version: MacBook Pro (Retina, 13-inch, Early 2015)

### Issue:
Hi, I'm working on Laravel 5.5, the development environment is Laradock & Sequel Pro is to connect to a MySQL server on Laradock.

The weird thing is that after I run the migration command which is 
``$ php artisan migrate``

I turn to **Sequel Pro** to connect to the DB but I cannot. 

My DB name is **odot** & whenever I clicked on it to access, the Sequel Pro was not showing data at all & it kept loading data.

I have checked that the tables were created successfully. The Laravel app could write & read records into DB properly.

Before running ``$ php artisan migrate``, I could connect to the DB using Sequel Pro & worked with it properly.

As I have experienced so far, this is not corrupt the DB. I just cannot using Sequel Pro to work with the DB.

P/s: I have tried to access that same DB using MySQL Workbench but no hopes. This corrupts the MySQL Workbench also.
_____

### Expected behavior:
I expect the Sequel Pro be able to connect to **odot** DB & I could manage to write/adjust entries to/in DB **odot**
_____

### Reproduce:
Run the migration command which is ``$ php artisan migrate``, & try to use Sequel Pro to connect to DB, manage to change/adjust entries
_____

### Relevant Code:
``$ php artisan migrate``

// place a code sample here
``$ php artisan migrate``

**Comment by mrusho** [comment]
Having the same problem. Found this over at Sequel Pro:
[https://github.com/sequelpro/sequelpro/issues/2699](url)

Changed my config to use MySQL 5.7 and now it works without any problems.

`### MYSQL ##############################################################################################################

MYSQL_VERSION=5.7
MYSQL_DATABASE=development
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d`

**Comment by martynishin** [comment]
@huuvan20 Hi! Do you solved this problem? I have the same problem after run migration and try to open my DB in sequel pro. In phpmyadmin or MySQL Workbench I can open my DB without problem.

**Comment by huuvan20** [comment]
Hi Martynishin, I play the safe way to come back to MySQL 5.7 which is working properly.
Not knowing if this is Sequel Pro problem or Laradock problem. T_T
