### ISSUE TITLE
Containers being removed each restart

### ISSUE THREAD

**Issue by makapaka23** [laradock/laradock#1263]
### Info:
- Docker version (`17.09.0-ce-win33 (13620)`): 
- System info ( PC ): 
- System info disto/version: 

### Issue:
Every time I restart my PC, docker itself doesn't start correctly - it throws some errors, but that is not the problem.  Usually I just exit it, restart it and it runs fine.  At that point I have to restart the laradock containers, which has been also fine. 

However just the last couple of days it seems that every restart with the above workflow is actually removing the containers such that my mysql container is lost and I have to rebuild. Pain!
_____

### Expected behavior:
Containers should not be removed.
_____

### Reproduce:
Not sure.

Really I just need to know why this might happen - is anyone else seeing it, and should I be raising issue with Docker itself or is it Laradock issue that would be removing containers ? As I said, while not ideal, the docker crash previously would at least not delete the containers so not a big deal really.  Obviously, losing my DB IS.
_____

**Comment by scaule** [comment]
Do you use ./sync.sh down ? this command do docker-compose down and this delete all containers.

**Comment by makapaka23** [comment]
no i'm not doing anything down myself - its simply in the process of rebooting windows

**Comment by saulo-silva** [comment]
I have the same problem.

**Comment by abstractk** [comment]
+1
