### ISSUE TITLE
 ls

### ISSUE THREAD

**Issue by benjolsen** [laradock/laradock#1264]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by scaule** [comment]
@benjolsen weird ticket here, what's the problem ?

**Comment by Mahmoudz** [comment]
>
