### ISSUE TITLE
Is the loading of the .env file the syntax of docker-compose?

### ISSUE THREAD

**Issue by uighurbabbage** [laradock/laradock#1267]
I'm a newbie to docker,Recently, the company is ready to use docker，We just met laradock and decided to use it。
But in the process of learning, always want to understand the mechanism of docker-compose loading .Env files？
So what I want to ask is, how do variables in docker-compose relate to .Evn files?
I can't find the relevant content in the docker and docker-compose related documents, so this should not belong to the docker or docker-compose syntax？

**Comment by Oleg-Arkhipov** [comment]
https://docs.docker.com/compose/env-file/

**Comment by uighurbabbage** [comment]
3Q
