### ISSUE TITLE
ERROR: .IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by xiaolony** [laradock/laradock#1268]
> docker-compose up -d nginx mysql phpmyadmin

get:

> ERROR: .IOError: [Errno 2] No such file or directory: u'.\\docker-compose.yml:docker-compose.dev.yml'

why?thanks

**Comment by uighurbabbage** [comment]
Do you order that you execute it under the laradoc project?

**Comment by codebykyle** [comment]
I also get this error, following the documentation on the documentation website. I am running Windows 10 with docker on hyper-v, on an existing laravel project. I added the git sub-module, and tried to run the command from documentation:

![image](https://user-images.githubusercontent.com/26160129/33169844-b5f08786-d078-11e7-8f45-71d969f842f6.png)

**Comment by uighurbabbage** [comment]
It won't be windows10 environmental problems。
I didn't have this problem at Mac, centos7.4, and ubuntu16.04。
Are you sure that there are two files docker-compose.yml and docker-compose-dev.yml in the directory that executes this command in person, and if this is available, see if the docker version is low, and if this is not, it's likely to be a windows10 environmental problem

**Comment by codebykyle** [comment]
The file is there
![image](https://user-images.githubusercontent.com/26160129/33170121-b32d6752-d079-11e7-896f-4c742685a688.png)

The docker version is 17.09.0-ce-win33 stable release, which I believe is the current stable release provided by docker. 
![image](https://user-images.githubusercontent.com/26160129/33170138-c9be772c-d079-11e7-978f-8d68a5c27153.png)

I have no issues running other docker containers. I do not believe this to be directly a windows 10 environmental problem.

**Comment by codebykyle** [comment]
I also tried this in powershell just to be sure. I receive the same error, while the file is discoverable in the directory by hitting tab 
![image](https://user-images.githubusercontent.com/26160129/33170352-a27d6a5a-d07a-11e7-91a9-df3fdccd1b0d.png)

**Comment by uighurbabbage** [comment]
The same version, I don't have this problem, that estimate is windows10 environmental problems, you try to use virtual machine installed linux environment to play。

**Comment by codebykyle** [comment]
Sorry, I'm really looking to use this on windows, since my development environment requires use of specific windows programs. Docker should be able to run on Windows alright. Additionally, the documentation discusses use on Windows, which leads me to believe Laradock should be able to run just as well regardless of the platform.

There is something specific going on here. I will look into this and report back if I find any solution to the problem.

**Comment by codebykyle** [comment]
Removing the `:` in the COMPOSE_FILE will let me run docker-compose up:

Doesn't work:
`COMPOSE_FILE=docker-compose.yml:docker-compose.dev.yml`

Works:
`COMPOSE_FILE=docker-compose.yml`

**Comment by cornelius-agrippa** [comment]
Windows doesn't seem to like `:` very much. I had the same problem. Using `;` instead, worked ok.

`COMPOSE_FILE=docker-compose.yml;docker-compose.dev.yml`

**Comment by francoisfaubert** [comment]
There's no hint it would work on Unix [in the documentation](https://docs.docker.com/compose/reference/envvars/#compose_file). When building maybe Laradock could figure the OS context and change `COMPOSE_PATH_SEPARATOR` accordingly, but seems like a lot of work for a small gain.

I personally feel you can get away by explaining it in `.env-example`. I'll send a PR doing just that and see what happens.

**Comment by jeff-h** [comment]
See https://github.com/laradock/laradock/pull/1265
