### ISSUE TITLE
Building nginx - Dockerfile parse error

### ISSUE THREAD

**Issue by tomasyhy** [laradock/laradock#1271]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): e779bf96ab13fff59f64f8928abc01c5e85f9ecc
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04

### Issue:

When building nginx container I get following error:

**Building nginx
ERROR: Dockerfile parse error line 13: unknown instruction: ;FI**

Even if variable CHANGE_SOURCE is set to false in my .env file
_____

### Expected behavior:

Container sholud build properly
_____

### Reproduce:

docker-compose up -d nginx
_____

### Relevant Code:

```
ARG CHANGE_SOURCE=false
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from dl-cdn.alpinelinux.org to aliyun source
    RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories
;fi

```

**Comment by rei-nfk** [comment]
I have the same error as you. Do you have any idea to avoid this problem?

**Comment by tigo-di** [comment]
For now, comment and it will works

#RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from dl-cdn.alpinelinux.org to aliyun source
    # RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories
#;fi

**Comment by rei-nfk** [comment]
> tigo-di, Thank you very much for your awesome advice!!! You saved my day!!

**Comment by mro1127** [comment]
My way：
```
RUN if [ ${CHANGE_SOURCE} = true ]; then 
 Change application source from dl-cdn.alpinelinux.org to aliyun source
 RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories ;fi
```

**Comment by rickkuilman** [comment]
I've got the same issue, on Ubuntu 17.10

**Comment by x8core** [comment]
Same on Mac.

**Comment by EnnioSimoes** [comment]
Missed a "\" on the line above "; fi"

RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from dl-cdn.alpinelinux.org to aliyun source
    RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
;fi

**Comment by stueynet** [comment]
Sorry guys I am new to this. What is the fix? Which file do we do it in? The only reference I have to `CHANGE_SOURCE` is in `laradock/.env`. Do I replace that with @EnnioSimoes suggestion? Also then do we have to rebuild or something?

**Comment by stueynet** [comment]
Sorry just to clarify this should be changed in `/laradock/nginx/Dockerfile`

**Comment by aComputerGeek** [comment]
My way：
```
ARG CHANGE_SOURCE=false
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from dl-cdn.alpinelinux.org to aliyun source
     sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories; \
fi
```

**Comment by danaia** [comment]
We installing Laradock using a automated install shell script from a clean Ubunutu 16.04 instance and this is the only issue we have during the complete provisioning. Would like like to avoid manual labor here if this is an easy fix.

**Comment by gclove** [comment]
Same issues.

**Comment by danaia** [comment]
I just forked the master and fixed the issue. No biggie.

**Comment by matt-pinder** [comment]
Occurring to me also

**Comment by codeitlikemiley** [comment]
same also here need this to be fix on master and push the fix
