### ISSUE TITLE
Mysql build error

### ISSUE THREAD

**Issue by itarafath** [laradock/laradock#1272]
### Info:
- Docker version : 17.09.0-ce, build afdb6d4 
- Laradock commit :  e779bf96ab13fff59f64f8928abc01c5e85f9ecc
- System info : Linux 
- System info distro/version: Ubuntu 17.10

### Issue:
Im getting an error when run 
`$ docker-compose up -d nginx mysql`
The error is
`ERROR: Service 'mysql' failed to build: failed to register layer: symlink ../1ce44ddccd898a2513b63fa6ba4f2de6e04daaedf2a7686edd543426996a4060/diff /var/lib/docker/overlay2/l/ZCQCILMEGY5T3FQH6U4HKQQTJB: no such file or directory`

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by fengjianfei** [comment]
i have the same problem ,do you fix it yet?
