### ISSUE TITLE
Oracle Interface or oci8 support by default

### ISSUE THREAD

**Issue by richcoremedia** [laradock/laradock#1274]
### Idea:
Hi,

Nice to have this (LARADOCK). I would like to suggestion an idea it would be great to have oci8 support module by default for php/laravel and this feature is helpful to quick start development in enterprise level.

Thanks.

**Comment by whfamily2006** [comment]
1+

**Comment by tobysommer** [comment]
Hi and thanks a lot for this great project!

Any chance to get the OCI8 support into the official laradock?

**Comment by MgHtinLynn** [comment]
1+
