### ISSUE TITLE
Documentation suggestion: docker-compose exec

### ISSUE THREAD

**Issue by slava-vishnyakov** [LaraDock/laradock#129]
Maybe you should replace:

```
docker exec -it {Workspace-Container-Name} bash
Replace {Workspace-Container-Name} with your Workspace container name. 
To find the containers names type docker-compose ps.
```

with simple:

```
docker-compose exec workspace bash
```

Also, below

```
Enter a Container (SSH into a running Container)

1 - first list the current running containers with docker ps

2 - enter any container using:

docker exec -it {container-name} bash
```

with 

```
docker-compose exec {service-name} bash
```

And a few other places where `-it` appears

**Comment by AminMkh** [comment]
so docker toolbox and docker native for windows/mac still doesn't support this, it's still under development, but yeah it works under docker for linux. A couple of pull requests been opened for this feature too!

**Comment by slava-vishnyakov** [comment]
I'm not sure what Docker "Native" is, but if it is Docker for Mac (beta) - it seem to support it:

![image](https://cloud.githubusercontent.com/assets/817931/16706904/95361742-45c6-11e6-8296-71e2368b6ab6.png)

**Comment by slava-vishnyakov** [comment]
And previously I had Docker Toolbox on Mac - and it definitely supported this command.

**Comment by AminMkh** [comment]
On docker for windows using Hyper-v

```
$ docker-compose exec web bash
Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose exec`.
```

**Comment by AminMkh** [comment]
#95 #115

**Comment by Mahmoudz** [comment]
closed by LaraDock v4
