### ISSUE TITLE
The /var/www folder do not has my own projects, only laravel

### ISSUE THREAD

**Issue by ikingye** [laradock/laradock#1290]
### Info:
- Docker version (`$ docker --version`): Version 17.09.0-ce-win33 (13620)
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): PC
- System info disto/version: windows10

### Issue:
The project folder do not map to workspace. And i exec workspace bash, the /var/www folder only contain laradock, no my-projects at all.

_____

### Expected behavior:
My folder structure should look like this
+ laradock
+ project-a
+ project-b
+ project-c

So I expect when I run 'docker-compose exec workspace bash', and my project in /var/www/project-a, /var/www/project-b...
_____

### Reproduce:

I did it on the other PC, and it turned out the same problem.

PS, I did everything OK two days before, and I pretty sure I did not upgrade docker or laradock.
The only thing I did is change laradock to laradock-myprj.
And when things gone wrong, I change it back, but it didn't make that right again. 
I rm all the containers and images, and run 'docker-compose up -d mysql workspace' from the very beginning, but the problem remains.
_____

### Relevant Code:

Yes, I see this(https://github.com/laradock/laradock/issues/1026) and this(https://github.com/laradock/laradock/issues/696)
But they didnot help. My .env file has the setting: COMPOSE_CONVERT_WINDOWS_PATHS=1

Any help is appreciated.

**Comment by ikingye** [comment]
someone help?

**Comment by ikingye** [comment]
Upgrading docker to Version 17.09.1-ce-win42 (14687), then anything works just fine...

**Comment by kenichi1985** [comment]
Docker version ($ docker --version): 17.12.0-ce, build c97c6d6
Laradock commit ($ git rev-parse HEAD): acbe7160d9680dd77b801b8df12300da6ab08d45
System info (Mac, PC, Linux): PC
System info disto/version: windows10

Hi all, I still have the same issue that couldn't see my project folder.

![image](https://user-images.githubusercontent.com/20855190/37562584-8708af50-2ac0-11e8-8934-d8934338fd9c.png)

**Comment by ikingye** [comment]
I encounter this problem again. 
And I have no idea what is the reason.
Sicking of Docker-for-Windows more and more often..

**Comment by smuzammilali** [comment]
I'm also facing the exact same issue on my Windows 10 home using Docker Toolbox :
![2018-05-05_1702](https://user-images.githubusercontent.com/24757934/39667524-2143a76a-5086-11e8-9bd4-b8b4bbec0b30.png)

I have another machine having Windows 10 Pro and everything works perfectly Using Docker Client for pro with he same setup.

Looks like must be something related to Toolbox and Windows Home

**Comment by VladislavYurgel** [comment]
Yeah, i have the same issues too if i run docker-compose via **WSL (bash)**. I mean laradock folder in the workspace container.
But if i run docker-compose via **windows power shell (admin)** then it works perfectly, but slowly.

**Comment by eleftrik** [comment]
Some problem here, on Windows 10 Pro with Docker Version 18.05.0-ce-win67 (18263).

In my case, I have this folders:

```
application
application\.docker

```
`application` contains the Laravel application; sufolder `.docker` contains Laradock files.

```
cd .docker
docker-compose up -d nginx mariadb workspace
docker-compose run workspace bash
```

Once inside workspace container, if I run `ls -la` I got 

```
root@fa27bd542745:/var/www# ls -al
total 4
drwxr-xr-x 3 root root   60 Jul 10 11:26 .
drwxr-xr-x 1 root root 4096 Apr 10 13:59 ..
drwxr-xr-x 6 root root  120 Jul 10 11:26 .docker
root@fa27bd542745:/var/www#

```

**Comment by eleftrik** [comment]
@smuzammilali 

> Looks like must be something related to Toolbox and Windows Home

I don't think so, because I'm using Docker (not Toolbox) with Windows 10 Pro and I got the same result as you.
Did you solve it?

**Comment by boxcc** [comment]
try reset docker Shared Drivers. I fix this problem

**Comment by eleftrik** [comment]
Thank you very much @boxcc, you made my day!
Resetting docker shared drivers worked like a charm.

**Comment by aoltra** [comment]
> I'm also facing the exact same issue on my Windows 10 home using Docker Toolbox :
> ![2018-05-05_1702](https://user-images.githubusercontent.com/24757934/39667524-2143a76a-5086-11e8-9bd4-b8b4bbec0b30.png)
> 
> I have another machine having Windows 10 Pro and everything works perfectly Using Docker Client for pro with he same setup.
> 
> Looks like must be something related to Toolbox and Windows Home

**Comment by aoltra** [comment]
@smuzammilali I've had the same problem but I think I've found a fix.

1. Make sure you are installing in your folder user.
2. Check in Kitematic if, for your container, the local folder of the defined volumes is set.

**Comment by xzs1994** [comment]
@eleftrik can you help me to fix the problem you've fixed? my computer is windows-Home-Basic, so i use docker-toolbox to run the docker, now i can't find how to reset docker Shared Drivers, that's bad.

**Comment by eleftrik** [comment]
> @eleftrik can you help me to fix the problem you've fixed? my computer is windows-Home-Basic, so i use docker-toolbox to run the docker, now i can't find how to reset docker Shared Drivers, that's bad.

Sorry @xzs1994, I gave up with Laradock and moved to Lando.

**Comment by judgej** [comment]
For those coming here looking for a solution for Windows 7, the action of "resetting the docker shared drives" is done on the VM. It's the drives that the host machine shares with the VM, most likely in VirtualBox. There is a write-up on how to do this here:

http://support.divio.com/en/articles/646695-how-to-use-a-directory-outside-c-users-with-docker-toolbox-docker-for-windows

**Comment by devengvengg** [comment]
I Found a Solution That Works For Me (I've install Laravel with Docker :
 https://gist.github.com/ijaureguialzo/bf10504c742b44122ba62bfafe772c1c 

For repair this problem with the /var/www 

STEP 1:  
$pico ~/Documentos/laravel/laradock/.env

 ######## EDIT ##########
APP_CODE_PATH_HOST=../
########################

STEP 2:  BUILD AGAIN:
$sudo docker-compose up -d --build nginx mariadb phpmyadmin workspace;

CHECK:
------------
#RELOAD - Docker
$sudo docker-compose restart nginx; sudo docker-compose restart mariadb; sudo docker-compose restart phpmyadmin; sudo docker-compose restart workspace;

# See:
$cd ~/Documentos/laravel/laradock
$docker-compose exec workspace /bin/bash
$ls   


Now i have in /var/www   ;  app laradock
