### ISSUE TITLE
Left and Right padding problem in Laradock vs Homestead

### ISSUE THREAD

**Issue by jeffreyliim** [laradock/laradock#1291]
### Issue:
Hi, I have a left and right padding issue when using my project in Laradock, where both padding sides of the page seems to be more, as compared to using homestead for my project. It doesn't seem like a homestead issue though. Can anyone help me out on this?

### Homestead
<img width="1261" alt="homestead" src="https://user-images.githubusercontent.com/19368718/33526824-67e7f0bc-d7fb-11e7-927d-e487da4d87ba.png">

### Laradock
<img width="1263" alt="laradock" src="https://user-images.githubusercontent.com/19368718/33526833-7fb54316-d7fb-11e7-95bf-884c62d86a6a.png">

**Comment by massimoselvi** [comment]
show the 2 html(s) the second looks like it's Bootstrap grid container into a container (or row in a row)

**Comment by jeffreyliim** [comment]
This is the app.blade file. Both homestead and laradock examples are from the same file.

<img width="910" alt="screen shot 2017-12-12 at 5 28 54 pm" src="https://user-images.githubusercontent.com/19368718/33877074-40aafb16-df62-11e7-933f-a3cd98201a8d.png">
<img width="915" alt="screen shot 2017-12-12 at 5 29 02 pm" src="https://user-images.githubusercontent.com/19368718/33877078-4146f0a2-df62-11e7-9961-c6060293a023.png">
<img width="913" alt="screen shot 2017-12-12 at 5 29 30 pm" src="https://user-images.githubusercontent.com/19368718/33877079-4179e426-df62-11e7-8c8b-7c44f15e8ecf.png">
<img width="917" alt="screen shot 2017-12-12 at 5 29 35 pm" src="https://user-images.githubusercontent.com/19368718/33877080-41a8c764-df62-11e7-8d66-142e57b5104a.png">

**Comment by brianwfl88** [comment]
From what i see, it is related to your screen resolution. Mind if i know your screen resolution?

**Comment by jeffreyliim** [comment]
Its 2560x1600 13’ macbook pro. I doubt it has anything to do with screen resolution though

**Comment by brianwfl88** [comment]
Maybe you can do a quick checkup on your resolutions of ur respective vm’s in whatismyresolution.com

**Comment by massimoselvi** [comment]
don't show the blade file, of course it is the one and only, I asked for the HTML on the browser to check any difference in the Blade compilation/rendering on both platforms

**Comment by brianwfl88** [comment]
His laptop resolution is 2560 x 1600, which lead me to suspect that the homestead is using 1366 x 768, which make the difference in the margins on both sides

**Comment by ed-fruty** [comment]
No offense, but am I the only one who thinks, this issue sounds like:
`I have use laradock. I have bought an ice cream and a car. Why are the prices different?` ? :joy:

On the screens I see different browser zoom. As I assume, domains for laradock and homestead are different. And browser remember zoom settings for different domains. :squirrel:
