### ISSUE TITLE
mySQL Connection refused

### ISSUE THREAD

**Issue by rafa-acioly** [laradock/laradock#1299]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): dec08ec2b14006f106c9223b22ac52f634208ecf
- System info (Mac, PC, Linux): Linux 
- System info disto/version: ubuntu 14.04

### Issue:
I'm trying to connect on my local `mysql` installation and only get the error: `SQLSTATE[HY000] [2002] Connection refused`, i've already defined the configuration at my `.env` (laradock file), if i use `localhost` at my .env file (on project) i got the error : `SQLSTATE[HY000] [2002] No such file or directory `

### settings on `.env` (project):

```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=pluggto_admin
DB_USERNAME=root
DB_PASSWORD=root
```
**error**: php_network_getaddresses: getaddrinfo failed: Name or service not known

```
DB_HOST=127.0.0.1
```
**error**: Connection refused

### settings on `.env` (laradock):

```
MYSQL_VERSION=8.0
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```
i've also tried:

```
MYSQL_VERSION=8.0
MYSQL_DATABASE=mydbname
MYSQL_USER=root
MYSQL_PASSWORD=
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```

**Comment by jeffreyliim** [comment]
Set your database, username and password the same as project env file the same as configured the laradock env file.

**Comment by rafa-acioly** [comment]
@jeffreyliim i've changed to the same values and still got the error:

`SQLSTATE[HY000] [2002] Connection refused`

## .env file on laradock
```
MYSQL_VERSION=8.0
MYSQL_DATABASE=mydatabase
MYSQL_USER=root
MYSQL_PASSWORD=
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```

## .env file in project
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=mydatabase
DB_USERNAME=root
DB_PASSWORD=
```

**Comment by jeffreyliim** [comment]
Change DB_HOST=mysql

**Comment by rafa-acioly** [comment]
@jeffreyliim `SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known`

**Comment by jeffreyliim** [comment]
Go into your docker workspace in your laradock folder by doing
`docker-compose exec workspace`
then clear your config and cache
`php artisan config:clear`
`php artisan cache:clear`

**Comment by bestlong** [comment]
@rafa-acioly your Laravel app must run in laradock container, not host os.

**Comment by danaia** [comment]
Any ideas why this would be happening?: I have an install script which installs both Laradock and my Larvel application. I use this install script successfully within a Virtualbox VM - Ubuntu 16.04 without any issues at all. Every thing comes up any MySQL migrates no problem. I then install the exact same Ubuntu 16.04 OS on my same machine. This time, not as a VM but as the native OS. I run the exact same script, under the same Ubuntu OS with no modifications at all and I get the dreaded MySQL: SQLSTATE[HY000] [2002] Connection refused.  Why would 2 identical systems react this way? Everything is exactly the same and I have repeated this problem 3 times so far.

**Comment by bestlong** [comment]
Hi @danaia Your VM install source is same NativeOS (ISO image or CD/USB Flash Drive)?

**Comment by pedes42** [comment]
The solution from @rafa-acioly works, but please be aware to keep the DB_PORT to 3306 in your `Laravel .env` file, even if you have changed it in your `Laradock .env` file (e.g. 3007). So the config should be as follow:

**.env file on laradock**
```
MYSQL_VERSION=8.0
MYSQL_DATABASE=mydatabase
MYSQL_USER=root
MYSQL_PASSWORD=
MYSQL_PORT=3307
MYSQL_ROOT_PASSWORD=
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```

**.env file in project**
```
MYSQL_VERSION=8.0
MYSQL_DATABASE=mydatabase
MYSQL_USER=root
MYSQL_PASSWORD=
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```

I had to change the port in my Laradock config, because there was already a MySQL service listening to port 3306 my Linux machine. That's why i ran into this problem.

**Comment by sjsiegel001** [comment]
I entered my workspace by entering the laradock folder and running
```
docker-compose exec workspace bash
```
then I configured my .env from within the workspace container as such:
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```
then I exited the workspace and entered the mysql container with user root password root
```
docker-compose exec mysql mysql -u root -proot
```
then I created the homestead database, and then created a user homestead, then assigned wildcard privileges:
```
GRANT ALL PRIVILEGES ON homestead.* to homestead@'%' identified by 'secret';
```
finally I was able to re-enter my workspace and run `php artisan migrate`. I hope this helps someone.

**Comment by zetnet** [comment]
> `docker-compose exec workspace`

docker-compose exec workspace bash maybe ?

**Comment by sandeepchowdary7** [comment]
settings on .env (project):
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=root
DB_PASSWORD=root

settings on .env (laradock):
MYSQL_VERSION=latest
MYSQL_DATABASE=default
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

> Trying to connect mysql in sequel-pro somehow getting an error
sequel-pro connection details
name: deafult
host: 127.0.0.1
username: root
password: root 

Can anyone help me on this? Thanks in advance.

**Comment by hofstede-matheus** [comment]
> I entered my workspace by entering the laradock folder and running
> 
> ```
> docker-compose exec workspace bash
> ```
> then I configured my .env from within the workspace container as such:
> 
> ```
> DB_CONNECTION=mysql
> DB_HOST=mysql
> DB_PORT=3306
> DB_DATABASE=homestead
> DB_USERNAME=homestead
> DB_PASSWORD=secret
> ```
> then I exited the workspace and entered the mysql container with user root password root
> 
> ```
> docker-compose exec mysql mysql -u root -proot
> ```
> then I created the homestead database, and then created a user homestead, then assigned wildcard privileges:
> 
> ```
> GRANT ALL PRIVILEGES ON homestead.* to homestead@'%' identified by 'secret';
> ```
> finally I was able to re-enter my workspace and run `php artisan migrate`. I hope this helps someone.

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by 'secret'' at line 1

**Comment by sandeepchowdary7** [comment]
@hofstede-matheus even replacing username and password with root. and visit http://localhost:8080 (mysql, root, root) That will works for sure.

**Comment by christopherarter** [comment]
This issue persists.

```
MYSQL_VERSION=5.7
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```

```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
```

Throws these errors:

```
PDOException::("PDO::__construct(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known")
```

```
PDO::__construct("mysql:host=mysql;port=3306;dbname=default", "default", "secret", [])
```

**Comment by gsecho** [comment]
> docker-compose exec workspace bash
>cd laravel
>php artisan migrate
Migration table created successfully.

**Comment by mhosseizadeh** [comment]
open you'r .env project NOT .env laradock  and set this setting then run project

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=YOUR_DATABASE_NAME
DB_USERNAME=root
DB_PASSWORD=root
QUEUE_HOST=beanstalkd

**Comment by Lewi77** [comment]
> The solution from @rafa-acioly works, but please be aware to keep the DB_PORT to 3306 in your `Laravel .env` file, even if you have changed it in your `Laradock .env` file (e.g. 3007). So the config should be as follow:
> 
> **.env file on laradock**
> 
> ```
> MYSQL_VERSION=8.0
> MYSQL_DATABASE=mydatabase
> MYSQL_USER=root
> MYSQL_PASSWORD=
> MYSQL_PORT=3307
> MYSQL_ROOT_PASSWORD=
> MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
> ```
> 
> **.env file in project**
> 
> ```
> MYSQL_VERSION=8.0
> MYSQL_DATABASE=mydatabase
> MYSQL_USER=root
> MYSQL_PASSWORD=
> MYSQL_PORT=3306
> MYSQL_ROOT_PASSWORD=
> MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
> ```
> 
> I had to change the port in my Laradock config, because there was already a MySQL service listening to port 3306 my Linux machine. That's why i ran into this problem.

yeah, u're reight. I have changed the MYSQL_PORT=3307 in laradock `.env` file,  and also make it in laravel project `.env`. So using `DB_PORT=3306` in laravel is the right setting.

**Comment by prexma** [comment]
> php artisan migrate

This hint worked for me:
Very important to execute the `php artisan migrate` in the project folder **inside** the docker container!
