### ISSUE TITLE
Complete support for GD

### ISSUE THREAD

**Issue by neon64** [LaraDock/laradock#130]
The current support is incomplete as it doesn't include support for jpeg, png etc which is essential when using GD to edit images.

Can you tell me how to use the rest.

It should be something like adding `--with-jpeg-dir=???` and then also a line inside `apt_get`.

I tried 

```
RUN apt-get update && apt-get install -y \
    libjpeg8 \'
    ...
```

But it says: `Unable to locate package libjpeg8`. Sorry I am a noob with Docker.

**Comment by Mahmoudz** [comment]
@appleboy

**Comment by appleboy** [comment]
@neon64 Could you provide detail information or some example code? Thanks.

**Comment by neon64** [comment]
I am using the `intervention/image` PHP library. It complains that the function `imagecreatefromjpeg` doesn't exist. This is because in Dockerfile70 for php-fpm, gd is built without specifying libraries for JPEG/PNG/etc, only free type. To fix it, I think you need to add --with-jpeg-dir=?? and so on for each image type. The issue is I don't know how to get those required libraries.

Alternatively, I should be able to (at least on Ubuntu 16.04) `apt-get install php7.0-gd`. that also doesn't work because docker != Ubuntu (correct?)

**Comment by appleboy** [comment]
@neon64 I will try `intervention/image` out.

**Comment by appleboy** [comment]
@neon64 Please try `v2.6.2` version.

**Comment by andrewelkins** [comment]
Getting an error with GD running master.

> [2016-08-01 20:26:47] local.ERROR: Intervention\Image\Exception\NotSupportedException: GD Library extension not available with this PHP installation. in /var/www/laravel/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php:16

**Comment by appleboy** [comment]
@andrewelkins Please create another issue, post your example code and provide your `laradock` version.
