### ISSUE TITLE
Caddy fails on build

### ISSUE THREAD

**Issue by johnie** [laradock/laradock#1301]
### Info:
- Docker version (`$ docker --version`): `Docker version 17.09.0-ce, build afdb6d4`
- Laradock commit (`$ git rev-parse HEAD`): `f22ceb71a`
- System info (Mac, PC, Linux): Linux
- System info disto/version: `Ubuntu 16.04.3 LTS`

### Issue:
Caddy-image won't build on `docker-compose build caddy`
_____

### Relevant Code:

```
$ docker-compose build caddy
Building caddy
Step 1/7 : FROM zuohuadong/caddy:alpine
 ---> 88377d26556f
Step 2/7 : MAINTAINER Huadong Zuo <admin@zuohuadong.cn>
 ---> Using cache
 ---> d8637268424d
Step 3/7 : ARG plugins="cors"
 ---> Using cache
 ---> 8a48bc664146
Step 4/7 : RUN caddyplug install ${plugins}
 ---> Running in 97189e97aea6
installing cors...
github.com/captncraig/cors (download)
github.com/captncraig/cors
github.com/captncraig/cors/caddy
go build command-line-arguments: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
exit status 1
 ✗ cors
ERROR: Service 'caddy' failed to build: The command '/bin/sh -c caddyplug install ${plugins}' returned a non-zero code: 1
```

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/33818943-bc5a7cf4-de82-11e7-9e06-26d66d1eca8e.png)
please check your Network~

**Comment by jacoboospina** [comment]
Did you solve this problem? I'm facing the same issue and cannot find any solution

**Comment by jacoboospina** [comment]
ee

**Comment by hgezim** [comment]
I ran into a build issue and it was because I ran out of disk space. In case this helps someone in the future!
