### ISSUE TITLE
No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on 'mongo:27017']

### ISSUE THREAD

**Issue by ViktorMelnykCiklum** [laradock/laradock#1303]
### Info:
- Docker version (17.06.1-ce, build 874a737): 
- Laradock commit (`f22ceb71ab64e080d916734f65a68461208b54ee`): 
- System info (Ubuntu 16.04): 

### Issue:
Could not connect to mongo from my application, seems port 27017 closed.

I ran nmap on php-fpm container and got: 

```bash
root@81a367dc208f:/var/www# nmap -p 27017 mongo

Starting Nmap 6.47 ( http://nmap.org ) at 2017-12-08 14:16 UTC
Nmap scan report for mongo (172.20.0.2)
Host is up (0.00012s latency).
rDNS record for 172.20.0.2: docker_mongo_1.docker_backend
PORT      STATE  SERVICE
27017/tcp closed unknown
```

When I tried connect to mongo I got 
```php
No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on 'mongo:27017']
```
_____

### Expected behavior:
Port 27017 must be open
_____

### Reproduce:

```bash
docker-compose build --no-cache nginx mongo php-fpm
```
_____

**Comment by ivya-ciklum** [comment]
same problem here

**Comment by sajidunnar** [comment]
I belive both are related. https://github.com/laradock/laradock/issues/932

**Comment by vpiskunov** [comment]
Any luck with this? Trying to install Webiny, which depends on mongo...

**Comment by sajidunnar** [comment]
Not officially but I was able fixed by using mongo image directly

In docker compose file replace following

build: ./mongo to image: mongo:latest

**Comment by brusin** [comment]
Up guys ? :)
