### ISSUE TITLE
Files created as root (chown needed in order to edit them)

### ISSUE THREAD

**Issue by dsampaolo** [LaraDock/laradock#131]
Hi,

I'm new to Laradock and I already love it.
When I use "php artisan make:auth" on docker_workspace_1, it successfully scaffolds the views for login/register, but these files are owned by root - thus I can't edit them.

I can chown the files from outside the container to regain access to them, but I think I'm doing something wrong. Any ideas ?

**Comment by knnnrd** [comment]
I'm having the exact same problem and would also like some help/explanation on this.

**Comment by AminMkh** [comment]
so since you will be running artisan using the workspace container, it will be using the root user, so you will have to change the permissions or the owner of those files.

If you are on Linux or using the docker toolbox for windows/mac, you can do a 
```
sudo chown YourUserName file1 file2 
```
Using terminal of 
- docker machine in case of toolbox(windows/mac)
- native linux OS in case of Linux host

**Comment by knnnrd** [comment]
This is not really a solution for a development environment imo

**Comment by AminMkh** [comment]
I don't find myself creating files all the time, but on docker for windows using hyper-v I don't run into this issue, because windows ignores linux permissions.

Perhaps someone will have a better idea or docker community will improve this. But it's not a Laradock specific issue.

**Comment by jleonardolemos** [comment]
I'm having the same problem.

**Comment by nbicalcarata** [comment]
+1

**Comment by mitjarobic** [comment]
+1

**Comment by computerfr33k** [comment]
You could include a script similar to this in the workspace container to specify a specific user id to run as solving the permissions problem. https://github.com/linuxserver/docker-baseimage/blob/master/10_add_user_abc.sh

create default user
```dockerfile
RUN useradd -u 911 -U -d /config -s /bin/false abc && \
      usermod -G users abc && \
      mkdir -p /app/aptselect /config /defaults && \
```

**Comment by dsampaolo** [comment]
Actually this is embedded in LaraDock : SSH into your workspace by adding --user=laradock on the command line, ie : 

docker-compose exec --user=laradock workspace bash

Laradock is user with PUID 1000, PGID 1000, so it's "mapped" to the first created user on the host machine.
