### ISSUE TITLE
php7.1-phalcon : Depends: phpapi-20160303 but it is not installable

### ISSUE THREAD

**Issue by jarhom** [laradock/laradock#1314]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): ad3698670bd31528acdf5f125b39a78c24413c0e
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.11.6

### Issue:

When I install phalcon, it tell me php depends error message "php7.1-phalcon : Depends: phpapi-20160303 but it is not installable", I found the php-fpm container current system version is debain 8, maybe version too old, because phalcon 7  must debain 9+.

### Expected behavior:

install success

### Reproduce:

install phalcon

### Relevant Code:

```
curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | bash && \
apt-get install -y php7.1-phalcon

```

**Comment by sergeyklay** [comment]
Works well on clean Ubuntu 14.04 / 16.04

```bash
sudo apt-get update
sudo apt-get install curl software-properties-common

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update

sudo apt-get install -y php7.1-common

curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | sudo bash
sudo apt-get install php7.1-phalcon
```

**Comment by sergeyklay** [comment]
@jarhom I'm pretty sure it is the same issue: https://github.com/Codeception/Codeception/issues/5352#issuecomment-457016992. 
So this issue may be closed.
