### ISSUE TITLE
 How to add SSL to APACHE in laradock 

### ISSUE THREAD

**Issue by ekahrovic** [laradock/laradock#1316]
How to add SSL to APACHE in laradock?

**Comment by canhkieu** [comment]
Hi @ekahrovic 
Did you fixed it? any idea?

**Comment by ekahrovic** [comment]
@canhkieu Sorry for late response...
Yes, I sucessfully added SSL to apache by adding the following code to apache Dockerfile before the line that restarts the service:
`
RUN mkdir /etc/apache2/ssl 2> /dev/null

RUN openssl genrsa -out "/etc/apache2/ssl/MY_CERT_NAME.key" 2048 \
    && openssl req -new -key "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.csr" -subj "/CN=wptest.local/O=LGS/C=UK" \
    && openssl x509 -req -days 365 -in "/etc/apache2/ssl/MY_CERT_NAME.csr" -signkey "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.crt"
`


Also, you need to add following lines to the virtualhost conf:

`
SSLEngine on
SSLCertificateFile /etc/apache2/ssl/MY_CERT_NAME.crt
SSLCertificateKeyFile /etc/apache2/ssl/MY_CERT_NAME.key
`

**Comment by canhkieu** [comment]
It's missing before. 
```
RUN apk add --no-cache openssl
```

And then, after build. I got this error
```
/etc/nginx/ssl/demo1.key: No such file or directory
140523227229068:error:02001002:system library:fopen:No such file or directory:bss_file.c:406:fopen('/etc/nginx/ssl/demo1.key','w')
140523227229068:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:408:
```

**Comment by ekahrovic** [comment]
nginx? I thought we were talking about apache.

**Comment by FabrizioCafolla** [comment]
i used this conf
**file "apache2/Dockerfile"**
_before the ENTRYPOINT line_
`
RUN mkdir /etc/apache2/ssl 2> /dev/null
RUN openssl genrsa -out "/etc/apache2/ssl/ssl_site.key" 2048 \
    && openssl req -new -key "/etc/apache2/ssl/ssl_site.key" -out "/etc/apache2/ssl/ssl_site.csr" -subj "/CN=site.com/O=LGS/C=IT" \
    && openssl x509 -req -days 365 -in "/etc/apache2/ssl/ssl_site.csr" -signkey "/etc/apache2/ssl/ssl_site.key" -out "/etc/apache2/ssl/ssl_site.crt"

RUN a2enmod rewrite && a2enmod headers && a2enmod proxy proxy_html proxy_http xml2enc
RUN a2enmod ssl
RUN service apache2 restart
`

**file "apache2/sites/default.apache.conf"**
`
<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
        ServerAdmin webmaster@localhost
        ServerName site.com
        ServerAlias *.site.com
        DocumentRoot /var/www/public

        SSLEngine on
        SSLCertificateFile "/etc/apache2/ssl/ssl_site.crt"
        SSLCertificateKeyFile "/etc/apache2/ssl/ssl_site.key"

        #SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>

    	<Directory />
    		Options FollowSymLinks
    		AllowOverride None
    	</Directory>

        <Directory /var/www/public>
            Options FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Directory>
    </VirtualHost>
</IfModule>
`
"site.com" is your site, it must also replace it in the docker command.
"ssl_site" if you would change it, you can!

**@ekahrovic in the vhosts file you do not need those commands**

**Comment by anchetaWern** [comment]
this doesn't seem to work. I'm trying it locally.

**Comment by elbakh** [comment]
> @canhkieu Sorry for late response...
> Yes, I successfully added SSL to apache by adding the following code to apache Dockerfile before the ENTRYPOINT line:
> 
> ```
> RUN mkdir /etc/apache2/ssl 2> /dev/null
> 
> RUN openssl genrsa -out "/etc/apache2/ssl/MY_CERT_NAME.key" 2048 \
>     && openssl req -new -key "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.csr" -subj "/CN=wptest.local/O=LGS/C=UK" \
>     && openssl x509 -req -days 365 -in "/etc/apache2/ssl/MY_CERT_NAME.csr" -signkey "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.crt"
> 
> RUN service apache2 restart
> ```
> 
> Though, Im not sure the last line must be there, I never tested if it work without it.
> 
> Also, you need to add following lines to the virtualhost conf:
> 
> ```
> SSLEngine on
> SSLCertificateFile /etc/apache2/ssl/MY_CERT_NAME.crt
> SSLCertificateKeyFile /etc/apache2/ssl/MY_CERT_NAME.key
> ```

Thank you for this. Implemented it successfully without the last line

**Comment by zooneex9** [comment]
Can you pass and example of your final files cause i can't make it work....

> > @canhkieu Sorry for late response...
> > Yes, I successfully added SSL to apache by adding the following code to apache Dockerfile before the ENTRYPOINT line:
> > ```
> > RUN mkdir /etc/apache2/ssl 2> /dev/null
> > 
> > RUN openssl genrsa -out "/etc/apache2/ssl/MY_CERT_NAME.key" 2048 \
> >     && openssl req -new -key "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.csr" -subj "/CN=wptest.local/O=LGS/C=UK" \
> >     && openssl x509 -req -days 365 -in "/etc/apache2/ssl/MY_CERT_NAME.csr" -signkey "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.crt"
> > 
> > RUN service apache2 restart
> > ```
> > 
> > 
> > Though, Im not sure the last line must be there, I never tested if it work without it.
> > Also, you need to add following lines to the virtualhost conf:
> > ```
> > SSLEngine on
> > SSLCertificateFile /etc/apache2/ssl/MY_CERT_NAME.crt
> > SSLCertificateKeyFile /etc/apache2/ssl/MY_CERT_NAME.key
> > ```
> 
> Thank you for this. Implemented it successfully without the last line

**Comment by geraintdong** [comment]
> Can you pass and example of your final files cause i can't make it work....
> 
> > > @canhkieu Sorry for late response...
> > > Yes, I successfully added SSL to apache by adding the following code to apache Dockerfile before the ENTRYPOINT line:
> > > ```
> > > RUN mkdir /etc/apache2/ssl 2> /dev/null
> > > 
> > > RUN openssl genrsa -out "/etc/apache2/ssl/MY_CERT_NAME.key" 2048 \
> > >     && openssl req -new -key "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.csr" -subj "/CN=wptest.local/O=LGS/C=UK" \
> > >     && openssl x509 -req -days 365 -in "/etc/apache2/ssl/MY_CERT_NAME.csr" -signkey "/etc/apache2/ssl/MY_CERT_NAME.key" -out "/etc/apache2/ssl/MY_CERT_NAME.crt"
> > > 
> > > RUN service apache2 restart
> > > ```
> > > 
> > > 
> > > Though, Im not sure the last line must be there, I never tested if it work without it.
> > > Also, you need to add following lines to the virtualhost conf:
> > > ```
> > > SSLEngine on
> > > SSLCertificateFile /etc/apache2/ssl/MY_CERT_NAME.crt
> > > SSLCertificateKeyFile /etc/apache2/ssl/MY_CERT_NAME.key
> > > ```
> > 
> > 
> > Thank you for this. Implemented it successfully without the last line

it looks like we have an issue with random file creation of openssl
a little fix helps me make it work

```
RUN mkdir /etc/apache2/ssl 2> /dev/null
RUN openssl genrsa -out "/etc/apache2/ssl/ssl_site.key" 2048 \
    && openssl rand -out /root/.rnd -hex 256 \
    && openssl req -new -key "/etc/apache2/ssl/ssl_site.key" -out "/etc/apache2/ssl/ssl_site.csr" -subj "/CN=site.com/O=LGS/C=IT" \
    && openssl x509 -req -days 365 -in "/etc/apache2/ssl/ssl_site.csr" -signkey "/etc/apache2/ssl/ssl_site.key" -out "/etc/apache2/ssl/ssl_site.crt"

RUN a2enmod rewrite && a2enmod headers && a2enmod proxy proxy_html proxy_http xml2enc
RUN a2enmod ssl
RUN service apache2 restart
```

**Comment by ultrono** [comment]
@geraintdong Cheers, all working here! 👍 

For anyone else here via Google, the code within the Docker file need to come before the line 

`ENTRYPOINT ["/opt/docker/bin/entrypoint.sh"]`

**Comment by garbinmarcelo** [comment]
Has this been adjusted in the new versions of Laradock? I am trying to use SSL with apache2 but without success so far. I would like it to be something like the nginx container.

**Comment by garbinmarcelo** [comment]
Now when using Laradock it is possible to use HTTPS / SSL with the apache2 container (the step by step is in the comments of the merge), happy to have made this contribution 😀🎉
