### ISSUE TITLE
How to start the `schedule:run` command? Already asked on SOF but got no answers.

### ISSUE THREAD

**Issue by oberoivarun** [laradock/laradock#1318]
### Info:
- Docker version : 17.09.1-ce, build 19e2cf6
- Laradock commit : 4e486280f4ecc7eeb00751575a0541583a136be5
- System info (Mac, PC, Linux): Windows 10 Pro 64 Bit

### Issue:

Scheduler is not running.
_____

### Expected behavior:

It should run on its own after running `docker-compose up`
_____

I'm sure everyone knows the answer to this. But the only thing about cron in the docs is where i can put my own custom cron jobs. Not how i must start the schedule to run indefinitely every minute. So how does one start the schedule?

https://stackoverflow.com/questions/47881421/start-laravel-schedular-on-laradock-cron-jobs

**Comment by tjallingt** [comment]
the cron command is in the `workspace/crontab/laradock` file, it is running by default when you `docker-compose up` however it doesn't work for me either even though the command shows up in the syslog...

**Comment by lulucom** [comment]
I had a similar issue caused by [multiple projects setup](http://laradock.io/getting-started/#B).
It was resolved by modifying the path to `artisan` command in crontab and rebuilding `workspace` container.

`laradock/workspace/crontab/laradock`
```
* * * * * laradock php /var/www/project-1/artisan schedule:run >> /dev/null 2>&1
* * * * * laradock php /var/www/project-2/artisan schedule:run >> /dev/null 2>&1
```

**Comment by tpraxl** [comment]
@lulucom That fixed it for me! Thanks.

**Comment by NicksonYap** [comment]
turns out i did not notice the path to artisan!

**Comment by ZJaume** [comment]
Hi,

I have the same issue and the workaround of @lulucom is not my case, because I have only one project and is on `/var/www`. My `syslog` says every minute:
```
May  1 12:58:01 63ec7a9391d0 CRON[462]: (laradock) CMD (/usr/bin/php /var/www/artisan schedule:run > /var/www/storage/log/scheduler.log 2>&1)
```
And it doesn't do anything, but if I run manually the scheduler command it does its job (only run laravel backup). Also I redirected the output to a log and neither writes anything to the file.
