### ISSUE TITLE
Cannot start service phpmyadmin (on Macbook)

### ISSUE THREAD

**Issue by arikardnoir** [laradock/laradock#1334]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

ERROR: for phpmyadmin  Cannot start service phpmyadmin: driver failed programming external connectivity on endpoint 45c998c5cc23_45c998c5cc23_laradock_phpmyadmin_1 (69867d7a64751877f1a71d4c54fd0bd13ed9979b771d83d44306068b927f2bf3): Error starting userland proxy: Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

### Expected behavior:

When I run this on terminal: docker-compose up -d  phpmyadmin
### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by ed-fruty** [comment]
> port is already allocated

In your case 8080 port is busy.
Try to free this port or change port for phpmyadmin in your [.env file](https://github.com/laradock/laradock/blob/master/env-example#L243)
