### ISSUE TITLE
add php support for grpc and protobuf extensions

### ISSUE THREAD

**Issue by nickfan** [laradock/laradock#1336]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

need add php support for grpc and protobuf extensions

https://grpc.io/docs/quickstart/php.html

**Comment by jsgv** [comment]
Is there a current status for this?

**Comment by bruno-digitalmanager** [comment]
/laradock/.env

WORKSPACE_INSTALL_PHPGRPC=true
PHP_FPM_INSTALL_PHPGRPC=true


/laradock/php-fpm/Dockerfile

###########################################################################
# PHP GRPC EXTENSION
###########################################################################

ARG INSTALL_PHPGRPC=false

RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
    # Install Php gRPC  Extension
    printf "\n" | pecl install -o -f grpc \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable grpc \
;fi

===================================================================================================================================

/laradock/workspace/Dockerfile

###########################################################################
# PHP GRPC EXTENSION
###########################################################################

ARG INSTALL_PHPGRPC=false

RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
    # Install Php Grpc Extension
    pecl install grpc && \
    echo "extension=grpc.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini && \
    ln -s /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-grpc.ini \
    && php -m | grep -q 'grpc' \
;fi

**Comment by sera527** [comment]
@bruno-digitalmanager hello! Your code proves an error: unknown instruction: PECL.

**Comment by bruno-digitalmanager** [comment]
@sera527 

Put both codes after section PHP REDIS EXTENSION. 
after line 200 - /laradock/php-fpm/Dockerfile
after line 415 - /laradock/workspace/Dockerfile

Other thing you need to add is on file:
/laradock/docker-compose.yml
after line 148 - INSTALL_PHPGRPC=${PHP_FPM_INSTALL_PHPGRPC}
after line 69 - INSTALL_PHPGRPC=${WORKSPACE_INSTALL_PHPGRPC}

**Comment by sera527** [comment]
The following code works for me:
laradock/docker-compose.yml
After
`workspace:
      build:
        context: ./workspace
        args:`
add
`- INSTALL_PHPGRPC=${WORKSPACE_INSTALL_PHPGRPC}`
After
`php-fpm:
      build:
        context: ./php-fpm
        args:`
add
`- INSTALL_PHPGRPC=${PHP_FPM_INSTALL_PHPGRPC}`

laradock/.env
Add
`PHP_FPM_INSTALL_PHPGRPC=true
WORKSPACE_INSTALL_PHPGRPC=true`

laradock/php-fpm/Dockerfile
Add
`###########################################################################
# PHP GRPC EXTENSION
###########################################################################

ARG INSTALL_PHPGRPC=false

RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
    printf "\n" | pecl install -o -f grpc \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable grpc \
;fi`

laradock/workspace/Dockerfile
Add
`###########################################################################
# PHP GRPC EXTENSION
###########################################################################

ARG INSTALL_PHPGRPC=false

RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
    apt-get install zlib1g-dev && \
    pecl install grpc && \
    echo "extension=grpc.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini && \
    ln -s /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-grpc.ini \
    && php -m | grep -q 'grpc' \
;fi`

After changes make
`docker-compose build workspace php-fpm`

**Comment by bruno-digitalmanager** [comment]
> The following code works for me:
> laradock/docker-compose.yml
> After
> 
> ```
> workspace:
>       build:
>         context: ./workspace
>         args:
> ```
> 
> add
> `- INSTALL_PHPGRPC=${WORKSPACE_INSTALL_PHPGRPC}`
> After
> 
> ```
> php-fpm:
>       build:
>         context: ./php-fpm
>         args:
> ```
> 
> add
> `- INSTALL_PHPGRPC=${PHP_FPM_INSTALL_PHPGRPC}`
> 
> laradock/.env
> Add
> 
> ```
> PHP_FPM_INSTALL_PHPGRPC=true
> WORKSPACE_INSTALL_PHPGRPC=true
> ```
> 
> laradock/php-fpm/Dockerfile
> Add
> 
> ```dockerfile
> ###########################################################################
> # PHP GRPC EXTENSION
> ###########################################################################
> 
> ARG INSTALL_PHPGRPC=false
> 
> RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
>     printf "\n" | pecl install -o -f grpc \
>     && rm -rf /tmp/pear \
>     && docker-php-ext-enable grpc \
> ;fi
> ```
> 
> laradock/workspace/Dockerfile
> Add
> 
> ```dockerfile
> ###########################################################################
> # PHP GRPC EXTENSION
> ###########################################################################
> 
> ARG INSTALL_PHPGRPC=false
> 
> RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
>     apt-get install zlib1g-dev && \
>     pecl install grpc && \
>     echo "extension=grpc.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini && \
>     ln -s /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-grpc.ini \
>     && php -m | grep -q 'grpc' \
> ;fi
> ```
> 
> After changes make
> `docker-compose build workspace php-fpm`

Yeah, your response is more complete and beautiful. Sorry my partial response.

Gj @sera527

**Comment by pungky95** [comment]
Work fine thank you @bruno-digitalmanager

**Comment by fd6130** [comment]
> The following code works for me: laradock/docker-compose.yml After
> 
> ```
> workspace:
>       build:
>         context: ./workspace
>         args:
> ```
> 
> add `- INSTALL_PHPGRPC=${WORKSPACE_INSTALL_PHPGRPC}` After
> 
> ```
> php-fpm:
>       build:
>         context: ./php-fpm
>         args:
> ```
> 
> add `- INSTALL_PHPGRPC=${PHP_FPM_INSTALL_PHPGRPC}`
> 
> laradock/.env Add
> 
> ```
> PHP_FPM_INSTALL_PHPGRPC=true
> WORKSPACE_INSTALL_PHPGRPC=true
> ```
> 
> laradock/php-fpm/Dockerfile Add
> 
> ```dockerfile
> ###########################################################################
> # PHP GRPC EXTENSION
> ###########################################################################
> 
> ARG INSTALL_PHPGRPC=false
> 
> RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
>     printf "\n" | pecl install -o -f grpc \
>     && rm -rf /tmp/pear \
>     && docker-php-ext-enable grpc \
> ;fi
> ```
> 
> laradock/workspace/Dockerfile Add
> 
> ```dockerfile
> ###########################################################################
> # PHP GRPC EXTENSION
> ###########################################################################
> 
> ARG INSTALL_PHPGRPC=false
> 
> RUN if [ ${INSTALL_PHPGRPC} = true ]; then \
>     apt-get install zlib1g-dev && \
>     pecl install grpc && \
>     echo "extension=grpc.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini && \
>     ln -s /etc/php/${LARADOCK_PHP_VERSION}/mods-available/grpc.ini /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-grpc.ini \
>     && php -m | grep -q 'grpc' \
> ;fi
> ```
> 
> After changes make `docker-compose build workspace php-fpm`

Can we include this to the laradock repository? Because every time we need install grpc in fresh laradock we have to refer from here :/
