### ISSUE TITLE
No releases available for package "pecl.php.net/redis"

### ISSUE THREAD

**Issue by rushairer** [laradock/laradock#1337]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): master
- System info (Mac, PC, Linux):  Mac
- System info disto/version: 10.12.6

### Issue:
when i use 'docker-compose build php-fpm',
it goes wrong with: No releases available for package "pecl.php.net/redis"

_____

### Expected behavior:
```
Step 15/62 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl install -o -f redis     &&  rm -rf /tmp/pear     &&  docker-php-ext-enable redis ;fi
 ---> Running in 2a40c1b57944
No releases available for package "pecl.php.net/redis"
install failed
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl install -o -f redis     &&  rm -rf /tmp/pear     &&  docker-php-ext-enable redis ;fi' returned a non-zero code: 1
```
_____

### Reproduce:
run command 
```
docker-compose build php-fpm
```
_____

### Relevant Code:

I tried use 'pecl channel-update pecl.php.net' before install, it did not work.

**Comment by sytuacmdyh** [comment]
at the top of php-fpm/Dockerfile-71, change `FROM laradock/php-fpm:2.0-71` to `FROM laradock/php-fpm:1.4-71`.

**Comment by rushairer** [comment]
@sytuacmdyh Thanks.
I changed php-fpm version to 1.4-71, it works.
By the way, how to fix this bug for 2.0-71 ?

**Comment by sytuacmdyh** [comment]
@rushairer I just tried 2.0-71, it seems already been repaired~ good luck

**Comment by rushairer** [comment]
@sytuacmdyh thanks.

I have tried 2.0-71,I think it did not fixed yet.

it also show the error like that:
```
No releases available for package "pecl.php.net/redis"
```

**Comment by famelis** [comment]
[See my solution on another thread](https://github.com/laradock/laradock/issues/1315#issuecomment-380492758)

**Comment by liyuze** [comment]
[See my solution on another thread](https://github.com/laradock/laradock/issues/1670#issuecomment-416852440)

**Comment by bestlong** [comment]
Hi @rushairer try this
`docker-compose build --no-cache php-fpm`

**Comment by nskforward** [comment]
I got the same issue but the fix was only compiling PHP with openssl extension:
--with-openssl

**Comment by Wayne-jp** [comment]
I got the same issue here in China. Is there another solution , since changing php-fpm version is not work for me...

**Comment by AmirrezaNasiri** [comment]
For Iranian developers, this is happening for the same reason. Use some VPNs.

**Comment by shanezhiu** [comment]
I got the same issue here in China.
