### ISSUE TITLE
pecl/swoole requires PHP (version >= 7.0.0), installed version is 5.6.32

### ISSUE THREAD

**Issue by jourdon** [laradock/laradock#1339]
### Issue:
Swoole supports php5.3  in  swoole wiki. 
Why did swoole not support PHP 5.6 when it in laradock 

```
Step 17/64 : RUN if [ ${INSTALL_SWOOLE} = true ]; then     pecl install swoole     &&  docker-php-ext-enable swoole ;fi
 ---> Running in 2467103403da
pecl/swoole requires PHP (version >= 7.0.0), installed version is 5.6.32
No valid packages found
install failed
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_SWOOLE} = true ]; then     pecl install swoole     &&  docker-php-ext-enable swoole ;fi' returned a non-zero code: 1
```

**Comment by wxb** [comment]
Hi, @jourdon 
`pecl install swoole` 
The latest version will be installed

[pecl/swoole](http://pecl.php.net/package/swoole) 
> Release 2.0.12  : Dependencies PHP Version: PHP 7.0.0 or newer

![_20180111125706](https://user-images.githubusercontent.com/7111495/34809287-fbf382f2-f6ce-11e7-886c-1e70a6b3be28.png)

if you want use swoole in php 5.6 environment，you should modify `laradock/php-fpm/Dockerfile-56` line 123:
```
pecl install swoole \  
->
pecl install http://pecl.php.net/get/swoole-2.0.11.tgz
```
---
I'll deal with this bug later.

**Comment by jourdon** [comment]
@wxb Yes, I've found it. 
so I add the version number
it 's more simple
```    
#####################################
# Swoole EXTENSION FOR PHP 5
#####################################

ARG INSTALL_SWOOLE=false
RUN if [ ${INSTALL_SWOOLE} = true ]; then \
    pecl install swoole-2.0.10 && \
    docker-php-ext-enable swoole \
;fi
```

**Comment by wxb** [comment]
@jourdon 👍
