### ISSUE TITLE
Why bcmath does not take effect?

### ISSUE THREAD

**Issue by gavinliu6** [laradock/laradock#1344]
I have set the value of `PHP_FPM_INSTALL_BCMATH` to be `true` in .env file, shown as follows: 

```
...
PHP_FPM_INSTALL_BCMATH=true
...
```
then, I rebuild php-fpm with `docker-compose build php-fpm`, but it does not seem to be effective.

**Comment by 247163569** [comment]
@gavinliu6 help

**Comment by linus-zhou** [comment]
I got that problem too

**Comment by gavinliu6** [comment]
I have solved it by execute `docker-compose up php-fpm`. It is all my fault.
