### ISSUE TITLE
Workspace runs PHPUnit twice with single command

### ISSUE THREAD

**Issue by rodion-arr** [laradock/laradock#1349]
### Info:
- Docker version (`$ docker --version`): **Docker version 17.12.0-ce, build c97c6d6**
- Laradock commit (`$ git rev-parse HEAD`): **v5.9.0 SHA - 0077de2**
- System info (Mac, PC, Linux): **Mac**
- System info disto/version: **Mac OS 10.13.2 (17C88)**

### Issue:
Workspace runs PHPUnit twice with single command
![fail](https://user-images.githubusercontent.com/5843270/34877613-5fcf8272-f7af-11e7-9f3b-8014f560e3f8.png)

_____

### Expected behavior:
PHPUnit should be executed once
![correct](https://user-images.githubusercontent.com/5843270/34877626-7248d0ac-f7af-11e7-84bb-dc3e71b39959.png)

_____

### Reproduce:
"exec" to workspace and run phpunit tests
```
$ docker-compose exec workspace bash
$ vendor/bin/phpunit
```
_____

**Comment by bestlong** [comment]
@rodion-arr please check php config both enviroment:
`php -i | grep errors`
maybe display_errors = On
