### ISSUE TITLE
Install in Linux Mint

### ISSUE THREAD

**Issue by massiws** [LaraDock/laradock#135]
I install laradock either inside a laravel project (git submodule) and in an empty project (git clone), but when I try to run "docker-compose up -d   nginx mysql" I get these 3 errors:

> - WARNING: The INSTALL_PRESTISSIMO variable is not set. Defaulting to a blank string.
> - ERROR: for nginx  driver failed programming external connectivity on endpoint docktest_nginx_1 (a3205580cae2b7027e1a8f39fc3907251298d63465624204584a3446f1498590): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
> Traceback (most recent call last):
>   File "<string>", line 3, in <module>
>   File "compose/cli/main.py", line 63, in main
> AttributeError: 'ProjectError' object has no attribute 'msg'
> docker-compose returned -1
> - ERROR: for mysql  driver failed programming external connectivity on endpoint docktest_mysql_1 (ec51b5f5b5f1571c501f10b425c7d328349d0cd11cc397512ebdace7a6381993): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
> Traceback (most recent call last):
>   File "<string>", line 3, in <module>
>   File "compose/cli/main.py", line 63, in main
> AttributeError: 'ProjectError' object has no attribute 'msg'
> docker-compose returned -1

All docker-compose commands give me warning the first warning.

Any tips?

_Kernel: 4.2.0-34-generic
Docker: 1.11.2, build b9f10c9
Docker compose: 1.7.1, build 0a9ab35_

**Comment by Kauhat** [comment]
Hi @massiws 

The first warning is my fault! You can probably ignore that, as it doesn't have anything to do with the nginx & mysql containers.

**Comment by massiws** [comment]
On my Mint (and I suppose many Linux distribution) _apache2_ and _mysql_ services are enabled and running by default. I have to stop both and the last two errors gone away!
Maybe, there could be a suggestion in the documentation.
