### ISSUE TITLE
Nginx log rotation

### ISSUE THREAD

**Issue by fedemotta** [laradock/laradock#1357]
Hi Guys,
Could you help me to make it work the log rotation for nginx?

I tried in different ways but none works. 

What is the recommended way to use log rotation with nginx inside a docker container with laradock?

Thanks in advance

**Comment by vlauciani** [comment]
Hi all

is there any news about this issue? 

I'm using `nginx/sites/laravel.conf` that stores logs in:
```
error_log /var/log/nginx/laravel_error.log;
access_log /var/log/nginx/laravel_access.log;
```
 but they are not "rotated" and the single files are growing.
