### ISSUE TITLE
Warning: INSTALL_PRESTISSIMO

### ISSUE THREAD

**Issue by tiagoloureiro89** [LaraDock/laradock#136]
During docker-compose up command, all seems to go well, but the following warning is released:
`WARNING: The INSTALL_PRESTISSIMO variable is not set. Defaulting to a blank string.`

This only started to happen in the last week after I updated the submodule.
I work with Ubuntu, but similar warning has been showing on iOS as well.

**Comment by Kauhat** [comment]
Hi @tiagoloureiro89 

That's my fault - the INSTALL_PRESTISSIMO variable can be set using an `.env` file inside the laradock directory. It shouldn't cause any issues, but if it's not set then compose will throw the above warning.

I was hoping that there would be a way to set a default value for this in the compose file to prevent this warning, but it appears that this [isn't possible right now](https://github.com/docker/compose/issues/1377).

@Mahmoudz it's been bugging me too, so I'll submit a pull request later to set the variable in the `docker-compose.yml` file instead.

**Comment by tiagoloureiro89** [comment]
Thanks @Kauhat, that sounds like it would work ;)

Will wait for the pull to be live and close as soon as it is resolved.

**Comment by Mahmoudz** [comment]
This is solved 2df00ecdadc1d3d97c9b5ac1a56692e687467a06
