### ISSUE TITLE
laradock how to use gitlab webhook? 

### ISSUE THREAD

**Issue by linzi007** [laradock/laradock#1360]
### Info:
- Docker version (`$ docker --version`): 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 0077de28a13feea669f9d46ef21c20477fa6dbb0
- System info (Mac, PC, Linux): PC
- System info disto/version: win10 pro

### Issue:
I want to use a webhook to auto deploy, then i do:

First, run docker up:

`docker-compose up -d nginx redis mysql`

Second, add webhook in my gitlab project

`point to laravel website http://example.com/deploy/`

Third, laravel add router and Controller

```
// web.php
Route::post('/deploy', 'DeployController@index')->name('deploy');

// DeployController
//........
$result = shell_exec("/usr/bin/git pull");
logger('success result: ' . $result);
//.........
```

And it doesn't work, the command 'git pull' no run.

I found some error on container php-fpm
`[22-Jan-2018 07:46:46] WARNING: [pool www] child 7 said into stderr: "sh: 1: /usr/bin/git: not found"
` 
_____

### Expected behavior:
What shoud i do in laradock ?
Git has install in laradock_workspace_1, Should i install it again?
_____

**Comment by ed-fruty** [comment]
1. Links to your message, `git` is not installed on the `php-fpm` container. Why do you  check/search it in the `workspace` container? In your case you need it in the `php-fpm` container .
2. To execute external processes I suggest to use [symfony process component](https://symfony.com/doc/current/components/process.html)
3. For deploy by hook you can use ready utils, like jenkins, team city or another one. By the way, jenkins container is already exists in the laradock.

**Comment by glebgoloborodko** [comment]
Problem still exist!

When I run with Symfony process component bash script with "git" - I see an error : "git not found". While Symfony process my user = "www-data" and group = "www-data"

But it's strange, because when I go to workspace container with user "www-data" git command exists in /usr/bin/git...

Somehow from Symfony process or from Artisan::call "git" not exists... But user the same! =(

**Comment by jtomek** [comment]
I'm having the same issue, it's something with the php-fpm

If you look inside the PHP-FPM container `docker exec -it <DOCKER_PHP-FPM_ID> /bin/sh` it's possible to navigate to `/usr/bin/` but not `/usr/bin/git`

How can I add git to PHP-FPM? Or how can I make git visible (its visible from other containers in laradock)?

**Comment by jtomek** [comment]
I just figured it out.... There are multiple gits in those containers. You need to run the following command in your php-fpm:

apt-get update && apt-get install -y git
