### ISSUE TITLE
How to dump mongodb?

### ISSUE THREAD

**Issue by nunomazer** [LaraDock/laradock#137]
Hi, still a bit confused with Docker and Laradock.

I want to know in wich container should I run a mongodump to make a backup and how to get this backup in my synced/root folder ??

**Comment by Mahmoudz** [comment]
I will answer the first part regarding your confusion about Docker and LaraDock: LaraDock is Docker ready for Laravel. If you want to start with Docker you'll have to do few things (setup, configurations,...) this will take you time, and when you are using Docker for the first time you have to understand a lot of things before being able to start putting things together. LaraDock does all that for you and let you run a single command to get up and running with the Docker. So LaraDock allows you to use Docker and understand it later.

**Comment by nunomazer** [comment]
Ok, this I know, so I said still a bit confused, but the question is: in wich container should I run mongodump?

**Comment by Mahmoudz** [comment]
Try in the Mongo container, if not move the Workspace container.
