### ISSUE TITLE
Caddy container not getting let's encrypt certificates

### ISSUE THREAD

**Issue by luismt** [laradock/laradock#1370]
I have followed the tutorial to have an https secure setup.  However, once nginx and mysql is working properly under "compose up -d nginx and mysql", running "compose-up caddy" fails because nginx returns "404 not found" when let's encrypt requests "http://mysite.com/.well-known/acme-challenge/".

Any suggestions or workarounds?

**Comment by jasperf** [comment]
Did you every work this out @luismt ? Similar issue using Certbot at the moment.
