### ISSUE TITLE
SSH with laradock user not working

### ISSUE THREAD

**Issue by wvdongen** [laradock/laradock#1372]
SSH support for the laradock user was recently added: https://github.com/laradock/laradock/pull/1327. 

However, I'm unable to login using the laradock user with the specified SSH key. The pub key is present in `/home/laradock/.ssh/authorized_keys`. The permissions on the `.ssh` dir and contents are properly set. Furthermore SSH does work for the root user. Any ideas?

**Comment by mariano-dagostino** [comment]
I'm seeing the same issue: This is what `/var/log/auth.log` says:
```
sshd[1138]: User laradock not allowed because account is locked
```
