### ISSUE TITLE
Possible fix for `Call to undefined function imap_open()`

### ISSUE THREAD

**Issue by SvenSlijkoord** [laradock/laradock#1376]
### Info:
- Docker version (`$ docker --version`): Docker version 17.11.0-ce, build 1caf76c
- Laradock commit (`$ git rev-parse HEAD`): c3715165b6f55dd04b11e5f2d8344be60c5d6f56
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.10

### Issue:
imap functions are not available, even with WORKSPACE_INSTALL_IMAP=true
_____

### Expected behavior:
imap functions should be available
_____

#### To check if IMAP is working:
Try to use `imap_open()` function, or use this snippet to check if it is available.
```
if (function_exists('imap_open')) {
    echo "IMAP functions are available.<br />\n";
} else {
    echo "IMAP functions are not available.<br />\n";
}
```
#### Possible fix
**edit: modifying laravel.ini is not necessary**
~~Add this to php-fpm/laravel.ini
`extension=imap.so`~~

Add this to PHP-FPM Dockerfile. (tested with Dockerfile-71, added just before Final Touch)
```
RUN apt-get update && \
    apt-get install -y libc-client-dev libkrb5-dev && \
    rm -r /var/lib/apt/lists/* && \
    docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
    docker-php-ext-install imap
```
_____

### Relevant Code:

I took the snippets (and modified them) from here: http://fixwins.com/getAnswers.php?Problem-Resolved=7182&q=+Call+to+undefined+function+imap_open()+in+LaraDock+

### Note
Could someone else confirm this is also working? I will try to make a pull request with the needed ENV variables and docker-compose args.

**Comment by rcpearcentu** [comment]
Attempted to call function "imap_open" from namespace xxx
  
  
  We found a solution:

 I cant explain how this fixes the problem but it did seem to.

despite PHP reporting that imap extension is installed and me confirming it works by running a test script in the browser it wasnt working on the command line. So,basically reinstalled imap and dependancy php-curl

sudo apt install php-imap
  463  sudo phpenmod imap
  464  sudo apt update
  465  sudo apt
  467  sudo apt upgrade -y
  468  sudo reboot
  469  sudo apt update
  470  sudo apt upgrade
  471  sudo apt autoremove
  472  sudo reboot
  477  sudo add-apt-repository ppa:ondrej/php
  478  sudo apt-get update
  479  sudo apt-get install php-curl

**Comment by rcpearcentu** [comment]
thanks for your help and advice
