### ISSUE TITLE
How to use PHP7.2 with Laradock

### ISSUE THREAD

**Issue by Wasca** [laradock/laradock#1379]
### Info:
- Docker version (Docker version 17.12.0-ce, build c97c6d6): 
- Laradock commit (acbe7160d9680dd77b801b8df12300da6ab08d45): 
- System info (Mac): 
- System info disto/version: OSX 10.13.3 

### Issue:

Need to use PHP 7.2
_____

### Expected behavior:

PHP 7.2 Installed
_____

Hi Guys

I'm very new to Laradock and I need to use PHP v7.2.

I've been following the install instructions here http://laradock.io/getting-started/#installation and have noticed that Laradock is using PHP7.1

This is from the .env file in laradock

--------
PHP Version
Select a PHP version of the Workspace and PHP-FPM containers (Does not apply to HHVM). Accepted values: 71 - 70 - 56

PHP_VERSION=71
--------

How can I make Laradock use PHP 7.2?

Thanks

**Comment by Shadow2004** [comment]
There is currently a pull request out for adding the necessary entries to allow you to use php 7.2 see #1351

**Comment by Wasca** [comment]
@Shadow2004 

Thanks for letting me know, cheers!
