### ISSUE TITLE
First time - initial instructions don't work: ERROR: for mysql  Cannot create container for service mysql: b'create .: volume name is too short, names should be at least two alphanumeric characters'

### ISSUE THREAD

**Issue by bryan-kramer** [laradock/laradock#1383]
### Info:
- Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): acbe7160d9680dd77b801b8df12300da6ab08d45
- System info (Mac, PC, Linux): Linux
- System info disto/version: , Fedora 27, VirtualBox VM inside Windows 10

### Issue:
Initial steps from documentation (after changing port numbers) don't work:
      
      WARNING: The MYSQL_ENTRYPOINT_INITDB variable is not set. Defaulting to a blank string.
      ...
      ERROR: for mysql  Cannot create container for service mysql: b'create .: volume name is too short, names should be at least two alphanumeric characters'

_____

### Expected behavior:
Containers should start correctly
_____

### Reproduce:
1. Clone laradock
2. Edit .env file to change ports
3. docker-compose up -d nginx mysql redis beanstalkd
_____

### Relevant Code:

```
     Not applicable, just trying first steps
```

After I added 

      MYSQL_ENTRYPOINT_INITDB=./mysqldb/docker-entrypoint-initdb.d

to .env (missing from sample-env) the example worked.

Cannot find any information on what the correct value of MYSQL_ENTRYPOINT_INITDB should be (I copied the mariadb version). Also the mariadb directory has more files that are not in the mysql directory.

**Comment by bestlong** [comment]
@bryan-kramer after clone laradock, you need copy env-example to .env
By Default MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
