### ISSUE TITLE
No matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by Alinka24789** [laradock/laradock#1388]
### Info:
- Docker version (`$ docker --version`):
**Client:**
   Version:	17.12.0-ce
   API version:	1.35
   Go version:	go1.9.2
   Git commit:	c97c6d6
   Built:	Wed Dec 27 20:03:51 2017
   OS/Arch:	darwin/amd64
**Server:**
   Engine:
    Version:	17.12.0-ce
    API version:	1.35 (minimum version 1.12)
    Go version:	go1.9.2
    Git commit:	c97c6d6
    Built:	Wed Dec 27 20:12:29 2017
    OS/Arch:	linux/amd64
    Experimental:	true

- Laradock commit (`$ git rev-parse HEAD`): acbe7160d9680dd77b801b8df12300da6ab08d45
- System info (Mac, PC, Linux): macOS Sierra
- System info disto/version: version 10.12.6

### Issue:
I followed instruction by http://laradock.io/getting-started/ but on command 
<code>docker-compose up -d nginx mysql</code>
i got error _"Service 'nginx' failed to build: no matching manifest for linux/amd64 in the manifest list entries"_

Could somebody help me resolve this error?

**Comment by sinden** [comment]
[](https://github.com/nginxinc/docker-nginx/issues/230)

[](https://github.com/docker-library/repo-info/blob/master/repos/nginx/remote/1.13-alpine.md)

**Comment by sinden** [comment]
Looks to be a known issue: [https://github.com/nginxinc/docker-nginx/issues/230](https://github.com/nginxinc/docker-nginx/issues/230)

Other posts are stating to use a previous build until resolved

**Comment by sinden** [comment]
You can change the first line of the nginx Dockerfile from `FROM nginx:alpine` to `FROM nginx:1.13.8-alpine` for now until it's resolved. Should work fine.
