### ISSUE TITLE
Mysql. The server requested authentication method unknown to the client [caching_sha2_password]

### ISSUE THREAD

**Issue by mvladimir7** [laradock/laradock#1390]
### Info:
- Docker version: 17.12.0-ce, build c97c6d6
- Laradock commit: 13f55ef7967989337ed3538af3a8164268eeb623
- System info: Win
- System info disto/version: 10

### Issue:
New fresh laradock installation. All default settings. Driver is shared.
Except:
```
DATA_SAVE_PATH=../../data
```
Can't connect to the mysql from phpMyAdmin.
![image](https://user-images.githubusercontent.com/9190882/36596767-d5ccc98e-18b7-11e8-9120-f78057bca4b5.png)

`#2054 - The server requested authentication method unknown to the client`

`mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]`

`mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client`

**But I can connect to mysql inside mysql container with standard root/root credentials.**

I tried to delete all containers and images. Several times downloaded laradock. Tried to reinstall Docker. No success. 
_____

### Expected behavior:
Can connect to mysql with phpMyAdmin

_____
### Logs
```
$ docker logs laradock_mysql_1
2018-02-23T13:22:10.682788Z 0 [Warning] [MY-011070] Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it is deprecated and will be removed in a future release.
2018-02-23T13:22:10.682938Z 0 [Warning] [MY-010915] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
2018-02-23T13:22:10.695441Z 0 [System] [MY-010116] /usr/sbin/mysqld (mysqld 8.0.4-rc-log) starting as process 1 ...
mbind: Operation not permitted
mbind: Operation not permitted
2018-02-23T13:22:11.537504Z 0 [Warning] [MY-010068] CA certificate ca.pem is self signed.
2018-02-23T13:22:11.542367Z 0 [Warning] [MY-000000] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2018-02-23T13:22:11.549449Z 0 [Warning] [MY-010315] 'user' entry 'mysql.infoschema@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.549556Z 0 [Warning] [MY-010315] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.549594Z 0 [Warning] [MY-010315] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.549629Z 0 [Warning] [MY-010315] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.549676Z 0 [Warning] [MY-010323] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.549727Z 0 [Warning] [MY-010323] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.549779Z 0 [Warning] [MY-010311] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.565161Z 0 [Warning] [MY-010330] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.565260Z 0 [Warning] [MY-010330] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-02-23T13:22:11.570621Z 0 [System] [MY-010931] /usr/sbin/mysqld: ready for connections. Version: '8.0.4-rc-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL).

```

**Comment by mvladimir7** [comment]
### Root cause
https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/

### Corrective action
Downgrade mysql version

**Comment by RohitVenturit** [comment]
Don't uninstall MySQL latest version. Rather follow these steps https://gist.github.com/benlinton/d24471729ed6c2ace731
Basically you need to unlink latest installed mysql, install older MSQL version and link it.

**Comment by ondast** [comment]
If you want to use mysql 8 with native password (the old way) you can follow the following steps:

Add this to my.cnf in **laradock\mysql\my.cnf** under [mysqld]:
`
default-authentication-plugin=mysql_native_password
`
Clear the data-folder (will destroy your data), rebuild the mysql container and it should work.

**Comment by ailionx** [comment]
`alter user 'username'@'localhost' identified with mysql_native_password by 'password';` would fix it.

**Comment by najamalvi** [comment]
alter user 'username'@'localhost' identified with mysql_native_password by 'password';  
Bravoo. This is the solution

**Comment by MaiQuocDuy** [comment]
Hi Mr. Ailionx and Mr. Najamalvi,
I'm a student in a country which don't speak English. I'm very happy when reading your guide but I don't understand what steps I should do. Please tell me more details. Thank so much !!!

**Comment by CoderBill** [comment]
Don't uninstall MySQL 8.  Sign into mysql using a terminal program:
`mysql -u root -p`
`my_password` 
`alter user 'username'@'localhost' identified with mysql_native_password by 'password';` 

This does the trick.

**Comment by allexsv** [comment]
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';` would fix it.

work for me, thank you!

**Comment by MaiQuocDuy** [comment]
It also work for me. Many many thanks for you. Have a nice day!!!

**Comment by zacksleo** [comment]
added these lines in docker-compose.yml fixed my issue:
```yaml
    mysql:
        image: mysql:8
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
```

**Comment by Crowbrammer** [comment]
You do not have to uninstall MySQL 8.x. You just need to go to your MySQL installer, reconfigure your server, and select Legacy Authentication Method (which retains MySQL 5.x compatibility). I figured this out through trial and error after my dsn in my PDO didn't allow me to connect. 

https://i.imgur.com/u4giuUM.png

**Comment by mostafaznv** [comment]
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';` would fix it.

you saved my life.
I changed default auth plugin to mysql native password in `/etc/my.cnf` and then used your command.
my problem solved

**Comment by darlandieterich** [comment]
if external/remote use replace 'localhost' to '%'

**Comment by yeysus** [comment]
> added these lines in docker-compose.yml fixed my issue:
> 
> ```yaml
>     mysql:
>         image: mysql:8
>         command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
> ```
You just saved my life @zacksleo, Thanks. Installing latest drupal 8.6.4 with MySQL 8.0.13 both via docker.

**Comment by thicolares** [comment]
> If you want to use mysql 8 with native password (the old way) you can follow the following steps:
> 
> Add this to my.cnf in **laradock\mysql\my.cnf** under [mysqld]:
> `default-authentication-plugin=mysql_native_password`
> Clear the data-folder (will destroy your data), rebuild the mysql container and it should work.

Just in case someone else is using laradock too, by "clear the data-folder" I guess is:

       $ rm -rf ~/.laradock/data

**Comment by pr0f3ss0rst3ph** [comment]
> Don't uninstall MySQL 8. Sign into mysql using a terminal program:
> `mysql -u root -p`
> `my_password`
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';`
> 
> This does the trick.

I'm using windows and I don't know which terminal program I should use for this. I really need help on this.

**Comment by srinivasakumar-a** [comment]
> Basic PDO user with a possible solution. You do not have to uninstall MySQL 8.x or even do the above (maybe... I'm not using Laradock). You just need to go to your MySQL installer, reconfigure your server, and select Legacy Authentication Method (which retains MySQL 5.x compatibility). I figured this out through trial and error after my dsn in my PDO didn't allow me to connect.
> 
> [Finding the Installer in Windows](https://i.imgur.com/jBI1F67.png)
> [Click 'Reconfigure'](https://i.imgur.com/FPg0u9Y.png)
> [Select the bottom option](https://i.imgur.com/u4giuUM.png)

thanks a lot for your work around and it worked for me! :)

**Comment by sammysaita** [comment]
> alter user 'username'@'localhost' identified with mysql_native_password by 'password';
> Bravoo. This is the solution

this really helped me

**Comment by leandroruel** [comment]
just remove damn mysql and use mariadb 10.x as main database, it works fine.

**Comment by zeynepoguz** [comment]
ERROR 1396 (HY000): Operation ALTER USER failed for 'username'@'localhost'

I am getting this error when I write this : 

> alter user 'username'@'localhost' identified with mysql_native_password by 'password';

**Comment by Ivan1234** [comment]
alter user 'username'@'localhost' identified with mysql_native_password by 'password'; This one helps me. Thank you!

**Comment by vipankumar-JFL** [comment]
mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';


login through command line, it works after that

**Comment by parth11291** [comment]
Access denied for user 'root'@'localhost' (using password: YES)

i have already used ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';

what to do now??

**Comment by leewanvu** [comment]
> > If you want to use mysql 8 with native password (the old way) you can follow the following steps:
> > Add this to my.cnf in **laradock\mysql\my.cnf** under [mysqld]:
> > `default-authentication-plugin=mysql_native_password`
> > Clear the data-folder (will destroy your data), rebuild the mysql container and it should work.
> 
> Just in case someone else is using laradock too, by "clear the data-folder" I guess is:
> 
> ```
>    $ rm -rf ~/.laradock/data
> ```

Thanks so much. You save my life.

**Comment by marciabeatrizcp** [comment]
> Basic PDO user with a possible solution. You do not have to uninstall MySQL 8.x or even do the above (maybe... I'm not using Laradock). You just need to go to your MySQL installer, reconfigure your server, and select Legacy Authentication Method (which retains MySQL 5.x compatibility). I figured this out through trial and error after my dsn in my PDO didn't allow me to connect.
> 
> [Finding the Installer in Windows](https://i.imgur.com/jBI1F67.png)
> [Click 'Reconfigure'](https://i.imgur.com/FPg0u9Y.png)
> [Select the bottom option](https://i.imgur.com/u4giuUM.png)


Worked fine! Thank you

**Comment by spatariu** [comment]
> 
> 
> > If you want to use mysql 8 with native password (the old way) you can follow the following steps:
> > Add this to my.cnf in **laradock\mysql\my.cnf** under [mysqld]:
> > `default-authentication-plugin=mysql_native_password`
> > Clear the data-folder (will destroy your data), rebuild the mysql container and it should work.
> 
> Just in case someone else is using laradock too, by "clear the data-folder" I guess is:
> 
> ```
>    $ rm -rf ~/.laradock/data
> ```

This is working, but to clarify the things a bit:
- if you don't find the .laradock folder and you are on Windows look in the `C:\Users\YourProfileName`, it should be there, on Linux try the logged user's folder (root if you logging in with it)
- build with `docker-compose build --no-cache mysql` and restart containers (down & up)
- don't forget to login in phpmyadmin with mysql/root/root or whatever you have in your .env file (mysql/default/secret)

**Comment by XorExpr** [comment]
> Don't uninstall MySQL 8. Sign into mysql using a terminal program:
> `mysql -u root -p`
> `my_password`
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';`
> 
> This does the trick.

well done! thanks

**Comment by Yusov** [comment]
if you use mysql latest version in docker container, you can type this command into docker-compose.yaml
` mysql:
    image: mysql:latest
#    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306`

or use oldest version mysql.

**Comment by zzkevinlim** [comment]
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
```

source: https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

**Comment by AhmadShiddiq** [comment]
> This worked for me on CentosOS.
> 
> ```
> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
> ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
> ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
> ```
> 
> source: https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

This works very well for me :D

**Comment by djkolka** [comment]
Its work for me !!!
Don't uninstall MySQL 8. Sign into mysql using a terminal program:
mysql -u root -p
my_password
alter user 'username'@'localhost' identified with mysql_native_password by 'password';

**Comment by stannlee** [comment]
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';` would fix it.

This worked for me. Thank you

**Comment by chadyred** [comment]
And actually with `docker-compose.yaml`

```
version: "3"
services:
  database:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
```

**Comment by resham58** [comment]
> This worked for me on CentosOS.
> 
> ```
> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
> ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
> ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
> ```
> 
> source: https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

This worked for me. Thank You.

**Comment by brianjohn9527** [comment]
> Basic PDO user with a possible solution. You do not have to uninstall MySQL 8.x or even do the above (maybe... I'm not using Laradock). You just need to go to your MySQL installer, reconfigure your server, and select Legacy Authentication Method (which retains MySQL 5.x compatibility). I figured this out through trial and error after my dsn in my PDO didn't allow me to connect.
> 
> [Finding the Installer in Windows](https://i.imgur.com/jBI1F67.png)
> [Click 'Reconfigure'](https://i.imgur.com/FPg0u9Y.png)
> [Select the bottom option](https://i.imgur.com/u4giuUM.png)

This really helps me fix my problem! Thanks for sharing!!!

**Comment by D3M1S22** [comment]
For Mac users, just go to System Preference, MySql panel, initialize Database, if use "strong password encryption" is selected choose "Use Legacy Password encryption", insert the root password and then click ok. It will require your pc password. Thats all.

**Comment by sunil-tamang** [comment]
or You can follow this video if you want or reset mysql password 
https://www.youtube.com/watch?v=T5wg7ekMje0

**Comment by adroutos** [comment]
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';` would fix it.

That works for me as well!! Thanks brow!

**Comment by hackdavid** [comment]
if you are facing "caching_sha2_password" error during connectivity of your mysql database using python ,
go through this
https://www.youtube.com/watch?v=YNq-EuQEJos

**Comment by VadneyK** [comment]
You can also fix this issue using phpmyadmin:
navigate to users->
change password->
enter your new password
make sure to select "Native MYSQL authentication" on the drop down "password hashing" menu

**Comment by noveleven** [comment]
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';` would fix it.

Amazing😄

**Comment by zahangir05** [comment]
Add following line under `[mysqld]` of your mysql configuration file, so called `my.cnf`

`default-authentication-plugin=mysql_native_password`

**Comment by sredeck** [comment]
> alter user 'username'@'localhost' identified with mysql_native_password by 'password';

thank you...it worked for me

**Comment by aives81** [comment]
It's work for me too !!
Thank you

**Comment by daniaaalarshad** [comment]
> ### Root cause
> 
> https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/
> ### Corrective action
> 
> Downgrade mysql version

Thanks to tell the root of the problem :)

**Comment by daniaaalarshad** [comment]
> Don't uninstall MySQL 8. Sign into mysql using a terminal program:
> `mysql -u root -p`
> `my_password`
> `alter user 'username'@'localhost' identified with mysql_native_password by 'password';`
> 
> This does the trick.

Thankyou so much <3

**Comment by GoodJob** [comment]
Changing Auth Method for User didn't worked for me, but changing standard Auth method of MySQL 8 - did.

Add lines:
[mysqld]
default-authentication-plugin=mysql_native_password

At the end of:
/etc/mysql/my.cnf

**Comment by Rmann-Ngoy** [comment]
if you are using Mysql 8.0.+ on Mac,

Uninstall Mysql 
re-install it and choose 'legacy password'
problem solved for me.

**Comment by asousajnri** [comment]
This worked for me https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

**Comment by rivolity** [comment]
in mysql 8.4

```
command: [
      '--character-set-server=utf8mb4',
      '--mysql-native-password=ON',
      '--collation-server=utf8mb4_unicode_ci'
    ]
```

**Comment by alvesrafa** [comment]
> ```yaml
>     mysql:
>         image: mysql:8
>         command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
> ```

You saved me, thanks!!

Im running mysql on server and i need to add this variables manually, but is easy:

you need to find your my.cnf and edit

`sudo nano /etc/mysql/my.cnf`

Add these lines on the end:


```
[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default-authentication-plugin=mysql_native_password
```


Save and restart the service:

`sudo systemctl restart mysql`
