### ISSUE TITLE
NGINX returning 500 error

### ISSUE THREAD

**Issue by jonny-khattar** [laradock/laradock#1393]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 13f55ef7967989337ed3538af3a8164268eeb623
- System info (Mac, PC, Linux): Mac
- System info disto/version: Sierra 10.12.6

### Issue:
I cant seem to get the nginx to load my website. I tried using the default configs and followed the 'Getting started' page on the laradock website. I have also tried to point directly to my wordpress site from the .env file as well as the /nginx/sites/default.conf file. All containers are fine and when i use "docker-compose exec workspace bash" ls shows mywebsite and laradock folders listed. when i use "docker-compose exec nginx bash" and ls /var/www/ i get the same result. When i browse to localhost/mywebsite i get "localhost is currently unable to handle this request."

_____

### Expected behavior:
The website should load
_____

### Reproduce:
Directory structure is 

 -Laradock
 -mywebsite 
_____

### Relevant Code:

```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
c97c63716bc3        laradock_nginx       "nginx"                  21 hours ago        Up 21 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   laradock_nginx_1
5cd794b9ae7a        laradock_php-fpm     "docker-php-entrypoi…"   21 hours ago        Up 21 hours         9000/tcp                                   laradock_php-fpm_1
ca39225e30a9        laradock_workspace   "/sbin/my_init"          21 hours ago        Up 21 hours         0.0.0.0:2222->22/tcp                       laradock_workspace_1
355faea4f66b        laradock_mysql       "docker-entrypoint.s…"   21 hours ago        Up 21 hours         0.0.0.0:3306->3306/tcp                     laradock_mysql_1

### Application Path ###################################################################################################
# Point to your code, will be available at `/var/www`.

APPLICATION=../

### PHP Version ########################################################################################################
# Select a PHP version of the Workspace and PHP-FPM containers (Does not apply to HHVM). Accepted values: 71 - 70 - 56

PHP_VERSION=70

### NGINX ##############################################################################################################

NGINX_HOST_HTTP_PORT=80
NGINX_HOST_HTTPS_PORT=443
NGINX_HOST_LOG_PATH=./logs/nginx/
NGINX_SITES_PATH=./nginx/sites/
NGINX_PHP_UPSTREAM_CONTAINER=php-fpm
NGINX_PHP_UPSTREAM_PORT=9000

/nginx/sites/default.conf

server {

    listen 80;
    listen [::]:80;

    server_name mywebsite.local;
    root /var/www/mywebsite/;
    index index.php index.html index.htm;

```

**Comment by bestlong** [comment]
edit MAC /etc/hosts add one line:
```
127.0.0.1    mywebsite.local
```

for laravel project,  update nginx/sites/default.conf set `root    /var/www/mywebsite/public`

**Comment by jonny-khattar** [comment]
Hi @bestlong 

Thanks for replying, i have tried this and im getting a 404 not found error now.

**Comment by bestlong** [comment]
@jonny-khattar 
start container please run `docker-compose up -d nginx mysql`
and browser url is http://mywebsite.local

**Comment by jonny-khattar** [comment]
@bestlong 
Now getting a 500 error "currently unable to handle this request".

When entering the nginx container and checking the error logs at /var/log/nginx/error.log the logs are empty.

Is there anything else other than the nginx/sites/default.conf file and the .env that could impact this?

**Comment by jonny-khattar** [comment]
@bestlong 
**Update** i have found that the server is fine when returning html files, however seems to be an issue with php files. Any suggestions on troubleshooting?

**Comment by bestlong** [comment]
@jonny-khattar reset all you change in `nginx/sites`

for laravel project, copy `laravel.conf.sample` config file to `mywebsite.conf` and edit two parts:
```
    server_name mywebsite.test;
    root /var/www/mywebsite/public;
```
then edit host os (your Mac)  `/etc/hosts` add one line:
```
127.0.0.1   mywebsite.test
```
run `docker-compose up -d nginx`

open url `http://mywebsite.test`

that's it. one web project one nginx config.
