### ISSUE TITLE
Allowed memory size

### ISSUE THREAD

**Issue by rafa-acioly** [laradock/laradock#1400]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 0077de28a13feea669f9d46ef21c20477fa6dbb0
- System info (Mac, PC, Linux): Linux
- System info disto/version: Elementary OS

### Issue:
i'm trying to run my application and i'm getting memory size problem even when i upgraded it.

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 3795 bytes) in ...

Memory limit on `php56.ini`: memory_limit = 1024M

**Comment by UniBen** [comment]
Have you made sure your VM has been allocated at least 1024M?

You can change the allocated resources in the advanced tab of Docker:
![image](https://user-images.githubusercontent.com/32358483/38312558-f9085cf2-3819-11e8-806d-a92d1087de4b.png)

**Comment by UniBen** [comment]
I was referring to the memory of the docker vm, not the memory allocated in your php.ini.  It doesn't look like your script is trying to allocate more memory than available. Would it be possible to output the result of phpinfo?

**Comment by ryancwalsh** [comment]
I wonder if https://docs.docker.com/config/containers/resource_constraints/ helps. I'm running a small server (1 GB RAM) and am having problems with MySQL crashing, and I want to see what I can do to prevent crashes without upgrading my server to more memory. I'm hoping `memory-swap` will help, but I'm not yet sure where to configure that.

**Comment by ryancwalsh** [comment]
@rafa-acioly Did you find a solution?

**Comment by pifeifei** [comment]
> 

+1
