### ISSUE TITLE
Recommend way to run "php artisan migrate" on build

### ISSUE THREAD

**Issue by CorvinSteindl** [laradock/laradock#1403]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): a797d67f149cdcc922cc5df1f0ffd7e8fcceb570
- System info (Mac, PC, Linux): Ubuntu
- System info disto/version: 17.10

### Issue:
What is the recommend Way to migrate the database on build?
I added this to the workspace docker file but it failed:

`RUN /var/www/artisan migrate:fresh --seed`

`Could not find Input File`

**Comment by bestlong** [comment]
@CorvinSteindl Dockerfile RUN instruction will add new layer to image. mysql service not up.

**Comment by CorvinSteindl** [comment]
Okay but what is the recommend way to deploy a laravel Application to production (inclusive migration and seeding) ?
