### ISSUE TITLE
Eeee porcaria que não funiona : mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]

### ISSUE THREAD

**Issue by MattBidas** [laradock/laradock#1407]
# **Do not tell me to change the version of mysql**

### Info:
- Docker version (`$ docker --version`): 
Docker version 17.12.0-ce, build c97c6d6

- Laradock commit (`$ git rev-parse HEAD`): 
c4aef8e901a867a57df0b1aadf1c872165e65295

- System info (Mac, PC, Linux): 
Win10
- System info disto/version: 
Pro
### Issue:
On enter phpmyadmin panel in http://localhost:8080/
mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]

### Expected behavior:
Login in localhost:8080
Server: mysql
login: root
password: root

### Expected behavior:
Login in phpmyadmin Mysql Management
_____

### Reproduce:
#2054 - The server requested authentication method unknown to the client
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by Pherserk** [comment]
same problem here, my laravel configuration:
DB_CONNECTION=mysql
DB_HOST=laradock_mysql_1
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret

Mysql configuration has been left unchanged.

When i run artisan migrate I get:
`root@dbdfcc2b363f:/var/www# php artisan migrate -v

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = default and table_name = migrations)

  at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php: 664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]")
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php : 68

  2   PDO::__construct("mysql:host=laradock_mysql_1;port=3306;dbname=default", "default", "secret", [])
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php : 68

  3   Illuminate\Database\Connectors\Connector::createPdoConnection("mysql:host=laradock_mysql_1;port=3306;dbname=default", "default", "secret", [])
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php : 44

  4   Illuminate\Database\Connectors\Connector::createConnection("mysql:host=laradock_mysql_1;port=3306;dbname=default", [])
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php : 24

  5   Illuminate\Database\Connectors\MySqlConnector::connect()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php : 183

  6   Illuminate\Database\Connectors\ConnectionFactory::Illuminate\Database\Connectors\{closure}()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 915

  7   call_user_func(Object(Closure))
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 915

  8   Illuminate\Database\Connection::getPdo()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 940

  9   Illuminate\Database\Connection::getReadPdo()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 399

  10  Illuminate\Database\Connection::getPdoForSelect()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 325

  11  Illuminate\Database\Connection::Illuminate\Database\{closure}("select * from information_schema.tables where table_schema = ? and table_name = ?")
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 657

  12  Illuminate\Database\Connection::runQueryCallback("select * from information_schema.tables where table_schema = ? and table_name = ?", Object(Closure))
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 624

  13  Illuminate\Database\Connection::run("select * from information_schema.tables where table_schema = ? and table_name = ?", Object(Closure))
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 333

  14  Illuminate\Database\Connection::select("select * from information_schema.tables where table_schema = ? and table_name = ?")
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php : 18

  15  Illuminate\Database\Schema\MySqlBuilder::hasTable("migrations")
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php : 169

  16  Illuminate\Database\Migrations\DatabaseMigrationRepository::repositoryExists()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 545

  17  Illuminate\Database\Migrations\Migrator::repositoryExists()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php : 97

  18  Illuminate\Database\Console\Migrations\MigrateCommand::prepareDatabase()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php : 63

  19  Illuminate\Database\Console\Migrations\MigrateCommand::handle()
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  20  call_user_func_array([])
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  21  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 87

  22  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 31

  23  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php : 564

  24  Illuminate\Container\Container::call()
      /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php : 183

  25  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/vendor/symfony/console/Command/Command.php : 252

  26  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php : 170

  27  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/symfony/console/Application.php : 865

  28  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/symfony/console/Application.php : 241

  29  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/symfony/console/Application.php : 143

  30  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php : 88

  31  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php : 121

  32  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/artisan : 37
`

But entering the mysql container in bash:
mysql -udefault -psecret

authenticates me and the table default exists.

**Comment by Pherserk** [comment]
@MattBidas it seems there is another issue opened:
https://github.com/laradock/laradock/issues/1392

Downgrade to previous mysql version seems to work.

**Comment by bestlong** [comment]
stop all service `docker-compose down`
Edit `.env` file set `MYSQL_VERSION=5.7` or `MYSQL_VERSION=latest`
```
### Delete mysql database
$ rm -rf ~/.laradock/data/mysql

### rebuild mysql image
$ docker-compose build mysql

### retry
$ docker-compose up -d nginx mysql phpmyadmin
```
It's working for me.

**Comment by MattBidas** [comment]
Thanks @bestlong and @Pherserk !!!

You are awesome !!!

Work Fine Now !!!

Thanks Too Much

**Comment by MattBidas** [comment]
Thanks @bestlong and @Pherserk !!!

You are awesome !!!

Work Fine Now !!!

Thanks Too Much

**Comment by toorCode** [comment]
Thank you so much 
You are awesome  @bestlong 
Work well now

**Comment by kavim** [comment]
SIMMMMM funcionaaaaa!!

**Comment by SamuelYute** [comment]
This works perfectly

Thanks

**Comment by jeshio** [comment]
> stop all service `docker-compose down`
> Edit `.env` file set `MYSQL_VERSION=5.7` or `MYSQL_VERSION=latest`
> 
> ```
> ### Delete mysql database
> $ rm -rf ~/.laradock/data/mysql
> 
> ### rebuild mysql image
> $ docker-compose build mysql
> 
> ### retry
> $ docker-compose up -d nginx mysql phpmyadmin
> ```
> It's working for me.

only with `MYSQL_VERSION=5.7` works

**Comment by atualizado** [comment]
> stop all service `docker-compose down`
> Edit `.env` file set `MYSQL_VERSION=5.7` or `MYSQL_VERSION=latest`
> 
> ```
> ### Delete mysql database
> $ rm -rf ~/.laradock/data/mysql
> 
> ### rebuild mysql image
> $ docker-compose build mysql
> 
> ### retry
> $ docker-compose up -d nginx mysql phpmyadmin
> ```
> It's working for me.


You are awesome !!! ❤
Work Fine Now !!! 👍
Thanks

**Comment by hokhyk** [comment]
Change my.cnf file under mysql directory of laradock as below:
     [mysqld]
default_authentication_plugin=mysql_native_password

rebuild mysql image.

**Comment by valiner** [comment]
> stop all service `docker-compose down`
> Edit `.env` file set `MYSQL_VERSION=5.7` or `MYSQL_VERSION=latest`
> 
> ```
> ### Delete mysql database
> $ rm -rf ~/.laradock/data/mysql
> 
> ### rebuild mysql image
> $ docker-compose build mysql
> 
> ### retry
> $ docker-compose up -d nginx mysql phpmyadmin
> ```
> 
> It's working for me.

thx ~~
