### ISSUE TITLE
the data container and the application container can't open 

### ISSUE THREAD

**Issue by wangyijunjunjun** [LaraDock/laradock#141]
the container named laradock_data_1  just can't run 

Name                      Command             State                     Ports                   
laradock_application_1   true                          Exit 0                                            
laradock_data_1              true                          Exit 0

**Comment by Mahmoudz** [comment]
That's not a problem at all. They are made to remain in exit state, since you don't need to enter them.

Watch this demo for more info https://www.youtube.com/watch?v=-DamFMczwDA

Best,
