### ISSUE TITLE
Apigility+laradock

### ISSUE THREAD

**Issue by prashant7july** [laradock/laradock#1410]
Hi,

I need to setup laradock with redis cluster. laradock not suppot redis cluster, So how to modify docker-composer.yml for [Redis-Cluster](https://github.com/developersworkspace/Production-Apps/tree/master/Redis-Cluster)? means How to modify docker-composer.yml to execute curl command?

version: '2'
services:
  ...
  redis-cluster:
    build: .
    command: curl curl -s https://raw.githubusercontent.com/developersworkspace/Production-Apps/master/Redis-Cluster/install.sh | bash -s "7001|7002|7003|7004|7005|7006|7007|7008" && curl -s https://raw.githubusercontent.com/developersworkspace/Production-Apps/master/Redis-Cluster/cluster.sh | bash -s "1" "192.168.1.101|192.168.1.102" "7001|7002|7003|7004|7005|7006|7007|7008"

**Comment by hareku** [comment]
I opned PR #1981
