### ISSUE TITLE
installation issue: ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by cuihaifeng1234** [laradock/laradock#1411]
### Info:
- Docker version (`$ docker --version`): 17.12.0
- Laradock commit (`$ git rev-parse HEAD`): c4aef8e901a867a57df0b1aadf1c872165e65295
- System info (Mac, PC, Linux): PC
- System info disto/version: windows10

### Issue:

`[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_AEROSPIKE} = true ]; then     apt-get update -yqq &&     apt-get -y install sudo wget &&     curl -L -o /tmp/aerospike-client-php.tar.gz "https://github.com/aerospike/aerospike-client-php/archive/7.2.0-in-progress.tar.gz"     && mkdir -p aerospike-client-php     && tar -C aerospike-client-php -zxvf /tmp/aerospike-client-php.tar.gz --strip 1     && (         cd aerospike-client-php/src         && phpize         && ./build.sh         && make install     )     && rm /tmp/aerospike-client-php.tar.gz ;fi
[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_MSSQL} = true ]; then     apt-get update -yqq && apt-get install -y apt-transport-https gnupg         && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -         && curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list         && apt-get update -yqq         && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev libgss3 odbcinst msodbcsql locales         && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen         && pecl install pdo_sqlsrv-4.1.8preview sqlsrv-4.1.8preview         && docker-php-ext-enable pdo_sqlsrv sqlsrv ;fi
[WARNING]: Empty continuation lines will become errors in a future release.`

`Creating laradock_applications_1 ... error
Creating laradock_mysql_1        ... error
Creating laradock_applications_1 ...
Creating laradock_mysql_1        ...

ERROR: for laradock_applications_1  Cannot create container for service applications: Drive has not been shared

ERROR: for laradock_mysql_1  Cannot create container for service mysql: Drive has not been shared

ERROR: for applications  Cannot create container for service applications: Drive has not been shared

ERROR: for mysql  Cannot create container for service mysql: Drive has not been shared
ERROR: Encountered errors while bringing up the project.`

**Comment by ganicus** [comment]
I have the exact same issue

## Info:
- Docker version 17.12.0-ce, build c97c6d6
- Laradock Commit c4aef8e
- System info (Mac, PC, Linux): PC
- System info disto/version: windows10 Pro

**Comment by ganicus** [comment]
AH HA!!! 

In your .env file at the very bottom there is a variable you need to change for your Windows machine to allow proper Drive Sharing:

```
### DOCKER-SYNC ################################################################################################

# osx: 'native_osx' (default)
# windows: 'unison'
# linux: docker-sync not required

DOCKER_SYNC_STRATEGY=unison

########################################################################################################################
```
