### ISSUE TITLE
Cannot edit files created inside workbench

### ISSUE THREAD

**Issue by luis-don-dev** [laradock/laradock#1413]
### Info:
- Docker version 17.12.0-ce, build c97c6d6
- Linux
- Elementary OS Loki (based on ubuntu 16.04)
### Issue:
When I create files inside workbench I cannot edit them on my IDE (PHPSTORM) giving me error about permissions.

**Comment by BrunoBA** [comment]
I have the same problem... When create files inside the container (workspace) this file is inaccessible.. (Only by root)

Failed to save 'file.txt': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser.

**Comment by BrunoBA** [comment]
@luis-don-dev , try to set the user "laradock" when enter on container

`docker-compose exec --user=laradock workspace bash`
