### ISSUE TITLE
Getting started guide doc issue.

### ISSUE THREAD

**Issue by Oscar-21** [laradock/laradock#1416]
I have a question about step 4.
```4 - Add the domains to the hosts files.```
```
127.0.0.1  project-1.test
127.0.0.1  project-2.test
```
It's not all together clear to me what hosts file needs to be updated. The hosts file in the nginx container or the host machine?  

Thanks for all of your work on this project it's pretty awesome!

**Comment by brunen9** [comment]
It's on your host system. And there will be your nginx (or another http server) in the container, listening.
