### ISSUE TITLE
Add php-pcntl extension to php-worker Dockerfiles 

### ISSUE THREAD

**Issue by Degete** [laradock/laradock#1419]
### Info:
- Docker version: 17.12.1-ce
- Laradock commit: e580b7c510e04c48515b86e23a76702efb6ee75e
- System info: Linux
- System info disto/version: Debian

### Issue:
Laravel Horizon does not work because of php pcntl extension required.

### Reproduce:
command=php /var/www/artisan horizon

### Fix:
On the different Dockerfiles of the php-worker include:
RUN docker-php-ext-install mysqli mbstring pdo pdo_mysql mcrypt tokenizer xml **pcntl**

**Comment by hackel** [comment]
Looks like this can be closed after 6b6e2d5f86f89acfbc2c9ee50b7d9d54af1b875f was merged in v7.0.1.
