### ISSUE TITLE
mysql start issue with port binding

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [LaraDock/laradock#142]
when i run 
```
docker-compose start mysql
```
i get the error
```
ERROR: for mysql  driver failed programming external connectivity on endpoint 
761b565f95e4_laradock_mysql_1 
(c7d6669b4bb05506151f7cd1d43756c035944abb0977134d2998f258386776f9): 
Bind for 0.0.0.0:3306 failed: port is already allocated
```
while it is actually successfully started and i'm sure it was not started before this - i checked twice with mysql client. 
i don't get it...

proof screen: http://joxi.ru/L21LYKWF6lXNwm

**Comment by orette** [comment]
Try this **sudo lsof -i :3306** to see which process is already using the port.
You can then shutdown that process or do a **kill PID** to end the process if it's not critical.
