### ISSUE TITLE
Connection is closed by foreign host with xDebug in PhpStorm

### ISSUE THREAD

**Issue by sereden** [laradock/laradock#1422]
### Info:
- Docker version (`$ docker --version`):  17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): c4aef8e901a867a57df0b1aadf1c872165e65295
- System info (Mac, PC, Linux): macOS 10.13.3
- PhpStorm: 2017.1.4
- PhpStorm's JRE: 1.8.0_112

### Issue:
I was following [given tutorial](http://laradock.io/guides/#phpstorm-settings) to set up xDebug and I failed at step 1 when I need provide PhpStorm with `insecure_id_rsa.ppk`.
Firstly, I entered path to file in `laradock/workspace` and got 
```
Keypair ‘laradock/workspace/insecure_id_rsa.ppk’ is corrupt or has unknown format. Only SSH2 keys in OpenSSH format or PuTTY Private Key *.ppk are supported. Error message: The cipher ‘aes256-cbc’ is required, but it is not available
```
![screen shot 2018-03-11 at 11 20 44_censored](https://user-images.githubusercontent.com/1812174/37251784-fd036742-251e-11e8-99aa-81acb101341b.jpg)

Then I've found two possible solutions.
_First_ is to [download the correct "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files"](https://stackoverflow.com/a/26682459) and replace PhpStorm's files. Which didn't help me and I still received the message described above.

And _second_ one to [re-export](http://laradock.io/guides/#let-s-shell-into-workspace) `insecure_id_rsa` using `puttygen` (it was a nightmare to do on Mac) and finally describing error disappeared. But `Remote Host` tab displays another problem - 
```
connection is closed by foreign host
``` 
![screen shot 2018-03-11 at 11 33 46_censored](https://user-images.githubusercontent.com/1812174/37251865-5a370ddc-2520-11e8-8b57-d7994dc8fdec.jpg)

Does anyone have ideas why it might happen? Maybe I mixed something?

**Comment by dmz9** [comment]
@sereden 
+1, any news on that? )

**Comment by sereden** [comment]
@dmz9 no :-( Have spent time re-installing from scratch, watched different tutorial, used different versions of PhpStorm (btw, the latest one displays another message) and still no results

**Comment by paslandau** [comment]
Not sure why it's even recommended to use the .ppk file. Did you try using "laradock/workspace/insecure_id_rsa"?
