### ISSUE TITLE
Using mongodb with username/password

### ISSUE THREAD

**Issue by biren** [laradock/laradock#1428]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.1-ce, build 7390fc6
- Laradock commit (`$ git rev-parse HEAD`): c5c4d1947651c8311742fa974011a4c0b3815ce5
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04

### Issue:
There doesn't seem to be a way to run mongo container with authentication. Initial user creation functionality is missing (unlike postgres).
_____

### Expected behavior:
Mongo container to take care of user creation at the time of install. May be using a script approach like: [http://blog.bejanalex.com/2017/03/running-mongodb-in-a-docker-container-with-authentication/](url)
_____

### Reproduce:
* Follow all the setup/config instructions for jenssegers/mongodb and composer. 
php artisan tinker
```
$user = DB::connection('mongodb')->collection('users')->get();
MongoDB\Driver\Exception\AuthenticationException with message 'Authentication failed.'
```

* Verify there is no --auth for mongo command line inside the container 
```
mongodb      1     0  0 00:39 ?        00:00:12 mongod --bind_ip_all
```
* Connecting to mongodb from an external UI (like Robo 3T) without user/pass works too. 

* For running mongodb inside a docker container, may be we can drop an initial user creation script inside ```docker-entrypoint-initdb.d```. 

### Relevant Code:
* app/config/database.php:
```
        'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('MONGODB_HOST', '127.0.0.1'),
            'port' => env('MONGODB_PORT', '27017'),
            'database' => env('MONGODBDB_DATABASE', ''),
            'username' => env('MONGODB_USERNAME', ''),
            'password' => env('MONGODB_PASSWORD', ''),
            'options'  => [
                'database' => 'admin',
            ],
        ],

```

**Comment by fadighattas100** [comment]
is their some updated on this or it just closed and we need to reopen a new issue ?
