### ISSUE TITLE
docker-compose.yml is invalid

### ISSUE THREAD

**Issue by mlwooding** [laradock/laradock#1437]
### Info:
- Docker version (`$ docker --version`):  17.12.0-ce-win47 (15139)
- Laradock commit c34d2d12b3a32c90b4d5697ce6df8e56970dc9f6: 
- System info (Mac, PC, Linux):  PC
- System info disto/version:  Windows 10 Pro

### Issue:

there is something wrong with the docker-compose.yml file or something really wrong with your "Getting Started" instructions - even tried as per video on YouTube (with version 5 additional steps) and it fails everytime with "The compose file '\.docker-compose.yml' is invalid because: 
services.proxy.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.proxy2.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.memcached.ports is invalid: Port ranges don't match in length
services.beanstalkd.ports is invalid: Port ranges don't match in length
services.mssql.ports is invalid: Port ranges don't match in length
services.rabbitmq.ports is invalid: Port ranges don't match in length
services.rabbitmq.ports is invalid: Port ranges don't match in length
services.beanstalkd-console.ports is invalid: Port ranges don't match in length
services.workspace.ports is invalid: Port ranges don't match in length
services.maildev.ports is invalid: Port ranges don't match in length
services.mongo.ports is invalid: Port ranges don't match in length
services.aerospike.ports is invalid: Port ranges don't match in length
services.grafana.ports is invalid: Port ranges don't match in length
services.aerospike.ports is invalid: Port ranges don't match in length
services.aerospike.ports is invalid: Port ranges don't match in length
services.aerospike.ports is invalid: Port ranges don't match in length
services.mariadb.ports is invalid: Port ranges don't match in length
services.mysql.ports is invalid: Port ranges don't match in length
services.percona.ports is invalid: Port ranges don't match in length
services.apache2.ports is invalid: Port ranges don't match in length
services.caddy.ports is invalid: Port ranges don't match in length
services.nginx.ports is invalid: Port ranges don't match in length
services.selenium.ports is invalid: Port ranges don't match in length
services.jenkins.ports is invalid: Port ranges don't match in length
services.postgres.ports is invalid: Port ranges don't match in length
services.postgres-postgis.ports is invalid: Port ranges don't match in length
services.kibana.ports is invalid: Port ranges don't match in length
services.rabbitmq.ports is invalid: Port ranges don't match in length
services.laravel-echo-server.ports is invalid: Port ranges don't match in length
services.redis.ports is invalid: Port ranges don't match in length
services.apache2.ports is invalid: Port ranges don't match in length
services.caddy.ports is invalid: Port ranges don't match in length
services.maildev.ports is invalid: Port ranges don't match in length
services.nginx.ports is invalid: Port ranges don't match in length
services.phpmyadmin.ports is invalid: Port ranges don't match in length
services.adminer.ports is invalid: Port ranges don't match in length
services.jenkins.ports is invalid: Port ranges don't match in length
services.rethinkdb.ports is invalid: Port ranges don't match in length
services.haproxy.ports is invalid: Port ranges don't match in length
services.solr.ports is invalid: Port ranges don't match in length
services.minio.ports is invalid: Port ranges don't match in length
services.elasticsearch.ports is invalid: Port ranges don't match in length
services.elasticsearch.ports is invalid: Port ranges don't match in length
_____

### Expected behavior:
 should start a docker container
_____

### Reproduce:
 just do a brand new laradock install on a windows 
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by mlwooding** [comment]
with help from fantastic Roger Roelofs worked out this was caused by your instructions not working on my latest Windows 10 Pro laptop.   to rename to .env, I needed to first rename to env-example.env and then to .env

you might like to test and see whether that was just a one off, or a change for Windows

**Comment by TummenUppGeInteUpp** [comment]
Have the same issue and im on macos high sierra 10.13.5 , 

ERROR: The Compose file './docker-compose.yml' is invalid because:

services.proxy.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.proxy2.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.memcached.ports is invalid: Port ranges don't match in length

........


i totally gutted .. 

any tips ? 
@mlwooding
@brunoecq

**Comment by tarunhere** [comment]
I am also running on Mac OS High Sierra

```
laradock git:(master) ✗ docker-compose build
WARNING: The INSTALL_BLACKFIRE variable is not set. Defaulting to a blank string.
WARNING: The AEROSPIKE_PHP_REPOSITORY variable is not set. Defaulting to a blank string.
WARNING: The BLACKFIRE_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The BLACKFIRE_CLIENT_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The MEMCACHED_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The PMA_USER variable is not set. Defaulting to a blank string.
WARNING: The PMA_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The PMA_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The PMA_PORT variable is not set. Defaulting to a blank string.
WARNING: The PMA_DB_ENGINE variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.memcached.ports is invalid: Port ranges don't match in length
services.phpmyadmin.ports is invalid: Port ranges don't match in length
```

Would appreciate any help/tips. Thanks

**Comment by shingo0620** [comment]
you have to update your .env file

**Comment by wimdeblauwe** [comment]
I had the same problem on macOS. After updating laradock, you need to compare your `.env` file with the `env-example` file. By adding all missing properties to your `.env` file, docker compose works again.

**Comment by igorbuts** [comment]
Had the same problem on macOS sierra 10.13.5
@shingo0620 @wimdeblauwe, thanks, updating `.env` file from `env-example` helps 👍

**Comment by jasperf** [comment]
In my case I ran a crontab job on an ssh file that called `prod-docker-compose.yml` in a directory below. As it could not find .env in the same directory it started mentioning nothing was defined. Had to move the bash file down that directory where the `.env` was located.

**Comment by eddyson1006** [comment]
For my case, I terminal into the `/laradock` folder, make sure I have copied the `.env-example` to `.env`

P/S: Please make sure that the `.env` file has a "dot" in front of "env". Docker command doesn't recognise an "env" without a "dot".

**Comment by sonbarros** [comment]
Tive o mesmo problema no Fedora e foi solucionado com esse issue

**Comment by sonbarros** [comment]
Tive o mesmo problema no Fedora e foi solucionado com esse issue
