### ISSUE TITLE
Issue with docker.for.mac.host.internal 

### ISSUE THREAD

**Issue by GinoPane** [laradock/laradock#1448]
### Info:
- Docker version (`$ docker --version`): 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 0077de28a13feea669f9d46ef21c20477fa6dbb0
- System info (Mac, PC, Linux): MacOS Sierra
- System info disto/version: 10.12 (16A323)

### Issue:
Host IP may change that's why I wanted to utilize newly Mac-only DNS name `docker.for.mac.host.internal`. I set it tinto my .env file and got this error when I tried to start containers afterwards:

> ERROR: for laradock_workspace_1  Cannot create container for service workspace: invalid IP address in add-host: "docker.for.mac.host.internal"

_____

### Expected behavior:
Docker Host IP should be populated correctly

**Comment by spyridonas** [comment]
After a bit of searching I found a use who said
"Nevermind, I forgot that a program I'm running called Freedom messes up networking for some Docker images." Can you try that?

**Comment by bestlong** [comment]
@GinoPane why `docker.for.mac.host.internal` need manual setting?
just use it in container.

**Comment by GinoPane** [comment]
@bestlong This is the issue actually, I wanted to use it and set it in `.env` file (as `DOCKER_HOST` variable), which further populates `docker-compose.yaml` and got this error when building containers.
