### ISSUE TITLE
INSTALL_MSSQL ERROR

### ISSUE THREAD

**Issue by rjcfj** [laradock/laradock#1449]
### Info:
- Docker version (`$ docker --version`): Docker version 18.02.0-ce, build fc4de447b5 
- Laradock commit (`$ git rev-parse HEAD`): 21a5d5bf98b108400bbfee385e6489211a7a582e
- System info (Mac, PC, Linux):  PC 
- System info disto/version: Windiws 7 Pro

### Issue:

[WARNING]: Empty continuation line found in:
    RUN if [ ${INSTALL_MSSQL} = true ]; then     apt-get update -yqq && apt-get install -y apt-transport-https gnupg         && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
         && curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list         && apt-get update -yqq         && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev libgss3 odbcinst msodbcsql locales         && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen         && pecl install pdo_sqlsrv-4.1.8preview sqlsrv-4.1.8preview         && docker-php-ext-enable pdo_sqlsrv sqlsrv ;fi
[WARNING]: Empty continuation lines will become errors in a future release.
_____

### Expected behavior:

Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20170718/sqlsrv.so'
install ok: channel://pecl.php.net/sqlsrv-4.1.8preview
configuration option "php_ini" is not set to php.ini location
You should add "extension=pdo_sqlsrv.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=pdo_sqlsrv.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=sqlsrv.so" to php.ini

_____

### Reproduce:
SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2' : file not found
_____

**Comment by bestlong** [comment]
@rjcfj i increase build check at #1450 
please try again and update detail build fail info.

**Comment by rjcfj** [comment]
PHP version 7.1, It worked out well. But PHP 7.2 still issue same form "SQLSTATE [01000]: [unixODBC] [Driver Manager] Can not open lib".

**Comment by rjcfj** [comment]
Still problem PHP 7.2 until moment without SQL Server drive. something to fix SQLServe

**Comment by DeadMerc** [comment]
Got this problem too, on php7.1 works perfectly, thanks @rjcfj

**Comment by rjcfj** [comment]
Thanks dude @DeadMerc
