### ISSUE TITLE
Laravel is very slow on Mac?

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [LaraDock/laradock#145]
it's about 10-15 times slower then in VM environment (homestead/virtualbox). 
Just booting the laravel takes 1.2-1.3 sec.
xdebug disabled.
do i make something wrong?
docker supposed to be faster then VM, not 15 times slower!

host: MacBook Pro i7, 16G RAM, SSD - not an issue for sure.

**Comment by Vasiliy-Bondarenko** [comment]
Seems like it a problem with Docker for Mac.
Ok. I've used https://github.com/EugenMayer/docker-sync to solve this problem. Not so easy, but it works... Now times are even faster then on VM.

**Comment by Mahmoudz** [comment]
seems the issue of #97

**Comment by midascodebreaker** [comment]
is there a windows version of this docker sync? more or less this is something link turning nfs On for that folder if im not mistaken? im also looking for this option...

i know how to do it in windows , homestead installation but docker / laradock it is somewhat missing in the documentation...

**Comment by citosid** [comment]
@Vasiliy-Bondarenko how did you do it with docker-sync?

**Comment by huedaya** [comment]
Seems not yet improving in 2023, but my current solution is to run test/lint locally when on Mac

```bash
#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
    php ./vendor/bin/php-cs-fixer fix -vvv --show-progress=dots --config .php-cs-fixer.php

    php ./vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots
    php ./vendor/bin/phpstan analyse --memory-limit=2G
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    docker-compose exec app bash -c "composer lint"
    docker-compose exec app bash -c "composer sniff"
else
    echo "Unknown operating system"
fi

```
