### ISSUE TITLE
do I need to have visualization technology in machine to use laradock ?

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#1456]
hello guys , I tryed to install homestead in my machine but it was not success becose it does not has visualization technology in my computer ( it does not suport ) .
to work with laradock , my computer must support visualization technology as well ?

Thanks

**Comment by brunen9** [comment]
If you use Linux then you'll not need virtualization support, as Docker on Linux uses its kernel. For other operating systems, you'll need virtualization support as you'll need to run a virtual machine with Linux.
