### ISSUE TITLE
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

### ISSUE THREAD

**Issue by ankit20893** [laradock/laradock#1462]
ankit@ankit-X555LAB:~/Desktop/LaraDock/laradock$ docker-compose up -d nginx mysql
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by Multoryan** [comment]
**sudo** docker-compose up -d nginx mysql
