### ISSUE TITLE
Workspace Dockerfile parse error

### ISSUE THREAD

**Issue by idbartosz** [laradock/laradock#1467]
### Info:
- Docker version: 18.03.0-ce, build 0520e24
- Laradock commit: b45bf46436fb7513642f9c7aaee4f55cc1ca53e4
- System info disto/version: Windows 10

### Issue:
When docker-compose enters **workspace** related part (eg. ngnix or apache2) it throws:
`Dockerfile parse error line 58: unknown instruction: USERMOD`
_____

### Fix:
Add ` && \` at the end of line 57 in `workspace/dockerfile-72`

_____

### Reproduce:
```
docker system prune -a
cd laradock
docker-compose up nginx -d
```
_____

**Comment by inductor** [comment]
same for Dockerfile-71

**Comment by inductor** [comment]
seems fixed
