### ISSUE TITLE
Helm Chart for Kubernetes

### ISSUE THREAD

**Issue by oberoivarun** [laradock/laradock#1469]
### Feature Request:
A Helm Chart for deploying to a Kubernetes cluster.

To start, we can just focus on a mysql+nginx deployment.
_____

### Expected behavior:
Moving forward from docker-compose (which is not going to be supported in the long run by major cloud providers) to kubernetes.
_____
### Relevant Code:
https://github.com/markhilton/larakube
This is something to start with. But it is completely independent from laradock. Ideally, we should be able to build containers using laradock (Inside the minikube docker-env for minikube or upload them to a container repository) and then just do a `helm install`. 

Sample Code:

I am not proficient in Kubernetes, but due to the lack of any material out there, i am slowly learning. I just want to start this thread so we can at least start to move towards it.

**Comment by Anishmourya** [comment]
@oberoivarun  I have created laradock helm chart https://github.com/Anishmourya/laradock-kubernetes
