### ISSUE TITLE
docker-compose up failing when trying to install memcached

### ISSUE THREAD

**Issue by raheelkhan** [LaraDock/laradock#147]
![image](https://cloud.githubusercontent.com/assets/7078218/16845272/e9d3cd32-4a1a-11e6-9ff9-77b9e7139b00.png)

**Comment by francislavoie** [comment]
Same here.

**Comment by Kauhat** [comment]
#146 

Could replicate on Windows Beta after running `docker pull php:7.0-fpm`.

**Comment by infojasyrc** [comment]
Same error on OSX.

**Comment by Kauhat** [comment]
Seems to coincide with a today's update of the [official php images](https://hub.docker.com/r/library/php/tags/). Would need to dive a little deeper to find how it broke - although I believe it's linked to [this file](https://github.com/docker-library/php/blame/f016f5dc420e7d360f7381eb014ac6697e247e11/7.0/fpm/docker-php-source#L27) as a `memcached` directory doesn't appear to be in the `ext` directory of the PHP tarball that the script downloads.

In the meanwhile, you can build the container by deleting the `# Install Memcached for php 7` section from the `php-fpm/Dockerfile-70` directory.

**Comment by Kauhat** [comment]
I don't think Laravel uses memcached by default, so it may be a worthwhile idea to put it in a separate container if possible, or Redis instead!

**Comment by francislavoie** [comment]
No, that's the memcached PHP extension, not memcached itself. That extension is needed on the PHP-FPM container for it to be able to interface with memcached itself. It can't be in a separate container.

**Comment by luukverhoeven** [comment]
```
Possible values for ext-name:
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz"     && mkdir -p /usr/src/php/ext/memcached     && tar -C /usr/src/php/ext/memcached -zxvf /tmp/memcached.tar.gz --strip 1     && docker-php-ext-configure memcached     && docker-php-ext-install memcached     && rm /tmp/memcached.tar.gz' returned a non-zero code: 1
```

Same error here, docker-toolbox was working. Switch to docker itself and getting this error.

**Comment by luukverhoeven** [comment]
Is there some workarround for it?

**Comment by computerfr33k** [comment]
I have worked around it by doing this:

```dockerfile
# Install Memcached for php 7
RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
    && mkdir -p memcached \
    && tar -C memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
    && ( \
        cd memcached \
        && phpize \
        && ./configure \
        && make -j$(nproc) \
        && make install \
    ) \
    && rm -r memcached \
    && rm /tmp/memcached.tar.gz \
    && docker-php-ext-enable memcached
```

**Comment by Kauhat** [comment]
@computerfr33k I've tested your fix on my machine, and it works great!

I've also made a fork with [alternate versions of php-fpm for 5.6 & 7.0](https://github.com/Kauhat/laradock/tree/alpine#change-the-php-fpm-version). These images use PHP packages from Alpine's `testing` repository, so it's a little easier to add and remove modules. (As long as they exist in the repository!) As the compiling step is skipped, the initial build is also a little faster for me.

**Comment by thusfar7** [comment]
How to get this working on Debian??

**Comment by computerfr33k** [comment]
replace the code block here: https://github.com/LaraDock/laradock/blob/master/php-fpm/Dockerfile-70#L38 with the code I wrote above.

**Comment by ialexca** [comment]
The fix worked for me, thx

**Comment by cviebrock** [comment]
Just wondering ... why you are even building PHP from source here, and not using packages like the _workspace_ container?
