### ISSUE TITLE
Feature Suggestion: Enabling the execution of node commands from the host with 'docker-compose exec'

### ISSUE THREAD

**Issue by Dryr** [laradock/laradock#1471]
### Info:
- Docker version 18.03.0-ce, build 0520e24
- Laradock commit: 8a090f3e46f4d04f9111952b5d12f2e2c80ff7b9 
- System info: Linux
- System info disto/version: Ubuntu 16.04

### Issue:
When trying to execute `npm` commands in the workspace container by using `docker-compose exec workspace npm ...`, you get the following error:

```
OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"npm\": executable file not found in $PATH": unknown
```

`WORKSPACE_INSTALL_NODE` is set to true, and I see the relevant output when building the workspace image.
For it to work, you _have_ to `docker-compose exec workspace bash` into the container beforehand.
You get the same behavior when trying to run any node module command (bower, gulp, etc).

After some probing around, I realized this issue came from the fact that the `docker-compose exec` command somehow uses the host's PATH environment variable instead of the container's.
After I manually added the path to the '/home/laradock/.nvm/versions/node/v9.11.1/bin' folder in the host's PATH, then things started working. However, using this solution feels a bit dirty.
_____

### Expected behavior:
You should see the output of the command running in the container. For example, you should see something like `5.6.0` when you run `docker-compose exec workspace npm -v`
_____

### Reproduce:
After a fresh install, run the containers with `docker-compose up -d nginx mysql`.
Then, try to get the 'npm' version with 'docker-compose exec workspace npm -v'.
_____

### Feature Suggestion:
To fix this, I added symbolic links in 'usr/local/bin' directly pointing to the node modules executables. I added the following code into the workspace Dockerfiles. I tested it on mac os X and Ubuntu 16.04

### Relevant Code:

```
# Make it so the node modules can be executed with 'docker-compose exec'
# We'll create symbolic links into '/usr/local/bin'.
RUN if [ ${INSTALL_NODE} = true ]; then \
    find $NVM_DIR -type f -name node -exec ln -s {} /usr/local/bin/node \; && \
    NODE_MODS_DIR="$NVM_DIR/versions/node/$(node -v)/lib/node_modules" && \
    ln -s $NODE_MODS_DIR/bower/bin/bower /usr/local/bin/bower && \
    ln -s $NODE_MODS_DIR/gulp/bin/gulp.js /usr/local/bin/gulp && \
    ln -s $NODE_MODS_DIR/npm/bin/npm-cli.js /usr/local/bin/npm && \
    ln -s $NODE_MODS_DIR/npm/bin/npx-cli.js /usr/local/bin/npx && \
    ln -s $NODE_MODS_DIR/vue-cli/bin/vue /usr/local/bin/vue && \
    ln -s $NODE_MODS_DIR/vue-cli/bin/vue-init /usr/local/bin/vue-init && \
    ln -s $NODE_MODS_DIR/vue-cli/bin/vue-list /usr/local/bin/vue-list \
;fi

```

**Comment by MatthiasHertel** [comment]
works like a charm should be merged!

**Comment by Dryr** [comment]
Thanks.

I'm in the process of creating a pull request. I'll get to it when I have some free time.

**Comment by sfox55** [comment]
+1 please merge this =)
