### ISSUE TITLE
mysql can not start

### ISSUE THREAD

**Issue by vinwang** [laradock/laradock#1475]
### Info:
- Docker version (`$ docker --version`): 18.03.0
- Laradock commit (`$ git rev-parse HEAD`): master
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.13.4

![image](https://user-images.githubusercontent.com/1687353/38534639-aeac5edc-3cb1-11e8-9c84-2b69ca784060.png)

**Comment by vinwang** [comment]
@oberoivarun 
![image](https://user-images.githubusercontent.com/1687353/38542057-73350df0-3cd3-11e8-800e-a311756ab9e2.png)

**Comment by oberoivarun** [comment]
Is this a blank database? Seems like there is something wrong with your data.

**Comment by vinwang** [comment]
Thanks,the problem has been solved.
I delete .laradock/data/mysql
