### ISSUE TITLE
Package 'php-soap' has no installation candidate

### ISSUE THREAD

**Issue by jourdon** [laradock/laradock#1476]
### Info:

Docker version: 18.03.0-ce-mac60 (23751)
Laradock commit: 0c41fce:
System info (Mac, PC, Linux): Mac
System info disto/version: 10.13.4
### Issue:
.env 

```
WORKSPACE_INSTALL_SOAP=true
PHP_FPM_INSTALL_SOAP=true
```
When I try to run the command `docker-compose build  workspace php-fpm` , I get this error

```
Step 5/70 : RUN if [ ${INSTALL_SOAP} = true ]; then     apt-get update -yqq &&     apt-get -y install libxml2-dev php-soap &&     docker-php-ext-install soap ;fi
 ---> Running in 69e28f1b8df4
Reading package lists...
Building dependency tree...
Reading state information...
Package php-soap is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-soap' has no installation candidate
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_SOAP} = true ]; then     apt-get update -yqq &&     apt-get -y install libxml2-dev php-soap &&     docker-php-ext-install soap ;fi' returned a non-zero code: 100
```

**Comment by Crazymodder** [comment]
Hi,

Simply add

`rm /etc/apt/preferences.d/no-debian-php && \`

before
`
    apt-get update -yqq && \
    apt-get -y install libxml2-dev php-soap && \
`

in php-fpm/Dockerfile

**Comment by jeliasson** [comment]
@jourdon?

**Comment by remipou** [comment]
Hello, thanks for the the fix. It's working when i build the php-fpm container but not for the workspace container..

**Comment by matohavo** [comment]
Rebuilding images without cache helped:
`docker-compose build --no-cache workspace php-fpm`
