### ISSUE TITLE
 Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by anviod** [laradock/laradock#1479]
### Info:
- Docker version (`$ docker --version`): Docker version 1.13.1, build 774336d/1.13.1
- Laradock commit (`$ git rev-parse HEAD`): 736627cbb7e37bbbf112d73a93b39fca30ac0f87
- System info (Mac, PC, Linux): Linux
- System info disto/version: centos 7.4 X86_64

### Issue:
[root@serv100 laradock]# docker-compose up -d nginx
Building php-fpm
Step 1/68 : ARG PHP_VERSION=${PHP_VERSION}
ERROR: Service 'php-fpm' failed to build: Please provide a source image with `from` prior to commit
_____

**Comment by UnknowCC** [comment]
delete the line “ARG PHP_VERSION=${PHP_VERSION}" before the "FROM image" line in the php-fmp/Dockfile and use actual version number replace the variable ${PHP_VERSION} in the "FROM .." line

**Comment by UnknowCC** [comment]
is there any script to modify this??

**Comment by anviod** [comment]
@UnknowCC 
I  just     Enter the laradock folder and rename env-example to .env.

# cp env-example .env
and  run
# docker-compose up -d nginx

**Comment by UnknowCC** [comment]
I do the same thing like you, and got the same error, the nginx image depend on php-fpm, so it build php-fpm first, if the Dockfile's syntax rule was wrong. then you get the php-fpm error. 
I think there may be some lack step in the document

**Comment by anviod** [comment]
@UnknowCC  you can do this . 
### # yum remove docker docker-common -y 
### # yum install -y docker-engine
### # systemctl enbale docker && systemctl start docker
### docker-compose up -d nginx
---
now 
docker --version
Docker version 18.04.0-ce, build 3d479c0

uname -a
Linux bj141-143-178.bjtelecom.net 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
