### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by marast78** [laradock/laradock#1480]
### Info:
- Docker version Docker version 18.03.0-ce, build 0520e24: 
- Laradock commit 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a: 
- System info Linux: 
- System info Ubuntu 16.04: 

### Issue:

`docker-compose ps`

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**When I've replaced version 3 with 2 it started to work.**

**Comment by guicara** [comment]
Hello,

I have the same issue with a fresh install of Laradock.
OS: Linux Mint 18.3 Sylvia.

Docker version: 18.03.0-ce, build 0520e24
Docker compose version: 1.8.0

Thanks,

**Comment by neorganic** [comment]
Any news with this?

**Comment by nicholascm90** [comment]
@neorganic just make sure you are running a recent version of docker-compose...updating fixed for me. using v 1.18.0
