### ISSUE TITLE
Issue while building workspace

### ISSUE THREAD

**Issue by grafikkaos** [laradock/laradock#1482]
### Info:
- Docker version: 18.03.0-ce, build 0520e24: 
- Laradock commit:  0c41fce: 
- System info : PC: 
- System info disto/version: Windows 10 x64

### Issue:
While building workspace, I am getting an error installing libway client

_____

### Expected behavior:
Building of workspace should be not be failing.
_____

### Reproduce:
In the .env file, enable the installation of laravel dusk packages.
_____

### Relevant Code:

```
WORKSPACE_INSTALL_DUSK_DEPS=true
```

**Comment by Dryr** [comment]
You can fix it by adding `apt-get install` in the DUSK section of the workspace's Dockerfile

```
RUN if [ ${INSTALL_DUSK_DEPS} = true ]; then \
  apt-get update \
  && apt-get -y install zip wget unzip xdg-utils \
    libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4 xvfb \
    gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi \
    xfonts-base xfonts-scalable x11-apps \
  && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i --force-depends google-chrome-stable_current_amd64.deb \
  && apt-get -y -f install \
  && dpkg -i --force-depends google-chrome-stable_current_amd64.deb \
  && rm google-chrome-stable_current_amd64.deb \
  && wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip \
  && unzip chromedriver_linux64.zip \
  && mv chromedriver /usr/local/bin/ \
  && rm chromedriver_linux64.zip \
;fi
```

**Comment by johnreitano** [comment]
I had this same problem and "apt-get update -y" fixed the problem. Can someone update the repo with this fix? Thanks!
