### ISSUE TITLE
Cant serve index.php - 404 not found

### ISSUE THREAD

**Issue by charsi** [laradock/laradock#1484]
### Info:
- Docker version (`$ docker --version`):  17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`):  0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux):  Linux
- System info disto/version: Linux Mint - 4.10.0-38-generic #42~16.04.1-Ubuntu 

### Issue:
404 not found error when going to http://localhost/ after following the getting started guide
_____

### Expected behavior:
Be able to see my index.html or index.php file that I created in the project folder
_____

### Reproduce:
- Follow getting started guide
- docker-compose up -d nginx mysql workspace
- create a index.html file in the project folder
Try going to http://localhost/
_____

### Relevant Code:

I bashed into workspace and nginx and both containers can see the index.html file at /var/www/

I know this question is pretty basic. But if following the getting started guide doesn't get a user up and running maybe something needs to be changed.

EDIT: I moved a laravel app to the folder and it does work as expected! If somebody can explain what I am missing I'd greatly appreciate it.

**Comment by ogronau** [comment]
nginx' webroot is configured to be `/var/www/public`, which maps to `../public`, relative to laradock's root. A Laravel installation in the parent directory would have this directory, but your basic test fails. Had the same issue just recently ;-)
