### ISSUE TITLE
Noticeably slower than running without docker

### ISSUE THREAD

**Issue by beedubsss** [LaraDock/laradock#149]
I've setup 2 VM's on azure with the same specs after noticing a real that deploying my laravel project through this docker setup has slowed the response time down. For a request that would take 1.6secs when not running in docker, it has increased to 2.6secs inside docker. 

Has anyone else experienced any similar issues when using this docker image?

**Comment by rscotten** [comment]
Yep.  I believe Xdebug is slowing it everything down.  I dropped the load time about 0.5 seconds after adding these lines to the bottom of this project's `/php-fpm/laravel.ini` file:

```bash
; Disable xdebug
xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.profiler_enable=0
```

Or you can just comment out the Xdebug code in `\php-fpm\Dockerfile-70`
