### ISSUE TITLE
Unable to install nginx

### ISSUE THREAD

**Issue by JohnnyLeWebDeveloper** [laradock/laradock#1490]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.0-ce, build 0520e24- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a- System info (Mac, PC, Linux): Mac
- System info disto/version: High Sierra

### Issue:
Unable to install nginx within laradock.

Starting laradock_nginx_1 ... error

ERROR: for laradock_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (b7f62984dcaa2038d16300f705bebee3f56f82d6b80835fb51389c37562d2551): Error starting userland proxy: Bind for 0.0.0.0:443: unexpected error (Failure EADDRINUSE)

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (b7f62984dcaa2038d16300f705bebee3f56f82d6b80835fb51389c37562d2551): Error starting userland proxy: Bind for 0.0.0.0:443: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project._____

### Expected behavior:
Being able to access localhost
_____

### Reproduce:
Docker command works for everything but nginx via this ->
docker-compose up -d nginx mysql phpmyadmin redis workspace
_____

**Comment by lbsfei** [comment]
Me too.
Logs as below:
Step 6/11 : RUN apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data
 ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
 ---> Running in f0135f51d3a8
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
2 errors; 28 distinct packages available
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data' returned a non-zero code: 2
Why ?
please help me!
thanks!

**Comment by matthijs-neijenhuijs** [comment]
me too!

**Comment by limhu** [comment]
@lbsfei @matthijs-neijenhuijs

I solved this issues  with changed the apk mirror. (nginx/Dockerfile)

1. `cd laradock && vim nginx/Dockerfile`
![image](https://user-images.githubusercontent.com/17063861/40308561-35e347e2-5d39-11e8-8c51-f4ed1604a3e4.png)

2. `docker-compose build --no-cache nginx`

**Comment by akanbitoluwase** [comment]
Anyone able to resolve this particular issue. I'm having something similar
