### ISSUE TITLE
MySQL Container fails to start

### ISSUE THREAD

**Issue by SirNeural** [laradock/laradock#1492]
### Info:
- Docker version (`$ docker --version`): Docker version 18.04.0-ce, build 3d479c0
- Laradock commit (`$ git rev-parse HEAD`): 871a9d032a5ef36155d444c75fb47e0fc187fae6
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 17.10 x64

### Issue:

MySQL container does not start up when running docker-compose up mysql,
I've tried a few different releases, 6.0.0, 6.0.1, and the 7.0.0 release and I get the same error every time.

### Expected behavior:

MySQL container should start when given the command

### Reproduce:

git checkout v6.0.0
docker-compose up mysql

### Relevant Code:
Error report here
```
# docker-compose up mysql
WARNING: The APACHE_DOCUMENT_ROOT variable is not set. Defaulting to a blank string.
Starting laradock_mysql_1
Attaching to laradock_mysql_1
mysql_1                |
mysql_1                | ERROR: mysqld failed while attempting to check config
mysql_1                | command was: "mysqld --verbose --help"
mysql_1                |
mysql_1                | 2018-04-20T23:56:30.162694Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
mysql_1                | 2018-04-20T23:56:30.162798Z 0 [ERROR] [MY-011071] [Server] /usr/sbin/mysqld: Error while setting value 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' to 'sql_mode'
mysql_1                | 2018-04-20T23:56:30.165911Z 0 [ERROR] [MY-010119] [Server] Aborting
laradock_mysql_1 exited with code 1
```

**Comment by dayvsonsales** [comment]
same error here

**Comment by andrzejkupczyk** [comment]
Same problem:
- Docker version: 18.03.0-ce, build 0520e24
- Laradock commit: 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info: Ubuntu 18.04 (dev)

**Comment by naughtyjoint** [comment]
I had the same issue last night, I think it's the mysql version problem. What I did was 

- edited laradock/.env,  set MYSQL_VERSION from latest to 5.7

- deleted ~/.laradock/mysql/ directory completely (Warning, This may delete your data ! )

- then re-build `docker-compose build mysql`

- `docker-compose up -d mysql` as usual

Hope this helps :)

**Comment by zlanich** [comment]
@naughtyjoint's answer also fixed mine.

**Comment by carloshperes** [comment]
Thanks @naughtyjoint

**Comment by ccennis** [comment]
i also had to remove the sql_mode line from the my.cnf but then deleting the dir and rebuilding helped. thanks!!

**Comment by linganmin** [comment]
@naughtyjoint Thanks

**Comment by yabasha** [comment]
thanx @naughtyjoint I struggled with mysql container issue for one whole night your answer solved my issue.

**Comment by realhome** [comment]
🤣
MySQL 8.0.11 remove the ’NO_AUTO_CREATE_USER‘ from sql-mode.
/mysql/my.cnf [mysqld]
STRICT_TRANS_TABLES STRICT_TRANS_TABLES cannot be existing at the same time.
> MySQL 5.7: Using GRANT to create users. Instead, use CREATE USER. Following this practice makes the NO_AUTO_CREATE_USER SQL mode immaterial for GRANT statements, so it too is deprecated.
MySQL 8.0.11: Using GRANT to create users. Instead, use CREATE USER. Following this practice makes the NO_AUTO_CREATE_USER SQL mode immaterial for GRANT statements, so it too is removed.

**Comment by pack254** [comment]
@naughtyjoint Thank a lot for your answer is solved my life, have been straggled to solve this problem for whole day.

Cheers

**Comment by Totoross** [comment]
Excuse me, How to set up the password for Redis

**Comment by fernandoajn** [comment]
Thanks @naughtyjoint, that still works!

**Comment by hassanazimi** [comment]
in my case, in `/etc/mysql/my.cnf` file at the very end of the file, you need to add:

```
collation-server = utf8_unicode_ci
```

just under 

```
character-set-server = utf8
```
