### ISSUE TITLE
WORKSPACE_INSTALL_DUSK_DEPS causes 'docker-compose build workspace' to fail

### ISSUE THREAD

**Issue by Dryr** [laradock/laradock#1497]
### Info:
- Docker version 18.03.0-ce, build 0520e24
- Laradock commit 0c41fce
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04

### Issue:
When `WORKSPACE_INSTALL_DUSK_DEPS` is set to true in the '.env' file, the build will fail with the following error:

> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/wayland/libwayland-server0_1.12.0-1~ubuntu16.04.2_amd64.deb 404 Not Found [IP: 91.189.88.162 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Due to this, the travis-ci check for the pull requests will automatically fail.

_____

### Expected behavior:
The build completes without any issue 
_____

### Reproduce:
Set `WORKSPACE_INSTALL_DUSK_DEPS` to true in laradock's '.env' file and run `docker-compose build workspace`
_____

### Relevant Code:

In the workspace's Dockerfile:

```
RUN if [ ${INSTALL_DUSK_DEPS} = true ]; then \
  apt-get -y install zip wget unzip xdg-utils \
    libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4 xvfb \
    gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi \
    xfonts-base xfonts-scalable x11-apps \
  && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i --force-depends google-chrome-stable_current_amd64.deb \
  && apt-get -y -f install \
  && dpkg -i --force-depends google-chrome-stable_current_amd64.deb \
  && rm google-chrome-stable_current_amd64.deb \
  && wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip \
  && unzip chromedriver_linux64.zip \
  && mv chromedriver /usr/local/bin/ \
  && rm chromedriver_linux64.zip \
;fi
```

### Fix suggestion:

Adding `apt-get update` in the DUSK section of the Dockerfile.

```
RUN if [ ${INSTALL_DUSK_DEPS} = true ]; then \
  apt-get update \
  && apt-get -y install zip wget unzip xdg-utils \
    libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4 xvfb \
    gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi \
    xfonts-base xfonts-scalable x11-apps \
  && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i --force-depends google-chrome-stable_current_amd64.deb \
  && apt-get -y -f install \
  && dpkg -i --force-depends google-chrome-stable_current_amd64.deb \
  && rm google-chrome-stable_current_amd64.deb \
  && wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip \
  && unzip chromedriver_linux64.zip \
  && mv chromedriver /usr/local/bin/ \
  && rm chromedriver_linux64.zip \
;fi
```

I managed to build the workspace image with that.

**Comment by danieldevsquad** [comment]
Your fix suggestion works for me!

**Comment by evianoa** [comment]
Your suggestion worked for me too. Many thanks.

**Comment by ravencole** [comment]
Just worked for me as well
