### ISSUE TITLE
Help wanted: problem when trying to run nginx container

### ISSUE THREAD

**Issue by paddyurlich** [LaraDock/laradock#150]
After clone the laradock repository and running: docker-compose up -d  nginx 
I receive the following error.  I would appreciate if someone could please help me with this.

Note the mysql container runs without any issues. 
  
php-memcached-php7/tests/testdata.res
php-memcached-php7/tests/touch_binary.phpt
php-memcached-php7/tests/types.inc
php-memcached-php7/tests/types_igbinary.phpt
php-memcached-php7/tests/types_igbinary_multi.phpt
php-memcached-php7/tests/types_json.phpt
php-memcached-php7/tests/types_json_multi.phpt
php-memcached-php7/tests/types_msgpack.phpt
php-memcached-php7/tests/types_msgpack_multi.phpt
php-memcached-php7/tests/types_php.phpt
php-memcached-php7/tests/types_php_multi.phpt
php-memcached-php7/tests/undefined_set.phpt
php-memcached-php7/tests/user-flags.phpt
php-memcached-php7/tests/vbucket.phpt
php-memcached-php7/tests/version.phpt
←[91musage: /usr/local/bin/docker-php-ext-configure ext-name [configure flags]
   ie: /usr/local/bin/docker-php-ext-configure gd --with-jpeg-dir=/usr/local/something
←[0m←[91m
Possible values for ext-name:
←[0mbcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mcrypt mysqli oci8 odbc opcache pcntl p
do pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets spl standard
sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip
←[31mERROR←[0m: Service 'php-fpm' failed to build: The command '/bin/sh -c curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz"
     && mkdir -p /usr/src/php/ext/memcached     && tar -C /usr/src/php/ext/memcached -zxvf /tmp/memcached.tar.gz --strip 1     && docker-php-ext-configure memcached     && docker-p
hp-ext-install memcached     && rm /tmp/memcached.tar.gz' returned a non-zero code: 1

**Comment by rscotten** [comment]
Answer is posted by @computerfr33k here: https://github.com/LaraDock/laradock/issues/147

**Comment by paddyurlich** [comment]
thanks Richard !!
