### ISSUE TITLE
How to  forwarding port in laradock?

### ISSUE THREAD

**Issue by silsuer** [laradock/laradock#1500]
### Info:
- Docker version (`$ docker --version`): 17.09.1-ce, build 19e2cf6
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  PC
- System info disto/version: Windows10 x64

### Issue:

I installed the swoole, and I want use the nginx to forward port to the swoole http server;

I write the nginx config file like this:

    ``
      server {
          root /var/www/aaa;
          server_name aaa.test;
          index index.php

          location / {
              proxy_http_version 1.1;
              proxy_set_header Connection "keep-alive";
              proxy_set_header X-Real-IP $remote_addr;
              if (!-e $request_filename) {
                  proxy_pass http://127.0.0.1:9501;
               }
          }
      }
    ```

_____

### Expected behavior:

    when I restart the nginx : `docker-compose restart nginx` ,

    and `docker-compose ps`

    I see the nginx status :  ` Exit 1 `
_____

Help!

**Comment by merodiro** [comment]
did you find a solution? I have the same problem also
