### ISSUE TITLE
APP_CODE_PATH_HOST is not populating workspace.

### ISSUE THREAD

**Issue by spaceSquid** [laradock/laradock#1503]
### Info:
- Docker version (`$ docker --version`): 18.03.0-ce
- Laradock commit (`$ git rev-parse HEAD`): a6ed9e3b4e78f8a12c1f32f8841ce018957ce8aa
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 Pro

### Issue:
APP_CODE_PATH_HOST is not populating workspace.
_____

**Comment by sinden** [comment]
```
workspace_1            | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
workspace_1            | *** Running /etc/my_init.d/10_syslog-ng.init...
workspace_1            | Apr 24 08:40:08 bf76a3954b5e syslog-ng[9]: syslog-ng starting up; version='3.5.6'
workspace_1            | Apr 24 08:40:08 bf76a3954b5e syslog-ng[9]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
workspace_1            | *** Running /etc/rc.local...
```

**Comment by gl3nda85** [comment]
having the same issue

**Comment by bcdennis** [comment]
Add the entry APPLICATION=
and it will work.

**Comment by bradmccormack** [comment]
Same here.

$ docker --version
Docker version 18.03.1-ce, build 9ee9f40

**Comment by bradmccormack** [comment]
For me this was due to the APP_CODE_PATH_HOST having a relative path to the docker-compose file. After I updated it to use an absolute path, no more problems.

**Comment by mattogodoy** [comment]
Same here!
Docker version 18.06.0-ce, build 0ffa825

I tried using absolute paths and no luck either.
Did you solve it, @sinden ?

**Comment by kneipp** [comment]
After wasting my time in the last two days, i have found a solution:

In .env file set this PATH: 
APP_CODE_PATH_HOST=/d/your-workspace-path/your-project

** 
Running Windows 10 18.03?
Create and modify the new WSL configuration file:

vim nano /etc/wsl.conf

# Now make it look like this and save the file when you're done:
[automount]
root = /
options = "metadata"
**

Restart your computer and profit! 

** Credit: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

**Comment by Ablegang** [comment]
I have a both question.
