### ISSUE TITLE
not work when PHP_VERION = 7.2

### ISSUE THREAD

**Issue by lightWey** [laradock/laradock#1511]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux): Mac
- System info disto/version: High Sierra 10.13.4

### Issue:

When I change the `PHP_VERSION` to 7.2 in `.env` file , and  run `docker-compose build php-fpm`,the build will fail with the following error
```
E: Unable to locate package jpegoptim
E: Unable to locate package pngquant
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGE_OPTIMIZERS} = true ]; then     apt-get install -y --force-yes jpegoptim optipng pngquant gifsicle ;fi' returned a non-zero code: 100
```

### Expected behavior:

_____
### Reproduce:

```
docker-compose build php-fpm
```
_____
### Relevant Code:

```
// place a code sample here
```

**Comment by brunen9** [comment]
Look at #1476
