### ISSUE TITLE
Laradock doesn't generate workspace

### ISSUE THREAD

**Issue by shane-scalable** [laradock/laradock#1513]
### Info:
- Docker version (`Docker version 18.03.1-ce, build 9ee9f40`): 
- Laradock commit (`0c41fceae1b23089f5360dc4f8aeb85719c7bf5a`): 
- System info (Mac): 
- System info disto/version: 
El Capitan - 10.11.6
### Issue:

Laradock isn't creating workspace

### Expected behavior:

Workspace should be automatically created according to every other example I see online and in laradock docs.

### Reproduce:

clone fresh laradock on master as of now and run `docker-compose up -d nginx postgres redis` (with or without the -d)

### Relevant Code:
The only changes I have made other than enabling postgres inside of the laradoc/.env file are to add some user aliases so the psql driver can connect 
```
$ git diff
diff --git a/workspace/Dockerfile b/workspace/Dockerfile
index 6637419..1edcf6f 100644
--- a/workspace/Dockerfile
+++ b/workspace/Dockerfile
@@ -89,7 +89,9 @@ USER laradock
 RUN echo "" >> ~/.bashrc && \
     echo "# Load Custom Aliases" >> ~/.bashrc && \
     echo "source ~/aliases.sh" >> ~/.bashrc && \
-       echo "" >> ~/.bashrc
+       echo "" >> ~/.bashrc && \
+    sed -i 's/\r//' /home/laradock/aliases.sh && \
+    sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
```
What I run and see:
```
// place a code sample here
```
$ docker-compose up -d nginx postgres redis
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "laradock_frontend" with driver "bridge"
Creating network "laradock_backend" with driver "bridge"
Creating network "laradock_default" with the default driver
Creating laradock_redis_1    ... done
Creating laradock_php-fpm_1  ... done
Creating laradock_postgres_1 ... done
Creating laradock_nginx_1    ... done
```
^ Here it never creates any *workspace
```
shanes-MacBook-Pro:laradock shanemitchell$ docker-compose ps
       Name                      Command               State                    Ports                  
-------------------------------------------------------------------------------------------------------
laradock_nginx_1      nginx                            Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
laradock_php-fpm_1    docker-php-entrypoint php-fpm    Up      9000/tcp                                
laradock_postgres_1   docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp                  
laradock_redis_1      docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp                  
shanes-MacBook-Pro:laradock shanemitchell$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                   PORTS                                      NAMES
e57cf4e6deb6        laradock_nginx      "nginx"                  39 seconds ago      Up 40 seconds            0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   laradock_nginx_1
f46d5db9b478        laradock_php-fpm    "docker-php-entrypoi…"   40 seconds ago      Up 41 seconds            9000/tcp                                   laradock_php-fpm_1
f0ce40ed7a24        laradock_postgres   "docker-entrypoint.s…"   40 seconds ago      Up 40 seconds            0.0.0.0:5432->5432/tcp                     laradock_postgres_1
569a82d7ea60        laradock_redis      "docker-entrypoint.s…"   40 seconds ago      Up 40 seconds            0.0.0.0:6379->6379/tcp                     laradock_redis_1
```

**Comment by Dryr** [comment]
Does it work if you specify 'workspace' in the docker-compose command?

`docker-compose up -d workspace`

If it does not works, Rerun the command without the '-d' option to see the output of the command.

**Comment by toaomatis** [comment]
I ran into the same issue this morning. 

Using the `docker-compose up -d workspace` works.

**Comment by shane-scalable** [comment]
The documentation should be updated to show this as it literally says to run `docker-compose up redis nginx` then enter the workspace by running `docker-compose exec workspace bash`.
