### ISSUE TITLE
ERROR: for laradock_php-fpm_1

### ISSUE THREAD

**Issue by fauzipadlaw** [laradock/laradock#1515]
### Info:
- Docker version (`$ docker --version`): Docker version 18.04.0-ce, build 3d479c0af6
- Laradock commit (`$ git rev-parse HEAD`): a0c5ef75d2cc3462af537cb3a385ccb728e585c3
- System info (Mac, PC, Linux): Linux
- System info disto/version: 4.16.5-1-ARCH

### Issue:

```ERROR: for laradock_php-fpm_1```

### Reproduce:

```Creating laradock_php-fpm_1 ... error

ERROR: for laradock_php-fpm_1  Cannot create container for service php-fpm: invalid volume specification: '.:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute

ERROR: for php-fpm  Cannot create container for service php-fpm: invalid volume specification: '.:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
ERROR: Encountered errors while bringing up the project.

**Comment by Dryr** [comment]
What's the value of APP_CODE_PATH_HOST in your '.env' file?

**Comment by fauzipadlaw** [comment]
Im sorry my bad. I just upgrade to v7.0.0 and forgot to change my .env
