### ISSUE TITLE
Quick overview - 404 Not Found nginx - Shall I expect something different?

### ISSUE THREAD

**Issue by tomekit** [laradock/laradock#1516]
Hi,
I've followed the instructions from the documentation:

```
git clone https://github.com/Laradock/laradock.git
cp env-example .env
docker-compose up -d nginx mysql phpmyadmin redis workspace 

## Open your project’s .env file and set the following:
DB_HOST=mysql
REDIS_HOST=redis
QUEUE_HOST=beanstalkd

# Open your browser and visit localhost: http://localhost.
# That's it! enjoy :)

```

I got: `404 Not Found nginx`.

Should I enjoy it? :)
Was it just showing off example commands or should I see some `demo` / `example` project? Thanks

**Comment by Dryr** [comment]
Yeah, there's actually a bit more to it. The instructions assume that you are cloning laradock inside your Laravel project.

It's better if you change the value of APP_CODE_PATH_HOST in laradock's .env file, point it to your laravel's project folder.
If you are not using laravel, point it to a directory containing a folder named 'public'. Then put your web files in that folder.

**Comment by nmihaica** [comment]
thanks @Dryr.
