### ISSUE TITLE
MacOS Xdebug with phpStorm

### ISSUE THREAD

**Issue by dontinhqt** [laradock/laradock#1518]
### Issue:
I have tried to follow step docs and research related issues, but all is not workable
- Config php-fpm
![screen shot 2018-05-02 at 4 00 52 pm](https://user-images.githubusercontent.com/8046469/39517689-c564ac8a-4e2a-11e8-9eb6-66b1dfcac897.png)
- domain virtualhost
![screen shot 2018-05-02 at 5 04 16 pm](https://user-images.githubusercontent.com/8046469/39517761-06c9f428-4e2b-11e8-93e9-d9d5842f2d22.png)
- config in phpstorm
![screen shot 2018-05-02 at 4 01 11 pm](https://user-images.githubusercontent.com/8046469/39517787-1ac43560-4e2b-11e8-9b68-6fb66d5d1d0b.png)
![screen shot 2018-05-02 at 4 01 23 pm](https://user-images.githubusercontent.com/8046469/39517788-1afbb828-4e2b-11e8-80b3-b9329d629b51.png)
![screen shot 2018-05-02 at 4 01 33 pm](https://user-images.githubusercontent.com/8046469/39517789-1b2fcac8-4e2b-11e8-85d1-adea541982b5.png)
![screen shot 2018-05-02 at 4 01 57 pm](https://user-images.githubusercontent.com/8046469/39517790-1b717f7c-4e2b-11e8-96e4-bd638065389e.png)
![screen shot 2018-05-02 at 4 14 45 pm](https://user-images.githubusercontent.com/8046469/39517799-24fb15f8-4e2b-11e8-9c0a-5dc8578c9e03.png)
But as a result, it still does not work
So please help me pinpoint the cause, thank you

**Comment by manjurulcis** [comment]
Facing same problem. Anyone knows what wrong here?

**Comment by liangshuocj** [comment]
Can you solve this problem?

**Comment by dontinhqt** [comment]
@liangshuocj Sorry, I have not solved it yet

**Comment by ASK-Lee** [comment]
same to me

**Comment by dolpox** [comment]
This fixed mine.
`xdebug.remote_host=host.docker.internal`
