### ISSUE TITLE
How to install and apply SSL certificate?

### ISSUE THREAD

**Issue by thusfar7** [LaraDock/laradock#152]
How can I apply a SSL certificate to Laradock Nginx website?

Regards

**Comment by iannazzi** [comment]
Same issue here, need ssl

**Comment by computerfr33k** [comment]
If you don't need to use nginx, I added caddy server which would allow you to easily enable SSL by commenting out the tls option in the Caddyfile.

**Comment by iannazzi** [comment]
no need for nginx, so caddy looks perfect! (never heard of caddy so thanks for that!)

**Comment by midascodebreaker** [comment]
how about if you need nginx , how can you do it also with caddy side by side?

**Comment by vanderson139** [comment]
To enable self-signed certificates, edit the nginx Dockerfile:

1 - install openssl within "RUN apk update":
```bash
&& apk add --no-cache bash \
&& apk add --no-cache openssl \
&& adduser -D -H -u 1000 -s /bin/bash www-data \
```

2 - generate the keys for your local domain:
```bash
RUN mkdir /etc/nginx/ssl 2> /dev/null

RUN openssl genrsa -out "/etc/nginx/ssl/YOURLOCALDOMAIN.key" 2048 \
    && openssl req -new -key "/etc/nginx/ssl/YOURLOCALDOMAIN.key" -out "/etc/nginx/ssl/YOURLOCALDOMAIN.csr" -subj "/CN=YOURLOCALDOMAIN/O=YOURCOMPANYNAME/C=UK" \
    && openssl x509 -req -days 365 -in "/etc/nginx/ssl/YOURLOCALDOMAIN.csr" -signkey "/etc/nginx/ssl/YOURLOCALDOMAIN.key" -out "/etc/nginx/ssl/YOURLOCALDOMAIN.crt"
```

3 - update your site.conf file:

```conf
listen 80;
listen 443 ssl;
listen [::]:80;

ssl_certificate     /etc/nginx/ssl/YOURLOCALDOMAIN.local.crt;
ssl_certificate_key /etc/nginx/ssl/YOURLOCALDOMAIN.local.key;
```

**Comment by sid606** [comment]
I know is a stupid question but what is should I put for YOURLOCALDOMAIN and what if I have multiple sites?

Thanks

**Comment by cre8** [comment]
@sid606 you can put anything there. it's like a name for a ssl-certificate so you know to which domain the certificate belongs to.

**Comment by canhkieu** [comment]
I tried but not working. No file in /etc/nginx.... after run
Doccker-compose Build nginx
Docker-compose Up nginx

**Comment by swim89** [comment]
I have the same error message. Could you please help us?

**Comment by guicara** [comment]
Hello,

A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image. If you set up Laradock for multiple projects, I don't think it is a good practice to create the self-signed certificates for each sites in the nginx Dockerfile.

In my opinion you just need to add the first two lines of @vanderson139 in the Dockerfile :
```
# install openssl
RUN apk add --no-cache openssl

# create a folder for the keys
RUN mkdir /etc/nginx/ssl 2> /dev/null
```
```
cd laradock
docker-compose build nginx
```

Now, if you want to add a self signed certificate for one of your website:

```
docker-compose exec nginx bash
openssl genrsa -out "/etc/nginx/ssl/YOURLOCALDOMAIN.key" 2048 \
    && openssl req -new -key "/etc/nginx/ssl/YOURLOCALDOMAIN.key" -out "/etc/nginx/ssl/YOURLOCALDOMAIN.csr" -subj "/CN=YOURLOCALDOMAIN/O=YOURCOMPANYNAME/C=UK" \
    && openssl x509 -req -days 365 -in "/etc/nginx/ssl/YOURLOCALDOMAIN.csr" -signkey "/etc/nginx/ssl/YOURLOCALDOMAIN.key" -out "/etc/nginx/ssl/YOURLOCALDOMAIN.crt"
```
_(repeat this process for each site)_

Then update your virtual host file to load the certificate and the key.

**Comment by qingdi** [comment]
ssl_certificate     /etc/nginx/ssl/YOURLOCALDOMAIN.crt;
ssl_certificate_key /etc/nginx/ssl/YOURLOCALDOMAIN.key;

no "local"

**Comment by bobbysiagian** [comment]
@vanderson139 thanks, it still works!

**Comment by gutitrombotto** [comment]
@vanderson139 i have done this process but chrome browser still don't given access to the secure url. Should i add some cert?
