### ISSUE TITLE
Workspace not showing host files

### ISSUE THREAD

**Issue by emperorjm** [laradock/laradock#1525]
Docker version: Docker version 18.03.1-ce Stable 93354b3
Laradock commit: https://github.com/laradock/laradock/commit/0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
System info: Windows 10

I have been running my Laravel application on Laradock for over 4 months now but after upgrading to the latest version of Docker as well the lastest version of Laradock the workspace is not loading my files but instead showing a "laradock" and my website folder with nginx, log, apache2, php-fpm folders:

PS C:\website\laradock> docker-compose
Recreating laradock_php-fpm_1   ... don
Recreating laradock_workspace_1 ... don
Recreating laradock_nginx_1     ... don
PS C:\website\laradock> docker-compose
root@97ad54551288:/var/www# ls
laradock  website
root@97ad54551288:/var/www# cd laradock
root@97ad54551288:/var/www/laradock# ls
apache2  logs  nginx  php-fpm
root@97ad54551288:/var/www/laradock#

**Comment by Dryr** [comment]
Some of the environment variables defined in the '.env' file have changed names.

For example `APPLICATION` is now `APP_CODE_PATH_HOST`

The only way to find out which ones have changed is to compare your '.env' file with the last version of the 'env-example' file.

**Comment by emperorjm** [comment]
I downloaded the latest version of Laradock and I still had the same problem. I had to downgrade docker to the previous version and it now works. Laradock is not working with the latest version of Docker.

**Comment by oozone** [comment]
This is a real issue, latest laradock doesn't work

**Comment by AndalusiaDev** [comment]
I have the same issue.
Is there any news about it?

**Comment by AndalusiaDev** [comment]
I solved this problem by:

1. Disabling the firewall (in my case is necessary) or setting a rule
1. going to "Shared drives" in docker settings 
1. disabling then enabling the sharing again (C and E in my case) 
1. Enabling the firwall again

**Comment by zch513430014** [comment]
The same problem happened!
I changed Windows user password recently!
Then there are not files at /var/www 
I try to restart workspace. or rebuild workspace but still not working!
Then I going to Shared Drives and 'Reset credentials...'
And reauthorized (E: D:)
It's working!!!

**Comment by qnox81** [comment]
I had situation exacly like @zch513430014.

no files in workspace, rebuild and restarts doesnt worked. 

FIX: Shared Drives, reset credentials, reauthorize drives and its working
