### ISSUE TITLE
Installation and use of windows 10

### ISSUE THREAD

**Issue by zongmi** [laradock/laradock#1526]
- Windows Version: 1803 (OS Build 17134.1)
- Docker for Windows Version: 18.04.0-ce-win62 (build 3d479c0)

`> docker-compose up -d nginx mysql redis`

> Creating network "laradock_frontend" with driver "bridge"
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found

`>  docker network ls`

> NETWORK ID          NAME                DRIVER              SCOPE
cd23685dc007        nat                 nat                 local
32e395bbfdbe        none                null                local
ccc02ba9a9ed        test_default        nat                 local
a4639042fcea        默认交换机               ics                 local

`>  docker network create my_net`

> Error response from daemon: could not find plugin bridge in v1 plugin registry: plugin not found

`>  docker plugin ls`

>Error response from daemon: plugins are not supported on this platform

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking
![image](https://user-images.githubusercontent.com/18360503/39672756-003ac11a-5163-11e8-9ead-16b4cce96e95.png)

**Comment by zongmi** [comment]
Oh, yes, edit the.Env file NETWORKS_DRIVER=*.

**Comment by thavoo** [comment]
ERROR: could not find plugin * in v1 plugin registry: plugin not found @zongmi

**Comment by thavoo** [comment]
I solve modified file .env change NETWORKS_DRIVER=*. to NETWORKS_DRIVER=nat
