### ISSUE TITLE
Fail to build php-fpm image

### ISSUE THREAD

**Issue by fresnizky** [LaraDock/laradock#153]
Got the following error when trying to build php-fpm image on Docker for Windows:
Service 'php-fpm' failed to build: The command '/bin/sh -c curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz"     && mkdir -p /usr/src/phar.gz --strip 1     && docker-php-ext-configure memcached     && docker-php-ext-install memcached     && rm /tmp/memcached.tar.gz' returned a non-zero code: 1

**Comment by Kauhat** [comment]
Hi @fresnizky, see #147 for fixes.
