### ISSUE TITLE
Run composer as non root

### ISSUE THREAD

**Issue by jasperf** [laradock/laradock#1532]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux):  Linux
- System info disto/version: Ubuntu 16.0.4

### Issue:
Guide http://laradock.io/guides/#Digital-Ocean tells to run composer as root in workspace. That is discouraged
_____

### Expected behavior:
Should be a non root user that can work on this. Also the entire laravel setup following the guide is run under root. That is going to cause rights and permissions issues
_____

### Reproduce:
Follow the Digital Ocean production setup guide. Use Docker image at Digital Ocean. Do a `docker-compose up -d nginx mariadb workspace`. Let it all be installed Go into workspace using `docker-compose exec workspace bash`. Then go to /var/www/ and see that the guide tells you to run composer install as ROOT.

Do think the non root user laradock should be used instead no? But when I do run the composer install as laradock I get this
```
laradock@884cb7ea9243:/var/www$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 70 installs, 0 updates, 0 removals

                                                            
  [RuntimeException]                                        
  /var/www/vendor does not exist and could not be created.  
                                                            

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

laradock@884cb7ea9243:/var/www$ ll
total 108
drwxrwxr-x 13 1001 1001 4096 May  7 12:55 ./
drwxr-xr-x  1 root root 4096 May  7 13:04 ../
drwxrwxr-x  6 1001 1001 4096 May  7 12:55 app/
.......
```

**Comment by jasperf** [comment]
When I did a
```
root@e3ac39ce4546:/var# chown -R laradock:laradock www/
root@e3ac39ce4546:/var# su laradock
laradock@e3ac39ce4546:/var$ cd www/
laradock@e3ac39ce4546:/var/www$ ll
..
```
I was able to run composer as laradock:
```
composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 70 installs, 0 updates, 0 removals
  - Installing vlucas/phpdotenv (v2.4.0): Downloading (100%)         
  - Installing symfony/css-selector (v4.0.9): Downloading (100%) 
...
```
Still, would love to hear if this is better practice this way. Or if there are other, better and or easier ways.

**Comment by Dryr** [comment]
That is strange, normally the '/var/www' folder should already be owned by the 'laradock' user.

I saw that the id of the owner of the folder is '1001'
```
laradock@884cb7ea9243:/var/www$ ll
total 108
drwxrwxr-x 13 1001 1001 4096 May  7 12:55 ./
```
I guess that's the user of your host machine.
Try to set the `WORKSPACE_PUID` and `WORKSPACE_PGID` to 1001 in laradock's '.env' file

**Comment by jasperf** [comment]
> That is strange, normally the '/var/www' folder should already be owned by the 'laradock' user.

well when I follow the guide and install as root, then get into the workspace it shows all files owned by root @Dryr 
```
docker-compose exec workspace bash
root@b2ab9230ab52:/var/www# ll
total 112
drwxr-xr-x 13 root root  4096 May 12 07:47 ./
drwxr-xr-x  1 root root  4096 May 12 08:01 ../
drwxr-xr-x  6 root root  4096 May 12 07:46 app/
-rwxr-xr-x  1 root root  1686 May 12 07:46 artisan*
drwxr-xr-x  3 root root  4096 May 12 07:46 bootstrap/
-rw-r--r--  1 root root 10676 May 12 07:46 CHANGELOG.md
-rw-r--r--  1 root root  1477 May 12 07:46 composer.json
drwxr-xr-x  2 root root  4096 May 12 07:46 config/
drwxr-xr-x  5 root root  4096 May 12 07:46 database/
-rw-r--r--  1 root root   234 May 12 07:46 .editorconfig
-rw-r--r--  1 root root   651 May 12 07:46 .env.example
drwxr-xr-x  9 root root  4096 May 12 07:47 .git/
-rw-r--r--  1 root root   111 May 12 07:46 .gitattributes
-rw-r--r--  1 root root   155 May 12 07:46 .gitignore
-rw-r--r--  1 root root   101 May 12 07:47 .gitmodules
-rw-r--r--  1 root root  1022 May 12 07:46 package.json
-rw-r--r--  1 root root  1134 May 12 07:46 phpunit.xml
drwxr-xr-x  4 root root  4096 May 12 07:46 public/
-rw-r--r--  1 root root  3675 May 12 07:46 readme.md
drwxr-xr-x  5 root root  4096 May 12 07:46 resources/
drwxr-xr-x  2 root root  4096 May 12 07:46 routes/
-rw-r--r--  1 root root   563 May 12 07:46 server.php
drwxr-xr-x 18 root root  4096 May 12 07:51 laradock/
drwxr-xr-x  5 root root  4096 May 12 07:46 storage/
drwxr-xr-x  4 root root  4096 May 12 07:46 tests/
-rw-r--r--  1 root root   549 May 12 07:46 webpack.mix.js
```
And I think that is as all was git cloned as root. How do you normally set Laradock and an app up? Perhaps differently.

**Comment by ricardovigatti** [comment]
I'm facing a similar issue while using Laradock within my Jenkins testing process (Not the jenkins container from this package). Here, Jenkins create the workspace and git pull all my app using the "jenkins:jenkins" user. Then it's run ```git submodule add https://github.com/Laradock/laradock.git``` and that's my final workspace folder structure:

```
drwxr-xr-x 11 jenkins jenkins   4096 Oct  6 20:10 app
-rw-r--r--  1 jenkins jenkins   1686 Oct  6 20:10 artisan
drwxr-xr-x  3 jenkins jenkins   4096 Oct  6 20:10 bootstrap
drwxr-xr-x  2 jenkins jenkins   4096 Oct  6 20:10 breadcrumbs
-rw-r--r--  1 jenkins jenkins   3876 Oct  6 20:10 build.xml
-rw-r--r--  1 jenkins jenkins   3326 Oct  6 20:10 composer.json
-rw-r--r--  1 jenkins jenkins 281298 Oct  6 20:10 composer.lock
drwxr-xr-x  2 jenkins jenkins   4096 Oct  6 20:10 config
drwxr-xr-x  5 jenkins jenkins   4096 Oct  6 21:06 database
-rw-r--r--  1 jenkins jenkins    761 Oct  7 18:57 Jenkinsfile
drwxr-xr-x 56 jenkins jenkins   4096 Oct  7 05:21 laradock
-rw-r--r--  1 jenkins jenkins   1649 Oct  6 20:10 package.json
-rw-r--r--  1 jenkins jenkins 484478 Oct  6 20:10 package-lock.json
-rw-r--r--  1 jenkins jenkins    716 Oct  6 20:10 phpunit.dusk.xml
-rw-r--r--  1 jenkins jenkins   1040 Oct  6 20:44 phpunit.xml
drwxr-xr-x  2 jenkins jenkins   4096 Oct  7 04:11 public
-rw-r--r--  1 jenkins jenkins   1421 Oct  6 20:10 README.md
drwxr-xr-x  5 jenkins jenkins   4096 Oct  6 20:10 resources
drwxr-xr-x  2 jenkins jenkins   4096 Oct  6 20:10 routes
-rw-r--r--  1 jenkins jenkins    563 Oct  6 20:10 server.php
drwxr-xr-x  5 jenkins jenkins   4096 Oct  6 20:10 storage
drwxr-xr-x  5 jenkins jenkins   4096 Oct  6 20:10 tests
-rw-r--r--  1 jenkins jenkins   3299 Oct  6 20:10 webpack.mix.js
```

So far, so good.

During the process, i run ```docker-compose exec workspace bash``` and try install composer. Now my "vendor" folder is owned by "root:root". And i don't want this.

If i try ```docker-compose exec -u laradock workspace bash```:

```
[RuntimeException]                                        
  /var/www/vendor does not exist and could not be created.  
```

message appears

**Comment by prezire** [comment]
I see. So this is still ongoing.

**Comment by garbinmarcelo** [comment]
Hi, I just had the same problem, running laradock on an AWS EC2 Ubuntu 20.

Any solution for that?

![image](https://user-images.githubusercontent.com/9335588/93941548-13f97200-fd05-11ea-9657-d41bf7f3f880.png)

**Comment by garbinmarcelo** [comment]
If I access the command (without --user): ``docker-compose exec workspace bash``

and run composer install, it works. but I don’t know if this is correct.

![image](https://user-images.githubusercontent.com/9335588/93941841-a26df380-fd05-11ea-8821-8c11cd7f3f1d.png)


Any suggestion? is it correct to use as root?
