### ISSUE TITLE
xdebug installation fails when php version is 5.6

### ISSUE THREAD

**Issue by Zane1988** [laradock/laradock#1535]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux): centos 
- System info disto/version: 
CentOS Linux release 7.3.1611 (Core)

### Issue:
pecl/xdebug requires PHP (version >= 7.0.0), installed version is 5.6.35
No valid packages found
_____

### Expected behavior:

xdebug can be installed with php version 5.6
_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by dimsamaras** [comment]
Try this:

`ARG INSTALL_XDEBUG=false
RUN if [ ${INSTALL_XDEBUG} = true ]; then \
    # Install the xdebug extension
    # NECESSARILLY LOCK THE VERSION!!!
    pecl install xdebug-2.5.5 && \
    docker-php-ext-enable xdebug \
;fi`

Yet xdebug breaks when going over some static variable, [known issue](https://github.com/docker-library/php/issues/133)

This Dockerfile would work though: it uses an older Laradock image (quoting parts of it):

`FROM laradock/php-fpm:2.0-56`

and 

`ARG INSTALL_XDEBUG=false
RUN if [ ${INSTALL_XDEBUG} = true ]; then \
    apt-get install -y php5-xdebug && \
	echo "zend_extension=/usr/lib/php5/20131226/xdebug.so" > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
;fi`

**Comment by morfin** [comment]
I Just had to specify older xdebug version compatible with PHP 5.6:
pecl install xdebug-2.5.5
