### ISSUE TITLE
ERROR: for certbot  Cannot create container for service certbot: invalid mode: cached/letsencrypt

### ISSUE THREAD

**Issue by fanly** [laradock/laradock#1540]
ERROR: for certbot  Cannot create container for service certbot: invalid mode: cached/letsencrypt

**Comment by crcms** [comment]
@fanly I also encountered the same problem. Did you solve it?

**Comment by vortgo** [comment]
Any progress?

**Comment by j1yak** [comment]
doesn't work

**Comment by Trexology** [comment]
yes, @j1yak solution has fixed the issue.

**Comment by jasperf** [comment]
True, but even when you make it that path or remove `cache` in .env and avoid this error `ERROR: for certbot  Cannot create container for service certbot: invalid mode: cached/letsencrypt`
I still get
```
certbot_1     | Requested domain "domain.io" is not a FQDN
certbot_1     | cp: cannot stat '/etc/letsencrypt/archive/"larastud.io"/cert1.pem': No such file or directory
certbot_1     | cp: cannot stat '/etc/letsencrypt/archive/"larastud.io"/privkey1.pem': No such file or directory
```

**Comment by jasperf** [comment]
I needed domain and email without quotes for them to work:
```
environment:
        - CN=domain.io
        - EMAIL=noneofyourbusiness@gmail.com
```
