### ISSUE TITLE
Containers don't start when Docker service is automatically started because of the shared disk

### ISSUE THREAD

**Issue by rachid804** [laradock/laradock#1543]
### Info:
- Docker version (`$ docker --version`): **18.03.0-ce, build 0520e24**
- Laradock commit (`$ git rev-parse HEAD`): 7fc3a9cb7a737e0b44833b71ebb4f21cfaeda5cf
- System info (Mac, PC, Linux): Windows 10
- System info disto/version: 

### Issue:
The containers fail to start when i run ` docker-compose up` or `docker-compose start`
_____

### Expected behavior:
Containers running
_____

### Reproduce:
When i restart the computer and run up command, the issue is cause by the shared disk. I shared both C and D to resolve the problem i have to disable disks sharing, restart docker and share the disks again
_____

### Relevant Code:

```shell
ERROR: for laradock_redis_1  Cannot start service redis: b'driver failed programming external connectivity on endpoint laradock_redis_1 (7600eed90757b6bc0b718380ed25f6778d34282564d788e220552200c46d5714): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.18.0.2:6379: input/output error'
```

**Comment by randomcatgamer** [comment]
Am experiencing the same issue
