### ISSUE TITLE
Laravel Installer not available to root

### ISSUE THREAD

**Issue by georgemr** [laradock/laradock#1547]
### Info:
- Docker version (Docker version 18.03.1-ce, build 9ee9f40): 
- Laradock commit (0c41fceae1b23089f5360dc4f8aeb85719c7bf5a): 
- System info (PC): 
- Windows 10 version 1803 (os build 17134.48): 

### Issue:
Laravel Installer not available to root
_____

### Expected behavior:
Laravel Installer shoulb available to root after WORKSPACE_INSTALL_LARAVEL_INSTALLER is set to true in .env

_____

### Reproduce:
Set WORKSPACE_INSTALL_LARAVEL_INSTALLER=true to .env
docker-compose up -d workspace
docker-compose exec workspace bash
_____

### Relevant Code:
Code in Dockerfile is:

```
###########################################################################
# Composer:
###########################################################################

USER root

# Add the composer.json
COPY ./composer.json /home/laradock/.composer/composer.json

# Make sure that ~/.composer belongs to laradock
RUN chown -R laradock:laradock /home/laradock/.composer

USER laradock

# Check if global install need to be ran
ARG COMPOSER_GLOBAL_INSTALL=false
ENV COMPOSER_GLOBAL_INSTALL ${COMPOSER_GLOBAL_INSTALL}

RUN if [ ${COMPOSER_GLOBAL_INSTALL} = true ]; then \
    # run the install
    composer global install \
;fi

ARG COMPOSER_REPO_PACKAGIST
ENV COMPOSER_REPO_PACKAGIST ${COMPOSER_REPO_PACKAGIST}

RUN if [ ${COMPOSER_REPO_PACKAGIST} ]; then \
    composer config -g repo.packagist composer ${COMPOSER_REPO_PACKAGIST} \
;fi

# Export composer vendor path
RUN echo "" >> ~/.bashrc && \
    echo 'export PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc

```

The last commands runs for user laradock when it should run for root too.

**Comment by alexkb** [comment]
I'm using laradock as of ad316bab50e but the workspace/Dockerfile no longer mentions updating the bashrc file for either root or laradock. Also, it only seems to install it for root:
https://github.com/laradock/laradock/blob/master/workspace/Dockerfile#L495
