### ISSUE TITLE
chmod(): Operation not permitted

### ISSUE THREAD

**Issue by alcir-junior-caju** [laradock/laradock#1550]
### Info:
- Docker version (`$ docker --version`): Docker version 17.05.0-ce, build 89658be
- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux): Linux
- System info disto/version: Linux Mint 18.3

### Issue:

When I upload an image using the storeAs I get the error: chmod(): Operation not permitted
_____

### Expected behavior:

There should be no mistake and the image uploads
_____

### Reproduce:

I just ran the project with laradock and uploaded an image of laravel
_____

### Relevant Code:

        if ($request->hasFile('avatar')) :
            $birthday = str_replace('/', '-', $request->input('birthday'));
            $imageName  = strtolower($birthday . '-' . $request->input('first_name') . '-' . $request->input('last_name'));
            $imageName .= '.' . $request->avatar->getClientOriginalExtension();
            $data['avatar'] = $request->avatar->storeAs('avatars', $imageName);
        endif;

```
// place a code sample here
```

**Comment by muzammilaskari** [comment]
@alcir-junior-caju How did you resolve this? I am facing exactly same error in my code
