### ISSUE TITLE
Workspace packets package addition | npm -> mozjpeg build failed

### ISSUE THREAD

**Issue by AntoineDewaele** [laradock/laradock#1554]
### Info:
- Docker version (`$ docker --version`): Docker version 17.05.0-ce, build 89658be
- System info (Mac, PC, Linux): Linux

### Issue:

In some npm package, mozjpeg 5.0.0 is required. But to build, mozjpeg need nasm. Could it be possible to add nasm to workspace packet package ?

![screenshot from 2018-05-23 16-13-17](https://user-images.githubusercontent.com/9131295/40430137-b989f84a-5ea4-11e8-97f6-bff60c415700.png)

**Comment by jp-sauve** [comment]
I also just got this error while doing npm install in workspace, using laradock user (if that matters!). I was following [this guide](http://laraveldaily.com/quick-start-laravel-5-5-vue-js-simple-crud-project/) on a new install.

``
> mozjpeg@5.0.0 postinstall /var/www/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/var/www/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/var/www/node_modules/mozjpeg/vendor" --bindir="/var/www/node_modules/mozjpeg/vendor" --libdir="/var/www/node_modules/mozjpeg/vendor" && make -j2 && make install -j2
Command failed: ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/var/www/node_modules/mozjpeg/vendor" --bindir="/var/www/node_modules/mozjpeg/vendor" --libdir="/var/www/node_modules/mozjpeg/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)

``
