### ISSUE TITLE
ERROR: Service 'php-fpm' failed to build错误，执行docker-compose up -d  nginx

### ISSUE THREAD

**Issue by jhomephper** [laradock/laradock#1559]
### Info:
 执行：docker-compose up -d  nginx

### 报错:

```

No releases available for package "pecl.php.net/imagick"
install failed
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -y libmagickwand-dev imagemagick &&     pecl install imagick &&     docker-php-ext-enable imagick ;fi' returned a non-zero code: 1


```

**Comment by ikingye** [comment]
一样的错误。

切换 tag v7.0.0 版本正常：
```
git checkout -b v7.0.0 v7.0.0
cp env-example .env
```

**Comment by ikingye** [comment]
same

**Comment by ikingye** [comment]
git checkout -b v6.0.1 v6.0.1
cp env-example .env

解决

**Comment by jhomephper** [comment]
Annotate it out, haha

**Comment by bestlong** [comment]
Hi @jhomephper 
please try master brach new version again.

**Comment by elinxer** [comment]
git checkout -b v6.0.1 v6.0.1 is right, but master not fixed~

**Comment by bestlong** [comment]
@elinxer 
run `docker-compose build --no-cache php-fpm` rebuild image.

**Comment by zealerFT** [comment]
@ikingye fix the issues because WORKSPACE_INSTALL_IMAGEMAGICK=false

is not the real reason!!!!!!

**Comment by ramden** [comment]
Fixed it by dividing the RUN commands in Dockerfile to:

`RUN set -xe; \
    apt-get update -yqq`

and 

`RUN pecl channel-update pecl.php.net && \
    apt-get install -yqq \ .......`

**Comment by AlanAlbert** [comment]
run a few more times. I'm OK
