### ISSUE TITLE
laradock_mysql_1 state exit 1

### ISSUE THREAD

**Issue by jeffreyliim** [laradock/laradock#1562]
### Info:
When I run docker-compose up nginx mysql redis, it doesnt allow access to my data in mysql. I've tried reinstalling docker, deleting laradock folder and installing laradock folder and re-configure again, deleted docker images and run it again and rebuilding containers.

### Issue:
- state is exit 1
- ports is empty
_____

### Expected behavior:
- state should be Exit 1
- ports should be 0.0.0.0:3306->3306/tcp
_____

### Reproduce:

_____

### Relevant Code:

```

$ docker-compose ps
        Name                     Command              State               Ports
------------------------------------------------------------------------------------------
laradock_mysql_1       docker-entrypoint.sh mysqld    Exit 1
laradock_nginx_1       nginx                          Up       0.0.0.0:443->443/tcp,
                                                               0.0.0.0:80->80/tcp
laradock_php-fpm_1     docker-php-entrypoint php-     Up       9000/tcp
                       fpm
laradock_redis_1       docker-entrypoint.sh redis     Up       0.0.0.0:6379->6379/tcp
                       ...
laradock_workspace_1   /sbin/my_init                  Up       0.0.0.0:2222->22/tcp

**Comment by coderars** [comment]
Stop everything and then try to run only the mysql container without the `-d` param. See if any error comes up while starting the container.

`docker-compose up mysql`

Also check the value of `DATA_PATH_HOST` in laradock's `.env` file.

If no success at all, try to change the value of `MYSQL_VERSION` to 5.7 (backup your data folder first!) and rebuild the mysql container. Maybe you could try to point the `DATA_PATH_HOST` to an empty folder for testing.

What operating system, docker+compose version do you have?

**Comment by ZR87** [comment]
Same issue here...
```bash
ZR-MacBookAir:laradock ZR87$ docker-compose up  mysql 
Starting laradock_mysql_1 ... done
Attaching to laradock_mysql_1
mysql_1                | 
mysql_1                | ERROR: mysqld failed while attempting to check config
mysql_1                | command was: "mysqld --verbose --help"
mysql_1                | 
mysql_1                | 2018-05-27T21:37:46.266615Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
mysql_1                | 2018-05-27T21:37:46.271385Z 0 [ERROR] [MY-011071] [Server] /usr/sbin/mysqld: Error while setting value 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' to 'sql_mode'
mysql_1                | 2018-05-27T21:37:46.290011Z 0 [ERROR] [MY-010119] [Server] Aborting
laradock_mysql_1 exited with code 1


```

**Comment by jeffreyliim** [comment]
Thank you @ZR87 its exactly what I'm looking for!

**Comment by mkaddouriInet** [comment]
When using linux, you should keep in mind that you cannot use user root in your .env file. change the username to something else.
