### ISSUE TITLE
Error: Node version 'stable' not found when i up workspace container

### ISSUE THREAD

**Issue by salamex** [laradock/laradock#1564]
### Info:
- Docker version Docker version 18.03.1-ce: 
- Laradock commit 6e6284d00f0451f53aa3c208e2808a8607ef57f5
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04

### Issue:
when i run 
$ docker-compose up -d apache2 mysql redis phpmyadmin workspace
at first time, i get this error:

Removing intermediate container 190efb12c1d2
 ---> 8529f0b0c33b
Step 87/161 : ENV NVM_DIR /home/laradock/.nvm
 ---> Running in 4b10fd684832
Removing intermediate container 4b10fd684832
 ---> 12a32771604c
Step 88/161 : RUN if [ ${INSTALL_NODE} = true ]; then     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash &&         . $NVM_DIR/nvm.sh &&         nvm install ${NODE_VERSION} &&         nvm use ${NODE_VERSION} &&         nvm alias ${NODE_VERSION} &&         if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi &&         npm install -g gulp bower vue-cli ;fi
 ---> Running in fa56afbdb9f0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12540  100 12540    0     0  19144      0 --:--:-- --:--:-- --:--:-- 19145
=> Downloading nvm from git to '/home/laradock/.nvm'
=> Cloning into '/home/laradock/.nvm'...
Note: checking out '7ad6d98cedde01809e32d56ab8ced064f6f28175'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/laradock/.profile
=> bash_completion source string already in /home/laradock/.profile
=> Installing Node.js version stable
Version 'stable' not found - try `nvm ls-remote` to browse available versions.
Failed to install Node.js stable
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
Version 'stable' not found - try `nvm ls-remote` to browse available versions.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash &&         . $NVM_DIR/nvm.sh &&         nvm install ${NODE_VERSION} &&         nvm use ${NODE_VERSION} &&         nvm alias ${NODE_VERSION} &&         if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi &&         npm install -g gulp bower vue-cli ;fi' returned a non-zero code: 3

_____

### Expected behavior:
stop execution

### Reproduce:
to be sure i'm doing nothing wrong, i removed completely docker, all containers ($ docker system prune -a), removed the dir, clonned again and run composer up.
_____

**Comment by for0231** [comment]
it's same error.

**Comment by andrekutianski** [comment]
use on param `WORKSPACE_NODE_VERSION` the value `v8.12.0` (or another that you need). Works for me

**Comment by DoopSky** [comment]
`WORKSPACE_NODE_VERSION` available value is node.js version alias.

you can use `nvm ls` find some default alias.

`node` (Current v14)
`lts/erbium` (Active LTS v12)
`lts/dubnium`  (Maintenance LTS v10)
