### ISSUE TITLE
nginx-proxy

### ISSUE THREAD

**Issue by mitjarobic** [LaraDock/laradock#157]
How would i use it  with laradock? Can't get it to work.

https://github.com/jwilder/nginx-proxy

**Comment by beedubsss** [comment]
Make sure you use the same network. I would suggest creating a network and making sure all your containers that you want to host under the proxy are on the same network 

`networks:
  default:
    external:
      name: ${config_server_network_name}
`

I add this to my compose file to specify the network which is a variable based on my environment. Hope that helps.

**Comment by mitjarobic** [comment]
Thank you:)
