### ISSUE TITLE
How do I install PHPUnit?

### ISSUE THREAD

**Issue by ArtisanTinkerer** [laradock/laradock#1577]
### Info:
- Docker version (`$ docker --version`): 
Docker version 18.03.0-ce, build 0520e24302

- Laradock commit (`$ git rev-parse HEAD`): 
```0c41fceae1b23089f5360dc4f8aeb85719c7bf5a```

- System info (Mac, PC, Linux): 
PC
- System info disto/version: 
Win 7
### Issue:
PhpUnit not installed on php-fpm.
Cannot run tests.

_____

### Expected behavior:
Should be able to run tests.
_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by vicenteherrera** [comment]
Adding to JohnatanT that 'phpunit' is aliased to '/var/www/vendor/bin/phpunit'.
If you install phpunit on any other directory, change or unset the alias:
`unalias phpunit`

**Comment by mk-relax** [comment]
Thank you @vicenteherrera! The phpunit aliases in laradock made it impossible for me to run PHPUnit from PhpStorm in a Docker container. I got errors like `PHPUnit version: not installed` and `Can not parse PHPUnit version output: Could not open input file: /var/www/project/vendor/phpunit/phpunit/phpunit`.
I would never have found that without your remark, thank you!
