### ISSUE TITLE
Php.ini is a directory

### ISSUE THREAD

**Issue by jonaselan** [laradock/laradock#1588]
- Docker version: version 18.03.1-ce, build 9ee9f40 
- Laradock commit: 0c41fce 
- System info: Linux (Ubuntu 18)

When installing Mongo driver inside of php-fpm, is necessary change php.ini and add `extension=mongo.so` ([reference](http://php.net/manual/en/mongodb.installation.pecl.php)). I have to do that because the version I use of Mongo is 2.6, and this version is not more available on dockerhub.  

The problem is the php.ini, located in `/usr/local/etc/php/php.ini` is a directory instead. Last week was working fine. The screenshot below shows inside of php-fpm, after I run `pecl install mongo`. Some idea what happens? 

![php ini](https://user-images.githubusercontent.com/5933907/40987194-5d66d672-68be-11e8-8a7d-621858b0337a.png)

Thanks in advance!

**Comment by bestlong** [comment]
Fix by #1646
