### ISSUE TITLE
nginx - 404 Not Found

### ISSUE THREAD

**Issue by JohnatanT** [laradock/laradock#1589]
### Info:
- Docker version (`Docker version 18.05.0-ce`): 
- Laradock commit (`ad316bab50e98edf578d9c9c9500b7dc1a9b4dfc`): 
- System info (Linux): 
- System info disto/version: Ubuntu/18.04/bionic

### Issue:

Can not find Nginx page

### Expected behavior:

When you type localhost the Nginx page appears

### Reproduce:

sudo docker-compose up -d nginx mysql

Starting laradock_workspace_1 ... done
Starting laradock_mysql_1 ... done
Starting laradock_php-fpm_1 ... done
Recreating laradock_nginx_1 ... done

sudo docker-compose ps

Name Command State Ports 
--------------------------------------------------------------------------------
laradock_mysql_1 docker-entrypoint.sh Exit 1 
mysqld 
laradock_nginx_1 nginx Up 0.0.0.0:443->443/tcp, 
0.0.0.0:80->80/tcp 
laradock_php-fpm_1 docker-php-entrypoint Up 9000/tcp 
php-fpm 
laradock_phpmyadmin_1 /run.sh phpmyadmin Exit 0 
laradock_workspace_1 /sbin/my_init Up 0.0.0.0:2222->22/tcp

It was supposed to be okay :(

P.S: I do not have Apache on my machine

**Comment by JohnatanT** [comment]
I'm using Laradock just for one application.
My Folder Structure:

/Folder
 ------- / Laradock
-------- / App_Larave

**Comment by jonaselan** [comment]
@JohnatanT Did you create the .env file and mapped it to your application?

```
$ cp env-example .env

# inside .env
$ APPLICATION=../App_Laravel/
```

**Comment by JohnatanT** [comment]
My steps:

1.git clone https://github.com/Laradock/laradock.git laradock
2.cd laradock
3.cp env-example .env
4.docker-compose up -d nginx mysql

Recreating laradock_mysql_1     ... done
Recreating laradock_workspace_1 ... done
Recreating laradock_php-fpm_1   ... done
Recreating laradock_nginx_1     ... done

Accessed: localhost

Result: 

404 Not Found
nginx

**Comment by jonaselan** [comment]
@JohnatanT It's necessary to configure the nginx. If you go on `laradock/nginx/sites`, you will see files with extension `.conf`. Create a directory with this structure and try 

```
+ public
  - index.html
+ laradock
```

**Comment by hubertnnn** [comment]
Nginx might be dead.
Could you run this 2 commands:
`docker-compose ps`
`docker-compose logs nginx`

If the first one on column "State" have something else than UP then share log from second command here.

**Comment by almonax** [comment]
Hi guys
I had this problem. And this solution helped me: https://github.com/laradock/laradock/issues/86#issuecomment-264181045

**Comment by appleboy** [comment]
@JohnatanT I send the PR to fix this issue. See https://github.com/laradock/laradock/pull/2399

**Comment by deniskv** [comment]
Also, make sure you added your project dir to docker->preferences->file sharing.

**Comment by mikoop79** [comment]
> `docker-compose logs nginx`
really helped debug the issue. have to remove the other files in /nginx/sites

**Comment by douma** [comment]
Did you clone the laradock repo **inside** your application repo?

Try a clean install with the following steps, seems to be working:

```
cd ~/Desktop
composer create-project --prefer-dist laravel/laravel laravel
cd laravel
git clone https://github.com/Laradock/laradock.git
cd laradock/
cp env-example .env
docker-compose up -d nginx mysql redis workspace
```

While setting your **application's** env file:

```
DB_HOST=mysql
REDIS_HOST=redis
QUEUE_HOST=beanstalkd
```

```
curl -L localhost
```

**Comment by uzh13** [comment]
I changed nginx config file.
`laradock/nginx/sites/default.conf`
Instead of
`root /var/www/public;`
I typed
`root /var/www/my_app/public;`
(notice - no slash at the end)

**Comment by prsgodoi** [comment]
I have the same problem.
My Folder Structure VPS:

`root@server:~# ls
laradock  website`

I've done this procedure too.
`$ cp env-example .env

# inside .env
$ APPLICATION=../website/`

And the error continues.
`404 Not Found`

**Comment by ILkUVayne** [comment]
@prsgodoi have you solved this problem? I have the same problem.

**Comment by danielleplatt2020** [comment]
> @prsgodoi have you solved this problem? I have the same problem.

any luck? I'm stuck too

**Comment by mysticaltech** [comment]
To recap folks, just create a **public** folder inside your app folder, and move all of your website files there.
