### ISSUE TITLE
Docker-compose.yml reported as incorrect version

### ISSUE THREAD

**Issue by jp-sauve** [laradock/laradock#1594]
### Info:
Using the instructions to set up runners (either Linux or docker) provided by GitLab:
https://docs.gitlab.com/runner/register/index.html#docker
fails to complete, using either alpine:latest as default image during runner creation, or specifying jonaskello/docker-and-compose:1.12.1-1.8.0
The problem is that the Docker-compose.yml file requires a newer version of Docker-compose than you get following default instructions. Perhaps you could amend your instructions so that people know which docker image you used, or whether you just used your own and installed docker and compose manually?

- Docker version (`$ docker --version`):  Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  Linux
- System info disto/version: Ubuntu 16.04

### Issue:
Gitlab runner connects, but fails due to docker-compose version mismatch
_____

### Expected behavior:
Pipeline should run without failure in fresh clone.
_____

### Reproduce:
Install GitLab Omnibus edition (docker version), and set up runner as per:
https://docs.gitlab.com/runner/register/index.html#docker
Gnu/Linux section or docker section. result is the same.
_____

### Pipeline output:
[0KRunning with gitlab-runner 10.8.0 (079aad9e)
[0;m[0K  on GrokoDocko 67a9e927
[0;m[0KUsing Docker executor with image jonaskello/docker-and-compose:1.12.1-1.8.0 ...
[0;m[0KStarting service docker:1.12.1-dind ...
[0;m[0KPulling docker image docker:1.12.1-dind ...
[0;m[0KUsing docker image sha256:63384132523764a58b239155bba51de021bc12ebe1480b0c175e2989278c6e4a for docker:1.12.1-dind ...
[0;m[0KWaiting for services to be up and running...
[0;m[0KPulling docker image jonaskello/docker-and-compose:1.12.1-1.8.0 ...
[0;m[0KUsing docker image sha256:3370764d9846869e07cdc3a572b3086b8ed6607b66d6deb26d606168583681e6 for jonaskello/docker-and-compose:1.12.1-1.8.0 ...
[0;msection_start:1528408830:prepare_script
[0KRunning on runner-67a9e927-project-18-concurrent-0 via 75f4e5abe4d9...
section_end:1528408833:prepare_script
[0Ksection_start:1528408833:get_sources
[0K[32;1mCloning repository...[0;m
Cloning into '/builds/jp-sauve/laradock-drupal8'...
[32;1mChecking out 0821d959 as master...[0;m
[32;1mSkipping Git submodules setup[0;m
section_end:1528408836:get_sources
[0Ksection_start:1528408836:restore_cache
[0Ksection_end:1528408838:restore_cache
[0Ksection_start:1528408838:download_artifacts
[0Ksection_end:1528408840:download_artifacts
[0Ksection_start:1528408840:build_script
[0K[32;1m$ docker info[0;m
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-127-generic
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: 921f333dfae1
ID: 2PPY:WSSS:PBAC:VFCG:P7NM:ZRF2:J5VN:KVBS:E7L5:TXVI:N2KH:6J3B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
[32;1m$ docker-compose version[0;m
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
[32;1m$ cp env-example .env[0;m
[32;1m$ sed -i -- "s/=false/=true/g" .env[0;m
[32;1m$ cat .env[0;m
###########################################################
###########################################################

### Paths #################################################
Point to the path of your applications code on your host

APP_CODE_PATH_HOST=../

 Point to where the `APP_CODE_PATH_HOST` should be in the container. You may add flags to the path 

`:cached`, `:delegated`. When using Docker Sync add `:nocopy`
APP_CODE_PATH_CONTAINER=/var/www:cached

 Choose storage path on your machine. For all storage systems
DATA_PATH_HOST=~/.laradock/data

### Drivers ################################################

 All volumes driver
VOLUMES_DRIVER=local

 All Networks driver
NETWORKS_DRIVER=bridge

### Docker compose files ##################################

 Select which docker-compose files to include. If using docker-sync append `:docker-compose.sync.yml` at the end
COMPOSE_FILE=docker-compose.yml

 Change the separator from : to ; on Windows
COMPOSE_PATH_SEPARATOR=:

### PHP Version ###########################################

 Select a PHP version of the Workspace and PHP-FPM containers (Does not apply to HHVM). Accepted values: 7.2 - 7.1 - 7.0 - 5.6
PHP_VERSION=7.2

### PHP Interpreter #######################################

 Select the PHP Interpreter. Accepted values: hhvm - php-fpm
PHP_INTERPRETER=php-fpm

### Docker Host IP ########################################

 Enter your Docker Host IP (will be appended to /etc/hosts). Default is `10.0.75.1`
DOCKER_HOST_IP=10.0.75.1

### Remote Interpreter ####################################

 Choose a Remote Interpreter entry matching name. Default is `laradock`
PHP_IDE_CONFIG=serverName=laradock

### Windows Path ##########################################

 A fix for Windows users, to ensure the application path works
COMPOSE_CONVERT_WINDOWS_PATHS=1

### Environment ###########################################

 If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
CHANGE_SOURCE=true

### Docker Sync ###########################################

 If you are using Docker Sync. For `osx` use 'native_osx', for `windows` use 'unison', for `linux` docker-sync is not required
DOCKER_SYNC_STRATEGY=native_osx

###########################################################
###########################################################

### WORKSPACE #############################################

WORKSPACE_COMPOSER_GLOBAL_INSTALL=true
WORKSPACE_COMPOSER_REPO_PACKAGIST=
WORKSPACE_INSTALL_NODE=true
WORKSPACE_NODE_VERSION=stable
WORKSPACE_NPM_REGISTRY=
WORKSPACE_INSTALL_YARN=true
WORKSPACE_YARN_VERSION=latest
WORKSPACE_INSTALL_PHPREDIS=true
WORKSPACE_INSTALL_WORKSPACE_SSH=true
WORKSPACE_INSTALL_SUBVERSION=true
WORKSPACE_INSTALL_XDEBUG=true
WORKSPACE_INSTALL_LDAP=true
WORKSPACE_INSTALL_SOAP=true
WORKSPACE_INSTALL_IMAP=true
WORKSPACE_INSTALL_MONGO=true
WORKSPACE_INSTALL_AMQP=true
WORKSPACE_INSTALL_MSSQL=true
WORKSPACE_INSTALL_DRUSH=true
WORKSPACE_DRUSH_VERSION=8.1.17
WORKSPACE_INSTALL_DRUPAL_CONSOLE=true
WORKSPACE_INSTALL_AEROSPIKE=true
WORKSPACE_INSTALL_V8JS=true
WORKSPACE_INSTALL_LARAVEL_ENVOY=true
WORKSPACE_INSTALL_LARAVEL_INSTALLER=true
WORKSPACE_INSTALL_DEPLOYER=true
WORKSPACE_INSTALL_PRESTISSIMO=true
WORKSPACE_INSTALL_LINUXBREW=true
WORKSPACE_INSTALL_MC=true
WORKSPACE_INSTALL_SYMFONY=true
WORKSPACE_INSTALL_PYTHON=true
WORKSPACE_INSTALL_IMAGE_OPTIMIZERS=true
WORKSPACE_INSTALL_IMAGEMAGICK=true
WORKSPACE_INSTALL_TERRAFORM=true
WORKSPACE_INSTALL_DUSK_DEPS=true
WORKSPACE_INSTALL_PG_CLIENT=true
WORKSPACE_INSTALL_SWOOLE=true
WORKSPACE_PUID=1000
WORKSPACE_PGID=1000
WORKSPACE_CHROME_DRIVER_VERSION=2.32
WORKSPACE_TIMEZONE=UTC
WORKSPACE_SSH_PORT=2222

### PHP_FPM ###############################################

PHP_FPM_INSTALL_ZIP_ARCHIVE=true
PHP_FPM_INSTALL_BCMATH=true
PHP_FPM_INSTALL_MYSQLI=true
PHP_FPM_INSTALL_TOKENIZER=true
PHP_FPM_INSTALL_INTL=true
PHP_FPM_INSTALL_IMAGEMAGICK=true
PHP_FPM_INSTALL_OPCACHE=true
PHP_FPM_INSTALL_IMAGE_OPTIMIZERS=true
PHP_FPM_INSTALL_PHPREDIS=true
PHP_FPM_INSTALL_MEMCACHED=true
PHP_FPM_INSTALL_XDEBUG=true
PHP_FPM_INSTALL_IMAP=true
PHP_FPM_INSTALL_MONGO=true
PHP_FPM_INSTALL_AMQP=true
PHP_FPM_INSTALL_MSSQL=true
PHP_FPM_INSTALL_SOAP=true
PHP_FPM_INSTALL_GMP=true
PHP_FPM_INSTALL_EXIF=true
PHP_FPM_INSTALL_AEROSPIKE=true
PHP_FPM_INSTALL_PGSQL=true
PHP_FPM_INSTALL_GHOSTSCRIPT=true
PHP_FPM_INSTALL_LDAP=true
PHP_FPM_INSTALL_SWOOLE=true
PHP_FPM_INSTALL_PG_CLIENT=true
PHP_FPM_INSTALL_PCNTL=true

### PHP_WORKER ############################################

PHP_WORKER_INSTALL_PGSQL=true

### NGINX #################################################

NGINX_HOST_HTTP_PORT=80
NGINX_HOST_HTTPS_PORT=443
NGINX_HOST_LOG_PATH=./logs/nginx/
NGINX_SITES_PATH=./nginx/sites/
NGINX_PHP_UPSTREAM_CONTAINER=php-fpm
NGINX_PHP_UPSTREAM_PORT=9000

### APACHE ################################################

APACHE_HOST_HTTP_PORT=80
APACHE_HOST_HTTPS_PORT=443
APACHE_HOST_LOG_PATH=./logs/apache2
APACHE_SITES_PATH=./apache2/sites
APACHE_PHP_UPSTREAM_CONTAINER=php-fpm
APACHE_PHP_UPSTREAM_PORT=9000
APACHE_PHP_UPSTREAM_TIMEOUT=60
APACHE_DOCUMENT_ROOT=/var/www/

### MYSQL #################################################

MYSQL_VERSION=5.7
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

### REDIS #################################################

REDIS_PORT=6379

### Percona ###############################################

PERCONA_DATABASE=homestead
PERCONA_USER=homestead
PERCONA_PASSWORD=secret
PERCONA_PORT=3306
PERCONA_ROOT_PASSWORD=root
PERCONA_ENTRYPOINT_INITDB=./percona/docker-entrypoint-initdb.d

### MSSQL #################################################

MSSQL_DATABASE=homestead
MSSQL_PASSWORD=yourStrong(!)Password
MSSQL_PORT=1433

### MARIADB ###############################################

MARIADB_DATABASE=default
MARIADB_USER=default
MARIADB_PASSWORD=secret
MARIADB_PORT=3306
MARIADB_ROOT_PASSWORD=root
MARIADB_ENTRYPOINT_INITDB=./mariadb/docker-entrypoint-initdb.d

### POSTGRES ##############################################

POSTGRES_DB=default
POSTGRES_USER=default
POSTGRES_PASSWORD=secret
POSTGRES_PORT=5432

### RABBITMQ ##############################################

RABBITMQ_NODE_HOST_PORT=5672
RABBITMQ_MANAGEMENT_HTTP_HOST_PORT=15672
RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT=15671
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest

### ELASTICSEARCH #########################################

ELASTICSEARCH_HOST_HTTP_PORT=9200
ELASTICSEARCH_HOST_TRANSPORT_PORT=9300

### KIBANA ################################################

KIBANA_HTTP_PORT=5601

### MEMCACHED #############################################

MEMCACHED_HOST_PORT=11211

### BEANSTALKD CONSOLE ####################################

BEANSTALKD_CONSOLE_BUILD_PATH=./beanstalkd-console
BEANSTALKD_CONSOLE_CONTAINER_NAME=beanstalkd-console
BEANSTALKD_CONSOLE_HOST_PORT=2080

### BEANSTALKD ############################################

BEANSTALKD_HOST_PORT=11300

### SELENIUM ##############################################

SELENIUM_PORT=4444

### MINIO #################################################

MINIO_PORT=9000

### ADMINER ###############################################

ADM_PORT=8080
ADM_INSTALL_MSSQL=true

### PHP MY ADMIN ##########################################

 Accepted values: mariadb - mysql

PMA_DB_ENGINE=mysql

 Credentials/Port:

PMA_USER=default
PMA_PASSWORD=secret
PMA_ROOT_PASSWORD=secret
PMA_PORT=8080

### MAILDEV ###############################################

MAILDEV_HTTP_PORT=1080
MAILDEV_SMTP_PORT=25

### VARNISH ###############################################

VARNISH_CONFIG=/etc/varnish/default.vcl
VARNISH_PORT=8080
VARNISH_BACKEND_PORT=8888
VARNISHD_PARAMS=-p default_ttl=3600 -p default_grace=3600

### Varnish ###############################################

 Proxy 1
VARNISH_PROXY1_CACHE_SIZE=128m
VARNISH_PROXY1_BACKEND_HOST=workspace
VARNISH_PROXY1_SERVER=SERVER1

 Proxy 2
VARNISH_PROXY2_CACHE_SIZE=128m
VARNISH_PROXY2_BACKEND_HOST=workspace
VARNISH_PROXY2_SERVER=SERVER2

### HAPROXY ###############################################

HAPROXY_HOST_HTTP_PORT=8085

### JENKINS ###############################################

JENKINS_HOST_HTTP_PORT=8090
JENKINS_HOST_SLAVE_AGENT_PORT=50000
JENKINS_HOME=./jenkins/jenkins_home

### GRAFANA ###############################################

GRAFANA_PORT=3000

### BLACKFIRE #############################################

 Create an account on blackfire.io. Don't enable blackfire and xDebug at the same time. # visit https://blackfire.io/docs/24-days/06-installation#install-probe-debian for more info.
INSTALL_BLACKFIRE=true
BLACKFIRE_CLIENT_ID=<client_id>
BLACKFIRE_CLIENT_TOKEN=<client_token>
BLACKFIRE_SERVER_ID=<server_id>
BLACKFIRE_SERVER_TOKEN=<server_token>

### AEROSPIKE #############################################

AEROSPIKE_SERVICE_PORT=3000
AEROSPIKE_FABRIC_PORT=3001
AEROSPIKE_HEARTBEAT_PORT=3002
AEROSPIKE_INFO_PORT=3003

## Temp solution, this should be in the dockerfile
 for all versions "https://github.com/aerospike/aerospike-client-php/archive/master.tar.gz"
 for php 7.2 (using this branch until the support for 7.2 on master) "https://github.com/aerospike/aerospike-client-php/archive/7.2.0-in-progress.tar.gz"
AEROSPIKE_PHP_REPOSITORY=https://github.com/aerospike/aerospike-client-php/archive/7.2.0-in-progress.tar.gz

### RETHINKDB #############################################

RETHINKDB_PORT=8090

### MONGODB ###############################################

MONGODB_PORT=27017

### CADDY #################################################

CADDY_HOST_HTTP_PORT=80
CADDY_HOST_HTTPS_PORT=443
CADDY_HOST_LOG_PATH=./logs/caddy
CADDY_CUSTOM_CADDYFILE=./caddy/Caddyfile

### LARAVEL ECHO SERVER ###################################

LARAVEL_ECHO_SERVER_PORT=6001

### SOLR ##################################################

SOLR_VERSION=5.5
SOLR_PORT=8983
SOLR_DATAIMPORTHANDLER_MYSQL=true
[32;1m$ env | sort[0;m
CI=true
CI_BUILD_BEFORE_SHA=0000000000000000000000000000000000000000
CI_BUILD_ID=88
CI_BUILD_NAME=build:5.6:php-fpm
CI_BUILD_REF=0821d959b41969bec4e8df7ff24c8deed4a7796f
CI_BUILD_REF_NAME=master
CI_BUILD_REF_SLUG=master
CI_BUILD_STAGE=test
CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_COMMIT_DESCRIPTION=
CI_COMMIT_MESSAGE=Update .gitlab-ci.yml
CI_COMMIT_REF_NAME=master
CI_COMMIT_REF_SLUG=master
CI_COMMIT_SHA=0821d959b41969bec4e8df7ff24c8deed4a7796f
CI_COMMIT_TITLE=Update .gitlab-ci.yml
CI_CONFIG_PATH=.gitlab-ci.yml
CI_DISPOSABLE_ENVIRONMENT=true
CI_JOB_ID=88
CI_JOB_NAME=build:5.6:php-fpm
CI_JOB_STAGE=test
CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_PIPELINE_ID=19
CI_PIPELINE_SOURCE=web
CI_PROJECT_DIR=/builds/jp-sauve/laradock-drupal8
CI_PROJECT_ID=18
CI_PROJECT_NAME=laradock-drupal8
CI_PROJECT_NAMESPACE=jp-sauve
CI_PROJECT_PATH=jp-sauve/laradock-drupal8
CI_PROJECT_PATH_SLUG=jp-sauve-laradock-drupal8
CI_PROJECT_URL=http://gitlab.grokology.ca/jp-sauve/laradock-drupal8
CI_PROJECT_VISIBILITY=private
CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
CI_REGISTRY_USER=gitlab-ci-token
CI_REPOSITORY_URL=http://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.grokology.ca/jp-sauve/laradock-drupal8.git
CI_RUNNER_DESCRIPTION=GrokoDocko
CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
CI_RUNNER_ID=10
CI_RUNNER_REVISION=079aad9e
CI_RUNNER_TAGS=docker
CI_RUNNER_VERSION=10.8.0
CI_SERVER=yes
CI_SERVER_NAME=GitLab
CI_SERVER_REVISION=2268d0c
CI_SERVER_VERSION=10.8.4
DOCKER_BUCKET=get.docker.com
DOCKER_ENV_CI=true
DOCKER_ENV_CI_BUILD_BEFORE_SHA=0000000000000000000000000000000000000000
DOCKER_ENV_CI_BUILD_ID=88
DOCKER_ENV_CI_BUILD_NAME=build:5.6:php-fpm
DOCKER_ENV_CI_BUILD_REF=0821d959b41969bec4e8df7ff24c8deed4a7796f
DOCKER_ENV_CI_BUILD_REF_NAME=master
DOCKER_ENV_CI_BUILD_REF_SLUG=master
DOCKER_ENV_CI_BUILD_STAGE=test
DOCKER_ENV_CI_COMMIT_DESCRIPTION=
DOCKER_ENV_CI_COMMIT_MESSAGE=Update .gitlab-ci.yml
DOCKER_ENV_CI_COMMIT_REF_NAME=master
DOCKER_ENV_CI_COMMIT_REF_SLUG=master
DOCKER_ENV_CI_COMMIT_SHA=0821d959b41969bec4e8df7ff24c8deed4a7796f
DOCKER_ENV_CI_COMMIT_TITLE=Update .gitlab-ci.yml
DOCKER_ENV_CI_CONFIG_PATH=.gitlab-ci.yml
DOCKER_ENV_CI_DISPOSABLE_ENVIRONMENT=true
DOCKER_ENV_CI_JOB_ID=88
DOCKER_ENV_CI_JOB_NAME=build:5.6:php-fpm
DOCKER_ENV_CI_JOB_STAGE=test
DOCKER_ENV_CI_PIPELINE_ID=19
DOCKER_ENV_CI_PIPELINE_SOURCE=web
DOCKER_ENV_CI_PROJECT_DIR=/builds/jp-sauve/laradock-drupal8
DOCKER_ENV_CI_PROJECT_ID=18
DOCKER_ENV_CI_PROJECT_NAME=laradock-drupal8
DOCKER_ENV_CI_PROJECT_NAMESPACE=jp-sauve
DOCKER_ENV_CI_PROJECT_PATH=jp-sauve/laradock-drupal8
DOCKER_ENV_CI_PROJECT_PATH_SLUG=jp-sauve-laradock-drupal8
DOCKER_ENV_CI_PROJECT_URL=http://gitlab.grokology.ca/jp-sauve/laradock-drupal8
DOCKER_ENV_CI_PROJECT_VISIBILITY=private
DOCKER_ENV_CI_REGISTRY_USER=gitlab-ci-token
DOCKER_ENV_CI_RUNNER_DESCRIPTION=GrokoDocko
DOCKER_ENV_CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
DOCKER_ENV_CI_RUNNER_ID=10
DOCKER_ENV_CI_RUNNER_REVISION=079aad9e
DOCKER_ENV_CI_RUNNER_TAGS=docker
DOCKER_ENV_CI_RUNNER_VERSION=10.8.0
DOCKER_ENV_CI_SERVER=yes
DOCKER_ENV_CI_SERVER_NAME=GitLab
DOCKER_ENV_CI_SERVER_REVISION=2268d0c
DOCKER_ENV_CI_SERVER_VERSION=10.8.4
DOCKER_ENV_DIND_COMMIT=3b5fac462d21ca164b3778647420016315289034
DOCKER_ENV_DOCKER_BUCKET=get.docker.com
DOCKER_ENV_DOCKER_SHA256=05ceec7fd937e1416e5dce12b0b6e1c655907d349d52574319a1e875077ccb79
DOCKER_ENV_DOCKER_VERSION=1.12.1
DOCKER_ENV_GITLAB_CI=true
DOCKER_ENV_GITLAB_FEATURES=
DOCKER_ENV_GITLAB_USER_EMAIL=jean-paul@grokology.ca
DOCKER_ENV_GITLAB_USER_ID=2
DOCKER_ENV_GITLAB_USER_LOGIN=jp-sauve
DOCKER_ENV_GITLAB_USER_NAME=Jean-Paul Sauve
DOCKER_ENV_PHP_VERSION=5.6
DOCKER_HOST=tcp://docker:2375
DOCKER_NAME=/runner-67a9e927-project-18-concurrent-0-build-4/docker
DOCKER_PORT=tcp://172.17.0.4:2375
DOCKER_PORT_2375_TCP=tcp://172.17.0.4:2375
DOCKER_PORT_2375_TCP_ADDR=172.17.0.4
DOCKER_PORT_2375_TCP_PORT=2375
DOCKER_PORT_2375_TCP_PROTO=tcp
DOCKER_SHA256=05ceec7fd937e1416e5dce12b0b6e1c655907d349d52574319a1e875077ccb79
DOCKER_VERSION=1.12.1
GITLAB_CI=true
GITLAB_FEATURES=
GITLAB_USER_EMAIL=jean-paul@grokology.ca
GITLAB_USER_ID=2
GITLAB_USER_LOGIN=jp-sauve
GITLAB_USER_NAME=Jean-Paul Sauve
HOME=/root
HOSTNAME=runner-67a9e927-project-18-concurrent-0
OLDPWD=/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_VERSION=5.6
PWD=/builds/jp-sauve/laradock-drupal8
SHLVL=3
[32;1m$ docker-compose build php-fpm[0;m
Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
section_end:1528408843:build_script
[0Ksection_start:1528408843:after_script
[0Ksection_end:1528408845:after_script
[0K[31;1mERROR: Job failed: exit code 1

**Comment by khs1994** [comment]
Please update your `docker-compose` !
