### ISSUE TITLE
locales, python2 and php-fpm laravel.ini

### ISSUE THREAD

**Issue by marcelogarbin** [laradock/laradock#1596]
### Info:
- Docker version (`$ docker --version`):  `18.03.1-ce, build 9ee9f40`
- Laradock commit (`$ git rev-parse HEAD`): `ba1a83b40bd3380f836f26d3c4362c2c84621def`
- System info: `Linux 18.04 LTS`

### Issue:
This is more of a question, how do I define the locales in Laradock? I would like to set pt_BR.

Another issue is to install python2, can you set to when starting Laradock already install python2 or is it done manually through bash?

Another note, in the php-fpm folder, is a file called [laravel.ini](https://github.com/laradock/laradock/blob/master/php-fpm/laravel.ini). What is it for? I did not find references on how to set these settings.
_____

### Expected behavior:
Define new locales when starting the nginx postgres service. Start python2.
locale is essential for translation of dates. And also some settings to use in PHP.ini.
_____

**Comment by thorerik** [comment]
Unfortunately, currently, you will have to modify the Dockerfiles and add new locales following standard Debian procedures. 

as noted in #862 as you found, there's no way to do this in an automated way via docker-compose

**Comment by marcelogarbin** [comment]
@thorerik Would you have any examples of how I can do this? in which folder and which file to modify?

**Comment by marcelogarbin** [comment]
any news?
