### ISSUE TITLE
Multisite production with SSL

### ISSUE THREAD

**Issue by paulpoot** [laradock/laradock#1597]
I'm currently looking into using laradock to run two applications on a Ubuntu 16.04 VPS. These are run on two different subdomains (app.example.com and sub.app.example.com) and I want to enable SSL for both of them. Got it working on Nginx, but I'm looking to switch to Caddy since it should be easier to get the certificates.

I've followed the documentation [here](http://laradock.io/guides/#run-site-on-ssl-with-let-s-encrypt-certificate), but it doesn't seem to work. This is the error that shows up when running the container.

`[app.example.com] failed to get certificate: acme: Error 400 - urn:ietf:params:acme:error:connection - Fetching http://app.example.com/.well-known/acme-challenge/codeforletsencryptchallenge: Connection refused
`
So, the challenge can't be accessed from the outside. Entering the address in my browser confirms that. I looked around on my server, but couldn't find the .well-known folder either. 

Any clue what's going on or where the .well-known folder should be?

**Comment by ahkui** [comment]
@paulpoot  u need change [app.example.com] to your domain name like [google.com]
