### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by alcir-junior-caju** [laradock/laradock#1609]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux): Linux
- System info disto/version: Linux Mint 18.3

### Issue:

When I run npm install I have an error

### Expected behavior:

You should install all dependencies and compile

### Reproduce:

Access the workspace and run npm install on a new installation of laravel

### Relevant Code:
Error displayed in terminal

```
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/Frameworks/Laravel/Test/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/home/laradock/.nvm/versions/node/v10.4.1/bin/node" "/var/www/Frameworks/Laravel/Test/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/Frameworks/Laravel/Test/node_modules/node-sass
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-13T18_48_36_539Z-debug.log

```

**Comment by spyridonas** [comment]
Try to access the workspace by doing "docker-compose exec --user=laradock workspace bash"

**Comment by alcir-junior-caju** [comment]
I had tried it that way, but the same error persists.

Today I access via ssh, and still can not resolve.

**Comment by spyridonas** [comment]
Try to ommit the --user=laradock . If you do that you ssh as root in your box
________________________________
Από: Alcir Junior <notifications@github.com>
Στάλθηκε: Παρασκευή, 15 Ιουνίου 2018 2:05 μμ
Προς: laradock/laradock
Κοιν.: Spyros Sakellaropoulos; Comment
Θέμα: Re: [laradock/laradock] Error npm install (#1609)


I had tried it that way, but the same error persists.

Today I access via ssh, and still can not resolve.

**Comment by alcir-junior-caju** [comment]
I already access via root see:

ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 -i workspace/insecure_id_rsa root@localhost

**Comment by alcir-junior-caju** [comment]
After much research I found a solution, I do not know if the best one is working.

Installing and configuring python 2.7:
`apt-get update -yqq && apt-get install -y python2.7
npm config set python /usr/bin/python2.7`

Solving the permissions problem:
`npm config set user 0
npm config set unsafe-perm true`

**Comment by jeff-h** [comment]
@alcir-junior-caju thanks for posting your followup — it got me up and running after a very frustrating hour or so, fighting `npm update` access denied errors.

Of your two commands, I only needed to run `npm config set user 0`; in effect I believe this tells npm to run as root (uid 0), rather than as laradock (uid 1000) which it was prior.

However, I believe it's best practice NOT to run `npm` as root. Switching to using root for something is most often just a quick way to bypass a permissions config error, IMO.

**So my question is:**

Why does the laradock user fail with `EACCES: permission denied, mkdir` errors when writing to some directories inside `node_modules`? I mean — it created `node_modules` in the first place so clearly has write permissions there?!

**Comment by wietsewarendorff** [comment]
Same set of permissions problem here, and ```npm config set user 0``` also did the trick for me.

**Comment by charlesBochet** [comment]
Hope it helps: 
http://www.compulsivecoders.com/tech/laradock-how-to-fix-permission-denied-issue/

**Comment by bsdnomad** [comment]
WORKSPACE_INSTALL_PYTHON=true does the magic, just rebuild workspace

**Comment by lennon-mudenda** [comment]
Glad to have found this thread even after two days of hair pulling and dreading the daily scrum standup meeting. Its threads like this that make it so much worth it to be among the developer community. Much thanks guys keep up the spirit of sharing and having each other's back.
