### ISSUE TITLE
Can i use Containers by other VM to boostrap installation of that container?

### ISSUE THREAD

**Issue by midascodebreaker** [LaraDock/laradock#161]
the only concern im facing right now is, 

lets say i provision another docker-machine

when i do docker-compose up -d list of container i want...

it is fetching all fresh ....

i hope there can be a way to cache all container

then when you provision just choose the cache container...

coz as of now , in my experience , when i create a new docker machine

it will slowly download all dependencies again...

:( 

Any work around on this

**Comment by philtrep** [comment]
@midascodebreaker I'm closing this because I don't think this is an issue that's particular to this project. That being said, I suggest taking a look at http://blog.runnable.com/post/145362675491/distributing-docker-cache-across-hosts .

**Comment by g0ld3lux** [comment]
awesome ill check into it thanks
