### ISSUE TITLE
workspace base image not found

### ISSUE THREAD

**Issue by lx-berlin** [laradock/laradock#1616]
### Info:
- Docker version: 17.12.1-ce, build 7390fc6
- Laradock commit: 5016e88515a6ea2ee61153aa43b8af4c8e418b58
- System info: Linux 
- System info disto/version: Ubuntu18.04 

### Issue:
docker-compose build workspace cant find the base image

### Reproduce:
`
docker-compose build workspace
Building workspace
Step 1/164 : ARG PHP_VERSION=${PHP_VERSION}
 ---> 
Step 2/164 : FROM laradock/workspace:2.2-${PHP_VERSION}
ERROR: Service 'workspace' failed to build: manifest for laradock/workspace:2.2-71 not found
`

**Comment by wangjstu** [comment]
try update laradock to lastest And update Docker to lastest

**Comment by bestlong** [comment]
@lx-berlin 
check .env again
`PHP_VERSION=7.1` not 71

**Comment by lx-berlin** [comment]
thanks @bestlong 
That was the problem.
:laughing:
