### ISSUE TITLE
mongodb.so issu... hot wired in php.ini

### ISSUE THREAD

**Issue by midascodebreaker** [LaraDock/laradock#162]
Im receiving this warning when i type php -v 
or php artisan or any php commmand...
```PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mongodb.so' - /usr/lib/php/20151012/mongodb.so: cannot open shared object file: No such file or directory in Unknown on line 0```

i fixed it by commenting out mongodo extension in php.ini

it work fine , but when i do docker-compose stop or down

then do up again, the image of that php.ini is still at that state...

how can i change that image state?

its kinda awkward fixing it everynow and then

**Comment by emanuellarini** [comment]
Same problem here

**Comment by davidavz** [comment]
Same.
I commented it in php.ini for the moment.

**Comment by graymic** [comment]
The issue is definitely related to the workspace - PHP 7 - cli install. I've managed to get workspace playing nicely with mongo, will test further on my end and report.

**Comment by kayrules** [comment]
Yes the warning goes away if I commented it in php.ini, but when the driver is really needed, It will show us FatalThrowableError error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'MongoDB\Driver\Manager' not found  
```

The fix from [https://derickrethans.nl/undefined-symbol.html](url) says that we need to load the mongodb.so after JSON extension shared object is loaded. 

So creating mongodb.ini in mods-available and symbolic-linked it with priority 30 fixed the error.

```
; configuration for php mongodb module
; priority=30
extension=mongodb.so
```
`ln -s /etc/php/7.0/mods-available/mongodb.ini /etc/php/7.0/cli/conf.d/30-mongodb.ini`
