### ISSUE TITLE
Add my SSH KEY to 'php-fpm' docker.

### ISSUE THREAD

**Issue by vlauciani** [laradock/laradock#1620]
Dear all

I've a simple **Laravel 5.6** project that expose a lot of API; every API, execute a simple `ssh` command on remote host. Something like this:
`ssh my_user@my_host.int.com uptime`

the output will be reported to user.

To do that I need to `add` the **PRIVATE SSH KEY** to `php-fpm` docker build by 'laradock'; how I can do that? the `tty` is enabled only for `workspace` docker that is not the host that perform the connection to remote host by ssh.

Thank you,

**Comment by vlauciani** [comment]
Ok, found a solution.

`php-fpm` docker share the `/var/www` with `workspace` docker and the user `www-data` is user that execute the command. Then:
```
$ docker-compose exec --user=laradock workspace bash
$ mkdir .ssh
$ chmod 700 .ssh
$ echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa
```

the user `laradock` under `workspace` docker is the user `www-data` under `php-fpm`.

**Comment by godbout** [comment]
@vlauciani I'm having the same problem, but I can't follow what you're doing. Any chance you explain a bit more? I'm using a different laradock stack per project.

**Comment by vlauciani** [comment]
Hi @godbout 

I solved by installing in the `php-fpm` and `workspace` container, the `sshpass` software:
```
docker-compose exec -T php-fpm bash -c 'apt-get update -yqq && apt-get install -yqq sshpass'
docker-compose exec -T workspace bash -c 'apt-get update -yqq && apt-get install -yqq sshpass'
```

after that, in my Laravel `Model` I've used this command:
```
$command = "sshpass -p '<password>' ssh -o StrictHostKeyChecking=no <user>@<host> './myScript.sh'";
$process = new Process($command);
$process->run();
```

with `sshpass` the **PRIVATE SSH KEY** is not used.

**NOTE:** if you destroy the containers (`docker-compose down`) you must re-install `sshpass` again on a new containers (`docker-compose up -d`).

@vlauciani

**Comment by godbout** [comment]
@vlauciani thank you for the quick and detailed answer! Deeply appreciated. I thought you figured out how to deal with the private keys though. I'll have a look at sshpass. Maybe I can use it in dev and keys in prod. You can run envoy rather than a script as an arg to sshpass?

**Comment by godbout** [comment]
got it working. not sure exactly yet if all my steps are necessary, but i've created a `/home/www-data` folder with the root ssh keys. I've also made a few changes to allow the `www-data` user to ssh, and i had to create the ssh folder and keys in `/var/www/` in the php-fpm container. hope this helps!

**Comment by godbout** [comment]
started from clean builds, it appears that the only thing to do is to install `ssh` on the `php-fpm` container, and to create the `.ssh` folder in `/var/www/` with the key and rights. then it works! will ask if a PR is ok to add ssh to php-fpm.
