### ISSUE TITLE
ERROR: Service 'workspace' failed to build

### ISSUE THREAD

**Issue by vinwang** [laradock/laradock#1621]
### Info:
- Docker version (`$ docker --version`): 17.09.0-ce
- Laradock commit (`$ git rev-parse HEAD`): master
- System info (Mac, PC, Linux): Mac
- System info disto/version: 

W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' is no longer signed.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock' returned a non-zero code: 100

How to solve this problem ？

**Comment by vinwang** [comment]
I try it

git checkout -b v6.0.1 v6.0.1
cp env-example .env

解决

**Comment by ikingye** [comment]
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl -q install -o -f redis &&     echo "extension=redis.so" >> /etc/php/${PHP_VERSION}/mods-available/redis.ini &&     phpenmod redis ;fi' returned a non-zero code: 1

**Comment by weedsks** [comment]
I also get it, can master fixed it?

**Comment by vinwang** [comment]
@weedsks I have no solution here
