### ISSUE TITLE
SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2' : file not found

### ISSUE THREAD

**Issue by samoldenburg** [laradock/laradock#1622]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce
- Laradock commit (`$ git rev-parse HEAD`): 21d203da739c9292a9b2543f14aa2f1522538ce8
- System info (Mac, PC, Linux):  PC
- System info disto/version: Win 10 pro

### Issue:
When changing WORKBENCH_INSTAL_MSSQL and PHPFPM_INSTALL_MSSQL config and rebuilding containers, MSSQL still appears to not be working. The error message

```SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2' : file not found (SQL: SHOW TABLES)```

Is not overly useful - that file exists in the PHP-FPM container but is not working for some reason.

php.ini has extension=php_pdo_odbc.dll uncommented.

Using php 7.2.
_____

### Expected behavior:
Expect valid response from SQL Server db.
_____

### Reproduce:
Unsure if specific to 7.2 or if requires a specific combination of containers. I've been bringing up laradock as such:

```$ docker-compose up -d nginx mysql mssql php-worker workspace```
_____

**Comment by samoldenburg** [comment]
A few things I found from similar discussions in other packages

Running the following in the php-fpm container gets me at least started for now.

```
$ apt-get update
$ apt-get -y install wget
$ apt-get -y install dialog
$ wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_amd64.deb
$ dpkg -i libssl1.0.0_1.0.1t-1+deb8u8_amd64.deb
```

**Comment by antonyharfield** [comment]
I can confirm the problem. It appears that libmsodbcsql is particular about wanting lib1.0.0 installed. On php-fpm we have 1.1 and 1.0.2 only: 

```shell
root@effadf3a9b03:/var/www# ldconfig -p | grep libssl 
	libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
	libssl.so.1.0.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
```

I suspect that workspace is ok, as it has 1.0.0:

```shell
root@13b47c79e61a:/var/www# ldconfig -p | grep libssl
	libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
	libssl.so.1.0.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.1.0.0
	libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so
```
