### ISSUE TITLE
Access mariadb from host

### ISSUE THREAD

**Issue by gamevnlc** [laradock/laradock#1623]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 5016e88515a6ea2ee61153aa43b8af4c8e418b58
- System info (Mac, PC, Linux):  PC
- System info disto/version: Windows 10 64bit

### Issue:
Change access port from `3306` to `3307` can't connect from host
![image](https://user-images.githubusercontent.com/2215185/41775925-6ccca0e0-7658-11e8-9076-f46aa955133b.png)
_____

### Expected behavior:
Should connect without error
_____

### Reproduce:
Change access port of mariadb in `docker-compose.yaml` file 
![image](https://user-images.githubusercontent.com/2215185/41776035-cfe5574e-7658-11e8-92b3-b4609faf476f.png)

_____

### Relevant Code:

 mariadb:
      build: ./mariadb
      volumes:
        - ${DATA_SAVE_PATH}/mariadb:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3307"
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend

**Comment by bestlong** [comment]
only need update .env
MARIADB_PORT=3306
to
MARIADB_PORT=3307

**Comment by gamevnlc** [comment]
it worked thanks
