### ISSUE TITLE
Build fails on php-fpm

### ISSUE THREAD

**Issue by mquellhorst** [laradock/laradock#1624]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 154249a08f59197703649245461d30d51789f94b
- System info (Mac, PC, Linux): Mac 
- System info disto/version: macOS High Sierra Version 10.13.5

### Issue:
Running `docker-compose up -d nginx mariadb workspace` fails on php-fpm.
The following error occurs:

Digest: sha256:eec0f2bc08e949ebb6a5dc0b118e8f9409a9198a830db202778baadfe1736ecd
Status: Downloaded newer image for laradock/php-fpm:2.2-7.2
 ---> eb15f92a08af
Step 3/72 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
ERROR: Service 'php-fpm' failed to build: error creating overlay mount to /var/lib/docker/overlay2/25b85177dd62dd6df83785e8ec575310f7c98fe892c9ea248c7ff963e72841fc-init/merged: no such file or directory

### Expected behavior:
The expected behavious is that the images are build and the environments run.

### Reproduce:
See issue

Hopefully this is enough information and someone can help fix this.
Thanks in advance!

**Comment by bestlong** [comment]
rebuild images with no cache option:
```
docker-compose down
docker-compose build --no-cache php-fpm nginx mariadb workspace
docker-compose up -d nginx mariadb
```

**Comment by mquellhorst** [comment]
@bestlong This does not seem to help. I still get the same error. Any other ideas?

**Comment by mquellhorst** [comment]
I just found the solution.

Apparently it's a thing with Docker on mac.

[https://github.com/docker/for-mac/issues/1396](url)

**Comment by bestlong** [comment]
@mquellhorst 
maybe hard disk free space not enough.
