### ISSUE TITLE
Cannot start Nginx container

### ISSUE THREAD

**Issue by silvioiannone** [laradock/laradock#1627]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 154249a08f59197703649245461d30d51789f94b
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 Pro with WSL

### Issue:

Cannot start the Nginx container.

This is the error I'm receiving:

>    The POSTGRES_ENTRYPOINT_INITDB variable is not set. Defaulting to a blank string.
>    laradock_workspace_1 is up-to-date
>    laradock_php-fpm_1 is up-to-date
>    Starting laradock_nginx_1 ... done
>    Attaching to laradock_nginx_1
>    nginx_1                | nginx: [emerg] open() "/var/log/nginx/error.log" failed (2: No such file or directory)
>    laradock_nginx_1 exited with code 1
_____

### Expected behavior:

Nginx container should start as normal.
_____

### Reproduce:

1. Clone Laradock using git in WSL
2. Run `docker-compose up -d nginx mysql redis workspace`.

**Comment by silvioiannone** [comment]
Sorry, but that didn't solve the issue.

I removed all the containers and all the images but the issue presented itself again.

**Comment by silvioiannone** [comment]
Sorry, I don't have access anymore to the machine where this issue was encountered.

**Comment by kohlerdominik** [comment]
I have the same error.
@bestlong there is no more output in logs than
`nginx_1 | nginx: [emerg] open() "/var/log/nginx/error.log" failed (2: No such file or directory)`

However,  `nginx -t` in the container tells me:
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] open() "/var/log/nginx/error.log" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

so i tried different steps to reproduce, and my conclusion is:
- If git clone is executed in [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), this happens
- If git clone is executed in _git bash for windows_, all is fine.

The interessting thing, it's only nginx that fails, all other of my containers (php-fpm, workspace, pgadmin, postgres, redis) worked fine.

Ideas to fix this are welcome, i'll try it out. For now, i pulled laradock with Windows and it's working.

**Comment by kohlerdominik** [comment]
Current workaround for this: Clone with [git for windows](https://git-scm.com/download/win). You need to have installed git on your Windows host. All other works can then be done in WSL.

Change to repo directory
```
cd /your/repo/dir
```

Start Windows command line
```
cmd.exe
```
Fix line endings, if you want to work with LF (unix line ending)
```
git config --global core.autocrlf false
git config --global core.eol lf
```

Then, clone your repo
```
git clone https://github.com/Laradock/laradock.git
```
or
```
git clone --recurse-submodules https://bitbucket.org/you/your-repo.git
```

Finally, exit cmd and you can work on as usual
```
exit
```

**Comment by kohlerdominik** [comment]
Update on this:

It seems like clone-directory must be created on windows (for example in cmd.exe), otherwise nginx fails at start with this error. I have no time for further testing right now, but i will catch up when i find some time.

**Comment by DenzoNL** [comment]
@kohlerdominik I've tried your solution (a few times actually), but I can't get it to work unfortunately. I've tried it with and without fully resetting Docker.

Do you have any other ideas I could try?

**Comment by kohlerdominik** [comment]
@DenzoNL  I'm still not sure, why exactly this error occurs. I suspect some path problems right now. 

However, on my environment, it works well this way. Did you try to work with PowerShell/cmd only? Clone (in directory-path completely created in windows), and `docker-compose up -d` in PowerShell worked always well for me.

Maybe one thing you want to try, if you didn’t do already, is to set host path of windows drives to `/`. Without that entry, docker had issues to determine correct path for me. Simple open `/etc/wsl.conf` (in WSL-console) with a text editor, and make sure, this entry matches your config:
```
[automount]
root = / 
```
Default entry is `root = /mnt/`.

**Comment by DenzoNL** [comment]
@kohlerdominik I have been working with the latter solution already and I just tried it with just PowerShell, no dice however. However, the ```wsl.conf``` I used from a tutorial was this:

```ini
[automount]
root = /
options = "metadata"
```
Do you reckon that last option might be the issue here?

Also, I'm using the Ubuntu 18.04 from the Windows Store, if that matters anything.

**Comment by samoldenburg** [comment]
@DenzoNL Did you ever get a solution? I have the same error as you, also running Ubuntu 18.04 under WSL.

**Comment by mean-cj** [comment]
@kohlerdominik your solution have been work
install git on windows and git clone on cmd.

**Comment by Yiidiir** [comment]
@kohlerdominik Thanks for the helpful explanation! Do you have a reference saying it's safe to continue work on WSL after clone?

**Comment by kohlerdominik** [comment]
@Yiidiir Yes absolutely. I worked like this for months now.

**Comment by TatsuyaShimizu** [comment]
I got this error because `fsutil file setCaseSensitiveInfo enable` was set to laradock's parent folder. The error disappeared after changing to disable. (windows10)
