### ISSUE TITLE
Using Mongodb

### ISSUE THREAD

**Issue by graymic** [LaraDock/laradock#163]
It seems that the default Dockerfile doesn't seem to like to play with jenssegers/mongodb as it throws a bunch of dependency errors up around missing extensions in php. Is there a way of getting this to work?

It seems to be solely related to the workspace, as mongodb's extension is fine on the php-fpm container. I've had to run composer require jenssegers/mongodb --ignore-platform-reqs, as an example... just to get the package to play fairly with the php-fpm container's extension, which I know meets the criteria.

**Comment by midascodebreaker** [comment]
the only thing i did to resolve it , is commenting out mongo db extension, coz im not even using mongo db... but even when i try to docker-compose up mongo , it still has that issue ...

**Comment by Mahmoudz** [comment]
1. Upgrade your LaraDock `git pull origin master`. 
_(LaraDock v4 works only with Docker for Mac/Windows. If you want to keep using LaraDock toolbox (VM) use LaraDock v3)._
2. Rebuild your containers `docker-compose build --no-cache` (This might wipe your Data container)
3. Try again.. best of luck :)
