### ISSUE TITLE
Project folder in workspace is gone

### ISSUE THREAD

**Issue by ghost** [laradock/laradock#1657]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce
- Laradock commit (`$ git rev-parse HEAD`): 1d9cbd7c75a481cd86c23912841092b0aeb70890
- System info (Mac, PC, Linux): Windows 10 Pro
- System info disto/version: 1803

### Issue:
I'm new to Laradock. This morning, when I executed this command `docker-compose exec workspace bash`. I still had my project folder in the container. At lunchtime I got the latest update of Windows 10 and the result was I had to restart my computer. After the restart I noticed that I haven't anymore project folder in the container. 

How can I get back my project folder, because in Windows itself he still exists?

**Comment by eleftrik** [comment]
Some problem here. At the moment, I can't find any workaround.

**Comment by eleftrik** [comment]
Maybe it's a duplicate of https://github.com/laradock/laradock/issues/1290

**Comment by eleftrik** [comment]
Tried again on a fresh Laradock install, but I can't see project files in `/var/www`.
Noone experiencing this problem?
Thanks

**Comment by amayer5125** [comment]
Is your laradock folder inside your project folder on the host machine?

**Comment by ForzaSFerrari** [comment]
@amayer5125 It's outside. (multiple projects)

**Comment by amayer5125** [comment]
I have never set up laradock like that. Did you follow the directions [here](http://laradock.io/#B)?

**Comment by ForzaSFerrari** [comment]
yes i did that

**Comment by amayer5125** [comment]
If you start the containers without the `-d` flag do you get any helpful output? `docker-compose up workspace`

**Comment by eleftrik** [comment]
@amayer5125 Yes, in my case Laradock folder is a subfolder (`.docker`) of my project folder.

I solved my issue thanx to https://github.com/laradock/laradock/issues/1290#issuecomment-405890996
Resetting Docker Shared Drivers fixed the problem.
I have the same setup (subfolder) with many projects; on Mac OS, never had any problem, so I guess it's an issue related to Docker sharing in Windows.

**Comment by xzs1994** [comment]
@eleftrik hi, do you know how to fix the problem on docker-toolbox, i tried all my time but noting. thx~
