### ISSUE TITLE
mysql build error

### ISSUE THREAD

**Issue by LaJun** [laradock/laradock#1659]
### Info:
- Docker version   1.12.3
- Docker-compose version 1.8.1
- System info Win10

### Issue:

Step 1 : ARG MYSQL_VERSION=latest
ERROR: Service 'mysql' failed to build: Please provide a source image with `from` prior to commit

How to deal it

**Comment by bestlong** [comment]
@LaJun 
Maybe docker repository probleam, you can try pull image use:
`docker pull mysql:latest`

if download success then build laradock again.

**Comment by LaJun** [comment]
I follow， first i pull  mysql:latest then compose up ,still exist this error ;
if i remove Arg in mysql dockerfile then make this version argument to be latest, another error turns up
like below

Removing intermediate container 00ab5e91049c
ERROR: Service 'mysql' failed to build: One or more build-args [MYSQL_VERSION] were not consumed, failing build.

**Comment by LaJun** [comment]
@bestlong when i use the deepin linux system to compose up, it works well ,why?

**Comment by bestlong** [comment]
Hi @LaJun 
docker-compose load .env then base docker-compose.yml service `args` config, transfer specified variables to Dockerfile ARG.

If you remove ARG MYSQL_VERSION in mysql/Dockerfile then you also need to remove docker-compose.yml mysql service args: - MYSQL_VERSION=${MYSQL_VERSION}

**Comment by thavoo** [comment]
my error: 

PS C:\Users\thavoo\webapp\laradock> docker-compose up -d nginx mysql
Building mysql
Step 1/9 : ARG MYSQL_VERSION=latest
Step 2/9 : FROM mysql:${MYSQL_VERSION}
latest: Pulling from library/mysql
ERROR: Service 'mysql' failed to build: no matching manifest for unknown in the manifest list entries

**Comment by vladyslavstartsev** [comment]
@thavoo you're using windows that's their issue try https://github.com/docker/for-win/issues/1100
