### ISSUE TITLE
No releases available for package "pecl.php.net/redis",cant get the  redis pecl

### ISSUE THREAD

**Issue by LaJun** [laradock/laradock#1661]
### Info:
- Docker version (18.03.1): 
- System info (deepin15.6 Linux): 
### Issue:

No releases available for package "pecl.php.net/redis"
run `docker-compose up -d apache2  mysql redis  mongo rabbitmq memcached elasticsearch jenkins kibana workspace`
```shell

No releases available for package "pecl.php.net/redis"
install failed
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl -q install -o -f redis &&     echo "extension=redis.so" >> /etc/php/${PHP_VERSION}/mods-available/redis.ini &&     phpenmod redis ;fi' returned a non-zero code: 1

```

**Comment by bestlong** [comment]
Hi @LaJun 
If you are in China
I guess it should be a network problem.

**Comment by LaJun** [comment]
hi，@bestlong its should be network problem，i try install Again，successful，but when curl localhost，not found error，i set the param apppath  “../wwwroot”then add a index.html file to this path，still this error，nginx configure wrong or other problems？but nginx configure never changed

**Comment by liyuze** [comment]
1.) download the extension from http://pecl.php.net/packages.php

2.) there you get an .tgz file

3.) install the file:

edit file: `php-fpm/Dockerfile`

```
RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    # Install Php Redis Extension
    printf "\n" | pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis \
;fi
```

replace to

```
RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    # Install Php Redis Extension
    # printf "\n" | pecl install -o -f redis \
    printf "\n" | curl 'http://pecl.php.net/get/redis-4.1.1.tgz' -o redis-4.1.1.tgz \
    && pecl install redis-4.1.1.tgz \
    &&  rm -rf redis-4.1.1.tgz \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis \
;fi
```

happy to rebuild

**Comment by Irving-yang** [comment]
> 1.) download the extension from http://pecl.php.net/packages.php
> 
> 2.) there you get an .tgz file
> 
> 3.) install the file:
> 
> edit file: `php-fpm/Dockerfile`
> 
> ```
> RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
>     # Install Php Redis Extension
>     printf "\n" | pecl install -o -f redis \
>     &&  rm -rf /tmp/pear \
>     &&  docker-php-ext-enable redis \
> ;fi
> ```
> replace to
> 
> ```
> RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
>     # Install Php Redis Extension
>     # printf "\n" | pecl install -o -f redis \
>     printf "\n" | curl 'http://pecl.php.net/get/redis-4.1.1.tgz' -o redis-4.1.1.tgz \
>     && pecl install redis-4.1.1.tgz \
>     &&  rm -rf redis-4.1.1.tgz \
>     &&  rm -rf /tmp/pear \
>     &&  docker-php-ext-enable redis \
> ;fi
> ```
> happy to rebuild
have this error:
/bin/sh: 1: docker-php-ext-enable: not found

**Comment by rejidan** [comment]
try using vpn during installation, because in some cases the network can't access pecl.php.net

**Comment by musamamasood** [comment]
Faced the same issue due to network with proxy. Make sure that you should have internet access.

**Comment by kerryj89** [comment]
I ran into the same issue today.

I had to run the following commands: `pear update-channels` and `pecl update-channels` and after that I am able to move past the `No releases available for package "pecl.php.net/redis"` error.

**Comment by dlgombert** [comment]
Just following up with what @kerryj89 said.  It worked perfectly.  I had to add the lines in my php-worker Dockerfile, and I also added them in my php-fpm Dockerfile, because I'm sure it won't hurt anything to have them wherever I'm  potentially using pear or pecl.

**Comment by kilvn** [comment]
it works.
```
printf "\n" | curl 'http://pecl.php.net/get/redis-4.3.0.tgz' -o redis-4.3.0.tgz \
      && pecl install redis-4.3.0.tgz \
      && rm -rf -- redis-4.3.0.tgz \
      && rm -rf /tmp/pear \
      && docker-php-ext-enable redis
```

**Comment by iartist93** [comment]
@kerryj89 I'm confirming that this solution solved my issue too

```
# add these 2 lines before pecl install solved my download/connection issue
RUN pear update-channels
RUN pecl update-channels

RUN pecl install redis xdebug mongodb \
    && docker-php-ext-enable redis xdebug mongodb
```

**Comment by Mahmoudz** [comment]
**What's happening:** `pecl.php.net` failed to serve the Redis package during the build. It's almost always a transient/network issue (common behind a proxy, VPN, or on restricted connections), so the first thing to try is just rebuilding.

**If it keeps failing,** refresh PECL's channel list before the extension installs. Laradock v20+ already does this and retries flaky pecl downloads automatically, so on a recent copy a `git pull` of `master` + rebuild is usually enough. If you're coming from an old version, see the [upgrade guide](https://laradock.io/docs/upgrade-guide).

**On an older copy,** add this above the `pecl install` line in `php-fpm/Dockerfile` (and `workspace/Dockerfile`):

```dockerfile
RUN pear update-channels && pecl update-channels
```

This is the fix a few people confirmed in this thread (thanks kerryj89 and iartist93); current builds bake it in with retry logic.
