### ISSUE TITLE
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by kalwiggins** [laradock/laradock#1668]
### Info:
- Laravel Framework 5.6.26
- MYSQL Server version: 8.0.11 MySQL Community Server - GPL
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

### Issue:
I'm trying to connect my laravel app to mysql for the first time. Here's what I get when I migrate:

$ php artisan migrate
In Connection.php line 664:
  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = goldencabinet and table_name = migrations)

_____

### Expected behavior:
Schema should've been pushed into the database called goldencabinet
_____

### Reproduce:
Every time I run php artisan migrate it does this.
_____

### Relevant Code:
in database.php
    'default' => env('DB_CONNECTION', 'mysql'),
and 
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

in env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=goldencabinet
```

**Comment by knnhcn** [comment]
Have you tried https://github.com/laradock/laradock/issues/1392#issuecomment-368308494 ?

**Comment by knnhcn** [comment]
For me, actually running artisan commands inside the workspace container solved the same problem I had. Check out http://laradock.io/documentation/#run-artisan-commands

**Comment by adriiiprieto** [comment]
alter user 'username'@'localhost' identified with mysql_native_password by 'password'; would fix it.

**Comment by exodus244** [comment]
work for me. [problem with symfony]

**Comment by Jungey** [comment]
adriiprieto,

alter user 'username'@'localhost' identified with mysql_native_password by 'password'; would fix it.

could anybody elaborate this? i mean like where to go and do all this.

**Comment by marcelledi** [comment]
@Jungey You supposed to log in you mysql:

`mysql -u USERNAME -pPASS`

and then run the code above.

Cheers

**Comment by ahsanmster** [comment]
> alter user 'username'@'localhost' identified with mysql_native_password by 'password'; would fix it.

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'user 'root'@'localhost' identified with mysql_native_password 'password'' at line 1

**Comment by idontkillcoyotes** [comment]
> 
> 
> alter user 'username'@'localhost' identified with mysql_native_password by 'password'; would fix it.

Thanks, it worked for me.

Although I also changed the server config from:

> --default-authentication-plugin=caching_sha2_password

to

> --default-authentication-plugin=mysql_native_password

(I changed this directly from MySQL Workbench)

Because the default changed in MySQL ver 8.0.4 according to this: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-4.html#mysqld-8-0-4-security

**Comment by anglesson** [comment]
Try it create a new user on Mysql and add the new user into the file .env

**Comment by ScorpioCoding** [comment]
--> mysql -u root -p
--> alter user 'root'@'localhost' identified with mysql_native_password by 'password'; 

This fixed it for me

**Comment by congfandi** [comment]
@ScorpioCoding  its work for me man.. big thanks to you

**Comment by shivanibenosoft** [comment]
I am using laravel 5.8 and having MAMP server got this error resolved by adding `DB_SOCKET=/Applications/MAMP/tmp/mysql/mysql.sock` in .env file like below

```

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=8889
DB_DATABASE=dbname
DB_USERNAME=root
DB_PASSWORD=root
DB_SOCKET=/Applications/MAMP/tmp/mysql/mysql.sock
```

**Comment by CristianGitUtez** [comment]
@adriiiprieto , me funcionó amigo muchas gracias, pero me gustaría saber que fue lo que pasó.

**Comment by sarojbaskota** [comment]
If you have access to phpmyadmin via root login, then change Password Hashing:

**Comment by renoirtech** [comment]
> alter user 'username'@'localhost' identified with mysql_native_password by 'password'; would fix it.

Thanks, worked!

**Comment by trustidkid** [comment]
alter user 'username'@'localhost' identified with mysql_native_password by 'password'; returns error **You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'by 'password'' at line 1** I changed the password to my user password and user as well.

**Comment by samimiladian** [comment]
> alter user 'username'@'localhost' identified with mysql_native_password by 'password'; would fix it.

ok I did this and now I can connect to MySQL with sequel pro(not sure why didn't work before) BUT when I 'php artisan migrate' it still gives the error, let me just copy the whole thing:
"""
 Illuminate\Database\QueryException

  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = laravelTest and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

      +33 vendor frames
  34  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
"""
Does anybody know what am I doing wrong or anything?
oh by the way:: laravel version 8 --- MySQL version 8 ---- and on mac os version 11.2 (i don't have this problem on my ubuntu 20.4 with the same versions)
