### ISSUE TITLE
php-fpm xlaravel.pool.conf pool name missing, causing php-fpm to fail (on some configs)

### ISSUE THREAD

**Issue by godbout** [laradock/laradock#1669]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 7b1e52fbee4ff7333f30b4a34e6a14e5db6c98ca
- System info (Mac, PC, Linux): macOS High Sierra 10.13.5 (17F77)
- System info disto/version: 10.13.5 (17F77)

### Issue:
I can't start php-fpm, strangely, on my iMac. It starts ok on my MacBook. Both setup are exactly the same, same docker versions etc... The laradock used is my own fork, it includes .env and apache2 sites conf files. Everything is exactly the same, though on the iMac, it fails if there is no pool name in the xlaravel.pool.conf file.

```
php-fpm_1              | [03-Jul-2018 15:10:23] NOTICE: PHP message: PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
php-fpm_1              | [03-Jul-2018 15:10:23] ERROR: [/usr/local/etc/php-fpm.d/xlaravel.pool.conf:1] unknown entry 'user'
php-fpm_1              | [03-Jul-2018 15:10:23] ERROR: Unable to include /usr/local/etc/php-fpm.d/xlaravel.pool.conf from /usr/local/etc/php-fpm.conf at line 1
php-fpm_1              | [03-Jul-2018 15:10:23] ERROR: failed to load configuration file '/usr/local/etc/php-fpm.conf'
php-fpm_1              | [03-Jul-2018 15:10:23] ERROR: FPM initialization failed
```
_____

### Expected behavior:
```
php-fpm_1              | [03-Jul-2018 15:08:25] NOTICE: PHP message: PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
php-fpm_1              | [03-Jul-2018 15:08:25] NOTICE: fpm is running, pid 1
php-fpm_1              | [03-Jul-2018 15:08:25] NOTICE: ready to handle connections
```
_____

### Reproduce:
```
docker-compose up --build php-fpm
```
_____

### Relevant Code:
This is the beginning of the xlaravel.pool.conf file
```
; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
user = www-data
group = www-data

; The address on which to accept FastCGI requests.
```

adding a pool name solves the issue. Although it seems required only on some configs. I don't know what's happening here. Docker version, docker files, everything is the same on both config. One needs the pool name, one doesn't.
```
[poolname]
; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
user = www-data
group = www-data

; The address on which to accept FastCGI requests.
```

**Comment by aledelgo** [comment]
had same problem in past. it's due the fact you are mounting an ENTIRE php config dir on your container so the default WWW pool config file is not read as not available in your mounted dir.
try not mounting the entire config dir but only an additive file, it will be imported in the default www pool config (that already have a name).
