### ISSUE TITLE
Install locales on PHP container

### ISSUE THREAD

**Issue by Mastergalen** [LaraDock/laradock#167]
My Laravel application needs the it_IT.utf8 locale and the en_GB.utf8 locale to generate different time strings in those languages.

How do I install these locales?

When I run `docker exec -it laradock_php-fpm_1` and run:

```
root@603609edcfac:/var/www/laravel# locale -a
C
C.UTF-8
POSIX
```

I'm trying to install the locale by running:

```
root@603609edcfac:/var/www/laravel# locale-gen it_IT.utf8
Generating locales (this might take a while)...
Generation complete.
```

Still, the list of installed locales is the same:
```
root@603609edcfac:/var/www/laravel# locale -a
C
C.UTF-8
POSIX
```

**Comment by davidavz** [comment]
Shouldn't you generate it on the workspace container ? Like [here](https://github.com/LaraDock/laradock/blob/d6329c26b31a67f0dfa767f3f02006098f965e35/workspace/Dockerfile#L6)

**Comment by Mastergalen** [comment]
Thanks, I tried installing the locales in the workspace container as well, but that doesn't appear to work either.

When I'm in the terminal for the workspace container and I run `locales -a`:

```
root@86d85198dc60:/var/www/laravel# locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US
en_US.iso88591
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
it_IT.utf8
POSIX
```

The `it_IT.utf8` and `en_GB.utf8` are installed. However, when I to run the following code in Laravel:

```
$success = setlocale(LC_TIME, 'en_GB.utf8');
dd($success);
```

`false` is printed and the locale fails to get set.

**Comment by davidavz** [comment]
Actually you have to change the ENV parameters in the workspace Dockerfile and rebuild it.

You can't do it into the bash workspace.

**Comment by Mastergalen** [comment]
I also tried editing the workspace `Dockerfile` to run the `locale-gen` commands from there.

```
FROM phusion/baseimage:latest

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

RUN DEBIAN_FRONTEND=noninteractive
RUN locale-gen \
    en_US.UTF-8 \
    en_GB.UTF-8 \
    it_IT.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

# Install "software-properties-common" (for the "add-apt-repository")
RUN apt-get update && apt-get install -y \
    software-properties-common

# Add the "PHP 7" ppa
RUN add-apt-repository -y \
    ppa:ondrej/php

# Install PHP-CLI 7, some PHP extentions and some useful Tools with APT
RUN apt-get update && apt-get install -y --force-yes \
        php7.0-cli \
        php7.0-common \
        php7.0-curl \
        php7.0-json \
        php7.0-xml \
        php7.0-mbstring \
        php7.0-mcrypt \
        php7.0-mysql \
        php7.0-pgsql \
        php7.0-sqlite \
        php7.0-sqlite3 \
        php7.0-zip \
        php7.0-memcached \
        php7.0-gd \
        php7.0-xdebug \
        php-dev \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        sqlite3 \
        libsqlite3-dev \
        git \
        curl \
        vim \
        nano \
        pkg-config

# Clean up, to free some space
RUN apt-get clean

# remove load xdebug extension (only load on phpunit command)
RUN sed -i 's/^/;/g' /etc/php/7.0/cli/conf.d/20-xdebug.ini

# Add bin folder of composer to PATH.
RUN echo "export PATH=${PATH}:/var/www/laravel/vendor/bin" >> ~/.bashrc

# Install Composer
RUN curl -s http://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Load xdebug Zend extension with phpunit command
RUN echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/laravel/vendor/bin/phpunit'" >> ~/.bashrc

# Install mongodb extension
RUN pecl install mongodb
RUN echo "extension=mongodb.so" >> /etc/php/7.0/cli/php.ini

# Install nvm (Node Version Manager)
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash

ENV NVM_DIR=/root/.nvm

# Install stable node
RUN . ~/.nvm/nvm.sh \
    && nvm install stable \
    && nvm use stable \
    && nvm alias stable \
    && npm install -g gulp bower

# Source the bash
RUN . ~/.bashrc

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/laravel

# Install optional software
ARG INSTALL_PRESTISSIMO=false
RUN if [ "$INSTALL_PRESTISSIMO" = true ] ; then \
        composer global require "hirak/prestissimo:^0.3"; \
    fi
```

After running `docker exec -it laradock_workspace_1 bash` and running `locale -a`, the it_IT and en_GB locales are listed as installed. However, PHP still does not recognise those locales as installed when trying to execute `setlocale(LC_TIME, 'en_GB.utf8');`

**Comment by orette** [comment]
The locale needs to be on the container processing the PHP scripts when the call is made to the web server. I think in your case, this is the *php-fpm* container. You can enter the container and run the following code. You will need to restart the container once you have completed this.
    
    apt-get update && \
    apt-get install locales && \
    sed -i 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/# it_IT.UTF-8 UTF-8/it_IT.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

or modify the first **RUN** command in **Dockerfile-70** file from the *php-fpm* folder to the following code and rebuild the container.

## Dockerfile-70
    RUN apt-get update && apt-get install -y \
        libpq-dev \
        libmemcached-dev \
        curl \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        locales \
        --no-install-recommends \
        && rm -r /var/lib/apt/lists/* \
        && sed -i 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen \
        && sed -i 's/# it_IT.UTF-8 UTF-8/it_IT.UTF-8 UTF-8/' /etc/locale.gen \
        && locale-gen

**Comment by Mastergalen** [comment]
Awesome thank you @orette, it's indeed the php-fpm container that needed to have the locales installed on.

I had to however replace the `sed` commands because the `locale.gen` file never contained the line `# it_IT.UTF-8 UTF-8`.

My **RUN** command inside `Dockerfile-70` looks like this now:

```
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    libjpeg-dev \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    locales \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/* \
    && printf 'en_GB.UTF-8 UTF-8\n' >> /etc/locale.gen \
    && printf 'it_IT.UTF-8 UTF-8\n' >> /etc/locale.gen \
    && locale-gen
```

**Comment by itelmenko** [comment]
I think locales need be in laradock out of box

**Comment by BentCoder** [comment]
This is mine if it helps anyone any way.

```
FROM php:7.2-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
 && sed -i 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/g' /etc/locale.gen \
 && ln -s /etc/locale.alias /usr/share/locale/locale.alias \
 && locale-gen en_GB.UTF-8

ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8
```

```
$ docker exec app_php_1 locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```

```
$ docker exec app_php_1 printenv
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_ALL=en_GB.UTF-8
```

**Comment by marcelogarbin** [comment]
@BentCoder @Mastergalen which file did you modify for new locales? 

This is a listing of files in php-fpm (I do not know what half of these files are, what is laravel.ini for?):
![image](https://user-images.githubusercontent.com/9335588/41126626-8aba00c4-6a7e-11e8-955c-bf1b197ab648.png)

**Comment by marcelogarbin** [comment]
any news?

**Comment by BentCoder** [comment]
@marcelogarbin As you can see above in my example only `/etc/locale.gen` is being modified. Nothing is modified in php-fpm folder because it has nothing to do with PHP. It is more of a server thing. Read [this](http://www.inanzzz.com/index.php/post/2umd/setting-up-encoding-locale-timezone-and-ntp-server-on-linux-to-synchronise-the-time) if you wish.

**Comment by marcelogarbin** [comment]
@BentCoder Hello, I do not have much experience with Docker, so I am not sure how to do this. I tried several ways, but without success.

I tried to use what you posted, but where do I put this code? Do you have any specific files? 

I'm using the latest version of Laradock.

**Comment by napogf** [comment]
Thanks to other comments, my solution is to copy from my ubuntu host /etc/local.gen

 file to ./laradock/php-fpm/ directory, then add to php-fpm/Dockerfile :

```
COPY ./locale.gen /etc/locale.gen

RUN apt-get install -y locales \
    && ln -sfn /etc/locale.alias /usr/share/locale/locale.alias \
    && locale-gen
```

local.gen appear as a list of locales settings decomment locale that you want the build will generate 

```
 # en_SG.UTF-8 UTF-8
 # en_US ISO-8859-1
 # en_US.ISO-8859-15 ISO-8859-15
 en_US.UTF-8 UTF-8
 # en_ZA ISO-8859-1
 # en_ZA.UTF-8 UTF-8
 # en_ZM UTF-8
 # en_ZW ISO-8859-1
 # en_ZW.UTF-8 UTF-8
 # eo UTF-8
 # eo_US.UTF-8 UTF-8
 # es_AR ISO-8859-1
.....
# is_IS.UTF-8 UTF-8
# it_CH ISO-8859-1
# it_CH.UTF-8 UTF-8
# it_IT ISO-8859-1
it_IT.UTF-8 UTF-8

```
in this example  en_US.UTF-8 UTF-8 and it_IT.UTF-8 UTF-8 wil be installed when you rebuild php-fpm container. 
For workspace container the same solution can be applied

**Comment by mk-relax** [comment]
For reference, this seems to be supported out of the box now, by configuring `PHP_FPM_INSTALL_ADDITIONAL_LOCALES=true` and `PHP_FPM_ADDITIONAL_LOCALES` in .env. 
See #1976.
