### ISSUE TITLE
The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu xenial Release' does not have a Release file.

### ISSUE THREAD

**Issue by nghminh163** [laradock/laradock#1690]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

W: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch https://10.15.213.1/connect/Access?AgentCode=000&url=aHR0cDovL3BwYS5sYXVuY2hwYWQubmV0L29uZHJlai9waHAvdWJ1bnR1L2Rpc3RzL3hlbmlhbC9tYWluL2JpbmFyeS1hbWQ2NC9QYWNrYWdlcw==&params=AkuD6YmBcYmpcYnBkXGJgZHZo0trK+mJqZmBwbGZsbm5  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead.
_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by amayer5125** [comment]
Which container were you trying to run when you got this error?
