### ISSUE TITLE
Elasticsearch Container Stopped

### ISSUE THREAD

**Issue by dendihandian** [laradock/laradock#1699]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce, build 9ee9f40 
- Laradock commit (`$ git rev-parse HEAD`):  85c57a0b6fa3af2358e524010b95970ff9677a1b / update postgresql init db example file (#1689)
- System info (Mac, PC, Linux): Linux 
- System info disto/version: Ubuntu 18.04 LTS

### Issue:

Elasticsearch stopped after running a few seconds. Info: `laradock_elasticsearch_1      /usr/local/bin/docker-entr ...   Exit 78`

### Expected behavior:

Elasticsearch running and I can connect to it

### Reproduce:

Just do `sudo docker-compose up -d elasticsearch` and `sudo docker-compose ps` after a few minutes and see if it is still running or not.

### Relevant Code:

```
// place a code sample here
```

**Comment by bestlong** [comment]
@dendihandian 
try `docker-compose logs elasticsearch` to check error info.

**Comment by dendihandian** [comment]
thanks @bestlong , it helped me solved my problem.

I figured out why it's keep stopping everytime I `docker-compose up -d elasticsearch`. The log says `[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`. So I change the `vm.max_map_count` value to 262144 with this command `sudo sysctl -w vm.max_map_count=262144`.

**Comment by lionslair** [comment]
> thanks @bestlong , it helped me solved my problem.
> 
> I figured out why it's keep stopping everytime I `docker-compose up -d elasticsearch`. The log says `[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`. So I change the `vm.max_map_count` value to 262144 with this command in my local machine: `sudo sysctl -w vm.max_map_count=262144`.
> 
> The `vm.max_map_count` will be reseted to default value after you reboot your machine.

How do you set the value 
`sudo sysctl -w vm.max_map_count=262144`
in the docker build?

**Comment by DrudeskDevelopers** [comment]
Run sudo sysctl -w vm.max_map_count = 262144 in the terminal, not in the docker

**Comment by IgorMashev** [comment]
Run sudo sysctl -w vm.max_map_count = 262144 in the terminal, not in the docker

**Comment by ghassen98** [comment]
have the same issue and was resolved it with command 
`sudo sysctl -w vm.max_map_count = 262144 `
thanks

**Comment by mithiyamoiz** [comment]
have the same issue and was resolved it with command
sudo sysctl -w vm.max_map_count = 262144
thanks

**Comment by Robiussani152** [comment]
I am experiencing the same issue on my Mac M2, which runs on MacOS 14.0.

> sudo sysctl -w vm.max_map_count = 262144

I am seeing an error message that says `sysctl: unknown oid 'vm.max_map_count'`.

**Comment by calebjacobo** [comment]
This is necessary on Mac. Create a privileged container and set the docker VM max_map_count from there, then exit that container.

```
docker run -it --rm --privileged --pid=host justincormack/nsenter1

sysctl -w vm.max_map_count=262144
```
