### ISSUE TITLE
Cannot link to a non running container

### ISSUE THREAD

**Issue by Leuloch** [LaraDock/laradock#17]
I followed the tutorial to installing Laradock on Ubuntu 15.10.

When I run the command `docker-compose up -d` I get the following error on terminal:
`Starting data`
`Starting redis`
`Starting mysql`
`Starting 3f9705a53bbd_php-nginx`
`ERROR: Cannot link to a non running container: /9249350508fd_redis AS /php-nginx/redis
`
I'm new to docker, so I can't figure out if this issue is a bug or if I made a mistake.

And Thanks for this repo!

**Comment by Mahmoudz** [comment]
It seems like the `php-nginx/redis` container was not downloaded or installed correctly, try to do this:

1. first see all images `docker images`
2. then delete the `3f9705a53bbd_php-nginx` image with `docker rmi 3f9705a53bbd_php-nginx`
3. lastly run `docker-compose up` again, this will download the missed images, which in our case is `php-nginx/redis`

Let me know of that fixes it.

**Comment by Leuloch** [comment]
Oh, thanks @Mahmoudz , it worked!!!

Because of the conflict on port 80 (from my apache2 service) the `docker-compose up` failed and after turn off my apache it was really necessary to delete the docker image.

So, after deleting the images with the command:

`docker rmi -f <container ID>`

I run again the command:

`docker-compose up`

:+1:

**Comment by cvitbootcamp** [comment]
I have followed the readme and when I invoke:
$ docker-compose up -d apache2 mongo php-fpm mariadb

Removing laradock_apache2_1
Starting laradock_volumes_data_1
Starting laradock_volumes_source_1
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
Recreating c419d01e5058_c419d01e5058_laradock_apache2_1
laradock_mongo_1 is up-to-date
Recreating laradock_mariadb_1

ERROR: for apache2  Cannot start service apache2: oci runtime error: no such file or directory
ERROR: Encountered errors while bringing up the project.

I can't figure out what's' going on, I already changed the port  to an unused one.
