### ISSUE TITLE
ERROR: for volumes_data  Mounts denied: er -> Preferences.

### ISSUE THREAD

**Issue by godbout** [LaraDock/laradock#170]
Hi there!

I can't "docker-compose up" if I'm using DBs. I don't have local folders on my macOS machine, for example for mysql, no /var/lib/mysql. With my own images/containers, I create my DVC like this: "docker create -v /var/lib/mysql --name ...".

Is there any way to handle it in the same way with docker-compose? I'm not familiar with it yet. Or is there a way to create /var/lib/mysql on the fly like I do for my other containers, with some options in the docker-compose.yml? Curious.

Thanks!

**Comment by godbout** [comment]
For info:

How I start my containers from my own images:

![docker-run-redhead_sh_ _tm-agenda-generator](https://cloud.githubusercontent.com/assets/121373/17048890/f0df64fe-501b-11e6-9c83-5d810cfed9a9.jpg)

The issue I currently have with docker-compose up:

![bash](https://cloud.githubusercontent.com/assets/121373/17048909/0b56fc5c-501c-11e6-9aa4-c714bbc1fa8e.jpg)

**Comment by ronpeled** [comment]
@godbout So if you want to make it work on a Mac OS X - you may need to create a folder in your home directory: 'var' and modify the docker-compose.yml file to include the '~' in front of the volumes in the database container:
`### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - ~/var/lib/mysql:/var/lib/mysql
            - ~/var/lib/postgres:/var/lib/postgres
            - ~/var/lib/mariadb:/var/lib/mariadb
            - ~/var/lib/memcached:/var/lib/memcached
            - ~/var/lib/redis:/data
            - ~/var/lib/neo4j:/var/lib/neo4j/data
            - ~/var/lib/mongo:/data/db
`

**Comment by godbout** [comment]
Hey @ronpeled thanks for idea. As I don't need to use mysql for now I didn't dig into but yeah, that sure makes sense. When I'll have time I'll check if there's still a way to do like the "docker create" within a docker-compose.yml. Thanks

**Comment by godbout** [comment]
Actually I looked a bit, and it's possible to let the Docker Engine create a container by default with the db data:

````
volumes:
  # Just specify a path and let the Engine create a volume
  - /var/lib/mysql

  # Specify an absolute path mapping
  - /opt/data:/var/lib/mysql

**Comment by Mahmoudz** [comment]
New release of LaraDock was released today (LaraDock v4.*). 
1. Upgrade your LaraDock `git pull origin master`
2. Rebuild your containers `docker-compose build --no-cache` (This might wipe your Data container)
3. Try again.
