### ISSUE TITLE
container setting always restart such as php-fpm.work_space redis,nginx,mysql,

### ISSUE THREAD

**Issue by liminworks** [laradock/laradock#1701]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by ahkui** [comment]
you can try my fork version [https://github.com/ahkui/laradock](laradock)
