### ISSUE TITLE
Phpunit test using a remote php interpreter(from a docker container) returns a connection timed out

### ISSUE THREAD

**Issue by neorganic** [laradock/laradock#1703]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`):  f919979c9ba872da61378f0b46525603d0b5430f
- System info (Mac, PC, Linux):  Linux
- System info disto/version: Ubuntu 18.04 LTS

### Issue:
Having ```connection timed out``` when trying to do a PHPUnit test from PHP-fpm container

I am using different DBs for local and testing environments. The IP of my MySQL container is ```172.20.0.3```  and I don't have any issues running my main app.
_____

### Expected behavior:
Should be able to run my tests
_____

### Reproduce:

https://www.youtube.com/watch?v=I7aGWO6K3Ho <-- should be enough to reproduce it.
_____

### Relevant Code:
phpunit.xml
````
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="true">
    <testsuites>
        <testsuite name="only_fast_tests">
            <directory>./tests/Feature/fast</directory>
        </testsuite>
        <testsuite name="Feature Tests">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>

        <testsuite name="Unit Tests">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="app_testing"/>
    </php>

</phpunit>
````
database.php
````
     'app_testing' => [
            'driver' => 'mysql',
            'host' => env('DB_TESTING_HOST', '172.20.0.3'),  // 172.20.0.3
            'port' => env('DB_PORT', '3306'), // 3306
            'database' => env('DB_TESTING_DATABASE', 'forge'), // app_testing
            'username' => env('DB_USERNAME', 'forge'), // root
            'password' => env('DB_PASSWORD', ''), // secret
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => 'InnoDB'
        ],
````

A sanity check from inside the `PHP-fpm` container:
````
ping mysql
PING mysql (172.20.0.3) 56(84) bytes of data.
64 bytes from laradock_mysql_1.laradock_backend (172.20.0.3): icmp_seq=1 ttl=64 time=0.134 ms
````

````
docker://laradock_php-fpm:latest/php /opt/project/vendor/phpunit/phpunit/phpunit --configuration /opt/project/phpunit.xml /opt/project/tests/Feature/fast --teamcity
PHPUnit 7.1.5 by Sebastian Bergmann and contributors.


Doctrine\DBAL\Driver\PDOException : SQLSTATE[HY000] [2002] Connection timed out
````
P.S. I've using Phpstorm to setup remote PHP-interpreters etc, to run tests.. etc.
P.S.S I've tried the same setup, but just with MySQL being local not in a docker container which worked, but MySQL to be in a container as well (for dev reasons).

**Comment by neorganic** [comment]
Actually turns out was pointing to a bad env variable....

**Comment by lionslair** [comment]
> Actually turns out was pointing to a bad env variable....

I have the host as mysql but I am still having the same issue.

**Comment by ugurdnlr** [comment]
I'm getting this error too.

`Illuminate\Database\QueryException : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known `

when i run tests from phpstorm I'm getting this. But i didn't get this when i run from terminal like `phpunit Tests\ExampleTest`
