### ISSUE TITLE
Setting up Bedrock can't connect to MySQL Connection refused

### ISSUE THREAD

**Issue by abaracedo** [laradock/laradock#1708]
Yesterday I wanted to set up Bedrock using Laradock and I am using MySQL, PHP-FPM, Apache2 and Workspace.

All looks good and I can connect to the DB using a SQL editor but when I access to the URL for the Wordpress site it gives this error:

(HY000/2002): Connection refused and that probably the credentials, the host or the SQL server is wrong.

On the .env file I have this values for MySQL:
```
MYSQL_VERSION=5.7
MYSQL_DATABASE=blog
MYSQL_USER=dev
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=secret
MYSQL_ENTRYPOINT_INITDB=./env/docker/mysql/docker-entrypoint-initdb.d
```

And for Bedrock:
```
DB_NAME=blog
DB_USER=dev
DB_PASSWORD=secret
DB_ROOT_PASSWORD=secret

# Optional variables
DB_HOST="0.0.0.0"
DB_PREFIX=wp_

WP_ENV=development
WP_HOME=local.blog.dev
WP_SITEURL=${WP_HOME}/wp
```

For `DB_HOST` I tried using the port too `"0.0.0.0:3306"`. I Also tried removing the data created by the MySQL container and removing the container and rebuilding it.

**Comment by bestlong** [comment]
If bedrock run in php-fpm container, set bedrock .env file `DB_HOST="mysql"` ("mysql" is service name).

laradock .env file MYSQL_DATABASE is only effect database init stage, use to create first database.
so, if database is exist then use db tool like phpmyadmin or CLI tool to create new database.
or Regenerate database follow below step (will lost all database):
```
docker-compose down
rm -rf ~/.laradock/data/mysql
docker-compose up -d mysql
```

**Comment by joppuyo** [comment]
I'm having this error too with Vanilla WordPress. I can connect with phpmyadmin but trying to access the site gives "Error establishing a database connection".

Here's my `wp-config.php`

```php
define('DB_NAME', 'default');
define('DB_USER', 'root');
define('DB_PASSWORD', 'root');
define('DB_HOST', 'mysql');
```

**Comment by mobinzk** [comment]
I've used mariadb instead of mysql and that fixed the error.
