### ISSUE TITLE
'docker-compose run workspace bash' hangs

### ISSUE THREAD

**Issue by eleftrik** [laradock/laradock#1715]
### Info:
- Docker version (`$ docker --version`): Docker version 18.05.0-ce, build f150324
- Laradock commit (`$ git rev-parse HEAD`): 8624335f61e384163a3f3a2f11f8dbf69f94436f
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 Pro

### Issue:
Cannot connect to workspace container.
After running `docker-compose run workspace bash` the prompt hangs
_____

### Expected behavior:
I should be able to enter the container via bash
_____

### Reproduce:

```
git clone  https://github.com/Laradock/laradock.git
cd laradock
cp env-example .env
docker-compose -d nginx mariadb workspace
docker-compose run workspace bash

```
_____

### Relevant Code:
```
// place a code sample here
```

**Comment by amayer5125** [comment]
You should use `docker-compose exec` not `docker-compose run`.

**Comment by eleftrik** [comment]
@amayer5125 Shame on me, sorry for the confusion.

Now I'm able to enter workspace container with  `winpty docker-compose exec workspace bash` command.
But I cannot see any file/folder inside `/var/www`, as described in https://github.com/laradock/laradock/issues/1657.

Thank you
