### ISSUE TITLE
[Question] Change session timeout value in phpmyadmin container

### ISSUE THREAD

**Issue by vladyslavstartsev** [laradock/laradock#1718]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 21d203da739c9292a9b2543f14aa2f1522538ce8
- System info (Mac, PC, Linux): Linux
- System info disto/version: Linux Mint 18.2 Sonya

### Issue:
_____
I can't change `LoginCookieValidity` value
### Expected behavior:

_____
I can login to the container (`docker-compose exec phpmyadmin sh`) and change `LoginCookieValidity` value

### What I have tried:
_____
Yes, I've googled for it,  and read phpmyadmin (part of it) docs.
1. The `Settings->Features->General->Login cookie validity` doesn't exist 
![image](https://user-images.githubusercontent.com/17382248/42892118-aef9a290-8ab9-11e8-8c84-ead3b0f90990.png)
2.Trying to edit php config file.
------------------------------
The interesting thing is that I've found `config.inc.php` in 2 places inside the container (`docker-compose exec phpmyadmin sh`) - the `/etc/phpmyadmin` and `/www`.
When trying to edit some file (in my case `config.inc.php`) in the  `/etc/phpmyadmin` nothing changes. I mean I've added `var_dump('some random text');die;` in the `\etc\phpmyadmin\config.inc.php` and nothing changed.
When I did the same thing with `/www/index.php` nothing changed.
What I'm doing wrong? 
How do I change session timeout?

**Comment by vladyslavstartsev** [comment]
found installing volumes with `docker-compose` in `phpmyadmin` docs, but still doesn't work.
[Link to the docks](https://github.com/phpmyadmin/phpmyadmin/blob/master/doc/setup.rst#customizing-configuration-file-using-docker-compose)

**Comment by judos** [comment]
Is this somehow related to laradock? 
I tried the same for just a plain phpmyadmin container (nothing to do with laradock) and it also did not change anything. I'll check over the phpmyadmin github to see if I can find out more.

**Comment by vladyslavstartsev** [comment]
@judos sure thing!

**Comment by vladyslavstartsev** [comment]
the problem still occurs

**Comment by Perh0rd** [comment]
@vladyslavstartsev  Did you find a solution? Got same problem here...

**Comment by Perh0rd** [comment]
Solution here : https://anopetia.tinytake.com/tt/NDI1MjU5OF8xMzMxNDgxMw

**Comment by vladyslavstartsev** [comment]
![ezgif-4-8a075716565f](https://user-images.githubusercontent.com/17382248/88805886-63656b00-d1b8-11ea-850d-4f1e6574e1e4.gif)

upload for history reasons (not sure if anopetia.tinytake.com/tt/NDI1MjU5OF8xMzMxNDgxMw will exists for long time)

**Comment by CGYCGY** [comment]
edit **phpmyadmin/Dockerfile** like this also works

![image](https://user-images.githubusercontent.com/17208299/95000606-f8d80d80-05f4-11eb-9518-d9e262afc1be.png)

**Comment by rubensrocha** [comment]
My solution to extend cookie:

`docker-compose exec phpmyadmin bash`

Install nano:
```
apt-get update
apt-get install nano
```
Open user config file:
`nano /etc/phpmyadmin/config.user.inc.php`

Paste this code:
```
<?php

$cfg['LoginCookieValidity'] = 1440000000000000000; // define seconds here (type integer)
```

ctrl+x to exit, y to save and enter to confirm
