### ISSUE TITLE
SSH2 PECL Extension

### ISSUE THREAD

**Issue by phirschybar** [laradock/laradock#1724]
It doesn't appear that the SSH2 extension is part of Laradock. I am getting `Call to undefined function ssh2_connect()` when I try to SFTP using `$sftp = ssh2_sftp($connection);` etc. 

Anybody know the proper way to add this to the included Docker/PHP7.1? I will submit a thorough PR but am looking for some direction.

**Comment by vladyslavstartsev** [comment]
@phirschybar look at [this one](https://github.com/laradock/laradock/pull/1716) that I did last week it's almost the same, but for `workspace` container, not for `php-worker`

**Comment by vladyslavstartsev** [comment]
@phirschybar can you please close your issue if every thing works fine?
