### ISSUE TITLE
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? Service 'workspace' failed to build

### ISSUE THREAD

**Issue by Aidilrozi** [laradock/laradock#1725]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): b2ab970d04e4c4c958ff25fd1ea09af91c39df37

- System info (Mac, PC, Linux): PC
- System info disto/version: 

### Issue:

unable to build workspace after update .env mysql version to 5.7 
i get this error when do docker-compose up mysql php-fpm nginx 

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nasm/nasm_2.11.08-1ubuntu0.1_amd64.deb  Hash Sum mismatch  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? Service 'workspace' failed to build: The command '/bin/sh -c apt-get update -yqq     && apt-get -yqq install nasm' returned a non-zero code: 100

Please help to solve this issue , thank you
### Expected behavior:

mysql version should install version 5.7 and no issue in building workspace 

### Reproduce:

change mysql version to 5.7 original is latest

### MYSQL #################################################

MYSQL_VERSION=5.7
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

**Comment by rex-chien** [comment]
I had encountered this problem today. Solved it by restarting my docker service.

**Comment by Aidilrozi** [comment]
restarting docker solve my problem . thank you!

**Comment by valiner** [comment]
没有是重启不能解决的，如果有就重启两次。
