### ISSUE TITLE
[Request] PHP-GMP enable option in workspace .env settings

### ISSUE THREAD

**Issue by adammparker** [laradock/laradock#1726]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 2ec2312
- System info (Mac, PC, Linux): Mac
- System info disto/version: High Sierra 10.13.6

### Issue:
The PHP extension GMP is installed in the PHP-FPM container, but `composer install` won't run in the workspace because it's not enable there in the CLI.

**Comment by kinqsley** [comment]
@vladyslavstartsev  That doesn't work.

**Comment by vladyslavstartsev** [comment]
@adammparker  can you please close your issue if every thing works fine?

**Comment by vladyslavstartsev** [comment]
> Need help
> I need php7.1-gmp in workspace container. I have set the following variable to `WORKSPACE_INSTALL_GMP=true` and `PHP_FPM_INSTALL_GMP=true`. php version in workspace container is `PHP_VERSION=7.1`. Rebuilding (`docker-compose build --no-cache workspace`) workspace container installs `php7.2-gmp` instead of `php7.1-gmp`. @vladyslavstartsev

okay, somehow it installs old PHP 7.2,
make sure it installs 7.1 (for example check that you changed values in `.env` and not `env-example`)

**Comment by tomonsoejang** [comment]
@vladyslavstartsev Please check this [PR](https://github.com/laradock/laradock/pull/1933)
