### ISSUE TITLE
How to expose and run Node.js app / No Documentation

### ISSUE THREAD

**Issue by dendihandian** [laradock/laradock#1727]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 85c57a0
- System info (Mac, PC, Linux): Linux 
- System info disto/version: Ubuntu 18.04 LTS

### Issue:
 
No documentation to access running nodejs app in local machine browser

### Expected behavior:

There are explanation or guide in official laradock documentation to run (maybe expose a port) nodejs app. 

### Reproduce:
 
run any nodejs app server via `npm run dev` or `yarn dev` command. And It must be cannot be accessed in localhost:3000 / 0.0.0.0:3000 / {docker-host}:3000

### Relevant Code:

```
// place a code sample here
```

**Comment by CrediMarketIT** [comment]
+1. I facing the same problem. Trying to expose 3000 or add port 3000:3000 on workspace container but no luck, localhost:3000 still returns 'this site can't be reached'. 
Anyone know how to set this up?

**Comment by zuohuadong** [comment]
The workspace is not suitable for running the node.js program, but I can add it if needed.

**Comment by llioor** [comment]
@Denis00211  and @zuohuadong ... can u please advice...? 
Please check the print screens:
![screenshot-0 0 0 0-3300-2019 01 23-19-12-27](https://user-images.githubusercontent.com/6999073/51625560-2165c400-1f46-11e9-8153-fabdbc2a7ee9.png)
![screenshot-0 0 0 0-3300-2019 01 23-19-11-56](https://user-images.githubusercontent.com/6999073/51625561-21fe5a80-1f46-11e9-8ac9-709fbb01c712.png)
![screenshot-localhost-3300-2019 01 23-19-35-28](https://user-images.githubusercontent.com/6999073/51625562-21fe5a80-1f46-11e9-946f-23371da5726c.png)

**Comment by llioor** [comment]
Just made it with this:
![screenshot-localhost-3300-2019 01 23-19-39-19](https://user-images.githubusercontent.com/6999073/51625768-ae108200-1f46-11e9-929f-5431c07db460.png)

**Comment by ezra-obiwale** [comment]
@llioor Need more clarifications, please.

1. Vue 2 or 3?
2. You can access the dev server from the host?
3. Hot reload works?

**Comment by llioor** [comment]
@ezra-obiwale Hi Ezra... I'll be happy to help you.
1. I'm working with react and not Vue.. I don't think it matters.
2. I can access the dev server from localhost:3300 (as u see I changed the port in the webpack "devserver" setting because I'm running another container which listen to port 3000).
3. Hotreload works!

Basically u need to change in the "devServer" setting this:
1. port: 3000
2. host: 0.0.0.0
3. Then in the docker-compose.yml file I added this line under the workspace section:
```
ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "3300:3300" 
```
4. Then I re-build the workspace 
5. Then run the sever and go to http://localhost:3300

**Comment by juanjosv** [comment]
> @ezra-obiwale Hi Ezra... I'll be happy to help you.
> 
> 1. I'm working with react and not Vue.. I don't think it matters.
> 2. I can access the dev server from localhost:3300 (as u see I changed the port in the webpack "devserver" setting because I'm running another container which listen to port 3000).
> 3. Hotreload works!
> 
> Basically u need to change in the "devServer" setting this:
> 
> 1. port: 3300
> 2. host: 0.0.0.0
> 3. Then in the docker-compose.yml file I added this line under the workspace section:
> 
> ```
> ports:
>         - "${WORKSPACE_SSH_PORT}:22"
>         - "3300:3300" 
> ```
> 
> 1. Then I re-build the workspace
> 2. Then run the sever and go to http://localhost:3300

And how to add this to a running _dockerized_ apache o nginx? 
Can we add a site and map for example to localhost/appnode?

**Comment by DungBuiDeveloper** [comment]
same question for laradock please.
