### ISSUE TITLE
Getting 404 error on Digital Ocean droplet with Laradock installed

### ISSUE THREAD

**Issue by carraroenrico** [LaraDock/laradock#173]
I installed laradock on a digital ocean droplet, a followed the video tutorial, but at the end I get 404 error, is there any configuration that I have to change to get laradock working on an cloud server such as Digital Ocean?

**Comment by mattythebatty** [comment]
Is there any output in the logs

**Comment by midascodebreaker** [comment]
check my guide @carraroenrico
