### ISSUE TITLE
Errors building PHP container after upgrade to 7.3

### ISSUE THREAD

**Issue by Spudley** [laradock/laradock#1730]
### Info:
- Docker version (`$ docker --version`): 18.03.1-ce build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): Tag 7.3 (also current master)
- System info (Mac, PC, Linux): Macbook Pro.
- System info disto/version: 

### Issue:
Getting errors trying to start Laradock application after upgrade to Laradock 7.3. Errors did not occur with 7.2. Reverting to 7.2 is fine.

Dump of error:
```
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick-6-common_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6-arch-config_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6-headers_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-3_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6-headers_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6.q16-3_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-3-extra_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-dev_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6.q16-dev_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-dev_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick-6.q16_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found [IP: 217.196.149.233 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -y libmagickwand-dev imagemagick &&     pecl install imagick &&     docker-php-ext-enable imagick ;fi' returned a non-zero code: 100
```
_____

### Expected behavior:

I would expect to get a working set of containers when I do docker-compose up.

_____

### Reproduce:

Create a clean new Laravel project using composer create-project.
Download Laradock 7.3 zip file from Github. Unzip it into the Laravel project.
Create .env file from env.example.

    cd myProject/laradock
    docker-compose up -d nginx mariadb

Docker then tries to build the containers. After some time, we get the error messages above, the build fails, and the containers do not start.
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by Spudley** [comment]
Hmm. Actually, I just got the same issue from a fresh install using Laradock 7.2, so it obviously isn't specific to 7.3 after all. Sory for the mis-information.

Also, I can work around it by setting `PHP_FPM_INSTALL_IMAGEMAGICK=false` in the env file. I'm not planning to use ImageMagic on this project, so that workaround is okay for me, but it will still be a problem for anyone who does need it.

**Comment by bestlong** [comment]
Hi @Spudley 
try `docker-compose build --no-cache php-fpm`

**Comment by Spudley** [comment]
Hi @bestlong.

Thanks for the tip -- that worked.  :)   I'll close the issue.

Worth keeping a note of it though.
