### ISSUE TITLE
Error while building container

### ISSUE THREAD

**Issue by RobbeVW** [laradock/laradock#1736]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.06.0-ce, build 0ffa825
- Laradock commit (`$ git rev-parse HEAD`): e92f08e323dfa2fd488ab92ef38c5f224fb930e8
- System info (Mac, PC, Linux): Windows 10
- System info disto/version: 

### Issue:

After following instructions to set up my Laradock project I get an IO error. I have waited for a day, hoping the CDN would be down but I can perfectly download the file from my own computer.

### Expected behavior:

The error shouldn't appear?

### Reproduce:

All I did was follow the instructions to set up my Laradock project.

### Relevant Code:

```
$ docker-compose up -d nginx mysql
Building nginx
Step 1/11 : FROM nginx:alpine
 ---> 36f3464a2197
Step 2/11 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Using cache
 ---> 0bdeb3bb4181
Step 3/11 : COPY nginx.conf /etc/nginx/
 ---> Using cache
 ---> a1ece8ba2a09
Step 4/11 : ARG CHANGE_SOURCE=false
 ---> Using cache
 ---> 5728fdbcbe3b
Step 5/11 : RUN if [ ${CHANGE_SOURCE} = true ]; then     sed -i 's/dl-cdn.alpine                                                                   linux.org/mirrors.aliyun.com/' /etc/apk/repositories ;fi
 ---> Using cache
 ---> f2d7b6fe605d
Step 6/11 : RUN apk update     && apk upgrade     && apk add --no-cache bash                                                                        && adduser -D -H -u 1000 -s /bin/bash www-data
 ---> Running in b54ced39b5d4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: IO ERROR
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: IO ERROR
v3.7.0-224-g7b76ef5a44 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-223-g398c3a729f [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
2 errors; 9049 distinct packages available
Service 'nginx' failed to build: The command '/bin/sh -c apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data' returned a non-zero code: 2

```

**Comment by tobiasdalhof** [comment]
Have you tried to change the DNS Server settings under Network to `Fixed: 8.8.8.8`?

https://i.imgur.com/oJsjDlS.png

I had a similar problem back in the days.

Let me know if it worked.

**Comment by tobiasdalhof** [comment]
Have you tried simply restarting docker? Refering to https://github.com/gliderlabs/docker-alpine/issues/348#issuecomment-340954983

**Comment by RobbeVW** [comment]
@tobiasdalhof 
Restarted Docker and my computer, even re-installed Docker at this point. My connection is giving 10Mbps, should be sufficient.
