### ISSUE TITLE
update php-fpm container error

### ISSUE THREAD

**Issue by ahkui** [laradock/laradock#1740]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 0f4ed3f3c800c58408bb9a59a31de5a36b323bd8
- System info (Mac, PC, Linux): linux
- System info disto/version: ubuntu 16.04

### Issue:
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick-6-common_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6-arch-config_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6-headers_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-3_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6-headers_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6.q16-3_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-3-extra_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-dev_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6.q16-dev_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/libmagickwand-dev_6.9.7.4+dfsg-11+deb9u4_all.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick-6.q16_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Failed to fetch http://security.debian.org/pool/updates/main/i/imagemagick/imagemagick_6.9.7.4+dfsg-11+deb9u4_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
_____

### Expected behavior:

_____

### Reproduce:
add apt-get update -yqq to dockerfile
_____

### Relevant Code:

```
###########################################################################
# ImageMagick:
###########################################################################

USER root

ARG INSTALL_IMAGEMAGICK=false

RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get update -yqq && \
    apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick \
;fi
```

**Comment by bestlong** [comment]
try `docker-compose build --no-cache php-fpm`
apt-get update is run at the beginning of the Dockerfile build step, and will cache it.
so, if install source updated will meet this issue.

**Comment by bestlong** [comment]
Duplicate #1730
