### ISSUE TITLE
MySQL container is created but immediately disappears afterwards.

### ISSUE THREAD

**Issue by gabrielcamr9** [laradock/laradock#1741]
### Info:
- Docker version 18.06.0-ce, build 0ffa825: 
- Laradock commit 8180804ae0b0c731415174d6a8e9261f07b33161: 
- System info Linux Mint Sylvia 18.3: 

### Issue:
Can't connect to MySQL Database. I have tried numerous fixes from others with the same problem but so far nothing has worked. After a while I noticed that the MySQL container wasn't working at all.
_____

### Expected behavior:
The container should appear and I should be able to connect to a Database.
_____

### Reproduce:
´´´
composer create-project --prefer-dist laravel/laravel dummyProject
git clone https://github.com/Laradock/laradock.git
cd laradock
cp env-example .env
nano .env 
APP_CODE_PATH_HOST=../dummyProject
MYSQL_VERSION=5.7 #MySQL 8 seems to be even buggier
docker-compose up -d nginx mysql phpmyadmin
docker ps
´´´
![image](https://user-images.githubusercontent.com/31892881/43429765-e4ff9cc6-942a-11e8-9fc9-8374f1ae3ae7.png)

_____

**Comment by loonpwn** [comment]
You can debug this further by running `docker-compose up mysql` and seeing what is comes out. I've ran into this problem previously and it has had to with mounting an existing corrupt DB volume.

**Comment by aagarwal2286** [comment]
Did you try mariadb as well?

**Comment by gabrielcamr9** [comment]
Thanks for your replies, unfortunately this was a side project and I don't have the time to work on it anymore. I am closing this issue.
