### ISSUE TITLE
php-worker jobs should be run under another account

### ISSUE THREAD

**Issue by MoogyG** [laradock/laradock#1749]
I use php-worker and Daily log files in Laravel.

When a job started in php worker generates a new daily log file, it's created with root permission only.

So when my laravel app needs to log somehting later in php-fpm, it throws me an exception with "no right access" to this log file.

Anybody else? How to handle that?

**Comment by lokingwei** [comment]
In my case, you can specify  `user=www-data` in laravel-worker.conf when runing your worker.

However, be sure the www-data have the same uid with the apache www-data, strangely my supervisord spawn a different www-data user.

**Comment by grandkrav** [comment]
@MoogyG , have the same issue. Just added user and group creation.

In docker-compose.yml pass the same group and user ids from workspace:
```
php-worker:
...
- args:
  - PUID=${WORKSPACE_PUID}
  - PGID=${WORKSPACE_PGID}
```

In Dockerfile added user and group creation:

```
ARG PUID=1000
ENV PUID ${PUID}
ARG PGID=1000
ENV PGID ${PGID}

RUN addgroup -g ${PGID} laradock && \
    adduser -D -u ${PUID} -G laradock laradock
```

In supervisor.d/laravel-worker.conf set user:
```
[program:laravel-worker]
...
user=laradock
```

**Comment by lanphan** [comment]
Another way is to create new log file reserved for your job under php-worker only. In supervisor.d/laravel-worker.conf, please add 2 lines below:

```
redirect_stderr=true
stdout_logfile=YOUR_PROJECT_DIRECTORY/storage/logs/worker.log
```
