### ISSUE TITLE
using Socket.io

### ISSUE THREAD

**Issue by GeoIntranet** [LaraDock/laradock#175]
Hello , 
I'm testingto use socket.io in my project with laradock.

But i don't know , wich specific port i need to listen ? 
i start node server , that's step is ok , but in my view , i usually have :     
socket = io('http://127.0.0.1:3000/');

but , google chrome notice me :
http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=LOTnbqD net::ERR_CONNECTION_REFUSED

the controller make her job , he publish an event , the server listen , i see the response on the shell command , but no in the view >< 

anyone have idea for this issu ? or mistake from me..

**Comment by GeoIntranet** [comment]
anyone does how to available the port 3000 to acces 192.168.99.100:3000 ?

**Comment by Kauhat** [comment]
I'm not sure if I follow correctly, is your node server also a docker container? You can expose port 3000 using the `ports` property in your `docker-compose.yml`, e.g:

```yaml
    node:
        ports:
            - "3000:3000"
```

**Comment by GeoIntranet** [comment]
nop, cause i think to need to specify an image configuration like ..... 

--

node:
        build: ./node
        ports:
            - "3000:3000"

-- 

FROM node:4.3.2
EXPOSE 3000

CMD ["node"]

-- 

But i'm a newbie in docker ....

**Comment by Kauhat** [comment]
That looks fine to me!

I'd recommend to try running `docker-compose build node` and check for errors. Sometimes if there is a build error the container will stop immediately without much of a warning.

If that's good, double check the container is running with the `3000` port open using `docker ps`.

Finally try `docker-compose logs node` - this will let you know if the PID 1 process `node` (As described with CMD) ends or runs into an error. If this process finishes, the container usually stops, so a startup problem can stop the container immediately, even if `docker-compose up -d` appears to be successful.

**Comment by GeoIntranet** [comment]
i make , a little modification in the node build  - CMD ["node", "socket.js"]  - 
ok , so i build de node container , i try to up it , but he stay in exit 1 state.
When i look the log  : 
`Attaching to laradock_node_1
node_1                | module.js:442
node_1                |     throw err;
node_1                |     ^
node_1                |
node_1                | Error: Cannot find module '/socket.js'
node_1                |     at Function.Module._resolveFilename (module.js:440:15)
node_1                |     at Function.Module._load (module.js:388:25)
node_1                |     at Module.runMain (module.js:575:10)
node_1                |     at run (bootstrap_node.js:352:7)
node_1                |     at startup (bootstrap_node.js:144:9)
node_1                |     at bootstrap_node.js:467:3`

the soket.js file exist at the root of my project but he didn't find it

**Comment by Kauhat** [comment]
You might need to map the volumes to use that file if you haven't already. You can use the below in your `docker-compose.yml` to to this:

```yaml
    node:
        volumes_from:
            - volumes_source
```

If it's in the root, the file should be accessible at `/var/www/laravel/socket.js`.

**Comment by GeoIntranet** [comment]
pfouu >< after many test , won't work ... 
Docker-compose : 
`
## NODE #################################################
    node:
        build: ./node
        ports:
            - "3000:3000"
        volumes_from:
            - volumes_source
`

Build : 
`
FROM node:latest
EXPOSE 3000

CMD ["node", "socket.js"]  
`
