### ISSUE TITLE
laradock can't run migrate, connection refused.

### ISSUE THREAD

**Issue by xingaoau** [laradock/laradock#1752]
### Info:
- System info : Windows 10 

### Issue:
- php artisan migrate
- SQLSTATE[HY000] [2002] Connection refused
_____

### Expected behavior:
- connect to mysql in workspace container
_____

### Reproduce:
- go to laradock
- docker-compose exec workspace bash
- php artisan migrate
- SQLSTATE[HY000] [2002] Connection refused
_____

### Relevant Code:
- my laradock .evn
MYSQL_VERSION=8.0
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

- my laravel .env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=myDev
DB_USERNAME=root
DB_PASSWORD=root

- my docker-compose.yml
 mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

I am run those on Window platform. didn't have issue with Mac.

**Comment by shahzad-sarwar** [comment]
Change your db host to mysql

**Comment by jr-smith** [comment]
changed db host to 'mysql' in the .env
(running on windows 10)

Still doesn't work.

`DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=root
DB_PASSWORD=root`

Also changed to:
`DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret`

 and still does _not_ work.

**Comment by shahzad-sarwar** [comment]
Log in to phpmyadmin and add a database there. You're using default DB params which are not acceptable at any cost.
DB_DATABASE:your-database-name

**Comment by xingaoau** [comment]
my env
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=catapult
DB_USERNAME=root
DB_PASSWORD=root

- create new db via mysqlbencmark
- change db host to mysql

- docker-compose stop
- docker-compose up -d nginx mysql workspace
- docker-compose exec workspace bash
- php artisan migrate

still have the error:
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = catapult and table_name = migrations)

**Comment by shahzad-sarwar** [comment]
share the output of these commands.

1. docker-compose ps

2. docker-compose logs mysql

**Comment by shahzad-sarwar** [comment]
I have found a solution for your problem.

Go to laradock/mysql/my.cnf

change it with the following code.

# The MySQL  Client configuration file.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

[mysql]

[mysqld]
sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
character-set-server=utf8
default_authentication_plugin=mysql_native_password


Now rebuild your container.

docker-compose down

docker-compose build mysql

docker-compose up -d nginx mysql etc

docker-compose exec --user=laradock workspace bash

**Comment by amorZhu** [comment]
`cd laradock/mysql`
`vim mysql/my.cnf`
增加如下内容：（第一行作为参照）
`character-set-server=utf8`
`default_authentication_plugin=mysql_native_password`
docker-compose down
查看 laradock/.env 文件中 `DATA_PATH_HOST=~/.laradock/data`
`sudo rm -rf ~/.laradock/data`
`docker-compose up -d nginx mysql phpmyadmin redis workspace `
`docker-compose exec workspace bash`
`php artisan migrate`

OK

**Comment by Alex66668888** [comment]
I have the same trouble ,but when I setting on my laravel 5.6 's .ENV config file is  DB_HOST=mysql can deal with my trouble. This is my laravel 5.6 's about db config

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=lara_roast
DB_USERNAME=root
DB_PASSWORD=root

However , I find an another problem,when I connect mysql by phpMyAdmin  is still error.
error msg is  Connection refused.

but I use Navicat for mysql app connect Mysql is successful.

I use docker version is Docker version 18.09.2, build 6247962

**Comment by Alex66668888** [comment]
I deal with my problems ! 
first step: I change laradock Mysql version from latest to 5.7.
change laradock's Mysql version steps:

1. edit laradock .ENV config file : 
      MYSQL_VERSION=5.7
2.  docker-compose down
3.  rm -rf ~/.laradock/data/mysql
 (if you use powerShell you must use this command: rm -Force ~/.laradock/data/mysql )
4. docker-compose build mysql 
5. docker-compose up -d nginx mysql redis
6. docker inspect laradock_mysql_1

second step : change your laravel project .ENV config file
when you need execute "php artisan migrate" to create tables, you must edit  
   DB_HOST=127.0.0.1
==================================
when I execute "php artisan migrate" command, my .ENV config file

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
# DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=root
==================================

when you use ORM or DB select , you must edit 
    DB_HOST=mysql
==================================
when I use ORM or DB select, my .ENV config file

DB_CONNECTION=mysql
# DB_HOST=127.0.0.1
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=root
==================================

if you want to connet Mysql for phpMyAdmin ,you must 
Host : mysql
username: root 
password: root 

even if I don't know why , but I take a half one day to deal with my problems  55555

**Comment by shapito27** [comment]
thank you, it works
**DB_HOST=mysql**

and if you change database user you should set for it host equal **mysql host**
![Screenshot_14](https://user-images.githubusercontent.com/9530168/65394575-8fde7880-dd98-11e9-887d-47018f2e3de5.png)
.
My problem  was i set localhost. And only when i changed to '**any host**' i understood my fail.

**Comment by shafi-** [comment]
Host should be your database service name. For example, your `docker-compose.yml`


    services:

          app:
                 #app service config`

         #mysql service
         db:
                 #mysql service config

For this, `DB_HOST=db`

**Comment by VuongTran21** [comment]
This will work for me:
I try to down version of mysql in laradock to 5.7.
Follow step in @Alex66668888  comment for details.
Change your env on Laravel project.

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=yourdatabase
DB_USERNAME=username
DB_PASSWORD=password

**Comment by metalcamp** [comment]
@bestlong I believe this issue can now be closed.

**Comment by uranoni** [comment]
> Change your db host to mysql

thanks a lot!!
it's work for me

**Comment by iFrancs** [comment]
> > Change your db host to mysql
> 
> thanks a lot!!
> it's work for me

Which laravel version are you working with?

**Comment by ikidnapmyself** [comment]
I also had the same problem because I set `MYSQL_PORT=3307` like below:
> My local MySQL server starts with my OS, so everytime I use Laradock, I'd stop my local MySQL service with `brew services stop mysql` .
  
laradock/.env
```
### MYSQL #################################################

MYSQL_VERSION=latest
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3307
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```

And then I set my Laravel `.env` `DB_PORT=3307` but it's a **mistake!**  

![resim](https://user-images.githubusercontent.com/13779866/79334284-a7de3b00-7f28-11ea-9ea2-3ac5be7152d1.png)

I run `php artisan migrate` like commands in the container by using this command: `docker-compose exec workspace bash`

So, if I'm in the container, the port must be `3306`

laravel/.env
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
``` 
But surely if you'd like to go with your local tools such as your IDE, use `3307` port to connect.

PHPStorm:
<img width="808" alt="resim" src="https://user-images.githubusercontent.com/13779866/79266736-bbde5a00-7ea0-11ea-8c15-5cbac59e1096.png">

Another happy landing! 🚀

**Comment by spacedog4** [comment]
@ikidnapmyself how did you connected with phpstom, I'm using mysql 5.7 and I just cant,I'm exposing port 3307 aswell, I'v already tryied with 127.0.0.1, container IP, docker host ip, and nothing

![image](https://user-images.githubusercontent.com/19805404/87610981-43747880-c6dd-11ea-9d54-d3dbc94dd992.png)

**Comment by thanhtruong1992** [comment]
> Change your db host to mysql

working
