### ISSUE TITLE
need php7.2-mbstring ext

### ISSUE THREAD

**Issue by elinxer** [laradock/laradock#1753]
### Info:

It's all up to date. But has lost php-ext-mbstring, can add it to master?

**Comment by ganl** [comment]
It is recommended to recheck

![image](https://user-images.githubusercontent.com/11937688/45256291-270fa280-b3c7-11e8-85df-634e92184687.png)

![image](https://user-images.githubusercontent.com/11937688/45256271-e021ad00-b3c6-11e8-81d3-412a1a3b2f77.png)

**Comment by vladyslavstartsev** [comment]
@elinxer in which container?
