### ISSUE TITLE
Docker cache all route responses

### ISSUE THREAD

**Issue by Arjandewi** [laradock/laradock#1755]
### Info:
- Docker version 18.06.0-ce, build 0ffa825
- System info: Mac

### Issue:

Every route response is cached

### Expected behavior:

No caching

Hello,

I just installed Docker last week and i got a strange behavior; every second route response is cached.
On the internet i found a few fixes but nothing works.
I tried so far:

Change .env settings:
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_LOG_MAX_FILES=30
BROADCAST_DRIVER=log
CACHE_DRIVER=array
CACHE_EXPIRE=-1
SESSION_DRIVER=array
QUEUE_DRIVER=sync

I run docker with command docker-compose up -d nginx mysql

The only way to reset the cache is to restart docker.

Any thoughts?

Thanks in advanced
Arjan

**Comment by lixin1014** [comment]
Hello,I have  same problem.Have you solved the problem?

**Comment by andrey-helldar** [comment]
I have been using docker for more than a year, but the same problem appeared yesterday.

First solution: restarting docker.
The second solution: wait 10-15 minutes.

The problem of both solutions - after this, the routes are normally returned for 1-3 minutes, after which they again start to cache and you have to either restart the docker or wait ...

> Docker: 2.2.0.0 (42247) stable
> OS: Windows 10 Corporate 1909 (build 18363.592)
> Laradock Workspace: 2.6.1-7.4
> PHP 7.4

**Comment by andrey-helldar** [comment]
@Arjandewi, @ObrookO, I can assume that this is not a bug, but a feature of the docker itself: https://docs.docker.com/docker-for-mac/osxfs-caching/

> In particular, in many cases there is no need for writes performed in a container to be immediately reflected on the host.

I am now far from a working computer and I can’t check, but I can assume that I need to change the value of option `APP_CODE_CONTAINER_FLAG` of `.env` file to `APP_CODE_CONTAINER_FLAG=consistent`.

**Comment by andrey-helldar** [comment]
@appleboy, maybe it's worth adding the mention the `:consistent` key to the `env-example` file?

https://github.com/laradock/laradock/blob/ad2b455be577669aa599f3511704565e6a806629/env-example#L13-L14

See https://docs.docker.com/docker-for-mac/osxfs-caching/
In my [comment](https://github.com/laradock/laradock/issues/1755#issuecomment-577747557) above I wrote about this.
