### ISSUE TITLE
Xdebug doesn't work

### ISSUE THREAD

**Issue by zr87** [laradock/laradock#1761]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.06.0-ce, build 0ffa825
- Laradock commit (`$ git rev-parse HEAD`): 8180804ae
- System info (Mac, PC, Linux):  macOs HighSierra 10.13.6

### Issue:
Can't get Xdebug to work.
_____

### Expected behavior:
Should stop at breakpoint
_____

### Relevant Code:
laradock/.env 
```
PHP_FPM_INSTALL_XDEBUG=true
WORKSPACE_INSTALL_XDEBUG=true
```
php-fpm/xdebug.ini
```
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_connect_back=0
xdebug.cli_color=1
xdebug.profiler_enable=0
xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.remote_port=9000
xdebug.remote_host=172.16.3.97
xdebug.idekey=PHPSTORM
```
workspace/xdebug.ini has same content as in php-fpm folder

![phpinfo](https://user-images.githubusercontent.com/6025181/44300094-9bdc4900-a301-11e8-930c-3793dcf89ee4.jpg)
![remote_debug](https://user-images.githubusercontent.com/6025181/44300099-ac8cbf00-a301-11e8-8a5c-9e9e42e1c4e8.png)
![servers](https://user-images.githubusercontent.com/6025181/44300109-c3cbac80-a301-11e8-85ca-bd215a4c0371.png)
![debug_preferences](https://user-images.githubusercontent.com/6025181/44300122-fbd2ef80-a301-11e8-83a4-a019e2da15d3.png)
![deployment](https://user-images.githubusercontent.com/6025181/44300123-fbd2ef80-a301-11e8-9f05-e1288dd4413a.png)
![debugger_settings](https://user-images.githubusercontent.com/6025181/44300124-fbd2ef80-a301-11e8-8079-ad4824e7ecec.png)
![debugger_console](https://user-images.githubusercontent.com/6025181/44300125-fc6b8600-a301-11e8-8757-2862833ece5a.png)

![interpreter](https://user-images.githubusercontent.com/6025181/44300153-7996fb00-a302-11e8-8020-d6e6d9fb2e67.jpg)

**Comment by zr87** [comment]
Setting `remote_host` to `host.docker.internal`  solved the problem.
I found the solution here: https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds.

**Comment by redbonzai** [comment]
Hello, @zr87 When you mentioned Setting remote_host to host.docker.internal, where did you set it for xdebug to work for you ? Could you please post an example ? 

Thank you, 
Christian

**Comment by NicksonYap** [comment]
@redbonzai  
Yes it's in xdebug.ini

```
xdebug.remote_enable=1
xdebug.remote_host=docker.for.mac.localhost       <<<<< REPLACE THIS TO: host.docker.internal
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.remote_handler=dbgp
xdebug.max_nesting_level=250
xdebug.remote_log=”/var/www/xdebug_log/xdebug_docker.log”
```

See this guide, extremely helpful:
https://medium.com/full-stack-development/laradock-xdebug-ms-code-no-problem-35a4338deb3f

**Comment by lhduc** [comment]
Hello, I got same issue too. 

I've changed `xdebug.remote_host=host.docker.internal` (or "dockerhost" as well).
The xdebug validation is good with same xdebug.ini. 
The website sends correct cookie `XDEBUG_SESSION=PHPSTORM` as well.

However it is still not stopping at break point. Please advice me, thanks.

**Comment by shov** [comment]
![image](https://user-images.githubusercontent.com/1494325/56646188-c435f780-6687-11e9-84d9-0cf69822ea62.png)

xdebug.ini
```
xdebug.remote_host=docker.for.mac.localhost
xdebug.remote_connect_back=0
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM

xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.cli_color=1
xdebug.profiler_enable=1
xdebug.profiler_output_dir="~/xdebug/phpstorm/tmp/profiling"

xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1
xdebug.max_nesting_level=250
```

**Comment by xxRockOnxx** [comment]
I stumbled upon this while Googling, so for everyone else who did also that's using Linux, it seems like only Windows and Mac has a special DNS name for the host i.e `host.docker.internal` and `docker.for.mac.localhost`.

To solve it, I ran `docker network inspect bridge | grep Gateway` and used that as the `xdebug.remote_host` and for everything else, laradock's default should work. Maybe change the `xdebug.idekey` as well if you have to.

**Comment by afuz777** [comment]
> I stumbled upon this while Googling, so for everyone else who did also that's using Linux, it seems like only Windows and Mac has a special DNS name for the host i.e `host.docker.internal` and `docker.for.mac.localhost`.
> 
> To solve it, I ran `docker network inspect bridge | grep Gateway` and used that as the `xdebug.remote_host` and for everything else, laradock's default should work. Maybe change the `xdebug.idekey` as well if you have to.
> 
> Also, updating `./php-fpm/xdebug.ini` is not enough. Either rebuild or manually edit the `xdebug.ini` inside the container if you're lazy.

Work for me!!!! Tanks

**Comment by valeu36** [comment]
> I stumbled upon this while Googling, so for everyone else who did also that's using Linux, it seems like only Windows and Mac has a special DNS name for the host i.e `host.docker.internal` and `docker.for.mac.localhost`.
> 
> To solve it, I ran `docker network inspect bridge | grep Gateway` and used that as the `xdebug.remote_host` and for everything else, laradock's default should work. Maybe change the `xdebug.idekey` as well if you have to.
> 
> Also, updating `./php-fpm/xdebug.ini` is not enough. Either rebuild or manually edit the `xdebug.ini` inside the container if you're lazy.

Big thanks! I have struggled on this for four hours and finally find a solution thanks to you. :relaxed:
