### ISSUE TITLE
rsync

### ISSUE THREAD

**Issue by thferreira86** [laradock/laradock#1769]
### Info:
- Docker version ( Docker version 18.06.0-ce, build 0ffa825 ): 
- Laradock commit ( 1b865dd153818643b2bbab685dd7a2155e2ae9fc ): 
- System info (Mac ): 
- System info disto/version: High Sierra

### Issue:

I'm trying to run the command

```php
<?php
$path = "/var/www/teste-domain/logs";
$server = "user@ip";
$output = shell_exec('rsync -az --progress ' . $path . ' ' . $server . ':public_html 2>&1');
echo "<pre>$output</pre>";
?>
```

but it returns

sh: 1: rsync: not found

**Comment by TheDailySpank** [comment]
Have you tried adding 'rsync' to php-fpm/Dockerfile then rebuild php-fpm?

```# always run apt update when start and after add new source list, then clean up at end.
RUN apt-get update -yqq && \
    apt-get install -y apt-utils && \
    pecl channel-update pecl.php.net
```

becomes...

```
# always run apt update when start and after add new source list, then clean up at end.
RUN apt-get update -yqq && \
    apt-get install -y apt-utils \
    rsync && \
    pecl channel-update pecl.php.net
```

**Comment by thferreira** [comment]
@TheDailySpank  i try but have the same problem
sh: 1: rsync: not found Exit status

**Comment by thferreira** [comment]
No solution :(
