### ISSUE TITLE
volume the workspace/crontab/laradock file to  support the mutilp project 

### ISSUE THREAD

**Issue by liminworks** [laradock/laradock#1771]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

* * * * * laradock /usr/bin/php /var/www/artisan schedule:run >> /dev/null 2>&1
_____

### Expected behavior:

_____
* * * * * laradock /usr/bin/php /var/www/project1/artisan schedule:run >> /dev/null 2>&1
or
* * * * * laradock /usr/bin/php /var/www/project2/artisan schedule:run >> /dev/null 2>&1

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by vladyslavstartsev** [comment]
Have you looked at this one? http://laradock.io/#B
