### ISSUE TITLE
workspace bash ubuntu version

### ISSUE THREAD

**Issue by abdelwahidjr** [laradock/laradock#1777]
### Info:
how to update laradock workspace to ubuntu 18 instead of 16 ... when i type `lsb_realse -a` in workspace bash  get :
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by talapai** [comment]
I didn't find php7.2-soap extension for ubuntun-16.04. It's actual
