### ISSUE TITLE
Whether it is necessary to rename and group env variables?

### ISSUE THREAD

**Issue by hz61p1** [laradock/laradock#1778]
I think that it is more necessary to name variables and group them.
Before PR, I would like to know whether it is worth it to do?

Example:
WORKSPACE_INSTALL_NODE
WORKSPACE_NODE_VERSION
WORKSPACE_NPM_REGISTRY
WORKSPACE_INSTALL_YARN
WORKSPACE_YARN_VERSION
WORKSPACE_INSTALL_NPM_GULP
WORKSPACE_INSTALL_NPM_BOWER
WORKSPACE_INSTALL_NPM_VUE_CLI
WORKSPACE_COMPOSER_GLOBAL_INSTALL
WORKSPACE_COMPOSER_REPO_PACKAGIST
WORKSPACE_INSTALL_PHP_PHPREDIS
WORKSPACE_INSTALL_PHP_XDEBUG
WORKSPACE_INSTALL_PHP_PHPDBG
WORKSPACE_INSTALL_PHP_SSH2
...
WORKSPACE_INSTALL_SSH
WORKSPACE_INSTALL_SUBVERSION
WORKSPACE_INSTALL_LIBPNG
...

**Comment by vladyslavstartsev** [comment]
@hz61p1 I'm not maintainer, but I would like to see this.

Also if you will do the PR, pay attention to not only `.env` (`env-example` in our case) but also to the matching of `.env` to `docker-compose.yml`.
What I mean is if you will look into `.env` you will see `WORKSPACE_COMPOSER_GLOBAL_INSTALL` var as first, but if you open `docker-compose.yml` you will see it will but on over 10th place in the `args` list of `workspace` service.
