### ISSUE TITLE
Trouble with MySQL connection

### ISSUE THREAD

**Issue by mruzekw** [LaraDock/laradock#178]
I'm having trouble with the MySQL host.

I am starting a new Laravel project. Can't seem to run the initial migrations.

I'm using Docker Mac Native. So `docker-machine ip` shows nothing.

Current config
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

```
root@c710fd677388:/var/www/laravel# php artisan migrate


  [PDOException]
  SQLSTATE[HY000] [2002] Connection refused
```

**Comment by GeoIntranet** [comment]
default ip is 192.169.99.100 try this , i think that will work

**Comment by mruzekw** [comment]
No dice.

When I connect with Sequel Pro it connects via 127.0.0.1 but not
192.169.99.100.
Currently I'm getting a "bad request (invalid hostname)" when I go to
http://192.169.99.100/

I don't see any separate docker network device either.

Any ideas?

Thanks

Will Mruzek
willmruzek.com
linkedin.com/in/willmruzek

**Comment by GeoIntranet** [comment]
you have to go to connect with the ip of the docker machine.
i use navicat , and when i creat connection i specifiy 192.168.99.100 with port : 3306 userName : homestead / pass secret 

.env Laravel's project : 
DB_CONNECTION=mysql
DB_HOST=192.168.99.100
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

**Comment by mruzekw** [comment]
I'm aware. I tried connect both via Sequel Pro and the .env config.

**Comment by Kauhat** [comment]
@GeoIntranet I'm not sure about the Mac version, but from my experience with the Windows Beta the IP address of the VM is displayed in the networking section of the settings. I believe that a recent update will also try to map containers to localhost - but I'm still able to reach things by the original IP. Might be worth a shot if you've not tried already @mruzekw 

You can also try using the root MySQL user, the username/password of which should be `root` `root` if you've not changed these already. I tend to use the root user in HeidiSQL as I can create/edit other databases as well as the default `homestead` one.

**Comment by GeoIntranet** [comment]
yep you allright  , i'm on window , and in the network setting you can watch the ip of the Vm. and by default : it's 192.168.99.100 .

**Comment by FubuBy** [comment]
Hellow.

When I type:
`DB_HOST=localhost`
I get error:
`SQLSTATE[HY000] [2002] No such file or directory`
When I type:
`DB_HOST=127.0.0.1`
I get error:
`SQLSTATE[HY000] [2002] Connection refused`

I work on Ubuntu 14. And ip of MySQL = 127.0.0.1

**Comment by mruzekw** [comment]
I was able to get this working just by using the db name from the docker-compose.yml.

For example:
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

This works due to docker container networks: https://docs.docker.com/engine/userguide/networking/dockernetworks/

Alternatively you can grab the IP of all running containers via:
```
docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
```

**Comment by fndmiranda** [comment]
I also can not connect to the database, it returns the message Connection refused, someone could figure out how to solve?

**Comment by iannazzi** [comment]
A bit of confusion about connecting..... I run many projects with docker so in past versions of docker I would specify unique mysql port per project: like 3309.... In fact I don't think I can bring up laradock mysql container without a unique port.

`    mysql:
        build: ./mysql
        volumes:
            - ./mysql/startup:/docker-entrypoint-initdb.d
        volumes_from:
            - volumes_data
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234`

However to run `php artisan` from workspace container I need .env to specify port 3306:

`DB_HOST=mysql
DB_DATABASE=local_a
DB_USERNAME=root
DB_PASSWORD=1234
DB_PORT=3306`

I guess this is because I am connecting container to container, however maybe this will help someone.

**Comment by adulion** [comment]
Can you put @mruzekw comment into the readme- at least the "docker inspect -f" command as i spent hours reading the doc's and trying different combinations of ip's in frustration when this was the perfect solution.

You shouldn't set the ip of the container but the one of the mysql container! the docs are wrong.

**Comment by philtrep** [comment]
@adulion Feel free to make a PR for the `docker inspect` command. The first part of the answer is already in docs under the intro section https://github.com/LaraDock/laradock#intro.

**Comment by eugeneratkevich** [comment]
Need add  block "links" & "environment" in application container/
Example:
```
 app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  database:
    image: mysql:5.7.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dockerApp"
    ports:
      - "3306:3306"
    volumes:
      - ./:/var/lib/mysql'
```

**Comment by oberoivarun** [comment]
@mruzekw The command was working until the latest update for Docker to Version 17.12.0-ce-win47 (15139)

It gives the following error:
![image](https://user-images.githubusercontent.com/13959202/36096592-11f25788-101d-11e8-8be7-a7ac473584cd.png)

I have no idea how to write such a command. Any fixes?

**Comment by ashajjar** [comment]
I had this issue, and I fixed it by adding the following to my.conf:

```
[mysql]
bind-address = 202.71.99.195
```

Change the IP to your application container IP address :)

**Comment by diegoazh** [comment]
I change
`DB_HOST=127.0.0.1` for `DB_HOST=192.168.10.10`
192.168.10.10 is the IP where my homestead machine is runing!
I hope this will be useful.

**Comment by LucaswDeveloper** [comment]
My Solution (windows 10)
1 - open cmd 
2 - execute ipconfig 
3 - get your ip Ethernet 192.168.x.x.
4 - open .env 
5 - changed  DB_HOST your ip Ethernet
6 - Save.

**Comment by babul** [comment]
I hope this helps someone. I'm on a Mac, YMMV.

Do not call your database container "database" in your docker-compose.yml! 

Use "mysql" instead and all works as described above :D

**Comment by abrahamdic** [comment]
Goodnight,

I use laravel 5.8 with laradock and this solution worked for me.
I use Mac OS.
Thanks LucaswDeveloper and diegoazh

**Comment by mysticaltech** [comment]
My key to this folks was to understand that if I connect from within another container, I have to use the name of the DB container as hostname, i.e. **mysql** or **mariadb** for instance.
