### ISSUE TITLE
grafana does not boot

### ISSUE THREAD

**Issue by deviouspk** [laradock/laradock#1783]
### Info:
- Docker version 18.06.1-ce: 
- Laradock commit: 2e2cb6df227aef83285e627bada59320606674da
- System info: Linux 
- System info disto/version: Ubuntu 18.04.1

### Issue:
When i start up the container (docker-compose up -d grafana) it doesn't get started. No error message is displayed
_____

### Expected behavior:
The container should have started and grafana running
_____

### Reproduce:
docker-compose up -d grafana and go to localhost:3000
_____

**Comment by deviouspk** [comment]
docker logs:
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied

**Comment by bestlong** [comment]
need more info:
at host os run:
```$ diff .env env-sample```
post result let we know your config.

then go into container
```$ docker-compose exec grafana bash```
and in container run:
``` $ ls -la /var/lib```
``` $ ls -la /var/lib/grafana```
check owner and permissions

**Comment by amorZhu** [comment]
FROM grafana/grafana:latest
USER root
RUN chown -R root:root /etc/grafana && \
  chmod -R a+r /etc/grafana && \
  chown -R grafana:grafana /var/lib/grafana && \
  chown -R grafana:grafana /usr/share/grafana
EXPOSE 3000

**Comment by bestlong** [comment]
try `docker-compose build --no-cache --pull grafana`
i run Grafana 6.6.1 is works normally.

**Comment by jhoanborges** [comment]
Solved changing the grafana Dockerfile.

```
FROM grafana/grafana:latest

USER root
RUN chown -R root:root /etc/grafana && chmod -R a+r /var/lib/grafana

EXPOSE 3535
```
