### ISSUE TITLE
caddy service caddyplug install filemanager fail

### ISSUE THREAD

**Issue by ahkui** [laradock/laradock#1787]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 876935452ec75fb19f75fef386234dc38e7c78de
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04LTS

### Issue:
![image](https://user-images.githubusercontent.com/14049597/45256227-27f40480-b3c6-11e8-9943-9d549d2e03bf.png)

_____

### Expected behavior:
![image](https://user-images.githubusercontent.com/14049597/45256275-f6c80400-b3c6-11e8-8c9b-c65e1c63589a.png)

_____

### Reproduce:
add `filemanager` to ARG plugins
_____

### Relevant Code:
![image](https://user-images.githubusercontent.com/14049597/45256265-c1bbb180-b3c6-11e8-9d37-85dd299c838f.png)

**Comment by zuohuadong** [comment]
You can try it with the latest version and if there is a problem I will update it again.
