### ISSUE TITLE
Automated Image Builds

### ISSUE THREAD

**Issue by computerfr33k** [LaraDock/laradock#179]
Would you be interested into getting these images automatically built on docker hub so that users can just specify the image to pull so that everyone doesn't have to build them. This would make it much faster for most people as they wouldn't need to wait to build the image manually as it can take a long time for some of them. I've started trying it out on my account and have a few images built so far.

https://hub.docker.com/u/computerfr33k/

**Comment by gwindes** [comment]
+1

**Comment by Mahmoudz** [comment]
Yes absolutely this is right. That's how LaraDock got started (you can see the [old images](https://github.com/LaraDock) still on the repo). However, I removed that just to give people flexibility to edit the images locally very quick.. But yes the build time is getting so big with all the Containers and the more software's getting supported every week.. I will try to mix between both features and make it easy to switch between them where by default you'll get the pre built image.

**Comment by computerfr33k** [comment]
I think the best way to accomplish this might be to have the most common defaults as a pre-built image and then if the user wants to customize the software installed, they would have to then build the container manually from the dockerfile, which is what I think you're saying above.
