### ISSUE TITLE
nginx 404

### ISSUE THREAD

**Issue by bebjakub** [laradock/laradock#1804]
### Info:
- Docker version: 18.06.1-ce 
- Laradock commit: db02fe7570c50615e18dd7371cc5d8ed443bab4f
- System info: Linux
- System info disto/version: Ubuntu 18.04.1 LTS

### Issue:
Getting 404 error
_____

### Expected behavior:
show website
_____

### Reproduce:
Root directory:
```
my-project
laradock
```
cp .env-example .env

laradock/nginx/sites/default.conf changes:
`root /var/www/public;` to `root /var/www/my-project;`

docker-compose up -d nginx

_____

On local env it's working, problem is just on the production.
Thank you!

**Comment by ganl** [comment]
check `server_name` 

or

```
docker-compose exec nginx bash
ls /var/www/my-project
```

**Comment by bebjakub** [comment]
I already made same on a different machine and it's working. Thank you!
