### ISSUE TITLE
mysqli_real_connect(): (HY000/2002): Connection refused

### ISSUE THREAD

**Issue by vsnote** [laradock/laradock#1818]
### Info:
- Docker version (`$ docker --version`): Docker version 18.06.1-ce, build e68fc7a
- Laradock commit (`$ git rev-parse HEAD`): db02fe7570c50615e18dd7371cc5d8ed443bab4f
- System info (Mac, PC, Linux): windows 10
- System info disto/version: windows 10 Enterprise Edition 1803

### Issue:

phpmyadmin login error.
![image](https://user-images.githubusercontent.com/8895379/46127298-e1762500-c262-11e8-9d75-397c89548266.png)

navicat login error
Host '172.19.0.1' is not allowed to connect to this MySQL server --

`### MYSQL #################################################`
`MYSQL_VERSION=latest`
`MYSQL_DATABASE=default`
`MYSQL_USER=default`
`MYSQL_PASSWORD=secret`
`MYSQL_PORT=3306`
`MYSQL_ROOT_PASSWORD=root`
`MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d`

`# All Networks driver`
`NETWORKS_DRIVER=bridge`

**Comment by vsnote** [comment]
```
CREATE USER 'default'@'%' identified by 'password';
GRANT ALL ON *.* TO 'default'@'%' ;
FLUSH PRIVILEGES ;
```

**Comment by ABQJuan** [comment]
I had this problem. I was able access phpmyadmin with the following creds:
Server: mysql
Username: root
Password: root

**Comment by Mbogning** [comment]
Good
