### ISSUE TITLE
Possible to connect to Docker-hosted site on local network?

### ISSUE THREAD

**Issue by davestewart** [LaraDock/laradock#182]
Hi Mahmoud,

Do you know the best way to access a Docker-hosted site across a local network? 

We're running a centralised admin + kiosks system which we'd like to test out on Docker (the admin machine will be hosted, the kiosks connect to it) but have had difficulty accessing from other machines on anything other than the a machine's default localhost. 

Browser sync looks like it might be an option, but is there anything built into Docker for this?﻿

Many thanks!

Dave

**Comment by Mahmoudz** [comment]
Hi @davestewart, I never tried that thus I don't know. I would suggest asking this on the Docker repository. Best of luck.
