### ISSUE TITLE
Connect to local mysql from container

### ISSUE THREAD

**Issue by santigarcor** [laradock/laradock#1823]
### Info:
- Docker version:  18.06.1-ce
- Laradock commit: 9cfe5c61565a77b4da40817f3e1d45e18ef5920d
- System info: Linux 
- System info disto/version: Ubuntu 16.04

### Issue:
I have mysql installed in my pc, and i would like to know how can i connect from a laradock container to my database in my local machine.

What should i put in my `DB_HOST` inside the laravel .env file?

**Comment by vladyslavstartsev** [comment]
@santigarcor if you look inside laradock is just set of services binded together with docker-compose.yml file. That what I've found on SO for you question https://stackoverflow.com/questions/44543842/how-to-connect-locally-hosted-mysql-databse-with-the-docker-container

**Comment by santigarcor** [comment]
Thanks man it worked.

**Comment by adiletmaks** [comment]
> Thanks man it worked.

Can you explain your solution ?
