### ISSUE TITLE
Unable to locate package php7.1-sybase

### ISSUE THREAD

**Issue by soniibrol** [laradock/laradock#1826]
### Info:
- Docker version : 18.06.1-ce, build e68fc7a
- Laradock commit (`$ git rev-parse HEAD`): 9cfe5c61565a77b4da40817f3e1d45e18ef5920d
- System info (Mac, PC, Linux): Linux
- System info disto/version: ubuntu 16.04

### Issue:
I need to install package php7.1-sybase or php7.2-sybase, so I add line on php-fpm/Dockerfile:
```
&& apt-get update \
&& apt-get install php7.1-sybase \

```
on SQL Server Section.

But, the installation cannot be finished, and it return error message:

> Reading package lists...
> + apt-get install php7.1-sybase
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package php7.1-sybase
> E: Couldn't find any package by regex 'php7.1-sybase'

How could I solved this?

Thanks in advance.

**Comment by basepack** [comment]
I can second this for xdebug and soap:
```
Unable to locate package php7.2-xdebug
Unable to locate package php7.2-soap
```

Steps to reproduce:
1) `git clone https://github.com/Laradock/laradock.git`
2) `cd laradock`
3) `cp env-example .env`
4) set `WORKSPACE_INSTALL_XDEBUG=true` and `WORKSPACE_INSTALL_SOAP=true`
5) `docker-compose build --no-cache workspace`
6) View the error in the console:
``` 
Step 61/179 : RUN if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi
 ---> Running in 2a2a47b3da6b
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.2-xdebug
E: Couldn't find any package by glob 'php7.2-xdebug'
E: Couldn't find any package by regex 'php7.2-xdebug'
Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi' returned a non-zero code: 100
```
7) set `WORKSPACE_INSTALL_XDEBUG=false` to view the SOAP related error.
