### ISSUE TITLE
Cant install Caddy

### ISSUE THREAD

**Issue by tcharlezin** [laradock/laradock#1838]
I am trying to install caddy, following the guide of Laradock.

This happened:

`installing Caddy...
# github.com/mholt/caddy/caddy
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x64c236, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc00c000000, 0x4000000, 0x7fafd8)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x7e2560, 0x4000000, 0x7e2578, 0x7fa7c84bebf8)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x7e2560, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x7e2560, 0x1, 0x7fafe8, 0x400)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x7e2560, 0x1, 0x6, 0x7fa7c875afff)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x7e2560, 0x1, 0x7fa7c8010006, 0x7fa7c84bebf8)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.(*mcentral).grow(0x7e3a18, 0x0)
	/usr/local/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x7e3a18, 0x7fa7c84bebf8)
	/usr/local/go/src/runtime/mcentral.go:106 +0x2f8
runtime.(*mcache).refill(0x7fa7cadfb000, 0x7fa7c8558306)
	/usr/local/go/src/runtime/mcache.go:122 +0x95
runtime.(*mcache).nextFree.func1()
	/usr/local/go/src/runtime/malloc.go:749 +0x32
runtime.systemstack(0x454a99)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000522a98 sp=0xc000522a90 pc=0x454b90
runtime.(*mcache).nextFree(0x7fa7cadfb000, 0x6, 0x18, 0x61dba0, 0xc0008ecb20)
	/usr/local/go/src/runtime/malloc.go:748 +0xb6 fp=0xc000522af0 sp=0xc000522a98 pc=0x40b106
runtime.mallocgc(0x20, 0x61dba0, 0x1, 0xc00bffffe0)
	/usr/local/go/src/runtime/malloc.go:903 +0x793 fp=0xc000522b90 sp=0xc000522af0 pc=0x40ba53
runtime.newobject(0x61dba0, 0xc00bffffe0)
	/usr/local/go/src/runtime/malloc.go:1032 +0x38 fp=0xc000522bc0 sp=0xc000522b90 pc=0x40be38
cmd/link/internal/ld.stkcheck(0xc0004d6000, 0xc008b2eb60, 0x0, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1893 +0x14a fp=0xc000522c80 sp=0xc000522bc0 pc=0x57555a
cmd/link/internal/ld.(*Link).dostkcheck(0xc0004d6000)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1818 +0x218 fp=0xc000522ce8 sp=0xc000522c80 pc=0x575378
cmd/link/internal/ld.Main(0x7cfc20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64ddf0, 0x1b, 0x64af34, 0x14, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:220 +0xa9a fp=0xc000522e80 sp=0xc000522ce8 pc=0x58267a
main.main()
	/usr/local/go/src/cmd/link/main.go:65 +0x227 fp=0xc000523f98 sp=0xc000522e80 pc=0x5da857
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000523fe0 sp=0xc000523f98 pc=0x42bae7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000523fe8 sp=0xc000523fe0 pc=0x456af1
exit status 2
ERROR: Service 'caddy' failed to build: The command '/bin/sh -c apk add --no-cache     openssh     git     build-base &&     go get github.com/abiosoft/caddyplug/caddyplug     && caddyplug install-caddy     apk del build-base' returned a non-zero code: 1
`

**Comment by zoulux** [comment]
me too ，How do you solve？

**Comment by MinhNinja** [comment]
I also got this issue.
Any one has solved it successfully ?
Thanks for any support.

**Comment by betoflakes** [comment]
[This worked](https://github.com/laradock/laradock/issues/2019#issuecomment-478337248)
