### ISSUE TITLE
Can not connect mysql to sequel pro, phpmyadmin, or while trying to migrate DB using artisan

### ISSUE THREAD

**Issue by corbin88** [laradock/laradock#1839]
### Info:
- Docker version Docker version 18.06.1-ce, build e68fc7a
- System info Mac
- Laravel 5.7

### Issue:

**Sequel Pro**

> Unable to connect to host 127.0.0.1, or the request timed out.
> 
> Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).
> 
> MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)

**Migrating Database**

>  Illuminate\Database\QueryException  : SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)
> 
>   at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
>     660|         // If an exception occurs when attempting to run a query, we'll format the error
>     661|         // message to include the bindings with SQL, which will make this exception a
>     662|         // lot more helpful to the developer instead of just the database's errors.
>     663|         catch (Exception $e) {
>   > 664|             throw new QueryException(
>     665|                 $query, $this->prepareBindings($bindings), $e
>     666|             );
>     667|         }
>     668| 
> 
>   Exception trace:
> 
>   1   PDOException::("PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]")
>       /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
> 
>   2   PDO::__construct("mysql:host=mysql;port=3306;dbname=homestead", "homestead", "secret", [])
>       /var/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
> 
>   Please use the argument -v to see more details.

**While trying to log in to phpmyadmin on localhost:8080**

I'm getting a server input field on the login screen that I've never seen before. I get a variety of errors trying to login. 
_____

### Other issues I've Explored That Could Relate

MySql 5.8 does not yet work with sequel pro [Issue 1392](https://github.com/laradock/laradock/issues/1392) I took steps to change mysql 5.8 to 5.7 and ran into [issue 1391](https://github.com/laradock/laradock/issues/1391)

It looks like I'm running 5.7 from the instructions in issue 1391. 

`docker inspect d52e8d7638d5`

```
"Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "MYSQL_MAJOR=5.7",
                "MYSQL_VERSION=5.7.23-1debian9",
                "TZ=UTC"
            ],
```
How do I get mysql to work?

**Comment by alainperrier** [comment]
I have the same problem. 
**I found that it doesn't work when I use the build parameter from a docker compose file**
docker-compose.yml
```
  mysql:
    build:
      context: ./mysql
```
Dockerfile (in /mysql)
```
FROM mysql:5.7
```
Result (sequel pro)
> MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)

**But it works when I use the image parameter from a docker compose file**
docker-compose.yml
```
  mysql:
    image: mysql:5.7
```
Result (sequel pro)

> I can connect to MySQL

**Comment by Hironate** [comment]
@corbin88  post your laravel ENV file. 

Enter container name as DATABASE_HOST

ssh into workspace container and then run migration command

`docker-compose exec workspace bash` and then `migration command`

**Comment by kimett** [comment]
Original issue comes from this?:
https://stackoverflow.com/questions/50026939/php-mysqli-connect-authentication-method-unknown-to-the-client-caching-sha2-pa
