### ISSUE TITLE
Php 7.2 XDebug install error

### ISSUE THREAD

**Issue by Inkognitoo** [laradock/laradock#1847]
### Info:
- Docker version: 
Docker version 17.12.1-ce, build 7390fc6
- Laradock commit: 
9cfe5c61565a77b4da40817f3e1d45e18ef5920d
- System info (Mac, PC, Linux): 
Ubuntu 18.04
- System info disto/version: 

### Issue:
I can't install Xdebug when I'm using php 7.2
_____

### Expected behavior:
Successful build
_____

### Reproduce:
PHP_VERSION=7.2
WORKSPACE_INSTALL_XDEBUG=true
_____

### Relevant Code:

```
Step 60/179 : ARG INSTALL_XDEBUG=false
 ---> Using cache
 ---> f1c0af719c3b
Step 61/179 : RUN if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi
 ---> Running in 2895b9d82cec
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  php-xdebug
0 upgraded, 1 newly installed, 0 to remove and 110 not upgraded.
Need to get 915 kB of archives.
After this operation, 5,325 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php-xdebug amd64 2.6.0+2.5.5-1+ubuntu16.04.1+deb.sury.org+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php-xdebug_2.6.0+2.5.5-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_XDEBUG} = true ]; then     apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug &&     sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini &&     echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc ;fi' returned a non-zero code: 100

```

**Comment by Zhong1002** [comment]
the source has updated http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/,so you get 404
edit file laradock/workspace/Dockerfile line 261
`apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug && \`
to
`apt-get update && apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug && \`
then run docker-compose build workspace

**Comment by Inkognitoo** [comment]
Thank you.
I literally just got the same error when installing the ssh package.
Corrected it the same way as you advised here. It may be worthwhile to re-trigger an update when installing each package.
What do you think?

**Comment by manierim** [comment]
For the records, as of today apt-get update still needed (line is now 312)

**Comment by wesselstam** [comment]
This problem is still present in the latest version. Maybe it's good to reopen this issue?

**Comment by Inkognitoo** [comment]
@wesselstam  this is because cache. You need purge all docker images or add `apt-get update` before `apt get install` in error line

**Comment by Dailson** [comment]
Thank you!

**Comment by MiljkovicMarko** [comment]
This is still hapening...
