### ISSUE TITLE
mysql won't downgrade from 8 to 5.7

### ISSUE THREAD

**Issue by r00nscapenab** [laradock/laradock#1855]
### Issue:
i can't downgrade mysql 8 to 5.7

_____
### Relevant Code:
**.env file:** 
MYSQL_VERSION=5.7
MYSQL_DATABASE=biodidb
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

**then i did "docker-compose build --no-cache mysql" and got this:**
Building mysql
Step 1/9 : ARG MYSQL_VERSION=latest
Step 2/9 : FROM mysql:${MYSQL_VERSION}
 ---> 702fb0b7837f
Step 3/9 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Running in 4d329eae3c56
Removing intermediate container 4d329eae3c56
 ---> 8dea61fb4b87
Step 4/9 : ARG TZ=UTC
 ---> Running in 9f1aba1e54cb
Removing intermediate container 9f1aba1e54cb
 ---> 2509d15f1a07
Step 5/9 : ENV TZ ${TZ}
 ---> Running in 6ce1ca076a9f
Removing intermediate container 6ce1ca076a9f
 ---> 5dc677633cae
Step 6/9 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && chown -R mysql:root /var/lib/mysql/
 ---> Running in e896624dc915
Removing intermediate container e896624dc915
 ---> 5e999f074d28
Step 7/9 : COPY my.cnf /etc/mysql/conf.d/my.cnf
 ---> 769aab97d221
Step 8/9 : CMD ["mysqld"]
 ---> Running in 83afd25c3552
Removing intermediate container 83afd25c3552
 ---> e977217d11fa
Step 9/9 : EXPOSE 3306
 ---> Running in 27e4981a9d5f
Removing intermediate container 27e4981a9d5f
 ---> a95a67577259
Successfully built a95a67577259
Successfully tagged laradock_mysql:latest

**then i checked it by "docker inspect mysql" and still version 8:**

[
    {
        "Id": "sha256:2dd01afbe8df1fe326f6609c56b08beefc6bf254d28993263da188b8fbf1254d",
        "RepoTags": [
            "mysql:latest"
        ],
        "RepoDigests": [
            "mysql@sha256:811483efcd38de17d93193b4b4bc4ba290a931215c4c8512cbff624e5967a7dd"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-10-24T22:26:25.366603443Z",
        "Container": "21ecdcc2491314460345e673951f055b5b76fa4aef95c324687d7a2e12a58f20",
        "ContainerConfig": {
            "Hostname": "21ecdcc24913",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "33060/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "MYSQL_MAJOR=8.0",
                "MYSQL_VERSION=8.0.13-1debian9"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"mysqld\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:23ebb5c0c893698702420c945e5369aa52629db789e95842f2cd3473d616ae66",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.06.2-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "33060/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "MYSQL_MAJOR=8.0",
                "MYSQL_VERSION=8.0.13-1debian9"
            ],
            "Cmd": [
                "mysqld"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:23ebb5c0c893698702420c945e5369aa52629db789e95842f2cd3473d616ae66",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 485498316,
        "VirtualSize": 485498316,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/583680ec90f31ed394a467d3c91612296f069ccd2133ca45b0dcb58068dccf04/diff:/var/lib/docker/overlay2/f649115bf3ac6e0e5e17503bed5e78e975dec3615bac88ea9b0432219a7c1ce8/diff:/var/lib/docker/overlay2/77fc63bfb76f03747988fe09dd9fffa0c13aba88f85c0f368cf10638739c8071/diff:/var/lib/docker/overlay2/4ddcc1db7ca3b49586a8fdfff3d1d63cbc48365adcb3bb937f09a3c6146fe957/diff:/var/lib/docker/overlay2/9f47980ab98f0ffe0007e9f44033728be3a2420d81a482067864f4781d1818d0/diff:/var/lib/docker/overlay2/642735b745ea9cdac937537c84bdfe9122808f5640b38d9de3e163ffcecae18f/diff:/var/lib/docker/overlay2/c160d7f1c77a79c590614066fd48dcdf7aca85e2dcc34668e760ae252ada0156/diff:/var/lib/docker/overlay2/3049306261ab568a37a5ab857d215e2b69daf132ca40458ff71291aef2075f22/diff:/var/lib/docker/overlay2/60fc6392c3c204ca3d9a969ee01ada32f7f1f001988ebb41873c6ce8eca71844/diff:/var/lib/docker/overlay2/0d072123735d575c478c92f68612c789b93a0876104d557a6250154e06816930/diff:/var/lib/docker/overlay2/326ba80766e47bd00751d9d9b4d606aebe1193f81d788596d8f571017a71b38e/diff",
                "MergedDir": "/var/lib/docker/overlay2/a17af512b0d0246e2c18f73da78f5141b528c887fc3b99e18575e282c4973a54/merged",
                "UpperDir": "/var/lib/docker/overlay2/a17af512b0d0246e2c18f73da78f5141b528c887fc3b99e18575e282c4973a54/diff",
                "WorkDir": "/var/lib/docker/overlay2/a17af512b0d0246e2c18f73da78f5141b528c887fc3b99e18575e282c4973a54/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:237472299760d6726d376385edd9e79c310fe91d794bc9870d038417d448c2d5",
                "sha256:ebdd1217991da1723b94e0aa2dc12f959b957d9214d6de7863d6be5a9e0de353",
                "sha256:7332e314e51e07db5d294185f454382b08d4951058009b62f95812dc1e6ff431",
                "sha256:2039058a7b75d71d4123d0f33856f7b06ecdec1c60adfd1a68f1e12ebbefeef0",
                "sha256:cef03d1730e4b0696cb9226c2335e9bcd6389f7db1aa0dc600a61bc7430facde",
                "sha256:3538e779fb2898bfa017aece266a65a1f90285d0811c0d719bf0a4c0dece3528",
                "sha256:6ae996979161ac6ff3d87fd859b336e025abe62b476b9a6e31907d724c529f1b",
                "sha256:36d8a4e1f37125ad57d023e4755a49a527e53deae3d48cecc649190367c3681b",
                "sha256:57f27b056bcdaeec44e876e4b0cba6175b1fd0dc568237d249ff99f4c1297c7d",
                "sha256:dba2ff51a506a513a7b7d1b2516bad55829597631e705541077b21f037c956f6",
                "sha256:71f273c41192d85da4b4b8cb1d3820bfa83d25aa1f49b7f8a631b74f7e4bddbe",
                "sha256:fd8775ba5e74d5b15c5f2ee28dba7f276478b05f9ad05f24957ded880e30ef66"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by vladyslavstartsev** [comment]
In your `.env` file see the var called `DATA_PATH_HOST` and go to that folder, after that delete the mysql folder there and then do the `docker-compose build --no-cache mysql`

**Comment by goosmaster** [comment]
@vladyslavstartsev I have noticed that this won't always fix the problem, I've seen multiple macbooks simply ignoring the `${MYSQL_VERSION}` variable, even if I set it manually (in the `ARG MYSQL_VERSION=latest`) to a different version e.g. `5.7`

Behavior seen on:
MacOS Mojave
Version 10.14

it was fixed when I changed
`FROM mysql:${MYSQL_VERSION}`
to
`FROM mysql:5.7`
(but I forgot to delete the `DATA_PATH_HOST` folder, so I got another error, but that is not the problem, because once I updated the `FROM mysql` to my specific version, it pulled in the correct version instead  of the `latest`)

I expect it has something to do with macOS parsing the variable, but I have too little knowledge of macOS to verify this.

**Comment by freefzl** [comment]
@vladyslavstartsev you are right

**Comment by pbtintas** [comment]
.env file

MYSQL_VERSION=5.7

and 
run 

docker-compose build mysql

**Comment by renandame** [comment]
None of above worked to me. I had to edit the first line of /mysql/Dockerfile, where mysql version was still set to latest.

**Comment by takashi-kobayashi00** [comment]
@renandame 
You should remove volume and data

`docker volume rm laradock_mysql`
`sudo rm -rf ~/.laradock/data/mysql/`

**Comment by jtanaka** [comment]
Simply I needed just only @pbtintas solution.  
Its not need to edit `mysql/dockerfile`.

But, If you built once with 8.x, you have to remove cache, container and image correctly.  
Below is the list of the sfuffs have to be removed.

- MySQL host data specified by `DATA_PATH_HOST` in `.env`
- The container you have built with `docker-compose up..`
    - like `laradock_mysql` not `mysql`
- The Image you have built with `docker-compose up..`
    - like `laradock_mysql` not `mysql`

**Comment by thbighead** [comment]
For those who are still struggling, beware with docker image and container caching.
Running docker-compose down and removing ~/.laradock/data/mysql is not enough.
You should destroy your mysql containers and mysql images just after that.
Also if you tried in many ways to fix this problem, maybe you have made a mess into your containers and images list just like me. So I just removed all my containers and images.
You can get the commands from this link: https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
**JUST REMEMBER: YOU MUST REMOVE THE CONTAINERS BEFORE REMOVING THE IMAGES**
