### ISSUE TITLE
Unable to start Jenkins in Laradock

### ISSUE THREAD

**Issue by eokorieFA** [laradock/laradock#1861]
### Info:
- Docker version (`$ docker --version`): Docker version 18.06.1-ce, build e68fc7a
- Laradock commit (`$ git rev-parse HEAD`): 538b6aa0cd484c475c5c537a763e4e1fe330fcae
- System info (Mac, PC, Linux): PC 
- System info disto/version: Windows 10

### Issue:

_____ Unable to start Jenkins.  

### Expected behavior:

_____ I should be able to access the Jenkin UI via localhost:8090.

### Reproduce:

_____ docker-compose up -d jenkins

### Relevant Code:

```
λ docker-compose up jenkins
Recreating laradock_jenkins_1 ... done
Attaching to laradock_jenkins_1
: invalid option       | /bin/bash: -
laradock_jenkins_1 exited with code 1
```

**Comment by Ttdnts** [comment]
It was caused by git, which auto transformed LF to CRLF on windows.
I solved problem by:
git config --global core.autocrlf false
then re clone & build the project

**Comment by fero** [comment]
@Ttdnts it works. gG

**Comment by gmatkowski** [comment]
> It was caused by git, which auto transformed LF to CRLF on windows.
> I solved problem by:
> git config --global core.autocrlf false
> then re clone & build the project
> @eokorieFA

Can you please tell me what EXACTLY have you done to finally make it work? I have same issue and can't really figure it out :-/

Have you cloned whole LARADOCK one more time after this command:
git config --global core.autocrlf false

? Or what?

**Comment by fero** [comment]
@gmatkowski like @Kamicloud said, on your windows machine run `
git config --global core.autocrlf false` in command line and then re-clone laradock and rebuild it.

**Comment by gmatkowski** [comment]
Oh, ok RE-CLONE laradock - that's fine, I'm gonna try :-) thx!
