### ISSUE TITLE
xDebug 404 not found on laradock/workspace:2.2

### ISSUE THREAD

**Issue by ScottChayaa** [laradock/laradock#1865]
### Info:
- Docker version (`$ docker --version`):  18.06.1-ce
- Laradock commit (`$ git rev-parse HEAD`): 538b6aa0cd484c475c5c537a763e4e1fe330fcae
- System info (Mac, PC, Linux): Linux
- System info disto/version:  

### Reproduce:
`Note : $LARADOCK_PHP_VERSION = 7.1`

1. laradock workspace use ` laradock/workspace:2.2-x.x`, so : 
```
docker run -d --name workspace7.1 laradock/workspace:2.2-7.1
```

2. exec in
```
docker exec -it workspace7.1 bash
```

3. install xdebug : I copy this script from `./workspace/Dockerfile`  on `xDebug` tag
```
apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug
```

4. get 404 error : 
```sh
root@716d4de2e721:/# apt-get install -y php7.1-xdebug
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php-xdebug' instead of 'php7.1-xdebug'
The following NEW packages will be installed:
  php-xdebug
0 upgraded, 1 newly installed, 0 to remove and 28 not upgraded.
Need to get 915 kB of archives.
After this operation, 5,325 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php-xdebug amd64 2.6.0+2.5.5-1+ubuntu16.04.1+deb.sury.org+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php-xdebug_2.6.0+2.5.5-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by ScottChayaa** [comment]
I found I lose these parts in my script : 
```sh
# always run apt update when start and after add new source list, then clean up at end.
    RUN apt-get update -yqq && \
    pecl channel-update pecl.php.net && \
    groupadd -g ${PGID} laradock && \
    useradd -u ${PUID} -g laradock -m laradock -G docker_env && \
    usermod -p "*" laradock

....

# Clean up
    RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    rm /var/log/lastlog /var/log/faillog
```

Conclusion : It's my mistake

**Comment by vitomeuli** [comment]
Very similar problem for me, but 2 years later.
Rebuilding my workspace to add Xdebug failed with following error:
`Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-xdebug amd64 2.9.6+2.8.1+2.5.5-3+ubuntu18.04.1+deb.sury.org+1
  404  Not Found [IP: 91.189.95.83 80]`

The solution suggested by @ScottChayaa works for me: adding an `apt-get update` before the real install in the workspace Dockerfile like so:
`###########################################################################
# xDebug:
###########################################################################

USER root

ARG INSTALL_XDEBUG=false

RUN if [ ${INSTALL_XDEBUG} = true ]; then \
    # Load the xdebug extension only with phpunit commands
    apt-get update && \
    apt-get install -y php${LARADOCK_PHP_VERSION}-xdebug && \
    sed -i 's/^;//g' /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-xdebug.ini \
;fi
`
