### ISSUE TITLE
Parameter DOCKER_SYNC_STRATEGY is set twice in env-example 

### ISSUE THREAD

**Issue by masterjus** [laradock/laradock#1868]
### Info: 
Doesn't matter

### Issue:
Parameter DOCKER_SYNC_STRATEGY is set twice in env-example 
_____

### Expected behavior:
Parameter set once

### Reproduce:

_____

### Relevant Code:
https://github.com/laradock/laradock/blob/master/env-example#L381

**Comment by vladyslavstartsev** [comment]
already solved in https://github.com/laradock/laradock/pull/1866
waiting to be merged
