### ISSUE TITLE
Problem start nginx, php-fpm

### ISSUE THREAD

**Issue by uhgringow** [laradock/laradock#1872]
### Info:
- Docker version 18.06.1-ce, build e68fc7a
- Laradock commit git rev-parse HEAD 85c57a0b6fa3af2358e524010b95970ff9677a1b
- System info PC 
- System info Windows/10: 

### Issue:
configure: error: libxml2 not found. Use --with-libxml-dir=<DIR>
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c docker-php-ext-install pdo_mysql mysqli mbstring pdo tokenizer xml   && docker-php-ext-install pdo_pgsql   && docker-php-ext-configure gd     --enable-gd-native-ttf     --with-jpeg-dir=/usr/lib     --with-freetype-dir=/usr/include/freetype2 &&     docker-php-ext-install gd' returned a non-zero code: 1

**Comment by bestlong** [comment]
update your laradock and build again

`docker-compose build --no-cache nginx php-fpm`
