### ISSUE TITLE
[How-To] Using the dump-server

### ISSUE THREAD

**Issue by ghost** [laradock/laradock#1873]
Because the Symfony var-dump-server only checks for tcp://localhost:9912, running dump-server in the workspace or in the host machine won't work, since they are on a different IP address to the dumping client. 

The solution is to run the dump-server in the php-fpm container. 

```bash
docker exec -it laradock_php-fpm_1 /var/www/artisan dump-server
```
You should change the container name to your respective container.

**Comment by dungna83** [comment]
Work like a champ:
`$sudo docker-compose exec  php-fpm bash
$cd path_to_code_base
$php artisan dump-server
`

**Comment by megaxlr** [comment]
Yikes. Don't do `sudo docker-compose`. It will mess up your permissions big time. you should add your own user to the docker group on your system. 

On July 9, 2019 11:21:11 AM GMT+02:00, "dung.na" <notifications@github.com> wrote:
>Work like a champ:
>`$sudo docker-compose exec  php-fpm bash
>$cd path_to_code_base
>$php artisan dump-server
>`
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/laradock/laradock/issues/1873#issuecomment-509564166

--
Yours Sincerely,
MegaXLR

**Comment by glorand** [comment]
docker-compose exec --workdir /var/www/project  php-fpm  php artisan dump-server

**Comment by lanphan** [comment]
Not an issue anymore, close this
