### ISSUE TITLE
E: Unable to locate package php7.2-phpdbg

### ISSUE THREAD

**Issue by ludo237** [laradock/laradock#1876]
### Info:
- Docker version (`$ docker --version`): Docker version 18.06.1-ce, build e68fc7a
- Laradock commit (`$ git rev-parse HEAD`): 538b6aa0cd484c475c5c537a763e4e1fe330fcae
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

### Issue:

When you try to install PHPDBG on php-fpm it fails
_____

### Expected behavior:

PHPDBG installed inside php-fpm container
_____

### Reproduce:

- Enable `PHP_FPM_INSTALL_PHPDBG=true` in you `.env` file
- Build `docker-compose build php-fpm`
_____

### Relevant Code:

I guess the problem is here `php-fpm/Dockerfile`

```
###########################################################################
# Phpdbg:
###########################################################################

ARG INSTALL_PHPDBG=false

RUN if [ ${INSTALL_PHPDBG} = true ]; then \
    # Load the xdebug extension only with phpunit commands
    apt-get install -y --force-yes php${LARADOCK_PHP_VERSION}-phpdbg \
;fi
```

**Comment by nerijuso** [comment]
Suggest to update laradock version.

**Comment by mprocner** [comment]
Hi, I have the same problem with newest laradock version. Any ideas?

**Comment by bestlong** [comment]
try `docker-compose build --no-cache php-fpm`

**Comment by masterjus** [comment]
I've changed the command in Dockerfile to `apt-get install -y --force-yes php-phpdbg` and it shows that phpdbg is available only for php7.3 and 7.0. Looks like debian repository doesn't have php7.2-phpdbg package.

**Comment by engmsaleh** [comment]
This is what solved my problem, I have adjusted the lines to be 

```RUN if [ ${INSTALL_PHPDBG} = true ]; then \
    # Load the xdebug extension only with phpunit commands
    rm /etc/apt/preferences.d/no-debian-php && \
        apt-get update -yqq && \
    apt-get install -y --force-yes php${LARADOCK_PHP_VERSION}-phpdbg \
;fi
```
