### ISSUE TITLE
Can't curl on same server IP Address from php-fpm bash

### ISSUE THREAD

**Issue by Hironate** [laradock/laradock#1885]
Just installed fresh docker and docker-compose and laradock, pointed domain to server ip, spin up 

```
docker-compose up -d apache2 php-fpm
docker-compose exec php-fpm bash
```

now if i try to 
`curl MY_SERVER_IP`

it gets timeout. there is some fundamental issue with network access. can anybody help ?

 @Mahmoudz can you plz check into issue. can't go ahead on production server. stuck on this issue.

**Comment by acharrex** [comment]
Try to run this command :

```
curl host.docker.internal
```
