### ISSUE TITLE
When I am modifying code in controllers,it doesn't work

### ISSUE THREAD

**Issue by ObrookO** [laradock/laradock#1886]
### Info:
- Docker version (18.06.1-ce): 
- System info (Mac): 
- System info macOS Mojave/10.14.1: 

### Issue:

When I am modifying the code in controllers, I hope it works immediately.
But I have to run command "docker-compose restart" to make it work.
What can I do to make it work immediately.

**Comment by jonasgoderis** [comment]
I'm dealing with the same issue. For some controllers in my application I also have to run 'docker-compose down' to see my changes. It's not happening with all controllers but with some of them. 

First I thought it was opcache but I've built my container again without opcache and the same issue is happening. 

### Info

- Docker version: 18.09.2, build 6247962
- System info: Mac OS Mojave 10.14.2
- Laradock commit: 61d7b18922006d582ae68ca0cdf5e202e5bcf08d

Maybe https://github.com/laradock/laradock/issues/1992 is related.

**Comment by claudiul93** [comment]
Hi,

I have the same issue in multiple project environment. Only first project does sync without any problem, but the other projects not.

Do you know if there is any update regarding this? Or any workaround?
