### ISSUE TITLE
workspace - Permission denied: '/etc/container_environment'

### ISSUE THREAD

**Issue by vlauciani** [laradock/laradock#1889]
### Info:
- Docker version (`$ docker --version`): `Docker version 18.06.1-ce, build e68fc7a`
- Laradock commit (`$ git rev-parse HEAD`): `5c41a4f3e9539fe479b62471b14e00d9ebc1d31d`
- System info (Mac, PC, Linux): Linux
- System info disto/version: Debian 8.11

### Issue:
This command, return a `Permission denied` error:
```
$ docker-compose up workspace
Creating network "laradockdante_default" with the default driver
Creating network "laradockdante_frontend" with driver "bridge"
Creating network "laradockdante_backend" with driver "bridge"
Creating laradockdante_docker-in-docker_1 ...
Creating laradockdante_docker-in-docker_1 ... done
Creating laradockdante_workspace_1 ...
Creating laradockdante_workspace_1 ... done
Attaching to laradockdante_workspace_1
workspace_1            | *** Killing all processes...
workspace_1            | Traceback (most recent call last):
workspace_1            |   File "/sbin/my_init", line 417, in <module>
workspace_1            |     main(args)
workspace_1            |   File "/sbin/my_init", line 333, in main
workspace_1            |     import_envvars(False, False)
workspace_1            |   File "/sbin/my_init", line 90, in import_envvars
workspace_1            |     for envfile in listdir("/etc/container_environment"):
workspace_1            |   File "/sbin/my_init", line 74, in listdir
workspace_1            |     return sorted(os.listdir(path))
workspace_1            | PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
laradockdante_workspace_1 exited with code 1
$
```

**Comment by voppe** [comment]
You can just revert [https://github.com/laradock/laradock/pull/1875/commits/aecea0262778fa7f7e26081030cb228213566676](this commit)

**Comment by voppe** [comment]
You can just revert this commit

https://github.com/laradock/laradock/pull/1875/commits/aecea0262778fa7f7e26081030cb228213566676

**Comment by Glen1023** [comment]
There's no running test case before approved.

**Comment by vlauciani** [comment]
The solution **2.** is preferred for me...

**Comment by ptcampbell** [comment]
Is this fixed?

**Comment by albakov** [comment]
**2** it works. Thank you very much bro.

p.s. Do not forget _docker-compose build workspace_ after update USER laradock -> USER root

**Comment by jonwhittlestone** [comment]
I couldn't get solution 2 to work so I just checked out [release v7.7.0](https://github.com/laradock/laradock/releases/tag/v7.7.0) and built, and it worked.

**Comment by vsamadian** [comment]
File and directory owners (User and Groups) must be laradock : laradock :

docker-compose exec workspace bash
chown -R laradock:laradock /var/www
