### ISSUE TITLE
building php-fpm with imagick on results in 404 package not found (solution in, PR needed?)

### ISSUE THREAD

**Issue by godbout** [laradock/laradock#1890]
### Info:
Docker version 18.06.1-ce, build e68fc7a

- Laradock commit (`$ git rev-parse HEAD`): c116d69418ed7bb11013afe92056f1acd65dd971
- System info (Mac, PC, Linux): macOS
- System info disto/version: 10.14.1 (18B75)

### Issue:
When building php-fpm with imagick on, getting a message (sorry, no copy) that the imagick package can't be found online (404.
_____

### Expected behavior:
Package gets installed.
_____

### Reproduce:
1. Clone latest version of Laradock (at time of writing this issue)
2. Build a php-fpm container.
_____

### Relevant Code:

The way to solve this issue is to do an `apt-get update` before installing imagick.

In the `php-fpm` Docker file, add the `apt-get update` line:

`
RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get update && \
    apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick \
;fi
`

So I wanna ask, is this a real issue and a PR is useful here, or is it me who is doing something wrong?

**Comment by nicogranelliAA** [comment]
I found a work around until this can get fixed:

set the variable PHP_FPM_INSTALL_IMAGEMAGICK in the .env file to false

**Comment by maurobaptista** [comment]
This is the errors returned: 
`E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/imagemagick-6-common_6.9.7.4+dfsg-11+deb9u5_all.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6-arch-config_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6-headers_6.9.7.4+dfsg-11+deb9u5_all.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-3_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6-headers_6.9.7.4+dfsg-11+deb9u5_all.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6.q16-3_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-3-extra_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/p/python3.5/python3.5-minimal_3.5.3-1_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickcore-6.q16-dev_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickwand-6.q16-dev_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/libmagickwand-dev_6.9.7.4+dfsg-11+deb9u5_all.deb  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/ghostscript/libgs9-common_9.20~dfsg-3.2+deb9u2_all.deb  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/ghostscript/libgs9_9.20~dfsg-3.2+deb9u2_amd64.deb  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/ghostscript/ghostscript_9.20~dfsg-3.2+deb9u2_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/imagemagick-6.q16_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/i/imagemagick/imagemagick_6.9.7.4+dfsg-11+deb9u5_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get install -y libmagickwand-dev imagemagick' returned a non-zero code: 100
`

As far as I could see, in it is not available the file with 5, only with 6. (...deb9u**5**all.deb)

 http://security-cdn.debian.org/pool/updates/main/i/imagemagick/imagemagick-6-common_6.9.7.4+dfsg-11+deb9u5_all.deb

**Comment by maurobaptista** [comment]
Btw, this solution here solved for me: https://github.com/laradock/laradock/issues/1730

**Comment by godbout** [comment]
I solved it by add an `apt-get update` in my fork, in the `php-fpm` Docker file.

`
RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get update && \
    apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick \
;fi
`

**Comment by bestlong** [comment]
try `docker-compose build --no-cache php-fpm`
