### ISSUE TITLE
Session does not working.

### ISSUE THREAD

**Issue by arcarruda** [laradock/laradock#1896]
# Info:
- Docker version (`$ docker --version`): Docker version 18.09.0, build 4d60db4
- Laradock commit (`$ git rev-parse HEAD`): d8c36ab86007f04293d380bcf8325cb70c76fdd0
- System info (Mac, PC, Linux): Mac

### Issue:
The session of my application does not working. It is affecting my Auth session.
I couldn't anymore authenticate.
I have attempted to use with Redis but it keep does not working.
Thank you for your help...

### Reproduce:
I cloned the Laradock repository and up the containers mysql nginx.

### Relevant Code:
docker-compose up -d nginx mysql

$request->session()->get('key'); // empty
$request->session()->put('key', 'value'); // does not persist
$request->session()->get('key'); // value

**Comment by arcarruda** [comment]
Sorry, my fault...

**Comment by tripex** [comment]
I'm experiencing this as well, have you found any solution to this?
