### ISSUE TITLE
php-nginx exit 0

### ISSUE THREAD

**Issue by metal3d** [LaraDock/laradock#19]
The php-nginx container, using docker-compose, returns "exit 0" since the last change (one day).

And you didn't tag older version, so I cannot run my project now... damned.

Could you please:

- tag images
- fix the last one

Thanks a lot :)

**Comment by Mahmoudz** [comment]
@metal3d I reverted the last contribution to that image. Could you please try it again and let me know if it works now. Thanks

**Comment by metal3d** [comment]
No problem at this time, I just cloned docker-images repository, checkout -2 commits and used "build" instead of "image" in docker-compose.yml

```yaml
    -build: ../docker-images/phpnginx
```

I'll check later, I'm developping an urgent website :)

Thanks for you reactivity :+1: 

Anyway, tagging docker images and using automatic builds is the way to go IMHO.

**Comment by Mahmoudz** [comment]
Cool, I tagged the `docker-images` repo now.
