### ISSUE TITLE
Caddy and beanstalkd-console cannot up

### ISSUE THREAD

**Issue by redstrike** [LaraDock/laradock#190]
```sh
docker-compose up caddy

Creating laradock_volumes_source_1
Creating laradock_workspace_1
Creating laradock_php-fpm_1
Creating laradock_caddy_1

ERROR: for caddy  Cannot start service caddy: Container command '/usr/bin/caddy' not found or does not exist.
ERROR: Encountered errors while bringing up the project.
```
beanstalkd-console
```sh
Step 6 : RUN apt-get remove --purge -y curl &&
 ---> Running in 84a780961587
/bin/sh: 1: Syntax error: end of file unexpected
ERROR: Service 'beanstalkd-console' failed to build: The command '/bin/sh -c apt-get remove --purge -y curl &&' returned a non-zero code: 2
```
I cannot "docker exec" to caddy container to debug.

**Comment by Mahmoudz** [comment]
Do you have the latest LaraDock version?

**Comment by redstrike** [comment]
Yes, I follow the installation guide yesterday.
```sh
git clone https://github.com/LaraDock/laradock.git
```
And how can I "docker exec" to a specific container? It looks like that the console is freezing after I submit a command.

**Comment by redstrike** [comment]
Sure. I don't know why suddenly Caddy works, and I re-checked laradock dir to make sure that I didn't make any changes to caddy Dockerfile. I saw that I just edit some PHP settings in docker-compose.yml

Then I removed laradock and laravel src dir. Re-install via git clone again:

```sh
$ git clone https://github.com/LaraDock/laradock.git

Cloning into 'laradock'...
remote: Counting objects: 1122, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 1122 (delta 32), reused 0 (delta 0), pack-reused 1050
Receiving objects: 100% (1122/1122), 319.35 KiB | 160.00 KiB/s, done.
Resolving deltas: 100% (501/501), done.
Checking connectivity... done.

$ cd laradock
$ docker-compose up -d caddy mariadb

Creating network "laradock_default" with the default driver
Creating laradock_volumes_data_1
Creating laradock_volumes_source_1
Creating laradock_workspace_1
Creating laradock_mariadb_1
Creating laradock_php-fpm_1
Creating laradock_caddy_1

ERROR: for caddy  Cannot start service caddy: Container command 'caddy' not found or does not exist.
ERROR: Encountered errors while bringing up the project.

$ docker-compose down
$ docker run -itd laradock_caddy
$ docker exec -it {caddy_container_id} /bin/bash
rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/bash\": stat /bin/bash: no such file or directory"
``` 
Again, caddy doesn't suddenly work anymore :(

**Comment by redstrike** [comment]
Updated: I am sure that Caddy cannot work if the laravel src project is not the parent of laradock dir.

I git clone a separate laradock... up... error.
Then I try move that laradock dir inside a newly created laravel project... up... ok.

Finally, I docker-compose down and moved laradock outside again... up... error.

So that is the source of the problem. I am an all-new laravel user, so I don't have an existing laravel project.

**Comment by computerfr33k** [comment]
where are you storing your laradock folder. Because by default it needs to be in the root of the laravel project since it mounts `../` to `/var/www/laravel` in the container(s).
ex:
```bash
app/
laradock/
.env
...
```

**Comment by redstrike** [comment]
@computerfr33k 
```
$HOME/laradock
$HOME/laravel-project
```
Yes, if I place laradock in the root of laravel project, caddy works normally.

**Comment by Mahmoudz** [comment]
This was fixed.
1. Upgrade your LaraDock `git pull origin master`
2. Rebuild your containers `docker-compose build --no-cache caddy beanstalkd-console `
3. Try again.. best of luck :)
