### ISSUE TITLE
laradock_nginx_1 exited with code 2

### ISSUE THREAD

**Issue by pmua** [laradock/laradock#1902]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.09.0, build 4d60db4
- Laradock commit (`$ git rev-parse HEAD`):  d8c36ab86007f04293d380bcf8325cb70c76fdd0
- System info (Mac, PC, Linux):  PC
- System info disto/version:  Windows 10  Pro (1803, 17134.407)

### Issue:
Y:\vhosts\laradock>docker-compose up nginx
WARNING: The PHP_FPM_INSTALL_TOKENIZER variable is not set. Defaulting to a blank string.
laradock_workspace_1 is up-to-date
Starting laradock_docker-in-docker_1 ... done
Starting laradock_php-fpm_1          ... done
Starting laradock_nginx_1            ... done
Attaching to laradock_nginx_1
nginx_1                | /opt/startup.sh: line 2: $'\r': command not found
nginx_1                | /opt/startup.sh: line 10: syntax error: unexpected end of file
laradock_nginx_1 exited with code 2

https://stackoverflow.com/questions/53356394/cant-get-nginx-to-run-under-docker-environment-on-windows-for-unknown-reason

convert laradock\nginx\startup.sh file's windows style line endings to linux style line endings solve the problem
_____

### Expected behavior:
nginx start
_____

### Reproduce:
install docker on windows 10
_____

**Comment by mouyong** [comment]
i have the same problem! Normal file format after switching from DOS to UNIX. 

You can close the issue.

**Comment by mouyong** [comment]
this is a correct answers.

> convert laradock\nginx\startup.sh file's windows style line endings to linux style line endings solve the problem

**Comment by ABQJuan** [comment]
I am having the exact same issue. 

If this is solution

> convert laradock\nginx\startup.sh file's windows style line endings to linux style line endings solve the problem

How do you do it? Please explain.

**Comment by ABQJuan** [comment]
I was able to resolve this issue by opening  laradock\nginx\startup.sh with Notepad++ and changing the EOL setting there. Any more elegant solution?

**Comment by arthurching** [comment]
open vim nginx/startup.sh

:set fileformat=unix
:w startup.sh

docker-compose up --build nginx
docker-compose restart
docker-compose ps

**Comment by GinoPane** [comment]
Shouldn't the fixed file be committed?
