### ISSUE TITLE
Incorrect PHP versions launched

### ISSUE THREAD

**Issue by marast78** [laradock/laradock#1906]
### Info:
- Docker version `18.09.0`: 
- Laradock commit `d8c36ab86007f04293d380bcf8325cb70c76fdd0`: 
- System info `Linux`: 
- System info disto/version: Ubuntu 18.04 

### Issue:
In my .env I've set PHP_VERSION=7.2 but when I launch my app via http and check php version
I see PHP 5.6 :/
_____

### Expected behavior:

If I've set PHP_VERSION 7.2, nginx should use PHP  7.2 (not 5.6)
_____

### Reproduce:

I've installed laradock with php 7.2 and everything was ok, but when I've installed the second laradock with php 5.6 occurs my issue. It makes that workspace has php 7.2 and via http works php 5.6 :-1: It works the same via each laradock.

**Comment by bestlong** [comment]
after .env changed, need `docker-compose down` and `docker-compose up -d XXX YYY`.

**Comment by marast78** [comment]
@bestlong your tip did not help me to fix this issue. I have two separated folders in one I use PHP 7.2 and in the second PHP 5.6. Even if I do docker-compose up in the folder with PHP 5.6 works PHP 7.2. I have to each time to build with --no-cache my environment to set correct PHP version.

**Comment by bestlong** [comment]
hm...
if workspace and php-fpm is run PHP 7.2  and add one more php56-fpm
`docker-compose up -d nginx php56-fpm`
can that help you?

**Comment by marast78** [comment]
@bestlong how I can do it if in .env I see:

`# Select the PHP Interpreter. Accepted values: hhvm - php-fpm
PHP_INTERPRETER=php-fpm
`

**Comment by marast78** [comment]
I have to do each time docker-compose build php-fpm workspace nginx and then up. It solved my issue :+1:

**Comment by bestlong** [comment]
> @bestlong how I can do it if in .env I see:
> 
> ```
> # Select the PHP Interpreter. Accepted values: hhvm - php-fpm
> PHP_INTERPRETER=php-fpm
> ```

This part has not been processed.

**Comment by bestlong** [comment]
if you change .env PHP_VERSION, you need build all php related services.
like workspace, php-fpm, php-worker, laravel-horizon.
and suggest build with `--no-cache` option.

**Comment by marast78** [comment]
I think we can close this issue.
If you have my issue you should before docker-compose -d up .. run docker-compose build ...
