### ISSUE TITLE
How to enable php-gettext extention?

### ISSUE THREAD

**Issue by AratKruglik** [laradock/laradock#1909]
### Info:
- Docker version (`$ docker --version`): 18.09.0
- Laradock commit (`$ git rev-parse HEAD`): d8c36ab86007f04293d380bcf8325cb70c76fdd0
- System info (Mac, PC, Linux): Windows

### Issue:
I have installed Xinax\LaravelGettext package and it throws an exception:

FatalThrowableError in Gettext.php line 195:
Call to undefined function Xinax\LaravelGettext\bindtextdomain()

How to enable php-gettext extention?
_____

### Reproduce:
docker-compose up -d nginx workspace php-fpm mysql

**Comment by nmike** [comment]
first - need install it
fastway - add here https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile#L45 something like 

```
      # Install gettext extension
      docker-php-ext-install gettext && \
```

and rebuild container
