### ISSUE TITLE
You should add "extension=redis.so" to php.ini

### ISSUE THREAD

**Issue by gitzxd** [laradock/laradock#1913]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by GinoPane** [comment]
Isn't it working?

![image](https://user-images.githubusercontent.com/3897579/49882327-725fa400-fe41-11e8-8494-b2d102fb2e2d.png)

**Comment by bestlong** [comment]
build warning ?
