### ISSUE TITLE
PHP 7.1.3 version needed

### ISSUE THREAD

**Issue by AratKruglik** [laradock/laradock#1915]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.0, build 4d60db4
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): d8c36ab86007f04293d380bcf8325cb70c76fdd0
- System info disto/version: 

### Issue:
I need PHP (PHP-FPM) version 7.1.3. But in container I see that my PHP version is 7.1.25.
.env
```
# Select a PHP version of the Workspace and PHP-FPM containers (Does not apply to HHVM). Accepted values: 7.2 - 7.1 - 7.0 - 5.6
PHP_VERSION=7.1

### PHP Interpreter #######################################

# Select the PHP Interpreter. Accepted values: hhvm - php-fpm
PHP_INTERPRETER=php-fpm
```

How I can upgrade my PHP version to 7.1.3?

**Comment by roelgonzalez** [comment]
Version 7.1.25 is a higher version than version 7.1.3
