### ISSUE TITLE
cannot start nginx  "RUN APK" fail in dockerfile

### ISSUE THREAD

**Issue by absulation** [LaraDock/laradock#192]
I setup this behind proxy server in my office
 please see a dockerfile

 `FROM`

 nginx:alpine

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

ENV http_proxy 'http://mg:Pass1234@10.78.2.60:9090'
ENV https_proxy 'http://mg:Pass1234@10.78.2.60:9090'

ADD nginx.conf /etc/nginx/
ADD laravel.conf /etc/nginx/conf.d/laravel.conf

ARG PHP_UPSTREAM=php-fpm

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && adduser -D -H -u 1000 -s /bin/bash www-data \
    && rm /etc/nginx/conf.d/default.conf \
    && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf

CMD ["nginx"]

EXPOSE 80 443
`

and see the error

> Step 8 : RUN apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data     && rm /etc/nginx/conf.d/default.conf     && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf
 ---> Running in 204aabee34a1
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/main: Permission denied
WARNING: Ignoring APKINDEX.5a59b88b.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/community: Permission denied
WARNING: Ignoring APKINDEX.7c1f02d6.tar.gz: No such file or directory
2 errors; 31 distinct packages available
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data     && rm /etc/nginx/conf.d/default.conf     && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf' returned a non-zero code: 2

>

**Comment by madonion** [comment]
I have the same error.

**Comment by computerfr33k** [comment]
@madonion are you behind a proxy as well? Because nginx builds just fine for me, but i'm not behind a proxy. Unfortunately I do not know how to get alpine linux to work with a proxy so you'd have to do some digging around for that.

**Comment by madonion** [comment]
> @computerfr33k I am not. I got the same error on a debian 8.5 and an ubuntu 16.04. Both are behind a router doing NAT.  Apparently it has to do with the alpine linux image introduced in #184 (v.3.1)

**Comment by computerfr33k** [comment]
I just tried it on my ubuntu 16.04 server and it worked just fine there as well, and I am also behind a NAT router with ATT Uverse. Which version of docker & docker-compose are you using?

**Comment by madonion** [comment]
well, the containers have no internet access. Definitely an error in my configuration. It's something I must have been done wrong twice, though.
Docker version 1.12.0, build 8eab29e
docker-compose version 1.8.0, build f3628c7

**Comment by computerfr33k** [comment]
You could use this as a workaround and it should work, it just doesn't install the bash shell (which is only useful if you want to log into the container and run commands.).

```Dockerfile
FROM nginx:alpine

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

ADD nginx.conf /etc/nginx/
ADD laravel.conf /etc/nginx/conf.d/laravel.conf

ARG PHP_UPSTREAM=php-fpm

RUN adduser -D -H -u 1000 www-data \
    && rm /etc/nginx/conf.d/default.conf \
    && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf

CMD ["nginx"]

EXPOSE 80 443
```

As for the actual issue, I'm not sure why your container isn't getting an internet connection as it must be something wrong with your docker setup. If you can, try setting up a new machine or a VM and see if it works on a fresh install.

**Comment by madonion** [comment]
Well, I think it all happens because my ISP drops packages with TTL smaller than 63. I will append a rule to the firewall and I hope I'll fix it.

**Comment by absulation** [comment]
@computerfr33k that work for me thanks!!
