### ISSUE TITLE
Docker machine not mount data volume

### ISSUE THREAD

**Issue by datnq201088** [LaraDock/laradock#193]
I ssh container `nginx`, directory   `/var/www/laravel/`.  so i don't see any  files. How do I can mount my project into Machine container

**Comment by Mahmoudz** [comment]
New release of LaraDock was released today (LaraDock v4.0.1). 
1. Upgrade your LaraDock `git pull origin master`
2. Rebuild your containers `docker-compose build --no-cache`
3. Try again.. best of luck :)

**Comment by datnq201088** [comment]
Thank you so  much !
