### ISSUE TITLE
if should be closed after     docker-php-ext-enable apcu \ ";fi" cmon guys could not you notice that before since 8 years ????

### ISSUE THREAD

**Issue by RyannDev** [laradock/laradock#1940]
https://github.com/laradock/laradock/blob/bbff18c6314e72b7ac8fc60d84b6ad641ac2577e/php-fpm/Dockerfile#L553

**Comment by CreatopEJLin** [comment]
same issue!

**Comment by ludo237** [comment]
Apparently [it has been fixed](https://github.com/laradock/laradock/commit/ce7a29c66282e5f8060406ce7ff1827470495808) but no release has been made.
