### ISSUE TITLE
installation problem on ubuntu 18.04

### ISSUE THREAD

**Issue by ankit20893** [laradock/laradock#1943]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:
![screenshot from 2019-01-09 18-27-33](https://user-images.githubusercontent.com/12858398/50900908-9b715580-143c-11e9-97a5-62437c151d51.png)

```
// place a code sample here
```

**Comment by bestlong** [comment]
Hi @ankit20893 
i think will fixed by #1942. please update laradock

**Comment by ankit20893** [comment]
I have cloned the latest laradock as mentioned in documentation.Still i am
facing same issue.

**Comment by bestlong** [comment]
i run again manual all success and my step:
```
cd /tmp
git clone --depth 1 https://github.com/laradock/laradock.git
cd laradock
cp env-example .env
docker-compose build --no-cache --pull workspace php-fpm
```

**Comment by ankit20893** [comment]
Thanks Shao
Now it’s working fine.
