### ISSUE TITLE
Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_APCU} = true ]; then     pecl install apcu &&     docker-php-ext-enable apcu USER root' returned a non-zero co de: 2

### ISSUE THREAD

**Issue by jerry94test** [laradock/laradock#1944]
Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_APCU} = true ]; then     pecl install apcu &&     docker-php-ext-enable apcu USER root' returned a non-zero co
de: 2

system Linux miss-pc 4.19.13-1-MANJARO #1 SMP PREEMPT Sat Dec 29 15:43:56 UTC 2018 x86_64 GNU/Linux

**Comment by zswordsman** [comment]
I have encountered the same problem. Have you solved it?

**Comment by bestlong** [comment]
try `docker-compose build --no-cache php-fpm`

**Comment by nivin-studio** [comment]
> 尝试 `docker-compose build --no-cache php-fpm`

This answer will solve the problem.

**Comment by nivin-studio** [comment]
> try `docker-compose build --no-cache php-fpm`

This answer will solve the problem.

**Comment by nivin-studio** [comment]
> > try `docker-compose build --no-cache php-fpm`
> 
> This answer will solve the problem.

Or try add "USER root" In the "Dockerfile"

**Comment by nivin-studio** [comment]
> > try `docker-compose build --no-cache php-fpm`
> 
> This answer will solve the problem.

Or try add "USER root" In the Dockerfile
