### ISSUE TITLE
Workspace container runs as root

### ISSUE THREAD

**Issue by kauhat** [LaraDock/laradock#195]
Although the workspace container creates a `laradock` user, the container uses the root user.

* Using the `USER` command to run the container as `laradock` will prevent the container from starting as the Phusion init system will fail due to incorrect permissions.
* The workspace container would ideally be interactive only - having `docker-compose run workspace` take you straight to bash would be great.
* Removing the init system entirely is a possibility - but would this cause problems?

## Workaround
Specify the user using the `--user` argument of `docker exec`, i.e.

`docker exec -it --user laradock {Workspace-Container-Name} bash`

**Comment by computerfr33k** [comment]
I don't think it would be possible to remove the init system because you need a process to keep the container alive. And I did add the `docker-compose exec --user=laradock workspace bash` in the readme.

**Comment by garf** [comment]
But `--user=laradock` doesn't have ssh key of host machine.
