### ISSUE TITLE
There is no existing directory at "local path directory /MyLaravelApp/storage/logs" and its not buildable: Permission denied

### ISSUE THREAD

**Issue by agueroveraalvaro** [laradock/laradock#1952]
### Info:
- Docker version 18.09.0, build 4d60db4 
- MacOs Mojave

### Issue:
I have al fine but when i go to **localhost** appears:

> There is no existing directory at "local path directory /MyLaravelApp/storage/logs" and its not buildable: Permission denied

**Comment by Sander-Kastelein** [comment]
Try running:
`(sudo) docker-compose exec workspace bash`
this opens a bash environment within the container, then try running `artisan config:clear`, there might still be paths from your host system in the cache.

**Comment by alicfeng** [comment]
多谢！
thx~

**Comment by Hillaryudechukwu** [comment]
Possible fixes: 1 make sure that the path exists, 2 execute  " PHP artisan optimize: clear " in your work directory

**Comment by JoaoPedroMDP** [comment]
I had the same problem. All i had to do was to enter dock machine and use 'php artisan optimize:clear'.
