### ISSUE TITLE
New daily log files created by root instead of laradock user

### ISSUE THREAD

**Issue by ryancwalsh** [laradock/laradock#1953]
### Info:
- Docker version (`$ docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Laradock commit (`$ git rev-parse HEAD`): 85c57a0b6fa3af2358e524010b95970ff9677a1b
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04.3 LTS

### Issue:
I have a Laravel app running in a Laradock Docker container, and it creates a new log file every day. 

But recently* every day at midnight UTC, I need to go fix the permissions of the log file because it starts having errors:

> `UnexpectedValueException: The stream or file "/var/www/myapp/storage/logs/laravel-2019-01-07.log" could not be opened: failed to open stream: Permission denied`

When I run `ls -lah`, I see that the newly created daily log file is owned by "root" instead of "laradock"

So I run `chown laradock:laradock laravel-2019-01-07.log` to fix it. But then the problem happens again the next day.

*I said "recently", and the only change I know about is that I turned off my Digital Ocean server, resized it, turned it on again, and started up the Docker containers. 

Whatever I did during that process seemed to prevent new files from being created with the correct ownership.

How can I fix this?
_____

### Expected behavior:
All new files (logs etc) should be owned by laradock:laradock.
_____

### Reproduce:
Every day at midnight UTC, a new daily log file gets created by root instead of by laradock.
_____

### Relevant Code:

```
// none
```

**Comment by ronydebnath** [comment]
Give `chown laradock:laradock`  permission to storage/logs folder, this might solve your problem.

**Comment by ryancwalsh** [comment]
**New info:**

I also just noticed that this command no longer works:

`cd /apps/laradock/ && docker-compose exec workspace bash -c "cd /var/www/myapp/; npm run production"` and causes `bash: npm: command not found`, but then when I enter into the container and run it (as root), it works. So the permissions problem is affecting even more than I thought.

I'd really love to solve this and get Laradock working how it used to. Thanks for any ideas.

**Comment by ronydebnath** [comment]
Have you tried login to the workspace container with this:
`docker-compose exec --user=laradock workspace bash`

then running your npm command to your myapp folder?

if login with the non root user doesn't work, you should build the container again.
`docker-compose build --no-cache --force-rm workspace`

**Comment by ronydebnath** [comment]
As for your log issue, this usually happens because of the web server needs a write access to the storage and bootstrap/cache directories.

login to your php-fpm container and check the user:group of storage/logs folder. All files should be owned by www-data:1000 user/group.

You should  set the right permission again to the storage/logs folder if that helps you anyway.

```
chown www-data:1000 storage/logs -R && chmod g+s storage/logs/ -R
```

**Comment by ryancwalsh** [comment]
Thanks, @ronydebnath . I'll be able to try some of this in less than a couple hours. I've never had to use `--user=laradock` before, so that probably won't answer what happened / what the root cause of this problem is.

I assume I will NOT lose any files or MySQL data by running `docker-compose build --no-cache --force-rm workspace`?

**Comment by ryancwalsh** [comment]
I ran:
```
cd /apps/laradock
docker-compose build --no-cache --force-rm workspace
docker ps
docker-compose up -d nginx mysql redis php-worker memcached
docker ps
ls -lah /apps/myapp/storage/logs/
```

And the log file permissions now look good (until tomorrow midnight UTC?).

But `cd /apps/laradock/ && docker-compose exec workspace bash -c "cd /var/www/myapp/; npm run production"` still doesn't work, so I think I haven't fixed the problem. That command used to work.

Specifying the user **also did not work:**

```
cd /apps/laradock/ && docker-compose exec --user=laradock workspace bash -c "cd /var/www/myapp/; npm run production"
bash: npm: command not found
```

**Comment by ryancwalsh** [comment]
@lanphan Is this what you were asking? 

```
serviceUser@docker-s-1vcpu-1gb-nyc1-01:~$ id -u serviceUser
1000
```

**Comment by ryancwalsh** [comment]
@ronydebnath Hey, it's already passed midnight UTC, and the new daily log file got created with the correct `laradock laradock` permissions! (Thanks!)

So I guess `docker-compose build --no-cache --force-rm workspace` worked for fixing that.

And now I'm just trying to figure out why this no longer works, when it used to:

`cd /apps/laradock/ && docker-compose exec workspace bash -c "cd /var/www/myapp/; npm run production"`

**Comment by ryancwalsh** [comment]
I saw https://github.com/laradock/laradock/issues/309#issuecomment-328081229 and so tried: `cd /apps/laradock/ && docker-compose exec -T workspace bash -c -i "cd /var/www/myapp/; npm run production"`

And it successfully *started* to run npm but resulted in a new error:

`Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (67)` (same as https://github.com/laradock/laradock/issues/1898)

I ran `docker exec -it laradock_workspace_1 bash` and `npm rebuild node-sass --force` (because from https://stackoverflow.com/a/37690218/470749 it seems like it helped people with a similar error), but that didn't seem to help.

```
root@27a2fb0bd681:/var/www# nvm --version
0.33.8
root@27a2fb0bd681:/var/www# node --version
v11.6.0
root@27a2fb0bd681:/var/www# npm --version
6.5.0-next.0
```

And it seems like I have no version of Sass installed! I don't know where it went!

`npm install node-sass` failed with multiple errors, including "ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable."

I found https://github.com/sass/dart-sass instead and so ran:

```
npm install --save-dev sass
root@27a2fb0bd681:/var/www/myapp# which sass
/home/laradock/.nvm/versions/node/v11.6.0/bin/sass
root@27a2fb0bd681:/var/www/myapp# sass --version
1.16.0 compiled with dart2js 2.1.0
exit
cd /apps/laradock/ && docker-compose exec -T workspace bash -c -i "cd /var/www/myapp/; npm run production"
```

But same error: "Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (67)"

I can't believe my Laradock containers got so messed up when they were working fine a week ago.  I still haven't figured out what changed and how to fix all this.

**Comment by ronydebnath** [comment]
> @ronydebnath Hey, it's already passed midnight UTC, and the new daily log file got created with the correct `laradock laradock` permissions! (Thanks!)
> 
> So I guess `docker-compose build --no-cache --force-rm workspace` worked for fixing that.
> 
> And now I'm just trying to figure out why this no longer works, when it used to:
> 
> `cd /apps/laradock/ && docker-compose exec workspace bash -c "cd /var/www/myapp/; npm run production"`

Glad your log file permission issue being solved and hopefully you will find some solution with your npm and sass related problem in no time. Cheers!

**Comment by ryancwalsh** [comment]
Oh man. I found an answer of mine [from August 2018](https://stackoverflow.com/a/52048555/470749) that was related. 

Oh, and I changed my .env to say `WORKSPACE_INSTALL_PYTHON=true` instead of `false` and forced a rebuild and "up" of that container.

So now I think all I need to do is figure out how to edit the Docker config files so that npm and nodejs get installed on new containers so that this never happens again.

**Comment by vsamadian** [comment]
File and directory owners (User and Groups) must be laradock : laradock :

docker-compose exec workspace bash
chown -R laradock:laradock /var/www

**Comment by mescalera-xhash** [comment]
@vsamadian when I do exactly that, the owner of the files inside the container is `laradock`, correctly!, however outside from the container, in the host machine, the owner of the files is another user of my computer (which I used to install docker and docker-compose, not sure if that does have something to do with it) so I have to constantly be changing the owner of the files inside to be `laradock` and outside to be my current session user `current_user` to be able to edit files in my IDE

I constantly have to be running
```bash
chown -R laradock:laradock /var/www
```
this sets the owner as `laradock` inside the container, but as `another_user` from outside the container

```bash
chown -R current_user:current_user ~/my/project/path
```
this sets the owner as 'current_user' from outside the container, but as `1001` inside the container
