### ISSUE TITLE
Use of IDE-theia

### ISSUE THREAD

**Issue by wrtisans** [laradock/laradock#1958]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____
i've added the ide-theia to the docker-compose up -d nginx mysql ide-theia memcached and it installs but when i try to acces to the port 3000 it doesnt work ... 

### Expected behavior:

_____

i expect to use that ide with the laragon proyect

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by bestlong** [comment]
port 3000 is container export port, but docker-compose mapping to host port 987.

check .env
```
IDE_THEIA_PORT=987
```
