### ISSUE TITLE
How to run Nginx to test controller from workspace

### ISSUE THREAD

**Issue by jasperf** [laradock/laradock#1966]
Trying to test a controller in Laradock in workspace using 
```
art some-controller:update-something true
Something updating now.
+ Starting ...
+ Order expires 2019-01-31T04:57:56Z
+ Adding web server configuration for something
sh: 1: /usr/sbin/nginx: not found
+ Starting something-else
+ Saving  something-else file for something
+ Verifying  something-else for something
```

But it requires the Nginx binary and cannot locate it. How could I load the nginx binary here the best way with Laradock?

**Comment by albertosgz** [comment]
I need to fix this too. Any idea, clue or workaround?
The only point I came out with is to install ssh client in php-fpm container and install sshd on nginx container and configurate a certificate among them to run commands over nginx. But before that, I would like to know another solutions.

**Comment by jasperf** [comment]
Found some options here https://stackoverflow.com/questions/43442276/docker-can-a-container-a-call-an-executable-located-on-an-other-container-b like adding Docker client and using Docker socket or using volumes .  Will need more time to make choices as some of these options are new to me.

**Comment by jeremynikolic** [comment]
Hi, I am in a similar situation and my docker skills are not that sharp...

Here is what I am trying to achieve, run those commands from a laravel application :
- /etc/init.d/nginx configtest
- /etc/init.d/nginx reload

at the moment I encounter `sh: 1: /etc/init.d/nginx: not found`. I checked if nginx would be located somewhere here but it seems not. 

Seems like it would require to "expose" nginx to the workspace container. Could someone advise on how to achieve this ? I've read about using docker.sock, would that be a good approach ?
Also I may had that this is only for my dev environnement,
