### ISSUE TITLE
Ask for help! How do I install PECL install trader

### ISSUE THREAD

**Issue by laravel-emperor** [laradock/laradock#1987]
I need to install trader

Normal operating procedures

implement

PECL install trader

Modify php.ini

Restart php-fpm

Phpinfo () you can see that trader is installed correctly

This is my workspace code.

`RUN pecl channel-update pecl.php.net && pecl install trader && \
    echo "extension=trader.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/trader.ini && \
    ln -s /etc/php/${LARADOCK_PHP_VERSION}/mods-available/trader.ini /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-trader.ini \
`

Question:

Enter the workspace bash for PECL install trader prompt that the installation is complete

But open phpinfo without trader display

Mods-available could not find trader.ini

Conf.d could not find 20-trader.ini

Docker-composer restart workspace has been tried

Please tell me how to restart php-fpm to make php.ini effective

Or install trader in other ways

Thank you for your reply.

**Comment by marcos-kubis-mk** [comment]
I think you should install the extension in both containers: `workspace` and `php-fpm`.
