### ISSUE TITLE
E: Failed to fetch libgs9_9.26~dfsg-0+deb9u2_amd64.deb  404  Not Found

### ISSUE THREAD

**Issue by bagart** [laradock/laradock#1989]
### Issue:
IMAGEMAGICK not build
default: PHP_FPM_INSTALL_IMAGEMAGICK=***true***
```bash
apt-get install -y libmagickwand-dev imagemagick
```

`error:
E: Failed to fetch http://security-cdn.debian.org/pool/updates/main/g/ghostscript/libgs9_9.26~dfsg-0+deb9u2_amd64.deb  404  Not Found`

PROBLEM with
https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile#L503
_____

### Reproduce:
```bash
docker-compose build php-fpm
```
or any build

_____
### Temporary / local hotfix
https://github.com/laradock/laradock/blob/master/env-example#L143
`PHP_FPM_INSTALL_IMAGEMAGICK=false`

**Comment by bestlong** [comment]
try `docker-compose build --no-cache php-fpm`

**Comment by bagart** [comment]
Looks like work! :) thanks
