### ISSUE TITLE
404 on docker native (win 10)

### ISSUE THREAD

**Issue by r-moiseev** [LaraDock/laradock#199]
I have installed laradock as git submodule, then i do `docker-compose up -d nginx postgres`

And i have 404 on 127.0.0.1

When i look in worckspace container there is only laradock folder in /var/www/laravel

**Comment by r-moiseev** [comment]
So i reseted docker, rebuilded all images and now i have this

```
ERROR: for volumes_data  Cannot start service volumes_data: mkdir /d/docker/app/app/laradock/data: permission denied

ERROR: for nginx  Cannot start service nginx: mkdir /d/docker/app/app/laradock/logs: permission denied
[31mERROR[0m: Encountered errors while bringing up the project.
```

**Comment by xyos** [comment]
Did you enable file sharing in docker?
https://docs.docker.com/docker-for-windows/#docker-settings

**Comment by Kauhat** [comment]
If you've already enabled shared drives etc...

I've personally never been able to access files on one of my PC's due to some sort of [issue when mounting CIFS shares](https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/89) from the Hyper-V VM (Although it doesn't happen  for me on virtualbox!)

**Comment by r-moiseev** [comment]
I`ve fixed this by manually creating all mount dirs in laradock folder. But there was another error with some writing.

It seems docker has no permissions to write to host directory.  But it can read, ive tested it with `ls -la` on alpine

**Comment by Mahmoudz** [comment]
Go to the README scroll down to the [Debugging Section](https://github.com/LaraDock/laradock#debugging) and follow the steps under **I get Nginx error 404 Not Found on Windows**
