### ISSUE TITLE
Changes on project are not synchronized

### ISSUE THREAD

**Issue by claudiul93** [laradock/laradock#1992]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.1, build 4c52b90
- Laradock commit (`$ git rev-parse HEAD`): 913abc54f9edde865a1d6de8a03b38098593ebfb
- System info (Mac, PC, Linux):  macOS Mojave
- System info disto/version: 10.14.2

### Issue:

Hi, I have set up a 2 projects laradock with Docker 18.09.1 and for one project, when I do some changes in the code, these are not displayed/synchronized live. However for the other project any change I made in the project (ex: I just change a <div>), this change can be viewed immediately.

This behavior is not favorable, because I always must run 'docker-compose down' and then 'docker-compose up -d nginx mysql phpmyadmin workspace' in order to be able to see the changes.

### Expected behavior:

The changes made on the project should be seen immediately.

### Reproduce:

I have set 2 laravel projects as in the laradock guide.

### Relevant Code:
Not available

// place a code sample here
Not available

**Comment by jonasgoderis** [comment]
I'm dealing with a similar issue. For some controllers in my application I also have to run 'docker-compose down' to see my changes. It's not happening with all controllers but with some of them. 

First I thought it was opcache but I've built my container again without opcache and the same issue is happening. 

### Info

- Docker version: 18.09.2, build 6247962
- System info: Mac OS Mojave 10.14.2
- Laradock commit: 61d7b18922006d582ae68ca0cdf5e202e5bcf08d

**Comment by Thedigit** [comment]
i have the same issue. 

it seems to work for a little while. then the sync seems to stop and i am forced to restart the containers to get the updated code.

any feedback would be great.
