### ISSUE TITLE
Nginx build fails when COMPOSE_PROJECT_NAME changed

### ISSUE THREAD

**Issue by useaquestion** [laradock/laradock#1993]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): e0d7229e95b58af4905add4686f698cd367f38ca
- System info (Mac, PC, Linux): Ubuntu
- System info disto/version: 18.04.01

### Issue:
When I run the docker-compose command on a new project where I've modified the COMPOSE_PROJECT_NAME directive in laradock's .env file, the nginx build fails (example below). 

~~~~
$ docker-compose up -d nginx mariadb
Building nginx
Step 1/13 : FROM nginx:alpine
 ---> b411e34b4606
Step 2/13 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Using cache
 ---> 238921162d9f
Step 3/13 : COPY nginx.conf /etc/nginx/
 ---> Using cache
 ---> 5b6abf1d4fe9
Step 4/13 : ARG CHANGE_SOURCE=false
 ---> Using cache
 ---> 1550ef24eef6
Step 5/13 : RUN if [ ${CHANGE_SOURCE} = true ]; then     sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories ;fi
 ---> Using cache
 ---> 6480191a24b6
Step 6/13 : RUN apk update     && apk upgrade     && apk add --no-cache openssl     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data
 ---> Using cache
 ---> 68b1001df769
Step 7/13 : ARG PHP_UPSTREAM_CONTAINER=php-fpm
 ---> Using cache
 ---> 455e89afb460
Step 8/13 : ARG PHP_UPSTREAM_PORT=9000
 ---> Using cache
 ---> 227e06ede628
Step 9/13 : RUN echo "upstream php-upstream { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf     && rm /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 1176369ccf23
Step 10/13 : ADD ./startup.sh /opt/startup.sh
ERROR: Service 'nginx' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder612379973/startup.sh: no such file or directory
~~~~
_____

### Expected behavior:
It should work. Both the mariadb and apache2 containers appear to work perfectly when COMPOSE_PROJECT_NAME changed. 
_____

### Reproduce:
Change the COMPOSE_PROJECT_NAME directive and start the nginx image. 
_____

### Relevant Code:
N/A

**Comment by marciojc** [comment]
you need to build.
`docker-compose build --no-cache nginx`

**Comment by edtan-git** [comment]
`
ERROR: Service 'nginx' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder612379973/startup.sh: no such file or directory
`

Got this error message also.
Seem like the problem is because there is not permission to write on /var/lib/docker/tmp, when I run 
`sudo docker-compose build nginx` there is not problem.

**Comment by rossanoua** [comment]
same error here
any suggestion?
`docker-compose build --no-cache nginx` not help

**Comment by rossanoua** [comment]
@edtan-git 
normally you should not execute docker and docker-compose with sudo due to security risks.
