### ISSUE TITLE
PATH set with ENV does not persist

### ISSUE THREAD

**Issue by dimsamaras** [laradock/laradock#1994]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`):  39469e1404172d2d833b9eb9f0fb4665624815df
- System info (Mac, PC, Linux): Linux  
- System info disto/version: Ubuntu

### Issue:
I have added Python in the Workspace container  and i am trying to update the PATH with the following line 
```ENV PATH $PATH:~/.local/bin```
yet the path is not updated when i access the workspace image.
```$ echo $PATH
/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vendor/bin
```
I have tried placing the code in the end of the Dockerfile but still no luck.
I have tried the code in a simple Dockerfile and works fine.

Also the following from Node block does not work:
```
ENV PATH $PATH:$NVM_DIR/versions/node/v${NODE_VERSION}/bin
```
_____

### Expected behavior:
```$ echo $PATH
/root/.local/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vendor/bin
```
_____

### Reproduce:
```ENV PATH $PATH:~/.local/bin``` 
_____

### Relevant Code:

```

ARG INSTALL_PYTHON=false

RUN if [ ${INSTALL_PYTHON} = true ]; then \
  apt-get -y install python python-pip python-dev build-essential  \
  # && pip install --upgrade pip \
  # && hash -d pip \
  && pip install boto3 \
  # && pip install --upgrade virtualenv \
  && pip install awscli --upgrade --user\
;fi

ENV PATH $PATH:~/.local/bin
```

**Comment by dimsamaras** [comment]
The ENV needs to be reset due to the --user param in this line: pip install awscli --upgrade --user
Removing installs the awscli globally in the container.
It is a naive workaround since the ENV is not yet set!

**Comment by marciojc** [comment]
Use the same code as composer vendor, should work

    # Export python path
    RUN echo "" >> ~/.bashrc && \
    echo 'export PATH="~/.local/bin:$PATH"' >> ~/.bashrc
