### ISSUE TITLE
node: not found & npm: not found

### ISSUE THREAD

**Issue by OlegDemkiv** [laradock/laradock#1999]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): d8c36ab86007f04293d380bcf8325cb70c76fdd0
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04

### Issue:
When I using "spatie/browsershot" package with Laravel I getting errors:
`The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/mywebsite/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"https:\/\/example.com","action":"content","options":{"args":[],"viewport":{"width":800,"height":600}}}'" failed. Exit Code: 127(Command not found) Working directory: /var/www/mywebsite/public Output: ================ Error Output: ================ sh: 1: npm: not found sh: 1: node: not found`

Info from workspace:
`laradock@564453c81f03:/var/www$ node -v`
`v11.4.0`
`laradock@564453c81f03:/var/www$ npm -v`
`6.4.1`

### Expected behavior:
Puppeteer must run a headless version of Google Chrome and grab a website

### Reproduce:
Install package spatie/browsershot: `composer require spatie/browsershot`
Install puppeteer: `npm install puppeteer`
Try to run demo code: `Browsershot::url('https://example.com')->bodyHtml();`

### Relevant Code:

```
Browsershot::url('https://example.com')->bodyHtml();
```

**Comment by Lutick** [comment]
try this:
`
Browsershot::url('https://example.com')
->setNodeBinary('/usr/bin/node')
->setNpmBinary('/usr/bin/npm')
->bodyHtml();
`

**Comment by jeff-h** [comment]
My laradock instance is heavily customised so I can't be too specific, but I also had this issue. I realised my `php-fpm` needed node and nom installed. In fact, to get browsershot working, I added the following near the end of my `php-fpm/Dockerfile`:

```
#####################################
# Headless Chrome:
#
# From https://github.com/spatie/browsershot#requirements
#####################################

USER root

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```

As I said, laradock instance is heavily customised so unfortunately I suspect mileage may vary.

**Comment by szwss** [comment]
I also encountered the same problem,Is it solved?

**Comment by xxRockOnxx** [comment]
It's not. I derived my solution from @jeff-h 

```
#####################################
# Headless Chrome:
#
# From https://github.com/spatie/browsershot#requirements
#####################################

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev && \
    npm install --global --unsafe-perm puppeteer && \
    chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium
```

**Comment by xxRockOnxx** [comment]
No it isn't. Here's how I managed to make it work:

```
RUN apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs \
    && npm install --global --unsafe-perm puppeteer \
    && chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium
```

Derived from https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker, https://github.com/spatie/browsershot#requirements, and @jeff-h's answer

The binary would look something like: `/usr/lib/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome`
