### ISSUE TITLE
docker-composer up, nginx and data exits

### ISSUE THREAD

**Issue by huglester** [LaraDock/laradock#20]
Hello,

when I run this, I get: 
```
mysql     | 160403  7:23:03 InnoDB: Using Linux native AIO
mysql     | 160403  7:23:03 InnoDB: Initializing buffer pool, size = 128.0M
mysql     | 160403  7:23:03 InnoDB: Completed initialization of buffer pool
mysql     | 160403  7:23:03 InnoDB: highest supported file format is Barracuda.
php-nginx | Interactive shell
php-nginx |
data exited with code 0
mysql     | 160403  7:23:03  InnoDB: Waiting for the background threads to start
php-nginx exited with code 0
mysql     | 160403  7:23:04 InnoDB: 5.5.47 started; log sequence number 1595675
```

As you can see, mysql, (redis earlier) started..
but nginx an data containers - exited.

ANy ideas?

**Comment by Mahmoudz** [comment]
Try to delete your `phpnginx` image and run the command again (it should download another version, most probably doesn't include this problem).

to see all your images run `docker images`
to delete an image use `docker rmi {image-name}`

And please let me know if it worked.
