### ISSUE TITLE
How to use with laravel websockets?

### ISSUE THREAD

**Issue by windows1087** [laradock/laradock#2002]
How do i use laradock with the Laravel WebSockets package? https://docs.beyondco.de/laravel-websockets/

I have a nginx and postgres container running (with workspace and php-fpm of course). I go in the workspace container with `docker-compose exec workspace bash` and then to my laravel app and running `php artisan websockets:serve`.

This starts the laravel websocket server on port 6001. I added the port 6001 in my docker-compose.yml file.

I tried a few things out. Added the port in the `workspace` section. But it didnt work. Added the port in the `nginx` section. But id didnt work. Added the port in the php-fpm section. But it didnt work.

Anyone a idea? :/

**Comment by bestlong** [comment]
you start websocket in workspace container
need setup 

in workspace/Dockerfile add

```
EXPOSE 6001
```

in docker-compse.yml add

```
services:
  workspace:
    port:
      - 6001:6001
```

**Comment by rvkolosov** [comment]
How I can add laravel-webscokets in php-worker?
Im create proccess, and see that in process list, but websocket server not working.
If I start 

> artisan laravel-webscokets:serve

 manualy, all ok

**Comment by lionslair** [comment]
I am running the server through php-worker.

so I exposed EXPOSE 6001 in php-worker/Dockerfile

and  added  to ./docker-compose.yml

services:
  php-worker:
     ports:
        - "6001:6001"

However my broadcasts are having trouble reaching websockets.test site I setup. I am running websockets for multiple projects so made one site running the websockets server

**Comment by lionslair** [comment]
Following this post. https://github.com/beyondcode/laravel-websockets/issues/185 simply set the PUSHER_HOST to php-worker

**Comment by joeloudjinz** [comment]
@windows1087 did this worked for you ?

> you start websocket in workspace container
> need setup
> 
> in workspace/Dockerfile add
> 
> ```
> EXPOSE 6001
> ```
> 
> in docker-compse.yml add
> 
> ```
> services:
>   workspace:
>     port:
>       - 6001:6001
> ```

**Comment by vitaliy82** [comment]
> @windows1087 did this worked for you ?
> 
> > you start websocket in workspace container
> > need setup
> > in workspace/Dockerfile add
> > ```
> > EXPOSE 6001
> > ```
> > 
> > 
> > in docker-compse.yml add
> > ```
> > services:
> >   workspace:
> >     port:
> >       - 6001:6001
> > ```

When (PusherBroadcaster.php:119) curl calls  127.0.0.1:6001  it gets  "Connection refused"

**Comment by vitaliy82** [comment]
I fouond solution. For me it: 'host'="workspace:6001"  instead "127.0.0.1:6001"

**Comment by adesr** [comment]
@vitaliy82 
where do you exactly put that?

is anyone can help me to explain step by step to enable laravel-websockets in laradock? i already try all solution above but still no good.

what i've done is:

- install laravel-websockets via composer

- do vendor:publish, migrate etc

- adding ssl cert and key file path (/etc/nginx/ssl/default.crt <== which is defined in nginx container)

- put websockets:serve inside php-worker container

- adding port "6001:6001" in workspace - docker-compose.yml

- adding "Echo" script in bootstrap.js 

- running docker-compose up -d nginx mysql workspace redis php-worker

but when i trying to open websockets dashboard => failed: ERR_CONNECTION_CLOSED

**Comment by weec0008** [comment]
> I fouond solution. For me it: 'host'="workspace:6001" instead "127.0.0.1:6001"

Thanks for putting this out here! The broadcast works after the above changes, just set `'host' => workspace` in the `pusher` section in broadcasting.php

**Comment by verenzuela** [comment]
> `workspace`

Hi can you share your docker-compose.yaml, I am trying to run laravel-socket with docker and I have not succeeded

**Comment by M-Abdullahi** [comment]
After a lengthy weekend of fiddling around, here's how i managed to get it running on my dev machine.
I am using supervisor in the php-worker container to keep the php artisan websockets:serve command running. 
```
laravel-websockets.conf

[program:laravel-websocket]
process_name=%(program_name)s_%(process_num)02d
user=laradock
command=php /var/www/medic/artisan websockets:serve
autostart=true
autorestart=true
redirect_stderr=true

```
### PHP Worker ############################################
    php-worker:
      build:
        context: ./php-worker
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
         ....
  
      ports:
        - "6001:6001"

```
php-worker/Dockerfile
#laravel-websockets
EXPOSE 6001
```

rebuild the php-worker container and navigate to /laravel-websockets

The only caveat that i have, is for my vue spa to communicate with the websocket server

**Comment by lionslair** [comment]
Yeah what I am doing on my version. but I have switched to Caddy2 https://bitbucket.org/lionslair/laradock/src/master/

**Comment by vortechron** [comment]
> I fouond solution. For me it: 'host'="workspace:6001" instead "127.0.0.1:6001"

tq, this solves my problem !!

**Comment by joulgs** [comment]
what worked for me:

**/laradock/docker-compose.yml**
add port 6001 in services:
`services:
    workspace:
      ports:
        ...
        - 6001:6001
        `
        
**/laradock/workspace/Dockerfile**
expose port 6001:
`EXPOSE 6001`

**/config/broadcasting.php**
`...
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => false,
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],
...`
