### ISSUE TITLE
Auto build on dockerhub

### ISSUE THREAD

**Issue by panakour** [laradock/laradock#2004]
Wouldn't be better for laradock to have autobuilds enabled? for example php-fpm https://hub.docker.com/r/laradock/php-fpm/builds does not have autobuilds available

**Comment by bestlong** [comment]
both php-fpm and workspace auto build not enable.
Currently only @Mahmoudz can to that.
I was seed message to @Mahmoudz for request docker hub laradock repository permission, but no respond so far.

I plan to temporarily replace it with new docker hub repository
https://hub.docker.com/r/letsdockerize/laradock-php-fpm
https://hub.docker.com/r/letsdockerize/laradock-workspace

**Comment by Mahmoudz** [comment]
Hi @bestlong excuse my late response. I've granted you access on dockerhub.
