### ISSUE TITLE
Unsupported config

### ISSUE THREAD

**Issue by IgorDePaula** [LaraDock/laradock#201]
I trying run command:
docker-compose up -d nginx mysql, like readme.md file

 I received this error: Unsupported config option for services service: 'mongo', 

For postgres too.

**Comment by Mahmoudz** [comment]
try upgrading to LaraDock 4 and rebuilding your containers

**Comment by IgorDePaula** [comment]
I do clone now and I havent any containers.

2016-08-01 15:05 GMT-03:00 Mahmoud Zalt <notifications@github.com>:

**Comment by IgorDePaula** [comment]
Is necessary update docker-compose to minimum 1.6.0.
