### ISSUE TITLE
Can't spin up Caddy

### ISSUE THREAD

**Issue by rubybrowncoat** [laradock/laradock#2019]
### Info:
- Docker version (`$ docker --version`): `Docker version 18.09.1, build 4c52b90`
- Laradock commit (`$ git rev-parse HEAD`): `61d7b18922006d582ae68ca0cdf5e202e5bcf08d`
- System info (Mac, PC, Linux): `macOS Mojave 10.14.3`
- System info disto/version: ⬆️

### Issue:

Can't spin up Caddy. Something about undefined `tls.VersionTLS13`.
_____

### Expected behavior:
Should work, I suspect.
_____

### Reproduce:
I'm not sure. I tried multiple times and I get the same error every time. I am just following the laradock guide to "Run Site on SSL with Let's Encrypt Certificate" at the step "Run Your Caddy Container without the -d flag and Generate SSL with Let's Encrypt".
_____

### Relevant Code:

Relevant logs:

```
[...]
Cloning into 'sys'...
fetching missing dependencies: caddy, dnsproviders, hook.pluginloader
github.com/mholt/caddy/vendor/github.com/flynn/go-shlex
github.com/mholt/caddy/vendor/github.com/google/uuid
github.com/mholt/caddy/telemetry
github.com/mholt/caddy/caddyfile
github.com/mholt/caddy
Cloning into '/root/lib/caddy/gopath/src/github.com/caddyserver/dnsproviders'...
github.com/abiosoft/caddyplug (download)
github.com/abiosoft/caddyplug/internal
github.com/abiosoft/caddyplug
done fetching depedencies.

installing Caddy...
# github.com/mholt/caddy/caddytls
/root/lib/caddy/gopath/src/github.com/mholt/caddy/caddytls/config.go:410:31: undefined: tls.VersionTLS13
/root/lib/caddy/gopath/src/github.com/mholt/caddy/caddytls/config.go:433:12: undefined: tls.VersionTLS13
exit status 2
ERROR: Service 'caddy' failed to build: The command '/bin/sh -c apk add --no-cache     openssh     git     build-base     && mkdir -p $GOPATH/src/golang.org/x/     && cd $GOPATH/src/golang.org/x/     && git clone https://github.com/golang/sys.git sys     && go get github.com/abiosoft/caddyplug/caddyplug     && caddyplug install-caddy     apk del build-base' returned a non-zero code: 1
```

**Comment by mathin94** [comment]
I Have same problem 😥

**Comment by dithmer** [comment]
> Package tls partially implements TLS 1.2, as specified in RFC 5246, and TLS 1.3, as specified in RFC 8446.
> 
> TLS 1.3 is available only on an opt-in basis in Go 1.12. To enable it, set the GODEBUG environment variable (comma-separated key=value options) such that it includes "tls13=1". To enable it from within the process, set the environment variable before any use of TLS:
> 
> func init() {
>     os.Setenv("GODEBUG", os.Getenv("GODEBUG")+",tls13=1")
> }

> 

From https://golang.org/pkg/crypto/tls/

**Comment by mkrensing** [comment]
caddy updated TLS to 1.3 in https://github.com/mholt/caddy/commit/72d0debde6bf01b5fdce0a4f3dc2b35cba28241a

updating golang to version 1.12 works for me.

**Comment by davidbonting** [comment]
I also could not get caddy to work these days. I had some of the same issues described [here](https://github.com/mholt/caddy/issues/1180).

So I used a combination of an old Dockerfile and newer Dockerfile:

```
FROM zuohuadong/caddy:alpine


MAINTAINER Huadong Zuo <admin@zuohuadong.cn>

ARG plugins="cors"

## ARG plugins="cors cgi cloudflare azure linode"


RUN caddyplug install ${plugins}


EXPOSE 80 443 2015

WORKDIR /var/www/public

CMD ["sh","-c","/start.sh & /usr/bin/caddy -conf /etc/caddy/Caddyfile -agree"]
```

**Comment by bestlong** [comment]
#1838

**Comment by raykudo** [comment]
Still doesn't work for me
