### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by helioh3** [laradock/laradock#2023]
I'm having problems when running the migrate command on laravel ... artisan returns an error: 'could not find driver', I've already searched
I already checked my database.php file for laravel, it's all right and I also tried to uncomment the "extension = mysqli.dll" line of php7.2.ini from my laradock .env file ..
several things google to solve and so far nothing!
Can anyone give a light to this problem?...

### Relevant Code:

```
; If you wish to have an extension loaded automatically, use the following
; syntax:
;
   extension=modulename.extension
;
; For example, on Windows:
;
   extension=mysqli.dll
;
; ... or under UNIX:
;
   extension=mysqli.so
;
; ... or with a path:
;
   extension=/path/to/extension/mysqli.so
;
; If you only provide the name of the extension, PHP will look for it in its
; default extension directory.
;
```

**Comment by bestlong** [comment]
check php install extension list
you can use `php -m` CLI command.
or
```
<?php
echo phpinfo();
```

**Comment by bestlong** [comment]
php7.2.ini no need edit.

in .env set `PHP_FPM_INSTALL_MYSQLI=true`

then rebuild image `docker-compose build --no-cache php-fpm`

docker-compose down
docker-compose up -d php-fpm
docker-compose exec php-fpm php -m

**Comment by helioh3** [comment]
Yes!! Thanks!!
