### ISSUE TITLE
Can't build because of APP_CODE_CONTAINER_FLAG=:cached

### ISSUE THREAD

**Issue by axettone** [laradock/laradock#2037]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 8ca26e6c06c5841c8ca2c328ea5a0220209a3d71
- System info (Mac, PC, Linux): macOS
- System info disto/version: 10.13.6 (17G5019)

### Issue:
Can't run "docker-compose build", it says:
ERROR: Volume /Users/my-name/Sites/my-project:/var/www:cached:cached has incorrect format, should be external:internal[:mode]
_____

### Expected behavior:
Building stuff
_____

### Reproduce:
git clone laradock, copy env-example to .env, $ docker-compose build
_____

### Relevant Code:

```
// place a code sample here
```
Had to empty the APP_CODE_CONTAINER_FLAG in .env to make it work (instead of :cached)

**Comment by ahmad-sa3d** [comment]
yes after updating the repo i tried to build and i got the same error

**Comment by hawkup** [comment]
What is your `APP_CODE_PATH_CONTAINER` value ? It should be `APP_CODE_PATH_CONTAINER=/var/www`
