### ISSUE TITLE
Mailhog don't receive mails

### ISSUE THREAD

**Issue by webard** [laradock/laradock#2039]
### Info:
- Docker version 18.09.2, build 6247962
- Laradock commit 8ca26e6c06c5841c8ca2c328ea5a0220209a3d71
- System info (Mac, PC, Linux): Mac
- System info disto/version: Mojave

### Issue:
Mails never land in mailhog when sent by Laravel application on local environment. I have testing server with mailhog configured, and when I reconfigure local app to use that testing Mailhog everything works nice, so this must be a problem with docker mailhog. When I connect to workspace container and make
```
telnet mailhog 1025
```
I can see response from SMTP. Ping `ping mailhog` from workspace responses too.
_____

### Expected behavior:
See mails in docker mailhog
_____

### Reproduce:
Just config app like below and see nothing happened in mailhog
_____

### Relevant Code:
Configuration in .env:
```
MAIL_DRIVER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

**Comment by craigharman** [comment]
This doesn't work for me either. Same result.

**Comment by marcosdipaolo** [comment]
+1
