### ISSUE TITLE
Service nginx failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builderXXXXXXXXX/startup.sh: no such file or directory

### ISSUE THREAD

**Issue by rossanoua** [laradock/laradock#2042]
### Info:
- Docker version (`$ docker --version`):  18.09.3, build 774a1f4
- Laradock commit (`$ git rev-parse HEAD`): 8ca26e6c06c5841c8ca2c328ea5a0220209a3d71
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04.2 LTS

### Issue:
command
`docker-compose build --no-cache nginx mysql`
produce an error 
`ERROR: Service 'nginx' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder192688730/startup.sh: no such file or directory`

but if command executes with sudo 
`sudo docker-compose build --no-cache nginx mysql`
build successfull
_____

### Expected behavior:
docker & docker-compose should not be executed with sudo privilages

_____

### Reproduce:

just follow installation guide from scratch
https://laradock.io/getting-started/ 
for multiple projects
_____

**Comment by Okipa** [comment]
Same problem on a ubuntu machine. Did you manage to solve this ?

**Comment by rossanoua** [comment]
@Okipa hi Arthur!
For now I'm building nginx container with root privilages.
And then do `docker-compose up -d nginx mysql` normally.
I'm not looked up for root of problem, but my opinion is the same, something wrong with nginx container setup.
`docker` & `docker-compose` should not be executed with sudo privilages

**Comment by Okipa** [comment]
Thanks for your answer.  
Same for me, I solved this too by using `sudo` privileges, which seems wrong to me too.

**Comment by lionslair** [comment]
I am having the same issue. Anyone done this without sudo?

**Comment by rossanoua** [comment]
I'm have little bit of progress about figuring out what happens.
But not 100% sure.
Can only say next:
seems like during build of nginx container docker creates files and they have owner `root`
![image](https://user-images.githubusercontent.com/16378584/56466767-939f5500-641e-11e9-8cbc-ad52fb85479c.png)
after he try to get access to this two files but can't due to permissions issue.
So, little update.
If after unsaccessful build, make chown to this two files than build run good without `root`.

Wonder to hear from other people's.
Behaviour the same as me?

**Comment by zerinoid** [comment]
Same issue here.
Docker version 18.09.5, build e8ff056
Ubuntu 18.04.2 LTS x86_64

**Comment by zerinoid** [comment]
> I'm have little bit of progress about figuring out what happens.
> But not 100% sure.
> Can only say next:
> seems like during build of nginx container docker creates files and they have owner `root`
> ![image](https://user-images.githubusercontent.com/16378584/56466767-939f5500-641e-11e9-8cbc-ad52fb85479c.png)
> after he try to get access to this three files but can't due to permissions issue.
> So, little update.
> If after unsuccessful build, make chown to this three files than build run good without `root` (of course `--no-cache`).
> 
> Wonder to hear from other people.
> Behaviour the same as mine?

Chowning thoses files to my user solved nginx build.

**Comment by javoscript** [comment]
> I'm have little bit of progress about figuring out what happens.
> But not 100% sure.
> Can only say next:
> seems like during build of nginx container docker creates files and they have owner `root`
> ![image](https://user-images.githubusercontent.com/16378584/56466767-939f5500-641e-11e9-8cbc-ad52fb85479c.png)
> after he try to get access to this three files but can't due to permissions issue.
> So, little update.
> If after unsuccessful build, make chown to this three files than build run good without `root` (of course `--no-cache`).
> 
> Wonder to hear from other people.
> Behaviour the same as mine?

This solved it for me too

**Comment by lionslair** [comment]
I have those files as root. I have just chown them. Did not need root to rebuild the image. Are they root within the git repo or is something else making them root?

**Comment by rossanoua** [comment]
@lionslair Hi.
As you can see in the image provided by me, files with root privilages are created during build process, because they are ignored by VCS.
Also I have explained this in my comment https://github.com/laradock/laradock/issues/2042#issuecomment-485231146.

**Comment by lionslair** [comment]
I still have something in the logs of my project changed to root on up. I think its different to this.  I didn't need root to get the image to build now which was good. I had to make some other changes on my fork though. Unrelated to this though

**Comment by snowdon-dev** [comment]
Would the solution not be to map your userid into the docker container - giving the host permissions on the file - there is config already inside laradock for this.

**Comment by andrey-helldar** [comment]
CentOS 7.5
Docker 19.03.13

Docker installed from under the root. I assemble containers from under the user.

I get the error when running the `docker-compose up -d --build` command.

All laradock files are owned by the user.

If you run the build using the sudo command, then the containers are no longer built under the user and are owned by root. I do not need it.

What am I missing?

![image](https://user-images.githubusercontent.com/10347617/97417580-eb265700-1918-11eb-8e9f-d07c4444d1bd.png)
