### ISSUE TITLE
unable to connect to MySQL after upgrade to latest (8) version

### ISSUE THREAD

**Issue by ccennis** [laradock/laradock#2043]
### Info:
- Docker version (`$ docker --version`): 2.0.0.3
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Mac
- System info disto/version: High Sierra

### Issue:

After upgrade to MySQL 8 using current Laradock mysql settings, cannot get past authentication, even after adding "default_authentication_plugin=mysql_native_password" to my.cnf and several rebuilds. I have removed the image, the container, and still the issue persists. I cannot "mysql -uroot" in the mysql container or hit it externally with Sequel Pro. Error: "dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 2): image not found". 

Laravel also cannot hit my DB: 
"SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from `users` where `id` = 1 limit 1)
Previous exceptions
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (2054)
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (2054)
PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] (0)"

### Expected behavior:

Login as normal

**Comment by webard** [comment]
You should add
```
default_authentication_plugin=mysql_native_password
```
to `laradock/mysql/my.ini`, but I think it should be some way automated. If You have laradock as a submodule, modifying files makes submodule dirty...
