### ISSUE TITLE
Is it possible to run multiple Laravel Project with only using 1 Laradock?

### ISSUE THREAD

**Issue by khrisnagunanasurya** [laradock/laradock#2044]
Hi, i'm very new with docker, and just learned about Laradock, and already read & watch some tutorials, but usually it's for running only 1 project at a time.

so my question is it possible to running multiple laravel project with only using 1 Laradock?
so let's say when I run the laradock, the projects are running, ex:
- test.com
- api.test.com
- admin.test.com

I already followed this guide https://medium.com/@sorravitbunjongpean/running-multiple-laravel-sites-on-laradock-with-a-computer-which-port-80-is-occupied-2a2d4b274282,
but it doesn't working, I wonder because it's an old version of Laradock or what?

this is the error I get

```
laradock_docker-in-docker_1 is up-to-date
Recreating laradock_mysql_1 ...
Starting laradock_workspace_1 ... error

Recreating laradock_mysql_1   ... error1f343d92dcfcd0b308c77d2b6988a78c0e465ec7eb8188a): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2222:tcp:172.21.0.3:22: input/output error

ERROR: for laradock_mysql_1  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1 (a868b48d072542c1cb4de1405e9bfb34aaeedaa64534f4c96ada8aa5caa030be): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:3306:tcp:172.21.0.3:3306: input/output error

ERROR: for workspace  Cannot start service workspace: driver failed programming external connectivity on endpoint laradock_workspace_1 (3995ccefd3c8314781f343d92dcfcd0b308c77d2b6988a78c0e465ec7eb8188a): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2222:tcp:172.21.0.3:22: input/output error

ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1 (a868b48d072542c1cb4de1405e9bfb34aaeedaa64534f4c96ada8aa5caa030be): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:3306:tcp:172.21.0.3:3306: input/output error
ERROR: Encountered errors while bringing up the project.
```

**Comment by leoaxxess** [comment]
I sometimes get the _userland proxy_ and _programming external connectivity_ errors when starting up Laradock too. Restarting Docker fixes it for me. Let us know if it helps you.

**Comment by bestlong** [comment]
```
// one laradock and multiple project
+ laradock
+ php-project-1
+ php-project-2
+ laravel-project-1
+ laravel-project-2
```

.env file set `APP_CODE_PATH_HOST=../`

and update nginx site config file

```
// nginx/sites/php-project-1.conf
root /var/www/php-project-1
```

```
// nginx/sites/php-project-2.conf
root /var/www/php-project-2
``` 

```
// nginx/sites/laravel-project-1.conf
root /var/www/laravel-project-1/public
``` 

```
// nginx/sites/laravel-project-2.conf
root /var/www/laravel-project-2/public
```

**Comment by georgemr** [comment]
You can use only one configuration file and take advantage of regular expressions when using the `server_name` directive and service `local.gd` so you don't have to add entries in `hosts` file (e.g. local.gd.conf):
```
server {
    listen 80;
    listen [::]:80;

    server_name ~^(?<domain>.+)\.local(\.gd)?$;
    root /var/www/$domain/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/$domain.error.log;
    access_log /var/log/nginx/$domain.access.log;
}
```

With this setup app `SOME_APP` is accessed through `SOME_APP.local.gd`. Files reside in `/var/www/SOME_APP/public`. Logs are written in `SOME_APP.error.log` and `SOME_APP.access.log` in `logs` foder.

If you want to use the `hosts` file, just add an entry like `127.0.0.1       SOME_APP.local` for every app.

**Comment by ezekel** [comment]
@bestlong ,

If 1 laradock and multple project of laravel. how do you issue command npm install "dependecy name" on a certain project example laravel_project_c ?

**Comment by tarikhagustia** [comment]
> @bestlong ,
> 
> If 1 laradock and multple project of laravel. how do you issue command npm install "dependecy name" on a certain project example laravel_project_c ?

@ezekel you should make a folder laravel_project_c under app root and just run `cd /var/www/laravel_project_c && npm install`

**Comment by ezekel** [comment]
@bestlong  thank you I found out now
