### ISSUE TITLE
Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease

### ISSUE THREAD

**Issue by riddman** [laradock/laradock#2047]
### Info:
- Docker version: 18.09.3-ce
- Laradock commit: 254a9ae19490b53fc8f0647d81b7581c312f0724
- System info: Linux
- System info disto/version: Manjaro 18.0.4

### Issue:

I have got error when i try up laradock
I  execute in terminal **docker-compose up -d nginx mysql phpmyadmin**

The error is:
**+ apt-get update -yqq
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip &&       docker-php-ext-configure zip --with-libzip &&       docker-php-ext-install zip &&       php -m | grep -q 'zip'' returned a non-zero code: 100**

**Comment by bestlong** [comment]
try  `docker run -it --rm busybox ping www.google.com` check network is working.

**Comment by Tarik02** [comment]
Same problem. Network works normally.

**Comment by Tarik02** [comment]
This is some problem with your network. Seems like your IP is blocked in that repo.

**Comment by Tarik02** [comment]
P.S. Я так розумію, у вас Київстар? Бо у мене така проблема спостерігається саме на інтернеті від Київстару.

**Comment by riddman** [comment]
Так, інтернет від Київстар.

**Comment by Tarik02** [comment]
@riddman, ну тоді зрозуміло. Як тільки спробував запустити те ж саме на сервері, то все стало нормально працювати. Виходи - змінювати провайдер або використовувати проксі/VPN. Взагалі, скажу з досвіду, IP адреси Київстару заблоковані на багатьох ресурсах (наприклад, з інтернету від Київстар неможливо зареєструватися на Вікіпедії).

**Comment by riddman** [comment]
Confirmed my internet provider is blocked in repository. Thanks all for responses.

**Comment by chinahub** [comment]
when i try to change my php version from 7.2 to 7.1，and i build like this:
`docker-compose build php-fpm`
and it make wrong like this:
![image](https://user-images.githubusercontent.com/11291147/55715200-d4629b80-5a26-11e9-9548-b595271be988.png)
i have no idea,can you help,thanks!

**Comment by vdecree** [comment]
> 
> 
> Confirmed my internet provider is blocked in repository. Thanks all for responses.

Is there a solution to this?

**Comment by Tarik02** [comment]
@vdecree Yes, there's several ways:
1. Change internet provider.
2. Use VPN.
3. Something other..

**Comment by drtobbyas** [comment]
using VPN worked for me

**Comment by riddman** [comment]
Also, as a solution for me worked configure DNS for docker.
On the host (I'm using Manjaro), find out the primary and secondary DNS server addresses:

```
$ nmcli dev show | grep 'IP4.DNS'
IP4.DNS[1]:              192.168.0.1
```

Using these addresses, create a file /etc/docker/daemon.json:

```
$ cd /etc/docker
$ sudo touch daemon.json
```
Put this in /etc/docker/daemon.json:

```
{                                                                          
    "dns": ["192.168.0.1"]                                                                           
}   
```  
And after restart docker

Solution taket from [stackoverflow](https://stackoverflow.com/questions/24991136/docker-build-could-not-resolve-archive-ubuntu-com-apt-get-fails-to-install-a)
