### ISSUE TITLE
RabbitMQ:  "Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only"

### ISSUE THREAD

**Issue by AratKruglik** [laradock/laradock#2048]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 254a9ae19490b53fc8f0647d81b7581c312f0724
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

### Issue:

RabbitMQ not starting

Terminal output:
rabbitmq_1             | 09:50:10.483 [error] Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only

rabbitmq_1             | Distribution failed: {{:shutdown, {:failed_to_start_child, :auth, {'Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only', [{:auth, :init_cookie, 0, [file: 'auth.erl', line: 286]}, {:auth, :init, 1, [file: 'auth.erl
', line: 140]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}, {:child, :undefined, :net_sup_dynamic, {:erl_d
istribution, :start_link, [[:"rabbitmqcli-58-rabbit@laradock-rabbitmq", :shortnames, 15000], false]}, :permanent, 1000, :supervisor, [:erl_distribution]}}

rabbitmq_1             |     label: 201#{label=>{proc_lib,crash},report=>[9-03-18 09:50:23.738598 crash_report        [{initial_call,{auth,init,['Argument__1']}},{pid,<0.59.0>},{registered_name,[]},{error_info,{error,"Cookie file /var/lib/rabbitmq/.erlang.cookie mu
st be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_
p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[net_sup,kernel_sup,<0.46.0>]},{message_queue_len,0},{messages,[]},{links,[<0.57.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,559}],[]]}
rabbitmq_1             | 2019-03-18 09:50:23.739147 supervisor_report   #{label=>{supervisor,start_error},report=>[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{aut
h,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{
line,249}]}]}},{offender,[{pid,undefined},{id,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}

rabbitmq_1             | 2019-03-18 09:50:23.740906 supervisor_report   2019-03-18 09:50:23.741883 crash_report        #{label=>{proc_lib,crash},report=>[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.45.
0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,in
it,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}}}},{kernel,start,[normal,[]]}},[{applicat
ion_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[<0.44.0>]},{message_queue_len,1},{messages,[{'EXIT',<0.46.0>,normal}]},{links,[<0.44.0>,<0.43.0>]},{dictionary,[]},{trap_e
xit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,184}],[]]}

### Expected behavior:

RabbitMQ starts

### Reproduce:

Build and run docker-compose build rabbitmq, docker-compose up rabbitmq

**Comment by AratKruglik** [comment]
What can I do to fix it?

**Comment by AratKruglik** [comment]
Any ideas?

**Comment by ScottChayaa** [comment]
the `.erlang.cookie` location seems be changed
try modify `docker-compose.yml`
```
### RabbitMQ #############################################
      volumes:
        - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
```

**Comment by ishanbhutagate6** [comment]
@ScottChayaa 
Thanks for the resolution, It works for me.

**Comment by dendihandian** [comment]
docker-compose.yml:

```
### RabbitMQ #############################################
    rabbitmq:
      build: ./rabbitmq
      ports:
        - "${RABBITMQ_NODE_HOST_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
      privileged: true
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      hostname: laradock-rabbitmq
      volumes:
        - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
      depends_on:
        - php-fpm
      networks:
        - backend
```

Now I got this error...

```
C:\Users\dhn\git\laradock>docker-compose up rabbitmq
laradock_docker-in-docker_1 is up-to-date
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
Starting laradock_rabbitmq_1 ... done
Attaching to laradock_rabbitmq_1
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags: list of feature flags found:
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags:   [x] drop_unroutable_metric
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags:   [x] empty_basic_get_metric
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags:   [x] implicit_default_bindings
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags:   [x] quorum_queue
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags:   [x] virtual_host_metadata
rabbitmq_1             | 2020-03-27 15:16:33.794 [info] <0.8.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1             | 2020-03-27 15:16:35.984 [error] <0.8.0> 
rabbitmq_1             | Error description:
rabbitmq_1             |     init:do_boot/3
rabbitmq_1             |     init:start_em/1
rabbitmq_1             |     rabbit:start_it/1 line 465
rabbitmq_1             |     rabbit:'-boot/0-fun-0-'/0 line 313
rabbitmq_1             |     rabbit_node_monitor:write_cluster_status/1 line 134
rabbitmq_1             | throw:{error,{could_not_write_file,"/var/lib/rabbitmq/mnesia/rabbit@laradock-rabbitmq/cluster_nodes.config",
rabbitmq_1             |                                    ebusy}}
rabbitmq_1             | Log file(s) (may contain more information):
rabbitmq_1             |    <stdout>
rabbitmq_1             |
rabbitmq_1             | BOOT FAILED
rabbitmq_1             | ===========
rabbitmq_1             |
rabbitmq_1             | Error description:
rabbitmq_1             |     init:do_boot/3
rabbitmq_1             |     init:start_em/1
rabbitmq_1             |     rabbit:start_it/1 line 465
rabbitmq_1             |     rabbit:'-boot/0-fun-0-'/0 line 313
rabbitmq_1             |     rabbit_node_monitor:write_cluster_status/1 line 134
rabbitmq_1             | throw:{error,{could_not_write_file,"/var/lib/rabbitmq/mnesia/rabbit@laradock-rabbitmq/cluster_nodes.config",
rabbitmq_1             |                                    ebusy}}
rabbitmq_1             | Log file(s) (may contain more information):
rabbitmq_1             |    <stdout>
rabbitmq_1             |
rabbitmq_1             | {"init terminating in do_boot",{error,{could_not_write_file,"/var/lib/rabbitmq/mnesia/rabbit@laradock-rabbitmq/cluster_nodes.config",ebusy}}}
rabbitmq_1             | init terminating in do_boot ({error,{could_not_write_file,/var/lib/rabbitmq/mnesia/rabbit@laradock-rabbitmq/cluster_nodes.config,ebusy}})
rabbitmq_1             |
rabbitmq_1             | Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
laradock_rabbitmq_1 exited with code 0

C:\Users\dhn\git\laradock>
```

**Comment by webtekindo** [comment]
Same as @dendihandian , do you have a solution?

**Comment by mohamedhafezqo** [comment]
Just, `rm .erlang.cookie` file

**Comment by mohamedhafezqo** [comment]
or `chmod 600 ~/.erlang.cookie`

**Comment by littletom1** [comment]
> Hey @webtekindo, Just, `rm .erlang.cookie` file from the rabbit folder and then docker-compose up

it's work for me thank you
