### ISSUE TITLE
Not installing php.56

### ISSUE THREAD

**Issue by eskrano** [laradock/laradock#2049]
### Info:
- Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`):  d0ebb32ad121fee684201617e05b119e34c7241e
- System info (Mac, PC, Linux):Mac
- System info disto/version: Mojave

### Issue:
Can't install php.56 . Installing 7.0 version
_____

### Expected behavior:
Install php 5.6
_____

### Reproduce:
in .env change php_version to 5.6 and run docker-composer build php-fpm
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by bestlong** [comment]
`docker-compose build --no-cache php-fpm workspace`

**Comment by eskrano** [comment]
> `docker-compose build --no-cache php-fpm workspace`

![image](https://user-images.githubusercontent.com/10223123/54583172-054d4300-4a1c-11e9-8313-b7ba7558fbdf.png)
![image](https://user-images.githubusercontent.com/10223123/54583184-0d0ce780-4a1c-11e9-8c76-803b1610ba6a.png)

**Comment by eskrano** [comment]
Restart full docker and it works.
