### ISSUE TITLE
Complete working example of how wire up Laravel and LaraDock with PHPStorm for remote debugging.

### ISSUE THREAD

**Issue by LarryEitel** [LaraDock/laradock#205]
I have created [laravel-laradock-phpstorm](https://github.com/LarryEitel/laravel-laradock-phpstorm) that demonstrates how to set up `LaraDock` with `PHPStorm` for **remote debugging**. It includes many configuration screenshots.

To achieve this, among other things, I extended `php-fpm` to include `ssh` and `supervisor`. When `LaraDock` is started up, ssh is already running and can be ssh'd into as well as connected to with `PHPStorm`.

I know that there are issue(s) regarding this. I hope you don't mine me posted it here.

**Comment by Mahmoudz** [comment]
Nice work @LarryEitel, I saw this before I think it is cool and people will benefit from it.
Would you consider merging some of this with LaraDock? 

I think people would like to see a section "Use xDebug" (despite which IDE they are using, with subsections like "xDebug with PHPStorm") this will be like a tutorial for how to use xDebug in LaraDock.
This can be added right below the "[Install xDebug](https://github.com/LaraDock/laradock#Install-xDebug)" sections.

What do you think?

**Comment by LarryEitel** [comment]
I think that is a **GREAT** idea! 

I and no doubt others would prefer to be able to startup `LaraDock` with the ability to start debugging from the host out of the box, in my case Windows, against 'remote' docker-container. One reason for creating [laravel-laradock-phpstorm](https://github.com/LarryEitel/laravel-laradock-phpstorm) is to be able to document the configuration for myself as well as invite input from others who may suggest a better way to accomplish this. 

For example, I [added supervisor](https://github.com/LarryEitel/laravel-laradock-phpstorm/blob/master/llp/php-fpm/Dockerfile-70-ssh-supervisor) to `php-fpm` in order to automatically launch `ssh`. Is there a better way?

Would you be interested to discuss further via Skype or Hangout?

**Comment by Mahmoudz** [comment]
Hi @LarryEitel sure why not, also we can chat on [Gitter](gitter.im/LaraDock/laradock) if you don't mind.

**Comment by LarryEitel** [comment]
Found a much more elegant solution for full debugging in PHPStorm without having to `ssh` into the `php-fpm container`. Instead, I enabled `ssh` in the `workspace` container.  [laravel-laradock-phpstorm](https://github.com/LarryEitel/laravel-laradock-phpstorm)

**Comment by Mahmoudz** [comment]
I think this should be closed now. Thanks @LarryEitel
