### ISSUE TITLE
I cant install Laradock on Windowls 10 

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2058]
Please , some one can help me ? 

I installed Laradock / Docker in the computer of my Job ( on Mac ) , it runed OK . 
But I tried to install this on my personal computer ( Windowls 10 ) , but I have been having some problem . 
First I installed the docker, it runned OK , after I download the docker from git , with this command , in my docker folder  -
git clone https://github.com/Laradock/laradock.git 

After , I typed this command -
docker-compose up -d nginx mysql phpmyadmin

AND it gave an Error  , this one -
![errror_docker](https://user-images.githubusercontent.com/19832238/54865604-a868ca00-4d46-11e9-839f-c9de85424cb0.jpg)

Do you think that my computer dont suport docker ?
How could I check if my computer support docker ?

Thanks

**Comment by Daisuke-sama** [comment]
Hey,
Try to build from scratch and play around extensions you would like to install for PHP. Try to not install imagemagick, or choose another PHP version.

**Comment by murilolivorato** [comment]
hi @Daisuke-sama , how could I do it ? does have any tutorial to do that ?

**Comment by webard** [comment]
Some troubles witp apt, imagick need that packages, so disable it. `.env` file, set
```
WORKSPACE_INSTALL_IMAGE_OPTIMIZERS=false
WORKSPACE_INSTALL_IMAGEMAGICK=false
PHP_FPM_INSTALL_IMAGEMAGICK=false
PHP_FPM_INSTALL_IMAGE_OPTIMIZERS=false
``` 
to disable imagemagic.

**Comment by murilolivorato** [comment]
Hello my friend @webard , Thanks 
It is working now . Thanks a lot .
