### ISSUE TITLE
docker-compose exec workspace bash is not working 

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2060]
Hello my friends , I installed laradock in a windows 10 , It is working , but when I type this command -
```
docker-compose exec workspace bash
```

It shows this -
```
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty
```

Some one can help me please ? thanks a lot

**Comment by petardinic** [comment]
winpty docker-compose exec workspace bash
