### ISSUE TITLE
在laradock项目中执行docker-compose up -d nginx mysql时报错

### ISSUE THREAD

**Issue by shihaha** [laradock/laradock#2061]
具体报错内容如下：
![image](https://user-images.githubusercontent.com/20572395/55007283-1b5d9380-501a-11e9-9f51-97ea404138bf.png)
请大神帮忙

**Comment by bestlong** [comment]
firewall problem

update `.env` file, set CHANGE_SOURCE=true

**Comment by shihaha** [comment]
@bestlong 谢谢您的回答，可是我把.env文件中CHANGE_SOURCE改成true，依旧报错，如下：
![image](https://user-images.githubusercontent.com/20572395/55017700-3d601180-502c-11e9-9849-3d77c72aa708.png)

**Comment by shihaha** [comment]
@bestlong `diff .env env-example`如下：
![image](https://user-images.githubusercontent.com/20572395/55054482-05dc7e00-509b-11e9-99d3-af7bb96e25c0.png)

**Comment by bestlong** [comment]
剛檢查一下 `CHANGE_SOURCE=true` 目前只有處理到 nginx 容器。
簡單的說就是 apt/pecl/composer/npm 等等的安裝與更新來源都需要置換到境內

**Comment by Nicko0x1Chan** [comment]
i have the same problem, did you solve it ?
