### ISSUE TITLE
How can I add new Mysql database ?

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2063]
Hello , can some one help me here please ?
I created I mysql database inside laradock , like these - 
![myadmin1](https://user-images.githubusercontent.com/19832238/55182400-566fdc00-516c-11e9-878d-dc0738ea00be.jpg)

But dont give me a option to create a new database , like this one -

![myadmin2](https://user-images.githubusercontent.com/19832238/55182429-6c7d9c80-516c-11e9-8c4d-498ac173edb0.jpg)

how , is the best way to create new MYSQL datbase here ?

Thanks a lote

**Comment by marciojc** [comment]
@murilolivorato you are already inside a database. Click on top where said 'Servidor mysql' to go the mysql server and then there you can create a new database.

**Comment by murilolivorato** [comment]
@marciojc  , I dont have privileges .
How Can I add privileges ?

**Comment by murilolivorato** [comment]
![mysql_db](https://user-images.githubusercontent.com/19832238/56895463-940f9f80-6a5f-11e9-89e5-14582ed18724.jpg)

I have no Privileges

**Comment by mingyarn** [comment]
@murilolivorato View this document [https://laradock.io/documentation/#create-multiple-databases-mysql](https://laradock.io/documentation/#create-multiple-databases-mysql)
