### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by Rishats** [laradock/laradock#2068]
### Can you provide ngrok  like in homestead?

**Comment by Sogl** [comment]
I use some lines from this comment for my configuration:
https://github.com/laradock/laradock/issues/54#issuecomment-220486023

**Comment by lionslair** [comment]
Would be useful for testing paypal and other services that have webhook callbacks.

**Comment by dendihandian** [comment]
> I use some lines from this comment for my configuration:
> [#54 (comment)](https://github.com/laradock/laradock/issues/54#issuecomment-220486023)

How to expose one of my multiple projects in the workspace container? e.g I have a project called `http://simple-laravel.local` and has the `simple-laravel.local.conf` for the Nginx configuration

**Comment by ArtisanTinkerer** [comment]
I am also trying to do this for testing webhooks. It would be great to have a solution.

**Comment by lionslair** [comment]
Doesn't need to be baked in. Just use ngrok outside and proxy it. Works great

**Comment by ArtisanTinkerer** [comment]
Not sure what you mean? I am just following this: https://medium.com/@sam_ngu/docker-laradock-ngrok-%EF%B8%8F-81ae4a224f08

Looks like it should work but I am getting:

```
Failed to complete tunnel connection
The connection to http://gfdsg163.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.

Make sure that a web service is running on localhost:80 and that it is a valid address.`

```

**Comment by ArtisanTinkerer** [comment]
You mean install ngrok on the host?

**Comment by lionslair** [comment]
Yes. Just install ngrok on your host system then run the following

`ngrok http -host-header=site-name-here.test 80`

or port 443 but both will map to the local from remote. Ngrok gives you a https and http endpoint so just map them to local 80 or 443 up to you. I find 80 easier but can still use https from remote.

**Comment by minhlong** [comment]
> Yes. Just install ngrok on your host system then run the following
> 
> `ngrok http -host-header=site-name-here.test 80`
> 
> or port 443 but both will map to the local from remote. Ngrok gives you a https and http endpoint so just map them to local 80 or 443 up to you. I find 80 easier but can still use https from remote.

You save me,

Tks,

**Comment by okochunk** [comment]
Thanks @lionslair it's work, I think will be great if this information added in laradock documentation cheers

**Comment by lionslair** [comment]
I have been trying this out over the past week. works well and depends on nothing really. seems to handle local self signed https certificates from Caddy too.
