### ISSUE TITLE
Cant edit file by my editor when intall Laravel in workspace container 

### ISSUE THREAD

**Issue by datnq201088** [LaraDock/laradock#207]
- When I login `workspace` container  by  root user and installed Laravel. All files project permission root. So I can not edit on my editor.

```javascript 

root@7b5c9d4bf799:/var/www/html# ll
total 8
drwxr-xr-x 2 1612712222 1612710401 4096 Aug  3 09:00 ./
drwxr-xr-x 3 root       root       4096 Aug  4 06:26 ../

```

- I try to login by `--user=laradock`. I can NOT install Laravel.

```javascript
   composer create-project laravel/laravel .

 - Installing laravel/laravel (v5.2.31)
    Downloading: 100%         
    Downloading: 100%         
    Downloading: 100%         
    Failed to download laravel/laravel from dist: Could not delete ./: 
    Now trying to download from source

``` 
How can I install Laravel and can edit from  my  host (not in contatainer) using my editor as Sublime text ?

**Comment by zhikiri** [comment]
@datnq201088 Hi, please try to check permission for project folder on your host machine

**Comment by Lednerb** [comment]
Must have something to do with the permissions on the host.

Just checked it.
With the latest version of laradock it works without problems.

**Comment by malik-optisoft** [comment]
Please Any Luck? I'm still experiencing this problem with VSCode Editor. I am unable to Save changes
