### ISSUE TITLE
How to add  zookeeper extension？ please help me！！

### ISSUE THREAD

**Issue by dakong-yi** [laradock/laradock#2073]
### Issue:

How to add  zookeeper extension？ please help me！！

**Comment by jasperf** [comment]
Did you check out https://github.com/laradock/laradock/blob/master/docker-compose.yml#L473-L483 where Zookeeper was added?

**Comment by dakong-yi** [comment]
> Did you check out https://github.com/laradock/laradock/blob/master/docker-compose.yml#L473-L483 where Zookeeper was added?

I want to add php extension ,not zookeeper
