### ISSUE TITLE
Php Imagick extension enabled in laradock but composer is unable to find it

### ISSUE THREAD

**Issue by aissasell** [laradock/laradock#2074]
### Info:
- Docker version (`$ docker --version`): 18.09.4-ce
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Linux
- System info disto/version: Antergos ArchLinux based latest

### Issue:

_____The imagick php extension is enabled and works verry fine, but when i add it to the require section of composer it prints:
The requested PHP extension ext-imagick * is missing from your system. Install or enable PHP's imagick extension

### Expected behavior:

_____Composer should be able to detect it as it actually detects: ext-ctype and ext-iconv

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by jasperf** [comment]
You did not add your composer.yml file but did you have
```
PHP_FPM_INSTALL_IMAGEMAGICK=true
```
in your Laradock .env file?

I myself am having issues making GD work well with Dropzone and Image Intervention at https://github.com/laradock/laradock/issues/1969 but ImageMagick works jus fine.

**Comment by mrseth01** [comment]
Same issue. Has anyone found a fix?

**Comment by aissasell** [comment]
> You did not add your composer.yml file but did you have
> 
> ```
> PHP_FPM_INSTALL_IMAGEMAGICK=true
> ```
> 
> and or
> 
> ```
> WORKSPACE_INSTALL_IMAGEMAGICK=true
> ```
> 
> in your Laradock .env file?
> 
> I myself am having issues making GD work well with Dropzone and Image Intervention at #1969 but ImageMagick works jus fine.

I am sorry for late response i got no notifications from github. anyway i am trying to do what u suggested.

**Comment by aissasell** [comment]
Done it's working.

**Comment by Sogl** [comment]
@aissasell What you did to make it working? A have the same issue.

**Comment by bestlong** [comment]
@Sogl jasperf post is solution.

**Comment by kaungthant1083** [comment]
the best solution for me is to rebuild the containers via the following command. 
`docker-compose` build --no-cache`
