### ISSUE TITLE
change php version error

### ISSUE THREAD

**Issue by chinahub** [laradock/laradock#2076]
### Info:
- Docker version (`$ docker --version`): 18.09.4
- System info (Mac, PC, Linux): CentOS Linux release 7.6.1810 (Core)

### Issue:
when i try to change my php version from 7.2 to 7.1，and i change .env conf like this:
`PHP_VERSION=7.1`
and rebuild:
`docker-compose build php-fpm`
and it make wrong like this:

> W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update -yqq &&     apt-get install -y apt-utils &&     pecl channel-update pecl.php.net' returned a non-zero code: 100

![image](https://user-images.githubusercontent.com/11291147/55717587-37a2fc80-5a2c-11e9-814d-6e0e44ad82ca.png)

thanks very much.

**Comment by bestlong** [comment]
docker-compose build —no-cache php-fpm

**Comment by chinahub** [comment]
@bestlong  thanks,i try to add '--no-cache' ,but it's still error.
![image](https://user-images.githubusercontent.com/11291147/55766619-0700a880-5aa8-11e9-92dc-97a155455c23.png)

**Comment by bestlong** [comment]
Check network, use debian image
```bash
~$ docker run -it --rm debian:jessie bash
Unable to find image 'debian:jessie' locally
jessie: Pulling from library/debian
bf295113f40d: Pull complete
Digest: sha256:201b887113d1190ed7811152af4c14f46a7ce8612dfdaee540fc353f5135d25a
Status: Downloaded newer image for debian:jessie
root@de2262d7c426:/# apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Get:3 http://deb.debian.org jessie Release [148 kB]
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 8s (1241 kB/s)
Reading package lists... Done
root@de2262d7c426:/# exit
~$
```

**Comment by chinahub** [comment]
thanks.

**Comment by Sogl** [comment]
@chinahub @bestlong How to solve this problem? I tried to use these commands without success.

**Comment by bestlong** [comment]
@Sogl Same error message?
Failed to fetch mostly network problem, reboot and check again internet available.

**Comment by Sogl** [comment]
Yeah the same. Solved with pulling new laradock version (but it create new problems 😄 )
