### ISSUE TITLE
Can't connect to MySQL using mysql as host

### ISSUE THREAD

**Issue by andytriboletti** [laradock/laradock#2105]
### Info:
- Docker version (`$ docker --version`): 
[root@li1122-227 laradock]# docker --version

Docker version 18.09.5, build e8ff056
- Laradock commit (`$ git rev-parse HEAD`): 
d8c36ab86007f04293d380bcf8325cb70c76fdd0

- System info (Mac, PC, Linux): 
Linux

- System info disto/version: 
Centos

### Issue:
I can't connect to MySQL unless I use % as the host when granting privileges
_____

### Expected behavior:

I should be able to use 'mysql' as the host.
_____

### Reproduce:

Install the code I'm trying to install on Linux:
https://github.com/greenrobotllc/adserver/
_____

### Relevant Code:

In mysql/Dockerfile I added this:

RUN sed -i "s/skip-name-resolve/# /" /etc/mysql/conf.d/docker.cnf

I get this error:

Access denied for user 'adserver_c'@'laradock_php-fpm_1.laradock_backend' (using password: YES) 

Configure the databases:
CREATE DATABASE adserver
CREATE USER adserver_c@'mysql' IDENTIFIED WITH native_mysql_password BY 'password';
GRANT ALL ON adserver.* TO adserver_c@'mysql';
FLUSH PRIVILEGES

**Comment by metalcamp** [comment]
@bestlong I believe this issue can now be closed.
