### ISSUE TITLE
Apache?

### ISSUE THREAD

**Issue by qrczak** [LaraDock/laradock#211]
Is it possible run Laradock with Apache2 instead Nginx? I'm asking because here on Github page is mention there there are 3 web servers including Apache. But on http://laradock.github.io/laradock/ which is Laradoc information page there are no word about Apache2 at all.

**Comment by Mahmoudz** [comment]
Oh thanks for the notice we do actually support Apache2 but that pages wasn't updated. I will update it right now. Thanks again
