### ISSUE TITLE
question: Kompose - deploying with kubernetes

### ISSUE THREAD

**Issue by kvanleeuwen** [laradock/laradock#2128]
### Info:
- Docker version 3
- Using tools: Kompose.io, Kubernetes

### Issue:
Hello, I am trying to deploy laradock for production with Komose (kompose.io) to Kubernetes (and finally to a Cloud Provider). After 3 days of trying and researching it worked out. The only problem I got left, is that I still see welcome to nginx when it is deployed with Kubernetes to Digital Ocean. I think the main reason is that the internal IP (127.0.0.1) can access the host, but there is a loadbalancer active, and I guess there it goes wrong. Do I need to assign an IP or something? Does someone have a clue? I can not find any good resources or similar cases. Thanks a lot for helping me out!

Kevin

**Comment by andreustimm** [comment]
up
