### ISSUE TITLE
How to connect to host MySQL server without using MySQL Docker container

### ISSUE THREAD

**Issue by rscotten** [LaraDock/laradock#213]
Hello,

I'm running the latest Docker for Mac on OSX Yosemite.  I have a MySQL server running on my Mac.  Let's call my local machine my "Mac host."  Thus, Laradock is running on top of Docker for Mac, which is running on top of my Mac host.

From my Laradock instance, I want to connect to this MySQL server / database on my Mac host.  I've tried using "volumes" with the MySQL Laradock Docker container, and it works, but I wonder if it's slower than connecting to a "remote" MySQL server running on my Mac host.

The problem is, I'm not sure how to configure this.  It seems like the Docker containers all think that 127.0.0.1 or "localhost" lives within their container, and I don't know how to tell them to look outside their container at the IP address of my Mac host to connect to the MySQL server.

I've looked at the Docker Compose documentation, and I can't seem to find anywhere how to do this using port mapping/forwarding, extra hosts, networks, proxies, etc.  

Can somebody please tell me how to connect to the MySQL server running on my Mac host from the Laradock Docker containers?

**Comment by hal2dy** [comment]
Hi,
I'm not using Laradock but I got the same issue with my container and here is my solution:

try to `ifconfig` on your mac, and you will see your host ip address, in my case it's 192.168.1.90

> en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether d0:a6:37:eb:13:15 
	inet6 fe80::d2a6:37ff:feeb:1315%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.1.90 netmask 0xffffff00 broadcast 192.168.1.255
	...

use that ip address as mysql host, see if it can help 

(side comment: I found that docker-for-mac 1.12 is very slow compare to docker-machine)

**Comment by sidcool1234** [comment]
Where do I specify the IP address that you mention?
