### ISSUE TITLE
Xdebug Settings Help

### ISSUE THREAD

**Issue by kemalatila** [laradock/laradock#2130]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.6, build 481bc77
- Laradock commit (`$ git rev-parse HEAD`):  c84a57cd13e243d1f685937b1cd193dc9b621bbe
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04

### Issue:

I use webpack on frontend and my backend calling from proxy over http://localhost:4200/backend. I found my docker IP address from ifconfig.. set WORKSPACE_INSTALL_WORKSPACE_SSH=true

![image](https://user-images.githubusercontent.com/2404219/57618776-fbb00980-758c-11e9-84eb-43789f0b9a4a.png)

![image](https://user-images.githubusercontent.com/2404219/57618848-213d1300-758d-11e9-9218-975518e55515.png)

Also my example request contains XDEBUG_SESSION=PHPSTORM

![image](https://user-images.githubusercontent.com/2404219/57619088-c657eb80-758d-11e9-9cbc-bed61f07ecd8.png)

![image](https://user-images.githubusercontent.com/2404219/57619257-28185580-758e-11e9-9ab7-a5ceee6acf12.png)

![image](https://user-images.githubusercontent.com/2404219/57619305-4aaa6e80-758e-11e9-8c7d-043fe1bbf7a4.png)

I made the above settings. I checked Xdebug runs but still dosen't debug. Where am I making mistakes. I just want to use Xdebug.

**Comment by onahkenneth** [comment]
@kemalatila 
When you setup server **example.test**, did you also setup your path mapping from local to docker container?

**Comment by kemalatila** [comment]
@onahkenneth I have already made path mapping
![image](https://user-images.githubusercontent.com/2404219/57909772-62cf0600-788c-11e9-8250-c5da9abbc718.png)

**Comment by onahkenneth** [comment]
@kemalatila 
`xdebug.remote_host=dockerhost
xdebug.remote_connect_back=0
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM

xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.cli_color=1
xdebug.profiler_enable=0
xdebug.profiler_output_dir="~/xdebug/phpstorm/tmp/profiling"

xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1`

xdebug.ini settings that I use and it works for me.

**Comment by kemalatila** [comment]
I solved the problem. "xdebug.remote_host" was incorrect in both xdebug.ini because of dockerhost wasn't defined. fixed settings and rebuild containers with "docker-compose build workspace php-fpm" and than worked.
