### ISSUE TITLE
fail install soap 

### ISSUE THREAD

**Issue by xiaoguo0426** [laradock/laradock#2132]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.6, build 481bc77
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
Linux
- System info disto/version: 
Ubuntu16.04
### Issue:

_____

### Expected behavior:

_____

### Reproduce:

.env
`
WORKSPACE_INSTALL_SOAP=true
`
_____

### Relevant Code:

```
 ---> 041edcca4d28
Step 58/205 : RUN if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${LARADOCK_PHP_VERSION}-soap ;fi
 ---> Running in a0bf7768bc1d
Reading package lists...
Building dependency tree...
Reading state information...
libxml2-dev is already the newest version (2.9.4-1+deb.sury.org~xenial+2).
The following package was automatically installed and is no longer required:
  libzip5
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  php7.2-soap
0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
Need to get 111 kB of archives.
After this operation, 332 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.2-soap amd64 7.2.17-1+ubuntu16.04.1+deb.sury.org+3
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-soap_7.2.17-1+ubuntu16.04.1+deb.sury.org+3_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${LARADOCK_PHP_VERSION}-soap ;fi' returned a non-zero code: 100

```

**Comment by onahkenneth** [comment]
@xiaoguo0426 
Change `php${LARADOCK_PHP_VERSION}-soap` to `php-soap` in your docker file

**Comment by xiaoguo0426** [comment]
`
docker-compose build --no-cache workspace
`
it is work for me

**Comment by ledtest** [comment]
> ### Info:
> * Docker version (`$ docker --version`): Docker version 18.09.6, build 481bc77
> * Laradock commit (`$ git rev-parse HEAD`):
> * System info (Mac, PC, Linux):
>   Linux
> * System info disto/version:
>   Ubuntu16.04
> 
> ### Issue:
> ### Expected behavior:
> ### Reproduce:
> .env
> `WORKSPACE_INSTALL_SOAP=true`
> 
> ### Relevant Code:
> ```
>  ---> 041edcca4d28
> Step 58/205 : RUN if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${LARADOCK_PHP_VERSION}-soap ;fi
>  ---> Running in a0bf7768bc1d
> Reading package lists...
> Building dependency tree...
> Reading state information...
> libxml2-dev is already the newest version (2.9.4-1+deb.sury.org~xenial+2).
> The following package was automatically installed and is no longer required:
>   libzip5
> Use 'apt autoremove' to remove it.
> The following NEW packages will be installed:
>   php7.2-soap
> 0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
> Need to get 111 kB of archives.
> After this operation, 332 kB of additional disk space will be used.
> Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.2-soap amd64 7.2.17-1+ubuntu16.04.1+deb.sury.org+3
>   404  Not Found
> E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-soap_7.2.17-1+ubuntu16.04.1+deb.sury.org+3_amd64.deb  404  Not Found
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${LARADOCK_PHP_VERSION}-soap ;fi' returned a non-zero code: 100
> ```

First，you need to run：
docker-compose --no-cache build workspace php-fpm
Then，run：
docker-compose up -d nginx mysql redis workspace
Finally，enter your workspace，eg：
docker-compose exec workspace bash
composer show -p | grep -q ext-soap
You will see soap extension installed.

More details is here：
https://github.com/laradock/laradock/issues/1362
