### ISSUE TITLE
cannot send mail `sh: 1: /usr/sbin/sendmail: not found`

### ISSUE THREAD

**Issue by drizzersilverberg** [laradock/laradock#2134]
### Info:
- Docker version : Docker version 18.09.2, build 6247962
- Laradock commit : c7289f7db3b96be585a879ceaf0f208102f8233f 
- System info : PC
- System info disto/version: Windows 10 Enterprise 1809 

### Issue:
Trying to send email in laravel app, get error with `sh: 1: /usr/sbin/sendmail: not found`
_____

### Expected behavior:
Email sent to my mailtrap inbox
_____

### Reproduce:
1. run and build with this command `docker-compose up -d nginx mysql phpmyadmin`
2. try to sent simple email in laravel app, im create and using artisan command
3. get ` sh: 1: /usr/sbin/sendmail: not found` error in console
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by mlapan** [comment]
by default i dont think sendmail is installed on the docker box.
you shouldnt need sendmail to use the mailtrap api though?

is mailtrap configured correctly in your .env?
