### ISSUE TITLE
Cannot start service nginx

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2139]
Hello guys , 

I am trying to install laradock ,  version is -18.09.2 , in Windols 10 .
when I type -

```
docker-compose up -d nginx
```
give this error -

```
for laradock_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (4edb7eb00e41723e706396dbbdd2146fd896d24c89557a81d2fe6c93c5b53b31): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied

```
![error_2](https://user-images.githubusercontent.com/19832238/58041023-68874e80-7b0d-11e9-8613-d810c4f69002.gif)

Some one can help me please ?
Thanks

**Comment by mlapan** [comment]
`unexpected error Permission denied`

did you try `sudo docker-compose up -d nginx` ?
if that works, then docker isnt setup to use a non privileged user

**Comment by xiagw** [comment]
> Hello guys ,
> 
> I am trying to install laradock , version is -18.09.2 , in Windols 10 .
> when I type -
> 
> ```
> docker-compose up -d nginx
> ```
> 
> give this error -
> 
> ```
> for laradock_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (4edb7eb00e41723e706396dbbdd2146fd896d24c89557a81d2fe6c93c5b53b31): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied
> ```
> 
> ![error_2](https://user-images.githubusercontent.com/19832238/58041023-68874e80-7b0d-11e9-8613-d810c4f69002.gif)
> 
> Some one can help me please ?
> Thanks

open powershell with **super administrator** 
then `docker-compose up -d nginx`

**Comment by murilolivorato** [comment]
thanks

**Comment by PaddyLock** [comment]
I get the same error for latest laradock, on Mac (mojave 10.14.3) using Docker Desktop (Docker 2.0.0.3)

I'm not running as sudo

![Screenshot 2019-05-28 at 10 55 02](https://user-images.githubusercontent.com/539158/58469285-19f23980-8137-11e9-9d64-3eed617f220d.png)

**Comment by stevepop** [comment]
I am having the same error in Mac OS Mojave.  with the error, 
```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (18020b35677406ed1f76ef7b6807af110b69271ab62a84732532ebb9544ac3c5): Error starting userland proxy: port is already allocated.
```
I checked that port 80 is not being used so not sure what else to check.
Any fix for this please?
