### ISSUE TITLE
Using chmod 777 on production a good idea?

### ISSUE THREAD

**Issue by ojhaujjwal** [LaraDock/laradock#214]
So, I saw this in readme:
```bash
sudo chmod -R 777 storage bootstrap/cache
```

Is it a good idea in production as well or should it be done only in development environment?

**Comment by Mahmoudz** [comment]
@ojhaujjwal actually that's not a good idea, `755` for folders and `644` for files is more secure.

**Comment by appleboy** [comment]
@Mahmoudz Catch point. 👍 

@ojhaujjwal Change folder user permission as your `nginx` or `apache` user.

**Comment by ojhaujjwal** [comment]
In that case, I am not sure how to use this production.
I think `www-data` user in nginx container should have the same user id as the one in the host owner. Similiar to how it is done in workspace container for the `laravel` user.

**Comment by ojhaujjwal** [comment]
Can anybody create www-data user and group in nginx with $PUID and $PGID?
I tried doing that to send a PR. But. I couldn't not find that command to do that in alpine.
