### ISSUE TITLE
How to fix redis: Connection refused [tcp://redis:6379]

### ISSUE THREAD

**Issue by vietlai1190** [laradock/laradock#2143]
### Info:
- Docker version (`$ docker --version`):  18.09.2, build 6247962
- System info (Mac, PC, Linux): Mac
- System info disto/version: Mojave

### Issue:

I have set a password for redis by uncomment in redis Dockerfile
```ruby
## For security settings uncomment, make the dir, copy conf, and also start with the conf, to use it
RUN mkdir -p /usr/local/etc/redis
COPY redis.conf /usr/local/etc/redis/redis.conf
```
and 
```ruby
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
```

After, set enable "requirepass" is "mypass" in redis.conf
And then I updated the .env file in laravel project:
```ruby
REDIS_HOST=redis
REDIS_PASSWORD=mypass
REDIS_PORT=6379
```
But I get an exception error message:
```ruby
Predis \ Connection \ ConnectionException (111)
Connection refused [tcp://redis:6379]
```

**Comment by mlapan** [comment]
does redis work without the password (and dropping the requirement for the password in the conf)?

**Comment by fabbrikk** [comment]
to get it working, follow this steps:
[https://github.com/laradock/laradock/issues/2254](https://github.com/laradock/laradock/issues/2254)
