### ISSUE TITLE
nginx proxy not working

### ISSUE THREAD

**Issue by tranducit95** [laradock/laradock#2145]
### Info:
- Docker version (`$ docker --version`): 18.09.6, build 481bc77
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Linux
- System info disto/version: 18.04

### Issue:

I cannot request to server (laravel)
_____

### Expected behavior:

I use reactjs (ant design pro) as client, deploy using nginx in laradock. everything works normally, except I can't request to backend (laravel).
domain client: admin.localhost.dev
domain server: api.localhost.dev
I use nginx proxy to navigate requests to the server, but without success, status returns 302,
api url has the form: http: //api.localhost.dev/api /foo/bar
_____

### Reproduce:

_____

### Relevant Code:
file conf client: client.conf
```
server {
    listen 80;
    # gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    server_name admin.localhost.test;
    root /var/www/dist;

    location / {
        # Used in conjunction with browserHistory
        try_files $uri $uri/ /index.html;

        # If you have resources, it is recommended to use https + http2 for a better experience with on-demand loading.
        # rewrite ^/(.*)$ https://preview.pro.ant.design/$1 permanent;

    }

    location /api {
        proxy_pass http://api.localhost.test;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              api.localhost.test
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}

```

**Comment by mlapan** [comment]
for local dev, you cant use .dev anymore.

also does this config work on nginx outside of the docker container?

**Comment by tranducit95** [comment]
> for local dev, you cant use .dev anymore.
> 
> also does this config work on nginx outside of the docker container?
> also your proxy header host is api..localhost.dev, theres an extra `.` in there
Sorry, I corrected the domain incorrectly, I used .local instead of .dev, proxy_set_header Host api.localhost.dev, I wrote ".".

I use ant pro, when develop client does not use nginx, run another container and network connection together, everything works normally, now I want to deploy, I have this problem,
