### ISSUE TITLE
I cant set port in windowls 10

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2151]
Hello , I always used Laradock and Docker . but now I formated my computer . and installed windowls 10 ,
The problem is that windowls 10  does not aloud me to use port 80 . so I am trying to use port 8080 .
I have been having some problems , could some one help me here please ?

I am doing this -

I setted the .env file 
![1](https://user-images.githubusercontent.com/19832238/58426167-1fd21700-8072-11e9-9a38-166b638d54ef.gif)

I setted the docker-compose.yml file -
![2](https://user-images.githubusercontent.com/19832238/58426180-26608e80-8072-11e9-854d-516d6efde09c.gif)

nginx/sites/default.conf
![3](https://user-images.githubusercontent.com/19832238/58426226-48f2a780-8072-11e9-88bb-4099c37f3d75.gif)

windols - C:\Windows\System32\drivers\etc\hosts 
![4](https://user-images.githubusercontent.com/19832238/58426665-886dc380-8073-11e9-8917-c8615b86577e.gif)

I type - docker-compose up -d nginx 
It is working ok -
![6](https://user-images.githubusercontent.com/19832238/58426608-62e0ba00-8073-11e9-984b-3588e9affdaf.gif)

But I it cant find the host -
![5](https://user-images.githubusercontent.com/19832238/58426446-dfbf6400-8072-11e9-9986-510fee9e604d.gif)

**Comment by murilolivorato** [comment]
I used port 8081 , now it is ok .

**Comment by xiagw** [comment]
@murilolivorato ，
1, docker-compose.yml file , do not need to change
2, nginx/sites/default.conf, (look at "root /var/www/public")
You only need to create a directory:
```
mkdir laradock/../public
echo "welcome" >laradock/../public/index.html
```
