### ISSUE TITLE
 proc_open(): fork failed - Cannot allocate memory

### ISSUE THREAD

**Issue by AngryBigCat** [laradock/laradock#2154]
when i run `composer update` in the workspace container, print a error:
```
proc_open(): fork failed - Cannot allocate memory
```

i visited https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors
execute following command:
```
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1
```
and then, print a error:
```
swapon: /var/swap.1: swapon failed: Operation not permitted
```
What should i do?

**Comment by xiagw** [comment]
Do you run as root ?

**Comment by AngryBigCat** [comment]
of cause!
but root permission useless in the worksapce of docker conatiner

**Comment by AngryBigCat** [comment]
i tried rebuild workspace and set --memory param, then it work.

**Comment by fpcarva** [comment]
@AngryBigCat  How can I do this?
