### ISSUE TITLE
Failed to up mssql

### ISSUE THREAD

**Issue by lovebugs19930207** [laradock/laradock#2157]
### Info:
- Docker version : Docker version 18.09.2, build 6247962 
- System info : PC
- System info disto/version: windows10 x64

### Issue:
I tried to up the mssql service.The following error message appears.
```
$ docker-compose up mssql
Starting cps_mssql_1 ... done
Attaching to cps_mssql_1
mssql_1                | tail: cannot open '/dev/null'$'\r' for reading: No such file or directory
mssql_1                | tail: no files remaining
cps_mssql_1 exited with code 1
```

How to solve this problem？

**Comment by lovebugs19930207** [comment]
It has been settled.

**Comment by leandroruel** [comment]
where is the solution, downloaded laradock and today i'm facing same issue

**Comment by Stokoe0990** [comment]
We're having a similar issue.

Please post solution OP.
