### ISSUE TITLE
Not able to exec workspace as laradock user

### ISSUE THREAD

**Issue by stefanheimann** [LaraDock/laradock#216]
Hy,

I just wanted to try out laradock. As I'm switching from Homestead and I'm new to docker, I just followed the instructions, without having any deep background knowledge.

If I want to exec the workspace container as non-root user like explained in step 2, I get the following error:

`unable to find user laradock: no matching entries in passwd file`

I ran the following command
`docker-compose exec --user=laradock workspace bash`

Does anybody know why this is happening?

Additinal Info:
I'm running Docker native on MacOS 10.11.6

**Comment by Lednerb** [comment]
@stefanheimann did you try to rebuild the container and do you have the latest version of laradock?

I've had the same error some time ago but with the latest version of laradock and docker on Ubuntu it work's without any problems.

**Comment by prezire** [comment]
Just experienced this similar issue today on master.

**Comment by bestlong** [comment]
@prezire 

my test is ok.
```
~/Sites/laradock (master *)$ docker-compose up -d nginx
Creating network "laradock_frontend" with driver "bridge"
Creating network "laradock_backend" with driver "bridge"
Creating network "laradock_default" with the default driver
Creating laradock_docker-in-docker_1 ... done
Creating laradock_workspace_1        ... done
Creating laradock_php-fpm_1          ... done
Creating laradock_nginx_1            ... done
~/Sites/laradock (master *)$ docker-compose exec workspace bash
root@b2765ec3cd52:/var/www# id
uid=0(root) gid=0(root) groups=0(root)
root@b2765ec3cd52:/var/www# exit
~/Sites/laradock (master *)$ docker-compose exec -u laradock workspace bash
laradock@b2765ec3cd52:/var/www$ id
uid=1000(laradock) gid=1000(laradock) groups=1000(laradock),8377(docker_env)
laradock@b2765ec3cd52:/var/www$ exit
~/Sites/laradock (master *)$ git log -n 1
commit d27f4368eec570d0a6a12136cb8476fbc1cb343a (HEAD -> master)
Author: Slava Razum <modern.web.artisan@gmail.com>
Date:   Sat Feb 9 11:06:26 2019 +0200

    Run bash when login by `laradock` via ssh (#1541)
~/Sites/laradock (master *)$
```
