### ISSUE TITLE
nginx image fail to build -- adduser: group 'www-data' in use

### ISSUE THREAD

**Issue by ohmyhusky** [laradock/laradock#2160]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 9e537ee16ba90d782a9ab4614c520a5aa1118296
- System info (Mac, PC, Linux): 
- System info disto/version: 
'c.          
                 ,xNMM.          ----------------------------------------
               .OMMMMo           OS: macOS Mojave 10.14.5 18F132 x86_64
               OMMM0,            Host: MacBookPro14,3
     .;loddo:' loolloddol;.      Kernel: 18.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 4 days, 23 hours, 48 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 169 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.7.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080, 1440x900, 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: chunkwm
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: AurulentSansMonoNerdFontC-Regular 14
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-7920HQ (8) @ 3.10GHz
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel HD Graphics 630, Radeon Pro 560, Radeon RX Vega 64
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 9270MiB / 16384MiB
       .cooc,.    .,coo:.
### Issue:

_____
nginx image can not be built
### Expected behavior:

_____
nginx image should be built
### Reproduce:

_____
use the newest nginx:alpine to build 
### Relevant Code:

```
docker-compose build --no-cache nginx
```
The newest nginx:alpine image already has the `www-data` group, so maybe consider update the nginx Dockerfile to attach the `www-data` user to that existing group by `-Gwww-data`?

**Comment by lionslair** [comment]
Colleague is experiencing this today too. Not sure how to do the suggested change. I told him to change the FROM line of the nginx Dockerfile to 

FROM nginx:alpine:1.15.12

Should solve the issue in the meantime.

**Comment by ohmyhusky** [comment]
@lionslair I mean change the https://github.com/laradock/laradock/blob/HEAD/nginx/Dockerfile#L20 to `adduser -D -H -u 1000 -s /bin/bash -Gwww-data www-data`. You are right, lock the nginx version will help as well.

**Comment by lionslair** [comment]
Would the new line be 
&& adduser -G www-data

**Comment by zahdxj** [comment]
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apk update     && apk upgrade     && apk --update add logrotate     && apk add --no-cache openssl     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash -G www-data' returned a non-zero code: 1

**Comment by zahdxj** [comment]
who can help me.....

**Comment by Jano14** [comment]
Same problem here. 

In my case trying to make the build in google cloud.

**Comment by Jano14** [comment]
Works! Thank you!

**Comment by pleone** [comment]
In nginx Dockerfile i used `FROM` nginx:1.15.12-alpine` and it worked for me.

> Colleague is experiencing this today too. Not sure how to do the suggested change. I told him to change the FROM line of the nginx Dockerfile to
> 
> FROM nginx:alpine:1.15.12
> 
> Should solve the issue in the meantime.

**Comment by shov** [comment]
Hi @bestlong I think it's time to make a release because 7.14 has this issue

**Comment by hokhyk** [comment]
One of the correct way to solve this problem is:
 && adduser -D -H -u 1000 -s /bin/bash www-data -G www-data

**Comment by ajthenewguy** [comment]
@hokhyk Thanks!
To clarify I changed /nginx/Dockerfile:19 from:
`&& adduser -D -H -u 1000 -s /bin/bash www-data`
to
`&& adduser -D -H -u 1000 -s /bin/bash www-data -G www-data`

**Comment by ahmedElghandour1** [comment]
> In nginx Dockerfile i used `FROM nginx:1.15.12-alpine` and it worked for me.
> 
> > Colleague is experiencing this today too. Not sure how to do the suggested change. I told him to change the FROM line of the nginx Dockerfile to
> > FROM nginx:alpine:1.15.12
> > Should solve the issue in the meantime.

it worked for me too

**Comment by msartini** [comment]
it worked me too.

**Comment by MYSHINJII** [comment]
> it worked me too.

It Worked!!

**Comment by nguyenvq** [comment]
It worked me too

**Comment by IgnacioVidalVallejo** [comment]
It worked for me too ! 
nginx Dockerfile:  FROM nginx:1.15.12-alpine

**Comment by JexPY** [comment]
This bug is back
+ addgroup -g 82 -S www-data
addgroup: group 'www-data' in use
+ adduser -u 82 -D -S -G www-data www-data
adduser: user 'www-data' in use
+ exit 1

**Comment by danielfaust** [comment]
This happens again in Alpine 3.14.

I added a non-failing `delgroup` command before the `adduser` in my Dockerfile which fixed the problem.

```
(delgroup www-data || true) && \
adduser -D www-data && \
```

**Comment by lotyp** [comment]
```
adduser -u 82 -D -S -G www-data www-data
```
