### ISSUE TITLE
libgs9_9.26a~dfsg-0+deb9u1_amd64.deb  404  Not Found

### ISSUE THREAD

**Issue by zongmi** [laradock/laradock#2163]
### Info:
- Docker version: 

Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/version: dial unix /var/run/docker.sock: connect: permission denied

- Laradock commit (`$ git rev-parse HEAD`): 

9e537ee16ba90d782a9ab4614c520a5aa1118296

- System info (Mac, PC, Linux): 

linux-deepin

- System info disto/version: 

15.10.1

### Issue:

_____
`sudo docker-compose build php-fpm`
_____
`E: Failed to fetch http://security-cdn.debian.org/debian-security/pool/updates/main/g/ghostscript/libgs9_9.26a~dfsg-0+deb9u1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -y libmagickwand-dev imagemagick &&     pecl install imagick &&     docker-php-ext-enable imagick ;fi' returned a non-zero code: 100`

http://security-cdn.debian.org/debian-security/pool/updates/main/g/ghostscript/libgs9_9.26a~dfsg-0+deb9u1_amd64.deb  404 ?????
![深度截图_选择区域_20190605181236](https://user-images.githubusercontent.com/18360503/58948811-929f6880-87bd-11e9-9402-7300bd8ffcb6.png)

Thanks

**Comment by bestlong** [comment]
@zongmi try `sudo docker-compose build --no-cache php-fpm`
