### ISSUE TITLE
PHP Warning: PHP Startup: Unable to load dynamic library 'tideways.so'

### ISSUE THREAD

**Issue by vicenteherrera** [laradock/laradock#2169]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 63fc1fde44cc00aacb89511a441cb83685e8010c
- System info (Mac, PC, Linux): Mac & PC/Windows
- System info disto/version: macOS 10.14 Mojave & Windows 10

### Issue:
Each PHP execution returns a warning about missing tideways.so extension (used for XHPROF), when INSTALL_XHPROF=false in .env:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'tideways.so'`

_____

### Expected behavior:
No warning message
_____

### Reproduce:
```
$ cd laradock
$ ./php-fpm/xdebug status
PHP Warning:  PHP Startup: Unable to load dynamic library 'tideways.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/tideways.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/tideways.so: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/tideways.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/tideways.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.2.15 (cli) (built: Feb 21 2019 23:48:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies
```
_____

### Relevant Code:

```
// Shows on any php code execution
```

**Comment by vicenteherrera** [comment]
For a more permanent solution, see pull request #2170 that edits laradock/php-fpm/Dockerfile.

A workaround way to fix it is to execute:
```
cd laradock
docker-compose exec php-fpm sed -i "s/extension=tideways.so/;extension=tideways.so/" /usr/local/etc/php/conf.d/xhprof.ini
```

But if you rebuild the php-fpm image, you will have to run that again.

**Comment by forecho** [comment]
#2141

**Comment by JexPY** [comment]
Core Warning: PHP Startup: Unable to load dynamic library 'tideways.so' Still getting error after update.
