### ISSUE TITLE
docker-compose up -d nginx mysql

### ISSUE THREAD

**Issue by Jano14** [laradock/laradock#2172]
### Info:
- Docker version (18.09.6): 
- Laradock commit (63fc1fde44cc00aacb89511a441cb83685e8010c): 
- System info (Linux) 

### Issue:

When I run the command:

`sudo docker-compose up -d nginx mysql`

The process starts correctly but when arrive to the 11 step of the workspace:

`RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'`

Give this error:

`Err:23 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
  Connection failed`

`Err:24 http://security.ubuntu.com/ubuntu xenial-security/main Sources
  Connection failed [IP: 91.189.88.149 80]`

`Err:52 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources
  Connection failed [IP: 91.189.91.26 80]`

`Err:65 http://archive.ubuntu.com/ubuntu xenial-backports/main Sources
  Connection failed [IP: 91.189.88.31 80]`

`W: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/xenial/main/binary-amd64/Packages  Connection failed
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/source/Sources  Connection failed [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/source/Sources  Connection failed [IP: 91.189.91.26 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/source/Sources  Connection failed [IP: 91.189.88.31 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c set -xe;     apt-get update &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 100`
_____

### Expected behavior:

That it ups the machines correctly.
_____

**Comment by Jano14** [comment]
Can someone help me?

Please!!

**Comment by esfahanweb** [comment]
is your connection stable?
can you access these repositories in your system out of the docker?

**Comment by Jano14** [comment]
Yes, I have a stable connection and I can access to all the repositories out of the docker, through URL and IP. Also if I ping the repositories I reach it.

I don't understand... The server is connected to internet directly without proxy.

**Comment by Sogl** [comment]
@Jano14 It's in your `workspace` container.

Some thoughts:
- Try to rebuild it without cache: `docker-compose build --no-cache workspace` and `docker-compose up -d workspace`
- Try to use VPN or proxy on machine. Sometimes it helps me with connection problems.
- Is your `workspace` builded before? Set `WORKSPACE_INSTALL_PING=true` in `.env`, then `docker-compose build workspace` and finally check connection inside container `docker-compose exec workspace ping 8.8.8.8`
- See container logs with: `docker logs laradock_workspace_1` or install Kitematic to do this in GUI. Any errors or something?

**Comment by Jano14** [comment]
Thank you for the info!

I can reach to build the container, the process falls before. 

The first point give the same issues. And the another ones as I can build de `workspace` container doesn't work also.

Any other ideas?

Thank you!

**Comment by Sogl** [comment]
Try to set `CHANGE_SOURCE=true` in `.env` and `docker-compose build --no-cache workspace`.

If it doesn't help, try:
1. `docker images` to see all
2. `docker rmi {workspace-image-name}`
3. `docker-compose build --no-cache workspace`
4. `docker-compose up -d workspace`

Also you can try with experimental lines from here https://github.com/fideloper/docker-nginx-php/issues/15 (put it before problem lines):
```
RUN apt-get update -yqq
RUN apt-get -y install locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN add-apt-repository -y ppa:ondrej/php
```

If it doesn't help too, try to restart docker and machine... sometimes it helps after all 😄

**Comment by Sogl** [comment]
Forum topic with the same problem: https://ubuntuforums.org/showthread.php?t=1844030

**Comment by Jano14** [comment]
I go to try.

Thank you, I keep you informed.

**Comment by Jano14** [comment]
I have tried all and I have the same issues.

What I see is that the repositories in the `etc/apt/sources.list` file are different that the list showed when I run the command `apt-get update` from Docker.

Information that could help: The servers where I am working are located in Azerbaijan.

**Comment by Sogl** [comment]
Try to use european VPN.
For example, https://www.vpnbook.com/freevpn (i did't check it)

And also you can create an issue in Ondrej repo: https://github.com/oerdnj/deb.sury.org/issues
Your situation is interesting.

**Comment by mikloshumli** [comment]
I get this problem too. I delete all containers reinstall latest laradock and can't build containers. Anybody help me? If I copy and paste link to browser can download eg.: http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/i/icu/libicu64_64.1-0.1+ubuntu16.04.1+deb.sury.org+1_amd64.deb but docker build drop this errors:  
```
Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/i/icu/libicu64_64.1-0.1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/libz/libzip/libzip4_1.5.1-4+ubuntu16.04.1+deb.sury.org+2_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/libz/libzip/libzip-dev_1.5.1-4+ubuntu16.04.1+deb.sury.org+2_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-opcache_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-intl_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-json_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-readline_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-cli_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-mbstring_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-pgsql_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-xml_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-gd_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-common_7.2.19-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  Connection timed out
```

**Comment by Jano14** [comment]
Hello,

I solved the issue following this tutorial: [(https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-16-04]

)And also adding the MTU value in the file `/lib/systemd/system/docker.service`:

`ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --mtu 1450`

**Comment by MrLegeek** [comment]
logs/nginx/error.log
[emerg] 10#10: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1


help me

**Comment by bestlong** [comment]
@mikloshumli try `docker-compose build --no-cache nginx mysql php-fpm`

**Comment by Jason-LZai** [comment]
![image](https://user-images.githubusercontent.com/50620039/83500006-cf955c80-a4f0-11ea-8030-ebb1020eba00.png)
Hi guys, can some help me? When I try to install laradock I got this issue,
`docker-compose up -d nginx mysql phpmyadmin redis workspace`
got the error
`+ apt-get update -yqq
E: The repository 'http://mirrors.aliyun.com/ubuntu bionic Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu bionic Release' no longer has a Release file.
E: The repository 'http://mirrors.aliyun.com/ubuntu bionic-security Release' does not have a Release file.
E: The repository 'http://mirrors.aliyun.com/ubuntu bionic-updates Release' does not have a Release file.
E: The repository 'http://mirrors.aliyun.com/ubuntu bionic-proposed Release' does not have a Release file.
E: The repository 'http://mirrors.aliyun.com/ubuntu bionic-backports Release' does not have a Release file.
`
