### ISSUE TITLE
[emerg] getpwnam("www-data") failed in /etc/nginx/nginx.conf:1

### ISSUE THREAD

**Issue by lionslair** [laradock/laradock#2173]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by MrLegeek** [comment]
I have the same problem. How can I solve it?
