### ISSUE TITLE
PHP PG ADMIN with POSTGREE , I cant access 

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2178]
Hello , Some one can help me here . please .
I have been using MYSQL + PHPMYADMIN in all my projects , but now I will have to use in a project POSTGRES + PGADMIN .

so I did -

```
docker-compose down
docker-compose up -d nginx  postgres pgadmin
```

and -
```

docker-compose up -d nginx  postgres pgadmin
Creating network "laradock_frontend" with driver "bridge"
Creating network "laradock_backend" with driver "bridge"
Creating network "laradock_default" with the default driver
Creating laradock_docker-in-docker_1 ... done
Creating laradock_postgres_1         ... done
Creating laradock_pgadmin_1          ... done
Creating laradock_workspace_1        ... done
Creating laradock_php-fpm_1          ... done
Creating laradock_nginx_1            ... done

```

BUT when I try to access , this url , it does not access -
```
localhost:5050
or
127.0.0.1:5050/index.php
or
0.0.0.0:5050

```

I am using windowls 10 , and the Docker version -  18.09.2 .

**Comment by murilolivorato** [comment]
please , some one can help me ?

**Comment by menadio** [comment]
If you are using docker toolbox on windows, use the docker configure default machine IP which would be something like 192.168.99.100. In my case http://192.168.99.100 works for the laravel app and http://192.168.99.100:5050 brings up pgadmin.

**Comment by murilolivorato** [comment]
hello @menadio  , I am not using docker toolbox . where do I use this IP ? 
in the .env File here  - PGADMIN_PORT=http://192.168.99.100:5050  ? 

Thanks

**Comment by menadio** [comment]
Oh well, I use docker toolbox so to view pgadmin I simply enter the url http://192.168.99.100:5050

**Comment by parmonov98** [comment]
I'm facing the issue 
![image](https://user-images.githubusercontent.com/24564577/216575212-8c7a1a21-97f1-4d50-83ca-f44769ad6519.png)
