### ISSUE TITLE
Locating the mysql.conf or my.cnf or any MySQL config file

### ISSUE THREAD

**Issue by Enviii** [LaraDock/laradock#218]
I'm trying to disable strict_mode in MySQL, but I cannot find any configuration file to edit for MySQL.

The default location would be: 
/etc/my.cnf or /etc/mysql/my.cnf or ~/.my.cnf

but I cannot find anything there.

**Comment by gkweb** [comment]
Maybe related:
[](https://github.com/docker-library/mysql/issues/149)

**Comment by Enviii** [comment]
Figured it out. Edited the docker-compose.yml mysql config to include `command: mysqld --sql_mode=""` and then started the container as you normally would.
