### ISSUE TITLE
Multiple projects and internal curl request

### ISSUE THREAD

**Issue by fjugaldev** [laradock/laradock#2180]
### Info:
- Docker version (`$ docker --version`): 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 23193babf416102ce61001b829c8afdb53fa5d91 
- System info (Mac, PC, Linux): Mac
- System info disto/version: macOS Mojave 10.14.4

### Issue:
I configured my laradock project in order to use multiples projects, so my directory structure looks like this:
/var/www/html/
    - laradock
    - project1
    - project2

Everything is working fine, my containers are up and running an i can make http requests from outside using postman for example to each domain host like puf.loc and api.puf.loc and everything is ok.

My problem is that when project1 (puf.loc) wants to make an internal request using curl to project2 (api.puf.loc) im getting a connection refused message.

Making some research on google i found a post that indicates that i need to create add to the extra_hosts parameter in the docker-compose.yaml file for the php-fpm service the following entries:

- "api.puf.loc:${DOCKER_HOST_IP}"
- "puf.loc:${DOCKER_HOST_IP}"

And then run the following command:

docker-compose up -d --build nginx mysql redis beanstalkd memcached

But still no working.. i tried changing ${DOCKER_HOST_IP} with the ip of the nginx container and with no success. Have tried too with 127.0.0.1 and without response.

I understand that inside the container, when we make a request to a host like api.puf.loc, we need a entry in the /etc/hosts pointing to 127.0.0.1 but i can get working my two projects together inside the same container (multiple projects)

Can anyone help me with this??

Thank you guys!

_____

### Expected behavior:
I need that my project1 (puf.loc), can make a internal request via curl to my project2 (api.puf.loc) using the laradock for multiple projects.
_____

**Comment by lgfinfo** [comment]
I have the same issue.

**Comment by lgfinfo** [comment]
I  fixed it like this :
php-fpm
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "tegonganzhuang.test:${DOCKER_HOST_IP}"
        - "oauthserver.test:${DOCKER_HOST_IP}"

**Comment by semenikhin** [comment]
extra_hosts does not help for me.
I solved it by adding network aliases for nginx:

```
      networks:
        frontend:
        backend:
          aliases:
            - project1.local
            - project2.local

```

**Comment by Erisbv** [comment]
In any of these cases did you use curl? I can't run Curl ...

**Comment by diogenesderm** [comment]
Eu consertei assim:
php-fpm
extra_hosts:
- "dockerhost:${DOCKER_HOST_IP}"
- "site.development:192.168.1.178"

**Comment by thiagovieiradev** [comment]
> Eu consertei assim: php-fpm extra_hosts:
> 
> * "dockerhost:${DOCKER_HOST_IP}"
> * "site.development:192.168.1.178"

Esse IP 192 é o seu IP local?

**Comment by diogenesderm** [comment]
> > Eu consertei assim: php-fpm extra_hosts:
> > 
> > * "dockerhost:${DOCKER_HOST_IP}"
> > * "site.development:192.168.1.178"
> 
> Esse IP 192 é o seu IP local?

Sim. No meu caso ficou assim.
 "dockerhost:${DOCKER_HOST_IP}"
"site1.development:192.168.1.178"
"site2.development:192.168.1.178
"site3.development:192.168.1.178

**Comment by thiagovieiradev** [comment]
> > > Eu consertei assim: php-fpm extra_hosts:
> > > 
> > > * "dockerhost:${DOCKER_HOST_IP}"
> > > * "site.development:192.168.1.178"
> > 
> > 
> > Esse IP 192 é o seu IP local?
> 
> Sim. No meu caso ficou assim. "dockerhost:${DOCKER_HOST_IP}" "site1.development:192.168.1.178" "site2.development:192.168.1.178 "site3.development:192.168.1.178

Entendi. E como fazia o curl? Com o endereço mesmo ou IP? Tipo "http://site1.development/api/list" ou IP mesmo?

**Comment by grupoderaca** [comment]
> > > > Eu consertei assim: php-fpm extra_hosts:
> > > > 
> > > > * "dockerhost:${DOCKER_HOST_IP}"
> > > > * "site.development:192.168.1.178"
> > > 
> > > 
> > > Esse IP 192 é o seu IP local?
> > 
> > 
> > Sim. No meu caso ficou assim. "dockerhost:${DOCKER_HOST_IP}" "site1.development:192.168.1.178" "site2.development:192.168.1.178 "site3.development:192.168.1.178
> 
> Entendi. E como fazia o curl? Com o endereço mesmo ou IP? Tipo "http://site1.development/api/list" ou IP mesmo?

No CURL eu utilizo assim: http://site1.development:8081/api/list
