### ISSUE TITLE
Error workspace build at INSTALL_PHPREDIS

### ISSUE THREAD

**Issue by chatii** [laradock/laradock#2183]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): a2c7b467662706ba1af118048baeaf6e27f6a74d
- System info (Mac, PC, Linux): Mac
- System info disto/version: Mojave (10.14.5)

### Issue:
I try build `workspace`, `nginx`, `php-fpm` and `mysql` (PHP ver: 7.2)
But I had an error

> Step 93/217 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then     apt-get install -yqq php-redis ;fi
>  ---> Running in d5e2e70b87ce
> E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php-redis_4.2.0-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ 
> ${INSTALL_PHPREDIS} = true ]; then     apt-get install -yqq php-redis ;fi' returned a non-zero code: 100
> Failed to deploy 'Compose: docker-compose.yml': `docker-compose` process finished with exit code 1

**Comment by ephraimlambarte** [comment]
im experiencing this too. As a temporary fix, i  have set INSTALL_PHPREDIS to false in .env file of laradock

**Comment by zelsonia** [comment]
the same problem,  find the answer in other issue:  docker-compose build --no-cache xxxxxx ,it can resolve mine , you could try

**Comment by chatii** [comment]
@zelsonia 
I tried `docker-compose build-no-cache` and it worked! Thank you!
I will close this issue.
