### ISSUE TITLE
Laradock microservice

### ISSUE THREAD

**Issue by psxcoding** [laradock/laradock#2186]
Hello, i cant find any guide about how to make microservices in Laradock. For example main page opens http://example.com uses 80 port  (from var/ww/public) and i want to make microservice with lumen which will open http://example.com:custom_port (from var/ww/public/microservice). Any ideas ?

**Comment by lanphan** [comment]
please try this, setup multiple projects with laradock: https://laradock.io/getting-started/#B

**Comment by lgfinfo** [comment]
modify extra_hosts of nginx or apache
