### ISSUE TITLE
Setting PHP 7.3 in .env install PHP 7.2.15 instead

### ISSUE THREAD

**Issue by jeremy379** [laradock/laradock#2187]
### Info:
- Docker version (`$ docker --version`):  Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): a2c7b467662706ba1af118048baeaf6e27f6a74d
- System info (Mac, PC, Linux):  Mac Mojave 10.14.5
- System info disto/version: 

### Issue:

Setting Php version to 7.3 in .env file result in installing php 7.2.15 for php-fpm (and version 7.3 for workspace as expected)
_____

### Expected behavior:
Setting Php 7.3 for php-fpm 
_____

### Reproduce:
Set PHP_VERSION=7.3 and running docker-compose build --no-cache php-fpm
Then open a project with a simple phpinfo().
_____

While checking in php-fpm/Dockerfile I notice this

FROM letsdockerize/laradock-php-fpm:2.4-${LARADOCK_PHP_VERSION}

the tags 73 exists for lestdockerize (https://hub.docker.com/r/letsdockerize/laradock-php-fpm/tags).

I also checked with lastest instead of 2.4 but it gave me the same result.

Thanks

**Comment by zippos** [comment]
Same issue here.

**Comment by JexPY** [comment]
You need definitely to clean the cache causes I have even updated and changed versions several times (based on the project requirements) and had no problem, having same .env configuration as you described
`sudo docker-compose exec php-fpm php -version`

> PHP 7.3.2 (cli) (built: Feb 21 2019 22:54:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2, Copyright (c) 1999-2018, by Zend Technologies

`sudo docker-compose exec workspace php -version`

> PHP 7.3.7-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2019 11:44:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7-2+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**System**

> MacOs Mojave 10.14.6
> Docker version 19.03.1

**Comment by zippos** [comment]
Agree. Somehow I don't encounter this problem anymore.

**Comment by jeremy379** [comment]
Indeed there were an issue with the cache
docker-composer build --no-cache wasn't enough, I add to remove all my images and rebuild from scratch.
