### ISSUE TITLE
mailu not work pls check this project

### ISSUE THREAD

**Issue by eGirlAsm** [laradock/laradock#2188]
```
mailu_1                | sh: python: not found
mailu_1                | sh: python: not found
mailu_1                | sh: python: not found
mailu_1                | sed: /webmail/_data_/_default_/configs/config.ini: No such file or directory
mailu_1                | grep: /webmail/_data_/_default_/configs/config.ini: No such file or directory
mailu_1                | sh: can't create /webmail/_data_/_default_/configs/config.ini: nonexistent directory
mailu_1                | sh: can't create /webmail/_data_/_default_/configs/config.ini: nonexistent directory
mailu_1                | sh: can't create /webmail/_data_/_default_/configs/config.ini: nonexistent directory
```

i tried 1.4 1.5 version  all of them didn't work
i tried that on my linux server, mac book. etc.. 

suspicious that laradock contributors never checked that out
and of course i love it. its a great project!

**Comment by ZirionNeft** [comment]
Same trouble. Anybody found a resolution?

**Comment by ZirionNeft** [comment]
How to solve a problem:
1. Add an environment variable to the docker-compose.yml mailu-webmail image:
`mailu-webmail:
      image: "mailu/${MAILU_WEBMAIL}:${MAILU_VERSION}"
      environment:
        - MESSAGE_SIZE_LIMIT=${MAILU_MESSAGE_SIZE_LIMIT}`
2. change the mailu image startup script:
`command: ["sh", "-c", "flask mailu advertise ; flask db upgrade ; flask mailu admin ${MAILU_INIT_ADMIN_USERNAME} ${MAILU_DOMAIN} ${MAILU_INIT_ADMIN_PASSWORD} || true;sed -i -- \"s/= Off/= On/g\" /webmail/_data_/_default_/configs/config.ini || true;if grep -Fq \"registration_link_url\" /webmail/_data_/_default_/configs/config.ini;then echo Already set!;else echo \"\" >> /webmail/_data_/_default_/configs/config.ini; echo \"[login]\" >> /webmail/_data_/_default_/configs/config.ini;echo \"registration_link_url = '${MAILU_WEBSITE}${MAILU_WEB_ADMIN}/ui/user/signup'\" >> /webmail/_data_/_default_/configs/config.ini;fi"]`

**Comment by ZirionNeft** [comment]
Duplicate of #2137
