### ISSUE TITLE
psql from workspace (backup)

### ISSUE THREAD

**Issue by rodrigore** [LaraDock/laradock#219]
In my Laravel project I use the package `backup-manager` that run an artisan command 'db:restore" which run `psql` command.

I'm starting with laradock and If I enter to the workspace and run the command 'db:restore' obviosly in this container doesn't exist the `psql`command.

Anyone can help me with this ?

**Comment by Mahmoudz** [comment]
Someone need to install this `psql` in the workspace container, if you could do it yourself and create a PR I'll merge quickly. You will need to put it in this [file](https://github.com/LaraDock/workspace/blob/master/Dockerfile), "note that's an another repository". You might also need to check this [file](https://github.com/LaraDock/laradock/blob/master/workspace/Dockerfile).

**Comment by rodrigore** [comment]
Thanks, in my local machine I installed postgres-client into the workspace container and now it works.

I create a [pull  request](https://github.com/LaraDock/workspace/pull/5)  but  I don't tested.

**Comment by Mahmoudz** [comment]
Thank you this got merged and you can try it with LaraDock version 4.0.4
