### ISSUE TITLE
The fastest way to reload nginx config

### ISSUE THREAD

**Issue by namnguyen2091** [laradock/laradock#2191]
I create new config virtual host file, as usual I run 

> docker-compose up -d --force-recreate --build nginx

It will rebuild nginx with many times. How do I do this task with shortest time?

**Comment by lanphan** [comment]
```docker-compose restart nginx```

In case you need to reload configuration only, you can try command below to reload
```docker-compose exec nginx nginx -s reload```

**Comment by namnguyen2091** [comment]
@lanphan or recreate container do the same. Thanks.
