### ISSUE TITLE
Can I have many computers with one Docker account

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2198]
Hello guys , I have a question .
I have a computer in my work , and I have a computer in my home .
when I make a new enviroment , at my work ( install docker ) . do I have to use a new user account ?
Or can I have one docker Account to many enviroment  ( computer work , computer home , computer 3 .... )
Thanks

**Comment by lanphan** [comment]
you need 1 account only.
In fact, Docker account allows you to push image to Docker Hub. In case you pull image only (like me), you don't need it.
