### ISSUE TITLE
Usage of Postgis pgsql2shp or shp2pgsql commands from app 

### ISSUE THREAD

**Issue by felipenegrelli** [laradock/laradock#2205]
### Info:
- Docker version (18.09.2): 
- Laradock commit (63fc1fde44cc00aacb89511a441cb83685e8010c): 
- System info (PC): 
- System info Windows 10: 

### Issue:
I'm trying to use the POSTGIS Postgres Extension merged by @sneycampos  (https://github.com/laradock/laradock/pull/2110), but  I get the error "shp2pgsql: not found" from the server. 

What container does POSTGIS needs to installed so I can run the command from a laravel app (Workspace, Nginx or PHP_FPM)? I'm confused about that. Thanks!

### Expected behavior:
To run shp2pgsql command from laravel application and it imports Shapefile to POSTGIS database creating a new table.
_____

### Reproduce:
Clone the repo, change the variables PHP_FPM_INSTALL_PGSQL, PHP_FPM_INSTALL_PG_CLIENT,  PHP_FPM_INSTALL_POSTGIS to true, build the conteiners, start the conteiners (including postgres-postgis) and run the SHP2PGSQL from application running on nginx.
_____

### Relevant Code:
$command = "shp2pgsql -g geom -s 31984 /var/www/laravel/storage/app/temp/1.zip 1 | PGPASSWORD=postgres psql -h postgres-postgis -p "
$process = new Process($command);
$process->run();
$process->getErrorOutput()

"""
sh: 1: shp2pgsql: not found
sh: 1: psql: not found
"""

**Comment by sneycampos** [comment]
Sorry, the right command is pgsql2shp.

**Comment by sneycampos** [comment]
Have you tried to run PGSQL2SHP command?

POSTGIS must be installed in PHP-FPM Container if you're trying to use it in PHP.
