### ISSUE TITLE
你好我想问问 我每次修改了xdebug和php.ini 都需要重新build才能生效是什么原因

### ISSUE THREAD

**Issue by 449134904** [laradock/laradock#2206]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by helloMJW** [comment]
php-fpm 的配置文件(php.ini)是写在`docker-compose.yml`中的、所以不需要重新build
但是workspace是写在dockerfile中的所以每次修改都需要重新build 
如果期望修改配置文件生效, 那么可以在 https://github.com/laradock/laradock/blob/26184055c5126dc51f2aadadd7a3b4a9506a1d04/docker-compose.yml#L125 这一行下面增加一行 `- ./worksapce/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini`

**Comment by 449134904** [comment]
是在这里吗






------------------ 原始邮件 ------------------
发件人: "一年三班马同学"<notifications@github.com>; 
发送时间: 2019年7月18日(星期四) 上午10:15
收件人: "laradock/laradock"<laradock@noreply.github.com>; 
抄送: "宁静的夏天"<449134904@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [laradock/laradock] 你好我想问问 我每次修改了xdebug和php.ini 都需要重新build才能生效是什么原因 (#2206)




php-fpm 的配置文件(php.ini)是写在docker-compose.yml中的、所以不需要重新build
 但是workspace是写在dockerfile中的所以每次修改都需要重新build
 如果期望修改配置文件生效, 那么可以在 https://github.com/laradock/laradock/blob/26184055c5126dc51f2aadadd7a3b4a9506a1d04/docker-compose.yml#L125 这一行下面增加一行 - ./worksapce/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini

**Comment by 449134904** [comment]
加上你的代码
ERROR: for workspace  Cannot start service workspace: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/e/www/laradock-master/worksapce/xdeb
ug.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/b24b2d49d4d872349715c5cdb0cadcf4cc4313bf5bdaf72da6606e92463bafa4/merged\\\" at \\\"/var/lib/docker/overlay2/b24b2d49d4d872349715c5cdb0cadcf4cc4313bf5bdaf72da6606e92463bafa4/merged/etc/php/7.2/cli/conf.d/xdebug.ini\\
\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type




------------------ 原始邮件 ------------------
发件人: "一年三班马同学"<notifications@github.com>; 
发送时间: 2019年7月18日(星期四) 上午10:15
收件人: "laradock/laradock"<laradock@noreply.github.com>; 
抄送: "宁静的夏天"<449134904@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [laradock/laradock] 你好我想问问 我每次修改了xdebug和php.ini 都需要重新build才能生效是什么原因 (#2206)




php-fpm 的配置文件(php.ini)是写在docker-compose.yml中的、所以不需要重新build
 但是workspace是写在dockerfile中的所以每次修改都需要重新build
 如果期望修改配置文件生效, 那么可以在 https://github.com/laradock/laradock/blob/26184055c5126dc51f2aadadd7a3b4a9506a1d04/docker-compose.yml#L125 这一行下面增加一行 - ./worksapce/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini

**Comment by mouyong** [comment]
@449134904 因为这一行

https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile#L161

解决办法可以参考 @helloMJW 的回答，在  php-fpm 的 volumes 中添加一行 xdebug.ini 的配置映射

> php-fpm 的配置文件(php.ini)是写在`docker-compose.yml`中的、所以不需要重新build
> 但是workspace是写在dockerfile中的所以每次修改都需要重新build
> 如果期望修改配置文件生效, 那么可以在
> 
> https://github.com/laradock/laradock/blob/26184055c5126dc51f2aadadd7a3b4a9506a1d04/docker-compose.yml#L125
> 
> 这一行下面增加一行 `- ./worksapce/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini`
