### ISSUE TITLE
elasticsearch container problem

### ISSUE THREAD

**Issue by sas05** [laradock/laradock#2216]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 1602ff2dd054afd085881cffd5426246f880bfea
- System info (Mac, PC, Linux): mac
- System info disto/version: Mojave

### Issue:
`E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php-redis_4.2.0-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`
_____

### Reproduce:
while docker-compose up -d elasticsearch
_____

**Comment by stefnats** [comment]
Seems like a duplicate of #2203 (this is docker cache issue, try `docker-compose build workspace --no-cache`)

**Comment by sas05** [comment]
`docker-compose build --no-cache workspace`

**Comment by sas05** [comment]
thanks
