### ISSUE TITLE
关于xhprof问题

### ISSUE THREAD

**Issue by laijianbo** [laradock/laradock#2217]
遇到问题如下：
PHP Warning: PHP Startup: Unable to load dynamic library 'tideways.so'
找到问题是因为xhprof.ini配置了extension = tideways.so，但是xhprof扩展并没有安装，所以会一直报这个错误。
但是设置了.env中的PHP_FPM_INSTALL_XHPROF=true，
然后运行：docker-compose up -d --build php-fpm会发现并没有安装xhprof扩展，原因就是docker-compose.yml中的php-fpm并没有配置该项，这个问题很低级，不知道为啥会犯。
所以修改配置加缺少的配置加上，如下：
![image](https://user-images.githubusercontent.com/10562738/61938912-bd8b8900-afc4-11e9-8c29-9c8d0fa016b5.png)
然后再运行：docker-compose up -d --build php-fpm
所以希望开发者能够修复这个bug

**Comment by forecho** [comment]
不好意思，这个坑是我挖的。

但是我后来又给他们提了 [PR](https://github.com/laradock/laradock/pull/2141/files)

但是没人合并 😭

**Comment by forecho** [comment]
#2141
