### ISSUE TITLE
I can't get Laravel to change APP_ENV to 'testing'

### ISSUE THREAD

**Issue by ultrablue** [laradock/laradock#2218]
### Info:
- Docker version (`$ docker --version`): 
Docker version 18.09.2, build 6247962

- Laradock commit (`$ git rev-parse HEAD`): 
83a24efa709d15037b0d06ca7f4df235e240d642

- System info (Mac, PC, Linux): 
Windows

- System info disto/version: 
Windows 10
### Issue:
Something is overriding Laravel's APP_ENV setting, which is causing unit tests run against the application database instead of a sqlite in-memory database. I've added the following line to the top of routes/web.php:
`dd(App::environment());`

When I run my tests, that outputs:
`local`

Here are some relevant configurations:

- .env: APP_ENV=local
- phpunit.xml: `<env name="APP_ENV" value="testing"/>`
- .env.testing: APP_ENV=testing

I've tried a number of things, including:

- Clearing caches by running `php artisan cache:clear; php artisan config:cache`
- Creating .env.testing with the proper settings.
- Changed .env to: APP_ENV=testing
- Clearing the caches many times and before running tests.

I'm forced to conclude that something outside of Laravel is setting APP_ENV. However, I've grepped the laradock directory for 'app_env' and found nothing. So, I'm pretty stumped.

Please let me know if I can provide any other information.

Thanks!
_____

### Expected behavior:

At this point, I would like to see the bit that dumps the current APP_ENV output 'testing' when I run a test.
_____

### Reproduce:
I don't know?
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by byrontuckett** [comment]
@ultrablue  I'm Experiencing this with the multi project setup.  Do you ever find a resolution?

**Comment by byrontuckett** [comment]
@ultrablue typical.. just after I posted the message.

Busted the cache manually (deleted files under boostrap\cache) and it works as expected with the correct environment.  

```sh
cd /var/www/app1
 vendor/bin/phpunit --colors=always test/Feature/ExampleTest.php
```

**Comment by ultrablue** [comment]
@byrontuckett Ha, excellent.

I think that I ended up waiting a looooooong time (months), updating Laradock and Laravel, and violá, all cleared up! You're solution is probably better (and could very well be what happened behind the scenes with mine).

Thanks for following up!
