### ISSUE TITLE
./php-fpm/xdebug status no work

### ISSUE THREAD

**Issue by edwinhuish** [laradock/laradock#2220]
### Info:
- Docker version (`$ docker --version`): 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): #8254c34
- System info (Mac, PC, Linux): WIN10 
- System info disto/version: 18945

### Issue:

```./php-fpm/xdebug status``` no work as [XDEBUG GUIDE](https://laradock.io/guides/#enablePhpXdebug)

![image](https://user-images.githubusercontent.com/5207925/62190314-a45b5180-b3a3-11e9-9a34-70e0fce92490.png)

_____

### Expected behavior:

Show the XDEBUG STATUS as XDEBUG GUIDE
_____

### Reproduce:

Type ```./php-fpm/xdebug status``` in powershell 
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by alexelev** [comment]
try `php-fpm/xdebug status` without './' in the begin of the command

**Comment by jpenaroche** [comment]
Hi, i have the same problem, When i execute ./php-fpm/xdebug status from powershell doesn't work like the guide say. I have tried both ways with . and without . Even if i execute inside the php-fpm container doesn't work either because doesn't recognize docker executable. What should i do?

```Program 'xdebug' failed to run: No application is associated with the specified file for this operationAt line:1 char:1 + ./php-fpm/xdebug status                                                                                               + ~~~~~~~~~~~~~~~~~~~~~~~.                                                                                              At line:1 char:1                                                                                                        + ./php-fpm/xdebug status                                                                                               + ~~~~~~~~~~~~~~~~~~~~~~~                                                                                                   + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException                                       + FullyQualifiedErrorId : NativeCommandFailed ```
