### ISSUE TITLE
Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by HelplessMan** [laradock/laradock#2225]
### Info:
- Docker version (`$ docker --version`):  v4
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  mac
- System info disto/version: 

```
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/g/gobject-introspection/gir1.2-glib-2.0_1.50.0-1+b1_amd64.deb  500  Internal Server Error
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -y libmagickwand-dev imagemagick &&     pecl install imagick &&     docker-php-ext-enable imagick ;fi' returned a non-zero code: 100
```

**Comment by HelplessMan** [comment]
What's the reason?
V4 version has a lot of problems

**Comment by HelplessMan** [comment]
Who's coming to help me?

Installation failed many times!!

The mood is terrible!

**Comment by lanphan** [comment]
Hi,
Have you tried ```docker-compose build --no-cache php-fpm```?

**Comment by HelplessMan** [comment]
> Hi,
> Have you tried `docker-compose build --no-cache php-fpm`?

Yes, rebuilding php-fpm has this error, has tried many times

**Comment by lanphan** [comment]
Hi,

Please give me your .env file (php-fpm only)

**Comment by HelplessMan** [comment]
> Hi,
> 
> Please give me your .env file (php-fpm only)

Thank you very much for your help. I used the most stupid way. I reinstalled docker and laradocke all at once, and now I can use it.

**Comment by nfurkanyildiz** [comment]
> Hi,
> 
> Please give me your .env file (php-fpm only)

Hi sir, ı have the same problem.
[env.txt](https://github.com/laradock/laradock/files/10236577/env.txt)
[php-fpm in docker file.txt](https://github.com/laradock/laradock/files/10236578/php-fpm.in.docker.file.txt)
