### ISSUE TITLE
nginx_1                | nginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/upstream.conf:1 laradock_nginx_1 exited with code 1

### ISSUE THREAD

**Issue by mouyong** [laradock/laradock#2227]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.0-ce, build 0520e24302
- Laradock commit (`$ git rev-parse HEAD`): da8f0d086433d6cc269ee86c92bcc93a1f88b73c
- System info (Mac, PC, Linux): win10 PC
- System info disto/version: win10

### Issue:

_____
![image](https://user-images.githubusercontent.com/10336437/62437541-3aadbf80-b776-11e9-9562-21004a56c590.png)

### Expected behavior:

nginx container can bu run

### Reproduce:

docker-compose up -d nginx

### Relevant Code:

```
// place a code sample here
```

**Comment by kryptonn** [comment]
I've the same problem, how did you solve your issue ?

**Comment by kryptonn** [comment]
... well i did by simply restart all containers, maybe this is an order issue
