### ISSUE TITLE
Is Using LaraDock Advisable for Production?

### ISSUE THREAD

**Issue by midascodebreaker** [LaraDock/laradock#223]
Hi i try to Create a Digital Ocean Server with Docker
and Also Manage to Use Docker Compose
and Add Laravel Project...

But I Dont Know if it is advisable to do it this way?

What is the COrrect way, if i will want to use it on production
please i need sugguestions and opinions thanks

**Comment by Mahmoudz** [comment]
LaraDock is just Docker ready for Laravel with docker-compose file (all Docker technologies nothing invented by LaraDock). So the question should be "Is Using Docker Advisable for Production" and the answer of course YES, but that's not so simple yet! Best of luck
