### ISSUE TITLE
hhvm and php version issue

### ISSUE THREAD

**Issue by bharatgupta99** [laradock/laradock#2230]
### Info:
- Docker version: 19.03.1, build 74b1e89 
- Laradock commit: 8254c3464743d86f42e9d7c83764bf3c385b6ad8 
- System info: Mac
- System info disto/version: 

### Issue:
when I run composer install I get this error:-   
**This package requires php >=7.3.0 but your HHVM version does not satisfy that requirement.**
____

### Reproduce:
1. launch workspace 
2. go to the project
3. run composer install

I am using PHP 7.2.21 

**tried updating to php 7.3 but that was also no happening**
1. changed .env file php_version variable to 7.3
2. build php-fpm and build workspace
3. stopped containers and start again
3. nothing happened php version is still 7.2.21

**Comment by tomscholz** [comment]
How did you solve the issue?
