### ISSUE TITLE
Where is "executablePath"?

### ISSUE THREAD

**Issue by dukinfotech** [laradock/laradock#2233]
I need set  "executablePath" for using VSCode's extensions but i don't know where is it?

**Comment by lanphan** [comment]
Hi,

Please try this: https://qiita.com/kefian1go/items/bbc8f9d51fe890194ad7

**Comment by dukinfotech** [comment]
> 
> 
> Hi,
> 
> Please try this: https://qiita.com/kefian1go/items/bbc8f9d51fe890194ad7

Sorry but i think this is tutorial for windows users. I'm using Linux enviroment.
Thank you.
