### ISSUE TITLE
在国内，下载内部镜像超级慢！！！

### ISSUE THREAD

**Issue by huiyonghkw** [laradock/laradock#2238]
谁能告诉我，如何加速国内下载所有的内部镜像，简直是要死人

**Comment by NetBT** [comment]
使用国内镜像源，比如 http://hub-mirror.c.163.com

**Comment by bravist** [comment]
修改成了阿里镜像源， 一样的

**Comment by sjje** [comment]
科学上网

**Comment by wxb** [comment]
fork一份仓库到自己名下，速度就好多了

**Comment by bravist** [comment]
@wxb 这个怎么能解决问题？

**Comment by wxb** [comment]
@bravist 不太明白你的意思
1. 如果只是下载先来用 laradock的话，fork一份laradock，使用的时候clone自己fork出来的 速度回快很多(我用这种办法会快很多，具体其他的我没验证过)，使用上没有任何差异
2. 如果是想给laradock源码debug的话，可以直接修改fork出来的仓库，然后新建一个PR就可以

**Comment by bravist** [comment]
@wxb 

> fork，仅仅是将laradock源码克隆到自己的仓库。

我的意思是在克隆出来laradock源码够，使用docker-compose up -d nginx 时，镜像构建的过程非常非常慢。特别是在构建PHP镜像源码时，常常会断掉

**Comment by wxb** [comment]
@bravist 
😯明白了，之前的理解有点偏差😆
确实有点慢

**Comment by xiagw** [comment]
> 谁能告诉我，如何加速国内下载所有的内部镜像，简直是要死人
# .env 71行
# If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
# CHANGE_SOURCE=true

**Comment by bravist** [comment]
> > 谁能告诉我，如何加速国内下载所有的内部镜像，简直是要死人
> 
> # .env 71行
> # If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
> # CHANGE_SOURCE=true

看参数配置，貌似仅仅是将nginx镜像在国内加速了。PHP镜像还是无法加速

**Comment by yunlongw** [comment]
官方还是很贴心的 ，虽然只有 nginx 改变了国内源

```
ARG CHANGE_SOURCE=false
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from dl-cdn.alpinelinux.org to aliyun source
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
;fi
```

**Comment by xiagw** [comment]
> > > 谁能告诉我，如何加速国内下载所有的内部镜像，简直是要死人
> > 
> > 
> > # .env 71行
> > # If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
> > # CHANGE_SOURCE=true
> 
> 看参数配置，貌似仅仅是将nginx镜像在国内加速了。PHP镜像还是无法加速

你可以参考这个把php-fpm的dockerfile 修改切换apk source

**Comment by xiagw** [comment]
> 谁能告诉我，如何加速国内下载所有的内部镜像，简直是要死人

在 php-fpm/Dockerfile 第25行加上：   
```
ARG CHANGE_SOURCE=false
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from deb.debian.org to aliyun source
    sed -i 's/deb.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list \
;fi
```

**Comment by bravist** [comment]
![image](https://user-images.githubusercontent.com/1323776/64853511-1afb9800-d64e-11e9-89b9-5b58b8a4ebd6.png)

经常卡在这个环节!!!

**Comment by bravist** [comment]
![image](https://user-images.githubusercontent.com/1323776/64860548-1809a300-d660-11e9-85ec-8d0aac86ed42.png)
这里也非常的慢！！！

**Comment by baiyutang** [comment]
> 官方还是很贴心的 ，虽然只有 nginx 改变了国内源
> 
> ```
> ARG CHANGE_SOURCE=false
> RUN if [ ${CHANGE_SOURCE} = true ]; then \
>     # Change application source from dl-cdn.alpinelinux.org to aliyun source
>     sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
> ;fi
> ```

因为这段是中国人写的。
![image](https://user-images.githubusercontent.com/10782183/65751600-a17ba380-e13d-11e9-8fb7-7d9a5d67db8f.png)

**Comment by edwinhuish** [comment]
> > 谁能告诉我，如何加速国内下载所有的内部镜像，简直是要死人
> 
> 在 php-fpm/Dockerfile 第25行加上：
> 
> ```
> ARG CHANGE_SOURCE=false
> RUN if [ ${CHANGE_SOURCE} = true ]; then \
>     # Change application source from deb.debian.org to aliyun source
>     sed -i 's/deb.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list \
> ;fi
> ```

现在最新版的php-fpm已经有这段代码，不过在 ```docker-compose.yml``` 没有加入对应的args，我提交了一个PR #2311 , 不知道是否能merge，你们自己添加上吧。

**Comment by amorZhu** [comment]
请查看我的fork
workspace 下面有个 sources.sh 文件，不能通过 if [ ${CHANGE_SOURCE} = true ]; then \ xxxx;fi 执行，
但是可以这样执行：
`ARG PUID=1000
ENV PUID ${PUID}
ARG PGID=1000
ENV PGID ${PGID}

COPY ./sources.sh /tmp/sources.sh

RUN chmod +x /tmp/sources.sh && ./tmp/sources.sh aliyun`

**Comment by amorZhu** [comment]
还有下载安装 nvm 时非常慢，我正在请求合并我的修改，但是 修改 workspace 的 ubuntu 容器有问题，所以关闭了合并请求，按照 #2377 修改一下，老快了，哈哈哈。等解决ubuntu 源的问题，我会继续提交合并请求。
给你个地址：
WORKSPACE_NPM_REGISTRY=https://registry.npm.taobao.org/

**Comment by amorZhu** [comment]
别忘了修改 docker 本身的镜像源。百度搜索一下，很多的。

**Comment by wattszen** [comment]
> ![image](https://user-images.githubusercontent.com/1323776/64853511-1afb9800-d64e-11e9-89b9-5b58b8a4ebd6.png)
> 
> 经常卡在这个环节!!!

全局翻墙试试

**Comment by cshaptx4869** [comment]
楼主 我也卡在

> ![image](https://user-images.githubusercontent.com/1323776/64853511-1afb9800-d64e-11e9-89b9-5b58b8a4ebd6.png)
> 
> 经常卡在这个环节!!!
楼主 我也卡在这个问题好久了 死活下不去 请问你现在解决了没

**Comment by cshaptx4869** [comment]
> 请查看我的fork
> workspace 下面有个 sources.sh 文件，不能通过 if [ ${CHANGE_SOURCE} = true ]; then \ xxxx;fi 执行，
> 但是可以这样执行：
> `ARG PUID=1000
> ENV PUID ${PUID}
> ARG PGID=1000
> ENV PGID ${PGID}
> 
> COPY ./sources.sh /tmp/sources.sh
> 
> RUN chmod +x /tmp/sources.sh && ./tmp/sources.sh aliyun`
> 那里慢就放到哪个 Dockerfile 里面，贼快！

![image](https://user-images.githubusercontent.com/31907940/75306854-33224500-5885-11ea-9cc2-330e52160801.png)
dockfile 已经有这一段了 单还是卡在那个界面

**Comment by cshaptx4869** [comment]
已解决 https://www.cnblogs.com/cshaptx4869/p/12374234.html

**Comment by mouyong** [comment]
https://github.com/laradock/laradock/pull/1905
没办法对所有容器一次性进行换源处理。有需要的可以自己参考 nginx、php-fpm、workspace 等相关容器，进行换源，然后 PR 上来，一起方便大家丫？

**Comment by bravist** [comment]
## 今日又重新安装配置了下Laradock

> macOS: 10.15.4
> iterm2
> docker: 2.3.0.2
> laradock 已经很好的支持china镜像了， 不过在国内环境依然还是出现很多细小问题，地理位置：成都，如果你已经VPN了，最好关掉，修改.env

```bash
# If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
CHANGE_SOURCE=true
```


使用以下命令清理本地容器和镜像
```bash
列出所有的容器 ID
docker ps -aq

停止所有的容器
docker stop $(docker ps -aq)

删除所有的容器
docker rm $(docker ps -aq)

删除所有的镜像
docker rmi $(docker images -q)
```


###  克隆仓库

```bash
git clone https://github.com/laradock/laradock

git checkout v10.0
```
如果是master分支，我一直没有安装成功所有镜像，我切换到了稳定的tag后，一次安装成功了


### 禁止掉composer和node

```bash
WORKSPACE_COMPOSER_GLOBAL_INSTALL=false
WORKSPACE_COMPOSER_AUTH=false
WORKSPACE_COMPOSER_REPO_PACKAGIST=https://mirrors.aliyun.com/composer/
WORKSPACE_NVM_NODEJS_ORG_MIRROR=http://npm.taobao.org/mirrors/node
WORKSPACE_INSTALL_NODE=false
WORKSPACE_NODE_VERSION=node
WORKSPACE_NPM_REGISTRY=
```

如果上面的node和composer一打开，安装就不成功， 最后无奈，就关闭了他们两个，网上搜了很多资料，很少又没有实质性帮助，因此，贴这个说明在这里，希望能帮到相关的人

**Comment by jamesyu89** [comment]
> 已解决 https://www.cnblogs.com/cshaptx4869/p/12374234.html

macOS 10.15.5 试了一下，不行，依然报连接 https://raw.githubusercontent.com 不成功

**Comment by jamesyu89** [comment]
> > ![image](https://user-images.githubusercontent.com/1323776/64853511-1afb9800-d64e-11e9-89b9-5b58b8a4ebd6.png)
> > 经常卡在这个环节!!!
> 
> 全局翻墙试试

全局翻墙试过了，也不行，macOS 10.15.5试过了

**Comment by edwinhuish** [comment]
> > > ![image](https://user-images.githubusercontent.com/1323776/64853511-1afb9800-d64e-11e9-89b9-5b58b8a4ebd6.png)
> > > 经常卡在这个环节!!!
> > 
> > 
> > 全局翻墙试试
> 
> 全局翻墙试过了，也不行，macOS 10.15.5试过了

@jamesyu89 估计你是DNS污染，你试试用腾讯的DNS 119.29.29.29 或者阿里的DNS 223.5.5.5，最好是用远程DNS,  默认电信的DNS有污染。

**Comment by jamesyu89** [comment]
> > > > ![image](https://user-images.githubusercontent.com/1323776/64853511-1afb9800-d64e-11e9-89b9-5b58b8a4ebd6.png)
> > > > 经常卡在这个环节!!!
> > > 
> > > 
> > > 全局翻墙试试
> > 
> > 
> > 全局翻墙试过了，也不行，macOS 10.15.5试过了
> 
> @jamesyu89 估计你是DNS污染，你试试用腾讯的DNS 119.29.29.29 或者阿里的DNS 223.5.5.5，最好是用远程DNS, 默认电信的DNS有污染。

DNS改了之后，要继续翻墙试吗？

**Comment by jamesyu89** [comment]
> ## 再次安装配置 Laradock 要点提醒
> > macOS: 10.15.4
> > iterm2
> > docker: 2.3.0.2
> > laradock 已经很好的支持china镜像了， 不过在国内环境依然还是出现很多细小问题，地理位置：成都，如果你已经VPN了，最好关掉，修改.env
> 
> ```shell
> # If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
> CHANGE_SOURCE=true
> ```
> 
> 一定要设置docker镜像，最新版本的docker 镜像需要打开Docker Desktop => Docker Engine，修改其中的json文件，比如
> 
> ```shell
> {
>   "debug": true,
>   "experimental": false,
>   "registry-mirrors": [
>     "https://yj509r8j.mirror.aliyuncs.com"
>   ]
> }
> ```
> 
> 使用以下命令清理本地容器和镜像
> 
> ```shell
> 列出所有的容器 ID
> docker ps -aq
> 
> 停止所有的容器
> docker stop $(docker ps -aq)
> 
> 删除所有的容器
> docker rm $(docker ps -aq)
> 
> 删除所有的镜像
> docker rmi $(docker images -q)
> ```
> 
> ### 克隆仓库
> ```shell
> git clone https://github.com/laradock/laradock
> 
> git checkout v10.0
> 
> docker-compose up -d mysql redis nginx workspace
> ```
> 
> 如果是master分支，我一直没有安装成功所有镜像，我切换到了稳定的tag后，一次安装成功了
> 
> ### 禁止掉composer和node
> ```shell
> WORKSPACE_COMPOSER_GLOBAL_INSTALL=false
> WORKSPACE_COMPOSER_AUTH=false
> WORKSPACE_COMPOSER_REPO_PACKAGIST=https://mirrors.aliyun.com/composer/
> WORKSPACE_NVM_NODEJS_ORG_MIRROR=http://npm.taobao.org/mirrors/node
> WORKSPACE_INSTALL_NODE=false
> WORKSPACE_NODE_VERSION=node
> WORKSPACE_NPM_REGISTRY=
> ```
> 
> 当�打开composer时，`workspace/Dockerfile`文件中的154行
> 
> ```shell
> RUN if [ ${COMPOSER_GLOBAL_INSTALL} = true ]; then \
>     # run the install
>     composer global install \
> ;fi
> ```
> 
> 在构建镜像的过程中会出现
> 
> ```shell
>  https://packagist.org/packages.json" file could not be downloaded: failed to open stream
> ```
> 
> 类似的错误。
> 
> 当打开node时，`workspace/Dockerfile` 文件的657行左右
> 
> ```shell
> RUN if [ ${INSTALL_NODE} = true ]; then \
>     # Install nvm (A Node Version Manager)
>     mkdir -p $NVM_DIR && \
>     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
>         && . $NVM_DIR/nvm.sh \
> ```
> 
> 会出现连接 https://raw.githubusercontent.com 不成功的错误，尝试了#2459 的方法， 依然未解决问题。
> 
> 以上两个问题困扰很久，通过V2ray翻墙不好使，重装、清理容器和镜像也不好使，最后无奈，就关闭了他们两个，网上搜了很多资料，很少又没有实质性帮助，因此，贴这个说明在这里，希望能帮到相关的人

我试了你下面最后这个方法，居然还是不行，还是出现“连接 https://raw.githubusercontent.com 不成功”

**Comment by jamesyu89** [comment]
> 还有下载安装 nvm 时非常慢，我正在请求合并我的修改，但是 修改 workspace 的 ubuntu 容器有问题，所以关闭了合并请求，按照 #2377 修改一下，老快了，哈哈哈。等解决ubuntu 源的问题，我会继续提交合并请求。
> 给你个地址：
> WORKSPACE_NPM_REGISTRY=https://registry.npm.taobao.org/

试了下这个配置，果然要快多了，压根没留意这里要配淘宝镜像源，我真的是好难！

**Comment by huiyonghkw** [comment]
@jamesyu89 建议不在 macOS 使用Laradock了。 除了安装慢的问题，macOS与容器文件同步是非常的问题。 我已经在本地brew install php和nginx了，如果你成功安装了Laradock，你会对访问容器应用慢的问题折腾

**Comment by CreationLee** [comment]
> 请查看我的fork
> workspace 下面有个 sources.sh 文件，不能通过 if [ ${CHANGE_SOURCE} = true ]; then \ xxxx;fi 执行，
> 但是可以这样执行：
> `ARG PUID=1000
> ENV PUID ${PUID}
> ARG PGID=1000
> ENV PGID ${PGID}
> 
> COPY ./sources.sh /tmp/sources.sh
> 
> RUN chmod +x /tmp/sources.sh && ./tmp/sources.sh aliyun`
> 那里慢就放到哪个 Dockerfile 里面，贼快！
ERROR: Service 'workspace' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder188544908/sources.sh: no such file or directory

**Comment by Jedliu** [comment]
折腾了两天终于build成功了。全局翻不行的，因为build的时候压根不走全局的，尝试了使用vpn也不可以。最后解决的办法是在Dockerfile中的apt-get update -yqq前面加上代理
`# always run apt update when start and after add new source list, then clean up at end.
RUN set -xe; \
    export http_proxy="http://192.168.2.25:1080" &&\
    export https_proxy="http://192.168.2.25:1080" &&\
    apt-get update -yqq && \`
1080是酸酸乳的HTTP 代理设置中的端口，监听地址可以使用0.0.0.0

如果是报Failed to connect to raw.githubusercontent.com port 443: Connection refused，可以使用添加ip指向域名的方式解决。

**Comment by likunyan** [comment]
我用 proxychains-ng 不行，用了那位老哥的 change_source 可以

**Comment by likunyan** [comment]
不过遇到了新的错误，ERROR: libressl3.3-libtls-3.3.3-r0: trying to overwrite usr/lib/libtls.so.20 owned by libretls-3.3.3-r0.，看网上说是要降级
