### ISSUE TITLE
Setup for Basic Task List example

### ISSUE THREAD

**Issue by nojaf** [LaraDock/laradock#224]
Hi, I'm new to both Docker and Laravel and I would like to create the basic tutorial example found on https://laravel.com/docs/5.2/quickstart.

What containers do I need to run to follow along?

**Comment by Mahmoudz** [comment]
Hi @nojaf you are on the right path! by choosing Laravel and Docker. I recommend you watch that Video first [https://www.youtube.com/watch?v=-DamFMczwDA](https://www.youtube.com/watch?v=-DamFMczwDA). And as short answer `docker-compose up -d nginx mysql` is all you need.

**Comment by nojaf** [comment]
Thanks @Mahmoudz. Won't I need ```workspace``` as well to run the artisan commands?
Or will that come along when I ask for ```nginx``` and ```mysql```?

**Comment by Mahmoudz** [comment]
yes you will need to remove the existing container and run new one, `docker-compose down` then `docker-compose up....`.
