### ISSUE TITLE
Why service laravel-horizon is need?

### ISSUE THREAD

**Issue by ahkui** [laradock/laradock#2243]
laravel-horizon is duplicated with php-worker

### php-worker
![image](https://user-images.githubusercontent.com/14049597/63362540-95fdc580-c3a4-11e9-824a-49d4e9c08a35.png)

### laravel-horizon
![image](https://user-images.githubusercontent.com/14049597/63362606-b299fd80-c3a4-11e9-8043-57b54b0ebe74.png)

#1854

**Comment by cwilby** [comment]
As I understand it, the `laravel-horizon` container runs just the Horizon process, then `php-worker` creates a queue worker/runs task scheduler.

My question is, what does `php-worker` do with its link to `docker-in-docker`?  Is it capable of spawning new php-workers under load, or some other purpose?

**Comment by ahkui** [comment]
Hi @cwilby 

> As I understand it, the `laravel-horizon` container runs just the Horizon process, then `php-worker` creates a queue worker/runs task scheduler.

Okay, I knew it.

> My question is, what does `php-worker` do with its link to `docker-in-docker`? Is it capable of spawning new php-workers under load, or some other purpose?

Should you mean `php-fpm`? Because `php-worker` doesn't link with `docker-in-docker`.



Thanks.

**Comment by cwilby** [comment]
Yep, fpm, not worker.  My bad.

**Comment by ahkui** [comment]
> Yep, fpm, not worker. My bad.

I also don't know, we can ask contributor @vlauciani

**Comment by vlauciani** [comment]
Hi all

There was a simil question with my response here:
- https://github.com/laradock/laradock/pull/1655#issuecomment-514109989

Let me know if it is clear or not.

**Comment by cwilby** [comment]
Very clear thank you.   

I've added some security concerns to that PR.

**Comment by ahkui** [comment]
Okay,

If no more question i will close this issue soon.
