### ISSUE TITLE
Laradock on Raspberry.

### ISSUE THREAD

**Issue by crodrigor** [laradock/laradock#2245]
How to use Laradock on raspbian? Is there any solution? Thank you

**Comment by cwilby** [comment]
There shouldn't be much of a difference for Raspberry Pi, best way to find out is to try it out.

Install Docker and Compose for raspberry pi then move your code to the Pi via SSH/Git and `docker-compose up`.

That being said, I'm not sure which of the images in Laradock support ARM.

[This guide](https://withblue.ink/2019/07/13/yes-you-can-run-docker-on-raspbian.html) goes into more detail.
