### ISSUE TITLE
Guide: Setting Up Docker + Laravel + Laradock + Let's Encypt SSL in Digital Ocean

### ISSUE THREAD

**Issue by midascodebreaker** [LaraDock/laradock#225]
Here is what i did to Set up a laravel Project in Digital Ocean

### Install Docker
```
Login Digital Ocean
Add Droplet
1 Click Install docker
Choose Droplet
reset ROOT password
check email
```

### SSH to your Server
```
ssh root@ipaddress
```
you will be prompt of that password.
type the password you receive in your email

then it will ask to you to change a new password
just change it to the custom root password you want

After SSH
you can check that docker command is working by typing 
```
$root@midascode:~# docker
```

### Set Up Your Laravel Project
```
$root@midascode:~# apt-get install git
$root@midascode:~# git clone https://github.com/laravel/laravel
$root@midascode:~# cd laravel
$root@midascode:~/laravel# git checkout develop
$root@midascode:~/laravel/ git submodule add https://github.com/LaraDock/laradock.git
$root@midascode:~/laravel/ cd laradock
```

### Install docker-compose command

```
$root@midascode:~/laravel/laradock# curl -L https://github.com/docker/compose/releases/download/1.8.0/run.sh > /usr/local/bin/docker-compose
$root@midascode:~/chmod +x /usr/local/bin/docker-compose
```

### Create Your LaraDock Containers

```
$root@midascode:~/laravel/laradock# docker-compose up -d nginx mysql
```

### Go to Your Workspace
```
docker-compose exec workspace bash
```

### Install laravel Dependencies, Add .env , generate Key and give proper permission certain folder
```
$ root@0e77851d27d3:/var/www/laravel# composer install
$ root@0e77851d27d3:/var/www/laravel# cp .env.example .env
$ root@0e77851d27d3:/var/www/laravel# php artisan key:generate
$ root@0e77851d27d3:/var/www/laravel# exit
$root@midascode:~/laravel/laradock# cd ..
$root@midascode:~/laravel# sudo chmod -R 777 storage bootstrap/cache
```

you can then view your laravel site at your ipaddress
for example
```
192.168.1.1 
```

You will see there Laravel Default Welcome Page

but if you need to view on your custom domain name
which you would.

### Using Your Own Domain Name
login to your DNS provider
Godaddy, Namecheap what ever...
And Point the Custom Domain Name Server to

```
ns1.digitalocean.com
ns2.digitalocean.com
ns3.digitalocean.com
```
In Your Digital Ocean Account go to 
```
https://cloud.digitalocean.com/networking/domains
```
add your domain name and choose the server ip you provision earlier

### Serve Site With NGINX (HTTP ONLY)
Go back to command line
```
$root@midascode:~/laravel/laradock# cd nginx
$root@midascode:~/laravel/laradock/nginx# vim laravel.conf
```
remove default_server
```

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

```
 and add server_name (your custom domain)
```
    listen 80;
    listen [::]:80 ipv6only=on;
    server_name yourdomain.com;
```

### Rebuild Your Nginx
```
$root@midascode:~/laravel/laradock/nginx# docker-compose down
$root@midascode:~/laravel/laradock/nginx# docker-compose build nginx
```

### Re Run Your Containers MYSQL and NGINX
```
$root@midascode:~/laravel/laradock/nginx# docker-compose up -d nginx mysql
```

##### To go Caddy Folders and Edit CaddyFile

```
$root@midascode:~/laravel/laradock# cd caddy
$root@midascode:~/laravel/laradock/caddy# vim Caddyfile
```

Remove 0.0.0.0:80 
```
0.0.0.0:80
root /var/www/laravel/public
``` 
and replace with your https://yourdomain.com
```
https://yourdomain.com
root /var/www/laravel/public
```
uncomment tls 
```
#tls self-signed
```
and replace self-signed with your email address
```
tls midascodebreaker@gmai.com
```
This is needed Prior to Creating Let's Encypt 

###  Run Your  Caddy Container without the -d flag and Generate SSL with Let's Encypt

```
$root@midascode:~/laravel/laradock/caddy# docker-compose up  caddy
```

you will be prompt here to enter your email... you may enter it or not
```
Attaching to laradock_mysql_1, laradock_caddy_1
caddy_1               | Activating privacy features...
caddy_1               | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy_1               | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy_1               |   https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf
caddy_1               | Activating privacy features... done.
caddy_1               | https://yourdomain.com
caddy_1               | http://yourdomain.com
```

After it finish Press Ctrl + C to exit ...

### Stop All Containers and ReRun Caddy and Other Containers on Background
```
$root@midascode:~/laravel/laradock/caddy# docker-compose down
$root@midascode:~/laravel/laradock/caddy# docker-compose up -d mysql caddy
```
View your Site in the Browser Securely Using HTTPS (https://yourdomain.com)

###### References : 
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
https://www.digitalocean.com/products/one-click-apps/docker/
https://docs.docker.com/engine/installation/linux/ubuntulinux/
https://docs.docker.com/compose/install/
https://caddyserver.com/docs/automatic-https
https://caddyserver.com/docs/tls
https://caddyserver.com/docs/caddyfile

**Comment by midascodebreaker** [comment]
i fixed it by issuing this command
```
sudo chmod -R 777 storage bootstrap/cache
```

**Comment by Mahmoudz** [comment]
@midascodebreaker that's Great! thanks for sharing. I will add this to the README file.

**Comment by midascodebreaker** [comment]
Added Some More Tips , Like Using Let;'s Encypt SSL Certificate...
Hope this Helps Many People

**Comment by appleboy** [comment]
Let's Encrypt SSL Certificate ++

**Comment by midascodebreaker** [comment]
glad you like it thanks

**Comment by Mahmoudz** [comment]
@midascodebreaker this is now part of the **Readme**, feel free to edit it anytime anyway you prefer.
[https://github.com/LaraDock/laradock#Digital-Ocean](https://github.com/LaraDock/laradock#Digital-Ocean)

Thanks.

**Comment by carraroenrico** [comment]
Great guide, thanks a lot!
@midascodebreaker It would be amazing if you can do it for amazon ECS!

**Comment by g0ld3lux** [comment]
ive updated it .... since digital ocean also updated their set up...

ive also added vim , oh-my-zsh and other great stuff for your terminal 

if you watch laracast vim tutorial , ive implemented it all ....

and make the terminal more beautiful 

Hope @Mahmoudz  can update the official docs... 
and include this updated version thanks 

https://gist.github.com/g0ld3lux/4145d031bccf66404dcdb78e9c30dc11

**Comment by dopyoman** [comment]
@midascodebreaker Is this guide still current? 

I've tried to follow the guide but noticed a inconsistencies. Also when trying to build the caddy container it just hangs

![caddy](https://i.imgur.com/3NoDULR.png)

**Comment by codeitlikemiley** [comment]
docker-compose up -d caddy, use the detached mode

**Comment by dopyoman** [comment]
@codeitlikemiley collecting github accounts like pokemon. 

I guess I was just trying to point out that the guide asks us to run the `docker-composer` command undetached to input an email, but I'm asking if that's still necessary. Has something changed to make the email input unnecessary.

**Comment by njoguamos** [comment]
Great guide. Worked for me. I however made a few twist for my project

Instead of 
`$root@midascode:~/laravel/ git submodule add https://github.com/LaraDock/laradock.git`
I run 
`$root@midascode:~/laravel/ git submodule update --init --recursive`
Since i had already added the submodule to my project

Also remember to copy your web server sites configuration before running ` docker-compose up -d nginx mysql` i.e
`$root@midascode:~/laravel/laradock/ cp env-example .env`

I thought this might help someone.

**Comment by huuvan20** [comment]
Hi,
I followed the guide above & the environment runs well. But this morning there was a sudden stop of all containers, when I logged in to check to containers, there was no containers. I'm deploying the app with laradock in Digital Ocean.
When I was trying to start all containers using `docker-compose up -d mysql caddy`, the Caddy cannot get started since the port 80 has been occupied by the Apache (Ubuntu 16.04 server). I stopped the Apache & could start the Caddy again. Now the app is running well.
But I wonder if the accident could happen again & what should I do to avoid this repeats? Thank you.

**Comment by shov** [comment]
If you get an issue with agreement like this:
```
caddy_1                | http plugins loaded: git, cors
caddy_1                | Activating privacy features... 
caddy_1                | 
caddy_1                | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy_1                | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy_1                |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
caddy_1                | Do you agree to the terms? (y/n): yyyy/mm/dd hh:ii:ss user must agree to CA terms (use -agree flag)
```
update your ./caddy/Dockerfile CMD to following view:
`CMD ["/usr/bin/caddy", "-agree", "-conf", "/etc/Caddyfile"]`

**Comment by chhedadhaval120386** [comment]
I am doing 
[docker-compose exec workspace bash](url)

from laravel/lardock directory but then it does not have laravel directory in the docker container so I don't understand how to run composer and other commands if I cannot get into the laravel folder

**Comment by agoiabel** [comment]
Please what if I have subdomains, and I want to add SSL?

**Comment by kapkory** [comment]
> Hi, I followed the guide above & the environment runs well. But this morning there was a sudden stop of all containers, when I logged in to check to containers, there was no containers. I'm deploying the app with laradock in Digital Ocean. When I was trying to start all containers using `docker-compose up -d mysql caddy`, the Caddy cannot get started since the port 80 has been occupied by the Apache (Ubuntu 16.04 server). I stopped the Apache & could start the Caddy again. Now the app is running well. But I wonder if the accident could happen again & what should I do to avoid this repeats? Thank you.

you can disable apache so that it can not start automatically, use 

> systemctl disable apache2
