### ISSUE TITLE
Using --fix-missing with apt-get update

### ISSUE THREAD

**Issue by marast78** [laradock/laradock#2255]
Often some packages are lost or resources' URLs are changed. We can prevent this issue using **--fix-missing** parameter with **apt-get update**.

`
    # always run apt update when start and after add new source list, then clean up at end.
    RUN apt-get update -yqq --fix-missing && \
`

Thoughts?

**Comment by bbashy** [comment]
This is an issue using master branch. I moved to the tags because containers weren't building.

**Comment by marast78** [comment]
> This is an issue using master branch. I moved to the tags because containers weren't building.

@bbashy  Wich tag I should use? The latest one is always stable?

**Comment by bbashy** [comment]
I used the latest v7 for a while and then I've gone ahead and checked out v8. Seems fine for me building these containers: php-fpm, nginx, workspace, mariadb, redis

**Comment by marast78** [comment]
@bbashy thx for the explanation :+1:

**Comment by bbashy** [comment]
I don't really know why some apt repos are 404 on master but using releases (tags) works for me.

I'm not sure with adding `--fix-missing` but it might be worth doing a PR for it if it fixes it on master.

**Comment by marast78** [comment]
I think it is worthy of attention because using ubuntu, I have often this issue and adding this parameter, I save my time and it shouldn't make any additional issues.
