### ISSUE TITLE
Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by Daisuke-sama** [laradock/laradock#2257]
### Info:
- Docker version (`$ docker --version`): 2.101
- Laradock commit (`$ git rev-parse HEAD`): latest
- System info (PC): win
- System info disto/version: 10

### Issue:
php 7.3, container **php-fpm** is not being built with SSH2 and mysql modules.
E: Package 'mysql-client' has no installation candidate

Also, redis isn't installed in the workspace container.
_____

### Expected behavior:
no error, everything is installed correctly
_____

### Reproduce:
just try to build with php7.3 and enabled mentioned packages.
_____

P.S. too much nervous have come within latest months from laradock containers have been not building often ((((

**Comment by metalcamp** [comment]
Is anyone else getting same error using PHP 7.2?

**Comment by nmsmith22389** [comment]
I'm getting the same error with v7.4.

**Comment by adjarriawan** [comment]
https://stackoverflow.com/questions/57048428/e-package-mysql-client-has-no-installation-candidate-in-php-fpm-image-build-u

i'm hope this can helping solved this problem.

**Comment by metalcamp** [comment]
Already fixed in following pull request: https://github.com/laradock/laradock/pull/2511
