### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by partenit** [laradock/laradock#2258]
### Info:
How about laradock versioning?
Where I can see what is current version? 
Not found version number in readme and on laradock.io.

**Comment by shov** [comment]
Probably it depends on the commit you are on. `https://github.com/laradock/laradock/releases`
If you just cloned it try for instance `git checkout v8.0`

**Comment by zr87** [comment]
Ia there any known breaking change from v7.* to v8.0?

**Comment by bestlong** [comment]
v8.0 move back base image to laradock docker hub
