### ISSUE TITLE
When I changed the PHP version from 7.1 to 5.6, there was an error about redis.

### ISSUE THREAD

**Issue by nihenbucuo** [laradock/laradock#2263]
### Info:
- Docker version (`$ docker --version`): 2.1
- System info (Mac, PC, Linux): Mac

### Issue:

_____
This error occurred when I changed the PHP version from 7.1 to 5.6：

warning: pecl/redis requires PHP (version >= 7.0.0, version <= 7.9.99), installed version is 5.6.40

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuserV4yf8Y/redis-5.0.2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/redis -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserV4yf8Y/redis-5.0.2/include -I/tmp/pear/temp/pear-build-defaultuserV4yf8Y/redis-5.0.2/main -I/tmp/pear/temp/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/redis/redis.c -o redis.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/redis -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserV4yf8Y/redis-5.0.2/include -I/tmp/pear/temp/pear-build-defaultuserV4yf8Y/redis-5.0.2/main -I/tmp/pear/temp/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/redis/redis.c  -fPIC -DPIC -o .libs/redis.o
In file included from /tmp/pear/temp/redis/redis.c:27:0:
/tmp/pear/temp/redis/common.h:12:28: fatal error: zend_smart_str.h: No such file or directory
 #include <zend_smart_str.h> ^

compilation terminated.
Makefile:180: recipe for target 'redis.lo' failed
make: *** [redis.lo] Error 1
ERROR: `make' failed
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl install -o -f redis     &&  rm -rf /tmp/pear     &&  docker-php-ext-enable redis ;fi' returned a non-zero code: 1

**Comment by lfelipe1501** [comment]
Yes i had the same problem...

for solution and use PHP 5.6 you need edit the 
### .env 
file and change this variable:

`PHP_FPM_INSTALL_PHPREDIS=true`

to 

`PHP_FPM_INSTALL_PHPREDIS=false`

and then compile again with the command:

`sudo docker-compose build php-fpm`

or 

`sudo docker-compose build --no-cache php-fpm`

**Comment by glorand** [comment]
The problem remains pertinent and is capable of being replicated.
