### ISSUE TITLE
Laravel-echo-server Error

### ISSUE THREAD

**Issue by NetBT** [laradock/laradock#2268]
### Info:
- Docker version (`$ docker --version`): 19.03.2
- Laradock commit (`$ git rev-parse HEAD`): 99da6ff60ceb5027d45cc3f3a023c481cae8b923
- System info (Mac, PC, Linux): PC
- System info disto/version: Win 10

### Issue:
When I started laravel-echo-server.An error occurred as below:
laravel-echo-server_1  | npm WARN using --force I sure hope you know what you are doing.
laravel-echo-server_1  |
laravel-echo-server_1  | > laravel-echo-server-docker@0.0.1 start /usr/src/app
laravel-echo-server_1  | > laravel-echo-server start
laravel-echo-server_1  |
laravel-echo-server_1  | Error: There is already a server running! Use the option '--force' to stop it and start another one.
laradock_laravel-echo-server_1 exited with code 0
_____

### Expected behavior:
_____

### Reproduce:
I dont know, sometimes it will be OK.
_____

### Relevant Code:

```
// place a code sample here
```

**Comment by Jokerwin** [comment]
I rebuilt this service and then start it again and worked:
```bash
$ docker-compose build --no-cache laravel-echo-server
$ docker-compose up laravel-echo-server
```

**Comment by cgrinker** [comment]
I ran into this problem today. I believe it stems from the `laravel-echo-server.lock` file being stored on your host volume. Removing the lockfile fixed the problem from me.

**Comment by ash-rain** [comment]
> ...it stems from the `laravel-echo-server.lock` file being stored on your host volume. Removing the lockfile fixed the problem from me.

Thank you this saved me!

**Comment by CelaumMm** [comment]
How do I remove laravel-echo-server.lock file?
