### ISSUE TITLE
Laradock Workspace - Raspery Pi (Raspiban

### ISSUE THREAD

**Issue by s1x** [laradock/laradock#2269]
### Info:
- Docker version: Docker version 19.03.2, build 6a30dfc

- Laradock commit cb910c590e00cee77ebbf75867aae0c7d0199119
- System info\: Rasperry Pi 3 / ARM / Raspian Image

### Issue:
Building "workspace" container

### Reproduce:
` docker-compose up -d workspace`
_____
```
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G dock&&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 1

```

**Comment by cwilby** [comment]
Can you produce the full logs? I had a similar issue building workspace recently with `fstrim`.

**Comment by s1x** [comment]
I do thing it might be the case that I would need an ARM image. I had a similiar problem with MariaDB and swichted to a ARM package. However, I cant find one for workspace.

Here attached the full logs:
> pi@raspberrypi:/mnt/UniDrive/projects/App/laradock $ sudo docker-compose up -d workspace
> Building workspace
> Step 1/219 : ARG LARADOCK_PHP_VERSION
> Step 2/219 : FROM laradock/workspace:2.5-${LARADOCK_PHP_VERSION}
>  ---> f46add99cf6d
> Step 3/219 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
>  ---> Using cache
>  ---> 0f508902de5a
> Step 4/219 : ARG LARADOCK_PHP_VERSION
>  ---> Using cache
>  ---> 26d976fbf86b
> Step 5/219 : ENV DEBIAN_FRONTEND noninteractive
>  ---> Using cache
>  ---> 5ff31e70527b
> Step 6/219 : USER root
>  ---> Using cache
>  ---> 1f692ead587d
> Step 7/219 : ARG PUID=1000
>  ---> Using cache
>  ---> 61d6b3eb11d7
> Step 8/219 : ENV PUID ${PUID}
>  ---> Using cache
>  ---> 69fb921115c2
> Step 9/219 : ARG PGID=1000
>  ---> Using cache
>  ---> 9ea0abceb2c3
> Step 10/219 : ENV PGID ${PGID}
>  ---> Using cache
>  ---> 93754b6efdab
> Step 11/219 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'
>  ---> Running in 7a7a1bdac9ba
> standard_init_linux.go:211: exec user process caused "exec format error"
> ERROR: Service 'workspace' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 1
> pi@raspberrypi:/mnt/UniDrive/projects/App/laradock $

**Comment by cwilby** [comment]
I agree, looking at the [workspace image](https://github.com/laradock/workspace), it's using phusion:baseimage, which [recently merged support for multiarch images](https://github.com/ytti/oxidized/issues/1451).  You could copy the Dockerfile for workspace and change the base image to arm.. somehow :) 

Doesn't seem to be well documented yet.

**Comment by gmatkowski** [comment]
Have you found any solution on how to install laradock @ raspberry ARM ?

**Comment by s1x** [comment]
@gmatkowski Sorry, I have not tried it any further and set it up on a different environment.
