### ISSUE TITLE
Laravel can't connecto to mongo

### ISSUE THREAD

**Issue by IgorDePaula** [LaraDock/laradock#227]
I enabled installation of mongo extension, and to up apache and mongo, my laravel project do not connect to mongo container, after I down the mongo container and up my mongo local installation and again my laravel project do not connect to mongo.

```ConnectionTimeoutException in Collection.php line 666: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '127.0.0.1:27017': Connection refused]```

**Comment by kuerbi** [comment]
Have the same problem here:
What have you done to solve this problem? @IgorDePaula

**Comment by samarhaider** [comment]
@IgorDePaula How do you resolve this?

**Comment by daywong1119** [comment]
@samarhaider try to update project's .env file `DB_HOST=mongo`
