### ISSUE TITLE
MySQL DB Import

### ISSUE THREAD

**Issue by prezire** [laradock/laradock#2270]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.6, build 481bc77
- Laradock commit (`$ git rev-parse HEAD`): 871a9d032a5ef36155d444c75fb47e0fc187fae6
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04 LTS

### Issue:
I've placed these items to either **[mysql]** or **[mysqld]** section of **my.conf** file, and rebuilt the container by running `docker-compose build mysql`, however I'm still unable to import **.sql** files greater than 300MB:
```
max_allowed_packet=500M
upload_max_filesize=2G
innodb_log_file_size=100M
wait_timeout=1800
net_read_timeout=1800
```

**Comment by cwilby** [comment]
Is `my.cnf` being copied to the container? 

```bash
# shell into the mysql container
$ docker-compose exec mysql sh

# list where mysql looks for cnf file
$ mysql --help | grep /my.cnf | xargs
```

**Comment by namnguyen2091** [comment]
@cwilby I run your last query and I got result: /etc/my.cnf /etc/mysql/my.cnf ~/.my.cnf and I dont know my.cnf is copied or not

**Comment by namnguyen2091** [comment]
Rebuild container and docker-compose up
