### ISSUE TITLE
Laravel-Horizon Run Container error

### ISSUE THREAD

**Issue by quangvision** [laradock/laradock#2278]
Hi
I am running Laradock 8.0.
`docker-compose up -d laravel-horizon` caused this error:
![2019-09-12_160142](https://user-images.githubusercontent.com/12606323/64770450-68f19c80-d577-11e9-89c6-800e95db0c9b.png)
Is there anybody know why?
Thanks :)

**Comment by bestlong** [comment]
ref https://github.com/laradock/laradock/pull/2309
