### ISSUE TITLE
elastic up fail

### ISSUE THREAD

**Issue by mohammadkshn** [laradock/laradock#2283]
### Info:
- Docker version Docker version 19.03.2, build 6a30dfc: 
- System info linux-ubuntu: 
- System info 18.4: 

### Issue:
use elasticsearch 6.8.3
after docker-compose up -d elasticsearch 
elasticsearch exited with code 1 after 20 second

### Relevant Code:
// place a code sample here
 elasticsearch:
    build: ./elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=laradock-cluster
      - node.name=laradock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.initial_master_nodes=laradock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

**Comment by dziurka** [comment]
I have the same problem. Unfortunately

**Comment by dziurka** [comment]
Deleting the environment variable "cluster.initial_master_nodes" solved the problem in my case.

**Comment by mohammadkshn** [comment]
> I have the same problem. Unfortunately.
> 
> EDIT:
> Deleting the environment variable "cluster.initial_master_nodes" solved the problem in my case.

tnx work for me
