### ISSUE TITLE
centos7   apt-get update -yqq  

### ISSUE THREAD

**Issue by yonglefu** [laradock/laradock#2284]
---> Running in 328e44f5fa64
Removing intermediate container 328e44f5fa64
 ---> f8e67bb504ef
Step 11/219 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'
 ---> Running in c814e1afac2c
+ apt-get update -yqq

**Comment by shandongcy** [comment]
同样的问题，更换成ubuntu可行--

**Comment by huangxingle2009** [comment]
win7 也碰到这个问题， 如何解决大神们
