### ISSUE TITLE
rebuild failed because nginx default.key permission

### ISSUE THREAD

**Issue by Goddard** [laradock/laradock#2285]
OSError: Can not read file in context: laradock/nginx/ssl/default.key

Everything in the ssl directory is written as root.  I changed permission for ownership and group to my user and then I was able to build.

**Comment by BrothelUndercover** [comment]
same issue!

**Comment by ultrono** [comment]
Yep I'm getting the same via a new install from the latest version on Ubuntu. 

Changing file SSL permissions didn't work. Only way I could get the nginx container running was to comment out the SSL related settings in my nginx site config.

**Comment by VesterDe** [comment]
I'm also getting this issue, although yesterday a normal build just worked.

**Comment by VesterDe** [comment]
I dirty fix was to chown it to my user, but that shouldn't be needed.

**Comment by NoumanArshad83** [comment]
Hello,

I got the issue, to reproduce erro

1. Build default laradoc containers using command **docker-compose up -d mysql php-fpm nginx**
2. Stop containers using **docker-compose stop**
3. open **.env** file in laradoc and rename **COMPOSE_PROJECT_NAME** value to something else and save file
4. run command again **docker-compose up -d mysql php-fpm nginx**

it will give error
**Permission denied: '/home/laradock/nginx/ssl/default.key'** which were set as **root** and permissions **xr - -**

**Solution**
Changing permission to **chmod 644** resolved issue
