### ISSUE TITLE
multiple project .env problem

### ISSUE THREAD

**Issue by ezekel** [laradock/laradock#2287]
Hi can I ask some help I am new to the laradock and I want to run my 2 laravel app, but I am having problem. can you help me please.

```
# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=../
cp nginx/sites/laravel.conf.example nginx/sites/mysite1.conf
cp nginx/sites/laravel.conf.example nginx/sites/mysite2.conf

```

This is the error when I docker-composer up -d inside laradock

```

ERROR: In file .\.env: environment variable name 'cp nginx/sites/laravel.conf.example nginx/sites/mysite1.conf' may not contains whitespace.

```

**Comment by jzonta** [comment]
You cannot execute a "cp" command on the .env file. .Env is for variable variables only.

See in the application how you should add a new project.
https://laradock.io/getting-started/#B

**Comment by ezekel** [comment]
@jzonta 

Thank you so much it works now
