### ISSUE TITLE
laradock nginx sever 404

### ISSUE THREAD

**Issue by shandongcy** [laradock/laradock#2289]
### Info:
Docker version 18.09.7, build 2d0083d
Linux VM-0-4-ubuntu 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Issue:
setting:  APP_CODE_PATH_HOST=../webroot/
![image](https://user-images.githubusercontent.com/21023272/65163017-d1a3b200-da6c-11e9-8a86-93d7f3b0e916.png)

nginx container and php-fpm container has different CODE_PATH ,so i can't find the file when i use $document_root ,only this way to use it?

**Comment by bestlong** [comment]
base on .env `APP_CODE_PATH_HOST=../webroot/`
why you set nginx site config `root /var/www/webroot/join/api` ?
