### ISSUE TITLE
Erro with command vapor in laradock workspace

### ISSUE THREAD

**Issue by jzonta** [laradock/laradock#2291]
### Info:
- Docker version 18.09.9 build 039a7df9ba
- Laradock commit fa1f33bc518f23b850e8056fccc04a58e5185eca: 
- System info PC: 
- System info Windows 7: 

### Issue:
I try use new Laravel Vapor (https://vapor.laravel.com) in laradock and when i run any command vapor, return this:

`laradock@e8e682579899:/var/www/testevapor$ php vendor/bin/vapor help deploy`

```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd '../laravel/vapor-cli' && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/vapor" "$@"
```

Any ideia?

**Comment by cwilby** [comment]
I'm confused, is the Vapor command returning a bash script or an error?

**Comment by jzonta** [comment]
Sorry, not error message. Just returns:

`dir=$(cd "${0%[/\\]*}" > /dev/null; cd '../laravel/vapor-cli' && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/vapor" "$@"`

After return to command line.

**Comment by cwilby** [comment]
Similar issue here on a different project: https://github.com/nunomaduro/phpinsights/issues/41

Try running `vendor/bin/vapor help` without the php prefix.

**Comment by jzonta** [comment]
In the Vapor documentation says to run command "php vendor/bin/vapor list" but the correct is "vendor/bin/vapor list" without php at first.

Thanks @cwilby

**Comment by jzonta** [comment]
In the Vapor documentation says to run command "php vendor/bin/vapor list" but the correct is "vendor/bin/vapor list" without php at first.

Thanks @cwilby

**Comment by vortechron** [comment]
vendor/bin/vapor help without php solve my problem, tq @cwilby
