### ISSUE TITLE
Access ImageMagick in laravel-horizon

### ISSUE THREAD

**Issue by bastosh** [laradock/laradock#2296]
### Info:
- Docker version: 19.03.1, build 74b1e89
- Laradock commit: 818eb1f59d6830657c4318acc33a93ed812037ef
- System info: Debian GNU/Linux 9

### Issue:
We are using Spatie medialibrary. When uploading and processing images with a classical php artisan queue:work in the workspace, everything is fine. But when running laravel-horizon, jobs fail with this error:

```
ImageMagick module not available with this PHP installation.
```
or (when we change the driver)
```
GD Library extension not available with this PHP installation.
```

Is there a way to install the extensions in laravel-horizon container, or to make them accessible? Are we missing something? 

```
WORKSPACE_INSTALL_IMAGEMAGICK=true
PHP_FPM_INSTALL_IMAGEMAGICK=true
```

**Comment by Dylan-Duault** [comment]
Hello,

I have the same issue here, any help would be appreciated :)

Thanks

**Comment by tnduc** [comment]
The same problem, how did you solve it?
