### ISSUE TITLE
laravel-horizon docs

### ISSUE THREAD

**Issue by shaneparsons** [laradock/laradock#2297]
The steps to get the `laravel-horizon` container up and running properly are very confusing, and not "officially" documented anywhere.

I've followed [this](http://bit.ly/2llrMM7) and [this](https://github.com/laradock/laradock/pull/1854#issuecomment-451614549), and while it appears to finally be working now, I don't know which of the steps I followed were actually necessary, and which may just be bloating up my containers.

If somebody could please clarify exactly what needs to be done to set up `laravel-horizon` and add more information about it (as well as more info about `php-worker/supervisord.d`) in the official docs, it would go a long way to help confused individuals like myself.

**Comment by marcelogarbin** [comment]
Hello, I came across this too.. Any news on?

**Comment by shaneparsons** [comment]
@marcelogarbin If you already have supervisord running for other purposes it's probably more convenient to add the horizon.conf to it as described in the first link. If for some reason you only need horizon, or want it in a separate container for other reasons, then renaming laravel-horizon.conf.example -> laravel-horizon.conf per the second link is what you'll want to do. There definitely isn't a need for both...

Still not sure what the best way to handle this in multi-site situations is though... but my guess is you would need to use some form of iteration.

**Comment by marcelogarbin** [comment]
> @marcelogarbin If you already have supervisord running for other purposes it's probably more convenient to add the horizon.conf to it as described in the first link. If for some reason you only need horizon, or want it in a separate container for other reasons, then renaming laravel-horizon.conf.example -> laravel-horizon.conf per the second link is what you'll want to do. There definitely isn't a need for both...
> 
> Still not sure what the best way to handle this in multi-site situations is though... but my guess is you would need to use some form of iteration.

Thanks for the feedback. I'm using the 2 container: php-worker laravel-horizon.

So in this case I will only use php-worker as you explained earlier. I'm still testing Laradock.
