### ISSUE TITLE
Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by shinichi-ito** [laradock/laradock#2300]
### Info:
- Docker version (`$ docker --version`): Docker version 18.06.1-ce, build e68fc7a
- Laradock commit (`$ git rev-parse HEAD`): git clone https://github.com/Laradock/laradock.git
- System info (Mac, PC, Linux): windows10 pro
- System info disto/version: windows10pro

### Issue:
$ docker-compose up -d nginx mysql
_____

E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/libx/libxdmcp/libxdmcp6_1.1.2-3_amd64.deb  400  Bad Request [IP: 151.101.228.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGE_OPTIMIZERS} = true ]; then     apt-get install -y jpegoptim optipng pngquant gifsicle ;fi' returned a non-zero code: 100

↓

https://github.com/laradock/laradock/issues/1890#issuecomment-454434262

/laradock/php-fpm/Dockerfile

###########################################################################
# Image optimizers:
###########################################################################

USER root

ARG INSTALL_IMAGE_OPTIMIZERS=false

RUN if [ ${INSTALL_IMAGE_OPTIMIZERS} = true ]; then \
    apt-get update && \
    apt-get install -y jpegoptim optipng pngquant gifsicle \
;fi

↓

docker-compose build --no-cache php-fpm

↓

E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/libx/libxdmcp/libxdmcp6_1.1.2-3_amd64.deb  400  Bad Request [IP: 151.101.196.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGE_OPTIMIZERS} = true ]; then     apt-get update &&     apt-get install -y jpegoptim optipng pngquant gifsicle ;fi' returned a non-zero code: 100

Who's coming to help me?

Installation failed many times!!

.env
https://docs.google.com/document/d/13zccsQDJ49LlcqhqMkS2AE9JFmaFgz1XiQsbO2hiNiI/edit?usp=sharing

**Comment by khiconit** [comment]
Same issue

**Comment by BenjaminRouge923** [comment]
Same issue for me on macos

**Comment by mauriciomta** [comment]
I solved the issue by adding an `apt-get update` before the installation on `php-fpm/Dockerfile`
```
RUN if [ ${INSTALL_IMAGE_OPTIMIZERS} = true ]; then \
    apt-get update && apt-get install -y jpegoptim optipng pngquant gifsicle \
;fi
```
