### ISSUE TITLE
How to set up haproxy and varnish in laravel project

### ISSUE THREAD

**Issue by zatkniz** [laradock/laradock#2308]
I am trying to figure out how to make haproxy and varnish work in laradock. There is no documentation about it. I am composing up haproxy it automatically composing proxy1 proxy2 and then cant figure out how does this work. Can anyone give any tip or any tutorial? Please?

**Comment by asannikov** [comment]
Added PR with new varnish configuration. Probably it will help you. 
https://github.com/laradock/laradock/pull/2348

**Comment by zatkniz** [comment]
That sounds Great.. But what are the next steps? just composing up haproxy and everything works fine?

> Added PR with new varnish configuration. Probably it will help you.
> #2348

**Comment by avestique** [comment]
> That sounds Great.. But what are the next steps? just composing up haproxy and everything works fine?

Unfortunately i did not test it with haproxy. But proxy1 and proxy2 use varnish
