### ISSUE TITLE
suggestions: prestashop, magento2, wordpress

### ISSUE THREAD

**Issue by roscopecoltran** [laradock/laradock#2310]
Hi guys,

Hope you are all well !

I was just wondering why Prestashop, Magento2 or Wordpress are not bundled in Laradock.

It would awesome, isn't it ? or what are the reason ?

Ps. I am ready to fork and do it.

Cheers,
Rosco

**Comment by roscopecoltran** [comment]
some others:

https://github.com/dgraph-io/dgraph
https://github.com/devopsfaith/krakend-ce

**Comment by lanphan** [comment]
In fact, Laradock can support you to have dev environment for those awesome products.
In the past, I did try to use Laradock as a dev env for Magento2; Prestashop and Wordress, I don't touch them yet.

**Comment by shov** [comment]
If it could be useful for someone https://github.com/shov/wordpress-laradock

**Comment by x0rzkov** [comment]
Here are some refs:
- https://github.com/mattiamari/docker-prestashop1.7-php7-fpm
- https://github.com/aliuosio/mage2.docker
