### ISSUE TITLE
build workspace faild on 11/219 (apt-get update -yqq)

### ISSUE THREAD

**Issue by Justice112** [laradock/laradock#2312]
### Info:
- Docker version (`$ docker --version`): Docker version 18.06.3-ce, build d7080c1
- Laradock commit (`$ git rev-parse HEAD`): 861ea6b16ea3c2e9706425f5f0a49cc7c8988d3d
- System info (Mac, PC, Linux): Linux
- System info disto/version: centos8.1095

### Issue:

_____Dont know

### Expected behavior:

_____want to build workspace

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```
Step 11/219 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'
 ---> Running in 583a1012a185
+ apt-get update -yqq
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ pecl channel-update pecl.php.net
Updating channel "pecl.php.net"
Channel "pecl.php.net" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
Trying channel "pecl.php.net" over https:// instead
Cannot retrieve channel.xml for channel "pecl.php.net" (Connection to `ssl://pecl.php.net:443' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution)
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 1

**Comment by bestlong** [comment]
Maybe cause by firewall.
Ref #2238, #2232

**Comment by liminworks** [comment]
its ok？

**Comment by namnguyen2091** [comment]
@bestlong im not in china but I can not install
