### ISSUE TITLE
Cant connect from workspace by psql

### ISSUE THREAD

**Issue by LordJohn42** [laradock/laradock#2324]
### Info:
- Docker version: 18.09.6, build 481bc77
- Laradock commit: 04c6aaf3389ebd30e2874788b90437f229effb0b
- System info (Mac, PC, Linux): Linux 
- System info disto/version: Ubuntu 16.04 (Digital Ocean droplet)

### Issue:
Cant connect to postgres from workspace. 

Try command: 

    psql
	## OR
	psql -H localhost
	## OR
	psql -U default

    psql: could not connect to server: No such file or directory
    	Is the server running locally and accepting
    	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

_____

### Expected behavior:
Succesful connect to postgres db.
_____

### Reproduce:
psql
_____

This is really simple error. But i dont understand, what im doing wrong.

**Comment by DesarrolloJulio** [comment]
Hello, I try to log in to psql and send me this message
sudo docker-compose exec postgres psql -U gamest -d gamest
**psql: error: could not connect to server: FATAL:  role "gamest" does not exist**

**Comment by shov** [comment]
@LordJohn42 from inside of the workspace container you should connect **not to** `localhost` but to `postgres`

* Make sure you `workspace` and `postgres` are both running `docker-compose ps`
* Go into the workspace `docker-compose exec workspace bash`
* Connect `psql -U default -h postgres -p 5432 default`
ps check the creds in your .env and the port in output of ps

**Comment by LordJohn42** [comment]
@shov Thank you.

**Comment by parmonov98** [comment]
`psql: error: FATAL:  password authentication failed for user "default"`
