### ISSUE TITLE
Why is MySQL version variable ignored during build?

### ISSUE THREAD

**Issue by dmxd5** [laradock/laradock#2331]
In `.env` I have `MYSQL_VERSION=5.7`, but when I build containers, it still pulls the latest mysql image, not the 5.7 version as set in .env file.

**Comment by lanphan** [comment]
Which docker / docker-compose command you used to build?
In case you re-build it, please make sure you have a clean build (--no-cache option)

**Comment by dmxd5** [comment]
I use `docker-compose up -d`

**Comment by shov** [comment]
@dmxd5 perhaps you have got a cache, try `docker-compose build --no-cache mysql` then start again

**Comment by Glorydaqin** [comment]
I got the same problem . macos 10.15.

**Comment by saulopaiva** [comment]
I guess it is because of `MYSQL_VERSION` is fixed to use `latest` on `mysql/Dockerfile`.

I've changed to use the same ENV var and it worked.

This PR is a proposal to solve this: https://github.com/laradock/laradock/pull/2479
