### ISSUE TITLE
how to show diagram pgadmin laradock

### ISSUE THREAD

**Issue by duong120798** [laradock/laradock#2336]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Mac
- System info disto/version: pgadmin4

### Issue:

_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by lanphan** [comment]
What's exactly your issue?
