### ISSUE TITLE
Disable docker-in-docker (dind) by default

### ISSUE THREAD

**Issue by shaneparsons** [laradock/laradock#2338]
### Info:
- Docker version (`$ docker --version`): `19.03.4, build 9013bf5`
- Laradock commit (`$ git rev-parse HEAD`): `04c6aaf3389ebd30e2874788b90437f229effb0b`
- System info (Mac, PC, Linux): `Mac`
- System info disto/version: `Catalina`

### Question:
What's the purpose of `docker-in-docker`?

I'm trying to "minimize" my docker-compose.yml (removing everything I don't need) and I noticed that `workspace` and `php-fpm` both rely on this `docker-in-docker`... What does it do, and can I remove the `environment` and `links` references to it?

**Comment by lanphan** [comment]
docker-in-docker helps you to be able to run docker command in docker container. In case you don't need it, you can remove that.

**Comment by shaneparsons** [comment]
Ah okay... It doesn't sound like something I need, but can you perhaps give me an example of how / why somebody might use this?

**Comment by cwilby** [comment]
https://github.com/laradock/laradock/pull/1655

**Comment by shaneparsons** [comment]
Echoing cwilby's comment in the referenced pull request, I also think this should be turned off by default, with the option to turn it on in the rare case that somebody needs it... Somebody new to Docker / Laradock, like me, will just assume that this is needed and likely leave it enabled.

I'll leave this issue open for the above reason.

**Comment by lanphan** [comment]
@shaneparsons @vlauciani after reviewing, I see that using links from workspace / php-fpm to docker-in-docker (dind) makes dind become mandatory service in Laradock.
As we agree that dind should be an optional service, therefore, I'd like to remove that link. For those who want to have dind, just start it explicitly, for ex:
```
docker-compose up workspace php-fpm docker-in-docker
```
Let I test locally, then have PR for this soon.

**Comment by shaneparsons** [comment]
@lanphan For what it's worth, I tried it locally a few days ago with all links to dind removed and everything seemend to work fine. [Here's the docker-compose I was using](https://github.com/shaneparsons/laradock/blob/master/docker-compose.yml) if it helps... Note, a lot of the other default containers have also been removed for other reasons.

**Comment by Yiidiir** [comment]
@lanphan did u merge  a solution to this?

**Comment by attozk** [comment]
+1
