### ISSUE TITLE
Cryptojacking attack via Redis container

### ISSUE THREAD

**Issue by sondoha** [laradock/laradock#2346]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): 
- System info disto/version: 

### Issue:
Hello,

I've been using Laradock for a while. It was great!

But just realized that Redis Docker container had been attacked. All 16 CPU cores were up to 100%.

Use `htop` command, I see something like this:

```
xmrig-notls -o pinto.mamointernet.icu:4444 -u ver1 -p ver1 --max-cpu-usage 100 --donate-level 1 -B
```

Has anyone faced this issue? And how did you deal with it?

PS: The same issue has been reported here:

https://medium.com/threat-intel/cryptojacking-coin-mining-cybercrime-234895bec6e1
https://gitter.im/tiangolo/fastapi?at=5d89d0b78521b34d91803d83
_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by lanphan** [comment]
Hi,
I think you should secure your network more by configuring firewall / gateway / proxy more secure (allow 80, 443 ports out only, for ex).
In case you have more secure configuration for Redis, please help share with us.
Thanks.

**Comment by BernardoMG** [comment]
Hi, 
I'm facing the same issue on an ec2 instance. @sondoha any tip on how to remove trojan?

**Comment by sondoha** [comment]
It is still happening to me. Even if I banned the Redis port from public.

So I use queue driver `sync` instead of `redis`. Sure it is for development only, I do not have any solution for production atm.

**Comment by BernardoMG** [comment]
Yes, banning Redis port isn't enough @sondoha. 

We manage to fix it by:
1) Launching a new instance with the most recent Redis version;
2) Clean weird crontab entires (immediately after previous step);
3) Delete `networkservice` if exists 

This instance looks good, no weird process consuming CPU 🙂
