### ISSUE TITLE
mac 下报错 ， apt-get update -yqq 无法执行

### ISSUE THREAD

**Issue by 310898026** [laradock/laradock#2358]
---> Running in 9f40413d672a
+ apt-get update -yqq
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/by-hash/SHA256/b0c14b409c2c7b5a76a3d75e6b087f130f3dbe3145c319297e6a9ff5f008ae92  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 100

**Comment by t0rjan** [comment]
发英文，大哥你发中文谁看的懂？

**Comment by sleepm** [comment]
是因为网络问题，开代理就好了

**Comment by 310898026** [comment]
已经开代理了， mac，下好像没有  apt-get 这个命令，为什么会执行

**Comment by 310898026** [comment]
> 是因为网络问题，开代理就好了
已经开代理了， mac，下好像没有 apt-get 这个命令，为什么会执行

**Comment by sleepm** [comment]
> > 是因为网络问题，开代理就好了
> > 已经开代理了， mac，下好像没有 apt-get 这个命令，为什么会执行

dockerfile里的命令都是在容器里执行的
代理在 docker desktop 里有设置，或者命令行设置
export http_proxy='http://192.168.3.3:1087'
export https_proxy='http://192.168.3.3:1087'
不建议127.0.0.1:1087 是因为容器里读到的代理地址也是127.0.0.1

**Comment by sleepm** [comment]
系统代理
终端 shell 代理
应用代理
是三个不同的设置

**Comment by 310898026** [comment]
多谢，虽然我没明白，容器内怎么配置，使用宿主机代理，但是我把registry mirrors 的地址，复制到proxies里，好像还是好了，但还是报错了
> Verifying integrity...
gpg: keyring `/home/laradock/.gnupg/secring.gpg' created
gpg: key 86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: Signature made Tue 08 Oct 2019 11:36:57 AM UTC using RSA key ID 69475BAA
gpg: BAD signature from "Yarn Packaging <yarn@dan.cx>"
> GPG signature for this Yarn release is invalid! This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_YARN} = true ]; then     [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" &&     if [ ${YARN_VERSION} = "latest" ]; then         curl -o- -L https://yarnpkg.com/install.sh | bash;     else         curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION};     fi &&     echo "" >> ~/.bashrc &&     echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> ~/.bashrc ;fi' returned a non-zero code: 1
adeMacBook-Pro:laradock a$

**Comment by sleepm** [comment]
在Dockerfile中找需要代理的地方，在前面加
RUN export http_proxy='http://192.168.3.3:1087'
RUN export https_proxy='http://192.168.3.3:1087'
 比如 yarn install
apt的代理有些特殊，需要改
/etc/apt/apt.conf.d/proxy.conf
RUN echo 'Acquire::http::Proxy "http://user:password@proxy.server:port/";'  >>/etc/apt/apt.conf.d/proxy.conf
RUN echo 'Acquire::https::Proxy "http://user:password@proxy.server:port/";'>>/etc/apt/apt.conf.d/proxy.conf

系统代理是系统上设置的，但是终端比较调皮，终端里的shell不认系统代理，需要export设置变量，设置完也只是在当前shell当前标签页可用
应用内代理，就比如chrome有switchyomega插件设置，插件设置直连，那会就直接无视系统代理
所以是三个不同的代理

**Comment by 310898026** [comment]
> 在Dockerfile中找需要代理的地方，在前面加
> RUN export http_proxy='http://192.168.3.3:1087'
> RUN export https_proxy='http://192.168.3.3:1087'
> 比如 yarn install
> apt的代理有些特殊，需要改
> /etc/apt/apt.conf.d/proxy.conf
> RUN echo 'Acquire::http::Proxy "http://user:password@proxy.server:port/";' >>/etc/apt/apt.conf.d/proxy.conf
> RUN echo 'Acquire::https::Proxy "[http://user:password@proxy.server:port/";'>>/etc/apt/apt.conf.d/proxy.conf](http://user:password@proxy.server:port/%22;'%3E%3E/etc/apt/apt.conf.d/proxy.conf)
> 
> 系统代理是系统上设置的，但是终端比较调皮，终端里的shell不认系统代理，需要export设置变量，设置完也只是在当前shell当前标签页可用
> 应用内代理，就比如chrome有switchyomega插件设置，插件设置直连，那会就直接无视系统代理
> 所以是三个不同的代

好详细，多谢哈

**Comment by pabloleone** [comment]
I've restarted Docker for mac and then I've executed the following command:

```
docker-compose build --no-cache nginx mysql
```

It worked!

**Comment by amorZhu** [comment]
首先设置 docker 镜像为阿里云，其次，按照这个提交处理一下ubuntu源和nvm #2388
