### ISSUE TITLE
workspace and php-fpm does not connect to external MSSQL

### ISSUE THREAD

**Issue by crisleiria** [laradock/laradock#2362]
### Info:
- Docker version 19.03.4, build 9013bf5
- Laradock commit 3cdc771abd453f7ea30932659377ce9dc4806538
- System info (Mac, PC, Linux): PC - Windows 10

### Issue:

After setting variables WORKSPACE_INSTALL_MSSQL and PHP_FPM_INSTALL_MSSQL to true,
I want to connect to existing MSSQL Server.

When I try to connect I receive this error:

`local.ERROR: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (SQL: ...`

SQL Server versions where this issue was tested:
SQL Server 2008 R2 (10.50.6560.0)
SQL Server 2012 (12.0.6108.1)

_____

### Expected behavior:

Connect without any errors.

_____

### Reproduce:

Setup Laradock and test an SQL Server connections
_____

### Relevant Code:

Docker files from php-fpm and workspace, on the SQL Server section

```
###########################################################################
# SQL SERVER:
###########################################################################

ARG INSTALL_MSSQL=false

RUN set -eux; \
  if [ ${INSTALL_MSSQL} = true ]; then \
    if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
      apt-get -y install freetds-dev libsybdb5 \
      && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/libsybdb.so \
      && docker-php-ext-install mssql pdo_dblib \
      && php -m | grep -q 'mssql' \
      && php -m | grep -q 'pdo_dblib' \
    ;else \
      ###########################################################################
      # Ref from https://github.com/Microsoft/msphpsql/wiki/Dockerfile-for-adding-pdo_sqlsrv-and-sqlsrv-to-official-php-image
      ###########################################################################
      # Add Microsoft repo for Microsoft ODBC Driver 13 for Linux
      apt-get install -y apt-transport-https gnupg \
      && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
      && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
      && apt-get update -yqq \
      && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev libgss3 odbcinst msodbcsql17 locales \
              && echo "en_US.UTF-8 zh_CN.UTF-8 UTF-8" > /etc/locale.gen \
              && locale-gen \
      # Install Dependencies
      && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev libgss3 odbcinst msodbcsql17 locales \
      && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
      # link local aliases
      && ln -sfn /etc/locale.alias /usr/share/locale/locale.alias \
      && locale-gen \
      # Install pdo_sqlsrv and sqlsrv from PECL. Replace pdo_sqlsrv-4.1.8preview with preferred version.
      && if [ $(php -r "echo PHP_MINOR_VERSION;") = "0" ]; then \
        pecl install pdo_sqlsrv-5.3.0 sqlsrv-5.3.0 \
      ;else \
        pecl install pdo_sqlsrv sqlsrv \
      ;fi \
      && docker-php-ext-enable pdo_sqlsrv sqlsrv \
      && php -m | grep -q 'pdo_sqlsrv' \
      && php -m | grep -q 'sqlsrv' \
    ;fi \
  ;fi

```

Any one with this problem?

**Comment by cwilby** [comment]
Hi @crisleiria, what address are you trying to connect to?  

If you're connecting from SSMS, you'd make sure `MSSQL_PORT=1433` is set in `./laradock/.env` file, run your containers, then connect to `127.0.0.1:1433`.

For creating connections in Laravel, make sure `DB_HOST` is set to `mssql` in `.env` and in the same network.

**Comment by crisleiria** [comment]
Hi @cwilby,

I am trying to connect to an external SQL Server, ports are correctly setup, I have access to SQL Server from docker host.. 
I dont have connection to the network host?

Thanks in advance

**Comment by lanphan** [comment]
Hi @crisleiria ,
Would you please double check that mssql container is already up?
It's better to check docker logs of mssql to see it works or not
```
docker logs mssql
```

**Comment by crisleiria** [comment]
Hi @lanphan,

I am connecting to an existing SQL Server instance installed on an Windows Server 2008 R2. Not a docker container.
It is connected 24/7. Connected for sure ;)

Thanks in advance

**Comment by cwilby** [comment]
Is `DB_HOST` set to the SQL Server address in `.env`?

**Comment by crisleiria** [comment]
Hi @cwilby,

On which .env are you talking about? inside my laravel project yes it is and all settings are correct (I am able to connect on Homestead vitualbox).

on laradoc .env there is not DB_HOST variable...

**Comment by lanphan** [comment]
Hi @crisleiria ,
Current network driver doesn't support you to connect to external host (in ```.env``` of laradock):
```
NETWORKS_DRIVER=bridge
``` 

Please check this blog post to understand more about docker networking drivers:
https://www.docker.com/blog/understanding-docker-networking-drivers-use-cases/

I think you can try to switch to ```macvlan```

**Comment by crisleiria** [comment]
@lanphan I understand, 
I will definitely do a reading on this, thanks. I am clearly a newby on docker, and I want to learn more.

But I have made a simple test: 
On my .env projet file I have simply change to a wrong port number and test connection.
On this case I receive an expected time out error after some time.
When I set correct port number error above is immediate and it is a different error.

I honestly don't know what it is happening.. but I will give it a try. 

I also suspect some problem on TLS settings on php-fpm and workspace containers. It seems SQL server driver requires TLS 1.2.

**Comment by brunogasparetto** [comment]
I have the same issue.

When I run the query builder with Tinker in the Workspace container all works, but when I run in the browser or with Tinker in the php-fpm container I receive this same exception.

**Comment by andersson83** [comment]
Hi everyone, I have the same issue. I cannot connect to external MSSQL. Anyone can help me?

**Comment by crisleiria** [comment]
I have opened this issue and for me is an open issue. I didn't forward on this, because for me MSSQL connection is an requirement. I am still using homestead. On the biggining of June I will have a window time to get back on this. I will publish my findings here or open new issue.
