### ISSUE TITLE
执行到apt-get update -yqq这一步时报错了

### ISSUE THREAD

**Issue by ManiuLtd** [laradock/laradock#2368]
![TIM截图20191113210512](https://user-images.githubusercontent.com/36794003/68766167-53711f80-0659-11ea-815d-bd7f12727a2e.png)

错误信息如下：

> + apt-get update -yqq
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
W: GPG error: http://archive.ubuntu.com/ubuntu xenial-backports Release: The following signatures were invalid: BADSIG 40976EAF437D05B5 Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
E: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' is no longer signed.

求大佬们指教下，已经搞了一天都没搞定，全局翻墙代理都不起作用

**Comment by pabloleone** [comment]
I've restarted Docker for mac and then I've executed the following command:

```
docker-compose build --no-cache nginx mysql
```

It worked!

**Comment by HiWilliam** [comment]
我和你遇到了同样的问题，但是我只是不停重试这个命令，就正常通过了。还有其实不用翻墙，只需要更换sources.list就行了

**Comment by carveybunt** [comment]
大佬，您是怎么解决的呀？我现在也是这个问题。而且我还设置了.env的CHANGE_SOURCE=true。

**Comment by HiWilliam** [comment]
我这两天也在这这个，你可以尝试在php-fpm下添加一个sources. list文件，内容是国内的ubuntu镜像源,然后copy替换原有/etc/apt/sources.list，再试试看。可能好一点。


---原始邮件---
发件人: "carveybunt"<notifications@github.com&gt;
发送时间: 2019年11月24日(星期日) 晚上10:40
收件人: "laradock/laradock"<laradock@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"WuHao"<1216252072@qq.com&gt;;
主题: Re: [laradock/laradock] 执行到apt-get update -yqq这一步时报错了 (#2368)



大佬，您是怎么解决的呀？我现在也是这个问题。而且我还设置了.env的CHANGE_SOURCE=true。

**Comment by carveybunt** [comment]
@HiWilliam 多谢，我试试。

**Comment by carveybunt** [comment]
@HiWilliam 大佬，怎么查看laradock用的是哪个版本的ubuntu镜像呀？搞了几天了都还没搞定，懵了。

**Comment by HiWilliam** [comment]
> @HiWilliam 大佬，怎么查看laradock用的是哪个版本的ubuntu镜像呀？搞了几天了都还没搞定，懵了。
应该是16.04lts

**Comment by carveybunt** [comment]
@HiWilliam 多谢，好像是有命令可以查看的，是吗？

**Comment by HiWilliam** [comment]
> @HiWilliam 多谢，好像是有命令可以查看的，是吗？
我是在容器里面看的  lsb_release -a

**Comment by carveybunt** [comment]
@HiWilliam 多谢。

**Comment by amorZhu** [comment]
#2388 按照这个提交自己处理一下，看后期会不会合并
