### ISSUE TITLE
Run Two Laradock in one Host

### ISSUE THREAD

**Issue by KarmitoHerry** [laradock/laradock#2369]
### Info:
- Docker version (`$ docker --version`): 19.03.1
- System info (Mac, PC, Linux): Linux  
- System info Nginx version : 1.14.3

### Issue:
I'm new on docker , i have issue when i try to run 2 laradock in one host.
with the schema of my setting :
```
+ project A
  + laradock
+project B 
  +laradock
```
reporduce :
1.  on project A , execute this command 
```
docker-compose up -d php-fpm
```
2.  run ```docker-compose ps``` on project A , and i got this information
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
f18bd93e911a        projectA_php-fpm         "docker-php-entrypoi…"   13 minutes ago      Up 13 minutes       127.0.0.1:9000->9000/tcp             projectA_php-fpm_1
5fdb67b97a16        projectA_workspace       "/sbin/my_init"          14 minutes ago      Up 13 minutes       0.0.0.0:2222->22/tcp                 projectA_workspace_1
ef8195da6791        docker:dind              "dockerd-entrypoint.…"   14 minutes ago      Up 14 minutes       2375/tcp                             projectA_docker-in-docker_1
```
3. And i test access project A , and the UI show up
4. on project B , execute this command 
```
docker-compose up -d php-fpm
```
5. run ```docker-compose ps``` on project B , and i got this information
```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                NAMES
9609f23b5551       projectB_php-fpm      "docker-php-entrypoi…"   4 hours ago         Up 4 hours          9000/tcp, 127.0.0.1:9001->9001/tcp   projectB_php-fpm_1
b1cdbcc8a762        projectB_workspace   "/sbin/my_init"          4 hours ago         Up 4 hours          0.0.0.0:2223->23/tcp                 projectB_workspace_1
fd29bbdcb13f        docker:dind          "dockerd-entrypoint.…"   4 hours ago         Up 4 hours          2375-2376/tcp                        projectB_docker-in-docker_1
```

> Project A and B , setting with different port on ```docker-compose.yml```

6. And i test access project B , and on the web browser show up **502 Bad Gateway**

If I try another approach , with project A using same setting on project B : ```.env``` and ```docker-compose.yml```. When i build project A and turn off project B, i can access project A webapp. Otherwise when i turn off project A and build project B , i can access project B webapp. But I cannot run 2 laradock with same host.

so my question is it possible to running multiple laradock with only using 1 host?

**Comment by lanphan** [comment]
Hi @KarmitoHerry ,
Can you tell me how do you deal with Nginx container?

**Comment by KarmitoHerry** [comment]
> Hi @KarmitoHerry ,
> Can you tell me how do you deal with Nginx container?

Hi @lanphan 
on my project architecture , i using google cloud platform.

Flow of architecture 
```
Subdomain >> Load Balancer >> Nginx >> folder (sites-avaiable) >> (var/www/)>> Project A and Project B
```
Detail :
1. set subdomain for project A (test-projectA.laradock.com) and B (test-projectB.laradock.com) using 10.10.0.1 (dummy IP Public for illustration) 
2. On GCP Load Balancing , I already set with 10.10.0.1 Public using Port 80 and Port 443. And I registered my subdomain for the path list : test-projectA.laradock.com and test-projectB.laradock.com
3. On My NGINX , for sites-avaiable test-projectA.laradock.com
```
# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
server {

	server_name projectA.laradock.com;

        access_log /var/log/nginx/projectA.log;
        error_log /var/log/nginx/projectA.log;

	root /var/www/projectA/public/;
	index index.php index.html;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

        location ~ \.php {
	    include snippets/fastcgi-php.conf;
	    fastcgi_param SCRIPT_FILENAME $request_filename;
		#fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html$fastcgi_script_name;
		fastcgi_pass 127.0.0.1:9000;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot 
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
        if ($http_x_forwarded_proto = "http") { 
          return 301 https://$host$request_uri; 
        }

        access_log /var/log/nginx/projectA.log;
        error_log /var/log/nginx/projectA.log;

        root /var/www/projectA/public/;
        index index.php index.html;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php {
            include snippets/fastcgi-php.conf;
            fastcgi_param SCRIPT_FILENAME $request_filename;
		#fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html$fastcgi_script_name;
            fastcgi_pass 127.0.0.1:9000;
        }

	listen 80;
	listen [::]:80;

	server_name projectA.laradock.com;
}
```

and i try another new approach to prove my hypothesis. **Only project A** , i build it:
1. I try to Change on```docker-compose.yml```
```
php-fpm  ports from 127.0.0.1:9000:9000 to 127.0.0.1:9001:9001
```
2. on ```.env``` , i change
```
WORKSPACE_SSH_PORT = 2222 to 2233
```
3. my site-avaiable/projectA re-configure using point 1 setting
4. and i got 502 - Bad Gateway again

I try to search on stack-overflow or laradock issue. no one try 2 laradock in 1 host 😄.

maybe all my explanation can give you more clue and insight , which part can re-set it for another approach.

**Comment by lanphan** [comment]
Hi @KarmitoHerry ,
In case you want to run multiple PHP projects with Laradock, you can do it with 1 Laradock, no need to have 2 Laradock on your host.

Check document here: https://laradock.io/#B

**Comment by KarmitoHerry** [comment]
Hi @lanphan ,
Thx for your information.
I switch my architecture using 1 laradock multiple project.

If laradock can provide architecture using multiple laradock engine on host , that can be save more cost on production side 😄
