### ISSUE TITLE
Find the php.exe

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2374]
Hello My friend .  I am tring to find the php.exe file to use in studio code like this -

https://stackoverflow.com/questions/40287927/php-executable-not-found-install-php-7-and-add-it-to-your-path-or-set-the-php-e

{
    "php.validate.executablePath": "C:\\wamp64\\bin\\php\\php7.0.4\\php.exe",
    "php.executablePath": "C:\\wamp64\\bin\\php\\php7.0.4\\php.exe"
}

Do you know where can I find this file in laradock ?

**Comment by alec-joy** [comment]
Laradock uses docker, so you can't directly access the php file from windows. My suggestion would be to install the [Remote Development pack](https://code.visualstudio.com/docs/remote/remote-overview) and use it to attach to your running workspace container. That's what I do at least.
