### ISSUE TITLE
WIN10  和CENTOS7 下报错，求大佬指点。

### ISSUE THREAD

**Issue by carveybunt** [laradock/laradock#2385]
+ apt-get update -yqq
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is not valid yet (invalid for another 5h 25min 18s). Updates for this repository will not be applied.
Service 'php-fpm' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip &&       docker-php-ext-configure zip --with-libzip &&       docker-php-ext-install zip &&       php -m | grep -q 'zip'' returned a non-zero code: 100

该如何设置，才能快速构建 nginx redis php-fpm workspace容器呢？
求大佬指点，百度了2天都没解决。
.env已经设置了
# If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
CHANGE_SOURCE=true

**Comment by yehuifang** [comment]
解决了没有啊，我也有这个问题

**Comment by carveybunt** [comment]
@yehuifang 没有呢，百度几天都没搞定，按照Issues里面的办法也没能搞定。还是报错。

**Comment by amorZhu** [comment]
#2388 看这个，我已解决，等待合并

**Comment by HiWilliam** [comment]
> @yehuifang 没有呢，百度几天都没搞定，按照Issues里面的办法也没能搞定。还是报错。

墙的问题，尝试替换php-fpm和workspace中的镜像源，这个你试试https://learnku.com/articles/26066。不保证成功。替换后出错基本就是pecl安装php扩展失败。但是有时重复几次就会成功【看脸】。

**Comment by amorZhu** [comment]
[解决 Laradock 拉取镜像并创建容器时非常慢的问题](https://segmentfault.com/a/1190000021076776#shareToWeibo)

**Comment by carveybunt** [comment]
> > @yehuifang 没有呢，百度几天都没搞定，按照Issues里面的办法也没能搞定。还是报错。
> 
> 墙的问题，尝试替换php-fpm和workspace中的镜像源，这个你试试[https://learnku.com/articles/26066。不保证成功。替换后出错基本就是pecl安装php扩展失败。但是有时重复几次就会成功【看脸】。](https://learnku.com/articles/26066%E3%80%82%E4%B8%8D%E4%BF%9D%E8%AF%81%E6%88%90%E5%8A%9F%E3%80%82%E6%9B%BF%E6%8D%A2%E5%90%8E%E5%87%BA%E9%94%99%E5%9F%BA%E6%9C%AC%E5%B0%B1%E6%98%AFpecl%E5%AE%89%E8%A3%85php%E6%89%A9%E5%B1%95%E5%A4%B1%E8%B4%A5%E3%80%82%E4%BD%86%E6%98%AF%E6%9C%89%E6%97%B6%E9%87%8D%E5%A4%8D%E5%87%A0%E6%AC%A1%E5%B0%B1%E4%BC%9A%E6%88%90%E5%8A%9F%E3%80%90%E7%9C%8B%E8%84%B8%E3%80%91%E3%80%82)

多谢，不过我在前天已经解决了。

**Comment by carveybunt** [comment]
> [解决 Laradock 拉取镜像并创建容器时非常慢的问题](https://segmentfault.com/a/1190000021076776#shareToWeibo)

多谢，不过我在前天已经解决了。
