### ISSUE TITLE
ERROR: Service 'workspace' failed to build: mounting shm tmpfs: invalid argument

### ISSUE THREAD

**Issue by elceka** [LaraDock/laradock#239]
I have this error when I run command `docker-compose up --build -d nginx postgres`.

**Comment by Mahmoudz** [comment]
@elceka have you been able to solve this!?

**Comment by elceka** [comment]
@Mahmoudz I don't know, i don't using it now. But now, i've pull actual master to my environment and command `docker-compose up --build -d nginx postgres` works for me without any error.
