### ISSUE TITLE
nginx listen on specific ip

### ISSUE THREAD

**Issue by 0xbadc0de** [laradock/laradock#2391]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.1, build 4c52b90
- Laradock commit (`$ git rev-parse HEAD`): 50b6272ffffd0f75b6b8af81d842542c96dc8182
- System info (Mac, PC, Linux): Linux
- System info disto/version: Debian 10

### Issue:
Hello! I'm using laradock to server several projects. Each project should listen on their own ip (192.168.1.101, 192.168.1.102, 192.168.1...). Currently nginx container listening on all ip addresses. How i can make what i want? Port forward on the host? All configs are default. Thanks!

**Comment by metalcamp** [comment]
Look at this: https://serverok.in/configure-nginx-to-listen-on-single-ip-address

I presume you're using it on development machine. Why don't you just use domain names like project1.local, project2.local in nginx config and add those entries to hosts file?
