### ISSUE TITLE
Cannot declare class

### ISSUE THREAD

**Issue by 0xbadc0de** [laradock/laradock#2392]
### Info:
- Docker version (`$ docker --version`): 18.09.1, build 4c52b90
- Laradock commit (`$ git rev-parse HEAD`): 50b6272ffffd0f75b6b8af81d842542c96dc8182
- System info (Mac, PC, Linux): Linux
- System info disto/version: Debian 10

### Issue:
I have several installations of XenForo (different projects). All have exact same version and own databases. But there are an issue with php. If i restart php-fpm and then go to forum #1 it works but then forums #2 and #3 not works. Again if i restart php-fpm and then go to forum #2 (for example) it works but then forums #1 and #3 not works.

PHP log gives an error:

    Cannot declare class "CLASS_NAME" because the name is already in use

**Comment by shov** [comment]
@0xbadc0de I got that the projects are different, but what about `DATA_PATH_HOST` in `.env` files?

**Comment by 0xbadc0de** [comment]
Issue resolved by disabling PHP OPcache
