### ISSUE TITLE
Docker quick scripts

### ISSUE THREAD

**Issue by iannazzi** [LaraDock/laradock#24]
I use script.sh to get the shell quickly connected to the docker daemon, with the exception that you need to copy and paste `eval "$(docker-machine env default)"` as the shell script will not execute for some reason. I am sure someone will know. This allows me to bypass the quickstart terminal.
```
#!/usr/bin/env bash
docker-machine start default
docker-machine ip default
docker-machine env default
# this is not working: eval "$(docker-machine env default)"
```

Additionally I use `remove_containers.sh` which comes in handy when you mess up repeatedly. Also connection to container scrips like `php.sh`, `mysql.sh` as I can't ever remember the commands.

Would these be a good fit for this repository? I know I use them and love them. I think I found them on stackoverflow.

By the way awesome job, this is the only setup that got a development machine running!

**Comment by Mahmoudz** [comment]
Hi @iannazzi first thank you for your interest in this project. It's interesting and I can imagine how useful these commands are. Right now I'm trying to educate people about Docker and making them familiar with the commands. However I have plans to make this package function in a different way where these commands could be used. Meanwhile I'm gonna keep it clear for the users what they are doing in each step. Thanks again.
