### ISSUE TITLE
docker-compose up ... on production or just in development environment?

### ISSUE THREAD

**Issue by carraroenrico** [LaraDock/laradock#240]
Hi, I'm totally new to the docker world and probably I will write some stupid things in this question, so please be patient with me 👏 . 
I've seen some examples of docker repositories, but they all have one container (at least the one I saw), so, since Laradock has multiple containers, how do I push to my repo the set of containers that I have in my development environment? Or this is not the case and I should do `docker-compose up -d nginx mariadb` also on the production server?
Please help me, I'm confused.

**Comment by Mahmoudz** [comment]
Hi, running `docker-compose up -d nginx mariadb` is fine. An alternative method would be to delete all the other containers folders (everything that doesn't show up in the `docker-compose ps` after running your software) and then removing all the deleted containers from the `docker-compose.yml` file. After that you should be able to only run `docker-compose up` to get only the software's that you need. Note: you may only delete them from `docker-compose.yml` to be able to use `docker-compose up` but would be cleaner if you also remove the unused folders.
