### ISSUE TITLE
database  lose

### ISSUE THREAD

**Issue by HiWilliam** [laradock/laradock#2403]
### Info:
- Docker version (`$ docker --version`): Docker version 19.03.5, build 633a0ea
- Laradock commit (`$ git rev-parse HEAD`): c3620e95c8c6174f07c593e7fee3c7a6b2bdc1d7
- System info (Mac, PC, Linux): pc
- System info disto/version: 1909

### Issue:
when the containers quit Abnormally, mysql  databases those i created will lose or deleted.
and i cant find the data in user/.laradock/data/mysql
_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by bestlong** [comment]
need `diff .env env-example` result

**Comment by HiWilliam** [comment]
i copy the env-example, and made following change
APP_CODE_PATH_HOST=../wwwroot
PHP_VERSION=7.2
WORKSPACE_INSTALL_XDEBUG=true
PHP_FPM_INSTALL_XDEBUG=true
MYSQL_VERSION=5.7
