### ISSUE TITLE
Issue with php-worker not installing with PHP 7.4 set in env file

### ISSUE THREAD

**Issue by aj-norman** [laradock/laradock#2414]
### Info:
- Docker version (`$ docker --version`): 19.03.03
- Laradock commit (`$ git rev-parse HEAD`): Unknown
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04.03 LTS

### Issue:
When building php-worker with php 7.4 with the recent update to the Laradock master branch, php-worker fails to build as package "oniguruma" is missing.
_____

### Expected behavior:
PHP worker should build correctly
_____

### Reproduce:
Using a fresh laradock setup, build the php-worker container with php 7.4 set in the .env file
_____

I have found a solution to this, might be temporary for now, but in php-worker/Dockerfile, starting line 20, add "oniguruma-dev" to the list of needed packages, I've tried just using "oniguruma" but it doesn't seem to install. I've attached an image of my edit
 in order to build the container

<img width="1280" alt="Screenshot 2019-12-07 at 20 07 50" src="https://user-images.githubusercontent.com/31593647/70380058-4af4c780-192d-11ea-8958-2a20837e5503.png">

**Comment by ErnestStaug** [comment]
`oniguruma-dev` worked fine for me :/

**Comment by alirezamaleky** [comment]
when i run laradock by php7.4, will recive below error:

configure: error: Package requirements (oniguruma) were not met:

Package 'oniguruma', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
ERROR: Service 'php-worker' failed to build: The command '/bin/sh -c docker-php-ext-install mysqli mbstring pdo pdo_mysql tokenizer xml pcntl' returned a non-zero code: 1
ERROR: No container found for workspace_1
[root@dmon dmon]# docker-compose down
