### ISSUE TITLE
Laradock: nginx exit 1, mysql exit 2, and unable to connect to sequel pro using default root username and password on local 127.0.0.1 quick connect

### ISSUE THREAD

**Issue by FrontEndEnthusiast2019** [laradock/laradock#2415]
### Info:
**Docker version:** Docker version 19.03.5, build 633a0ea 
**Laradock commit:** (`$ git rev-parse HEAD`): **???**
**System info:** MacBook pro 13inch 2019
**macOS:** Mojave 10.14.5
**Upon request, will i supply relevant information of subject**: YES

### Issue:
**What seems to be wrong?** New laradock installation and configuration on new macBook Pro computer, can not quick connect to sequel pro via 127.0.0.1, default root and password supplied by laradock. 

laradock shows after what has to been believed as the correct way of installing as following the laradock.io resource.

**nginx exits at 1**, and **mysql exit at 2** after **docker-compose up command** used, but gives the impression that every container is installed, config'd, and working correctly, though nginx and mysql seem to be missing - note that redis, workspace, and php-fpm work fine and as they should upon using the docker-compose up command.

All help will be greatly appreciated.
_____

### Expected behavior:
**What should happen instead?** it is believed that once you docker-compose up -d {container-name} all should work without any issues, and allow you to connect to database application via default 127.0.0.1 / localhost connection, also believed that once you docker-compose stop all containers should become offline and show through docker-compose ps as such, though redis, workspace, and php-fpm do, nginx and mysql do not.
_____

### Reproduce:
**How can we reproduce the error?** try installing a new laradock on new macBook pro with the system info above, and following the laradock resource guides/information, i may be missing the trick somewhere potentially.
_____

### Relevant Code:

```
**Action one**
docker --version
Docker version 19.03.5, build 633a0ea

**Action two**
docker-compose up -d nginx mysql redis workspace
laradock_docker-in-docker_1 is up-to-date
laradock_redis_1 is up-to-date
Starting laradock_mysql_1 ...
laradock_workspace_1 is up-to-date
**Starting laradock_mysql_1 ... done**
**Starting laradock_nginx_1 ... done**

**Action three**
docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
eabca3a84e27        laradock_php-fpm     "docker-php-entrypoi…"   59 minutes ago      Up 14 minutes       9000/tcp                 laradock_php-fpm_1
1ec12d23a6ba        laradock_workspace   "/sbin/my_init"          59 minutes ago      Up 14 minutes       0.0.0.0:2222->22/tcp     laradock_workspace_1
e6e4f63d875a        laradock_redis       "docker-entrypoint.s…"   59 minutes ago      Up 14 minutes       0.0.0.0:6379->6379/tcp   laradock_redis_1
edca2ff83e7a        docker:dind          "dockerd-entrypoint.…"   59 minutes ago      Up 14 minutes       2375-2376/tcp            laradock_docker-in-docker_1

**Action four**
docker-compose ps
           Name                          Command               State            Ports
----------------------------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh            Up       2375/tcp, 2376/tcp
**laradock_mysql_1              docker-entrypoint.sh mysqld      Exit 2**
**laradock_nginx_1              /bin/bash /opt/startup.sh        Exit 1**
laradock_php-fpm_1            docker-php-entrypoint php-fpm    Up       9000/tcp
laradock_redis_1              docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp
laradock_workspace_1          /sbin/my_init                    Up       0.0.0.0:2222->22/tcp

**Action five**
docker volume list
DRIVER              VOLUME NAME
local               laradock_adminer
local               laradock_aerospike
local               laradock_caddy
local               laradock_cassandra
local               laradock_confluence
local               laradock_dind
local               laradock_elasticsearch
local               laradock_graylog
local               laradock_mariadb
local               laradock_memcached
local               laradock_minio
local               laradock_mongo
local               laradock_mosquitto
local               laradock_mssql
local               laradock_mysql
local               laradock_neo4j
local               laradock_percona
local               laradock_phpmyadmin
local               laradock_postgres
local               laradock_redis
local               laradock_rethinkdb
local               laradock_sonarqube

**Action six**
docker-compose stop
Stopping laradock_php-fpm_1          ... done
Stopping laradock_workspace_1        ... done
Stopping laradock_redis_1            ... done
Stopping laradock_docker-in-docker_1 ... done

**Action seven**
docker-compose ps
           Name                          Command               State    Ports
-----------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh            Exit 0
**laradock_mysql_1              docker-entrypoint.sh mysqld      Exit 2**
**laradock_nginx_1              /bin/bash /opt/startup.sh        Exit 1**
laradock_php-fpm_1            docker-php-entrypoint php-fpm    Exit 0
laradock_redis_1              docker-entrypoint.sh redis ...   Exit 0
laradock_workspace_1          /sbin/my_init                    Exit 0
```

**Comment by bestlong** [comment]
use `docker-compose logs nginx` to check nginx log

**Comment by FrontEndEnthusiast2019** [comment]
@bestlong thank you for taking the time in helping me out with this issue, an update is required of resolvent progression, the nginx with it interesting exit 1 issue, i have managed to solve, turns out it was a silly semi-colon ( ; ) placed within the laradock->nginx->sites->*.conf file, to this interrupting the nginx server listening for port 80 (self reminder always check your semi-colons, post of commenting within any file), the mysql i believe was related to some data being cached remaining from uninstallation of laradock prior to its reinstallation, so with this i uninstalled laradock fully and also removed the .laradock folder, and then reinstalled the entire laradock environment.

Though the connection to the sequel pro application via 127.0.0.1 is still remaining a problem and a mystery, with this issue it presents with the following;

**Access denied**
Unable to connect to host 127.0.0.1 because access was denied.

Double-check your username and password and ensure that access from your current location is permitted.

MySQL said: Access denied for user 'root'@'172.19.0.1' (using password: YES)

Do you have any ideals to why this might be or how to resolve this?
