### ISSUE TITLE
ccertbot can't start up

### ISSUE THREAD

**Issue by liminworks** [laradock/laradock#2417]
Info:

Docker version ($ docker --version):
Docker version 18.06.1-ce, build e68fc7a

Laradock commit ($ git rev-parse HEAD):
83a24ef

System info (Mac, PC, Linux):
Linux

System info disto/version:
Ubuntu 18.04.1 LTS

Issue:

Certbot exited with code 1

vagrant@bogon:/www/web/laradock(master⚡) » docker-compose up certbot
WARNING: The WORKSPACE_INSTALL_IONCUBE variable is not set. Defaulting to a blank string.
WARNING: The PHP_FPM_INSTALL_IONCUBE variable is not set. Defaulting to a blank string.
Starting laradock_certbot_1 ... done
Attaching to laradock_certbot_1
certbot_1 | /root/certbot/run-certbot.sh: line 2: $'\r': command not found
certbot_1 | usage:
certbot_1 | certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
certbot_1 |
certbot_1 | Certbot can obtain and install HTTPS/TLS/SSL certificates. By default,
certbot_1 | it will attempt to use a webserver both for obtaining and installing the
certbot_1 | certificate.
certbot_1 | certbot: error: unrecognized arguments: --text
certbot_1 | /root/certbot/run-certbot.sh: line 4: $'\r': command not found
certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/laravel.test/cert1.pem': No such file or directory
certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/laravel.test/privkey1.pem': No such file or directory
laradock_certbot_1 exited with code 1

Relevant Code:

mk@mkubus-Vostro-5568:~/workspace/laradock$ cat docker-compose.yml |grep -i certbot -A 5

Certbot

certbot:
  build:
    context: ./certbot
  volumes:
    - ./data/certbot/certs/:/var/certs
    - ./certbot/letsencrypt/:/var/www/letsencrypt
  environment:
    - CN=mydomain.pl
    - EMAIL=my.email@gmail.com
  networks:
    - frontend

nginx:
build:
context: ./nginx
args:
- PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
- PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
volumes:
- ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
- ${NGINX_HOST_LOG_PATH}:/var/log/nginx
- ${NGINX_SITES_PATH}:/etc/nginx/sites-available
- ./data/certbot/certs/:/var/certs
- ./certbot/letsencrypt/:/var/www/letsencrypt
ports:
- "${NGINX_HOST_HTTP_PORT}:80"
- "${NGINX_HOST_HTTPS_PORT}:443"
depends_on:
- php-fpm
networks:
- frontend
- backend

**Comment by pbebbo** [comment]
Why was this closed Im also getting this issue?

**Comment by moreishi** [comment]
I'm getting this issue as well. Any solution?

**Comment by lucassmacedo** [comment]
Hello
i have a problem with LaraDock + CertBot
certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/app.test/cert1.pem': No such file or directory
certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/app.test/privkey1.pem': No such file or directory
any knows how to fix this?

**Comment by Simoon-F** [comment]
had the same problem。
