### ISSUE TITLE
php-fpm 502 Bad Gateway after building version 2.6.1-7.3

### ISSUE THREAD

**Issue by andreladocruz** [laradock/laradock#2419]
### Info:
- Docker version (`$ docker --version`): Docker version 19.03.5, build 633a0ea
- Laradock commit (`$ git rev-parse HEAD`): 9de14a6deab358111dcafeeace7f38b46160baf8
- System info (Mac, PC, Linux): Windows 10
- System info disto/version: 

### Issue:
Error while login into laravel application.

With version 2.4-7.3 it worked. (this version is no longer in docker hub. why?)
_____

### Expected behavior:
Log in correctly
_____

### Reproduce:
We have GRPC and Protobuf extensions configured
_____

#########################################################################
# PHP PROTOBUF EXTENSION - Workspace
#########################################################################

ARG INSTALL_PHPPROTOBUF=false

RUN if [ ${INSTALL_PHPPROTOBUF} = true ]; then \
    pecl install protobuf \
    && echo "extension=protobuf.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/protobuf.ini \
    && ln -s /etc/php/${LARADOCK_PHP_VERSION}/mods-available/protobuf.ini /etc/php/${LARADOCK_PHP_VERSION}/cli/conf.d/20-protobuf.ini \
    && php -m | grep -q 'protobuf' \
    ;fi

##########################################################################
# PHP PROTOBUF EXTENSION - php-fpm
##########################################################################

ARG INSTALL_PHPPROTOBUF=false

RUN if [ ${INSTALL_PHPPROTOBUF} = true ]; then \
    printf "\n" | pecl install -o -f protobuf \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable protobuf \ 
    ;fi

```
// place a code sample here
```

**Comment by andreladocruz** [comment]
just got back version 7.15 and saw that the container used is 

# letsdockerize/laradock-php-fpm:2.4-${LARADOCK_PHP_VERSION} #

The latest version of laradock uses 

# laradock/php-fpm:2.6.1-${LARADOCK_PHP_VERSION} #

Obviously, there are some differences that make it do not work. :(

**Comment by bestlong** [comment]
after change version suggest run `docker-compose build --no-cache php-fpm` first.

**Comment by bestlong** [comment]
need php-fpm:2.4-7.3 ?
i will try recreate

**Comment by bestlong** [comment]
> just got back version 7.15 and saw that the container used is
> 
> # letsdockerize/laradock-php-fpm:2.4-${LARADOCK_PHP_VERSION}
> The latest version of laradock uses
> 
> # laradock/php-fpm:2.6.1-${LARADOCK_PHP_VERSION}
> Obviously, there are some differences that make it do not work. :(

yes, Ref #2004

**Comment by andreladocruz** [comment]
Found the issue at protobuf 3.11.* extension. Went back to version 3.10.0 and it's working
