### ISSUE TITLE
PHP 7.4 ZIP extension option  --enable-zip was removed

### ISSUE THREAD

**Issue by ErnestStaug** [laradock/laradock#2421]
### Info:
- Docker version (`$ docker --version`):  19.03.5, build 633a0ea
- Laradock commit (`$ git rev-parse HEAD`): fb617de
- System info (Mac, PC, Linux): Mac
- System info disto/version: 

### Issue:
PHP 7.4 Zip extension no longer supports `--enable-zip` option it, all builds fail if zip extension is enabled.
_____

### Expected behavior:
Builds should pass
_____

### Reproduce:
Change PHP version to 7.4 and enable zip extensions in .env file
_____

### Relevant Code:

```
      # next lines are here becase there is no auto build on dockerhub see https://github.com/laradock/laradock/pull/1903#issuecomment-463142846
      libzip-dev zip unzip && \
      docker-php-ext-configure zip --with-libzip && \
      # Install the zip extension
      docker-php-ext-install zip && \
      php -m | grep -q 'zip'
```

**Comment by hackel** [comment]
The solution is as simple as removing the `docker-php-ext-configure zip --with-libzip` line entirely for PHP >= 7.4.  Defaults are sufficient.

**Comment by MartinCN** [comment]
`For PHP < 7.3

#install some base extensions
RUN apt-get install -y \
        libzip-dev \
        zip \
  && docker-php-ext-configure zip --with-libzip \
  && docker-php-ext-install zip
For PHP >= 7.3

#install some base extensions
RUN apt-get install -y \
        libzip-dev \
        zip \
  && docker-php-ext-install zip`
https://stackoverflow.com/questions/48700453/docker-image-build-with-php-zip-extension-shows-bundled-libzip-is-deprecated-w/48700777#48700777

**Comment by daryledesilva** [comment]
> The solution is as simple as removing the `docker-php-ext-configure zip --with-libzip` line entirely for PHP >= 7.4. Defaults are sufficient.

worked for me, had to edit `php-fpm\Dockerfile`. thanks!

**Comment by glorand** [comment]
@bestlong same issue on php - worker (php v7.4 with PHP_WORKER_INSTALL_ZIP_ARCHIVE=true

**Comment by ErnestStaug** [comment]
We should unify all php settings/extensions (including php.ini) across all containers

**Comment by mrwilbroad** [comment]
nothing work for me, on window **PHP 8.2.1**
