### ISSUE TITLE
Setup of a cloned project that uses laradock

### ISSUE THREAD

**Issue by mg98** [laradock/laradock#2423]
This might be a very noobie question.

I have a project setup with laradock that I uploaded to github. From another computer I cloned the repository. I get the laradock repository and it is empty. I understand that this is a good thing. But how do I get its contents now? There must be a command or something but I can't find it in the guides.

Thank you.

**Comment by JeroenBoesten** [comment]
Assuming you added it to the github project as a submodule u can run; `git submodule update --init
`

**Comment by mg98** [comment]
Thanks, I have never worked with git submodules before, so that command was exactly what I was looking for!
