### ISSUE TITLE
windows下配置env中APP_CODE_PATH_HOST后，并没有把本地的路径挂载到/var/www/目录下，请问是什么原因呢？

### ISSUE THREAD

**Issue by qingk3038** [laradock/laradock#2428]
windows下配置env中APP_CODE_PATH_HOST后，并没有把本地的路径挂载到/var/www/目录下，请问是什么原因呢？
通过workspace进入后查看/var/www/目录，并没有什么东西，我本地的路径是有文件的，应该是没挂载上。

**Comment by zealerFT** [comment]
# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=../www/

# Point to where the `APP_CODE_PATH_HOST` should be in the container. You may add flags to the path `:cached`, `:delegated`. When using Docker Sync add `:nocopy`
APP_CODE_PATH_CONTAINER=/var/www:cached

这两个地址弄对
