### ISSUE TITLE
In Aliyun Installtion of Jenkins is so slow

### ISSUE THREAD

**Issue by harrisdt15f** [laradock/laradock#2441]
### Info:
- Docker version (`$ docker --version`): 19.03.5, build 633a0ea
- Laradock commit (`$ git rev-parse HEAD`): 8203e5da2992db2e242a6dd9733f12f5c664842e
- System info (Mac, PC, Linux): Linux centos
- System info disto/version: 

### Issue:
Install Jenkins on Aliyun so slow only in byte package installtion please help to add support for changing source or somethings better. Thanks
_____

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by 520** [comment]
Fuck GFW!! FUCK. Wasting my most of time on that shit. Fuck

**Comment by harrisdt15f** [comment]
please not close until it solve.
