### ISSUE TITLE
supervisor in workspace not starting up

### ISSUE THREAD

**Issue by sohaibilyas** [laradock/laradock#2442]
### Info:
- Docker version (`$ docker --version`): version 18.09.7, build 2d0083d
- Laradock commit (`$ git rev-parse HEAD`): 11c59aebe7d5b316f5c5b8fdfe38849d2b248700
- System info (Mac, PC, Linux): Linux
- System info disto/version: 18.04.1-Ubuntu

### Issue:
I followed steps mentioned here https://laradock.io/documentation/#install-supervisor to install supervisor inside workspace service, after successful build and run, it seems like its not picking up conf files from /php-worker/supervisord.d/

Note: If I run a separate php-worker service it works fine but then it doesnt create/save files so i thought lets setup supervisor in workspace itself.
_____

### Expected behavior:
As soon as we run workspace service it should start up the supervisor with all conf files in /php-worker/supervisord.d/ as mentioned at https://laradock.io/documentation/#install-supervisor
_____

### Reproduce:
Fresh copy of laradock, follow steps here https://laradock.io/documentation/#install-supervisor and run any worker to test it.
_____

### Relevant Code:
worker.conf
```
[program:gearman-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/public/gearman/index.php
autostart=true
autorestart=true
numprocs=3
user=laradock
redirect_stderr=true
```

**Comment by Zerosez** [comment]
Hello, this is my first ever comment on this answer machine. 
So first, I want you to [G]oogle [E]very [A]ugmented [R]eality within that software.
And then man.index-php

So second, when you mirror an index it doesn't appear as far away as that galaxy is rendered.
PS: I never learned any code, I'm your biggest fan.
Zero

**Comment by rlustemberg** [comment]
I can confirm to have same issue

**Comment by theyudhiztira** [comment]
I'm having same thing here
