### ISSUE TITLE
Unable to connect to mssql server

### ISSUE THREAD

**Issue by avifatal** [laradock/laradock#2446]
### Info:
- Docker version  19.03.5, build 633a0ea
- Laradock commit 8203e5da2992db2e242a6dd9733f12f5c664842e
- System info  PC: 
- System info disto/version:  10 pro

### Issue:
```
PDOException::("SQLSTATE[28000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'sa'.")
```
_____

### Relevant Code:
this is the laradock config:
```
ADM_INSTALL_MSSQL=true
WORKSPACE_INSTALL_MSSQL=true
PHP_FPM_INSTALL_MSSQL=true
....
MSSQL_DATABASE=master
MSSQL_PASSWORD=RTGDFER453edrr4!!!
MSSQL_PORT=1433
```
this is that laravel config 
```
DB_CONNECTION=sqlsrv
DB_HOST=mssql
DB_PORT=1433
DB_DATABASE=master
DB_USERNAME=sa
DB_PASSWORD=RTGDFER453edrr4!!!
````
I can see that the password is read correctly because I see in the error:
```  PDO::__construct("sqlsrv:Server=mssql,1433;Database=master", "sa", "RTGDFER453edrr4!!!", [])```

this is how I run my app: 
``` docker-compose up nginx mssql workspace```
_____
I am mentioning that I have temporarly changed the mssql docker image from `mcr.microsoft.com/mssql/server:2017-latest-ubuntu` to `mcr.microsoft.com/mssql/server:2017-CU11-ubuntu`

What am I doing wrong?

Thanks

**Comment by harrisdt15f** [comment]
I also got same problem.

**Comment by dgbrown** [comment]
Hi, late to the party but I hope this other thread and my comment there might help you: https://github.com/laradock/laradock/issues/2462#issuecomment-605516886
