### ISSUE TITLE
win10构建workspace时，报错提示/tmp/sources.sh: not found

### ISSUE THREAD

**Issue by carveybunt** [laradock/laradock#2450]
### laradock版本:
_____
拉取的最新分支。
### 报错内容如下:
_____
Step 7/249 : RUN if [ ${CHANGE_SOURCE} = true ]; then     sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list ;fi
 ---> Using cache
 ---> 6e42a47d400c
Step 8/249 : USER root
 ---> Using cache
 ---> fa0c6e890ce6
Step 9/249 : ARG PUID=1000
 ---> Using cache
 ---> f57da5f6a81d
Step 10/249 : ENV PUID ${PUID}
 ---> Using cache
 ---> 6eaae0c47cac
Step 11/249 : ARG PGID=1000
 ---> Using cache
 ---> fd2804be9b14
Step 12/249 : ENV PGID ${PGID}
 ---> Using cache
 ---> d759de373b28
Step 13/249 : ARG CHANGE_SOURCE=false
 ---> Using cache
 ---> 79dc3fc1a2b9
Step 14/249 : ARG UBUNTU_SOURCE
 ---> Using cache
 ---> 81d82c3e5c6a
Step 15/249 : COPY ./sources.sh /tmp/sources.sh
 ---> Using cache
 ---> 2461ea25055f
Step 16/249 : RUN if [ ${CHANGE_SOURCE} = true ]; then     /bin/sh -c /tmp/sources.sh &&     rm -rf /tmp/sources.sh ;fi
 ---> Running in 71c8f81ece52
/bin/sh: 1: /tmp/sources.sh: not found
Service 'workspace' failed to build: The command '/bin/sh -c if [ ${CHANGE_SOURCE} = true ]; then     /bin/sh -c /tmp/sources.sh &&     rm -rf /tmp/sources.sh ;fi' returned a non-zero code: 127

### 在laradock/workspcae目录下，确定存在sources.sh:
_____
![image](https://user-images.githubusercontent.com/37894474/71538324-f6f56580-2963-11ea-8ee1-8b5d9d1e0f4f.png)

### workspace\Dockerfilee对应的代码:

```
ARG LARADOCK_PHP_VERSION

FROM laradock/workspace:2.6.1-${LARADOCK_PHP_VERSION}

LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"

ARG LARADOCK_PHP_VERSION

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

# If you're in China, or you need to change sources, will be set CHANGE_SOURCE to true in .env.

ARG CHANGE_SOURCE=false
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from deb.debian.org to aliyun source
    sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
    sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list \
;fi

# Start as root
USER root

###########################################################################
# Laradock non-root user:
###########################################################################

# Add a non-root user to prevent files being created with root permissions on host machine.
ARG PUID=1000
ENV PUID ${PUID}
ARG PGID=1000
ENV PGID ${PGID}

ARG CHANGE_SOURCE=false
ARG UBUNTU_SOURCE
COPY ./sources.sh /tmp/sources.sh

RUN if [ ${CHANGE_SOURCE} = true ]; then \
    /bin/sh -c /tmp/sources.sh && \
    rm -rf /tmp/sources.sh \
;fi

```

COPY ./sources.sh /tmp/sources.sh 不是已经复制了吗？为什么还会提示找不到文件呢？

**Comment by carveybunt** [comment]
经过我测试，发现，好像确实是copy这步没有复制成功文件，导致文件不存在。

**Comment by carveybunt** [comment]
如果在 windows 环境下启动容器报如下信息错误：
/bin/sh: 1: /tmp/sources.sh: not found
请使用 git bash 工具进行如下解决：

vim sources.sh
:set ff 如果是 dos
:set ff=unix
:wq
继续执行 docker-compose up --build -d xx

#2338

**Comment by Mortence** [comment]
@carveybunt 你这个问题是咋解决的

**Comment by carveybunt** [comment]
> @carveybunt 你这个问题是咋解决的

请使用 git bash 工具进行如下解决：

vim sources.sh
:set ff 如果是 dos
:set ff=unix
:wq
继续执行 docker-compose up --build -d xx

**Comment by DoopSky** [comment]
> @carveybunt 你这个问题是咋解决的

git bash 中 切换到 laradock 目录
`vi ./workspace/sources.sh`
`:set ff=unix`
`:wq`
然后继续执行 docker-compose up --build -d xx

**Comment by 1242048704** [comment]
i wanna know reason in it...please

**Comment by DoopSky** [comment]
> i wanna know reason in it...please

在 Windows 环境下 git clone 代码会导致文本文件换行符自动转换为 CRLF 格式。

由于 ./workspace/sources.sh 是在 Debian 中运行的，错误的换行符会导致文件无法运行。

`:set ff =unix` 这个命令就是将换行符转换为 LF 格式

**Comment by MoHen19** [comment]
使用了以上方法还是没有用咋办,求助大佬

**Comment by hwtdnet** [comment]
> 使用了以上方法还是没有用咋办,求助大佬

3100771535加Q

**Comment by MoHen19** [comment]
> > 使用了以上方法还是没有用咋办,求助大佬
> 
> 3100771535加Q

好的,感谢大佬支援
