### ISSUE TITLE
Error while building PHP zip extension with PHP7.4

### ISSUE THREAD

**Issue by amiraliio** [laradock/laradock#2453]
### Info:
- Docker version: 19.03.5, build 633a0ea838
- Laradock commit: [da40e2966db](https://github.com/laradock/laradock/commit/fc5ab30d4f53663d08aabade5c357da40e2966db) 
- System info:  Linux
- System info: Ubuntu 16.4 

### Issue:
I wanna build PHP zip extension with php7.4, I got ``configure: error: unrecognized options: --with-libzip``

### Expected behavior:
In php7.4 instead of ``docker-php-ext-configure zip --with-libzip`` should be ``docker-php-ext-configure zip ``

**Comment by f-ricci** [comment]
I have found a [similar problem here](https://stackoverflow.com/questions/48700453/docker-image-build-with-php-zip-extension-shows-bundled-libzip-is-deprecated-w)

The solution, as mentioned in the link above, should be replacing the line
`docker-php-ext-configure zip --with-libzip && \` with this one `docker-php-ext-configure zip && \` in `php-fpm/Dockerfile`.

I cannot guarantee that this is the best solution but it's working for me.

**Comment by amiraliio** [comment]
> I have found a [similar problem here](https://stackoverflow.com/a/48700777/6318542)
> 
> The solution, as mentioned in the link above, should be replacing the line
> `docker-php-ext-configure zip --with-libzip && \` with this one `docker-php-ext-configure zip && \` in `php-fpm/Dockerfile@line:54`.
> 
> I cannot guarantee that this is the best solution but it's working for me.

Maybe this isn't a good solution for the Laradock which want to support multiple version of PHP

**Comment by bestlong** [comment]
Duplicate #2421
