### ISSUE TITLE
Consider upgrading to a newer apache image

### ISSUE THREAD

**Issue by skript-cc** [laradock/laradock#2456]
### Issue:
The dockerfile used for apache uses an outdated version (2.4.18). The latest stable apache version at the time of writing is [2.4.41](https://httpd.apache.org/download.cgi).

This is because the docker image used for apache is based on ubuntu 16.04. That version of ubuntu comes with apache 2.4.18 (see https://packages.ubuntu.com/search?suite=xenial&keywords=apache2).

Although [ubuntu 16.04 is still a supported ubuntu version](https://ubuntu.com/about/release-cycle) there are newer versions of ubuntu available that come with newer versions of apache.

I'm raising this issue because a security scan marked version of 2.4.18 as a vulnerability. When I attempted to upgrade I found out that this currently isn't possible with laradock because of the above.

Whether or not to use a newer image might depend on your maintenance/upgrade policy, if you have any. Based on that I might reconsider using laradock.

### Relevant Code:

https://github.com/laradock/laradock/blob/3c36fc7d16967ce14a67fa6fe43313e177a6701c/apache2/Dockerfile#L1

**Comment by skript-cc** [comment]
Thanks @bestlong when is the next release scheduled?

**Comment by bestlong** [comment]
released.

**Comment by skript-cc** [comment]
Ah, very soon I see. Thanks again.
