### ISSUE TITLE
Service 'workspace' failed to build. Failed to connect to raw.githubusercontent.com port 443: Connection refused. /bin/sh: 1: .: Can't open /home/laradock/.nvm/nvm.sh

### ISSUE THREAD

**Issue by laraws** [laradock/laradock#2459]
### Info:
- Docker version (`$ docker --version`):  Docker version 19.03.5, build 633a0ea838
- Laradock commit (`$ git rev-parse HEAD`):  0d086024a8b7cff30f45860fe28c9ae896281bc8
- System info (Mac, PC, Linux):  Linux
- System info disto/version: Ubuntu 18.04.3 LTS

### Issue:

When I run the command `docker-compose up -d nginx mysql`, then the error displayed  below.

```
Step 139/251 : ARG NVM_NODEJS_ORG_MIRROR
 ---> Running in e4cad9ad77fc
Removing intermediate container e4cad9ad77fc
 ---> 476b6a3bf857
Step 140/251 : ENV NVM_NODEJS_ORG_MIRROR ${NVM_NODEJS_ORG_MIRROR}
 ---> Running in a7b49cab04cd
Removing intermediate container a7b49cab04cd
 ---> 8f1c53fcada9
Step 141/251 : RUN if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi
 ---> Running in c6f5f534b449
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
/bin/sh: 1: .: Can't open /home/laradock/.nvm/nvm.sh
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi' returned a non-zero code: 2
```

### Expected behavior:

No error.

### Reproduce:

```
docker-compose up -d nginx mysql
```

### Relevant Code:

```
docker-compose up -d nginx mysql
```

**Comment by 1002534056** [comment]
遇到同样的问题

**Comment by b9813147** [comment]
me too

**Comment by lucifer103** [comment]
目测是网速问题导致 node 的包没下载下来，科学上网应该可以解决。

**Comment by bestlong** [comment]
network problem?

```shell
Step 140/251 : ENV NVM_NODEJS_ORG_MIRROR ${NVM_NODEJS_ORG_MIRROR}
 ---> Running in d73360186e9f
Removing intermediate container d73360186e9f
 ---> d35c6173e63b
Step 141/251 : RUN if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi
 ---> Running in 148bd8dd4fdd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12819  100 12819    0     0  20380      0 --:--:-- --:--:-- --:--:-- 20412
=> Downloading nvm from git to '/home/laradock/.nvm'
=> Cloning into '/home/laradock/.nvm'...
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/laradock/.bashrc
=> Appending bash_completion source string to /home/laradock/.bashrc
=> Installing Node.js version node
Downloading and installing node v13.5.0...
Downloading https://nodejs.org/dist/v13.5.0/node-v13.5.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v13.5.0 (npm v6.13.4)
Creating default alias: default -> node (-> v13.5.0)
=> Node.js version node has been successfully installed
=> Close and reopen your terminal to start using nvm or run the following to use it now:
```

**Comment by laraws** [comment]
> network problem?
> 
> ```shell
> Step 140/251 : ENV NVM_NODEJS_ORG_MIRROR ${NVM_NODEJS_ORG_MIRROR}
>  ---> Running in d73360186e9f
> Removing intermediate container d73360186e9f
>  ---> d35c6173e63b
> Step 141/251 : RUN if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi
>  ---> Running in 148bd8dd4fdd
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 12819  100 12819    0     0  20380      0 --:--:-- --:--:-- --:--:-- 20412
> => Downloading nvm from git to '/home/laradock/.nvm'
> => Cloning into '/home/laradock/.nvm'...
> => Compressing and cleaning up git repository
> 
> => Appending nvm source string to /home/laradock/.bashrc
> => Appending bash_completion source string to /home/laradock/.bashrc
> => Installing Node.js version node
> Downloading and installing node v13.5.0...
> Downloading https://nodejs.org/dist/v13.5.0/node-v13.5.0-linux-x64.tar.xz...
> ######################################################################## 100.0%
> Computing checksum with sha256sum
> Checksums matched!
> Now using node v13.5.0 (npm v6.13.4)
> Creating default alias: default -> node (-> v13.5.0)
> => Node.js version node has been successfully installed
> => Close and reopen your terminal to start using nvm or run the following to use it now:
> ```

Maybe it's a network problem. There's a network restriction in my area. Do you konw hom to solve it?

**Comment by laraws** [comment]
> 目测是网速问题导致 node 的包没下载下来，科学上网应该可以解决。

I'll try it, thanks.

**Comment by clint-box** [comment]
公司用的网可以安装 在家构建的时候也是这样，估计还是要科学上网

**Comment by fengjianfei** [comment]
199.232.28.133 raw.githubusercontent.com
试试这个

**Comment by BluceOne** [comment]
> 199.232.28.133 raw.githubusercontent.com
> 试试这个

好用，谢谢

**Comment by jamesyu89** [comment]
遇到了相同的问题，科学上网后还是不行，求解 @bestlong

**Comment by phoenixg** [comment]
It's a China problem.

**Comment by michael-xgw** [comment]
> > 199.232.28.133 raw.githubusercontent.com
> > 试试这个
> 
> 好用，谢谢

not work for me :( @Docker Toolbox

**Comment by williamtse** [comment]
我也是，只能科学上网才行吗？有没有其他方法？

**Comment by williamtse** [comment]
change 
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \`
to
`git clone https://github.com/nvm-sh/nvm.git .$NVM_DIR \`

**Comment by michael-xgw** [comment]
收到.实测有效,谢谢.我已临时弃用laradocker,恢复homestead了.以后有机会再研究.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laradock/laradock"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 下午5:16
收件人:&nbsp;"laradock/laradock"<laradock@noreply.github.com&gt;;
抄送:&nbsp;"1020846675"<1020846675@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [laradock/laradock] Service 'workspace' failed to build. Failed to connect to raw.githubusercontent.com port 443: Connection refused. /bin/sh: 1: .: Can't open /home/laradock/.nvm/nvm.sh (#2459)





 
change
 curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
 to
 git clone https://github.com/nvm-sh/nvm.git .$NVM_DIR \

**Comment by hankin-h-k** [comment]
hosts 增加这个199.232.28.133 raw.githubusercontent.com    还是无效，有什么办法

**Comment by williamtse** [comment]
加到workspace的Dockerfile文件里面
```
.......
RUN  if [ ${INSTALL_NODE} = true ]; then \
    # Install nvm (A Node Version Manager)
    echo '151.101.76.133 raw.githubusercontent.com' >> /etc/hosts && \   # 这里加入这一行
    mkdir -p $NVM_DIR && \
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh|bash \
......
```

**Comment by 1115332213** [comment]
I try it by changing the ip in /etc/hosts, but It can not work.

I solved it by such process. 

Then I open the (https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh) file and upload this file to aliyun oss.
Then you can  use this piece of code
```
curl -o- https://monitor-majors.oss-cn-shenzhen.aliyuncs.com/install.sh|bash \
```
to replace the line in laradock/workspace/Dockerfile
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh|bash \
```

**Comment by carveybunt** [comment]
> I try it by changing the ip in /etc/hosts, but It can not work.
> 
> I solved it by such process.
> 
> Then I open the (https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh) file and upload this file to aliyun oss.
> Then you can use this piece of code
> 
> ```
> curl -o- https://monitor-majors.oss-cn-shenzhen.aliyuncs.com/install.sh|bash \
> ```
> 
> to replace the line in laradock/workspace/Dockerfile
> 
> ```
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh|bash \
> ```

Master, it's working, thanks a lot. Can you teach me how to deal with similar problems in the future?

**Comment by mackyuok** [comment]
> I try it by changing the ip in /etc/hosts, but It can not work.
> 
> I solved it by such process.
> 
> Then I open the (https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh) file and upload this file to aliyun oss.
> Then you can use this piece of code
> 
> ```
> curl -o- https://monitor-majors.oss-cn-shenzhen.aliyuncs.com/install.sh|bash \
> ```
> 
> to replace the line in laradock/workspace/Dockerfile
> 
> ```
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh|bash \
> ```

thanks. it's working!!!! wow!

**Comment by sux789** [comment]
以前解决方案 github.com和文件相关贴换加速地址,install.sh | bash 贴换为,install.sh |sed 's/git相关/加速相关/' | bash,但是后来再装发现加速网站挂了,不用加速网站也可以,可能是我科学上网原因
