### ISSUE TITLE
nginx permission denied

### ISSUE THREAD

**Issue by gfd6th** [laradock/laradock#2464]
### Info:
- Docker version (`$ docker --version`): 19.03.5
- Laradock commit (`$ git rev-parse HEAD`): 0d086024a8b7cff30f45860fe28c9ae896281bc8
- System info (Mac, PC, Linux):  Linux
- System info disto/version:  Ubuntu

### Issue:

_____

Nginx has no permission for public/index.php, 
I have tried change owner or permission in nginx container and workspace container

```
chmod -R 777 /var/www/app/public
# or
chmod -R 777 /var/www/app/
# or
chown -R root:root /var/www/app/
chown -R www-data:www-data /var/www/app

```

But still failed, and get logs in nginx error log  as below 

```
[crit] 11#11: *7 stat() "/var/www/app/public/index.php" failed (13: Permission denied)
```

### Expected behavior:

_____

### Reproduce:

_____

### Relevant Code:

```
// place a code sample here
```

**Comment by LexSombra** [comment]
I've got the same problem!

**Comment by gfd6th** [comment]
@LexSombra I've found the solution that change user from root to normal user will fix this issue.

**Comment by praguevara** [comment]
Can you be a little more specific please? I'm having the same problem.

**Comment by gfd6th** [comment]
Run docker-compose command in normal user account

**Comment by praguevara** [comment]
I'm already running docker-compose from a normal user account.

**Comment by gfd6th** [comment]
That's weird. It helps me that run docker-compose from a normal user account

**Comment by gfd6th** [comment]
@praguevara @LexSombra I found that user www-data has no permission on /var/www, so you should chmod to 755 in nginx container

**Comment by praguevara** [comment]
> @praguevara @LexSombra I found that user www-data has no permission on /var/www, so you should chmod to 755 in nginx container 

This was some time ago, but I believe my problem was I had the folder on an NTFS drive, and that was messing with the permissions.
