### ISSUE TITLE
Mysql 8 connection / Create new Database with Line command 

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#2465]
Hello my friends . I need help a lot .
I have been working with Laradock for 2 years , And to connect to  mysql database I had to downgrade to MYSQL_VERSION=5.7 , becose php my admin didnt accept version 8  , you can see in this link -

https://github.com/laradock/laradock/issues/1855

well , now I have a new project that I need a more recent version of MySql  ( I need JSON Data Type
that mysql 5.7 does not support   ) .  

I dont need to use phpmy admin , I could use Mysql Workbench to adminstrate my database . But I need to create a database to connect with mysql Workbench . I just know how to create a database in PHP my admin .

Does some one could help me , telling how could I create a new database in line command  in Laradock ?

Thanks a lot

**Comment by murilolivorato** [comment]
I need to use mysql 8 , instead the 5.7 version . does some one could help me ?

**Comment by lfelizari** [comment]
Php 7.4, works out of the box.
Set in .env file.
`PHP_VERSION=7.4`
In terminal run
`docker-compose build php-fpm`
`docker-compose build workspace`
and then restart the container by running
`docker-compose down`
`docker-compose up -d nginx mysql workspace redis`
https://medium.com/@abdulwahabcomsi/change-php-version-in-laradock-6bdb4722d26b
