### ISSUE TITLE
phpmyadmin not working with port 8000 (digitalocean)

### ISSUE THREAD

**Issue by partenit** [LaraDock/laradock#247]
I changed to 8080 in docker-compose and now working properly.

**Comment by Mahmoudz** [comment]
@partenit thanks I will update that now to 

```yml
            - "8080:80"
```

**Comment by Mahmoudz** [comment]
@partenit could write a small doc on how to use PhpMyAdmin in general (not for DO).
Something like the [Use Redis](https://github.com/LaraDock/laradock#use-redis)  I think will make it easy for users.

If you prefer to you can write it in a comment and I'll add it to the doc or just submit a PR urself. 

Thanks

**Comment by appleboy** [comment]
@Mahmoudz I can write the document for `phpMyAdmin`.

**Comment by appleboy** [comment]
@partenit @Mahmoudz  Please help review this PR https://github.com/LaraDock/laradock/pull/250
