### ISSUE TITLE
Cant enter workspace after Docker Update (Docker version 19.03.5, build 633a0ea)

### ISSUE THREAD

**Issue by s1x** [laradock/laradock#2473]
### Info:
- Docker version Docker version 19.03.5, build 633a0ea (Docker v2.2 Windows)
- Laradock commit (`$ git rev-parse HEAD`): 0d086024a8b7cff30f45860fe28c9ae896281bc8
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

In the last couple of months worked fine, after updating to the next stable release I cannot enter via bash to the workspace.

### Issue:
Cant enter workspace bash
_____

### Expected behavior:
Enter workspace bash
_____

### Reproduce:
docker-compose up -d nginx mysql phpmyadmin workspace
docker-compose exec --user=laradock workspace bash
_____

### Relevant Code:
```
K:\Applications\App\laradock>docker-compose up -d nginx mysql phpmyadmin workspace
Starting laradock_mysql_1            ... done
Starting laradock_docker-in-docker_1 ... done
Starting laradock_workspace_1        ... done
Recreating laradock_phpmyadmin_1     ... done
Starting laradock_php-fpm_1          ... done
Starting laradock_nginx_1            ... done
K:\Applications\App\laradock>docker-compose exec --user=laradock workspace bash
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[10732] Failed to execute script docker-compose
```

**Comment by RizwanAslam** [comment]
Getting the same error.

**Comment by a-wenzel** [comment]
Same here.

**Comment by s1x** [comment]
To rollback to an older version until it is fixed you can use 2.1.0.4 which is available for download as Channel 39773. (Docker Desktop Community 2.1.0.4 from 2019-10-21 (https://download.docker.com/win/stable/39773/Docker%20Desktop%20Installer.exe).

2.1.0.4 works fine - however, you need to reconfigure your Docker and shared drives.

**Comment by RizwanAslam** [comment]
Try this [fix](https://github.com/docker/compose/issues/7169#issuecomment-576987766), until this issues is fixed by docker team. It's working for me.

**Comment by dolpox** [comment]
To fix this you have to upgrade your docker-compose to 1.25.3.

To update docker-compose (windows user)
1. update python to 3.x
2. execute this command `pip install --upgrade docker-compose`
3. restart docker

**Comment by ezekel** [comment]
@dolpox 

how to update to `update python to 3.x` ?

**Comment by cbnuke** [comment]
if use docker-compose direct has bug now. but you can enter workspace by docker command such as 
`docker exec -it --user=laradock laradock_workspace_1 bash`
