### ISSUE TITLE
Mirroring php extensions on php-worker

### ISSUE THREAD

**Issue by pedrofornaza** [laradock/laradock#2475]
Shouldnt php-worker have the same extensions as php-fpm or workspace?

In my project, for example, i use the default laravel worker with supervisor and i cant run my jobs in php-worker since some parts of it depends on intl, which is not installed.

**Comment by maid450** [comment]
In my case I make SQL Server queries in my jobs, so they fail because MSSQL driver is not installed.

**Comment by brahmbhattsnehal** [comment]
Any update on this issue? How you guys fix this issue?
