### ISSUE TITLE
Unable to install V8JS into Workspace

### ISSUE THREAD

**Issue by ralls** [laradock/laradock#2482]
### Info:
- Docker version (`$ docker --version`): Docker version 19.03.5, build 633a0ea
- Laradock commit (`$ git rev-parse HEAD`): ad2b455be577669aa599f3511704565e6a806629
- System info (Mac, PC, Linux): Mac
- System info disto/version: MacOS Mojave // 10.14.5

### Issue:
I'm unable to install V8JS as described in the documentation. After changing `WORKSPACE_INSTALL_V8JS=true` in `.env` and running `docker-compose build workspace` the build ultimately fails.
_____

### Expected behavior:
Building workspace should succeed without error and V8JS should be enabled.
_____

### Reproduce:
1. open .env
2. set `WORKSPACE_INSTALL_V8JS` to `true`
3. `docker-compose build workspace`
4. Observe the following error:
```
checking for libv8_libplatform... configure: error: could not find libv8_libplatform library
ERROR: `/tmp/pear/temp/v8js/configure --with-php-config=/usr/bin/php-config --with-v8js' failed
root@c184a9b01d6e:/tmp/v8js# exit
```
_____

### Relevant Code:
`.env`:
`WORKSPACE_INSTALL_V8JS=false`
`PHP_VERSION=7.1`
(also have tried 7.2, 7.3 with same results)

`workspace/Dockerfile`:
```
###########################################################################
# PHP V8JS:
###########################################################################

USER root

ARG INSTALL_V8JS=false

RUN set -xe; \
  if [ ${INSTALL_V8JS} = true ]; then \
    add-apt-repository -y ppa:pinepain/libv8-archived \
    && apt-get update -yqq \
    && apt-get install -y libv8-5.4 && \
    if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
      pecl install v8js-0.6.4; \
    else \
      pecl install v8js; \
    fi \
    && echo "extension=v8js.so" >> /etc/php/${LARADOCK_PHP_VERSION}/cli/php.ini \
    && php -m | grep -q 'v8js' \
  ;fi
```

**Comment by fynduck** [comment]
founded a solution to this problem?

**Comment by ralls** [comment]
> founded a solution to this problem?

Unfortunately no, I gave up.
