### ISSUE TITLE
Cant's install ffmpeg

### ISSUE THREAD

**Issue by awolad** [laradock/laradock#2483]
### Info:
- Docker version (`$ docker --version`): Docker version 19.03.5
- Laradock commit (`$ git rev-parse HEAD`): cb910c590e00cee77ebbf75867aae0c7d0199119
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04 LTS

### Issue:

Cant's install WORKSPACE_INSTALL_FFMPEG=true

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libs/libssh/libssh-gcrypt-4_0.6.3-4.3ubuntu0.2_amd64.deb  404  Not Found [IP: 91.189.88.24 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_FFMPEG} = true ]; then   apt-get -y install ffmpeg ;fi' returned a non-zero code: 100

**Comment by bestlong** [comment]
try `docker-compose build --no-cache workspace`

**Comment by awolad** [comment]
Thanks @bestlong it's working now.
