### ISSUE TITLE
Sync between docker 2.2.0.0 and windows host is not reliable

### ISSUE THREAD

**Issue by jvihrial** [laradock/laradock#2484]
This is mostly a docker bug, but listing it here as it appears on Laradock.

### Info:
- Docker version 2.2.0.0
- Laradock commit ad2b455be577669aa599f3511704565e6a806629
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 64bit pro

### Issue:
When using Docker 2.2.0.0 , files updated on host do not appear changed on the host.
_____

### Expected behavior:
When you save file on editor at host - it should be updated on the docker container too.
_____

### Reproduce:
Run VSCode on host, edit files etc and over time it suddenly drops out of sync.
_____

### Relevant Code:

```
### Workaround: Install Docker 2.1.0.5.
```

**Comment by harrisdt15f** [comment]
i already installed that version, I think docker v 2.2.0.0 has so many errors. And I ownly run perfectly on
