### ISSUE TITLE
BZ2 & GMP for Workspace, FPM and Horizon

### ISSUE THREAD

**Issue by bumbummen99** [laradock/laradock#2488]
### Info:
- Docker version (`$ docker --version`): 19.03.3, build a872fc2f86
- Laradock commit (`$ git rev-parse HEAD`): ad2b455
- System info (Mac, PC, Linux): Ubuntu Eoan
- System info disto/version: 19.10

### Issue:

_____
The User is able to install gmp for php-fpm and workspace containers but NOT in horizon, this will break queued jobs that require these extensions (and can be installed since they are available in workspace).

Secondly bz2 has to be added manually completely in php-fpm and horizon.

### Expected behavior:

_____
There should be options to install **all** php extensions in **all** containers that **could** run the very same code with the same requirements in terms of extensions.
### Reproduce:

_____
Use bz2 or gmp in Horizon, for example try to create a queued Job using [GameQ](https://github.com/Austinb/GameQ) while horizon is your queue handler.

### Relevant Code:

There is no relevant code.

**Comment by bestlong** [comment]
#652
