### ISSUE TITLE
request pending for 21 seconds before getting response from apache laradock

### ISSUE THREAD

**Issue by cissecedric** [laradock/laradock#2489]
### Info:
- Docker desktop 2.1.0.4: 
- Laradock commit ad2b455be577669aa599f3511704565e6a806629: 
- System info PC
- System info windows 10 

### Issue:
All my requests takes a least 21 seconds because they are pending during this time , I don't know how to change that
![image](https://user-images.githubusercontent.com/12851286/73596260-0480ab00-4521-11ea-82ea-3f26f60ce863.png)
 
_____

### Expected behavior:
Laradock / apache shouldn't let my request pending during 21 seconds before responding.
_____

### Reproduce:
Add a laravel project as described in documentation
_____

Thank you for your help !

**Comment by vanwhebin** [comment]
Docker desktop 2.1.0.5:
Laradock commit ad2b455:
System info MacOS 10.14.3

Same here,  all my requests takes at least 5 seconds

![image](https://user-images.githubusercontent.com/8357785/74508882-1e67b800-4f3b-11ea-8c5b-09a1a2f5f8c1.png)

I checked .env file and asked some friends while it is working good on their devices.

Any idea? Thanks.

**Comment by vanwhebin** [comment]
> Docker desktop 2.1.0.5:
> Laradock commit [ad2b455](https://github.com/laradock/laradock/commit/ad2b455be577669aa599f3511704565e6a806629):
> System info MacOS 10.14.3
> 
> Same here, all my requests takes at least 5 seconds
> 
> ![image](https://user-images.githubusercontent.com/8357785/74508882-1e67b800-4f3b-11ea-8c5b-09a1a2f5f8c1.png)
> 
> I checked .env file and asked some friends while it is working good on their devices.
> 
> Any idea? Thanks.

My bad. Due to DNS service on Mac, the pending http request delayed 5s.
I have fixed it by adding 127.0.0.1 localhost  devdomain  on /etc/hosts
