### ISSUE TITLE
Better way to handle multi site

### ISSUE THREAD

**Issue by tjb328** [LaraDock/laradock#249]
I came across this article using haproxy to handle a multi site dev environment:
http://blog.dubizzle.com/boilerroom/2016/08/18/setting-development-environment-docker-compose/

We should be able to do something similar and have a one container per project setup.
@LarryEitel

**Comment by LarryEitel** [comment]
I recall reading about that. I am all in favor of anything that will make it easier to accommodate multiple sites. :) I will review ASAP.

**Comment by LarryEitel** [comment]
@tjb328 Thanks for the tip. :)

**Comment by tjb328** [comment]
I didn't realize that issue #54 was still open. I'm closing this and adding this info to that issue.
