### ISSUE TITLE
php-fpm cannot get the latest stable version e.g 7.3.14

### ISSUE THREAD

**Issue by harrisdt15f** [laradock/laradock#2494]
### Description:
php-fpm container now can only be get 7.3.13 but I net to get the latest stable one.
it already out for a few days, but still cannot get the latest.
now version shown is
PHP 7.3.13 (cli) (built: Dec 28 2019 21:22:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans

### Expected Behavior:
as soon as pull the image should get the latest version of php version, like worksapce container do.
In workspace container php version now is 
PHP 7.3.14-6+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  5 2020 16:51:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-6+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### Context information:

**Output of `git rev-parse HEAD`**

```
c8c63e6a78d492e54311c36a8ea3abaa09da42bc
```

**Output of `docker version`**

```
Docker version 19.03.5, build 633a0ea
```

**Output of `docker-compose version`**

```
docker-compose version 1.24.1, build 4667896b
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Microsoft Windows [Version 10.0.18363.628]
```

### Steps to reproduce the issue:
as soon as pulled the image every time easy to reproduce.

**Comment by spyridonas** [comment]
Change this line

https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile#L16

To say php-fpm:latest on your local Dockerfile
