### ISSUE TITLE
 Failed to connect to raw.githubusercontent.com port 443: Connection timed out

### ISSUE THREAD

**Issue by xafzz** [laradock/laradock#2495]
[
  ##![微信截图_20200207114959](https://user-images.githubusercontent.com/25863091/73999709-88fb7f80-49a0-11ea-920a-a58a02543040.png)
](url)
实在是无能为力了，阿里云上也不行

tep 141/251 : RUN if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi
 ---> Running in 1e79f9c4cec8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection timed out
/bin/sh: 1: .: Can't open /home/laradock/.nvm/nvm.sh
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi' returned a non-zero code: 2
root@iZm5e6m2vttqlgxmaercobZ:/wwwroot/laradock#

**Comment by xafzz** [comment]
![微信截图_20200207114959](https://user-images.githubusercontent.com/25863091/73999617-49cd2e80-49a0-11ea-89f4-5699c613aa13.png)

**Comment by godhelpjun** [comment]
浏览器打开
把内容copy下来保存文件 nvm-install.sh
修改Dockerfile文件 
copy nvm-install.sh  /tmp/nvm-install.sh
run /tmp/nvm-install.sh

**Comment by romanad** [comment]
Is there any way to solve this issue?
