### ISSUE TITLE
ERROR: Named volume " ~/.laradock/data/minio/data:/export:rw" is used in service "minio" but no declaration was  found in the volumes section.

### ISSUE THREAD

**Issue by godhelpjun** [laradock/laradock#2497]
### Description:

docker-compose up mysql
get error output 
ERROR: Named volume " ~/.laradock/data/minio/data:/export:rw" is used in service "minio" but no declaration was
 found in the volumes section.

### Expected Behavior:

get mysql container running like yesterday
### Context information:

**Output of `git rev-parse HEAD`**
792d803d9ca6896c113e30d568d1822ba6ed1c94
```
{paste here}
```

**Output of `docker version`**
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
{paste here}
```

**Output of `docker-compose version`**

```
{paste here}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
{paste here}
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by ridhozhr10** [comment]
how about try using `/home/$USER/.laradock/data/minio/data` instead of `~`. also make sure that directory is exist (no typo or anything)
