### ISSUE TITLE
"php_network_getaddresses: getaddrinfo failed: Name or service not known[xxxx]

### ISSUE THREAD

**Issue by pizsd** [laradock/laradock#2503]
### Description:
mysql, redis This problem occurs under the debug of phpstorm. This problem does not occur directly in the browser or postman. I want to know what causes it.
### error

redis
php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://reids:6379]
mysql
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

Project configuration file .env
redis
```json
REDIS_HOST=reids
REDIS_PASSWORD=null
REDIS_PORT=6379
```
mysql
```json
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=campaign
DB_USERNAME=root
DB_PASSWORD=root
```

docker fo mac 
dcoker:19.03
docker-compsoe:1.25.2

**Comment by bestlong** [comment]
check container working first.
`docker-compse ps`
`docker-compse logs mysql`
`docker-compse logs redis`

**Comment by metalcamp** [comment]
Probably typo: 

> REDIS_HOST=reids

**Comment by pizsd** [comment]
@metalcamp Not the problem, the configuration is wrong

**Comment by metalcamp** [comment]
@pizsd: Is your redis service (in docker-compose.yml) also named reids?

**Comment by bestlong** [comment]
edit .env file
```
REDIS_HOST=redis
```

**Comment by ugurdnlr** [comment]
I'm getting this error too.

`Illuminate\Database\QueryException : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known `

when i run tests from phpstorm I'm getting this. But i didn't get this when i run from terminal like `phpunit Tests\ExampleTest`

**Comment by ugurdnlr** [comment]
My Solution: 

PhpStorm->Preferences->Languages & Frameworks->PHP->Test Frameworks

Add PHPUnit by Remote Interpreter 

Select Docker interpreter

After created you should add link ( Links section ) which one do u want to use ( mysql, redis) to docker container (click Browse in docker container section)

And if you know which network is using in docker container you should write name of network ( `docker network ls` ) into Network Mode section then click OK . That’s it.

But if you don’t know which network is using . First you should remove all unused networks ( `docker network prune` ) then run ( `docker network ls` )

**Comment by maMykola** [comment]
> My Solution:
> 
> PhpStorm->Preferences->Languages & Frameworks->PHP->Test Frameworks
> 
> Add PHPUnit by Remote Interpreter
> 
> Select Docker interpreter
> 
> After created you should add link ( Links section ) which one do u want to use ( mysql, redis) to docker container (click Browse in docker container section)
> 
> And if you know which network is using in docker container you should write name of network ( `docker network ls` ) into Network Mode section then click OK . That’s it.
> 
> But if you don’t know which network is using . First you should remove all unused networks ( `docker network prune` ) then run ( `docker network ls` )

changing **Network mode** from **bridge** to docker internal network fixed my problem

**Comment by BonBonSlick** [comment]
In my case error was misleading. You have to run commands from docker container eg docker-compose exec containerName (app) php (serviceName) bin/console doctrine:migrations:migrate (service command).
I was trying to run it from outside of container.

**Comment by HuyNguyen206** [comment]
hi @ugurdnlr,
Regarding this section "After created you should add link ( Links section ) which one do u want to use ( mysql, redis) to docker container (click Browse in docker container section)", could you explain in more detail with screenshot?
I try to config but an error occurs
This is screenshots of my config
![image](https://user-images.githubusercontent.com/30259638/212469976-c0a50e85-93d0-46d4-83a6-e751f22f181d.png)
![image](https://user-images.githubusercontent.com/30259638/212470018-2144cf6f-c1b8-464e-832d-faf8b19563a6.png)
![image](https://user-images.githubusercontent.com/30259638/212470044-d9d692fd-a1e9-417a-b526-82728c9c7715.png)


Thanks in advance

**Comment by keizah7** [comment]
> My Solution:
> 
> PhpStorm->Preferences->Languages & Frameworks->PHP->Test Frameworks
> 
> Add PHPUnit by Remote Interpreter
> 
> Select Docker interpreter
> 
> After created you should add link ( Links section ) which one do u want to use ( mysql, redis) to docker container (click Browse in docker container section)
> 
> And if you know which network is using in docker container you should write name of network ( `docker network ls` ) into Network Mode section then click OK . That’s it.
> 
> But if you don’t know which network is using . First you should remove all unused networks ( `docker network prune` ) then run ( `docker network ls` )

thank you! Changed `Network mode` in Docker container settings and it started working
