### ISSUE TITLE
problem with php5.6

### ISSUE THREAD

**Issue by naghiloo** [laradock/laradock#2506]
hi, I am serving up some containers that my php should be 5.6.
but I faced with this error unfortunately:

```
Step 120/251 : RUN if [ ${INSTALL_AST} = true ]; then     printf "\n" | pecl -q install ast-${AST_VERSION} &&     echo "extension=ast.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/ast.ini &&     phpenmod -v ${LARADOCK_PHP_VERSION} -s cli ast ;fi
 ---> Running in 6cbea836fac5
pecl/ast requires PHP (version >= 7.0.0), installed version is 5.6.40-21+ubuntu16.04.1+deb.sury.org+1
No valid packages found
install failed
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_AST} = true ]; then     printf "\n" | pecl -q install ast-${AST_VERSION} &&     echo "extension=ast.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/ast.ini &&     phpenmod -v ${LARADOCK_PHP_VERSION} -s cli ast ;fi' returned a non-zero code: 1
```

**Comment by bestlong** [comment]
need ast extension in php 5.6 ?
seem not support.

**Comment by naghiloo** [comment]
I know but what should I do right now?
I am looking to set up some containers such as apache and MySQL to run my web application.
my friend suggested laradock but I can't build workspace image with php5.6
can you help me?

**Comment by bestlong** [comment]
edit .env set WORKSPACE_INSTALL_AST=false

**Comment by GinoPane** [comment]
I believe the proper fix for this should be by checking the PHP version before installation

**Comment by ultrono** [comment]
Unfortunately I had to use PHP 5.6 for the first times in ages, on an old Cake PHP project. Setting `WORKSPACE_INSTALL_AST` to `false` allowed me to rebuild the workspace container after changing the php-fpm version to 5.6 🍾
