### ISSUE TITLE
ERROR: for nginx  Cannot start service nginx

### ISSUE THREAD

**Issue by appkr** [LaraDock/laradock#251]
Help me out. I'm having trouble up and running laradock.

```sh
$ docker-compose build --no-cache
# ...
```

```sh
$ docker-compose up -d nginx mysql
# Creating network "laradock_default" with the default driver
# Creating laradock_volumes_source_1
# Creating laradock_volumes_data_1
# Creating laradock_workspace_1
# Creating laradock_mysql_1
# Creating laradock_php-fpm_1
# Creating laradock_nginx_1
# 
# ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (c9651bd4e4ae303693c7b8b1f9fdbb39f410896171fb6ded93f759b3f5e6c327): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
# ERROR: Encountered errors while bringing up the project.
```

For your information, I'm using docker for mac.

```sh
$ docker --version
# Docker version 1.12.0, build 8eab29e
$ docker-compose --version
# docker-compose version 1.8.0, build f3628c7
```

Did I miss something?

**Comment by zhikiri** [comment]
@appkr I had the same error. Try to use Docker Toolbox

**Comment by appkr** [comment]
@zhikiri thanks for the information. no I can wait untill it gets fixed.

**Comment by LarryEitel** [comment]
I am also confirming this with the latest laradock. I removed all laradock_ containers and images and restarted docker as well.

docker-compose up -d mysql nginx
```
Creating laradock_volumes_source_1
Creating laradock_volumes_data_1
Creating laradock_mysql_1
Creating laradock_workspace_1
Creating laradock_php-fpm_1
Creating laradock_nginx_1

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (fa628c2c44fd43467db7ab6fc87b4501f616b512371ae7fbaa2dfc9340dbd32b): Error starting userland proxy: Bind for 0.0.0.0:443 failed: port is already allocated
Encountered errors while bringing up the project.
```

```
          Name                        Command              State             Ports
-------------------------------------------------------------------------------------------
laradock_mysql_1            docker-entrypoint.sh mysqld   Up         0.0.0.0:3306->3306/tcp
laradock_nginx_1            nginx                         Exit 128
laradock_php-fpm_1          php-fpm                       Up         9000/tcp
laradock_volumes_data_1     /true                         Exit 0
laradock_volumes_source_1   /true                         Exit 0
laradock_workspace_1        /sbin/my_init                 Up         0.0.0.0:22->22/tcp
```

While this problem exists with latest LaraDock on my laptop, I AM running OK with a slightly older version of LaraDock on my workstation. Don't know exactly what is causing problem at this point.

**Comment by LarryEitel** [comment]
I wiped LaraDock CLEAN and am failing to fire up mysql nginx on my Dell Windows 10. This looks interesting: https://github.com/docker/docker/issues/22614

**Comment by grisotto** [comment]
I had the same problem. I fixed this by stopping the Apache2 service on my host.

**Comment by LarryEitel** [comment]
Don't have apache running on my host but I found the culprit!!!! Skype!!!
See: http://superuser.com/a/125459/187185

**Comment by grisotto** [comment]
Yes. Same port number.

**Comment by miguelvaladez** [comment]
I was having the same issue and fixed it by editing the port mapping of the nginx container from 

`- "80:80"`

to

`- "8080:80"`

After that I found my project at: http://localhost:8080

**Comment by appkr** [comment]
@miguelvaladez Thank a million, that helped me.

Thanks to @miguelvaladez 's comment, I suspect that the problem may be caused by Laravel Valet. To ensure that I did `lsof` command, and I got the hint.

```sh
~ $ lsof -i TCP:80
COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    1129 appkr  127u  IPv4 0xb6f109901b654883      0t0  TCP 192.168.88.187:50208->hkg12s01-in-f98.1e100.net:http (CLOSE_WAIT)
Google    1129 appkr  207u  IPv4 0xb6f1099020192693      0t0  TCP 192.168.88.187:50204->ns1.daum.net:http (ESTABLISHED)
```

I stopped the valet and retried boot up Laradock and it worked.

```sh
~ $ valet stop
~/Laradock $ docker-compose up -d nginx
# Creating network "laradock_default" with the default driver
# Creating laradock_volumes_data_1
# Creating laradock_volumes_source_1
# Creating laradock_workspace_1
# Creating laradock_mysql_1
# Creating laradock_php-fpm_1
# Creating laradock_nginx_1
```

Thanks community!

---

#### CONCLUSION

> 1. TURN THE VALET OFF BEFORE USING LARADOCK.
>
> 2. CHANGE YOUR LARADOCK NGINX CONTAINER's PORT, IF THE 80 PORT ALREADY IN USE.

**Comment by SamoilenkoEvgeniy** [comment]
also you can turn off in skype check box with 80 and 443 ports.

**Comment by Mahmoudz** [comment]
an alternative to `miguelvaladez` solution is to stop using port 80 on your machine. 

# see port usage
`sudo lsof -i :80`

# 1
`sudo killall httpd`

# 2
`sudo launchctl unload /System/Library/LaunchDaemons/org.apache.httpd.plist`

DONE

**Comment by zzpwestlife** [comment]
@appkr Yes. That's the solution. Valet is the culprit. Stop it and everything is OK. Thanks.

**Comment by andim27** [comment]
if you use win  10 do next:
net stop w3svc

**Comment by DiegoFelipe** [comment]
sudo service apache2 stop

**Comment by ashajjar** [comment]
I had the same issue .. and I am using Valet, so just stop Valet and everything will be fine :)

**Comment by Baldrani** [comment]
Okay so I found out there was an nginx on my computer running on port 80.
 Way to know if it's your case : 
`sudo lsof -i :80` 
which output 
```
Google      309 mael  186u  IPv4 0xc09d7f680ef39365      0t0  TCP 192.168.0.19:64275->par10s27-in-f14.1e100.net:http (CLOSED)
Google      309 mael  203u  IPv4 0xc09d7f680e21fa05      0t0  TCP 192.168.0.19:64276->cache.google.com:http (CLOSED)
Google      309 mael  206u  IPv4 0xc09d7f6808120cc5      0t0  TCP 192.168.0.19:64277->64.15.115.97:http (CLOSED)
nginx     12529 root    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12530 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12531 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12532 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12533 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12534 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12535 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12536 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
nginx     12537 mael    6u  IPv4 0xc09d7f6810787cc5      0t0  TCP *:http (LISTEN)
```

Then run `sudo nginx -s stop` to kill the process. 

And you'll be good to un docker-compose up

**Comment by jayhill90** [comment]
@Mahmoudz 's response worked for me for another repo that I was having this same issue with.

**Comment by Dailson** [comment]
I've stopped apache service and it worked for me

**Comment by RamosRenan** [comment]
> Help me out. I'm having trouble up and running laradock.
> 
> ```shell
> $ docker-compose build --no-cache
> # ...
> ```
> 
> ```shell
> $ docker-compose up -d nginx mysql
> # Creating network "laradock_default" with the default driver
> # Creating laradock_volumes_source_1
> # Creating laradock_volumes_data_1
> # Creating laradock_workspace_1
> # Creating laradock_mysql_1
> # Creating laradock_php-fpm_1
> # Creating laradock_nginx_1
> # 
> # ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (c9651bd4e4ae303693c7b8b1f9fdbb39f410896171fb6ded93f759b3f5e6c327): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
> # ERROR: Encountered errors while bringing up the project.
> ```
> 
> For your information, I'm using docker for mac.
> 
> ```shell
> $ docker --version
> # Docker version 1.12.0, build 8eab29e
> $ docker-compose --version
> # docker-compose version 1.8.0, build f3628c7
> ```
> 
> Did I miss something?

I solved this issue stoping apache
if you are in Linux type:
$ sudo service apache2 stop
