### ISSUE TITLE
ZipArchive not found from laravel-horizon

### ISSUE THREAD

**Issue by glorand** [laradock/laradock#2513]
ZipArchive not found from laravel-horizon

**Comment by lionslair** [comment]
Add the below to the Dockerfile should work.
`# Install ZipArchive: Force Install
ARG PHP_WORKER_INSTALL_ZIP_ARCHIVE=false
RUN set -eux; \
  if [ ${PHP_WORKER_INSTALL_ZIP_ARCHIVE} = true ]; then \
    apk --update add libzip-dev && \
    if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ]; then \
      docker-php-ext-configure zip; \
    else \
      docker-php-ext-configure zip --with-libzip; \
    fi && \
    # Install the zip extension
    docker-php-ext-install zip \
;fi`
