### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by burakcakirel** [laradock/laradock#2518]
### Description:
Same issue #1764

When trying to use file_get_contents, an exception is thrown.

Exception thrown:
file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### Expected Behavior:
The requested resource should be returned

### Context information:

**Output of `git rev-parse HEAD`**

```
6a92eb0d589c66ef1ccd8945de1d07a6e35861e1
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose version`**

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu 19.10
```

### Steps to reproduce the issue:
Try to fetch an asset using file_get_contents

### Stacktrace & Additional info:

```
$file = file_get_contents(xyz.com/assets/image.extension)
```

**Comment by ugurdnlr** [comment]
I'm getting this error too.

`Illuminate\Database\QueryException : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known `

when i run tests from phpstorm I'm getting this. But i didn't get this when i run from terminal like `phpunit Tests\ExampleTest`

**Comment by ismartSa** [comment]
It has the same problem with connecting to databases in another container
