### ISSUE TITLE
[php-worker] alpine 3.11 missing `default-mysql-client`

### ISSUE THREAD

**Issue by ahkui** [laradock/laradock#2520]
### Description:
php-worker build fail because alpine 3.11 missing `default-mysql-client`

### Expected Behavior:
![image](https://user-images.githubusercontent.com/14049597/75307054-b5126e00-5885-11ea-9574-f086ded2a12d.png)

[build-php-worker.log](https://github.com/laradock/laradock/files/4253238/build-php-worker.log)

**Comment by bestlong** [comment]
#2257 
#2511
