### ISSUE TITLE
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

### ISSUE THREAD

**Issue by grisotto** [LaraDock/laradock#253]
`ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.`

Add to documentation:
require docker-composite >= 1.6.0.
I was using docker-composite [1.5.2](https://packages.debian.org/unstable/main/docker-compose). This is default Debian version.

**Comment by Mahmoudz** [comment]
@grisotto I tried to reproduce that error now but I couldn't!! I advise you to `pull` the latest version of LaraDock and try again. 

If you still have that error, please give us more details about your case: past the docker-compose.yml file content here and share which commands are you trying to run. 
Thanks

**Comment by grisotto** [comment]
The error:

```
sudo docker-compose up -d  nginx mysql
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

`uname -a`
`Linux 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux`

```
docker-compose -v
docker-compose version 1.5.2, build unknown
```

I fixed this updating the docker-compose to version 1.8.
I suggest you to add in requirements docker-composite >= 1.6.

**Comment by Mahmoudz** [comment]
I will mention the version of Docker itself, because currently the documentation only ask for downloading Docker native which comes by default with the latest version of docker-compose >= `1.8.0` you are probably still using the docker on vm! or you downloaded the beta long time ago. Thanks.

**Comment by hopewise** [comment]
I have the same issue on Ubuntu 16, but I don't know how to upgrade docker-compose to 1.8 ?!

**Comment by philtrep** [comment]
@hopewise take a look at https://docs.docker.com/compose/install/#/alternative-install-options

**Comment by hopewise** [comment]
thanks

**Comment by manoj8928** [comment]
Update your docker-compose and issue will be resolved
curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by Dartanjan** [comment]
After doing the above, and running `docker-compose`, or `docker-compose version`, I get:

`/usr/local/bin/docker-compose: line 1: {error:Not Found}: command not found`

Context: I installed Docker for OSX, but had docker-compose version 1.5.2 and I tried to upgrade to 1.9.0.

**Comment by Dartanjan** [comment]
Solved, I updated docker-compose with instructions from https://docs.docker.com/compose/install/
The cURL call is a bit different for OSX. Thanks for pointing in the right direction :)
