### ISSUE TITLE
DOCKER_HOST_IP don't work in centos7?

### ISSUE THREAD

**Issue by carveybunt** [laradock/laradock#2541]
Why can't I see DOCKER_HOST_IP of default of .env in IP list when I use command "ip addr"  after I run command "docker-compose up -d nginx redis mysql php-fpm" in Centos 7.6. I just setting "CHANGE_SOURCE=true" of .env. Who can help me solve the problem, please?
![image](https://user-images.githubusercontent.com/37894474/77842834-9297ab80-71c9-11ea-9bbf-8c3c65d592c8.png)

**Comment by vladyslavstartsev** [comment]
Hi! I don't really understand your problem
probably this command will help you to get it 
```shell
ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'
```

**Comment by carveybunt** [comment]
@vladyslavstartsev thanks
