### ISSUE TITLE
ERROR: Service 'mysql' failed to build: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by abdel24hour** [laradock/laradock#2545]
[root@ip-172-31-42-146 laradock]# cp env-example .env

[root@ip-172-31-42-146 laradock]# docker-compose up -d nginx mysql redis
Building mysql
Step 1/10 : ARG MYSQL_VERSION
ERROR: Service 'mysql' failed to build: Please provide a source image with `from` prior to commit

**Comment by softwarefreak** [comment]
Can you paste the contents of your mysql/Dockerfile ?
