### ISSUE TITLE
Can't call API from react native

### ISSUE THREAD

**Issue by phuongpt0301** [laradock/laradock#2547]
I used Postman call to API(https://laravel.qrcode.test/api/qrcodes/5555) then it success. But when 
call the API from React Native app then it's appear error "Network request failed". Can you help me, please?(url)

**Error on app:**
<img width="308" alt="error" src="https://user-images.githubusercontent.com/37206038/78467108-777dec00-7733-11ea-80b7-84d8bb3d485f.png">

**Call from Postman:**
<img width="966" alt="Postman" src="https://user-images.githubusercontent.com/37206038/78467122-97151480-7733-11ea-9ebd-b6bfca7399e4.png">

**Docker running:**
<img width="1115" alt="docker" src="https://user-images.githubusercontent.com/37206038/78467137-b6ac3d00-7733-11ea-805b-6662f8a5622f.png">

**Comment by softwarefreak** [comment]
The issue here is, from wherever you're running the react native app, that environment doesn't know how to resolve the DNS qrcode.test

Whereas postman is able to do that because of the host file entry.
