### ISSUE TITLE
docker-compose build --no-cache nginx : network error (check Internet connection and firewall)

### ISSUE THREAD

**Issue by nikhrrazn** [laradock/laradock#2551]
Building nginx
Step 1/17 : FROM nginx:alpine
 ---> 377c0837328f
Step 2/17 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Running in 8d53a074e85a
Removing intermediate container 8d53a074e85a
 ---> 6053f271c802
Step 3/17 : COPY nginx.conf /etc/nginx/
 ---> ba65da2b9c43
Step 4/17 : ARG CHANGE_SOURCE=false
 ---> Running in 1d31fc76ab76
Removing intermediate container 1d31fc76ab76
 ---> 8864e5fb904e
Step 5/17 : RUN if [ ${CHANGE_SOURCE} = true ]; then     sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories ;fi
 ---> Running in d0f8c3bd67dd
Removing intermediate container d0f8c3bd67dd
 ---> c6e0c7aaf66f
Step 6/17 : RUN apk update     && apk upgrade     && apk --update add logrotate     && apk add --no-cache openssl     && apk add --no-cache bash
 ---> Running in 37305c5f0e55
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.10/main: network error (check Internet connection and firewall)
WARNING: Ignoring APKINDEX.00740ba1.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.10/community: network error (check Internet connection and firewall)
WARNING: Ignoring APKINDEX.d8b2a6f4.tar.gz: No such file or directory
2 errors; 36 distinct packages available
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apk update     && apk upgrade     && apk --update add logrotate     && apk add --no-cache openssl     && apk add --no-cache bash' returned a non-zero code: 2

**Comment by nikhrrazn** [comment]
Anyone have any ideas here?

**Comment by orangeShadow** [comment]
Yes I get this error too, solving problem by this command:  ```docker pull nginx:alpine```

**Comment by zhaoqinghuan** [comment]
hi brother, I also encountered this problem yesterday. I solved the problem by restarting the computer and restarting the Docker client. Hope to help others!
