### ISSUE TITLE
pgadmin exit code 3 PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'

### ISSUE THREAD

**Issue by carlosedulucas** [laradock/laradock#2552]
### Description:
pgadmin_1              | WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
pgadmin_1              | Traceback (most recent call last):
pgadmin_1              |   File "run_pgadmin.py", line 4, in <module>
pgadmin_1              |     from pgAdmin4 import app
pgadmin_1              |   File "/pgadmin4/pgAdmin4.py", line 109, in <module>
pgadmin_1              |     app = create_app()
pgadmin_1              |   File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
pgadmin_1              |     create_app_data_directory(config)
pgadmin_1              |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
pgadmin_1              |     _create_directory_if_not_exists(config.SESSION_DB_PATH)
pgadmin_1              |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
pgadmin_1              |     os.mkdir(_path)
pgadmin_1              | PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
pgadmin_1              | [2020-04-08 22:12:50 +0000] [1] [INFO] Starting gunicorn 19.9.0
pgadmin_1              | [2020-04-08 22:12:50 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin_1              | [2020-04-08 22:12:50 +0000] [1] [INFO] Using worker: threads
pgadmin_1              | [2020-04-08 22:12:50 +0000] [87] [INFO] Booting worker with pid: 87
pgadmin_1              | [2020-04-08 22:12:50 +0000] [87] [ERROR] Exception in worker process
pgadmin_1              | Traceback (most recent call last):
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
pgadmin_1              |     worker.init_process()
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
pgadmin_1              |     super(ThreadWorker, self).init_process()
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
pgadmin_1              |     self.load_wsgi()
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
pgadmin_1              |     self.wsgi = self.app.wsgi()
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
pgadmin_1              |     self.callable = self.load()
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
pgadmin_1              |     return self.load_wsgiapp()
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
pgadmin_1              |     return util.import_app(self.app_uri)
pgadmin_1              |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
pgadmin_1              |     __import__(module)
pgadmin_1              |   File "/pgadmin4/run_pgadmin.py", line 4, in <module>
pgadmin_1              |     from pgAdmin4 import app
pgadmin_1              |   File "/pgadmin4/pgAdmin4.py", line 109, in <module>
pgadmin_1              |     app = create_app()
pgadmin_1              |   File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
pgadmin_1              |     create_app_data_directory(config)
pgadmin_1              |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
pgadmin_1              |     _create_directory_if_not_exists(config.SESSION_DB_PATH)
pgadmin_1              |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
pgadmin_1              |     os.mkdir(_path)
pgadmin_1              | PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
pgadmin_1              | [2020-04-08 22:12:50 +0000] [87] [INFO] Worker exiting (pid: 87)
pgadmin_1              | WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
pgadmin_1              | [2020-04-08 22:12:51 +0000] [1] [INFO] Shutting down: Master
pgadmin_1              | [2020-04-08 22:12:51 +0000] [1] [INFO] Reason: Worker failed to boot.

### Context information:

**Output of `git rev-parse HEAD`**

3f71fc2c15216d61911b94c886f094e42e5efb57

**Output of `docker version`**
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Thu Aug 15 15:12:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Output of `docker-compose version`**

docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**System info: Mac, Windows or Linux. Include which disto/version**
eduardo@notehp:~/Code/laradocknovo$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
Linux notehp 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce the issue:

1. docker-compose up -d postgresql pgadmin

### Stacktrace & Additional info:

eduardo@notehp:~/Code/laradocknovo$ docker-compose ps
           Name                          Command              State                                         Ports                                     
------------------------------------------------------------------------------------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh           Up       2375/tcp, 2376/tcp                                                             
laradock_nginx_1              /bin/bash /opt/startup.sh       Up       0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:81->81/tcp                   
laradock_pgadmin_1            /entrypoint.sh                  **Exit 3**                                                                                  
laradock_php-fpm_1            docker-php-entrypoint php-fpm   Up       9000/tcp                                                                       
laradock_postgres_1           docker-entrypoint.sh postgres   Up       0.0.0.0:5432->5432/tcp                                                         
laradock_workspace_1          /sbin/my_init                   Up       0.0.0.0:2222->22/tcp, 0.0.0.0:3000->3000/tcp, 0.0.0.0:3001->3001/tcp,          
                                                                       0.0.0.0:8001->8000/tcp, 0.0.0.0:8080->8080/tcp     

eduardo@notehp:~/.laradock/data$ ll
total 16
drwxr-xr-x  4 root    root    4096 Abr  8 19:04 ./
drwxr-xr-x  3 eduardo eduardo 4096 Abr  8 19:04 ../
drwxr-xr-x  2 root    root    4096 Abr  8 19:04 pgadmin/
drwx------ 19      **70** root    4096 Abr  8 19:05 postgres/

**Comment by rossanoua** [comment]
Hi @carlosedulucas.
As a temporary fix I'm using 
`sudo chmod -R 777 ~/.laradock/data/pgadmin`

**Comment by carlosedulucas** [comment]
temporarily had already performed

sudo chmod -R 777 ~/.laradock/data

only

~/.laradock/data/pgadmin

didn't solve

**Comment by minhlong** [comment]
same problem

**Comment by mario-spitze** [comment]
When you manual chown to the pgadmin user and group, pgadmin starts.
