### ISSUE TITLE
Failed to build php-fpm.

### ISSUE THREAD

**Issue by HelloZouYou** [laradock/laradock#2554]
### Description:
error caused when run `apt-get update -yqq`

![image](https://user-images.githubusercontent.com/28775622/78885569-70d2da00-7a8f-11ea-865c-85b35fefb1f1.png)
![image](https://user-images.githubusercontent.com/28775622/78885675-99f36a80-7a8f-11ea-92b2-ce8d2d44eb5b.png)

Docker Version:
![image](https://user-images.githubusercontent.com/28775622/78885764-bb545680-7a8f-11ea-8241-983d74a93b85.png)

**Comment by HelloZouYou** [comment]
I got it! Because of the argument "http_proxy", it cause the container to use the proxy of the host

**Comment by AngelBS** [comment]
@HelloZouYou i'm having the same issue running `docker-compose up -d nginx mysql phpmyadmin redis workspace 
` for the first time i tried to remove the "- http_proxy" argument from the workspace docker-compose.yml build
