### ISSUE TITLE
multiple projects on localhost

### ISSUE THREAD

**Issue by lumenier1** [laradock/laradock#2558]
### Description:

I've installed Laradock but can not setup multiple projects on localhost for development.
Nginx container fails if I add more than one working config in `nginx/sites/` folder.

### Expected Behavior:

If I add multiple project folders next to `laradock` folder I should be able to config Nginx for handling those projects on localhost, same domain name but different routing, i.e.:
1) `http://localhost/project-one`
2) `http://localhost/project-two`
3) ...

### Context information:

**Output of `git rev-parse HEAD`**

```
3f71fc2c15216d61911b94c886f094e42e5efb57
```

**Output of `docker version`**

```
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose version`**

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
macOS Catalina 10.15.4
```

### Steps to reproduce the issue:

1. Cloning Laradock git repo
`git clone https://github.com/Laradock/laradock.git`
2. Creating several project folders
```
- laradock
- new-project
   ﹂index.php
- test-project
   ﹂index.php
```
3. Setting up Nginx config files for each project
Same config for two files:
`laradock/nginx/sites/new-project.conf`
`laradock/nginx/sites/test-project.conf`
```
server {

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    server_name ~^(?<project>.+)\.laradock\.dev$;
    root /var/www/$project;
    index index.php index.html index.htm;
...
}
```

4. Compose
`docker-compose up -d nginx mysql phpmyadmin`

### Stacktrace & Additional info:

```
$ docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                     PORTS                                                                                                    NAMES
3189cee03979        laradock_nginx        "/bin/bash /opt/star…"   6 seconds ago       Exited (1) 4 seconds ago                                                                                                            laradock_nginx_1
b078751511b4        laradock_php-fpm      "docker-php-entrypoi…"   6 seconds ago       Up 5 seconds               9000/tcp                                                                                                 laradock_php-fpm_1
e4c2eab1cd2b        laradock_phpmyadmin   "/docker-entrypoint.…"   8 seconds ago       Up 6 seconds               0.0.0.0:8081->80/tcp                                                                                     laradock_phpmyadmin_1
d2f5ce2fdda4        laradock_workspace    "/sbin/my_init"          8 seconds ago       Up 6 seconds               0.0.0.0:3000-3001->3000-3001/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:2222->22/tcp, 0.0.0.0:8001->8000/tcp   laradock_workspace_1
40da6b9cfdd5        laradock_mysql        "docker-entrypoint.s…"   8 seconds ago       Up 7 seconds               0.0.0.0:3306->3306/tcp, 33060/tcp                                                                        laradock_mysql_1
7963bf244ca6        docker:19.03-dind     "dockerd-entrypoint.…"   8 seconds ago       Up 7 seconds               2375-2376/tcp                                                                                            laradock_docker-in-docker_1
```

As the result Nginx container fails.

---
But it works in case of just one Nginx config file i.e. `laradock/nginx/sites/new-project.conf`. If I leave one `new-project.conf` file in this directory it would work only for one project `new-project` respectively and there is no rule for routing in this case, `http://localhost/any` will route to `new-project` too.

Is there any approach to configure routing for multiple projects with one entry point (domain) in Laradock? Can I hardcode it in `nginx/sites` config files instead of using variables like `$project`?

**Comment by softwarefreak** [comment]
Nginx logs will tell us what the problem is, did you try getting the logs of nginx?

```
#cd to your laradock
docker-compose logs nginx
```

**Comment by lumenier1** [comment]
@softwarefreak 
Here it is
```
nginx_1                | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/sites-available/test-project.conf:3
nginx_1                | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/sites-available/test-project.conf:3
nginx_1                | nginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/upstream.conf:1
```
Also I've changed this part of config
```
server {

    listen 80;
    listen [::]:80 ipv6only=on;
...
```
But result is pretty the same
```
nginx_1                | nginx: [emerg] duplicate listen options for [::]:80 in /etc/nginx/sites-available/test-project.conf:4
```

**Comment by softwarefreak** [comment]
>  listen [::]:80 ipv6only=on;

Remove that as well, that's for ipv6 support not needed for local environment

So, there are two ways to solve this as much as I know.

Change ports to something else (you'll need to expose the extra port in docker-compose nginx block)

An easier way is to map hostnames in hosts file and use them in nginx config, like below
```
server {

    listen 80 server1.local;
...
server {

    listen 80 server2.local;
...
```

**Comment by lumenier1** [comment]
Thank you for the reply.
Is there another way to do this without changing hosts file?

**Comment by softwarefreak** [comment]
Open up your docker-compose file, look for "nginx:"
```
    nginx:
    ...
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        #add the port you want, make sure the port is not in use by others
        - "8080:8080" 
        - "${NGINX_HOST_HTTPS_PORT}:443"
```

And in your nginx site config, add the new port
```
server {

    listen 80 default;
...

server {

    listen 8080 default;
...
```
Rebuild nginx

**Comment by lumenier1** [comment]
@softwarefreak

> And in your nginx site config, add the new port

Actually, this is not what I need

> An easier way is to map hostnames in hosts

Even in this case it doesn't work.

I've added two config files:

```
# laradock/nginx/sites/project-one
server {
    listen 80;
    listen [::]:80;

    server_name server1.localhost;
    index index.php index.html index.htm;
    root /var/www;

    location ~ ^/project-one {
         try_files $uri $uri/ /index.php$is_args$args;
    }
...
}
```

```
# laradock/nginx/sites/project-two
server {
    listen 80;
    listen [::]:80;

    server_name server2.localhost;
    index index.php index.html index.htm;
    root /var/www;

    location ~ ^/project-two {
         try_files $uri $uri/ /index.php$is_args$args;
    }
...
}
```

Also I've added it to `hosts` file:

```
127.0.0.1  server1.localhost
127.0.0.1  server2.localhost
```

Structure of my root folder:

```
- laradock
- project-one
   ﹂index.php
- project-two
   ﹂index.php
```

Buuuut... If I check `/var/www` directory in `laradock_nginx_1` container by `docker exec -it laradock_nginx_1 bash` command there is only... one file - `index.php`.

```
- /var/www
   ﹂index.php
```

Literally, Laradock serves just one `index.php` file given from random project folder. It ignores my folder structure `project-one` and `project-two`.

I want to make Laradock serve it properly in relation to my project structure:

```
- /var/www/project-one
   ﹂index.php
- /var/www/project-two
   ﹂index.php
```

Please, help.

**Comment by sfx101** [comment]
> root /var/www;

Here, just set 2 different paths and you're done

root /var/www/server1 => index.php
root/var/www/server2 => index.php

**Comment by sfx101** [comment]
> server {
>     listen 80;
>     listen [::]:80;
> 
>     server_name server2.localhost;
>     index index.php index.html index.htm;
>     root /var/www;

Here, just set 2 different paths and you're done

root /var/www/server1 => index.php
root/var/www/server2 => index.php

The nginx is a single container here, so even if you have 2 different site configs the path /var/www is same both everybody inside the container.

**Comment by lumenier1** [comment]
In the end of the day, it finally unscrewed my nuts.

If I set it in the one config file:

```
Attaching to laradock_nginx_1
nginx_1                | nginx: [emerg] "root" directive is duplicate in /etc/nginx/sites-available/default.conf:24
nginx_1                | nginx: [emerg] "root" directive is duplicate in /etc/nginx/sites-available/default.conf:24
```

If I set 2 separate config files it just can’t be reached.

I've added multiple roots, added hosts, added aliases for frontend and backend in docker-compose file. Doesn't work.
