### ISSUE TITLE
Missing libpng-dev while trying to install custom tool with Nova and yarn 

### ISSUE THREAD

**Issue by Perh0rd** [laradock/laradock#2574]
**Is your feature request related to a problem? Please describe.**

While installing yarn on a custom nova tools , this error popup : 

"pngquant failed to build"

**Describe the solution you'd like**

Install Library in the Dockerfile of workspace if libpng is true on .env file

```
###########################################################################
# Libpng16 EXTENSION
###########################################################################

ARG INSTALL_LIBPNG=false

RUN if [ ${INSTALL_LIBPNG} = true ]; then \
    apt-get update && \
    apt-get -y install libpng16-16 && \
    apt-get -y install libpng-dev \
;fi
```
**Describe alternatives you've considered**
Install manualy

**Additional context**

**Comment by garbinmarcelo** [comment]
I have a similar problem, I already set WORKSPACE_INSTALL_LIBPNG=true but when I do `npm install` it returns the following error:

![image](https://user-images.githubusercontent.com/9335588/121698630-8df4a580-caa4-11eb-896f-3d22622d5a76.png)

can anybody help me? Thanks
