### ISSUE TITLE
 ImageMagick | GD module not available with this PHP installation

### ISSUE THREAD

**Issue by tnduc** [laradock/laradock#2592]
### Context information:

**Output of `git rev-parse HEAD`**

```
653587d4a833e2e11310a982f7310a658d41114a
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           19.03.8  
 API version:       1.40     
 Go version:        go1.12.17
 Git commit:        afacb8b  
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose version`**

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 10, version 1909
```

### Steps to reproduce the issue:

1. Install package `https://github.com/spatie/laravel-medialibrary`
2. Defining conversions 
```
$this->addMediaConversion('thumb')
     ->width(368)
     ->height(232)
     ->extractVideoFrameAtSecond(20)
     ->performOnCollections('videos');
```
3. `PerformConversionsJob` fail when I use `GD`or `ImageMagick` 

### Stacktrace & Additional info:
![Annotation 2020-05-18 151209](https://user-images.githubusercontent.com/26267956/82189706-04fb5100-991a-11ea-932f-0fcd50e31670.png)
![Annotation 2020-05-18 151228](https://user-images.githubusercontent.com/26267956/82189716-0af13200-991a-11ea-8f9c-32cbe0b037d1.png)

**Comment by bestlong** [comment]
edit .env set:
```
WORKSPACE_INSTALL_IMAGEMAGICK=true
PHP_FPM_INSTALL_IMAGEMAGICK=true
```
and rebuild:
```
docker-compose build --no-cache workspace php-fpm
```

**Comment by tnduc** [comment]
> edit .env set:
> 
> ```
> WORKSPACE_INSTALL_IMAGEMAGICK=true
> PHP_FPM_INSTALL_IMAGEMAGICK=true
> ```
> 
> and rebuild:
> 
> ```
> docker-compose build --no-cache workspace php-fpm
> ```
I did so, but it didn't work

**Comment by zl910627** [comment]
Please, please fix this!

**Comment by bestlong** [comment]
need PerformConversionsJob fail error log

**Comment by tnduc** [comment]
> need PerformConversionsJob fail error log
I updated laradock and got a new error

![Capture](https://user-images.githubusercontent.com/26267956/85045801-aeec2880-b1b9-11ea-91da-651907995b3a.PNG)
