### ISSUE TITLE
Can't run 'php artisan migrate' from workspace

### ISSUE THREAD

**Issue by rotaercz** [laradock/laradock#2600]
### Description:

Can't run 'php artisan migrate' from workspace.

### Expected Behavior:

I expect database migrations to happen.

### Context information:
Basically I'll run the following to access the container:

    docker-compose exec workspace bash

It seems to be able to do everything but it doesn't seem to be able to access the mysql container. If I login to the mysql container I can access mysql but no php access.

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
2.3.0.2
```

**Output of `docker-compose version`**

```
1.25.5
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 10 Version 1909
```

### Steps to reproduce the issue:

1. docker-compose exec workspace bash
2. php artisan migrate
3. You'll get an error saying the connection is refused

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by aidan-casey** [comment]
I believe this issue can be closed. In working with @rotaercz, we were able to determine that there were several factors to this problem.

* Docker needed file sharing permissions for the project folder. Steps for this are:
    1. Open Docker Desktop.
    2. Press the gear icon on the toolbar to access settings.
    3. Press the "Resources" button
    4. Press "File Sharing"
    5. Press the add icon and browse to your project folder and select "Add Folder"
* Due to some configuration changes made throughout debugging the above issue, it ended up being easier to create a brand new project. Steps for this are below and assume the install of git bash.
    1. Open git bash
    2. Type `cd Desktop`
        * This simply changes the current directory to your desktop folder
    3. Type `mkdir testing`
        * This creates a new directory called "testing" in the current folder (your desktop).
    4. Type `cd testing`
        * This changes the current directory to the testing folder on your desktop.
    5. Type `git clone https://github.com/laradock/laradock.git`
        * This downloads Laradock from GitHub and places it in a sub-folder in your project directory.
    6. Type `cd laradock`
        * Once more we are changing the directory, this time to the Laradock folder in the project folder on your desktop.
    7. Type `copy env-example .env`
        * This copies the example environment file for Laradock to the actual environment file that will be used to configure your Laradock instance.
    8. Now open the .env file in Notepad and change the line that says `WORKSPACE_VUE_CLI_SERVE_HOST_PORT=8080` to `WORKSPACE_VUE_CLI_SERVE_HOST_PORT=8081`
        * This changes the port that the Workspace container serves Vue CLI on avoiding a conflict with the phpMyAdmin container.
    9. Add the testing folder to folder sharing in Docker desktop as described above.
    10. Go back to your Git Bash window and type `docker-compose up -d nginx mysql phpmyadmin redis`
        * This will startup the Nginx, MySQL, phpMyAdmin, and Redis containers.
    11. Your containers should be up and running. Note: we did not install a Laravel project, so nothing will be serving on `http://localhost` but you should be able to access phpMyAdmin at `http://localhost:8080`.
        * Default MySQL server is `mysql`
        * Default MySQL root username is `root`
        * Default MySQL root password is `root`

**Comment by dendihandian** [comment]
This seems to be the misconfiguration in the laravel .env file or sometime in my local machine case, the MySQL container is ready to be accessed in about 10-15 minutes after it's up and running.

**Comment by hsmfawaz** [comment]
try to connect to your **phpmyadmin** if it connected correctly then the problem is misconfiguration in your **.env** file for example check if 
`DATABASE_HOST=mysql`
