### ISSUE TITLE
php-worker change pdf to blank page

### ISSUE THREAD

**Issue by theyudhiztira** [laradock/laradock#2603]
Hi everyone I’m having problem with the php-worker.

What i tried to do is merging multiple pdf into one single pdf.
Here is the library I used to do a pdf merging : [lara-pdf-merger](https://github.com/deltaaskii/lara-pdf-merger) 

I saw on the php-worker Dockerfile that the worker is using php alpine. But i can also enable the GD library through the env, set the INSTALL_GD to true referring to #2516 , but instead of merging it what i got is a blank pdf and also it changed my source pdf to a blank page as well.

 But if i run the queue manually through the workspace it works well.

**Comment by theyudhiztira** [comment]
spent my whole day to re-read the things and learn it, finally i came up with something.
The php-worker is using alpine version of php, i'm sure some pdf library is not come with it so anyone had any idea what kind of things i should do?

**Comment by dendihandian** [comment]
@theyudhiztira try to set `PHP_WORKER_INSTALL_GD=true` in `.env` and rebuild & re-run the container

**Comment by theyudhiztira** [comment]
> @theyudhiztira try to set `PHP_WORKER_INSTALL_GD=true` in `.env` and rebuild & re-run the container

@dendihandian I tried already but got the same problem it keeps turning my template pdf to a blank pdf
I think the problem is because the workspace and the worker they are not having the same library.

So what i do for this problem i run my supervisor from workspace instead of php-worker

**Comment by bestlong** [comment]
check log first `docker-compose logs -f php-worker`

**Comment by theyudhiztira** [comment]
> check log first `docker-compose logs -f php-worker`

I lost the information and forgot to keep an eye on this problem. But solved it already so the workaround i did is run the supervisor on the workspace container instead of php-worker.
