### ISSUE TITLE
docker compose conflict in env var value

### ISSUE THREAD

**Issue by Abouhassane** [laradock/laradock#2618]
### Description:
The docker compose prioritize reading environment variables from the system shell than from the env file. therefore some variables conflicts with those already existing in the system, such an example would be the "PHP_VERSION".

### Expected Behavior:
When you set the same environment variable in multiple files, here’s the priority used by Compose to choose which value to use:

Compose file
Shell environment variables
Environment file
Dockerfile
Variable is not defined

=> I think that the variables in Environment file should be prioritized

### Steps to reproduce the issue:

1. chose a variable that already exist in the env file
2. source it in your system with a different value from the env file
3. run you docker compose

### Workaround:

As docker compose doesn't give a way to chose the priority of the env vars, i suggest naming the variables with a unique name

**Comment by bestlong** [comment]
in php base container like workspace, php-fpm, php-worker, laravel-horizon

use build args LARADOCK_PHP_VERSION=${PHP_VERSION} avoid conflict.

**Comment by mberizzo** [comment]
@bestlong something like this for example? `docker-compose build --build-arg LARADOCK_PHP_VERSION=${PHP_VERSION} php-fpm`

**Comment by bestlong** [comment]
> @bestlong something like this for example? `docker-compose build --build-arg LARADOCK_PHP_VERSION=${PHP_VERSION} php-fpm`

It's not like this. PHP_VERSION environment variable is already used in PHP-based containers
Therefore, when the PHP_VERSION environment variable of Laradock .env is transferred to the PHP container through docker-compose, it will be processed with LARADOCK_PHP_VERSION instead.

**Comment by mberizzo** [comment]
In my case when I try to build php-fpm or workspace Dockerfile does not respect .env value, ie: if I change PHP_VERSION=7.3 to 7.4 I still with 7.3

**Comment by bestlong** [comment]
after change .env PHP_VERSION
need

``` shell
docker-compose down
docker-compose build --no-cache php-fpm workspace [and other PHP base services...]
docker-compose up -d php-fpm workspace [and other PHP base services...]
```

**Comment by mberizzo** [comment]
That's the first thing I did but does not work

**Comment by bestlong** [comment]
in linux, maybe need upgrade docker-compse version.

**Comment by Matra-Master** [comment]
> in linux, maybe need upgrade docker-compose version.

I'm using docker-compose 2.1.0 on arch-linux and i get this error when building:
```
Sending build context to Docker daemon  20.19kB
Step 1/303 : ARG LARADOCK_PHP_VERSION
Step 2/303 : ARG BASE_IMAGE_TAG_PREFIX=latest
Step 3/303 : FROM laradock/workspace:${BASE_IMAGE_TAG_PREFIX}-${LARADOCK_PHP_VERSION}
Sending build context to Docker daemon  165.9kB
Step 1/185 : ARG LARADOCK_PHP_VERSION
Step 2/185 : ARG BASE_IMAGE_TAG_PREFIX=latest
Step 3/185 : FROM laradock/php-fpm:${BASE_IMAGE_TAG_PREFIX}-${LARADOCK_PHP_VERSION}
2 errors occurred:
	* Status: manifest for laradock/workspace:false-false not found: manifest unknown: manifest unknown, Code: 1
	* Status: manifest for laradock/php-fpm:false-false not found: manifest unknown: manifest unknown, Code: 1
```
My .env has variables like so
```
PHP_VERSION=7.4
WORKSPACE_BASE_IMAGE_PREFIX=latest
PHP_FPM_BASE_IMAGE_PREFIX=latest
```
My variables sometimes become false-false, sometimes true-true and sometimes latest-latest. After much search i think it's an issue from Laradock and not mine because this wasn't happening to my projects two days ago. I can report more if necessary.
