### ISSUE TITLE
Connection timed out [IP: 91.189.95.83 80]

### ISSUE THREAD

**Issue by 1242048704** [laradock/laradock#2650]
Step 111/273 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then     apt-get update -yqq &&     apt-get install -yqq php-redis ;fi
 ---> Running in 5c5564d2d561

E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php-redis_5.3.0+4.3.0-1+ubuntu18.04.1+deb.sury.org+1_amd64.deb  Connection timed out [IP: 91.189.95.83 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

我可以在浏览器中直接下载，但是安装过程中报连接超时错误，而且这个地址是可以ping通的

I can download it directly in the browser, but a connection timeout error is reported during the installation process, and this address can be pinged

everyone? how should i do? please...

**Comment by 1242048704** [comment]
everyone? how should i do? How odd!

**Comment by 1242048704** [comment]
> Step 111/273 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then apt-get update -yqq && apt-get install -yqq php-redis ;fi
> ---> Running in 5c5564d2d561
> 
> E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php-redis_5.3.0+4.3.0-1+ubuntu18.04.1+deb.sury.org+1_amd64.deb Connection timed out [IP: 91.189.95.83 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> 
> 我可以在浏览器中直接下载，但是安装过程中报连接超时错误，而且这个地址是可以ping通的
> 
> I can download it directly in the browser, but a connection timeout error is reported during the installation process, and this address can be pinged
> 
> everyone? how should i do? please...

**Comment by DoopSky** [comment]
#2529

**Comment by 1242048704** [comment]
> #2529

thanks，brother！！！
