### ISSUE TITLE
Multi projects not working

### ISSUE THREAD

**Issue by Samuel-Bie** [laradock/laradock#2654]
### Description:

Look I've already successfully performed the configuration for just one project. (Both in the local environment and in the production environment).

But now I need the configuration for multiple projects.

I performed the patent configuration at the link https://laradock.io/getting-started/#B, and it worked perfectly on the local env, but when I upload the settings to production. Both projects fall into error 404.

I thank you for your help.

### Project configuration
>-laradock
>-project1
>-project2

### Nginx Config

>- laradock/nginx/sites/default.conf

```
server {

    listen 80 default_server;
    listen [::]:80 default_server;

    # For https
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server; # dont add ipv6only=on
    ssl_certificate /etc/nginx/ssl/default.crt;
    ssl_certificate_key /etc/nginx/ssl/default.key;

    server_name domain.com www.domain.com;
    root /var/www/project1/public; 
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
```

>- laradock/nginx/sites/site.conf

```
     server {
....
          server_name domain2.com www.domain2.com;
          root /var/www/project2/public; 
....
     }

**Comment by bestlong** [comment]
``` shell
cp laravel.conf.example laravel-project1.conf
cp laravel.conf.example laravel-project2.conf
```

update new *.conf sever_name and root

**Comment by Samuel-Bie** [comment]
@bestlong I have done that, still dont work.

**Comment by bestlong** [comment]
check log first. `docker-compose logs -f nginx`
There may be important informationㄡ

**Comment by Samuel-Bie** [comment]
It Just shows:
            Attaching to laradock_nginx_1

**Comment by theyudhiztira** [comment]
> It Just shows:
> 
>             Attaching to laradock_nginx_1
> 
> 

Try to compose up without -d flag and see what's happening with your nginx.

I don't thing the file naming is a real cause of your problem.

**Comment by bestlong** [comment]
It’s not a file name issue. I suggest that every project will create a new profile.

after `docker-compose logs -f nginx` to see log, also need open browser Will show 404 related messages

**Comment by Samuel-Bie** [comment]
I could not solve this using one nginx container to serve two apps, instead i used traefik and created two nginx instances each one for an app.

Its working, but now i wonder if this is a good approach for solving this issue, since this approach forced me to run for each app another related container. I.E 

For app1
```
nginx1,
workspace1,
php-fpm1,
php-worker1
```

For app2


```
nginx2,
workspace2,
php-fpm2,
php-worker2
```
