### ISSUE TITLE
 I get an error that the container cannot be started because dev/shm already exists

### ISSUE THREAD

**Issue by getahead92** [laradock/laradock#2663]
### Description:
Removing intermediate container 0880214a4049
 ---> 3c9afc1c0421
Successfully built 3c9afc1c0421
Successfully tagged om_selenium:latest
WARNING: Image for service selenium was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating om_docker-in-docker_1 ... done
Creating om_workspace_1        ... done
Creating om_php-fpm_1          ... done
Creating om_php-worker_1       ... done
Creating om_apache2_1          ... done
Creating om_selenium_1         ... error

ERROR: for om_selenium_1  Cannot start service selenium: error while creating mount source path '/dev/shm': mkdir /dev/shm: file exists

ERROR: for selenium  Cannot start service selenium: error while creating mount source path '/dev/shm': mkdir /dev/shm: file exists
ERROR: Encountered errors while bringing up the project.

**Output of `docker version`**

```
Docker version 19.03.8, build afacb8b
```

**Output of `docker-compose version`**

```
docker-compose version 1.25.5, build 8a1c60f6
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
window10 pro 
```

Hello, it works fine on other computers, but I get the above error on a specific computer, I'm not sure what's wrong because I'm a beginner. Sorry, but I would like some advice on this.

**Comment by pratikid** [comment]
In your case, I consider that Docker is running on Windows 10 Pro with WSL/2 support.
Can you mention the output of below command?
``` bash
ls -la /dev/shm
```

Permission Issue:
https://github.com/git-for-windows/git/issues/1449

Solution:
https://github.com/git-for-windows/git-sdk-64/blob/master/etc/post-install/01-devices.post#L44-L57
