### ISSUE TITLE
Connect the external redis timeout

### ISSUE THREAD

**Issue by lemonlyue** [laradock/laradock#2666]
### Description:

I want to connect the external redis,
but connect the external redis timeout

I tried to command connect to the external Redis using the ping , but the local machine can, and redis desktop manager can
### Context information:

**Output of `docker version`**

```
Docker version 19.03.5
```

**Output of `docker-compose version`**

```
docker-compose version 1.25.2
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
windows
```

**Comment by FoxxMD** [comment]
@lemonlyue what was the issue? I'm having very slow responses from an external redis connection.
