### ISSUE TITLE
PhpMyAdmin

### ISSUE THREAD

**Issue by everaldo** [LaraDock/laradock#267]
Hi!

I couldn't access phpmyadmin using Laradock.

I spinned up the container with docker-compose up -d mysql phpmyadmin

and tried to access localhost:8080

I didn't understand why in docker-composer.yml the EXPORTS are 8080:80

Anyone could help me please?

**Comment by appleboy** [comment]
Please show your `docker ps` log.

**Comment by bvbunnik** [comment]
I have exactly the same problem. Trying to get phpmyadmin to run with `docker-compose up -d mysql phpmyadmin`

Output is:
```
Starting laradock_volumes_data_1
Starting laradock_mysql_1
Starting laradock_phpmyadmin_1

```
`docker ps` shows:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
d1ea975601eb        laradock_mysql      "docker-entrypoint.sh"   About an hour ago   Up 4 seconds        0.0.0.0:3306->3306/tcp   laradock_mysql_1
```
There is no error reported not on the cli nor in the logs of docker.

Any further suggestions?

**Comment by appleboy** [comment]
Please try the following command and show the output log messages.

<img width="1186" alt="screen shot 2016-08-29 at 8 56 28 pm" src="https://cloud.githubusercontent.com/assets/21979/18052146/373629ce-6e2b-11e6-9c9e-b6f0f1e7eb12.png">

**Comment by bvbunnik** [comment]
Thanks for your suggestion!
running `docker-compose up phpmyadmin` results in:
![docker1](https://cloud.githubusercontent.com/assets/443751/18052822/6383466a-6df4-11e6-8df3-da5e1ac292a3.png)

**Comment by everaldo** [comment]
Hi! My output is the same as @bvbunnik

**Comment by appleboy** [comment]
@everaldo Please provide docker engine version.

**Comment by appleboy** [comment]
@everaldo @bvbunnik I create new PR to fix this issue. Please help to verify patch file.

**Comment by everaldo** [comment]
The message "laradock_phpmyadmin_1 exited with code 0" is gone, but still not working.
