### ISSUE TITLE
Laravel cannot connect to to mysql database

### ISSUE THREAD

**Issue by gamenic-pawanrai** [laradock/laradock#2672]
I have the following DB config snippet from laravel .env file

    DB_CONNECTION=mysql
    DB_HOST=127.0.0.1
    DB_PORT=3306
    DB_DATABASE=api
    DB_USERNAME=root
    DB_PASSWORD=root`

With the above config  I can run `php artisan migrate` commands but the app it self cannot connect to database. I get this error:

> SQLSTATE[HY000] [2002] Connection refused 

Following the issue #1752 I changed `DB_HOST=127.0.0.1` to `DB_HOST=mysql`  with this setting the app connects to the database but cannot run `php artisan migrate` commands in the terminal.

FYI: I created laravel project from host terminal not laradock workspace bash. As sudo password is required every time I save the file,

**Comment by ultrono** [comment]
Have you tried logged into the workspace as a none root user i.e. `docker-compose exec --user=laradock workspace bash` ?

**Comment by gamenic-pawanrai** [comment]
Yeah, I can run those commands from workspace but not from terminal of host machine.

I'd installed Laravel from host terminal so I'm trying to run these commands from there.

**Comment by hwtdnet** [comment]
rename ~/.laradock

**Comment by r-yeganeh** [comment]
Try changing `DB_HOST=127.0.0.1` to `DB_HOST=mysql`

**Comment by azizgharbi** [comment]
> DB_HOST=mysql

awesome thank you

**Comment by sa1eemKhan** [comment]
replace the DB_HOST=127.0.0.1 with DB_HOST=localhost
