### ISSUE TITLE
How to resolve the error "gettext is not installed"

### ISSUE THREAD

**Issue by JMultimidia** [laradock/laradock#2678]
I'm trying to run an application using laradock and the message "Fatal error: Uncaught RuntimeException: This class require the gettext extension for PHP in /var/www/valedopi/vendor/gettext/gettext/src/GettextTranslator.php:15 Stack trace: #0 /var/www/valedopi/app/translator.php(4): Gettext\GettextTranslator->__construct() #1 /var/www/valedopi/config/app.php(65): require_once('/var/www/valedo...') #2 /var/www/valedopi/index.php(10): require_once('/var/www/valedo...') #3 {main} thrown in /var/www/valedopi/vendor/gettext/gettext/src/GettextTranslator.php on line 15" appears.

I changed ARG INSTALL_GETTEXT = true in the Dockerfile in php-fpm and restarted the docker but it still didn't work.
Does anyone have any better suggestions?

**Comment by xiagw** [comment]
> changed ARG INSTALL_GETTEXT = true in the Dockerfile in php-fpm and restarted the docker
not restart , need build

docker-compse up -d --build php-fpm
