### ISSUE TITLE
CertBot  No such file or directory

### ISSUE THREAD

**Issue by lucassmacedo** [laradock/laradock#2679]
Problem to generate cert on localhost

docker-compose up certbot

Starting laradock_certbot_1 ... done
Attaching to laradock_certbot_1
certbot_1              | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1              | Plugins selected: Authenticator webroot, Installer None
certbot_1              | Unable to register an account with ACME server
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/app.test/cert1.pem': No such file or directory
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/app.test/privkey1.pem': No such file or directory
laradock_certbot_1 exited with code 1

  ### Certbot #########################################
  certbot:
    build:
      context: ./certbot
    volumes:
      - ./data/certbot/certs/:/var/certs
      - ./certbot/letsencrypt/:/var/www/letsencrypt
    environment:
      - CN=app.test
      - EMAIL="test@app.test"
    networks:
      - frontend

**Comment by bestlong** [comment]
check debug log `/var/log/letsencrypt/letsencrypt.log`

**Comment by lucassmacedo** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 520, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 182, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 214, in perform_registration
    raise errors.Error(msg)
certbot.errors.Error: The ACME server believes "test@app.test" is an invalid email address. Please ensure it is a valid email and attempt registration again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    load_entry_point('certbot==0.27.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1238, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 641, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 526, in _determine_account
    "Unable to register an account with ACME server")
certbot.errors.Error: Unable to register an account with ACME server

**Comment by lucassmacedo** [comment]
It's on localhost

**Comment by lucassmacedo** [comment]
Hi. Not working yet.

**Comment by china-enoch** [comment]
I had the same problem, Have you solved it ？

![Uploading image.png…]()

**Comment by china-enoch** [comment]
![Uploading image.png…]()

**Comment by china-enoch** [comment]
![Uploading image.png…]()


> Hi. Not working yet.

I had the same problem, Have you solved it ？

**Comment by china-enoch** [comment]
> Hi. Not working yet.

I had the same problem, Have you solved it ？
<img width="842" alt="473829BC-AFF5-433A-A288-B257CD5204D2" src="https://user-images.githubusercontent.com/16871710/102985743-a1d63a80-454a-11eb-8096-27ba707a07c0.png">

**Comment by lucassmacedo** [comment]
Not yet.. a have the same error

**Comment by lucassmacedo** [comment]
Not yet.. a have the same error

**Comment by bestlong** [comment]
This error message

> certbot.errors.Error: The ACME server believes "[test@app.test](mailto:test@app.test)" is an invalid email address. Please ensure it is a valid email and attempt registration again.

u need use real email address.

**Comment by maksimtvg** [comment]
Certbot can't create folder archive
certbot_1              | drwx------ 3 root root 4096 Apr 27 14:43 accounts
certbot_1              | -rw-r--r-- 1 root root  121 Feb 11  2019 cli.ini
certbot_1              | drwxr-xr-x 5 root root 4096 Apr 27 14:43 renewal-hooks
