### ISSUE TITLE
soap extension is not installed despite configuration

### ISSUE THREAD

**Issue by r-yeganeh** [laradock/laradock#2682]
### Description:
I'm trying to enable and use soap but it is not recognized by the system and I'm getting Class 'SoapClient' not found while using it.

### Expected Behavior:
Get the soap work and enabled and get **true** when running **extension_loaded('soap')** by PHP.

### Context information:

**Output of `docker version`**

```
Docker version 19.03.6, build 369ce74a3c
```

**Output of `docker-compose version`**

```
docker-compose version 1.17.1, build unknown
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu 18.04.5 LTS
```

### Steps to reproduce the issue:
In all _php-fpm/phpX.ini_ files I uncommented this line:

`extension=php_soap.dll // uncommented`

In _php-fpm/Dokcerfile_ and _workspace/Dockerfile_ I set this line to true:

`ARG INSTALL_SOAP=true`

And in _.env_ file I got these lines:

    WORKSPACE_INSTALL_SOAP=true
    PHP_FPM_INSTALL_SOAP=true

I build with command:

`docker-compose build --no-cache`

**Comment by millman2394** [comment]
same issue

**Comment by r-yeganeh** [comment]
@millman2394 I figured out that setting `ARG INSTALL_SOAP=false` in php-fpm/Dockerfile and keeping it true in workspace/Dockerfile solves the issue. However, I do not clearly know why this is happening.

**Comment by millman2394** [comment]
@r-yeganeh 

It's a weird isssue for me to. I'm making a Craft CMS project. Initially when I loaded the page, I got the SOAP error. But then after I went to the dashboard, it went away.

I'll check out the Dockerfile next time I start up my environment. I have all SOAP enabled in my `.env` file.

Weird.

**Comment by chavesAnderson** [comment]
I also had the same problem, I followed the process that @r-yeganeh did. However, after docker-compose build --no-cache php-fpm workspace I ran:
docker-compose up -d workspace php-fpm
and it worked.
