### ISSUE TITLE
build php-fpm error.

### ISSUE THREAD

**Issue by jiangzhangy** [laradock/laradock#2692]
execute dokker-compose build php-fpm return a error. as follows:
Get:170 http://mirrors.aliyun.com/debian buster/main amd64 netpbm amd64 2:10.0-15.3+b2 [1029 kB]
E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/p/python3.7/python3.7-minimal_3.7.3-2+deb10u2_amd64.deb  Undetermined Error [IP: 171.220.238.241 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 67.6 MB in 42s (1608 kB/s)
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_IMAGEMAGICK} = true ]; then     apt-get install -y libmagickwand-dev imagemagick &&     pecl install imagick &&     docker-php-ex
t-enable imagick ;fi' returned a non-zero code: 100

**Comment by phpyii** [comment]
I met too

**Comment by Dezeter** [comment]
same

**Comment by z-wp** [comment]
me too

**Comment by youjiaxing** [comment]
.env

set CHANGE_SOURCE to false can fix this.

change UBUNTU_SOURCE won't effect.
