### ISSUE TITLE
There is no existing directory at \"/storage/logs\" and it could not be created: Permission denied

### ISSUE THREAD

**Issue by bido-bido** [laradock/laradock#2701]
### Description:
the PUID and GUID in host and workspace container are the same but give me permission denied

### Expected Behavior:
my all folder and file have read and write permission 
and the user with UID and group with GID are the same on host and workspace container
but I have permission denied error

### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:34 2020
 OS/Arch:           linux/amd64
 Experimental:      false

```

**Output of `docker-compose version`**

```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019


```

**System info: Linux. Include which distro/version**

```
ubuntu 20
```

### Steps to reproduce the issue:

1- when I want to show image or login this error happened :
There is no existing directory at \"/home/devops/Dev/Laravel/designhouse/storage/logs\" and it could not be created: Permission denied
2- how can I solve it?

### Stacktrace & Additional info:
output of host:
```
ls -la
.
.
.
drwxrwsrwx  6 laradock laradock   4096 سپتامبر  2 21:49 storage
.
.

id laradock
uid=1001(laradock) gid=1000(laradock) groups=1000(laradock)

```
as I login to laptop by user devop
output of workspace container: 
```
ls -la
.
.
.
drwxrwsrwx  6 laradock laradock   4096 Sep  2 17:19 storage
.
.

id laradock
uid=1001(laradock) gid=1000(laradock) groups=1000(laradock),8377(docker_env)

```

**Comment by fluffyst** [comment]
Same issue, tried giving www-data owner, still doesn't work, Ubuntu 18.04 here

**Comment by bido-bido** [comment]
> Same issue, tried giving www-data owner, still doesn't work, Ubuntu 18.04 here
> 
> Edit: I believe the laradock user id isn't being set correctly no matter what PUID or GUID I change it to, the laradock user always has the id of 1000, changing `WORKSPACE_PUID / WORKSPACE_PGID` in the `.env` has no effect.
> 
> You can hard code the GUID/PUID in the [ `workspace/Dockerfile` Line 44,](https://github.com/laradock/laradock/blob/master/workspace/Dockerfile#L44) and rebuild workspace and it changes the ID to the default value but doesn't pull from the ENV.

ALready I change the (https://github.com/laradock/laradock/blob/master/workspace/Dockerfile#L44)  but not worked

**Comment by pirex360** [comment]
Any feedback from this ? i also have this problem....

**Comment by MayurVirkar** [comment]
Faced the same problem. In my case, I had to replace

```
PHP_FPM_PUID=1001
PHP_FPM_PGID=1001
```

My advice is to search for *_PUID and *_PGID and replace all with your user.

**Comment by bido-bido** [comment]
> Faced the same problem. In my case, I had to replace
> 
> ```
> PHP_FPM_PUID=1001
> PHP_FPM_PGID=1001
> ```
> 
> My advice is to search for *_PUID and *_PGID and replace all with your user.

I replace all *_PUID and *_PGID with my user and rebuild my docker-compose but not worked.

**Comment by MayurVirkar** [comment]
Try setting up a new stack with these settings.

**Comment by DanielFloris** [comment]
Did anyone work out what is going on here, I've just hit this on a new project.

**Comment by abumosaab** [comment]
If you're using docker, then do the following or similar.
./vendor/bin/sail artisan route:clear
./vendor/bin/sail artisan config:clear
./vendor/bin/sail artisan cache:clear

**Comment by romankm** [comment]
I've faced this problem though had /storage/logs folder with permissions. This helped me: sudo chmod 777 -R storage

**Comment by mariano-pualiu** [comment]
Better of, connect to the workspace as root using `docker-compose exec workspace bash` then change the owner of all the repository files to laravel `chown -R laradock /var/www/` then disconect and connect again as a laradock user `docker-compose exec --user=laradock workspace bash`

**Comment by adam-aido** [comment]
`composer dumpautoload` helped in my case :)

**Comment by CarlosCab19** [comment]
Después de intentar y darle los permisos a todas las carpetas no me funcionaba hasta que corrí este comando 'composer dumpautoload' y ya me funciono, así que si tienen ese problema den los permisos y todo lo que los demás sugieren y por ultimo igual ejecuten ese comando que a mi me funciono, espero les ayude:)

**Comment by shubhammalik19** [comment]
install php-dom
sudo dnf install php-dom
