### ISSUE TITLE
Multiple Projects with apache2

### ISSUE THREAD

**Issue by micha-ried** [laradock/laradock#2702]
Hello there,

I'm currently trying to get multiple projects working on on the laradock apache2 webserver.

What have i done?:

- I copied the sample.conf.example and changed the values 

`<VirtualHost *:80>
  ServerName projekt.test
  DocumentRoot /var/www/projekt/
  Options Indexes FollowSymLinks

  <Directory "/var/www/projekt/">
    AllowOverride All
    <IfVersion < 2.4>
      Allow from all
    </IfVersion>
    <IfVersion >= 2.4>
      Require all granted
    </IfVersion>
  </Directory>

</VirtualHost>`

- then i added the servername to the vhost.conf File with this line
`127.0.0.1  projekt.test`

- then i restarted the container but i doesnt work. When i try to connect to the servername my browser responds, that they cant find the site.

Greetings Micha

**Comment by ikeedo** [comment]
Hey @micha-ried, 

perhaps you need to rebuild the apache2 service:

`docker-compose build apache2`

And try adding a second VirtualHost (with port 443) directive in your config file:

```
<VirtualHost *:443>
  ServerName projekt.test
  …
```

**Comment by ortish** [comment]
I am also running into the same issue. Rebuilding has not helped. Ill try the 443 method, but I tried a hard route of 80 and that didn't work unless it auto redirects
