### ISSUE TITLE
Supervisord not starting on build/up

### ISSUE THREAD

**Issue by bringerofrain** [laradock/laradock#2710]
Supervisor issues error: unix:///tmp/supervisor.sock no such file, keeping me from an supervisor use for Horizon or DB queue.

Internet has not been much help from a docker perspective.

Solutions attempted
- Moving `/etc/supervisord.conf` to `/etc/supervisor.d/` -> Leads to `Cannot assign requested address: file: /usr/lib/python2.7/socket.py line: 57`
- When attempting to `systemctl restart supervisord` -> Leads to `Failed to connect to bus: No such file or directory`

I need help resolving:

1. Being able to restart the Service.
2. Get past supervisor.sock no such file.

`Laradock Version: 3`
Initiation command: `sudo docker-compose up -d nginx mysql redis beanstalkd php-worker`

------Update Edit 09/22/2020 
Updated `Laradock Ver: 4`

I've noticed in both Version 3 & 4 that the standard supervisord.conf was not copied but a base template of the conf file.  I manually overwrote the file in both attempts under version 3& 4 and still get a refused connection.
Because I'm using the inet setting from the laradock conf file my errors are in line with that.  Docker's were stopped and reupped with all changes.

Conf file

```
[supervisord]
nodaemon=true
[supervisorctl]
serverurl=http://127.0.0.1:9001
[inet_http_server]
port=127.0.0.1:9001
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = supervisord.d/*.conf
```

Run `supervisorctl`
Response: `error: <class 'socket.error'>, [Errno 99] Cannot assign requested address: file: /usr/lib/python2.7/socket.py line: 575`

Run `supervisorctl -c /etc/supervisord.conf -s http://127.0.0.1:9001`
Response: `http://127.0.0.1:9001 refused connection`

Any help would be appreciated.

**Comment by bringerofrain** [comment]
Shameless Bump.

**Comment by bringerofrain** [comment]
Ok, here's the issue.  Suprervisord was not starting on build/up. Needed to run after build/up
`Sudo docker exec -it laradock_workspace_1 bash -c "supervisord -n -c /etc/supervisord.conf"`

**Comment by jhoanborges** [comment]
> Ok, here's the issue. Suprervisord was not starting on build/up. Needed to run after build/up `Sudo docker exec -it laradock_workspace_1 bash -c "supervisord -n -c /etc/supervisord.conf"`

Everytime containers are down i needed to re-build php-fpm and workspace, now i just eddited this to re-run supervisor without any problem
`sudo docker exec -d laradock_workspace_1 bash -c "supervisord -n -c /etc/supervisord.conf"`

Just added -d instead -it to run in background.

**Comment by simonbuehler** [comment]
shouldn't supervisod autostart? is there a config for it?

**Comment by simonbuehler** [comment]
related: #2442

**Comment by alvaro-canepa** [comment]
> Everytime containers are down i needed to re-build php-fpm and workspace, now i just eddited this to re-run supervisor without any problem `sudo docker exec -d laradock_workspace_1 bash -c "supervisord -n -c /etc/supervisord.conf"`
> 
> Just added -d instead -it to run in background.

For [docker compose 2](https://docs.docker.com/compose/compose-v2/) (not docker-compose) use:
`docker exec -d laradock-workspace-1 bash -c "supervisord -n -c /etc/supervisord.conf"`

**Comment by xcesaralejandro** [comment]
Is there any news for this? I'm going crazy.

Beyond the problems mentioned by the author and the solution provided, I think it is inelegant to depend on a manual action for something that should be in the Dockerfile, that is, to be able to add the command without having to depend on an exec.

In my case, all the problems identified with the socket are mainly due to the fact that supervisord (the daemon) is not starting as a service from the beginning and therefore does not create its corresponding socket.

If after the container has been built I do an exec or login to the container to start the service with: `service supervisor start` everything works correctly, my socket is created and the supervisorctl command works normally.

The problem is that when I add that command as CMD, in my ENTRYPOINT or in the execution of a .SH for the entrypoint, the service is not starting up.

This brings a lot of problems because if the container is restarted the service dies.

**Comment by xcesaralejandro** [comment]
I have found the solution almost by magic, after trying a thousand things.

**Before (Not working)**
````
ENTRYPOINT ["/bin/bash","-c","apache2-foreground && service supervisor start"]
````

**After (Working)**
````
ENTRYPOINT ["/bin/bash","-c","service supervisor start && apache2-foreground"]
````
In my case, the initialization of apache2-foreground meant that the service was not initialized, when I tried with the ubuntu image I don't know what really happened, what I want to get by sharing this solution is that depending on the image, there may be processes which are unknown and block the initialization of supervisor (in this case) or other service.

The image used is: ````FROM php:8.1-apache````

**Comment by warsemann** [comment]
Hi, where you modify this please ? I m the same problem, queue works when i manually start but not when restart container

**Comment by xcesaralejandro** [comment]
> Hi, where you modify this please ? I m the same problem, queue works when i manually start but not when restart container

First make sure that there is no other service preventing the initialization of supervisord.

Then use "docker inspect CONTAINER_NAME" to see what the entry point of your image is so  you can include it manually at final of  .sh 

When defining my entrypoint I overwrite the one in the image, I use a call to a .sh file to configure my server (the entrypoint is called whenever the container is started, be careful with code that can execute duplicate actions). My .sh file looks like this:

````
service cron start
service supervisor start
supervisorctl reread && supervisorctl update
supervisorctl start all
apache2-foreground
````

and in my dockerfile:

````
ENTRYPOINT ["/tini", "--", "/tmp/init.sh"]
````

If you notice, starting Apache before supervisord was what gave me problems, so I make sure to start the supervisor service first and update its configuration (it will do this only when the container starts).

There is probably a technical explanation for why this happens, but I don't know it and as I have defined it, my application has been working correctly for many months, even when there are other processes in my application that are responsible for stopping and resuming work queues.

**Comment by warsemann** [comment]
Hi thanks for the response, i dont think i have the same problem, supervisor start correctly at container startup but laravel queue dont start. When i run sudo docker exec -d laradock_workspace_1 bash -c "supervisord -n -c /etc/supervisord.conf" the queue start correctly, but when i start or stop supervisor nothing happen , my apps-worker :

`[program:intranet-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/intranet/artisan queue:work redis
autostart=true
autorestart=true
numprocs=2
user=laradock
redirect_stderr=true
stdout_logfile=/var/www/intranet/log/laravel-queue.log`
