### ISSUE TITLE
ERROR: expr: syntax error

### ISSUE THREAD

**Issue by WDZThorn** [LaraDock/laradock#272]
When I run `./xdebugPhpFpm start` in terminal, it show `expr: syntax error`. My system version is `osx 10.11.6`, is there some problem run `$(expr substr $(uname -s) 1 5)` on osx?

**Comment by WDZThorn** [comment]
I typed this code to fix the problem.

```
if [[ "$(uname)" == "Darwin" ]]; then
    OS_TYPE="OSX"
else
    OS_TYPE=$(expr substr $(uname -s) 1 5)
fi
```
and change 
`if [[ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]]; then`
to
`if [[ $OS_TYPE == "MINGW" ]]; then`
it work correct.

**Comment by LarryEitel** [comment]
@WDZThorn Could you verify this merge works for you? Then this issue can be closed. :)

**Comment by WDZThorn** [comment]
@LarryEitel It's ok.
