### ISSUE TITLE
PHPStorm debugging guide link missing

### ISSUE THREAD

**Issue by simonbuehler** [laradock/laradock#2736]
hi,

https://laradock.io/documentation/#phpstorm-debugging-guide leads to https://laradock.io/guides/ which is a 404

**Comment by terry-lonesski** [comment]
That link is still broken

**Comment by bestlong** [comment]
https://github.com/laradock/laradock/commit/5c10a024f1d61c99c42d5cb53694f760f00d051e

**Comment by matthew-cupist** [comment]
[That link](https://laradock.io/guides/#PHPStorm-Debugging) is still broken
