### ISSUE TITLE
apache2: oci runtime error

### ISSUE THREAD

**Issue by tblancog** [LaraDock/laradock#274]
I have followed the readme, I got Ubuntu 14.04 and when I invoke:
$ docker-compose up -d apache2 mongo php-fpm mariadb

Removing laradock_apache2_1
Starting laradock_volumes_data_1
Starting laradock_volumes_source_1
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
Recreating c419d01e5058_c419d01e5058_laradock_apache2_1
laradock_mongo_1 is up-to-date
Recreating laradock_mariadb_1

ERROR: for apache2 Cannot start service apache2: oci runtime error: no such file or directory
ERROR: Encountered errors while bringing up the project.

I can't figure out what's' going on, I already changed the port to an unused one.

**Comment by alejodaraio** [comment]
same error here :/

**Comment by ssilvan** [comment]
Same error as well; has anyone figured out how to fix this?

**Comment by cool14521** [comment]
+1

**Comment by Mahmoudz** [comment]
I think this error is the same as this https://github.com/LaraDock/laradock/issues/277

**Comment by HeidemannMarkus** [comment]
+1

**Comment by altjsus** [comment]
I had this problem. That's how I managed to solve it:
- install laravel with composer **first**. made `git init `and added laradock as a submodule
- changed laradock/workspace container port to 666. then `docker-compose build workspace `
- `docker-compose up -d apache2 mysql
Works!

**Comment by wtwei** [comment]
+111111

**Comment by philtrep** [comment]
@wtwei could the fix from @altjsus also apply to you?

**Comment by Mahmoudz** [comment]
Is this solved or not yet!!

**Comment by tblancog** [comment]
Yes, this is solved, thanks a lot @Mahmoudz and everyone!
