### ISSUE TITLE
MySQL service not working with docker desktop 2.4.0.0

### ISSUE THREAD

**Issue by yaquawa** [laradock/laradock#2740]
### Description:
seems like the mysql service exit with an error. 
I found this issue after I updated my docker desktop(mac) to version 2.4.0.0
I've tried rebuild the mysql service, but still not working.

```
docker-compose up -d mysql nginx workspace

...
...
...

docker-compose exec mysql bash
ERROR: No container found for mysql_1

...
...
...

docker-compose ps
           Name                          Command              State                                                                       Ports                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh           Up       2375/tcp, 2376/tcp                                                                                                                          
laradock_mysql_1              docker-entrypoint.sh mysqld     Exit 1                                                                                                                                               
laradock_nginx_1              /bin/bash /opt/startup.sh       Up       0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:81->81/tcp                                                                                
laradock_php-fpm_1            docker-php-entrypoint php-fpm   Up       9000/tcp                                                                                                                                    
laradock_workspace_1          /sbin/my_init                   Up       0.0.0.0:2222->22/tcp, 0.0.0.0:3000->3000/tcp, 0.0.0.0:3001->3001/tcp, 0.0.0.0:4200->4200/tcp, 0.0.0.0:8001->8000/tcp, 0.0.0.0:8080->8080/tcp
```

### Context information:

**Output of `git rev-parse HEAD`**

```
89c9cfe09941bead05d63ec3c0fe9b9173ce0526
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
MacOS 10.15.6
```

### Steps to reproduce the issue:

1. `docker-compose up -d mysql nginx workspace`
2. `docker-compose exec mysql bash`

**Comment by shlk20** [comment]
I meet the same issue as yours, still haven't resolved yet.  Can anyone help us to solve this problem?

**Comment by shlk20** [comment]
> ### Description:
> seems like the mysql service exit with an error.
> I found this issue after I updated my docker desktop(mac) to version 2.4.0.0
> I've tried rebuild the mysql service, but still not working.
> 
> ```
> docker-compose up -d mysql nginx workspace
> 
> ...
> ...
> ...
> 
> docker-compose exec mysql bash
> ERROR: No container found for mysql_1
> 
> ...
> ...
> ...
> 
> docker-compose ps
>            Name                          Command              State                                                                       Ports                                                                    
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> laradock_docker-in-docker_1   dockerd-entrypoint.sh           Up       2375/tcp, 2376/tcp                                                                                                                          
> laradock_mysql_1              docker-entrypoint.sh mysqld     Exit 1                                                                                                                                               
> laradock_nginx_1              /bin/bash /opt/startup.sh       Up       0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:81->81/tcp                                                                                
> laradock_php-fpm_1            docker-php-entrypoint php-fpm   Up       9000/tcp                                                                                                                                    
> laradock_workspace_1          /sbin/my_init                   Up       0.0.0.0:2222->22/tcp, 0.0.0.0:3000->3000/tcp, 0.0.0.0:3001->3001/tcp, 0.0.0.0:4200->4200/tcp, 0.0.0.0:8001->8000/tcp, 0.0.0.0:8080->8080/tcp
> ```
> 
> ### Expected Behavior:
> ### Context information:
> **Output of `git rev-parse HEAD`**
> 
> ```
> 89c9cfe09941bead05d63ec3c0fe9b9173ce0526
> ```
> 
> **Output of `docker version`**
> 
> ```
> Client: Docker Engine - Community
>  Cloud integration  0.1.18
>  Version:           19.03.13
>  API version:       1.40
>  Go version:        go1.13.15
>  Git commit:        4484c46d9d
>  Built:             Wed Sep 16 16:58:31 2020
>  OS/Arch:           darwin/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.13
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       4484c46d9d
>   Built:            Wed Sep 16 17:07:04 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          v1.3.7
>   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> **Output of `docker-compose version`**
> 
> ```
> docker-compose version 1.27.4, build 40524192
> docker-py version: 4.3.1
> CPython version: 3.7.7
> OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
> ```
> 
> **System info: Mac, Windows or Linux. Include which disto/version**
> 
> ```
> MacOS 10.15.6
> ```
> 
> ### Steps to reproduce the issue:
> 1. `docker-compose up -d mysql nginx workspace`
> 2. `docker-compose exec mysql bash`

Found the solution, https://github.com/laradock/laradock/issues/2732#issuecomment-703026101

**Comment by yaquawa** [comment]
@shlk20 Thanks a lot!
