### ISSUE TITLE
build workspace failed

### ISSUE THREAD

**Issue by pndx** [laradock/laradock#2759]
**System information**
macOS Catalina Version 10.15.7

**Description:**
run `docker-compose build workspace` failed on `apt-get update -yqq`.

**Context information:**
```
Building workspace
Step 1/291 : ARG LARADOCK_PHP_VERSION
Step 2/291 : ARG BASE_IMAGE_TAG_PREFIX=latest
Step 3/291 : FROM laradock/workspace:${BASE_IMAGE_TAG_PREFIX}-${LARADOCK_PHP_VERSION}
 ---> 20591799e8a7
Step 4/291 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Using cache
 ---> 20aab26ea475
Step 5/291 : ARG LARADOCK_PHP_VERSION
 ---> Using cache
 ---> f1012c55d75a
Step 6/291 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> d32e63bea97e
Step 7/291 : ARG CHANGE_SOURCE=false
 ---> Using cache
 ---> 1208f7b59a5a
Step 8/291 : RUN if [ ${CHANGE_SOURCE} = true ]; then     sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list ;fi
 ---> Using cache
 ---> 3d8abd1e9a9b
Step 9/291 : USER root
 ---> Using cache
 ---> 79cd52cc8f0c
Step 10/291 : ARG PUID=1000
 ---> Using cache
 ---> 372a29f76c51
Step 11/291 : ENV PUID ${PUID}
 ---> Using cache
 ---> 4590d453a70e
Step 12/291 : ARG PGID=1000
 ---> Using cache
 ---> 57d71464df3f
Step 13/291 : ENV PGID ${PGID}
 ---> Using cache
 ---> ef0eb4e4987e
Step 14/291 : ARG CHANGE_SOURCE=false
 ---> Using cache
 ---> ed44f8eb2260
Step 15/291 : ARG UBUNTU_SOURCE
 ---> Using cache
 ---> 5a442503a225
Step 16/291 : COPY ./sources.sh /tmp/sources.sh
 ---> Using cache
 ---> 4dd8afbd3ff3
Step 17/291 : RUN if [ ${CHANGE_SOURCE} = true ]; then     chmod +x /tmp/sources.sh &&     /bin/sh -c /tmp/sources.sh &&     rm -rf /tmp/sources.sh ;fi
 ---> Using cache
 ---> fb3974df7d31
Step 18/291 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'
 ---> Running in ed1cac11881f
+ apt-get update -yqq
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  503  Service Unavailable [IP: 91.189.88.152 80]
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is no longer signed.
ERROR: Service 'workspace' failed to build : The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 100
```
run `docker-compose build workspace` serval times and get some error:
```
ERROR: `phpize' failed
ERROR: Service 'workspace' failed to build : The command '/bin/sh -c if [ ${INSTALL_AST} = true ]; then     if [ $(php -r "echo PHP_MAJOR_VERSION;") != "5" ]; then         printf "\n" | pecl -q install ast-${AST_VERSION} &&         echo "extension=ast.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/ast.ini &&         phpenmod -v ${LARADOCK_PHP_VERSION} -s cli ast     ;fi ;fi' returned a non-zero code: 1
``` 
tried everything and got some more errors:
```
+ apt-get update -yqq
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  503  Service Unavailable [IP: 91.189.88.152 80]
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is no longer signed.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  503  Service Unavailable [IP: 91.189.88.152 80]
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports InRelease' is no longer signed.
```
after change source list , got error below:
```
Step 122/291 : ENV AST_VERSION ${AST_VERSION}
 ---> Using cache
 ---> 96daeeba1a1c
Step 123/291 : RUN if [ ${INSTALL_AST} = true ]; then     if [ $(php -r "echo PHP_MAJOR_VERSION;") != "5" ]; then         printf "\n" | pecl -q install ast-${AST_VERSION} &&         echo "extension=ast.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/ast.ini &&         phpenmod -v ${LARADOCK_PHP_VERSION} -s cli ast     ;fi ;fi
 ---> Running in 5673700ebc4b
ERROR: `/tmp/pear/temp/ast/configure --with-php-config=/usr/bin/php-config' failed
ERROR: Service 'workspace' failed to build : The command '/bin/sh -c if [ ${INSTALL_AST} = true ]; then     if [ $(php -r "echo PHP_MAJOR_VERSION;") != "5" ]; then         printf "\n" | pecl -q install ast-${AST_VERSION} &&         echo "extension=ast.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/ast.ini &&         phpenmod -v ${LARADOCK_PHP_VERSION} -s cli ast     ;fi ;fi' returned a non-zero code: 1
```
**Docker version**:
```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by Eight0** [comment]
same problom

**Comment by pndx** [comment]
Still the same message, don't know what is the problem.

**Comment by exSnake** [comment]
Mine stop here

`Step 18/291 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'
 ---> Running in 0390aade2977
+ apt-get update -yqq
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 1h 42min 30s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 1h 41min 44s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 1h 43min 23s). Updates for this repository will not be applied.
ERROR: Service 'workspace' failed to build : The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 100`

**Comment by exSnake** [comment]
`Step 18/291 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'
 ---> Running in 0390aade2977
+ apt-get update -yqq
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 1h 42min 30s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 1h 41min 44s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 1h 43min 23s). Updates for this repository will not be applied.
ERROR: Service 'workspace' failed to build : The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g ${PGID} laradock &&     useradd -u ${PUID} -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php${LARADOCK_PHP_VERSION}-zip       nasm &&       php -m | grep -q 'zip'' returned a non-zero code: 100`
