### ISSUE TITLE
Bind for 0.0.0.0:22 failed: port is already allocated

### ISSUE THREAD

**Issue by dshiells** [LaraDock/laradock#276]
I want to run `docker-compose up -d nginx mysql`, but am getting an error:

> Bind for 0.0.0.0:22 failed: port is already allocated

Nothing is using port 22 (as far as I'm aware) before running this. Any ideas?

> damienshiells@MacBook-Pro-2 laradock (master) $ lsof -i tcp:22
damienshiells@MacBook-Pro-2 laradock (master) $ docker-compose up -d nginx mysql
Creating network "laradock_default" with the default driver
Creating laradock_volumes_source_1
Creating laradock_volumes_data_1
Creating laradock_workspace_1
Creating laradock_mysql_1
Creating laradock_php-fpm_1

> ERROR: for php-fpm  Cannot start service php-fpm: driver failed programming external connectivity on endpoint laradock_php-fpm_1 (27854cece00612e3b61fce9db84524ad59e66f7ea571e345f71358daea4ca1ed): Bind for 0.0.0.0:22 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
damienshiells@MacBook-Pro-2 laradock (master) $ lsof -i tcp:22
COMMAND    PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 1564 damienshiells   20u  IPv4 0x3cb5866d777d4fcf      0t0  TCP *:ssh (LISTEN)

**Comment by dshiells** [comment]
I changed the workspaces ports from `22:22` to `2201:22`. Mac must secretly have something bound to port 22 already. Anyway, works now :)

**Comment by morales2k** [comment]
I found this error as well, and ran: 
`netstat -lp | grep 2222`  
The relevant return line:
```
tcp6       0      0 [::]:2222               [::]:*                  LISTEN      4546/docker-proxy
```
That allowed me to find out what was hanging onto that port and discovered it was `4546/docker-proxy` (whatever that is)  I'm not too docker savvy, but I know laradock workspace had absolutely no problems running on that port for ssh, now it is choking and I had to switch the port to something else as that was being used. Ran that netstat again and looked for docker-proxy instead... here's all it has it's nose in:
```tcp6       0      0 [::]:mysql              [::]:*                  LISTEN      28843/docker-proxy  
tcp6       0      0 [::]:6379               [::]:*                  LISTEN      29077/docker-proxy  
tcp6       0      0 [::]:2222               [::]:*                  LISTEN      4546/docker-proxy   
tcp6       0      0 [::]:http               [::]:*                  LISTEN      31281/docker-proxy  
tcp6       0      0 [::]:9010               [::]:*                  LISTEN      28733/docker-proxy  
tcp6       0      0 [::]:8087               [::]:*                  LISTEN      4470/docker-proxy   
tcp6       0      0 [::]:https              [::]:*                  LISTEN      31267/docker-proxy  
tcp6       0      0 [::]:2722               [::]:*                  LISTEN      30749/docker-proxy
```

I have no idea what this docker-proxy process is and/or why is it needed now, as opposed to all the time I've been using docker and this never happened.... Will have to keep looking for more info and see....
