### ISSUE TITLE
 Cannot start service workspace: oci runtime error: no such file or director

### ISSUE THREAD

**Issue by majuansari** [LaraDock/laradock#277]
```
 docker-compose up apache2
Starting laradock_volumes_source_1
Starting laradock_workspace_1

ERROR: for workspace  Cannot start service workspace: oci runtime error: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

I am getting the above mentioned error . Can any one help me out here please ?

**Comment by qq447665722** [comment]
You have found the answer yet?

**Comment by ssilvan** [comment]
Same issue here; any fix?

**Comment by cool14521** [comment]
+1

**Comment by ssilvan** [comment]
It is working now for me. What I did was to execute:
git clone https://github.com/LaraDock/laradock.git

IN THE LARAVEL APP DIRECTORY. It is very important to have a laravel application ready before cloning the repository by executing first:
composer create-project laravel/laravel your_application_name

After the application has been created go to the "your_application_name" directory and clone the laradock repository. This will create a laradock directory under your application; cd to laradock directoy and execute "docker-compose up -d  apache2 mysql"

That worked for me, hope this helps!

**Comment by tblancog** [comment]
It's not working for me, I did as you said from an ubuntu and docker fresh installation, it just shows this error:
`$ docker-compose up -d apache2 mysql

ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
`

**Comment by Mahmoudz** [comment]
If this is related to #274 then it's solved :) if not reopen :(

**Comment by ssilvan** [comment]
Glad to see it worked for you tblancog; indeed you need to have docker version 1.7 at least.
