### ISSUE TITLE
Build workspace faild with install PHP V8JS

### ISSUE THREAD

**Issue by ttungbmt** [laradock/laradock#2775]
### Description:
WORKSPACE_INSTALL_V8JS=false

![bug-v8js](https://user-images.githubusercontent.com/12232155/99360904-de779c00-28e3-11eb-9b6d-9417e4302db5.png)

### Expected Behavior:
Build image successful with option WORKSPACE_INSTALL_V8JS set to TRUE

### Context information:

**Output of `git rev-parse HEAD`**

```
89c9cfe09941bead05d63ec3c0fe9b9173ce0526
```

**Output of `docker version`**

```
Docker version 19.03.13, build 4484c46d9d 
```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 10
```

### Steps to reproduce the issue:

1.Set: WORKSPACE_INSTALL_PNPM=true
2.docker-compose build workspace

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by Jedliu** [comment]
When I encounter the 404 error when build, I will try to build --no-cache. Check if this works.
```
docker-compose build --no-cache workspace
```
