### ISSUE TITLE
chmod() Operation not permitted

### ISSUE THREAD

**Issue by muzammilaskari** [laradock/laradock#2776]
Hi,

First of all many thanks for such a wonderful package for docker support. I want to ask that when I enter the Workspace container:
`docker-compose exec --user=laradock workspace bash`
and after that I run composer install but I see an error which is like
```
In Filesystem.php line 205:
chmod() Operation not permitted
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
but if I enter in the workspace container as root user then everything works well but in my project whenever I try to upload any file I see same exception thrown by laravel

`chmod() Operation not permitted`

how do I make this permission work correctly?

FYI - I am using Ubuntu 18.04

**Comment by clubcube** [comment]
Hey folks!
Got the error by
`sail artisan route:cache`

`
In Filesystem.php line 205:
chmod(): Operation not permitted
`

Using Docker on Windows 10.

**Comment by lpupopena** [comment]
Hi:

It works for me:

sudo umount /mnt/c sudo mount -t drvfs C: /mnt/c -o metadata

https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/

**Comment by iiismail** [comment]
Got this error running php artisan migrate on a Laravel project

**Comment by frankamente** [comment]
> Got this error running php artisan migrate on a Laravel project

I faced this problem too.

To solve it, I moved all my project from /mnt/c/Users/... to ~/laravel/...

I close all terminals and then I had no problem with the migration in a new terminal.

Hope it works for you too.
