### ISSUE TITLE
Add newrelic as an option to the PHP extensions installation

### ISSUE THREAD

**Issue by DrowningElysium** [laradock/laradock#2777]
**Is your feature request related to a problem? Please describe.**
Hello for our project we use a service called newrelic. This has also been added in our composer.json which makes it so we need to have it locally too. I would love to be able to install this extension in Laradock. 

If it can't be supported officially I love to get some instructions on how to add it myself. I wasn't able to find this out by looking at the docker file (I am new to docker).

**Additional context**
Installation instructions that I got:
```
echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | sudo tee /etc/apt/sources.list.d/newrelic.list
wget -O- https://download.newrelic.com/548C16BF.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install newrelic-php5
sudo newrelic-install install
```
Docs about installation:
https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian

Docs about preseeding:
https://docs.newrelic.com/docs/agents/php-agent/installationaphp-agent-installation-ubuntu-debian#preseeding

**Comment by DrowningElysium** [comment]
What I've tried adding to php-fpm/Dockerfile and workspace/Dockerfile is:
```
###########################################################################
# NEWRELIC:
###########################################################################

USER root

ARG INSTALL_NEWRELIC=false

RUN if [ ${INSTALL_NEWRELIC} = true ]; then \
 	echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | sudo tee /etc/apt/sources.list.d/newrelic.list \
	&& wget -O- https://download.newrelic.com/548C16BF.gpg | sudo apt-key add - \
	&& apt-get update -yqq \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y install newrelic-php5 \
;fi
```

After installation I still get that the extension is not enabled. I've added it to the .env and set it to true.

**Comment by calebanthony** [comment]
This is already a PR: https://github.com/laradock/laradock/pull/2755

**Comment by DrowningElysium** [comment]
My bad. I didn't see it at the time. But also there is an issue with the PR. And I am not sure if it is still gonna be fixed or merged.
