### ISSUE TITLE
Fresh Laravel jetstream project is unable to run on Laradock

### ISSUE THREAD

**Issue by daniloesser** [laradock/laradock#2787]
### Description:
Hi guys! 
I've been trying to set up a new Laravel Jetstream install but it looks like something "internal" in Nginx or so is preventing the Laravel app from rendering the Livewire components properly. It hangs and after some time it shows a lot of warnings.

P.S: If I try to run the project ignoring the nginx/php-fpm (using php artisan serve instead) everything runs fine. So it's clearly an "environment" problem since it's a common PHP project.  I've reviewed all file permissions and everything looks good. 

**System info: **
- Latest Laradock version, 
- Windows 10 build 19042, 
- Docker desktop 2.5.0.1 running on Hyper-V mode

### Steps to reproduce the issue:
0. Install latest laradock as git submodule
1. Build and run => "php-fpm, nginx, postgres, workspace and mailhog"
2. From workspace , Install laravel installer => "composer global require laravel/installer"
3. Set up a new project with Jetstream => "laravel new test-project --jet"
4. Pick stack [0] - Livewire, as a frontend option
5. From workspace => "npm install && npm run dev"
6. From workspace => update laravel's ".env" with proper hosts and run "php artisan migrate"
7. Register a new user and try to navigate to the initial Dashboard page.

### Stacktrace & Additional info:
```
[36mphp-fpm_1              |[0m NOTICE: PHP message: PHP Warning:  Uncaught InvalidArgumentException: No hint path defined for [<?php extract(collect($attributes->getAttributes())->mapWithKeys(function ($value, $key) { return [Illuminate\Support\Str]. in /var/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112
[36mphp-fpm_1              |[0m Stack trace:
[36mphp-fpm_1              |[0m #0 /var/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments('<?php extract(c...')
[36mphp-fpm_1              |[0m #1 /var/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView('<?php extract(c...')
[36mphp-fpm_1              |[0m #2 /var/www/vendor/laravel/framework/src/Illuminate/View/Factory.php(272): Illuminate\View\FileViewFinder->find('<?php extract(c...')
[36mphp-fpm_1              |[0m #3 /var/www/vendor/laravel/framework/src/Illuminate/View/Component.php(78): Illuminate\View\Factory->exists('<?php extract(c...')
[36mphp-fpm_1              |[0m #4 /var/www/vendor/laravel/framework/src/Illuminate/View/Component.php(84): Illuminate\View\Component->Illuminate\View\{closure}('<?php extract(c...')
[36mphp-fpm_1              |[0m #5 /var/www/vendor/ in /var/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 112
[36mphp-fpm_1              |[0m NOTICE: PHP message: PHP Stack trace:
[36mphp-fpm_1              |[0m NOTICE: PHP message: PHP   1. {main}() /var/www/public/index.php:0
...................
```

**Comment by lionslair** [comment]
I am having a weird issue to. Ended up rebuilding workspace and php-fpm today. Have now done it from fresh (all of them) many times. each time we hit the php page through the browser the php-fpm container runs wild until all RAM is gone and crashes.

Not getting any log for what the issue is. Have tried changing docker images and all sorts. Same result every time.

**Comment by lionslair** [comment]
My issue was xdebug

**Comment by daniloesser** [comment]
Yeah, that could be applied to my case as well, because the only flags that I've turned on inside laradock's env file were the xdebug ones.  Maybe it can be related. I'll try to run it without xdebug to and see.

**Comment by Mailzas** [comment]
I am novice for laravel, but why you not running "composer install"

**Comment by Jedliu** [comment]
Check with this issue if it helps. I'm encountering the problem after xdebug is enabled. #2792

**Comment by daniloesser** [comment]
Thanks @Jedliu , I've changed all Xdebug flags to false on the .env file and now everything runs smoothly.  Since there are a lot of other similar issues reported, I'll close this one.
