### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by majuansari** [LaraDock/laradock#279]
`PDOException in Connector.php line 119:
could not find driver`

I created a vhost. Not sure what is the issue . artisan migrate is working fine from console.

But not working from php . Can anyone help please ?

**Comment by Mahmoudz** [comment]
@majuansari if you haven't solved this problem, consider reopening this issue and explaining more, how are you doing and how. so we can understand exactly what the problem is and hopefully help. Best
