### ISSUE TITLE
Xdebug stop alone

### ISSUE THREAD

**Issue by stephanesoares** [laradock/laradock#2791]
Hello everyone, when I'm debugging, it ends the process alone. It only happens since upgrading to xdebug 3. Does anyone know how to fix it?

**Comment by jonpage999** [comment]
I've added two issues recently #2794 and #2792, these both include solutions that will force the installation of xDebug v2. I'd say that's the correct solution as it works with the bundled xdebug ini files, and will work with any manual updates you've made.

Alternatively the solution is to rewrite the ini files for xDebug v3 compatibility, but certain older PHP versions (I believe 7.1 and below) aren't compatible with xDebug v3, so you'd need to be aware of that.

**Comment by stephanesoares** [comment]
> I've added two issues recently #2794 and #2792, these both include solutions that will force the installation of xDebug v2. I'd say that's the correct solution as it works with the bundled xdebug ini files, and will work with any manual updates you've made.
> 
> Alternatively the solution is to rewrite the ini files for xDebug v3 compatibility, but certain older PHP versions (I believe 7.1 and below) aren't compatible with xDebug v3, so you'd need to be aware of that.

Yes i made your changes and its working. But it would be nice to get support for xdebug v3 and of course php8

**Comment by jonpage999** [comment]
You won't get any argument from me, but I think that's a separate issue.
