### ISSUE TITLE
How hidden PHP version?

### ISSUE THREAD

**Issue by carveybunt** [laradock/laradock#2796]
As security, I need to hidden the PHP version, but I don't where will be to set the 'expose_php Off' of 'php.ini' in the container php-fpm or workspace? Somebody was trying to do that, can share your setting? Thanks a lot for you.

**Comment by jonpage999** [comment]
@carveybunt Hiding the version doesn't do a lot to increase your security, but the ini files all exist in the php-fpm folder. Change the ini file for the version you're running and rebuild php-fpm.

**Comment by carveybunt** [comment]
@jonpage999 Thank you. I'll try it later，because I thought it was in the workspace container, so I tried to modify php.ini in the workspace container without success, so I went to ask for help.
