### ISSUE TITLE
when i change laravel controller file, but it do not change in container of php-fpm,workspace,nginx

### ISSUE THREAD

**Issue by qingdi** [laradock/laradock#2798]
### Description:

when i change laravel controller file, but it do not change in container of php-fpm,workspace,nginx.

### Context information:

**Output of `docker version`**

```
docker 3.0.1
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
mac 11.1
```

### Steps to reproduce the issue:

1. docker build php-fpm nginx workspace mysql mongo
2. docker up -d php-fpm nginx workspace mysql mongo
3. visit url
4. everything is fine now
5. when i edit php file. the changed file not change in container

anyone encounter this problem??

**Comment by glitterlip** [comment]
same problem here.
After rebuild php-fpm container, I check phpinfo message to make sure opcache is not enabled, and code change on host is fine.But after a while , any change made in host doesnt work in container,I mean every change, restart php-fpm container change nothing. Seems like a opcache issue but I check the php-container opcache.ini, its disabled

**Comment by d-pollard** [comment]
I thought I was going crazy; seems to work for a while then I have to kill all the docker processes and restart docker for my changes to appear. Its become more fighting with docker than actual development time

**Comment by glitterlip** [comment]
> I thought I was going crazy; seems to work for a while then I have to kill all the docker processes and restart docker for my changes to appear. Its become more fighting with docker than actual development time

me too. Thank you for your reply, now I just need restart Docker instead of rebuild container every this problem occurs.

**Comment by d-pollard** [comment]
@glitterlip - I'm going to try out the docker sync setup that comes with laradock and see if that makes any difference

**Comment by d-pollard** [comment]
Related docker issue: https://github.com/docker/for-mac/issues/5046

**Comment by glitterlip** [comment]
> Related docker issue: [docker/for-mac#5046](https://github.com/docker/for-mac/issues/5046)

should be this problem.

**Comment by qingdi** [comment]
i back docker version。

> same problem here.
> After rebuild php-fpm container, I check phpinfo message to make sure opcache is not enabled, and code change on host is fine.But after a while , any change made in host doesnt work in container,I mean every change, restart php-fpm container change nothing. Seems like a opcache issue but I check the php-container opcache.ini, its disabled

it is not about opcache。i had checked。file not change。i back docker version 2.5.0.1。
