### ISSUE TITLE
restarted redis should not be set as "always"

### ISSUE THREAD

**Issue by metal3d** [LaraDock/laradock#28]
Hi,

At line https://github.com/LaraDock/laradock/blob/master/docker-compose.yml#L40 you set "restart: always" that makes redis to be restarted each time I restart my laptop.

You should remove this line to let it start only when we need the compose stack to be up.

Thanks :)

**Comment by Mahmoudz** [comment]
Done. 530ffe7

**Comment by metal3d** [comment]
Thanks a lot and thanks again for this repository.
