### ISSUE TITLE
How solve  can't connect to raw.githubusercontent.com ?

### ISSUE THREAD

**Issue by carveybunt** [laradock/laradock#2800]
Had some way installed Laradock latest in CentOS 8 if I unlucky can't connect to `raw.githubusercontent.com`?

**Comment by lihhil** [comment]
手工添加到 hosts 文件:
199.232.28.133 raw.githubusercontent.com

**Comment by carveybunt** [comment]
> 手工添加到 hosts 文件:
> 199.232.28.133 raw.githubusercontent.com
多谢，已经解决。
