### ISSUE TITLE
Invalid compose .yml (clickhouse)

### ISSUE THREAD

**Issue by glorand** [laradock/laradock#2802]
![Screenshot from 2020-12-21 13-19-38](https://user-images.githubusercontent.com/883989/102771872-4744af00-438f-11eb-8575-2434f1c0fb01.png)

In case of clickhouse params missing form ".env" environment file

**Comment by jcannata** [comment]
I just pulled the latest changes and am now getting the same error. Previously I was working with commit 2f575017e440a336e4a02d346d86ed6d16898ee0 without issue.

**Comment by jcannata** [comment]
Solved. The env-example was updated with the appropriate CLICKHOUSE variables however I did not copy them to my .env file.

**Comment by calebanthony** [comment]
The problem with all these updates is when they add ports. I have a spot at the bottom of my `.env` file that I add the port variable and just set it to 0. When it's blank, it breaks.
