### ISSUE TITLE
docker-compose up -d certbot Fail

### ISSUE THREAD

**Issue by china-enoch** [laradock/laradock#2803]
### Description:
docker-compose up -d certbot
Building certbot
Step 1/6 : FROM phusion/baseimage:bionic-1.0.0
 ---> 32c929dd2961
Step 2/6 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Using cache
 ---> 765d1aded17a
Step 3/6 : COPY run-certbot.sh /root/certbot/run-certbot.sh
 ---> Using cache
 ---> 30888cdd5df1
Step 4/6 : RUN apt-get update
 ---> Using cache
 ---> 26617a619f6d
Step 5/6 : RUN apt-get install -y letsencrypt
 ---> Running in 76b75c139451
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package letsencrypt
ERROR: Service 'certbot' failed to build : The command '/bin/sh -c apt-get install -y letsencrypt' returned a non-zero code: 100

### Expected Behavior:
成功运行，且生成对应的证书

### Context information:

**Output of `git rev-parse HEAD`**

```
{f73b8fb642ac5f90d575292a987377ace028fea3}
```

**Output of `docker version`**

```
{Docker version 20.10.0, build 7287ab3}
```

**Output of `docker-compose version`**

```
{docker-compose version 1.27.4, build 40524192}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
{ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B50}
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by china-enoch** [comment]
docker-compose.yml certbot config

certbot:
      build:
        context: ./certbot
      volumes:
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      environment:
        - CN="service.test"
        - EMAIL="919398752@qq.com"
      networks:
        - frontend

**Comment by adriangordon1231** [comment]
How do I fix this?

**Comment by china-enoch** [comment]
> How do I fix this? I am having the same issue

You should change the file certbot/Dockerfile first line
```
FROM phusion/baseimage:latest

LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"

COPY run-certbot.sh /root/certbot/run-certbot.sh

RUN apt-get update
RUN apt-get install -y letsencrypt

ENTRYPOINT bash -c "bash /root/certbot/run-certbot.sh && sleep infinity"

```

```
docker-compose build certbot
docker-compose up -d certbot
```

But i have new issue, as same

<img width="842" alt="473829BC-AFF5-433A-A288-B257CD5204D2" src="https://user-images.githubusercontent.com/16871710/103050210-c116ab80-45ce-11eb-9778-34eecfd21e7f.png">

**Comment by bestlong** [comment]
Duplicate #2679
