### ISSUE TITLE
laradock downloading in the background

### ISSUE THREAD

**Issue by zynth17** [laradock/laradock#2808]
### Description:
Why is my laradock keep downloading an images that i dont want?
i only using adminer nginx and mysql but laradock keep downloading an images in the background.
i'm using the laradock multiproject settings
### Expected Behavior:
i only want to use an images i use

i'm using docker version 20.10  build 7287ab3 and docker compose 1.27.4 build 40524192

**System info: Mac, Windows or Linux. Include which disto/version**

wsl2 : ubuntu20.04
### Steps to reproduce the issue:

1. just install the laradock multi project and run docker-compose up -d mysql nginx adminer

**Comment by bestlong** [comment]
docker-compose depends_on affect

nginx -> php-fpm -> workspace
