### ISSUE TITLE
problem in build

### ISSUE THREAD

**Issue by harsh6768-svg** [laradock/laradock#2809]
[+] Building 0.2s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.1s
 => => transferring dockerfile: 31B                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                                                               0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 1: unknown instruction: "FROM

**Comment by bestlong** [comment]
which version `docker-compose` ?

**Comment by mclxly** [comment]
same error
-------------------------------------------------
docker-compose build --no-cache php-fpm
Building php-fpm
[+] Building 0.2s (3/3) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 38B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/laradock/php-fpm:latest-  0.0s
------
 > [internal] load metadata for docker.io/laradock/php-fpm:latest-5.6:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest-5.6]: 403 Forbidden
ERROR: Service 'php-fpm' failed to build
---------------------------------------------------

docker-compose version 1.28.5, build c4eb3a1f

------------------------------------------------
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
