### ISSUE TITLE
Nginx and Laravel Echo Server can't communicate

### ISSUE THREAD

**Issue by privarepan** [laradock/laradock#2821]
laravel-echo-server_1  | [1:32:36 AM] - Preparing authentication request to: http://nginx
laravel-echo-server_1  | [1:32:36 AM] - Sending auth request to: http://nginx/broadcasting/auth
laravel-echo-server_1  |
laravel-echo-server_1  | ⚠ [1:32:36 AM] - qB_XZVpp3mCknKfrAAAA could not be authenticated to presence-chat
laravel-echo-server_1  | <html>
laravel-echo-server_1  | <head><title>404 Not Found</title></head>
laravel-echo-server_1  | <body>
laravel-echo-server_1  | <center><h1>404 Not Found</h1></center>
laravel-echo-server_1  | <hr><center>nginx</center>
laravel-echo-server_1  | </body>
laravel-echo-server_1  | </html>

my laravel-echo-server.json

{
	"authHost": "http://nginx",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "7b9325b3b6dfe8f9",
			"key": "22539cb6dd11df297d145df517ee4f49"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}

**Comment by erikn69** [comment]
Look in config/app.php if you have uncommented

App\Providers\BroadcastServiceProvider::class,
