### ISSUE TITLE
Change Composer Version in Workspace

### ISSUE THREAD

**Issue by geoalexidis** [laradock/laradock#2822]
Hello people from Laradock

We need composer version 1 because of some dependencies.

We tried to set `WORKSPACE_COMPOSER_REPO_PACKAGIST=1.10.19` in `.env` but that didn't set the installated composer version to that. 

Instead the newest version of 2 is installed.

**Comment by kaibadash** [comment]
It looked like we should set `WORKSPACE_COMPOSER_REPO_PACKAGIST` as URL.

https://github.com/laradock/laradock/blob/master/DOCUMENTATION/content/help/index.md
```
WORKSPACE_NPM_REGISTRY=https://registry.npm.taobao.org
WORKSPACE_COMPOSER_REPO_PACKAGIST=https://packagist.phpcomposer.com
```

**Comment by bestlong** [comment]
ref #2817

**Comment by geoalexidis** [comment]
Thx for the Info and quick implementation.

So do we now close this issue or will this be done by the organizers here?
