### ISSUE TITLE
php-worker doesn't work with MSSQL

### ISSUE THREAD

**Issue by AndreFigueredo-Multilaser** [laradock/laradock#2826]
**Is your feature request related to a problem? Please describe.**
I need to use laravel queue/horizon, but my database is MSSQL and the laradock doesn't support this drivers in php-worker.

**Describe the solution you'd like**
Add support to MSSQL in php-worker container.

**Comment by vitomeuli** [comment]
same for me

**Comment by daydevelops** [comment]
I am having the same issue. I tried changing the workspace Dockerfile to contain the 2 drivers needed (sqlsrv and pdo_sqlsrv) but that was a messy solution and did not work well.
