### ISSUE TITLE
Laravel-Horizon and PHP-Worker Build Issue

### ISSUE THREAD

**Issue by prezire** [laradock/laradock#2828]
### Description:

The Images laravel-horizon and php-worker won't build successfully.
No firewalls set and wifi network is fine.

### Expected Behavior:

A successful build of Images.

### Context information:

**Output of `git rev-parse HEAD`**

```
840c6a96ceacd5967cd6e0b6da507a27facc58f3
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
ProductName:    Mac OS X
ProductVersion: 10.15.1
BuildVersion:   19B88
```

### Steps to reproduce the issue:

1. docker-compose up -d php-worker laravel-horizon
2. docker-compose build --no-cache php-worker
3. docker-compose build --no-cache laravel-horizon

I already pruned all images, containers, caches, etc. but still no luck.

### Stacktrace & Additional info:

Below is from laravel-horizon, but the same thing also happens to php-worker.
```
Updating channel "pecl.php.net"
Channel "pecl.php.net" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: php_network_getaddresses: getaddrinfo failed: Name does not resolve
Trying channel "pecl.php.net" over https:// instead
Cannot retrieve channel.xml for channel "pecl.php.net" (Connection to `ssl://pecl.php.net:443' failed: php_network_getaddresses: getaddrinfo failed: Name does not resolve)
ERROR: Service 'laravel-horizon' failed to build : The command '/bin/sh -c pecl channel-update pecl.php.net && pecl install memcached mcrypt-1.0.1 mongodb && docker-php-ext-enable memcached mongodb' returned a non-zero code: 1
```

**Comment by robgwin** [comment]
I get the same error with php:7.4-fpm-alpine -- for some reason it can't resolve DNS for pecl.php.net. But it works fine on php:7.4-fpm-buster. I wonder what the difference is.

```
$ docker run -it php:7.4-fpm-alpine sh
/var/www/html # pecl channel-update pecl
Updating channel "pecl"
Channel "pecl" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: php_network_getaddresses: getaddrinfo failed: Name does not resolve
Trying channel "pecl" over https:// instead
Cannot retrieve channel.xml for channel "pecl.php.net" (Connection to `ssl://pecl.php.net:443' failed: php_network_getaddresses: getaddrinfo failed: Name does not resolve)
/var/www/html # curl -I https://pecl.php.net/
curl: (6) Could not resolve host: pecl.php.net
/var/www/html # curl -I https://www.google.com/
HTTP/2 200 
/var/www/html # nslookup pecl
Server:		192.168.65.1
Address:	192.168.65.1:53

** server can't find pecl: NXDOMAIN

** server can't find pecl: NXDOMAIN
```

```
$ docker run -it php:7.4-fpm-buster sh
# pecl channel-update pecl
Updating channel "pecl"
Channel "pecl" is up to date
# curl -I https://pecl.php.net/
HTTP/1.1 200 OK
```

**Comment by robgwin** [comment]
Okay I think this may be a problem with my (and OP's) local Docker network settings.

This fails on alpine and succeeds on buster:
nslookup pecl.php.net

If I explicitly query Google's nameserver, it succeeds on both alpine and buster
nslookup pecl.php.net 8.8.8.8

And if I explicitly query the docker container's local nameserver (found in /etc/resolv.conf) it fails on both alpine and buster:
nslookup pecl.php.net 192.168.65.1

So I'm guessing the difference is that buster is just more willing than alpine to fail back to non-authoritative DNS answer. And the real question is what's wrong with my docker network.

Anyway it's probably not a laradock problem.

**Comment by prezire** [comment]
@robgwin I'm not sure if it's my network as well. However I'm thinking more it's related to arch problem. I'll dig for more info.

**Comment by robgwin** [comment]
@prezire Updating Docker-for-Mac to 3.1.0 fixed it for me.

**Comment by prezire** [comment]
@robgwin Good work. Thanks for that. But I'm also wondering its effects on AWS CodeBuild. Just a heads up for you in case you also need the images built for Pipelining which is what I'm doing right now...

**Comment by ManuDoni** [comment]
I had the same problem with laradock v12 and on Docker for Windows v3.3.1.
I solved it commenting these lines (43-48) in php-worker/Dockerfile:
```Dockerfile
#RUN if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
#      pecl install memcached-2.2.0 mcrypt-1.0.1; \
#    else \
#      pecl install memcached mcrypt-1.0.1; \
#    fi; \
#    docker-php-ext-enable memcached
```
Fortunately I use Redis and not Memcached.

**Comment by ManuDoni** [comment]
UPDATE:
I tried with laradock v12 and v12.1 but it doesn't work if you install the Redis extension by enabling it in the .env file (PHP_WORKER_INSTALL_REDIS).
The same Memcached error occurs for Redis

**Comment by ManuDoni** [comment]
I solved it manually by editing the php-worker Dockerfile:
```Dockerfile
FROM php:${LARADOCK_PHP_VERSION}-alpine3.12
```
I'm setting the version of alpine to 3.12 instead of the latest (currently 3.13) due to this issue: https://github.com/docker-library/php/issues/1134
