### ISSUE TITLE
Blackfire not working

### ISSUE THREAD

**Issue by eduardor2k** [laradock/laradock#2832]
### Description:
Unable to run blackfire service in laradock, after setting up INSTALL_BLACKFIRE=true and rebuilding the container, everything is built correctly, but agent is not working.

If i run the following commands, the agent starts correctly.
blackfire-agent --register --server-id="<your_server_id>" --server-token="<your server_token>"
/etc/init.d/blackfire-agent restart

After running the command to profile my app:
blackfire -v="4" --client-id="<your_client_id>" --client-token="<your_client_token>" run php artisan

I get the following message:

    No data received from the probe, is it installed and enabled correctly?
    Get help troubleshooting this issue at: https://blackfire.io/help/probe-not-found

Anyone has ever used blackfire.io with laradock?

### Expected Behavior:
Command should run correctly

### Context information:

**Output of `git rev-parse HEAD`**

```
-
```

**Output of `docker version`**

```
-
```

**Output of `docker-compose version`**

```
-
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Linux Ubuntu 20.10
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
-
```

**Comment by eduardor2k** [comment]
I got it to work, at least using the cli.

I will try to fix the workspace installer in the next few days.

**Comment by Shuma2** [comment]
> I got it to work, at least using the cli.
> 
> I will try to fix the web cli in the next few days.

Could you share how you make it work for CLI, please?
