### ISSUE TITLE
Upgrade sqlite in workspace container

### ISSUE THREAD

**Issue by mattcrn** [laradock/laradock#2833]
The current version of sqlite in the workspace container is `3.22.0`.

It would be greate to upgrade it to at least `3.25.0.` so the syntax for renaming columns works.

**Comment by ionparticle** [comment]
In addition, sqlite 3.24.0 is the minimum required for the new upsert() method in the query builder.

Laravel Upsert: https://laravel.com/docs/8.x/queries#upserts
Using upsert results in an error as sqlite 3.22.0 doesn't understand the "on conflict" clause: https://sqlite.org/lang_upsert.html

**Comment by bestlong** [comment]
now is 3.31

```shell
$ docker-compose build --no-cache --pull workspace

$ docker-compose up -d workspace

$ docker-compose exec workspace bash
root@37a46c430eda:/var/www# sqlite3 -version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
root@37a46c430eda:/var/www#
```
