### ISSUE TITLE
ERR_SOCKET_TIMEOUT when Installing Node.js

### ISSUE THREAD

**Issue by abkrim** [laradock/laradock#2843]
### Description:
Try up build `docker-compose up -d nginx mysql phpmyadmin`and get error ERR_SOCKET_TIMEOUT, detected in nginx

### Expected Behavior:
I was hoping to build a system with nginx, mysql and phpmyadmin for a laravel project, based on independent laradoc per project

### Context information:

**Output of `git rev-parse HEAD`**

```
3a73aa60eeb40a807f7ed064f51d1ac12d7ce26f
```

**Output of `docker version`**

```
Docker version 20.10.3, build 48d30b5
```

**Output of `docker-compose version`**

```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Linux 5.4.0-65-generic x86-64 Ubuntu 20.04.2 LTS 
```

### Steps to reproduce the issue:

1. Clone submodule laradock
2. Copy env-example to .env
3. docker-compose up -d nginx mysql phpmyadmin
4. Get error npm ERR! errno ERR_SOCKET_TIMEOUT      
5. Investigate npm ERR! errno ERR_SOCKET_TIMEOUT      
6. Modify npm WORKSPACE_NPM_FETCH_RETYR_MINTIMEOUT and _MAXTIMEOUT
7. I get same result      

### Stacktrace & Additional info:

```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.8.8.tgz failed, reason: Socket timeout

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/laradock/.npm/_logs/2021-02-16T09_01_42_556Z-debug.log
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     mkdir -p $NVM_DIR &&     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash         && . $NVM_DIR/nvm.sh         && nvm install ${NODE_VERSION}         && nvm use ${NODE_VERSION}         && nvm alias ${NODE_VERSION}         && npm config set fetch-retries ${NPM_FETCH_RETRIES}         && npm config set fetch-retry-factor ${NPM_FETCH_RETRY_FACTOR}         && npm config set fetch-retry-mintimeout ${NPM_FETCH_RETRY_MINTIMEOUT}         && npm config set fetch-retry-maxtimeout ${NPM_FETCH_RETRY_MAXTIMEOUT}         && if [ ${NPM_REGISTRY} ]; then         npm config set registry ${NPM_REGISTRY}         ;fi         && if [ ${INSTALL_NPM_GULP} = true ]; then         npm install -g gulp         ;fi         && if [ ${INSTALL_NPM_BOWER} = true ]; then         npm install -g bower         ;fi         && if [ ${INSTALL_NPM_VUE_CLI} = true ]; then         npm install -g @vue/cli         ;fi         && if [ ${INSTALL_NPM_ANGULAR_CLI} = true ]; then         npm install -g @angular/cli         ;fi         && ln -s `npm bin --global` /home/laradock/.node-bin ;fi' returned a non-zero code: 1
```

**Comment by Keysox** [comment]
See also https://github.com/npm/cli/issues/3078

**Comment by heiscostly** [comment]
I get this error when i run npm i -d --force

> npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to http://registry.npmjs.org/tapable failed, reason: Socket timeout


Please
 Solution please

**Comment by sgupta40** [comment]
I get this error when trying to run npm install:

npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to (internal link) failed, reason: Socket timeout

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Local\npm-cache\_logs\2021-05-11T18_50_01_074Z-debug.log

PLZZZ HELP us!!! :(

**Comment by sgupta40** [comment]
re-running worked for me.

**Comment by sakthi0314** [comment]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to http://registry.npmjs.org/react-refresh failed, reason: Socket timeout

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sakthi/.npm/_logs/2021-05-18T17_39_30_794Z-debug.log

**Comment by schulzalbrecht** [comment]
same error here

npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: Socket timeout

**Comment by JodelVillena** [comment]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/expo-cli: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TOSHIBA\AppData\Local\npm-cache\_logs\2021-09-07T15_54_06_050Z-debug.log
 

please help me to install react native

**Comment by danyalhabib-10p** [comment]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/expo-cli: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\TOSHIBA\AppData\Local\npm-cache_logs\2021-09-07T15_54_06_050Z-debug.log

please help me to solve this issue

**Comment by danyal2050** [comment]
> npm ERR! code ERR_SOCKET_TIMEOUT npm ERR! errno ERR_SOCKET_TIMEOUT npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/expo-cli: Socket timeout npm ERR! network This is a problem related to network connectivity. npm ERR! network In most cases you are behind a proxy or have bad network settings. npm ERR! network npm ERR! network If you are behind a proxy, please make sure that the npm ERR! network 'proxy' config is set properly. See: 'npm help config'
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\TOSHIBA\AppData\Local\npm-cache_logs\2021-09-07T15_54_06_050Z-debug.log
> 
> please help me to install react native

I am facing same issue when installing npm packages(using "npm install" command), using dockerfile with node version 16.
**Solution:** 
When I lowered the node version to 14 in dockerfile now its working fine. Its solved my issue

**Comment by haythamdahri** [comment]
Downgrading based Docker image from **17** to **14** solved the issue. The majority of issues was because of that.

**Comment by ewatch** [comment]
Lowering the node version through the env file works like the following:
```WORKSPACE_NODE_VERSION=lts/fermium``` 

I know that nvm outputs those "tags" but didn't find a proper list for all values:
lts/fermium -> v14.19.0 (-> N/A)
lts/gallium -> v16.13.2 (-> N/A)

**Comment by khyarih** [comment]
> Downgrading based Docker image from **17** to **14** solved the issue. The majority of issues was because of t

i have face the same with version 16, downgrade to 14 solve the issue

**Comment by halaBarid** [comment]
npm ERR! code ERR_SOCKET_TIMEOUT npm ERR! errno ERR_SOCKET_TIMEOUT npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@babel%2Fplugin-transform-modules-commonjs: Socket timeout npm ERR! network This is a problem related to network connectivity. npm ERR! network In most cases you are behind a proxy or have bad network settings. npm ERR! network  npm ERR! network If you are behind a proxy, please make sure that the npm ERR! network 'proxy' config is set properly.  See: 'npm help config'  npm ERR! A complete log of this run can be found in: npm ERR!     /Users/chaos/.npm/_logs/2022-04-08T17_43_30_612Z-debug-0.log  Aborting installation.   npm install --no-audit --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.  Deleting generated file... package.json Deleting bmi-calculator/ from /Users/chaos/Desktop/learn-react Done.

help me to solve this problem please ! thank you in advance !

**Comment by xgravellx** [comment]
Try these and run again:
`npm config set fetch-retry-mintimeout 20000`
`npm config set fetch-retry-maxtimeout 120000 `

**Comment by mustafaKamal-fe** [comment]
@xgravellx I have. Nothing unfortunately

**Comment by mustafaKamal-fe** [comment]
I changed node from `18-alpine` to `14.20.0-alpine3.16` and it works !!! Several hours of trying. The worst is my internet connection is bad and that was my first and only guess

**Comment by imansarwar** [comment]
IS the error resolved? I am facing same error.

**Comment by danyal2050** [comment]
> IS the error resolved? I am facing same error.

Yes, Its resolved
