### ISSUE TITLE
There is no workspace for PHP v7.4

### ISSUE THREAD

**Issue by sauriio** [laradock/laradock#2846]
### Description:
While I was building the images for v7.4 of PHP the docker-compose fails to fetch the workspace for this specific version

### Expected Behavior:
build with no fails

### Context information:
sudo docker-compose build php-fpm php-worker workspace
Building workspace
Step 1/68 : ARG LARADOCK_PHP_VERSION
Step 2/68 : FROM letsdockerize/laradock-workspace:2.4-${LARADOCK_PHP_VERSION}
ERROR: Service 'workspace' failed to build : manifest for letsdockerize/laradock-workspace:2.4-7.4 not found: manifest unknown: manifest unknown
```

**Output of `docker version`**

```
Docker version 20.10.3, build 48d30b5

```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192

```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Linux  5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Xubuntu 20.04
```

### Steps to reproduce the issue:
<!--- How can we reproduce the issue? -->

1. Set on .env PHP Version to 7.4
2. Build with docker-compose build
3. Fails

### Stacktrace & Additional info:

```
https://hub.docker.com/r/letsdockerize/laradock-workspace/tags?page=1&ordering=last_updated&name=7.4 there is no builds for 7.4
```

**Comment by calebanthony** [comment]
`FROM letsdockerize/laradock-workspace` 

should be

`FROM laradock/workspace`

Did you manually override this option? The official `laradock/workspace` image has the 7.4 build.

**Comment by bestlong** [comment]
@sauriio update your laradock
