### ISSUE TITLE
build php-fpm Xdebug

### ISSUE THREAD

**Issue by AndreiiP** [laradock/laradock#2848]
### Description:
php 7.4
When I build php-fpm I get in phpinfo (Xdebug v2.9.8). But Xdebug doesn't work. If I take a folder (php-fpm) from an old project in which I did the same build, then Xdebug starts working. What could be the reason?

`This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans`

### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
Docker version 20.10.2, build 2291f61
```

**Output of `docker-compose version`**

```
docker-compose version 1.24.1, build 4667896b
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
ubuntu 18
```

### Steps to reproduce the issue:

1. docker-compose build --no-cache php-fpm 
2. Xdebug doesn't work.

phpinfo()  http://i.imgur.com/iEPmm82.png

**Comment by andrewwongyedpay** [comment]
Please try the following:

In php-fpm/xdebug.ini
```
xdebug.remote_host="172.17.0.1"
xdebug.remote_connect_back=1
```

In docker-compose.yml
`Remove         - "${PHP_FPM_XDEBUG_PORT}:9003"
`

After the changes, run
`docker-compose build --no-cache`

**Comment by Sogl** [comment]
@andrewwongyedpay Didn't work for me. Any ideas?

**Comment by andrewwongyedpay** [comment]
> @andrewwongyedpay Didn't work for me. Any ideas?

It is difficult to tell what didn't work if no error message is provided.

1. Is xdebug enabled inside docker? In which service (php-fpm / workspace)?
2. Did you receive any error message when docker-compose up?
3. What is your OS? OSX and Window may need remote_connect_back=1, on Linux  remote_connect_back should be 0.

**Comment by Sogl** [comment]
1. Enabled in both `php-fpm` and `workspace`
2. No error messages.
3. OSX, but I have `xdebug.remote_connect_back=0`

My full file:
```ini

; NOTE: The actual debug.so extention is NOT SET HERE but rather (/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini)

xdebug.remote_host="host.docker.internal"
xdebug.remote_connect_back=0
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM

xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.cli_color=0
xdebug.profiler_enable=0
xdebug.profiler_output_dir="~/xdebug/phpstorm/tmp/profiling"

xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1
```

**Comment by andrewwongyedpay** [comment]
> 1. Enabled in both `php-fpm` and `workspace`
> 2. No error messages.
> 3. OSX, but I have `xdebug.remote_connect_back=0`
> 
> My full file:
> 
> ```ini
> ; NOTE: The actual debug.so extention is NOT SET HERE but rather (/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini)
> 
> xdebug.remote_host="host.docker.internal"
> xdebug.remote_connect_back=0
> xdebug.remote_port=9000
> xdebug.idekey=PHPSTORM
> 
> xdebug.remote_autostart=0
> xdebug.remote_enable=0
> xdebug.cli_color=0
> xdebug.profiler_enable=0
> xdebug.profiler_output_dir="~/xdebug/phpstorm/tmp/profiling"
> 
> xdebug.remote_handler=dbgp
> xdebug.remote_mode=req
> 
> xdebug.var_display_max_children=-1
> xdebug.var_display_max_data=-1
> xdebug.var_display_max_depth=-1
> ```

The setting looks correct to me if your ide is listening on port 9000.
However, it is usually used by php-fpm in your host environment, so your ide may not able to start the debug client.

**Comment by Sogl** [comment]
1. Deployment
![image](https://user-images.githubusercontent.com/7556290/119625989-6e5a4d80-be13-11eb-946b-07f00df7f699.png)


2. CLI
![image](https://user-images.githubusercontent.com/7556290/119625366-c80e4800-be12-11eb-8511-12ffa8dadc06.png)

2.1. CLI 2nd image
![image](https://user-images.githubusercontent.com/7556290/119625622-115e9780-be13-11eb-8c94-4415ad4fc247.png)

3. Xdebug validate
![image](https://user-images.githubusercontent.com/7556290/119626354-c8f3a980-be13-11eb-8ec8-0901f05a988c.png)

4. PHP Servers
![image](https://user-images.githubusercontent.com/7556290/119626786-3acbf300-be14-11eb-9633-ff07e5d37abc.png)

5. Configuration
![image](https://user-images.githubusercontent.com/7556290/119627107-8ed6d780-be14-11eb-8735-507e45616815.png)

6. My port now is 9000
![image](https://user-images.githubusercontent.com/7556290/119627831-381dcd80-be15-11eb-9f2e-87b28d57601e.png)


7. Breakpoints in code
![image](https://user-images.githubusercontent.com/7556290/119627663-1290c400-be15-11eb-98f0-ec9d7499c2a6.png)

8. I use this button to start debug
![image](https://user-images.githubusercontent.com/7556290/119628180-8763fe00-be15-11eb-8f80-184432dfe547.png)

9. My browser open URL `http://sogl.lar/?XDEBUG_SESSION_START=18293` but breakpoints are not active.

**Comment by andrewwongyedpay** [comment]
xdebug.remote_autostart=1
xdebug.remote_enable=1

**Comment by Sogl** [comment]
Not working. I did all my changes in `php_fpm\xdebug.ini`

I also tried to bring back writing log:
https://github.com/laradock/laradock/commit/48933479809a318cb17bed7742655f65da4aac03

with this line `xdebug.remote_log=/var/log/php/xdebug_remote.log`

But errors:
```
➜  laradock git:(master) ✗ docker-compose logs php-fpm
Attaching to laradock_php-fpm_1
php-fpm_1              | [26-May-2021 10:37:00] NOTICE: fpm is running, pid 1
php-fpm_1              | [26-May-2021 10:37:00] NOTICE: ready to handle connections
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | 172.19.0.6 -  26/May/2021:10:38:52 +0000 "GET /index.php" 200
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | 172.19.0.6 -  26/May/2021:10:38:55 +0000 "GET /index.php" 200
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | 172.19.0.6 -  26/May/2021:10:38:55 +0000 "GET /index.php" 200
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | 172.19.0.6 -  26/May/2021:10:39:29 +0000 "GET /index.php" 200
php-fpm_1              | NOTICE: PHP message: Xdebug could not open the remote debug file '/var/log/php/xdebug_remote.log'.
php-fpm_1              | 172.19.0.6 -  26/May/2021:10:39:51 +0000 "GET /index.php" 200

```

**Comment by Sogl** [comment]
Also found this error in Debug console:
![image](https://user-images.githubusercontent.com/7556290/119647673-39f18c00-be29-11eb-8cb0-ccb6a3e844d6.png)
