### ISSUE TITLE
PHP message: PHP Fatal error: Uncaught ReflectionException: Class log does not exist in 

### ISSUE THREAD

**Issue by Shmp** [LaraDock/laradock#285]
I can't get laravel to run because of the following error. The log is from the nginx error.log.
I get an error 500 in chrome when trying to connect. Phpmyadmin is showing his page correctly.

 > 08:43:53 [error] 7#7: *13 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))

**Comment by Mahmoudz** [comment]
@Shmp does this issue still exist?!

**Comment by Shmp** [comment]
I will try a new installation with fresh containers this week. Will report back asap

**Comment by Mahmoudz** [comment]
@Shmp thanks, also don't forget to rebuild the containers before testing it.

**Comment by Shmp** [comment]
Did a fresh install with laradock, build the contrainers, edited the docker-compose.yml, rebuild the containers again. Everything works 👍
