### ISSUE TITLE
Not working ImageMagick in workspace with php 7.*

### ISSUE THREAD

**Issue by inguldima** [laradock/laradock#2850]
**Is your feature request related to a problem? Please describe.**
Not working ImageMagick in workspace with php 7.*

**Describe the solution you'd like**
Change this piece of code in workspace/Dockerfile
```
RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get install -y imagemagick php-imagick \
;fi
```
to this
```
RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
    apt-get update \
    && apt-get install -y --force-yes imagemagick php-imagick \
    && apt-get install -y libmagickwand-dev --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && pecl install imagick \
;fi
```

**Comment by ideepblue** [comment]
I encountered the same issue.

The latest workspace image laradock/workspace:latest-7.3 only installed imagick that work for php8.0.

The solution @inguldima provided is incomplete. I still need to create imagick config in `/etc/php/7.3/cli/conf.d` by run the command `ln -s /etc/php/8.0/mods-available/imagick.ini`.

**Comment by aconital** [comment]
I'm using php 7.2 and I'm having the same issue

**Comment by bestlong** [comment]
#2862 
pull new source and build again
