### ISSUE TITLE
Redis is not installed or enabled

### ISSUE THREAD

**Issue by GautierDele** [laradock/laradock#2851]
### Description:
`Please make sure the PHP Redis extension is installed and enabled.`

I've got this error when trying to php artisan optimize:clear

### Expected Behavior:
Cleared cache

### Context information:

**Output of `git rev-parse HEAD`**

```
f6c53ce53838cae74aee79689e07a432f83b1361
```

**Output of `docker version`**

```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Debian GNU/Linux 10 (buster)
```

### Steps to reproduce the issue:

1. Install and launch laradock with php_redis to true on .env
2. connect to workspace
3. launch `php artisan optimize:clear`

### Stacktrace & Additional info:

Ini redis file is loaded: /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
and redis is present in phpinfo:

Redis Version | 5.3.3
-- | --
Redis Sentinel Version | 0.1
Available serializers | php, json

I'm only getting this error on cli side, this might help with this problem.
My site is working well

**Comment by GautierDele** [comment]
Ok so basically i solved the problem by installing many things on the container.
I still believe this is a bug that just hapenned with the latest deploy.

Here are the commands i ran to fix my problem:
`apt-get install php-redis` -> shouldn't be the problem
`apt-get install php7.4-redis` -> should be the fix

and i restarted all the containers.

I might have a deeper look on that later to try to give a PR if i'm not short on time

**Comment by GautierDele** [comment]
Ok, seems like the redis.ini is not loaded in workspace as it is in php-fpm

So that wasn't about the command i gave in the previous comment, the workspace config is not good is seems like

**Comment by fdjkgh580** [comment]
```
docker-compose exec workspace bash
sudo dpkg -l | grep php
sudo apt install php7.4-redis
systemctl restart php7.4-fpm
```

**Comment by glebovdev** [comment]
I have the same issue with redis and with memcached as well. The only workaround is to `apt update` and `apt install ......` modules again inside the `workspace` container.

**Comment by kamilkozak** [comment]
Same issue here.

**Comment by andreladocruz** [comment]
Same issue here... 

apt update
apt install php7.3-redis 

and worked

**Comment by harunthuo** [comment]
Same issue. @fdjkgh580 solution resolved it for me

**Comment by GautierDele** [comment]
Closing this since the problem is resolved. Thanks all
