### ISSUE TITLE
Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by rfussien** [LaraDock/laradock#286]
Hello,

It seems that since aerospike was added, using php 5.6 isn't possible anymore.

docker-compose build php-fpm
[...]
ERROR: Service 'php-fpm' failed to build: One or more build-args [INSTALL_AEROSPIKE_EXTENSION] were not consumed, failing build.

Thanks for your time :)

**Comment by Mahmoudz** [comment]
@luciano-jr
