### ISSUE TITLE
symfony install dont working

### ISSUE THREAD

**Issue by ezamlinux** [laradock/laradock#2874]
### Description:
While setting `WORKSPACE_INSTALL_SYMFONY=true` on .env, the workspace dockerfile execute the following CLI install : 

`curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony \`
https://github.com/laradock/laradock/blob/master/workspace/Dockerfile#L1135

This will dowload a 404 file.

according to the documentation the new install command is :  
`wget https://get.symfony.com/cli/installer -O - | bash`

with curl this is something like this : 
`curl https://get.symfony.com/cli/installer -o - | bash`

### Expected Behavior:
The dockerfile should download the new installer 

**System info: Mac, Windows or Linux. Include which disto/version**

```
Docker-Desktop / Windows 10
Laradock fresh install
```

### Steps to reproduce the issue:

1. set WORKSPACE_INSTALL_SYMFONY=true
2. run `docker-compose up -d workspace |  docker-compose exec workspace bash`
3. run `symfony new my_project`

### Stacktrace & Additional info:

I would have liked to provide a PR directly but the docker integrates execution for backward compatibility with symfony 2 and 3 alias, having little knowledge of symfony, I prefer that someone comfortable with this framework makes the appropriate change !
(and i don't know how to escape pipe in Dockerfile ...)

Note : Once in the workspace, running the curl installation command works perfectly

**Comment by oussaka** [comment]
Hello @ezamlinux 

can you try this fix #2683 and tell if it works ?

Thank you

**Comment by ezamlinux** [comment]
@oussaka

I confirm the functioning of your PR ! Thanks you
