### ISSUE TITLE
Laradock - PHP Redis extension is installed and enabled

### ISSUE THREAD

**Issue by Richathon** [laradock/laradock#2875]
i'm trying to enable Horizon on Laradock but i always received this message "**Please make sure the PHP Redis extension is installed and enabled**" I've accessed to Workspace container to check whether the php-redis extension is installed or not. But you can see the image the php-redis is already newest version [docker-compose exec workspace bash](https://i.stack.imgur.com/YXIm4.png)

I've open the .env of Laravel project and changed as below

```
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
```
I've also open the .env file in Laradock folder and enable to all `INSTALL_PHPREDIS=true`. After that, **docker-compose build --no-cache workspace php-fpm php-worker**

This is [.env](https://drive.google.com/file/d/13-_f9fU8JkDstylr5-SM_1t-yITvJ44Q/view) file of Laradock folder

But it's still error with php-redis extension

I found some [answers](https://stackoverflow.com/questions/61168156/logicexception-please-make-sure-the-php-redis-extension-is-installed-and-enable) that install predis . but i dont want to use it. I would like to use phpredis and keep `'client' => env('REDIS_CLIENT', 'phpredis')` in config/database.php

Is there anybody faced this issued, please help me. Thank you so much

**Comment by calebanthony** [comment]
I'm having the same issue. Examining the packages installed, it looks like it's installing `php8.0-redis` instead of the version for 7.4 like I need.

I manually edited my `workspace/Dockerfile` file manually on the PHPRedis section to `install php7.4-redis` instead of `install php-redis`. A hack, but got me live again.

**Comment by Richathon** [comment]
Thanks @calebanthony  you save my life <3

**Comment by du-go2joy** [comment]
@calebanthony it doesn't work for me. should i restart or run anything else after do it

**Comment by calebanthony** [comment]
You'll always need to rebuild a Docker container when changing the `Dockerfile` that builds it.
