### ISSUE TITLE
Secure Nginx with Let's Encrypt Guide

### ISSUE THREAD

**Issue by harunthuo** [laradock/laradock#2889]
**Problem Definition**
There doesn't seem to be a well documented way to guide on the process for setting up certbot to install Let's Encrypt SSL certificate.

**Possible Solution**
Kindly showcase how we can setup certbot hassle free. In a non-Laradock environment, the process usually takes less than 5 minutes. I'm almost sure with some proper guidelines in place, we can achieve the same on Laradock.

**Additional context**
When i try to bring up certbot container(i already have nginx and other containers running at this point), i get the following response:

`Attaching to laradock_certbot_1
certbot_1              | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1              | Plugins selected: Authenticator webroot, Installer None
certbot_1              | Unable to register an account with ACME server
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/cert1.pem': No such file or directory
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/privkey1.pem': No such file or directory
certbot_1              | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1              | Plugins selected: Authenticator webroot, Installer None
certbot_1              | Unable to register an account with ACME server
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/cert1.pem': No such file or directory
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/privkey1.pem': No such file or directory
`
Anyone faced a similar issue and how to resolve it?

**Comment by orizzonti** [comment]
Just yesterday i solved this problem for me with nginx.
Try this:

1. in docker-compose.yml set $CN and $EMAIL with your data:

`certbot:
  build:
    context: ./certbot
  volumes:
    - ./data/certbot/certs/:/var/certs
    - ./certbot/letsencrypt/:/var/www/letsencrypt
  environment:
    - CN="fake.domain.com"
    - EMAIL="fake.email@gmail.com"
  networks:
    - frontend
`
2. in docker-compose.yml add the volumes used in certbot:

`nginx:
  volumes:
    - ./data/certbot/certs/:/var/certs
    - ./certbot/letsencrypt/:/var/www/letsencrypt
`
3. Make sure port 443 is disabled in your laradock/nginx/sites/xxx.conf

`    # For https
    # listen 443 ssl;
    # listen [::]:443 ssl ipv6only=on;
    # ssl_certificate /etc/nginx/ssl/default.crt;
    # ssl_certificate_key /etc/nginx/ssl/default.key;
`
4. stop nginx container

`docker-compose stop nginx`

5. rebuild nginx container with --no-cache option

`docker-compose build --no-cache nginx`

6. build certbot container

`docker-compose build --no-cache certbot`

7. start nginx container

`docker-compose up -d nginx`

8. now install the certifcates with certbot

`docker-compose up -d certbot`

9. reactivates port 443 and set the correct paths of the certificates on laradock/nginx/sites/xxx.conf

`    # For https
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    ssl_certificate /var/certs/xxx-cert1.pem;
    ssl_certificate_key /var/certs/xxx-privkey1.pem;
`
Set the ssl directory with the setting of the volume in the nginx section of docker-compose.yml
Substitute xxx with the CN set in the certbot section of docker-compose.yml

10. finally stop and rebuild nginx with --no-cache option:

`docker-compose stop nginx`
`docker-compose build --no-cache nginx`
`docker-compose up -d nginx`

That's all.
I spent 2 days for find this solution... I hope it will save you time.
;)

**Comment by harunthuo** [comment]
Hello @orizzonti 

Thank you so much for your input!

Finally have certbot running after following the suggested steps:

`Attaching to laradock_certbot_1
certbot_1              | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1              | Plugins selected: Authenticator webroot, Installer None
certbot_1              | Obtaining a new certificate
certbot_1              | Performing the following challenges:
certbot_1              | http-01 challenge for mydomain.domain.com
certbot_1              | Using the webroot path /var/www/letsencrypt for all unmatched domains.
certbot_1              | Waiting for verification...
certbot_1              | Cleaning up challenges
certbot_1              | IMPORTANT NOTES:
certbot_1              |  - Congratulations! Your certificate and chain have been saved at:
certbot_1              |    /etc/letsencrypt/live/mydomain.domain.com/fullchain.pem
certbot_1              |    Your key file has been saved at:
certbot_1              |    /etc/letsencrypt/live/mydomain.domain.com/privkey.pem
certbot_1              |    Your cert will expire on 2021-06-15. To obtain a new or tweaked
certbot_1              |    version of this certificate in the future, simply run certbot
certbot_1              |    again. To non-interactively renew *all* of your certificates, run
certbot_1              |    "certbot renew"
certbot_1              |  - Your account credentials have been saved in your Certbot
certbot_1              |    configuration directory at /etc/letsencrypt. You should make a
certbot_1              |    secure backup of this folder now. This configuration directory will
certbot_1              |    also contain certificates and private keys obtained by Certbot so
certbot_1              |    making regular backups of this folder is ideal.
certbot_1              |  - If you like Certbot, please consider supporting our work by:
certbot_1              |
certbot_1              |    Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
certbot_1              |    Donating to EFF:                    https://eff.org/donate-le`

Massive progress. Have also been on this the past 2 days! Appreciate your input.

Only issue arising is nginx is not coming up after running `docker-compose up -d nginx` on step 10 above.  When i run `docker-compose logs nginx` i see that `nginx` cannot locate the cert files:

`nginx_1                | nginx: [emerg] cannot load certificate "/var/certs/default.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/certs/default.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1                | nginx: [emerg] cannot load certificate "/var/certs/default.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/certs/default.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

Thought i'd share this with you first to see if you might notice where the issue is. Here's my laradock/nginx/sites/default.conf file:

`server {

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    # For https
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server ipv6only=on;
    ssl_certificate /var/certs/default.crt;
    ssl_certificate_key /var/certs/default.key;

    server_name localhost;
    root /var/www/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
`

And here are relevant section of laradock's docker-compose.yml file:
`### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "${VARNISH_BACKEND_PORT}:81"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend`
     
`### Certbot #########################################
    certbot:
      build:
        context: ./certbot
      volumes:
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      environment:
        - CN=test.carevault.com.au
        - EMAIL=harunthuo4@gmail.com
      networks:
        - frontend`
        
Could you have idea why nginx fails to run? Thanks

**Comment by orizzonti** [comment]
You have to put the $CN variable set in Certobt in your nginx conf file using the volume set in a nginx section of a docker-composer.yml file and add:

-cert1.pem; for ssl_certificate
-privkey1.pem for ssl_certificate_key

So, your correct configuration would be:

`# For https`
`listen 443 ssl default_server;`
`listen [::]:443 ssl default_server ipv6only=on;`
`ssl_certificate /var/certs/test.carevault.com.au-cert1.pem;`
`ssl_certificate_key /var/certs/test.carevault.com.au-privkey1.pem;`

Then restart nginx.

**Comment by harunthuo** [comment]
Finally! I'm all set up. After 2 and 1/4 days!

Highly appreciate your invaluable input @orizzonti 

One final request, because of the mental exhaustion working on this, i forgot to replace my domain with a dummy/placeholder one. Could you kindly edit your above comment and replace on the ssl_certificate section with dummy domain name? I'm currently deleting all my edit history from my post to remove any reference to my actual domain.

Thanks again!

**Comment by orizzonti** [comment]
You are welcome!

Unfortunately there is adequate documentation on using certbot in laradock.

I am happy to have helped you.

**Comment by harunthuo** [comment]
Cheers mate!

**Comment by harunthuo** [comment]
Hi @orizzonti 

So ssl is properly installed on the server instance i was initially working with following the steps you outlined here: https://github.com/laradock/laradock/issues/2889#issuecomment-801005214

Currently i'm facing issues running the same process on an instance on a separate sub-domain.

Here's my use case: I have ssl installed using certbot on a sub-domain: sub1.domain.com. I try to implement the same on my other domain, sub2.domain.com and while certbot installs the ssl certificate successfully(i confirm this from my certbot logs, everything is fine), my nginx container just won't start. Here's the log for it:

`Attaching to laradock_nginx_1
nginx_1                | nginx: [emerg] cannot load certificate "/var/certs/sub2.domain.com-cert1.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/certs/sub2.domain.com-cert1.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

Here's my configuration files for reference on my sub2.domain.com:

`docker-compose.yml`

`certbot:
      build:
        context: ./certbot
      volumes:
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      environment:
        - CN=sub2.domain.com
        - EMAIL=mymail@gmail.com
      networks:
        - frontend`
        
`nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "${VARNISH_BACKEND_PORT}:81"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend`

Here's my `laradock/nginx/sites/default.conf` file:

`server {

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    # For https
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server ipv6only=on;
    ssl_certificate /var/certs/sub2.domain.com-cert1.pem;
    ssl_certificate_key /var/certs/sub2.domain.com-privkey1.pem;

    server_name localhost;
    root /var/www/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
`

I believe i've mirrored the exact process i followed on my working sub1.domain.com instance but this for some reason does not work. Where could i be going wrong? Thanks.

**Comment by orizzonti** [comment]
@harunthuo try this https://github.com/laradock/laradock/issues/1146

**Comment by harunthuo** [comment]
Hello @orizzonti 

Finally got it working. This is how i did it:

1. As mentioned i have 2 sub-domains: sub1.domain.com and sub2.domain.com
2. I was able to setup SSL using the steps you outlined here: https://github.com/laradock/laradock/issues/2889#issuecomment-801005214
3. But for some reason following same steps was not working on my second sub-domain
4. This is what finally got it working(i got idea from https://github.com/laradock/laradock/issues/1146 you pointed me to)
5. In laradock/nginx/sites/default.conf this was not working:

    `# For https
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server ipv6only=on;
    ssl_certificate /var/certs/sub2.domain.com-cert1.pem;
    ssl_certificate_key /var/certs/sub2.domain.com-privkey1.pem;`

Certbot was successfully generating the SSL certificate but the nginx container was crashing, with error i had stated earlier.

6. I resolve the issue by removing my sub-domain prefix from the ssl_certificate and ssl_certificate_key:

    `# For https
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server ipv6only=on;
    ssl_certificate /var/certs/cert1.pem;
    ssl_certificate_key /var/certs/privkey1.pem;`

This now works! So weird. Its the opposite of the setup in the first subdomain that, as you had laid out in your answer, is prefixed with the sub-domain for the ssl_certificate and ssl_certificate_key. 

Thanks again for your input!

**Comment by harunthuo** [comment]
Hello @orizzonti 

Finally got it working. This is how i did it:

1. As mentioned i have 2 sub-domains: sub1.domain.com and sub2.domain.com
2. I was able to setup SSL using the steps you outlined here: https://github.com/laradock/laradock/issues/2889#issuecomment-801005214
3. But for some reason following same steps was not working on my second sub-domain
4. This is what finally got it working(i got idea from https://github.com/laradock/laradock/issues/1146 you pointed me to)
5. In `laradock/nginx/sites/default.conf` this was not working:

    `# For https`
    `listen 443 ssl default_server;`
    `listen [::]:443 ssl default_server ipv6only=on;`
    `ssl_certificate /var/certs/sub2.domain.com-cert1.pem;`
    `ssl_certificate_key /var/certs/sub2.domain.com-privkey1.pem;`

Certbot was successfully generating the SSL certificate but the `nginx` container was crashing, with error i had stated earlier.

6. I resolve the issue by removing my sub-domain prefix from the `ssl_certificate` and `ssl_certificate_key`:

    `# For https`
    `listen 443 ssl default_server;`
    `listen [::]:443 ssl default_server ipv6only=on;`
    `ssl_certificate /var/certs/cert1.pem;`
    `ssl_certificate_key /var/certs/privkey1.pem;`

This now works! So weird. Its the opposite of the setup in the first subdomain that, as you had laid out in your answer, is prefixed with the sub-domain for the `ssl_certificate` and `ssl_certificate_key`. 

Thanks again for your input!

**Comment by ignatius-n** [comment]
> **Problem Definition**
> There doesn't seem to be a well documented way to guide on the process for setting up certbot to install Let's Encrypt SSL certificate.
> 
> **Possible Solution**
> Kindly showcase how we can setup certbot hassle free. In a non-Laradock environment, the process usually takes less than 5 minutes. I'm almost sure with some proper guidelines in place, we can achieve the same on Laradock.
> 
> **Additional context**
> When i try to bring up certbot container(i already have nginx and other containers running at this point), i get the following response:
> 
> `Attaching to laradock_certbot_1 certbot_1 | Saving debug log to /var/log/letsencrypt/letsencrypt.log certbot_1 | Plugins selected: Authenticator webroot, Installer None certbot_1 | Unable to register an account with ACME server certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/cert1.pem': No such file or directory certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/privkey1.pem': No such file or directory certbot_1 | Saving debug log to /var/log/letsencrypt/letsencrypt.log certbot_1 | Plugins selected: Authenticator webroot, Installer None certbot_1 | Unable to register an account with ACME server certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/cert1.pem': No such file or directory certbot_1 | cp: cannot stat '/etc/letsencrypt/archive/mydomain.domain.com/privkey1.pem': No such file or directory `
> Anyone faced a similar issue and how to resolve it?

check out my fork [https://github.com/ignatius-n/laradock](https://github.com/ignatius-n/laradock). it fully works

**Comment by orizzonti** [comment]
@ignatius-n it seems that let's encrypt validation doesn't work successful.

I see references to mydomain.domain.com in your code ... maybe you haven't set CN and EMAIL in docker-compose.yml as I suggested in point 1 of my first comment?

Then remember to rebuild the containers.

However if you follow my guide step by step (https://github.com/laradock/laradock/issues/2889#issuecomment-801005214) you should do it.

I hope I was helpful.
:)

**Comment by ignatius-n** [comment]
> @ignatius-n it seems that let's encrypt validation doesn't work successful.
> 
> I see references to mydomain.domain.com in your code ... maybe you haven't set CN and EMAIL in docker-compose.yml as I suggested in point 1 of my first comment?
> 
> Then remember to rebuild the containers.
> 
> However if you follow my guide step by step ([#2889 (comment)](https://github.com/laradock/laradock/issues/2889#issuecomment-801005214)) you should do it.
> 
> I hope I was helpful.
> :)

With the forked version? I have two separate VPS servers running the forked version with zero errors. I had similar errors plus needed a few custom features that led me to develop custom mod for certbot. currently I wasn't experiencing any issues but rather was trying to give another option [in this repo](https://github.com/ignatius-n/laradock)

**Comment by nonghinh** [comment]
Thanks @orizzonti , SSL worked perfectly.
But How to renew certbot every 3 months? Need a cronjob?

**Comment by orizzonti** [comment]
@nonghinh yes, you can use supervisor with php-worker.

**Comment by AEK-BKF** [comment]
Hello here,
Thanks @orizzonti for your great tutorial, for me it works fine for one domain example.com
But I want to get it working in case sub-domains, any user can register to my saas and get his own xxxx.example.com domain.
How can I resolve this?
Thank you.

**Comment by orizzonti** [comment]
> @orizzonti any chance you could help with php-worker setup, how would it be able to refresh nginx and renew cert?

I apologize for the delay...
For php-worker you can start from the laravel-worker.conf.example 

On the Laravel website it is well written how to do it: https://laravel.com/docs/8.x/queues#configuring-supervisor.
Pay attention to the version of laravel you use. If you are using an older version of laravel the php-worker may need to be configured differently. Just consult the Laravel guide.

In the "command line" of "php-worker" remember to set the correct directory-root of the project containing the command "artisan" (ex. /var/www/directory-of-your-site/artisan).

For supervisor, I suggest you this excellent guide: https://sudonull.com/post/876-Laravel-Docker-Our-Successful-Experience.

I hope I was helpful.

**Comment by orizzonti** [comment]
> Hello here, Thanks @orizzonti for your great tutorial, for me it works fine for one domain example.com But I want to get it working in case sub-domains, any user can register to my saas and get his own xxxx.example.com domain. How can I resolve this? Thank you.

Unfortunately I have not yet had the need to manage subdomains with a single laradock environment.
You should be able to use a "wildcard certificate" valid for all subdomains.

**Comment by AEK-BKF** [comment]
Thanks for quick reply,
Do you have any links as tutorials how can we use wildcare certificate ?
Since my project on Hetzner, I tried this : https://community.hetzner.com/tutorials/letsencrypt-dns
I tried to edit the paths in certbot & nginx containers but doesn't work.
Any help please, thanks

**Comment by orizzonti** [comment]
Try this: https://micropyramid.medium.com/letsencrypt-wildcard-setup-wildcard-subdomain-using-letsencrypt-and-certbot-97ffb17414dd

**Comment by AEK-BKF** [comment]
Thank you again for your best,
In fact, I'm able to generate wildcard certificate but How can I set it in nginx container sites config, 
 I run commands to get the certificate in certbot container, and the files are in /etc/letsecrypt/live.
 but your setup is :
  ```
- ./data/certbot/certs/:/var/certs
  - ./certbot/letsencrypt/:/var/www/letsencrypt
```

**Comment by helloeyesimple** [comment]
for those who have this Unable to register with ACME server, just delete " on your docker-compose.yml
both for $CN and $EMAIL

**Comment by rahat1994** [comment]
> for those who have this Unable to register with ACME server, just delete " on your docker-compose.yml both for $CN and $EMAIL

remove double quotes from your compose yml file

` environment:`
   ` - CN=fake.domain.com`
   ` - EMAIL=fake.email@gmail.com`

**Comment by rahu431** [comment]
Im getting same issue:
signa@inux:~/DockerSignaDartAI$ docker compose -f docker-compose-4.yml up -d
[+] Building 0.0s (0/0)
WARN[0000] volume "dockersignadartai_sql_data" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume
[+] Running 3/3
 ✔ Container dockersignadartai-sqlserver-1   Running                                                                                                               0.0s
 ✔ Container dockersignadartai-frontend-1    Started                                                                                                               0.6s
 ✔ Container dockersignadartai-middleware-1  Running                                                                                                               0.0s
signa@inux:~/DockerSignaDartAI$ docker ps -a
CONTAINER ID   IMAGE                                        COMMAND                  CREATED             STATUS                     PORTS                                       NAMES
a126cd1aa748   192.168.1.166:5000/dartlive                  "/docker-entrypoint.…"   4 seconds ago       Exited (1) 2 seconds ago                                               dockersignadartai-frontend-1
da9785de0e01   192.168.1.166:5000/dartapi                   "docker-entrypoint.s…"   5 minutes ago       Up 4 minutes               0.0.0.0:3001->3001/tcp, :::3001->3001/tcp   dockersignadartai-middleware-1
dfe29d7f6cff   mcr.microsoft.com/mssql/server:2019-latest   "/opt/mssql/bin/perm…"   About an hour ago   Up About an hour           0.0.0.0:1433->1433/tcp, :::1433->1433/tcp   dockersignadartai-sqlserver-1
3de7fb88b721   registry:latest                              "/entrypoint.sh /etc…"   3 months ago        Up About an hour           0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   registry
signa@inux:~/DockerSignaDartAI$ docker logs a126cd1aa748
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/03/28 21:32:28 [emerg] 1#1: cannot load certificate "/etc/nginx/conf.d/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/conf.d/fullchain.pem, r) error:10000080:BIO routines::no such file)
nginx: [emerg] cannot load certificate "/etc/nginx/conf.d/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/conf.d/fullchain.pem, r) error:10000080:BIO routines::no such file)
