### ISSUE TITLE
`supervisord.log` and `supervisord.pid` are now created in the project root with root privileges when `apache2` is started

### ISSUE THREAD

**Issue by ngmy** [laradock/laradock#2928]
### Description:
After updating Laradock, `supervisord.log` and `supervisord.pid` are now created in the project root with root privileges when `apache2` is started.

### Expected Behavior:
Not to be created (the same as before).
Or be created in a different location outside of git control.

### Context information:

**Output of `git rev-parse HEAD`**

```
ecdfa174dc82771ff5effa3303b65505eb09ae8a
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 10 + WSL 2 (Ubuntu 20.04.1 LTS)
```

### Steps to reproduce the issue:

1. `cd laradock` (I have Laradock installed as a submodule)
2. `docker-compose up -d apache2`
3. `cd ../`
3. `git status` (`supervisord.log` and `supervisord.pid` are displayed)

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by garbinmarcelo** [comment]
Hello @ngmy, how are you?

Did you try to update to the latest version to see if this bug persists?

I tried the steps here with the last commit and apparently it is no longer causing this situation, I would just like to confirm with you.

Could you return as soon as possible?

Thanks

**Comment by garbinmarcelo** [comment]
Hello @ngmy , at first the last merge is to fix this problem with these supervisor single files. 

Could you test there if everything was right? 

if everything is ok, we close this issue.

Thanks

**Comment by ngmy** [comment]
Hello @garbinmarcelo ,

The `supervisord.log` and `supervisord.pid` are no longer created and the issue seems to be solved.

Thanks,
