### ISSUE TITLE
Why we have different base images ?

### ISSUE THREAD

**Issue by majuansari** [LaraDock/laradock#293]
Hi,

First of all thanks for the docker settings.

But may I know why we have different base images ?

Apache - Ubuntu 16:04
Phpfpm & mysql - Debian Wheezy
Workspace - Phusion base image

I am pretty new to docker. Sorry if I am wrong .

Can any one please explain ?
Thanks in advance.

**Comment by Mahmoudz** [comment]
There's no need to have them on the same base image. We choose the best base image for every software. Base images have different sizes and pre-installed software's, so they could be required by some software's and not by others..

**Comment by francislavoie** [comment]
For apache specifically, wouldn't it make sense to use `debian-7` (wheezy) as the base image? See here, they have builds with debian. http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/apache.html
