### ISSUE TITLE
ERROR: Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by danylloweb** [laradock/laradock#2936]
### Description:

ERROR: Service 'php-fpm' failed to build

![image](https://user-images.githubusercontent.com/39008944/113619488-6c53e980-962f-11eb-9ef4-92dff69c223c.png)

**System info: Mac, Windows or Linux. Include which disto/version**

```
{windows 10}
```

**Comment by apodacaduron** [comment]
Same on Mac OS Big Sur I think this is related to that error [https://github.com/laradock/laradock/pull/2935](https://github.com/laradock/laradock/pull/2935)

**Comment by danylloweb** [comment]
OK! works after I commented
