### ISSUE TITLE
IDE and php-fpm ports concurrent

### ISSUE THREAD

**Issue by vertx-one** [laradock/laradock#2948]
### Description:
Config:
```
services:
    php-fpm:
        ports:
              - "${PHP_FPM_XDEBUG_PORT}:9003"
```

This config allocate port on 9003 on host machine. When i try to start debug listening in IDE (phpstorm in my case) it show notification "Port 9003 is busy" and it busy by container php-fpm.

From https://2.xdebug.org/docs/remote#communication
xDebug don't need to allocate port for external connections. xDebug notify client which listen on port 9000(9003) about new debug session.

### Expected Behavior:

1. Remove services.php-fpm.ports
1. If we need ability to change port, i think better do it on container build stage something like this
```
sed -i "s/xdebug.remote_port=9000/xdebug.client_port=${PHP_FPM_XDEBUG_PORT}/" /usr/local/etc/php/conf.d/xdebug.ini && \
```

### Context information:

**Output of `git rev-parse HEAD`**

```
89ad4c805445d47f0a1a635784b105a0252998bc
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker-compose version`**

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Linux Ubuntu 20.04.2
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by Sogl** [comment]
I have the same `Port 9003 is busy`. How to fix?

**Comment by vertx-one** [comment]
> I have the same `Port 9003 is busy`. How to fix?

If you don't need specific xdebug port just remove from   docker config section services.php-fpm.ports

**Comment by Sogl** [comment]
Removed. Now my page is open with `?XDEBUG_SESSION_START=12690` but breakpoints isn't catch.

**Comment by vertx-one** [comment]
> Removed. Now my page is open with `?XDEBUG_SESSION_START=12690` but breakpoints isn't catch.

You should check xdebug and/or php-fpm logs, there is may some additional info. Check config of your ide, read your ide docs for configure debug. 

I think better place for help is SO ;)

**Comment by Sogl** [comment]
I got it working after some hours of struggling: https://github.com/laradock/laradock/issues/2848#issuecomment-848668788

**Comment by simonbuehler** [comment]
this is still relevant for a new install, please remove the listen part!

**Comment by kimitaka** [comment]
I have the same problem and tried a pull request https://github.com/laradock/laradock/pull/3136.
It works fine with default port settings in my environment with PHP 8.1, Nginx, and PhpStorm.

> If we need ability to change port, i think better do it on container build stage something like this
> ```
> sed -i "s/xdebug.remote_port=9000/xdebug.client_port=${PHP_FPM_XDEBUG_PORT}/" /usr/local/etc/php/conf.d/xdebug.ini && \
> ```

I think this @vertx-one's idea to change a port is good, but I haven't tried it yet.

**Comment by glitterlip** [comment]
php8 and xdebug3 got the same problem. Phpstorm says port `9003 is busy` ,  try comment out `docker-compose.yml` ,php-fpm section 
````
# ports:
        # - "${PHP_FPM_XDEBUG_PORT}:9003"
````
fix the problem .

**Comment by kimitaka** [comment]
I think PR https://github.com/laradock/laradock/pull/3206 solves this problem.
