### ISSUE TITLE
Malware kdevtmpfsi using the entire CPU arising from the php-fpm container

### ISSUE THREAD

**Issue by vietlai1190** [laradock/laradock#2949]
### Description:
When I deployed the production version, there was malware that used up the entire CPU.
This problem is probably coming from the php-fpm container.
When I stop the php-fpm container, the CPU is freed.

**Comment by bestlong** [comment]
Is redis used?

#2451

**Comment by vietlai1190** [comment]
> Is redis used?
> 
> post your `docker-compose ps` result
> 
> #2451

Yep, i used Redis but I have set a password for it.
![Screen Shot 2021-04-15 at 14 03 29](https://user-images.githubusercontent.com/30292665/114828091-b12c0d00-9df3-11eb-94aa-77a08ba97745.png)
The photo above is the result of `docker-compose ps`.
Thanks!
