### ISSUE TITLE
laradock fresh install and docker-compose up error on : unknown flag: --iidfile

### ISSUE THREAD

**Issue by qingtiandalaoye** [laradock/laradock#2955]
### Description:

when fresh install laradock, run this command to start by default setting.
sudo docker-compose  --verbose  up  -d nginx  phpmyadmin redis workspace

stoped by error:

compose.service.build: Building redis
unknown flag: --iidfile
See 'docker build --help'.
ERROR: compose.cli.main.exit_with_metrics: Service 'redis' failed to build : Build failed

### Context information:

**Output of `git rev-parse HEAD`**

```
3778c90932b5d95c88ad25f9713ec053a1dd1209
```

**Output of `docker version`**

```
Docker version 1.13.1, build 0be3e21/1.13.1
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.1, build unknown

```

**System info: Mac, Windows or Linux. Include which disto/version**

```
linux centos7&64
```

### Steps to reproduce the issue:

1.   sudo docker-compose  --verbose  up  -d nginx  phpmyadmin redis workspace
2.
3.

### Stacktrace & Additional info:

```

compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('laradock_redis')
compose.service.build: Building redis
unknown flag: --iidfile
See 'docker build --help'.
ERROR: compose.cli.main.exit_with_metrics: Service 'redis' failed to build : Build failed
```

**Comment by codex-corp** [comment]
@qingtiandalaoye

Try to build from source directly 
```
RUN docker-php-source extract \
    && curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/refs/tags/5.3.4.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mv phpredis-5.3.4 /usr/src/php/ext/redis \
    && docker-php-ext-install redis
```
