### ISSUE TITLE
ERROR [internal] load metadata for docker.io/laradock/workspace:latest-7.0

### ISSUE THREAD

**Issue by pizsd** [laradock/laradock#2961]
### Expected Behavior:
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Successfully built 20cf958a363a6bed7415b8626c61c20ef3d20530e3e99ca1e9f256d130cb5469
Building workspace
[+] Building 3.2s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 38B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for docker.io/laradock/workspace:latest-7.0                                     3.0s
------
 > [internal] load metadata for docker.io/laradock/workspace:latest-7.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed commit on ref "unknown-sha256:6a5855c8e1ad4113358b80782d08188872cbdbf60b7e5288addec921b1155683": unexpected commit digest sha256:40e2f13a4c7de4ccecb965b3ad1e383bfb868f684cca761eb1d8b76dc3a359fc, expected sha256:6a5855c8e1ad4113358b80782d08188872cbdbf60b7e5288addec921b1155683: failed precondition
ERROR: Service 'workspace' failed to build

Docker version 20.10.5, build 55c4c88

**Comment by bestlong** [comment]
try again `docker-compose build --no-cache --pull workspace`
