### ISSUE TITLE
构建laradock时报错E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by Mockingbird-io** [laradock/laradock#2974]
### Description:

通过命令行执行 `docker compose up -d nginx`  进程终止报错 `E: Unable to correct problems, you have held broken packages.`
### Docker version:
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
### Steps to reproduce the issue:

1.docker compose up -d nginx 
![image](https://user-images.githubusercontent.com/18682588/119078682-42148a80-ba29-11eb-930b-e8b47bfc671a.png)

**Comment by chowjiawei** [comment]
我刚刚也也遇到了 弄了半天  你把中国镜像弄掉 false 不要用true 就可以了

**Comment by Mockingbird-io** [comment]
> 我刚刚也也遇到了 弄了半天 你把中国镜像弄掉 false 不要用true 就可以了

那需要挂VPN下载吗？

**Comment by chowjiawei** [comment]
可以不挂  我刚刚没有挂也成功了  如果还有问题就挂一个

**Comment by Mockingbird-io** [comment]
> 可以不挂 我刚刚没有挂也成功了 如果还有问题就挂一个

成功了 非常感谢！:)

**Comment by hugo-z** [comment]
同样的问题，改成false，问题依旧

**Comment by chowjiawei** [comment]
网络问题，需要重试好几次，不行就等1小时，在多重试，看报错信息就可以看到你当前那个包无法获取

**Comment by yuhal** [comment]
成功了 非常感谢！:)
