### ISSUE TITLE
php-worker's extension  redis not effective

### ISSUE THREAD

**Issue by wotemenige** [laradock/laradock#2975]
I want use supervisor for my queue,and queue driver is redis;

but , when i run docker-compose exec php-worker php -m  , i can't find the extension of redis;

I try to edit the php-worker/Dockfile, but i can't success.

**Comment by bestlong** [comment]
edit .env set `PHP_WORKER_INSTALL_REDIS=true`

run `docker-compose build php-worker`

then try again.
