### ISSUE TITLE
Rebuild workspace error php7.x-any

### ISSUE THREAD

**Issue by carlorregod** [laradock/laradock#2991]
OS: Windows 10
Using: Docker desktop

Please see attach txt file.
First exec 
docker-compose build –-no-cache workspace
Then, docker-compose throw error 👍 
```
 > [17/62] RUN if [ true = true ]; then   apt-get -y install libxml2-dev php7.2-soap ;fi:
#21 0.462 Reading package lists...
#21 1.323 Building dependency tree...
#21 1.448 Reading state information...
#21 1.516 E: Unable to locate package php7.2-soap
#21 1.516 E: Couldn't find any package by glob 'php7.2-soap'
#21 1.516 E: Couldn't find any package by regex 'php7.2-soap'
```
I use a laradock version 1. years old, but I don't change it.

Thanks
Abrazos, Carlos
[informe.txt](https://github.com/laradock/laradock/files/6610861/informe.txt)

**Comment by bestlong** [comment]
try upgrade laradock

**Comment by carlorregod** [comment]
Any another alternative? :(

**Comment by raczekm** [comment]
Try changing the CHANGE_SOURCE to true (.env file). This was the solution for PHP7.4

**Comment by carlorregod** [comment]
Nice, I try it @raczekm
Thanks
