### ISSUE TITLE
Dusk dependencies fails to build on MacOS (M1 apple chip)

### ISSUE THREAD

**Issue by lfrichter** [laradock/laradock#2992]
### Description:
When `INSTALL_DUSK_DEPS`=true, workspace fails on MacOs using M1 apple chip

### Expected Behavior:
Is expected to build workspace correctly

### Context information:

**Output of `git rev-parse HEAD`**

```
3d57064466e3232cecc6c47ebdf9ca164b8773c3
```

**Output of `docker version`**

```
Docker version 20.10.6, build 370c289
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.1, build c34c88b2
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
MacOs Big Sur 11.4 (20F71) - M1 Apple chip
```

### Steps to reproduce the issue:

1. Change file .env update line INSTALL_DUSK_DEPS=true,
2. Rebuild using docker-compose build --no-cache workspace
3. Pop up the error message

### Stacktrace & Additional info:

```
2021-06-08 12:23:56 (3.37 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [83335940/83335940]

dpkg: error processing archive google-chrome-stable_current_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 google-chrome-stable_current_amd64.deb
```

**Comment by janehernandez** [comment]
up
