### ISSUE TITLE
Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by dinacuatro** [laradock/laradock#2994]
### Info:
OS: Ubuntu 16.04
Docker version: 20.10.6
Commit: 63fc1fd
Project versions: 
 - Laravel 5.8.33
 - Vue 2.6.10

### Problem:
This morning, after running `composer install` and `npm install`, my docker environment stopped working.  
After sereval tries, I deleted all docker images on my machine and tried to build again.
I get the following error:

```
$ sudo docker-compose build --no-cache php-fpm
Building php-fpm
Step 1/117 : ARG LARADOCK_PHP_VERSION
Step 2/117 : FROM letsdockerize/laradock-php-fpm:2.4-${LARADOCK_PHP_VERSION}
 ---> e3d0ee5192e7
Step 3/117 : LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
 ---> Running in 3c0feed11948
Removing intermediate container 3c0feed11948
 ---> 016c4fb4b8d7
Step 4/117 : ARG LARADOCK_PHP_VERSION
 ---> Running in 9e983dae02f4
Removing intermediate container 9e983dae02f4
 ---> 5e2ededa0f8a
Step 5/117 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in a72e6830f3d1
Removing intermediate container a72e6830f3d1
 ---> 600bd709b83d
Step 6/117 : RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip &&       docker-php-ext-configure zip --with-libzip &&       docker-php-ext-install zip &&       php -m | grep -q 'zip'
 ---> Running in 1469322a9ffe
+ apt-get update -yqq
+ pecl channel-update pecl.php.net
Updating channel "pecl.php.net"
Update of Channel "pecl.php.net" succeeded
+ apt-get install -yqq apt-utils libzip-dev zip unzip
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip &&       docker-php-ext-configure zip --with-libzip &&       docker-php-ext-install zip &&       php -m | grep -q 'zip'' returned a non-zero code: 100
```

![image](https://user-images.githubusercontent.com/51204470/121385886-cdf34580-c949-11eb-9496-394cdb39904f.png)

**Comment by codeinfo** [comment]
me too

**Comment by orangbus** [comment]
Try it a few times, or you can ask me to import the image

**Comment by githubzhangwei** [comment]
me too!
![image](https://user-images.githubusercontent.com/26473383/129013741-e76bb9db-47a5-4c47-8034-c71384efcb86.png)

**Comment by lonsty** [comment]
![image](https://user-images.githubusercontent.com/42596173/132235319-8a5445c9-5f0a-4e42-a826-82a6411a61d8.png)

**Comment by kacol24** [comment]
@lonsty I'm having the exact issue as yours. Have you found a solution yet?

![Screen Shot 2021-10-19 at 13 21 36](https://user-images.githubusercontent.com/11154858/137854714-551815a6-2852-4b68-b34c-a00962db8a55.png)

**Comment by gerdzhikov** [comment]
The problem is still there:

- OSX: 10.15.7 (19H1713)
- Laradock 10.0
- Ubuntu 16.04.6 LTS

**Comment by robertopc** [comment]
I had the same issue. In my case I set FALSE in the directive PHP_FPM_INSTALL_IMAGEMAGICK.
And workarounded this problem.
