### ISSUE TITLE
NPM: execute docker-compose build workspace error

### ISSUE THREAD

**Issue by Seagant** [laradock/laradock#3003]
hi,
error msg: curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
/bin/sh: 1: .: Can't open /home/laradock/.nvm/nvm.sh

**Comment by Seagant** [comment]
error msg: curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
/bin/sh: 1: .: Can't open /home/laradock/.nvm/nvm.sh

**Comment by egege** [comment]
国内访问GitHub服务不稳定，等着过了这段敏感时期，你再试一下。着急的话就只能梯子了
