### ISSUE TITLE
Session error message when starting phpmyadmin

### ISSUE THREAD

**Issue by mbasfour** [LaraDock/laradock#301]
I'm getting this error message `session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/sessions)` when opening phpmyadmin in browser.
It's seems that the session files are created but they are empty.
How can i fix this issue?

Here is my system information:

- Host: Windows 7 64b
- Docker toolbox: 1.12
- Laradock: 4..0

@appleboy

**Comment by Hajsen** [comment]
This also happened to me, seems to be related to symfony but couldn't find anything there. https://github.com/symfony/symfony/issues/17845

**Comment by Hajsen** [comment]
Found the error!!! You have to unmount sessions, you can do this easily with the help of kitematic by pressing remove and it will look like below. Would open a pull request for this but I am still a newbie with dockers.

![unmounting](https://cloud.githubusercontent.com/assets/9657107/18485451/288fa3dc-79ed-11e6-88ad-66b746336b41.PNG)

**Comment by mbasfour** [comment]
I updated to latest version and it seems to be fixed.

**Comment by appleboy** [comment]
@mbasfour Could you close this issue?
