### ISSUE TITLE
I used php-worker to keep the laravels process running。

### ISSUE THREAD

**Issue by 444136347** [laradock/laradock#3010]
<img width="600" alt="WeChatcea593f04309ecbbf3216f23eac3e808" src="https://user-images.githubusercontent.com/22359201/124237346-030a4680-db4a-11eb-8064-31ea872bca20.png">

supervisor：
```
[program:laravel-s]
command=php  /var/www/yourmao-api/bin/laravels start -i
numprocs=1
autorestart=true
autorestart=true
startretries=3
stopwaitsecs=60
redirect_stderr=true
user=root
stdout_logfile=/var/www/yourmao-api/storage/logs/laravel-s.log
stdout_logfile_maxbytes=0
```
I got this error:
[ERROR] LaravelS requires swoole extension, try to `pecl install swoole` and `php --ri swoole`.

**Comment by lionslair** [comment]
Have you enabled it in the .env file. 
Actually exists three times for different containers

PHP_WORKER_INSTALL_SWOOLE=false
WORKSPACE_INSTALL_SWOOLE=false
PHP_FPM_INSTALL_SWOOLE=false
