### ISSUE TITLE
Laradock does not work for users with Apple Silicon processor (yarn missing in workspace)

### ISSUE THREAD

**Issue by johnennewtpximpact** [laradock/laradock#3034]
### Description:
The libssl library version used on Ubuntu 20.04 will segfault when connected to some TLS servers, for example `curl https://dl.yarnpkg.com`

yarn not being available after build is the most obvious symptom of the problem.
In the .env file with all defaults set, including `WORKSPACE_INSTALL_YARN=true` the build appears to work fine (no errors).
However, when connected to the workspace container, running any `yarn` command will result in the error `bash: yarn: command not found`

If the user runs:
`curl https://dl.yarnpkg.com` then the output is `Segmentation fault` 

This appears to be happening during build although its not registered as an error:

`curl -o- -L https://yarnpkg.com/install.sh`
Segmentation fault

`openssl version` --> OpenSSL 1.1.1f  31 Mar 2020

This is a known fault recorded in the Docker for Mac release notes:
https://docs.docker.com/docker-for-mac/release-notes/#known-issues

> On Apple Silicon in native arm64 containers, older versions of libssl in debian:buster, ubuntu:20.04 and centos:8 will segfault when connected to some TLS servers, for example curl https://dl.yarnpkg.com. The bug is fixed in newer versions of libssl in debian:bullseye, ubuntu:21.04 and fedora:35.

So Laradock now no longer works for people using Apple Silicon and will continue to not work until the base image is updated to `ubuntu:21.04` unless anyone can work out a workaround.

Note - it was working when the base image used ubuntu:18.04

### Expected Behavior:
When connected to the workspace container bash shell, executing `yarn` should trigger yarn if it was set to be installed in the .env file

Running `curl https://dl.yarnpkg.com` the output should not be `Segmentation fault` 

### Context information:

**Output of `git rev-parse HEAD`**

```
471e69977c90666a7440e35a7a9d82f76f9db835
```

**Output of `docker version`**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:23 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Mac Silicon, Big Slur, 11.4.1
```

### Steps to reproduce the issue:

On a Mac Silicon computer:

1. git clone git@github.com:laradock/laradock.git
2. cd laradock
3. cp .env.example .env
4. docker-compose build workspace
5. docker-compose up -d workspace
6. docker-compose exec workspace bash
7. `yarn` -- output currently `bash: yarn: command not found`
8. `curl https://dl.yarnpkg.com` -- output currently `Segmentation fault`

**Comment by johnennewmanifesto** [comment]
Looks like Sail has the same issue - they went for the Ubuntu upgrade to 21.04 to solve:

https://github.com/laravel/sail/issues/159

**Comment by zlanich** [comment]
I too would like to know how this could be fixed in Laradock. I just received my M! MacBook Pro, and just discovered that none of my local dev environments work yet.

**Comment by zlanich** [comment]
I too would like to know how this could be fixed in Laradock. I just received my M! MacBook Pro, and just discovered that none of my local dev environments work yet.

**Comment by PopkornKevin** [comment]
+1 for this issue, can't get laradock to work

**Comment by heikokrebs** [comment]
+1

**Comment by maurosbu** [comment]
+1
