### ISSUE TITLE
Can not install mssql extension on php-fpm

### ISSUE THREAD

**Issue by dinhchuong7913** [laradock/laradock#3042]
### Description:

After change config
PHP_FPM_INSTALL_MSSQL=true
WORKSPACE_INSTALL_MSSQL=true
I run build php by running command docker compose build php-fpm

I get the error

```
 => ERROR [laradock_php-fpm 42/76] RUN set -eux;   if [ true = true ]; then     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then       apt-get -yqq install freetds-dev libsybdb5       && ln -s /u  6.3s
------
 > [laradock_php-fpm 42/76] RUN set -eux;   if [ true = true ]; then     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then       apt-get -yqq install freetds-dev libsybdb5       && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/libsybdb.so       && doc
```
`failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -eux;   if [ ${INSTALL_MSSQL} = true ]; then     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then       apt-get -yqq install freetds-dev libsybdb5       && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/libsybdb.so       && docker-php-ext-install mssql pdo_dblib       && php -m | grep -q 'mssql'       && php -m | grep -q 'pdo_dblib'     ;else       apt-get install -yqq apt-transport-https gnupg       && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -       && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list       && apt-get update -yqq       && ACCEPT_EULA=Y apt-get install -yqq unixodbc unixodbc-dev libgss3 odbcinst msodbcsql17 locales       && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen       && ln -sfn /etc/locale.alias /usr/share/locale/locale.alias       && locale-gen       && if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "2" ]; then         pecl install pdo_sqlsrv-5.8.1 sqlsrv-5.8.1       ;elif [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "1" ]; then         pecl install pdo_sqlsrv-5.6.1 sqlsrv-5.6.1       ;elif [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "0" ]; then         pecl install pdo_sqlsrv-5.3.0 sqlsrv-5.3.0       ;else         pecl install pdo_sqlsrv sqlsrv       ;fi       && docker-php-ext-enable pdo_sqlsrv sqlsrv       && php -m | grep -q 'pdo_sqlsrv'       && php -m | grep -q 'sqlsrv'     ;fi   ;fi]: exit code: 100`

**System info: Mac, Windows or Linux. Include which disto/version**
Mac 11.5.2

Please help me

**Comment by GautierDele** [comment]
@bestlong thanks for workspace fix, will see what I can do on php-fpm

**Comment by GautierDele** [comment]
It seems like i'm not able to install mssql odbc drivers on debian ... Will investigate more

**Comment by bestlong** [comment]
Hi @GautierDele 

php-fpm image now base on Debian 11 (bullseye).

unfortunately Microsoft ODBC 17 not support it.

Maybe I will locked php-fpm base image on Debian 10 (buster) or change into FreeTDS.

**Comment by typebrad** [comment]
I have pulled all changes and also experiencing the same issue as OP @dinhchuong7913

**Comment by GautierDele** [comment]
Hi @bestlong,

Yeah maybe waiting a bit for packages to release could be a good idea,

For now, all users can use a former image from php-fpm / workspace.

Did you have time to look at my PR ?
Could be great since I need SMB in my project 😄 

Thanks

**Comment by arthr** [comment]
How can i solve that problem with laradock/php-fpm msodbcsql17 install?

**Comment by joe-niland** [comment]
I agree with @GautierDele - should hardcode to Debian 10 for now.

@arthr you can try changing the base image to use the php-buster variant.

**Comment by wdarking** [comment]
https://github.com/MicrosoftDocs/sql-docs/issues/6494

**Comment by wdarking** [comment]
Temp workaround:

1 - Comment the line 17 from the file https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile on your installation of laradock, and paste this: 

`FROM laradock/php-fpm:buster-7.4`

2 - Create a file Docker-7.4 inside the folder laradock/php-fpm with the contents of this file: https://raw.githubusercontent.com/laradock/php-fpm/master/Dockerfile-7.4 then change the line 7 from:

`FROM php:7.4-fpm` to `FROM php:7.4-fpm-buster`

3 - Inside the laradock directory, rebuild the php-fpm image with this command:

```
docker build -f php-fpm/Dockerfile-7.4 . -t laradock/php-fpm:buster-7.4
```

then

```
docker-compose build php-fpm
```

Everything should be built without errors. Now you can start up your containers, with

```
docker-compose build nginx mssql workspace
```
It worked for me. I hope it works for you as well.

**Comment by banpar** [comment]
> Temp workaround:
> 
> 1 - Comment the line 17 from the file https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile on your installation of laradock, and paste this:
> 
> `FROM laradock/php-fpm:buster-7.4`
> 
> 2 - Create a file Dockerfile-7.4 inside the folder `laradock/php-fpm` with the contents of this file: https://raw.githubusercontent.com/laradock/php-fpm/master/Dockerfile-7.4 then change the line 7 from:
> 
> `FROM php:7.4-fpm` to `FROM php:7.4-fpm-buster`
> 
> 3 - Inside the laradock directory, rebuild the php-fpm image with this command:
> 
> ```
> docker build -f php-fpm/Dockerfile-7.4 . -t laradock/php-fpm:buster-7.4
> ```
> 
> then
> 
> ```
> docker-compose build php-fpm
> ```
> 
> It should build without errors. Now you can start up your containers, with
> 
> ```
> docker-compose up -d nginx mssql workspace
> ```
> 
> It worked for me. I hope it works for you as well.

When i try to run the second step i got this error:
ERROR [internal] load metadata from docker.io/laradock/php-fpm:buster-7.4

and then build fail.

**Comment by arthr** [comment]
> PHP_FPM_BASE_IMAGE_TAG_PREFIX=20210814

Thx for the help! <3

**Comment by duchymor** [comment]
It seems Microsoft finally released an update https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15, just need to check if the issue healed itselfs...

**Comment by MiguelAngelVM** [comment]
I couldn't fix it with this
https://github.com/laradock/laradock/issues/3042#issuecomment-913623296

Does anyone have another solution?
