### ISSUE TITLE
PHP-FPM LDAP - Failure to create /etc/ldap/ldap.conf, can't connect to AD Server

### ISSUE THREAD

**Issue by dqfan2012** [laradock/laradock#3044]
### Description:
When PHP_FPM_INSTALL_LDAP is set to true, all the necessary files and configuration should be put in place so that the docker container can make successful LDAP connections. The **/etc/ldap/ldap.conf** file is missing after building the image and starting the container, which causes an ldap_bind() error when attempting to connect to an LDAP server.

Note: The workspace container installs ldap properly, and it just works out of the box.

### Expected Behavior:
When I set PHP_FPM_INSTALL_LDAP to true, I expect all the necessary LDAP configuration to be installed so that the LDAP connection works out of the box.

### Context information:

**Output of `git rev-parse HEAD`**

```
910211ba2d0212532d32b3f5aca360ca84ff830d
```

**Output of `docker version`**

```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
```

**System info: Mac, Windows or Linux. Include which disto/version**
I work on this app on both Windows 10 and MacOS.

```
MacOS Big Sur 11.5.2
Windows 10.0.19042 Build 19042
```

### Steps to reproduce the issue:

I've configured a Laravel application to use Laravel Breeze with the composer package LdapRecord to authenticate Active Directory users in the application.

1. Setup a Laravel application.
2. Install Laravel Breeze.
3. Install LdapRecord
4. Configure LdapRecord to connect to an Active Directory server (we use SSL instead of TLS but I don't think this matters) with database syncing - follow the documentation, config goes in a .env file.
5. Make sure to install LDAP in both the Workspace and PHP-FPM containers.
6. You can run `php artisan ldap:test` in both containers to test your LDAP connection. OR
7. You can test your LDAP connection by attempting to log in with an Active Directory user (using the proper username/password)
8. You'll see that the PHP-FPM test/connection fails while the Workspace test is successful.
9. Create the typical /etc/ldap/ldap.conf file in the PHP-FPM container and try again.
10. You'll see that it now works.

### Stacktrace & Additional info:

```
No additional info.
```

**Comment by dant89** [comment]
Similar issues here, only seems to have happened recently though as this certainly worked in the past.
