### ISSUE TITLE
Service 'workspace' failed to build : Build failed

### ISSUE THREAD

**Issue by ThArthur** [laradock/laradock#3059]
### Description:

After running docker-compose this error appears, and when it isn't, another "php-fpm" appears

**Output of `docker version`**

```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 10 Pro
```

### Steps to reproduce the issue:
```

1.docker-compose up -d nginx postgres-postgis pgadmin redis php-fpm workspace
```

![image](https://user-images.githubusercontent.com/38262050/134072416-8ef41172-608e-40d9-9939-9c25f8e4ad06.png)

**Comment by adjarriawan** [comment]
microsoft not ready for release debian 11 driver msodbc 17
