### ISSUE TITLE
ERROR: Service 'workspace' failed to build : Build failed

### ISSUE THREAD

**Issue by juejixiaohaipi** [laradock/laradock#3062]
+ add-apt-repository -y ppa:pinepain/libv8-archived
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:6 http://ppa.launchpad.net/pinepain/libv8-archived/ubuntu focal InRelease
Err:7 http://ppa.launchpad.net/pinepain/libv8-archived/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists...
E: The repository 'http://ppa.launchpad.net/pinepain/libv8-archived/ubuntu focal Release' does not have a Release file.
The command '/bin/sh -c set -xe;   if [ ${INSTALL_V8JS} = true ]; then     add-apt-repository -y ppa:pinepain/libv8-archived     && apt-get update -yqq     && apt-get install -y libv8-5.4 &&     if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then       pecl install v8js-0.6.4;     else       pecl install v8js;     fi     && echo "extension=v8js.so" >> /etc/php/${LARADOCK_PHP_VERSION}/cli/php.ini     && php -m | grep -q 'v8js'   ;fi' returned a non-zero code: 100
ERROR: Service 'workspace' failed to build : Build failed

**Comment by juejixiaohaipi** [comment]
docker-compose build --no-cache workspace

**Comment by bestlong** [comment]
now laradock os version is 20.04

libv8-archived only supports up to 16.04.
