### ISSUE TITLE
Xdebug error on Laravel Artisan Commands

### ISSUE THREAD

**Issue by glorand** [laradock/laradock#3064]
### Description:
When run any artisan command there is an xdebug related issue.

Clear laradock installation with XDEBUG on workspace and php-fpm enabled

```
php artisan migrate
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
Nothing to migrate.
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
```

**Comment by merlinblack** [comment]
If you are not using XDebug in your workspace - edit xdebug.ini (use php --ini to find where it is) and set "xdebug.mode=off" instead of "xdebug.mode=debug". You can switch it back on temporarily the the env var XDEBUG_MODE which overrides this setting.

In addition if you *are* using Xdebug you need to remove some lines from docker-compose.yml. For the php-fpm container there is a "ports" section, forwarding php-fpm:9003 to the host. This is not correct, as it's your debugging program (e.g. PHPStorm) that opens port 9003 and listens on it for php to connect.

**Comment by onahkenneth** [comment]
@merlinblack 
Is there a reason why the "ports" section was added. It was not there previously.

**Comment by merlinblack** [comment]
> @merlinblack Is there a reason why the "ports" section was added. It was not there previously.

You would have to ask the author - having the 9003 port there is incorrect, hence why it should be removed.

**Comment by simonbuehler** [comment]
please merge this fix as its related to #797 #3083 and others

**Comment by glorand** [comment]
@merlinblack removeing the ports section it's not solve the problem :(

**Comment by merlinblack** [comment]
> @merlinblack removeing the ports section it's not solve the problem :(

Unfortunately, Xdebug is a quirky beast - I can only suggest to make sure Xdebug can contact the port it is configured for on your localhost. You can use Netcat, or start up a temporary HTTP server on port 9003 for example and try to use curl or similar. Look in the logs for Xdebug.

**Comment by glorand** [comment]
I think there is also a version problem. For example with version 3.1.3 xdebug works fine but with version 3.1.2 no.  And the problems starts when the php 8 was added. Before everything just woks fine. Hard to understand why this problem is not solved and every month a new not wide used service is added to laradock.

**Comment by merlinblack** [comment]
There was a problem with a  laradock dependency dragging in another version of php and causing havok too. Something to check for 

⁣Sent from BlueMail ​

**Comment by paulocjota** [comment]
My 2 cents. If you are running with Laravel Sail you can put in your .env file:
`SAIL_XDEBUG_CONFIG="log_level=0"`
to get rid these messages

remember to rerun containers (sail down then sail up -d) after change
