### ISSUE TITLE
When I try to install ioncube, the following error is now displayed when arg is enabled.

### ISSUE THREAD

**Issue by alienwebvision** [laradock/laradock#3067]
Step 80/179 : RUN if [ ${INSTALL_IONCUBE} = true ]; then     curl -L -o /tmp/ioncube_loaders_lin_x86-64.tar.gz https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz     && tar zxpf /tmp/ioncube_loaders_lin_x86-64.tar.gz -C /tmp     && mv /tmp/ioncube/ioncube_loader_lin_${LARADOCK_PHP_VERSION}.so $(php -r "echo ini_get('extension_dir');")/ioncube_loader.so     && printf "zend_extension=ioncube_loader.so\n" > $PHP_INI_DIR/conf.d/0ioncube.ini     && rm -rf /tmp/ioncube* ;fi
 ---> Running in 1052b1d29b85
/bin/sh: 1: [: true: unexpected operator
Removing intermediate container 1052b1d29b85
 ---> 67cbc63cf97d

**Comment by alienwebvision** [comment]
This error possibly interrupts the installation of the ioncube extension.

**Comment by bestlong** [comment]
set `.env`

```
WORKSPACE_INSTALL_IONCUBE=true
PHP_FPM_INSTALL_IONCUBE=true
```

then run `docker-compose build --pull --no-cache php-fpm workspace`
