### ISSUE TITLE
Improved laravel speed

### ISSUE THREAD

**Issue by proctar** [LaraDock/laradock#307]
Hi,

Laravel is slow without OpCache if used as a back-end for API calls.
Opcache is installed but apparently not activated.

I had to add the following configuration to laravel.ini (php-fpm image) to enable opcache and dramatically speed up things:

zend_extension=opcache.so
opcache.enable="1"
opcache.memory_consumption="256"
opcache.use_cwd="0"
opcache.validate_timestamps="0"
opcache.fast_shutdown="1"
opcache.max_file_size="0"

Hope this helps

**Comment by Mahmoudz** [comment]
@proctar wow that's very nice, would you like to make a PR with that, so I can merge it?

**Comment by proctar** [comment]
I'm not familiar with pull requests, and I don't have a fork/branch of your code.

Can you just paste those few lines into your own code?

Please note: i've found that on internet somewhere, this is my work.

Besides this, I strongly suggest to comment out "opcache.validate_timestamps = 0" on dev machines, otherwise the Opcache is not refreshed when editing/saving dev files. Only use on prod server I guess.

**Comment by LarryEitel** [comment]
Found this in the docs:

`opcache.validate_timestamps` `boolean`

If enabled, OPcache will check for updated scripts every opcache.revalidate_freq seconds. **When this directive is disabled, you must reset OPcache manually via opcache_reset(), opcache_invalidate() or by restarting the Web server for changes to the filesystem to take effect.**


`opcache.revalidate_freq` `integer`

How often to check script timestamps for updates, in seconds. 0 will result in OPcache checking for updates on every request.

This configuration directive is ignored if opcache.validate_timestamps is disabled.

**Comment by Mahmoudz** [comment]
@proctar can you verify that it's working now. You can pull the master branch to get the changes. See the changes here #5640bd963d5fde4c8761e7b1c62d56f2dea63026
