### ISSUE TITLE
Latest docker throws "unexpected character "-" in variable name" while setting up weaver (WEAVER_ATHENA_CMD)

### ISSUE THREAD

**Issue by ryanrapini** [laradock/laradock#3076]
### Description:
Updated my system the other day and now when running `docker-compose up -d apache2 postgres redis workspace mailhog` I get:

```
unexpected character "-" in variable name near "-S\nWEAVER_MAX_WORKERS=10\nWEAVER_MAX_CONVERSION_QUEUE=50\nWEAVER_WORKER_TIMEOUT=90\nWEAVER_CONVERSION_FALLBACK=false\n\n# CloudConvert\n# API key can be found: https://cloudconvert.com/user/profile\n# CLOUDCONVERT_API=https://api.cloudconvert.com\n# CLOUDCONVERT_KEY=\n\n# Monitoring\n# STATSD_ADDRESS=\n# STATSD_PREFIX=\n# SENTRY_DSN="
```

### Context information:
I assume this is a result of a docker update, my current version is `Docker version 20.10.8, build 3967b7d28e` - unsure what my Docker was at before it updated but i have 

```
docker-1:20.10.6-1-x86_64.pkg.tar.zst
docker-1:20.10.7-1-x86_64.pkg.tar.zst
docker-1:20.10.8-1-x86_64.pkg.tar.zst
```

in my pacman cache. Both 10.7 and 10.6 were working, I believe.

Tried updating my laradock to the latest release, made no difference.

currently on tag `v12.1` but also tried `v11.0`

OS: Manjaro 21.1.5 Pahvo
Kernel: x86_64 Linux 5.15.0-1-MANJARO

To fix this, I opened up `weaver/conf/sample.env`
and changed this line:
```
WEAVER_ATHENA_CMD=athenapdf -S
```
to
```
WEAVER_ATHENA_CMD="athenapdf -S"
```

This fixed the issue. Just capturing this in case anyone else has this issue.

**Comment by bestlong** [comment]
fixed by #3066

**Comment by enashed** [comment]
I had the same issue, had to go through *.env  files, and put any thing that has a space between double quotes. This fixed the issue for me!

**Comment by mmshehatta** [comment]
Adding double quotes  in error line in .env file fix my problem...thanks

**Comment by deepansh96** [comment]
Same issue! I was trying to build a container for a Django app and in my `.env` file, there was a setting
```env
ALLOWED_HOSTS=[::1] *
```

Changed it to 
```env
ALLOWED_HOSTS="[::1] *"
```
And it's working fine now

**Comment by lagoonos** [comment]
Had the same issue with '.' and '-' in variable names in *.env file.

Disabling the following in Docker Desktop fixed it for me:

**_Settings -> General -> Use Docker Compose V2_**

**Comment by IssacAnand** [comment]
Hi. Could someone explain and/or show how to access weaver/conf/sample.env and make the changes. New to docker and learning your help would be appreciated
