### ISSUE TITLE
mongo db get Unauthorize command listDatabases requiere authentication

### ISSUE THREAD

**Issue by pokemonhan** [laradock/laradock#3081]
### Description:
mongo db get Unauthorize command listDatabases requiere authentication

### Expected Behavior:
can connet mongo well.

Docker version 20.10.8, build 3967b7d

**Output of `docker-compose version`**

Docker Compose version v2.0.0

**System info: Mac, Windows or Linux. Include which disto/version**

Windows 10

**Comment by Asimilamy** [comment]
@pokemonhan you can try to remove the username and password field in .env file

```
MONGODB_PORT=27017
MONGO_USERNAME=
MONGO_PASSWORD=
```
