### ISSUE TITLE
xdebug 3.1 not work 

### ISSUE THREAD

**Issue by liminworks** [laradock/laradock#3083]
### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
{paste here}
```

**Output of `docker-compose version`**

```
{paste here}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
{paste here}
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

![image](https://user-images.githubusercontent.com/16682560/138817446-bc7e5348-e5b6-42d4-ad61-760457a2cdb8.png)
![image](https://user-images.githubusercontent.com/16682560/138817731-7636f130-0092-4992-8a0c-9efc7a716ef1.png)

![image](https://user-images.githubusercontent.com/16682560/138817514-33a48afe-c338-43a9-964d-66e968e99f40.png)
![image](https://user-images.githubusercontent.com/16682560/138817633-a890fbf6-f959-4f6b-a267-237c8503d7d9.png)

![image](https://user-images.githubusercontent.com/16682560/138817663-3e8325c3-9538-462a-8c3e-8867b00fea9b.png)

**Comment by aveblackmetalstudio** [comment]
Does anybody know how to resolve it?

**Comment by aveblackmetalstudio** [comment]
In that way it is working

laradock/php-fpm/Dockerfile
![image](https://user-images.githubusercontent.com/26859846/142198701-2e489c46-b1e0-413c-8792-21d9c927b63a.png)

laradock/php-fpm/xdebug.ini
![image](https://user-images.githubusercontent.com/26859846/142198629-e40d517c-3a04-46d5-8b66-41e6e46840d6.png)

**Comment by liminworks** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by glorand** [comment]
Dis issue still is open?

**Comment by liminworks** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liminworks** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
