### ISSUE TITLE
php-fpm take up all memory

### ISSUE THREAD

**Issue by victornguyen195** [laradock/laradock#3085]
### Description:

I use laradock to build environment include workspace, php7.3-fpm/php7.4-fpm, nginx, mysql, elasticsearch. 
Everythings seem ok but when I try to type server name in browser then hit enter. php-fpm container starting take up all memory. I
### Context information:

**Output of `docker version`**

```
Docker version 20.10.9, build c2ea9bc

```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu 20.04 LTS
```

### Steps to reproduce the issue:

1. Config .env file about mysql version 5.7 or 8.0
2. Change config of PHP_FPM_INSTALL_SOAP=true, WORKSPACE_INSTALL_SOAP=true
3. Config nginx in default.conf

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by Witti** [comment]
I have the same issue. 
The php-fpm process is running with 100% cpu usage and fills up the memory. 

Docker: 20.10.9
Docker-Compose: 2.0.1
OS: Arch Linux
