### ISSUE TITLE
workspace root user cannot use nvm, npm or gulp

### ISSUE THREAD

**Issue by edmundluong** [LaraDock/laradock#309]
Hi,

I have noticed that the `laradock` user is the only user in the `workspace` container that is able to use the nvm, npm and gulp binaries. Is there any rationale behind this? Why can't the `root` user use these binaries?

I am trying to deploy a Laravel application to a DigitalOcean Docker 1-Click droplet but I cannot execute any gulp commands as `root` in the `workspace` container. I run into permission issues when trying to run `gulp install --production` as the `laradock` user on the server. Anything I can do to work around this?

I have been following this guide to deploy my application to production: https://github.com/LaraDock/laradock/blob/master/_guides/digital_ocean.md

**Comment by philtrep** [comment]
The fix I found is: 
```
docker-compose exec -T workspace bash -c 'export NVM_DIR=/home/laradock/.nvm; [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; <nvm/npm commands>'
```
Which is basically just running the last 2 lines in the `laradock` user `~/.bashrc` followed by my commands.
I too would like to know the rational behind not having the binaries available to root?

**Comment by edmundluong** [comment]
@philtrep 

Perhaps if your solution can be generalized, it might be worth a pull request IMO for the sheer convenience of having access to those binaries as root.

What are your thoughts on this, @Mahmoudz ?

**Comment by KikeMendez** [comment]
I'm having the same issue, i can not use gulp inside workspace all the rest of comands are working fine, Can you tell me how to fix it?

**Comment by philtrep** [comment]
@KikeMendez 

You can use the `laradock` user to run commands in the workspace like so:
`docker-compose exec --user=laradock workspace bash`
you should then be able to run `gulp`.

**Comment by philtrep** [comment]
@edmundluong 
Made the PR but note that this won't work for commands that don't load the .bashrc ie. `docker-compose exec workspace bash -c '...'`. I tried making it work for the best part of a day and my fix above is the only thing that does it...

**Comment by KikeMendez** [comment]
I runned gulp but now I'm having this issue, 
stream.js:74
      throw er; // Unhandled stream error in pipe.
     ^Error: EACCES: permission denied, open '/var/www/laravel/public/css/app.css.map'
    at Error (nativ

**Comment by suncoastkid** [comment]
Using  docker-compose exec --user=laradock workspace bash I still get gulp command not found.

**Comment by Seros** [comment]
I just found a way for commands like `docker-compose exec -T --user=laradock workspace bash -c 'npm-command'`
You could to add the -i parameter to bash like `docker-compose exec -T --user=laradock workspace bash -c -i 'npm-command'` to make interactively inside the container and to load .bashrc
