### ISSUE TITLE
Can't change display_errors.

### ISSUE THREAD

**Issue by seriiserii825** [laradock/laradock#3093]
### Description:

I install laradock, and after start a workspace with nginx and mysql. 
`sudo service  apache2 stop && sudo docker-compose up -d nginx php-fpm mysql workspace`

And all works fine, but i forgot to set display errors. 

And in .env i saw, that my php version is 7.4. 
I went to php7.4 and set display_errors to On. 

After i stoped laradock. 

`sudo docker-compose down`

And after rebuild php. 
`sudo docker-compose up -d --force-recreate --build php-fpm`

But after restart laradock, in phpinfo(), display_errors is still Off. 

https://i.imgur.com/niaOOl7.png

Thanks in advance.

**Comment by Skyline404** [comment]
watch in `laravel.ini` for `display_errors` and try to rebuild workspce container also
