### ISSUE TITLE
docker-compose up -d nginx mysql failed.

### ISSUE THREAD

**Issue by lifeblood** [laradock/laradock#3097]
Zend Extension Api No:   320190902
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
The command '/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       gnupg2       git       libzip-dev zip unzip &&       if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then         docker-php-ext-configure zip;       else         docker-php-ext-configure zip --with-libzip;       fi &&       docker-php-ext-install zip &&       php -m | grep -q 'zip'' returned a non-zero code: 2
ERROR: Service 'php-fpm' failed to build : Build failed

**Comment by johnathansantos** [comment]
upgrade Docker version 19.03.6 to Docker version 20.10.12

Centos 7

https://docs.docker.com/engine/install/centos/#install-using-the-repository
```
sudo service docker stop

sudo yum remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine


 sudo yum install -y yum-utils
 
 sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
 
 sudo yum install docker-ce docker-ce-cli containerd.io
 
 sudo systemctl start docker
```

**Comment by lifeblood** [comment]
fixed
