### ISSUE TITLE
schema:dump fails due to pg_dump version incompatibility with postgres

### ISSUE THREAD

**Issue by ronaldwanink** [laradock/laradock#3098]
### Description:
`php artisan schema:dump` fails: pg_dump version 12  incompatible with postgres 14

### Expected Behavior:
In the workspace container, squashing the migrations with `php artisan schema:dump` fails and gives an error

pg_dump: error: server version: 14.0; pg_dump version: 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
pg_dump: error: aborting because of server version mismatch

Info from previous similar issues does not help, since no separate postgres client version 14 seems available

### Context information:
e6d5f17e4b203aeb96f378a154485b430ea598bf

**Output of `docker version`**
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Output of `docker-compose version`**
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

**System info: Mac, Windows or Linux. Include which disto/version**
Latest Laradock, running Apache2, phpfpm and postgres

### Steps to reproduce the issue:

1. `php artisan schema:dump` 

### Stacktrace & Additional info:

The command "pg_dump --no-owner --no-acl -Fc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --username="${:LARAVEL_LOAD_USER}" --dbname="${:LARAVEL_LOAD_DATABASE}" --file="${:LARAVEL_LOAD_PATH}" --exclude-table-data="*.users" --exclude-table-data="*.password_resets" --exclude-table-data="*.failed_jobs" --exclude-table-data="*.personal_access_tokens" --exclude-table-data="*.departments" --exclude-table-data="*.maps" --exclude-table-data="*.floors" --exclude-table-data="*.languages" --exclude-table-data="*.categories" --exclude-table-data="*.module_types" --exclude-table-data="*.modules" --exclude-table-data="*.products" --exclude-table-data="*.beacons" --exclude-table-data="*.iots" --exclude-table-data="*.workplaces" --exclude-table-data="*.groups" --exclude-table-data="*.workplaces_in_groups" --exclude-table-data="*.companies" --exclude-table-data="*.locations" --exclude-table-data="*.buildings"" failed.

Exit Code: 1(General error)

Working directory: /var/www

Output:
================

Error Output:
================
pg_dump: error: server version: 14.0; pg_dump version: 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
pg_dump: error: aborting because of server version mismatch
 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"pg_dump --no-owner --no-acl -Fc --host=\"${:LARAVEL_LOAD_HOST}\" --port=\"${:LARAVEL_LOAD_PORT}\" --username=\"${:LARAVEL_LOAD_USER}\" --dbname=\"${:LARAVEL_LOAD_DATABASE}\" --file=\"${:LARAVEL_LOAD_PATH}\" --exclude-table-data=\"*.users\" --exclude-table-data=\"*.password_resets\" --exclude-table-data=\"*.failed_jobs\" --exclude-table-data=\"*.personal_access_tokens\" --exclude-table-data=\"*.departments\" --exclude-table-data=\"*.maps\" --exclude-table-data=\"*.floors\" --exclude-table-data=\"*.languages\" --exclude-table-data=\"*.categories\" --exclude-table-data=\"*.module_types\" --exclude-table-data=\"*.modules\" --exclude-table-data=\"*.products\" --exclude-table-data=\"*.beacons\" --exclude-table-data=\"*.iots\" --exclude-table-data=\"*.workplaces\" --exclude-table-data=\"*.groups\" --exclude-table-data=\"*.workplaces_in_groups\" --exclude-table-data=\"*.companies\" --exclude-table-data=\"*.locations\" --exclude-table-data=\"*.buildings\"\" failed.

Exit Code: 1(General error)

Working directory: /var/www

Output:
================

Error Output:
================
pg_dump: error: server version: 14.0; pg_dump version: 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
pg_dump: error: aborting because of server version mismatch
 at /var/www/vendor/symfony/process/Process.php:270)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/PostgresSchemaState.php(30): Symfony\\Component\\Process\\Process->mustRun()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/DumpCommand.php(44): Illuminate\\Database\\Schema\\PostgresSchemaState->dump()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\DumpCommand->handle()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#8 /var/www/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#10 /var/www/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#11 /var/www/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /var/www/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#15 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()

**Comment by litvinenkow** [comment]
confirming, issue is still alive
