### ISSUE TITLE
xdebug version to install in php-fpm according php version doesn't work in 7.4

### ISSUE THREAD

**Issue by albsierra** [laradock/laradock#3099]
https://github.com/laradock/laradock/blob/b3b0b0c40fcba1fc891cb6201d3d6f01e6cebfdb/php-fpm/Dockerfile#L223

The version of xdebug that is installed according php version (7.4) is different in workspace that in php-fpm.

In my case, I needed paste [the lines that install xdebug from workspace Dockerfile](https://github.com/laradock/laradock/blob/b3b0b0c40fcba1fc891cb6201d3d6f01e6cebfdb/workspace/Dockerfile#L333) to php-fpm Dockerfile, to get debugging.
```
  if [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
    pecl install xdebug-3.0.0; \
  else \
    if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
      pecl install xdebug-2.5.5; \
    else \
      if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "0" ]; then \
        pecl install xdebug-2.9.0; \
      else \
        if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ] && [ $(php -r "echo PHP_MINOR_VERSION;") = "1" ]; then \
          pecl install xdebug-2.9.8; \
        else \
          if [ $(php -r "echo PHP_MAJOR_VERSION;") = "7" ]; then \
            pecl install xdebug-2.9.8; \
          else \
            #pecl install xdebug; \
            echo "xDebug 3 required, not supported."; \
          fi \
        fi \
      fi \
    fi \
  fi && \
```

**Comment by frizikk** [comment]
This solutions worked for me.

**Comment by archer247** [comment]
Hey @albsierra thank you so much, I have been for days trying to solve error on nginx when I used xdebug on Laravel PHP 7.4 the error was recv() failed, meaning that php-fpm broke the connection, no error logs, no clues, but in the end, I did this and Is working normally, it would be great if this fix would be on master branch!

Genius!

**Comment by bnechef** [comment]
Hi.
I tried a lot of different things, but just in php-fpm until I came over this issue here. Oh my god!
Why this isn't tested before. The Dockerfile in php-fpm was updated in november, but not the workspace Dockerfile at the same time.
I didn't try the if conditions from php-fpm in workspace, but maybe it should work this way too :)

Thank you so much! @albsierra

**Comment by praveesh4u** [comment]
This solution works fine. After trying a lot of things I had almost given up on getting this fixed. @albsierra Thank you very much. You are a life saver.

**Comment by spaceageliving** [comment]
WTF is wrong with the team developing this code? It supports selecting PHP7.4, and enabling Xdebug, but somehow the code is removed to make the appropriate check to NOT install Xdebug 3 on PHP7.4. So it goes ahead and installs the wrong Xdebug version, which fails silently, presumably so people like me can waste a day of their life on this BS.
