### ISSUE TITLE
The Docker Deamon cant connect.

### ISSUE THREAD

**Issue by kayyyy** [LaraDock/laradock#31]
I am complete new to docker and i am trying to get it up & running within my laravel project.
Okay so i installed docker / docker-toolbox aud cloned the repo into my laravel application folder. e.g `/Users/chris/Desktop/code/laravoice/docker`.

Okay now i try to get it up & running. I edited my `.env` file to match the DB_HOST with my docker IP. In my case `DB_HOST=192.168.99.100`.

After this i switched to the `/docker` directory in my laravel app and run the command `docker-compose up -d`. But then i am getting the error below.
```
Host already exists: "default"
☁  docker [master] docker-machine ip default
192.168.99.100
☁  docker [master] docker-compose up -d
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
☁  docker [master] docker-machine start default
Starting "default"...
Machine "default" is already running.
```
Could you tell me what i am doing wrong? The Docker machine seems to be running, so i dont know why the daemon cant connect

**Comment by Mahmoudz** [comment]
Everything you did seems ok! let's try these steps:
1. `docker-machine stop default`
2. `docker-machine start default`
3. `docker ps` if it list anything do `docker stop {container-ID}` then `docker rm {container-ID}`
4. `docker ps -a` if it list anything do `docker rm {container-ID}`
5. `docker-compose up`

Let me know what will happen.
