### ISSUE TITLE
Unsupported config option for services service: 'phpmyadmin'

### ISSUE THREAD

**Issue by cool14521** [LaraDock/laradock#310]
root@bogonubuntu:/opt/laradock# docker-compose up -d  nginx mysql
Unsupported config option for services service: 'phpmyadmin'

root@bogonubuntu:/opt/laradock# docker -v
Docker version 1.6.2, build 7c8fca2

root@bogonubuntu:/opt/laradock# python 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2

**Comment by cool14521** [comment]
https://docs.docker.com/compose/install/

**Comment by ayaup** [comment]
docker-compose up -d nginx
Unsupported config option for services service: 'phpmyadmin'
 #cdocker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
@cool14521  我也遇到这问题了，求指导。解决了吗。我也重新安装docker了，依然不行。。
