### ISSUE TITLE
docker-compose up - PHP Fatal error:  Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s)

### ISSUE THREAD

**Issue by lonelyButterflyAtWork** [laradock/laradock#3103]
### Description:
The command "docker-compose up --build -d nginx postgres workspace" returns error:
------
```
ERROR [laradock_workspace  13/106] RUN set -eux;       if [ "2" = "1" ] || [ "2" = "2" ]; then           composer self-update --2;       else        1.0s
 > [laradock_workspace  13/106] RUN set -eux;       if [ "2" = "1" ] || [ "2" = "2" ]; then           composer self-update --2;       else           composer self-update 2;       fi:
#32 0.668 + [ 2 = 1 ]
#32 0.668 + [ 2 = 2 ]
#32 0.668 + composer self-update --2
#32 0.792 PHP Fatal error:  Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php:137
#32 0.792 Stack trace:
#32 0.792 #0 [internal function]: Composer\Util\ErrorHandler::handle()
#32 0.792 #1 phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php(137): preg_match_all()
#32 0.792 #2 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(155): Symfony\Component\Console\Formatter\OutputFormatter->format()
#32 0.792 #3 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write()
#32 0.792 #4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(641): Symfony\Component\Console\Output\Output->writeln()
#32 0.792 #5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException()
#32 0.792 #6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\ in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 137
#32 0.792
#32 0.792 Fatal error: Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php:137
#32 0.792 Stack trace:
#32 0.792 #0 [internal function]: Composer\Util\ErrorHandler::handle()
#32 0.792 #1 phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php(137): preg_match_all()
#32 0.792 #2 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(155): Symfony\Component\Console\Formatter\OutputFormatter->format()
#32 0.792 #3 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write()
#32 0.792 #4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(641): Symfony\Component\Console\Output\Output->writeln()
#32 0.792 #5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException()
#32 0.792 #6 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\ in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 137

failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -eux;       if [ "$COMPOSER_VERSION" = "1" ] || [ "$COMPOSER_VERSION" = "2" ]; then           composer self-update --${COMPOSER_VERSION};       else           composer self-update ${COMPOSER_VERSION};       fi]: exit code: 255
PS D:\docker_projects\uouw-isos\laradock> docker-compose up --build -d nginx postgres workspace
```
------
### Expected Behavior:
The docker container should build.

### Context information:

**Output of `git rev-parse HEAD`**

```
{a7d1a185ea12f5a46b2557924816b9dc075b1a85}
```

**Output of `docker version`**

```
{20.10.10}
```

**Output of `docker-compose version`**

```
{v2.1.1}
```
**PHP version**

```
{7.4}
```
**System info: Mac, Windows or Linux. Include which disto/version**

```
{Windows 10}
```

### Steps to reproduce the issue:

1. Download docker and clone laradock 
2. Type docker-compose up --build -d nginx postgres workspace in the console ( Powershell /  git bash / Ubuntu WSL
![errLaradock](https://user-images.githubusercontent.com/64274349/142649853-3895422e-31d1-4742-8f4a-008bd69312af.png)

**Comment by sz3jdii** [comment]
Same problem here on the newest Docker Desktop on macOS Monterey

**Comment by CodeBlastr** [comment]
Same problem here on Windows 10, Docker 4.2.0 (70708) and Mac OS Big Sur v 11.6

**Comment by bcdennis** [comment]
Same problem.  Windows 10, Docker 4.1.1

**Comment by mdeimert** [comment]
Same problem. macOS Big Sur Docker version 20.10.7

**Comment by OhKannaDuh** [comment]
Sounds like a composer issue

**Comment by GareginH** [comment]
Open laradock/workspace/dockerfile and add 
`libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1` before apt-utils \
so it looks like this  
![image](https://user-images.githubusercontent.com/23278167/142674727-aa214beb-1c3d-41ef-8d9e-ff4f440c6d7c.png)

**Comment by fungaldore** [comment]
Another solution, admittedly messy, in case it can be helpful: I had this same problem with the latest image and code on macOS 11.6.  I haven't tried the above solution.  I copied the last line from the laradock/workspace image build script on docker hub and stuck it after the above mentioned apt-get install command.

```
diff --git a/workspace/Dockerfile b/workspace/Dockerfile
index 092e711..9c11de9 100644
--- a/workspace/Dockerfile
+++ b/workspace/Dockerfile
@@ -73,6 +73,22 @@ RUN set -xe; \
       nasm && \
       php -m | grep -q 'zip'

+RUN /bin/sh -c set -eux \
+    && apt-get install -y software-properties-common \
+    && add-apt-repository -y ppa:ondrej/php \
+    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
+    && apt-get update \
+    && apt-get upgrade -y \
+    && apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
+      php8.0-cli php8.0-common php8.0-curl php8.0-intl php8.0-xml php8.0-mbstring php8.0-mysql \
+      php8.0-pgsql php8.0-sqlite php8.0-sqlite3 php8.0-zip php8.0-bcmath php8.0-memcached \
+      php8.0-gd php8.0-dev pkg-config libcurl4-openssl-dev libedit-dev libssl-dev libxml2-dev \
+      xz-utils libsqlite3-dev rsync sqlite3 git curl vim nano tree postgresql-client \
+    && apt-get clean \
+    && curl -s http://getcomposer.org/installer | php \
+    && echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc \
+    && mv composer.phar /usr/local/bin/composer
+
 #
 #--------------------------------------------------------------------------
 # Optional Software's Installation
```

**Comment by christiancuri** [comment]
> 

I tried your solution but not worked

**Comment by christiancuri** [comment]
> Open laradock/workspace/dockerfile and add `libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1` before apt-utils so it looks like this ![image](https://user-images.githubusercontent.com/23278167/142674727-aa214beb-1c3d-41ef-8d9e-ff4f440c6d7c.png)

Your solution worked for me

**Comment by issamlk1** [comment]
> Open laradock/workspace/dockerfile and add `libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1` before apt-utils so it looks like this ![image](https://user-images.githubusercontent.com/23278167/142674727-aa214beb-1c3d-41ef-8d9e-ff4f440c6d7c.png)

thank you it work for me on Mac OS Big Sur

**Comment by Azmandios** [comment]
> Open laradock/workspace/dockerfile and add `libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1` before apt-utils so it looks like this ![image](https://user-images.githubusercontent.com/23278167/142674727-aa214beb-1c3d-41ef-8d9e-ff4f440c6d7c.png)

thank you, it works for me on Ubuntu 20.04 LTS

**Comment by pitylee** [comment]
This solution also works on Mac.
Yet, in some cases, if used via git submodule, it may be quite impossible to make the change, so imo the easiest is to automate and include in the readme what to do if someone encounters this problem.
This why, I created a command that will make the change and hereby I share with you guys, maybe it is easier.

> 
> With the latest Laradock version you will get some errors during the docker-compose build, that can be easily fixed by injecting some dependencies, in this case, since it is a submodule, it is required to do so after the submodule got initialised, in the Laradock workspace Dockerfile with the command:
> 
> ```
> awk '{sub(/apt-utils/,"libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1 apt-utils")}1' ./laradock/workspace/Dockerfile > ./laradock/workspace/Dockerfile.txt && mv ./laradock/workspace/Dockerfile.txt ./laradock/workspace/Dockerfile
> ```

Also the above command can be used in your project's root dir, just copy paste it.

**Comment by PanovAlexey** [comment]
> Open laradock/workspace/dockerfile and add `libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libxml2 libzstd1` before apt-utils so it looks like this ![image](https://user-images.githubusercontent.com/23278167/142674727-aa214beb-1c3d-41ef-8d9e-ff4f440c6d7c.png)

That is fix the problem for me too (Ubuntu 21). 
Thank you!

**Comment by simonbuehler** [comment]
fixes win 10 also, nice catch!
