### ISSUE TITLE
=> ERROR [ 13/106] RUN set -eux; 

### ISSUE THREAD

**Issue by koumuking** [laradock/laradock#3104]
### Description:
=> ERROR [ 13/106] RUN set -eux;       if [ "2" = "1" ] || [ "2" = "2" ]; then           composer self-update --2;       else           compose  0.3s
------
.... ......

executor failed running [/bin/sh -c set -eux;       if [ "$COMPOSER_VERSION" = "1" ] || [ "$COMPOSER_VERSION" = "2" ]; then           composer self-update --${COMPOSER_VERSION};       else           composer self-update ${COMPOSER_VERSION};       fi]: exit code: 255
ERROR: Service 'workspace' failed to build : Build failed

**Comment by CodeBlastr** [comment]
This is a duplicate of #3103, and is just another person experiencing the same issue.
