### ISSUE TITLE
How increase MEM USAGE for workspace, php fpm or nginx, mysql?

### ISSUE THREAD

**Issue by at-locbm** [LaraDock/laradock#311]
How increase MEM USAGE to 4GB or more to workspace, php fpm or nginx? because i want to runing migration data with many record.
Or which check `cgroup_enable=memory swapaccount=1` already enable to swap memory?
My containers stats:
```json
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O               BLOCK I/O             PIDS
a314b37c1b96        0.00%               4.863 MiB / 7.711 GiB   0.06%               14.28 kB / 648 B      0 B / 0 B             5
d2e5056d169d        0.00%               9.203 MiB / 7.711 GiB   0.12%               14.88 kB / 648 B      0 B / 0 B             3
9bd61b55610d        0.00%               392 KiB / 7.711 GiB     0.00%               24.74 kB / 5.519 kB   0 B / 0 B             1
0a545b379783        0.00%               4.855 MiB / 7.711 GiB   0.06%               15.9 kB / 648 B       0 B / 0 B             5
9cb3c254a0a4        0.00%               9.195 MiB / 7.711 GiB   0.12%               16.66 kB / 648 B      0 B / 0 B             3
e4f1752897ad        0.00%               388 KiB / 7.711 GiB     0.00%               17.5 kB / 648 B       0 B / 0 B             1
b719f881ce6e        0.07%               202.3 MiB / 7.711 GiB   2.56%               506.6 kB / 317.2 kB   106.5 kB / 13.52 MB   28
5e5fe0a31f89        0.06%               6.375 MiB / 7.711 GiB   0.08%               17.59 kB / 648 B      53.25 kB / 0 B        3
```
Thank advance!

**Comment by francislavoie** [comment]
I'm not sure what you're asking. `MEM USAGE` is the current RAM usage of that container, and `LIMIT` is the maximum allowed for the container (based on your hardware).

**Comment by at-locbm** [comment]
@francislavoie i meant i'm trying migration data with 1000 records on laradock_mysql_1 however mysql has gone away after i run migration to create. Then i tried to stats my containers:
```json
CONTAINER                    CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O             PIDS
laradock_nginx_1             0.00%               6.891 MiB / 7.711 GiB   0.09%               22.5 kB / 648 B     2.118 MB / 0 B        5
laradock_php-fpm_1           0.00%               19.64 MiB / 7.711 GiB   0.25%               25.21 kB / 648 B    10.94 MB / 0 B        3
laradock_workspace_1         0.00%               19.42 MiB / 7.711 GiB   0.25%               28.11 kB / 648 B    19.95 MB / 0 B        1
laradock_nginx-admin_1       0.00%               7.09 MiB / 7.711 GiB    0.09%               22.04 kB / 648 B    2.331 MB / 0 B        5
laradock_php-fpm-admin_1     0.00%               18.18 MiB / 7.711 GiB   0.23%               25.21 kB / 648 B    9.417 MB / 0 B        3
laradock_workspace-admin_1   0.00%               21.48 MiB / 7.711 GiB   0.27%               27.85 kB / 648 B    22.13 MB / 0 B        1
laradock_mysql_1             0.03%               227.1 MiB / 7.711 GiB   2.88%               28.69 kB / 648 B    39.18 MB / 12.67 MB   27
laradock_redis_1             0.06%               10.63 MiB / 7.711 GiB   0.13%               28.2 kB / 648 B     4.522 MB / 0 B        3
```  
i saw MEM USAGE not increase while migration data. I think we are easy increase memory for RAM of machine on Windows or Mac however i dont know how to increase memory on Linux OR the machine already auto swap memory on Linux.
Please help, thanks!

**Comment by francislavoie** [comment]
Your question isn't clear. That memory usage looks normal for MySQL. I'm not sure why you want to increase memory usage, that doesn't make much sense. MySQL just uses what it needs to use. This doesn't seem like a docker related question and more a MySQL question, so maybe you should try there?

**Comment by at-locbm** [comment]
@francislavoie 
hm...i want increase memory usage to save many records (like more than 1000 records). When i insert record to table, i always get message "Mysql has gone away" or wait more times to insert. I saw MEM USAGE always show less than 300Mb while i'm inserting record. Could you help me resolve or recommend the way to fix this issue?

**Comment by francislavoie** [comment]
I've never seen a "Mysql has gone away" message in my life. I really don't know what you're talking about. Is this really a performance issue? This doesn't really sound problematic. You're not explaining it very well.

**Comment by francislavoie** [comment]
Alright, I think this is what you need: http://stackoverflow.com/questions/35036547/mysql-server-has-gone-away-error-during-installing-migration-laravel

**Comment by philtrep** [comment]
@at-locbm has your issue been fixed?

**Comment by Mahmoudz** [comment]
let's close this for now.
