### ISSUE TITLE
Failed to fetch Redis repositry

### ISSUE THREAD

**Issue by vsko-dev** [laradock/laradock#3129]
### Description:
Step 101/305 : RUN if [ ${INSTALL_PHPREDIS} = true ]; then apt-get install -yqq php${LARADOCK_PHP_VERSION}-redis ;fi
---> Running in dd163787da37
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php7.4-redis_5.3.4+4.3.0-5+ubuntu20.04.1+deb.sury.org+3_amd64.deb 404 Not Found [IP: 91.189.95.85 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then apt-get install -yqq php${LARADOCK_PHP_VERSION}-redis ;fi' returned a non-zero code: 100
ERROR: Service 'workspace' failed to build : Build failed
make: *** [Makefile:59: run] Ошибка 1

### Expected Behavior:
On http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/ no more exist
php7.4-redis_5.3.4+4.3.0-5+ubuntu20.04.1+deb.sury.org+3_amd64.deb 

New version of file
php7.4-redis_5.3.5+4.3.0-5+ubuntu20.04.1+deb.sury.org+10_amd64.deb	2022-01-17 17:35	150K	

Please fix here /var/www/laradock/workspace/Dockerfile:527

###########################################################################
# PHP REDIS EXTENSION
###########################################################################

ARG INSTALL_PHPREDIS=false

RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    apt-get update && \
    apt-get install -yqq php${LARADOCK_PHP_VERSION}-redis \
;fi

### Context information:

**Output of `git rev-parse HEAD`**

```
---------
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by pikoroco** [comment]
I have the same issue too.

**Comment by pikoroco** [comment]
> I have the same issue too.

Update:
1. I fetch and merge my forked repo then I pull my local laradock git. 
2. Atfer that running fine I rebuild laradock containers with --no-cache tag. 

Now work fine laradock and no got that error like before.

I hope help you.

**Comment by ixhuman** [comment]
I have the same issue too.

**Comment by xuewlcn** [comment]
I have the same issue too.

**Comment by nice-yu** [comment]
I have the same issue too.
`http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php7.4-redis_5.3.6+4.3.0-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb  404  Not Found`
