### ISSUE TITLE
PHP-FPM Build fails on latest version

### ISSUE THREAD

**Issue by TheRealSpiderman** [laradock/laradock#3135]
### Description:

Tried to upgrade my php version from 7.4 to 8.1 but keep getting the error php-fpm failed to build. 
I have tried this with a fresh clone of laradock, however the same issue still persists.

### Expected Behavior:
Build to complete successfully.

### Context information:

**Terminal output**

```
Building php-fpm
[+] Building 94.6s (7/82)                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 44.27kB                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/laradock/php-fpm:latest-8.1                                                                                                                   2.2s
 => [ 1/78] FROM docker.io/laradock/php-fpm:latest-8.1@sha256:d745e7c6440ab29e6fec58f76afd464f4f762e63b1da6a38b4be80ef46123a01                                                           0.0s
 => [internal] load build context                                                                                                                                                        0.0s
 => => transferring context: 5.30kB                                                                                                                                                      0.0s
 => CACHED [ 2/78] RUN if [ false = true ]; then     sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.tuna.ts  0.0s
 => ERROR [ 3/78] RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       gnupg2       git       libzip-dev zip  92.2s
------                                                                                                                                                                                        
 > [ 3/78] RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       gnupg2       git       libzip-dev zip unzip &&       if [ 8.1 = "7.3" ] || [ 8.1 = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then         docker-php-ext-configure zip;       else         docker-php-ext-configure zip --with-libzip;       fi &&       docker-php-ext-install zip &&       php -m | grep -q 'zip':                                                                                                            
#6 0.216 + apt-get update -yqq
#6 31.28 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to deb.debian.org:80 (199.232.174.132), connection timed out
#6 31.28 W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Could not connect to security.debian.org:80 (151.101.66.132), connection timed out Could not connect to security.debian.org:80 (151.101.130.132), connection timed out Could not connect to security.debian.org:80 (151.101.194.132), connection timed out Could not connect to security.debian.org:80 (151.101.2.132), connection timed out
#6 31.28 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:80:
#6 31.28 W: Some index files failed to download. They have been ignored, or old ones used instead.
#6 31.28 + pecl channel-update pecl.php.net
#6 31.31 Updating channel "pecl.php.net"
#6 91.71 Channel "pecl.php.net" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: Connection timed out
#6 91.71 Trying channel "pecl.php.net" over https:// instead
#6 92.18 Channel "pecl.php.net" is up to date
#6 92.18 + apt-get install -yqq apt-utils gnupg2 git libzip-dev zip unzip
#6 92.20 E: Package 'apt-utils' has no installation candidate
#6 92.20 E: Package 'gnupg2' has no installation candidate
#6 92.20 E: Package 'git' has no installation candidate
#6 92.20 E: Unable to locate package libzip-dev
#6 92.20 E: Unable to locate package zip
#6 92.20 E: Unable to locate package unzip
------
executor failed running [/bin/sh -c set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     apt-get install -yqq       apt-utils       gnupg2       git       libzip-dev zip unzip &&       if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then         docker-php-ext-configure zip;       else         docker-php-ext-configure zip --with-libzip;       fi &&       docker-php-ext-install zip &&       php -m | grep -q 'zip']: exit code: 100
ERROR: Service 'php-fpm' failed to build : Build failed

```

**Output of `docker version`**

```
Docker version 20.10.11, build dea9396
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Macbook Pro: OS 12.0.1
```

### Steps to reproduce the issue:

1. Clone laradock
2. `cp .env.example .env`
3. Set `PHP_VERSION` of .env to 8.1
4. Run command `docker-compose build php-fpm`

Any ideas whats causing this?

**Comment by davidjr82** [comment]
Same here with a fresh installation in Windows with PHP 8.0.

@TheRealSpiderman laradock don't support PHP 8.1 at this moment, right?

**Comment by TheRealSpiderman** [comment]
> Same here with a fresh installation in Windows with PHP 8.0.
> 
> @TheRealSpiderman laradock don't support PHP 8.1 at this moment, right?

It should according to [the laradock/php-fpm](https://github.com/laradock/php-fpm)

**Comment by xrezut** [comment]
You mention you are on Mac OS. If you have iCloud private relay turned on, be sure to turn it off when rebuilding the image. Issue has been reported here, https://github.com/docker/for-mac/issues/6027, and seems to be related to apples private relay feature.

**Comment by davidjr82** [comment]
> You mention you are on Mac OS. If you have iCloud private relay turned on, be sure to turn it off when rebuilding the image. Issue has been reported here, [docker/for-mac#6027](https://github.com/docker/for-mac/issues/6027), and seems to be related to apples private relay feature.

Should not be related to SO environment, because it also happens in Windows.

If in any old running project you run `docker-compose buid php-fpm --no-cache` throws the same error.

**Comment by TheRealSpiderman** [comment]
> You mention you are on Mac OS. If you have iCloud private relay turned on, be sure to turn it off when rebuilding the image. Issue has been reported here, [docker/for-mac#6027](https://github.com/docker/for-mac/issues/6027), and seems to be related to apples private relay feature.

Thanks this has fixed it for me.

**Comment by EvilTwin01** [comment]
same issue here, is anyone able to build it?

**Comment by r0lodex** [comment]
I'm able to build by updating `WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115` in `.env`

**Comment by dipenchand** [comment]
I spent my whole days trying with PHP version 8.0.
But, when I change **PHP Version to 8.1** in **.env** file like below:
```
# Accepted values: 8.0 - 7.4 - 7.3 - 7.2 - 7.1 - 7.0 - 5.6
PHP_VERSION=8.1
```
Its working
```
 docker-compose ps                                                                                                                 ─╯
NAME                          COMMAND                  SERVICE             STATUS              PORTS
laradock-docker-in-docker-1   "dockerd-entrypoint.…"   docker-in-docker    running             2375-2376/tcp
laradock-mariadb-1            "docker-entrypoint.s…"   mariadb             running             0.0.0.0:3306->3306/tcp
laradock-nginx-1              "/docker-entrypoint.…"   nginx               running             0.0.0.0:80-81->80-81/tcp, 0.0.0.0:443->443/tcp
laradock-php-fpm-1            "docker-php-entrypoi…"   php-fpm             running             0.0.0.0:9003->9003/tcp
laradock-phpmyadmin-1         "/docker-entrypoint.…"   phpmyadmin          running             0.0.0.0:8081->80/tcp
laradock-workspace-1          "/sbin/my_init"          workspace           running             0.0.0.0:2222->22/tcp, 0.0.0.0:3000-3001->3000-3001/tcp, 0.0.0.0:4200->4200/tcp, 0.0.0.0:8001->8000/tcp, 0.0.0.0:8080->8080/tcp
```

**Comment by r0lodex** [comment]
> I spent my whole days trying with PHP version 8.0. But, when I change **PHP Version to 8.1** in **.env** file like below:
> 
> ```
> # Accepted values: 8.0 - 7.4 - 7.3 - 7.2 - 7.1 - 7.0 - 5.6
> PHP_VERSION=8.1
> ```
> 
> Its working
> 
> ```
>  docker-compose ps                                                                                                                 ─╯
> NAME                          COMMAND                  SERVICE             STATUS              PORTS
> laradock-docker-in-docker-1   "dockerd-entrypoint.…"   docker-in-docker    running             2375-2376/tcp
> laradock-mariadb-1            "docker-entrypoint.s…"   mariadb             running             0.0.0.0:3306->3306/tcp
> laradock-nginx-1              "/docker-entrypoint.…"   nginx               running             0.0.0.0:80-81->80-81/tcp, 0.0.0.0:443->443/tcp
> laradock-php-fpm-1            "docker-php-entrypoi…"   php-fpm             running             0.0.0.0:9003->9003/tcp
> laradock-phpmyadmin-1         "/docker-entrypoint.…"   phpmyadmin          running             0.0.0.0:8081->80/tcp
> laradock-workspace-1          "/sbin/my_init"          workspace           running             0.0.0.0:2222->22/tcp, 0.0.0.0:3000-3001->3000-3001/tcp, 0.0.0.0:4200->4200/tcp, 0.0.0.0:8001->8000/tcp, 0.0.0.0:8080->8080/tcp
> ```

Perhaps that's why latest image of `WORKSPACE_BASE_IMAGE_TAG_PREFIX` won't work with 8.0?

**Comment by lutzklai** [comment]
I ran into a similar issue building the workspace container for php `8.0` on the latest tag. I believe it was breaking on a pecl command.

Changing tag to `WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115` worked for me.

**Comment by tancou** [comment]
You can upvote this PR which fixes workspace base image build https://github.com/laradock/workspace/pull/53

**Comment by Silassiai** [comment]
> I'm able to build by updating `WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115` in `.env`
> 
> See last comment in #2781

this one worked for me! (upgrading from php 8.0 to 8.1)
