### ISSUE TITLE
Feature Request : Add CertBot (SSL AutoRenewal ) and ngx_pagespeed  in Nginx

### ISSUE THREAD

**Issue by g0ld3lux** [LaraDock/laradock#316]
I hope we can be able to auto renew SSL certificate with Cerbot and Optimize GOOGLE PAGESPEED with ngx_pagespeed module for nginx...

This way we can have our focus more on code and not on optimizing the app...

**Comment by philtrep** [comment]
This issue should be split into two seperate issues:

* Cerbot for generating SSL
* ngx_pagespeed for NGINX
