### ISSUE TITLE
Xdebug wrong ini when using php 7.4/3

### ISSUE THREAD

**Issue by bolivir** [laradock/laradock#3169]
### Description:
In https://github.com/laradock/laradock/commit/780d0bb764017554f95404d679c7edbf13261cef, the version of xdebug gets determined based on the PHP version.

But the part that sets the ini values only checks for PHP 8, and then uses the new ini settings. This should be the same check as for the xdebug version.

https://github.com/laradock/laradock/blob/df4ccf5eb7857d459e2b1d15c17ac07655d030bf/php-fpm/Dockerfile#L238 
`RUN if [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \`

### Expected Behavior:
When using a version that installs xdebug 3, use the new config values also.

**Comment by cyberbit** [comment]
I also encountered this problem. I pulled the modified file from a newer PHP version and got the following working as a baseline:

```ini
; NOTE: The actual debug.so extention is NOT SET HERE but rather (/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini)

xdebug.client_host="host.docker.internal"
xdebug.discover_client_host=false
xdebug.client_port=9003
xdebug.idekey=PHPSTORM

xdebug.start_with_request=yes
xdebug.mode=debug
xdebug.cli_color=1
; xdebug.profiler_enable=0
xdebug.output_dir="~/xdebug/phpstorm/tmp/profiling"

xdebug.remote_handler=dbgp
; xdebug.remote_mode=req

xdebug.var_display_max_children=-1
xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1
```

**Comment by albsierra** [comment]
Have you tried applying the suggested solution in #3099 ?
