### ISSUE TITLE
 Host '172.18.0.1' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by Tang1024** [LaraDock/laradock#317]
I can't connect to the mysql service.

**Comment by Tang1024** [comment]
I didn't change anything of mysql. I just changed one thing '- INSTALL_MEMCACHED=true'. After I run the command "docker-compose up -d apache2 mysql memcached",there was no user 'homestead' in the user table.How can I make it works?

**Comment by barnabas-szekeres** [comment]
Same issue here.

**Comment by barnabas-szekeres** [comment]
This caused by wrong mysql scheme, so you should remove /var/lib/mysql files on your host machine. This directory mapped to mysql container and create these filles.

@Tang1024 can you confirm?

**Comment by Tang1024** [comment]
There is no such dir /var/lib/mysql on my host machine. @barnabas-szekeres

**Comment by philtrep** [comment]
@Tang1024  I think @barnabas-szekeres meamt `data/mysql` in the LaraDock folder.

**Comment by Tang1024** [comment]
I rebuilt the mysql container and the problem had been fixed.
