### ISSUE TITLE
can not run laradock postgres

### ISSUE THREAD

**Issue by pndx** [laradock/laradock#3178]
### Context information:

**Output of `git rev-parse HEAD`**

```
df4ccf5eb7857d459e2b1d15c17ac07655d030bf
```

**Output of `docker version`**

```
Docker version 20.10.12, build e91ed57
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
MacOS Monterey 12.2.1
```

### Steps to reproduce the issue:

1.Run laradock_postgres in docker desktop and it won't start

### Stacktrace & Additional info:

The log data in doker desktop as below.
```
PostgreSQL Database directory appears to contain a database; Skipping initialization


2022-03-19 01:43:09.191 UTC [1] FATAL:  database files are incompatible with server

2022-03-19 01:43:09.191 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.2.
```

**Comment by bobbyshaw** [comment]
Hi @pndx This is because the default version of Postgres is now 14 and your install was previously using version 13. 

>   The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.2.

You might choose to downgrade the version but updating your `.env` file with the line:

```
POSTGRES_VERSION=13
```

Alternatively you would need to go through the upgrade process. I'm not familiar with how to do that myself.

**Comment by pndx** [comment]
@bobbyshaw Thanks for reply. i will try it.
