### ISSUE TITLE
timezone in workspace

### ISSUE THREAD

**Issue by partenit** [LaraDock/laradock#318]
My local time GMT+3, but in workspace container is UTC.

Maybe this can be solution?
Mount volume in workspace to sinc date with host:
        volumes:
            - /etc/localtime:/etc/localtime

**Comment by Mahmoudz** [comment]
@partenit seems nice solution. would you like to submit a PR with that?

**Comment by appleboy** [comment]
@partenit @Mahmoudz 

I think the better way was to change the `Application Timezone` setting in `config/app.php` not to overwrite `/etc/localtime` file on workspace container.

**Comment by Mahmoudz** [comment]
@partenit could you confirm that @appleboy solution works fine with you!

**Comment by partenit** [comment]
> I think the better way was to change the Application Timezone setting in config/app.php not to overwrite /etc/localtime file on workspace container.
@appleboy thank you, my idea not about application timezone settings - i'm already use them.
for example, i may run cron tasks in workspace container and i want correct time settings for this.

**Comment by partenit** [comment]
> seems nice solution. would you like to submit a PR with that?
i try this tomorow, thank you!

**Comment by appleboy** [comment]
> @appleboy thank you, my idea not about application timezone settings - i'm already use them.
for example, i may run cron tasks in workspace container and i want correct time settings for this.

If you want to run cron tasks in workspace container. I think you can edit docker-compose config by yourself not add  `/etc/localtime:/etc/localtime` setting in `laradock` project.

**Comment by philtrep** [comment]
@Mahmoudz since we have crons available now I'm that thinking @appleboy 's fix is worth being the default config. What do you think?

**Comment by Mahmoudz** [comment]
@philtrep I agree with you on @appleboy's solution.

**Comment by philtrep** [comment]
@appleboy @Mahmoudz  After digging a bit, the /etc/localtime mount is not a suitable option since it won't work on all host. Please take a look at #354 and tell me if you find it acceptable.
