### ISSUE TITLE
Bind for 0.0.0.0:443 failed: port is already allocated

### ISSUE THREAD

**Issue by ChitaGideon** [laradock/laradock#319]
run `docker-compose up -d nginx`
I got this problem .

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint 3a0d42a192a1_laradock_nginx_1 (b233457704c54acc5a4b2c50e99858a0e2cf0fb290d03effa5976369fa60c264): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

according to #251 I don`t use skype.

```
Docker version 1.12.0, build 8eab29e
docker-compose version 1.8.0, build f3628c7
```

**Comment by sc0Vu** [comment]
Hi
I met this problem before.
Finally, I found there is another docker container use port 443.
Maybe there is other application use port 443.

**Comment by ChitaGideon** [comment]
Hi @sc0Vu ,thanks for your help.
`docker ps ` show there is no other container running.
I try `lsof -i TCP:443`

```
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 422 chita   28u  IPv4 0x7c85bacf055be923      0t0  TCP *:https (LISTEN)
```

Then I don`t figure out how to find the app that use 443.

**Comment by Stubbs** [comment]
I have this issue too, but port 22, not 443.

@ChitaGideon Looking at your output form lsof, it looks like you have another docker process running, the `com.docker` command, not necaserily another container, but something docker related.

To find out what, try this: `ps axu | grep 422` (where 422 is the number in the PID column).

**Comment by Stubbs** [comment]
In my case it was because I'd enabled SSH on the host.

**Comment by mwwhitted** [comment]
I think I have the same issue, but port 80...

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (74f42259b85dfde5b6c133935b80bcce30eab2396bc48d2ae42def3f6258f64e): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

docker-compose ps
          Name                        Command              State           Ports
---------------------------------------------------------------------------------------
laradock_mysql_1            docker-entrypoint.sh mysqld   Up         3306/tcp
laradock_nginx_1            nginx                         Exit 128
laradock_php-fpm_1          php-fpm                       Up         9000/tcp
laradock_volumes_data_1     /true                         Exit 0
laradock_volumes_source_1   /true                         Exit 0
laradock_workspace_1        /sbin/my_init                 Up         0.0.0.0:22->22/tcp

**Comment by michaeljhopkins** [comment]
I had this issue. My environment (host) is OSX with a full laravel dev setup previously installed on my host.

Running `valet stop` fixed it

**Comment by zhenqidong** [comment]
Found this is quite old, not sure if it has ever been resolved, I have the same issue today though.
Docker version 1.12.6, build 88a4867/1.12.6
no indication that 443 is used by anything else in the output of netstat and lsof  
no container at all
# docker ps -a
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
  
errors after trying to run a container:
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint phs (67436f1d349b4dde3bf71b176b405e3bb80430e201955f92edf9abaad9155e57): Bind for 0.0.0.0:443 failed: port is already allocated.
Error response from daemon: Container 89877291b5198048164d9e34762e565e6c0a5cffd3dd1f5e449271d5b136e277 is not running

**Comment by Kuzirashi** [comment]
I have the same issue.

**Comment by Minemega19** [comment]
+1

**Comment by hutber** [comment]
+2

**Comment by mickutz** [comment]
Same issue in port 443 over here.

I actually had a container running that I'd killed at some point but never removed and popped back up after a reboot.

**Comment by Kevinlearynet** [comment]
This isn't an issue or bug with laradock, it just means that you're already running an instance of nginx on your machine and Docker isn't able to spin up a new one because the existing nginx is already consuming ports 443 and/or 80. Try this to stop the existing one:

`sudo nginx -s stop`

Then try again.

**Comment by gellowg** [comment]
For anyone still looking for a solution, just make sure you have binded your port the right way round in your docker-compose.yml

It goes:
`- <EXTERNAL SERVER PORT>:<INTERNAL CONTAINER PORT>`
