### ISSUE TITLE
Token missmatch exception [Session issue]

### ISSUE THREAD

**Issue by devfelipereis** [laradock/laradock#321]
I just created the issue(#320) about a nginx module. Now I have disabled the feature that uses that module to test laradock in my app. 

I can access my app but when I try to login or try to use any form, I got a "Token missmatch exception".
In production my app is working fine and in my last local env it was too.

All that I found in forums, etc, don't work. This is happening with me in all containers that I'm trying to use :/

Any ideias? Thank you!

EDIT 1:

I know that is a session issue cause I can disable csrf middleware and try to login. I put a wrong password   and I should see an alert that render errors from session. Nothing is shown.

EDIT 2:

I've created this issue on stack: http://stackoverflow.com/questions/39619526/laravel-tokenmismatchexception
There you can have more details.

I decide to install my development env in my host machine and it's working. It's the same version that I'm trying to use with laradock. It's weird Oo Same server block and same project folder. 

I will try to change laradock files for php fpm to install like I did in my host and see if it works. Maybe at night I'll try to do this and post here my results.

**Comment by philtrep** [comment]
@devfelipereis can you give us an update on this?

**Comment by Gdewilde** [comment]
I'm having the same difficulties with the csrf token. The token is being created and passed into the form but it still gives a token missmatch exception. The csrf_token issue is related to laradock because I tested it on homestead and it didn't threw the error.
