### ISSUE TITLE
invalid characters for a local volume

### ISSUE THREAD

**Issue by anoopsrma** [laradock/laradock#3211]
Error response from daemon: create ~/.laradock/data/mysql: "~/.laradock/data/mysql" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

while using docker compse 2.5.0

**Comment by nhiembv** [comment]
I have same issue

**Comment by KierynAnnette** [comment]
same

**Comment by anoopsrma** [comment]
downgrading to 2.4.0 works for me

**Comment by helderlj** [comment]
Same here

**Comment by helderlj** [comment]
Downgrading docker-compose to 2.4.0 also worked for me.

**Comment by grasebit** [comment]
DockerDesktop > Preferences > General > Use Docker Compose V2 
OFF the check box.

**Comment by trd-warren** [comment]
The same issue, after upgrading Docker Desktop 4.8.1

**Comment by trd-warren** [comment]
> DockerDesktop > Preferences > General > Use Docker Compose V2
> OFF the check box.

Works for me.

**Comment by amorZhu** [comment]
The naming restrictions of docker composer V2 are problematic!

**Comment by da-mask** [comment]
@grasebit 's suggestion didn't work for me, but I was able to get back to work by running `docker-compose up .....` instead of  `docker compose up ....`. Hope that helps somebody until someone better at docker than me can sort this out.

**Comment by wrpota** [comment]
> DockerDesktop > Preferences > General > Use Docker Compose V2 OFF the check box.

Don't work for me  :(

**Comment by weidmaster** [comment]
@grasebit solution works for me too in the new Docker Desktop

**Comment by tmtung144** [comment]
Is this the problem of new docker version or our problem, will the following versions of docker compose be fixed?

**Comment by huynhquocbao92** [comment]
> DockerDesktop > Preferences > General > Use Docker Compose V2 OFF the check box.

Thanks, it works for me.

**Comment by grasebit** [comment]
In my case,

DockerDesktop 4.5.0 + Use Docker Compose V2 OFF  it work.
DockerDesktop 4.5.0 + Use Docker Compose V2 ON it work.
DockerDesktop 4.8.1 + Use Docker Compose V2 OFF it work.
DockerDesktop 4.8.1 + Use Docker Compose V2 ON it not work.

**Comment by dangtinh97** [comment]
> The naming restrictions of docker composer V2 are problematic!

it worked

**Comment by HsuMsix** [comment]
Downgrade docker to ver. 4.7.1 worked for me.

**Comment by dlgombert** [comment]
Can confirm that downgrading Docker Desktop to ver 4.7.1 fixed it for me. 

Turning off use compose v2 setting didn't work, I'm assuming, because some of the dockerfiles baked into laradock explicitly set COMPOSE version to 2.  

Downgrading docker-compose by itself isn't really practical for most Windows users, but it should be technically possible  provided you  could find version 2.4.1 of docker-compose.exe.  On windows 10 replacing the  docker-compose binary in `C:\Program Files\Docker\cli-plugins` with the 2.4.1 version should work.   

Thanks @HsuMsix for suggesting this approach

**Comment by rmsite** [comment]
> Can confirm that downgrading Docker Desktop to ver 4.7.1 fixed it for me. Thanks @HsuMsix and @glebovdev for suggesting this approach.
> 
> Turning off use compose v2 setting didn't work, I'm assuming, because some of the dockerfiles baked into laradock explicitly set COMPOSE version to 2.
> 
> Downgrading docker-compose by itself isn't really practical for most Windows users, but it should be technically possible provided you could find version 2.4.1 of docker-compose.exe. On windows 10 replacing the docker-compose binary in `C:\Program Files\Docker\cli-plugins` with the 2.4.1 version should work.

Desn't work for me.

**Comment by mosinve** [comment]
As another solution it works for me this way for latest docker version
```dockerfile
#path to root of my laradock project 
ROOT_PATH=/Users/foo/bar

# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=${ROOT_PATH}/backend

CONTAINERS_PATH_HOST=${ROOT_PATH}/docker

# Choose storage path on your machine. For all storage systems
DATA_PATH_HOST=${CONTAINERS_PATH_HOST}/.laradock/data
```

**Comment by CleisonPaiva** [comment]
> DockerDesktop > Preferences > General > Use Docker Compose V2 OFF the check box.

that worked, thanks

**Comment by kiksy** [comment]
I had this issue with exisiting containers with names such as

`d15877a2e0a1_d15877a2e0a1_d15877a2e0a1_d15877a2e0a1_d15877a2e0a1_laradock_docker-in-docker_1`

Using `docker rename` on them solved the issue. 

eg.

`docker rename d15877a2e0a1_d15877a2e0a1_d15877a2e0a1_d15877a2e0a1_d15877a2e0a1_laradock_docker-in-docker_1 laradock_docker-in-docker_1 `

**Comment by grasebit** [comment]
fixed in Docker Desktop 4.8.2

**Comment by trd-warren** [comment]
> fixed in Docker Desktop 4.8.2

Fixed after upgrading. 👍

**Comment by dszhxb** [comment]
> Reference in

Fixed, thanks！

**Comment by dlgombert** [comment]
is this happening for anyone on 4.8.2 or later?  Or can this be closed?

**Comment by grasebit** [comment]
worked v4.9.1
I think it's okay to close it.
