### ISSUE TITLE
Error Phpmyadmin login

### ISSUE THREAD

**Issue by MultiArtsTuts** [laradock/laradock#3212]
### Description:
I just cloned the repository and ran docker-composer up -d and created the containers without errors, but when I enter phpmyadmin it displays the error:
 ```mysqli::real_connect(): (HY000/2002): No such file or directory ```

### Context information:

**Output of `git rev-parse HEAD`**

```
a2dd97674f76e114717e9ff1e98f3912d053c96d
```

**Output of `docker version`**

```
20.10.12
```

**Output of `docker-compose version`**

```
2.4.1
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Ubuntu 22.04
```

**Comment by Geovanek** [comment]
Same error here.

**Comment by arifaslaan** [comment]
Hi, I find a solution.

My system is **Ubuntu 18.04**.

In laradock folder;

First run this code:

`sudo docker-compose exec phpmyadmin bash`

And then your command line show like this, so you in phpmyadmin container:

_root@e5c4df1945ea:/var/www/html#_

**Maybe you must download nano editor in phpmyadmin container.**
For this firstly run in container:

`apt-get update`
`apt install nano`

And then copy sample config file:

`cp config.sample.inc.php config.inc.php`

And then edit like this line:

Original: 
`$cfg['Servers'][$i]['host'] = 'localhost';`

Edited: 
`$cfg['Servers'][$i]['host'] = 'mysql';`

And it is working for  me!

**Comment by Geovanek** [comment]
> Hi, I find a solution.
> 
> My system is **Ubuntu 18.04**.
> 
> In laradock folder;
> 
> First run this code:
> 
> `sudo docker-compose exec phpmyadmin bash`
> 
> And then your command line show like this, so you in phpmyadmin container:
> 
> _root@e5c4df1945ea:/var/www/html#_
> 
> **Maybe you must download nano editor in phpmyadmin container.** For this firstly run in container:
> 
> `apt-get update` `apt install nano`
> 
> And then copy sample config file:
> 
> `cp config.sample.inc.php config.inc.php` `nano config.inc.php`
> 
> And then edit like this line:
> 
> Original: `$cfg['Servers'][$i]['host'] = 'localhost';`
> 
> Edited: `$cfg['Servers'][$i]['host'] = 'mysql';`
> 
> And it is working for me!

Nice, this work for me too!!!!

**Comment by arifaslaan** [comment]
> > Hi, I find a solution.
> > My system is **Ubuntu 18.04**.
> > In laradock folder;
> > First run this code:
> > `sudo docker-compose exec phpmyadmin bash`
> > And then your command line show like this, so you in phpmyadmin container:
> > _root@e5c4df1945ea:/var/www/html#_
> > **Maybe you must download nano editor in phpmyadmin container.** For this firstly run in container:
> > `apt-get update` `apt install nano`
> > And then copy sample config file:
> > `cp config.sample.inc.php config.inc.php` `nano config.inc.php`
> > And then edit like this line:
> > Original: `$cfg['Servers'][$i]['host'] = 'localhost';`
> > Edited: `$cfg['Servers'][$i]['host'] = 'mysql';`
> > And it is working for me!
> 
> Nice, this work for me too!!!!

I gave five hours to solve this problem :D

**Comment by MultiArtsTuts** [comment]
> Hi, I find a solution.
> 
> My system is **Ubuntu 18.04**.
> 
> In laradock folder;
> 
> First run this code:
> 
> `sudo docker-compose exec phpmyadmin bash`
> 
> And then your command line show like this, so you in phpmyadmin container:
> 
> _root@e5c4df1945ea:/var/www/html#_
> 
> **Maybe you must download nano editor in phpmyadmin container.** For this firstly run in container:
> 
> `apt-get update` `apt install nano`
> 
> And then copy sample config file:
> 
> `cp config.sample.inc.php config.inc.php` `nano config.inc.php`
> 
> And then edit like this line:
> 
> Original: `$cfg['Servers'][$i]['host'] = 'localhost';`
> 
> Edited: `$cfg['Servers'][$i]['host'] = 'mysql';`
> 
> And it is working for me!

Nice, this work for me too!!!!
