### ISSUE TITLE
Latest docker update requires absolute path

### ISSUE THREAD

**Issue by robertwt7** [laradock/laradock#3214]
### Description:

```
Error response from daemon: create ./postgres/docker-entrypoint-initdb.d: "./postgres/docker-entrypoint-initdb.d" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

After the latest docker update in windows, I have to use absolute path and change some of my env file, is this expected? is anyone experiencing this issue?

so now only this part works `/home/myuser/laradock/postgres/docker-entrypoint-initdb.d`

**Output of `docker version`**

```
Docker version 20.10.14, build a224086
```

**Output of `docker-compose version`**

```
Docker Compose version v2.5.0
```

**System info: Mac, Windows or Linux. Include which disto/version**
Ubuntu 20 in WSL

**Comment by Christopher-Law** [comment]
I am facing the same issue.

**Comment by myusufid** [comment]
I have same the problem
