### ISSUE TITLE
env and docker-compose.yml

### ISSUE THREAD

**Issue by amorZhu** [laradock/laradock#3215]
I've been using laradock for a long time, but I don't understand how the configuration in env affects docker-comopse.yml.
How env and docker-compose.yml interact.

**Comment by duchymor** [comment]
Read this https://docs.docker.com/compose/environment-variables/

**Comment by amorZhu** [comment]
> You can set default values for environment variables using a [.env file](https://docs.docker.com/compose/env-file/), which Compose automatically looks for in project directory (parent folder of your Compose file). Values set in the shell environment override those set in the .env file.

**Comment by amorZhu** [comment]
@duchymor Think you!
