### ISSUE TITLE
Question about backups

### ISSUE THREAD

**Issue by partenit** [LaraDock/laradock#322]
I have a question about backups.

Year ago I start to use one solid custom LAMP image. It was wrong way in point of docker view.
Today we have laradock and I already use it in production with fun - big thanks to creators. I think LaraDock - the best way for docker+php simbiosis. 

But in LAMP image no problem with backup setup, for example for mysql data dump. 

In laradock we have no access to "mysqldump" command in workspace container and my laravel sheduled backup tasks not working now. 

Yes, I try doing some of that on host:
`docker-compose exec mysql mysqldump ... `

But in my case this commands working properly with manual starting, not as a crontab task. 

How others solve same problems? Working example of crontab config for backup mysql data in laradock?
What to do:
- more experiments with crontab and /dev/null 2>&1 ?
- further linking containers? (for run mysqldump in workspace)
- start separate cron in mysql container?
- somewhat else? 

Thank you for support.

**Comment by philtrep** [comment]
I added a PR for Cronjob. You could mount a volume for workspace at `/opt/backups` then have the cronjob do a `mysqldump`.

**Comment by philtrep** [comment]
@partenit Does #340 resolve your issue?

**Comment by partenit** [comment]
@philtrep Thank you very much. This solve my issue :)
