### ISSUE TITLE
Issue with ext-mail

### ISSUE THREAD

**Issue by edweld** [laradock/laradock#3227]
https://github.com/laradock/laradock/blob/6092304046e476545c6374569424e641ec55f05b/workspace/Dockerfile#L1468

ext-mailparse is version specific, this should be  `apt-get install -yqq php${LARADOCK_PHP_VERSION}-mailparse \`

**Comment by dant89** [comment]
+1 on this issue, breaks php 7.4 workspace build as it tries to install php-mailparse for php 8.1
