### ISSUE TITLE
./xdebugPhpFpm start/stop

### ISSUE THREAD

**Issue by dennisc1** [LaraDock/laradock#323]
I'm not able in getting the ./xdebugPhpFpm start/stop script to work on my windows machine. If I'm correct it's a bash script, so I cannot execute it trough a regular windows command. With windows 10 there is an option however to use Bash on Ubuntu on Windows. Trough this bash console I can execute the script, however the script is not able to execute docker-compose because it is a windows command.

So I'm stuck between two options. Trough windows console I can't execute the bash script and trough the bash console I can't execute the windows command.

Am I doing something wrong?

**Comment by LarryEitel** [comment]
Noticed that this question was asked and answered [here](https://github.com/LarryEitel/laravel-laradock-phpstorm/issues/6).
