### ISSUE TITLE
Login timeout expired when trying to connect to mssql

### ISSUE THREAD

**Issue by michalakis** [laradock/laradock#3232]
### Description:
Trying to use mssql, but when trying to connect to the database, I get 
[ERROR] Connection failed: SQLSTATE[HYT00]: [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired

### Expected Behavior:
Run migrations on the database

### Context information:

I clone laradoc in my project (octobercms), edit the .env file to enable mssql php-fpm extention and select php v8.1, run ```docker-compose up -d nginx mssql```, use workspace terminal to run october installation, but when it tries to connect to database, it times out

**Output of `docker version`**

```
Client: Docker Engine - Community
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:39 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
Docker Compose version v2.6.0
```

**System info: Mac, Windows or Linux. Include which disto/version**

Windows 10

### Steps to reproduce the issue:

1. clone laradock in project
2. edit .env to include php v8.1 and enable php mssql extention
3. run docker-compose up -d nginx mssql
4. open worskspace terminal
5. run php artisan october:install

I also tried installing mssql on my system and manually creating a database instead of running a container through laradoc, but get the same issue

sorry to post this here, I cant find any information online, I'm not even sure this is a bug or something I am doing wrong

**Comment by nickolasvitor** [comment]
Did you solved this problem?
