### ISSUE TITLE
Change application directory via script

### ISSUE THREAD

**Issue by lukasoppermann** [LaraDock/laradock#324]
Hey,

so I deploy my app via capistrano for now, this means I get a new folder, that is symlinked to current for every deploy.

So I would need to link the volume that laradock uses to my current folder. However I do not have laradock within this folder. Is this setup possible? And if so, how?

**Comment by lukasoppermann** [comment]
Hey @Mahmoudz is this possible yet?

**Comment by Mahmoudz** [comment]
@lukasoppermann sorry for the delayed response, was too busy last week..

Yes you can do this, it has to point to your Laravel app wherever it is.
