### ISSUE TITLE
docker compose build fails

### ISSUE THREAD

**Issue by bingalls** [laradock/laradock#3246]
### Description:
Docs seem to indicate that I should use the command line, but are unclear on which one.
Running `docker compose build` returns error messages, also implying that Laradock is unusable.
Related to
* #2539
* #3165
I also have a VPN & Application Firewall, but I do not see any relevant errors reported.

### Expected Behavior:
I expect a clear indication that `docker compose up` will succeed.
Docs should clarify whether I should use cmd, powershell (as admin?). I believe Docker Desktop also has a console.

### Context information:

**Output of `git rev-parse HEAD`**

```
a4c79b5d8e7db92a8d069da7babb329ce45d5412
```

**Output of `docker version`**

```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 11 pro
```

### Steps to reproduce the issue:

1. [Install](https://chocolatey.org/) Docker Desktop, Docker CLI, Docker Compose & Unison. Docs are unclear about required packages.
2. Install WSL2 with Alpine Linux. Again, Docs are unclear here. 
3. Docs make no mention of [Hardware Virtualization](https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1) I'm assuming that it is not important.
4. Configure settings in Docker Desktop to use Docker Compose 2.0. (also missing from Docs) These steps require reboots. I assume that registering an account is also not required.
5. Follow https://laradock.io/getting-started/#A2 _Don’t have a PHP project yet:_ (This also fails for an existing project)
6. Continue with https://laradock.io/getting-started/#Usage I don't think I have Docker Toolbox;  again, docs are unclear on how to tell.
7. Edit .env (from .env.example) This step is unclear on how to disable services; I made my best guess.
8. Docs say to run `docker-compose up` ; it seems that the problem is in `docker compose build` and makes no difference, whether I run CMD as myself, or PowerShell as Administrator.

### Stacktrace & Additional info:

```
 docker-compose up
Creating network "laradock_frontend" with driver "bridge"
ERROR: failed to update bridge store for object type *bridge.networkConfiguration: open /var/lib/docker/network/files/local-kv.db: read-only file system
```

**Comment by brucehot** [comment]
Since I already run VirtualBox, it will kill Windows 11 performance, to turn on Hyper-V in Windows. I do have the UEFI hypervisor enabled. This requires me to run the old Docker Toolbox:
https://poweruser.blog/docker-on-windows-10-without-hyper-v-a529897ed1cc

**Comment by bingalls** [comment]
As of Virtualbox 7.0, Virtualbox cannot be run on Hyper-V at all. Worse, Windows 11's Settings display seems to not accurately show the status of Hyper-V. I've had to disable Hyper-V on the command line to ensure such.

**Comment by bingalls** [comment]
Since I already run VirtualBox, it will kill Windows 11 performance, to turn on Hyper-V in Windows. I do have the UEFI hypervisor enabled. This requires me to run the old Docker Toolbox:
https://poweruser.blog/docker-on-windows-10-without-hyper-v-a529897ed1cc
