### ISSUE TITLE
PHP Startup: Invalid library

### ISSUE THREAD

**Issue by marttosc** [LaraDock/laradock#325]
I'm using PHP 5.6 and I get the following error from php-fpm log:

`NOTICE: PHP message: PHP Warning:  PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=opcache.so from php.ini) in Unknown on line 0`

I tried to set all the arguments to true and rebuild the image, but the error continues.

How can I fix this?

**Comment by philtrep** [comment]
@marttosc Have you tried the `zend_extension=opcache.so from php.ini` suggestion?

**Comment by marttosc** [comment]
@philtrep I have tried, but it doesn't work. I have commented the `ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/` line from Dockerfile and then it works.

**Comment by philtrep** [comment]
@marttosc glad you got it to work. I'll close this for now, we'll reopen if we see this is a recurring issue.

**Comment by eodin** [comment]
There is `docker-php-ext-install opcache` used.
According to https://github.com/docker-library/php/blob/master/docker-php-ext-install it runs docker-php-ext-enable

https://github.com/docker-library/php/blob/master/docker-php-ext-enable make a decision 
```
	if nm -g "$module" | grep -q ' zend_extension_entry$'; then
		line="zend_extension=$(readlink -f "$module")"
	else
		line="extension=$module"
	fi
```
in my environment it said
```
$  nm -g "/usr/lib/php/20151012/opcache.so"
nm: /usr/lib/php/20151012/opcache.so: no symbols
```

**Comment by aconital** [comment]
I'm getting the same error. I tried commenting out `ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/
` but didn't work

**Comment by abdinegoro** [comment]
change to 7.2 version..works for me
