### ISSUE TITLE
With PHP version 8.1, phpredis version does not install

### ISSUE THREAD

**Issue by laidbackwebsage** [laradock/laradock#3255]
### Description:
I am writing a bash script to automate the initial setup of a new Laravel project using Laradock.

The script sets `PHP_VERSION` to '8.1' in Laradock's `.env`. (Full list of `.env` changes below.)

When the script runs `docker-compose up --detach --build --force-recreate apache2 mysql redis`, the build of the `workspace` container fails with the following error:

```
=> ERROR [new-app-name-api_workspace  39/109] RUN if [ true = true ]; then     apt-get install -yqq php8.1-redis ;fi                                                                                                            1.7s
------
 > [new-app-name-api_workspace  39/109] RUN if [ true = true ]; then     apt-get install -yqq php8.1-redis ;fi:
#67 1.550 E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-redis/php8.1-redis_5.3.6+4.3.0-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb  404  Not Found [IP: 185.125.190.52 80]
#67 1.550 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then     apt-get install -yqq php${LARADOCK_PHP_VERSION}-redis ;fi]: exit code: 100
```
I checked the repository, and there are no (longer) any packages for `php8.1-redis_5.3.6`; there are only `php8.1-redis_5.3.7` packages.

### Expected Behavior:
Install `phpredis` in the `workspace` container.

### Context information:

**Output of `git rev-parse HEAD`**

```
d1b42c75ed72080923c659bb23fcc5cbd9b8c5ed
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:00:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
Docker Compose version v2.0.1
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
OS: Kubuntu 22.04.1 LTS x86_64 
Kernel: 5.15.0-43-generic 
Shell: bash 5.1.16 
DE: Plasma 5.24.4 
```

### Steps to reproduce the issue:

1. In Laradock `.env` file, set `PHP_VERSION` to '8.1'
2. Run `docker-compose up --detach --build --force-recreate apache2 mysql redis`

### Stacktrace & Additional info:

Laradock `.env` file (changes only):
```
APP_CODE_PATH_HOST=../../src
DATA_PATH_HOST=../storage
COMPOSE_PROJECT_NAME=new-app-name-api
PHP_VERSION=8.1
PHP_IDE_CONFIG=serverName=new-app-name-api
WORKSPACE_INSTALL_YARN=false
WORKSPACE_INSTALL_NPM_GULP=false
WORKSPACE_INSTALL_NPM_VUE_CLI=false
MYSQL_DATABASE=new-app-namedb
MYSQL_USER=new-app-namedbadmin
MYSQL_PASSWORD=<new password>
MYSQL_ROOT_PASSWORD=<new password>
REDIS_PASSWORD=<new password>
```
Laradock `docker-compose.yml` (changes only):

MySQL: Changed bind mount (`- ${DATA_PATH_HOST}/mysql:/var/lib/mysql`) to volume (`mysql:/var/lib/mysql`)
Redis: Changed bind mount (`${DATA_PATH_HOST}/redis:/data`) to volume (`redis:/data`)

**Comment by laidbackwebsage** [comment]
WORK-AROUND:

Setting `PHP_VERSION` to '8.0' allows the `phpredis` extension to install correctly.

**Comment by dairidong** [comment]
open `workspace/Dockerfile`,  search `PHP REDIS EXTENSION`, add `apt-get update` : 
```
###########################################################################
# PHP REDIS EXTENSION
###########################################################################

ARG INSTALL_PHPREDIS=false

RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    # add here
    apt-get update && \
    apt-get install -yqq php${LARADOCK_PHP_VERSION}-redis \
;fi
```

**Comment by erikn69** [comment]
https://github.com/laradock/laradock/issues/1315#issuecomment-808711311
> `try docker-compose build --no-cache --pull php-fpm`
