### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by digitalit** [LaraDock/laradock#327]
# IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)

What exactly does that mean? 

I get cant connect to server.

if i use 127.0.0.1:8080 i get phpmyadmin and even 127.0.0.1 gets me to phpmyadmin, why cant i get the laravel on 127.0.0.1 ?

**Comment by LarryEitel** [comment]
You want the IP of your Docker Container.

**Comment by digitalit** [comment]
which one? i ran 
`/sbin/ip route|awk '/default/ { print $3 }' `
inside nginx and got 172.18.0.1 and typed "dockerhost:172.18.0.1" in both workspave and php-fpm container.

Still didn't work

**Comment by LarryEitel** [comment]
Are you trying to view laravel running in your browser? Dockerhost is only needed for xdebug would be running in workspace to 'talk' to PHPStorm on port 9000.

**Comment by digitalit** [comment]
Ok, and yes im just trying to see Laravel in my browser.

no problem with phpmyadmin on port 8080 but cant connect to server on port 80

**Comment by LarryEitel** [comment]
Do you see php-fpm running? If so, you should be able to browse to the IP of the Docker container and see Laravel. If not, what specifically is the error message?

**Comment by cassiohalmeida** [comment]
I can't view laravel in the browser too.

I did : 
`docker-compose up -d nginx mysql`

Then, type 'docker ps' : 

```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
813af2523d70        laradock_nginx       "nginx"                  26 hours ago        Up 30 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   laradock_nginx_1
31b9f5fd1d4c        laradock_php-fpm     "php-fpm"                26 hours ago        Up 30 minutes       9000/tcp                                   laradock_php-fpm_1
adfa7afb5cdb        laradock_workspace   "/sbin/my_init"          26 hours ago        Up 30 minutes       0.0.0.0:22->22/tcp                         laradock_workspace_1
7f1ec22d2fc7        laradock_mysql       "docker-entrypoint.sh"   26 hours ago        Up 30 minutes       0.0.0.0:3306->3306/tcp                     laradock_mysql_1
```

When I try to acces localhost, nothing happens ( i tried with container IP too ) and i get "localhost is currently unable to handle this request." in the browser.

I dont know what to do. Maybe add some config in my hosts file? Maybe the bind IP is wrong?
If someone could help me, i appreciate :dancer:

**Comment by philtrep** [comment]
@cassiohalmeida 

A few things:

- try rebuilding the containers `docker-compose up --build --force-recreate -d  nginx mysql`
- try to curl from the `workspace` container, you should be getting your index page as html
- look at `access.log in `laradock/logs/nginx`, you should be seeing your request
