### ISSUE TITLE
laravel-horizon doesn't call artisan horizon

### ISSUE THREAD

**Issue by GlauberF** [laradock/laradock#3277]
### Description:
I can't find the problem why the file in supervisor(laravel-horizon) doesn't call php artisan horizon.
if I just call it this way, `php /var/www/api/laravel/artisan horizon` works perfectly.
but not from the configuration file.
![Captura de Tela_selecionar área_20220927185419](https://user-images.githubusercontent.com/11314585/192643035-f44e8c76-0fda-443a-8041-f982457f438d.png)

I have some logs that I checked here
command `docker-compose logs laravel-horizon`
![Captura de Tela_selecionar área_20220927185624](https://user-images.githubusercontent.com/11314585/192643451-3432e21d-ff53-4041-91fa-02acdd85cd9a.png)

**Comment by theia-kevin** [comment]
@GlauberF Have you managed to solve this?
