### ISSUE TITLE
Rebuilding Mysql & removing data saved to volumes_data

### ISSUE THREAD

**Issue by iannazzi** [LaraDock/laradock#329]
Hi Everyone! I am building a custom Mysql database startup script... It will take me several builds to get the starting point correct. 

Creating the mysql container is no problem. However, when modifying the startup script my data does not change. I seem stuck with the original data.

I tried the following without sucess....
`docker-compose down`
`docker-compose build --no-cache mysql`

I then went in and manually deleted the data in the  volumes_data folder ./data/mysql

This has caused more issues.

How do I re-create or re-initialize the mysql data in volumes_data?

**Comment by appleboy** [comment]
Try the following steps.

```bash
$ mkdir ./data/mysql
$ docker-compose run -d mysql phpmyadmin
# on workspace container.
$ php artisan migrate
```

**Comment by iannazzi** [comment]
I found that removing the entire data folder, removing the containers, modifying the sql script, then rebuilding worked for me. To summarize, to rebuild with fresh data:
`docker-compose down`
Delete ./data
Modify sql
`docker-compose up -d nginx mysql`
