### ISSUE TITLE
Where does the container naming happen?

### ISSUE THREAD

**Issue by wyattbiker** [laradock/laradock#3294]
Hello, as no one responds on Gitter, I thought I would ask a question here.

I have a container that I startup with `docker-compose up -d mysql`.

The resulting container name is **laradock-mysql-1**

I am trying to figure out where is the definition (or script) on how a container name is created. 

Thanks

**Comment by da-mask** [comment]
Have you set the `COMPOSE_PROJECT_NAME=laradock` to something else in the .env file?

**Comment by wyattbiker** [comment]
I can change that, but was wondering how the number one shows up at the end. E.g. **laradock-mysql-1**

**Comment by da-mask** [comment]
Well, I don't know nor do I care. I don't know why you'd want to know, but someone else might be able to help, but not me.

**Comment by wyattbiker** [comment]
its for dockerfile dev purposes. thanks

**Comment by ahkui** [comment]
that number is docker compose scale feature, you can override it with `container_name`

Note: if you have more question with sequence number you can move to ask docker compose community, have a nice day

**Comment by wyattbiker** [comment]
thanks for the clarification.
