### ISSUE TITLE
Can't reach Laravel

### ISSUE THREAD

**Issue by Henriquedrdc** [LaraDock/laradock#33]
I'm not being able to reach my laravel, what could be the reason?
Where should I run "php artisan" commands?
When I run it with "docker-compose up -d" , does it get the mysql configuration (username and password) from my .env file?﻿

**Comment by Mahmoudz** [comment]
Can you try to clone LaraDock again, few minutes ago I made a huge updates, they might fix your problems.

However the `artisan commands` should be running on your machine for now. There's no container having laravel installed in it, however SOON I will create a container that will have laravel, composer, git, gulp.. and all the other development tools.
