### ISSUE TITLE
Setup for Single Project, same image name

### ISSUE THREAD

**Issue by zishiguo** [laradock/laradock#3300]
### Description:

* project-a
*   laradock-a
* project-b
*   laradock-b

build in laradock-a
```
docker-compose build php-fpm
```
build in laradock-b
```
docker-compose build php-fpm
```
image name are both `laradock_php-fpm`
### Expected Behavior:
laradock-a_php-fpm
laradock-b_php-fpm
### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
{paste here}
```

**Output of `docker-compose version`**

```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.13.1 (90346)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Mac
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by the-paulus** [comment]
In order for laradock to create different containers and images for each project you have to set the `COMPOSE_PROJECT_NAME` variable in the .env file.

**Comment by zhushaolong** [comment]
look https://laradock.io/getting-started/
