### ISSUE TITLE
Service 'workspace' failed to build : Build failed

### ISSUE THREAD

**Issue by mirendeweixiao** [laradock/laradock#3302]
![image](https://user-images.githubusercontent.com/68169749/203709866-edc78c90-0c6c-45ef-a561-c23251c14147.png)

![image](https://user-images.githubusercontent.com/68169749/203709998-af264a8c-7693-4637-8ef9-4b1340d214ed.png)

**Comment by bestlong** [comment]
try `docker compose --no-cache --pull build workspace`
