### ISSUE TITLE
MySQL port (3306) exposed by default

### ISSUE THREAD

**Issue by philtrep** [LaraDock/laradock#332]
According to https://github.com/docker/compose/issues/2260, we cannot yet override the ports options in docker-compose, could we remove the database ports by default so the `docker-compose.yml` is viable for production?

If you'd really need host access to the database you could just add a `docker-compose.override.yml` with the port mapping.

**Comment by Mahmoudz** [comment]
It's possible but not sure if would be easy for the current users, to adapt that!

**Comment by philtrep** [comment]
@Mahmoudz

From what I gather we could change the `ports` to `expose` without requiring most users to adapt. The proper way to execute any command is from the `workspace` anyhow.

Maybe it's just me but the default behavior should be restrictive rather than permissive, especially when it comes to database access.
