### ISSUE TITLE
Service 'clickhouse' failed to build : Build failed 

### ISSUE THREAD

**Issue by xhong1024** [laradock/laradock#3341]
### Description:
E: Version '22.2.2.1' for 'clickhouse-common-static' was not found
22.2.2.1 is the default Clickhouse version in .env, and I tried to change to other version,still show me this error.Any help would be appreciated

**System info: Mac, Windows or Linux. Include which disto/version**

```
M1 Mac
```

![image](https://user-images.githubusercontent.com/21967955/210949542-e4c32367-6400-4cc3-9674-e9035926c3c9.png)

**Comment by xiaoguo0426** [comment]
same error

M1 Mac
