### ISSUE TITLE
Error Building Nginx

### ISSUE THREAD

**Issue by ygarasab** [laradock/laradock#3350]
### Description:
Hello, my coworker is having a problem building his project from master, nginx won't build

### Context information:

**Output of `git rev-parse HEAD`**

```
6c8cb6dd85eb1fcad6f7dce3e9d6c6a29c6e3ed8
```

**Output of `docker version`**

```
20.10.22
```

**Output of `docker-compose version`**

```
Docker Compose version v2.15.1
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows/Wsl2 -  linux/amd64
```

### Steps to reproduce the issue:

1. Checkout laradock's master
2. Copy .env.example to .env
3. Change some basic stuff like db credentials and project name
4. Run `docker-compose up -d nginx postgres redis`

### Stacktrace & Additional info:

```
[project-nginx  4/11] RUN apk update     && apk upgrade     && apk --update add logrotate     && apk add --no-cache openssl     && apk add --no-cache bash:
#0 14.82 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
#0 20.74 ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.17/main: temporary error (try again later)
#0 20.74 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
#0 20.74 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: No such file or directory
#0 94.61 v3.17.1-175-g19cab0fa64 [https://dl-cdn.alpinelinux.org/alpine/v3.17/community]
#0 94.61 1 errors; 12886 distinct packages available
------
failed to solve: executor failed running [/bin/sh -c apk update     && apk upgrade     && apk --update add logrotate     && apk add --no-cache openssl     && apk add --no-cache bash]: exit code: 1
```

Btw, this is inside another repo as a submodule

**Comment by afsh7n** [comment]
Changing the php version from 7.4 to 8.1 in the env file solves the problem.
