### ISSUE TITLE
docker compose build fails 

### ISSUE THREAD

**Issue by yasinedr** [laradock/laradock#3351]
### Description:

when I'm trying to execute docker-compose build --no-cache workspace it stucks at composer self-update --2
Storing "stable" as default update channel for the next self-update run.
Upgrading to version 2.5.2 (2.x channel).
   
In CurlDownloader.php line 365:
                                                                               
  curl error 28 while downloading https://getcomposer.org/download/2.5.2/comp  
  oser.phar: Operation timed out after 300036 milliseconds with 580966 bytes   
  received                                                                     

even if I have the latest version of composer installed 
### Expected Behavior:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/34688076/217399086-e06d3eb5-1c5a-426a-a4b0-33d2a741a1d4.png">

### Context information:

**Output of `git rev-parse HEAD`**

```
6c8cb6dd85eb1fcad6f7dce3e9d6c6a29c6e3ed8
```

**Output of `docker version`**

```
Docker version 20.10.12, build 20.10.12-0ubuntu4
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
windows 11 wsl2 ubuntu20
```

### Steps to reproduce the issue:

1. [Install](https://chocolatey.org/) Docker Desktop, Docker CLI, Docker Compose & Unison. Docs are unclear about required packages.
2. Install WSL2 with ubuntu Docker , docker-compose ....
3. Follow https://laradock.io/getting-started/#A2 This also fails for an existing project
4. Run docker-compose build --no-cache workspace

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by parallels999** [comment]
Feel free to make a PR to fix that, thanks
