### ISSUE TITLE
wsl2 windows problems

### ISSUE THREAD

**Issue by developcreativo** [laradock/laradock#3356]
### Description:
When connecting to the workspace container, this process takes about 5 or more minutes connected but after a while, it presents a reconnection problem, any suggestions to avoid these problems.

![image](https://user-images.githubusercontent.com/5873347/220727849-4e8cc505-49b6-45dc-b04a-03e7922debc5.png)

Versión de WSL: 1.0.3.0
Versión de kernel: 5.15.79.1
Versión de WSLg: 1.0.47
Versión de MSRDC: 1.2.3575
Versión de Direct3D: 1.606.4
Versión DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versión de Windows: 10.0.22621.1265

Docker version 20.10.17, build 100c701

**Comment by da-mask** [comment]
Are you sure you are on WSL2 ? Your message shows `Versión de WSL: 1.0.3.0`

Also, why are you trying to connect vscode to the docker container? Its best to work with vscode connected to your WSL, and in the terminal you can ssh into the container with a command like: 
`docker compose exec -u=laradock -w=/var/www/project workspace zsh"
