### ISSUE TITLE
a bug for "CHANGE_SOURCE=true"

### ISSUE THREAD

**Issue by crisslin** [laradock/laradock#3363]
https://github.com/laradock/laradock/blob/6c8cb6dd85eb1fcad6f7dce3e9d6c6a29c6e3ed8/workspace/Dockerfile#L36
Two more lines of code need to be added here
`sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list; \ `
`sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list; \ `
After increasing, the image source can be accelerated.

**Comment by seek-x2y** [comment]
One more line of code need to be added ?
`touch /etc/apt/sources.list  &&  \`
for the exception 
```bash
------                                                                                                                                                                                                                                                                        
 > [ 2/80] RUN if [ true = true ]; then     sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list ;fi:
#0 0.250 sed: can't read /etc/apt/sources.list: No such file or directory
------

```
