### ISSUE TITLE
Refresh files

### ISSUE THREAD

**Issue by lukasoppermann** [LaraDock/laradock#337]
Hey @Mahmoudz,

I am running laradock with caddy to use https. However, I have a problem, that when I update files on the server (the actual files not inside docker), the files within the docker directory are not updated. 

This means even if I just change a css file I need to `docker-compose down`, `docker-compose up -d`, `composer install` and run `chmod -R 777 storage && chmod -R 777 bootstrap/cache`.

Is there no better way of doing this?

I am deploying using capistrano, this means a new file is created `releases/12345435` and is symlinked to `current`. Does this pose a problem? After re-running the above mentioned commands it is picked up fine from `current`.

**Comment by philtrep** [comment]
@lukasoppermann 

Try `docker-compose up --force-recreate -d`

**Comment by lukasoppermann** [comment]
@philtrep doesn't this doe the same? As in remove everything and recreate it? I would like to just update the files.

**Comment by philtrep** [comment]
@lukasoppermann by reading your question again I think I get what you are trying to do. The problems lies in the symlink. When VOLUME loads, it copies the path the symlink points to so if you change the link location, VOLUME still points to the initial directory!

I think the easiest solution would be to create a volume for all the releases:
```
# docker-compose.overwrite.yml
[...]
volumes_source:
        image: tianon/true
        volumes:
            - <host path to releases>/releases/:/var/www/releases
```
When you've ran the container you'll want to remove the Laravel directory:
```
rm -rf /var/www/laravel/
```
Then create a symlink from _within_ the workspace:
```
ln -s /var/www/releases/12345435 /var/www/laravel
```
When you have a new release just do:
```
rm /var/www/laravel
ln -s /var/www/releases/<newrelease> /var/www/laravel
```

That should do it!

**Comment by lukasoppermann** [comment]
@philtrep Thank you for your advise. I will try it out as soon as I get a chance. This sounds pretty sensible. Since capistrano automatically symlinks the latest release to current I can probably just make docker look into the current folder instead of `/var/www/laravel` and as long as it is all on a volume it should work as well.

However are are you sure the `volume` will refetch a new release from `<host path to releases>/releases/:/var/www/releases`? I mean, if I add a release to `<host path to releases>/releases/` will it be reflected on `/var/www/releases`? 

And would I have to run this on the docker volumen?

```
# on volume or on the file system?
rm /var/www/laravel
ln -s /var/www/releases/<newrelease> /var/www/laravel
```

**Comment by philtrep** [comment]
@lukasopperman

Yes, VOLUME mounts a directory in the host file system, you should see the `current` folder being modified from within the container after the mount has taken place.

From the `workspace` container. However, if you are always going to be pointing to the same folder you shouldn't have to run the last command. That being said I haven't tested it out so I could be wrong.

**Comment by philtrep** [comment]
@lukasoppermann Did my fix resolve your issue?

**Comment by Mahmoudz** [comment]
If the problem still exist feel free to open this issue again :)

**Comment by lukasoppermann** [comment]
Hey @Mahmoudz thanks. I got it solved now, thanks to @philtrep help. However for anyone trying the same, make sure to manually clean the `opcache` if it is activated.

Capistrano creates a symlink and `opcache` does not update the cache if changes happen through a symlink, so you need to clear the cache in an `execute` command. I recommend using https://github.com/gordalina/cachetool for this.

You also probably need to create a new symlink as capistrano creates an absolute symlink which points to the file on the server, NOT in the volume. However you can create a "relative" symlink in another execute command.

```php
execute "cd #{fetch(:deploy_to)} && ln -sfn ./releases/#{fetch(:release_timestamp)} ./latest"
```

**Comment by MilanUnjiya4149** [comment]
Open the composer.json file and Find this package under require : "spatie/laravel-responsecache".If you see it, remove it. and update composer using composer update command.

php artisan composer update
php artisan config:cache
