### ISSUE TITLE
docker-compose up -d nginx 构建nvm失败

### ISSUE THREAD

**Issue by xioayangge** [laradock/laradock#3377]
![image](https://user-images.githubusercontent.com/43867289/233267879-56350859-88ea-40bc-965b-617ae73ae2a1.png)
![image](https://user-images.githubusercontent.com/43867289/233267919-fb760da7-c2bd-495e-8c0a-18819e024aba.png)

**Comment by xioayangge** [comment]
![image](https://user-images.githubusercontent.com/43867289/233268251-dc8f1546-0eaa-4120-a3c1-ca91fd73cac3.png)

**Comment by xiaoguo0426** [comment]
#3347 参考下
