### ISSUE TITLE
No privileges to create databases

### ISSUE THREAD

**Issue by HeadStudios** [laradock/laradock#3385]
### Description:

I just went into phpmyadmin in Laradock to create a new database and it is saying:
No privileges to create databases No privileges to create databases
https://share.getcloudapp.com/Z4unRDdm

### Expected Behavior:

Would imagine as admin I can create as many databases as I like?

### Context information:

**Output of `git rev-parse HEAD`**

```
6c8cb6dd85eb1fcad6f7dce3e9d6c6a29c6e3ed8
```

**Output of `docker version`**

```
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:20:34 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.9.0 (80466)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:14:19 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
MacOS Big Sur
```

### Steps to reproduce the issue:
Just  and 

1. login to mysql / default / secret credentials in phpMyAdmin
2. try to create DB

### Stacktrace & Additional info:

```
Video for context:
https://share.getcloudapp.com/yAuJNQ8A
```

**Comment by HeadStudios** [comment]
Video for context: https://share.getcloudapp.com/yAuJNQ8A

**Comment by bestlong** [comment]
https://stackoverflow.com/questions/38504257/mysql-scripts-in-docker-entrypoint-initdb-are-not-executed

**Comment by HeadStudios** [comment]
Thank you!
