### ISSUE TITLE
removal of php5.6 build flows

### ISSUE THREAD

**Issue by makowskid** [laradock/laradock#3409]
Can we finally remove those outdated GitHub Actions build workflows?
- CI / build-php (5.6, php-fpm)
- CI / build-php (5.6, php-worker)

**Comment by makowskid** [comment]
Hi guys, I want to start the discussion of removing all dependencies (and build workflows) for unsupported PHP versions:
https://www.php.net/supported-versions.php
I believe we shall remove everything that depends on PHP lower than 8.0
Thoughts?

@mahmoudz
@appleboy
@philtrep
@mikeerickson
@zeroc0d3
@thorerik
@winfried-van-loon
@sixlive
@bestlong
@urukalo
@vwchu
@zuohuadong
@lanphan
@ahkui

**Comment by makowskid** [comment]
Thoughts? guys?

**Comment by zuohuadong** [comment]
I support keeping 7.x or even 7.4.x and dropping 5.x

**Comment by makowskid** [comment]
5.x for sure, but do we want to keep 7.x?

**Comment by zuohuadong** [comment]
7.4.x should be retained

**Comment by appleboy** [comment]
remove 5.x and keep 7.x version.

**Comment by makowskid** [comment]
@Mahmoudz
@appleboy
@philtrep
@mikeerickson
@zeroc0d3
@thorerik
@winfried-van-loon
@sixlive
@bestlong
@urukalo
@vwchu
@zuohuadong
@lanphan
@ahkui

Thoughts guys? Can we vote on it? Or can we simply start removing 5.x dependencies?

**Comment by winfried-van-loon** [comment]
I would limit to PHP's official Supported Versions and remove older versions:
https://www.php.net/supported-versions.php

**Comment by makowskid** [comment]
> I would limit to PHP's official Supported Versions and remove older versions: https://www.php.net/supported-versions.php

Would you drop everything < 8.1 ?
