### ISSUE TITLE
Laravel 10 npm install error

### ISSUE THREAD

**Issue by jeromevillaver** [laradock/laradock#3411]
Is crating new version of Laravel 10 is not compatible in laradock?

Cannot proceed because npm install is not completeed

```
npm install
```

**Docker version 24.0.2, build cb74dfc**

```
laradock@a67457351398:/var/www/bam-gaming$ npm install
npm ERR! code 1
npm ERR! path /var/www/bam-gaming/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:internal/errors:496
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! <ref *1> Error: spawnSync /var/www/bam-gaming/node_modules/esbuild/bin/esbuild ETXTBSY
npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
npm ERR!     at spawnSync (node:child_process:871:24)
npm ERR!     at Object.execFileSync (node:child_process:914:15)
npm ERR!     at validateBinaryVersion (/var/www/bam-gaming/node_modules/esbuild/install.js:98:28)
npm ERR!     at /var/www/bam-gaming/node_modules/esbuild/install.js:285:5 {
npm ERR!   errno: -26,
npm ERR!   code: 'ETXTBSY',
npm ERR!   syscall: 'spawnSync /var/www/bam-gaming/node_modules/esbuild/bin/esbuild',
npm ERR!   path: '/var/www/bam-gaming/node_modules/esbuild/bin/esbuild',
npm ERR!   spawnargs: [ '--version' ],
npm ERR!   error: [Circular *1],
npm ERR!   status: null,
npm ERR!   signal: null,
npm ERR!   output: null,
npm ERR!   pid: 0,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR! 
npm ERR! Node.js v20.3.1

npm ERR! A complete log of this run can be found in: /home/laradock/.npm/_logs/2023-07-07T05_48_58_433Z-debug-0.lo
```

**Comment by nightvis** [comment]
+1

**Comment by nightvis** [comment]
npm ERR! code 1
npm ERR! path /var/www/api.kulcslyukkiado.hu/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! node:internal/errors:496
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR!
npm ERR! <ref *1> Error: spawnSync /var/www/api.kulcslyukkiado.hu/node_modules/esbuild/bin/esbuild ETXTBSY
npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
npm ERR!     at spawnSync (node:child_process:871:24)
npm ERR!     at Object.execFileSync (node:child_process:914:15)
npm ERR!     at validateBinaryVersion (/var/www/api.kulcslyukkiado.hu/node_modules/esbuild/install.js:98:28)
npm ERR!     at /var/www/api.kulcslyukkiado.hu/node_modules/esbuild/install.js:285:5 {
npm ERR!   errno: -26,
npm ERR!   code: 'ETXTBSY',
npm ERR!   syscall: 'spawnSync /var/www/api.kulcslyukkiado.hu/node_modules/esbuild/bin/esbuild',
npm ERR!   path: '/var/www/api.kulcslyukkiado.hu/node_modules/esbuild/bin/esbuild',
npm ERR!   spawnargs: [ '--version' ],
npm ERR!   error: [Circular *1],
npm ERR!   status: null,
npm ERR!   signal: null,
npm ERR!   output: null,
npm ERR!   pid: 0,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR!
npm ERR! Node.js v20.3.1

**Comment by makowskid** [comment]
Closing because it's a local configuration issue
