### ISSUE TITLE
Support Abandoned for Docker Toolbox in Laradock v4? 

### ISSUE THREAD

**Issue by edmundluong** [laradock/laradock#342]
Hi,

Great work on this project, it is working well on both Debian 8 and Windows 10 in my limited testing so far.

However, I noticed that in the current documentation for Laradock it has the following section regarding Docker Toolbox, suggesting that it is no longer supported (different branch):

> **Read Before starting:**
> 
> If you are using **Docker Toolbox** (VM), do one of the following:
> - Upgrade to Docker [Native](https://www.docker.com/products/docker) for Mac/Windows (Recommended). Check out [Upgrading Laradock](#upgrading-laradock)
> - Use LaraDock v3.\* (Visit the `LaraDock-ToolBox` [Branch](https://github.com/LaraDock/laradock/tree/LaraDock-ToolBox)).
> 
> If you are using **Docker Native** (For Mac/Windows) or even for Linux, continue this documentation normally since LaraDock v4 and above is just for that.

I realize that there is now a native Docker application for Windows/Mac/Linux, but there are some restrictions to installing Docker for Windows specifically.

From the [Docker for Windows](https://docs.docker.com/engine/installation/windows/#/docker-for-windows) website, these are the necessary requirements for your Windows system to work with Docker natively:

> - 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later). In the future we will support more versions of Windows 10.
> - The Hyper-V package must be enabled. The Docker for Windows installer will enable it for you, if needed. (This requires a reboot).

As you can see, not all editions of Windows can use Docker currently. Anybody still on Windows 7/8 or using Windows 10 Home cannot use the native Docker application, leaving them no option but to use Docker Toolbox.

I have been able to successfully run the Laradock v4.7.2 containers on my Windows 10 Home system using Docker Toolbox and did not run into many problems doing so. 

I was wondering if this project has officially abandoned support for Docker Toolbox?

**Comment by Mahmoudz** [comment]
@edmundluong thanks for your interest. This project was created a long time ago! and have always been following the latest Docker updates and changes.. Yes in V4 we dropped the support the Docker Toolbox, assuming everyone is switching and following up with the latest Docker releases.. 

However, the case you showed seems very convenient, and I have no problem adding documentations support for Docker Toolbox back again. 

I won't be able to personally do it as I don't have it anymore. So if you or anyone interested please submit a PR with an updated docs. 

(Note: create new section for that docs (do not merge with the existing sections) and use links from the existing to the new one).

**Comment by g0ld3lux** [comment]
I tried installing the native but reverted back to docker- toolbox...

Since im using both homestead and docker...
and if i enable hyper-v , it will restrict me creating new images in my virtualbox...
all the remaining images i have is retained but , 
when i installed a new homestead per installation i cant...

So i defer to using the toolbox again...
i hope we can maintain the docker-toolbox branch...
im willing to help thanks

**Comment by ArtisanTinkerer** [comment]
I am also stuck on Windows 7 and want to use the latest version of Laradock, is there any reason why it wouldn't work with Docker Toolbox? Thanks.

**Comment by hlorofos** [comment]
per my understanding docker-sync wouldn't work out of the box. Actually I wasn't able to setup synchronization. .env-example telling to use `unison`, but it doesn't make a thing.

**Comment by Burnett01** [comment]
Works perfectly fine with latest Docker-Toolbox and Laradock (master).
