### ISSUE TITLE
Cannot start service nginx: stat /volume1/web/laradock/logs/nginx:

### ISSUE THREAD

**Issue by rajjejosefsson** [laradock/laradock#343]
Trying to setup a laradock on my synology nas. But get two errors, the first errors workaround is to change the port to like 8080:80, but then the second error will ask me again and again that some folders are missing. 

All happening after 
1. Get LaraDock inside your Laravel project: 
`git clone https://github.com/LaraDock/laradock.git.
`
2.Enter the laradock folder and run only these Containers: 
`docker-compose up -d nginx mysql 
`

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (7a14e7fbddae15f5f387a8d135568727c24fb8a12cf292bb5f895dd901e0308c): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

```
ERROR: for volumes_data  Cannot start service volumes_data: stat /volume1/web/laradock/data/sessions: no such file or directory

ERROR: for nginx  Cannot start service nginx: stat /volume1/web/laradock/logs/nginx: no such file or directory
ERROR: Encountered errors while bringing up the project.

```

`stat /volume1/web/laradock/data/mysql: no such file or directory
` and so on....

**Comment by philtrep** [comment]
The second error seems to be an issue with the `volumes_data` container. Try purging the container and running it manually. If this doesn't work, try adding the volumes from `volumes_data` directly to the appropriate containers.

**Comment by Mahmoudz** [comment]
@philtrep I sent you an email 2 days ago to `phil.trepanier@gmail.com` but didn't get a reply from you! have you received it (sent from `mahmoudz.me@gmail.com`)?

**Comment by philtrep** [comment]
@Mahmoudz Just got it, sent you a reply. :)
