### ISSUE TITLE
Add CertBot (SSL AutoRenewal )

### ISSUE THREAD

**Issue by philtrep** [laradock/laradock#345]
This idea comes from #316 (the original issue was split in two since the proposed features are not related).

**Comment by philtrep** [comment]
I think this should be it's own container, if someone has an idea feel free to contribute

**Comment by g0ld3lux** [comment]
In My Understanding , We Already Have nginx Container...
which is an alpine version... 

Im the One Who Sugguest to have this Feature Anyway...
I wanna help in anyway... 
Give Ideas , but , ill admit, my understanding in docker is not yet in depth..

Ive tried searching for solution ..
i found this one is building an image with certbot
https://github.com/jwanglof/docker-alpine-nginx-letsencrypt

Please Check if this is compatible with our current settings of our nginx...

ill post other solution also for pagespeed + nginx

**Comment by philtrep** [comment]
@g0ld3lux I started working on it, the image is working but I haven't found a proper way to integrate it with our webservers. I'll post a initial PR in a few, you should definitely add to it if you have any ideas.

**Comment by philtrep** [comment]
@g0ld3lux This is the initial PR #370, do contribute.
