### ISSUE TITLE
Can't open /root/.nvm/nvm.sh 

### ISSUE THREAD

**Issue by geocine** [LaraDock/laradock#347]
May you please check what is the problem?
```
Step 15 : RUN if [ ${INSTALL_NODE} = true ]; then     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.6/install.sh | bash &&         . ~/.nvm/nvm.sh &&                 source $NVM_DIR/nvm.sh &&         nvm install ${NODE_VERSION} &&         nvm use ${NODE_VERSION} &&         nvm alias ${NODE_VERSION} &&         npm install -g gulp bower vue-cli ;fi
 ---> Running in f740bc2abbb2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9321  100  9321    0     0   7428      0  0:00:01  0:00:01 --:--:--  7433
=> Downloading nvm from git to '/home/laradock/.nvm'
=> Cloning into '/home/laradock/.nvm'...
* (HEAD detached at v0.31.6)
  master

=> Appending source string to /root/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="/home/laradock/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
/bin/sh: 1: .: Can't open /root/.nvm/nvm.sh
Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_NODE} = true ]; then     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.6/install.sh | bash &&         . ~/.nvm/nvm.sh &&          source $NVM_DIR/nvm.sh &&         nvm install ${NODE_VERSION} &&         nvm use ${NODE_VERSION} &&         nvm alias ${NODE_VERSION} &&         npm install -g gulp bower vue-cli ;fi' returned a non-zero code: 2
```

**Comment by appleboy** [comment]
What is your laradock version?

I try to install workspace and enable `INSTALL_NODE` flag in laradock master branch version.

```bash
$ docker-compose build --no-cache workspace
```
It is working for me. The following is my screenshots.

<img width="1280" alt="screen shot 2016-10-09 at 9 13 11 am" src="https://cloud.githubusercontent.com/assets/21979/19216878/ae3df886-8e00-11e6-8f51-a76c3488843a.png">

**Comment by outakukou** [comment]
you need to stop workspace at first
`$ docker-compose stop`
then you try to build again once
`$ docker-compose build  workspace`

**Comment by geocine** [comment]
Hi guys thank you for all the responses. For some reason I was able to make this work by changing this line

https://github.com/LaraDock/laradock/blob/master/workspace/Dockerfile#L153

from

```bash
. ~/.nvm/nvm.sh && \
```
to 

```bash
. $NVM_DIR/nvm.sh && \
```

**Comment by philtrep** [comment]
Let's keep this open, we need a PR for @geocine 's fix

**Comment by geocine** [comment]
@philtrep can you verify if its a bug? I was thinking it was an isolated case on my machine, because I did not see any open issues.

**Comment by philtrep** [comment]
@geocine Might have jumped to gun on it although there is no downside in using your fix but if we do not then we may run into the same issue again.

**Comment by philtrep** [comment]
@geocine Thanks for the contribution :)

**Comment by rmirandadev** [comment]
I have this problem, I am using UBUNTU 18.04. Has anyone managed to solve?

**Comment by yorunegy** [comment]
I editted /etc/hosts like this. ( if you use WIN, also need to edit local hosts file. C:Windows\System32\drivers\etc\hosts)
199.232.68.133 raw.githubusercontent.com

**Comment by EdwinShaw** [comment]
> I editted /etc/hosts like this. ( if you use WIN, also need to edit local hosts file. C:Windows\System32\drivers\etc\hosts)
> 199.232.68.133 raw.githubusercontent.com

Thank you!Your method has done!

**Comment by uwang** [comment]
> I editted /etc/hosts like this. ( if you use WIN, also need to edit local hosts file. C:Windows\System32\drivers\etc\hosts)
> 199.232.68.133 raw.githubusercontent.com

good job!

**Comment by huiyonghkw** [comment]
https://learnku.com/laravel/t/40477
