### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by gabrielrbarbosa** [laradock/laradock#3479]
[PHP 8.3 Release Notes](https://www.php.net/releases/8.3/en.php)

Is there any estimate for php 8.3 support?

**Comment by parallels999** [comment]
Too soon 😄😄, the estable version just came out today
And the image is still not on docker, look
https://hub.docker.com/_/php/tags?page=1
And all PECLs and extensions should add support too

**Comment by angeljqv** [comment]
There is a PR: #3485
