### ISSUE TITLE
How to grow up php-worker container PHP Memory Limit

### ISSUE THREAD

**Issue by huiyonghkw** [laradock/laradock#3504]
### Description:

How to grow up php-worker container PHP Memory Limit

### Context information:

**Output of `git rev-parse HEAD`**

```
# docker exec php-worker-74 php -i |grep memory
memory_limit => 128M => 128M
Collecting memory statistics => No

```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           19.03.12

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
```

**Output of `docker-compose version`**

```
docker-compose version 1.26.0, build d4451659
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Linux
```

### Steps to reproduce the issue:

1.  `sed -i -e "s/^ *memory_limit.*/memory_limit = 512M/g" /usr/local/etc/php/php.ini`
2. docker compose build --no-cache php-worker
3.  docker exec php-worker-74 php -i |grep memory

### Stacktrace & Additional info:

<img width="653" alt="image" src="https://github.com/laradock/laradock/assets/1323776/6993861d-dca4-4053-959c-66843dc33f74">

**Comment by huiyonghkw** [comment]
<img width="780" alt="image" src="https://github.com/laradock/laradock/assets/1323776/7053abc7-f7f9-4bf9-95cc-e479be4fd89d">
1. copy php.ini from php-fpm folder to php-worker folder
2. add `- ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini` in docker-compose.yml php-worker location
3. docker compose -f docker-compose.yml build --no-cache php-worker
4. use the new image

**Comment by dlespinosa365** [comment]
In your laravel-worker.conf just put the php artisan command with the limit that you want 
`command=php -d memory_limit=1024M /var/www/artisan queue:work --queue=populate_exercise_data,emails,background,default --sleep=3 --tries=3
`
