### ISSUE TITLE
Can't build php-fpm and workspace if I enable xdebug

### ISSUE THREAD

**Issue by Skatox** [laradock/laradock#3513]
### Description:
 If I follow the official instructions to enable Xdebug. I cannot build php-fpm and workspace. They get hanged when downloading software from pecl. 

### Expected Behavior:
Build the images with xdebug without problems

### Context information:

**Output of `git rev-parse HEAD`** 

```
581649752536a9d63f42e481cdc1a85e1dd2bad4
```

**Output of `docker version`**

```
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
Docker Compose version v2.24.6-desktop.1
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
MacOS latest version
```

### Steps to reproduce the issue:

1. follow steps to enable xdebug
2. build php-fpm and workspace
3. both images won't pass building AST

**Comment by velibegov** [comment]
Hello! Stop listening to debug connection in Phpstrom. It help me.

**Comment by Skatox** [comment]
Thanks! it worked.
