### ISSUE TITLE
Docker on Mac is slow

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#353]
The entire development environment is slow for some reason, not sure if this is a Docker problem or something added to LaraDock that makes it that slow!! (By slow I mean the response time is slow, and the commands running in the workspace container are also slow).

We need your help to find out what's slowing it and make it fast again.

This is also mentioned in the following issues #97, #145, #149 & #307.

**Comment by geocine** [comment]
I am also experiencing some issues on Windows 10 using Docker Toolbox. I am not sure if this is directly related to this container or Docker, or Docker Toolbox per se. 
I have hosted a basic dingo api on my Windows 10 Docker Machine using the following stack:
- php-fpm php7
- nginx
- redis
- mysql

Average time for requests  to complete is 1.5 seconds. Even for basic authentication requests

I have hosted this on a non-powerful VPS and is geographically far from my region. It sits on a different continent. I am using this stack:
- php5.5
- apache2
- mysql

Average time for requests to complete is 300 ms

**Comment by elceka** [comment]
I have same trouble, not specially with Laradock but with Docker generally.
My dev environment is based on Mac OSX (10.11.6 (15G1104)). I think, speed has been degraded when i move from **Docker Toolbox** to the **Docker for Mac**.

**Comment by Mahmoudz** [comment]
Let's gather more data from all the users to try to find out where is the problem exactly!

@elceka I have the same feeling as I started experiencing this performance problems only using Docker for MAC. However, @geocine is on Windows and still using Docker Toolbox and facing the same problems! So far this tells me that there's a problem with some LaraDock containers!!

**Comment by elceka** [comment]
@Mahmoudz YOP, I understand, but truth may bee somewhere in the middle. :)

**Comment by Mahmoudz** [comment]
Everything is possible :D I'm excited about this Issue!

**Comment by robertpcontreras** [comment]
I have been having issues with Docker on mac related to performance. I think its due to this... https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/203. Laradock, and Docker in general runs perfectly for me when im running linux.

**Comment by citosid** [comment]
@Mahmoudz in this issue https://github.com/LaraDock/laradock/issues/145 Vasiliy says he fixed it by using `rsync` instead of `osxfuse`. I think that make sense if the problem is the way OS handle the mounting points. And maybe the same can be true of Windows, specially windows 10. I've been trying to make it work (via rsync), but I'm quite new at docker, so I have not succeed. Will keep trying and update this if I make it work.

**Comment by edmundluong** [comment]
I can attest that my native Docker for Linux for Xubuntu runs flawlessly and performs pretty well while my Windows 10 Home that uses Docker Toolbox is pretty slow. I think my issue is more about the virtual machine rather than the workspaces, though I thought I'd share my observations

**Comment by deleonn** [comment]
I'm experiencing some issues too on macOS Sierra and _Docker version 1.12.0-rc4, build e4a0dbc, experimental_. Every time I update something, an html file, js file, any file, the browser takes forever to reload what I updated, even when deleting the whole file, I can still access to it from the browser for a few minutes -yes, minutes!-. I'm currently using nginx+hhvm on Laravel 5.3. On the other hand, updating files with apache2+php-fpm takes no more than a few seconds, tho.

But still, my whole project takes 1 second to load with nginx+hhvm, and 7 to 9 seconds with apache2+php-fpm.

My teammates are experiencing the same issues on both linux (Ubuntu 16) and windows.

**Comment by philtrep** [comment]
@deleonn please take a look at #355

**Comment by deleonn** [comment]
@philtrep Thanks a lot, I'll try it out later

**Comment by brianvice** [comment]
Take a look at this project: https://github.com/IFSight/d4m-nfs There is a small issue with the script, but if you see the issue comments on the repo there is a simple fix for them. Using this script in conjunction with laradock decreased my api calls from ca. 10 seconds waiting to ca. 1 second waiting.

**Comment by michaeljhopkins** [comment]
as @brianvice suggested, nfs definitely speed things up. I used this project to enable nfs mounts on my Mac (technically a Hackintosh, but I'm not sure that's relevant). https://github.com/adlogix/docker-machine-nfs

The performance boost seems to be 13%. 
* Laravel/laravel from 283ms to 245ms. [Blackfire delta](https://blackfire.io/profiles/compare/e0e6d214-7c57-4970-b2cc-26a354e56294/graph)
* Personal project from 2s to 1.75s No blackfire delta because free plan only enables 1 share at a time

**Comment by dtkoval** [comment]
Laradock by itself has no reasons to work slow. In my case it depends on the default Virtualbox driver which uses to mount volumes. 

> The solution is to use [NFS](https://github.com/adlogix/docker-machine-nfs) to mount the “Users” directory.

Also there is an important difference between [Docker Toolbox & Docker for Mac](https://docs.docker.com/docker-for-mac/docker-toolbox/). Docker Toolbox uses docker-machine with Virtualbox driver to provision a virtual machine whereas Docker for Mac is native app which uses HyperKit. Likely, it's typical for Docker Toolbox with default Virtualbox mount driver.

**Comment by joaojoyce** [comment]
I also can confirm improved performance with:
https://github.com/IFSight/d4m-nfs

This was with an installation of Statamic which I'm guessing that it does some more file IO than Laravel.

**Comment by scoutman57** [comment]
What type of file system are you mounting the shares with? NFS?

**Comment by maurosbu** [comment]
Hi guys, I managed to use https://github.com/IFSight/d4m-nfs with a ruby on rails app and it works very well.
I would like to use it for a Laravel project:
1. How would you update the docker-compose.yml?
2. How woud you update the d4m-nfs-mounts.txt (d4m-nfs config file)

Many thanks.

**Comment by maurosbu** [comment]
Found the solution: https://github.com/IFSight/d4m-nfs/issues/5

In order to be able to use d4m-nfs you just need to perform the folowing steps.

Clone d4m-nfs repository (in your home directory)
```
git clone https://github.com/IFSight/d4m-nfs ~/d4m-nfs
```

Update configuration file (~/d4m-nfs/etc/d4m-nfs-mounts.txt), the following configuration let you use relative paths for volumes in docker-compose.yml
```
/Users:/Users
/Volumes:/Volumes
/private:/private
```

Check the system file /etc/exports and clean it up if required (there may be collisions if you come from Vagrant or if you already executed the d4m-nfs.sh script)

Run the d4m-nfs.sh script 
```
~/d4m-nfs/etc/d4m-nfs.sh
```

Bring your containers up through docker-compose, in my case
```
cd ~/my_cool_project/laradock
docker-compose up -d nginx mysql phpmyadmin
```


This approach let me have NFS speed benefits on both laravel (on laradock) and ruby on rails (on passenger-docker) projects.

Hope this can help!

Mauro

**Comment by michaelgracious** [comment]
@maurosbu I tried your little "how to", but i kept getting errors when docker tried to mount the volumes. 

> volumes:
            - /Users/michael/Sites:/var/www

I have 1 laradock for all my projects and modify the nginx vhost settings accordingly, it works fine when Docker shares the directories. But when i use the steps you used, i just get errors.

**Comment by maurosbu** [comment]
@michaelgracious can you please check that:
1. /tmp is the only shared folder (Docker > Preferences > File Sharing)
2. there isn't any conflict in /etc/exports (I had problems with old vagrant exports)

For volumes you can use relative path. If you cloned laradock in your home directory then in ~/laradock/docker-compose.yml you can use:

> volumes:
>     - ../Sites:/var/www

Let me know if it works.

Mauro

**Comment by michaelgracious** [comment]
@maurosbu I did only share /tmp in Docker, i tried both absolute and relative paths.

I keep getting the following:

> Starting laradock_redis_1
Starting laradock_applications_1
Starting laradock_mysql_1

>ERROR: for applications  Cannot start service applications: Mounts denied:
The path /Users/michael/Sites
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
ERROR: Encountered errors while bringing up the project.

**Comment by maurosbu** [comment]
@michaelgracious did you start the d4m-nfs.sh script?

**Comment by michaelgracious** [comment]
@maurosbu yes i did, it is running  and i can access with via "screen -r d4m". note that it's only the nginx container that keeps failing

**Comment by maurosbu** [comment]
@michaelgracious can you please post the content of /etc/exports ?

**Comment by michaelgracious** [comment]
@maurosbu 

> $ cat /etc/exports
\# d4m-nfs exports
"/Users" -alldirs -mapall=0:0 localhost
"/Volumes" -alldirs -mapall=0:0 localhost
"/private" -alldirs -mapall=0:0 localhost

**Comment by soundsgoodsofar** [comment]
Just adding a +1.  We're migrating from homestead to laradock and I'm noticing way slower response times with laradock.  Docker for Mac 1.12.3 (13776) here.  Relatively vanilla laradock config.

**Comment by maurosbu** [comment]
@soundsgoodsofar it is a Docker for Mac issue. If you want to speed things up I suggest to using d4m-nfs.

**Comment by michaelgracious** [comment]
@soundsgoodsofar let us know if it works for you right away, i couldnt get it to work on my Mac Book Air at all, using Sierra. d4m-nfs that is

**Comment by soundsgoodsofar** [comment]
Yep thanks guys, followed the steps for d4m-nfs from @maurosbu and things have sped up considerably.

Would be great if we could get this pushed up into the core D4M implementation.  I'll add it to our setup instructions, but people on our team use vagrant and other things that probably write to /etc/exports for a variety of reasons, so I'm a little hesitant to automate it.

**Comment by philtrep** [comment]
@soundsgoodsofar @michaelgracious @maurosbu could someone create a PR adding the fix to the docs? This seems like a recurring issue.

**Comment by pixelone** [comment]
Same issue here on OSX, its really slow. I tried (d4m-nfs) , but unable to get it to boot with docker.  

With d4m-nfs I keep getting 

`ERROR: for applications  Cannot start service applications: Mounts denied: r more info.  /Volumes/Development/http is not shared from OS X and is not known to Docker.` 

Does anyone have d4m-nfs working on OSX sierra ?  Other then the slowness, its great ready to fully switch over to this from homestead.

**Comment by maurosbu** [comment]
@pixelone did you follow my guide?
I'm running docker for mac + d4m-nfs on MacOS Sierra successfully.
Did you run d4m-nfs.sh before bringing containers up?
Did you check /etc/exports for conflicts (you have conflicts if you worked with vagrant + nfs before switching to docker).

Mauro

**Comment by pixelone** [comment]
@maurosbu - Yeah tried it step by step even deleted the /etc/exports to ensure it was empty. I have my development code on an external drive mounted as Development.  I think most people are just mounting the Users/ folder, so maybe something with it being on another drive.   

My exports file looks correct, the only other issue is private won't mount. I get this when I screen -r d4m

`mount.nfs: access denied by server while mounting 192.168.65.1:/private
mount: mounting 192.168.65.1:/private on /private failed: Permission denied`

Any suggestion would be great.

**Comment by soundsgoodsofar** [comment]
@maurosbu I'm also running into this issue periodically.  Seems like whenever I restart OS X or just randomly after a while of non-use.  Running d4m-nfs.sh again fixes it, but that's pretty annoying and I hesitate to call it a "solution".

> ERROR: for applications  Cannot start service applications: Mounts denied: tps://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

**Comment by lavenkin** [comment]
@michaelgracious I follow your guide but I get the error.

```
ERROR: for applications  Cannot start service applications: Mounts denied:
The path /Users/lavenkin/www
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.
```

this is my `/etc/export` content 

```
# d4m-nfs exports

"/Users" -alldirs -mapall=501:20 localhost
"/Volumes" -alldirs -mapall=501:20 localhost
"/private" -alldirs -mapall=501:20 localhost
```

and `/tmp` is the only shared folder in my docker file sharing

@michaelgracious are you solve the problem

**Comment by lavenkin** [comment]
when I rebot my mac again and run the script `~/d4m-nfs/d4m-nfs.sh` it work success, I check the mount use ` screen -r d4m` 

```
192.168.65.1:/Users/lavenkin /mnt nfs nolock,local_lock=all 0 0
192.168.65.1:/Users /Users nfs nolock,local_lock=all 0 0
192.168.65.1:/Volumes /Volumes nfs nolock,local_lock=all 0 0
192.168.65.1:/private /private nfs nolock,local_lock=all 0 0
```

I think it mount failed before I reboot the mac.

**Comment by gagarine** [comment]
I solved this issue on https://github.com/gagarine/docker-php by using http://docker-sync.io/ . It's in my opinion the best solution for mac.

**Comment by Mahmoudz** [comment]
@gagarine can you share with us a PR of your solution!?

**Comment by gagarine** [comment]
Sure, but after my post I was looking at https://github.com/IFSight/d4m-nfs/issues/7 and it seem d4m use heavy caching than make it perform better than I taught (I already tested other nfs workaround).

I will test it with laradock and see if I can do a PR. Generally, think it make no sens to continue maintaining https://github.com/gagarine/docker-php if this project can provide similar functionalities.

**Comment by Mahmoudz** [comment]
@gagarine Can't wait to close this issue.

You are welcome to join our team of Admins and maintain this project with us, since we are currently looking for a 5th Admin :)

**Comment by scoutman57** [comment]
Mahmoud,

I spoke with you when you did the Live feed with Laravel DFW. I would like
to join the admin team if you are seriously looking for a 5th.

**Comment by Mahmoudz** [comment]
Hi @scoutman57 I do remember you very well, hope you are doing good :) 

The project is growing everyday and thus we needs more maintainers.. @appleboy, @philtrep and I been maintaining this project lately. Few days ago @mikeerickson has joined us as well.

For the 5th Admin "maintainer", we decided to do the following:

<img width="584" alt="screen shot 2017-02-06 at 5 38 56 pm" src="https://cloud.githubusercontent.com/assets/1983984/22669718/f629ddc6-ec93-11e6-9dd2-73cf90c2bd11.png">

The reason I welcomed @gagarine to join us, is because he has his own docker project and he's helping to solve a major problem in Laradock. Usually people like him will always find time for open source contributions...

Anyway, there is always room for passionate developers to join us anytime, all they have to do contribute, contribute and contribute more :D and we will reach them!

@scoutman57 I will contact you in our next round of recruiting admins. Best,

**Comment by gagarine** [comment]
I need some time to get familiar with laradock, but it seem to take a similar approach to what I did. I'm switching right now a drupal 8 project to laradock to see how it works on a real project. 

I'm not sure I have time to take the responsibility of joining the admin team (thanks for asking!), I need to think about it and perhaps do a quick chat with you guys.

In any case I will gladly help with this issue.

**Comment by EugenMayer** [comment]
I developed docker-sync initially to cope with heavy load PHP projects like Drupal, which have a lot of files and read a lot during every bootstrap ( request ). Those kind of frameworks, also like Magento, tend to basically not work in any proper sense using dockertoolbox (native fusion/vbox share ), d4m ( own sync FS, slower then NFS ) or NFS. 

Running things like drush or anything else without having opcache involved should get you crazy in no time.

That said, i guess it could be a good match with laradock. Some metrics, we use docker-sync in a 
env of:

 - 25.000 files
 - 140 MB PHP code
 - multi microservices stack ( mecached/redis/nginx/FPM/percona/mongodb )

This is used on daily base in development. This should match the use-cases you have with laradock.

What i recommand:

 - use unison as a sync_strategy
 - probably either plan to use the daemon mode ( 0.2.0 ) or think about using docker-sync as a library https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync to orchestrate your own bootstrap, if you need that. 
 - Depending on your needs, you might use docker-sync (only sync, docker-compose is your duty ) or docker-sync-stack ( docker-compose integration build in https://github.com/EugenMayer/docker-sync/wiki/2.2-sync-stack-commands
- you can easily provide docker-sync as a alternative solution using portable docker-compose.yml files https://github.com/EugenMayer/docker-sync/wiki/Keep-your-docker-compose.yml-portable .. you could use docker-compose-docker-sync.yml in case someone wants to run with docker-sync. This keeps your usual docker-compose files untouched
 - consider looking at https://github.com/EugenMayer/docker-sync-boilerplate yourself and creating such a starting point for testers if needed. I guess laradock is a "boilerplate" generator by default, so having this repo is either temporary or not needed

**Comment by rickshawhobo** [comment]
If anyone is interested there is an active issue on the docker for mac github here https://github.com/docker/for-mac/issues/77

I finally got d4m-nfs to work after some hassles. The one thing I discovered is that you should not the script as root, if you happened to run it as root in the past you may need to remove the files under /tmp/d4m*

`sudo rm -rf /tmp/d4m*`

Hope that helps someone, thanks for the hard work.

**Comment by Vanuan** [comment]
Don't know about php, but for `ruby` and `node` mounting `.bundle` and `node_modules` using named volumes instead of through osxfs fixes performance. Is it `vendor` in php? Here's how:

```
php-compose:
  volumes:
    vendor:/src/vendor

php-app:
  volumes:
    .:/src
    vendor:/src/vendor

volumes:
  - vendor_dir
```

**Comment by Mahmoudz** [comment]
Some speed improvements solutions [http://laradock.io/documentation/#improve-speed-on-macos](http://laradock.io/documentation/#improve-speed-on-macos)

**Comment by MatthewDrouin** [comment]
I had problems with Laravel being slow on Docker for Mac like everyone else here. I looked at the possible solutions listed here but I also found some interesting information on https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/ and https://docs.docker.com/docker-for-mac/osxfs-caching/

My api calls were taking between 1.0 to 1.2 seconds at minimum. I decided to try the `:cache` option for the www volume and now the API calls take between .3 and .4 seconds. It isn't as fast as it is on our linux boxes but it is certainly usable for dev. Just wanted to throw it out there in case  someone else finds this thread as a quick option they can try.

I didn't use `:cache` for the mysql or mongo mounts though as I believe those systems do their own memory caching once loaded anyway so they shouldn't be hitting the hard drive much. I did try with them cached but it resulted in no increase plus I'm not 100% sure what issues it would cause anyway.

I did some testing where I made changes to the laravel/php code and instantly did the api call and the code was used so I'm pretty sure you don't have to worry too much about old code running. 

YMMV but again I wanted to share because it was a quick easy fix for me. I haven't compared it to nfs but I would have to think that since the container itself has a copy of the files that it should be just as fast but hopefully others can chime in.

**Comment by flexgrip** [comment]
@MatthewDrouin - Where exactly did you add :cache? To the docker-compose.yml?

**Comment by glaesser** [comment]
@MatthewDrouin would like to know as well.

Unfortunately docker-sync doesn't appear to make any difference in my projects. My laravel pages still take 0.8-1.5 seconds to load wether I'm using docker-compose or ./sync commands. Any ideas?

**Comment by EugenMayer** [comment]
@glaesser either you configured docker-sync the wrong way ( which i highly suggest ) e.g. by missing the limitation docker-compose allows you to override volumes, e.g. see https://github.com/EugenMayer/docker-sync/issues/479 ....

or you are using opache with stat=1 so files are not read directly on bootstrap, which is pretty nonsense for development ( since you would need to restart  fpm or flush opcache cache each time you change a file to be in affect ).

We use Laravel ( lumen ) and docker-sync has an significant impact (positiv ), so there is for sure a gain, but those numbers should speak for themself: https://github.com/EugenMayer/docker-sync/wiki/4.-Performance

**Comment by glaesser** [comment]
@EugenMayer thanks for the comment! I simply followed the laradock instructions (http://laradock.io/documentation/#improve-speed-on-macos), meaning I installed docker-sync and then ran laradock's included ./sync.sh script to start docker-sync & subsequently docker. 

Laradock works fine out of the box, and docker-sync seems to install + start fine, I'm just not seeing *any* performance improvements in my laravel app at all - so clearly something is not right. Any suggestions on how I can I go about debugging this?

OSX 10.13.0
Laradock 0.5.8
Docker 17.09.0 CE
Docker-Sync 0.4.6

**Comment by flexgrip** [comment]
Same here. Zero change in query time. I think for the other loss in speed I'm seeing is just that laravel, through laradock, is only serving one request at a time. If I run it through homestead it serves multiple chunks of them at once. Maybe I've configured something wrong.

But again, using sync.sh I'm still seeing 2 second requests that take milliseconds when using laravel through vagrant or any other VM.

**Comment by samthomson** [comment]
@flexgrip Following @MatthewDrouin :cache tip I added `:cached` to my volume parameter in docker compose:
```
services:
  applications:
    build: 
      context: ./docker-containers/applications
    volumes:
      - ./www-workspace:/var/www:cached
```

**Comment by glaesser** [comment]
@samthomson strange, I added the :cached flag into docker-compose.yml, rebuilt my docker images, but it made no difference in script execution time, still 1-1.5seconds to load any page:

```
    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www:cached
```

Am I missing something?

**Comment by Vanuan** [comment]
@glaesser `cached` is for reading. Maybe you're writing?
Are there any temporary files being created at `${APPLICATION}`?
You might want to use `delegated` for these folders.
E.g.:

    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www:cached
        - ${APPLICATION}/tmp:/var/www/tmp:delegated

**Comment by glaesser** [comment]
Thanks for the suggestion @Vanuan, I'm def. reading, i.e. just rendering standard laravel views that take <0.1s to generate on nginx/mac, but 1-1.5s with nginx/laradock. I tried your suggestion anyways but unfortunately it made no difference in speed.

@flexgrip where you able to try the :cached option?

**Comment by EugenMayer** [comment]
:cached will not help you - you struggle with the read performance, and that one is not affected by :cached.

docker-sync will help you to go down to the speed you have with the mac native.

**Comment by EugenMayer** [comment]
Just looked at the setup to help you out guys - would be good if you did not simply ignore my comment above, its all in there already.

i created https://github.com/laradock/laradock/issues/1226 which is basically what i already wrote in https://github.com/laradock/laradock/issues/353#issuecomment-340504119

Now its up to you guys to fork this repo, test what i have done there and then make a pull request.
You can also quick-test that by simply removing this line https://github.com/laradock/laradock/blob/master/docker-compose.yml#L10

Then stop docker-sync: `docker-sync clean`

And start it again using `./sync.sh`

**Comment by EugenMayer** [comment]
I would even advise, for all of you really relying on that, do not use sync.sh at , just do

Installing docker-sync once

`gem install docker-sync`

then for your daily tasks

`docker-sync clean` 

to cleanup and stop your stack, start from scratch, and 

`docker-sync start` 

to start your stack. That it is, not need for a wrapper for that, it usually overcomplicates things. Use the documentation  https://github.com/EugenMayer/docker-sync/wiki - maybe more specifically https://github.com/EugenMayer/docker-sync/wiki/2.1-sync-commands

**Comment by Vanuan** [comment]
> :cached will not help you - you struggle with the read performance, and that one is not affected by :cached.

Why not? https://docs.docker.com/docker-for-mac/osxfs-caching/

> cached: the host’s view is authoritative
> (permit delays before updates on the host appear in the container)

So it is specifically to improve the read performance (mac -> virtual machine -> container).

Does laradock override the `:cached` option in some way so it is not used?

**Comment by Vanuan** [comment]
@glaesser what command do you use to start containers?

Is it `docker-compose up`? Or is it `sync.sh`? Do you have `docker-compose.override.yml` file?

**Comment by EugenMayer** [comment]
@Vanuan `:cached` - sorry!. I mixed it up with delegated, which is the other side of the island. `:cached` could potentially help, i yet see that i never benchmarked it, since it has yet implemented very lately. I will add this to my performance tests. At least i remember people already tried a very early implementation and it was worth basically nothing.

to be honest, i would be glad if cached + delegated would fix the issue overall - and thus every need of docker-sync in general.

**Comment by flexgrip** [comment]
I'll try using docker-sync directly instead of the sync.sh script (shouldn't it be identical though?). But so far, cached or the sync.sh script are still giving be incredibly slow response times. Reading or making API get reqs seem to get served in 3 seconds average. The same requests through vagrant take milliseconds.

**Comment by ndberg** [comment]
As of 2018 docker for mac has native support for nfs:
[https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc](url)
[https://forums.docker.com/t/nfs-native-support/48531](url)
[https://github.com/IFSight/d4m-nfs](url)

But I can't get it to work with laradock. Has anyone already done?

**Comment by EugenMayer** [comment]
By now means this is native, you will get a cold shower :)

Beside that, there are way to many issues with that so a fear, thats still not solution ;/

**Comment by ndberg** [comment]
Hmm perhaps I could get it to work for the mysql & the php-fpm container with adding / editing this in docker-compose.yml

```
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${DATA_PATH_HOST}"
  php-fpm:
    driver: ${VOLUMES_DRIVER}
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${APP_CODE_PATH_HOST}"
```

and running this bash script, as described in [https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc](url)
```
#!/usr/bin/env bash

OS=`uname -s`

if [ $OS != "Darwin" ]; then
  echo "This script is OSX-only. Please do not run it on any other Unix."
  exit 1
fi

if [[ $EUID -eq 0 ]]; then
  echo "This script must NOT be run with sudo/root. Please re-run without sudo." 1>&2
  exit 1
fi

echo ""
echo " +-----------------------------+"
echo " | Setup native NFS for Docker |"
echo " +-----------------------------+"
echo ""

echo "WARNING: This script will shut down running containers."
echo ""
echo -n "Do you wish to proceed? [y]: "
read decision

if [ "$decision" != "y" ]; then
  echo "Exiting. No changes made."
  exit 1
fi

echo ""

if ! docker ps > /dev/null 2>&1 ; then
  echo "== Waiting for docker to start..."
fi

open -a Docker

while ! docker ps > /dev/null 2>&1 ; do sleep 2; done

echo "== Stopping running docker containers..."
docker-compose down > /dev/null 2>&1
docker volume prune -f > /dev/null

osascript -e 'quit app "Docker"'

echo "== Resetting folder permissions..."
U=`id -u`
G=`id -g`
sudo chown -R "$U":"$G" .

echo "== Setting up nfs..."
LINE="/Users -alldirs -mapall=$U:$G localhost"
FILE=/etc/exports
sudo cp /dev/null $FILE
grep -qF -- "$LINE" "$FILE" || sudo echo "$LINE" | sudo tee -a $FILE > /dev/null

LINE="nfs.server.mount.require_resv_port = 0"
FILE=/etc/nfs.conf
grep -qF -- "$LINE" "$FILE" || sudo echo "$LINE" | sudo tee -a $FILE > /dev/null

echo "== Restarting nfsd..."
sudo nfsd restart

echo "== Restarting docker..."
open -a Docker

while ! docker ps > /dev/null 2>&1 ; do sleep 2; done

echo ""
echo "SUCCESS! Now go run your containers 🐳"
```
I looks right when I inspect the volume
```
➜  toportal git:(master) ✗ docker volume inspect laradock_toportal_php-fpm
[
    {
        "CreatedAt": "2018-11-28T10:33:24Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "laradock_toportal",
            "com.docker.compose.version": "1.23.1",
            "com.docker.compose.volume": "php-fpm"
        },
        "Mountpoint": "/var/lib/docker/volumes/laradock_toportal_php-fpm/_data",
        "Name": "laradock_toportal_php-fpm",
        "Options": {
            "device": ":../",
            "o": "addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3",
            "type": "nfs"
        },
        "Scope": "local"
    }
]
➜  toportal git:(master) ✗ docker volume inspect laradock_toportal_mysql
[
    {
        "CreatedAt": "2018-11-28T08:58:51Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "laradock_toportal",
            "com.docker.compose.version": "1.22.0",
            "com.docker.compose.volume": "mysql"
        },
        "Mountpoint": "/var/lib/docker/volumes/laradock_toportal_mysql/_data",
        "Name": "laradock_toportal_mysql",
        "Options": {
            "device": ":~/Code/toportal/.docker/data",
            "o": "addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3",
            "type": "nfs"
        },
        "Scope": "local"
    }
]
```

But I doesn't feel like it's faster..

**Comment by siteboomhub** [comment]
Hello, @ndberg 
Do you resolve your issue with docker speed on the mac os? Could you say how you improve your docker speed?

**Comment by ndberg** [comment]
Hmm I'm not shure but I don't think so. I changed back to laravel/homestead and am still working with it.
