### ISSUE TITLE
Idea: Add support for Selenium containers (for PHPUnit, Behat)

### ISSUE THREAD

**Issue by edmundluong** [laradock/laradock#356]
Hi,

[Behat](https://github.com/Behat/Behat) is a very popular BDD testing framework for PHP that has relevance in the Laravel community thanks to the [Laracasts series on it](https://laracasts.com/lessons/laravel-5-and-behat-bffs). 

Although Behat is great for testing static HTML and PHP code, it cannot test Javascript frontend components without [using a browser emulator](http://mink.behat.org/en/latest/drivers/selenium2.html), such as [Selenium](http://www.seleniumhq.org/). Selenium is also [supported in PHPUnit](https://phpunit.de/manual/4.8/en/selenium.html) as well, giving the developer the option to use it if they choose to.

With Javascript frontend frameworks being so prevalent these days, it might be useful to have the option to run a Selenium server in a container in Laradock so you have the capability of testing Javascript frontend components. 

There appears to be existing Docker repository for Selenium at [SeleniumHQ/docker-selenium](https://github.com/SeleniumHQ/docker-selenium), but I am not very experienced with configuring Docker Compose and adding new containers.

If there is support for this and I can figure out how to add containers to Docker Compose, I wouldn't mind  doing this as a PR. Let me know what you think.

**Comment by Mahmoudz** [comment]
@edmundluong it's nice to have support for Behat.

I can say just submit a PR and we'll review it together.. In general look at any supported tool and try to do the exact same thing! 

Just one note, since it's a tool make sure it has parameter in the docker-compose file so users can set to TRUE if they want it to be installed.

Best,

**Comment by Modelizer** [comment]
@edmundluong If you are specific to a Laravel base project and can go on with standalone server then you can use this [package](https://github.com/modelizer/selenium)

**Comment by edmundluong** [comment]
Finally got a chance to take a look at this, I was able to successfully run Selenium and execute tests using it with the changes from #519
