### ISSUE TITLE
docker-compose build workspace stuck without error or timeout

### ISSUE THREAD

**Issue by WiselyCST** [laradock/laradock#3564]
I just reinstalled docker-desktop and cloned the repo.

when i run docker-compose build workspace , I am stuck at below 
```
 => [workspace  52/116] RUN if [ true = true ]; then     mkdir -p /home/laradock/.nvm &&     curl -o- https://r  615.8s
 => => # (node:3472) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and mig
 => => # ht change at any time
 => => # (Use `node --trace-warnings ...` to show where the warning was created)
 => => # (node:3527) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and mig
 => => # ht change at any time
 => => # (Use `node --trace-warnings ...` to show where the warning was created)
```

There is no timeout or any other log appearing. I tried in my other laptop also it produces the same outcome . It just does not stop building and has no timeout. my internet is stable too.

Steps to reproduce , 

```
1. Install docker desktop
2. git clone https://github.com/laradock/laradock.git
3. cd laradock
4. cp .env.example .env
5. docker-compose build workspace
```

OS : Windows 11 Pro

Please help.

**Comment by vtaudesign** [comment]
I'm experiencing the same issue. To resolve it, I updated the `WORKSPACE_NODE_VERSION` variable in the `.env` file 
from 
`WORKSPACE_NODE_VERSION=node` 
to 
`WORKSPACE_NODE_VERSION=22.6.0` 
Hopefully, this change will help others who are facing the same problem.
