### ISSUE TITLE
Video tutorial 

### ISSUE THREAD

**Issue by soly2014** [LaraDock/laradock#36]
I need video tutorial to understand it

**Comment by Mahmoudz** [comment]
I will make a new video tutorial soon of the latest version.

Meanwhile check out the last available tutorial covering version 0.3.0 https://www.youtube.com/watch?v=jGkyO6Is_aI

**Comment by Mahmoudz** [comment]
@soly2014 Here's the new video ;) https://www.youtube.com/watch?v=-DamFMczwDA
