### ISSUE TITLE
Video tutorial for docker 1.2?

### ISSUE THREAD

**Issue by manshoor** [LaraDock/laradock#362]
Hey,
I was wondering if you can make a new video tutorial for docker 1.2 with multisite?

**Comment by g0ld3lux** [comment]
I believe multisite has something to do with
your webserver container...
nginx/apache/caddy
as i can see... or if you check the docker-compose.yml
theres a portion there that allows you to add new site volumes... for nginx...
its straight forward if you dont need ssl ...
i dont know for apache..
but caddy can be configured using the caddyfile... by adding a new host...
you can check the documentation of caddyfile...

**Comment by philtrep** [comment]
@manshoor I don't believe we have a fully integrate solution at the moment (someone correct me if I am wrong) but I have seen @LarryEitel work on it #54 , he might be able to give you some pointers.

**Comment by Mahmoudz** [comment]
@manshoor @g0ld3lux as @philtrep mentioned it's not fully integrated, I'll include full documentation about that part once it's fully tested and ready.

Make sure to read my second and third comments here [https://github.com/LaraDock/laradock/pull/231](https://github.com/LaraDock/laradock/pull/231) and feel free to test and help speed up that proceess. Thanks
