### ISSUE TITLE
PHP_IDE_CONFIG XDebug environment variable, remove "

### ISSUE THREAD

**Issue by thelittlebug** [LaraDock/laradock#363]
In the php-fpm section of the docker-compose.yml file is a environment variable set. Xdebug is not working for me unless i change it from

```
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"
```

to:

```
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel
```

i've tested the correctnes of the environment variable via:

```
docker exec -ti laradock_php-fpm_1 bash
echo $PHP_IDE_CONFIG
```

**Comment by Mahmoudz** [comment]
@LarryEitel might help with this. Thanks in advanced.

**Comment by LarryEitel** [comment]
Happy to help. Been traveling for three weeks. Trying to catch up on stuff. Will get to this ASAP. :)

**Comment by appleboy** [comment]
confirmed this issue.

**Comment by appleboy** [comment]
@LarryEitel I created new PR. Waiting for your response.
