### ISSUE TITLE
Mysql downgrade to 5.6 replace mysql:mysql:5.6 to mysql:5.6

### ISSUE THREAD

**Issue by henrychavez** [LaraDock/laradock#366]
@Mahmoudz I had a problem when I try to run the command 
`docker-compose up -d  nginx mysql`

This is the error 
`Step 1 : FROM mysql:mysql:5.6
ERROR: Service 'mysql' failed to build: Error parsing reference: "mysql:mysql:5.6" is not a valid repository/tag`

To solve the problem I had to replace 
`FROM mysql:mysql:5.6` to `FROM mysql:5.6`

**Comment by philtrep** [comment]
this was solved by #367
