### ISSUE TITLE
Time in container is out of sync

### ISSUE THREAD

**Issue by aoki-sora** [laradock/laradock#372]
Moved from Homestead to Laradock recently and have encountered the following issue.
After creating a container, turning down the host machine for a while and running it again, the time in a container becomes out of sync.
As an example, it can be checked with oauth authorization flow:
![1](https://cloud.githubusercontent.com/assets/12220926/19417126/d365c84c-93bd-11e6-99f3-f4b2900aaf04.PNG)

Platform: Windows
Docker: 1.12.1-stable (build: 7135)

**Comment by aoki-sora** [comment]
Noticed that it happens when the docker's deamon starts on system boot. If you disable that option and run docker manually, then it works fine.

**Comment by Jono20201** [comment]
Also experiencing this issue.
