### ISSUE TITLE
Static files access

### ISSUE THREAD

**Issue by aoki-sora** [laradock/laradock#373]
After viewing static file in the browser (compiled css for example), there is no write access to it.
Trying to run gulp after viewing an asset in the browser - it will result in the following error:
![2](https://cloud.githubusercontent.com/assets/12220926/19417143/add9b9e8-93be-11e6-96a5-40912b6193ed.png)
Trying to delete the file will produce an error as well:
![3](https://cloud.githubusercontent.com/assets/12220926/19417144/b1aaa60e-93be-11e6-89f9-c270765dfae3.PNG)

Related to  #148 

Platform: Windows
Docker: 1.12.1-stable (build: 7135)

**Comment by aoki-sora** [comment]
When checking the files in the container I've noticed that files have root owner, not laradock. Laradock has been added to an already created project. Not sure if it's related.

**Comment by philtrep** [comment]
@aoki-sora Try using the `laradock` user to run gulp.

```
docker-compose exec --user=laradock workspace bash
gulp
```

Make sure your `public` and `resources` folders are owned by `laradock:laradock` and have at least `644` permissions.

**Comment by aoki-sora** [comment]
Thank you. I will try.
They are owned by root. I tried to run chown to change owner to laradock:laradock, but it didn't take effect.

**Comment by philtrep** [comment]
@aoki-sora You are welcomed.

It's probably because the `root` user is the one running `gulp` so it rewrites the output files with `root` as the owner.

**Comment by aoki-sora** [comment]
All directories are owner by root inside the project.

**Comment by philtrep** [comment]
@aoki-sora Okay, that's not normal. The files should be owned by `laradock:laradock`. Purge all images and containers then build and run LaraDock. If that doesn't do it, it's probably a host specific issue...

**Comment by philtrep** [comment]
@aoki-sora Did you manage to get it working?

**Comment by ovidius72** [comment]
I had the same problem while trying to access files on a local server.
I solved it by installing the `acl` package in the workspace container

`docker-compose exec workspace bash`

`apt-get update & apt-get install acl`

after that I was able to run the command:

`setfacl -d -R -m o::rwx /var/www`

From now on all new created files (either by php artisan and directly from your IDE) will have the UID and GID set to 500 (normal user) and you are able to edit and save them.

Because the existing files will retain the original permissions I don't think this could lead to security issues.

**Comment by AlennGK** [comment]
```
►/var/www# setfacl -d -R -m o::rwx /var/www/public/css
setfacl: /var/www/public/css: Operation not supported
```
But after 10 minutes the file deleted on by own. Now I can't recreate the bug. It is fine and file is  `root root ... app.style.css` So there must be some other issue. Anyway I have this problem everytime I boot my windows X and run the docker.

**Comment by ovidius72** [comment]
@AlennGK Are you running the command as laradock user or as root? Maybe the laradock user doesn't have the permissions to perform the action.
To have it permanently working you have to add it in the workspace Dockerfile so that it runs every time you boot the machine.
