### ISSUE TITLE
Nginx + Postgres + Mac + Docker Mac => FastCGI Uncaught ReflectionException: Class App\Http\Kernel does not exist

### ISSUE THREAD

**Issue by Selsynn** [LaraDock/laradock#378]
I don't understand.
I have done the upgrade of laradock monday. It worked.
Tuesday and Wednesday morning, i was working on other website (on docker but not on laradock) 
And when I wanted to come back to my laradock project, yesterday afternoon : bug.

No response. 
I killed docker, restart it, docker-composed and build a new time the project. No luck.
I killed the mac, restart it this morning, with high expectation. No more luck.
I will end the little story here. 

In laradock/logs/nginx/error, there is a lot of : 

```
2016/10/20 09:44:15 [error] 8#8: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class App\Http\Kernel does not exist in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('App\\Http\\Kernel')
#1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('App\\Http\\Kernel', Array)
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('App\\Http\\Kernel', Array)
#3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(230): Illuminate\Foundation\Application->make('App\\Http\\Kernel', Array)
#4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 /va" while reading response header from upstream, client: 172.18.0.1, server: laravel, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost"
```

Docker-compose command line : 
```
docker-compose up --build --force-recreate -d nginx postgres
```

I doesn't understand why this error has popped. 
I deleted the "extra-host" because I don't use PHP storm (I use IntelliJ) and I understand it was only for debugging processes.
I didn't change other thing.

I dunno where to look. When I ago to test the api, I have an error 500, and when I open the welcome page, I have nothing (on Safari) and an error 500 (on Chrome).
(I tested with localhost and with 127.0.0.1. If it is another ip address I don't know where to find it ?)

If you have the least idea where to look ?
I tried https://github.com/LaraDock/laradock/issues/327 with no more luck. In Workspace, localhost is not known.

Edit : seems to be a link with https://github.com/LaraDock/laradock/issues/285. But I install fresh from monday ???

**Edit 2 : I did a composer update on my project files and it seems to do the thing.**

**Comment by philtrep** [comment]
@Selsynn glad you go it to work and thanks for sharing your solution :)
