### ISSUE TITLE
ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by hopewise** [LaraDock/laradock#380]
I tried to connect to workspace container, I've used the included private key in the repo,

> ssh -i ~/.ssh/insecure_id_rsa  -v root@192.168.1.34 -p 223
> OpenSSH_6.9p1, LibreSSL 2.1.8
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 21: Applying options for *
> debug1: /etc/ssh/ssh_config line 56: Applying options for *
> debug1: Connecting to 192.168.1.34 [192.168.1.34] port 223.
> debug1: Connection established.
> debug1: key_load_public: No such file or directory
> debug1: identity file /Users/samir/.ssh/insecure_id_rsa type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /Users/samir/.ssh/insecure_id_rsa-cert type -1
> debug1: Enabling compatibility mode for protocol 2.0
> debug1: Local version string SSH-2.0-OpenSSH_6.9
> ssh_exchange_identification: Connection closed by remote host

here is the settings of workspace:

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_YARN=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - TZ=UTC
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            # from inside container, run:  /sbin/ip route|awk '/default/ { print $3 }'
            - "dockerhost:172.17.0.1"
        ports:
           - "223:22"
        tty: true
        links:
            - postgres

Any idea how to ssh through workspace container?

**Comment by philtrep** [comment]
Unless you need to remotely access the `workspace` container, I suggest you connect to it using ```
docker-compose exec --user=laradock workspace bash
``` instead of ssh.

**Comment by philtrep** [comment]
That being said I haven't used SSH in LaraDock yet, this could be an bug.

**Comment by hopewise** [comment]
I need to setup xdebug, in PHPStorm I create remote debug profile, so I had to point to the remote PHP interpreter via ssh?
Can you please tell me how to setup xdebug without using ssh using laradock?

**Comment by philtrep** [comment]
@hopewise Make sure you follow the docs https://github.com/LaraDock/laradock#install-xdebug.
Checkout #363  and #369 if you still have a problem.
