### ISSUE TITLE
Editing xdebug.ini?

### ISSUE THREAD

**Issue by hopewise** [LaraDock/laradock#382]
When I edit:

    /Users/samir/Documents/projects/project-apis/laradock/workspace/xdebug.ini

Shall I just restart the container? 
I tried `docker-compose up -d nginx php-fpm workspace` but:

```
Starting laradock_volumes_source_1
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
laradock_nginx_1 is up-to-date
```

**Comment by philtrep** [comment]
Try `docker-compose down; docker-compose up --build -d nginx php-fpm workspace`
