### ISSUE TITLE
./xdebugPhpFpm: Permission denied

### ISSUE THREAD

**Issue by hopewise** [LaraDock/laradock#385]
in the php-fpm Container, in laradock folder, I tried to run:

    ./xdebugPhpFpm status

but I got:

    ./xdebugPhpFpm: Permission denied

I tried sudo after installing it, but I got:

```
root@aa51abf59215:/var/www/laravel/laradock# sudo ./xdebugPhpFpm status
sudo: ./xdebugPhpFpm: command not found
```

So, what do I miss?

**Comment by hopewise** [comment]
I also tried:

    docker exec --user=laradock laradock_php-fpm_1 bash

but I got:

    unable to find user laradock: no matching entries in passwd file

**Comment by Mahmoudz** [comment]
@hopewise I think @LarryEitel can help with that.

**Comment by LarryEitel** [comment]
Sorry for the delay. Everyone keeps throwing more rocks on my pile!!!

I pulled down the latest just now and ran the command from `../laravel/laradock`:

`./xdebugPhpFpm status`

It returned:
```
xDebug status
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/aeros
pike.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/aerospike.so: cannot open shared object file: No such
 file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=opcache.so
from php.ini) in Unknown on line 0
PHP 7.0.9 (cli) (built: Aug 10 2016 19:45:48) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

I thought the `Unable to load ... aerospike.so` was previously resolved. Anyway, I do not see a `Permission denied` error. 

Curious, did you switch on xdebug for php-fpm in the `docker-compose.yml` file? 
```
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
```

**Comment by hopewise** [comment]
yes, I did set it to true

**Comment by LarryEitel** [comment]
Dumb question... you are running `./xdebugPhpFpm status` from the host prompt rather than Inside php-fpm container?

What OS are you running Docker on?

**Comment by hopewise** [comment]
From inside the container, I am running docker on OS X, Capitan 10.11.16

```
$docker version

Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by LarryEitel** [comment]
So to be clear, the command should be run from the same prompt where you run docker-compose. :) Not Inside any of the running containers.

**Comment by hopewise** [comment]
> To controll the behavior of xDebug (in the php-fpm Container), you can run the following commands from the LaraDock root folder:
> 
> Stop xDebug from running by default: ./xdebugPhpFpm stop.
> Start xDebug by default: ./xdebugPhpFpm start.
> See the status: ./xdebugPhpFpm status.

oh, sorry! I thought that `in the php-fpm Container` is, from inside the container, I think the doc needs to be little more clear for dumbs 🤐

**Comment by philtrep** [comment]
@hopewise if the doc is not clear I encourage you to do a PR with a rewording :)

**Comment by hopewise** [comment]
sure!  but I still have some questions please.

Would you explain how docker-compose work? what is meant by 

```
build:
    context: ./workspace
```

And how 
```
volumes_from:
            - volumes_source
```
led to the folder in which LaraDock folder in?

What is `tty: true` ?

Also, aren't we have two php interpreters? one in the workspace container? and another in PHP-FPM container? which one to point to from PHPStorm?

**Comment by LarryEitel** [comment]
PHP in php-fpm is what is used by web server and is what is controlled by ./xdebugPhpFpm. PHP in workspace is what is used when running php unit tests.

**Comment by hopewise** [comment]
I see, thanks.
Here is [PR](https://github.com/LaraDock/laradock/pull/391) about where to run the xdebugPhpFpm command

**Comment by philtrep** [comment]
@hopewise I'd rather not give you an mediocre answer, I suggest reading the [docker compose documentation](https://docs.docker.com/compose/compose-file/) if you want learn more.

And thanks for the PR :)

**Comment by hopewise** [comment]
you are welcome

**Comment by dannysood** [comment]
@philtrep Even though this ticket is closed but I was facing a similar issue. Turns out Permission Denied can also be caused because xdebugPhpFpm didnt have execution permission. Simple enough fix but I missed it and that is how I ended up here. Should I do a pull request with this detail in readme?

**Comment by philtrep** [comment]
@dannysood Yes, absolutely.

**Comment by dannysood** [comment]
@philtrep Ill take care of the PR tomorrow.
