### ISSUE TITLE
I'm using laradock for Codeigniter 3

### ISSUE THREAD

**Issue by manshoor** [LaraDock/laradock#387]
I'm getting this issue in my project.

PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=opcache.so from php.ini)

**Comment by philtrep** [comment]
I believe this is a duplicate of #325

**Comment by Mahmoudz** [comment]
@manshoor could you share with us the steps of how to setup codeigniter on laradock? I'd like to mention that in the documentation. If you prefer you can send a PR or just comment it here and I'll move it to a new section in the docs. Thanks.

**Comment by manshoor** [comment]
@Mahmoudz 
yes sure, it's actually the same as Laravel but here is the only change for mysqli extension in php-fpm/Dockerfile-56

# PHP extensions

RUN docker-php-ext-install mysqli

RUN docker-php-ext-install tokenizer

**Comment by Mahmoudz** [comment]
@manshoor could you try the last laradock release 4.8.0 and confirm that Codeigniter is running perfectly, you may need to check this section for some help [https://github.com/LaraDock/laradock#Install-Codeigniter](https://github.com/LaraDock/laradock#Install-Codeigniter) Thanks.

**Comment by manshoor** [comment]
@Mahmoudz Yep it worked like a charm (y)
I'm setting up a Symfony application on Laradock, I'll share the PR with you :)

**Comment by Mahmoudz** [comment]
@manshoor amazinggg thanks

**Comment by mjawaids** [comment]
I've tried to use CodeIgniter but page always shows Nginx 404 page. I've tried the suggestions above and from #325 but still not working.

**Comment by manshoor** [comment]
enable `CODEIGNITER=true` in docker compose and in nginx config map the public folder correctly like this 

```
server_name projectName.local;

root /var/www/projectName/public_html;

```

**Comment by mjawaids** [comment]
I already enabled the codeigniter=true but didn't configure nginx as wanted
to run default with localhost.

**Comment by manshoor** [comment]
so, now is it working fine?

**Comment by mjawaids** [comment]
Nope.

**Comment by magicuniverse-azeem** [comment]
@manshoor were you able to set symfony project. Is there a PR for it?
