### ISSUE TITLE
i got SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by Lopez-i** [LaraDock/laradock#389]
i've running apache2 and mysql containers and i follow your tutorial but i got SQLSTATE[HY000] [2002] Connection refused

**Comment by Lopez-i** [comment]
i work on macOS Sierra

**Comment by Lopez-i** [comment]
ok Solved by adding MYSQL_HOST=mysql but there is no way to configure with 127.0.0.1 ? and same for redis ?

**Comment by philtrep** [comment]
@Lopez-i Glab you got it to work. Thing is, these services are all runing in different containers, that's why you can't access other services through 127.0.0.1.

Do you have a particular reason for wanting them accessible through 127.0.0.1?

**Comment by Lopez-i** [comment]
no i've not and i notice that laradock running very slowly

**Comment by philtrep** [comment]
@Lopez-i I'm closing this since your issue has been fixed.

About LaraDock running slowly, please have a look at #353.
