### ISSUE TITLE
Standardize syntax in docker-compose.yml

### ISSUE THREAD

**Issue by philtrep** [laradock/laradock#392]
We're currently using two syntax in the default `docker-compose.yml`:

```
args:
    - INSTALL_XDEBUG=false
    - INSTALL_MONGO=false
```

and

```
environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
```

To make it easier to understand, I believe we should change the lines using the second syntax to the first (actual YAML collections).
#383 is a good example of having multiple syntaxes being confusing.

What do you guys think?

**Comment by Mahmoudz** [comment]
@philtrep I closed this since it's been for a long time, however I will try to fix this in the next release. Thanks
