### ISSUE TITLE
xDebug PhpStorm Working Via CLI - Not Working Via Web Page/Apache

### ISSUE THREAD

**Issue by calebfavor** [laradock/laradock#393]
Hello I am having an issue getting php-fpm to trigger debugging when hitting web pages. I have setup everything correctly as far as I know, here are my configs:

docker-composer.yml:
![image](https://cloud.githubusercontent.com/assets/5841780/19746314/b57c865c-9b8a-11e6-930c-ec23b432dd8a.png)

php-fpm/xdebug.ini:
![image](https://cloud.githubusercontent.com/assets/5841780/19746336/cda31cfa-9b8a-11e6-8262-365fd54986bb.png)

The debugging works great when calling php from the CLI (inside the fpm container):
![image](https://cloud.githubusercontent.com/assets/5841780/19746360/ffcdb9a6-9b8a-11e6-9958-34cca09f74d5.png)

However when I load a web page it refuses to try and connect to phpstorm, there is no output inside php storm at all. Also the web pages still load at full speed (in my experience if xdebug is properly trying to look for a remote connection the page load times double).

Here is phpinfo output for xdebug, so its definitley being loaded properly:
![image](https://cloud.githubusercontent.com/assets/5841780/19746418/4c609d24-9b8b-11e6-8eba-9adcee6dbf73.png)

I also have the xdebug chrome extension setting the cookie for the ide key to PHPSTORM.

I am totally stumped, any advice would be appreciated.

*Edit - I am using apache.

Cheers!

**Comment by LarryEitel** [comment]
Check out a Pull Request I submitted: [phpstorm-guide](https://github.com/LarryEitel/laradock/blob/phpstorm-guide/_guides/phpstorm.md). That may give you some ideas. [This branch](https://github.com/LarryEitel/laradock/blob/phpstorm-debug/_guides/phpstorm.md) actually has various settings switched on. In other words, this branch actually is fully configured to successfully debug in PHPStorm. Hope this helps.

**Comment by calebfavor** [comment]
@LarryEitel - Thanks for getting back to me! I actually used your guide to get setup (the guide is awesome). My files/settings match that branch exactly, however I still cant get it to work through the web. It works when I call files directly from the CLI, makes me think everything is setup correctly. I think I've pin pointed the issue to php-fpm simple not triggering a remote debug session when being called via apache, which seems strange to me since apache shouldn't have much impact on a fpm setup.

**Comment by LarryEitel** [comment]
Your dockerhost IP appears to be your local network IP. You would need to make sure that port 9000 is open or PHPStorm app is open in firewall.

Do you get some kind of error like "Failed to connect to xdebug"?

**Comment by LarryEitel** [comment]
Can you find your docker host IP? Mine is `10.0.75.1` Here is one way on Windows:
<img src="https://farm6.staticflickr.com/5693/30500352911_748ed5d939.jpg">

**Comment by calebfavor** [comment]
@LarryEitel - I had no idea docker ran another adapter! Yes my host IP is 10.0.75.1. I changed my dockerhost to that in the compose file and rebuilt. Still have the exact same issue. I do get that error when trying to run xdebug in a test. I have the remote interpreter setup as per your guide, and I can run phpunit tests through docker inside php storm successfully. However when I try and run the test with debugging I get: 

![image](https://cloud.githubusercontent.com/assets/5841780/19748483/cc6acf34-9b96-11e6-95fe-99ebca0b10d9.png)

**Comment by LarryEitel** [comment]
Almost positive that your firewall is blocking port 9000. I actually installed telnet in php-fpm to conveniently verify I was able to connect to PHPStorm. 

Also, you DO have PHP remote debug running right?

**Comment by LarryEitel** [comment]
Did you change to 10.0.75.1? Otherwise you will not be able to reach your local IP unless you configure your router to route traffic from public to your local IP.

**Comment by calebfavor** [comment]
@LarryEitel - Yes I did change the dockerhost lines to 10.0.75.1. I have verified the php-fpm container can access my hosts ip on port 9000:

![image](https://cloud.githubusercontent.com/assets/5841780/19748698/47f84180-9b98-11e6-9342-2ebce995ca1e.png)

I am not sure what you mean by having 'php remote debug' running. I have the php-fpm apache2 containers running. Also yes I can successfully debug inside phpstorm when calling php directly from the cli (see first post picture). Its only over localhost when viewing the actual web pages where it wont trigger.

**Comment by LarryEitel** [comment]
https://raw.githubusercontent.com/LarryEitel/laradock/phpstorm-debug/_guides/photos/PHPStorm/DebugRemoteOn.png

Is this running in your PHPStorm?

**Comment by calebfavor** [comment]
Yes:

![image](https://cloud.githubusercontent.com/assets/5841780/19748873/73bac472-9b99-11e6-851b-bb12a66dcc3b.png)

![image](https://cloud.githubusercontent.com/assets/5841780/19748879/7a67c806-9b99-11e6-8dfc-fb12c7f6c272.png)

**Comment by LarryEitel** [comment]
Unselect the 'phone' icon. :)

**Comment by calebfavor** [comment]
That seemed to have no effect. I dont think php-fpm is even attempting to connect to phpstorm.

**Comment by LarryEitel** [comment]
When you run ./xdebugPhpFpm status from laradock folder does it say the xdebug is enabled?

**Comment by LarryEitel** [comment]
I just realized that you said that you cannot connect xdebug when running unit tests. You don't need to have remote debugging on for that.

**Comment by calebfavor** [comment]
Yes xdebug is enabled, I can see that it is enabled and set correctly via the phpinfo page.

**Comment by LarryEitel** [comment]
Curious, are you running on a MAC?

Also, how about we focus on unit test debugging first. Turn of Remote debugging. Right-click on ExampleTest and select debug.

**Comment by calebfavor** [comment]
I get the same error:

![image](https://cloud.githubusercontent.com/assets/5841780/19749656/8cbd6a96-9b9f-11e6-919e-2f80ed347685.png)

Clicking 'validate installation' has no effect. 

I am done for today, thanks so much for your help thus far I really appreciate it.

**Comment by calebfavor** [comment]
@LarryEitel - I am running on windows. Here is the output when running a test inside phpstorm with debugging:

`sftp://root@localhost:2222/usr/bin/php -dzend_extension=/usr/lib/php/20151012/xdebug.so -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=172.18.0.1 /root/.phpstorm_helpers/phpunit.php --configuration /var/www/laravel/phpunit.xml --filter "/::test_persist_many_update( .*)?$/" AccessLevelDataMapperTest /var/www/laravel/tests/integration/data-mappers/access/AccessLevelDataMapperTest.php
Testing started at 8:33 AM ...
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.


Time: 644 ms, Memory: 16.00MB

OK (1 test, 20 assertions)

Process finished with exit code 0
`

With this small popup:

![image](https://cloud.githubusercontent.com/assets/5841780/19774105/ce38284a-9c20-11e6-92b2-08c02b5780e0.png)

If I click validate I can also view the php info which reveals this: 
![image](https://cloud.githubusercontent.com/assets/5841780/19774153/f00f838c-9c20-11e6-88f6-46a32eeafda7.png)
![image](https://cloud.githubusercontent.com/assets/5841780/19774171/fe344d44-9c20-11e6-8852-ac77d9393ec0.png)


It looks like it is trying to use remote debugging to connect to phpstorm, is that not correct?

**Comment by LarryEitel** [comment]
-dxdebug.remote_host=172.18.0.1 

where is that IP? 

Are you available on Skype?

**Comment by calebfavor** [comment]
@LarryEitel - After our chat and getting everything working, I was able to reverse engineer some of the steps and how they work. Here is a breakdown of what solved my problem.

First off I was using localhost (mapped to 127.0.0.1) to load my application in the browser, which does _work_ (since port 80 is mapped), but causes issues with network access on ports other than 80, therefore not allowing xdebug to connect on 9000. Instead you want to use the dockers hyper-v VM adapter IP. It can be found by opening Hyper-V Manager, clicking your computer on the left, and clicking the Networking tab at the bottom.

![image](https://cloud.githubusercontent.com/assets/5841780/19777897/21b9029c-9c2f-11e6-8d36-448612ba70ca.png)

Generally it will automatically be set to 10.0.75.2. This is not to be confused with the docker daemon adapters IP, which is 10.0.75.1. **Your actual application and containers run on the VMs adapter, which is 10.0.75.2.** 

So you need to be connecting to your application in the browser using the VMs ip. Ex. http://10.0.75.2/my-page (or the 'laravel' host alias as per the guide)

Also inside phpstorm you should be using 10.0.75.2 whenever referencing a connection to docker.

One other thing to note, you dont actually need a PHP -> Server setup in phpstorm to get debugging working. All you need is the sftp remote php interpreter setup properly using the correct IP (10.0.75.2) as per the guide, with the correct php executable/xdebug.so paths.

Hope thats helps with developing the guide, thanks again for your help Larry. 

Cheers!

**Comment by calebfavor** [comment]
One other thing, inside your docker-compose.yml, the php-fpm and workspace 'extra_hosts' -dockerhost: NEED to be set to the main docker adapters IP:  '10.0.75.1'

![image](https://cloud.githubusercontent.com/assets/5841780/19778289/e9b84874-9c30-11e6-8693-75fd88084bd2.png)

**Comment by LarryEitel** [comment]
I am very glad that you are up and running. I will further refine the guide per your observations.

I assume that you can now close this issue. :)

**Comment by LoopKarma** [comment]
I faced with same problem on Mac. I can debugging works from the CLI, but not from web pages

**Comment by calebfavor** [comment]
@LoopKarma I'm not very familiar with how the networking is setup on macs but my guess is the container cant connect with PhpStorm over port 9000. This could be due to your docker host not being set correctly or the port is being blocked by something.

**Comment by LoopKarma** [comment]
@calebfavor I roughly fixed this problem with adding `fastcgi_param REMOTE_ADDR your.host.ip.address` into http-server config file

**Comment by fideloper** [comment]
Thanks @LoopKarma, that was the final thing I had to figure out as well.

Since we're using Docker on mac/windows, we're port forwarding into the VM used by Docker on whatever port we expose.

PHP-FPM therefore receives the wrong REMOTE_ADDR, so I also hard-coded it into my config (which is just the worst hack imaginable for sharing this amongst a team :D )

Wonder if there's a better solution for that.

1. Either an env variable used to build the nginx config on the fly when starting the container
2. Some way to geting correct REMOTE_ADDR into the docker container, perhaps from setting up a new local network interface (on the host) and using it with docker? (e.g. [answer as described here](http://stackoverflow.com/questions/39143814/xdebug-not-working-in-docker-for-mac))

**Comment by fideloper** [comment]
Current work-around that's a bit more portable for Mac users:

**docker-compose.dev.yml** (extends a base compose file, but that's not important here):

```yaml
version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
     - "${APP_PORT}:80"
    environment:
      APP_ENV: ${APP_ENV}
      XDEBUG_PORT: ${XDEBUG_PORT}
```

`develop` bash script that runs docker-compose for me (passes arguments through), setting up env vars first

```bash
# Get local IP address on mac that container can ping
export XDEBUG_PORT=$(ipconfig getifaddr en1)
export APP_ENV=${APP_ENV:-local}
export APP_PORT=${APP_PORT:-80}

docker-compose -f docker-compose.dev.yml "$@"
```

`run.sh` script that starts php and nginx inside my container:

```bash
#!/usr/bin/env bash

# Find and replace configuration to support xdebug 

# Config /etc/nginx/sites-available/default
sed -i "s/#FINDREPLACE/fastcgi_param REMOTE_ADDR $XDEBUG_PORT;/g" /etc/nginx/sites-available/default

# Config /etc/php/7.0/mods-available/xdebug.ini
sed -i "s/xdebug\.remote_host\=.*/xdebug\.remote_host\=$XDEBUG_PORT/g" /etc/php/7.0/mods-available/xdebug.ini

# start supervisord
/usr/bin/supervisord
```

Then I have to setup PHPStorm to listen on port 9000 (I just did all networks) and debugging works for both CLI (as it always did) and Web (thanks to `REMOTE_ADDR` hack).

![image](https://cloud.githubusercontent.com/assets/467411/21192962/1297c2e4-c1f0-11e6-9ea7-68faa6485791.png)

**Comment by fideloper** [comment]
Update: I still updated xdebug.ini using the `start.sh` script, but I can avoid the hacky nginx configuration change simply by setting `xdebug.remote_connect_back=0`, which attempts to use the REMOTE_ADDR to send xdebug info back for web requests, if that is set.

Docs on that: https://xdebug.org/docs/all_settings

**Comment by Rastusik** [comment]
@fideloper just fyi, you can workaround the xdebug.ini replacing by this:
```
xdebug.remote_host = developer.local
```

and then modify the php container in docker-compose.yml with:
```
extra_hosts:
      - developer.local:${HOST_IP}
```

and just export the HOST_IP variable in the bash script which runs docker-compose up ;)

**Comment by coyl** [comment]
@fideloper all you need is set `xdebug.remote_connect_back = Off`

Here is a quote from xdebug documentation
> If enabled, the xdebug.remote_host setting is ignored and Xdebug will try to connect to the client that made the HTTP request. It checks the $_SERVER['HTTP_X_FORWARDED_FOR'] and $_SERVER['REMOTE_ADDR'] variables to find out which IP address to use.

So, if remote_connect_back is off, xdebug will just connect to `xdebug.remote_host` and that's all.

**Comment by wajdijurry** [comment]
Sometimes you should disable "xdebug.remote_connect_back" to get it work

**Comment by j3rrey** [comment]
just adding my 2 cents since I was debugging this for hours
adding 
```
xdebug.remote_host="host.docker.internal"
```
should do the trick ;)

**Comment by miertschink** [comment]
> @calebfavor I roughly fixed this problem with adding
> `fastcgi_param REMOTE_ADDR your.host.ip.address`
> into http-server config file

This did the trick for me, but instead of a fixed IP I set 
`fastcgi_param REMOTE_ADDR host.docker.internal`
