### ISSUE TITLE
Support HHVM

### ISSUE THREAD

**Issue by dearteno** [LaraDock/laradock#4]
i am currently using Vagrant with homestead building 
and try to migrate to docker.
Can you support for HHVM and mariadb ?

**Comment by Mahmoudz** [comment]
Yes sure, I am willing to support many other software's.
Currently I am in a vacation, 2 weeks from now and a support will be released for `HHVM` and `MariaDB`.

**Comment by AleksanderKoko** [comment]
Working on this feature right now. Will let you know @dearteno when my pull is merged with the project.

**Comment by Mahmoudz** [comment]
Finally HHVM is there #174 
Thanks to @orette

**Comment by marpaia** [comment]
It looks like the HHVM support was broken in e1dbb972f17e09659f111e85cd9979336245d9db.
