### ISSUE TITLE
Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by limatheus** [laradock/laradock#402]
Hi,

After last release, running  `docker-compose up -d nginx mysql redis` I got de following error:
``` 
Starting laradock_applications_1
laradock_redis_1 is up-to-date
laradock_mysql_1 is up-to-date
laradock_workspace_1 is up-to-date
Starting laradock_php-fpm_1

ERROR: for php-fpm  Cannot start service php-fpm: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/var/www/laravel\\\") set in config.json failed: no such file or directory\"\n"
ERROR: Encountered errors while bringing up the project.
```
Any tip?

**Comment by limatheus** [comment]
Hello again, 

I solved this issue removing all images with `docker rmi $(docker images -q)` and running `docker-compose up -d nginx mysql redis`.

Thank you anyway

**Comment by lexcode** [comment]
I got the same issue on my windows machine

ERROR: for workspace  Cannot start service workspace: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/var/www/laravel\\\") set in config.json failed: no such file or directory\"\n"
ERROR: Encountered errors while bringing up the project.

I tried @limatheus  solution but no lucky.

Thank you

**Comment by mitjarobic** [comment]
same problem

**Comment by ivanji** [comment]
same here - everything was working fine and decided to do a Laradock update and now I'm experiencing the same error. The above solution didn't work for us.

**Comment by philtrep** [comment]
I can't reproduce the error but I believe that modifying the compose config:
```
applications:
        image: tianon/true
        volumes:
            - ../:/var/www/laravel # changed from '/var/www'
```

should fix this.

**Comment by dennisc1** [comment]
For me, rebuilding all the containers with `docker-compose build --no-cache` did the trick. 
This method is described at [Upgrading LaraDock](https://github.com/LaraDock/laradock#upgrading-laradock)

**Comment by xonge** [comment]
@philtrep you're right,but what time will fix it?

**Comment by zhibuzu** [comment]
@philtrep  Thanks, it's works.

**Comment by silgon** [comment]
@dennisc1 thanks!, it worked for me!

**Comment by vickurt** [comment]
> For me, rebuilding all the containers with `docker-compose build --no-cache` did the trick.
> This method is described at [Upgrading LaraDock](https://github.com/LaraDock/laradock#upgrading-laradock)

You are DA MASTAAAA!
