### ISSUE TITLE
Cannot start service workspace

### ISSUE THREAD

**Issue by Kianda** [laradock/laradock#406]
OS: macOS 10.12
Docker: 1.12.1
Laradock: tag 4.10.0
Installation type: A.1) Setup environment in existing Project

Issue:
$ docker-compose up -d nginx mysql
Creating laradock_applications_1
Creating laradock_mysql_1
Creating laradock_workspace_1

ERROR: for workspace  Cannot start service workspace: oci runtime error: no such file or directory
ERROR: Encountered errors while bringing up the project.

Ideas? Thanks! :)
It's working with tag v4.8.0

**Comment by tylerkoldenjtp** [comment]
OS: Ubuntu 16.04.1 LTS
Docker: version 1.12.3, build 6b644ec
Laradock: tag 4.10.0
Installation type: A.1) Setup environment in existing Project

Issue:
$ sudo docker-compose -p test up -d nginx postgres elasticsearch redis

Creating test_applications_1
Creating test_postgres_1
Creating test_redis_1
Creating test_workspace_1

ERROR: for workspace  Cannot start service workspace: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/var/www/laravel\\\") set in config.json failed: no such file or directory\"\n"
ERROR: Encountered errors while bringing up the project.

[This post](https://github.com/docker/compose/issues/4039) recommends running as sudo which did not work for me.

**Comment by appleboy** [comment]
I try to remove all workspace container and images and rebuild again. It is working for me on tag `v4.10.0`

**Comment by bruno-farias** [comment]
+1 with the same problem

Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

**Comment by Kianda** [comment]
Thanks @appleboy that fixed my issues!
