### ISSUE TITLE
Moving from homestead to laradock running into problems with NPM

### ISSUE THREAD

**Issue by jschaftenaar** [laradock/laradock#408]
When running npm install in the workspace I run into this error for many packages

npm ERR! tar.unpack untar error /root/.npm/request/2.65.0/package.tgz

Things I have tried so far:
removed the ~/.npm and node modules directory and ran npm cache clean will still result in the same problem.

running tar -xvzf on the archives will untar them without incident. 
Not sure if this is specific to laradock, docker, or npm/node. Any suggestions are appreciated.

**Comment by appleboy** [comment]
@jschaftenaar Please provide your `packages.json` config.

**Comment by jschaftenaar** [comment]
this is my packages.json

`{
  "private": true,
  "scripts": {
    "build": "webpack --progress --colors --watch"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "bootstrap-sass": "^3.0.0",
    "css-loader": "^0.23.1",
    "eslint": "^2.10.1",
    "eslint-config-standard": "^5.3.1",
    "eslint-config-standard-jsx": "^1.2.0",
    "eslint-config-standard-react": "^2.4.0",
    "eslint-plugin-promise": "^1.1.0",
    "eslint-plugin-react": "^5.1.1",
    "eslint-plugin-standard": "^1.3.2",
    "gulp": "^3.9.1",
    "laravel-elixir": "^5.0.0",
    "laravel-elixir-webpack": "^1.0.1",
    "node-sass": "^3.7.0",
    "react": "^15.0.2",
    "react-dom": "^15.0.2",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "sass-loader": "^3.2.0",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.0",
    "webpack-livereload-plugin": "^0.8.1"
  },
  "dependencies": {
    "axios": "^0.11.1",
    "babel-core": "^6.8.0",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "jquery": "^2.2.4"
  }
}
`

**Comment by jschaftenaar** [comment]
Other things I have tried include the --no-bin-links option and different versions of npm and node.

**Comment by jschaftenaar** [comment]
when running the workspace as user laradock I am running into a bunch of these errors

```npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/laradock/.nvm/versions/node/v7.0.0/bin/node" "/home/laradock/.nvm/versions/node/v7.0.0/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
```

**Comment by korneliuskristianr** [comment]
I've same problem with npm

**Comment by edmundluong** [comment]
@jschaftenaar @korneliuskristianr 

You will likely run into that error when you use the `--no-bin-links` option when running `npm install` when you are trying to install a large number of dependencies. The quick and dirty way to resolve the error is simply to re-run the exact same command again: `npm install --no-bin-links`.

If you want a more "robust" solution, perhaps you can write a simple bash script that loops that command until it completes successfully:

```bash
#!/usr/bin/env bash

# Loops command until completes successfully
until npm install --no-bin-links; do npm install --no-bin-links; done;
```

It's not the prettiest solution but it works for me.

**Comment by jschaftenaar** [comment]
I switched to use yarn and all seems to be good now. npm is just a pain when working with network maps.
