### ISSUE TITLE
Supporting PostGis

### ISSUE THREAD

**Issue by joaojoyce** [laradock/laradock#410]
Is there any plan on supporting PostGis?

If not could someone give me a help on the best way to add it to laradock?

Thank you very much.

**Comment by philtrep** [comment]
@joaojoyce 

I don't believe anyone has suggested it yet. If you want to create a PR go right ahead :)

I think you will find https://hub.docker.com/r/mdillon/postgis/ relevant, it seems to be actively supported. As far as the configuration goes, something similar to the current Postgres config should do it.

You can always create an initial PR for review if you feel like your code can/should be improved.

**Comment by joaojoyce** [comment]
Thank you for your help.

I've created a Pull Request #414. 
This needs revision because I'm new to docker and making pull-requests.
