### ISSUE TITLE
Error when creating phpmyadmin

### ISSUE THREAD

**Issue by danielsdeboer** [laradock/laradock#411]
When running `docker-compose up -d mysql phpmyadmin` I get this error:

> ERROR: for phpmyadmin  Cannot create container for service phpmyadmin: Invalid volume spec "phpmyadmin": Invalid volume destination path: 'phpmyadmin' mount path must be absolute.
> ERROR: Encountered errors while bringing up the project.

Everything else builds and runs fine except for phpmyadmin.

**Comment by appleboy** [comment]
@danielsdeboer I will take this.

**Comment by korneliuskristianr** [comment]
Hi @danielsdeboer : 
```
1. Open your **laradock/docker-compose.yml** file
2. Find ### phpmyAdminContainer  ####################################
3. Change **volumes: - phpmyadmin** into **- phpmyadmin:/www/config.user.inc.php**
```

**Comment by danielsdeboer** [comment]
@korneliuskristianr Thanks, that worked great.
