### ISSUE TITLE
multiple projects setting?

### ISSUE THREAD

**Issue by lichnow** [laradock/laradock#412]
According to the documentation, we can have multiple projects with nginx but it is not clear on how to set multiple mysql or mariadb?

I use symfony3. In production env, symfony will use app.php and in dev it will use app_dev.php.

How can I edit the nginx conf  to let the symfony app decide what file (app.php or app_dev.php) will be the entry?

**Comment by Exadra37** [comment]
I believe that once proposals #424 or #425 be accepted and implemented it will help you with setting your specific needs.

**Comment by philtrep** [comment]
@lichnow Edited your issue for clarity.

For the multiple mysql, please refer to #404 for the moment.

For the moment (until @Exadra37 finishes his PR), I suggest using multiple Docker Compose files. (This)[https://github.com/laradock/laradock#prepare-laradock-for-production] should help you out getting started with multiple configurations.
