### ISSUE TITLE
404 Not Found nginx error (on MacOSX)

### ISSUE THREAD

**Issue by naretini** [laradock/laradock#413]
I followed instructions in order to configure laradock with multiple sites.

But I keep having the erro on this issue's subject.

What I find strange is the by entering my nginx container I don't find my defined *.conf files
in /etc/nginx/sites-available/
as I created them unde ../laradock/nginx/sites/*.conf
as I see on nginx/Dockerfile there's a istruction : COPY sites/*.conf /etc/nginx/sites-available/

Is this normal? Or could it be the cause? What prevents from coping the config files?

For instance if I create a laravel directory with a clean laravel install at laradock folder level. And add in docker-compose.yml the mapping
- ../laravel/:/var/www/laravel

I start seeing my laravel project : IT WORKS

BUT if a I add the second sample site included sample.conf.example -> renamed to sample.conf (contents unchanged):

### Applications Code Container #############################
    applications:
        image: tianon/true
        volumes:
            - ../laravel/:/var/www/laravel
            - ../sample/:/var/www/sample

(added 127.0.0.1 sample.dev in /etc/hosts host machine)
Inside sample i placed only a index.html file
sample.dev still displays laravel contents... NOT WORKING

I believe the problem is that it's not copying my conf files inside /etc/nginx/site-available/..

what am I missing?

**Comment by naretini** [comment]
I've found out my problem.
Since I switch from an older version of laradock to a new version today.
After setting up multiple sites for nginx container.

I was only refreshing docker's config by 

$ docker-compose down && docker-compose up -d nginx

You actually need to perform a 

$docker-compose build nginx 

too anytime you change Dockerfile under nginx folder

**Comment by philtrep** [comment]
@naretini You can also use the `--build` argument with the `docker-compose up` command.

Closing this since you figured it out :)
