### ISSUE TITLE
container for phpmyadmin service cannot be created

### ISSUE THREAD

**Issue by SamAriafar** [laradock/laradock#420]
When I try to bring up phpmyadmin, it attempts to start mysql first while mariadb is already started, so it ends to the error below:

> ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1: Bind for 0.0.0.0:3306 failed: port is already allocated

And when I stop mariadb and bring up mysql, the phpmyadmin still has error and doesn't start:

> ERROR: for phpmyadmin  Cannot create container for service phpmyadmin: Invalid volume spec "phpmyadmin": Invalid volume destination path: 'phpmyadmin' mount path must be absolute.

**Comment by jakeim** [comment]
same Issue

ERROR: Invalid volume spec "phpmyadmin": Invalid volume destination path: 'phpmyadmin' mount path must be absolute.

**Comment by BennyWang** [comment]
@jakeim @SamAriafar 
just remove 
volumes: 
        - phpmyadmin 
from docker-compose.yml

**Comment by Mahmoudz** [comment]
@BennyWang can you submit a PR fixing this? Thanks
