### ISSUE TITLE
Feature Request: add a password and shell to laradock user

### ISSUE THREAD

**Issue by tms320c** [laradock/laradock#422]
Currently IDE (PHPStorm specifically) can connect to the container as root user only (using SFTP deployment server).

It may be convenient to have an option to connect as non privileged user (i.e. laradock) using password authentication.

Now laradock user does not have neither password/key, nor the shell which leaves the only docker-compose exec option

**Comment by Exadra37** [comment]
@tms320c The proposal of using multiple docker compose files in #425 and the possibility to set config values from the Laravel `.env` file on them, as proposed in #424 will make possible to easily achieve the specific needs of each project.

**Comment by philtrep** [comment]
@tms320c sounds like a good idea. If you want to make a PR feel free to do so.

Also @LarryEitel  as the IDE connoisseur, I think this might be of interest to you.

**Comment by cjmaxik** [comment]
It would be awesome? Any changes since November?
