### ISSUE TITLE
Works with nginx but 403 no access with apache2

### ISSUE THREAD

**Issue by jschaftenaar** [laradock/laradock#423]
I might be missing a step but I thought this worked before. With a fresh install of both laravel and laradock apache2 does not seem to work out of the box. I am running into a 403 no access error. While starting up with nginx there are no issues. Any suggestions are appreciated.

**Comment by Exadra37** [comment]
Try to share any local modifications by forking this project and upload them in a branch of your fork and link it here.

Please give also print screens of the commands you run and output so that we can better understand what is going on.

**Comment by jschaftenaar** [comment]
This happens with a fresh clone of laravel and laradock. when running `docker-compose` up -d apache2 mysql` I run into a 403 but when I start the containers with `docker-compose up -d nginx mysql` the website initial laravel website loads.

**Comment by jschaftenaar** [comment]
It turned out to be a permissions issue. Not sure why it would not be accessible on Apache2 but work on nginx out of the box. I had to change the permission of the directory to 755 for directories and 644 for the .htaccess file.

**Comment by Exadra37** [comment]
Nginx does not read `.htaccess` files, therefore not failing ;)
