### ISSUE TITLE
Caddy is issuing a new SSL on each down & up

### ISSUE THREAD

**Issue by SamAriafar** [laradock/laradock#431]
It seems Caddy is requesting a new certificate from Let'sEncrypt on every down and up commands instead of using the already obtained one, so it causes reaching the issuance limitation and not coming up. There is no problem after several stop and up commands.

> caddy_1               | Activating privacy features... ... ... [...] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for exact set of domains: ...
laradock_caddy_1 exited with code 1

**Comment by francislavoie** [comment]
Add `- ./data/caddy:/root/.caddy` to your `volumes_data` service in `docker-compose.yml` and make sure the `caddy` service has 
```
        volumes_from:
            - volumes_data
```

The `/root/.caddy` directory is where the cert data is stored in the Caddy container. Making a data volume will persist that info and prevent needing to re-issue on every restart.

**Comment by tariqbilal** [comment]
I am having the same issue with Laradock release version 2.

**Comment by francislavoie** [comment]
@tariqbilal `version: '2'` is the version of the docker-compose spec, not of laradock.

@Mahmoudz it looks like `- caddy:/root/.caddy` was lost at some point... hmm...

**Comment by francislavoie** [comment]
I found the offending commit https://github.com/laradock/laradock/commit/380eef5fd954f3066ad0df6a6e613302ba0edf1a

I'll make a PR to fix this again.

**Comment by tariqbilal** [comment]
<img width="1437" alt="screen shot 2017-02-21 at 6 26 14 pm" src="https://cloud.githubusercontent.com/assets/12066559/23166693/6b915b18-f863-11e6-8218-a7c6b93f6557.png">

still persisting and I don't see any changes in master branch. Let's Encrypt documentations has a limit of 20 certificates per week. Do I have to wait then?

**Comment by francislavoie** [comment]
Yep you need to wait a week until your limit expires

**Comment by tariqbilal** [comment]
Thank you so much

**Comment by francislavoie** [comment]
You should make the same change I made in my pull request yourself for now until the change gets merged.

**Comment by tariqbilal** [comment]
I tried a couple of times, Have played around with yaml file. But unless the limit isn't over I can't test it because no matter what Caddy isn't taking on old certificates and starting up.
