### ISSUE TITLE
Confuse to parameter server name mariadb, when use mysqli_connect

### ISSUE THREAD

**Issue by bangcode082** [laradock/laradock#439]
I try to connect to the database using
```
mysqli_connect('localhost','root','root','db')
```
with the `mariadb` and `nginx` images.

I am not using a framework and the page is not working, could somebody help?

**Comment by manshoor** [comment]
First in  **php-fpm** Container

`- CODEIGNITER=true`

This will enable the mysqli extension

and rebuild your fpm container and try this.

`mysqli_connect('mysql','root','root','homestead')`

let me know if it works.

**Comment by bangcode082** [comment]
thanks a lot,, its works ^_^

**Comment by philtrep** [comment]
@manshoor Shouldn't we be making this a bit more obvious? It's not very clear that `CODEIGNITER` enables mysqli. Maybe we should have a `MYSQLI` option? What do you think?

**Comment by manshoor** [comment]
@philtrep Yes, that sounds more appropriate.
My suggestion is to install mysqli extension by default because some basic application/frameworks like codeigniter uses mysqli driver instead of pdo.
