### ISSUE TITLE
Slow startup/connection.

### ISSUE THREAD

**Issue by Stubbs** [laradock/laradock#440]
When I first started using Laradock I was a little surprised how slowly it took the containers to start, but after doing a pull of the latest head a few weeks ago everything changed and I got the speed I would expect.

However I updated to head again in the last few days and it's gone back to the old timing, at the moment startup of a simple group of containers looks like this:

```
laradock [master] time docker-compose up -d nginx postgres
Creating network "laradock_default" with the default driver
Creating laradock_applications_1
Creating laradock_postgres_1
Creating laradock_workspace_1
Creating laradock_php-fpm_1
Creating laradock_nginx_1
docker-compose up -d nginx postgres  1.86s user 0.57s system 0% cpu 7:33.58 total
```

I'm using OSX, with the beta version of native Docker, I'm not using a Vagrant VM. I have plenty of other docker containers that I run, and they spin up almost instantly.

Is this a known issue?

**Comment by philtrep** [comment]
@Stubbs I don't know about the spinning up specifically but speed is a known issue #353. I invite you to add to the existing issue.

Closing this as a duplicate.
