### ISSUE TITLE
"sshd is not running"

### ISSUE THREAD

**Issue by wasmetqall** [laradock/laradock#441]
docker-compose.yml:
```
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_YARN=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - TZ=UTC
```
When testing SFTP connection on phpstorm:
Connection to 'laravel' failed.
Session.connect: java.net.ConnectException: Connection refused: connect

After `docker exec -it 8d8d7a44d045 bash` and `service ssh status`, it returns `sshd is not running`

Then I enter `service ssh start` and it returns:
 ```
* Starting OpenBSD Secure Shell server sshd                                                                                                                                                                   key_load_public: invalid format
Could not load host key: /etc/ssh/ssh_host_rsa_key
```
Then testing SFTP connection it returns "Auth fail".

It takes me a long time to fix that, and it's somewhat driving me nuts.
Sorry for my poor English.

**Comment by philtrep** [comment]
@wasmetqall Just a shot in the dark but have you tried stopping and rebuilding the containers?
```
docker-compose down && docker-compose up --force-recreate --build -d <services>
```

**Comment by wasmetqall** [comment]
@philtrep OMG!!!!!!!!!!IT WORKS!!!!!THANK U VERY MUCH!!!!!
But how did that happen?Maybe I toggled  something?
When using `docker-compose exec workspace bash` it returns
```
 ERROR: Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose exec`.
```

May I ask a stupid question?I don't know where the mysql data stores, cause there is only `mysql:/var/lib/mysql` in docker-compose.yml, and I can't locate the so-called `mysql`:(

**Comment by philtrep** [comment]
@wasmetqall Glad it works! You can see the data stored in `laradock/data/mysql`. Those are however the actual database files so I suggest dumping the database instead if you want to keep a backup of the data.

I did not know about interactive mode not being supported, thank you for the info.

**Comment by wasmetqall** [comment]
@philtrep I still have no idea where the `laradock/data/mysql` is :( There isn't a directory called `data` under the `laradock`, but I do find there is a `logs` directory under `laradock` which stores the data from nginx. Could u please tell me more specifically? Thanks a lot!!!
