### ISSUE TITLE
Application code container not able to point from root directory.

### ISSUE THREAD

**Issue by Modelizer** [laradock/laradock#447]
Hi,
  When I mount a directory to a container I get an empty directory. Example `/Volumes/driver/www/laravel.dev/:/var/www/laravel.dev`

Note: I'm not able to figure out whether is due to I'm starting with root directory or problem is something which I'm missing.
The problem persists on Linux and Mac.

Thanks.

**Comment by vothanhliem1994it** [comment]
I have the same problem

**Comment by helbing** [comment]
I had the same problem too
```
System: windows7
docker-compose version 1.9.0, build 2585387
```
