### ISSUE TITLE
Could not connect mysql from host?

### ISSUE THREAD

**Issue by gfd6th** [laradock/laradock#449]
I just tried
`docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -p 3306:3306 -d mysql:5.7`. This command works for me. 
The command `docker-compose up -d mysql` should create a new service, I could inspect it by `docker-compose ps`, and show as below
```
     Name                    Command               State            Ports
-----------------------------------------------------------------------------------
laradock_mysql_1   docker-entrypoint.sh mysql ...   Exit 1   0.0.0.0:3306->3306/tcp
```

But I could not connect from host by `root@127.0.0.1 -p root ` or `homestead@127.0.0.1 -p secret`.
The error is 
```
Unable to connect to host 127.0.0.1, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)
```

**Comment by gfd6th** [comment]
#446 
I got the same issue on Mac.
I have tried Docker for Mac(both stable Version 1.12.3 and beta Version 1.12.3-beta30.1 ), but got the same issue

**Comment by lavenkin** [comment]
I got the same issue.
connect failure.

**Comment by philtrep** [comment]
@gfd6th Let's keep this discussion on #446.
