### ISSUE TITLE
Sqllite embedded 

### ISSUE THREAD

**Issue by pcottrell** [LaraDock/laradock#45]
For testing purposes with hello api it would be nice to have sql lite embedded into the container.

**Comment by mattythebatty** [comment]
SQLite worked fine for me in all 3 PHP versions without any modification

**Comment by pcottrell** [comment]
@mattythebatty can you elaborate?  We have to ssh into the container and install sql lite.

**Comment by mattythebatty** [comment]
Sure, here is what I did:
`laravel new sqlite-test`
`cd sqlite-test/`
`git init`
`git submodule add https://github.com/LaraDock/laradock.git docker`
`touch database/database.sqlite`

I then edited the .env file 
`DB_CONNECTION=sqlite`
and commented out `DB_DATABASE`

Then edited the routes.php to have some DB testing e.g.
```
Route::get('/', function () {
    DB::statement('CREATE TABLE IF NOT EXISTS wines (name TEXT, price INTEGER )');

    DB::insert('insert into wines (name, price) values (?, ?)', ['red', 10]);
    DB::insert('insert into wines (name, price) values (?, ?)', ['white', 15]);
    DB::insert('insert into wines (name, price) values (?, ?)', ['rose', 5]);

    $results = DB::select('select * from wines');
    print_r($results);
});
```

Then:
`cd docker/`
`docker-compose up --force-recreate --build nginx php`

In my hosts file I had `127.0.0.1 laradock.dev`

Then visited laradock.dev and got:
```
Array ( [0] => stdClass Object ( [name] => red [price] => 10 ) [1] => stdClass Object ( [name] => white [price] => 15 ) [2] => stdClass Object ( [name] => rose [price] => 5 ) )

**Comment by Mahmoudz** [comment]
SQLite is now part of the Workspace container f0e2d83618ddf1818da9279896a78d4d04ccdbcf
