### ISSUE TITLE
Add comments to sample.conf.example

### ISSUE THREAD

**Issue by milroyfraser** [laradock/laradock#450]
It will be really helpful if there are comments in `nginx/sites/sample.conf.example`. e.g. If I need to setup a domain for a vue, angular, etc. SPA I think php stuff is not needed.

Question: how to configure nginx to redirect all the requests to maybe `index.html` as mention in https://router.vuejs.org/en/essentials/history-mode.html under nginx.

**Comment by philtrep** [comment]
@milroyfraser Is there a specific reason you want to use LaraDock to serve a static site? We could definitely add comments to the nginx site config example, feel free to do a PR with the proposed additions.
