### ISSUE TITLE
fix problem for php 7 (bcmath) to work to AMQP

### ISSUE THREAD

**Issue by armandojose0009** [laradock/laradock#453]
this is for fix a problem with rabbitMQ, to fix the problem with phpamqplib bcadd() the only we can do is add list line  RUN docker-php-ext-install bcmath  in Dockerfile-70

**Comment by philtrep** [comment]
@armandojose0009 could you add your fix in a PR?

**Comment by armandojose0009** [comment]
hi  @philtrep how can do it ?? i create a branch in my git but whe try push to the repository don't have permission in the repo..

**Comment by philtrep** [comment]
@armandojose0009 follow the instructions from https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by armandojose0009** [comment]
Hi thanks you
El 21/12/2016 3:10 p. m., "Mahmoud Zalt" <notifications@github.com>
escribió:

Closed #453 <https://github.com/laradock/laradock/issues/453> via #502
<https://github.com/laradock/laradock/pull/502>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/laradock/laradock/issues/453#event-902046704>, or mute
the thread
