### ISSUE TITLE
Add a "related projects" section

### ISSUE THREAD

**Issue by philtrep** [laradock/laradock#455]
As per the discussion in #425, it could be interesting to list LaraDock related projects in the docs.

LaraDock-related projects:
* laradock-cli - https://github.com/logaretm/laradock-cli
* laradock_env - https://github.com/bagart/laradock_env

Other Docker stacks:
* magedock - https://github.com/ojhaujjwal/magedock
* rubydev-dock - https://github.com/scudelletti/rubydev-dock

This should help promote other projects as well as LaraDock.

What do you guys think?

**Comment by Mahmoudz** [comment]
Awesome let's do this :D
