### ISSUE TITLE
Installing PHP extensions without forking Laradock?

### ISSUE THREAD

**Issue by khromov** [laradock/laradock#457]
Is it possible to install a PHP extension without forking Laradock?

If not, could I suggest it being possible to override the default Laradock files with your own ones without needing to fork?

**Comment by philtrep** [comment]
@khromov I think most people clone the repo then modify the Dockerfile of the php-fpm service if they need a particular extension.

If you want to ensure you keep the same extensions everywhere, there isn't yet a way to do so using only the configuration. Personally, I have a private repo containing my own configurations/modified images that I apply on top of every LaraDock fresh clone.

If you can think of a way to have custom PHP extensions through the configuration file (`docker-compose.yml`) that would be pretty cool 😎

**Comment by khromov** [comment]
Thanks for the response. Sounds like a fork is the easiest way if you want to be up to date with changes in the main repo by merging it into the fork periodically?

**Comment by philtrep** [comment]
@khromov Yes, a fork would probably be the easiest solution.

That being said, if you think that the extension(s) that you are using could be useful to someone, I invite you to do a PR with your proposed modifications.

**Comment by LarryEitel** [comment]
I fork and then create a branch on top of that. That way I always have a convenient reference point. Just merge updated master into your branch.
