### ISSUE TITLE
Nginx default page in Docker Beta

### ISSUE THREAD

**Issue by georgebaev** [LaraDock/laradock#46]
Hi,

I built the nginx, php, mariadb and data containers but I see the "Welcome to Nginx" default page when opening the http://localhost URL in the browser. 

I use the Docker Beta software instead of the Docker Machine. Do you know what could be the problem?

**Comment by Mahmoudz** [comment]
first you need to visit the docker ip in the browser and not the localhost unless you are on linux OS.
however make sure you have a docker folder inside your laravel project.
and you have the right permissions set for some laravel folders. 
also check the laravel.conf https://github.com/LaraDock/laradock/blob/master/nginx/laravel.conf file and make sure the paths are correct.
you can try to enter the nginx container for better understanding what's going on and debug it

**Comment by annielmenezes** [comment]
Hi @Mahmoudz I get the same error. I'm using Ubuntu 16.04.

**Comment by petehouston** [comment]
@annielmenezes what is the result of `$ docker-machine env`?

**Comment by mattythebatty** [comment]
@georgebaev I get this on my Windows machine but it works fine on linux.

Could you try `docker-compose up --force-recreate --build nginx php mysql` and add an entry to your hosts file e.g.
Linux:  `127.0.0.1 laradock.dev`
Windows probably `DOCKER_IP laradock.dev`

Where DOCKER_IP is the result of 
```$ docker-machine ip```

**Comment by georgebaev** [comment]
@mattythebatty thank you very much! This fixed the problem.

**Comment by Mahmoudz** [comment]
The solution summary is: use `127.0.0.1` instead of `localhost` in your browser.
