### ISSUE TITLE
Possible documentation typo in Switch from PHP 7.0 to PHP 5.6  section

### ISSUE THREAD

**Issue by sasokovacic** [laradock/laradock#461]
Is it possible that command for rebuilding the container iz wrong? 

when I run 
$ docker-compose build php
I get following error: 
ERROR: No such service: php

If I run 
$ docker-compose build php-fpm
everything works ok...

is this ok or did I miss something?

thanks

**Comment by philtrep** [comment]
No, `php-fpm` is the right name for the container. If you take a look at the `docker-compose.yml` file, you can see that the service is called `php-fpm`.
