### ISSUE TITLE
Datetime in container is not synced

### ISSUE THREAD

**Issue by dcnl1980** [laradock/laradock#462]
I notice that the datetime in the container is not syncing with any time server around the world en is not accepting to do this. My local time on the host is Dec 1 14:00, while the docker container shows It is Nov 30 22:06. Also an NTP server installation or ntpdate is not working within the container, also change the timezone with tzdata is not helping. Does more people have the same problem?

**Comment by philtrep** [comment]
@dcnl1980 To change the timezone you can follow https://github.com/laradock/laradock/blob/master/README.md#Change-the-timezone .

The drift seems to be a known issue http://stackoverflow.com/a/38133871/1830104 .

According to the previous link, you'll have to access the Docker for Mac VM TTY then sync with a ntp server.

If this helps you out we'll add the info in the docs.

**Comment by pangminfu** [comment]
I have the exactly same issue change the timezone doesn't solve the issue

**Comment by philtrep** [comment]
@pangminfu try following the instructions in the SO link I posted above

**Comment by philtrep** [comment]
@dcnl1980 @pangminfu did you ever manage to make this work? If this fixes your issue Ill add it to our docs

**Comment by dcnl1980** [comment]
@philtrep To fix the timezone in the container, I did the following:

- changing the timezone (in the above link) in docker-compose.yml
- stop and rebuild the container (docker-compose up -d)
