### ISSUE TITLE
PHPSTORM can not edit file in public directory

### ISSUE THREAD

**Issue by lechengyu** [laradock/laradock#463]
![image](https://cloud.githubusercontent.com/assets/17262681/20799037/eecab052-b81b-11e6-86c9-39a1f6f7da3a.png)

Like #113 
Running Windows native Beta.

When the nginx container is running , the first time I edit index.php file, it works fine. But after that everytime I edit it ,  it fails and has no effect. I try to run PHPSTORM as admin, the problem remains.

However I use VSCODE to edit the index.php file,there is no problem.

**Comment by bagart** [comment]
As I think - os problem of windows docker :(
I get this bug too with php and js (with direct access by nginx)

**Comment by philtrep** [comment]
@lechengyu @bagart please follow the instructions in https://github.com/laradock/laradock/issues/113#issuecomment-265506361
