### ISSUE TITLE
How about change docker-compose.yml into docker-compose.yml.example

### ISSUE THREAD

**Issue by nickfan** [laradock/laradock#465]
if i use laradock with my develop Environment and my each project have to tweak docker-compose.yml anyway.
so why not change docker-compose.yml into docker-compose.yml.example and in the document guide user to copy and tweak the docker-compose.yml by each project context.

**Comment by philtrep** [comment]
@nickfan This is something we had previously discussed and decided against. The reason being that we want to make the initial setup as easy as possible for new users.

I personally keep my own repository with a `docker-compose.yml` file for my specific needs but if you can think of a better solution feel free to share it. 😃
