### ISSUE TITLE
Cannot access corporate proxy inside laradock container

### ISSUE THREAD

**Issue by tblancog** [laradock/laradock#467]
Hello, 
I have a simple laradock setup container with nginx and mysql.
I'm having an issue trying to access a corporate proxy inside my app.
If I ping outside docker it just works.
But inside nginx container don't:
```
ping my-company.corp.net
ping: bad address 'my-company.corp.net'
```
and when i run my php app which makes curl requests it shows:
`Could not resolve proxy: my-company.corp.net` 

How can i configure the container so it resolves the given proxy DNS?

 Thanks in advance.

**Comment by geekstek** [comment]
How can you fix it? I had the same error
