### ISSUE TITLE
How to execute node code in workplace on startup

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#469]
Now that I have node (and associated tools npm and yarn).  How do I configure `docker-compose.yml` to execute code when the container is started.

Typically, i would do this in a `Dockerfile` for the associated container, but since not using `Dockerfile` (above) assuming I configure in workplace section of `docker-compose.yml` file

**Comment by mikeerickson** [comment]
@philtrep One thing that is curious to me.   Why does node get installed with workspace, as opposed to its own container?

**Comment by philtrep** [comment]
@mikeerickson I believe it was the simplest option at the time it was implemented. This was actually discussed in #398. If you think this would be a good feature you should definitely make a PR for it.
