### ISSUE TITLE
Gulp command not found in Workspace

### ISSUE THREAD

**Issue by suncoastkid** [laradock/laradock#470]
Using `sudo docker-compose exec --user=laradock workspace bash` and unable to run gulp:

> bash: gulp: command not found

**Comment by philtrep** [comment]
@suncoastkid are you able to use `nvm` and `npm`?

**Comment by suncoastkid** [comment]
No, npm or nvm commands not found either.

**Comment by philtrep** [comment]
@suncoastkid have you followed https://github.com/laradock/laradock#install-node--nvm ?

If you have, then make sure you have
```
export NVM_DIR=/home/laradock/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; 
```
in the `~/.bashrc` file.

If you do not see the code above, I would remove and rebuild the workspace container.

These instructions shouldve been added to the bashrc when the container was built https://github.com/laradock/laradock/blob/master/workspace/Dockerfile#L169

**Comment by suncoastkid** [comment]
After doing a rebuild, npm is working but I'm getting:

> Local gulp not found in /var/www try running:npm install gulp

Is this the expected behavior?

**Comment by philtrep** [comment]
@suncoastkid Glad it works.
