### ISSUE TITLE
Problems running phpunit on workspace with user laradock

### ISSUE THREAD

**Issue by TiagoDamascena** [laradock/laradock#471]
I'm tryint to run `docker-compose run -u laradock workspace phpunit` but getting this error:
`ERROR: Cannot start service workspace: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"phpunit\\\": executable file not found in $PATH\"\n"`

If i use `docker-compose run -u laradock workspace bash` an then `phpunit` it works.
`docker-compose run workspace phpunit` works to.

**Comment by nbicalcarata** [comment]
I'm having the same problem, and i have a question, there is any side effect running the command like this?
`docker exec -it --user=laradock laradock_workspace_1 ./vendor/bin/phpunit`
