### ISSUE TITLE
no such file or directory starting workspace container on a new project

### ISSUE THREAD

**Issue by dilone** [laradock/laradock#473]
i'm getting this error with the most recent version of **Laradock** 

`ERROR: for workspace  Cannot start service workspace: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/var/www/laravel\\\") set in config.json failed: no such file or directory\"\n"
ERROR: Encountered errors while bringing up the project.
`
im using Fedora 24 and i tested with my fork of a older **Laradock** version and it works fine.

**Comment by mikeerickson** [comment]
@dilone Where are you seeing this error?  What is the exact command when you see this?  

I have seen this error as well, but in my case, the cmd sent to `exec` was incorrect

**Comment by helbing** [comment]
I also had this problem, and now I solved it. You should use `docker-machine` first, and then execute `docker-compose -up -d mysql nginx`

**Comment by philtrep** [comment]
@dilone It seems like you are using an older version of the `docker compose` config. Try deleting your containers/images/volumes and re-upping everything with an updated `docker compose` config and you should be golden!

@helbing Docker-Machine is no longer supported in the default branch, Docker native should be working on all platforms now.

Ill reopen this issue if the problem persists.
