### ISSUE TITLE
laradock super slow migrations and seeding with docker 1.13 and Macosx sierra

### ISSUE THREAD

**Issue by naretini** [laradock/laradock#475]
I have the same project running on Yosemite osx + docker 1.12 + laradock.
Running inside the workspace:
 php artisan migrate--seed

It takes less than 50"

Running the same command under Macosx sierra with docher 1.13 + laradock  I experience 
slowness. It takes minutes to complete.

I tryed to augment RAM for Docker native or adding directives in mysql my.cnf 
But no relvant improvement...always very slow.

How can I fix this? 
Someone else with same problem?

**Comment by philtrep** [comment]
@naretini Slowness is a known concern #353. Try increasing the cpu count https://docs.docker.com/docker-for-mac/#/preferences
