### ISSUE TITLE
Can't enter phpmyadmin container

### ISSUE THREAD

**Issue by gentcys** [laradock/laradock#480]
While i input `sudo docker-compose exec phpmyadmin bash`,
an error occurred:
`rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: startin│ 58         expose:
g container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n"`

**Comment by indapublic** [comment]
+1

**Comment by zeroc0d3** [comment]
You need to enter by "ash"
* Check your container name & id for phpmyadmin
```
docker ps
```
* Login into your container phpmyadmin
```
docker exec -it [container_id] busybox ash
```

**Comment by zeroc0d3** [comment]
* Find your "mysql" container IP (after "dockker ps")
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' [container_id]
```

* Test on your terminal
```
mysql -uroot -h[container_ip] -p
```
by default:
username = **root**
password = **root**

* Login by phpmyadmin
```
http://[container_ip]
server: [container_ip]
username: root
password: root
```

**Comment by zeroc0d3** [comment]
@Mahmoudz, we can closed this as solved "bug fixed"
