### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by ZaffJa** [laradock/laradock#481]
I've already enable the zip instance in php-fpm but still laravel would throw me this error.

I was trying to upload a csv file using package "phpoffice/phpexcel": "^1.8". 

![image](https://cloud.githubusercontent.com/assets/12205174/21144117/732ccdd2-c184-11e6-9249-500aa90f61ee.png)

**Comment by pabloalbrecht** [comment]
Same problem !

**Comment by zhenfdfs** [comment]
After i set INSTALL_ZIP_ARCHIVE = true, then rebuild php-fpm. I encounter a problem 
Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_ZIP_ARCHIVE} = true ]; then     pecl install zip &&     docker-php-ext-enable zip ;fi' returned a non-zero code: 1

**Comment by ZaffJa** [comment]
I solved my problem by requiring this package https://packagist.org/packages/league/flysystem-ziparchive

**Comment by philtrep** [comment]
@ZaffJa could you add this to our documentation?

**Comment by kamrava** [comment]
Same here :(

**Comment by kamrava** [comment]
@ZaffJa  Please tell me how did you solve the problen? I required [https://packagist.org/packages/league/flysystem-ziparchive](https://packagist.org/packages/league/flysystem-ziparchive).
But nothing changed! Same error :(

**Comment by camiant** [comment]
in .env file set:
`INSTALL_ZIP_ARCHIVE = true`

then in your terminal:
`docker-compose build --no-cache php-fpm`
to rebuild your php-fpm with zip extension

restart your whole laradock environment

here you go!

**Comment by mystique123** [comment]
Hi all,

I am also having this problem and have tried the above solution as follows:

I have set:
`PHP_FPM_INSTALL_ZIP_ARCHIVE=true`
in my .env file

I have included:
`"require": {
        "league/flysystem-ziparchive": "^1.0"
    }`
in my composer.json file and updated composer

And I have run:
`docker-compose build --no-cache php-fpm`
in my terminal to rebuild your php-fpm with zip extension

However I still get the error. Have I done everything correctly?

Thanks :-)

**Comment by mgralikowski** [comment]
same..

**Comment by jaredchu** [comment]
@mystique123 you need to restart laradock environment
`docker-compose down`
and then:
`docker-compose up -d mysql nginx`

**Comment by ZR87** [comment]
hey, had the same error with laradok v6.0.0
There was no `INSTALL_ZIP_ARCHIVE` in my `.env` file as described by @camiant , only `PHP_FPM_INSTALL_ZIP_ARCHIVE=true` which had no effect.

I ended up setting  `ARG INSTALL_ZIP_ARCHIVE=true` under `php-fpm/Dockerfile-72` and rebuilded ofc :)
