### ISSUE TITLE
Idea: Add option to install Google's V8 Javascript Engine PHP extension

### ISSUE THREAD

**Issue by edmundluong** [laradock/laradock#482]
Hi,

I came across [this ReactJS package](https://github.com/talyssonoc/react-laravel) I would like to use with Laravel and Laradock, however, it has an indirect dependency on v8js. 

I thought it might be useful for some users if there was an option to install the [Google's V8 Javascript Engine PHP extension (v8js)](https://github.com/phpv8/v8js). 

If there is some support for this, I do not mind submitting a pull request. Thanks.

**Comment by philtrep** [comment]
Fixed by #483. Good job @edmundluong 😸
