### ISSUE TITLE
 Cannot create container for service volumes_data

### ISSUE THREAD

**Issue by sudden-break** [laradock/laradock#497]
```
? docker-compose up -d  nginx mysql
Creating laradock_volumes_source_1
Creating laradock_volumes_data_1
```

```
ERROR: for volumes_data  Cannot create container for service volumes_data: creat
e \var\lib\postgres: "\\var\\lib\\postgres" includes invalid characters for a lo
cal volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

ERROR: for volumes_source  Cannot create container for service volumes_source: I
nvalid bind mount spec "C:\\Users\\Public\\Tools:/var/www/laravel:rw": Invalid v
olume specification: 'C:\Users\Public\Tools:/var/www/laravel:rw'
←[31mERROR←[0m: Encountered errors while bringing up the project.
```

**Comment by derekwebb** [comment]
Any traction on this at all? I am fairly new to Docker still... However, I have a feeling this issue affects (a great many) Windoze users (those of us that didn't end up lucky) I have been hitting my head against this now for a full day... At the moment I am using just a docker-compose.yml file that reads like so:

# Drupal with MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '2'

services:

  drupal:
    image: drupal:7.53-apache
    ports:
      - 8080:80
    volumes:
        - './:/tmp:ro'
    restart: always
    env_file: ./.env

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always

I have tried lots of different configurations... Ultimately I really just want to be able to share my Drupal codebase with the container... Any assistance is greatly appreciated!

I have a .env file that contains: COMPOSE_CONVERT_WINDOWS_PATHS = 1

And a test text file, test.txt in the same root folder as docker-compose.yml... What might I be missing? Thanks!

**Comment by Marooned-MB** [comment]
I gave up. I assumed that docker is not working on Windows.

**Comment by SorenJ89** [comment]
following this guide: http://containertutorials.com/docker-compose/flask-compose.html i have run into the same problem.
as suggested here https://github.com/laradock/laradock/issues/508 i created an .env file (something.env) with COMPOSE_CONVERT_WINDOWS_PATHS=1

However i still get the message 

> $ docker-compose up
> Creating flaskcomposesample_web_1
> 
> ERROR: for web  Cannot create container for service web: invalid bind mount spec "C:\\Users\\Soren Jensen\\Desktop\\flask_compose_sample:/code:rw": invalid volume specification: 'C:\Users\Soren Jensen\Desktop\flask_compose_sample:/code:rw'
> [31mERROR[0m: Encountered errors while bringing up the project.

**Comment by IvanCaceres** [comment]
i found that if you run the docker-compose command with the following variable set, it will fix the path for windows:

COMPOSE_CONVERT_WINDOWS_PATHS=1 docker-compose up -d


setting this variable only works in bash like environments howerver, i resorted to using the git bash terminal instead of my usual Cmder
