### ISSUE TITLE
Problem in windows when i excute "docker-compose exec -d workspace bash"

### ISSUE THREAD

**Issue by alixez** [laradock/laradock#503]
# the system is window10 
if i excute "docker-compose exec workspace bash"  
I get the error "Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose exec`".
But if i excute "docker-compose exec -d workspace bash"
I get a timeout error
 "An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60)."

**Comment by omitobi** [comment]
Have you tried `docker exec -it {workspace-container-id} bash`. I had a problem running that command although my issue was different from yours it worked

**Comment by springjk** [comment]
update your docker version, `docker-compose exec workspace bash` will be work.
