### ISSUE TITLE
Cannot create container for service applications: Invalid mount spec

### ISSUE THREAD

**Issue by vertisan** [laradock/laradock#508]
Hi,
I trying to start Laradoc on Docker Toolbox but on `docker-compose up -d  nginx mysql` I'm getting error:
`
ERROR: for applications  Cannot create container for service applications: Invalid bind mount spec "P:\\xampp\\htdocs\\____LaravelTesty\\docker-laravel:/var/www:rw": Invalid volume specification: 'P:\xampp\htdocs\____LaravelTesty\docker-laravel:/var/www:rw'
ERROR: Encountered errors while bringing up the project.
`
Where is the problem?

**Comment by bigblueeio** [comment]
Hi,

place a .env file next to your docker-compose.yml file, with the  following content :  COMPOSE_CONVERT_WINDOWS_PATHS=1

That should do the trick.

**Comment by pakistanihaider** [comment]
@bigblueeio 
Many Thanks. The ".env" method worked.
I guess there is no better documentation for windows :(

**Comment by edmundluong** [comment]
+1 had a developer run into this problem, the .env fix solved this problem. Potential candidate for PR? @philtrep

**Comment by philtrep** [comment]
@edmundluong yes

**Comment by edmundluong** [comment]
@philtrep I would imagine this would involve removing the .env from the .gitignore file? Thoughts? I don't mind submitting a PR if it's fine to modify the .gitignore

**Comment by philtrep** [comment]
@edmundluong That would appear to be the simplest solution, you can definitely do a PR for it.

**Comment by SorenJ89** [comment]
*moving my comment to here as it fits better the error type
following this guide: http://containertutorials.com/docker-compose/flask-compose.html i have run into the same problem.
as suggested here i created an .env file (something.env) with COMPOSE_CONVERT_WINDOWS_PATHS=1

However i still get the message

$ docker-compose up
Creating flaskcomposesample_web_1

> ERROR: for web Cannot create container for service web: invalid bind mount spec "C:\Users\Soren Jensen\Desktop\flask_compose_sample:/code:rw": invalid volume specification: 'C:\Users\Soren Jensen\Desktop\flask_compose_sample:/code:rw'
> �[31mERROR�[0m: Encountered errors while bringing up the project.

**Comment by ProfDecodor** [comment]
is your file really names "something.env" ?
As far as I know, the file must be named ".env", nothing before the dot.

**Comment by SorenJ89** [comment]
That was indeed the problem. Thanks a bunch!

**Comment by frops** [comment]
@ProfDecodor Thank you. Method with .env file work! Well done

**Comment by tmndungu** [comment]
Hi,

I have added the .env file and still getting the following error, please assist.

PS C:\Projects\DOCKER\ELK> docker-compose up
Creating elk_elasticsearch_1 ...
Creating elk_elasticsearch_1 ... error

ERROR: for elk_elasticsearch_1  Cannot create container for service elasticsearch: invalid bind mount spec "/c/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:C:/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:rw": invalid volume specification: '/c/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:C:/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:rw'

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid bind mount spec "/c/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:C:/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:rw": invalid volume specification: '/c/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:C:/Projects/DOCKER/ELK/elasticsearch/config/elasticsearch.yml:rw'
ERROR: Encountered errors while bringing up the project.
PS C:\Projects\DOCKER\ELK>

**Comment by itoonx** [comment]
i'm getting error same above :(

**Comment by mludi** [comment]
Is there any workaround? I've the same issue, `.env ` - file didn't work for me on Windows 10

**Comment by jsheehan61** [comment]
Cannot create container for service web: invalid volume specification: '/c/My Work Stuff/Docker/containers/django:/code:rw' happens after I create the .env file

It was Cannot create container for service web: invalid volume specification: 'C:\My Work Stuff\Docker\containers\django:/code:rw'

Did anyone ever fix this? The Docker Django tutorial leads you to this error, someone must have figured it out

**Comment by Nereg** [comment]
Yeah same error. Tryed it with .env but nothing changed. Windows 10

**Comment by vikash-sharma-php** [comment]
> Hi,
> 
> place a .env file next to your docker-compose.yml file, with the following content : COMPOSE_CONVERT_WINDOWS_PATHS=1
> 
> That should do the trick.

Worked for windows 8.1
