### ISSUE TITLE
ERROR: for application  argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by M0on75e1l** [LaraDock/laradock#51]
I have an error described in https://github.com/docker/compose/issues/3451

Here is what I was trying to do:

```
$ docker-compose up -d nginx mysql redis workspace
Starting laradock_data_1
Starting laradock_application_1

ERROR: for application  argument of type 'NoneType' is not iterable

ERROR: for data  argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 57, in main
  File "compose/cli/main.py", line 108, in perform_command
  File "compose/cli/main.py", line 728, in up
  File "compose/project.py", line 395, in up
  File "compose/parallel.py", line 60, in parallel_execute
TypeError: argument of type 'NoneType' is not iterable
docker-compose returned -1
```

Any suggestions?

**Comment by Mahmoudz** [comment]
I wasn't able to reproduce that
However try doing these steps:
1. Pull the latest version: `git pull origin master` now it's `2.2.1`
2 . Remove the workspace images and any `<none>` images with `docker rmi {container-id}`
3 . Rebuild the containers `docker-compose build --no-cache nginx mysql redis` (note there's no need to run the workspace now, it will automatically run)
4 . Try again..

**Comment by M0on75e1l** [comment]
I just had to update docker-engine to the latest version which is unsupported in Fedora 21. So I had to upgrade my Fedora to version 23, and that led me to almost ten hours of struggle with unsupported video card drivers. But now it's working. 

Just one last question since I don't want to create another issue: 
I did everything as described in manual, and installed the project in `workspace` container, but when I visit `http://localhost` I see nginx welcome page.

I prefer not to use docker-machine, so shouldn't it work with just `localhost`?
Or what is causing the problem?

Thanks.

**Comment by Mahmoudz** [comment]
@M0on75e1l I think your error is discussed here #46 and was solved by `mattythebatty` check it and let me know if it fixes yours.

**Comment by M0on75e1l** [comment]
@Mahmoudz almost. 

After that I also had to do `composer install` and `php artisan key:generate` in the root of my project in workspace container.

Now it works.

One note. Consider updating manual [here](https://github.com/LaraDock/laradock#view-the-log-files):
`The Nginx Log file is stored in the logs/nginx directory.`

[That's not the truth by default](https://github.com/LaraDock/laradock/blob/master/nginx/nginx.conf#L21) and can be confusing.

**Comment by Mahmoudz** [comment]
@M0on75e1l done
