### ISSUE TITLE
Making LaraDock work with Wordpress 

### ISSUE THREAD

**Issue by cesarhgd10** [laradock/laradock#514]
Hi, I'm new to Docker and I was wondering if someone could give some tips on how to run Wordpress with Laradock

Thanks in advance

**Comment by manshoor** [comment]
well that's simple just follow the video instructions and place your wordpress dir in public folder.

**Comment by cesarhgd10** [comment]
Wow, i changed the nginx root, but that didn't work out very well. Always when i try to install, i get the white screen of death in the second step

**Comment by abtrumpet** [comment]
You have to change the nginx root and set the proper mysql variables.
On a side note, this could be an additional feature. I'll take a look at adding this into laradock.

**Comment by cesarhgd10** [comment]
That's is my actual problem... i can't put the MySQL variables... I tried to put the same as another docker I was using but until now no luck

**Comment by cesarhgd10** [comment]
i'm using the default ones now... I saw the error log in nginx: 

```
2016/12/30 22:04:39 [error] 9#9: *79 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/public/wp-includes/wp-db.php:1570
Stack trace:
#0 /var/www/public/wp-admin/setup-config.php(274): wpdb->db_connect()
#1 {main}
  thrown in /var/www/public/wp-includes/wp-db.php on line 1570" while reading response header from upstream, client: 172.18.0.1, server: laradock, request: "POST /wp-admin/setup-config.php?step=2 HTTP/1.1", upstream: "fastcgi://172.18.0.5:9000", host: "localhost", referrer: "http://localhost/wp-admin/setup-config.php?step=1"

```
Always in the step 2 I get  _HTTP ERROR 500_

**Comment by manshoor** [comment]
@cesarhgd10 first of all 500 is a sever side error 

make sure your directory mappings are correct and you have a nginx like this https://github.com/laradock/laradock/blob/master/nginx/sites/sample.conf.example


so in my docker compose 


    applications:

        image: tianon/true

        volumes:

           - ../WordpressDev/:/var/www/wordpressdev


And my Nginx is 


    server_name wordpress-dev.local

    root /var/www/wordpressdev

**Comment by wsung** [comment]
Hi, I'm new here and I had the same problem with mysql_connect. But it seems, that I get it running.

The error message says, that mysql_connect is missing. If you are using php 7, mysql_connect is removed in this version. You should use mysqli instead of mysql. But mysqli is not enabled on default. 

See: https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile-70
and: https://github.com/laradock/php-fpm/blob/master/Dockerfile-70

There is only on place mysqli ist enabled:
####################################
# Codeigniter Modifications:
#####################################

ARG CODEIGNITER=false
RUN if [ ${CODEIGNITER} = true ]; then \
    # Install Codeigniter PHP extentions requirements
     docker-php-ext-install mysqli && \
     docker-php-ext-install tokenizer \
;fi

I set CODEIGNITER to true. 

Well, I'm new in Docker and Laradock. So please correct me, if there is something wrong.

**Comment by cesarhgd10** [comment]
@manshoor , I followed your steps, but still in the step 2 of the installation I get HTTP 500 error

**nginx/sites/default.conf**

```
server_name laradock;
 root /var/www/wordpressdev;
 index index.php index.html index.htm;
```

**docker-compose.yml**

 `- ../wordpressdev:/var/www/wordpressdev
`

**My file structure is:**

```
project/
    laradock/
    wordpressdev/
```

**Comment by wsung** [comment]
My configuration looks like yours except one line:

root /var/www/wordpressdev/web;

**Comment by cesarhgd10** [comment]
@wsung  But how is your folder structure ?
The strange part is that, the first's steps of the Wordpress installation run normally, but in the step 2 i get error 500, maybe is something to do with the database ? Like pointed in the log

**Comment by mikeerickson** [comment]
Perhaps since this is "Laradock" supporting outside of Laravel might not be the best direction.  I am guessing there are some quality projects which supports WP?

**Comment by philtrep** [comment]
@mikeerickson Supporting other frameworks was discussed in #76. You can definitely open a new issue to argue that position.

**Comment by wsung** [comment]
Sorry! My path is wrong for you. Because I'm using roots/bedrock, so my root-folder is under web. 

There is something in your error, that is different to my configuration.

your DB_HOST=localhost

my DB_HOST=mysql  

Like in the Quick Overview from laradock readme.

**Comment by cesarhgd10** [comment]
Hi guys, i managed to get it working, all i had to do was set the Codeigniter flag to **true** in the docker-compose.yml and change the root of nginx/sites/default.conf to `/var/www;`

**Comment by shouhuori** [comment]
In .env file set  
`PHP_FPM_INSTALL_MYSQLI=true`
