### ISSUE TITLE
Cannot build php-fpm

### ISSUE THREAD

**Issue by gabfiocchi** [laradock/laradock#516]
When try run `docker-compose up` or `docker-compose up nginx mysql redis` with some parameter the result it's same. I have this error..
`Building php-fpm`
`ERROR: Unknown instruction: DOCKER-PHP-EXT-INSTALL`

And can't fixed this. Any idea?

**Comment by alexweb** [comment]
+1 Same issue

**Comment by springjk** [comment]
This problem is laradock docker image need to update.

```
docker-compose pull
docker-compose build --no--cache
```

**Comment by alexweb** [comment]
Nope, didn't help.
After updating and executing `docker-compose build --no-cache`
there is an error: `Unknown instruction: DOCKER-PHP-EXT-INSTALL`

**Comment by alexweb** [comment]
Here is the latest lines from log:
`
Removing intermediate container 5972a30904db
Step 56/71 : RUN if [ ${INSTALL_AEROSPIKE_EXTENSION} = false ]; then     rm /etc/php/7.0/cli/conf.d/aerospike.ini ;fi
 ---> Running in edaddb812af3
 ---> ce9aa3e36066
Removing intermediate container edaddb812af3
Step 57/71 : USER root
 ---> Running in 227e104e9897
 ---> 92df6c5e7d28
Removing intermediate container 227e104e9897
Step 58/71 : ARG INSTALL_V8JS_EXTENSION=false
 ---> Running in b7ef71531d79
 ---> 9fba64f2b493
Removing intermediate container b7ef71531d79
Step 59/71 : ENV INSTALL_V8JS_EXTENSION ${INSTALL_V8JS_EXTENSION}
 ---> Running in b2372855b5bb
 ---> 4850a0e3796e
Removing intermediate container b2372855b5bb
Step 60/71 : RUN if [ ${INSTALL_V8JS_EXTENSION} = true ]; then     add-apt-repository -y ppa:pinepain/libv8-5.4     && apt-get update     && apt-get install -y php-dev php-pear libv8-5.4     && pecl install v8js     && echo "extension=v8js.so" >> /etc/php/7.0/cli/php.ini ;fi
 ---> Running in eb0b8d4770c0
 ---> f7d9eb46dc95
Removing intermediate container eb0b8d4770c0
Step 61/71 : USER laradock
 ---> Running in b6713b030c35
 ---> 882127330220
Removing intermediate container b6713b030c35
Step 62/71 : RUN echo "" >> ~/.bashrc &&     echo 'export PATH="/var/www/vendor/bin:$PATH"' >> ~/.bashrc
 ---> Running in 10836598fbb7
 ---> e5bbabcbf4b3
Removing intermediate container 10836598fbb7
Step 63/71 : USER root
 ---> Running in c28730c3fa2d
 ---> 52853673d158
Removing intermediate container c28730c3fa2d
Step 64/71 : RUN echo "" >> ~/.bashrc &&     echo 'alias art="php artisan"' >> ~/.bashrc
 ---> Running in 9a533fbf13d4
 ---> fe0f12c4d772
Removing intermediate container 9a533fbf13d4
Step 65/71 : USER laradock
 ---> Running in d3f57598558a
 ---> 31fac7bb78c5
Removing intermediate container d3f57598558a
Step 66/71 : ARG INSTALL_LARAVEL_ENVOY=true
 ---> Running in 2f859890bf0a
 ---> 3d78f787d92f
Removing intermediate container 2f859890bf0a
Step 67/71 : ENV INSTALL_LARAVEL_ENVOY ${INSTALL_LARAVEL_ENVOY}
 ---> Running in f3343ec64ee6
 ---> 816bcb47d309
Removing intermediate container f3343ec64ee6
Step 68/71 : RUN if [ ${INSTALL_LARAVEL_ENVOY} = true ]; then     echo "" >> ~/.bashrc &&     echo 'export PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc     && composer global require "laravel/envoy=~1.0" ;fi
 ---> Running in 42a05a8d4a89
 ---> e486ae534155
Removing intermediate container 42a05a8d4a89
Step 69/71 : USER root
 ---> Running in 55361bbf9f68
 ---> da74fe2826fe
Removing intermediate container 55361bbf9f68
Step 70/71 : RUN apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in 7d0b31de191e
 ---> 86cb86940fba
Removing intermediate container 7d0b31de191e
Step 71/71 : WORKDIR /var/www
 ---> 1322108cdad2
Removing intermediate container 78b4afc65c03
Successfully built 1322108cdad2
Building php-fpm
ERROR: Unknown instruction: DOCKER-PHP-EXT-INSTALL
`

**Comment by springjk** [comment]
` docker images | grep "laradock/"`

```
laradock/workspace                                             1.2                 c486cc00e710        7 weeks ago         707 MB
laradock/php-fpm                                               7.0--1.2            ee574fa56381        4 months ago        410 MB
laradock/php-fpm                                               5.6--1.2            c5d737fd42b0        4 months ago        397 MB
laradock/workspace                                             1.1                 a3f8d1f74013        4 months ago        696 MB
laradock/php-fpm                                               7.0--1.1            0a29c8c254a6        4 months ago        410 MB
laradock/workspace                                             1.0                 fa59baa68a65        5 months ago        694 MB
```

`docker pull laradock/php-fpm 7.0--1.2`

**Comment by alexweb** [comment]
`docker images | grep "laradock/"`
returns:
`laradock/workspace          1.3                 4973a22e69b6        7 days ago          709 MB`

 `docker pull laradock/php-fpm 7.0--1.2`
returns:
`"docker pull" requires exactly 1 argument(s).
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry`

**Comment by springjk** [comment]
`docker pull laradock/php-fpm:7.0--1.2`

i can sure it will be work.

**Comment by alexweb** [comment]
laradock/php-fpm was updated, however `docker-compose up -d nginx mysql redis` and `docker-compose build --no-cache` still returns same error.

**Comment by springjk** [comment]
A few days ago I also encountered this problem and solved, but I think I missed what step, I have to look back and determine the correct and then back to you later.

**Comment by alexweb** [comment]
Ok, thanks for help!

**Comment by springjk** [comment]
`docker rmi laradock/php-fpm:7.0--1.2`

`docker-compose build --pull php-fpm`

```
Building php-fpm
ERROR: Unknown instruction: DOCKER-PHP-EXT-INSTALL
```

In there, i think it's a cache problem, i has been delete `laradock/php-fpm:7.0--1.2`, but it still returns "Unknown instruction", so i modify file `/laradock/php-fpm/Dockerfile-70` ***line 13*** to `FROM laradock/php-fpm:7.0--1.2s`, and i exec this:

`docker-compose build --pull php-fpm`

```
Building php-fpm
Step 1/31 : FROM laradock/php-fpm:7.0--1.2s
^CERROR: Aborting.
```

`laradock/php-fpm:7.0--1.2s` is a wrong image tag, so this is expected results，then i modify `laradock/php-fpm:7.0--1.2s` back to `laradock/php-fpm:7.0--1.2` and exec this:


`docker-compose build --pull php-fpm`

```
Building php-fpm
Step 1/31 : FROM laradock/php-fpm:7.0--1.2
```

it work for me, and now i can't reproduce the bug, please try it.

if it still return error, try remove your all images or reset your docker, i think it is a finally way.

**Comment by alexweb** [comment]
When I i modified file `/laradock/php-fpm/Dockerfile-70` line 13 to `FROM laradock/php-fpm:7.0--1.2s` I got the same error when run `docker-compose build --pull php-fpm`:

`>docker-compose build --pull php-fpm`
Building php-fpm
ERROR: Unknown instruction: DOCKER-PHP-EXT-INSTALL

And it didn't download anything.

**Comment by alexweb** [comment]
You said that laradock image need to update. But first time I installed it was 28 of Dec. Shouldn't it be already up to date? I think I if I remove all my images and reinstall it I'll got the same state as i had 28 of Dec.

**Comment by springjk** [comment]
Yesterday,i used a new win10 pc to first install laradock, it is worked; And i found this error when my mac update laradock version, after updated laradock images, it has been fixed.

please show me `docker images | grep "laradock/"` return.

**Comment by alexweb** [comment]
`>docker images | grep "laradock/"`
`laradock/workspace          1.3                 4973a22e69b6        8 days ago          709 MB`

**Comment by springjk** [comment]
you miss `laradock/php-fpm`

exec `docker pull laradock/php-fpm:7.0--1.2`, and make sure it's done.

**Comment by alexweb** [comment]
Done. Now it's:
`>docker images | grep "laradock/"`
laradock/workspace          1.3                 4973a22e69b6        8 days ago          709 MB
laradock/php-fpm            7.0--1.2            ee574fa56381        4 months ago        410 MB

**Comment by springjk** [comment]
`docker-compose build --no-cache php-fpm `

**Comment by alexweb** [comment]
`docker-compose build --no-cache php-fpm`
Building php-fpm
ERROR: Unknown instruction: DOCKER-PHP-EXT-INSTALL

**Comment by springjk** [comment]
😢 Ok, maybe my way no use to you, maybye you can try modified php-fpm dockerfile again.

Finally if you have no idea , try reset docker and update docker/docker-compose version, sorry for can't help you.

**Comment by alexweb** [comment]
Yep, thank you for help!

**Comment by danielhomer** [comment]
Any luck with this @alexweb? I'm getting the same issue as you.

I've also tried deleting all of my Docker images and rebuilding, still no dice.

**Comment by alexweb** [comment]
Nope. Don't know how to fix this

**Comment by danielhomer** [comment]
Ok, I've just got it working, although I'm still not sure on the exact cause, what I did:

1) `git checkout f82d3b30b483abdac72b0554ff7d72218c45fa34`
2) `docker-compose up -d nginx mysql redis` (this should build now)
3) `docker-compose stop`
4) `git checkout master`
5) `docker-compose up -d nginx mysql redis`

Someone with a bit more knowledge can probably understand why this works, it might be running an old image now, I don't know, but it starts :)

**Comment by alexweb** [comment]
It works! Thanks!

**Comment by alexweb** [comment]
And one more question (not related to the issue):
Can't login to workspace:
 `> docker-compose exec workspace bash
ERROR: No container found for workspace_1`
Any ideas?

**Comment by danielhomer** [comment]
Same here 👎 , looks like it's not as easy as that after all.

**Comment by springjk** [comment]
@alexweb For can't login to workspace:
1.  add `command: "/sbin/my_init"` to workspace Container in `docker-compose.yml`
2. `docker-compose down`
3. `docker-compose up -d xxxx`
4. `docker-compose exec workspace bash`

It's work for me. BTW, `command: "/sbin/my_init"` is from `laradock/workspace 1.1` tag.

**Comment by mouyong** [comment]
@alexweb hao do you fixed the problem? i have a same problem

**Comment by frano-sasvari-typeqast** [comment]
Same problem here, I'm on Windows 10. Error says: "docker-php-ext-install command not found".

**Comment by ruman** [comment]
While I run the command:
docker-compose build php-fpm now I got this:

Building php-fpm
Step 1/91 : ARG LARADOCK_PHP_VERSION
ERROR: Service 'php-fpm' failed to build: Please provide a source image with `from` prior to commit
