### ISSUE TITLE
Redirect to https problem

### ISSUE THREAD

**Issue by dannyweb8** [laradock/laradock#520]
I can connect to my site: example.dev
Everything works fine until I add "https" to middleware like this:
```
 /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!$request->isSecure()) {
            return redirect()->secure($request->getRequestUri());
        }
        else {
            return $next($request);
        }
    }
```
When I try to access to my site "example.dev", it's forced redirected to "https://example.dev", which cause: "This site can’t be reached" error.

Any suggestion?

**Comment by NerdsvilleCEO** [comment]
+1 on this, soon as I disable the Secure middleware, it works fine, any plans to support https?
