### ISSUE TITLE
ERROR: Service 'workspace' failed to build: unauthorized: authentication required

### ISSUE THREAD

**Issue by elshahat** [laradock/laradock#521]
Hello,

I have pulled laradock and I pulled it as submodule of my current git project.

When I run this command: **docker-compose up -d nginx mysql**

I get this error:

Building workspace
Step 1 : FROM laradock/workspace:1.3
1.3: Pulling from laradock/workspace
f069f1d21059: Downloading [================================>                  ] 31.98 MB/49.17 MB
ecbeec5633cf: Download complete
ea6f18256d63: Download complete
54bde7b02897: Download complete
a3ed95caeb02: Download complete
ce9e695a6234: Download complete
346026b9659b: Download complete
17c22d06a66b: Download complete
f8d88db8090b: Download complete
f1d344a31ba1: Downloading [========>                                          ]  31.9 MB/193 MB
def84dfaaf29: Downloading
ERROR: Service 'workspace' failed to build: unauthorized: authentication required
Ahmed-ElShahat:laradock Ahmed$ 

This error appears only with **elasticsearch and workspace**

I have tried many many times to execute it again but the same error.
Also I have tried to login to docker via this command: **docker login**, but also the same error after logging in successfuly.

I need your help and thanks in advance.

Regards,
Ahmed ElShahat

**Comment by pakistanihaider** [comment]
![image](https://cloud.githubusercontent.com/assets/3355880/21582893/3d295fa6-d08a-11e6-8d3c-383ff62705d5.png)

**Comment by infacq** [comment]
```bash
ERROR: Service 'mysql' failed to build: unauthorized: authentication required
```

**Comment by dougblackjr** [comment]
Not sure why this was closed. However, I solved it by:

1. Running `docker login`.
2. Entering my docker username (not my email) and password.
3. Once I was reauthorized, I ran `docker-compose up --build (whatever containers I needed)`

Your Docker username is not your email address. You can get your username by going to docker.com and signing in. The name at the top right of the screen is your username.

**Comment by Tyraan** [comment]
docker login can't solve this issue  ,fuXXXXXK

**Comment by pranshubarve** [comment]
I am getting the same error: 
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_PHPREDIS} = true ]; then     printf "\n" | pecl -q install -o -f redis &&     echo "extension=redis.so" >> /etc/php/${LARADOCK_PHP_VERSION}/mods-available/redis.ini &&     phpenmod redis ;fi' returned a non-zero code: 1
