### ISSUE TITLE
Remove production-docker-compose.yml!

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#524]
@laradock/admins I suggest removing [production-docker-compose.yml](https://github.com/laradock/laradock/blob/master/production-docker-compose.yml) and replacing it with documentation on how to build your own. Since it's already outdated and really hard to keep updating it whenever a change applied to the main `docker-compose.yml`. What do you guys think?

**Comment by appleboy** [comment]
Agree with @Mahmoudz 👍

**Comment by philtrep** [comment]
@Mahmoudz sounds good
