### ISSUE TITLE
Nginx exit 1 (Fedora 25)

### ISSUE THREAD

**Issue by cernicc** [laradock/laradock#529]
Hi.

When I run "docker-compose up -d nginx mysql" the nginx container is started and than immediately fails with exit code 1.

![screenshot from 2017-01-05 19-48-46](https://cloud.githubusercontent.com/assets/6370441/21693175/37c43f4c-d380-11e6-97b8-2f6ab21a0c33.png)

I have tried running only nginx container from docker registry (nginx:alpine) and its working.

**Comment by FMate** [comment]
I have the same problem with Nginx. My host system is Ubuntu 16.10. Last time I was using Laradock 10 days ago and everything worked fine.

**Comment by cernicc** [comment]
I have figure it out.
SELinux was preventing nginx from write access on the directory nginx.
So i have disabled SELinux for now. 

![screenshot from 2017-01-08 15-00-51](https://cloud.githubusercontent.com/assets/6370441/21750432/72d4c892-d5b3-11e6-935b-0a46c779d59e.png)

**Comment by FMate** [comment]
I simply reinstalled the Laradock and it has started working as usual.
