### ISSUE TITLE
imagick support

### ISSUE THREAD

**Issue by dopyoman** [laradock/laradock#530]
How would I add imagick support the docker container? 
I have a dependency (http://glide.thephpleague.com/) that needs either imagick or gd.

Thanks

**Comment by dopyoman** [comment]
Sorry it seems like the base php image contains gd support the error I was getting  was 

> Reading Exif data is not supported by this PHP installation.

So the issue is still similar. How would I go about modifying the php's ini file?

**Comment by sc0Vu** [comment]
Maybe you can edit laravel.ini in ./php-fpm or you can mv your ini files into php-fpm container ./usr/local/etc/php/conf.d
Hope this helps.

**Comment by hamony** [comment]
1+ I also need to install imagick.

**Comment by hamony** [comment]
Hope this could help someone wants to install imagick extension https://gist.github.com/pascalbaljet/bd7b8fd63b76c7564189

**Comment by filipac** [comment]
It could be as simple as adding this to ```php-fpm/Dockerfile-70```:
```
RUN apt-get -y update && \
    apt-get install pkg-config libmagickwand-dev -y && \
    pecl install imagick

RUN docker-php-ext-enable imagick
```

**Comment by ihd2911** [comment]
Not working, i tried it but images are still not generated

**Comment by xcafebabe** [comment]
Using php-5.6 add this in your `php-fpm/Dockerfile-56` before `Final Touch` comment
```
RUN apt-get -y update && \
    apt-get install pkg-config imagemagick libmagickwand-dev -y && \
    pecl install imagick && \
    docker-php-ext-enable imagick
```

**Comment by jleonardolemos** [comment]
@filipac your code works fine!! thanks!!

**Comment by JexPY** [comment]
```
RUN apk --no-cache update \
    && apk add --update imagemagick-dev imagemagick \
    && pecl install imagick \
    && docker-php-ext-enable imagick
```

After some research I installed imagick on php 7.4.3 for **php-worker** with this commands, @Mahmoudz if you like this kind of workaround I could create pr for it.

**Comment by ultrono** [comment]
As this thread is ranked highly in Google, the following may help. Newer version of Laradocm have a setting you can change. Look for `PHP_FPM_INSTALL_EXIF` in your `.env` file.
