### ISSUE TITLE
Make the Laradock the official docker image from Laravel

### ISSUE THREAD

**Issue by luciano-jr** [laradock/laradock#534]
The last Laravel [survey](https://laravel-news.com/2016-survey) reveal us, that one thing that the community would like to see in the next steps to the framework is having the official docker image.

Maybe we could adapt or even create a specific branch of Laradock to provide that.

This topic could be improve to plan it with more details.

**Comment by philtrep** [comment]
@luciano-jr Very good idea, we should definitely investigate this further. We could contact the guys @ https://github.com/laravel/laravel to see if they would be open to it.

@laradock/admins What do you guys think?

**Comment by springjk** [comment]
What a great plan!  👍

**Comment by appleboy** [comment]
Great news.

**Comment by Mahmoudz** [comment]
Yes it's great idea, it's the first thing I thought about when reading that survey 2 days ago.
**Make Laradock official.** Support this by retweeting [https://twitter.com/Mahmoud_Zalt/status/818825430350315522](https://twitter.com/Mahmoud_Zalt/status/818825430350315522)

**Comment by mikeerickson** [comment]
@Mahmoudz I am all for an official docker repo and this package is a great start. Curious if Taylor et al would make it happen though.  For most part, they follow the Not Invented Here syndrome much like other leaders.

**Comment by mikeerickson** [comment]
@Mahmoudz well, looks like Taylor is keen on this repo, doesn't want to maintain.  What (if any) issues are open that need cleaning or fixing to clean up any rough edges

**Comment by philtrep** [comment]
I'm not sure I understand the reservation on that point, LaraDock is self-sufficient. We can definitely clean up some more issues but is that the actual problem or just a nice to have?

From what I gather, the community is asking for Docker support of Laravel which is exactly we are doing. Is there a difference in ideology getting in the way?

**Comment by mikeerickson** [comment]
@philtrep I don't have a problem with it at all.  I am merely stating how the Laravel community would react as a whole.  I don't care where it comes from so long as it works!

**Comment by philtrep** [comment]
@mikeerickson I see, we'll do my best to clean up. I have to say that re-reading Taylor's tweet I think that it's the word `Official` he find implies too much responsibility. I'd be happy for this community even if we only got a single line under the `Server Requirements`.

> Alternatively, you can use LaraDock (unofficial) for Docker support.

In the end I think most Laravel users think like you do: if it works, who cares where it's from.

**Comment by mikeerickson** [comment]
@philtrep I have tried LaraDock in the past, but at the time, I had to decide quickly between using Docker and Vagrant as I had to get to work ASAP.   I do recall when trying it in the last, had some pain points and moved on to Vagrant (Homestead).

However, now I have more time to invest in getting the Docker implementation working and am doing that now.

I will report back and report where those pain points and you can decide accordingly how they will be addressed (if necessary).

**Comment by mikeerickson** [comment]
@philtrep One thing that I recall needing in my previous attempt was better node support?  I will make notes as I progress today :-)

**Comment by philtrep** [comment]
@mikeerickson Sounds great, I look forward to your feedback!

**Comment by g0ld3lux** [comment]
rather than making this an official repo, i think we should focus on Making this Production Ready...
And Ready for scalability , Also we Should Limit the number of stacks that we would maintain...
basically we can add unlimited images, but that would sucks and confuse many people...
maybe we can have a Core Stack, where we have the basic 

php , mysql , redis , nginx , laravel, node

then a plugin stack , for example HAProxy and etc...

I think that would be a better approach to make this repo more maintainable...

rather than keep this thing expanding to the core...

**Comment by gagarine** [comment]
Personally, I think it's should focus more to be the "the PHP default stack" than "Laravel default". Of course Laravel can adopt the "PHP default stack" has is "official stack"...

I know it started with laravel, but I think it will be greatly beneficial to have on tools to serve all major PHP app and framework. Most of use use more than just one framework.

In my vision, it's a matter of time before project like that will have GUI and replace stuff like MAMP.
