### ISSUE TITLE
Suggestion to avoid port/address bind issues , like Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use 

### ISSUE THREAD

**Issue by oprudkyi** [laradock/laradock#535]
in case of use of many different laradocks setups for different projects there a lot of such issues as by default laradock configured to use 0.0.0.0 as primary IP 

docker-compose provides [custom networks](https://docs.docker.com/compose/compose-file/#network-configuration-reference) which can be used as workaround of bind problems 

also seems '.env' already part of project so it might be useful to employ custom networks in some way like 
http://oleksii-prudkyi.blogspot.com/2016/09/docker-compose-error-starting-userland.html

i.e. have 
```
>cat .env
GATEWAY_IP=172.16.240.1
SUBNET=172.16.240.0/24

>cat docker-compose.yml 
networks:
  export:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "${SUBNET}"
        gateway: "${GATEWAY_IP}"
```

as well every service should have updated ports and networks, like 

```
services:
  nginx:
    image: nginx:latest
    ports:
      - "${GATEWAY_IP}:80:80"
    networks:
      - export
```

while implementing of this is relatively simple , it may affect current users 

- /etc/hosts should be updated to point to new IPs
- projects settings should be updated as well, because ports will be available on new IP (and not on localhost) 

so it can be added to docs instead

**Comment by ntopulos** [comment]
To use Laradock I definitely need to be able to set the IP of the local server, thank you for this post @oprudkyi.

Unfortunately I wasn't yet able to make it work: after changing the configuration according to those instructions and running ``docker-compose up -d nginx`` I get:

    ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (831f12dce64d4355386e5bc671e945ab5bdf98741dab447b93b7cd5b268d529b): Error starting userland proxy: listen tcp 172.16.240.1:443: bind: cannot assign requested address
    Encountered errors while bringing up the project.

I am not sure where to add the ``networks`` definition. I included it only to the nginx block and then to nginx, workspace, php-fpm. In both cases I get the same error.
