### ISSUE TITLE
Xdebug does not install

### ISSUE THREAD

**Issue by tom-sinclair** [laradock/laradock#536]
I am trying to generate a code coverage report from PHPUnit which requires Xdebug, however when I install Xdebug following the instructions, Xdebug is still not available when I ssh into the workspace container. I have read through the various issues and posts on SO but nothing has offered me an option to get this working. Also, I have been unable to run the xdebugPhpFpm commands as described, I have been running them by prefixing it with bash (I'm unsure if this is the correct usage). The output from this is:

```
Start xDebug
laradock_php-fpm_1
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/aerospike.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/aerospike.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=opcache.so from php.ini) in Unknown on line 0
PHP 7.0.9 (cli) (built: Aug 10 2016 19:45:48) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

 I'm not sure what information you need but here is the output from `php -v` from the workspace container:

```
PHP 7.0.14-2+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14-2+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
```

Aside from adding my volumes to the `docker-compose.yml` file, this is a fresh install of laradock.

I hope someone can help here.

**Comment by jtoler** [comment]
Same here.

**Comment by dannysood** [comment]
I am facing the same issue. This is what i could figure out this far. Even though the dynamic file is being referenced and read (from PHPSTORM) but the values are not being red by phpstorm and are not idnetified in the final config.

I would love if we can bump priority on this as without xdebug the dev cant happen. I am using homestead as a dev server temporarily.

**Comment by Harreh** [comment]
Experiencing this issue also, it appears that `/etc/php/7.0/cli/conf.d/20-xdebug.ini` still has the `;` comment in place so the extension isn't loaded. I've set the `INSTALL_XDEBUG` to `true` in both the `php-fpm` and `workspace` settings in `docker-compose.yml` and rebuilt these containers. The output of this process suggested it did run the install script for xdebug when it got to it

**Comment by HolyKindom** [comment]
Hey guys,
As a solution for this. We can see the guide in https://github.com/laradock/laradock/blob/master/_guides/phpstorm.md 
and the issue : https://github.com/laradock/laradock/issues/460.
It really works after I configure the phpstorm step by step after the instructions above.
Hope it works for you successfully!

**Comment by Harreh** [comment]
I tried following the guide but can't complete the SFTP step. If I set the host to my docker container IP I get 'Connection is closed by foreign host' and if I set it to local host I get 'Auth fail'. If I select the `.ppk` it says it's an invalid format for corrupt so I selected the `insecure_private_key_rsa`

Also, when I run `./xdebugPhpFpm status` I get a PHP warning about aerospike

    xDebug status
    PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/aerospike.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/aerospike.so: cannot open shared object file: No such file or directory in Unknown on line 0
    PHP Warning:  PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=opcache.so from php.ini) in Unknown on line 0
    PHP 7.0.9 (cli) (built: Aug 10 2016 19:45:48) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
        with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

I've managed to set up a remote PHP interpreter with docker (one for the workspace and one for php-fpm) and this works for running CLI scripts or Behat.

**Comment by HolyKindom** [comment]
You selected the right ssh key as you use the mac platform.
Do you enter the "localhost" into the "SFTP host" ? It should be effective...
![qq 20170223085047](https://cloud.githubusercontent.com/assets/16679341/23239954/5243428c-f9a5-11e6-9722-f4ae1fb3dc1c.png)

And the warning does not matter,it's about another bug which is in another issue ~~

**Comment by Harreh** [comment]
Yep, if I enter localhost I get 'Auth failed' error
