### ISSUE TITLE
Upgrade to use PHP 7.1??

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#539]
Do you happen to have plans to upgrade to use PHP 7.1?   If not, can you shed some light on the process necessary for using PHP 7.1 locally?

**Comment by mikeerickson** [comment]
I have done the following:

- Created Dockerfile-71 (based from Dockerfile-70) and updated version to 7.1
- Updated `docker-compose.yml` to point to the `Dockerfile-71` in php-fm section
   ```
            dockerfile: Dockerfile-71
   ```

- execute `docker-compose up -d nginx mysql redis`

**Comment by philtrep** [comment]
@mikeerickson There's a PR waiting for some modifications and we should be good to go! #484

**Comment by mikeerickson** [comment]
@philtrep Excellent, thx!

**Comment by mikeerickson** [comment]
@philtrep Good day sir... Has this been released yet?  The #484 issue still appears to be open?

**Comment by philtrep** [comment]
@mikeerickson  still waiting on @AliveCorpse

**Comment by mikeerickson** [comment]
@philtrep sounds good

**Comment by AliveCorpse** [comment]
What can i do? Im temporary use my own images [alivecorpse/php-fpm:latest](https://github.com/AliveCorpse/laradock/blob/local_env/php-fpm/Dockerfile-71) and [`alivecorpse/workspace:7.1`](https://github.com/AliveCorpse/laradock/blob/local_env/workspace/Dockerfile-71).

**Comment by philtrep** [comment]
@mikeerickson @AliveCorpse My apologies, I did not realize we had to update the tags on Dockerhub manually. I do not have access to the Dockerhub account so @Mahmoudz will have to do it.

**Comment by Mahmoudz** [comment]
@philtrep I just did that right now. It will take few minutes for the build to finish.
<img width="846" alt="screen shot 2017-01-17 at 12 06 08 pm" src="https://cloud.githubusercontent.com/assets/1983984/22031017/6428e688-dcad-11e6-9c18-ec10b8cd355c.png">

**Comment by Mahmoudz** [comment]
@philtrep @mikeerickson got this error with the **5.6** version: 

Build failed: The command '/bin/sh -c docker-php-ext-install mysqli && docker-php-ext-install pdo_mysql RUN docker-php-ext-install pdo_pgsql' returned a non-zero code: 1

**Comment by mikeerickson** [comment]
@philtrep @Mahmoudz Hey gang, it seems that this is still an open issue?   Is PHP 7.1 now available in Laradock?

**Comment by jakubkratina** [comment]
Hello, where do you plan to add support for PHP 7.1? Thank you.
