### ISSUE TITLE
[FEATURE] Provide ability to copy user alias script and source it in ~/.bashrc

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#540]
Is there an entrypoint for copying `.sh` files (in my case, I have a number of bash aliases I use) 

I can easily copy it around and be done with it, but I am curious if there is already a method in place for doing this when I `docker-compose up -d nginx mysql redis`

**Comment by philtrep** [comment]
There is no LaraDock specific way of doing this. You can add a volumes instruction in the docker-compose file for the service you want to mount.

```yaml
volumes:
    - ./my_scripts/:/tmp/scripts
```

I don't believe we currently have anything to add aliases. I would suggest sourcing the file yourself when entering the container `docker-compose exec workspace bash -c "source myaliasfile.sh && bash"`.

We have a PR #487 to allow running commands from outside the containers. I think a good feature would be to have a list of alias that loads the user specific commands, allowing you to run the commands you want without having to ever go into the containers via `exec`.

**Comment by philtrep** [comment]
@mikeerickson And in case it wasn't obvious enough, my previous comment was an invitation to do a PR 😉

**Comment by mikeerickson** [comment]
@philtrep gotcha!  Will get it done after my open PR is done :)

**Comment by mikeerickson** [comment]
@philtrep OK, having closed up https://github.com/laradock/laradock/issues/541 I am now moving onto this feature.

**Comment by mikeerickson** [comment]
@philtrep FYI, I am starting on this one now....

**Comment by philtrep** [comment]
@mikeerickson awesome, looking forward to the PR :)

**Comment by philtrep** [comment]
Fixed by #557
