### ISSUE TITLE
[FEATURE] Add linuxbrew option to workspace

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#541]
I don't see this as an option anywhere?

**Comment by philtrep** [comment]
@mikeerickson Thank you for the suggestion. We can definitely investigate the possibility of adding this but I doubt it would be preferable to the `git submodule` way of installing LaraDock.

Since the goal is to have an exact replica of the `dev` environment on all machines, it makes sense to keep the version of LaraDock used within the project as a part of version control.

Can you see any benefits to adding LaraDock to brew other than availability?

**Comment by mikeerickson** [comment]
Perhaps I was not clear in first message :)

What I am actually requesting is having homebrew (linuxbrew) available as with other installed tools (ala yarn, node, mom, etc) 

Not a homebrew method for install laradock, the current method is just fine :)

**Comment by philtrep** [comment]
Oh I see, good idea.

**Comment by mikeerickson** [comment]
@philtrep If you would like, I can take a stab at it :-)   Still learning the whole docker approach, so not sure where to "start" but surely cant be too difficult.   I will see if I can figure it out.

**Comment by philtrep** [comment]
@mikeerickson Sure thing. Let's keep this issue open, we'll close it when you (or someone else) implements a solution!

**Comment by mikeerickson** [comment]
@philtrep In the process right now (rebuilding the workspace container) quite a slow process :-)

**Comment by mikeerickson** [comment]
Can you advise?

1. Update workspace/Dockerfile to include installation script for linuxbrew
2. Set the INSTALL_LINUXBREW flag in docker-compose.yml 
3. Rebuilding workspace container

I receive error when rebuilding workspace container

```
Step 72 : RUN if [ ${INSTALL_LINUXBREW} = true ]; then     git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
 ---> Running in 5195af2ba8fc
/bin/sh: 1: Syntax error: end of file unexpected (expecting "fi")
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_LINUXBREW} = true ]; then     git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew' returned a non-zero code: 2
```

In case you wish to see, here is the updated code in `workspace/Dockerfile`

```
#####################################
# Linuxbrew:
#####################################
USER laradock

ARG INSTALL_LINUXBREW=true
ENV INSTALL_LINUXBREW ${INSTALL_LINUXBREW}

RUN if [ ${INSTALL_LINUXBREW} = true ]; then \
    # Install the Linuxbrew
    git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew

    echo "" >> ~/.bashrc && \

    # Until LinuxBrew is fixed, the following is required.
    # See: https://github.com/Homebrew/linuxbrew/issues/47
    echo 'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH'
    ## Setup linux brew
    echo 'export LINUXBREWHOME=$HOME/.linuxbrew'
    echo 'export PATH=$LINUXBREWHOME/bin:$PATH'
    echo 'export MANPATH=$LINUXBREWHOME/man:$MANPATH'
    echo 'export PKG_CONFIG_PATH=$LINUXBREWHOME/lib64/pkgconfig:$LINUXBREWHOME/lib/pkgconfig:$PKG_CONFIG_PATH'
    echo 'export LD_LIBRARY_PATH=$LINUXBREWHOME/lib64:$LINUXBREWHOME/lib:$LD_LIBRARY_PATH'
;fi
```

**Comment by mikeerickson** [comment]
@philtrep Please see above (forgot to tag you)

**Comment by mikeerickson** [comment]
@philtrep I think I figured out the issue (forgot the \ at end of each line).  Please hold while I confirm the issue (rebuilding workspace now).

**Comment by mikeerickson** [comment]
@philtrep OK, workspace is rebuilt but brew was not installed (looks like it is being installed correctly when watching rebuild, but nothing there).   

If you have any advise on how to fix this, I would greatly appreciate it.   

For now, I have `linuxbrew` installed (doing it manually) but would love to get this added in core :-)

**Comment by mikeerickson** [comment]
@philtrep 

When you have a chance, can you please review my PR  https://github.com/laradock/laradock/pull/543

**Comment by philtrep** [comment]
@mikeerickson I'll be testing it out today.

**Comment by mikeerickson** [comment]
Feature added (see above)
