### ISSUE TITLE
HOST and POST when connect to Database

### ISSUE THREAD

**Issue by louisluu** [laradock/laradock#556]
Hi,

I setup a Lumen project using this Laradock with nginx and mariadb. I follow the Docs and everything works just fine exception the connection to database.

I want to run nginx on port `8080` and mariadb on port `33061`. At first, I change the `DB_HOST` and `DB_PORT` in `.env` to 

````
DB_CONNECTION=mysql
DB_HOST=mariadb
DB_PORT=33061
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
````

But get error when running `artisan` command

````
[PDOException]                                                                                                     
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known 

[ErrorException]                                                                                                
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known 
````

But when I change the DB_HOST to `127.0.0.1` and it works (the astisan command). However, I cannot connect to the DB inside the Lumen app with this:

````
$results = app('db')->select("SELECT * FROM users");
var_dump($results);
````

And the error is:

````
PDOException in Connector.php line 119:
SQLSTATE[HY000] [2002] Connection refused
````

Then, when I change DB_HOSTto `mariadb` and DB_POST to `3306` (not 33061 as in docker config) and it works (in Lumen app but not in astisan) !?!

What did i do wrong here?

Thanks

**Comment by appleboy** [comment]
post your `docker-compose.yml`.

**Comment by louisluu** [comment]
Parts that I touched:

nginx:
````
ports:
            - "8080:80"
            - "4431:443"
````

and mariadb:
````
ports:
            - "33061:3306"
````

And of course the application:
````
    applications:
        image: tianon/true
        volumes:
            - ../myproject1/:/var/www/myproject1
````

**Comment by appleboy** [comment]
You should connect the database as the following config In container.

```
DB_CONNECTION=mysql
DB_HOST=mariadb
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

**Comment by appleboy** [comment]
In your terminal. You can try the following command to connect mysql.

```
mysql -u homestead -p -h 127.0.0.1 -P 33061
```

**Comment by mastacheata** [comment]
You only changed the external ports for Mariadb and nginx. Internally the different containers still communicate over the default ports (80 and 3306).
The forwarded/external ports only matter for communication from your host computer or from outside via the host computer. 

Think of it like port forwarding in your home network.

**Comment by louisluu** [comment]
Thanks @appleboy @mastacheata 

Now I know why I need to switch between them.

But is that a good practices? Or is there a better way to handle this kind of scenario (running app and astisan) without changing the HOST and PORT?

**Comment by mastacheata** [comment]
What kind of scenario?
Your Lumen installation is running INSIDE the laradock network, so it should obviously use the hostnames/ip addresses of that internal network with the internal ports used by the services.

You should probably run artisan from inside the workspace container and not from your host system as well. That way you don't have to worry about ports and paths.

**Comment by winfried-van-loon** [comment]
Closing this issue as I assume it has been fixed. Feel free to leave a comment if it's not fixed or if you've got any unanswered questions. 👍

**Comment by shivangianya** [comment]
While creating command in console (lumen), when I've tried to fetch data by using RepositoryInterface then I am facing the same issue but it is working fine with controllers.The issue occures only with console commands.

![artisan issue](https://user-images.githubusercontent.com/44433606/52848232-36440a80-3134-11e9-8a35-08a51c1c514f.png)
