### ISSUE TITLE
Cannot rebuild containers after upgrade

### ISSUE THREAD

**Issue by maurosbu** [laradock/laradock#559]
Hi,
I'm trying to upgrade laradock but I get the following error when rebuilding containers:

    groupadd: GID '20' already exists
    ERROR: Service 'workspace' failed to build: The command '/bin/sh -c groupadd -g $PGID laradock &&     useradd -u $PUID -g laradock -m laradock' returned a non-zero code: 4

In docker-compose.yml PUID & PGID reflect those of my user.
It worked in the past with GID equals to 20.

Many thanks,
Mauro

**Comment by philtrep** [comment]
@maurosbu try stopping the compose stack
```
docker-compose down
```
Removing the existing containers
```
docker rm $(docker ps -qa)
```

And rebuilding + rerunning your stack `docker-compose up --build -d <services>`

**Comment by maurosbu** [comment]
@philtrep according to https://docs.docker.com/compose/reference/down/ there is no need to execute

    docker rm $(docker ps -qa)

These are the commands I usually execute when I need to upgrade laradock:

    docker-compose down
    docker-compose build --no-cache nginx mysql phpmyadmin workspace php-fpm
    docker-compose up -d nginx mysql phpmyadmin

Unfortunally I get the error specified in the first comment.

**Comment by philtrep** [comment]
@maurosbu I did not know about the removal on containers, still I was missing a command under the `rm`:
```
docker rmi $(docker images -qa --digests)
```
To be honest with you, most problems _à la_ `it used to work but now it doesn't` get "solved" by doing a complete purge of containers/images/networks/volumes.

**Comment by philtrep** [comment]
@maurosbu Did you ever manage to get it working?

**Comment by maurosbu** [comment]
@philtrep No.

I removed volumes and images, but I'm still getting the same errror.
I'm on MAC and I'm trying to use 20 as group id. 
I think that the problem is here:
https://github.com/laradock/laradock/blob/master/workspace/Dockerfile#L47

Of course it is not possible to add a group if it already exists.
I suggest to create the group only if it doesn't already exist.

What do you think?

**Comment by philtrep** [comment]
@maurosbu Sounds good, something like `getent group laradock || groupadd -g $PGID laradock`

**Comment by maurosbu** [comment]
@philtrep I think that workspace/Dockerfile should be fixed.
