### ISSUE TITLE
If I use the redis,the laravel will have these problem

### ISSUE THREAD

**Issue by sasuke6** [LaraDock/laradock#56]
I want to use the redis as the cache/session driver and open the `.env` file to rewrite `CACHE_DRIVER ` and `SESSION_DRIVER `
`CACHE_DRIVER=redis
SESSION_DRIVER=redis
 `
But when  I open the 192.168.99.100,the laravel reports the problem like this:
`FatalThrowableError in Database.php line 62:
Fatal error: Class 'Predis\Client' not found
 `
What's the problem with the redis?

**Comment by Mahmoudz** [comment]
This is very normal, heck this part of the documentation: https://github.com/LaraDock/laradock#Use-Redis
