### ISSUE TITLE
How can i create cakePHP project with laradock?

### ISSUE THREAD

**Issue by at-tienpd** [laradock/laradock#560]

**Comment by sc0Vu** [comment]
Maybe you should follow these install instruction:

https://github.com/laradock/laradock#Installation
https://book.cakephp.org/3.0/en/installation.html

*Remember to enter workspace  container to install cakePHP project
*Maybe you need to set httpd.conf or nginx.conf root correctly

Hope this helps.

**Comment by kvahuja** [comment]
You have to start by installing Laradock as a fresh project. Once the workspace is up and running, you can then bash into the container and install a CakePHP or any other project for that matter.

This is what i was thinking as well (not specifically for Cake) but for any work i want to do. This whole project seems to a lot more useful than just "Laravel".

**Comment by at-tienpd** [comment]
I have successfully created my projects in local by nginx, php-fpm and mysql. Thanks you so much!
