### ISSUE TITLE
No changes to source code are applied until docker-compose is restarted

### ISSUE THREAD

**Issue by alexey-m-ukolov** [laradock/laradock#562]
When I edit source code nothing is changing, only executing `docker-compose kill && docker-compose up -d` helps.
How can I fix this issue?

**Comment by philtrep** [comment]
@alexey-m-ukolov which OS and Docker version are you using? Did you change anything in the compose file from the default config?

**Comment by alexey-m-ukolov** [comment]
Yeah, i've broken something trying to upgrade to PHP 7.1. Sorry for bothering, original config works fine.
P.S. I'm on Ubuntu 15.10 and Docker 1.12.6.

**Comment by philtrep** [comment]
@alexey-m-ukolov No probs, we have PRs waiting for PHP 7.1

**Comment by alexey-m-ukolov** [comment]
Actually, no, this problem occurs with a default config too.
It worked fine for an hour or so, but now I have to restart docker-compose to see any changes in the browser.
The only changes I made to docker-compose.yml this time are some INSTALL_XXX flags.

**Comment by alexey-m-ukolov** [comment]
OK, I figured it out - it's Opcache's fault.
Stumbled on it here - https://github.com/docker/docker/issues/15793#issuecomment-210569321
Disabling Opcache in `./php-fpm/opcache.ini` or setting `INSTALL_OPCACHE=false` in `docker-compose.yml` helps.
I think it should be noted in the Debugging section of the repo's readme.

**Comment by philtrep** [comment]
@alexey-m-ukolov absolutely, could you open a PR with the relevant information?

**Comment by alexey-m-ukolov** [comment]
Sure, in a few days, when I got the time.
