### ISSUE TITLE
NGinx is throwing an error when using React/Babel front-end

### ISSUE THREAD

**Issue by kvahuja** [laradock/laradock#568]
I am making a Laravel application that uses React/Babel as it's front-end. NGinx doesn't always renders the JSX files correctly. Here are the logs that NGinx throws..

2017/01/25 09:33:56 [alert] 6#6: *300 sendfile() reported that "/var/www/learn-react/app.jsx" was truncated at 0 whil
request: "GET /learn-react/app.jsx HTTP/1.1", host: "localhost", referrer: "http://localhost/learn-react/index.html"

**Comment by kvahuja** [comment]
The issue is with teh fastcgi parameters and we need to use the following parameters on our nginx setup. I will send a PR soon with the fix. 

```
fastcgi_buffers 16 16k; 
fastcgi_buffer_size 32k;
````

**Comment by philtrep** [comment]
@kvahuja great, I look forward to your PR 👍

**Comment by appleboy** [comment]
fixed by #574
