### ISSUE TITLE
php-fpm won't build with EXIF extension enabled

### ISSUE THREAD

**Issue by suncoastkid** [laradock/laradock#575]
When setting `INSTALL_EXIF=true` in docker-compose.yml: 

> Service 'php-fpm' failed to build: One or more build-args [INSTALL_EXIF] were not consumed, failing build.

**Comment by alexey-m-ukolov** [comment]
Are you using Dockerfile-56? If so, it's definitely a bug - [PR #564](https://github.com/laradock/laradock/pull/564/files) added this option only to Dockerfile-70.

**Comment by suncoastkid** [comment]
No, I'm using Dockerfile-70.

**Comment by alexey-m-ukolov** [comment]
Does your Dockerfile has these lines I linked to?

**Comment by suncoastkid** [comment]
That was it! I added those lines and now it works. Thanks!

**Comment by alexey-m-ukolov** [comment]
I'm guessing your clone is behind the main repo for a few commits and you just need to pull the latest changes.

**Comment by lechengyu** [comment]
I have the same problem when I switched php from 7.0 to 5.6,  not only the Exif but also the Redis Extension lines missing from Dockerfile-56,  paste these lines into your Dockerfile-56 solved it.

**Comment by ganlub** [comment]
This shouldn't be closed. Those lines are still missing on Dockerfile-56.

**Comment by philtrep** [comment]
@ganlub I'm not the one who closed it but there ya

**Comment by winfried-van-loon** [comment]
@ganlub Your solution was merged into the Dockerfiles in #788. Thank you for the suggestion. Will close the issue now, however if your issue is still there, please reply and we'll look into it, again.
