### ISSUE TITLE
Changes to views and routes are not taking effect until I restart all docker containers.

### ISSUE THREAD

**Issue by mth3n** [laradock/laradock#576]
Whenever I make a change to routes or views the changes do not take effect until I stop and restart all docker containers.

Containers being used are nginx, php-fpm, workspace, mariadb, mongo, beanstalkd, and beanstalkd-console.          

User laradock with Laravel 5.4

**Comment by betoflakes** [comment]
The same here...

**Comment by alexey-m-ukolov** [comment]
Possibly you have the same problem I had: https://github.com/laradock/laradock/issues/562

**Comment by mth3n** [comment]
Thanks, that solved the issue is was having.
