### ISSUE TITLE
Setting of mysql database name is not working

### ISSUE THREAD

**Issue by indapublic** [laradock/laradock#577]
Hello. I have issue with mysql and custom database

mysql/Dockerfile
```
ARG MYSQL_DATABASE=test
ARG MYSQL_USER=user
ARG MYSQL_PASSWORD=password
ARG MYSQL_ROOT_PASSWORD=root
```
docker-compose build mysql && docker-compose up -d mysql

But there is not database with 'test' name

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| homestead          |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.00 sec)

Is it bug or feature? Thanks

**Comment by indapublic** [comment]
I did

```
docker stop $(docker ps -qa) && docker rm $(docker ps -qa) && docker volume rm $(docker volume ls -q)
```
and
```
docker-compose up -d mysql
``` 
and now I receive exception while connecting:

```
Can't connect to local MySQL server through socket '(null)' (57)
```

**Comment by philtrep** [comment]
@indapublic you have to set the values in `docker-compose.yml`, the ones above are going to be overwritten otherwise.
