### ISSUE TITLE
Empty content of synced folder

### ISSUE THREAD

**Issue by nemanjam** [LaraDock/laradock#58]
I didn't change default in docker-compose.yml

`    application:
        build: ./application
        volumes:
            - ../:/var/www/laravel`

I cloned laradock repo inside my existing laravel repo. Laradock folder is in there.

`username@pc MINGW64 /c/xampp/htdocs/1/zemke2/laradock (master)
$ ls .. -a
./              .gitignore     composer.lock  node_modules/  server.php
../             .gitmodules    config/        package.json   storage/
.env            app/           database/      phpspec.yml    tests/
.env.example    artisan*       gulpfile.js    phpunit.xml    vendor/
.env_1.example  bootstrap/     laradock/      public/
.git/           bower.json     LICENSE        README.md
.gitattributes  composer.json  nbproject/     resources/`

And when i ssh into container laradock is the only folder in there?

`username@pc MINGW64 /c/xampp/htdocs/1/zemke2/laradock (master)
$ docker exec -it laradock_workspace_1 bash
root@1a20519ccc78:/var/www/laravel# ls -a
.  ..  laradock
root@1a20519ccc78:/var/www/laravel# exit
exit`

Pastebin with nicer formatting http://codepad.org/79BRcwrb

**Comment by Mahmoudz** [comment]
you need to have the LaraDock folder installed inside your Laravel Project (on the root directory of your Laravel app). Otherwise you have to edit this `../:/var/www/laravel` and the path of your laravel app and rebuild the container `../path-to-laravel/:/var/www/laravel`

**Comment by nemanjam** [comment]
> you need to have the LaraDock folder installed inside your Laravel Project (on the root directory of your Laravel app)

It is, laradock is in the root of laravel. See the pic.

http://s32.postimg.org/bdoxcqkmt/Capture.png

**Comment by Mahmoudz** [comment]
oh I see, that's wired! you are on windows! try to set the full path in `/full-path-to-laravel:/var/www/laravel`

**Comment by nemanjam** [comment]
It should see content of parent folder... i'll research further.

http://s32.postimg.org/j15o9114l/Capture.png

**Comment by nemanjam** [comment]
Solved it, I needed to mount folder on machine, then within it I can map subfolder as volume. For example:

//create shared folder in vbox D:\myapp with id myappshare
//from machine mount it
sudo mount -t vboxsf -o uid=$UID,gid=$(id -g) myappshare /myapp
//map volume
/d/myapp:/var/www/laravel
