### ISSUE TITLE
Git submodule - Advice for changing and tracking changes to project specific laradock files

### ISSUE THREAD

**Issue by iannazzi** [laradock/laradock#582]
Hi everyone, I encountered some issues in using git submodules as recommended. I am using laradock within my project folder and it is configured specifically for a project. I used `git submodule add https://github.com/LaraDock/laradock.git ` to add laradock to my project.

Within the laradock folder I have custom startup scripts and testing/development databases.  I had to clone my main repository to another computer to realize none of my customized and new files in the laradock folder were ever tracked. 

I ended up putting the folder on a thumb drive to move it to the new computer. Pretty lame I know.

So now I am staring at the folder and wondering what the best approach to 
a) track the modified files within the laradock folder
b) keep up to date with laradock changes

Thanks for your wisdom!

**Comment by alexey-m-ukolov** [comment]
I guess the best way to do it is to fork this repo and use that fork as a submodule. This way you can commit all your changes and pull new stuff from the main repo from time to time.

**Comment by dannysood** [comment]
@iannazzi I follow the same process. Do close the ticket if it answers your question.

**Comment by philtrep** [comment]
Sounds like this should be documented, if you guys want to submit a PR that'd be great.

**Comment by Mahmoudz** [comment]
Done #8f44a0800b11c71ea063b378ed3537295a304102

**Comment by dannysood** [comment]
@philtrep @alexey-m-ukolov Ill take care of it tomorrow.

**Comment by marcoskubis** [comment]
Can I just `git clone` (instead of  `git submodule`) inside my project? So laradock will be part of my project. Or is it not correct?

**Comment by philtrep** [comment]
You can do either.

I personally keep a private fork for each project using Laradock, makes it much easier to maintain in the long term.

**Comment by neorganic** [comment]
Has this been removed from the docs? Can't seem to find any notes on this in current version .

**Comment by IvanRibakov** [comment]
@neorganic https://laradock.io/documentation/#keep-track-of-your-laradock-changes

**Comment by jasperf** [comment]
> @marcoskubis You can do either.
> 
> I personally keep a private fork for each project using Laradock, makes it much easier to maintain in the long term.

You cannot make a private fork of a public repo. So I guess you mean you have your own main laradock repo which is private and then made a private fork per project @philtrep ?
