### ISSUE TITLE
[Question] Need help with composer installing automation

### ISSUE THREAD

**Issue by a-h-abid** [laradock/laradock#590]
Hi, I need a little help...

I'm trying to run a Lumen project where composer install/update hasn't done yet. I want to run the composer install/update after Laradock containers are up & running inside containers. Same thing for npm.

How can I do it??

**Comment by scoutman57** [comment]
You can find this in the documentation under "Usage"

2 - Enter the Workspace container, to execute commands like (Artisan, Composer, PHPUnit, Gulp, ...).
docker-compose exec workspace bash

**Comment by a-h-abid** [comment]
I checked that but I want that part to be done auto when the containers are up and running. Once i do docker-compose up, it will also launch composer install/update auto. Is this possible?

**Comment by scoutman57** [comment]
The only way to do it automatically is to modify one of the docker images or to add a new image to the bottom of the docker file that will trigger this. There is currently no other way to automate this.

**Comment by mikeerickson** [comment]
Do you have any this automation task executed whenever you docker-compose or only done first time?

**Comment by a-h-abid** [comment]
I haven't done any automation task, not sure where to even put one. I tried something like this:

In the workspace Dockerfile, at the end I put things like this:


    #
    #--------------------------------------------------------------------------
    # Final Touch
    #--------------------------------------------------------------------------
    #

    # Clean up
    USER root
    RUN apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    # Set default work directory
    #USER laradock
    WORKDIR /var/www

    # Install PHP Dependencies with Composer
    # composer.json copied from my project
    ADD ./composer.json /var/www/
    RUN composer install --no-scripts --no-autoloader
    # ^^^ ran with no problem

    # Install Node Dependencies
    ADD ./package.json /var/www/
    #RUN npm install
    #^^^ npm was not working

    # Add App/Project Files
    ADD ./ /var/www/
    RUN composer dump-autoload --optimize


Tried & did this way so that it will create composer files when build done. But this wasn't working as when I checked inside the workspace container, the vendor folder was not created or there. I had to manually run composer install inside the container. This manual part I wanted to avoid.

Just on the side note, I don't have any node, composer, not even php, apache etc. installed in my main machine. just docker. I'm trying to run all my dev environment from the docker.

**Comment by scoutman57** [comment]
This could not be working because the order in which the containers are built.

**Comment by scoutman57** [comment]
One option you have is to create a shell script that will run your docker-compose then runs the docker-compose exec command directly to composer install or npm install

**Comment by a-h-abid** [comment]
Yes. This works for my dev env. 

Thanks.
