### ISSUE TITLE
cURL error 7: Failed to connect to 127.0.0.1 port 80: Connection refused.

### ISSUE THREAD

**Issue by trungke21** [laradock/laradock#594]
(see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by francislavoie** [comment]
There's hardly any context here, so it's hard to know what you're asking or reporting.

**Comment by yaoshanliang** [comment]
curl localhost and file_get_content localhost all give Connection refused.

**Comment by yaoshanliang** [comment]
string(62) "Failed to connect to dashboard.dev port 80: Connection refused"

```
    $curl = curl_init($url);
    //curl_setopt($curl, CURLOPT_HEADER, 0);
    //curl_setopt($curl, CURLOPT_TIMEOUT, 30);
    //curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    //curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
    //curl_setopt($curl, CURLOPT_USERAGENT, 'user_agent_from_dashboard');

    $return = curl_exec($curl);
    var_dump(curl_error($curl));
```

**Comment by thorerik** [comment]
There's a distinct lack of information here...
which containers are you using?
Have you tried talking to the webserver(eg. with nginx, webserver isn't `localhost` or `127.0.0.1`, it's `nginx`)?

**Comment by anondev32** [comment]
Refer to this:
https://laracasts.com/discuss/channels/laravel/guzzlehttp-exception-connectexception-curl-error-7-failed-to-connect-to-localhost-port-8087-connection-refused

**Comment by boyavamsi123** [comment]
curl -X POST http://127.0.0.1:5001/api/products
