### ISSUE TITLE
Move the README.MD content somewhere else!

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#595]
This documentation getting soo big and somehow ugly to maintain! 

So far I'm thinking of Github Wiki I'm not a big fan of it, so we're for suggestions to a better alternatives.

**Nice feature to have in the doc tool:** 
- Supports versioning, in case Docker made an upgrade and we had to change some commands like in the past.
- Easy to find and replace words in all pages, not having to open every single page.
- Allows user to search all pages for any keyword.

**Nice Github WIKI's for inspirations:**
- https://github.com/snowplow/snowplow/wiki
- https://github.com/mcMMO-Dev/mcMMO/wiki
- https://github.com/Netflix/Hystrix/wiki/Configuration

**Comment by mikeerickson** [comment]
@Mahmoudz I like the format used by Netflix (not a big gamer so ... :-) 

This one does look complete (https://github.com/Netflix/Hystrix/wiki/Configuration)

In addition, might want to consider airbnb style guide format (https://github.com/airbnb/javascript)

I am willing to help upgrade documentation

**Comment by Mahmoudz** [comment]
@mikeerickson sounds great. I like those docs.

What about the tool, any recommendations!? I'm really trying to stay away from the Github WIKI unless I have no other choices! I've tried it with other projects in addition to the missed features mentioned above it's somehow ugly! and hard to navigate in it unless you create your own navigations in each page..

Thanks!

**Comment by mikeerickson** [comment]
@mahmoudz I am not sure on the tools, but I will do some research and get back to you.

**Comment by gagarine** [comment]
We can use github page. We can keep the doc in this repository (so you have the documentation when you clone the repository) or use an other repository. Search can use lunr.js.

- https://github.com/blog/2233-publish-your-project-documentation-with-github-pages
- https://github.com/blog/1939-how-github-uses-github-to-document-github

**Comment by dannysood** [comment]
I would love to contribute on this. @Mahmoudz @mikeerickson. Do keep me in the loop once the documentation format is finalized.

**Comment by Mahmoudz** [comment]
@dannysood @mikeerickson I was looking for some tools today and I found that [Jekyll](https://jekyllrb.com/) plays well with Github Pages. And while looking for themes I found [this theme](http://idratherbewriting.com/documentation-theme-jekyll/index.html), it seems perfect for a documentation.

So I was testing it and I created a new [repository](https://github.com/laradock/documentation) to host the docs files only. _Main reason why new repo and not `/docs` folder on this repository is to get this nice URL [laradock.github.io/documentation](https://laradock.github.io/documentation/) instead of "laradock.github.io/laradock"._

So guys feel free whenever you have some free time to migrate all the docs there. It's pretty easy just will take couple hours to move everything there. Check the readme of the new documentation repo for some help.

Note: the current documentation hosted is the demo site of that theme. I made no changes at all but adding `README.md` file to the root. So we need to clean all the default markdowns files from `pages/` and modify the `_data/sidebars/` yaml files to setup our own sidebar...

**Comment by mikeerickson** [comment]
@Mahmoudz Funny you mention Jekyll, I am looking at this right now :-)

I have always considered using it for my repos, but didnt want the overhead as none of them are highly used projects.

**Comment by mikeerickson** [comment]
@Mahmoudz If you want to add me, I will do the forking dance and get started with contribution :-)

**Comment by gagarine** [comment]
@Mahmoudz you can use a /doc folder as a source for github website and I think get a nice URL. See the end of this documentation: https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

**Comment by Mahmoudz** [comment]
@mikeerickson it looks like the Github team like this tool! anyway feel free to start anytime, and try to migrate section by section, each on it's own commit so we can see the changes and probably work with you in parallel or suggest editing.. Please also look at some existing [examples](https://github.com/showcases/github-pages-examples) to get inspired for naming the pages..

@gagarine seems by default Github Pages creates the following link `{organization-name}.github.io/{repository-name}` but not sure if we can change the default behavior! So if I create the `docs` here in this repo I'll get `laradock.github.io/laradock` which is not as cool as `laradock.github.io/documentation`.

**Comment by philtrep** [comment]
@Mahmoudz might be worthwhile to buy a domain name, we can then use it for the github pages. laradock.io could be an idea?

**Comment by appleboy** [comment]
vote laradock.io domain and we can use [hugo](https://github.com/spf13/hugo) Static Site Generator.

**Comment by gagarine** [comment]
@Mahmoudz the coolness of the domain shouldn't force you of splitting repository if it make more sens to keep the doc with the code. Their is advantage of having one repository: pull request can contain the code and corresponding doc change. I can't see an advantage of a second repository for a small project like laradock. For extra fun, like @philtrep  we can use a custom domain.

@appleboy jekyll works out of the box on  GitHub and is widely used. Hugo is also popular but I can't see the advantage for a documentation over Jekyll. With Jekyll peoples don't even have to install any tools on their machine and can simply edit markdown file right on the repository using the GitHub editor (I don't clone locally the repository for a small text change)

@Mahmoudz for moving the documentation: first migrate (move the all readme on one page in a simple copy past), then improve (move section...).

**Comment by appleboy** [comment]
@gagarine Agree. Thanks for your explanation.

**Comment by Mahmoudz** [comment]
@philtrep I just got that domain today :D 

@appleboy Hugo is a another great popular tool. I'm not sure how well it works with Github! however we can always change the tool in the future if we found the need to.

@gagarine I get your point for making contribution less complex for users, the domain can actually solve the url little issue, so I'm gonna merge them in this repo now.

**Comment by Mahmoudz** [comment]
@dannysood @mikeerickson kindly note I've moved the docs to this repository inside the `/docs` folder and deleted the other one. The domain pointing there is [laradock.io](http://laradock.io/).

**Comment by Mahmoudz** [comment]
@laradock/admins Kindly note I've moved the docs from the readme.md to `/docs`. I've used [Hugo](https://gohugo.io/) as website generator tool, just because I think it's a little cleaner, faster and I like that [theme](http://themes.gohugo.io/theme/material-docs). Also I've included steps for how to contribute to the documentation [here](http://laradock.io/contributing/#edit-the-documentation).

**Comment by appleboy** [comment]
@Mahmoudz Good to hear using Hugo as website generator tool. 👍

**Comment by gagarine** [comment]
Happy to see the doc moved :) but I keep my position "against" Hugo for documentation mainly because we are going to commit generated HTML instead of clean markdown. But I'm curious to see how it works.

**Comment by Mahmoudz** [comment]
@gagarine I do agree on that, that's why I started playing with Jekyll first, but after giving Hugo a chance, I found it more elegant! and this theme we're using is really cool :D

I don't mind at any point later switching to another alternatives, as I myself forget to regenerate the site couple times, before pushing my changes.
