### ISSUE TITLE
Explain how this project works behind the scenes.

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#596]
Laradock is pretty much simple project! it might look complex because of the amount of supported tools "containers" and their configuration files.. But for many people the complexity is coming from Docker itself!

However, I suggest creating `INTERNAL.md` or updating the `CONTRIBUTING.md` to include how things work internally, the folder structure, relations between those folders and files, diagrams, workfolows.. 

I believe this will reduce the time and effort we put to support out new users, as well as will increase the amount of contributions and their quality!

**Comment by alexey-m-ukolov** [comment]
> I suggest creating INTERNAL.md or updating the CONTRIBUTING.md to include how things work internally, the folder structure, relations between those folders and files, diagrams, workfolows.
I think wiki would be a better choice for this type of information.
It has a problem of being inaccessible offline, but it's not essential requirement, imo.
