### ISSUE TITLE
Class Memcached not found   

### ISSUE THREAD

**Issue by MatthiasSchmittCOLO21** [laradock/laradock#598]
Hello

Docker containers are running with:

`docker-compose up -d nginx mariadb memcached`

After that I´m trying to publish a vendor with:

`php artisan vendor:publish --provider="xxx"`

**`[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Memcached' not found`**

Memcached extension (php-fpm) is enabled:

`- INSTALL_MEMCACHED=true`

When trying to tun the Artisan command inside the workspace container:

**`[RuntimeException]
  No Memcached servers added.`**

Some idea what´s happening here?

Thanks.

**Comment by francislavoie** [comment]
It wasn't clear, but I think you're running commands on your host machine and not in your `workspace` container. You should be running artisan commands in there. Do `docker-compose exec --user=laradock workspace bash` to get a shell into the `workspace` container. 

You might also not have memcached installed in the workspace container, so you may have to modify it to have those dependencies installed.

**Comment by Shadow2004** [comment]
I am having the these same problems.

@francislavoie would you be able to expand on what config I might need in the workspace container ?

**Comment by francislavoie** [comment]
@Shadow2004 you'll probably have to add this stuff https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile-70#L109-L129 to the workspace Dockerfile. You might need to make some changes for it to build though. You'll also need to add the environment variable to your `docker-compose.yml`.

I don't use memcached so YMMV

**Comment by Shadow2004** [comment]
Thanks for that I will give it a shot.
