### ISSUE TITLE
Question / Enhancement

### ISSUE THREAD

**Issue by pbreah** [LaraDock/laradock#6]
I have been looking for a Laravel docker, and yours is the best documented & updated. Thanks for sharing.

I would love to be able to reuse my existing laravel code, but this is not configurable from the documentation, this would make sense if we are migrating an existing project from Vagrant.

In addition, it would be great to have a mongodb available as well. I'm just getting started with docker, and would love to see what is the process when adding a new software to docker-compose, and how you integrate them. 

Excellent work, thanks.

**Comment by Mahmoudz** [comment]
Hi, @pbreah thanks for your interest in LaraDock.

I have a plan to make this project as a package that can be used on existing projects. Anyway if you want to use it in your own project right now, all you have to do is replace the fresh Laravel installation with your project, then update the `.env` file and your app's config files. That should be so easy.

I am currently really overwhelmed with the amount of the private projects I have, however I will create a ticket for supporting MongoDB, and hopefully w'll add the support very soon.

Thank you.
