### ISSUE TITLE
Why using a volume for memcached?

### ISSUE THREAD

**Issue by gagarine** [laradock/laradock#600]
In docker-compose file a volume is configured for the memcached containers. I don't see the point as memcached is using memory. I guess I'm missing somethings...

**Comment by francislavoie** [comment]
You're right, I couldn't find any documentation about a `/var/lib/memcached` directory being used. My only thought would be for logs, but it doesn't seem to be used that way by default.

**Comment by gagarine** [comment]
Ok I will do a pull request to remove this volume.
