### ISSUE TITLE
MariaDB has no configuration files

### ISSUE THREAD

**Issue by gagarine** [laradock/laradock#601]
The MySQL container configuration has a "my.cnf" ready to use, but the MariaDB have none such file. The settings are in /etc/mysql/my.cnf but anythings in /etc/mysql/conf.d that end with .cnf will be loaded. Files in the conf.d directory can overwrite the default config.

So I'm more to add a file in /etc/mysql/conf.d/my.cnf so we still get the stock config from /etc/mysql/my.cnf .

**Comment by philtrep** [comment]
@gagarine Sorry, I'm not sure I get what your proposing?

**Comment by gagarine** [comment]
I will do a pull request.. going to be clearer ;)
