### ISSUE TITLE
Elastic search - NoNodesAvailableException

### ISSUE THREAD

**Issue by progsmile** [laradock/laradock#603]
Hello Guys! Need your help with ElasticSearch. I've tried combinations of hosts, but still fail
I'm using Laravel 5.3 + Laravel Scout, and driver for elastic. In browser elastic works. From code got this error:

`
NoNodesAvailableException in StaticNoPingConnectionPool.php line 51: No alive nodes found in your cluster`

My scout.php config
```yml
  'elasticsearch' => [
        'index' => 'books_app',
        'hosts' => [
            '127.0.0.1:9300',
            '127.0.0.1:9200',
            '172.18.0.1:9200',
            '172.18.0.1:9300',
            'localhost:9300',
            '172.18.0.1:9200',
            'localhost:9200',
            'http://172.18.0.1:9200',
            'http://172.18.0.1:9300',
        ],
    ],
```

For adding data - that's ok, but for getting - fails

**Comment by thorerik** [comment]
set the host to `elasticsearch` should work (did for me at least)

**Comment by progsmile** [comment]
That was my fault, missed to add connection to client
