### ISSUE TITLE
Xdebug with phpStorm on MacOS

### ISSUE THREAD

**Issue by gagarine** [laradock/laradock#607]
I didn't find anyone able to make xdebug works on MacOS. If someone know the trick, that would be very nice to share :).

See also https://github.com/laradock/laradock/issues/460

**Comment by mikeerickson** [comment]
@gagrine I am working on this very task.  Hope to have it wrapped up this weekend. I will be creating a video along with written instructions to add to documentation when it is all done

**Comment by mikeerickson** [comment]
@gagarine sorry for name typo, replying on phone and it doesn't support auto complete for names :)

**Comment by gagarine** [comment]
Great! I broke my head on https://github.com/LarryEitel/laravel-laradock-phpstorm ....

Now I was following https://confluence.jetbrains.com/display/PhpStorm/Docker+Support+in+PhpStorm witch seem lot more simple. But still no success yet.

**Comment by mikeerickson** [comment]
@gagarine I have learned that half the battle (if not higher) is the myriad of attributes that storm requires (kind of convoluted).  Stay tuned, another long night and day tomorrow still on my horizon 🤓

**Comment by dannysood** [comment]
Thanks in advance @mikeerickson. This is something that I too have been struggling with. Looking forward to the content.

**Comment by HolyKindom** [comment]
I alse followed the instrunction in[https://github.com/laradock/laradock/blob/master/_guides/phpstorm.md](url).After following the instruction , I configured the phpstorm by myself and I can run the phpunit test successfully.**But still, I can not run the debug**, the phpstorm always tells that :"Connection with 'xdebug 2.5.0' can not established etc".
Hope you can  make a breakthrough.

**Comment by HolyKindom** [comment]
I find the issue and it solve the problem.
Here it is:https://github.com/laradock/laradock/issues/460

**Comment by gagarine** [comment]
@HolyKindom you are my hero of the day :). let me close this issue and keep #460 open as a follow up.

**Comment by jcorry** [comment]
@mikeerickson I am eager to see this when you get it completed (or even ready for beta testing/review).
