### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by gagarine** [laradock/laradock#608]
This really go beyond my knowledge of docker, so I really don't know about best practices in this area.

But I think it should be possible to write some test for this project. For example a script can:
- check everything build correctly
- test if all service are running and responding like expected
- do some basic benchmark

The advantage would be: when you do a modifications, run the tests and you know you didn't break somethings.

**Comment by mikeerickson** [comment]
@gagarine while this is surely possible, it will be a hefty task as there are so many different technologies and options available in laradock.   

Having said that, writing a set of core tests to perform heartbeat tests for the various services is more in line with what you are asking for.

**Comment by gagarine** [comment]
Yes, I was thinking of heartbeat tests. If we just test if the container build, run and if the service reply it's already pretty cool. For example with elastic search we can use curl to index some data and try to read them back. It's really closer to functional test and not unit test. I will think about it and post if I find some documentation.

**Comment by mikeerickson** [comment]
Definitely functional/integration testing would suffice (really hard to define "units"). I will write up some soft specs to get things started.  

I don't have enough experience with all myriad of features so can't do complete coverage, but it can be a solid work in progress and a good base for others to chime in where need be

**Comment by philtrep** [comment]
If we could get a list of features we want tested it would be easier to dispatch them to multiple people.

**Comment by mikeerickson** [comment]
@philtrep I agree, hence the reason I said I would create some soft specs as to what will be required.

**Comment by gagarine** [comment]
We are all PHP dev so perhaps it's best to write tests in PHP? In the future we can use part of those test to run some kind status report like the one in drupal :
![screen shot 2017-02-12 at 21 02 27](https://cloud.githubusercontent.com/assets/164074/22865541/a1159ba4-f166-11e6-828b-c87f1233352b.png)

**Comment by scoutman57** [comment]
PHP is NOT a good way to write these test. JMI

**Comment by philtrep** [comment]
@gagarine I tend to agree with @scoutman57, I think it would be better to have bash scripts doing functional tests on the various configurations. What do you think @mikeerickson ?

**Comment by mikeerickson** [comment]
@philtrep @gagrine @scoutman57 I was thinking of using JavaScript if only because that is what I have most extensive.  I have done some prelim working using JS and seems to be a good direction.

**Comment by philtrep** [comment]
@gagarine @scoutman57 Based on our discussion in #487 and https://github.com/laradock/cli/issues/1, we decided to go with Go to write our tests. The main reason is that Go is multi-platform and won't require weird setups to get working on our less developer friendly OSes (wink wink Windows).

**Comment by fedemotta** [comment]
Hi Guys, what do you think about using this tool?

https://github.com/aelsabbahy/goss

I am integrating this to make CI using circleCI.
