### ISSUE TITLE
Recommended way to use `artisan migrate`

### ISSUE THREAD

**Issue by daviestar** [laradock/laradock#610]
Hello, thanks for a great project, I've been picking it apart for some time and it's been a great way to learn docker.

There are a [few issues](https://github.com/laradock/laradock/issues?utf8=%E2%9C%93&q=is%3Aissue%20getaddrinfo) on here relating to my problem, but no clear recommended solution.

When I create a demo Laravel project and change in `.env`:
```
DB_HOST=mysql
```
then in terminal run:
```
php artisan make:auth
php artisan migrate
```
there is the error:
```
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
```
if I change `.env` back to:
```
DB_HOST=127.0.0.1
```
I can run the migration, but when I try to register a user with Laravel app auth demo, I get the error:
```
SQLSTATE[HY000] [2002] Connection refused
```
Are we supposed to toggle between `mysql` and `127.0.0.1` to use the `php artisan migrate` command?  Or should we use `docker-compose exec {one of the containers} bash` and run migrations from there, similar to how vagrant works?

**EDIT**
When I try the IP generated with `dd(Request::ip())` in `.env`:
```
DB_HOST=172.19.0.1
```
I can register users with the app, but get the follow error running `php artisan migrate` command:
```
SQLSTATE[HY000] [2002] Operation timed out
```

**Comment by daviestar** [comment]
Here's a decent solution:
```shell
env DB_HOST=127.0.0.1 php artisan migrate
```
wrapped in a function in your `.zshrc` or similar:
```shell
function migrate() {
  (env DB_HOST=127.0.0.1 php artisan migrate $*)
}
```

**Comment by francislavoie** [comment]
You should probably be running your artisan commands inside of the workspace container.

A good way way to set this up is like this: 

```
cmd() {
    docker-compose exec --user laradock workspace ${@}
}
```

Usage:
```
./cmd php artisan migrate
```

Also, the way you're doing it now, you're allowing mysql to be bound to your host's 3306 port, which is insecure if your machine is publicly accessible. I recommend to change `ports` to `expose` and `3306:3306` to `3306` in your `docker-compose.yml` for your mysql container.

**Comment by Maras0830** [comment]
$ cd <your laradock folder>

$ docker-compose exec workspace bash

$ cd <your project>

$ php artisan migrate

and it work.

**Comment by zeroc0d3** [comment]
My answer is look like in #[647](https://github.com/laradock/laradock/issues/647)

I'll coverage with 2 situation:
A) Project outside container of Laradock
```
- root_folder
---+ project
---+ laradock
``` 
B) Project inside container of Laradock
```
- laradock
---+ /var/www/project
```

Check your running docker:
```
docker ps
```
Check your docker container IP:
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' [container_name_or_id] 
```
container_name_or_id => docker container nginx & mysql, which has different IP

References: you can read [this](http://stackoverflow.com/questions/17157721/getting-a-docker-containers-ip-address-from-the-host)

**Solution for A:**
Change your DB_HOST (.env file) with docker container IP for mysql, eg:
```
DB_HOST=172.25.0.2   # laradock_mysql_1
```
and 
```
APP_URL=172.25.0.3  # laradock_nginx_1
```

**Solution for B:**
After check your running docker (docker ps), you need to enter the workspace container
```
docker exec -it [container_id] bash
```
then change your laravel environment (.env) file with docker container IP address

**Comment by pengpn** [comment]
cd your workspace container and cd your project to run php artisan migrate

**Comment by curunoir** [comment]
Pretty painful each time we have to run artisan commands.

**Comment by b4dnewz** [comment]
This is what I use after the build:
`docker-compose exec [workspace] php artisan migrate:fresh`
and as prefix for any other command that needs to run inside the container:
`docker-compose exec [workspace] some-command`
where **workspace** is a running container with a laravel application

Without using docker-compose it will be:
`docker exec -it [container_id] some-command`
where **container_id** is the id of a running container with laravel application

**Comment by cwilby** [comment]
I use MySQL and automate migrations/seeding when the container starts using an `ENTRYPOINT` script.

1.  Set `WORKSPACE_INSTALL_MYSQL_CLIENT` to true in your `.env` file.

2. Add the following environment variables to workspace service in docker-compose.yml

```yml
  workspace:
    ...
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ...
```

2. Create a `docker-entrypoint.sh` in your `*/workspace` folder.

```bash
#!/bin/bash

# wait for mysql
while ! mysqladmin ping -h"mysql" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" --silent; do
  sleep 1
done

# run artisan scripts
php artisan migrate
php artisan db:seed
```

3. Add the following to the end of `*/workspace/Dockerfile`

```dockerfile
COPY docker-entrypoint.sh .

ENTRYPOINT ["docker-entrypoint.sh"]
```

**Comment by mattkenefick** [comment]
You could also create a separate `.env.artisan` file then use that when you execute:

    php artisan migrate --env=artisan

**Comment by wailashraf71** [comment]
> I use MySQL and automate migrations/seeding when the container starts using an `ENTRYPOINT` script.
> 
> 1. Set `WORKSPACE_INSTALL_MYSQL_CLIENT` to true in your `.env` file.
> 2. Add the following environment variables to workspace service in docker-compose.yml
> 
> ```yaml
>   workspace:
>     ...
>     environment:
>       MYSQL_USER: "${MYSQL_USER}"
>       MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
>     ...
> ```
> 
> 1. Create a `docker-entrypoint.sh` in your `*/workspace` folder.
> 
> ```shell
> #!/bin/bash
> 
> # wait for mysql
> while ! mysqladmin ping -h"mysql" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" --silent; do
>   sleep 1
> done
> 
> # run artisan scripts
> pushd /var/www
>   composer update --no-plugins --no-scripts
>   php artisan migrate
>   php artisan db:seed
> popd
> 
> # start workspace process
> /sbin/my_init
> ```
> 
> 1. Add the following to the end of `*/workspace/Dockerfile`
> 
> ```dockerfile
> COPY docker-entrypoint.sh .
> 
> ENTRYPOINT ["docker-entrypoint.sh"]
> ```

This approach is working for me but **Entrypoint** is an infinite loop, so my migrations are being refreshed over and over again, How can I let it do the migrations only once?

**Comment by douglasfelc** [comment]
I simply added this:

ENTRYPOINT ["php", "artisan", "migrate"]
