### ISSUE TITLE
Upgrade to latest Docker for macOS

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#611]
Have any of our fine users upgraded to latest Docker for macOS?   If so, any issues with laradock?

![image](https://cloud.githubusercontent.com/assets/183153/23032957/1f6c8686-f42b-11e6-8869-82d5b9280a4e.png)

**Comment by francislavoie** [comment]
There shouldn't be any issues. It's just a bugfix release.

**Comment by mikeerickson** [comment]
@franceslavoie famous last words :) I assumed that, but one never knows.   Thx though, updating now!
