### ISSUE TITLE
Add a docker-sync configuration and provide documentation

### ISSUE THREAD

**Issue by gagarine** [laradock/laradock#612]
Related to slow performance on Mac. See https://github.com/laradock/laradock/issues/353

As docker-sync 0.2 is almost ready I think it make sens to work directly with this version.

I'm actually testing it and will provide a PR.

@EugenMayer provide some pointers the general issue:

-   use unison as a sync_strategy
-   probably either plan to use the daemon mode ( 0.2.0 ) or think about using docker-sync as a library https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync to orchestrate your own bootstrap, if you need that.
-   Depending on your needs, you might use docker-sync (only sync, docker-compose is your duty ) or docker-sync-stack ( docker-compose integration build in https://github.com/EugenMayer/docker-sync/wiki/2.2-sync-stack-commands
-   you can easily provide docker-sync as a alternative solution using portable docker-compose.yml files https://github.com/EugenMayer/docker-sync/wiki/Keep-your-docker-compose.yml-portable .. you could use docker-compose-docker-sync.yml in case someone wants to run with docker-sync. This keeps your usual docker-compose files untouched
-   consider looking at https://github.com/EugenMayer/docker-sync-boilerplate yourself and creating such a starting point for testers if needed. I guess laradock is a "boilerplate" generator by default, so having this repo is either temporary or not needed

**Comment by gagarine** [comment]
At the moment, I'm blocked with: https://github.com/EugenMayer/docker-sync/issues/243

**Comment by winfried-van-loon** [comment]
@gagarine Hi, is there any update on this? 

Would be cool to get it working as Docker for Mac is still really slow. Even though they're working on fixing it, it may take a while longer until it's "fast".
