### ISSUE TITLE
error while building workspace which is set "INSTALL_YARN=true"

### ISSUE THREAD

**Issue by thundersword** [laradock/laradock#614]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by mikeerickson** [comment]
This is a typical warning whenever Node is executed.  There is nothing to worry about :(

**Comment by thundersword** [comment]
Thanks for you quick response! The building process stayed at this warning for long time, now it is working fine. Thank you!

**Comment by mikeerickson** [comment]
@thundersword this won't be the last time you ever see it in your console 😉

**Comment by thundersword** [comment]
ERROR: Service 'hhvm' failed to build: The command '/bin/sh -c apt-get update -y     && apt-get install -y software-properties-common     && add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"     && a
pt-get update -y     && apt-get install -y hhvm     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by thundersword** [comment]
before this error, Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch
