### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by xralphack** [laradock/laradock#615]
Laravel Mix Version: ^0.7.2
Node Version (node -v): 6.9.4
NPM Version (npm -v): 3.10.10
OS: Windows10
Description:

I use laradock to run laravel, sometimes chrome console shows

GET http://localhost/js/app.js net::ERR_CONTENT_LENGTH_MISMATCH

sometimes this will show, but not always

Steps To Reproduce:

add laradock as git submodule
docker-compose up -d nginx mysql phpmyadmin
npm run watch

**Comment by philtrep** [comment]
@xralphack Is it possible that the request is being sent while the assets are being compiled?

**Comment by xralphack** [comment]
I am not sure. However npm run watch works for me when the os is mac os x 10.11

**Comment by asolopovas** [comment]
its likely to be the problem with docker or docker nginx. As when I try to login into domain.dev/public/css/app.css which is present it throws exactly same error.

**Comment by wiliam969** [comment]
I had the same issue.
I fixed it by assigning Docker 3 CPU Cores in the Settings/Advanced Section. 
Unfortunately i cant test this on Mac. 

![image](https://cloud.githubusercontent.com/assets/13550402/24740603/448a942e-1aa2-11e7-8d22-19a5aaccf508.png)
