### ISSUE TITLE
Nginx Container doesn't allow me to edit my codes in phpStorm

### ISSUE THREAD

**Issue by stanleyli60** [laradock/laradock#619]
I have come across a strange problem where once my Nginx container is up and running, and I have access my dev website, I am no longer able to edit the codes in phpStorm. 

OS: Windows 10
Docker version: 1.13.1
Docker-compose version: 1.11.1
Containers: Nginx Php-fpm Workspace

Problem details:
1. If I just run the three containers, I can edit the code as many time as I want in PHPStorm. However, once I hit the website, using either chrome or firefox, it will lock my local files and I am no longer able to edit the codes in phpStorm. However, if I login to the workspace container, I can still edit the codes there using VIM.

2. If I docker-compose down and up the container again, the problem still exists

3. Only when I rebuild my nginx container, I can edit my codes again. But once I hit the webpage again, it won't allow me to edit my codes anymore. I have to rebuild my nginx container again.

4. Once switch back to Apache2, the problem is gone. The problem only occurs on Nginx container.

Please help.

**Comment by scoutman57** [comment]
what commands are you using to run the nginx container?

**Comment by stanleyli60** [comment]
The command I use is:

docker-compose up -d nginx php-fpm workspace

Also, my code directory is outside the laradock folder, could this cause the problem?

--Home
   --laradock
   --myApp

**Comment by scoutman57** [comment]
That is the same setup I have as well. Are you on windows/linux/osx?

**Comment by stanleyli60** [comment]
Windows 10. My OS info and docker versions are included in the original description. I have tried two different Win 10 pc (one laptop and one desktop) and they all have the same problem.

**Comment by scoutman57** [comment]
I don't use windows so I am unable to test this. I am surprised that windows would have this issue. Can you post your docker config file (removing passwords)

**Comment by stanleyli60** [comment]
Please see below my config files 

`
version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ../php/:/var/www
#            - ../sample/:/var/www/sample

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_YARN=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - INSTALL_V8JS_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=false
                - INSTALL_LARAVEL_ENVOY=false
                - INSTALL_LINUXBREW=false
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - YARN_VERSION=latest
                - TZ=UTC
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
           - "2222:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_SOAP=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_BCMATH=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_EXIF=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - CODEIGNITER=false
            dockerfile: Dockerfile-70
        volumes_from:
            - applications
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### Apache Server Container #################################

    apache2:
        build:
            context: ./apache2
            args:
                - PHP_SOCKET=php-fpm:9000
        volumes_from:
            - applications
        volumes:
            - ./logs/apache2:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm


### MySQL Container #########################################

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=homestead
                - MYSQL_USER=test
                - MYSQL_PASSWORD=test
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"

### Redis Container #########################################

    redis:
        build: ./redis
        volumes:
            - redis:/data
        ports:
            - "6379:6379"
            
### phpMyAdmin Container ####################################

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        links:
            - "mysql:db"

### Selenium Container #########################################

    selenium:
        build: ./selenium
        ports:
            - "4444:4444"

### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"
    phpmyadmin:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"`

**Comment by stanleyli60** [comment]
And you are right. This issue only happens in Windows. I have no problem running this when the same setting is published to EC2 instance. Not sure why this is causing issues on Windows.

**Comment by mikeerickson** [comment]
@stanleyli60 @scoutman57 Any chance you can create a simple repo with all this code so I can try it locally (using Windows 10)

**Comment by stanleyli60** [comment]
@mikeerickson Yes, I can do that tonight to mock out a simple repo for testing.

**Comment by stanleyli60** [comment]
@mikeerickson sorry for the delay. I have created a temp test repo: https://github.com/stanleyli60/test

Step to reproduce the issue:

1. clone the project in Windows 10
2. cd laradock
3. docker-compose up -d nginx php-fpm workspace
4. use phpStorm to open the app folder
5. setup a host file to point local.test.dev to 127.0.0.1
6. open a browser and enter local.test.dev and you should see 'Hello World!'
7. use phpStorm to make a change to the index.php file.
(Note: the first time you should be able to save the changes and see the changes in the browser after refreshing the page)
8. use phpStorm to make another change and this time will fail. You won't allow to do further changes.

**Comment by alchimik** [comment]
related https://github.com/laradock/laradock/issues/113, https://github.com/laradock/laradock/issues/113#issuecomment-265506361

**Comment by stanleyli60** [comment]
@alchimik Thanks a lot. It works without "Safe write".

However, why would Nginx disallow "safe write"? Also it works fine with Apache.

**Comment by stanleyli60** [comment]
@mikeerickson are you able to reproduce the problem?

@alchimik I have encountered the same problem when using gulp to compile my js files. I believe gulp also uses "safe write" which cause problems when using the Nginx container. Do you have any suggestions on that?

**Comment by alchimik** [comment]
@stanleyli60 sorry I can't help. I use apache

**Comment by thorerik** [comment]
After a bit of googling, it may look like `open_file_cache` can be the culprit, I'm going to test this later and open a PR if it does indeed solve the issue.

**Comment by thorerik** [comment]
Tested the above and seemed to work for me, @stanleyli60 can you give it a shot as well and confirm?

**Comment by evsign** [comment]
I had same issue on Ubuntu 16.04.2 LTS and disabling `open_file_cache` solve this.
