### ISSUE TITLE
Caddy use on local development

### ISSUE THREAD

**Issue by robbydooo** [laradock/laradock#623]
Are we able to add the DNS provider options to the caddy download URL in the dockerfile so we can run caddy with the DNS fallback option? 

Right now unless you open up your local machine to the world you can not used caddy with https via letsencrpyt. By adding a local.xyz.com to your DNS provider you can get round this issue so long as the DNS plugins are available which they are currently not.

I can create a pull request if you think this is acceptable.

The change is in short changing the curl url to 

    https://caddyserver.com/download/build?os=linux&arch=amd64&features=cloudflare%2Cdigitalocean%2Cdnsimple%2Cdyn%2Cgooglecloud%2Clinode%2Croute53

from 

    https://caddyserver.com/download/build?os=linux&arch=amd64

Then we just add this config in the Caddyfile cont to enable:

```
tls {
    dns <DNSPROVIDER>
}
```

Thanks!

**Comment by philtrep** [comment]
@robbydooo Go for pull request!

**Comment by robbydooo** [comment]
This is now https://github.com/laradock/laradock/pull/635

**Comment by appleboy** [comment]
merged.
