### ISSUE TITLE
fail install node

### ISSUE THREAD

**Issue by hudarui** [laradock/laradock#626]
cloning into  '/home/laradock/.nvm'...卡住

**Comment by philtrep** [comment]
@hudarui Could you repeat in English if you could?

**Comment by alixez** [comment]
@philtrep i think when he opened this configuration "INSTALL_NODE=true"  to build the container and stop at "cloning into '/home/laradock/.nvm' ..."   sorry, my English is so bad.

**Comment by hudarui** [comment]
yes，I edit the configuration install_node＝True
,but it stop  at  cloning into/home/laravel/.nvm

**Comment by hudarui** [comment]
win10 docker native

**Comment by hudarui** [comment]
@alixez help

**Comment by iannazzi** [comment]
I set node to true and it hangs here
```stable -> 7.8 (-> v7.8.0) (default)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.```

**Comment by thorerik** [comment]
@iannazzi your issue is different to this issue, this issue is spesifically about failing to clone node version manager, you are beyond that step.
