### ISSUE TITLE
Cannot execute php artisan migrate

### ISSUE THREAD

**Issue by dioseltorre** [laradock/laradock#630]
When I execute: _php artisan migrate_
it always gives me this Exception:

[Illuminate\Database\QueryException]                                                                                            
  could not find driver (SQL: select * from information_schema.tables where table_schema = mydb and table_name = migrations)  
                                                                                                                                  

                         
  [PDOException]         
  could not find driver  

Could anyone tell me how to fix this?

**Comment by Maras0830** [comment]
see https://github.com/laradock/laradock/issues/610

**Comment by yahsharahla** [comment]
It's like no one as the answer for this question, they keep saying to install php5-mysql which comes with the PDO extension.. but nothing happens after installing it. There are so many different ways i have tried to action this problem, but nothing works.

**Comment by kelvinogwa** [comment]
(Windows) Check the database.php file ensure `'default' => env('DB_CONNECTION', 'mysql'),` is properly done for me the problem was I was using `'default' => env('DB_CONNECTION', 'pgsql'),` when using a MySQL database. Changed `pgsql` to `sql` and I was able to proceed.
