### ISSUE TITLE
Xdebug not being installed

### ISSUE THREAD

**Issue by jaesung2061** [laradock/laradock#633]
I've destroyed all containers/images, replaced every instance of `INSTALL_XDEBUG=false` to `INSTALL_XDEBUG=true` and rebuilt/started the containers. This doesn't seem to be working. What am I doing wrong?

Edit: I noticed there are 2 xdebug ini files in `conf.d` and that the line to load the extension was commented out. After uncommenting it, xdebug is loaded. Is there another way to enable this with laradock?

**Comment by flashbag** [comment]
Watch this PR https://github.com/laradock/laradock/pull/632
