### ISSUE TITLE
【php composer】Composer could not run the update commend

### ISSUE THREAD

**Issue by josonchou** [laradock/laradock#634]
I could not use " composer update " in the workspace container

It's stop at " Updating dependencies (including require-dev)"

 System:  Ubuntu16.04
 Docker-engine: 1.12.3

**Comment by thorerik** [comment]
Are you still experiencing this issue?

What do you get if you do `curl -IL https://packagist.org/packages.json` in the container? On the host?

Can you try running `composer self-update`?
