### ISSUE TITLE
Switch from "links" to "depends_on" in docker-compose.yml

### ISSUE THREAD

**Issue by AnatolyRugalev** [laradock/laradock#636]
Laradock is using `links` to link containers together, but this functionality is [deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) in Docker.

In a new version of Docker, all containers can reach each other until they are in the same network. docker-compose transparently creates such network by default.

Just removing `links` may break starting order of services, so we need to replace `links` to [`depends_on`](https://docs.docker.com/compose/compose-file/#/dependson).

**Comment by philtrep** [comment]
@AnatolyRugalev Excellent point, a PR would be most welcomed :)
