### ISSUE TITLE
Php-fpm not returns error logs 

### ISSUE THREAD

**Issue by klikrzys** [laradock/laradock#638]
I'm getting blank page instead of php errors. Code without defects works fine. What should i do to see error log?

**Comment by philtrep** [comment]
@klikrzys Do you have `DEBUG` set to true in you `.env` file for Laravel?

**Comment by klikrzys** [comment]
@philtrep thanks! Now it's working correctly.

**Comment by abidihoussem** [comment]
Hello,
I have the same problem but I'm using laradock for a ZF2 project. is there anything to do in the php config side. Thanks !
