### ISSUE TITLE
Laradock and Spatie Backup – `mysqldump` command not found

### ISSUE THREAD

**Issue by Dartanjan** [laradock/laradock#644]
Hi, I'm new to Docker so this may be a bit basic. I want to use Spatie Backup (https://github.com/spatie/laravel-backup) but it needs access to `mysqldump`. Of course, `mysqldump` is only available under mysql container, not workspace. By default, spatie/laravel-backup takes current database configuration, so shouldn't `mysqldump` be available, as it runs on the same exposed port as mysql, i.e. `laradock_mysql`?
Thanks.

**Comment by hasangilak** [comment]
open up your workspace/Dockerfile and add these lines to it
```
#
#--------------------------------------------------------------------------
# mysql-client
#--------------------------------------------------------------------------
#

USER root

RUN apt update && \
    apt install -y mysql-client
```
down your containers
`docker-compose down`
then rebuild workspace just by
`docker-compose build workspace`
and re-up you containers for example
`docker-compose up redis nginx mysql`

**Comment by Dartanjan** [comment]
Thanks, that does it. I thought maybe there's a way to not install mysql cli inside of workspace, but that works as well. Cheers!

**Comment by ohblue** [comment]
i got a error, when i run ```apt install -y mysql-client``` in workspace bash.

E: Unable to locate package mysql-client

**Comment by hasangilak** [comment]
@ohblue run apt update first

**Comment by ohblue** [comment]
already run apt update

**Comment by ryancwalsh** [comment]
Thank you, @hasangilak . That was helpful. I agree with @Dartanjan :

> "I thought maybe there's a way to not install mysql cli inside of workspace, but that works as well."

**Comment by xlstefan** [comment]
I had this same issue but in order to solve it completely you have to add this same lines to the **php-fpm/Dockerfile** too.

I had the same problem when I created new backup from **Laravel Backpack Backup UI** . This snippet which install mysql client solves error which was showing up.

> open up your workspace/Dockerfile and add these lines to it
> 
> ```
> #
> #--------------------------------------------------------------------------
> # mysql-client
> #--------------------------------------------------------------------------
> #
> 
> USER root
> 
> RUN apt update && \
>     apt install -y mysql-client
> ```
> down your containers
> `docker-compose down`
> then rebuild workspace just by
> `docker-compose build workspace`
> and re-up you containers for example
> `docker-compose up redis nginx mysql`

**Comment by NicksonYap** [comment]
in newer laradock `.env`, you can now use: WORKSPACE_INSTALL_MYSQL_CLIENT=false

**Comment by rvanbaalen** [comment]
@ohblue I ran into that error as well. Found a SO post explaining that the package is called `default-mysql-client` now.

`apt-get install default-mysql-client` inside my PHP container did the trick and installed MySQL and, what I came for, `mysqldump`.

**Comment by Girevik1** [comment]
If you are using postgresql that add 
`RUN apt update &&  apt install -y postgresql-client `
in your php Dockerfile
