### ISSUE TITLE
LDAP and SQL Server support - PHP-FPM [Need Help]

### ISSUE THREAD

**Issue by cabrerabywaters** [laradock/laradock#645]
Hello there!
I have a Laravel app that connects to an LDAP and SQL Server to run some queries.
 I'm trying to install the LDAP and SQL Server extensions for the PHP-FPM container.
So far, I manage to install LDAP with 

`RUN \
    apt-get update && \
    apt-get install libldap2-dev -y && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap`

But I'm having problems with the SQL Server extension. I have run
`RUN apt-get update && \
    apt-get install -y --force-yes freetds-common libsybdb5`
`RUN pecl install sqlsrv`
`RUN pecl install pdo_sqlsrv`

and included both in the php.ini (laravel.ini file)
`extension=sqlsrv.so`
`extension=pdo_sqlsrv.so`

But I'm missing the msodbcsql Driver v13 and I haven't been able to install it on the PHP-FPM container
I was running the app in another container (Laraedit) and just running 
`RUN apt-get install -y --force-yes php7.0-ldap  php7.0-sybase freetds-common libsybdb5`
Solved both issues

Has anyone already solved this? Shouldn't the PHP-FPM container have another arg to give support for SQLSRV (As Laravel includes it in the config/database file)?

Thank you for your help!

**Comment by cabrerabywaters** [comment]
Ok....finally manage to install this...so for future readers, here it comes.

First, LDAP.
I included a LDAP arg at the bottom of the Dockerfile (laradock/php-fpm/Dockerfile-70), with the following
`#####################################
# LDAP:
#####################################
ARG LDAP=false
RUN if [ ${LDAP} = true ]; then \
    apt-get update && \
    apt-get install libldap2-dev -y && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap
;fi`

Secondly, I added a MSSQL arg at the end of the same file to install the sql server drivers and extensions. The microsoft github account was very useful for this. [(LINK)](https://github.com/Microsoft/msphpsql/wiki/Dockerfile-for-getting-pdo_sqlsrv-for-PHP-7.0-on-Debian-in-3-ways)
So the MSSQL install goes as follows:

`#####################################
# SQL SERVER:
#####################################
RUN if [ ${MSSQL} = true ]; then \

    #####################################
    # Install Depenencies:
    #####################################
    RUN apt-get update && \
        apt-get install -y --force-yes wget apt-transport-https curl freetds-common php5-odbc libsybdb5 freetds-bin unixodbc unixodbc-dev php5-sybase

    #####################################
    #  The following steps were taken from
    #  Microsoft's github account:
    #  https://github.com/Microsoft/msphpsql/wiki/Dockerfile-for-getting-pdo_sqlsrv-for-PHP-7.0-on-Debian-in-3-ways
    #####################################

    # Add PHP 7 repository
    # for Debian jessie
    # And System upgrade
    RUN echo "deb http://packages.dotdeb.org jessie all" \
        | tee /etc/apt/sources.list.d/dotdeb.list \
        && wget -qO- https://www.dotdeb.org/dotdeb.gpg \
        | apt-key add - \
        && apt-get update \
        && apt-get upgrade -qq

    # Install UnixODBC
    # Compile odbc_config as it is not part of unixodbc package
    RUN apt-get install -y whiptail \
        unixodbc libgss3 odbcinst devscripts debhelper dh-exec dh-autoreconf libreadline-dev libltdl-dev \
        && dget -u -x http://http.debian.net/debian/pool/main/u/unixodbc/unixodbc_2.3.1-3.dsc \
        && cd unixodbc-*/ \
        && dpkg-buildpackage -uc -us -B -d \
        && cp -v ./exe/odbc_config /usr/local/bin/

    # Fake uname for install.sh
    RUN printf '#!/bin/bash\nif [ "$*" == "-p" ]; then echo "x86_64"; else /bin/uname "$@"; fi' \
        | tee /usr/local/bin/uname \
        && chmod +x /usr/local/bin/uname

    # Microsoft ODBC Driver 13 for Linux
    # Note: There's a copy of this tar on my hubiC
    RUN wget -nv -O msodbcsql-13.0.0.0.tar.gz \
        "https://meetsstorenew.blob.core.windows.net/contianerhd/Ubuntu%2013.0%20Tar/msodbcsql-13.0.0.0.tar.gz?st=2016-10-18T17%3A29%3A00Z&se=2022-10-19T17%3A29%3A00Z&sp=rl&sv=2015-04-05&sr=b&sig=cDwPfrouVeIQf0vi%2BnKt%2BzX8Z8caIYvRCmicDL5oknY%3D" \
        && tar -xf msodbcsql-13.0.0.0.tar.gz \
        && cd msodbcsql-*/ \
        && ldd lib64/libmsodbcsql-13.0.so.0.0 \
        && ./install.sh install --accept-license \
        && ls -l /opt/microsoft/msodbcsql/ \
        && odbcinst -q -d -n "ODBC Driver 13 for SQL Server"

    #####################################
    # Install sqlsrv y pdo_sqlsrv
    # extensions:
    #####################################
    RUN pecl install sqlsrv-4.0.6
    RUN pecl install pdo_sqlsrv-4.0.6
;fi`


Finally, I had to include the extensions in one of the php.ini files. I decide to do it manually in the (laradock/php-fpm/laravel.ini), just because I had to modify a couple more variables for my app. So you have to include the following
`extension=php_sqlsrv.dll
extension=php_pdo_sqlsrv.dll`

And then just rebuild the container and UP your docker-compose.
@Mahmoudz would you consider including this as args for the Laradock/php-fpm container?

Hope it helps.
Best Regards!

**Comment by philtrep** [comment]
@cabrerabywaters Wow. You should definitely put this in a PR.

**Comment by cabrerabywaters** [comment]
@philtrep No problem! I'm going to try to do it today.

**Comment by cabrerabywaters** [comment]
@philtrep OK, it took me a while but finally did a proper pull request for PHP7.0
I divided everything that I'm using in 4 different PR.
PHP-Worker: https://github.com/laradock/laradock/pull/673
GHOSTSCRIPT:https://github.com/laradock/laradock/pull/672
LDAP:https://github.com/laradock/laradock/pull/671
MSSQL:https://github.com/laradock/laradock/pull/670

Hope you can check it and tell me what you think.

**Comment by hounded** [comment]
Hey nice work @cabrerabywaters I have got the container running and have pdo_sqlsrv and sqlsrv, however  I can not get the dblib working, any suggestions ?

**Comment by cabrerabywaters** [comment]
Hello there! Sorry but I haven't use dblib yet, do you have something that I could use to test if Dblib is working OK?
Let me give it a try and I'll see if I can come up with a fix for this one.
Cheers!
________________________________

**Comment by hounded** [comment]
Hi @cabrerabywaters 
I don't have anything to test dblib. My use case is that I have an external MSSQL database source and i'm using 
[LswDoctrinePdoDblib](https://github.com/LeaseWeb/LswDoctrinePdoDblib)
in my application to connect to the external MSSQL database.
