### ISSUE TITLE
Stuck at Starting laradock_application_1

### ISSUE THREAD

**Issue by sasaorz** [laradock/laradock#646]
Hi,

I'm trying to get all the containers running but one of the container "laradock_application_1" is stuck at starting. 
![capture](https://cloud.githubusercontent.com/assets/26119140/23468534/f231246a-fe98-11e6-919f-1ed3f9789794.PNG)

Any help would be appreicated!

**Comment by mikeerickson** [comment]
@sasaorz what tool (and version) are you using to execute `docker-compose`

**Comment by sasaorz** [comment]
@mikeerickson I have tried to use Windows CMD and Power Shell and Kitematic to run docker-compose, they all gave me the same result. I ran `docker version` on CMD it shows Version: 1.13.1

**Comment by cjmaxik** [comment]
@sasaorz This container is only a volume. It should starts and stops immediately.

**Comment by zeroc0d3** [comment]
@cjmaxik
That's right, no need to confuse. It's only running once time and then stop...

**Comment by philtrep** [comment]
@sasaorz Please see @cjmaxik 's comment. Checkout https://hub.docker.com/r/tianon/true/ for more info.
