### ISSUE TITLE
mysql root user cant login into phpmyadmin nor into mysql container nor connect via php

### ISSUE THREAD

**Issue by hasangilak** [laradock/laradock#647]
I did provide solutions too.
there is two problem. login into mysql and login into phpmyadmin
problem 1) there is a startup sql script for mysql software that each time mysql starts up would be executed each time by mysql itself. you can find it in mysq/startup in laradock folder. with the help of this file you can put some sql code to update root password. this link form mysql site should help 
[resetting permissions](https://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html)
down and build and up your containers

problem 2) phpmyadmin needs user hosts to be %. but user host was changed to localhost it seems.
exec into mysql container and try these lines. (I did set my password to root)
```
mysql -uroot -proot
use mysql;
update user set Host = "%" where User="root";
flush PRIVILEGES;
```
see the result
`select * from user \G`

**Comment by philtrep** [comment]
@hasangilak I'm not sure I understand what you are proposing?

**Comment by zeroc0d3** [comment]
@hasangilak, first you need to check your docker container IP:

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' [container_name_or_id] 
```
container_name_or_id => docker container phpmyadmin & mysql, which has different IP

References: you can read [this](http://stackoverflow.com/questions/17157721/getting-a-docker-containers-ip-address-from-the-host)

Then put it on your browser, eg: http://172.19.0.2:8080 for phpmyadmin

**Comment by zeroc0d3** [comment]
Perhaps this is the sollution #480
