### ISSUE TITLE
workspace container, laravel installer isn't finding composer

### ISSUE THREAD

**Issue by AminMkh** [LaraDock/laradock#65]
Workspace container has an issue, laravel global installer isn't finding composer, will look into it soon:

```
root@bc0a9189bfdd:/var/www/laravel# laravel new project
Crafting application...
sh: 1: composer: not found
Application ready! Build something amazing.
```
Though composer is installed all good.

```
root@bc0a9189bfdd:/var/www/laravel# composer -V
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Composer version 1.1.1 2016-05-17 12:25:44
```

**Comment by Mahmoudz** [comment]
Yes I've noticed that this only happens with the Laravel installed. However I'm thinking of removing that useless laravel installer from the container since even installing it takes a lot of time, and the `composer create-project` command is doing the same job better with least effort.

**Comment by Mahmoudz** [comment]
adaaa25f479384bd2fcd66acda239e9c33d2d73a
