### ISSUE TITLE
Can't installl php7.0-gmp into php-fpm container...

### ISSUE THREAD

**Issue by sasokovacic** [laradock/laradock#652]
it can be done for every other version of linux but not for jessie... or am I missing something?
I've tried everything without success... I really need this for a project I'm working on...

**Comment by kahunacoder** [comment]
I needed gmp too but when I installed it using laradock fpm that I modified, I kept getting an error saying gmp.h couldn't be found.

I added this to Dockerfile-70
```
#####################################
# GMP:
#####################################

ARG INSTALL_GMP=false
RUN if [ ${INSTALL_GMP} = true ]; then \
    # Install the gmp extension
    apt-get update && \
    apt-get -y install libgmp-dev && \ 
    docker-php-ext-install gmp \
;fi

and changed this FROM to
FROM laradock/php-fpm:7.1--1.3
```

This didn't work. So I added my own dockerfile to laradock fpm, it installs a lot of extensions and their required libraries. I don't know what my file added that was missing in the modified Dockerfile-70 but here is my custom dockerfile.

```
FROM php:fpm

RUN apt-get update && apt-get install -y \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
		libcurl4-gnutls-dev \
		libxml2-dev \
		libbz2-dev \
		re2c \
		libpng++-dev \
        libpng3 \
        libjpeg-dev \
        libvpx-dev \
        zlib1g-dev \
        libgd-dev \
        libssl-dev \
        libtidy-dev \
        libxslt1-dev \
        libmagic-dev \
        libexif-dev \
        file \
        libssh2-1-dev \
        git \
        wget	\
		sqlite3	\
		libsqlite3-dev \
		libgmp-dev \


	&& docker-php-ext-install json \
	&& docker-php-ext-install mbstring \
	&& docker-php-ext-install tokenizer \
    && docker-php-ext-install gmp \
    && docker-php-ext-install gd \
	&& docker-php-ext-install curl \
	&& docker-php-ext-install dom \
	&& docker-php-ext-install bz2 \
	&& docker-php-ext-install mysqli \
	&& docker-php-ext-install pcntl \
	&& docker-php-ext-install pdo \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install phar \
	&& docker-php-ext-install posix \
	&& docker-php-ext-install simplexml \
	&& docker-php-ext-install soap \
	&& docker-php-ext-install sockets \
	&& docker-php-ext-install tidy \
	&& docker-php-ext-install zip \
	&& docker-php-ext-install bcmath \
	&& docker-php-ext-install calendar \
	&& docker-php-ext-install ctype \
	&& docker-php-ext-install exif \
	&& docker-php-ext-install pcntl \
	&& docker-php-ext-install pdo_sqlite
```

**Comment by sasokovacic** [comment]
Thanks for your answer...  Today I found shorter solution on https://hub.docker.com/r/ianblenke/simplesamlphp/~/dockerfile/

# Install the gmp and mcrypt extensions
RUN apt-get update -y
RUN apt-get install -y libgmp-dev re2c libmhash-dev libmcrypt-dev file
RUN ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/
RUN docker-php-ext-configure gmp 
RUN docker-php-ext-install gmp


and it works...
you can ignore mcrypt if you don't need it...

**Comment by steinkel** [comment]
The provided link is 404 now, but the fix worked for me when dealing with a similar issue in a .gitlab-ci.yml file, Thanks!

**Comment by neorganic** [comment]
````php -i | grep gmp ```` Shows the gmp installed on php-fpm, but not on workspace from where I install my composer packages, not sure why both the documented recipe and @sasokovacic  fails to do it's job.

**Comment by jayenne** [comment]
I've set all the GPM's to true in the laradock env file and rebuilt. phpinfo is showing it enabled but I'm still getting an error saying it's not there (webpush notifcations failing). also 'php -i | grep gmp' shows nothing in workspace but fine from outside docker workspace.

any thoughts?

**Comment by Dsantacruz** [comment]
@sasokovacic , this solutions is worked
