### ISSUE TITLE
Custom domain not working for me

### ISSUE THREAD

**Issue by samijnih** [laradock/laradock#663]
Hello here, I've been trying to resolve this issue until 5am lol.

I've created my default docker virtual host. He is currently running because when I do docker-machine ls, I can see it running:

```
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v17.03.0-ce   
```

I've built my workspace, nginx and php-fpm.

### My default nginx conf contains:
```
    listen 80;
    listen [::]:80 ipv6only=on;
    server_name laravel.dev;
    root /var/www/fymh/public;
```

### My docker-compose.yml:
* I removed the extra_hosts in the docker-compose.yml on the php-fpm and workspace because I don't need it.

### IP
* I have my docker IP by doing `docker-machine ip default` resulting on `192.168.99.100`
* I did `docker-compose up -d nginx mysql redis phpmyadmin`
* I logged into my workspace as the root user and I updated the `/etc/hosts` to set `192.168.99.100 laravel.dev`

* When accessing my browser, it is not working, the domain could not respond

I tried to update the `/etc/hosts` by setting `127.0.0.1 laravel.dev` and nothing new.

Accessing the docker by `127.0.0.1` is working

Any help would be really appreciated

```
Running on macOS Sierra 10.12.3
Docker version 17.03.0-ce, build 60ccb22
docker-compose version 1.11.2, build dfed245
docker-machine version 0.10.0, build 76ed2a6
```

**Comment by samijnih** [comment]
I was updating the docker host file and not my mac host file.

**Comment by sjlouji** [comment]
hey @samijnih  did you find any solution for this issue. If so please do help me with this issue.  I amn't able to solve it
