### ISSUE TITLE
MySQL exists on first start

### ISSUE THREAD

**Issue by oleic** [laradock/laradock#664]
A brand new MySQL Container exists on first run. I am using laradock v4.19.0.

This is the output when running `docker-compose up nginx mysql`:

	mysql_1               | Initializing database
	mysql_1               | 2017-03-13T15:15:33.081588Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
	mysql_1               | 2017-03-13T15:15:33.081630Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
	mysql_1               | 2017-03-13T15:15:33.739471Z 0 [Warning] InnoDB: New log files created, LSN=45790
	mysql_1               | 2017-03-13T15:15:33.889219Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
	mysql_1               | 2017-03-13T15:15:33.994743Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: e77e2133-07ff-11e7-907b-0242ac120003.
	mysql_1               | 2017-03-13T15:15:34.006449Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
	mysql_1               | 2017-03-13T15:15:34.007002Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
	mysql_1               | 2017-03-13T15:15:37.593592Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:37.593714Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:37.593757Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:37.594194Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:37.594630Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | Database initialized
	mysql_1               | Initializing certificates
	mysql_1               | Generating a 2048 bit RSA private key
	mysql_1               | ...................................................................................................................................................................+++
	mysql_1               | ....................................+++
	mysql_1               | unable to write 'random state'
	mysql_1               | writing new private key to 'ca-key.pem'
	mysql_1               | -----
	mysql_1               | Generating a 2048 bit RSA private key
	mysql_1               | ..........+++
	mysql_1               | .........+++
	mysql_1               | unable to write 'random state'
	mysql_1               | writing new private key to 'server-key.pem'
	mysql_1               | -----
	mysql_1               | Generating a 2048 bit RSA private key
	mysql_1               | ...............................................................................................................................................................+++
	mysql_1               | ..............+++
	mysql_1               | unable to write 'random state'
	mysql_1               | writing new private key to 'client-key.pem'
	mysql_1               | -----
	mysql_1               | Certificates initialized
	mysql_1               | MySQL init process in progress...
	mysql_1               | 2017-03-13T15:15:41.290879Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
	mysql_1               | 2017-03-13T15:15:41.290932Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
	mysql_1               | 2017-03-13T15:15:41.291805Z 0 [Note] mysqld (mysqld 5.7.17) starting as process 80 ...
	mysql_1               | 2017-03-13T15:15:41.294161Z 0 [Note] InnoDB: PUNCH HOLE support available
	mysql_1               | 2017-03-13T15:15:41.294194Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
	mysql_1               | 2017-03-13T15:15:41.294201Z 0 [Note] InnoDB: Uses event mutexes
	mysql_1               | 2017-03-13T15:15:41.294206Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
	mysql_1               | 2017-03-13T15:15:41.294211Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
	mysql_1               | 2017-03-13T15:15:41.294223Z 0 [Note] InnoDB: Using Linux native AIO
	mysql_1               | 2017-03-13T15:15:41.294432Z 0 [Note] InnoDB: Number of pools: 1
	mysql_1               | 2017-03-13T15:15:41.294551Z 0 [Note] InnoDB: Using CPU crc32 instructions
	mysql_1               | 2017-03-13T15:15:41.295895Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
	mysql_1               | 2017-03-13T15:15:41.301031Z 0 [Note] InnoDB: Completed initialization of buffer pool
	mysql_1               | 2017-03-13T15:15:41.302401Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
	mysql_1               | 2017-03-13T15:15:41.314950Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
	mysql_1               | 2017-03-13T15:15:41.338038Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
	mysql_1               | 2017-03-13T15:15:41.338101Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
	mysql_1               | 2017-03-13T15:15:41.384724Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
	mysql_1               | 2017-03-13T15:15:41.385702Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
	mysql_1               | 2017-03-13T15:15:41.385734Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
	mysql_1               | 2017-03-13T15:15:41.386290Z 0 [Note] InnoDB: Waiting for purge to start
	mysql_1               | 2017-03-13T15:15:41.438117Z 0 [Note] InnoDB: 5.7.17 started; log sequence number 2534561
	mysql_1               | 2017-03-13T15:15:41.439278Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
	mysql_1               | 2017-03-13T15:15:41.439406Z 0 [Note] Plugin 'FEDERATED' is disabled.
	mysql_1               | 2017-03-13T15:15:41.441476Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170313 15:15:41
	mysql_1               | 2017-03-13T15:15:41.443701Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
	mysql_1               | 2017-03-13T15:15:41.443942Z 0 [Warning] CA certificate ca.pem is self signed.
	mysql_1               | 2017-03-13T15:15:41.457911Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:41.457956Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:41.457979Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:41.457989Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:41.459105Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:41.463619Z 0 [Note] Event Scheduler: Loaded 0 events
	mysql_1               | 2017-03-13T15:15:41.463801Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
	mysql_1               | 2017-03-13T15:15:41.463832Z 0 [Note] Beginning of list of non-natively partitioned tables
	mysql_1               | 2017-03-13T15:15:41.471742Z 0 [Note] End of list of non-natively partitioned tables
	mysql_1               | 2017-03-13T15:15:41.471771Z 0 [Note] Execution of init_file '/etc/mysql/startup' started.
	mysql_1               | 2017-03-13T15:15:41.472624Z 0 [Note] Execution of init_file '/etc/mysql/startup' ended.
	mysql_1               | 2017-03-13T15:15:41.472710Z 0 [Note] mysqld: ready for connections.
	mysql_1               | Version: '5.7.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
	mysql_1               | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
	mysql_1               | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
	mysql_1               | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
	mysql_1               | 2017-03-13T15:15:44.847905Z 6 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:44.848002Z 6 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:44.848035Z 6 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:44.848058Z 6 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | 2017-03-13T15:15:44.848176Z 6 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
	mysql_1               | mysql: [Warning] Using a password on the command line interface can be insecure.
	mysql_1               | mysql: [Warning] Using a password on the command line interface can be insecure.
	mysql_1               | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'homestead'@'%'
	laradock_mysql_1 exited with code 1

**Comment by alchimik** [comment]
see #649 and #583

**Comment by Mahmoudz** [comment]
closed in favor of #583
