### ISSUE TITLE
multiple projects setting problem : 404 Not Found

### ISSUE THREAD

**Issue by yoak1234** [laradock/laradock#665]
I used DigitalOcean.
I setting follow [Laradock/GettingStarted/Installation/B)SetupforMultipleProjects](http://laradock.io/getting-started/#installation) document for run multiple Laravel projects with Docker.
1. I edited laradock/docker-compose.yml.
![image](https://cloud.githubusercontent.com/assets/11187221/23865208/8812427c-0847-11e7-884c-dbda7508ce73.png)
2. I added **project1.conf** and **project2.conf** in **laradock/nginx/sites** then edit it.
![image](https://cloud.githubusercontent.com/assets/11187221/23865341/f2360fb2-0847-11e7-9e54-7b3485152da0.png)
![image](https://cloud.githubusercontent.com/assets/11187221/23865354/fef29f18-0847-11e7-93e1-4886ecd4cdab.png)
3. Then I added 2 lines include **127.0.0.1 project1.dev** and **127.0.0.1 project2.dev** in **etc/hosts**
![image](https://cloud.githubusercontent.com/assets/11187221/23865434/426e318a-0848-11e7-834b-dda492e95262.png)
3. And I installed Laravel framework in workspace container. Then run command 
`chmod 777 -R storage bootstrap/cache`
![image](https://cloud.githubusercontent.com/assets/11187221/23865502/838dc84c-0848-11e7-92b2-390dfa4f3f03.png)
4. I run command `docker-compose build nginx` and then run `docker-compose up -d nginx`
5. Finally, I browsed to **<my_ip>/project1** but nginx return **404 Not Found**.
![image](https://cloud.githubusercontent.com/assets/11187221/23865869/a0ff69f2-0849-11e7-9853-956d9a0d17a2.png)

I will appreciated if someone can help me.

ps. I did not quite good English if misprint was sorry,

**Comment by thorerik** [comment]
The issue is that you went to <my_ip>/project1, nginx is looking for http://project1.dev.

On your local machine, add 
```
<your digital ocean machine> project1.dev
<your digital ocean machine> project2.dev
```
to your /etc/hosts (on windows, this is C:\Windows\System32\drivers\etc\hosts), then you should be able to enter http://project1.dev and http://project2.dev

**Comment by Erchoc** [comment]
我们能说中文吗

**Comment by ghulam-mustafa** [comment]
Still it gives error.

**Comment by evantolorio** [comment]
Hi @ghulam-mustafa. Did you put the IP address of your digital ocean machine on your /etc/hosts file as what @thorerik suggested?
