### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by Nguonchhay** [laradock/laradock#674]
I got this error when run `docker-compose up -d nginx mysql redis beanstalkd`

```
Building mysql
Step 1/16 : FROM mysql:5.7
ERROR: Service 'mysql' failed to build: Get https://registry-1.docker.io/v2/library/mysql/manifests/5.7: unauthorized: incorrect username or password
```

**Comment by thorerik** [comment]
Not an issue with this project spesificly, docker.io is to blame.

Try `docker pull mysql:5.7` manually, if not, you'll probably have to ask over at the docker forums: https://forums.docker.com/
