### ISSUE TITLE
Call to undefined function imap_open()

### ISSUE THREAD

**Issue by akajack** [laradock/laradock#681]
Hi,
I am creating an artisan command that read the email and interprets it.
I'm using the [Zalazdi\LaravelImap](https://github.com/zalazdi/laravel-imap) package that, as many, uses the php function [imap_open()](http://php.net/manual/en/function.imap-open.php)
I added in file **php-fpm/laravel.ini**:
```
; IMAP
extension=imap.so
```
the file **php-fpm/Dockerfile-70** instead:
```
#RUN rm -r /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap
```
With phpinfo() I can see that imap is properly installed. However, the command keeps giving me this error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]     
Call to undefined function Zalazdi\LaravelImap\imap_open() 
```
I can not understand where I'm wrong :(
Thanks at all

**Comment by thorerik** [comment]
Does this happen outside laradock?

It looks to be an error in his code where he's incorrectly using the namespace before imap_open(), hence the full error showing the namespace before imap_open(), if imap_open was the failure, you'd see
```
Call to undefined function imap_open() 
```

**Comment by lab1353** [comment]
No, out laradock works perfectly, in different environments.
To find out if it was a code problem or not, I tried to make a simple php page, but it does not work. And the file is a simple php page with only the calls necessary `imap_`
The same code with Laravel both the php file, out Laradock, work properly without problems.
The php page code is:
```
<?php

$mail_server = 'imaps.myhost.com';
$mail_port = 993;
$mail_username = 'info@myhost.com';
$mail_password = '43n345h10Vxuch08ffssd8wxR';
$mail_folder = 'INBOX';

echo "<h1>".$mail_username." on ".$mail_server."</h1>\n\n" ;
$mbox = imap_open("{".$mail_server.":".$mail_port."/imap/ssl}$mail_folder", $mail_username, $mail_password) or die("Error opening mailbox: ".imap_last_error());
$mailboxheaders = imap_headers($mbox);
if ($mailboxheaders == false) {
    echo "<p>".$mail_folder." is empty.</p>\n\n";
} else {
    echo "<h2>".$mail_folder."</h2>\n" ;
    echo "<ol>\n" ;
    $msgno = 0;
    foreach ($mailboxheaders as $val) {
        $msgno++;
        echo "  <li>".$val ."</li>\n";
    }
    echo "</ol>\n\n" ;
}
imap_close($mbox);
```

**Comment by thorerik** [comment]
I hope you didn't just post your actual password @lab1353, even if everything else is obfuscated, suggest changing it ;)

OT: I'll have a poke at it and see if I can replicate the issue

**Comment by thorerik** [comment]
Quick test both with your provided script and ```
<?php
if (function_exists('imap_open')) {
    echo "IMAP functions are available.<br />\n";
} else {
    echo "IMAP functions are not available.<br />\n";
}
```
Yeilds that it works for me.

Also worth noting, you don't need to add `extension=imap.so` to laravel.ini, because docker-php-ext-configure adds it to the default include path anyways.

try rebuilding the image:
`docker-compose build --no-cache php-fpm`

**Comment by lab1353** [comment]
Yes yes @thorerik....the data are fake, thanks ;)
Now I try as you suggested and let you know if it works.
Thanks :)

**Comment by winfried-van-loon** [comment]
@akajack It has been a while, hopefully that means your issue was resolved. If you're still experiencing this issue, please feel free to let us know in a comment.

Closing this issue for now. 👍
