### ISSUE TITLE
Too many errors 

### ISSUE THREAD

**Issue by mhetreramesh** [laradock/laradock#683]
Got too many error, not sure whether am I doing something wrong? 

WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE variable is not set. Defaulting to a blank string.
WARNING: The DB_PORT variable is not set. Defaulting to a blank string.
WARNING: The SERVER_PORT variable is not set. Defaulting to a blank string.
WARNING: The SERVER_SSL_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mysql.ports is invalid: Invalid port ":3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.apache2.ports is invalid: Invalid port ":443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.apache2.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by Mahmoudz** [comment]
@mhetreramesh I'm cleaning up the project right now, closing old issues and closing/merging some PR's probably I merged a PR that causes this (I didn't have time to really test them all there are over 150 in total :P), as a quick solution for you reset --hard your code to old commit or use an older version just for today. Thanks and sorry for this.

**Comment by mhetreramesh** [comment]
Ok, let us know once this issue is fixed. Thanks

**Comment by Mahmoudz** [comment]
Done.

**Comment by mhetreramesh** [comment]
Now I'm getting below error

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (62e707fb876e45ff10b073cbaecb134bbb95e94849e27cbaa114db5e8bb4c78e): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.

**Comment by Mahmoudz** [comment]
@mhetreramesh checking that right now

**Comment by Mahmoudz** [comment]
#30cf27e011eb2d2c4f47f67fa783b00d63f208b5

**Comment by mhetreramesh** [comment]
No luck yet, now I'm getting below errors. (on docker-compose build --no-cache & docker-compose up -d nginx mysql redis beanstalkd )

WARNING: The WORKSPACE_INSTALL_YARN variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_INSTALL_DRUSH variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_INSTALL_AEROSPIKE_EXTENSION variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_INSTALL_INSTALL_V8JS_EXTENSION variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_COMPOSER_GLOBAL_INSTALL variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_INSTALL_WORKSPACE_SSH variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_INSTALL_LARAVEL_ENVOY variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_INSTALL_MC variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_PUID variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_PGID variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_NODE_VERSION variable is not set. Defaulting to a blank string.
WARNING: The WORKSPACE_TIMEZONE variable is not set. Defaulting to a blank string.
WARNING: The MEMCACHED_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The BEANSTALKD_HOST_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.memcached.ports is invalid: Invalid port ":11211", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.beanstalkd.ports is invalid: Invalid port ":11300", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.rabbitmq.ports is invalid: Invalid port ":15671", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.rabbitmq.ports is invalid: Invalid port ":15672", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.workspace.ports is invalid: Invalid port ":22", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.mariadb.ports is invalid: Invalid port ":3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.mysql.ports is invalid: Invalid port ":3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.apache2.ports is invalid: Invalid port ":443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx.ports is invalid: Invalid port ":443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.selenium.ports is invalid: Invalid port ":4444", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.postgres.ports is invalid: Invalid port ":5432", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.postgres-postgis.ports is invalid: Invalid port ":5432", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.rabbitmq.ports is invalid: Invalid port ":5672", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.apache2.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.phpmyadmin.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.minio.ports is invalid: Invalid port ":9000", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.elasticsearch.ports is invalid: Invalid port ":9200", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.elasticsearch.ports is invalid: Invalid port ":9300", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by Mahmoudz** [comment]
@mhetreramesh have you renamed `env-example` to `.env`? I forget to add this to the installation steps, I only added it to the quick overview section. Sorry for that.

**Comment by gazatem** [comment]
Same error occurring with fresh installation

**Comment by Mahmoudz** [comment]
@gazatem are you sure you have your `.env` file and you are getting this error? If yes please share your error.

**Comment by lisabonde** [comment]
First time used under existing Laravel project, can't run docker-compose ps command.. Errors are the same as 
above..
WARINNG: ............
..................................
WARNING: The BEANSTALKD_HOST_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.proxy.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.proxy2.expose is invalid:.................................
.................................

**Comment by winfried-van-loon** [comment]
@lisabonde Please, copy the `env-example` file to `.env`. Within the `.env` file, you can then set your preferences on what features you want Laradock to contain. Without the `.env`, you'll get these errors. 

On Linux and MacOS:
```
cp env-example .env
```

Source: http://laradock.io/ Step 2

**Comment by harryhan24** [comment]
same error. also i did 'cp env-example .env'
what you guys said not worked :-(

**Comment by winfried-van-loon** [comment]
In #865, @JakeYim said his docker-compose was outdated and that caused the same errors. Could you check your version?

**Comment by harryhan24** [comment]
@winfried-van-loon yes i did.. i just reinstalled everything. so now it wor. so i guess that is my problem.
sorry about it

**Comment by valdezalbertm** [comment]
@winfried-van-loon it works!

**Comment by skyjerry** [comment]
The same error, because I did not execute in the laradock directory.😶......

**Comment by ahmedeagle** [comment]
it works
