### ISSUE TITLE
Lack of production documentation

### ISSUE THREAD

**Issue by CharlieTap** [laradock/laradock#685]
Hi,

I noticed in the docs it references a production compose yaml file but nothing seems to be present in repo?

Also are you looking to expand the section on deployment into production? realistically you shouldn't be mounting a volume for the Laravel application code in the live environment and instead should be copying that into your own image.
For scalability you could probably roll FPM and nginx into a single image, and then possible a load balancing container like haproxy or even another nginx container. Understandably the current repo is built for flexibility whilst in the development env, but with a little more on the steps to production this could be the complete solution.

**Comment by Mahmoudz** [comment]
@CharlieTap that's why we removed it #524. Please read my answer here #668 for the why. Checkout #davehensley answer #244 here for "Deploying to Amazon Elastic Beanstalk".

**Comment by deleugpn** [comment]
+1 here. I'm starting to study Docker and after playing with some settings I'm starting to understand what Laradock provides, which is quite incredible. Yet, I see some hard concepts I yet need to figure out to get it from local to production on Amazon.
