### ISSUE TITLE
Class 'Memcached' not found

### ISSUE THREAD

**Issue by Gummibeer** [LaraDock/laradock#69]
> Script php artisan clear-compiled handling the post-install-cmd event returned with an error
>                                                                                                                           
>   [RuntimeException]                                                                                                       
>   Error Output: PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php:51    
>                                                                      
>   Stack trace:                                                                                                             
>   #0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php(20): Illuminate\Cache\MemcachedConnector->getMemcached()                                                                                               
>   #1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(164): Illuminate\Cache\MemcachedConnector->connect(Array)                                                                                                    
>   #2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(102): Illuminate\Cache\CacheManager->createMemcachedDriver(Array)                                                                                            
>   #3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(77): Illuminate\Cache\CacheManager->resolve('memcached')                                                                                                     
>   #4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(55): Illuminate\Cache\CacheManager->get('memcached')                                                                                                         
>   #5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(66): Illuminate\Cache\CacheManager->store('memcached')                                                                                                       
>   #6 /var/www/laravel/vendo in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 51
>                                                                                                                  
>   PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php:51                                                                                       
>   Stack trace:                                                                                                             
>   #0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php(20): Illuminate\Cache\MemcachedConnector->getMemcached()                                                                                               
>   #1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(164): Illuminate\Cache\MemcachedConnector->connect(Array)                                                                                                    
>   #2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(102): Illuminate\Cache\CacheManager->createMemcachedDriver(Array)                                                                                            
>   #3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(77): Illuminate\Cache\CacheManager->resolve('memcached')                                                                                                     
>   #4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(55): Illuminate\Cache\CacheManager->get('memcached')                                                                                                         
>   #5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(66): Illuminate\Cache\CacheManager->store('memcached')                                                                                                       
>   #6 /var/www/laravel/vendo in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 51

This error occurs when I connect to the workspace and run any kind of artisan command. Even if I not use memcached as the cache driver. :/

Solution was to require `php7.0-memcached` in the workspace Dockerfile. In my opinion it isn't good to have two configurations of php for the same application. Is there any solution to use the php-cli from the php-fpm container? Or have an extra php-cli container to know that there are these two different containers and the structure of both is the same?

**Comment by Mahmoudz** [comment]
@Gummibeer that's because we are missing the installation of `memcached` in the workspace container (PHP-CLI). If you like you can add it and create a PR. Also you can check the PHP-CLI dockerfiles where we have it installed.

**Comment by Mahmoudz** [comment]
Closed by #70
