### ISSUE TITLE
ERROR: Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by phpmaple** [laradock/laradock#690]
when I run `docker-compose up -d nginx mysql redis beanstalkd`, 

it shows:
 `Step 32/40 : RUN if [ ${INSTALL_INTL} = true ]; then     apt-get install -y zlib1g-dev libicu-dev g++ &&     docker-php-ext-configure intl &&     docker-php-ext-install intl ARG GHOSTSCRIPT=false
 ---> Running in 7ecf73bd5658
/bin/sh: 1: Syntax error: end of file unexpected (expecting "fi")
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_INTL} = true ]; then     apt-get install -y zlib1g-dev libicu-dev g++ &&     docker-php-ext-configure intl &&     docker-php-ext-install intl ARG GHOSTSCRIPT=false' returned a non-zero code: 2`

**Comment by davidtaboas** [comment]
In file php-fpm/Dockerfile-70 exists this block of code:

```

ARG INSTALL_INTL=false
RUN if [ ${INSTALL_INTL} = true ]; then \
    # Install intl and requirements
    apt-get install -y zlib1g-dev libicu-dev g++ && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl \

```
You have to add on the end of this block `;fi`:

```
ARG INSTALL_INTL=false
RUN if [ ${INSTALL_INTL} = true ]; then \
    # Install intl and requirements
    apt-get install -y zlib1g-dev libicu-dev g++ && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl \
;fi
```


I made a pull request for fix this: https://github.com/laradock/laradock/pull/691

**Comment by phpmaple** [comment]
and it show:

`ERROR: for applications  Cannot create container for service applications: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.`

**Comment by Rozbo** [comment]
I meet this too.

**Comment by phpmaple** [comment]
@Rozbo I solved this, you can set APPLICATION=xxx in .env file

**Comment by phpmaple** [comment]
When I run `docker-compose up -d nginx mysql redis beanstalkd` success, 
but localhost did not work, it show 404, I already set map to my project

**Comment by Rozbo** [comment]
@phpmaple ok ,I will try it, thank you very much!

**Comment by zhangrxiang** [comment]
@phpmaple 但是我这还是有这个错误？
![image](https://cloud.githubusercontent.com/assets/11625343/24074332/7c088240-0c41-11e7-80c4-a41aac55dabb.png)
![image](https://cloud.githubusercontent.com/assets/11625343/24074343/a14396d0-0c41-11e7-99e3-b72338331dff.png)

**Comment by phpmaple** [comment]
@zhangrxiang  你需要重新build一下images

**Comment by zhangrxiang** [comment]
谢谢，问题解决了
