### ISSUE TITLE
Getting syntax error on step 32/40

### ISSUE THREAD

**Issue by tblancog** [laradock/laradock#693]
```
Step 32/40 : RUN if [ ${INSTALL_INTL} = true ]; then     apt-get install -y zlib1g-dev libicu-dev g++ &&     docker-php-ext-configure intl &&     docker-php-ext-install intl ARG GHOSTSCRIPT=false
 ---> Running in 889a3ca4a821
/bin/sh: 1: Syntax error: end of file unexpected (expecting "fi")
ERROR: Service 'php-fpm' failed to build:
```

Steps to reproduce:
1. Cloned laradock
`git clone https://github.com/laradock/laradock.git dckr
`
2. copied env example
`cp env-example .env
`
3. Launch containers
`docker-compose exec workspace bash
`

**Comment by Mahmoudz** [comment]
@tblancog probably this type was fixed. Can you try again, if it is fixed please close this otherwise let me know to fix it. it's only missing `fi`

**Comment by tblancog** [comment]
@Mahmoudz Tried again and it worked.
Thanks!
