### ISSUE TITLE
ERROR: Service 'hhvm' failed to build

### ISSUE THREAD

**Issue by phpmaple** [laradock/laradock#695]
E: Unable to locate package hhvm
ERROR: Service 'hhvm' failed to build: The command '/bin/sh -c apt-get update -y     && apt-get install -y software-properties-common     && add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"     && apt-get update -y     && apt-get install -y hhvm     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by thorerik** [comment]
try re-running it, I'm unable to reproduce the issue, and considering the error it sounds like the issue could be that the repository was unavailable.

If you're still having issues, check that you can reach http://dl.hhvm.com/ubuntu/dists/trusty/

You should see a bunch of files, among them Release, Release.gpg and InRelease

**Comment by lyairmg** [comment]
Hi, I solved by changing the following line

`RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449`
for
`RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 BBEBDCB318AD50EC6865090613B00F1FD2C19886`
in file `hhvm/Dockerfile`

the key used belongs to ubuntu 14.04lts, but the code installs the last lts of ubuntu
**I'm sorry for my English**
