### ISSUE TITLE
Running Container - Error (PMA_password variable not set)

### ISSUE THREAD

**Issue by jaasaria** [laradock/laradock#697]
Hope someone could help me on this error. Please see 

![container](https://cloud.githubusercontent.com/assets/5240819/24074469/518c189e-0c44-11e7-8019-161323479f38.png)

**Comment by hnquang112** [comment]
Perhaps missing the `.env` file

**Comment by jaasaria** [comment]
.env file is exist. actually im running by app using xampp and wanted to use docker. hope some could give idea.

**Comment by gazatem** [comment]
Still same. I think docker compose can not read from .env file 

I'm using imac with zssh. I able to run other dockers without any error.

**Comment by amadeann** [comment]
I was getting the same messages and renaming env-example to .env _inside_ the laradock directory fixed the issue.

**Comment by winfried-van-loon** [comment]
Yep, these errors are almost always caused by the dotenv file within Laradock. Follow the steps in the documentation: http://laradock.io/getting-started/#usage (step 1)
