### ISSUE TITLE
Support MongoDB

### ISSUE THREAD

**Issue by Mahmoudz** [LaraDock/laradock#7]
Need a MongoDB Docker container.

**Comment by tristanbailey** [comment]
MongoDB is a little more fiddly as you need to remember you need the client installed with php and also the php extension. There was some issues last year getting it to compile in limited images, so one to watch for

**Comment by edbizarro** [comment]
+1

**Comment by JoeyHoutenbos** [comment]
+1

**Comment by Mahmoudz** [comment]
#f3eb6a5fc4fd11016e0fb157ea28ab5b3033d3a1
