### ISSUE TITLE
Can not connect to the postgres DB

### ISSUE THREAD

**Issue by davidavz** [laradock/laradock#702]
I've just updated my laradock repo, deleted/rebuilt every containers.

I used to use pgadmin to check my database and now i just can't connect to the database.

I also tried to bash into the postgres container but I have the `password authentication failed for user "XXX"`

I just don't understand the issue here. I thought it would be relative to the new env variables but i'm not sure now.

Do you have any idea?

**Comment by Mvzundert** [comment]
If it was an existing DB it wouldn't have new credentials as the DB's are stored locally by default.

**Comment by davidavz** [comment]
I deleted all images and containers to restart clean.

Now I can't even start the postgres container, it stop few seconds after my `docker-compose up -d ...`

And if I try to enter this container I have 
````
The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.1.
````

**Comment by davidavz** [comment]
The problem was the volumes.

I just try a `docker system prune` to remove all.

Now it's OK with fresh new containers.
