### ISSUE TITLE
Missing APPLICATION variable in yml file

### ISSUE THREAD

**Issue by infacq** [laradock/laradock#703]
I hit this error when run `docker-compose up -d nginx mysql` on initial setup

```bash
WARNING: The APPLICATION variable is not set. Defaulting to a blank string.
Creating network "laradock_default" with the default driver
Creating laradock_mysql_1
Creating laradock_applications_1

ERROR: for applications  Cannot create container for service applications: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

is there any missing steps in docs?

**Comment by Mvzundert** [comment]
Did you copy the env-example file to a .env file ?

**Comment by zeroc0d3** [comment]
You need to:
1) copy env-example to .env, as @Mvzundert mention it
2) add line `APPLICATION=../` or `APPLICATION=../[project_folder]` in your .env file

**Comment by cjmling** [comment]
I have to same problem. APPLICATION key is not set but not sure what value I should set there.   For example my laravel project on my Mac is at .. _Users\USERNAME\docker-web-project\testproject\_ 

What value I should put there as APPLICATION = ?? 

Thanks 

### Application
# Point to your application code, wish should be available at `/var/www`

### PHP version (Does not apply for HHVM)
# PHP_VERSION=55
# PHP_VERSION=56
PHP_VERSION=70

**Comment by Mvzundert** [comment]
Hi @cjmling 

it's relative to the laradock location. So for example, if laradock is in users/USERNAME/docker-web-project/laradock you'd set the it to APPLICATION = ../ 

It depends on the location of your laradock relative to the folder(s) you're trying to map.

**Comment by Mahmoudz** [comment]
That was my mistake, while developing this feature I edit my `.env` file and forget to also edit the `env-example` file. I fixed it now, the `APPLICATION = ../` is back.

**Comment by infacq** [comment]
I still got 404 nginx not found using `APPLICATION = ../`. My structure project as below

-ProjectDir
  -laradock

**Comment by Mvzundert** [comment]
Whats in the project dir? Can you include a screenshot?

**Comment by infacq** [comment]
<img width="205" alt="screen shot 2017-03-26 at 12 52 09 pm" src="https://cloud.githubusercontent.com/assets/1596891/24328892/b5785c84-1228-11e7-948a-a47cafa5f5fc.png">
