### ISSUE TITLE
Define a specific static IP for nginx

### ISSUE THREAD

**Issue by ntopulos** [laradock/laradock#705]
I need to define the IP of the nginx container.

I followed the instructions from #535, and it worked for some time, but it doesn't anymore. Maybe something changed with the last commits or maybe I was just lucky to have it work on the first place thanks to some mess up with my docker networks.

Does someone got it working ?

Here is my trial.

In **.env** I added:

    GATEWAY_IP=127.0.0.45
    SUBNET=127.0.0.0/24

In **docker-compose.yml** I added the new network definition:

    networks:

        static-network:
            driver: bridge
            ipam:
                driver: default
                config:
                - subnet: "${SUBNET}"
                  gateway: "${GATEWAY_IP}"

The nginx configuration in **docker-compose.yml** becomes:

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${GATEWAY_IP}:${NGINX_HOST_HTTP_PORT}:80"
            - "${GATEWAY_IP}:${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        networks:
            - static-network
            - default

When I run``docker-compose up -d nginx``, the nginx container crashes immediately and nginx reports this error:

    [emerg] 1#1: host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/upstream.conf:1

When I set the networks of nginx image with ``static-network`` only (without ``default``), the ``docker-compose`` crashes:

    ERROR: for nginx  Cannot start service nginx: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 0 caused \"error running hook: exit status 1, stdout: , stderr: time=\\\"2017-03-21T10:00:00Z\\\" level=fatal msg=\\\"failed to set gateway while updating gateway: route for the gateway 127.0.0.45 could not be found: invalid argument\\\" \\n\""
    Encountered errors while bringing up the project.

**Comment by mitjarobic** [comment]
i get the same problem... no changes to initial settings

nginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/upstream.conf:1

**Comment by ntopulos** [comment]
I also tried adding a longer timeout to the nginx upstream definition on line 17 of the nginx Dockerfile:

    && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000 fail_timeout=60s max_fails=2; }" > /etc/nginx/conf.d/upstream.conf

It doesn't appear to have any effect, the nginx container still crashes after about 2s.

**Comment by mitjarobic** [comment]
after rebuild in restart it works now

docker rm -f $(docker ps -qa)
docker rmi $(docker images -qa --digests)
docker-compose up --build -d nginx mysql

**Comment by ntopulos** [comment]
@mitjarobic I tried removing all images, recloning laradock and rebuilding containers, but I still get this php-upstream error.  
Could you please show your configuration files?

**Comment by mitjarobic** [comment]
@ntopulos settings are default...haven't changed a line. But when it happens, i need to restart my computer.

**Comment by Snaver** [comment]
I think you need to assign nginx a unique IP, from your example you're reusing the gateway IP? 

You should be able to follow my example here to fix https://github.com/laradock/laradock/issues/435#issuecomment-315064141
