### ISSUE TITLE
Recompile PHP with --enable-calendar

### ISSUE THREAD

**Issue by berdam** [laradock/laradock#709]
Certain functions like cal_days_in_month() are not available with default config, because of missing calendar support. 

Solution is probably to recompile php with --enable-calendar option according to this:
http://stackoverflow.com/a/9240933

Any ideas how to do that?

**Comment by alchimik** [comment]
You can add line `RUN docker-php-ext-install calendar` in file `php-fpm/Dockerfile-70`

**Comment by berdam** [comment]
Works! Thank you!
