### ISSUE TITLE
PHPUnit not working on the workspace container

### ISSUE THREAD

**Issue by CharlieTapSonin** [laradock/laradock#713]
Any combination of:
phpunit 
./vendor/bin/phpunit 
/vendor/bin/phpunit

all results in no such file or directory

**Comment by thorerik** [comment]
How about `~/.composer/vendor/bin/phpunit`?

**Comment by CharlieTapSonin** [comment]
No luck unfortunately

**Comment by thorerik** [comment]
How did you install phpunit?
