### ISSUE TITLE
Neo4j auth error

### ISSUE THREAD

**Issue by KyawNaingTun** [laradock/laradock#719]
Hello everybody
Please help me. I can't login to neo4j server(http://localhost:7474) and then Neo4j version is out of date. So, how can i upgrade neo4j version(3)?
 My console error message is follow:
`http://beatnana.docker.dev:7474/db/data/ Failed to load resource: the server responded with a status of 401 (Unauthorized)`
![neo4j](https://cloud.githubusercontent.com/assets/6079250/24353534/03005e02-1314-11e7-872f-7974d7ebfaef.png)

Thanks

**Comment by thorerik** [comment]
For updating neo4j, try reverting 06c4c19a6fc7a0f85782002344017bec16f8deff or use the latest tag from the official neo4j image.

**Comment by darkeus** [comment]
@KyawNaingTun i think you should use username default and password secret, it was specified in docker-compose.yaml on neo4j service
