### ISSUE TITLE
default config : ERROR: for application  Container command 'true' not found or does not exist.

### ISSUE THREAD

**Issue by parkshinhye** [LaraDock/laradock#72]
```
ERROR: for application  Container command 'true' not found or does not exist.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

**Comment by Mahmoudz** [comment]
@parkshinhye I need your help reproducing this error. Which command caused it (what containers are you trying to build or run)?

**Comment by parkshinhye** [comment]
@Mahmoudz  i use defalut Config; i run `docker-compose up  nginx mysql redis` 

errors is `application`  containers

**Comment by parkshinhye** [comment]
@Mahmoudz  
> docker version

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Mon May 23 20:50:37 2016
 OS/Arch:      linux/amd64
```

> docker-compose version 

```
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by Mahmoudz** [comment]
@parkshinhye I wasn't able to reproduce that, however can you try doing these general steps:

1. Stop and remove all the containers (or just the application container) with `docker-compose down`.
2. Pull the latest version: `git pull origin master`.
3. Remove all the images (or just the application) with `docker rmi {image-id}` also remove all the `<none>` images the same way. To list all your images type `docker images`.
4. Rebuild the containers `docker-compose build --no-cache nginx mysql redis`.
5. Try again.

**Comment by parkshinhye** [comment]
@Mahmoudz 
 I am Chinese users, for some inexplicable reason, I will build field image instead, to use the docker images
I am using is ali cloud docker automated build service!!!!!!
I think this is not the cause of this error!!!!!!!!!
Ali cloud automated build docker version for `1.10.3`

**Comment by parkshinhye** [comment]
@Mahmoudz

```
workspace:
        image:  registry.aliyuncs.com/parkshinhye/workspace
        volumes:
            - ./web:/var/www
        tty: true
```

**Comment by parkshinhye** [comment]
@Mahmoudz It could be 10, Windows docker, docker beta, VirtualBox between bugs,
It is possible that the server automatically build the bug,
I changed the Windows 7 with hub.docker.com an automated build, run docker, no bug,
So, I'm sorry to disturb you

**Comment by lialosiu** [comment]
@parkshinhye It maybe not a bug, but a misstake.
I have same issue today, and I found the probleam is I changed `docker-compose.yml` files to 

```yml
### Laravel Application Code Container ######################

    application:
        build: ./application
        volumes:
            - ../:/var/www
```

removed `/laravel` subfolder

when I run docker-compose up application, will throw this: `ERROR: for application Container command 'true' not found or does not exist.`

Because in `application\Dockerfile` file, `WORKDIR /var/www/laravel`

That mean if the image dockerfile workdir *NOT EXIST*, `CMD ["true"]` will let you got `ERROR: for application Container command 'true' not found or does not exist.`.
