### ISSUE TITLE
How to set php max file size?

### ISSUE THREAD

**Issue by hidace** [laradock/laradock#721]
HI, 

I'm using Laradock with Craft CMS. I'm trying to upload a file that's 70MB, but am getting a 

`file could not be uploaded, because it exceeds the maximum upload size of 16.0 MB.`

Where can I update this in Laradock? I thought it might be in the laradock/php-fpm/laravel.ini file. Here's what mine looks like now:

```
date.timezone=UTC
display_errors=Off
log_errors=On

; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 128M
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 128M
; Sets max size of post data allowed.
; http://php.net/post-max-size
post_max_size = 128M
```

After updating, I stopped all containers and re-started them. Is there a step I'm missing? Thank you!

**Comment by hidace** [comment]
**SOLVED:** 

So I got this working. What I had to do is also adjust my nginx configuration (in the `laradock/nginx/nginx.conf` file) by extending the `keepalive_timeout 120` (originally it was set to 15). So my `nginx.conf` file now looks like this:
```

user www-data;
worker_processes 4;
pid /run/nginx.pid;
daemon off;

events {
  worker_connections  2048;
  multi_accept on;
  use epoll;
}

http {
  server_tokens off;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 120;
  types_hash_max_size 2048;
  client_max_body_size 90M;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;
  gzip on;
  gzip_disable "msie6";
  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-available/*;
  open_file_cache max=100;
  charset UTF-8;
}
```

After doing this (and updating my laravel.ini settings from the post above), I stopped all running containers from the `laradock` directory by running `docker stop $(docker ps -a -q)` then deleted my nginx and php-fpm containers by running `docker rm php-fpm` and `docker rm nginx`. 

Then, I re-built my nginx and php-fpm containers to make sure there wasn't a weird caching issue that was causing the problem by running:

`docker-compose build --no-cache php-fpm`
`docker-compose build --no-cache nginx`

Afterwards, I was able to upload my 70MB file. Hope this helps!

**Comment by bharatgupta99** [comment]
The upload size if updated in phpinfo() but its not getting reflected in phpmyadmin.

**Comment by rizkysyazuli** [comment]
not sure about adding the `keepalive_timeout`. but rebuilding the container works for me. phpinfo() inside the php-fpm container always shows the old values until I rebuild it. so weird and so annoying.
