### ISSUE TITLE
mysql_connect adapter?

### ISSUE THREAD

**Issue by sid606** [laradock/laradock#722]
Hi I have legacy project that run on php 5.6 but the tricky part is that it need mysql_connect() to work. Is there any way to enable this in laradock with apache2 php-fpm  mysql redis?

I added this `docker-php-ext-install mysql` but still no luck

**Comment by alchimik** [comment]
`docker-php-ext-install mysql` work fine for me
Don't forget to rebuild the image - `docker-compose build --no-cache php-fpm`
Which file you edit?

**Comment by sid606** [comment]
I edit Dockerfile-56 and added 
`ARG INSTALL_MYSQL=true
RUN if [ ${INSTALL_MYSQL} = true ]; then \  
     docker-php-ext-install mysql \
;fi`

after save i run docker-compose build --no-cache php-fpm but no luck

**Comment by Mahmoudz** [comment]
Closed by @winfried-van-loon #738
