### ISSUE TITLE
YARN version

### ISSUE THREAD

**Issue by markhilton** [laradock/laradock#723]
docker-compose.yml workspace pulls variable for YARN version from timezone 

YARN_VERSION=${WORKSPACE_TIMEZONE}

and if .env WORKSPACE_INSTALL_YARN=true then during build process throws an error: 

> Version number must match MAJOR.MINOR.PATCH.

I've created a new environment variable: WORKSPACE_YARN_VERSION=latest and used it in docker-compose.yml and that fixed the issue.

**Comment by thorerik** [comment]
Make sure you've pulled the latest version, it was fixed with 894cb6ea270db0f4975156182e0af1638d729664
