### ISSUE TITLE
workspace and php-fpm should run the same PHP version

### ISSUE THREAD

**Issue by ntopulos** [laradock/laradock#724]
The workspace and php-fpm do not run the same PHP version:

    workspace: PHP 7.0.14-2+deb.sury.org~xenial+1 
    php-fpm: PHP 7.0.9 (cli) (built: Aug 10 2016 19:45:48)

It means that if one uses the workspace container - as intended - to execute `composer` commands, the installed dependencies will then be executed on another version of PHP.

I haven't yet found out how to configure both images to get exactly the same PHP version. Any idea ?

___

When setting the PHP version to 7.1 in the `.env` file, it is even worse: the php-fpm container runs PHP 7.1 and the workspace container PHP 7.0.

To solve this latter issue, I would suggest removing `WORKSPACE_DOCKER_FILE` from **.env** and relying only on the `PHP_VERSION` argument.  
In the **docker-compose.yml** I would replace:

        dockerfile: ${PHP_FPM_DOCKER_FILE}

by:

        dockerfile: "dockerfile-${PHP_VERSION}"

And, of course add this same line to the ``workspace`` block.  
This would also solve #714.

What do you think?

**Comment by Mahmoudz** [comment]
That looks a nice idea, thanks for the suggestion. Would you mind submitting a PR?
