### ISSUE TITLE
gulp watch not working in workspace 

### ISSUE THREAD

**Issue by suncoastkid** [laradock/laradock#725]
Running `gulp watch` in workspace does not work with Dockerfile-70. It compiles once when called but never detects changes. Running `gulp` manually after every change is painful.

**Comment by suncoastkid** [comment]
Turned out to be an IDE bug. All good.

**Comment by suncoastkid** [comment]
Turned out to be an IDE bug. All good.

**Comment by leandrosousa** [comment]
I have the same problem. How to solve it?
