### ISSUE TITLE
php-worker config file is broken

### ISSUE THREAD

**Issue by gufoe** [laradock/laradock#731]
Hello, the the php-worker [supervisor.conf](https://github.com/laradock/laradock/blob/master/php-worker/supervisord.conf) file has hardcoded references to the folder `/var/www/laravel/artisan` while it should just be `/var/www/artisan`

**Comment by winfried-van-loon** [comment]
This issue seems to be fixed in #732, so I'm closing this issue. However if you're still experiencing this issue, please feel free to let us know in a comment. 👍

**Comment by ben-joostens** [comment]
How exactly do you set this up in a multi-project setup as described in the docs? Not updating the path in `docker-compose.yml` to have it point to one of the projects' directories leads to `Could not open input file: artisan`. But if I do point it to a directory of one of the projects, it doesn't log any errors but nothing from the queue is being processed either.
