### ISSUE TITLE
xdebug on Mac needs nginx REMOTE_ADDR set

### ISSUE THREAD

**Issue by novalis111** [laradock/laradock#733]
I tried to get xdebug working on a Mac, setting my local IP (192.168.1.51) as DOCKER_HOST_IP in .env. Remote Debugging on CLI worked, but Web Debug did not. 

- xdebug IDE key = PHPSTORM
- xdebug.remote_autostart=1 + xdebug.remote_enable=1

But xdebug wouldn't connect to the docker host. The problem is in the nginx server config, where you have to pass the IP of the host as REMOTE_ADDR:

<pre><code>
    location ~ \.php$ {  
        try_files $uri /index.php =404;  
        fastcgi_pass php-upstream;  
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REMOTE_ADDR "192.168.1.51";
        include fastcgi_params;
    }
</code></pre>

I couldn't figure out how to set it from .env though, nginx only accepts IP addresses here. After setting that, the xdebug connection worked flawlessly. Would be great to add this to your PHPStorm guide. I think this is a Mac Problem, b/c the routing is done differently.

**Comment by yangliuyu** [comment]
Got xdebug works with `https://github.com/DevinY/dlaravel` (https://www.youtube.com/watch?v=IdMs5LjbEX0) which not modify REMOTE_ADDR. When I open the root page of the laravel project in web browser, phpstorm prompt a remote connection(xdebug) event. But for laradock, it seems no connection started from the docker.

**Comment by novalis111** [comment]
That's because nginx + php is in same docker container. The IP gets rewritten by nginx in laradock, so php container doesn't get the correct remote address. Setting REMOTE_ADDR fixes that.

**Comment by yangliuyu** [comment]
@novalis111 It works now, thanks 😄  I changed the directive orders below.
```
include fastcgi_params;
fastcgi_param REMOTE_ADDR "192.168.1.51";
```

**Comment by coyl** [comment]
https://github.com/LaraDock/laradock/issues/393#issuecomment-299147584 here is more classy solution =)

**Comment by pouya-daneshvar-freelands-it** [comment]
what should i put instead of 192.168.1.51 ? the ip address where i have the IDE ?
