### ISSUE TITLE
CI integration to auto-generate the Hugo docs

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#735]
Noticed the contributions to the docs became so slow, after moving to hugo... Would cool if anyone can find a good CI service to build the site automatically after each commit. This way users will only update the text in the markdown files without worrying about regenerating the site.

**Comment by computerfr33k** [comment]
I would recommend using Travis CI, https://travis-ci.org/

**Comment by computerfr33k** [comment]
Here's a repo I setup to test deployment with Travis CI, https://github.com/computerfr33k/hugo-gh-pages-test .

You can get an idea on how to set it up from there.
Documentation: https://docs.travis-ci.com/user/deployment/pages/

**Comment by dtunes** [comment]
Not particularly related to this ticket, but noticed that when running hugo from DOCUMENTATION/_settings, the docs generated don't match the existing folder structure.

before:
docs/getting-started/{index.html, index.xml}

after running hugo:
docs/getting-started/index/index.html
docs/getting-started/index.xml

```sh
hugo env
Hugo Static Site Generator v0.20 darwin/amd64 BuildDate: 2017-04-11T13:43:59+12:00
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.8.1"
```

Was about to send a PR for percona container.

Any tips? Don't want to screw with the documentation.

**Comment by dtunes** [comment]
Hi, really keen to push this PR through, just need some help with hugo. As I mentioned above, deleting the docs folder and running hugo to regenerate the docs, causes the a subfolder to be created before the index.html files, but its affecting other *.html files as well.

This is the git status after running hugo.

```sh
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   DOCUMENTATION/_settings/content/getting-started/index.md
	modified:   docker-compose.yml
	deleted:    docs/contributing/index.html
	modified:   docs/contributing/index.xml
	deleted:    docs/documentation/index.html
	modified:   docs/documentation/index.xml
	deleted:    docs/getting-started/index.html
	modified:   docs/getting-started/index.xml
	deleted:    docs/help/index.html
	modified:   docs/help/index.xml
	modified:   docs/index.html
	modified:   docs/index.xml
	deleted:    docs/introduction/index.html
	modified:   docs/introduction/index.xml
	deleted:    docs/license/index.html
	modified:   docs/license/index.xml
	deleted:    docs/related-projects/index.html
	modified:   docs/related-projects/index.xml
	modified:   docs/sitemap.xml
	modified:   env-example

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/404.html
	docs/categories/
	docs/contributing/index/
	docs/documentation/index/
	docs/getting-started/index/
	docs/help/index/
	docs/index/
	docs/introduction/index/
	docs/license/index/
	docs/related-projects/index/
	docs/tags/
	percona/

no changes added to commit (use "git add" and/or "git commit -a")
```

@Mahmoudz do you have any idea what's causing this behaviour in hugo?

**Comment by computerfr33k** [comment]
The docs folder is what is defined as the directory for which hugo stores the generated site. These settings are stored under `DOCUMENTATION/_settings/config.toml`

**Comment by computerfr33k** [comment]
@dtunes have you explored the hugo website to learn more about it? http://gohugo.io/

**Comment by dtunes** [comment]
Yep, just following exactly the instructions given on http://laradock.io/contributing/#i-want-to-update-the-documentation-site.

**Comment by Mahmoudz** [comment]
@computerfr33k Thanks man, that's awesome. 

Could you please check if there's any error with the travis file 3a7e6e4b1a06393d97f069b103e4e886c79ad0fe

## Here's my putput:
![screencapture-travis-ci-org-laradock-laradock-builds-222000410-1492157168007](https://cloud.githubusercontent.com/assets/1983984/25037572/dbc01078-20c7-11e7-9125-1379075ead79.png)

**Comment by bestlong** [comment]
try to change local_dir: to docs or ../../docs

**Comment by computerfr33k** [comment]
The `local_dir` variable should be defined the same as hugo's `publishDir`. So, setting `local_dir` to `../../docs` should fix the deployment.

**Comment by Mahmoudz** [comment]
@computerfr33k @bestlong thank you guys, this supposed to be working now https://travis-ci.org/laradock/laradock
