### ISSUE TITLE
[emerg] 1#1: open() "/var/log/nginx/access.log" failed (13: Permission denied)

### ISSUE THREAD

**Issue by wanfeiyy** [laradock/laradock#746]
I'm using docker for CentOS7
when I run ```docker-compose up -d nginx mysql redis```
```
laradock_mysql_1          docker-entrypoint.sh mysql ...   Up       0.0.0.0:3306->3306/tcp 
laradock_nginx_1          nginx                            Exit 1                          
laradock_php-fpm_1        php-fpm                          Up       9000/tcp               
laradock_redis_1          docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp 
laradock_workspace_1      /sbin/my_init                    Up       0.0.0.0:2222->22/tcp  

```
nginx doesn't work
when run ```docker-compose up nginx```
it shows
```
nginx_1               | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1               | 2017/04/05 05:59:52 [emerg] 1#1: open() "/var/log/nginx/access.log" failed (13: Permission denied)
laradock_nginx_1 exited with code 1
```

**Comment by winfried-van-loon** [comment]
Have you updated to the latest version of Laradock? It may have been already fixed in commit 585baf06

**Comment by wanfeiyy** [comment]
after updated to the latest version ,Still stuck
```
Attaching to laradock_nginx_1
nginx_1               | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
nginx_1               | 2017/04/06 03:44:53 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
laradock_nginx_1 exited with code 1
```

**Comment by Mahmoudz** [comment]
@wanfeiyy try to rebuild the Container with `--no-cache`

**Comment by wanfeiyy** [comment]
rebuild the container still encounter the same issue

**Comment by winfried-van-loon** [comment]
Okay, perhaps try the following things. 

- Try to switch out what happened on commit 585baf0. Debug a bit, see if some of the variations are working
- Check if the `/var/log/nginx/error.log` file exists. See if it has unexpected file rights, file owner or group.
- Check the same for the parent directory. 
- Try removing the whole error log file. And/or the folder. Or create them, if not existing. Try creating the directory then the file itself.
- Try updating the Docker compose file and/or the relevant Dockerfile settings. The error has to come from somewhere.

Sorry to have to say I haven't got time to try these things for you at the moment. Perhaps in the weekend, if I can find the time time. Having said that, I'm not an expert at these things myself: may not be able to fix it, either. Just try, see if you can debug the issue yourself, get more information about the problem or even fix it yourself until contributors/members and others can. 👍  Good luck!

**Comment by winfried-van-loon** [comment]
Closing this issue for now, if your issue still persists after updating to the latest version of Laradock, please let us know and we'll look into it.

**Comment by vitoo** [comment]
I have the same issue on my fedora (kde) laptop
but not on my fedora (cinnamon) PC 

i've tried to chmod 777 -R  laradock/logs/nginx 

same issue with mariadb  : 

`mariadb_1             | chown: cannot read directory '/var/lib/mysql/': Permission denied`

**Comment by vitoo** [comment]
This was SELINUX

fix :  `su -c "setenforce 0"`

**Comment by shailensobhee** [comment]
Tried all suggestions above - big bump

**Comment by toknsi** [comment]
`open() "/var/log/nginx/error.log" failed`  happen in **laradock clone in wsl git** ,do not happen in  **laradock clone in powershelll git**

docker for windows , laradock 7.0.0

**Comment by orubel** [comment]
same issue on ARM built version. I touched my nginx dir and both files (since they weren't being created) and even gave them the correct permissions. NOTHING.

Is this a librries that isn't being included properly ? I say this because I noticed the '/var/log/nginx' dir needed to be created on Armbian/Raspbian (AKA Debian)
