### ISSUE TITLE
Enter mysql is error 

### ISSUE THREAD

**Issue by sasuke6** [LaraDock/laradock#75]
When I enter the mysql container `docker exec -it docker_mysql_1 bash`,there is no problem.But if I enter the `mysql`,there is `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`.
When I use `mysql -u root -p`,there is `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`
What is the initial password and how to reset it quickly?

**Comment by Mahmoudz** [comment]
As you can see from the [MySQL Dockerfile](https://github.com/LaraDock/laradock/blob/master/mysql/Dockerfile) we barely modify the original image, however if you need a quick solution, I advice you google this problem as if it's heppening on the [original MySQL docker image](https://hub.docker.com/_/mysql/). And I will try to reproduce this error and investigate it during the next week. I really hope someone can debug it and help you soon.

**Comment by Mahmoudz** [comment]
@sasuke6 Hi again, I found a reason today to work on this project and I tried to reproduce your error.
It's not actual bug you just need to provide some info for MySQL in the command, so try running this it should work:

```shell
mysql --user=homestead --password=secret homestead
```

**Comment by sasuke6** [comment]
Thanks a lot!

**Comment by jakelacey2012** [comment]
Hi I had this issue, this fixed it for me.

I'm just wondering if this happens every time for every developer? If so could we add this to the documentation?

**Comment by Mahmoudz** [comment]
@jakelacey2012 if you feel it needs to be documented, please go ahead and create a new section in the readme about MySQL (example: Use MySQL) and then show all the tips such as how to ssh into that container `docker-compose exec mysql bash` and how to login to MySQL and see the tables.. `show database;` `use homestead;` ....
Thanks.

**Comment by saumya04** [comment]
@Mahmoudz How can I change my mysql password. I've tried changing the password from `docker-compose.yml` file but the changes doesn't seems to be reflected. Can you help me with it.

**Comment by appleboy** [comment]
@saumya04 Delete your container and rebuild again.

```
$ docker-compose down
$ docker-compose up
```

**Comment by saumya04** [comment]
@appleboy I've tried that already, its not working yet!

**Comment by eperiou** [comment]
I found this command on another question, related to this topic. Supposedly it deletes the data that normally isn't deleted by deleting the old containers and images

docker-compose rm -v

**Comment by francoism90** [comment]
This still happens to me, it doesn't update the root password set in docker-compose.xml

**Comment by eperiou** [comment]
Yes, this is because the mysql image creates a volume storing the password, so it needs to be deleted in the event that everything was not set up correctly the first time you composed. 
use 
    docker volume ls 
and you can find it and delete it or: 
    docker-compose rm -v
to remove the volumes created by the docker-compose before composing again
