### ISSUE TITLE
[Help] Need to increase Adminer import file size...

### ISSUE THREAD

**Issue by a-h-abid** [laradock/laradock#750]
I can't seem to find where / how to increase the import file size limit from 2MB to 100MB. How can I set it for my adminer container?

**Comment by partounian** [comment]
I found this link, https://sourceforge.net/p/adminer/discussion/960418/thread/082cef34/ . You might want to open up the container and update the php.ini upload_max_filesize, another alternative is to put your file into the same webserver folder as Adminer and use that option. Also, gzip your file.

**Comment by a-h-abid** [comment]
@partounian Setting in the .ini worked. So based on that I updated the Dockerfile for adminer to reflect this.


    FROM adminer:latest

    MAINTAINER Patrick Artounian <partounian@gmail.com>

    USER root

    # Store PHP Configs at /usr/local/etc/php/conf.d
    RUN echo "upload_max_filesize = 500M" >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
        && echo "post_max_size = 500M"       >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
        && echo "memory_limit = -1"           >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
        && echo "max_execution_time = 0"      >> /usr/local/etc/php/conf.d/upload_large_dumps.ini

    # Add volume for sessions to allow session persistence
    VOLUME /sessions

    USER adminer

    # We expose Adminer on port 8080 (Adminer's default)
    EXPOSE 8080


Thanks

**Comment by partounian** [comment]
Great! I did put my name as maintainer for that container, so I'm glad I could be helpful.

**Comment by lanphan** [comment]
FYI, latest version from Adminer Docker image already contains this setting (max 128MB, max input vars 5000, max execution time 600, max mem 1G) (link: https://github.com/TimWolla/docker-adminer/blob/9995b788b8948892a1aed163ab78796d5acaa276/4/Dockerfile ) no need to update / add more in Laradock, just remove base Adminer image and build again.

**Comment by abronin** [comment]
There is a NGINX limit also. Unfortunately, I'm unable to upload my 53.3Mb sql.gz file right now.

**Comment by mikaeldusenne** [comment]
> @partounian Setting in the .ini worked. So based on that I updated the Dockerfile for adminer to reflect this.
> 
> ```
> FROM adminer:latest
> 
> MAINTAINER Patrick Artounian <partounian@gmail.com>
> 
> USER root
> 
> # Store PHP Configs at /usr/local/etc/php/conf.d
> RUN echo "upload_max_filesize = 500M" >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
>     && echo "post_max_size = 500M"       >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
>     && echo "memory_limit = -1"           >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
>     && echo "max_execution_time = 0"      >> /usr/local/etc/php/conf.d/upload_large_dumps.ini
> 
> # Add volume for sessions to allow session persistence
> VOLUME /sessions
> 
> USER adminer
> 
> # We expose Adminer on port 8080 (Adminer's default)
> EXPOSE 8080
> ```
> 
> Thanks

Thank you man, you just saved me a bunch of hours, most likely !
Cheers !
