### ISSUE TITLE
Workspace build error with PHP7.1

### ISSUE THREAD

**Issue by kp77** [laradock/laradock#752]
Hi,

Tried to build with PHP7.1 version and received the following error:

> Step 1/59 : FROM laradock/workspace:1.3 # placeholder. Need change after new image would be built.
ERROR: Service 'workspace' failed to build: Error parsing reference: "laradock/workspace:1.3 # placeholder. Need change after new image would be built." is not a valid repository/tag: invalid reference format

I set the PHP version to 7.0 and the error disappeared, the build was successful.

**Comment by garlian** [comment]
The error lies in the Dockerfile-71 Line 13 in the workspace directory, the line has a wrong comment which stops docker from building. You could manually remove the comment and retry. The problem will be solved.

**Comment by kp77** [comment]
@garlian Thanks. Actually, I'm fine with 7.0, just thought it would be worth reporting this, as it breaks the build process.

**Comment by brazitech** [comment]
deleted the comments... naw it gives error 
Step 1/57 : ARG PUID=1000 ERROR: Service 'workspace' failed to build: Please provide a source image with `from` prior to commit

**Comment by mikeerickson** [comment]
@kp77 I had the same error earlier today, but was able to cure it by cloning a fresh copy of the laradock repo.   I just saved my `.env` file along with the webserver configuration and reinstalled `docker-compose up -d mysql nginx`

**Comment by brazitech** [comment]
thanks @kp77 . did not work for me. still getting the same error.

**Comment by winfried-van-loon** [comment]
There's a separate issue open for the PHP version within the workspace: #776. Linking everything together so we can find all the related issues when the solution is available.

**Comment by mikeerickson** [comment]
@mahmoudz so, since you have closed this issue, am I to assume selecting PHP71 in .ENV file should actually work?  If so, spread the secret.

**Comment by winfried-van-loon** [comment]
Yep, this is working. Laradock is now using PHP version 7.1 by default, which can be changed in the dotenv file. All workspace arg options in the dotenv can be enabled safely, except these ones:

* `WORKSPACE_INSTALL_AEROSPIKE_EXTENSION` -> Issue #855
* `WORKSPACE_INSTALL_INSTALL_V8JS_EXTENSION` -> Issue #792

If you experience any issues, feel free to let us know!
