### ISSUE TITLE
Can't login to PHPMyAdmin

### ISSUE THREAD

**Issue by kp77** [laradock/laradock#754]
A few days ago I didn't have this problem, but I cloned laradock yesterday and built new images. Since then I can't login to PHPMyAdmin.

Previously, I could enter either the short version of the container ID hash or the container name (laradock_mysql_1) as Server and it worked. Now if I do this I get this error:

> #2005 - Unknown MySQL server host 'laradock_mysql_1' (-2)

I also tried with localhost and 127.0.0.1, but then I get this error on the PHPMyAdmin login page:

>  #2002 - Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 &quot;No such file or directory&quot;) &mdash; The server is not responding (or the local server's socket is not correctly configured).

Interestingly, I can connect with HeidiSQL without problems using localhost, so my guess is this is related to PHPMyAdmin.

**Comment by maurosbu** [comment]
I have the same issue since laradock v. 5.1.0

**Comment by zeroc0d3** [comment]
Could you try this:
`docker-compose build && docker-compose up -d nginx mysql phpmyadmin` 

Perhaps it will help

**Comment by maurosbu** [comment]
This is what i did:
docker-compose build --no-cache nginx mysql phpmyadmin workspace php-fpm applications
docker-compose up -d nginx mysql phpmyadmin

**Comment by kp77** [comment]
@maurosbu 
@zeroc0d3 
I tried these, but I get the same error.

**Comment by maurosbu** [comment]
@kp77 Sorry, my previous message was an answer for @zeroc0d3. The error persists.

**Comment by thorerik** [comment]
the hostname you should use is `mysql` or `mariadb` depending on which flavour you use.

**Comment by kp77** [comment]
@thorerik I tried `mysql` but I got the same error.

> #2005 - Unknown MySQL server host 'mysql' (-2)

**Comment by zeroc0d3** [comment]
@kp77. could you send the log process?

**Comment by maurosbu** [comment]
@zeroc0d3 Same feedback when using `mysql` as host. 
`#2005 - Unknown MySQL server host 'mysql' (-3)`

**Comment by kp77** [comment]
@zeroc0d3 Could you tell me which log process do you mean, and how I can get it?

I looked at the container logs in Kitematic, but I couldn't see any related records.

**Comment by a-h-abid** [comment]
@kp77 are you using the latest laradock update? If so, you need to open `docker-compose.yml` file go to your `phpmyadmin` section, then the network section and there check if both `frontend` and `backend` networks are added.

**Comment by maurosbu** [comment]
@a-h-abid thank you.

**Comment by louiscocks** [comment]
Try putting what you have in DB HOST in the server section and use password & username as root.

**Comment by neutt22** [comment]
@neuthral how come the user and password were `root`? it works tho! I thought it was `secret` as specified in the `.env` file of laradock.

**Comment by neuthral** [comment]
@neutt22 i have no idea, i found that out by chance, it works good after changing .env password

**Comment by murilolivorato** [comment]
I cant connec as well , please , ome one can help ?

**Comment by ikingye** [comment]
change mysql from latest to 5.7
and rebuild
then login with
mysql + root + root

**Comment by maxkossatz** [comment]
Had the same issue:
downgrade mysql from 8 to 5.7 

by setting   MYSQL_VERSION=5.7  in laradock/.env
after that in your .env file see the var called `DATA_PATH_HOST` and go to that folder, after that delete the mysql folder there and then do the `docker-compose build --no-cache mysql` and then `docker-compose up -d mysql`

https://github.com/laradock/laradock/issues/1855#issuecomment-433393678

**Comment by m-maharjan** [comment]
Solved by changing the authentication method of user `default` to mysql native password. 

go to mysql bash `docker-compose exec mysql bash`
login using root `mysql -u root -p`  password is root. 
then issue following mysql command `ALTER USER 'default' IDENTIFIED WITH mysql_native_password BY 'secret';`

Now in phpmyadmin login page input server as `mysql` user `default` and password `secret`.

**Comment by Hazelwu2** [comment]
> Solved by changing the authentication method of user `default` to mysql native password.
> 
> go to mysql bash `docker-compose exec mysql bash`
> login using root `mysql -u root -p` password is root.
> then issue following mysql command `ALTER USER 'default' IDENTIFIED WITH mysql_native_password BY 'secret';`
> 
> Now in phpmyadmin login page input server as `mysql` user `default` and password `secret`.

thank you for your kind of help. It's really useful.

**Comment by trazmaniac** [comment]
> Solved by changing the authentication method of user `default` to mysql native password.
> 
> go to mysql bash `docker-compose exec mysql bash`
> login using root `mysql -u root -p` password is root.
> then issue following mysql command `ALTER USER 'default' IDENTIFIED WITH mysql_native_password BY 'secret';`
> 
> Now in phpmyadmin login page input server as `mysql` user `default` and password `secret`.

thanks for your kind of help. It's work for me. I'm used default setting on .env file just change the DOCKER_HOST_IP and version of node. Everything just default.

**Comment by beganovich** [comment]
Solved this by using `mariadb` instead of `mysql`. Next time, Oracle.

```
# Accepted values: mariadb - mysql
PMA_DB_ENGINE=mariadb`

**Comment by sayalok** [comment]
go to mysql bash ` docker-compose exec mysql bash`

run this to login  `mysql -u root -p`

run below command to update the root user password
`ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY '123';`
