### ISSUE TITLE
deployment to digital ocean faliure

### ISSUE THREAD

**Issue by iannazzi** [laradock/laradock#756]
Hi all, I am attempting to deploy to digital ocean following the laradock guide and I am having some issues....

I attempted  one-click docker on both 14.04 and 16.04

I followed the instructions exactly to see if it worked. 

when attempting docker-compose up -d nginx mysql I receive the following....

```ERROR: The Compose file './docker-compose.yml' is invalid because:
services.proxy.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.proxy2.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.memcached.ports is invalid: Invalid port ":11211", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.beanstalkd.ports is invalid: Invalid port ":11300", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.mssql.ports is invalid: Invalid port ":1433", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.rabbitmq.ports is invalid: Invalid port ":15671", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.rabbitmq.ports is invalid: Invalid port ":15672", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.workspace.ports is invalid: Invalid port ":22", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.mariadb.ports is invalid: Invalid port ":3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.mysql.ports is invalid: Invalid port ":3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.apache2.ports is invalid: Invalid port ":443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx.ports is invalid: Invalid port ":443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.selenium.ports is invalid: Invalid port ":4444", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.postgres.ports is invalid: Invalid port ":5432", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.postgres-postgis.ports is invalid: Invalid port ":5432", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.rabbitmq.ports is invalid: Invalid port ":5672", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.apache2.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.phpmyadmin.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.adminer.ports is invalid: Invalid port ":8080", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.balancer.ports is invalid: Invalid port ":8085", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.minio.ports is invalid: Invalid port ":9000", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.elasticsearch.ports is invalid: Invalid port ":9200", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.elasticsearch.ports is invalid: Invalid port ":9300", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
root@cgtest:~/laravel/laradock#```

**Comment by winfried-van-loon** [comment]
Hi! First of: If you've got a huge code block like above, don't just use one `, use three of them. It'll look like this: a lot more readable.

```
Test
```

Then about your issue itself. Have you followed the steps in the readme? In step two, the `.env` file is created. Without this file, you may get this error.

**Comment by iannazzi** [comment]
Thanks for the tip @winfried-van-loon .... 

At first I did not copy the .env file. I knew it was coming, just didn't know it arrived. Once I realized there was a .env file added I did copy it, looked through it and did not make any changes. The error persisted, and then I started adding in updates, rebuilding containers, etc. I never made it past the errors.

There was a whole bunch of newness and uncertainty in the process... like do I make /var/www folder or am I really running all the commands in the home folder.

Anyway I am working through the docker docs, it looks like the entire process has been updated. Docker-machine quickly spun up a droplet on digital ocean, and I was able to get an image working within a few minutes following their guide. Today I hope to apply that knowledge to my docker setup and codebase and have an update for the docs.

I am hoping to arrive at a continuous integration pipeline. The guides on the web are pretty scattered, so any information would be helpful. 

I believe I want an automated process to fire up a jenkins server, test the code, look at it on a staging server, then move it to production if all is good.

Soo.... any thoughts would be appreciated

**Comment by iannazzi** [comment]
I copied to env, not .env. I will start a different discussion on deployment, I have some cool stuff so far

**Comment by winfried-van-loon** [comment]
That sounds great! Idea's like that can really help improve already good projects.

**Comment by iannazzi** [comment]
I guess I have reached the point where I need a good method to deploy... it should work in one liner.... like ./development.sh or ./production.sh

It looks like docker-machine with a shell script is the way to go for deployment. I have the digital ocean droplets spinning up in one line which I put in a shell script. This is better than manually creating droplets. Plus if this method works we can immediately spin up a staging server and see work live....that would be sweet.

 I believe we have the general setup of laradock incorrect - it should be designed to transition between development through deployment to staging and production. Even development could be deployed to docker machine... it actually worked better for me that way, especially with multiple instances. That said it looks like the laradock folder should be next to the laravel folder, not in it. Then the .env file should be split and removed, as we will be controlling the environment from the client computer, so the client has to have the knowledge of different environments. Especially important for staging as I plan on spinning up, running test, then destroying.

 I have a start on a development.yml which extends a common.yml, like wise staging.yml and production.yml extend common.yml. Variables could be placed in these files. Otherwise the .env could be split to common.env, development.env, production.env, etc. I am a bit stuck here, but I think that is the correct way. This way we have one environment, which then gets pushed to different machines. I am a few days in, have a basic swarm created, just have to pull it all into laradock and get it working again.

I will start a separate thread to discuss when it all comes together.
