### ISSUE TITLE
php-fpm can't enabled MySQL Support

### ISSUE THREAD

**Issue by bestlong** [laradock/laradock#759]
edit docker-compose.yml set PHP_FPM_INSTALL_MYSQL=true
then run docker-compose up --build -d nginx mysql
run phpinfo(), i did not see mysql support.

**Comment by winfried-van-loon** [comment]
Hi Bestlong, it's a bit depending on the PHP version. Within PHP5, MySQL was deprecated and removed in PHP7. If you want to use MySQL in PHP5, be sure to switch to that version of php-fpm. For PHP7, I'd recommend using MySQLi.

**Comment by bestlong** [comment]
Hi @winfried-van-loon, thanks for your advice. I need on the PHP56 version to maintain some legacy project. If it can keep this feature, It's very helpful to me.

**Comment by winfried-van-loon** [comment]
After checking, I've got the same issue now. I'll look into it in the weekend.
