### ISSUE TITLE
[Warning] One or more build-args [INSTALL_MYSQL] were not consumed

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#764]
While building the php-fpm container using PHP_VERSION 70 or 71.
Cause INSTALL_MYSQL is not using on those dockerfiles.

**Comment by winfried-van-loon** [comment]
We could remove the `INSTALL_MYSQL` option, merging it with the `INSTALL_MYSQLI` option. When using `PHP_VERSION` 56 with `INSTALL_MYSQLI` enabled, we could automatically install the MySQL extension, along with the MySQLi extension. For 70 and 71, we would never install it. That way, we wouldn't be displaying an deprecated/removed PHP feature. 

It could, however, pose a bit of a usability issue: Users may not know that MySQLi also installs MySQL and may think it's not available.

**Comment by Mahmoudz** [comment]
I like your idea, and regarding the usability we can add this to the docs.
