### ISSUE TITLE
Workspace error after pulling latest

### ISSUE THREAD

**Issue by suncoastkid** [laradock/laradock#767]
`docker-compose exec --user=laradock workspace bash` returns
```
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: /home/laradock/aliases.sh: line 61: syntax error near unexpected token `$'{\r''
'ash: /home/laradock/aliases.sh: line 61: `function mkd() {
laradock@3a355f5c93e0:/var/www$ 
```

**Comment by winfried-van-loon** [comment]
@suncoastkid Just tried the exact command, it's working for me. To investigate further into this issue, we need some additional information.

Do you have the latest Laradock version, what kind of Docker version do you have, that OS and are you still experiencing this issue? Have you changing any of the dotenv file preferences?

**Comment by suncoastkid** [comment]
I'm using Laradock version 2 on Ubuntu 16.04.

**Comment by mikeerickson** [comment]
@winfried-van-loon @suncoastkid This was an old issue which has been resolved.  Are you sure you have the latest version of laradock pulled down

```
$ git pull http://github.com/laradock/laradock
```

Also, the issue only occurred on Windows as I recall (I cant lookup past issues at the moment)

**Comment by mikeerickson** [comment]
See this ticket for details

```
https://github.com/laradock/laradock/issues/563
```

**Comment by winfried-van-loon** [comment]
It's possible your Docker installation is outdated. The error suggests it wouldn't accept this syntax: `${variable_name}` which has been around for a while now. Please, check your Docker version. If that's not it, pull the latest version of Laradock in the master branch. If you are still experiencing the issue, please do not hesitate to let us know and we'll reopen the issue.
