### ISSUE TITLE
Service 'workspace' failed to build

### ISSUE THREAD

**Issue by percymamedy** [LaraDock/laradock#77]
I am Still facing issues building up the containers as i pointed in issue #73 

Now am facing another error:

```
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.0/php7.0-sqlite3_7.0.7-1+donate.sury.org~trusty+1_amd64.deb  Connection failed

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y --force-yes         php7.0-cli         php7.0-common         php7.0-curl         php7.0-json         php7.0-xml         php7.0-mbstring         php7.0-mcrypt         php7.0-mysql         php7.0-pgsql         php7.0-sqlite         php7.0-sqlite3         php7.0-zip         php7.0-memcached         sqlite3         libsqlite3-dev         git         curl         vim         nano         nodejs         nodejs-dev         npm' returned a non-zero code: 100
```

Any help would be appreciated.

Thanks

**Comment by Mahmoudz** [comment]
@percymamedy I just installed LaraDock and provisioned all my containers, without any problem!

Seems you have a connection problem on your computer, check if you are behind a proxy, test your internet connection and try changing your DNS. Basically try debugging the problem on your local computer because it's not related to LaraDock.

**Comment by percymamedy** [comment]
@Mahmoudz , alright thanks I will try that. Its worth noting am on a windows system, that might be the roots of my problems.

**Comment by AminMkh** [comment]
@percymamedy you could do some debugging and troubleshooting, I would run a base image like phusion:
```
docker run -ti phusion/baseimage bash
```
And play around, install PHP manually 
```
apt-get update && apt-get install -y  software-properties-common
add-apt-repository -y ppa:ondrej/php
RUN apt-get update && apt-get install -y --force-yes \
        php7.0-cli \
        php7.0-common \
        php7.0-curl \
        php7.0-json \
        php7.0-xml \
        php7.0-mbstring \
        php7.0-mcrypt \
        php7.0-mysql \
        php7.0-pgsql \
        php7.0-sqlite \
        php7.0-sqlite3 \
        php7.0-zip \
        php7.0-memcached \
        sqlite3 \
        libsqlite3-dev \
        git \
        curl \
        vim \
        nano \
        nodejs \
        nodejs-dev \
```

Basically, going through the workspace Dockerfile manually, your changes won't be persistent. But you are basically building the image manually and you should get to the root of the problem, if you get an error for instance try to fix it or post it here.
