### ISSUE TITLE
Multiple MySql

### ISSUE THREAD

**Issue by ajmerainfo** [laradock/laradock#771]
First of thank for making great package.

I have one question. 
How can we make multiple mysql databases with multiple laravel project?

**Comment by mikeerickson** [comment]
@jamerainfo while laradock does not support this (I will add as a feature request). It can be done quite easily after `docker-compose... ` up command 

Just enter the my sql container 

```
$ docker exec laradock_mysql_1 /bin/bash
```

Then inside container, log into MySQL
```
$ mysql -uroot -proot 

> mysql CREATE DATABASE name;
```

**Comment by mikeerickson** [comment]
@ajmerainfo my apologies for misspell on name, git on iPhone is rough without autocomplete.  Please see (Watch) this ticket for feature support -- https://github.com/laradock/laradock/issues/773
