### ISSUE TITLE
a little help setting up deploy to staging, production

### ISSUE THREAD

**Issue by iannazzi** [laradock/laradock#779]
I am working on transitioning the laradock dev setup to a live staging server. I developed a cool app, now I want to show some colleagues for feedback, so I have to get it up, test it, and have a temporary copy sitting on the web. This needs to happen using one line of code, probably a shell script `./staging.sh` or a githook.

To do this it looks like we use `docker-machine` in combination with `docker-compose` files. We would create a `common.yml` file, and then extend that file to development, staging, production, etc.

Then there is the question of environmental variables. I can predict we will need a common.env, then development.env, staging.env, etc.

And in setting all this up I get stuck on importing a .env file into a .yml file. Which basically you can't do. The issue is described [here](https://github.com/docker/compose/issues/4001). So you get one .env file.

Three other approaches come to mind to get variables into the .yml file. 

1) Hardcode the values into the extended .yml files. This seems reasonable. 

2) Use a common .env file for values that do not change. Define the variables in a shell script. I am stuck with this option not working - the shell will not load the variable to the .yml file. Here is the shell script: 

```#!/usr/bin/env bash
APPLICATION='../craiglorious'
docker-compose -f development.yml up workspace

```
I have executed the script using `./development.sh` and source `development.sh`. 
Some help here would be appreciated. I could pull those variables to the docker-compose command if I can't figure out how to define variables in the shell for the .yml file to use.

3) Modify the .env file with more variables: like DEV_variable name and STAGE_name. for some reason this seems messy.

Any thoughts? and ideas on that shell script issue?

Finally now the .env is really confusing. What is .env???? there are now many environments, all being controlled by my macbook. I believe the original thought was to have a file to put in the things you do not want to distribute. The things I would want in .env are sensitive information, tokens, usernames, server names, passwords, etc. Ports, True/false config things, folders, those sound like config items.

**Comment by dtunes** [comment]
Hey man,

just wondering, have you read the docs about environment variable substitution in the docs?
https://docs.docker.com/compose/compose-file/#variable-substitution

Also, old post, but might be useful.
https://blog.docker.com/2015/04/easily-configure-apps-for-multiple-environments-with-compose-1-2-and-much-more/

also, in your second example:
```sh
APPLICATION='../craiglorious'
docker-compose -f development.yml up workspace
```
should be:
```sh
export APPLICATION='../craiglorious'
docker-compose -f development.yml up workspace
```

Also, check this link https://docs.docker.com/compose/extends/.

Hope this helps.

**Comment by iannazzi** [comment]
@dtunes Yes yes yes, I needed the `export` keyword in the shell script. So now I have first, second, and third option working.

Also thanks for the links. I have been living in the docs [https://docs.docker.com/compose/production/,](https://docs.docker.com/compose/production/) but the older post confirmed one thing I was thinking - use an old-school non docker mysql database for production data.

I also thought I was going to have to modify the base images for staging, production, etc, essentially to pull from git and install, run tests, but now I think I have a better approach, tbd. It looks like I will mount the source from the client for staging, and for production it looks like I will copy the built folders.

[https://forums.docker.com/t/best-practices-for-getting-code-into-a-container-git-clone-vs-copy-vs-data-container/4077/7](https://forums.docker.com/t/best-practices-for-getting-code-into-a-container-git-clone-vs-copy-vs-data-container/4077/7)

I will update later this week, any other ideas please let me know.

**Comment by dtunes** [comment]
Glad it helped.

As a side note, please note that the .env file located at the root of laradock, is not to be confused with the .env file (if any) in your laravel or lumen app.

the .env file in the laradock root is read by docker-compose, these "secrets" are not really safe if you have to check them into source control. I would look into etcd, vault https://www.vaultproject.io/ or even consul to store the secrets, another option is to encrypt the repo or just the .env file https://www.agwa.name/projects/git-crypt/.

**Comment by mikeerickson** [comment]
@iannazzi what items remain unanswered?  Would like to get this resolved and documentation updated for better clarification.

**Comment by winfried-van-loon** [comment]
It's good to see Laradock being using in production and combined with `docker-machine`. We're always open for suggestions and enhancements for Laradock. Feel free to keep us updated if you've got any news, questions or if you've still got the same issue. 👍

**Comment by iannazzi** [comment]
Thanks, I take a break from coding in the spring, but this is next on my list when I get back on it. I have some cool stuff so far, like creating a staging server with one command. It looks like we would run all tests on the local environment, then copy the files to staging or production, so no composer install, or npm install. I was stuck on npm install running out of memory.

**Comment by jasperf** [comment]
@iannazzi Hope you had a nice break. Was reading through this all and would love to hear whether you worked it all out and if so how.

**Comment by iannazzi** [comment]
Ahh my break continues through the summer! I Design and Build all summer.....

I have it all set in my mind how it will work, just have to sit down and do it.

It involves ripping apart docker-compose.yml to development.yml, staging.yml and production.yml which all reference a common.yml 

then create script files develpment.sh, staging.sh, etc

It also involves re-thinking the .env file. That file probably should only have sensitive server info, and things related to development, staging, production move to the .yml files.

The best reference I found is the docker docs - there are a few sections about deployment. Look at the user guides, then look at the reference for docker-compose, which is in a different section....


However this is where I am at.... This will fire up a machine named DATE, copy your files over ( I found npm install fails always)

I think I left off at the copy step, so the steps after it may not be correct...

staging.sh

#!/usr/bin/env bash
name=$RANDOM
DATE=`date +%Y%m%d%H%M%S`
docker-machine create --driver digitalocean --digitalocean-size 2gb --digitalocean-access-token YOUR_DIGITAL_OCEAN_TOKEN  $DATE

#copy the files over from local to staging
docker-machine scp -r ../tests/apptest $DATE:/var/www

#bring up the machine
eval $(docker-machine env $DATE)
docker-compose -f staging.yml up -d nginx mysql

#run tests

**Comment by jasperf** [comment]
@iannazzi Did you have manage to wrap this up? Been looking into Laradock again, especially setting things up for production. There the documentation is lacking somewhat still. And the production-docker-compose.yml example is no longer there as it was outdated.

**Comment by ryancwalsh** [comment]
@jasperf I'm curious if you ever got Deployer working with Laradock. I'm stuck here: https://github.com/deployphp/deployer/issues/1636#issuecomment-403786878 Thanks.
