### ISSUE TITLE
Where is the workspace container?

### ISSUE THREAD

**Issue by sasuke6** [LaraDock/laradock#78]
When I start up the LaraDock,and I run `docker-compose ps`,I can not see the workspace container,but I try to enter `docker_php_1`,the laravel project has been existing.Why is there or have change the container name?

**Comment by AminMkh** [comment]
so regarding the workspace, the container is called "workspace", and the image should be something like laradock_workspace_1:
```
docker-compose ps
laradock_workspace_1               /sbin/my_init                    Up                                                      
```

The workspace container is mostly used for composer require/updates/...etc + the artisan command line. The image you are trying to connect to is the PHP-FPM, not sure why you need it. But either ways it should be up, not exited.

I suggest checking the logs, maybe do a 
```
docker-compose up nginx mysql
```

Without the -d parameter, you should be seeing the output right away.
Or use 
```
docker-compose logs
```
And check for the PHP-FPM output, it should display more details.

**Comment by tristanbailey** [comment]
@sasuke6 you will not see workspace with docker ps, as the volumes do not stay running they stay in the background. 
So look for `docker ps -a` see the containers that stopped and also workspace.

**Comment by sasuke6** [comment]
@tristanbailey `docker ps -a`,I can not see the workspace,But the Laradock is based on the laravel project,I create a project laravel and git clone in the directory,the`.env` I have update

**Comment by sasuke6** [comment]
@AminMkh Thanks for your advice!I have checked the logs,but there is still not information for the workspace.May I have some mistake in setting laravel's file `.env`?However,I also can see the laravel page.

**Comment by AminMkh** [comment]
@sasuke6 Laravel and the .env file don't have anything to do with Laradock, Laradock containers should run even if you don't have a Laravel installation or configuration.

Could you please post the output of the following commands:
```
docker-compose up nginx mysql
dc up nginx mysql
Starting laradock_data_1
Starting laradock_application_1
laradock_workspace_1 is up-to-date
Starting laradock_mysql_1
laradock_php-fpm_1 is up-to-date
Starting laradock_nginx_1
Attaching to laradock_mysql_1, laradock_nginx_1
```

Then
```
docker-compose ps
         Name                   Command                   State                    Ports          
-------------------------------------------------------------------------------------------------
6ad247dc9c80_laradock_   /docker-entrypoint.sh    Exit 137                                        
postgres_1               postgres                                                                 
7dcefc9da64e_laradock_   docker-entrypoint.sh     Exit 137                                        
redis_1                  redis ...                                                                
b7ebdff76e3c_laradock_   /bin/bash -c             Exit 137                                        
neo4j_1                  /launch.sh                                                               
fd53f7ce6896_laradock_   docker-entrypoint.sh     Exit 1                                          
mariadb_1                mysqld                                                                   
laradock_application_1   true                     Exit 0                                          
laradock_beanstalkd-     /bin/sh -c bash -c       Exit 137                                        
console_1                'BEANST ...                                                              
laradock_beanstalkd_1    /usr/bin/beanstalkd      Exit 137                                        
laradock_data_1          true                     Exit 0                                          
laradock_mariadb_1       docker-entrypoint.sh     Exit 0                                          
                         mysqld                                                                   
laradock_memcached_1     /entrypoint.sh           Exit 137                                        
                         memcached                                                                
laradock_mongo_1         /entrypoint.sh mongod    Exit 0                                          
laradock_mysql_1         docker-entrypoint.sh     Up                       0.0.0.0:3306->3306/tcp 
                         mysqld                                                                   
laradock_neo4j_1         /bin/bash -c             Exit 0                                          
                         /launch.sh                                                               
laradock_nginx_1         nginx                    Up                       0.0.0.0:443->443/tcp,  
                                                                           0.0.0.0:80->80/tcp     
laradock_php-fpm_1       php-fpm                  Up                       9000/tcp               
laradock_postgres_1      /docker-entrypoint.sh    Exit 0                                          
                         postgres                                                                 
laradock_redis_1         docker-entrypoint.sh     Exit 0                                          
                         redis ...                                                                
laradock_workspace_1     /sbin/my_init            Up                                              
```
And 
```
docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
7322017d48f7        laradock_nginx       "nginx"                  4 minutes ago       Up 47 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   laradock_nginx_1
c8aa49bfd93c        laradock_php-fpm     "php-fpm"                4 minutes ago       Up 47 seconds       9000/tcp                                   laradock_php-fpm_1
021456e92ac3        laradock_workspace   "/sbin/my_init"          4 minutes ago       Up 48 seconds                                                  laradock_workspace_1
ed87a7a0c0ba        laradock_mysql       "docker-entrypoint.sh"   4 minutes ago       Up 47 seconds       0.0.0.0:3306->3306/tcp                     laradock_mysql_1
```

The logs would help us investigate more, thanks.

**Comment by sasuke6** [comment]
@AminMkh Thanks for your help,there is my logs

`docker-compose up nginx mysql
Starting docker_data_1
Starting docker_php_1
Starting docker_mysql_1
Starting docker_nginx_1
Attaching to docker_mysql_1, docker_nginx_1`
And

`docker-compose ps
           Name                          Command                State                  Ports
----------------------------------------------------------------------------------------------------------
docker_beanstalkd-console_1   /bin/sh -c bash -c 'BEANST ...   Exit 137
docker_beanstalkd_1           /usr/bin/beanstalkd              Exit 137
docker_data_1                 true                             Exit 0
docker_mariadb_1              docker-entrypoint.sh mysqld      Exit 1
docker_memcached_1            /entrypoint.sh memcached         Exit 0
docker_mysql_1                docker-entrypoint.sh mysqld      Up         3306/tcp, 0.0.0.0:3307->3307/tcp
docker_nginx_1                nginx                            Up         443/tcp, 0.0.0.0:80->80/tcp
docker_php_1                  php-fpm                          Up         9000/tcp
docker_postgres_1             /docker-entrypoint.sh postgres   Exit 0
docker_redis_1                docker-entrypoint.sh redis ...   Exit 0
`
And absolutely
`docker-compose logs workspace
ERROR: No such service: workspace`

Last,
`docker -v
Docker version 1.11.1, build 5604cbe
`
Above all

**Comment by sasuke6** [comment]
@AminMkh  Thanks for your help,there is my logs

```
docker-compose up nginx mysql
Starting docker_data_1
Starting docker_php_1
Starting docker_mysql_1
Starting docker_nginx_1
Attaching to docker_mysql_1, docker_nginx_1
```

And

```docker-compose ps

           Name                          Command                State                  Ports
----------------------------------------------------------------------------------------------------------
docker_beanstalkd-console_1   /bin/sh -c bash -c 'BEANST ...   Exit 137
docker_beanstalkd_1           /usr/bin/beanstalkd              Exit 137
docker_data_1                 true                             Exit 0
docker_mariadb_1              docker-entrypoint.sh mysqld      Exit 1
docker_memcached_1            /entrypoint.sh memcached         Exit 0
docker_mysql_1                docker-entrypoint.sh mysqld      Up         3306/tcp, 0.0.0.0:3307->3307/tcp
docker_nginx_1                nginx                            Up         443/tcp, 0.0.0.0:80->80/tcp
docker_php_1                  php-fpm                          Up         9000/tcp
docker_postgres_1             /docker-entrypoint.sh postgres   Exit 0
docker_redis_1                docker-entrypoint.sh redis ...   Exit 0
```

And absolutely

```docker-compose logs workspace 
ERROR: No such service: workspace
```

Last,

```
docker -v
Docker version 1.11.1, build 5604cbe
```
Above all

**Comment by AminMkh** [comment]
I am not sure what's going on, please post the file content of docker-compose.yml

https://github.com/LaraDock/laradock/blob/master/docker-compose.yml

I think you're missing the workspace container there.

**Comment by sasuke6** [comment]
@AminMkh Oh,it is!The`docker-compose.yml` is not existed!But why I can see the laravel page?My step is that,first I use composer to install laravel and change the `.env` file,such as 
`
DB_HOST=192.168.99.100
REDIS_HOST=192.168.99.100
`
I think it is the reason I can access the laravel page although the workspace is not existed.Because I have install the laravel project

**Comment by Mahmoudz** [comment]
@sasuke6 you can see the Laravel page without the Workspace container, this container just provide you with additional software's.. So for now just run the following command from the laradock folder and start over `git pull origin master`.

**Comment by sasuke6** [comment]
It is OK,because I use the other tutorial,their solution is not following you.I think it is not a bad solution,the container and Laravel project is separation.The IP address is associated with Laravel.
