### ISSUE TITLE
ERROR: Service 'php-fpm' failed to build

### ISSUE THREAD

**Issue by Euthimios** [laradock/laradock#780]
The bellow  is what i get with when i try to run : docker-compose up -d --build nginx mysql redis

ERROR: Service 'php-fpm' failed to build: One or more build-args [INSTALL_MYSQL] were not consumed, failing build.

At docker-compose.yml if i put a comment tag at line 67 ( INSTALL_MYSQL=${PHP_FPM_INSTALL_MYSQL} ) it works fine

**Comment by bestlong** [comment]
@Euthimios
Please insert into .env one line PHP_FPM_INSTALL_MYSQL=true after PHP_FPM_INSTALL_MYSQLI

**Comment by winfried-van-loon** [comment]
Closing this issue as either the solution by @bestlong or my pull request should have fixed this issue. However, if your issue is still there, please reply and we'll look into it, again.
