### ISSUE TITLE
PHP Warning:  Module 'soap' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by markhilton** [laradock/laradock#787]
when compiled with Dockerfile-70 workspace CLI php commands throw:

PHP Warning:  Module 'soap' already loaded in Unknown on line 0

**Comment by winfried-van-loon** [comment]
Okay, I've done some research. In the workspace container, when looking in the following folder: `/etc/php/7.0/cli/conf.d/`, these (relevant: `ls | grep soap`) files are installed:

**20-soap.ini**
```
; configuration for php soap module
; priority=20
extension=soap.so
```

**40-soap.ini**
```
extension=soap.so
```

This'll load the extension twice, I assume. I'm however not sure what happened that this warning is now being displayed.
