### ISSUE TITLE
Browser shows default nginx page, not laravel app

### ISSUE THREAD

**Issue by tripper54** [LaraDock/laradock#79]
Hi there,

I'm trying to run laradock with an existing laravel app. From the project root:

````
git submodule add https://github.com/LaraDock/laradock.git
cd laradock/
docker-compose up -d nginx
````

The containers start OK, but in my browser the default "Welcome to nginx" page shows instead of the laravel app.

Bashing into the nginx container shows the laravel app code at /var/www/laravel where you would expect, and the nginx config files all seem to have copied correctly - sites-available/laravel.conf and conf.d/* .

Any idea what might be up here?

Note I'm on a mac, running the docker for mac beta.

**Comment by nevedimko** [comment]
I have the same error on Ubuntu 14.04.

"Welcome to nginx!" instead of Laravel Homepage

**Comment by Mahmoudz** [comment]
@tripper54 @nevedimko can you please check this issue #46 @mattythebatty have solved it.

If that solves it for you, would love if anyone writes the solution steps (clearly explained) and what's causing this problem, in order to include it in the docs since many users are facing this. Thanks

**Comment by nevedimko** [comment]
If I open http://localhost, then I see "Welcome to nginx!"
But if http://127.0.0.1, then Laravel app.

@Mahmoudz Thanks for fast help :)

**Comment by tripper54** [comment]
@nevedimko : Yes, same for me. localhost goes to nginx, 127.0.0.1 goes to laravel.

Thanks!

**Comment by Mounir-Bennacer** [comment]
Hi, 
i'm facing the same issue, neither of theses solutions works for me, i try to use 127.0.0.1 and get 404
But when i try localhosti get "welcome to nginx"

any workaround ? 
thanks

**Comment by tecsolucionesinformaticas** [comment]
Be careful not to run multiple servers on the same machine, as they might be sharing the port and it could actually be another server that is responding. This happened to me because I had a Docker container running, and in one case, Laragon was responding and in another, one of the 5 Dockers I had running was responding haha.

**Comment by taylorivanoff** [comment]
I was using WSL2 and docker for my Laravel Sail setup and had the same problem showing the default Apache page. It was because WSL2 had Apache2 installed pre-installed and. I removed it with `sudo apt remove apache2` and it was resolved.
