### ISSUE TITLE
Php-fpm ghostscript

### ISSUE THREAD

**Issue by winfried-van-loon** [laradock/laradock#798]
After the installation of ghostscript was repaired in #784 and #790, the following error is now displayed when the arg is enabled.

```
Step 34/42 : ARG INSTALL_GHOSTSCRIPT=false
 ---> Running in 37863e26bb79
 ---> 6c08bfd50b74
Removing intermediate container 37863e26bb79
Step 35/42 : RUN if [ ${GHOSTSCRIPT} = true ]; then     apt-get update &&     apt-get install -y poppler-utils ghostscript ;fi
 ---> Running in e364236876b9
/bin/sh: 1: [: =: unexpected operator
 ---> bcb82e380a22
Removing intermediate container e364236876b9
```

This error possibly breaks the installation of the ghostscript extension, as it does not show up in `phpinfo()`.

**Comment by thorerik** [comment]
Can you please confirm that this issue is resolved @winfried-van-loon?

**Comment by winfried-van-loon** [comment]
Will check within the hour and get back to you.

**Comment by winfried-van-loon** [comment]
That's working, thanks! 👍
