### ISSUE TITLE
Failed Build INSTALL_EXIF and INSTALL_PHPREDIS in php-fpm 5.6

### ISSUE THREAD

**Issue by qZzQ1** [laradock/laradock#801]
hi everyone,

I have a problem whit laradock i can't build my php-fpm 5.6 version because he can't build INSTALL_EXIF and INSTALL_PHPREDIS extension.

error bash is :
```bash
Service 'php-fpm' failed to build: One or more build-args [INSTALL_EXIF INSTALL_PHPREDIS] were not consumed, failing build.
```

can you help me please ?

Thanks

**Comment by winfried-van-loon** [comment]
Hi @qZzQ1! 

Do you have the latest version of Laradock cloned? Many fixes where implemented yesterday, your issue may already have been fixed.

Make sure to rebuild the containers, like so:
```
docker-compose up -d --force-recreate --build apache2 mariadb
```
Feel free to replace `apache2 mariadb` with the containers you'd like to build, of course.

**Comment by qZzQ1** [comment]
Yes it's ok, i have solved my issue whit this post :

https://github.com/laradock/laradock/issues/575

I go to rebuild my containers

it's good for me thanks :+1:

**Comment by winfried-van-loon** [comment]
Great news! Enjoy Laradock! 👍
