### ISSUE TITLE
dockefile build error on source /root/.bashrc

### ISSUE THREAD

**Issue by nickfan** [LaraDock/laradock#81]
workspace Dockerfile:

the console log show:
 ---> 56b18cc9b3b7
Removing intermediate container bbd2ceb35e86
Step 27 : RUN . ~/.bashrc
 ---> Running in 75b252000649
/bin/sh: 13: /root/.bashrc: shopt: not found
/bin/sh: 21: /root/.bashrc: shopt: not found
 ---> 425a7d29ecfc

**Comment by Mahmoudz** [comment]
I'll close this old issue now, if the error still exist we'll open it back.

**Comment by slc-laravel-shift** [comment]
Still exists for me in the latest commit (https://github.com/laradock/laradock/commit/c4aef8e901a867a57df0b1aadf1c872165e65295), @Mahmoudz . Did you ever find a fix @nickfan?

**Comment by nickfan** [comment]
still exists.
