### ISSUE TITLE
Distributed Laradock environments

### ISSUE THREAD

**Issue by tpetry** [laradock/laradock#811]
First i have to say laradock is a really really nice solution for moving php applications to containers because it's the only solution which has a really wide support for different modules.
But laradock is clearly oriented more towards development (#143) because it's separating the webserver and php-fpm process which each have to mount the source files by shared folders.

The problem with distributed environments like docker swarm, kubernetes, openshift or any other solution is the management of these source files. You no longer have the ability to update the sourcefiles on every server that your laradock containers will see the new sourcecode.

You could try to solve the problem by "burning" the sourcecode into the nginx/apache/caddy and php-fpm container and no longer use the folder mounting technique. But this solution is tricky in production because container rollout may need a few minutes in geographically distributed environments with hundreds of containers on every continent. It would be much simpler and efficient to roll-out a combined webserver + php-fpm container because they __have__ to share some files. Think of the webserver checking first if a php file is existing to call php-fpm.

I'll propose a new container/solution which simply allows combining the webserver and php-fpm into __one__ container.

**Comment by Mahmoudz** [comment]
@tpetry let's combine them. Will you be willing to submit a PR with that change.

Whoever gonna do this, should make sure we have the least amount of duplicated code, since we currently support 3 PHP versions in the php-fpm container. And we have 3 servers as you named them.

**Comment by winfried-van-loon** [comment]
Excellent idea, in my opinion. There is, as you've pointed out, a lot of duplicate code. Fixing that would make it more maintainable as well.

**Comment by zeroc0d3** [comment]
Yes agree... that's sound great...

**Comment by tpetry** [comment]
@Mahmoudz To be honest i will have not time for a PR for several weeks because i will now have to the building of docker containers by my own as laradock was not feasible and there are a few more languages that need to be containerised.

Does anybody have an idea how this could be generally done without duplicating all the code? The docker devs states that they will not extend the Dockerfile language anymore, like adding [include statements](https://github.com/docker/docker/issues/735). And solutions like Ansible/Chef/Puppet would drastically change the orientation of the project.

**Comment by a-h-abid** [comment]
Just a thought, could we make something like bash script / batch file which will generate the Dockerfile and then we build the image of that generated Dockerfile?

**Comment by Mahmoudz** [comment]
@tpetry kinda the same situation. Hopefully after 6 weeks I'll have more free time..

Let's keep this open, to see if anyone would like to give it a shot.

@a-h-abid that's pretty much the concept of the [CLI](https://github.com/laradock/cli) which I don't think anyone is working on right now. If we gonna do it this way (scripts to generate dockerfiles), we need to have some discussions first, as the tool should be capable of doing other useful stuff.. checkout this [video](https://www.youtube.com/watch?v=QA-AHdydEt4) it's a demo from this [repo](https://github.com/stacker/stacker-cli), it's a nice CLI tool, similar to what I had in mind for Laradock a long time ago.

@laradock/admins you might also be interested in checking this [repo](https://github.com/stacker/stacker-cli).

**Comment by calnation** [comment]
@tpetry Take a look at [rocker](https://github.com/tyrken/rocker)

I have a question for laradock maintainers relevant to it being oriented towards development. I noticed the project is built where the application code is assumed to be on the host machine, not as a container/volume container, is there an intent to give some focus on production environments?

**Comment by Mahmoudz** [comment]
@calnation yes there's intent to support production as much as we do support development. Obviously, there are some major changes that needs to be done for that purpose, like stop running the workspace by default, merging php-fpm in the servers (nginx)......

If you are willing start that "or anyone else reading this", we'll be more than happy to support you. Just let us know, to make an experimental branch, to test the new changes and help you fix the problems you might face...

**Comment by calnation** [comment]
Well, what I admire most about Laradock is how it takes into consideration many scenarios out there (at least in development env for now) and simplifies adapting to them. So I'd say you can start by planning things out here for the production env and getting others input, scenarios and ideas for the best way possible to approach this.

**Comment by Mahmoudz** [comment]
@calnation that would be cool.
_Also note the PHP version problem is fixed now._

**Comment by CharlieTapSonin** [comment]
As a quick bit of feedback for you guys on this, you shouldn't need to add both a Webserver and FPM into one container, in fact running multiple processes is taboo. Whilst I don't run laradock in production I run something very close to it, heres a quick break down:

Get rid of the workspace container, it will cause more trouble than its worth. No more mounting to the host OS, this is fine in dev but destroys portability in production.

Copy your laravel public folder into the webserver container.

Copy your laravel project into php fpm container. Also install cron on this container but don't run it.

These two new images will serve all the features of laravel you need.

Create three services from the fpm image, one for the actual fpm process, one for the laravel scheduler (just start the container with the cron start command), one for the laravel queue (Just start the container with the  artisan queue command )

Voila

**Comment by a-h-abid** [comment]
So... how would I run npm tasks without the workspace container? or composer install/update??

**Comment by CharlieTapSonin** [comment]
What tasks are you looking to run?

**Comment by cr101** [comment]
@CharlieTapSonin We are building React-powered websites using [Create React App](https://github.com/facebookincubator/create-react-app) so we need to run npm tasks like: `npm start` (The page will reload if you make edits), `npm run build`, `npm test`, etc.

**Comment by winfried-van-loon** [comment]
(off topic) For the react app, #553 could be interesting as well.

(on topic) I really like this discussion. We should implement it sooner rather than later, I think. Would mean a lot less maintenance, as well. However, we should not lose the aspect that makes Laradock pretty cool right now, the workspace functionality. We can still merge it into the php-fpm container and make it args, prefixed with `WORKSPACE_` or `DEV_` or something.

**Comment by CharlieTapSonin** [comment]
I'm not particularly familiar with react so I'm not sure if these tasks need to be called for pre production packaging or they are actual tasks that get called in production?

If its the former then it's straight forward enough, just run them prior to copying the files into the images using the existing workspace container.

If its the latter then you would just have to install npm and any other dependencies in the php fpm container.

The key thing really is just ensuring that tools for Dev and build stay in those phases of development, it will mean that your containers stay lighter and have less surface area for attack. That being said @winfried-van-loon you guys should look into using the alpine images for most of the containers, I'm running alpine nginx alongside alpine fpm and it's saved me hundreds of mb.

**Comment by cr101** [comment]
@CharlieTapSonin Those npm tasks are used during development so not called in production

**Comment by CharlieTapSonin** [comment]
@cr101 Then yeah just use the workspace container to prep the application files ready for copying into the production container, I actually do this on my CI/CD server as it saves a ton of time.

**Comment by poor-bob** [comment]
I've been scouring the documentation and source to find a way to essentially reverse engineer laradock to package these containers for portability so I can run laradock in production on kubernetes.

@CharlieTapSonin you seem knowledgable, may I ask for advice? I believe I have a simple use-case for Laravel: I want to use laravel in our CI/CD pipeline with Gitlab, which will re-create the Nginx & FPM containers via web hook. The problem is that Laradock doesn't seem production ready for anything other than docker-compose. Is it worth trying to make this work for my use-case or should I just start from scratch? 

Also, for things like composer, is it best practice to run 'composer install' at build time or deployment time? Seems to be a trade-off of either larger containers or slower deployments.
