### ISSUE TITLE
Hidden Directory?

### ISSUE THREAD

**Issue by androso** [LaraDock/laradock#82]
On Windows,
After creating a new project, e.g with the command "composer create-project laravel/laravel my-cool-app "5.2.*"" 

The "my-cool-app" directory is seen in the command shell with the "l" command but I can't find the directory with windows explorer?

**Comment by AminMkh** [comment]
I'm guessing you downloaded Laravel but in a directory not shared with Windows, which directory did you download Laravel in ?
