### ISSUE TITLE
non-downloaded containers passed 

### ISSUE THREAD

**Issue by PedramMarandi** [LaraDock/laradock#83]
Hello guys, 

I tried to pull Laradock container but when it was php-7 turn I closed terminal and process 4cea9bf5d067 marked as downloaded 
`Step 1 : FROM php:7.0-fpm
7.0-fpm: Pulling from library/php
51f5c6a04d83: Already exists
a3ed95caeb02: Pulling fs layer
a28c68f3894c: Already exists
1818204ff701: Already exists
4cea9bf5d067: Downloading [======>                                            ] 5.359 MB/40.85 MB
733550adfc5c: Download complete
99b1c7d2a3b6: Download complete`

Ho can i complete that process ?

**Comment by AminMkh** [comment]
Typically docker does a great job of determining which layers are downloaded then building them all together. I suggest doing 
```
docker-compose up nginx mysql
```
It should continue where it left off, if that doesn't work, just do a 
```
docker-compose build php-fpm
```
It should rebuild the php-fpm image again.
You can also remove the image entirely from your pc using
```
docker images
php                            7.0-fpm             51930951710a        3 weeks ago         500.9 MB
```
You will see a list of all images, then delete the php-fpm one
```
docker rmi -f 51930951710a
```

**Comment by PedramMarandi** [comment]
Yes I have tried `rmi` command but 7.0-fpm is not listed in images

**Comment by AminMkh** [comment]
so when you do ```docker-compose up nginx ``` what do you get ?
