### ISSUE TITLE
The display_errors is not working

### ISSUE THREAD

**Issue by zomboo** [laradock/laradock#832]
I have change "display_errors = off" to "display_errors = On " in php-fpm/php70.ini and laravel.ini , and restart the nginx and php-fpm ,but when I refresh the phpinfo page , it shows display_errors is still off.
so I can't display the php errors on the page.
Could you tell me how to fix it ,thanks.

**Comment by zomboo** [comment]
I am using Mac.

**Comment by zomboo** [comment]
And I found when I changed some configs in php70.ini, something is working , something is not working.why?

**Comment by zomboo** [comment]
[php-fpm.zip](https://github.com/laradock/laradock/files/947367/php-fpm.zip)
here is the php-fpm folder files

**Comment by winfried-van-loon** [comment]
To check what was going on, I tried to change the same variables as you have. Strangely, I did not come across the issue you've described. Here's what I did.

* Used a fresh Docker installation on a mac
* Copied `env-sample` to `.env`
* Set `PHP_VERSION=71` to `PHP_VERSION=70` to use the version you've mentioned.

```
docker-compose up -d --force-recreate --build nginx mariadb
```

With those settings, when running the previous command, the `phpinfo()` shows, as expected, that `display_errors` is set to `Off`.

* Changed `laravel.ini` to have `display_errors=On`
* Changed `php70.ini` to have `display_errors = On`

With those settings, when running the same command, the `phpinfo()` shows that `display_errors` is set to `On`. I've included a screenshot below.

<img width="979" alt="screen shot 2017-04-23 at 21 54 54" src="https://cloud.githubusercontent.com/assets/756956/25316944/fcd0791a-286f-11e7-822e-5beb92097c95.png">

To resolve your issue, I would suggest the following.
* Try the command I've used above to build and recreate everything if needed
* Make sure to have the latest version of Laradock
* Clone a fresh version of Laradock and follow the steps I have above and see where you get different results

Feel free to comment here if you've resolved the issue or are still having problems. Good luck!

**Comment by zomboo** [comment]
thank you very much.
Finally, I have found the reason.
Because the laravel.ini doesn't reload. I have modified display error from off to on in the laravel.ini in laradock/php-fpm/, and run 
 docker-compose stop, then run docker composer up -d  nginx mysql, but when I enter the php-fpm container, I find the laravel.ini still not change, it hasn't reload or
Updated. Could you tell me How to update the ini file?

**Comment by zomboo** [comment]
I try the cmd
 docker-compose up -d --force-recreate 
it works！
thanks very much!

**Comment by winfried-van-loon** [comment]
Hey, that's great news! Enjoy Laradock! 👍 If you've got any other issue, feel free to let us know.

**Comment by Soufraz** [comment]
I also can not view the php logs. I changed the directive in the php 7.1 php.ini but still phpinfo still shows that the display_errors is Off. 

Below my env file:

`############################
# General Setup
############################

### Application Path
# Point to your application code, will be available at `/var/www`.

APPLICATION=../

### Data Path:
# For all storage systems.

DATA_SAVE_PATH=~/.laradock/data

### PHP version
# Applies to the Workspace and PHP-FPM containers (Does not apply to HHVM)
# Accepted values: 71 - 70 - 56

PHP_VERSION=71

### PHP interpreter
# Accepted values: hhvm - php-fpm

PHP_INTERPRETER=php-fpm

############################
# Containers Customization
############################

### WORKSPACE ##########################################################################################################

WORKSPACE_INSTALL_XDEBUG=false
WORKSPACE_INSTALL_SOAP=false
WORKSPACE_INSTALL_MONGO=false
WORKSPACE_INSTALL_MSSQL=false
WORKSPACE_INSTALL_NODE=false
WORKSPACE_INSTALL_YARN=false
WORKSPACE_INSTALL_DRUSH=false
WORKSPACE_INSTALL_AEROSPIKE=false
WORKSPACE_INSTALL_V8JS=false
WORKSPACE_COMPOSER_GLOBAL_INSTALL=false
WORKSPACE_INSTALL_WORKSPACE_SSH=false
WORKSPACE_INSTALL_LARAVEL_ENVOY=false
WORKSPACE_INSTALL_LARAVEL_INSTALLER=false
WORKSPACE_INSTALL_DEPLOYER=false
WORKSPACE_INSTALL_LINUXBREW=false
WORKSPACE_INSTALL_MC=false
WORKSPACE_INSTALL_SYMFONY=false
WORKSPACE_INSTALL_PYTHON=false
WORKSPACE_INSTALL_IMAGE_OPTIMIZERS=false
WORKSPACE_PUID=1000
WORKSPACE_PGID=1000
WORKSPACE_NODE_VERSION=stable
WORKSPACE_YARN_VERSION=latest
WORKSPACE_TIMEZONE=UTC-3
WORKSPACE_SSH_PORT=2222

### PHP_FPM ############################################################################################################

PHP_FPM_INSTALL_XDEBUG=false
PHP_FPM_INSTALL_MONGO=false
PHP_FPM_INSTALL_MSSQL=false
PHP_FPM_INSTALL_SOAP=false
PHP_FPM_INSTALL_ZIP_ARCHIVE=false
PHP_FPM_INSTALL_BCMATH=false
PHP_FPM_INSTALL_PHPREDIS=false
PHP_FPM_INSTALL_MEMCACHED=false
PHP_FPM_INSTALL_OPCACHE=false
PHP_FPM_INSTALL_EXIF=false
PHP_FPM_INSTALL_AEROSPIKE=false
PHP_FPM_INSTALL_MYSQLI=false
PHP_FPM_INSTALL_TOKENIZER=false
PHP_FPM_INSTALL_INTL=false
PHP_FPM_INSTALL_GHOSTSCRIPT=false
PHP_FPM_INSTALL_LDAP=false
PHP_FPM_INSTALL_SWOOLE=false
PHP_FPM_INSTALL_IMAGE_OPTIMIZERS=false

### NGINX ##############################################################################################################

NGINX_HOST_HTTP_PORT=80
NGINX_HOST_HTTPS_PORT=443
NGINX_HOST_LOG_PATH=./logs/nginx/
NGINX_SITES_PATH=./nginx/sites/
NGINX_PHP_UPSTREAM_CONTAINER=php-fpm
NGINX_PHP_UPSTREAM_PORT=9000

### APACHE #############################################################################################################

APACHE_HOST_HTTP_PORT=80
APACHE_HOST_HTTPS_PORT=443
APACHE_HOST_LOG_PATH=./logs/apache2
APACHE_SITES_PATH=./apache2/sites
APACHE_PHP_UPSTREAM_CONTAINER=php-fpm
APACHE_PHP_UPSTREAM_PORT=9000

### MYSQL ##############################################################################################################

MYSQL_VERSION=5.6
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d

### REDIS ##############################################################################################################

REDIS_PORT=6379

### Percona ############################################################################################################

PERCONA_DATABASE=homestead
PERCONA_USER=homestead
PERCONA_PASSWORD=secret
PERCONA_PORT=3306
PERCONA_ROOT_PASSWORD=root
PERCONA_ENTRYPOINT_INITDB=./percona/docker-entrypoint-initdb.d

### MSSQL ##############################################################################################################

MSSQL_DATABASE=homestead
MSSQL_PASSWORD=yourStrong(!)Password
MSSQL_PORT=1433

### MARIADB ############################################################################################################

MARIADB_DATABASE=default
MARIADB_USER=default
MARIADB_PASSWORD=secret
MARIADB_PORT=3306
MARIADB_ROOT_PASSWORD=root
MARIADB_ENTRYPOINT_INITDB=./mariadb/docker-entrypoint-initdb.d

### POSTGRES ###########################################################################################################

POSTGRES_DB=default
POSTGRES_USER=default
POSTGRES_PASSWORD=secret
POSTGRES_PORT=5432

### RABBITMQ ###########################################################################################################

RABBITMQ_NODE_HOST_PORT=5672
RABBITMQ_MANAGEMENT_HTTP_HOST_PORT=15672
RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT=15671
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest

### ELASTICSEARCH ######################################################################################################

ELASTICSEARCH_HOST_HTTP_PORT=9200
ELASTICSEARCH_HOST_TRANSPORT_PORT=9300

### KIBANA #############################################################################################################

KIBANA_HTTP_PORT=5601

### MEMCACHED ##########################################################################################################

MEMCACHED_HOST_PORT=11211

### BEANSTALKD CONSOLE #################################################################################################

BEANSTALKD_CONSOLE_BUILD_PATH=./beanstalkd-console
BEANSTALKD_CONSOLE_CONTAINER_NAME=beanstalkd-console
BEANSTALKD_CONSOLE_HOST_PORT=2080

### BEANSTALKD #########################################################################################################

BEANSTALKD_HOST_PORT=11300

### SELENIUM ###########################################################################################################

SELENIUM_PORT=4444

### MINIO ##############################################################################################################

MINIO_PORT=9000

### ADMINER ############################################################################################################

ADM_PORT=8080
ADM_INSTALL_MSSQL=false

### PHP MY ADMIN #######################################################################################################

# Accepted values: mariadb - mysql

PMA_DB_ENGINE=mysql

# Credentials/Port:

PMA_USER=default
PMA_PASSWORD=secret
PMA_ROOT_PASSWORD=secret
PMA_PORT=8080

### VARNISH ############################################################################################################

VARNISH_CONFIG=/etc/varnish/default.vcl
VARNISH_PORT=8080
VARNISH_BACKEND_PORT=8888
VARNISHD_PARAMS=-p default_ttl=3600 -p default_grace=3600

### Varnish ############################################################################################################

# Proxy 1

VARNISH_PROXY1_CACHE_SIZE=128m
VARNISH_PROXY1_BACKEND_HOST=workspace
VARNISH_PROXY1_SERVER=SERVER1

# Proxy 2

VARNISH_PROXY2_CACHE_SIZE=128m
VARNISH_PROXY2_BACKEND_HOST=workspace
VARNISH_PROXY2_SERVER=SERVER2

### HAPROXY ############################################################################################################

HAPROXY_HOST_HTTP_PORT=8085

### JENKINS ############################################################################################################

JENKINS_HOST_HTTP_PORT=8090
JENKINS_HOST_SLAVE_AGENT_PORT=50000
JENKINS_HOME=./jenkins/jenkins_home

### BLACKFIRE ##########################################################################################################

# Create an account on blackfire.io. Don't enable blackfire and xDebug at the same time.
# visit https://blackfire.io/docs/24-days/06-installation#install-probe-debian for more info.

INSTALL_BLACKFIRE=false
BLACKFIRE_CLIENT_ID=<client_id>
BLACKFIRE_CLIENT_TOKEN=<client_token>
BLACKFIRE_SERVER_ID=<server_id>
BLACKFIRE_SERVER_TOKEN=<server_token>

### AEROSPIKE ##########################################################################################################

AEROSPIKE_SERVICE_PORT=3000
AEROSPIKE_FABRIC_PORT=3001
AEROSPIKE_HEARTBEAT_PORT=3002
AEROSPIKE_INFO_PORT=3003

### RETHINKDB ##########################################################################################################

RETHINKDB_PORT=8090

### MONGODB ############################################################################################################

MONGODB_PORT=27017

### CADDY ##############################################################################################################

CADDY_HOST_HTTP_PORT=80
CADDY_HOST_HTTPS_PORT=443
CADDY_HOST_LOG_PATH=./logs/caddy
CADDY_CUSTOM_CADDYFILE=./caddy/Caddyfile

### LARAVEL ECHO SERVER ################################################################################################

LARAVEL_ECHO_SERVER_PORT=6001

### DOCKER-SYNC ################################################################################################

# osx: 'native_osx' (default)
# windows: 'unison'
# linux: docker-sync not required

DOCKER_SYNC_STRATEGY=native_osx

##### TO BE CONTINUE .................................

# ......... Missing: neo4j mongo rethinkdb redis aerospike pgadmin...
# .........
# .........

############################
# Miscellaneous
############################

# Replace with your Docker Host IP (will be appended to /etc/hosts)

DOCKER_HOST_IP=10.0.75.1


# The Remote Interpreter entry matching name `laradock`

PHP_IDE_CONFIG=serverName=laradock


# Fix for windows users to make sure the application path works.

COMPOSE_CONVERT_WINDOWS_PATHS=1

`

**Comment by jonzrj** [comment]
after modified laravel.ini and try `docker-compose up -d --force-recreate --build php-fpm`
it works for me

**Comment by sowork** [comment]
How do you make configuration files automatically synced？

**Comment by pathros** [comment]
Based on what @Z2l0 did, for me it worked with:
`docker-compose up -d --build php-fpm`.

But why do we have to do this? Like @sowork asked, how do we reload the `laravel.ini` configuration changes we've just made, without having to restart or rebuild the containers?

In other posts, [such as this one](https://stackoverflow.com/a/43076457/1883256), they suggest killing a process which loads the php.ini, but the Laradock's php container does not have neither the `ps` nor the `pkill` commands. If you try to install ps command, the `apt-get` doesn't find it. This has become cumbersome.

Any ideas how to reload those settings without rebuilding (stopping) the container?

**Comment by devkacper** [comment]
I have simmilar problem with project based on swoole and upload_max_filesize rule. The only way is edit php.ini inside workspace container but when docker is going down container just return default php.ini configuration. I don't use php-fpm only nginx and swoole inside workspace container.

Maybe someone have tip for this case?
