### ISSUE TITLE
Undefined class constant 'SQLSRV_ATTR_FETCHES_NUMERIC_TYPE' for mssql driver

### ISSUE THREAD

**Issue by chkm8** [laradock/laradock#843]
I am using Ms Sql (For project Requirement) for my database and I know laradock has already supported ms sql container. Mssql need to have sqlsrv installed, I already installed it in the workspace and I was able to use php artisan migrate, the problem in mssql is the integer from db is converted as string so we will put attrib SQLSRV_ATTR_FETCHES_NUMERIC_TYPE = true, but when you refresh the browser you will have this error Undefined class constant 'SQLSRV_ATTR_FETCHES_NUMERIC_TYPE' , I already updated the php-fpm with the latest mssql driver but still not working, already checked that sqlsrv is loaded in php-fpm module by using php -m. My last option would be in apache2 but there is no php.ini in that container, any ideas?

**Comment by thorerik** [comment]
How did you set this? please provide at least a partial code example of how you did this.

**Comment by chkm8** [comment]
I already fixed it, somehow the current driver that is being installed via the docker file is not updated that is why SQLSRV_ATTR_FETCHES_NUMERIC_TYPE  is not found. I edited the Dockerfile-71 for php-fpm to install the latest driver.
```
    #####################################
    # Install sqlsrv y pdo_sqlsrv
    # extensions:
    #####################################
    
    pecl install sqlsrv-4.1.7preview && \
    pecl install pdo_sqlsrv-4.1.7preview && \
```

**Comment by winfried-van-loon** [comment]
Should be fixed now, thanks for the research! 👍
