### ISSUE TITLE
MSSQL Initialise Problem 

### ISSUE THREAD

**Issue by arnondora** [laradock/laradock#846]
I have run `docker-compose up mssql` and it turnout to be error as a log in the following

```
mssql_1               | This is an evaluation version.  There are [177] days left in the evaluation period.
mssql_1               | 2017-04-22 11:50:39.89 Server      Microsoft SQL Server vNext (CTP2.0) - 14.0.500.272 (X64) 
mssql_1 Apr 13 2017 11:44:40 
mssql_1 Copyright (C) 2017 Microsoft Corporation. All rights reserved.
mssql_1 Developer Edition (64-bit) on Linux (Ubuntu 16.04.2 LTS)
2017-04-22 11:50:39.89 Server      UTC adjustment: 0:00
2017-04-22 11:50:39.90 Server      (c) Microsoft Corporation.
2017-04-22 11:50:39.90 Server      All rights reserved.
2017-04-22 11:50:39.90 Server      Server process ID is 4116.
2017-04-22 11:50:39.90 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2017-04-22 11:50:39.91 Server      Registry startup parameters: 
mssql_1  -d /var/opt/mssql/data/master.mdf
mssql_1  -l /var/opt/mssql/data/mastlog.ldf
mssql_1  -e /var/opt/mssql/log/errorlog
2017-04-22 11:50:39.94 Server      Error: 17113, Severity: 16, State: 1.
2017-04-22 11:50:39.94 Server      Error 87(The parameter is incorrect.) occurred while opening file '/var/opt/mssql/data/master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.
2017-04-22 11:50:39.95 Server      SQL Server shutdown has been initiated
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
mssql_1               | Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
mssql_1               | Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```

**Comment by thorerik** [comment]
I'm unable to reproduce this issue.

Can you please provide the contents of your .env file?

**Comment by arnondora** [comment]
Here's my .env file
`############################
# General Setup
############################

### Application Path
# Point to your application code, will be available at `/var/www`.

APPLICATION=../

### Data Path:
# For all storage systems.

DATA_SAVE_PATH=../data

### PHP version
# Applies to the Workspace and PHP-FPM containers (Does not apply to HHVM)
# Accepted values: 71 - 70 - 56

PHP_VERSION=71

### PHP interpreter
# Accepted values: hhvm - php-fpm

PHP_INTERPRETER=php-fpm

############################
# Containers Customization
############################

### WORKSPACE Container ################################################################################################

WORKSPACE_INSTALL_XDEBUG=false
WORKSPACE_INSTALL_SOAP=false
WORKSPACE_INSTALL_MONGO=false
WORKSPACE_INSTALL_NODE=true
WORKSPACE_INSTALL_YARN=true
WORKSPACE_INSTALL_DRUSH=false
WORKSPACE_INSTALL_AEROSPIKE_EXTENSION=false
WORKSPACE_INSTALL_INSTALL_V8JS_EXTENSION=false
WORKSPACE_COMPOSER_GLOBAL_INSTALL=false
WORKSPACE_INSTALL_WORKSPACE_SSH=false
WORKSPACE_INSTALL_LARAVEL_ENVOY=false
WORKSPACE_INSTALL_DEPLOYER=false
WORKSPACE_INSTALL_LINUXBREW=false
WORKSPACE_INSTALL_MC=false
WORKSPACE_PUID=1000
WORKSPACE_PGID=1000
WORKSPACE_NODE_VERSION=stable
WORKSPACE_YARN_VERSION=latest
WORKSPACE_TIMEZONE=UTC
WORKSPACE_SSH_PORT=2222

### PHP_FPM Container ##################################################################################################

PHP_FPM_INSTALL_XDEBUG=false
PHP_FPM_INSTALL_MONGO=false
PHP_FPM_INSTALL_SOAP=false
PHP_FPM_INSTALL_ZIP_ARCHIVE=false
PHP_FPM_INSTALL_BCMATH=false
PHP_FPM_INSTALL_PHPREDIS=false
PHP_FPM_INSTALL_MEMCACHED=false
PHP_FPM_INSTALL_OPCACHE=false
PHP_FPM_INSTALL_EXIF=false
PHP_FPM_INSTALL_AEROSPIKE_EXTENSION=false
PHP_FPM_INSTALL_MYSQLI=true
PHP_FPM_INSTALL_TOKENIZER=false
PHP_FPM_INSTALL_INTL=false
PHP_FPM_INSTALL_GHOSTSCRIPT=false

### NGINX Container ####################################################################################################

NGINX_HOST_HTTP_PORT=80
NGINX_HOST_HTTPS_PORT=443
NGINX_HOST_LOG_PATH=./logs/nginx/
NGINX_SITES_PATH=./nginx/sites/

### BLACKFIRE Container ################################################################################################
# Create an account on blackfire.io
# Don't enable blackfire and xDebug at the same time
# see https://blackfire.io/docs/24-days/06-installation#install-probe-debian
INSTALL_BLACKFIRE=false
BLACKFIRE_CLIENT_ID=<client_id>
BLACKFIRE_CLIENT_TOKEN=<client_token>
BLACKFIRE_SERVER_ID=<server_id>
BLACKFIRE_SERVER_TOKEN=<server_token>

### APACHE Container ###################################################################################################

APACHE_HOST_HTTP_PORT=80
APACHE_HOST_HTTPS_PORT=443
APACHE2_PHP_SOCKET=php-fpm:9000
APACHE_HOST_LOG_PATH=./logs/apache2
PHP_SOCKET=php-fpm:9000

### MYSQL Container ####################################################################################################

MYSQL_DATABASE=MyDB
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root

### Percona Container ##################################################################################################

PERCONA_DATABASE=homestead
PERCONA_USER=homestead
PERCONA_PASSWORD=secret
PERCONA_PORT=3306
PERCONA_ROOT_PASSWORD=root

### MSSQL Container ####################################################################################################

MSSQL_DATABASE=MyDatabase
MSSQL_PASSWORD=An123456789
MSSQL_PORT=1433

### MARIADB Container ##################################################################################################

MARIADB_DATABASE=default
MARIADB_USER=default
MARIADB_PASSWORD=secret
MARIADB_PORT=3306
MARIADB_ROOT_PASSWORD=root

### POSTGRES Container #################################################################################################

POSTGRES_DB=default
POSTGRES_USER=default
POSTGRES_PASSWORD=secret
POSTGRES_PORT=5432

### RABBITMQ Container #################################################################################################

RABBITMQ_NODE_HOST_PORT=5672
RABBITMQ_MANAGEMENT_HTTP_HOST_PORT=15672
RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT=15671
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest

### ELASTICSEARCH Container ############################################################################################

ELASTICSEARCH_HOST_HTTP_PORT=9200
ELASTICSEARCH_HOST_TRANSPORT_PORT=9300

### MEMCACHED Container ################################################################################################

MEMCACHED_HOST_PORT=11211

### BEANSTALKD CONSOLE #################################################################################################

BEANSTALKD_CONSOLE_BUILD_PATH=./beanstalkd-console
BEANSTALKD_CONSOLE_CONTAINER_NAME=beanstalkd-console
BEANSTALKD_CONSOLE_HOST_PORT=2080

### BEANSTALKD Container ###############################################################################################

BEANSTALKD_HOST_PORT=11300

### SELENIUM Container #################################################################################################

SELENIUM_PORT=4444

### MINIO Container ####################################################################################################

MINIO_PORT=9000

### ADMINER Container ##################################################################################################

ADM_PORT=88

### PHP MY ADMIN Container #############################################################################################

# Accepted values: mariadb - mysql

PMA_DB_ENGINE=mysql

# Credentials/Port:

PMA_USER=default
PMA_PASSWORD=secret
PMA_ROOT_PASSWORD=secret
PMA_PORT=88

### VARNISH Container ##################################################################################################

VARNISH_CONFIG=/etc/varnish/default.vcl
VARNISH_PORT=8080
VARNISH_BACKEND_PORT=8888
VARNISHD_PARAMS=-p default_ttl=3600 -p default_grace=3600

### Varnish Container ##################################################################################################

# Proxy 1

VARNISH_PROXY1_CACHE_SIZE=128m
VARNISH_PROXY1_BACKEND_HOST=workspace
VARNISH_PROXY1_SERVER=SERVER1

# Proxy 2

VARNISH_PROXY2_CACHE_SIZE=128m
VARNISH_PROXY2_BACKEND_HOST=workspace
VARNISH_PROXY2_SERVER=SERVER2

### HAPROXY Container ##################################################################################################

HAPROXY_HOST_HTTP_PORT=8085

### JENKINS Container ##################################################################################################

JENKINS_HOST_HTTP_PORT=8090
JENKINS_HOST_SLAVE_AGENT_PORT=50000
JENKINS_HOME=./jenkins/jenkins_home

##### TO BE CONTINUE .................................

# ......... Missing: neo4j mongo rethinkdb redis aerospike pgadmin...
# .........
# .........



############################
# Miscellaneous
############################

# Replace with your Docker Host IP (will be appended to /etc/hosts)

DOCKER_HOST_IP=10.0.75.1


# The Remote Interpreter entry matching name `laradock`

PHP_IDE_CONFIG=serverName=laradock


# Fix for windows users to make sure the application path works.

COMPOSE_CONVERT_WINDOWS_PATHS=1
`

**Comment by arnondora** [comment]
Here's my .env file
https://gist.github.com/arnondora/879e2d53b4d945856a5b60669e3e1105

**Comment by thorerik** [comment]
I suggest wiping the data directory used by MSSQL and re-initilizing the container, then batch load your data again, can't see any obvious reasons why this should fail. If it still fails, I think you should see if it happens if you use the bare `microsoft/mssql-server-linux` container, if so, https://github.com/Microsoft/mssql-docker is the right place to raise an issue, if not, if you can share the data loaded into SQLserver, I can maybe tell whats going wrong.

**Comment by arnondora** [comment]
I have found that if I doesn't mount the data file, everything run smoothly but when I use default settings of laradock which mount data files into ../data/mssql, it got an error that I mentioned before. I struggle this problem on macOS, I don't know that this problem happen in other platform.

**Comment by winfried-van-loon** [comment]
Perhaps the port is already being used by another application?

**Comment by chkm8** [comment]
Hi, I'm also having this error in the updated/latest laradock version, but when I tried the https://hub.docker.com/r/microsoft/mssql-server-linux/ docker container I was able to create it successfully and linked to the laradock containers.

**Comment by Nelsoft-EphraimLambarte** [comment]
I am experiencing an error as well in running docker-compose up mssql:

`Attaching to laradock_mssql_1
mssql_1                | tail: cannot open '/dev/null'$'\r' for reading: No such file or directory
mssql_1                | tail: no files remaining
laradock_mssql_1 exited with code 1`

this is my .env file: https://pastebin.com/FLWU9S5i

**Comment by bradleySuira** [comment]
Hi @Nelsoft-EphraimLambarte, it's happened a couple of months ago, not sure if it´s fixed now but I'm not using PHP for some time, but if the error is the same, you need to edit the docker-compose.yml file in the services section of laradock, find `volumes:` and change `- ${DATA_PATH_HOST}/mssql:/var/opt/mssql` to `- mssql:/var/opt/mssql` you can´t use DATA_PATH_HOST on mac with you setting for example `~/.laradock/data` in a local folder instead you can find the volumen associated to the container using `docker volume ls` and then `docker volume inspect [VOLUME_NAME]`

Regards!

**Comment by Nelsoft-EphraimLambarte** [comment]
@bradleySuira  im really sorry, i forgot to mention im using a windows 10 machine.

**Comment by bradleySuira** [comment]
@Nelsoft-EphraimLambarte no problem, I don't use windows but maybe we have the same issue than macOs because is not linux :)

**Comment by Kayvaan44** [comment]
@Nelsoft-EphraimLambarte I have the same error, did you find a way to solve it or any workaround?

**Comment by robbygallo** [comment]
> I am experiencing an error as well in running docker-compose up mssql:
> 
> `Attaching to laradock_mssql_1 mssql_1 | tail: cannot open '/dev/null'$'\r' for reading: No such file or directory mssql_1 | tail: no files remaining laradock_mssql_1 exited with code 1`
> 
> this is my .env file: https://pastebin.com/FLWU9S5i

i have the same issue on win10 with the latest version of laradock

**Comment by bradleySuira** [comment]
@robbydooo Hi, you can't use the env var as is: `DATA_PATH_HOST=~/.laradock/data`, you need to edit your `you need to edit the docker-compose.yml` file, check my past comment: [https://github.com/laradock/laradock/issues/846#issuecomment-434549501](https://github.com/laradock/laradock/issues/846#issuecomment-434549501)

Hope it helps, (I assuming that you are using macOs), Regards!

**Comment by robbygallo** [comment]
@bradleySuira 
i have tried your solution without success.

`docker-compose --verbose up mssql`

get me 

```
Attaching to laradock_mssql_1
compose.cli.verbose_proxy.proxy_callable: docker events <- (filters={'label': ['com.docker.compose.project=laradock', 'com.docker.compose.oneofmssql_1                |f=False']}, decode=True) sleep: invalid time interval '45\r'

mssql_1                | Try 'sleep --help' for more information.
mssql_1                | tail: **cannot open '/dev/null'$'\r'** for reading: No such file or directory
mssql_1                | tail: no files remaining
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/events?filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dlaradock%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker events -> <docker.types.daemon.CancellableStream object at 0x0000017F17D7AE48>
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('f92299dea904b8e1768f49e17184b50193b8ddf895b536cdc8833603588b1fe2')
compose.cli.verbose_proxy.proxy_callable: docker wait <- ('f92299dea904b8e1768f49e17184b50193b8ddf895b536cdc8833603588b1fe2')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/f92299dea904b8e1768f49e17184b50193b8ddf895b536cdc8833603588b1fe2/json HTTP/1.1" 200 None
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/f92299dea904b8e1768f49e17184b50193b8ddf895b536cdc8833603588b1fe2/wait HTTP/1.1" 200 30
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
 'Args': ['-c', '/bin/bash ./entrypoint.sh'],
 'Config': {'ArgsEscaped': True,
            'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['/bin/sh', '-c', '/bin/bash ./entrypoint.sh'],
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['MSSQL_DATABASE=homestead',
...
compose.cli.verbose_proxy.proxy_callable: docker wait -> {'Error': None, 'StatusCode': 1}
laradock_mssql_1 exited with code 1
```
i hae found the error in the second line:

`sleep: invalid time interval '45\r'`

but i am not able to solve it

**Comment by rmeira** [comment]
I have the same problem ... :/
My SO is Win 10

![image](https://user-images.githubusercontent.com/8323576/57989910-c2d5d000-7a77-11e9-8c8f-f5ebc10f2641.png)

**Comment by Topith** [comment]
I also encountered the problem while installing mssql in laradock  : (
win10 docker desktop
