### ISSUE TITLE
Apache2 Docroot

### ISSUE THREAD

**Issue by kevin-coyle** [laradock/laradock#849]
Just done a recent clone of the project and I've noticed that the document root is set to /var/www instead of /var/www/public in the apache2 container.

Is there a variable in the .env file to control this? I can see
```
ENV WEB_DOCUMENT_ROOT=/var/www
```
In the Dockerfile, it used to be /var/www/public

**Comment by winfried-van-loon** [comment]
This should just work. For the NGINX container, it looks for the public directory, for the Apache container, it does not. It should either be both looking for the public directory, or both not looking for the public directory.

**Comment by kevin-coyle** [comment]
Hmm they seem to be different now

**Comment by winfried-van-loon** [comment]
This should have been fixed in the #850 pull request. If you're still experiencing this issue, let us know. 👍

**Comment by vladthecodeimpaler** [comment]
Hi Guys,

apache2 doesnt work by default again, whats the reason for the revert?
```
DocumentRoot /var/www/public
is now
DocumentRoot /var/www/
```

**Comment by Mahmoudz** [comment]
@vladthecodeimpaler cause without creating the `public` folder the container causes errors. Without this it will be working same like NGINX, and reading all the projects on the /var/www/ which is the directory where the Laradock folder exist.

**Comment by benkelukas** [comment]
Hi, I have the same problem, will this be configurable in .env in the future? Right now i have rewritten it in default.apache.conf, but that does not seem right :)

Thanks
