### ISSUE TITLE
Existing laravel project dont "mount" the project directory into a container

### ISSUE THREAD

**Issue by JulianaApolo** [LaraDock/laradock#85]
I have a laravel project directory into my machine and I used git submodule to clone de laradock. A laradock directory was created into my laravel project directory. I entered into the laradock directory and I run "docker-composer up -d nginx mysql redis" and the containers started correctly. But when I enter to the bash, into de /var/www/laravel, don`t show my project files. When I go to the browser and enter "http://192.168.99.100/" I see "404 Not Found nginx".

I tried to change my .env file where is "localhost" to docker ip, but doesn't work too.

Please, help me.
What am i doing wrong?

**Comment by Mahmoudz** [comment]
From what you are explaining seems everything correct! now can you tell me which version of docker are you using? and also which one for docker-compose. And most importantly are you using the docker machine? or the native Docker beta?

**Comment by JulianaApolo** [comment]
Hi Mahmoundz,

Thanks your response.

I'm using Mac. 
Docker version 1.11.0.
Docker Compose version 1.8.0.
Permissions of local laravel project directory and all files into: rwx-rwx-rwx

**Comment by Mahmoudz** [comment]
1. try pulling the latest version, and test everything again.

2. I'm using older Docker version on my machine (will update soon), however are you using the docker machine?

3. When you mentioned "I enter to the bash" did you meant you typed `docker exec -it laradock_workspace_1 bash` and then when you typed `ls` you see nothing?

4. I want you to check this line `- ../:/var/www/laravel` in the docker-compose.yml file and maybe try to modify it and see if it affects the error basically `../` should point the laravel home directory.

5. Finally also you might need to check this line `root /var/www/laravel/public;` in the laravel.conf file inside the nginx folder.

I couldn't think of other possibilities for now!

**Comment by nemanjam** [comment]
I think she is using virtualbox and her project is outside home directory that is mounted by default with the toolbox.

**Comment by MeixnerTobias** [comment]
Agree with @nemanjam 
This should be related to shared folders defined and mapping in docker-machine.

In Windows there seems to be an issue with case of folder e.g. in Windows by default
C:/Users
the laradock folder is correctly mounted but into /c/users/ in guest system
So in docker-compose.yml it should be set to
/c/Users/PATHTOYOURLARAVELAPP

![image](https://cloud.githubusercontent.com/assets/2327615/15801150/3c6edf66-2ab6-11e6-8672-0d3cb73c423d.png)

**Comment by uar-daniel-gafitescu** [comment]
The code needs to be on /Users/[xxxxx] directory

**Comment by JulianaApolo** [comment]
@nemanjam yes, I`m using Virtual Box.
I saw in Virtualbox configuration and I have /Users shared folder.
I put my laravel project into /Users of my computer and started the "docker-compose up nginx...."
When I enter the bash of laravel_workspace_1 container and type ls I can`t see my laravel project yet.

Please, what am i doing wrong?
Can you explain step by step what I have to do?

**Comment by nhieunguyen** [comment]
*Note: If you are using Docker Machine on Mac or Windows, your Docker Engine daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your /Users (OS X) or C:\Users (Windows) directory. So, you can mount files or directories on OS X using. (https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume)
*I use win , after clone src from git:
-C:\Users\projects\laradock
-C:\Users\projects\my-cool-app
*Edit docker-compose.yml:
    application:
        build: ./application
        volumes:
            - ../my-cool-app/:/var/www/laravel
*Go to C:\Users\projects\laradock and run
docker-compose up -d  nginx mysql

**Comment by GeoIntranet** [comment]
Hi ! i have exactly the same issue ! i don't understand what's append !
- 1 : create a new laravel project 
- 2 : init git in the project folder
- 3  : git submodule add https://github.com/LaraDock/laradock.git
- 4 :  cd in laradock and docker-composer up -d nginx mysql 
- 5 : exec .... workspace 
-----------------------------------------------------------------
But i didn't see the project ! only the laradock folder >< ....
Any idea ? i'm on win 10 
thanks !

**Comment by Mahmoudz** [comment]
Let's just upgrade.

1. Upgrade your LaraDock `git pull origin master`. 
_(LaraDock v4 works only with Docker for Mac/Windows. If you want to keep using LaraDock toolbox (VM) use LaraDock v3)._
2. Rebuild your containers `docker-compose build --no-cache` (This might wipe your Data container)
3. Try again.. best of luck :)
