### ISSUE TITLE
Upgrade Docker-Compose Syntax to V3

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#861]
[Compose file version 3 reference](https://docs.docker.com/compose/compose-file/)

**Comment by calnation** [comment]
Note v3 is heavily geared towards production env, e.g. there are issues with local persistence docker/compose#4379

**Comment by CharlieTapSonin** [comment]
From the talks at DockerCon it looks like they're working on the issues caused from the v2 to v3 jump, but the solution is a way off. In the interim the compose file could at least be upgraded to 2.2, the new depends_on healthchecks are really useful for overcoming issues where containers still start before others (I.E. in CI Servers)

**Comment by Nvservicing** [comment]
Is there a solution for that ?

**Comment by Mahmoudz** [comment]
a0c5ef75d2cc3462af537cb3a385ccb728e585c3
