### ISSUE TITLE
applications exited with code 0

### ISSUE THREAD

**Issue by ghost** [laradock/laradock#863]
the applications container exited automatically after starting it with a message "applications exited with code 0 "

**Comment by winfried-van-loon** [comment]
This could be the same issue as mentioned within #864

**Comment by winfried-van-loon** [comment]
@madaonoyabo To find the issue, we'll need some additional information. Could you tell more about what you're trying to do, what command is used to bring Laradock up and if you've got the latest Laradock version?

**Comment by jvzanatta** [comment]
Same here... After all the containers start, i get `applications_1 exited with code 0`.

```
SO: Ubuntu 16.04 (Gnome)
docker-compose --version
docker-compose version 1.11.1, build 7c5d5e4
docker --version 
Docker version 17.03.1-ce, build c6d412e
```

**Comment by gbgelado** [comment]
Same here :/

```
# docker --version
Docker version 17.05.0-ce, build 89658be

# docker --version
Docker version 17.05.0-ce, build 89658be
