### ISSUE TITLE
Workspace fails to build

### ISSUE THREAD

**Issue by aft3rlife** [laradock/laradock#864]
Using a fresh clone of Laradock as of today (25/04/2017), it fails to build workspace.

`ERROR: Service 'workspace' failed to build: One or more build-args [INSTALL_LINUXBREW INSTALL_SOAP YARN_VERSION INSTALL_V8JS_EXTENSION INSTALL_LARAVEL_ENVOY INSTALL_MC INSTALL_DEPLOYER] were not consumed, failing build.`

Using Ubuntu 17.04.

**Comment by thorerik** [comment]
Confirmed, It seems the php71 container doesn't have soap (maybe others) in it's installation steps

**Comment by winfried-van-loon** [comment]
Without a doubt, we should fix that. However, there may be another issue, as when I try to reproduce that issue, I'm getting an warning, not an error.

```
[Warning] One or more build-args [INSTALL_MC INSTALL_V8JS_EXTENSION INSTALL_LARAVEL_ENVOY INSTALL_LINUXBREW INSTALL_DEPLOYER YARN_VERSION INSTALL_SOAP] were not consumed
```

**Comment by winfried-van-loon** [comment]
Should be fixed now 👍 Let us know if you're still experiencing issues.

**Comment by mitjarobic** [comment]
i am getting the following error in ubuntu

Service 'workspace' failed to build: One or more build-args [INSTALL_MSSQL] were not consumed, failing build.

**Comment by winfried-van-loon** [comment]
Moved to #895

**Comment by bestlong** [comment]
Hi @aft3rlife  Please upgrade docker version > 1.13

https://github.com/moby/moby/pull/27412
