### ISSUE TITLE
Connecting Laravel Project with Host Mysql

### ISSUE THREAD

**Issue by Hironate** [laradock/laradock#869]
I have following laravel .env file

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1 (mysql - works fine with docker mysql containers)
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=root
```

If i connect db with DOCKER mysql Container it works perfectly fine. I want to migrate my data into host's my sql through laradock containers. 

i tried binding

```
bind-address = 127.0.0.1
````
 in my.cnf in mysql docker config. but it didn't helped out.

Please guide me how to do it.

**Comment by winfried-van-loon** [comment]
If you're using the mysql container, you cam do this:

```ini
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=root
````

For MariaDB, its similair:

```ini
DB_CONNECTION=mysql
DB_HOST=mariadb
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=root
```

This is because the php-fpm container and database container are not on the same machine. Therefore, 127.0.0.1 or localhost won't work. You could lookup the container IP, however just connecting by the socket name like above works fine, most of the time.

To connect to mysql from your host, see the docs: http://laradock.io/documentation/#mysql-access-from-host

**Comment by Hironate** [comment]
@winfried-van-loon i don't want to use docker's Mysql container, i want to use host's mysql server. It's perfectly working fine if i use docker mysql container.

**Comment by winfried-van-loon** [comment]
Right, then I misunderstood the question.

**Comment by Hironate** [comment]
I found a solution, i bind my host mysql with binding-address="0.0.0.0" and In .env file i used Bridge IP Address to access host mysql server.

**Comment by core01** [comment]
@Hironate your solution does not work for me.
I have ubuntu 16.04 as host and MariaDB 10.
Did you do something else with my.cnf?

**Comment by Shivani-Parihar** [comment]
@Hironate can you please paste your .env file and .mycnf for mysql container

**Comment by AdrianoMarra** [comment]
@Hironate Can you please explain better how did you solve this problem?

**Comment by Hironate** [comment]
@Shivani-Parihar @AdrianoMarra in your hosts mysql config bing address from bind-address = 127.0.0.0 to 0.0.0.0 and use your bridge ip address to access host.

- use `docker ps` command to get list of containers and copy bridge container id.
- use `docker inspect <cid>` to get ip address and of bridge container,
- use that ip as host of your db application
- kindly add access privilege of bridge_ip in your mysql db

**Comment by latanoel** [comment]
This worked for me using laradock nginx and mysql containers

```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=root
DB_PASSWORD=root
```

**Comment by sovrinbloc** [comment]
go into hosts and add `127.0.0.1 mysql`. The docker container name is hosts in the Dockerfile so inside .env you have it looking for mysql attached the DB_HOST=mysql. So inside the browser it works correctly but when you are running migrations (well at least in my case) it wouldn't work with mysql. In shell I had to have it set to 0.0.0.0 and then I could run migrations, but I couldn't connect in the browser. so the solution was in hosts.

hosts
`127.0.0.1 mysql`

save.
done.

**Comment by redzjovi** [comment]
> @Shivani-Parihar @AdrianoMarra in your hosts mysql config bing address from bind-address = 127.0.0.0 to 0.0.0.0 and use your bridge ip address to access host.
> 
> * use `docker ps` command to get list of containers and copy bridge container id.
> * use `docker inspect <cid>` to get ip address and of bridge container,
> * use that ip as host of your db application
> * kindly add access privilege of bridge_ip in your mysql db

It works. Use docker inspect <cid>, and use ip from gateway, to access local host machine from docker host.

**Comment by khushbupatel24** [comment]
@Hironate ,

 - use docker inspect <cid> to get ip address and of bridge container.

But what if ip address changed after we build docker container again?

**Comment by jimmyyem** [comment]
> ```ini
> DB_HOST=mysql
> ```

I got a question, why `DB_HOST` must be `mysql`? In other environments this may be `localhost`,  `127.0.0.1` or some other IP addresses.

**Comment by thiagopetherson** [comment]
> > ```ini
> > DB_HOST=mysql
> > ```
> 
> I got a question, why `DB_HOST` must be `mysql`? In other environments this may be `localhost`, `127.0.0.1` or some other IP addresses.

It's the name of your mysql service in the docker-compose file

**Comment by murilolivorato** [comment]
it worked for me -

```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=database_name
DB_USERNAME=root
DB_PASSWORD=secret

```
