### ISSUE TITLE
Workspace on PHP 7.0 PHP Warning:  Module 'soap' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by markhilton** [laradock/laradock#871]
When build with SOAP extension the workspace CLI constantly throws: 

PHP Warning:  Module 'soap' already loaded in Unknown on line 0

**Comment by mikeerickson** [comment]
@markhilton Would you mind supplying your .env file?  I just rested with the default .env file (from laradock repo) and all is working correctly.

**Comment by markhilton** [comment]
PHP_VERSION=70
PHP_INTERPRETER=php-fpm

### WORKSPACE Container
WORKSPACE_INSTALL_XDEBUG=false
WORKSPACE_INSTALL_SOAP=true
WORKSPACE_INSTALL_MONGO=false
WORKSPACE_INSTALL_NODE=true
WORKSPACE_INSTALL_YARN=true
WORKSPACE_INSTALL_DRUSH=false
WORKSPACE_INSTALL_AEROSPIKE_EXTENSION=false
WORKSPACE_INSTALL_INSTALL_V8JS_EXTENSION=false
WORKSPACE_COMPOSER_GLOBAL_INSTALL=false
WORKSPACE_INSTALL_WORKSPACE_SSH=false
WORKSPACE_INSTALL_LARAVEL_ENVOY=false
WORKSPACE_INSTALL_DEPLOYER=false
WORKSPACE_INSTALL_LINUXBREW=false
WORKSPACE_INSTALL_MC=false
WORKSPACE_PUID=1000
WORKSPACE_PGID=1000
WORKSPACE_NODE_VERSION=stable
WORKSPACE_YARN_VERSION=latest
WORKSPACE_TIMEZONE=UTC
WORKSPACE_SSH_PORT=2222

**Comment by markhilton** [comment]
I just downloaded latest version from laradock and this bug appears to be fixed already. I do not get the warning anymore.

**Comment by mikeerickson** [comment]
@markhilton great, glad to hear.  I am going to close this issue.
