### ISSUE TITLE
Failed to build workspace

### ISSUE THREAD

**Issue by markhilton** [laradock/laradock#872]
Building workspace
Step 1/106 : FROM laradock/workspace:1.8-70
ERROR: Service 'workspace' failed to build: manifest for laradock/workspace:1.8-70 not found

**Comment by maurosbu** [comment]
Step 1/102 : FROM laradock/workspace:1.8-56
ERROR: Service 'workspace' failed to build: manifest for laradock/workspace:1.8-56 not found

Step 1/106 : FROM laradock/workspace:1.8-70
ERROR: Service 'workspace' failed to build: manifest for laradock/workspace:1.8-70 not found

It only works with php 7.1 (PHP_VERSION=71)

**Comment by winfried-van-loon** [comment]
My bad, seems there [wasn't a 1.8 tag yet]() for the versioned fixed in #860. They're added, now building and should soon be usable.

**Comment by winfried-van-loon** [comment]
Ok, this should be fixed now!
