### ISSUE TITLE
Experience with Amazon ECS CLI

### ISSUE THREAD

**Issue by ejblom** [laradock/laradock#875]
Hi,

I am interested in deploying a laravel app to AWS using Laradock. Does anyone have experience with the Aamzon docker-compose alternative : http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html
or any other systems to employ docker for Laravel on AWS.

I was looking for an easy solution for laravel on AWS and stumbled on Forge and similar approaches but not many people trying to run it directly on the container service of Amazon.

Anyway, it seems like trying out the one year free tier will suffice. Was thinking to use the native Amazon SQS and in addition the free database service RDS as well. The only thing one would have to pay for are the workers that perform the calculations.

Best 

EJ

**Comment by shahzeb1** [comment]
Yes, so instead of pushing your Docker containers to Dockerhub, use [EC2 Container Registry](https://aws.amazon.com/ecr/) to compile your container and push it to ECR.

Here's a [helpful YouTube video](https://www.youtube.com/watch?v=kzC4RlSxYno).
