### ISSUE TITLE
ERROR happen when build, but Travis-CI still PASSED

### ISSUE THREAD

**Issue by bestlong** [laradock/laradock#876]
Review build log at https://travis-ci.org/laradock/laradock/builds/227215247

PHP_VERSION=56
> ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_V8JS_EXTENSION} = true ]; then     add-apt-repository -y ppa:pinepain/libv8-5.4     && apt-get update     && apt-get install -y php-dev php-pear libv8-5.4     && pecl install v8js     && echo "extension=v8js.so" >> /etc/php/5.6/cli/php.ini ;fi' returned a non-zero code: 1

PHP_VERSION=70
> ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_V8JS_EXTENSION} = true ]; then     add-apt-repository -y ppa:pinepain/libv8-5.4     && apt-get update     && apt-get install -y php-dev php-pear libv8-5.4     && pecl install v8js     && echo "extension=v8js.so" >> /etc/php/7.0/cli/php.ini ;fi' returned a non-zero code: 1

PHP_VERSION=71
> ERROR: Service 'workspace' failed to build: One or more build-args [YARN_VERSION INSTALL_DEPLOYER INSTALL_MC INSTALL_LARAVEL_ENVOY INSTALL_SOAP INSTALL_LINUXBREW INSTALL_V8JS_EXTENSION] were not consumed, failing build.

**Comment by bestlong** [comment]
Ref: https://github.com/travis-ci/travis-ci/issues/1066

**Comment by winfried-van-loon** [comment]
Is this issue related to #809?

**Comment by bestlong** [comment]
@winfried-van-loon No, Travic CI is run build test for laradock/laradock.
I found ERROR in build log, but Travic CI aways report success, is not right.

you can check build log for PHP56
https://travis-ci.org/laradock/laradock/jobs/227215248

In my PR #877 build test for PHP56, TravisCI get failed caused by build ERROR, Is the correct result.
https://travis-ci.org/laradock/laradock/jobs/227364183
