### ISSUE TITLE
Cleanup xDebug documentation

### ISSUE THREAD

**Issue by winfried-van-loon** [laradock/laradock#892]
Currently, there is a lot of documentation written on getting xDebug to work. Also, there is a guide, there are screenshots, there is a php-fpm CLI script and it's built for both the php-fpm and workspace container. Configuring xDebug is far from easy to understand at the moment, which is discussed in #393 and #733. Also, it may differ when using different operating systems.

Would like to see outdated, wrong and confusing information removed from the docs and have a single, clearly written tutorial on how to enable xDebug.

**Comment by ko22009** [comment]
Solution: #893

**Comment by winfried-van-loon** [comment]
This isn't a simple task to completely research and write proper documentation for. I don't have the time to research this one for now, I'll unassign it for now. Feel free to pick it up if anyone has the time. I'll drop a comment here when I can find the time again.

**Comment by mikeerickson** [comment]
@winfried-van-loon I am willing to take on this task, but don't want to waste time if some work has already been done.  If you (or anybody for that matter) have produced a working solution, please feel free to share with me.  I will create a clean organized version accordingly.

**Comment by xsu1991** [comment]
@winfried-van-loon  There are follow step to ensure xdebug work well, 
1. Check you .env file
PHP_FPM_INSTALL_XDEBUG=true  
DOCKER_HOST_IP=10.0.75.1
PHP_IDE_CONFIG=serverName=laradock

`laradock` is your server_name, and must set same in phpstorm, 
Setting > Languages & Frameworks > PHP > Servers
press "+" to add one 
Name -> laradock            make sure same with `PHP_IDE_CONFIG=serverName=laradock`
Host -> localhost   Port->80
Check `Use path mappings`
File/Directory             Absolution path on server
D:\opt\www\public     /var/www/public

2. Check you xdebug.ini
laradock
/php-fpm/xdebug.ini
```
xdebug.remote_enable=1

xdebug.remote_port=9000
xdebug.remote_host

=dockerhost
xdebug.idekey=PHPSTORM
```
xdebug.remote_enable must be set  to 1
3.rebuild your images
```shell
docker-compose build php-fpm 
```
4. try xdebug
```
docker-compose up php-fpm nginx
```
Open phpstorm and create new file `index.php` to `www` dir
such as 
```
$a = 'hello ';
$b = 'world';

echo $a . $b;
```
make break

point to line `$b = 'world';` and set phpstorm to listen debug connection

**Comment by winfried-van-loon** [comment]
Thank you! I'll give it a try soon and add it to the docs if it works

**Comment by xsu1991** [comment]
@winfried-van-loon 
maybe you should visit the url like this `http://localhost/index.php?XDEBUG_SESSION_START=1`, add arg `XDEBUG_SESSION_START`
or add `xdebug.remote_autostart=1` to xdebug.ini

**Comment by mikeerickson** [comment]
@winfried-van-loon I have started on verbose documentation on this very subject.  If you want to take it, that is fine by me, no sense in doubling the effort.

**Comment by biwerr** [comment]
Environment: Windows 10
Docker: Version 18.03.0-ce-win59 (16762) Linux Containers

I have to access the Server via IP 10.0.75.2 to get x_debug working in PHP Storm

If you add `xdebug.remote_connect_back = 1 `to xdebug.ini `xdebug.remote_host` will be ignored (See [Doc](https://xdebug.org/docs/all_settings#remote_connect_back) )
