### ISSUE TITLE
Not enable debug in workspace

### ISSUE THREAD

**Issue by ko22009** [laradock/laradock#893]
The latest version. Windows Hyper-V
Not correct installation in workspace container. INSTALL_XDEBUG is true, but commented in
/etc/php/7.1/cli/conf.d/xdebug-20.ini
zend_extension=xdebug
/etc/php/7.1/cli/conf.d/xdebug.ini doesn't have it, it our file, is located in installation.

**Comment by bestlong** [comment]
Need more info, Please run following two command
```
git rev-parse HEAD
```
```
diff .env env-example
```

**Comment by ko22009** [comment]
8c8
< APPLICATION=../advService/
---
> APPLICATION=../
32c32
< WORKSPACE_INSTALL_XDEBUG=true
---
> WORKSPACE_INSTALL_XDEBUG=false
41c41
< WORKSPACE_INSTALL_WORKSPACE_SSH=true
---
> WORKSPACE_INSTALL_WORKSPACE_SSH=false
50c50
< WORKSPACE_TIMEZONE=Asia/Yekaterinburg
---
> WORKSPACE_TIMEZONE=UTC
55c55
< PHP_FPM_INSTALL_XDEBUG=true
---
> PHP_FPM_INSTALL_XDEBUG=false
231c231,232
< DOCKER_HOST_IP=192.168.0.104
---
> DOCKER_HOST_IP=10.0.75.1
> 
235c236
< PHP_IDE_CONFIG=serverName=172.21.0.4
---
> PHP_IDE_CONFIG=serverName=laradock

**Comment by bestlong** [comment]
Hi @ko22009 
if you change .env, you need to run `docker-compoe build --no-cache workspace` to build new image.

**Comment by ko22009** [comment]
I know, I do it. @bestlong

**Comment by bestlong** [comment]
It seems to be a bug:

```
~/Sites/laradock (master *)$ git rev-parse HEAD
aa5e8e666683a67a3946b577b2f9293ddf127ced
~/Sites/laradock (master *)$ diff .env env-example
32c32
< WORKSPACE_INSTALL_XDEBUG=true
---
> WORKSPACE_INSTALL_XDEBUG=false
```

```
root@0d7695410378:/var/www# ls /etc/php/7.1/mods-available/
bcmath.ini    dom.ini       gd.ini        json.ini       msgpack.ini  pdo.ini         pgsql.ini     shmop.ini      sysvmsg.ini    wddx.ini       xmlwriter.ini
calendar.ini  exif.ini      gettext.ini   mbstring.ini   mysqli.ini   pdo_mysql.ini   phar.ini      simplexml.ini  sysvsem.ini    xdebug.ini     xsl.ini
ctype.ini     fileinfo.ini  iconv.ini     mcrypt.ini     mysqlnd.ini  pdo_pgsql.ini   posix.ini     sockets.ini    sysvshm.ini    xml.ini        zip.ini
curl.ini      ftp.ini       igbinary.ini  memcached.ini  opcache.ini  pdo_sqlite.ini  readline.ini  sqlite3.ini    tokenizer.ini  xmlreader.ini
root@0d7695410378:/var/www# ls /etc/php/7.1/cli/conf.d/
10-mysqlnd.ini  20-calendar.ini  20-fileinfo.ini  20-igbinary.ini  20-mysqli.ini      20-phar.ini       20-sockets.ini  20-tokenizer.ini  20-xsl.ini
10-opcache.ini  20-ctype.ini     20-ftp.ini       20-json.ini      20-pdo_mysql.ini   20-posix.ini      20-sqlite3.ini  20-wddx.ini       20-zip.ini
10-pdo.ini      20-curl.ini      20-gd.ini        20-mbstring.ini  20-pdo_pgsql.ini   20-readline.ini   20-sysvmsg.ini  20-xdebug.ini     25-memcached.ini
15-xml.ini      20-dom.ini       20-gettext.ini   20-mcrypt.ini    20-pdo_sqlite.ini  20-shmop.ini      20-sysvsem.ini  20-xmlreader.ini  xdebug.ini
20-bcmath.ini   20-exif.ini      20-iconv.ini     20-msgpack.ini   20-pgsql.ini       20-simplexml.ini  20-sysvshm.ini  20-xmlwriter.ini
```
```
root@0d7695410378:/var/www# cat /etc/php/7.1/mods-available/xdebug.ini
zend_extension=xdebug.so
```
```
root@0d7695410378:/var/www# cat /etc/php/7.1/cli/conf.d/xdebug.ini
; NOTE: The actual debug.so extention is NOT SET HERE but rather (/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini)

xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.remote_connect_back=0
xdebug.cli_color=0
xdebug.profiler_enable=0
xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.remote_port=9000
xdebug.remote_host=dockerhost
xdebug.idekey=PHPSTORM
```
```
root@0d7695410378:/var/www# cat /etc/php/7.1/cli/conf.d/20-xdebug.ini
;zend_extension=xdebug.so
```

**Comment by ko22009** [comment]
@bestlong Yes, the same!!!

**Comment by ko22009** [comment]
DockerFile xdebug:
#####################################
# xDebug:
#####################################

ARG INSTALL_XDEBUG=false
RUN if [ ${INSTALL_XDEBUG} = true ]; then \
    # Load the xdebug extension only with phpunit commands
    apt-get update && \
    apt-get install -y --force-yes php-xdebug && \
    sed -i 's/^/;/g' /etc/php/7.1/cli/conf.d/20-xdebug.ini && \
    echo "alias phpunit='php -dzend_extension=xdebug.so /var/www/vendor/bin/phpunit'" >> ~/.bashrc \
;fi
# ADD for REMOTE debugging
COPY ./xdebug.ini /etc/php/7.1/cli/conf.d/xdebug.ini

**Comment by ko22009** [comment]
I found solution for phpunit debug,
[solution](http://i.piccy.info/i9/be98041abd16bc8f8fed5d25f945df26/1493964418/43364/1142960/Bezymiannyi_800.jpg)

**Comment by ko22009** [comment]
I decided the problem!
