### ISSUE TITLE
What is workflow debug in docker?

### ISSUE THREAD

**Issue by ko22009** [laradock/laradock#894]
Help!

Who can describe how right debug docker app in phpstorm?
I have some trouble. I try debug and only working way(listennig to server)
![Remote PHP](http://i.piccy.info/i9/6a895d55d5bcbb382097cbdefa874642/1493903314/18636/1142960/Bezymiannyi_500.jpg)
Line of Debugger Extension I write myself. With out it, PHP executable not have Debugger. (How I know, IDE automatically attach debugger when you debug app).
![Remote Server](http://i.piccy.info/i9/458185e7c43cb50a4577a9319c0de8ea/1493903647/18706/1142960/Bezymiannyi2_500.jpg)
And also I set Mapping by offical instruction.

![PHP Server](http://i.piccy.info/i9/e7eec62f022907f40e076d098751f0d2/1493903815/15746/1142960/Bezymiannyi3_500.jpg)
When I listenning server, IDE automatically create server 172.21.0.4. Port: 22, not 80 (by guide!)

DBGp Proxy is not set.

Debug is not working while I uncomment zend_extension=xdebug in /etc/php/7.1/cli/conf.d/xdebug-20.ini by workspace container. For web I use bookmarklet, but a few time I see result in debug and browser draw full page.

I should listening server that can catch debug mode. When I run debug mode, I should error, that xdebug is activated yet. When I use phpUnit, I also listening and after run it. 
It looks like crutches.

**Comment by winfried-van-loon** [comment]
This seems to be a duplicate to #892, if I'm interpreting this correctly.

**Comment by ko22009** [comment]
@winfried-van-loon yes, but I show some solution, but it's not perfect.

**Comment by ko22009** [comment]
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -qy install python-pip
RUN apt-get -qy autoremove && DEBIAN_FRONTEND=noninteractive apt-get -qy clean
RUN pip2 install --upgrade pip
RUN pip2 install komodo-python-dbgp

CMD pydbgpproxy -d 127.0.0.1:9000 -i 0.0.0.0:9001

I add to workspace/Dockerfile-71, and also open port 9001:9001 in workspace in root yml.
Phpstorm success add key dbpg server, but doesn't debug, why?
I do it: https://confluence.jetbrains.com/display/PhpStorm/Multi-user+debugging+in+PhpStorm+with+Xdebug+and+DBGp+proxy

**Comment by ko22009** [comment]
#893
