### ISSUE TITLE
Service workspace failed to build 

### ISSUE THREAD

**Issue by mrignacio1231** [laradock/laradock#895]
### Info:
- Docker version (`$ docker --version`): 1.12.6
- Laradock commit (`$ git rev-parse HEAD`): aa5e8e666683a67a3946b577b2f9293ddf127ced
- System (`place x between the [ ]`):
	- [ ] Mac
	- [ ] PC
	- [x] Linux
	- Info:

### Issue:
I have this problem.

ERROR: Service 'workspace' failed to build: One or more build-args [INSTALL_MSSQL] were not consumed, failing build.

**Comment by bestlong** [comment]
Hi @mrignacio1231 
Please upgrade docker version > 1.13
https://github.com/moby/moby/pull/27412

**Comment by mrignacio1231** [comment]
Hi @bestlong How do i do that?

**Comment by bestlong** [comment]
@mrignacio1231 Your OS version is ?

**Comment by mrignacio1231** [comment]
My OS 
```
NAME="elementary OS"
VERSION="0.4 Loki"
ID="elementary"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 0.4 Loki"
VERSION_ID="0.4"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://bugs.launchpad.net/elementary/+filebug"
VERSION_CODENAME=loki
UBUNTU_CODENAME=loki
```

Docker version
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```

**Comment by bestlong** [comment]
.env PHP_VERSION is ?

**Comment by mrignacio1231** [comment]
It's 7.1

**Comment by mrignacio1231** [comment]
The problem is in workspace/Dockerfile-71 and php-fpm/Dorckerfile-71 files. They have not mssql installation like as Dockerfile-70,

**Comment by bestlong** [comment]
If you don't need MSSQL,

you can edit workspace/Dockerfils-71 add temporary code befor "Final Touch" section like:

```
#####################################
# MSSQL (Build pass for Old Docker version)
#####################################
ARG INSTALL_MSSQL=false
ENV INSTALL_MSSQL ${INSTALL_MSSQL}
RUN if [ ${INSTALL_MSSQL} = true ]; then \
    echo 'Just consume INSTALL_MSSQL arg' \
;fi

#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#
```

**Comment by mrignacio1231** [comment]
Yes, i did that and work
