### ISSUE TITLE
Mysql container can't start 

### ISSUE THREAD

**Issue by chgalvez** [laradock/laradock#899]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 15d7cd1d35d05dadbbe5b1a440de0f7e38059733
- System info (Mac, PC, Linux): Windows 10 Enterprise

Seems some type of writing permissions problem or something like that. On mariadb happens somthing similar.
mysql database container doesnt start and gives errors
_____

##### How might we be able to reproduce the error?
c:\Proyectos\atsa\laradock>docker-compose up mysql
Starting laradock_mysql_1
Attaching to laradock_mysql_1
mysql_1               | Initializing database
mysql_1               | 2017-05-05T14:14:15.181404Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1               | 2017-05-05T14:14:15.181460Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql_1               | 2017-05-05T14:14:15.186028Z 0 [Warning] InnoDB: Unable to open "./ib_logfile0" to check native AIO read support.
mysql_1               | 2017-05-05T14:14:15.186091Z 0 [Warning] InnoDB: Linux Native AIO disabled.
mysql_1               | 2017-05-05T14:14:15.207782Z 0 [ERROR] InnoDB: Can't create file './ibdata1' when --innodb-read-only is set
mysql_1               | 2017-05-05T14:14:15.207838Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mysql_1               | 2017-05-05T14:14:15.508357Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
mysql_1               | 2017-05-05T14:14:15.508384Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mysql_1               | 2017-05-05T14:14:15.508389Z 0 [ERROR] Failed to initialize plugins.
mysql_1               | 2017-05-05T14:14:15.508392Z 0 [ERROR] Aborting
mysql_1               |
laradock_mysql_1 exited with code 1
_____

**Comment by Erchoc** [comment]
> I hava the same problem with you. form yesterday, still no answer

**Comment by Erchoc** [comment]
>  D:\OneDrive\LaraDock\laradock>docker logs ed2
Initializing database
2017-05-05T14:43:08.180539Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-05-05T14:43:08.180592Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
2017-05-05T14:43:08.221195Z 0 [Warning] InnoDB: Retry attempts for writing partial data failed.
2017-05-05T14:43:08.221309Z 0 [ERROR] InnoDB: Write to file ./ibdata1failed at offset 0, 1048576 bytes should have been written, only 0 were written. Operating system error number 28. Check that your OS and file system support files of this size. Check also that the disk is not full or a disk quota exceeded.
2017-05-05T14:43:08.221362Z 0 [ERROR] InnoDB: Error number 28 means 'No space left on device'
2017-05-05T14:43:08.221395Z 0 [ERROR] InnoDB: Could not set the file size of './ibdata1'. Probably out of disk space
2017-05-05T14:43:08.221730Z 0 [ERROR] InnoDB: InnoDB Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
2017-05-05T14:43:08.822761Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
2017-05-05T14:43:08.822803Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2017-05-05T14:43:08.822815Z 0 [ERROR] Failed to initialize plugins.
2017-05-05T14:43:08.822820Z 0 [ERROR] Aborting

**Comment by Erchoc** [comment]
@Mahmoudz  we need you, people's friend.

**Comment by chgalvez** [comment]
Finally it seems to be a file permissions problem. I just edit DATA_SAVE_PATH .env variable to my User directory, to have full access (anyway I specifically  give it Full Control to All group, just in case) and voila

In my case editing .env to

DATA_SAVE_PATH=c:\Users\chgalvez\temp\

and giving that directory full control to All. Thats all.

I figured it out just browsing docker-compose.yml to mysql section

### MySQL Container #########################################

    mysql:
      .
      .
      .
      volumes:
        **- ${DATA_SAVE_PATH}/mysql:/var/lib/mysql**

**Comment by Erchoc** [comment]
but I change DATA_SAVE_PATH , still  isn't work.

mysql_1               | Initializing database
mysql_1               | 2017-05-06T03:58:24.165962Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1               | 2017-05-06T03:58:24.166015Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql_1               | 2017-05-06T03:58:24.246209Z 0 [Warning] InnoDB: New log files created, LSN=45790
mysql_1               | 2017-05-06T03:58:24.263888Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
mysql_1               | 2017-05-06T03:58:24.317699Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 409fe934-3210-11e7-84bc-0242ac170002.
mysql_1               | 2017-05-06T03:58:24.318763Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
mysql_1               | 2017-05-06T03:58:24.321642Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
mysql_1               | 2017-05-06T03:58:24.558509Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_1               | 2017-05-06T03:58:24.558632Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1               | 2017-05-06T03:58:24.558699Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1               | 2017-05-06T03:58:24.558764Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1               | 2017-05-06T03:58:24.559431Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1               | Database initialized
mysql_1               | Initializing certificates
mysql_1               | Generating a 2048 bit RSA private key

**Comment by chgalvez** [comment]
Are you sure? Apparently there are no error in that sequence ... Execute docker ps to know if MySQL container is running or not

**Comment by Erchoc** [comment]
the mysql container still start failed. I don't know the how to do

**Comment by Erchoc** [comment]
oh thanks, just I forgot use `dockercomposer up -d mysql` then exit.我真差劲

**Comment by bestlong** [comment]
@Erchoc 如果你有改變過 .env 設定，都要重新 build image

或 啟動時加參數 --build
```
docker-compose up -d --build mysql
```

如果你不在意 mysql 資料會在  container 刪除時一同消失
可以先編輯 docer-compose.yml 的 mysql 段落將 volumes 設定改為註解
```
    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #volumes:
      #  - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
```
這樣 mysql 就不會使用到 Host OS 的檔案系統（以你的環境是 Win10 來說）
應該可以先繞過此一困擾

**Comment by khaninejad** [comment]
I changed `docker-compose.yml` volume section and gave mysql volumes new name like:
volumes:
```
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql_new
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
```

then start docker dontainer and everything works fine. 
`docker-compose up -d --build mysql`
