### ISSUE TITLE
Illegal instruction: 4 error when running docker-compose up -d on MAC OSX

### ISSUE THREAD

**Issue by neilyoung2013** [LaraDock/laradock#9]
Laradock looks great and looks like something we would use to deploy our Laravel projects using Docker however I get an error when running the project on MAC OSX El Capitan.

I get the following error when trying to bring up the image: 

Illegal instruction: 4

Is this because the project was written for an older version of MAC OSX?

**Comment by Mahmoudz** [comment]
Well I don't think the MAC version cause such error, however can you provide us with more details such as the last commands you run some more details on the error?

**Comment by Mahmoudz** [comment]
That should be solved with the latest LaraDock release.

**Comment by neilyoung2013** [comment]
Thank you Mahmoud!
