### ISSUE TITLE
Gulp is not found

### ISSUE THREAD

**Issue by dantecoding** [LaraDock/laradock#90]
http://joxi.ru/Vm67yVySxY9Z72

**Comment by Mahmoudz** [comment]
@dantecoding that's because gulp is installed globally and needs to be linked locally to work. I will include that by default very soon. Meanwhile try typing this command from inside the workspace container `npm link gulp` and then play with gulp. Thanks

**Comment by dantecoding** [comment]
Thanks.

**Comment by Mahmoudz** [comment]
If you clone the latest release (v2.3.6) that I just published now, it should also be fixed. 

you're welcome :)
