### ISSUE TITLE
About MySQL database when I have mutilsites

### ISSUE THREAD

**Issue by Erchoc** [laradock/laradock#913]
<pre>
D:\OneDrive>docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
</pre>

----------------

About MySQL database when I have mutilsites, the mysql info in `.env` just one database . Now I hava two web sites.

**Comment by bestlong** [comment]
Hi @Erchoc You can create new mysql database by other tool, like adminer or phpmyadmin.

**Comment by Erchoc** [comment]
@bestlong but I couldn't use laradock do this ??

**Comment by bestlong** [comment]
No, It can't. Just now i check Dockerfile, this feature not yet implemented.

**Comment by winfried-van-loon** [comment]
Issues #773 and #616 are about this subject as well.

**Comment by Erchoc** [comment]
@winfried-van-loon thinks very much

**Comment by jhkueh** [comment]
Hi @bestlong, how do you use multiple database with this for my ${MYSQL_USER} (_homestead_, for example)? My _homestead_ can only access one DB specified at MYSQL_DATABASE in the docker-compse.yml file. But my _root_ user can access all the other DBs.

**Comment by bestlong** [comment]
Hi @jhkueh , your comment let me know i added solution has permission bug. i will fix it.

**Comment by bestlong** [comment]
@jhkueh your issue new fix PR is merged, try again please.

**Comment by jhkueh** [comment]
Thanks for that @bestlong! It's working now :D

However, I just found out that you don't need to include `FLUSH PRIVILEGES;` at the end of the `createdb.sql.example` file. According to the [docs ](https://dev.mysql.com/doc/refman/5.7/en/privilege-changes.html)& [here](https://dbahire.com/stop-using-flush-privileges/):

> When mysqld starts, it reads all grant table contents into memory. The in-memory tables become effective for access control at that point.
> 
> If you modify the grant tables indirectly using account-management statements such as `GRANT`, `REVOKE`, `SET PASSWORD`, or `RENAME USER`, the server notices these changes and loads the grant tables into memory again immediately.
