### ISSUE TITLE
cant install php-extension   successfully

### ISSUE THREAD

**Issue by stevesgit** [laradock/laradock#914]
### Info:
- Docker version (`$ docker --version`): Version 17.03.0-ce-mac2 (15654)
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): mac
- System info disto/version: mac os 10.12.4 (16E195)

### Issue:
i cant install php extension , Is the method of my operation wrong?
first i modify dockerfile-70 in php-fpm.the content : 
`
ARG INSTALL_SWOOLE=true
RUN if [ ${INSTALL_SWOOLE} = false ]; then \
    # Install the swoole extension
    pecl install swoole && \
    docker-php-ext-enable swoole \
;fi
`
and then, i rebuild php-fpm.install successfully, but when i enter php-fpm container, use command php -m ,i cant find swoole module.
also ,i change the .env file ,modify other agrs like ` PHP_FPM_INSTALL_MEMCACHED=true`,
install successfully，also cant find memcached  module , i want to change php.ini file ,add extension ,but i dont konw where it is.

_____

**Comment by bestlong** [comment]
Hi @stevesgit you can set .env file PHP_FPM_INSTALL_SWOOLE=true

**Comment by evantolorio** [comment]
Hi @stevesgit.

I think your code should be `RUN if [ ${INSTALL_SWOOLE} = true ];` 
rather than `RUN if [ ${INSTALL_SWOOLE} = false ];` to enter the block statement of installing swoole.

**Comment by stevesgit** [comment]
thanks all.I has solved this problem

**Comment by TanvirAlam** [comment]
@stevesgit How did you solve the issue, I am having same issue not with SWOOLE but with TRADER
