### ISSUE TITLE
exec-ing latest workspace shows errors cause by aliases.sh

### ISSUE THREAD

**Issue by a-h-abid** [laradock/laradock#915]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce
- Laradock commit (`$ git rev-parse HEAD`): 5291f0f884b5484a7e9c94e2fd7c19795cbbbb89
- System info (Mac, PC, Linux): PC (Windows)
- System info disto/version: Windows 10

##### What seems to be going wrong?
Showing aliases errors when getting into workspace container using `docker-compose exec workspace bash` on windows command line.

_____

##### What should be happening instead?
Should not show the aliases errors.
_____

##### How might we be able to reproduce the error?
On windows 10:
* docker-compose build workspace
* docker-compose exec workspace bash
_____

### Relevant Code:

```
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: /home/laradock/aliases.sh: line 61: syntax error near unexpected token `$'{\r''
'ash: /home/laradock/aliases.sh: line 61: `function mkd() {
```

**Comment by mikeerickson** [comment]
@a-h-abid Please make sure you have the latest version of laradock, as this issue has been cured long ago.

```bash
$ git pull https://github.com/laradock/laradock
```

**Comment by a-h-abid** [comment]
I pulled the latest laradock and still see issue on my Windows OS. If I modify my Workspace DockerFile according to this [comment](https://github.com/laradock/laradock/issues/563#issuecomment-279414632), then it works properly.

So maybe you guys include on the Workspace Dockerfile? Thou needs to make sure it also works on MacOS / Linux machines.

**Comment by mikeerickson** [comment]
@a-h-abid I will have a look closer at this issue.  But, it only happens on Windows and thus the reason it was fixed long ago (again on windows).
