### ISSUE TITLE
Postgres container fails to launch

### ISSUE THREAD

**Issue by aft3rlife** [laradock/laradock#919]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 0e0dc44a49441fe10010ae757eee81b12cc5cdc8
- System info (Mac, PC, Linux): MacOS
- System info disto/version: 10.12.4

##### What seems to be going wrong?
With a fresh copy of laradock, the postgres container fails to launch.
_____

##### What should be happening instead?
Self-explanatory
_____

##### How might we be able to reproduce the error?
docker-compose up -d postgres
_____

### Relevant Code:
Console output:
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
2017-05-08T16:31:05.846593429Z 
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
2017-05-08T16:31:05.846867875Z 
Data page checksums are disabled.
2017-05-08T16:31:05.846872770Z 
initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".
```

**Comment by FMate** [comment]
I have a same problem. My solution was add to docker-compose.yml file `- PGDATA=/tmp` in postgres container.

Like this:
`### PostgreSQL Container ####################################

    postgres:
      build: ./postgres
      volumes:
        - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PGDATA=/tmp
      networks:
        - backend`

**Comment by rlindner81** [comment]
Can confirm, I had this bug and the suggested addition fixes it

**Comment by yblondeau** [comment]
I had the same issue also and the suggested edit to the `docker-compose.yml` file fixed it.

### Info:
- Docker version (`$ docker --version`):  `17.09.0-ce, build afdb6d4`
- Laradock commit (`$ git rev-parse HEAD`): `9877f0453ef5d1c8f556403804f8f21df2618de6`
- System info (Mac, PC, Linux): Windows
- System info disto/version: 10 Pro

**Comment by dmz9** [comment]
helped     - PGDATA=/tmp

**Comment by mhaagens** [comment]
Setting PGDATA=/tmp worked for me as well!

**Comment by eloyekunle** [comment]
I think it will affect the database persistence since everything is lost on reboot.

**Comment by abhijitgujar86** [comment]
Thanks @FMate but @eloyekunle and @SalahAdDin  is right  the data is not persistent on reboot everything is lost. does any one know better solution.
