### ISSUE TITLE
Got issue after reconfig docker-compose.yml like what i needed

### ISSUE THREAD

**Issue by at-locbm** [LaraDock/laradock#92]
Why i trying to reconfig docker-compose.yml file just have services: php-fpm, application, data, nginx, mysql and workspace (removed: postgres, mariadb, neo4j, redis, memcached, beanstalkd, beanstalkd-console)
  Then i type  `docker-compose up`, i got below issues ? please explain help me, its ok?

>Attaching to laradock_application_1, laradock_data_1, laradock_mysql_1, laradock_workspace_1, laradock_php-fpm_1, laradock_nginx_1
> mysql_1        | Initializing database
> mysql_1        | 2016-06-04T04:01:01.649470Z 0 [Warning] InnoDB: New log files created, LSN=45790
> mysql_1        | 2016-06-04T04:01:02.241479Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
> mysql_1        | 2016-06-04T04:01:02.549254Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: f4242203-2a08-11e6-8a2c-0242ac120002.
> mysql_1        | 2016-06-04T04:01:02.648709Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
> mysql_1        | 2016-06-04T04:01:02.649049Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
> laradock_data_1 exited with code 0
> php-fpm_1      | [04-Jun-2016 04:01:01] NOTICE: fpm is running, pid 1
> laradock_application_1 exited with code 0
> php-fpm_1      | [04-Jun-2016 04:01:01] NOTICE: ready to handle connections
> workspace_1    | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
> workspace_1    | *** Running /etc/rc.local...
> workspace_1    | *** Booting runit daemon...
> workspace_1    | *** Runit started as PID 8
> workspace_1    | Jun  4 04:00:59 eb4e3e51900e syslog-ng[14]: syslog-ng starting up; version='3.5.3'
> mysql_1        | 2016-06-04T04:01:15.032798Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:15.032822Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:15.032848Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.

>mysql_1        | 2016-06-04T04:01:15.032870Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.

> mysql_1        | 2016-06-04T04:01:15.032903Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | Database initialized
> mysql_1        | MySQL init process in progress...
> mysql_1        | 2016-06-04T04:01:22.639948Z 0 [Note] mysqld (mysqld 5.7.12) starting as process 51 ...
> mysql_1        | 2016-06-04T04:01:22.642734Z 0 [Note] InnoDB: PUNCH HOLE support available
> mysql_1        | 2016-06-04T04:01:22.642751Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> mysql_1        | 2016-06-04T04:01:22.642755Z 0 [Note] InnoDB: Uses event mutexes
> mysql_1        | 2016-06-04T04:01:22.642758Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> mysql_1        | 2016-06-04T04:01:22.642762Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
> mysql_1        | 2016-06-04T04:01:22.642769Z 0 [Note] InnoDB: Using Linux native AIO
> mysql_1        | 2016-06-04T04:01:22.642942Z 0 [Note] InnoDB: Number of pools: 1
> mysql_1        | 2016-06-04T04:01:22.643017Z 0 [Note] InnoDB: Using CPU crc32 instructions
> mysql_1        | 2016-06-04T04:01:22.648409Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
> mysql_1        | 2016-06-04T04:01:22.654034Z 0 [Note] InnoDB: Completed initialization of buffer pool
> mysql_1        | 2016-06-04T04:01:22.655509Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
> mysql_1        | 2016-06-04T04:01:22.666869Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
> mysql_1        | 2016-06-04T04:01:22.723813Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> mysql_1        | 2016-06-04T04:01:22.723895Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> mysql_1        | 2016-06-04T04:01:22.887204Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> mysql_1        | 2016-06-04T04:01:22.888228Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
> mysql_1        | 2016-06-04T04:01:22.888241Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
> mysql_1        | 2016-06-04T04:01:22.889097Z 0 [Note] InnoDB: 5.7.12 started; log sequence number 2523255
> mysql_1        | 2016-06-04T04:01:22.889693Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> mysql_1        | 2016-06-04T04:01:22.890256Z 0 [Note] Plugin 'FEDERATED' is disabled.
> mysql_1        | 2016-06-04T04:01:22.892361Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160604  4:01:22
> mysql_1        | 2016-06-04T04:01:22.892717Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
> mysql_1        | 2016-06-04T04:01:22.933179Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:22.933212Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:22.933224Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:22.933230Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:22.934081Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:22.938132Z 0 [Note] Event Scheduler: Loaded 0 events
> mysql_1        | 2016-06-04T04:01:22.938252Z 0 [Note] mysqld: ready for connections.
> mysql_1        | Version: '5.7.12'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
> mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
> mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
> mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
> mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
> mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
> mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
> mysql_1        | 2016-06-04T04:01:29.116547Z 4 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:29.116560Z 4 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:29.116579Z 4 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | mysql: [Warning] Using a password on the command line interface can be insecure.
> mysql_1        | mysql: [Warning] Using a password on the command line interface can be insecure.
> mysql_1        | mysql: [Warning] Using a password on the command line interface can be insecure.
> mysql_1        | mysql: [Warning] Using a password on the command line interface can be insecure.
> mysql_1        | 2016-06-04T04:01:29.133237Z 8 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:29.133261Z 8 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:29.133368Z 8 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 
> mysql_1        | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
> mysql_1        | 
> mysql_1        | 2016-06-04T04:01:29.134198Z 0 [Note] Giving 0 client threads a chance to die gracefully
> mysql_1        | 2016-06-04T04:01:29.134211Z 0 [Note] Shutting down slave threads
> mysql_1        | 2016-06-04T04:01:29.134214Z 0 [Note] Forcefully disconnecting 0 remaining clients
> mysql_1        | 2016-06-04T04:01:29.134217Z 0 [Note] Event Scheduler: Purging the queue. 0 events
> mysql_1        | 2016-06-04T04:01:29.134244Z 0 [Note] Binlog end
> mysql_1        | 2016-06-04T04:01:29.134735Z 0 [Note] Shutting down plugin 'ngram'
> mysql_1        | 2016-06-04T04:01:29.134743Z 0 [Note] Shutting down plugin 'BLACKHOLE'
> mysql_1        | 2016-06-04T04:01:29.134746Z 0 [Note] Shutting down plugin 'partition'
> mysql_1        | 2016-06-04T04:01:29.134749Z 0 [Note] Shutting down plugin 'ARCHIVE'
> mysql_1        | 2016-06-04T04:01:29.134751Z 0 [Note] Shutting down plugin 'MEMORY'
> mysql_1        | 2016-06-04T04:01:29.134756Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
> mysql_1        | 2016-06-04T04:01:29.134768Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
> mysql_1        | 2016-06-04T04:01:29.134785Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
> mysql_1        | 2016-06-04T04:01:29.134794Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
> mysql_1        | 2016-06-04T04:01:29.134802Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
> mysql_1        | 2016-06-04T04:01:29.134810Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
> mysql_1        | 2016-06-04T04:01:29.134819Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
> mysql_1        | 2016-06-04T04:01:29.134828Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
> mysql_1        | 2016-06-04T04:01:29.134837Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
> mysql_1        | 2016-06-04T04:01:29.134846Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
> mysql_1        | 2016-06-04T04:01:29.134854Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
> mysql_1        | 2016-06-04T04:01:29.134862Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
> mysql_1        | 2016-06-04T04:01:29.134870Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
> mysql_1        | 2016-06-04T04:01:29.134879Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
> mysql_1        | 2016-06-04T04:01:29.134887Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
> mysql_1        | 2016-06-04T04:01:29.134894Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
> mysql_1        | 2016-06-04T04:01:29.134901Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
> mysql_1        | 2016-06-04T04:01:29.134908Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
> mysql_1        | 2016-06-04T04:01:29.134916Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
> mysql_1        | 2016-06-04T04:01:29.134923Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
> mysql_1        | 2016-06-04T04:01:29.134940Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
> mysql_1        | 2016-06-04T04:01:29.134943Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
> mysql_1        | 2016-06-04T04:01:29.134945Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
> mysql_1        | 2016-06-04T04:01:29.134948Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
> mysql_1        | 2016-06-04T04:01:29.134955Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
> mysql_1        | 2016-06-04T04:01:29.134962Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
> mysql_1        | 2016-06-04T04:01:29.134970Z 0 [Note] Shutting down plugin 'INNODB_CMP'
> mysql_1        | 2016-06-04T04:01:29.134977Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
> mysql_1        | 2016-06-04T04:01:29.134985Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
> mysql_1        | 2016-06-04T04:01:29.134992Z 0 [Note] Shutting down plugin 'INNODB_TRX'
> mysql_1        | 2016-06-04T04:01:29.135000Z 0 [Note] Shutting down plugin 'InnoDB'
> mysql_1        | 2016-06-04T04:01:29.135052Z 0 [Note] InnoDB: FTS optimize thread exiting.
> mysql_1        | 2016-06-04T04:01:29.135258Z 0 [Note] InnoDB: Starting shutdown...
> mysql_1        | 2016-06-04T04:01:29.235509Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
> mysql_1        | 2016-06-04T04:01:29.235737Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 160604  4:01:29
> mysql_1        | 2016-06-04T04:01:31.577887Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12128666
> mysql_1        | 2016-06-04T04:01:31.579429Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
> mysql_1        | 2016-06-04T04:01:31.579441Z 0 [Note] Shutting down plugin 'MyISAM'
> mysql_1        | 2016-06-04T04:01:31.579448Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
> mysql_1        | 2016-06-04T04:01:31.579452Z 0 [Note] Shutting down plugin 'CSV'
> mysql_1        | 2016-06-04T04:01:31.579455Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
> mysql_1        | 2016-06-04T04:01:31.579476Z 0 [Note] Shutting down plugin 'sha256_password'
> mysql_1        | 2016-06-04T04:01:31.579480Z 0 [Note] Shutting down plugin 'mysql_native_password'
> mysql_1        | 2016-06-04T04:01:31.579589Z 0 [Note] Shutting down plugin 'binlog'
> mysql_1        | 2016-06-04T04:01:31.579969Z 0 [Note] mysqld: Shutdown complete
> mysql_1        | 
> mysql_1        | 
> mysql_1        | MySQL init process done. Ready for start up.
> mysql_1        | 
> mysql_1        | 2016-06-04T04:01:31.879755Z 0 [Note] mysqld (mysqld 5.7.12) starting as process 1 ...
> mysql_1        | 2016-06-04T04:01:31.882396Z 0 [Note] InnoDB: PUNCH HOLE support available
> mysql_1        | 2016-06-04T04:01:31.882431Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> mysql_1        | 2016-06-04T04:01:31.882438Z 0 [Note] InnoDB: Uses event mutexes
> mysql_1        | 2016-06-04T04:01:31.882441Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> mysql_1        | 2016-06-04T04:01:31.882446Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
> mysql_1        | 2016-06-04T04:01:31.882452Z 0 [Note] InnoDB: Using Linux native AIO
> mysql_1        | 2016-06-04T04:01:31.882705Z 0 [Note] InnoDB: Number of pools: 1
> mysql_1        | 2016-06-04T04:01:31.882809Z 0 [Note] InnoDB: Using CPU crc32 instructions
> mysql_1        | 2016-06-04T04:01:31.888370Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
> mysql_1        | 2016-06-04T04:01:31.893991Z 0 [Note] InnoDB: Completed initialization of buffer pool
> mysql_1        | 2016-06-04T04:01:31.895555Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
> mysql_1        | 2016-06-04T04:01:31.906975Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
> mysql_1        | 2016-06-04T04:01:31.975396Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> mysql_1        | 2016-06-04T04:01:31.975488Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> mysql_1        | 2016-06-04T04:01:32.172161Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> mysql_1        | 2016-06-04T04:01:32.172862Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
> mysql_1        | 2016-06-04T04:01:32.172871Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
> mysql_1        | 2016-06-04T04:01:32.173372Z 0 [Note] InnoDB: 5.7.12 started; log sequence number 12128666
> mysql_1        | 2016-06-04T04:01:32.173906Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> mysql_1        | 2016-06-04T04:01:32.174059Z 0 [Note] Plugin 'FEDERATED' is disabled.
> mysql_1        | 2016-06-04T04:01:32.175766Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
> mysql_1        | 2016-06-04T04:01:32.175783Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
> mysql_1        | 2016-06-04T04:01:32.175820Z 0 [Note] IPv6 is available.
> mysql_1        | 2016-06-04T04:01:32.175828Z 0 [Note]   - '::' resolves to '::';
> mysql_1        | 2016-06-04T04:01:32.175850Z 0 [Note] Server socket created on IP: '::'.
> mysql_1        | 2016-06-04T04:01:32.177059Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160604  4:01:32
> mysql_1        | 2016-06-04T04:01:32.217794Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:32.217821Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:32.219483Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> mysql_1        | 2016-06-04T04:01:32.223209Z 0 [Note] Event Scheduler: Loaded 0 events
> mysql_1        | 2016-06-04T04:01:32.223321Z 0 [Note] mysqld: ready for connections.
> mysql_1        | Version: '5.7.12'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
> ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by mattythebatty** [comment]
Could you try `docker-compose down` and then (make sure any data in the DB is safe)  `docker-compose up --build --force-recreate`

**Comment by at-locbm** [comment]
thank you, i tried like you reported however it still get same issue

**Comment by zysoo** [comment]
`docker-compose up -t 100`
try to give it a bit long time for a try.

**Comment by vladdancer** [comment]
Just try to restart a docker
