### ISSUE TITLE
ERROR: No such service: varnish

### ISSUE THREAD

**Issue by moiroca** [laradock/laradock#925]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): ac895209f0cf9f4591f0780a715ec4ada84ed2d7
- System info (Mac, PC, Linux): Mac
- System info disto/version: 

##### What seems to be going wrong?

I'm trying to setup Varnish. When I tried 'docker-compose up varnish

**Comment by bestlong** [comment]
Hi @moiroca varnish service name is proxy or proxy2, you can search docker-compose.yml.

**Comment by moiroca** [comment]
@bestlong Oh, I was just looking at their documentation. Thanks for this one.
