### ISSUE TITLE
Mariadb plugin 'InnoDB' init function returned error.

### ISSUE THREAD

**Issue by SDLyu** [laradock/laradock#93]
When I run command `docker-compose up mariadb`, I got error likes below

```
$ docker-compose up mariadb
Starting laradock_data_1
Starting laradock_mariadb_1
Attaching to laradock_mariadb_1
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] mysqld (mysqld 10.1.14-MariaDB-1~jessie) starting as process 1 ...
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Memory barrier is not used
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Using Linux native AIO
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Warning] InnoDB: Failed to set O_DIRECT on file ./ibdata1: OPEN: Invalid argument, continuing anyway. O_DIRECT is known to result in 'Invalid argument' on Linux on tmpfs, see MySQL Bug#26662.
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1             | InnoDB: No valid checkpoint found.
mariadb_1             | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
mariadb_1             | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
mariadb_1             | InnoDB: If this error appears when you are creating an InnoDB database,
mariadb_1             | InnoDB: the problem may be that during an earlier attempt you managed
mariadb_1             | InnoDB: to create the InnoDB data files, but log file creation failed.
mariadb_1             | InnoDB: If that is the case, please refer to
mariadb_1             | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1             | 2016-06-10 15:39:08 140264666331072 [ERROR] Aborting
```

How to build mariadb correctly? Thank advaned!

**Comment by AminMkh** [comment]
I can confirm I'm having the same issue:

```
mariadb_1             | 2016-06-11  9:46:19 139817969948608 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1             | 2016-06-11  9:46:19 139817969948608 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1             | 2016-06-11  9:46:19 139817969948608 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1             | 2016-06-11  9:46:19 139817969948608 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1             | 2016-06-11  9:46:19 139817969948608 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1             | 2016-06-11  9:46:19 139817969948608 [ERROR] Aborting
```

**Comment by shadowbane** [comment]
I can confirm it too

```
Creating network "laradock_default" with the default driver
Creating laradock_data_1
Creating laradock_mariadb_1
Attaching to laradock_mariadb_1
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] mysqld (mysqld 10.1.14-MariaDB-1~jessie) starting as process 1 ...
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Memory barrier is not used
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Using Linux native AIO
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1             | InnoDB: No valid checkpoint found.
mariadb_1             | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
mariadb_1             | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
mariadb_1             | InnoDB: If this error appears when you are creating an InnoDB database,
mariadb_1             | InnoDB: the problem may be that during an earlier attempt you managed
mariadb_1             | InnoDB: to create the InnoDB data files, but log file creation failed.
mariadb_1             | InnoDB: If that is the case, please refer to
mariadb_1             | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1             | 2016-06-14  4:03:56 140566295365568 [ERROR] Aborting
mariadb_1             | 
laradock_mariadb_1 exited with code 1
```

**Comment by Oook** [comment]
Same here. Dead in the water.

```
2016-06-20 14:29:35 140066604308352 [ERROR] Plugin 'InnoDB' init function returned error.
2016-06-20 14:29:35 140066604308352 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2016-06-20 14:29:35 140066604308352 [Note] Plugin 'FEEDBACK' is disabled.
2016-06-20 14:29:35 140066604308352 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2016-06-20 14:29:35 140066604308352 [ERROR] Unknown/unsupported storage engine: InnoDB
2016-06-20 14:29:35 140066604308352 [ERROR] Aborting
```

**Comment by Oook** [comment]
I thought maybe their default build scripts disable innodb by default. If you ./configure --with-plugin-innodb_plugin instead of using cmake, then make/make install, it will build and install, but attempting to start the server gives the exact same error. I'm going to continue to play with this to see if I can get it to work - is this an actual bug in mariadb?

**Comment by Daveawb** [comment]
The only way I found round this was to backup my `/var/lib/mysql` and `/var/lib/mariadb` directories byh renaming them, then creating them as empty directories. I'm aware this isn't an option for many, if you're still in development and working on seed data this should work for you.

**Comment by Oook** [comment]
I tried that, and it starts and gets past that point, but then it gives about 1800 lines like this:

InnoDB: wrong number of columns in SYS_INDEXES record

And eventually:
2016-06-21  7:59:51 140678803330944 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2016-06-21  7:59:51 140678803330944 [Warning] InnoDB: Cannot open table mysql/servers from the internal data dictionary of InnoDB though the .frm file for the table exists. See http://dev.mysql.com/doc/refman/5.6/en/innodb-troubleshooting.html for how you can resolve the problem.
2016-06-21  7:59:51 140678803330944 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist in engine
2016-06-21  7:59:51 140678803330944 [Note] Server socket created on IP: '::'.
2016-06-21  7:59:51 140678803330944 [ERROR] Fatal error: mysql.user table is damaged or in unsupported 3.20 format.

What is funny is that if I delete all of the files from my data directory, so there is nothing there at all, I get the *exact* same error messages. It is as if it does not recognize my mysql database at all.

Maybe my mysql table version is too new for mariadb to recognize??? It's from a production system running mysql 5.7.11, and it is rock solid. If I drop in Mariadb (you know, it's supposed to be a drop in replacement for mysql, right?) this happens, and I can't even get the server to start.

I'm going to keep trying, but so far, deleting the log files does not work, and using an empty data directory does not work either.

**Comment by Oook** [comment]
As an update, if I run mysql_install_db against an empty data directory, it will create the mysql and performance_schema and test databases, and then the server will start.

At this point I conclude:

1) The version of mariadb I'm using, 10.1.14 is not compatible with the tables from mysql 5.7.11 

AND/OR

2) Mariadb is not quite the "drop in replacement for mysql" as they would like us to believe.

AND/OR

3) There is a step that I'm missing necessary to make this work with existing mysql tables.

At any rate, until I figure out how to get mariadb to work with an existing mysql database, I have no choice but to stay with mysql...

**Comment by Oook** [comment]
PS: This is for a production database, and no I'm not going to export all of my production data, create a new mariadb databse, and import all of my data into it. My tables are huge and this simply is not going to happen. Mariadb will either work with the existing mysql data, or I stay with mysql. Until I figure out what I'm missing or doing wrong, I have no choice but to stay with mysql...

**Comment by zhiyong80** [comment]
I too just experienced the problem that OooK had. After a system reboot, mariadb failed to start, and I got the error message like this:
Fatal error: mysql.user table is damaged or in unsupported 3.20 format.
In my case, the problem was caused by a mysqldump --all-databases from mysql 5.7 and then imported into mariadb 10.1. As stated, there is some difference in mysql.user which caused the problems. Hope this helps someone directed here by google.

**Comment by Mahmoudz** [comment]
I'll close this old issue now, if the error still exist we'll open it back.

**Comment by Lucassith** [comment]
This error still exists:

`mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] mysqld (mysqld 10.1.18-MariaDB-1~jessie) starting as process 1 ...
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Using Linux native AIO
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1             | InnoDB: No valid checkpoint found.
mariadb_1             | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
mariadb_1             | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
mariadb_1             | InnoDB: If this error appears when you are creating an InnoDB database,
mariadb_1             | InnoDB: the problem may be that during an earlier attempt you managed
mariadb_1             | InnoDB: to create the InnoDB data files, but log file creation failed.
mariadb_1             | InnoDB: If that is the case, please refer to
mariadb_1             | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1             | 2016-10-10 17:07:16 140096807745472 [ERROR] Aborting`

**Comment by mroedel** [comment]
same here...

```
2016-10-11 19:28:44 139966758561728 [Note] mysqld (mysqld 10.1.18-MariaDB-1~jessie) starting as process 1 ...
2016-10-11 19:28:44 139966758561728 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: The InnoDB memory heap is disabled
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Compressed tables use zlib 1.2.8
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Using Linux native AIO
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Using SSE crc32 instructions
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Initializing buffer pool, size = 256.0M
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Completed initialization of buffer pool
2016-10-11 19:28:44 139966758561728 [Note] InnoDB: Highest supported file format is Barracuda.
InnoDB: No valid checkpoint found.
InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
InnoDB: If this error appears when you are creating an InnoDB database,
InnoDB: the problem may be that during an earlier attempt you managed
InnoDB: to create the InnoDB data files, but log file creation failed.
InnoDB: If that is the case, please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
2016-10-11 19:28:44 139966758561728 [ERROR] Plugin 'InnoDB' init function returned error.
2016-10-11 19:28:44 139966758561728 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2016-10-11 19:28:44 139966758561728 [Note] Plugin 'FEEDBACK' is disabled.
2016-10-11 19:28:44 139966758561728 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2016-10-11 19:28:44 139966758561728 [ERROR] Unknown/unsupported storage engine: InnoDB
2016-10-11 19:28:44 139966758561728 [ERROR] Aborting
2016-10-11T19:28:44.699407403Z 
```

**Comment by ludk17** [comment]
Error

mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] mysqld (mysqld 10.1.18-MariaDB-1~jessie) starting as process 1 ...
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Using Linux native AIO
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1             | InnoDB: No valid checkpoint found.
mariadb_1             | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
mariadb_1             | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
mariadb_1             | InnoDB: If this error appears when you are creating an InnoDB database,
mariadb_1             | InnoDB: the problem may be that during an earlier attempt you managed
mariadb_1             | InnoDB: to create the InnoDB data files, but log file creation failed.
mariadb_1             | InnoDB: If that is the case, please refer to
mariadb_1             | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1             | 2016-10-26  0:25:11 139965033494464 [ERROR] Aborting
mariadb_1             | 
laradock_mariadb_1 exited with code 1

**Comment by aft3rlife** [comment]
Same error here on a fresh install of Laradock. Happens with both MariaDB and MySQL.

**Comment by riccardoravaro** [comment]
Same error

php_1      | [30-Oct-2016 13:30:25] NOTICE: fpm is running, pid 5
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Note] InnoDB: Initializing buffer pool, size = 1.0G
php_1      | [30-Oct-2016 13:30:25] NOTICE: ready to handle connections
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Note] InnoDB: Completed initialization of buffer pool
pma_1      | 2016-10-30 13:30:25,809 CRIT Supervisor running as root (no user in config file)
pma_1      | 2016-10-30 13:30:25,810 WARN Included extra file "/etc/supervisor.d/nginx.ini" during parsing
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Note] InnoDB: Restoring page 0 of tablespace 0
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Warning] InnoDB: Doublewrite does not have page_no=0 of space: 0
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] InnoDB: space header page consists of zero bytes in data file ./ibdata1
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
pma_1      | 2016-10-30 13:30:25,812 WARN Included extra file "/etc/supervisor.d/php.ini" during parsing
pma_1      | Unlinking stale socket /run/supervisord.sock
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1  | 2016-10-30 13:30:25 140095212170280 [ERROR] Aborting

**Comment by sahithithandra** [comment]
Hi, 

I also have a same error when trying to start Maria 10.1.8 on Ubuntu 14.04 ~trusty.  Did you guys find any solution?
![aria_error](https://cloud.githubusercontent.com/assets/15042896/20017326/77c63d74-a299-11e6-9c2c-47f85d7d889d.PNG)

**Comment by tboztuna** [comment]
I updated mysql version  from 5.6 to 5.7 . The problem is resolved  now.

**Comment by tripper54** [comment]
For the googlers out there, had the same error on startup of the mysql container. Rebuilding the container - ``` docker-compose build mysql ```  - solved it for me.

**Comment by AliveCorpse** [comment]
Cant start MariaDB too.

```mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] mysqld (mysqld 10.1.19-MariaDB-1~jessie) starting as process 1 ...
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Using Linux native AIO
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Using generic crc32 instructions
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1             | InnoDB: No valid checkpoint found.
mariadb_1             | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
mariadb_1             | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
mariadb_1             | InnoDB: If this error appears when you are creating an InnoDB database,
mariadb_1             | InnoDB: the problem may be that during an earlier attempt you managed
mariadb_1             | InnoDB: to create the InnoDB data files, but log file creation failed.
mariadb_1             | InnoDB: If that is the case, please refer to
mariadb_1             | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1             | 2016-11-15 19:50:53 140322466129856 [ERROR] Aborting
mariadb_1             | 
laradock_mariadb_1 exited with code 1```

**Comment by omurphy27** [comment]
I was getting the same issue with a fresh install of laradock. In the docker-compose.yml file I changed the mariadb volumes to the following:

```
volumes:
            - mariadb:/var/lib/mysql
```

And deleted my docker images and containers (_note this will delete ALL your docker containers and images and is probably overkill_) by doing the following:

```
docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -q)
```

Then I reran `docker-compose up mariadb` and now the mariadb container starts and works with no issues.

**Comment by rwforsythe** [comment]
Have the problem described above ("Could not open mysql.plugin table. Some plugins may be not loaded") after installing MariaDB on a fresh centos box. No previous install of mysql. I'm wondering if that is an unusual installation environment and causing the issues I am having...

**Comment by beatwade** [comment]
I meet the issues today, here is my solutions 👍
because I want to reused the databases' data, 
so here is these steps:
1 . stop all the mysql container
2.  rmi the mysql images
3. run up -d again
everyting is ok again

and I found the reason is when mysql image start , it will create or use some files in itself
e.g. /var/log/mysql
/tmp/mysql
/var/run/mysqld

so if a new container setup with these , next time you want to set up a  new container with the same image will meet serials issues with these
![image](https://user-images.githubusercontent.com/6858148/33762865-31f0eae8-dc49-11e7-9e5f-842470e77968.png)

finally I don't know why , /var/run/mysqld folder can't use docker-compose volumes command to reference , if as this, we can't create multiple containers with the same mysql images?
if someone knows , please point out, thanks

**Comment by JohnNiang** [comment]
delete other mysql version lib(/var/lib/mysql)
and reinstall it.

**Comment by anabeto93** [comment]
This is how I finally got it solved.

[Issues with Docker DB images](https://github.com/farmOS/farmOS/issues/55#issuecomment-517837850)

**Comment by huypx-nfq** [comment]
In my case, i crash to mariadb data in ~/.laradock/data/mariadb so solution is remove or rename data folder and restart laradock

Ref: https://devhoi.com/threads/laradock-on-mac-error-unknown-unsupported-storage-engine-innodb.28/

**Comment by Ducmy** [comment]
> The only way I found round this was to backup my `/var/lib/mysql` and `/var/lib/mariadb` directories by renaming them, then creating them as empty directories. I'm aware this isn't an option for many, if you're still in development and working on seed data this should work for you.
> 
> There has been some talk about just removing log files from these directories and thus preserving data though I haven't tried this.
> 
> Log files reportedly removed that fixed this issue:
> 
> ```
> /var/lib/mysqld/ib_logfile0
> /var/lib/mysql/ib_logfile1
> /var/lib/mysql/aria_log_control
> ```

It work for me! Thank you so much!

**Comment by billyromano** [comment]
I had a similar issue with wordpress not connecting to mariadb. For my fix, I didn't realize that I had changed the mariadb version from the original version I started with. The issue was the data was created/saved using an older version of mariadb and changing the mariadb version to something newer caused the issue, so the database needs to be updated to work with the newer version of mariadb. Instead of updating the database, I just reverted back to using the original mariadb version I was using from the beginning.

My original mariadb version I started the project with: docker.io/bitnami/mariadb:10.3-debian-10
Updated version that caused the issue: docker.io/bitnami/mariadb:10.5

Moral of the story, don't update the version unless you need to and then plan to update the database to work with the newer version.
