### ISSUE TITLE
Permission denied docker-compose up

### ISSUE THREAD

**Issue by atiladelcanton** [laradock/laradock#940]
### Info:
- Docker version (`$ docker --version`):  1.12.6
- Laradock commit (`$ git rev-parse HEAD`): c85fd97e0031d29e07249dd5cbf951f78197255f
- System info (Mac, PC, Linux): LINUX
- System info disto/version: Fedora 25

##### What seems to be going wrong?
When I excused the docker-compose up nginx mysql command, it returns me a permission error denied
_____

##### What should be happening instead?
You should rotate the container
_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
 zencompany@localhost  ~/Documentos/projetos/playmu/app/laradock   master  docker-compose up nginx mysql
Recreating laradock_mysql_1
Recreating laradock_applications_1
Recreating laradock_workspace_1
Recreating laradock_php-fpm_1
Recreating laradock_nginx_1
Attaching to laradock_mysql_1, laradock_nginx_1
nginx_1               | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
mysql_1               | chown: cannot read directory '/var/lib/mysql/': Permission denied
nginx_1               | 2017/05/14 00:11:36 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
laradock_mysql_1 exited with code 1
laradock_nginx_1 exited with code 1

```

**Comment by bestlong** [comment]
Hi @atiladelcanton 

By default, nginx container will save log at host os ./logs, and mysql container also save data at host os /tmp/mysql, please check these folders is enabled write permission.

**Comment by atiladelcanton** [comment]
@bestlong 

My machine does not have these folders

**Comment by bestlong** [comment]
@atiladelcanton 

please use this command to up container:
```
docker-compose up -d nginx mysql
```
and check log you can use:
```
// for nginx
docker-compose logs nginx
// for mysql
docker-compose logs mysql
```

then please provide more info use command:
```
ls -l ~/Documentos/projetos/playmu/app | grep laradock
```
i guess your laradock folder, maybe docker no write permission.

**Comment by atiladelcanton** [comment]
I put the laradocke's permission in 777 and the same problem continues.

**Comment by bestlong** [comment]
can you post this command result when container is up:
```
docker inspect laradock_nginx_1
```

**Comment by aft3rlife** [comment]
AFAIK you need to add your user to the docker group on Fedora or run docker-compose with sudo

**Comment by josephinemho** [comment]
Also check if SELinux is set to permissive, and then do `docker-compose up` again. If it's not set to permissive, run `setenforce 0` and that should do it!
