### ISSUE TITLE
PHP-worker : Could not open input file: artisan

### ISSUE THREAD

**Issue by ihd2911** [laradock/laradock#944]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce
- System info (Mac, PC, Linux): Windows 7

##### What seems to be going wrong?
Following is my docker-compose.yml
php-worker:
      build:
        context: ./php-worker
      volumes_from:
        - applications
      depends_on:
        - workspace
      networks:
        - backend
      command: php artisan queue:work

I have added command. When i run php-worker container i am getting error

"Could not open input file: artisan"

**Comment by bestlong** [comment]
Hi @ihd2911 

why you try add command to docker-compose.yml?

please check php-worker/supervisord.conf first, has set laravel-worker section like you need command.

```
command=php /var/www/artisan queue:work --sleep=3 --tries=3 --daemon
```

**Comment by ihd2911** [comment]
My Bad, Thanks, I will test it.
