### ISSUE TITLE
Could not load localhost:8000 after php artisan serve in workspace bash

### ISSUE THREAD

**Issue by joseph-lum** [laradock/laradock#945]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce-mac12 (17661)
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Mac
- System info disto/version: 

### Issue:
I've been trying to create a new Laravel project in Laradock environment, but the closest I got was to enter the workspace bash and do a php artisan serve there. However, the browser could not load anything when localhost:8000 was accessed. How do I view the homepage? It seems like my configuration files are not properly set but try as I might I just could not manage to access it on localhost..

**Comment by RobbeVW** [comment]
I don't think you're supposed to use Artisan to serve Laravel, that's what Docker is for. run `docker-compose up -d nginx mysql` and try to connect to `localhost` (no port). The introduction section of http://laradock.io/introduction/ explains things nicely.
