### ISSUE TITLE
error accour when run the command:$docker-compose up -d nginx mysql redis beanstalkd 

### ISSUE THREAD

**Issue by xushaobo** [laradock/laradock#947]
$docker-compose up -d nginx mysql redis beanstalkd
laradock_redis_1 is up-to-date
Starting laradock_mysql_1 ...
Starting laradock_applications_1 ...
Starting laradock_mysql_1
Starting laradock_mysql_1 ... error

ERROR: for laradock_mysql_1  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1 (ed83e672Starting laradock_applications_1 ... done
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
Starting laradock_nginx_1 ...
Starting laradock_beanstalkd_1 ...
Starting laradock_nginx_1
Starting laradock_nginx_1 ... error

ERROR: for laradock_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (99bc5275Starting laradock_beanstalkd_1 ... error

ERROR: for laradock_beanstalkd_1  Cannot start service beanstalkd: oci runtime error: container with id exists: 6baed0f6b5338b0316b8cc267d95a76efc239986d324930ec2de8bea8a136d3c

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (99bc5275ccf2f6bb10f09353d71fa3b89267e4d618fbe49cffa9ac5eff5db8ae): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for beanstalkd  Cannot start service beanstalkd: oci runtime error: container with id exists: 6baed0f6b5338b0316b8cc267d95a76efc239986d324930ec2de8bea8a136d3c

ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint laradock_mysql_1 (ed83e672d944f8db591d3fd46cedd2748d99c5fc9edc288cce5dff88cc3777ae): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by bestlong** [comment]
0.0.0.0:80
0.0.0.0:3306
bind: address already in use

you host os already run service bind port 80, 3306.
stop related service then run docker-compose up again.

**Comment by xushaobo** [comment]
Thanks first at all, But is there any way can change the port that docker use ? instead of  to change the host's default setting.

**Comment by bestlong** [comment]
yes, you can change mapping port in .env file.

**Comment by xushaobo** [comment]
Yeap, but when I run the command again it shows something up-to-date:
$docker-compose up -d nginx mysql redis beanstalkd
laradock_redis_1 is up-to-date
laradock_mysql_1 is up-to-date
Starting laradock_applications_1 ...
Starting laradock_applications_1 ... done
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
laradock_beanstalkd_1 is up-to-date
laradock_nginx_1 is up-to-date

**Comment by bestlong** [comment]
because containers already up, and you run again

you can
```
// Stop services
docker-compose stop

// Stop and remove containers, networks, images, and volumes
docker-compose down
```

**Comment by xushaobo** [comment]
So, this is right?
but since there is no errors, why when I visit http://localhost, there goes a 404 Not Found nginx.

**Comment by xushaobo** [comment]
Yes,it's okay now .thank you very much.
谢谢兄弟!

**Comment by bestlong** [comment]
need make nginx/sites/your-project.conf (copy from project-1.conf.example), edit server_name and root set.

then also edit host os /etc/hosts add
```
127.0.01  your-project.dev
```
then you can open browser http://your-project

ref: http://laradock.io/getting-started/#installation

**Comment by datphan123** [comment]
jhsvachjasc
