### ISSUE TITLE
error: service "rethinkdb" uses an undefined network "backend"

### ISSUE THREAD

**Issue by xushaobo** [laradock/laradock#948]
$ docker-compose up --build -d nginx mysql
WARNING: Some networks were defined but are not used by any service: static-network
ERROR: Service "rethinkdb" uses an undefined network "backend"

**Comment by bestlong** [comment]
@xushaobo 

Are you changed docker-compose.yml ? Why do you want to do that?

need more info, and post command result, please.
```
git diff docker-compose.yml
```
