### ISSUE TITLE
Need Help with mysql container

### ISSUE THREAD

**Issue by rasparac** [laradock/laradock#950]
Hi guys, I'm new to the laradoc and I need help with mysql/postgres default user.
I want to create user form the .env file in laradock folder, but when I start the mysql container only root user is created and there are no other users.

Here is the .env conf for mysql.

MYSQL_DATABASE=docker
MYSQL_USER=igor2
MYSQL_PASSWORD=secret
MYSQL_PORT=3306

but when I try to login into the mysql shell via **mysql via -uigor -psecret** I get access denied.
How to create default user and database on container boot?

I can see in the [(documentation)](http://laradock.io/documentation/#mysql-root-access) that one more non-root user should be created but there are no other users.

**Comment by bestlong** [comment]
db create user only run one time when init db stage,

by default mysql/postgres data folder at /tmp/mysql /tmp/postgres

if you don't mind delete these data folder, do with container not run.

when container up will check data folder is exist , if not then will run init db and create user use .env set value.

if want to create more user, you can check mysql/docker-entrypoint-initdb.d/createdb.sql.example
copy it to createdb.sql then add sql script by you need.

**Comment by bestlong** [comment]
Hi @rasparac BTW more notice:

in workspace container
```
mysql -h msyql -uigor -psecret
```
on host os
```
mysql -h 127.0.0.1 -uigor -psecret
```

**Comment by rasparac** [comment]
Hi @bestlong but mysql laradock won't create a non-root user.

**Comment by mikeerickson** [comment]
@rasparac what error are you receiving when attempting to create the user.  Can you share exact command and error (copy / paste if you can)

**Comment by rasparac** [comment]
@mikeerickson I don't get any error. everything works just fine but there is no non-root user. i have another issue opened [here](https://github.com/laradock/laradock/issues/952)

**Comment by bestlong** [comment]
@rasparac 

when you first time run
```
// .env file
DATA_SAVE_PATH=/tmp

MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
```
```
// shell command
docker-compose up -d mysql
```
will run init db step, because /tmp/mysql not exists. right now you have one not-root user `default`.

then you change .env file to:
```
MYSQL_DATABASE=docker
MYSQL_USER=igor2
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
```
and run again
```
// shell command
docker-compose up -d mysql
```
you will get `Recreating laradock_mysql_1` info, but this time will not run init db step, because /tmp/mysql is exist. so you change will not effective. right now you still have one not-root user `default`.

these rule is follow mysql parent Dockerfile.

quick solution (after change .env and all mysql data can delete):
```
docker-compose down
rm -rf /tmp/mysql
docker-compose up -d mysql
```

**Comment by connor11528** [comment]
Check out this [stackoverflow answer](https://stackoverflow.com/a/11091462/2031033) on various ways to stop MySQL. For me the one that did the trick was:

```
/usr/local/mysql/bin/mysqladmin -u root -p shutdown
```

**Comment by saeidee** [comment]
Just find the **DATA_PATH_HOST** key inside your **.env** 
`
cd <DATA_PATH_HOST>
`
`
rm -rf mysql
`
