### ISSUE TITLE
MySql won't create non-root user and default database from laradock.env

### ISSUE THREAD

**Issue by rasparac** [laradock/laradock#952]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce
- Laradock commit (`$ git rev-parse HEAD`): c6d412e
- System info (Mac, PC, Linux): Linux
- System info disto/version: 16.04 Trusty

##### What seems to be going wrong?
I followed [this](http://laradock.io/getting-started/) instructions to set laradock on my project, but when I run 
`docker-compose up -d nginx mysql`
 a database from laradock.env was not created.

##### What should be happening instead?
I expected test database to be created with test_user user, but there is only root user after I run docker-compose up.
_____

##### How might we be able to reproduce the error?
run
`docker-compose up -d nginx mysql`
_____

### Relevant Code:

```
MYSQL_DATABASE=test
MYSQL_USER=test_user
MYSQL_PASSWORD=test
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
```
here is the solution when I comment some fields it is working. commented context, build volumes.
`
mysql:

    # build:

     # context: ./mysql
      image: mysql:5.7
       environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # volumes:
        # - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        # - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
`

**Comment by bestlong** [comment]
duplicate #950

if you accept lost mysql data when remove mysql container happened. you only need commented one line:
```
# - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
```
