### ISSUE TITLE
redis error starting laradock

### ISSUE THREAD

**Issue by im-hs** [laradock/laradock#953]
### Info:
- Docker version (`$ docker --version`): 
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux):  Ubuntu 16.04 
- System info disto/version: 

##### What seems to be going wrong?
Laradock application don't start. The site is down. Redis service don't start.

Starting laradock_redis_1
ERROR: mkdir /var/run/docker/libcontainerd/containerd/997c0b5fbdbb586c6312bf4466e34662b676dcc744946254d202adb89e3a0410: file exists

_____

##### What should be happening instead?
The site must be visible and up
_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:
...

The command that I use: 

docker-compose up -d nginx mysql redis beanstalkd

...

**Comment by im-hs** [comment]
Docker version 17.05.0-ce, build 89658be

**Comment by ab-su-rd** [comment]
try executing `docker-compose rm` and rerun `up` command

**Comment by im-hs** [comment]
Excellent! Thank you!
