### ISSUE TITLE
How To Run Crontab In Docker?

### ISSUE THREAD

**Issue by bushibigniu** [laradock/laradock#959]
I want to use crontab in docker,but in docker similiar not to run.so,how should I do.
I use docker-composer version 2.1
linux system is ubuntu
php7.0
can you help me.thanks.

**Comment by CharlieTapSonin** [comment]
Each container should really represent one running executable (So you shouldn't have fpm and cron running in the same container), so what you can do is just create another service in your compose file that is the same as php-fpm but overrides the command option to start cron. Provided you have added to cron package to the fpm image the you can either:

```
command: bash -c "crontab -l | { cat; echo '* * * * * /usr/local/bin/php /var/www/artisan schedule:run >> /dev/null 2>&1'; } | crontab - && cron -f"
```
or if you already have the crontab files copied in then

```
command: bash -c "cron -f"

```

The dash f flag runs it in the foreground as cron usually runs in the background and thus the container would just stop.

**Comment by bushibigniu** [comment]
Can you say something more?

**Comment by codejam1024** [comment]
@bushibigniu 
laradock\php-worker\laravel-worker2.conf
```
[program:laravel-worker2]
process_name=%(program_name)s_%(process_num)02d
command=php -r "sleep (60);" && php /var/www/artisan schedule:run
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
```

And run a command:
> docker-compose up -d php-worker
