### ISSUE TITLE
Switching from 7.0 to 5.6 without machine restart

### ISSUE THREAD

**Issue by berdam** [laradock/laradock#963]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 45bd807ec72c38e3bf3f1659ac4783ab580ed2c0
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.12.4 

### Issue:

PHP Version 7.0.18 is running.

I want to downgrade PHP to 5.6 for another project.

When I change this:

```
### PHP version
# Applies to the Workspace and PHP-FPM containers (Does not apply to HHVM)
# Accepted values: 71 - 70 - 56

PHP_VERSION=70
```

to this

`PHP_VERSION=56`

And do
`$ docker-compose build --no-cache php-fpm`

Nothing happens - PHP Version 7.0.18 is still the same.

However when I restart my Mac and do `docker-compose up` it does change to 5.6.

So what's the trick?

**Comment by vitoo** [comment]
The build command do the image, you have to restart the container next

docker-compose restart php-fpm

**Comment by berdam** [comment]
@vitoo thank you for your answer, but it's still unchanged

**Comment by vitoo** [comment]
So you can try

docker-compose up -d php-fpm

**Comment by berdam** [comment]
That did the magic! Thank you my friend @vitoo!
