### ISSUE TITLE
MySQL container is dropping all tables after a system reboot

### ISSUE THREAD

**Issue by mbemvieira** [laradock/laradock#966]
### Info:
- Docker version (`$ docker --version`): Docker version 17.05.0-ce, build 89658be
- Laradock commit (`$ git rev-parse HEAD`): 3288c206588495941c5880bd20027d0a3dd96b9d
- System info (Mac, PC, Linux): Linux x64
- System info disto/version: Ubuntu 16.04

##### What seems to be going wrong?
The MySQL database container is dropping all tables after rebooting the operating system. On previous versions of Laradock it had never happened before. After updating to the latest version, this issue appeared.
_____

##### What should be happening instead?
The containers should keep all the data.
_____

##### How might we be able to reproduce the error?
Just reboot the OS and the MySQL database will be all erased. Even if I use a `sudo docker-compose down`.

**Comment by maurosbu** [comment]
Databases are lost when stopping container.
I think it is related to:

    DATA_SAVE_PATH=/tmp

It works if I go back to:

    DATA_SAVE_PATH=../data

Commit changing the variable: https://github.com/laradock/laradock/commit/0cf26af724b9611509eebf5dbab9a5340afe12fc

**Comment by mbemvieira** [comment]
Thanks! That solved the problem :)
