### ISSUE TITLE
MYSQL - How to reload the previously created the database?

### ISSUE THREAD

**Issue by at-minhnguyen** [laradock/laradock#969]
### Info:
- Docker version (`$ docker --version`): 1.12.3
- Laradock commit (`$ git rev-parse HEAD`): bf4a5beb0be77eb952a5012c27f7e538f950c274
- System info (Mac, PC, Linux): Mac
- System info disto/version: 10.11.4 (15E65)

### Issue:
I follow the steps as follows:
docker-machine start dev
docker-machine env dev
eval $(docker-machine env dev)
docker-compose up -d

I access to workspace of mysql and create more a new database "db2". I check and db2 is created.

After that, I do as follows:
docker-machine stop dev
docker-machine start dev
docker-machine env dev
eval $(docker-machine env dev)
docker-compose up -d

After start again, I access to workspace of mysql and check exist database "db2" but it's not EXIST.
_____

### Expected behavior:
After start docker-compose again, I want to load the database already create "db2".

I tried to fix it but failed.
Could you help me to fix it?

**Comment by minkbear** [comment]
This may help you. https://github.com/laradock/laradock/issues/966
