### ISSUE TITLE
Fail to start jenkins with no permission in entrypoint?

### ISSUE THREAD

**Issue by NewbMiao** [laradock/laradock#973]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 81053c0868723d7f615906ab5be0273dcde86b81
- System info (Mac, PC, Linux): Mac
- System info disto/version: Darwin newbmiaodeMacBook-Pro.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

### Issue:
RT
When start jenkins use `docker-compose start jenkins` it failed
and i get log using `docker-compose logs jenkins`
```
$ docker-compose logs jenkins
Attaching to laradock_jenkins_1
jenkins_1             | [FATAL tini (6)] exec /usr/local/bin/jenkins.sh failed: Permission denied
```

obviously, it caused by no permission
so i simply change dockerfile like this:
```
# use root to set permission and group of jenkins.sh
USER root
COPY jenkins-support /usr/local/bin/jenkins-support
COPY jenkins.sh /usr/local/bin/jenkins.sh
RUN chown -R ${user} /usr/local/bin/jenkins.sh && chmod +x /usr/local/bin/jenkins.sh
USER ${user}
ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
```
now it seems ok. 

and there is some line comfused me:
```
# Add jenkins to the correct group
# see http://stackoverflow.com/questions/42164653/docker-in-docker-permissions-error
# use "getent group docker | awk -F: '{printf "%d\n", $3}'" command on host to find correct value for gid or simply use 'id'
ARG DOCKER_GID=998
```
does this GID right for every environment?

**UPDATE**:
For mac, there is no docker group default, and i finally use below solution.
[use sudo to run docker in host](http://container-solutions.com/running-docker-in-jenkins-in-docker/)

Or
add `daemon` group for jenkins
>  docker for mac is use daemon group for docker 
>  use echo $(ls -al /var/run/docker.sock  | awk '{print $4}')

**Comment by NewbMiao** [comment]
Why install docker twice?And when i attach in jenkins container by exec,there is no docker command?

there is the inatall section in jenkins dockfile
```
# Add jenkins to the correct group
# see http://stackoverflow.com/questions/42164653/docker-in-docker-permissions-error
# use "getent group docker | awk -F: '{printf "%d\n", $3}'" command on host to find correct value for gid or simply use 'id'
ARG DOCKER_GID=998

RUN groupadd -g ${DOCKER_GID} docker \
  && curl -sSL https://get.docker.com/ | sh \
  && apt-get -q autoremove \
  && apt-get -q clean -y \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin

# Install Docker-in-Docker from git@github.com:jpetazzo/dind.git
# RUN apt-get update -qq && apt-get install -qqy apt-transport-https ca-certificates curl lxc iptables
# Install Docker from Docker Inc. repositories.
RUN apt-get install -y curl && curl -sSL https://get.docker.com/ | sh
RUN usermod -aG docker jenkins
```

**Comment by NewbMiao** [comment]
Try to use docker outside jenkins-docker with `-v \var\run\docker.sock: \var\run\docker.sock`
Cause docker in docker share volume is totaly bad idea!
It cost me half day to figure it out!
see [do-not-use-docker-in-docker-for-ci](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

**Comment by mouyong** [comment]
https://github.com/jenkinsci/docker/issues/493

It solve my problem. 

> cd laradock && chown -R 1000:1000 jenkins/jenkins_home
