### ISSUE TITLE
Public folder not found for caddy

### ISSUE THREAD

**Issue by cre8** [laradock/laradock#976]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce
- Laradock commit (`$ git rev-parse HEAD`): bf4a5beb0be77eb952a5012c27f7e538f950c274
- System info (Mac, PC, Linux): Windows
- System info disto/version: Windows 10

### Issue:
ERROR: for caddy  Cannot start service caddy: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/var/www/public\") set in config.json failed: no such file or directory"
ERROR: Encountered errors while bringing up the project.
##### What seems to be going wrong?
I want to point to another folder than public folder because I have another structure.
When I have an empty public folder in my directory everything works fine, but when I delete it caddy throws an error on start up.

_____

##### What should be happening instead?
I changed all necessary paths in caddy (Caddyfile and Dockerfile) and it works with the other folders as long as the empty public folder exists. 

_____

##### How might we be able to reproduce the error?
point the root folder not to /var/www/public but /var/www/foobar
delete the public folder
start caddy container
_____

Is there another package that caddy is using that is pointing to the public folder that I have to change?

**Comment by amadeann** [comment]
I was getting the same error. Your question, however, is also a solution in itself, at least in me case.
My project is on Laravel, and there is a 'public' directory in Laravel project anyway. So I just have to set up a project, before starting the caddy container. I also changed:

`root /var/www/public`
to
`root /var/www/laravel/public `

in Caddyfile (the project name is 'laravel')

and 
`APPLICATION=../`
to
`APPLICATION=../laravel`

in .env (copied from env-example)

Is your project not Laravel that this wouldn't work for you as well?

**Comment by cre8** [comment]
I found out that you have to rebuild the project. For normal changing at the caddy file it's not necessary, but a rebuild for caddy removed the error.
