### ISSUE TITLE
Time is off in the workspace container, and it's not the timezone

### ISSUE THREAD

**Issue by Dartanjan** [laradock/laradock#979]
### Info:
- Docker version: 17.03.1-ce, build c6d412e
- Laradock commit: not sure how to get this
- System info (Mac, PC, Linux): OSX 10.11.6

##### What seems to be going wrong?
Time in the workspace container shows as `Wed May 24 10:10:23 CEST 2017`, while local time outside of container is: `Fri May 26 08:18:44 CEST 2017`. So the timezone is correct, but date, hour and minutes are completely off.
_____

##### What should be happening instead?
The dates should be correct :)
_____

##### How might we be able to reproduce the error?
Just compare the two. Inside the `docker-compose.yml` I've changed the TZ argument to `TZ=Europe/Berlin`, rebuilt the container and all that. I'm not sure whether the issue existed before I changed the timezone.

This issue prevents me from using AWS SQS service, as I'm getting `Signature expired: 20170524T073504Z is now earlier than 20170526T052830Z (20170526T054330Z - 15 min.)` which usually means that the time isn't in sync. I tried installing `ntp` inside the workspace container, but had no luck running it.

Thanks for taking a look.

**Comment by bestlong** [comment]
Hi @Dartanjan 

try AWS SDK correctClockSkew property
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property

or

https://github.com/arunvelsriram/docker-time-sync-agent/

**Comment by Dartanjan** [comment]
Thanks @bestlong, I fixed it with `docker-time-sync-agent`.

**Comment by Dartanjan** [comment]
Perhaps a note in the docs somewhere could be useful, if this happens regularly (for Docker on Mac at least).
