### ISSUE TITLE
Add Apache support

### ISSUE THREAD

**Issue by vv3d0x** [LaraDock/laradock#98]
It would be grate to have apache support, and you can switch run site on apache or nginx

**Comment by Mahmoudz** [comment]
@vv3d0x I see no point for using Apache over Nginx personally!!! But it's cool feature to have.

**Comment by vv3d0x** [comment]
@Mahmoudz I meant using Apache instead of Nginx, so you can choose which server will handing requests. Apache - Nginx (Proxy) setup is not clear in local case

**Comment by Mahmoudz** [comment]
@vv3d0x Yes I understand you, I'm just saying why would you use Apache when Nginx exist?! Can you tell me from your experience why you prefer Apache or what is your use case?

**Comment by vv3d0x** [comment]
@Mahmoudz Because you can developing application for a long time with Apache and you can not switch to another. I am new with Docker, your idea amazing, maybe I will try to integrate Apache self, when I will have a time

**Comment by pabloleone** [comment]
I totally agree with @vv3d0x , I already use apache for my projects and most important I'm confident using it, I've never used ngix. I know is good and probably better than apache, but I didn't have the time to play with nor even implement on my projects, so this is a major feature as the majority of people is using apache as far as I know. I won't switch to docker till this is implemented.
Also, the majority of shared servers, and I'm pretty sure about this, are using apache. If we're using shared hosts like goDaddy, sometimes is nearly impossible to say to the provider to switch to ngix because is better, so you should stick to apache or migrate, which not too many people or companies can afford.

**Comment by mikeerickson** [comment]
@vv3d0x I am trying to get apache2 configured to work with laradock and am having mild success.  I have laradock configured to with multiple projects and have created the associated `.conf` file (see below).  However, when I serve up the site, the "root" goes to a listing of files.   If I append the directory where the laravel app is located, then into public folder, the site is served.

![image](https://cloud.githubusercontent.com/assets/183153/24825602/4bae1aac-1bd6-11e7-8c13-c65db2ce542f.png)

Do you have any additional information on what it takes to properly configure the .conf file?  If you have a sample file you could share which works, I would greatly appreciate it.

Here is what I currently have for one of the sites.  what is actually served by default is two directories up

```
<VirtualHost *:80>
  ServerName l54-sotg
  DocumentRoot /var/www/l54-sotg/public/
  Options Indexes FollowSymLinks

  <Directory "/var/www/l54-sotg/public/">
    AllowOverride All
    <IfVersion < 2.4>
      Allow from all
    </IfVersion>
    <IfVersion >= 2.4>
      Require all granted
    </IfVersion>
  </Directory>

</VirtualHost>
```

@Mahmoudz As soon as I can get this working, I will take the necessary steps to update the documentation as per our conversation earlier this afternoon.

**Comment by mikeerickson** [comment]
@vv3d0x @Mahmoudz I have some success...

I found that if I modify the `default.apache.conf` file as follows, I am able to hit this specific site

```
<VirtualHost *:80>
  ServerName l54-sotg.dock
  DocumentRoot /var/www/l54-sotg/public
  Options Indexes FollowSymLinks

  <Directory "/var/www/l54-sotg/public">
    AllowOverride All
    <IfVersion < 2.4>
      Allow from all
    </IfVersion>
    <IfVersion >= 2.4>
      Require all granted
    </IfVersion>
  </Directory>

</VirtualHost>
```

Now, I just need to figure out how to support multiple projects?   Suggestions?

**Comment by mikeerickson** [comment]
S U C C E S S ! ! !

I now understand how it works... I am up and running with all 4 separate apps :-)

@vv3d0x @Mahmoudz My apologies for the noise

**Comment by delmicio** [comment]
@mikeerickson please contribute with your solution
