### ISSUE TITLE
[Feature Request]: Add laravel-echo-server package

### ISSUE THREAD

**Issue by cre8** [laradock/laradock#982]
Since realtime applications become more popular the websocket protocol is getting more important.

Laravel has a great implementation with broadcasting and the package `laravel-echo-server`  would it make possible to use websockets with socket.io at the client. So you are independent from external services like pusher.

I found a docker image for that https://github.com/tlaverdure/laravel-echo-server and wanted to ask if it's possible to integrate this into the laradock. I am new to docker so I am not able yet to build a perfect image and pull it by myself. But I think someone with the knowledge can do it in under an hour :)

**Comment by Mahmoudz** [comment]
closed by #983
