### ISSUE TITLE
Want to know how the Windows system loads this .env variable into the runtime environment.

### ISSUE THREAD

**Issue by parkshinhye** [laradock/laradock#987]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): f296a39bf5b6a449dc833d36a36c880aa95169d1
- System info : windows 10
- System info disto/version: 

##### What seems to be going wrong?

I have copied the .env file.
Want to know how the Windows system loads this .env variable into the runtime environment.

  I found windows running docker-compose up -d nginx mysql. 80,443,3306 port does not throw, that is .env has not been loaded! The The

Hope to be able to solve, thank you! The The

_____

##### What should be happening instead?

_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
// place code here
```

**Comment by gr-jialeiwang** [comment]
you need under laradock folder and run docker-compose up -d nginx mysql
```
$ pwd
/laradock
$ ls
DOCUMENTATION		aerospike		certbot			hhvm			mailhog			mssql			percona			postgres		selenium
LICENSE			apache2			docker-compose.yml	jenkins			mariadb			mysql			pgadmin			postgres-postgis	squid
README-zh.md		beanstalkd		elasticsearch		kibana			memcached		nbproject		php-fpm			rabbitmq		travis-build.sh
README.md		beanstalkd-console	env-example		laravel-echo-server	minio			neo4j			php-worker		redis			varnish
adminer			caddy			haproxy			logs			mongo			nginx			phpmyadmin		rethinkdb		workspace
$ 
```
be sure you have .env under this folder and 
then you can run docker-compose up -d nginx mysql
