### ISSUE TITLE
PHP-FPM container timezone not in sync with defined TZ 

### ISSUE THREAD

**Issue by od3n** [laradock/laradock#989]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): bf4a5beb0be77eb952a5012c27f7e538f950c274
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 16.04.2 LTS

##### What seems to be going wrong?
Timezone for PHP-FPM container
_____

##### What should be happening instead?
Same timezone as defined in TZ build argument in the Docker Compose file

**Comment by ardziej** [comment]
It is true. Timezone is set only for workspace container.

`
#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
`

Should be added for example to mysql/Dockerfile to set timezone in right way.

**Comment by xcaptain** [comment]
I also encountered this problem and solved by manually adding `ARG TZ=UTC ENV TZ ${TZ} RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone` to `php-fpm/Dockerfile-{VERSION}` and then edit `php-fpm/php{VERSION}.ini` to set local timezone.

I think all containers share the same timezone config would be a good idea.

**Comment by andreladocruz** [comment]
after building the machines today, the container (php-fpm and workspace) time is totally different from my computer time. does anyone knows the container ntp server??

**Comment by mathiasonea** [comment]
Hey guys, this issue cost me a few hours today.. it is already possible to set a Workspace Timezone vie the .env file

How about we rename that .env variable to TIMEZONE and apply it to at least mysql, php-fpm and workspace ? It would probably save many people many hours of troubleshooting when the (local) server time is critical to the application they are building.

**Comment by Emalton** [comment]
This would be great if this was added!
