### ISSUE TITLE
Is it possible to install npm packages from dockerfile

### ISSUE THREAD

**Issue by zysoo** [LaraDock/laradock#99]
Some npm packages are used in my project, so I wish to install them in the workspace Dockerfile and make a rebuild. However I tried to add
`RUN npm install`
I shows error of  package.json file not found. But I can install packages in the workspace container.
Please help.

**Comment by Belphemur** [comment]
It's normal. The volume is only mounted when running the container not when building the image.

In other words, the container *application* has a folder **/var/www/laravel** and docker-compose is mounting your project on your host machine directly there when running the *application* container.

You would need to push your package.json in the application container before running the npm install.

**Comment by fanly** [comment]
But, I have something wrong with when I run 'npm install' in the application container or workspace container:
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/laravel/npm-debug.log

**Comment by appleboy** [comment]
@fanly Please try this PR https://github.com/LaraDock/laradock/pull/111 in `workspace` container.
