### ISSUE TITLE
Host mysql connection Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by ihd2911** [laradock/laradock#990]
Docker version 17.03.1-ce, build c6d412e
OS: Ubuntu

I am trying to connect to host mysql from the docker container.  but i am getting this error.

Error: connect ECONNREFUSED 0.0.0.0:3306

I am getting same for mysql if i use mysql container.

I get this issue only on ubuntu. On windows i use tooblox which give ip 192.168.99.100 and its works

**Comment by canxml** [comment]
I got the same issue on macOS 10.12
Can't login via Phpmyadmin but it's work on Sequel Pro.

**Comment by ihd2911** [comment]
`version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www/html

    apache2:
      build:
        context: ./apache2
      volumes_from:
        - applications
      volumes:
        - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
        - ./apache2/sites:/etc/apache2/sites-available
      ports:
        - "${APACHE_HOST_HTTP_PORT}:80"
        - "${APACHE_HOST_HTTPS_PORT}:443"
      networks:
        - frontend
        - backend

    node:
      build:
        context: ./node
      volumes_from:
        - applications
      ports:
        - "4000:30001"
      networks:
        - frontend
        - backend    

### MongoDB Container #######################################

    mongo:
      build: ./mongo
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - ${DATA_SAVE_PATH}/mongo:/data/db
      networks:
        - backend

    rabbitmq:
      build: ./rabbitmq
      ports:
        - "${RABBITMQ_NODE_HOST_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
      privileged: true
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        - php-fpm
      networks:
        - backend

        ### MySQL Container #########################################

    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes_from:
        - applications  
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      expose:
        - "3306"
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend


### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"
  mongo:
    driver: "local"
  node:
    driver: "local"
  apache2:
    driver: "local"
`

This is my docker-compose.yml file
