### ISSUE TITLE
Since My Old Account guide was Delete For Digital Ocean , This is The Updated One!

### ISSUE THREAD

**Issue by g0ld3lux** [laradock/laradock#998]
My Other Account @midascodebreaker has a guide before here for Digital Ocean
Sadly  the link is Down even in the Laradock Official Documentation

So To Update it...

More Or Less If You Want to Add Some Functionalies to Your Terminal Commands
Using OH MY ZSH , and if you are windows User that wanted to make your Terminal Beautiful

Then You may Copy all my Config and Follow this Guide...

If your None Windows 10, You may have to Remove or Omit Some Vim Config
if you need help or have question just ask me...

Here is My Gist for the Production Set Up of my Docker in Digital OCean
And Some Bonus Config for vim and Ohmy zsh

https://gist.github.com/g0ld3lux/4145d031bccf66404dcdb78e9c30dc11

**Comment by winfried-van-loon** [comment]
Hi there! Great to see you again. Thank you for taking the time to write documentation for Laradock. Would like to append the updated documentation to the docs. 

I do have a question though: There are a lot of uppercase characters in the texts: Would you mind changing them to lowercase to improve the readability?
