### ISSUE TITLE
Can't use mailhog through php mail function

### ISSUE THREAD

**Issue by g4b0** [laradock/laradock#999]
### Info:
- Docker version (`$ docker --version`): 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): 58995966ec0d431c8a4a617194d68d50d3f9d6a1
- System info (Mac, PC, Linux): Linux
- System info disto/version: Debian Jessie

##### What seems to be going wrong?
I'm working on a project that use php mail() to send email and I'm not able to send mail through mailhog.

_____

##### What should be happening instead?
No email is sent, and the following appear in php-fpm logs:

php-fpm_1             | [05-Jun-2017 07:03:11] WARNING: [pool www] child 7 said into stderr: "sh: 1: -t: not found"
php-fpm_1             | 172.21.0.6 -  05/Jun/2017:07:03:11 +0000 "GET /email.php" 200
_____

##### How might we be able to reproduce the error?
Just run the following script

_____

### Relevant Code:
```php
<?php 
    ini_set( 'display_errors', 1 );
    error_reporting( E_ALL );
    $from = "emailtest@YOURDOMAIN";
    $to = "YOUREMAILADDRESS";
    $subject = "PHP Mail Test script";
    $message = "This is a test to check the PHP Mail functionality";
    $headers = "From:" . $from;
    mail($to,$subject,$message, $headers);
    echo "Test email sent";
```

**Comment by devployment** [comment]
Just encountered the same issue. My host machine is Windows 10. A workmate running the same code on a Mac as I do does not have this issue.

**Comment by jasperf** [comment]
Issue I had running the mentioned test above inside the workspace using tinker was `sh: 1: /usr/sbin/sendmail: not found` So it had to work from php-fpm.  Decided to just run the script form the public folder. 

Did set 
```
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

In `.env` and with port open I can check Mailhog at `http://laravel.test:8025/#` but using a simple test script I do not see an email arriving.

**Comment by drizzersilverberg** [comment]
hello, @g4b0 @devployment @jasperf . I have the same `sh: 1: /usr/sbin/sendmail: not found` problem. Do you have resolved this problem? Either using Mailtrap or Mailhog, I still got the issue.

**Comment by bestlong** [comment]
try PHPMailer use SMTP.

**Comment by dboune** [comment]
I needed to have this for a legacy project which I can not change to use a proper mailer.

The following linked thread and comment resolved the issue for me, and I'm now able to use MailDev with the standard php mail() function. With some adaptation it could support whatever reasonable solution is desired.

I did not dig too deeply into the specific configuration, and only followed the author's instruction. It worked. I'm currently unaware of any side effects.

https://github.com/djfarrelly/MailDev/issues/115#issuecomment-216831734

- In `php-fpm/Dockerfile`
```dockerfile
###########################################################################
# SENDMAIL:
###########################################################################
ARG INSTALL_SENDMAIL=false

RUN if [ ${INSTALL_SENDMAIL} = true ]; then \
    apt-get update && apt-get -q -y install ssmtp mailutils \
    && rm -rf /var/lib/apt/lists/* \
    && echo "hostname=localhost.localdomain" > /etc/ssmtp/ssmtp.conf \
    && echo "root=<your-email>" >> /etc/ssmtp/ssmtp.conf \
    && echo "mailhub=maildev" >> /etc/ssmtp/ssmtp.conf \
    && echo "sendmail_path=sendmail -i -t" >> /usr/local/etc/php/conf.d/php-sendmail.ini \
    && echo "localhost localhost.localdomain" >> /etc/hosts \
;fi
```

**Note for anyone attempting this on their own** - You have to follow the existing pattern for `INSTALL_*` variables in `.env` and `docker-compose.yml`, or remove the conditional.

Would be better to abstract the variables.

Apologies for the lack of PR.

**Comment by dboune** [comment]
This should probably not be closed.

**Comment by jasperf** [comment]
Well, perhaps you should make this a PR after all @dboune . And one with variables added for `localdomain`, `<your-email>`. That way this could help others and me in the future.

**Comment by dboune** [comment]
@jasperf I don’t disagree. However I’m no longer using laradock at the moment (though I’d like to be), and unfortunately this reminder comes right as I’m neck deep. If I can come back to it, I will do so.
